### ISSUE TITLE
Set Content-Type header for requests from Consul Go API

### ISSUE THREAD

**Issue by blake** [hashicorp/consul#10011]
#### Feature Description

Consul's Go API does not set the Content-Type header in any of its requests (notably, in PUT and POST requests it makes). Consul itself handles this fine and it works as expected. Some proxies or firewalls will reject HTTP requests that do not have the Content-Type header set. If you have one of these between the client and Consul, the lack of this header will cause requests to fail.

In order to avoid this situation, the API package should set the appropriate Content-Type header when sending requests to the Consul API. [Section 3.5.1](https://tools.ietf.org/html/rfc7231#section-3.1.1.5) from RFC 7231, Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content, suggests that:

> A sender that generates a message containing a payload body SHOULD generate a Content-Type header field in that message unless the intended media type of the enclosed representation is unknown to the sender.

The content-type header is not explicitly required to be sent, but doing so will help address the aforementioned scenario where the request is dropped by an intermediary firewall/proxy.

#### Use Case(s)

This surfaces most prominently when using the official Consul Terraform Provider to configure Consul. It uses the v1.5.2 Go Consul API to perform its API requests and this issue prevents the Terraform runs from completing successfully if you have a firewall or proxy rejecting requests because of the absence of the Content-Type header.

**Comment by mikemorris** [comment]
Fixed in https://github.com/hashicorp/consul/pull/10204#issuecomment-847955418
