### ISSUE TITLE
Transparent proxy doesn't work with service resolver redirect

### ISSUE THREAD

**Issue by tjhiggins** [hashicorp/consul#10053]
#### Overview of the Issue

Tried out the hashicorp/consul:1.10.0-beta1 because we were excited about potentially using the transparent proxy when its released. It seems to work for explicit service upstreams, but doesn't work when refing a service resolver that has a redirect to a service. Switching from mode transparent to direct allows traffic again. 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Install consul with image hashicorp/consul:1.10.0-beta1
1. Create service A
1. Create service resolver B that redirects to A
1. Create service C that refs B as an upstream destination

#### Log Fragments

The following is the envoy sidecar logs for service C

When mode is direct I see the listener added:
```console
[info][upstream] [source/server/lds_api.cc:79] lds: add/update listener 'public_listener:10.1.1.120:21000'
[info][upstream] [source/server/lds_api.cc:79] lds: add/update listener 'B:127.0.0.1:12345'
[info][upstream] [source/server/lds_api.cc:79] lds: add/update listener 'outbound_listener:127.0.0.1:15001'
```

However, when the mode is transparent no listener for B gets added:
```console
[info][upstream] [source/server/lds_api.cc:79] lds: add/update listener 'public_listener:10.1.1.120:21000'
[info][upstream] [source/server/lds_api.cc:79] lds: add/update listener 'outbound_listener:127.0.0.1:15001'
```

Using service A does work when mode is transparent, but we want to use service resolvers:
```console
[info][upstream] [source/server/lds_api.cc:79] lds: add/update listener 'public_listener:10.1.1.120:21000'
[info][upstream] [source/server/lds_api.cc:79] lds: add/update listener 'A:127.0.0.1:12345'
[info][upstream] [source/server/lds_api.cc:79] lds: add/update listener 'outbound_listener:127.0.0.1:15001'
```

**Comment by jsosulska** [comment]
Hi @tjhiggins 

Thanks for reporting this, and welcome to the Consul Repo! The engineering team is looking into this more, and will link the fix to this issue when it is submitted.

Happy coding!

**Comment by tjhiggins** [comment]
@freddygv thank you for fixing! I'll keep any eye out for the next beta release and try again.

**Comment by freddygv** [comment]
@tjhiggins awesome! We should be releasing beta2 shortly. 

The main caveat is mentioned in the PR:

> NOTE: this implementation requires an intention to the redirecting
> virtual service and not just to the final destination. This is how
> we can know that the virtual service is an upstream to watch.
> 
> A later PR will look into traversing discovery chains when computing
> upstreams so that intentions are only required to the discovery chain
> targets.

That chain traversal should be in beta3 in a couple weeks.

**Comment by tjhiggins** [comment]
@freddygv Just tried out beta2. Still having issues using a service resolver as an upstream. It looks like the listener isn't being added even when I add intentions for both the virtual and final destination. Do you see anything wrong with my configuration? Envoy adds the listener for resolver-B when the mode is direct.

```json
{
  "name": "service-C",
  "port": 8080,
  "tags": [],
  "connect": {
    "sidecar_service": {
      "port": 21000,
      "proxy": {
        "mode": "transparent",
        "upstreams": [
          {
            "destination_name": "resolver-B",
            "destination_type": "service",
            "local_bind_port": 12345
          }
        ]
      }
    }
  }
}
```

resolver-B redirects to service-A and I created intentions for:
- service-C -> resolver-B
- service-C -> service-A

**Comment by freddygv** [comment]
@tjhiggins Does service-B have a service registration? Or does it only exist via a service-resolver? and did you update the Helm chart/consul-k8s? 

The idea implemented with transparent proxying is that applications would discover the virtual address of a logical upstream using kube-dns, then traffic to that upstream's virtual IP would be redirected through the proxy and forwarded based on any routing rules configured.

In your case, service-C's Envoy should be configured with an outbound_listener that associates the address of service-B with the upstream cluster and endpoints for service-A. 

If you define an upstream for resolver-B then resolver-B MUST be dialed through that local_bind_port, and that connection is not subject to transparent proxy redirection. The iptables rules will exclude upstream ports defined in the proxy registration.

Let me know if that makes sense.

**Comment by tjhiggins** [comment]
> @tjhiggins Does service-B have a service registration? Or does it only exist via a service-resolver? and did you update the Helm chart/consul-k8s?

It only exists as a service resolver. In direct mode it still registers a listener. I'm using `hashicorp/consul:1.10.0-beta2` for the init container/servers/agents. 
```json
{
    "Kind": "service-resolver",
    "Name": "resolver-B",
    "Redirect": {
        "Service": "service-A"
    }
}
```

> The idea implemented with transparent proxying is that applications would discover the virtual address of a logical upstream using kube-dns, then traffic to that upstream's virtual IP would be redirected through the proxy and forwarded based on any routing rules configured.

I saw that which is great, but I'd still like to use upstreams while having all traffic go through the envoy sidecar. We also deploy to ECS and wouldn't be able to utilize kube-dns. Although its possible we could accomplish something similar using cloud map. 

> In your case, service-C's Envoy should be configured with an outbound_listener that associates the address of service-B with the upstream cluster and endpoints for service-A.

There is no service-B its a service resolver to service A.

> If you define an upstream for resolver-B then resolver-B MUST be dialed through that local_bind_port, and that connection is not subject to transparent proxy redirection. The iptables rules will exclude upstream ports defined in the proxy registration.

This makes it seem like service-resolvers don't work as upstreams when the proxy mode is transparent. We currently use a mix of services and service-resolvers as upstreams for various services. The reason being service resolvers allow us to easily toggle between services without having to update/re-deploy with new environment variables for the address. 

Sorry if this all wasn't clear in the initial issue. Should I re-open?

**Comment by tjhiggins** [comment]
@blake Is there a more prescribed way to toggle between services now without re-deploying? Happy to migrate off service resolvers if there is an alternative.

**Comment by freddygv** [comment]
@tjhiggins I think service-resolver entries make sense for that kind of toggling. 

I'm still not sure what behavior you're expecting from transparent proxying though, let me dig in a bit more:

Do you want to continue to define every upstream explicitly and dial them through the local_bind_port, but have outbound traffic to other ports be blocked?

Since you're not on k8s, how are you configuring the iptables traffic redirection? if you're using the new `consul connect redirect-traffic` command, what arguments are you passing?

**Comment by tjhiggins** [comment]
The reason we want to use a transparent proxy is not so much for kube dns, but to take advantage of all of the traffic going through the envoy sidecar. It'll allow us to have better telemetry and improve security because we can lock down traffic just to ports 21000 and 15001 and let consul intentions do the work inside the cluster.

> Do you want to continue to define every upstream explicitly and dial them through the local_bind_port, but have outbound traffic to other ports be blocked?

Can you elaborate on this? We want to use upstreams in the same way we are currently declaring them for direct traffic, but with the transparent proxy. I'm not sure what it would take from an implementation perspective on your end.

> Since you're not on k8s, how are you configuring the iptables traffic redirection? if you're using the new consul connect redirect-traffic command, what arguments are you passing?

Sorry I'm getting a little off topic. To be clear I'm testing all of this on k8s. We use both k8s and ecs and I want to make sure this feature we eventually be more generic to work on both. However, I can create a separate issue for any issues I run into using the transparent proxy on ECS. Which I have not tried yet.
