### ISSUE TITLE
1.10-beta1 master token bound to global-management policy has no permissions in ui

### ISSUE THREAD

**Issue by optiz0r** [hashicorp/consul#10077]
#### Overview of the Issue

Before upgrading 1.9.4+ent to 1.10.0+ent-beta1, logging into consul ui using master token (as configured in acl.tokens.agent_master, and bound to global-management policy in default namespace) provided full access to consul features.

After installing 1.10.0+ent-beta1, this token has almost no permissions in ui (in fact fewer than the anonymous policy has). Another token obtained via vault secret engine also bound to the global-management policy (in default namespace) still provides full access. All navigation items disappear from the sidebar except Nodes (works) and Tokens (permission denied), and all except default namespace disappear from the dropdown.

Possibly related to #10013 ?

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create token bound to global-management policy
2. Set this token as the `agent_master` token in the consul server configuration files
3. Login to ui with said token
4. Observe no access to view tokens/roles/policies/services/kv/intentions/other namespaces

### Consul info for both Client and Server

```
output from server 'consul info' command here
```

<details>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 4
	services = 4
build:
	prerelease = beta1
	revision = fce24969
	version = 1.10.0+ent
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.x.x.x:8300
	server = true
license:
        omitted
raft:
	applied_index = 2824919
	commit_index = 2824919
	fsm_pending = 0
	last_contact = 0
	last_log_index = 2824919
	last_log_term = 2006
	last_snapshot_index = 2818656
	last_snapshot_term = 2006
	latest_configuration = [{Suffrage:Voter ID:3a85258b-1a61-941b-9b81-5260dec51a80 Address:10.2x.x.x:8300} {Suffrage:Voter ID:43e06df8-2152-00a6-0011-7f78f5b7d62a Address:10.y.y.y:8300} {Suffrage:Voter ID:109380fa-6432-42a0-3262-955ba2225146 Address:10.z.z.z:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2006
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 168
	max_procs = 4
	os = linux
	version = go1.15.8
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 25
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2091
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 228
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

CentOS 7

### Log Fragments

Nothing is logged on the server at standard log level while the master token is being used.

**Comment by freddygv** [comment]
Hi @optiz0r, yes #10013 is related. Tokens created in Consul and stored on servers, like you did in step 1, are not meant to be used as the `agent_master` token. This token should be a user-generated identifier.

Since your UI is using a token stored as the `agent_master` token, the resolved authorizer only contains this policy set: https://www.consul.io/docs/security/acl/acl-system#acl-agent-master-token

The reason why this didn't show up previously is that this token's resolution was exclusively handled in the agent endpoints, and I don't believe the UI uses those.

My recommendation would be to set the `agent_master` token to an identifier not associated with an existing ACL token. This way when you use the token bound to the `global-management` policy it will have full permissions.

**Comment by optiz0r** [comment]
Ok thanks for confirming. This was a user-specified management token which got mapped to the global-management policy during the consul 1.4 acl migration. I will create a separate token to use for our breakglass fallback.
