### ISSUE TITLE
Add enterprise license from environment variable or file

### ISSUE THREAD

**Issue by jasonmccallister** [hashicorp/consul#10084]
#### Feature Description

Nomad 1.1.0 adds the ability to define an enterprise license from an environment variable or file. This makes it a lot easier to manage servers with IaaC with Terraform. It would be awesome if Consul had the same capability.

#### Use Case(s)

https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md#110-unreleased

**Comment by blake** [comment]
Hi @jasonmccallister, we are working on adding this same capability to Consul. You can expect to see it in a future release.

**Comment by blake** [comment]
Hey Jason, this feature now exists Consul Enterprise as of version 1.10.0 https://github.com/hashicorp/consul/blob/main/CHANGELOG.md#1100-june-22-2021.
