### ISSUE TITLE
systemctl start consul not success

### ISSUE THREAD

**Issue by edidada** [hashicorp/consul#10115]
#### Overview of the Issue
centos 7, systemclt start consul

ExecStart=/usr/bin/consul agent -server -bootstrap-expect 1 -ui -bind 10.23.29.39 -config-dir=/etc/consul.d/ -client 0.0.0.0

#### Reproduction Steps

systemclt start consul

### Consul info for both Client and Server

systemclt status consul
error

### Operating system and Environment details
centos 7

**Comment by blake** [comment]
Hi @edidada, could you please provide the error messages you're seeing so that we can better assist in troubleshooting this issue?

**Comment by edidada** [comment]
restart too many times

**Comment by jsosulska** [comment]
Hi @edidada 

Can you please follow the template for submitting bugs or issues? 

Namely, we would like:
- A copy of your Consul config file, with the sensitive bits removed.
- The exact error
- The complete systemD file
- Any relevant logs, including context from log lines around it. Feel free to use gist.github.com to upload this.

When you run this command without systemd controlling the process, what happens?

**Comment by jkirschner-hashicorp** [comment]
Hi @edidada,

Were you able to figure out why this was happening? If not, we may be able to assist in troubleshooting if you can provide the information mentioned by @jsosulska.

**Comment by jkirschner-hashicorp** [comment]
Hi @edidada,

We don't have enough information at this time to take any further action and haven't heard any updates in a while, so I'm closing this for now.

If you are still experiencing this issue, please reopen and provide some of the additional information requested by @jsosulska .

Thanks!
