### ISSUE TITLE
terraform, atlas and consul..

### ISSUE THREAD

**Issue by sirvon** [hashicorp/consul#1011]
I watched this excellent quick [video][1] and did the same, now I have a consul cluster!

But of course, I want more... so I want to add that cluster to atlas and I want to do it in the same magically way. using the terraform automated magic.

So, in the terraform consul/aws module, what/where must I add the atlas flags so that when the cluster
is started its automatically added to atlas.

thanks.
[1]: https://vimeo.com/108755280

**Comment by ryanuber** [comment]
Hey @sirvon Glad to hear you are enjoying the tooling!

It looks like the Terraform module in this repository currently just installs some files using the `file` provisioner. The upstart script and consul config are both uploaded to the instances using this method. What you could do is add an extra `file` provisioner to push a configuration file into `/etc/consul.d/atlas.json`, with contents like this:

```
{
  "atlas_infrastructure": "myorg/myproject",
  "atlas_token": "xxxxxxxxxxxx",
  "atlas_join": true
}
```

With that configuration in place, your cluster should be able to successfully register in Atlas!

**Comment by sirvon** [comment]
This project is sooo sweet.
thanks.
