### ISSUE TITLE
Consul does API Gateway, but that service can make this function alongside Consul?

### ISSUE THREAD

**Issue by alexandref93** [hashicorp/consul#1012]
About [API Gateway](http://microservices.io/patterns/apigateway.html).

How implement a API Gateway with Consul?

**Comment by highlyunavailable** [comment]
I'm sort of doing this at my company - the idea is that we use Consul for service discovery and nginx + [consul-template](https://github.com/hashicorp/consul-template) to generate an nginx config file based off of the service discovery data do the routing/auth upstream of each service.

**Comment by alexandref93** [comment]
Consul-template generate a nginx config based on servicer registered on Consul? How? I don't understand... =s

**Comment by highlyunavailable** [comment]
The purpose of consul template is to make configuration files based on the data in Consul. The documentation for consul-template contains a good example of how to write up a service config - check out the readme for that.

A broad example, using the example from the page you linked where there is a client that talks to an endpoint that exposes Product Info, Recommendation and Review service would end up being something like:

* <n> Servers (or docker containers) run instances of Product Info, Recommendation, and Review services. These get registered at the Consul level using a [Service Registration](https://github.com/hashicorp/consul-template). They can now be queried for either via DNS (e.g. productinfo.service.consul) or via the HTTP API (which is what consul-template uses.)

* A template is created that will result in  upstreams for a nginx [load balancer](http://nginx.com/resources/admin-guide/load-balancer/). Your [consul-template file](https://github.com/hashicorp/consul-template/blob/master/README.md#examples) would then define replacers that query the service information in consul to populate the `upstream` section of each section. Paths are also mapped in the nginx template file to point `/productinfo/*`, `/recommendation/*` and `/review/*` to their respective upstreams.

* The nginx load balancer is exposed to the client and requests routed through it are then routed to each service.

**Comment by ray-** [comment]
@highlyunavailable this is very clever. A couple of questions.

1. How do you determine the endpoint names like `/recomendation/`? Are those the consul service names?
2. What if some services are private? Do you tag the specific ones you want to expose as "public" in the consul service registration?

**Comment by ray-** [comment]
This also looks interesting: http://getkong.org/

**Comment by highlyunavailable** [comment]
@ray- The endpoint names are mapped to whatever you want in the nginx config file. You could make a mapping like:

```
upstream recsvc
{
      server IP_ADDRESS; # this is where consul template is really useful
      server OTHER_IP; # this is where consul template is really useful
}

location /recommendation/
{
      proxy_pass https:/recsvc
}
```
or whatever. It's totally up to you what you map them to.

For private services you would need to bind them to a different listener or add authentication.

Re: Kong: what you'd be building is basically portions of that thing.

**Comment by cwinters** [comment]
FWIW this recent presentation from DockerCon has some broad strokes about using nginx + consul + consul-template: https://www.youtube.com/watch?v=6uucWLPcAPY

**Comment by huyifanstar** [comment]
Container internal port and external port is not the same, how to do it better

**Comment by jstoja** [comment]
@slackpad I think this can be closed
