### ISSUE TITLE
Mismatching encryption key error message

### ISSUE THREAD

**Issue by kolis** [hashicorp/consul#1013]
It would be helpful to get a more descriptive error message when joining a cluster with the wrong encryption key. Right now this is the output I get from my agent as it fails to connect

```
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
==> EOF
```

Something simple like

```
Invalid encryption key
```

would be very helpful

**Comment by ryanuber** [comment]
Agreed, thanks!

**Comment by johntdyer** [comment]
+1

**Comment by MansM** [comment]
+2 (hours ... the time I lost because of this)
Also add a message when you dont enter the encryption key at all

**Comment by Mehonoshin** [comment]
+1 faced the same issue
more detailed message would be great!

**Comment by DjinnS** [comment]
+1

**Comment by awwithro** [comment]
+1

**Comment by logie17** [comment]
👍

**Comment by petercunha** [comment]
+1, its ridiculous that there isn't a more coherent error message for this. So many people have lost so much time from the ominous "EOF" error. Fix this in the next release, **PLEASE**.
