### ISSUE TITLE
Does Consul support polling git for KV data?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/consul#10143]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Maybe Consul already offers this feature, but historically this was accomplished via a third party git2consul service.

https://github.com/breser/git2consul

In fact, this service has not seen new commits since 2017, not even security updates. There are some attempts to revive the project, however I do not know if one of the forks is any more authoritative than the other forks:

https://medium.com/devops-dudes/git2consul-alternatives-key-value-filesystem-syncing-for-consul-dede928704f7

If Consul can offer similar KV data loading from git, then there would be no need for a third party tool. And we would benefit from the rigor that HashiCorp applies to their products.

#### Use Case(s)

KV data is presently difficult to organize, automate, review, and audit. Compared to simply tracking this data in a conventional version control system repository. This is because git and other version control systems provide excellent capabilities for managing complex configurations in an automated, peer-reviewed way suitable for enterprise systems.

In a large organization, it can be next to impossible to track down where server changes come from. You end up guessing, waiting for a response from department heads, and sifting through wrong answers. The human condition. In contrast, with KV data sourced from git, you can invoke the git-blame command to directly identify when a configuration change was made and who authored the change. There are many ways to track KV data, but version control maintains a particularly transparent view of the timeline of changes.

**Comment by blake** [comment]
Hi @mcandre, Consul does not natively offer the ability to load KV data from Git. There are a few third-party tools listed on https://www.consul.io/docs/download-tools which provide this capability and are actively maintained. Perhaps one of those would work for your use case.

FYI, the author of #9837 found success in using https://github.com/miniclip/gonsul. It might be worth a look.
