### ISSUE TITLE
Stop prompting to register for webinars

### ISSUE THREAD

**Issue by mcandre** [hashicorp/consul#10142]
The Consul website is difficult to use given the excessive marketing material. I can't read the documentation without being pestered to register for webinars. I can't stand webinars, they are the slowest possible form of education.

I just want to use Consul, I am already a customer. There's not even a button to permanently close and hide the ads.

At the very least, remove these ads from the documentation portal.

**Comment by david-yu** [comment]
Hi @mcandre thank your for the feedback and sorry for the poor experience on Consul.io as it relates to the banners that show up for for marketing events. We have sent this feedback over to the web development team to see how we could remediate this and perhaps make this collapsible, which I was also surprised to find out that it was not.

**Comment by david-yu** [comment]
Closing as per feedback, this banner is now disabled on consul.io.
