### ISSUE TITLE
Incompatibility issue with Consul 1.10 beta and Nomad 

### ISSUE THREAD

**Issue by arushi315** [hashicorp/consul#10147]
Hi team, 

We are currently exploring feature [9554](https://github.com/hashicorp/consul/pull/9554) added in consul 1.10.0-beta1. 
We upgraded our consul as well as envoy to a compatible version and while deploying ingress service using nomad job we are running into an issue.
This is the error that we see:
`[2021-04-28 20:44:14.244][1][critical][main] [source/server/server.cc:109] error initializing configuration '/secrets/envoy_bootstrap.json': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(tracing.http) config: Cannot find field.) has unknown fields
[2021-04-28 20:44:14.244][1][info][main] [source/server/server.cc:782] exiting
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(tracing.http) config: Cannot find field.) has unknown fields`

We suspect that there is a compatibility issue with consul and nomad. 
Here is our proxy default json:

`{
  "Kind": "proxy-defaults",
  "Name": "global",
  "Config": {
    "envoy_dogstatsd_url": "$METRICS_SINK_URL",

    {# using 172.26.64.1 as the address. It is the default gateway for nomad bridged network. https://www.nomadproject.io/docs/configuration/client#bridge_network_subnet #}
    "envoy_extra_static_clusters_json": "{\"connect_timeout\":\"3.000s\",\"dns_lookup_family\":\"V4_ONLY\",\"lb_policy\":\"ROUND_ROBIN\",\"load_assignment\":{\"cluster_name\":\"zipkin\",\"endpoints\":[{\"lb_endpoints\":[{\"endpoint\":{\"address\":{\"socket_address\":{\"address\":\"172.26.64.1\",\"port_value\":29999,\"protocol\":\"TCP\"}}}}]}]},\"name\":\"zipkin\",\"type\":\"STRICT_DNS\"}",

    {# the trace endpoint (by default) is provided through wavefront proxy #}
    "envoy_tracing_json": "{\"http\":{\"name\":\"envoy.zipkin\",\"config\":{\"collector_cluster\":\"zipkin\",\"collector_endpoint\":\"/tracing-endpoint/api/v1/spans\"}}}"
  }
}`

**Versions**
Consul: 1.10.1-beta1
Envoy: 1.17.0
Nomad: 1.0.4 

Please let us know if there is anything else you require to further look into this and thank you for your assistance.

**Comment by rboyer** [comment]
Does it work if you use this instead for `envoy_tracing_json`?

```
{
  "http": {
    "name": "envoy.tracers.zipkin",
    "typedConfig": {
      "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
      "collector_cluster": "zipkin",
      "collector_endpoint_version": "HTTP_JSON",
      "collector_endpoint": "/tracing-endpoint/api/v1/spans",
      "shared_span_context": false
    }
  }
}
```

vs what you had:
```
{
  "http": {
    "name": "envoy.zipkin",
    "config": {
      "collector_cluster": "zipkin",
      "collector_endpoint": "/tracing-endpoint/api/v1/spans"
    }
  }
}
```

Before 1.10 GA there are several additional upgrade guide callouts that will be written soon. Relevant to this thread is a note pertaining to the upgrade of our support of xDS from using the v2 (deprecated) variant and switching to the v3 variant. One of them is that all extension points using `config` fields have been switched to `typedConfig` fields that require including a `@type` key to assist in decoding the protobuf `*any.Any` structure.

**Comment by idrennanvmware** [comment]
Thanks @rboyer  - we are testing this now - as well as with backwards compatibility with consul 1.9.2 (not the timeout but the above envoy config change)

**Comment by arushi315** [comment]
Hi @rboyer, 
I tried the suggest configuration and I am still getting the error with ingress service: 
`[2021-04-30 22:57:31.979][1][critical][main] [source/server/server.cc:109] error initializing configuration '/secrets/envoy_bootstrap.json': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[0].filters[0]) config: Cannot find field.) has unknown fields
[2021-04-30 22:57:31.979][1][info][main] [source/server/server.cc:782] exiting
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[0].filters[0]) config: Cannot find field.) has unknown fields`

When I move back to 1.9.2, this configuration works and service is healthy. 

Let me know if there is any other detail that you would like me to share. Thank you.

**Comment by rboyer** [comment]
Your static cluster json is also still using xDS v2 syntax for the `config` key (needs to be `typedConfig` with an inner `@type` parameter) and is still referring to the http connection manager and http router filters by their older deprecated names:

```
{
  "v3_snippet": {
    "filter_chains": [
      {
        "filters": [
          {
            /* filter is using the non-deprecated name */
            "name": "envoy.filters.network.http_connection_manager",
            /* "config" key is removed; only "typedConfig" + "@type" is supported */
            "typedConfig": {
              "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
              "http_filters": [
                {
                  /* filter is using the non-deprecated name */
                  "name": "envoy.filters.http.router"
                }
              ]
            }
          }
        ]
      }
    ]
  },
  "v2_snippet_unsupported": {
    "filter_chains": [
      {
        "filters": [
          {
            "name": "envoy.http_connection_manager",
            "config": {
              "http_filters": [
                {
                  "name": "envoy.router"
                }
              ]
            }
          }
        ]
      }
    ]
  }
}
```


This is an [example](https://github.com/hashicorp/consul/blob/master/agent/xds/testdata/listeners/connect-proxy-with-http-chain.envoy-1-18-x.golden#L18) of a v3 listener you can consult for reference.

**Comment by arushi315** [comment]
Thank you @rboyer. Let me update the job and give this a try. I will share the result soon.

**Comment by arushi315** [comment]
Hi @rboyer, thank you so much for guiding us to correct our configuration. 
After the suggested changes, ingress service is up and running. 

The original part that I am exploring is [9554](https://github.com/hashicorp/consul/pull/9554), where we would like to increase the request timeout but I am still receiving 504 Gateway Timeout - "upstream request timeout" after 15seconds when I access my service via ingress. 
Snippet from my service: 
` connect {
sidecar_service {
           proxy {
            config {
              local_request_timeout_ms = 360000
            }
          }
        }
      }`
      
Also tried adding timeout in route configuration in ingress job: 
 "route": {
       "cluster": "local_app",
       "timeout": "0s"
      }
 
 No luck so far, we are still troubleshooting this but sharing it here as well for any insight/suggestion. 
 
 Thank you again!

**Comment by arushi315** [comment]
Hi @rboyer, 
I was able to achieve the desired result with the changes in [9554](https://github.com/hashicorp/consul/pull/9554 ). 
Thank you for your help and looking forward to 1.10 GA.
