### ISSUE TITLE
kv import doc ahead of released version

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/consul#10172]
#### Overview of the Issue

As of this writing, the current consul docs for [`kv import`](https://www.consul.io/commands/kv/import) describe a `-prefix` argument that is not available in the current consul release 1.9.5. It looks like this is planned for the 1.10 series.

I know there are nearly 800 open issues and this falls somewhere below the lowest priority. Filing the issue anyway because it's confusing and less than ideal use of time to RTFM, go try something the docs say can be done - then head scratching, digging, goose chasing, then figure out the docs are wrong.

Maybe a little note near an upcoming feature in the docs that says "new in 1.10+" - just some way that makes it clear <this> doesn't work yet. I went to the consul code to figure it out because I can more or less read Golang, but that's a bit much for most users IMHO.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Run `consul kv import -prefix=foo/bar < some_file.json`
1. Get error `flag provided but not defined: -prefix`

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

version 1.9.5

</details>

### Operating system and Environment details

CLI client on macOS

**Comment by dnephin** [comment]
Thank you for reporting the problem. That enhancement was merged in PR #9792. Normally docs should not get published until the release is out. We released a beta version of 1.10. It may be that we accidentally published the docs ahead of time as part of the beta release.

**Comment by blake** [comment]
Hi @rjhornsby, thanks for bringing this to our attention. I've updated the docs to state that the prefix option was recently added as of Consul 1.10. Hopefully this helps avoid confusion in future.

**Comment by rjhornsby** [comment]
Thanks guys. Sometimes things fall through the cracks, and sometimes things are meant to be in the cracks until they’re ready. It happens. 

Appreciate your willingness to attend to what might seem like trivial details despite how busy I’m sure you are. So much of what we do is many little things accumulating over time, hardly noticed, forming into something not so little — either a big, sloppy, frustrating mess or a solid product that feels well designed and productive.
