### ISSUE TITLE
is it compulsory to have that IP Address in SAN for own generated certificates

### ISSUE THREAD

**Issue by vijayalp** [hashicorp/consul#10247]
we created our certificate without IP Address in the SAN
when we are making https request it fails with that error

Overview:

Consul TLS with own ssl certificates generated without ipaddress in SAN fails with error x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

**Comment by jsosulska** [comment]
Hello @vijayalp ,

I see this is a duplicate of #10235. I will be closing this in favor of the answer there.

**Comment by vijayalp** [comment]
Thank you Jono.
Ok to close this ticket.

Best Regards,
Vijaya

[amdocs-2017-brand-mark-rgb]
