### ISSUE TITLE
How to restrict the registered IP in the specified overlay network segment

### ISSUE THREAD

**Issue by herryFight** [hashicorp/consul#10264]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
How to restrict the registered IP in the specified docker overlay network segment

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. docker create network mynet xxx.xxx.xxx.xxx/16
2. The dockersarm is used to deploy consul with mynet
3. Register to consul
4.Get registered IP from consul 
5. the ip not in mynet xxx.xxx.xxx.xxx/16

**Comment by blake** [comment]
Hi @herryFight, the service IP can be specified when registering the service to Consul by setting the [`Address`](https://www.consul.io/api-docs/agent/service#address) field in the service registration. If not specified, it defaults to the IP address of the node on which it is running.

Can you provide a bit more info on how you are registering these services to Consul? Have you tried explicitly setting this address to the desired value?

**Comment by jkirschner-hashicorp** [comment]
Hi @herryFight,

Just checking in again, any updates on this?

**Comment by jkirschner-hashicorp** [comment]
We don't have enough information at this time to take any further action and haven't heard any updates in a few months, so I'm closing this for now.

If you are still experiencing this issue, please reopen and provide some of the additional information requested by @blake.

Thanks!
