### ISSUE TITLE
ctalogervicescom.ecwid.consul.transport.TransportException: ong.apece.ittp.com.comectrimeotException

### ISSUE THREAD

**Issue by jayzc1234** [hashicorp/consul#10319]
i don't know if it's a bug. i just want to know why it's act that .once  a online machine cpu up to 100% cause the service report a exception :
  "-Ebre watcting Cosol (ctalogervicescom.ecwid.consul.transport.TransportException: ong.apece.ittp.com.comectrimeotException: Comect to aget:150 [agent/"ip"】 feilet: comect tied ort
at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstnactHttpIranspont.java:77)"
 
   i use the ip word instead the true ip address. after the exception reporting ,the service never reconnect to consul  and the exception continuing reporting .
   i am wondering  why the service cannot connect to consul again?

**Comment by jsosulska** [comment]
Hello @jayzc1234 ,

I am sorry to hear that you're dealing with issues on your host machine. This question may be better suited for our [Discuss Forums](https://discuss.hashicorp.com/c/consul/29), where others can potentially help you more. 

If you are able to provide replication steps, or more contextual information, can you please open a new issue that follows the template? There is currently not enough information to say that there is anything related to Consul going on. Can you provide application or debug logs? What is the state of the Consul agent on the host? Why did the CPU max out, and how long did it remain there? What happened afterwards?

From what I can see - Whatever Java application you have trying to communicate with Consul could be the issue. That error code doesn't indicate that the response from Consul was a failure.

Best,
