### ISSUE TITLE
Treat 100.64.0.0/10 as a private subnet

### ISSUE THREAD

**Issue by alamut** [hashicorp/consul#1031]
According to RFC 6598 http://tools.ietf.org/html/rfc6598 there's also a 4th subnet 100.64.0.0/10, which may be used by Service Providers as a private network.

Technically, we're using that subnet within AWS EC2 (in purpose of not intersecting with RFC 1918's addresses), and at first I was quite surprised seeing the Consul's message like "Hey, this is not a private IP, I wont start with this".

I know, the RFC says it is intended to use for NAT purposes, but since it's definitely not a public subnet, we can treat it as a private one.

**Comment by highlyunavailable** [comment]
We're running into this on Azure too.

**Comment by ryanuber** [comment]
Thanks for reporting this, fixed in #1050!
