### ISSUE TITLE
docs: Note the Grafana dashboard

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#10327]
Since last year we've had an "official" Grafana dashboard which lives in the source tree and we [publish publicly](https://grafana.com/grafana/dashboards/13396).

But many users including internal teams aren't aware it exists.

We should update the Telemetry page to note it's existence!

**Comment by jsosulska** [comment]
Add a new paragraph near the tutorial reference on the [telemetry](https://www.consul.io/docs/agent/telemetry) page pointing to the dashboard and any install helpers.

**Comment by anihm136** [comment]
Hi! I'd like to work on this. It's my first time contributing to this project, so I'd appreciate some pointers. I've identified the page to make changes on, and I generally understand what is required here. What kind of content would be needed?

**Comment by banks** [comment]
Thanks @anihm136 <https://github.com/anihm136> for contributing!

Jared, everything you've said sounds great to me, thanks!
