### ISSUE TITLE
Connect must be enabled in order to use this endpoint

### ISSUE THREAD

**Issue by rola0411** [hashicorp/consul#10350]
deployed with docker 。

![consul-error](https://user-images.githubusercontent.com/46880610/120749243-ce00d900-c536-11eb-92aa-92f04558e167.jpg)

console：
 [ERROR] agent.http: Request error: method=GET url=/v1/connect/intentions?dc=consul-center from=172.16.15.200:55158 error="Connect must be enabled in order to use this endpoint"

**Comment by rboyer** [comment]
Consul Connect is not enabled by default. You would need to set this on the server nodes in the config file:
```
connect {
  enabled = true
}
```
see: https://www.consul.io/docs/agent/options#connect_enabled

**Comment by jsosulska** [comment]
Hi @rola0411 
Thanks for your question. Questions like this are better suited for our [Discuss Forums](https://discuss.hashicorp.com/c/consul/29) This looks to be answered by @rboyer , as you do not have Consul's Connect features enabled. I hope this helps.

In the event that you have found a bug in this endpoint, even with Connect enabled, please create a new issue that provides the reproduction steps, your Consul config, and expected functionality.

I will close this issue in the meantime. Happy Coding!
