### ISSUE TITLE
What user do health checks run as?

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/consul#1036]
Reading the Consul documentation on health checks, I am left wondering what user the health checks are run as. This would probably be useful to include in the docs themselves, but I also would just like to know. Thank you!

**Comment by ryanbreen** [comment]
I'm not sure there's a universal answer to this. Checks run as the same user as Consul, so it's really an OS-specific and deployment-specific thing.

**Comment by ryanuber** [comment]
I think the answer @ryanbreen gave probably *is* the universal answer, at least currently. Consul uses a simple fork/exec mechanism to run script-based health checks, so the child process is spawned as the same user who started Consul. We could add something to this effect in the health checks documentation.

**Comment by siddharthist** [comment]
Thank you for your quick response! That still might be useful to include in the docs, would you like me to submit a pull request?

**Comment by ryanuber** [comment]
@siddharthist yeah, please do!

**Comment by ryanbreen** [comment]
Sure!
