### ISSUE TITLE
Topology visualization stopped working in 1.9.1 for downstreams and upstreams

### ISSUE THREAD

**Issue by svobol13** [hashicorp/consul#10362]
#### Overview of the Issue

Stats in topology view stopped working after upgrade to 1.9.1 from 1.9.0.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Setup consul with metrics. You might follow https://learn.hashicorp.com/tutorials/consul/kubernetes-layer7-observability?utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS
1. You should see metrics on all upstreams and downstreams.
1. Update file `consul-values.yaml` and configure `global.image` to value `consul:1.9.1` and follow first step again.
1.  You will not see metrics stats on upstreams nor downstreams but only on selected service. It is not correct.
1. When debugging the UI `this.args.item` is `undefined` in this place https://github.com/hashicorp/consul/blob/v1.9.1/ui/packages/consul-ui/app/components/topology-metrics/stats/index.js#L20 . It was correctly defined in 1.9.0 version.

![image](https://user-images.githubusercontent.com/5737461/121092403-c74ebc00-c7eb-11eb-9d08-68cef7f46e61.png)

**Comment by sojki** [comment]
This issue (thanks @svobol13) is reason, why we stopped the upgrade to 1.9.1 :(

**Comment by kaxcode** [comment]
@svobol13 Thank you for reporting this. We've backported the fix to v1.9.x in PR [#10535](https://github.com/hashicorp/consul/pull/10535). I hope you can upgrade to 1.9.1 with no further issues. 

cc @sojki
