### ISSUE TITLE
Connect: CDS update makes all service sidecars return only 503

### ISSUE THREAD

**Issue by maxramqvist** [hashicorp/consul#10379]
#### Overview of the Issue

We have services that are Connect-enabled and deployed with Nomad (job provided below). 
The services are connected to upstreams through intentions and are accessed through the service mesh.
On a CDS update the sidecar will start responding with ONLY 503 "no healthy upstream" for the upstreams.

We have 4  jobs with the almost same config that experience this error at _different_ times.
All 4 jobs have the same upstream. The upstream itself is alive and whenever this happens - it only affects one of the jobs - even though the upstream is the same.

To clarify - any time this happens, it happens to both instances/sidecars of the job at the same time - but no other jobs connecting to the same upstream.

When the jobs have been running for a while we see this log message from Envoy, at the same time from both sidecars:

```
[1][info][upstream] [source/common/upstream/cds_api_helper.cc:28] cds: add 2 cluster(s), remove 0 cluster(s)
```

Right after that the containers sidecar proxy (Envoy) starts responding with only a 503 and "no healthy upstream" for the upstream requests.

Looking at this Grafana screenshot its pretty clear that we go from steady traffic to zero successful traffic and 503 (5xx)-response codes. It gets resolved on a restart/redeploy of the services about 15 minutes later.
![image](https://user-images.githubusercontent.com/12249718/121702194-f1e19300-cad1-11eb-9ac1-f693db36e22a.png)

It seems to match this issue in Envoy:
https://github.com/envoyproxy/envoy/issues/11498

Our services are configured with "http" as the mesh-protocol. We are trying TCP with 2/4 jobs to see if we still hit the issue.

The issue seems to start occuring within 3 days of starting the job.

#### Reproduction Steps

Not sure what triggers the issue.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 3
	checks = 56
	services = 42
build:
	prerelease = beta4
	revision = 477a6c73
	version = 1.10.0
consul:
	acl = enabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 1342
	max_procs = 4
	os = linux
	version = go1.16.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 68
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 51906
	members = 32
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 4
	services = 4
build:
	prerelease = beta4
	revision = 477a6c73
	version = 1.10.0
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 3
	leader = false
	leader_addr = 10.30.0.201:8300
	server = true
raft:
	applied_index = 8868882
	commit_index = 8868882
	fsm_pending = 0
	last_contact = 28.896572ms
	last_log_index = 8868882
	last_log_term = 9099
	last_snapshot_index = 8862611
	last_snapshot_term = 9099
	latest_configuration = [{Suffrage:Voter ID:849ab75f-2371-f504-3689-8443661ae78c Address:10.30.0.201:8300} {Suffrage:Voter ID:49c24e2d-e561-7e00-fa55-39e0b272d530 Address:10.30.0.200:8300} {Suffrage:Voter ID:29bb8d7e-0926-9cf2-cf0d-9d8e38941f83 Address:10.30.0.202:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 9099
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 634
	max_procs = 1
	os = linux
	version = go1.16.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 68
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 51906
	members = 32
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 3
	intent_queue = 0
	left = 0
	member_time = 2162
	members = 9
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Nomad job</summary>
```
{
  "ID": "academy-web@se",
  "Name": "academy-web@se",
  "Type": "service",
  "Datacenters": [
    "prod-az1"
  ],
  "Meta": {
    "timestamp": "1623419681",
    "version": "aeab287"
  },
  "Constraints": [
    {
      "LTarget": "${node.class}",
      "RTarget": "build",
      "Operand": "!="
    }
  ],
  "Update": {
    "Stagger": 10000000000,
    "MaxParallel": 2,
    "HealthCheck": "checks",
    "MinHealthyTime": 10000000000,
    "HealthyDeadline": 301000000000,
    "AutoRevert": true,
    "AutoPromote": true,
    "Canary": 2
  },
  "TaskGroups": [
    {
      "Name": "academy-web",
      "Count": 2,
      "Networks": [
        {
          "Mode": "bridge",
          "DynamicPorts": [
            {
              "Label": "healthcheck",
              "Value": 0,
              "To": -1,
              "HostNetwork": "default"
            },
            {
              "Label": "envoy-metrics",
              "Value": 0,
              "To": 9102,
              "HostNetwork": "default"
            }
          ]
        }
      ],
      "Services": [
        {
          "Name": "academy-web--se",
          "Port": 3000,
          "PortLabel": "3000",
          "AddressMode": "auto",
          "Tags": [
            "team=cawa",
            "namespace=se",
            "service=academy-web",
            "version=aeab287",
            "awesomejobid=91f39385-f187-4076-a4b4-5dd7b20947c7",
            "external",
            "mesh",
            "prometheus_metrics_path=/metrics",
            "prometheus_metrics_address=${attr.unique.network.ip-address}:${NOMAD_PORT_metrics}",
            "prometheus_metrics=false"
          ],
          "Checks": [
            {
              "Type": "http",
              "Protocol": "http",
              "Port": null,
              "Path": "/api/health",
              "AddressMode": "",
              "Interval": 10000000000,
              "Timeout": 2000000000,
              "CheckRestart": {
                "Limit": 5,
                "Grace": 90000000000,
                "IgnoreWarnings": true
              },
              "PortLabel": "healthcheck",
              "Expose": true
            }
          ],
          "Connect": {
            "Native": false,
            "SidecarService": {
              "Tags": [
                "mesh",
                "ingress",
                "prometheus_metrics_address=${NOMAD_HOST_ADDR_envoy-metrics}",
                "prometheus_metrics_path=/metrics"
              ],
              "Proxy": {
                "ExposeConfig": {
                  "Path": [
                    {
                      "Path": "/api/health",
                      "Protocol": "http",
                      "LocalPathPort": 3000,
                      "ListenerPort": "healthcheck"
                    }
                  ]
                },
                "Upstreams": [
                  {
                    "DestinationName": "academy-api",
                    "LocalBindPort": 13370
                  },
                  {
                    "DestinationName": "assessio-service",
                    "LocalBindPort": 13371
                  }
                ],
                "Config": {
                  "envoy_prometheus_bind_address": "0.0.0.0:9102",
                  "local_request_timeout_ms": 15000
                }
              }
            },
            "SidecarTask": {
              "Config": {
                "labels": [
                  {
                    "environment": "prod",
                    "namespace": "se",
                    "owner": "cawa",
                    "service": "academy-web-connect-proxy"
                  }
                ]
              },
              "Resources": {
                "CPU": 100,
                "MemoryMB": 128
              }
            }
          }
        }
      ],
      "Tasks": [
        {
          "Name": "academy-web",
          "Vault": null,
          "Driver": "docker",
          "Config": {
            "network_mode": null,
            "image": "...redacted",
            "volumes": [
              "/usr/local/share/ca-certificates/:/certs/",
              "local/etc/hosts:/etc/hosts"
            ],
            "logging": [],
            "labels": [
              {
                "image": "...redacted",
                "environment": "prod",
                "image_tag": "aeab287",
                "namespace": "se",
                "owner": "cawa",
                "service": "academy-web"
              }
            ]
          },
          "Services": null,
          "Env": {
            "SERVICE_PORT": "3000",
            "SERVICE_NAME": "academy-web",
            ...redacted
          },
          "Templates": [
            {
              "SourcePath": "",
              "DestPath": "local/etc/hosts",
              "EmbeddedTmpl": "127.0.0.1 localhost\n"
            }
          ],
          "Resources": {
            "CPU": 100,
            "MemoryMB": 256
          },
          "RestartPolicy": {
            "Attempts": 10,
            "Interval": 1800000000000,
            "Delay": 15000000000,
            "Mode": "fail"
          },
          "Artifacts": [],
          "KillTimeout": 15000000000
        }
      ],
      "EphemeralDisk": {
        "SizeMB": 300
      }
    }
  ]
}
```
</details>

### Operating system and Environment details

- Running on Azure
- Consul 1.1.10-beta4, same issue with beta3
- Nomad 1.1.1 (same with 1.1.0)
- Ubuntu 20.04
- Envoy with this image: envoyproxy/envoy:v1.18.3 (same with 1.18.2)

### Log Fragments
Haven't been able to capture meaningful logs from Consul YET - will update when I have them.

Envoy logs just before this is happening:

```
[1][info][upstream] [source/common/upstream/cds_api_helper.cc:28] cds: add 2 cluster(s), remove 0 cluster(s)
```
_Edit: Wrong Nomad job template_

**Comment by rboyer** [comment]
Nice find, though it's always a bummer when this sort of thing is found by someone out in the world vs internally.

The current working theory is that Clusters and Endpoints are more related in Envoy machinery than the xDS protocol documentation seems to imply (at least every time I've re-read it). Specifically, until today I was unaware of this fun issue: https://github.com/envoyproxy/envoy/issues/13009

Consul 1.10 switches the xDS protocol from the state-of-the-world xDS variant to the incremental xDS variant. This does differential version comparison of individual named resources between Consul and Envoy and only exchanges delta operations over xDS, in lieu of just transmitting every resource in a type when any resource changes.

The engine for this comparison follows the documented logic for the order to perform high level Cluster/Endpoint/Listener/Route update/delete operations to _avoid_ 503 errors.

But, beyond this safety guaranteeing ordering there is no other interaction between the engine passes for the 4 primary resource types. The [issue](https://github.com/envoyproxy/envoy/issues/13009) clearly shows that actually when a Cluster is updated the corresponding Endpoint is implicitly deleted and needs to be updated in the same pass. Likely the same needs to happen for Listener changes implying Route changes.

**Comment by maxramqvist** [comment]
Thanks for the quick response!

I don't know enough about the Connect data plane or Envoy itself to comment - but please let me know if I can assist with either trying the new code or gathering more info.. logs, envoy metrics or anything else. Reading the docs for the Envoy metrics it looks like some of the upstream metrics should indicate the issue as well.

We really like 1.10 and would like to keep running it. ;)
Btw switching to TCP protocol seem to have mitigated the issue. I can't be sure yet though, it could be that we just haven't hit the bug yet.

**Comment by rboyer** [comment]
Both the `master` branch and the `release/1.10.x` branch (where 1.10.x releases are cut from) have been patched for the underlying issue and will go out in the next beta/rc/GA release of 1.10.x
