### ISSUE TITLE
failed to write NodeID to disk: open /consul/data/node-id: permission denied

### ISSUE THREAD

**Issue by cleveritcz** [hashicorp/consul#10403]
#### Overview of the Issue

Consul won't attach pvc from OpenEBS

#### Steps to reproduce this issue

> apiVersion: v1
> kind: PersistentVolumeClaim
> metadata:
>   name: data-default-consul-server-0
> spec:
>   accessModes:
>     - ReadWriteOnce
>   storageClassName: openebs-lvmpv
>   resources:
>     requests:
>       storage: 3Gi

> config:
> global:
>   name: consul
>   datacenter: dc1
> server:
>   replicas: 1
> ui:
>   enabled: true
>   service:
>     type: 'ClusterIP'
> connectInject:
>   enabled: true
>   default: true
> controller:
>   enabled: true

helm install -f config.yaml consul hashicorp/consul

```
output from client 'consul info' command here
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 10bb6cb3
        version = 1.9.4
consul:
        acl = disabled
        known_servers = 0
        server = false
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 46
        max_procs = 4
        os = linux
        version = go1.15.8
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1

### Operating system and Environment details

Centos 7.9

### Log Fragments

I got error when is mounted:
failed to setup node ID: failed to write NodeID to disk: open /consul/data/node-id: permission denied

I installed OpenEBS lvm with vg so no rights needs to be added.

**Comment by cleveritcz** [comment]
resolved

**Comment by chris-aeviator** [comment]
how?

**Comment by chris-aeviator** [comment]
I've completely & recusively 777'ed the directory and this still pops up and crashes the process  :/

**Comment by dnephin** [comment]
If this is happening in a container (or even if it's not) I suspect the problem is a read-only filesystem. You can check `mount` or otherwise inspect the filesystem to see if it is mounted read-only.

**Comment by davidcsi** [comment]
this is happening to me, too. Any ideas how to solve this?

**Comment by davidcsi** [comment]
@cleveritcz ^^

**Comment by davidcsi** [comment]
ok so i finally figured out the problem.
One needs to add the EBS driver and then add a storage-class.
like
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2 
  fsType: ext4 
```

the trick is this:
```
storageclass.kubernetes.io/is-default-class: "true"
```
because that sets gp2 as default and consul's pods are looking for a specific storage named "default". EKS creates a gp2 storage-class, but doesn't set the default.

**Comment by prashantnitt07** [comment]
permission issue 
chmod -R 777 /mnt/data 
and restart pod

**Comment by prashantnitt07** [comment]
also create pv as 
apiVersion: v1
kind: PersistentVolume
metadata:
    name: data-consul-consul-server-0
    labels:
     type: local
spec:
  storageClassName: local-storage
  capacity:
      storage: 10Gi
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
       namespace: kube-system
       name: data-consul-consul-server-0
  hostPath:
      path: "/mnt/data"

**Comment by prashantnitt07** [comment]
[cloudshell-user@ip-10-6-28-5 ~]$ kubectl get po -n consul
NAME                                          READY   STATUS    RESTARTS      AGE
consul-connect-injector-75bbb95d86-8c2zh      0/1     Running   3 (35s ago)   3m36s
consul-server-0                               1/1     Running   0             24m
consul-server-1                               1/1     Running   0             9m50s
consul-server-2                               1/1     Running   0             9m43s
consul-server-acl-init-5glqf                  0/1     Error     0             94m
consul-server-acl-init-g5bhj                  0/1     Error     0             3h
consul-server-acl-init-jf5jn                  0/1     Error     0             114m
consul-server-acl-init-n6n4f                  0/1     Error     0             3h15m
consul-server-acl-init-s75tr                  0/1     Error     0             148m
consul-server-acl-init-sk54k                  0/1     Error     0             164m
consul-server-acl-init-xcvc6                  0/1     Error     0             132m
consul-webhook-cert-manager-f4988cf75-hrzfm   1/1     Running   0             3h15m
[cloudshell-user@ip-10-6-28-5 ~]$
