### ISSUE TITLE
Consul agent does not respond

### ISSUE THREAD

**Issue by astrekalova** [hashicorp/consul#1043]
I have a problem with the behaviour of a consul agent. The consul agent is listed as alive in the cluster members information, but it does not register a service or respond to queries via HTTP interface. There is an error in the log but I can not interpret it:
```2015/06/16 16:09:42 [INFO] agent: Joining cluster...
2015/06/16 16:09:42 [INFO] agent: (LAN) joining: [10.10.100.226]
2015/06/16 16:09:42 [INFO] agent: (LAN) joined: 1 Err: <nil>
2015/06/16 16:09:42 [INFO] agent: Join completed. Synced with 1 initial agents```

I tried restarting this agent but it returns to the same state. The server seems to have outdated information because it shows the service as healthy although it does not pass the health check.

Here is the configuration of the consul agent that runs on this server:
```{"data_dir":"/opt/consul","datacenter":"dc","log_level":"INFO","node_name":"app01","retry_join":["10.10.100.226"]}```

And the configuration of the server. The cluster has 3 server agents.
```{"client_addr":"0.0.0.0","data_dir":"/opt/consul","datacenter":"ovh-rbx","log_level":"INFO","node_name":"consul-server","server":true,"ui_dir":"/opt/consul/ui"}```

Version of consul is 0.5.0

**Comment by ryanuber** [comment]
This was also asked on the mailing list, so pasting in my response from that avenue:

The log message that you pasted with the error, which says "Err: <nil>", is actually fine. We always dump any error on that step, even if there was none. The message following that one, "Join completed", confirms that the join was successful, so this shouldn't be anything to worry about.

I noticed that you don't have any bootstrap options set in the server configuration. Bootstrapping a Consul cluster is a required step. Did you pass any bootstrap options on the command line during start? You can read about bootstrapping here: https://consul.io/docs/guides/bootstrapping.html, but basically if you don't already, you should just add "bootstrap_expect": 3 to your configuration on the server nodes.

I am not sure I understand the problem with the services. If they are not able to register at all, then I would try solving the above bootstrap issue first as that would definitely be a problem. If the services are registered, providing us the service and health check definitions, along with logs (changing the log_level to debug preferred) would be a big help in diagnosing the problem.

**Comment by astrekalova** [comment]
Thank you for the answer! I changed the configuration on all the servers to use "bootstrap_expect": 3  and now everything works as expected. However, I find the documentation on the website confusing because it says that it is possible to either provide the same bootstrap information for all the servers or not to provide it at all.

**Comment by ryanuber** [comment]
It is possible that a cluster is already bootstrapped before a given server joins in, so we document that it is possible to start Consul without any bootstrap options at all. Prior to Consul 0.4, we had a much more manual bootstrapping process which actually required starting one agent with bootstrap mode enabled, and the others without it, so it's also partly legacy.

If you have any suggestions on how to make that more clear in the docs we would love a PR!
