### ISSUE TITLE
Support ?dc=*

### ISSUE THREAD

**Issue by eirslett** [hashicorp/consul#1044]
By default, consul returns services from within the same data center. You can tweak the query so you ask for services in a different given data center. It would be nice if you could query for services from all data centers!
A couple of use cases for this would be:
1) haproxy configured to load balance across data centers (needed in some cases)
2) databases where the master node is running in another data center, but you don't know which

**Comment by armon** [comment]
This is a bit of a duplicate for #208, closing in favor of that!
