### ISSUE TITLE
consul/api@v1.9.0 uses go1.16-only variable

### ISSUE THREAD

**Issue by knusbaum** [hashicorp/consul#10470]
#### Overview of the Issue

When pulling the latest `consul/api` (`v1.9.0`) I get a build error when using go < 1.16 due to the use of `io.Discard`

#### Reproduction Steps

```
% go version
go version go1.14.15 darwin/amd64
% go get github.com/hashicorp/consul/api@latest
go: github.com/hashicorp/consul/api latest => v1.9.0
# github.com/hashicorp/consul/api
../../../../../../go/pkg/mod/github.com/hashicorp/consul/api@v1.9.0/api.go:1072:17: undefined: io.Discard
```

#### Fix

The [`go.mod`](https://github.com/hashicorp/consul/blob/master/api/go.mod) file says that go1.12 is the minimum version.
To keep `consul/api` compatible with previous versions of Go, it should use `ioutil.Discard` rather than `io.Discard`, which was not introduced until `go1.16`

**Comment by dnephin** [comment]
Thank you for the bug report! 

Note the Go language policy is to only support the [last two Major versions](https://golang.org/doc/devel/release#policy), so similarly we would only support the last two major Go versions for the `api` and `sdk` modules. Code outside of those modules (ex: `command/`) is not intended to be used as a library, and may only support the single version of Go we use to build Consul. However in this case making it support older versions is easy, so not a problem.

The [`go.mod` go directive](https://golang.org/ref/mod#go-mod-file-go) is more about communicating to the Go toolchain how to compule the binary. It's not a statement that the code works with that version of Go. 

We will update our CI to test against the latest 2 Go versions (go1.15, and go1.16 at this time), to prevent similar problems in the future.

**Comment by knusbaum** [comment]
Thanks, @dnephin 

Would you consider releasing a `v1.9.1` patch version of `api`, since `v1.9.0` is broken with `go1.15`, which you say you should support?

**Comment by dnephin** [comment]
Yes, we have tagged v1.9.1 for the api: https://github.com/hashicorp/consul/releases/tag/api%2Fv1.9.1
