### ISSUE TITLE
recursors could resolve *.consul addresses

### ISSUE THREAD

**Issue by amiorin** [hashicorp/consul#1047]
In our vagrant box we have a consul service (```datacenter=virtualbox```) and we would like to access to consul hostnames in other environments (```datacenter=staging```).

We cannot join the two datacenter, because it doesn't make sense.

It would be useful to have a config option to allow ```recursors``` dns to resolve ```*.consul``` hostnames.

**Comment by amiorin** [comment]
I'm evaluating dnsmasq in front of consul.

**Comment by highlyunavailable** [comment]
What about just changing the [domain](https://www.consul.io/docs/agent/options.html#domain) value on the virtualbox instance to something else? Then Consul on the virtualbox instance shouldn't try to process the names and would pass it to the recursor.

**Comment by ryanuber** [comment]
What @highlyunavailable suggests should work nicely, good idea!

**Comment by amiorin** [comment]
Good tip.
