### ISSUE TITLE
UI bug: In the Services panel, a failing machine-level check does not set the header of the node to orange

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#1049]
This is a very minor problem that confused one of our devs today when using the Consul UI.

Actual behavior: UI looks like this (this is a terminated node, so of course the Serf health check is failing):

![image](https://cloud.githubusercontent.com/assets/6266125/8260917/7c78c00e-167b-11e5-8249-bb9931e5b317.png)

Expected behavior:

The green area next to the instance ID (the i-1e1whatever) bit would be orange as well because a machine-level check is failing, because the service instance will be marked unhealthy due to the machine-level check failing.

**Comment by ryanuber** [comment]
Makes sense to me, marking as an enhancement! /cc @pearkes
