### ISSUE TITLE
Which API call should we make to make a TTL check pass?

### ISSUE THREAD

**Issue by denislins** [hashicorp/consul#1052]
I don't believe the docs show this information. In the page Check Definition (https://www.consul.io/docs/agent/checks.html), it's mentioned a PUT request, but I just can't find it.

The page that displays the health API endpoints also don't have this information. (https://www.consul.io/docs/agent/http/health.html)

Is it on the docs somewhere? If it is, can you please include it on a more fit location?

**Comment by ryanuber** [comment]
Hey @denislins, the endpoints used are `/v1/agent/check/pass/<id>` and `/v1/agent/check/fail/<id>`. They are documented in the HTTP API docs [here](https://consul.io/docs/agent/http/agent.html#agent_check_pass). I also updated the documentation to include these links on the checks page in c8b3e48. Thanks for the suggestion!

**Comment by denislins** [comment]
Awesome, thank you!
