### ISSUE TITLE
ensure replication routines can report what the last error message was

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#10521]
Namely when the acl replication routines fail, they set `LastError` on the [acl replication status endpoint](https://www.consul.io/api-docs/acl#check-acl-replication). It would be nice to include something like `LastErrorMessage` captured the content of the `error` that caused the `LastError` field to be updated.

Possibly worth also including giving any replication routines their own replication status endpoints if they don't currently have one (like federation states, config entries, etc).

**Comment by bigmikes** [comment]
I'd like to take a look into this.

I might need some pointers later to develop the replication status endpoints for the other replication routines.
