### ISSUE TITLE
connect/ca/roots endpoint do not return the intermediate cert when using vault provider

### ISSUE THREAD

**Issue by dhiaayachi** [hashicorp/consul#10532]
When using a vault provider with consul and starting a new server. the call to `v1/connect/ca/roots` will not return an intermediate cert until half the root cert life time passed.

This happen because in `getIntermediateCAPrimary` we don't store the generated intermediate in raft

**Comment by dnephin** [comment]
Thinking about this more, the issue might not simply be the API missing data. Envoy also won't receive the intermediate cert, which would mean the TLS chain can not be verified and it could lead to services not being able to connect to each other.

**Comment by dnephin** [comment]
#10826 sounds like it might be the same issue

**Comment by dnephin** [comment]
After looking at this more, I think Envoy is fine because it gets the intermediates from the `Sign` leaf API call, not from the response of `/connect/ca/roots`, but this is still a problem for anyone using the API.
