### ISSUE TITLE
add a field to the /v1/discovery-chain/:service endpoint to indicate it is the default

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#10533]
Today if the discovery chain endpoint was generated off of no `service-router`, `service-splitter`, or `service-resolver` config entry it looks like this:

```
{
  "Chain": {
    "ServiceName": "blah",
    "Namespace": "default",
    "Datacenter": "dc1",
    "Protocol": "tcp",
    "StartNode": "resolver:blah.default.dc1",
    "Nodes": {
      "resolver:blah.default.dc1": {
        "Type": "resolver",
        "Name": "blah.default.dc1",
        "Resolver": {
          "ConnectTimeout": "5s",
          "Default": true,
          "Target": "blah.default.dc1"
        }
      }
    },
    "Targets": {
      "blah.default.dc1": {
        "ID": "blah.default.dc1",
        "Service": "blah",
        "Namespace": "default",
        "Datacenter": "dc1",
        "MeshGateway": {},
        "Subset": {},
        "SNI": "blah.default.dc1.internal.a470f28e-0477-3b21-61de-3e5d5801cd24.consul",
        "Name": "blah.default.dc1.internal.a470f28e-0477-3b21-61de-3e5d5801cd24.consul"
      }
    }
  }
}
```

You can infer that no content went into this by checking:
1. is the top node a resolver node?
2. is the `Resolver.Default` field `true`?
3. is the `Resolver.Target` pointing to a target in the `Targets` map that points to the same name/namespace as the requested discovery chain (and with no subset), in the same datacenter.

It would be convenient to populate a top level field like `Default bool` server-side so that consumers who care about the distinction can just read a single field instead of doing some field introspection.

**Comment by supra08** [comment]
@rboyer I would like to take this up

**Comment by markan** [comment]
@supra08 That would be great! 

Happy to coach you through the process. The main thing is to make sure we get test coverage; most likely you'll be updating discovery_chain_endpoint_test.go.

**Comment by bisakhmondal** [comment]
Hey @markan, I have made the required changes. Is it okay if I open a PR?
Thanks : )

**Comment by kisunji** [comment]
Hi again @bisakhmondal! Unfortunately after some discussion with our UI team we concluded that this field will not provide much value so I'll be closing this issue.

**Comment by bisakhmondal** [comment]
Sure, no issues.
Thanks : )
