### ISSUE TITLE
Make Consul FIPS 140-2 compliant

### ISSUE THREAD

**Issue by erandacr** [hashicorp/consul#10530]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Is there any plan to get Consul FIPS 140-2 certified? I saw there was an issue reported and closed about 4 years ago because it wasn't prioritized at that point.
Can I please know the current status of that? 

As I understand main change should be in encryption modules used for Gossip protocol and RPC, please share if there's any estimation of the complexity of the task? 

#### Use Case(s)

Use Consul in FIPS 140-2 required infractures. 

[1]. https://github.com/hashicorp/consul/issues/3039

**Comment by blake** [comment]
HI @erandacr,

Thanks for the feature request.

Would you mind sharin a bit more detail about your use case for Consul, and which areas you would like to see FIPS certified? For example, are you primarily looking to use Consul for service discovery use cases, or service mesh? If service mesh, is it safe to assume that you would also require a FIPS 140-2 compliant (or certified) version of Envoy?

**Comment by erandacr** [comment]
Hi @blake 
thanks for the reply. Our use case is a bit different from service-mesh and service-discovery. We have a cluster of Consul servers as a distributed key-value store and currently we access the data from application nodes through consul http APIs (agents are not installed in application servers) so Envoy is not a blocker for us.

**Comment by blake** [comment]
Thanks for sharing additional info about your use case, @erandacr.

We currently do not have any near term plans to make Consul FIPS 140-2 compliant, but this is something which has been requested by a number of customers and which we may consider supporting in the future.

We'll be sure to provide an update on this issue if this feature is added to our roadmap in the future, and scheduled for a release.

**Comment by JSurf** [comment]
I came across this issue since we are evaluating to use consul on a redhat system with FIPS kernel mode enabled
Wondering if there are things known that actively break with FIPS kernel mode enabled ? Or is just consul not FIPS certified but everything else is expected to work ?

**Comment by david-yu** [comment]
Closing as FIPS 140-2 support is now included as part of Consul Enterprise: https://developer.hashicorp.com/consul/docs/enterprise/fips
