### ISSUE TITLE
Cannot get package using go get

### ISSUE THREAD

**Issue by Chaunceyan** [hashicorp/consul#10547]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

go: extracting github.com/hashicorp/consul v1.10.0
-> unzip /home/chauncey/go/pkg/mod/cache/download/github.com/hashicorp/consul/@v/v1.10.0.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot
go get github.com/hashicorp/consul/connect: unzip /home/chauncey/go/pkg/mod/cache/download/github.com/hashicorp/consul/@v/v1.10.0.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot

#### Reproduction Steps

Steps to reproduce this issue, eg:

run go get -u  github.com/hashicorp/consul/connect 

### Consul info for both Client and Server

N/A

</details>

<details>
  <summary>Server info</summary>

N/A

</details>

### Operating system and Environment details
Linux Ubuntu 20.04

### Log Fragments

go: extracting github.com/hashicorp/consul v1.10.0
-> unzip /home/chauncey/go/pkg/mod/cache/download/github.com/hashicorp/consul/@v/v1.10.0.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot
go get github.com/hashicorp/consul/connect: unzip /home/chauncey/go/pkg/mod/cache/download/github.com/hashicorp/consul/@v/v1.10.0.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot

**Comment by Chaunceyan** [comment]
This seems only happening in the older version of go.

**Comment by mikemorris** [comment]
This appears to be related to https://github.com/golang/go/issues/27299 on older versions of Go and is fixed when using any currently supported more recent version. Please use https://github.com/hashicorp/consul/issues/10548 if you're still seeing issues with `go get` when using a newer version of Go.
