### ISSUE TITLE
go get github.com/hashicorp/consul failed

### ISSUE THREAD

**Issue by zsyu9779** [hashicorp/consul#10548]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

go get github.com/hashicorp/consul failed

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Run `go get github.com/hashicorp/consul`
2. View error

### Operating system and Environment details

MacOS, Arm64

### Log Fragments

handler: GET /github.com/hashicorp/consul/@v/v1.10.0.info [404].

**Comment by mikemorris** [comment]
Is the following the error you were seeing?
```
../go/src/github.com/hashicorp/consul/vendor/github.com/envoyproxy/go-control-plane/envoy/type/http_status.pb.go:11:2: code in directory /Users/mikemorris/go/src/github.com/hashicorp/consul/vendor/github.com/envoyproxy/protoc-gen-validate/validate expects import "github.com/lyft/protoc-gen-validate/validate"
```

**Comment by jkirschner-hashicorp** [comment]
Hi @zsyu9779,

`go get github.com/hashicorp/consul` is not an officially supported approach to install the main consul package (though should work for the `api` package).

Please use one of the approaches listed here: https://www.consul.io/docs/install
