### ISSUE TITLE
Consul support for service instances?

### ISSUE THREAD

**Issue by VaradDeolankar** [hashicorp/consul#1054]
Does Consul return different instances of the same service in a load balanced manner(round-robin) etc.?

Eg: Lets say i have a service named "Test" and we create 3 instances of the same service during service registration. We currently use a serviceManager class that manages the service(Test) instance. This class has a method getService("Test") which returns different instances of the service(in round robin fashion) upon different calls with same service name.

So, Is this possible in Consul?

**Comment by slackpad** [comment]
Hi @VaradDeolankar - Consul does a randomized load balance for DNS if there are multiple healthy nodes with a given service:

> The DNS query system makes use of health check information to prevent routing to unhealthy nodes. When a service query is made, any services failing their health check or failing a node system check will be omitted from the results. To allow for simple load balancing, the set of nodes returned is also randomized each time. These mechanisms make it easy to use DNS along with application-level retries as the foundation for an auto-healing service oriented architecture.

See [DNS Interface](https://www.consul.io/docs/agent/dns.html) for more details.

**Comment by VaradDeolankar** [comment]
And if i am using the HTTP API, then?

**Comment by highlyunavailable** [comment]
If you're using the HTTP API you can't query for a single instance of a service like DNS - by querying the [health endpoint](https://www.consul.io/docs/agent/http/health.html#health_service) (which you'd have to if you want only passing instances), then you will get a list of all available instances and must pick a random or round-robin one yourself.

**Comment by VaradDeolankar** [comment]
Okay. Alright. Thanks a lot. Also my client side API is in java. So just a small question, Does anyone happen to have any suggestions other than the use of dnsjava library?
http://www.xbill.org/

**Comment by slackpad** [comment]
You shouldn't need any special libraries to use the Consul DNS interface, you just need to have DNS queries go through the local Consul agent (and then forward off to somewhere else if necessary). We've got an [example with BIND](https://www.consul.io/docs/guides/forwarding.html) and it's also pretty common to use dnsmasq which has been blogged about. We don't recommend running Consul as root to sit on port 53 directly.

Consul serves each DNS response with a 0 TTL by default, so you'll get load balancing / bad service avoidance every time your app does a lookup - see [DNS Caching](https://www.consul.io/docs/guides/dns-cache.html).
