### ISSUE TITLE
Error WAN federation between 2 GKE clusters

### ISSUE THREAD

**Issue by ayushkr04** [hashicorp/consul#10541]
For reference, I have been following 2 documents: 
a. https://www.hashicorp.com/blog/connecting-kubernetes-clusters-with-hashicorp-consul-wan-federation
b. https://learn.hashicorp.com/tutorials/consul/kubernetes-mesh-gateways

I have created 2 dc's (dc1 and dc2) running on 2 GKE clusters hosted in us-central1 and asia-south1. I am also able to request service information from the WAN connected datacenter and could verify that the 2 dc's are successfully connected as per the output below:

kubectl exec statefulset/consul-server -- consul members -wan
Node                 Address          Status  Type    Build   Protocol  DC   Segment
consul-server-0.dc1  10.72.3.14:8302  alive   server  1.10.0  2         dc1  <all>
consul-server-0.dc2  10.4.4.15:8302   alive   server  1.10.0  2         dc2  <all>
consul-server-1.dc1  10.72.1.7:8302   alive   server  1.10.0  2         dc1  <all>
consul-server-1.dc2  10.4.3.6:8302    alive   server  1.10.0  2         dc2  <all>
consul-server-2.dc1  10.72.4.16:8302  alive   server  1.10.0  2         dc1  <all>
consul-server-2.dc2  10.4.0.13:8302   alive   server  1.10.0  2         dc2  <all>

But when I am trying to retrieve the service from dc2 to dc1, I successfully get the output. But when trying to retrieve the service from dc1 to dc2, I get "Remote DC has no server currently reachable" error.
Please find the output below:

dc2 to dc1:

Command: kubectl exec statefulset/consul-server -- consul catalog services -datacenter dc1

consul
dashboard-sidecar-proxy
mesh-gateway

dc1 to dc2: 

Command: kubectl exec statefulset/consul-server -- consul catalog services -datacenter dc2

Error: 

Error listing services: Unexpected response code: 500 (Remote DC has no server currently reachable)
command terminated with exit code 1

The proxy default (global) in dc1 is synced to True but the proxy defaults in dc2 is synced to False. (Outputs Below)

dc1:

kubectl get proxydefaults global
NAME     SYNCED   LAST SYNCED   AGE
global   True     50m           50m

dc2:

kubectl get proxydefaults global
NAME     SYNCED   LAST SYNCED   AGE
global   False                  11s

Below is the output from consul-server-0 from dc1:

2021-07-01T07:38:59.936Z [ERROR] agent.server.memberlist.wan: memberlist: Failed to send gossip to 10.4.3.6:8302: read tcp 10.72.3.14:52082->10.72.1.6:8443: read: connection reset by peer
2021-07-01T07:38:59.936Z [ERROR] agent.server.memberlist.wan: memberlist: Failed to forward ack: read tcp 10.72.3.14:52086->10.72.1.6:8443: read: connection reset by peer from=10.4.4.15:8302
2021-07-01T07:38:59.992Z [ERROR] agent.server.memberlist.wan: memberlist: Failed to send gossip to 10.4.4.15:8302: read tcp 10.72.3.14:41104->10.72.4.12:8443: read: connection reset by peer
2021-07-01T07:39:03.251Z [ERROR] agent.server.memberlist.wan: memberlist: Failed to send gossip to 10.4.4.15:8302: read tcp 10.72.3.14:52110->10.72.1.6:8443: read: connection reset by peer
2021-07-01T07:39:04.666Z [ERROR] agent.server.rpc: RPC failed to server in DC: server=10.4.0.13:8300 datacenter=dc2 method=Internal.ServiceDump error="rpc error getting client: failed to get conn: read tcp 10.72.3.14:41100->10.72.4.12:8443: read: connection reset by peer"

dc1.yaml:

global:
  name: consul
  datacenter: dc1
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
    createReplicationToken: true
  federation:
    enabled: true
    createFederationSecret: true
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
connectInject:
  enabled: true
meshGateway:
  enabled: true
controller:
  enabled: true

dc2.yaml:

global:
  name: consul
  datacenter: dc2
  tls:
    enabled: true
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey
  acls:
    manageSystemACLs: true
    createReplicationToken: true
    replicationToken:
      secretName: consul-federation
      secretKey: replicationToken
  federation:
    enabled: true
    createFederationSecret: true
  gossipEncryption:
    secretName: consul-federation
    secretKey: gossipEncryptionKey
connectInject:
  enabled: true
meshGateway:
  enabled: true
controller:
  enabled: true
server:
  extraVolumes:
  - type: secret
    name: consul-federation
    items:
      - key: serverConfigJSON
        path: config.json
    load: true

proxydefaults.yaml:

apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  meshGateway:
    mode: local

**Comment by david-yu** [comment]
Hi @ayushkr04 could you provide your Consul Helm and Consul versions you are deploying this on?

**Comment by ayushkr04** [comment]
Hi @david-yu 

I was able to establish communication between both dc's and could discover the services as well.

Now, when I deploy the application, I am not able to verify that communication is routed through the mesh gateways. It throws an error.

**kubectl exec deploy/static-client -c static-client -- curl -sS http://static-server**
curl: (6) Could not resolve host: static-server
command terminated with exit code 6

Ref Doc: https://learn.hashicorp.com/tutorials/consul/kubernetes-mesh-gateways

However, I am able to discover the services from dc1 to dc2 and vice versa.

kubectl exec statefulset/consul-server -- consul catalog services -datacenter dc2
consul
mesh-gateway
static-server
static-server-sidecar-proxy

**Comment by david-yu** [comment]
Hi @ayushkr04 we recently updated that Learn guide based on other feedback since it was not updated to work with Transparent Proxy in 1.10 ([learn guide](https://learn.hashicorp.com/tutorials/consul/kubernetes-mesh-gateways)). I'll go ahead and close for now but please open a new issue in https://github.com/hashicorp/consul-k8s if you still have issues.
