### ISSUE TITLE
Autopilot: PUT to /v1/operator/autopilot/configuration sets unspecified params to zero/false

### ISSUE THREAD

**Issue by watsonian** [hashicorp/consul#10558]
#### Overview of the Issue

If you attempt to update a single field of the autopilot configuration via a PUT to `/v1/operator/autopilot/configuration`, this results in all unspecified fields being set to zero/false rather than the default values.

#### Reproduction Steps

```
$ consul operator autopilot get-config
CleanupDeadServers = true
LastContactThreshold = 200ms
MaxTrailingLogs = 250
MinQuorum = 0
ServerStabilizationTime = 10s
RedundancyZoneTag = ""
DisableUpgradeMigration = false
UpgradeVersionTag = ""

$ curl -XPUT localhost:8500/v1/operator/autopilot/configuration -d '{"DisableUpgradeMigration":true}'
true

$ consul operator autopilot get-config
CleanupDeadServers = false
LastContactThreshold = 0s
MaxTrailingLogs = 0
MinQuorum = 0
ServerStabilizationTime = 0s
RedundancyZoneTag = ""
DisableUpgradeMigration = true
UpgradeVersionTag = ""
```

### Consul info for both Client and Server

This has been tested in fresh 1.6.9, 1.8.10, 1.9.7, and 1.10.0 versions.

**Comment by jkirschner-hashicorp** [comment]
Closed as of e517e744af81c8d1653bb7c9ce5a4a3edb673727
