### ISSUE TITLE
KV Import fails on Windows using Consul version 1.10.0

### ISSUE THREAD

**Issue by DDSGooch** [hashicorp/consul#10583]
Summary
======
Consul KV import fails using version 1.10.0 when running under Windows.

This is  due to the change made to this line:
https://github.com/hashicorp/consul/blob/13bd86527bcba8bc25a6086688c3e02ec04ea7a3/command/kv/imp/kv_import.go#L82

in this pull request: https://github.com/hashicorp/consul/pull/9792/files#diff-4b09e89bd0587b4486d7a8c6e36e86b4dbc1253737775c39e593ab09020ff3c7R82

Unfortunately this means that all keys are imported with backslashes (\\) rather than forward slashes (/), as can be seen below.

Steps to Reproduce
======
With version 1.10.0 of consul:
1. Create import file
```json
[{"key": "prefix/KeyField1/KeyField2", "flags": 0, "value": "QmFja3VwXA==" }]
```
2. Import the file with the command:
`consul kv import @consuldata.json`
which gives the following output
`Imported: prefix\KeyField1\KeyField2`
3. Export the data
`consul kv export`
which gives the following output
```json
[
       {
                "key": "prefix\\KeyField1\\KeyField2",
                "flags": 0,
                "value": "QmFja3VwXA=="
        }
]
```
Expected Behaviour
============
With version 1.9.5 of consul:
1. Create import file
```json
[{"key": "prefix/KeyField1/KeyField2", "flags": 0, "value": "QmFja3VwXA==" }]
```
2. Import the file with the command:
`consul kv import @consuldata.json`
which gives the following output
`Imported: prefix/KeyField1/KeyField2`
3. Export the data
`consul kv export`
which gives the following output
```json
[
        {
                "key": "prefix/KeyField1/KeyField2",
                "flags": 0,
                "value": "QmFja3VwXA=="
        }
]
```

**Comment by dnephin** [comment]
Thank you for reporting this issue and identifying the problem! I think that line you identified needs to change to use `path.Join` instead of `filepath.Join`.
