### ISSUE TITLE
What characters are allowed in service names? 

### ISSUE THREAD

**Issue by siddharthist** [hashicorp/consul#1058]
This is a request for documentation/question. It was recently pointed out to our project that [not all characters are allowed in Consul service names](https://github.com/CiscoCloud/microservices-infrastructure/pull/528). Can you help clarify which ones are? Thanks in advance!

**Comment by ryanuber** [comment]
Hi @siddharthist,

Characters allowed in services as well as tag names can include any alpha-numeric characters as well as dashes. You can use other characters to do registrations, but they won't work with the DNS interface. I've added a small documentation section on the service definitions page to make this more clear in 6290cb9. The Consul agent should also throw a warning in the logs if a non-compliant name is registered.

Let me know if I missed anything!

**Comment by siddharthist** [comment]
@ryanuber That looks awesome. Thank you!
