### ISSUE TITLE
Feature Request: Send Telemetry for events

### ISSUE THREAD

**Issue by nicholascapo** [hashicorp/consul#1059]
As referenced here [1] it would be nice to see some telemetry data on changes for services and nodes.
This would help to indicate a high load on the cluster.

Admittedly I could write a script to wrap `consul watch` and send the stats to statsd, but since the consul servers already have to react to the change, it should be easy to add.

I am willing to add it myself, but I am at a loss as to where this change should be made.

Example statsd names:
`stats.consul.watch.nodes.change`
`stats.consul.watch.services.change`
`stats.consul.watch.service.{name_of_service}.change`

[1] https://groups.google.com/forum/#!topic/consul-tool/RxIs8FTknKM

**Comment by Kosta-Github** [comment]
I am doing something like this with `consul-template` and this `template` which creates a `shell` script that can be executed after each detected configuration change:
```
{{$statsd := service "statsd"}}{{if gt (len $statsd) 0}}
{{$host := (index $statsd 0).NodeAddress}}{{$port := (index $statsd 0).Port}}

echo "[INFO] sending consul service stats to: {{$host}}:{{$port}}"

nc -u -w0 {{$host}} {{$port}} <<-EOF
	consul.send_stats:1|ms

	consul.nodes.count:{{len nodes}}|g

	consul.services.count:{{len services}}|g

	{{range services}}consul.service.{{.Name}}.count:{{$s := service .Name "any"}}{{len $s}}|g
	{{end}}
	{{range services}}consul.service.{{.Name}}.status.passing.count:{{$s := service .Name "passing"}}{{len $s}}|g
	{{end}}
	{{range services}}consul.service.{{.Name}}.status.warning.count:{{$s := service .Name "warning"}}{{len $s}}|g
	{{end}}
	{{range services}}consul.service.{{.Name}}.status.critical.count:{{$s := service .Name "critical"}}{{len $s}}|g
	{{end}}
EOF

{{else}}

echo "[WARN] no statsd service found"

{{end}}
```
The template first retrieves the address and port for the `statsd` server from `consul` (first 2 lines) and then iterates over all currently registered services and does some stats representing the different states (`passing`, `warning`, `critial`) per service.

For sending the stats to the `statsd` service it uses the `nc` command.

**Comment by nicholascapo** [comment]
@Kosta-Github Very nice! But since the consul server already needs to react to the changes, it could easily send the stats, that's what I'm requesting.

**Comment by pearkes** [comment]
Closing this in favor of https://github.com/hashicorp/consul/issues/4431.
