### ISSUE TITLE
Change copy on Tokens page when ACLs disabled

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#10591]
**Old UI or New UI**
New UI

**Describe the problem you're having**

~Should **Tokens** be clickable when ACLs are disabled? I see the other views are greyed out:~

**edit:** after discussion I've updated this ticket to suggest changing the copy on the Tokens page to something that suggests how to enable ACLs.

![image](https://user-images.githubusercontent.com/1034429/125206080-1b5d1e00-e23a-11eb-88a6-4d347106a237.png)

**Comment by johncowen** [comment]
😄 so this is a feature!

> Should Tokens be clickable when ACLs are disabled? I see the other views are greyed out

A decision was made that we wanted to keep that page there as it has links to documentation etc with the thinking that we want to push folks to enable ACLs.

Thanks for submitting the report though, please let us know if you spot anything else 🙏 

Closing for the moment, but feel free to reopen if I didn't quite cover it.

**Comment by lkysow** [comment]
Right now if you read what the Tokens page says it doesn't talk about enabling ACLs. It makes it seem like you don't have permissions.

> You are not authorized
> Error 403
> You must be granted permissions to view this data. Ask your administrator if you think you should have access.

So perhaps this could read something like "ACLs are disabled. To enable them..."

**Comment by johncowen** [comment]
Perfect thanks Luke 🙌 

We have a page for this already that seems not to be showing here, thanks for clarifying!

**Comment by johncowen** [comment]
Thanks Luke, fix in the works ^. I added you as a reviewer in case you had time or wanted to give it a run over, but don't worry if not. Should be in next patch release 🙇
