### ISSUE TITLE
Go can't download certain versions of api module

### ISSUE THREAD

**Issue by eli-darkly** [hashicorp/consul#10597]
#### Overview of the Issue

My project uses the `github.com/hashicorp/consul/api` module. I was previously using ~v1.6.10~ v1.5.0; my `go.mod` contains the line `github.com/hashicorp/consul/api v1.5.0`, and that has been working fine.

Now I want to update to a more recent version. When I change `v1.5.0` to `v1.9.7` in my `go.mod`, and make _no_ other changes, running `go mod download` produces this error:

`go: github.com/hashicorp/consul/api@v1.9.7: reading github.com/hashicorp/consul/api/api/go.mod at revision api/v1.9.7: unknown revision api/v1.9.7`

Trial and error has shown that the same problem happens with versions 1.9.2, 1.9.3, 1.9.4, 1.9.5, and 1.9.6. It does _not_ happen with 1.9.1— that is, if I use `v1.9.1` in my `go.mod`, there's no error. I can also reproduce the error with recent patch versions of other minor versions, for instance `v1.6.10` gets the error.

I don't know how to explain this behavior, given that `v1.9.7` is clearly a valid tag in this repository. I'm also confused by the error output because I can't figure out where it is getting the extra `api/` ("github.com/hashicorp/consul/api/api/go.mod" and "revision api/v1.9.7").

#### Reproduction Steps

1. In an empty directory, create the following `go.mod`:

```
module github.com/hashicorp/module-loading-error

go 1.14

require (
	github.com/hashicorp/consul/api v1.9.1
)
```

2. Create a minimal Go file `main.go`, just so there's a reference to the module:
```go
package main

import "github.com/hashicorp/consul/api"

func main() {
	_ = api.HTTPAddrEnvName
}
```

3. Run `go build`. The build succeeds.

4. Change line 6 of `go.mod` to:

```
	github.com/hashicorp/consul/api v1.9.7
```

5. Rerun `go build`. The build fails with the error described above.

### Operating system and Environment details

Go 1.16.5 (also reproduced with 1.15.13 and 1.14.15)
MacOS 10.15.7 (also reproduced with Debian 10)

**Comment by mikemorris** [comment]
This is a bit confusing, but `consul/api` is versioned and released separately from the main `consul` package - valid tags can be found at https://github.com/hashicorp/consul/tags as e.g. `api/v1.9.1`

**Comment by eli-darkly** [comment]
That's more than a bit confusing! I didn't think Go even supported module tags that don't begin with "v".

**Comment by eli-darkly** [comment]
And as far as I can tell— it doesn't. That is, if I change `v1.9.7` to `api/v1.9.7` in my `go.mod`, I get this:

`go: errors parsing go.mod:`
`./go.mod:6: require github.com/hashicorp/consul/api: version "api/v1.9.7" invalid: version "api/v1.9.7" invalid: disallowed version string`

So I don't understand how we are supposed to consume the module.

**Comment by eli-darkly** [comment]
Correction: I was previously using v1.5.0, not v1.6.10. The latter is another one of the recent patches that doesn't work.

**Comment by eli-darkly** [comment]
Some background, which may not be relevant but you never know: I don't really need any newer API functionality or fixes in this project. My problem is simply that if I import v1.5.0, some vulnerability scanners that are able to see Go module dependency versions inside compiled Go executables (I didn't realize those were even visible in there, but they are) will consider that to be a use of v1.5.0 of Consul itself (that is, the agent) which has known security issues, even though those issues are specific to the agent and not the API client. The lowest patch version that doesn't have those issues appears to be v1.6.10. But that seems to fall into the category of `api` patch releases that happened after this change in tag usage, so I can't figure out how to consume it.

**Comment by rboyer** [comment]
As Mike mentioned above, there is no api version for `1.9.7`. The latest tag for the api submodule is `api/v1.9.1` which corresponds to:
```
require (
	github.com/hashicorp/consul/api v1.9.1
)
```
You can also see available versions of the api submodule here: https://pkg.go.dev/github.com/hashicorp/consul/api?tab=versions`

The versions for the main module (e.g. the agent itself) have absolutely nothing to do with the versions for the submodules `api` and `sdk`. There may be similarly numbered versions that exist in both due to the cadence that each independent module was released, such as `1.9.1` which also exists in the [main module](https://pkg.go.dev/github.com/hashicorp/consul?tab=versions)

**Comment by eli-darkly** [comment]
OK, so then it has just been a coincidence that the versions I was using before, based on what I thought the latest version of the overall repo was, happened to also be valid versions of the `api` module. I'm still confused in that the `api` module does not seem to have its own changelog and I don't see `api` releases mentioned in the main changelog, and they don't have their own entries in the GitHub [releases list](https://github.com/hashicorp/consul/releases) (the tags are just shown with the latest commit message), so it doesn't seem as if the maintainers expect people to know or care about these releases. But at least now the error behavior makes more sense.

However... then I think I still have the same problem I mentioned in my last comment. This vulnerability scanner does not consider the API module versions to be independent of the base module version. If I write 1.9.1, it thinks that that is simply "Consul 1.9.1". I realize that is not exactly Consul's problem, but if there is no workaround, it may be something the maintainers would like to be aware of.

**Comment by eli-darkly** [comment]
Superseded by https://github.com/hashicorp/consul/issues/10674 which describes the remaining problem.
