### ISSUE TITLE
can not build ui target (make ui) on Linux

### ISSUE THREAD

**Issue by zhangguanzhang** [hashicorp/consul#10629]
step:
```
$ git clone https://github.com/hashicorp/consul.git
$ cd consul
$ git checkout v1.8.14
$ export XC_OS=linux XC_ARCH=amd64
$ make static-assets-docker
Building Golang build container
sha256:266a702eeda31911c04861b120285d775694e1b9298817632466ea728dd3c931
==> Building Static Assets
Creating the Go Build Container with image: consul-build-go
Copying the sources from '/root/go/src/github.com/hashicorp/consul/(pkg/web_ui|GNUmakefile)' to /consul/pkg
tar: pkg/web_ui: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Running build in container
fatal: not a git repository (or any of the parent directories): .git
bindata: Failed to stat input path 'pkg/web_ui': lstat pkg/web_ui: no such file or directory
Error: go-bindata:  exit status 1
make: *** [GNUmakefile:309: static-assets] Error 1
make: *** [static-assets-docker] Error 1

```

**Comment by mikemorris** [comment]
`make static-assets-docker` is not meant to be invoked directly, try building the UI with `make ui` instead?

**Comment by zhangguanzhang** [comment]
```
[root@centos7 consul]# export DOCKER_BUILD_QUIET=0
[root@centos7 consul]#  export XC_OS=linux XC_ARCH=amd64
[root@centos7 consul]# make ui
...
==> Building Static Assets
Creating the Go Build Container with image: consul-build-go
Copying the sources from '/root/go/src/github.com/hashicorp/consul/(pkg/web_ui|GNUmakefile)' to /consul/pkg
Running build in container
fatal: not a git repository (or any of the parent directories): .git   <======= error
bindata_assetfs.go
Copying back artifacts

```

**Comment by jkirschner-hashicorp** [comment]
@mikemorris : when building on Ubuntu 20.04 LTS under Windows WSL, I get the same error message as @zhangguanzhang:

```
// I seem to need sudo because of Windows WSL to connect to the Docker daemon socket
$ sudo make ui 

...

==> UI Built with Version: 1.10.0-dev (5a7c39a01), Logo: oss
Building Golang build container
sha256:d36236a1d37aaa314794f22886a2f96bf4362aac80de5c85b6b0ef0408a63140
==> Building Static Assets
Creating the Go Build Container with image: consul-build-go
Copying the sources from '/home/jkirschner/go/src/github.com/hashicorp/consul/(pkg/web_ui|GNUmakefile)' to /consul/pkg
Running build in container
fatal: not a git repository (or any of the parent directories): .git
bindata_assetfs.go
Copying back artifacts
```

**Comment by jkirschner-hashicorp** [comment]
Hi @zhangguanzhang:

**About improving docs**

There may be an opportunity to improve the docs here. When originally you ran...
```
$ git clone https://github.com/hashicorp/consul.git
$ cd consul
$ git checkout v1.8.14
$ export XC_OS=linux XC_ARCH=amd64
$ make static-assets-docker
```

... what were you trying to accomplish? And what led you to using that build target?

**About your last comment**

I get the same build output as you (pasted above). After looking into it, it seems that despite the `fatal: not a git repository` line in the output, the `make ui` build step succeeded for you.

You can verify by looking at the `agent/uiserver/bindata_assetfs.go` file that is generated by that build step. It should include the contents of `pkg/web_ui`.

Can you confirm that the `agent/uiserver/bindata_assetfs.go` was generated?

**Comment by jkirschner-hashicorp** [comment]
Based on #10659, I'm now more confident that the message...
```
fatal: not a git repository (or any of the parent directories): .git
```

...is not affecting the functionality of `make ui`.

**Comment by zhangguanzhang** [comment]
nice catch

**Comment by jkirschner-hashicorp** [comment]
If you're willing to share, what originally led you to run `make static-assets-docker`? This will help us improve the docs for future users!

**Comment by zhangguanzhang** [comment]
> If you're willing to share, what originally led you to run `make static-assets-docker`? This will help us improve the docs for future users!

I just want to build a docker image within a consul bin file.

**Comment by jkirschner-hashicorp** [comment]
Ah, I see - you're trying to build a `consul` binary from source. In the places you expected to find information on how to do that, what did you see?

I think what you're looking for is this: https://www.consul.io/docs/install#compiling-from-source

[Your use of `XC_OS` and `XC_ARCH` is correct](https://github.com/hashicorp/consul/blob/main/build-support/functions/20-build.sh#L264), though I don't see it documented in an easily accessible page (like the [contributor guide](https://github.com/hashicorp/consul/blob/main/.github/CONTRIBUTING.md#building-consul) or the link given above).

**Comment by zhangguanzhang** [comment]
> Ah, I see - you're trying to build a `consul` binary from source. In the places you expected to find information on how to do that, what did you see?
> 
> I think what you're looking for is this: https://www.consul.io/docs/install#compiling-from-source
> 
> [Your use of `XC_OS` and `XC_ARCH` is correct](https://github.com/hashicorp/consul/blob/main/build-support/functions/20-build.sh#L264), though I don't see it documented in an easily accessible page (like the [contributor guide](https://github.com/hashicorp/consul/blob/main/.github/CONTRIBUTING.md#building-consul) or the link given above).

These steps are what I know after reading the makefile and script, there is no relevant documentation

**Comment by jkirschner-hashicorp** [comment]
@zhangguanzhang : just following up, we've updated the documentation in the README and on the [docs website](https://www.consul.io/docs/install#compiling-from-source) to call out how to cross-compile for another system from source. Thanks for your feedback!

![image](https://user-images.githubusercontent.com/85913323/152381832-543950dc-8233-4a38-a0ea-ccb9b7b5ff5b.png)

**Comment by zhangguanzhang** [comment]
Thank you so much for updating the documentation
