### ISSUE TITLE
consul lock command to support parameters

### ISSUE THREAD

**Issue by isamuelson** [hashicorp/consul#1063]
I'm having problems use the `consul lock` command for a child process with arguments, the lock is released immediately and child process dies...

**Comment by slackpad** [comment]
Hi @isamuelson - can you provide more details about your setup and what you are seeing in the logs?

**Comment by babbottscott** [comment]
https://github.com/hashicorp/consul/issues/776 Maybe?

Try enclosing the command in quotes.
```
consul lock mylock 'cat -v filename'
```

A "-v" in the command string outside of quotes will cause consul to print a version banner and exit.

**Comment by slackpad** [comment]
Closing this as we never heard back. Please let us know if you still need help.
