### ISSUE TITLE
[Docker Image support]

### ISSUE THREAD

**Issue by Young200808** [hashicorp/consul#10648]
I run this command in my machine: docker pull consul,  which expect could pull consul latest image from dockerhub, it work before, but seems dockerhub add some restriction as below

Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

May I know apart from dockerhub, any other way I could achieve consul latest image?

**Comment by jkirschner-hashicorp** [comment]
Hi @Young200808 : Docker Hub is the currently the only place we publish Consul images. If you are pulling images from docker faster than is allowed under free usage of docker, you could authenticate and upgrade with docker per that link you shared. Alternatively, you could also pull the latest Consul image (and other images you use frequently) and [publish them to a private/local registry](https://www.docker.com/blog/how-to-use-your-own-registry-2/) which you can pull from without rate limits.
