### ISSUE TITLE
Updated service tags are removed when agent "Synced service"

### ISSUE THREAD

**Issue by sfncook** [hashicorp/consul#1064]
I'm assuming other people have dealt with this, but I couldn't find any solutions by searching and the answers to similar questions seemed to either miss the problem I'm having or implied that what I am seeing is abnormal.  So apologies if this question is answered elsewhere. (Please provide a link if so!)  

I would like to use Consul with Redis and Sentinel.  When the Redis instances start they register themselves with their local Consul agent with no tags.  i.e.:
{
    "service": {
        "id": "redis-holt-overflow.12.1.2.13:6380",
        "name": "redis-pushqueue",
        "port": 6380,
        "address": "12.1.2.13",
        "check": {
            "script":"/bin/check_scripts/check_redis.sh 12.1.2.13  6380",
            "interval": "2s"
        }
    }
}

Then Sentinel uses Consul to discover the Redis instances and registers them with tags that reflect their roles.  i.e. "master" or "slave"  This actually works for several seconds until the Consul agent local to the Redis instances synchronizes the services at that point the tags are removed.

What am I doing wrong?  How have other people addressed this design problem?  Thanks for any help!

**Comment by slackpad** [comment]
Just in case someone finds this and is curious, there was a discussion over email and this script was used to dynamically update the tag configuration:

https://gist.github.com/mfischer-zd/6b5a8e7d4c8a99f066c3

**Comment by phinze** [comment]
Also worth investigating is [redishappy-consul](https://github.com/mdevilliers/redishappy#redishappy-consul).
