### ISSUE TITLE
Service ACL rules: Support both exact and longest-match

### ISSUE THREAD

**Issue by rmt** [hashicorp/consul#1067]
According to my interpretation of the documentation, if ACL A has the rule:

> service "" { policy = "read" }
> service "secure-foo" { policy = "write" }

and ACL B has the rule:

> service "" { policy = "read" }
> service "secure-foobar" { policy = "write" }

Then it would be possible to register the service "secure-foobar" when using ACL A.

It's of course possible to explicitly require an extra suffix to service names by using "secure-foo-" and "secure-foobar-", but I could also imagine having two rules, along the lines of:

> service "secure-foo$" { policy = "write" }
> service "secure-foo-" { policy = "write" }

It would similarly affect the KV store, but is far less likely to affect people because of the path semantics.

**Comment by armon** [comment]
@rmt Agreed, I think we need a suffix or something to indicate a non-greedy match. Marking as enhancement.

**Comment by fengyehong** [comment]
Run into the same problem, hode Consul can support both prefix match and exact match.

**Comment by gaumire** [comment]
I ran into the same problem as well, I am not too sure if it's actually possible. However having some sort of regex/pattern matching on the acl rules would be great.

**Comment by Lasering** [comment]
I would really like a regex/pattern matching rule (for service, nodes and kv). Or alternatively a suffix rule (which for my deploy is far more useful).

**Comment by mkeeler** [comment]
Closing this as the new ACL implementation in v1.4.0-rc1 supports both exact and prefix matching now.
