### ISSUE TITLE
Service should be in Warning state before breaching failures_before_critical

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/consul#10680]
#### Feature Description

Currently if I set `failures_before_critical` to a value higher than `1` the service appears to be healthy even if checks are failing. We can see this in the implementation here:

https://github.com/hashicorp/consul/blob/c6859b3fb07031e3ea1fcd0230bacb070315d93d/agent/checks/check.go#L946-L952

What would make more sense would be either to:

* Update the service state as `Warning`, which will show the new check state in UI.
* Provide a `failures_before_warning` config to configure when it is updated to `Warning`.

#### Use Case(s)

Right now if I have a fleet of 3 hosts that I deploy an update to gradually - one host at a time - and that deployment is faulty, and the relevant service has a value of `failures_before_critical` higher than `1`(lets say it's a test fleet and we don't want to alarm too early), the state of the service will change only once the threshold is breached. This is an issue for 3 reasons:

1. It delays indication of the issue in the UI until threshold is breached.
2. Obscures the scale of impact, since the issue will appear only on one host initially.
3. It hides the current state of the checks on other hosts in the Web UI.

For someone debugging the issue live as they watch the deployment happen it might make them think at first that the issue is specific to just one host, rather than the whole fleet.

A more sensible approach would be to at least mark the service with a failing check as `Warning`, which would:

1. Indicate the issue in the services/nodes views in the Web UI.
2. Update the response from the check in the `Health Checks` view.

#### Options

The simplest possible fix is to just update the service state to be `Warning` on first failure if the `failures_before_critical` is not reached. But that would change the default behavior of all checks for all users.

The more advanced and more customizable solution would involve introducing a new setting called `failures_before_warning` which by default would be set to the same value as `failures_before_critical` so as to preserve the old behavior. If need be anyone could simply set it to a lower value than `failures_before_critical` and gain ability to see the changed state of the service earlier.

**Comment by jakubgs** [comment]
@dnephin hey. I think this functionality would be really cool, and I could attempt to implement it, since it doesn't look that difficult to do, but I'd like to get the idea of what the Consul team thinks about it. I don't want to waste time implementing `failures_before_warning` only to find out that that's not the right way to do it.

If I could get some feedback on which option makes more sense to you and how you'd expect this to be done I could attempt it.

**Comment by jkirschner-hashicorp** [comment]
@jakubgs : thanks for the detailed write-up and offer to make the enhancement! The Consul team will meet to think through the options and their implications early next week, then follow-up with you on our thoughts to ensure your time is well spent.

**Comment by jakubgs** [comment]
Thanks. Yeah, I think option 2 makes much more sense. I'll try to do it.

But now that I think about it I'm not entirely sure how to do the "by default would be set to the same value as `failures_before_critical`" part. If the default value of an unset `failures_before_warning` is `0` is there a way to distinguish between it being unset and being explicitly set to `0` by the user? If I cannot distinguish between those states then the value of `0` would not be possible to set and would have to be reserved for the special setting of "same as `failures_before_critical`".

**Comment by jakubgs** [comment]
One possibility is to modify the `raw` interface to include a special default value for `failures_before_warning`:
https://github.com/hashicorp/consul/blob/ff9700b068f202d41a345a1ad08708770bf360d2/agent/config/config.go#L42

Since the type of `FailuresBeforeWarning` will be `int` and not `uint`, I could do something like:
```go
	var raw map[string]interface{}
        // Special default for detecting unset FailuresBeforeWarning.
        raw["FailuresBeforeWarning"] = -1
```
And then handle that differently in `consul/agent/checks/check.go`. But not sure.

**Comment by jakubgs** [comment]
According to this article you can distinguish between set and unset field in JSON by using a pointer:
https://medium.com/@arpitkh96/differentiate-between-empty-and-not-set-fields-with-json-in-golang-957bb2c5c065

Worth a try.

**Comment by jakubgs** [comment]
Oh, I see, this already is being handled as pointes and converted via `intVal` function:
https://github.com/hashicorp/consul/blob/ff9700b068f202d41a345a1ad08708770bf360d2/agent/config/builder.go#L1902-L1907

**Comment by jakubgs** [comment]
Here's the PR: https://github.com/hashicorp/consul/pull/10701

I'm expecting it will require some attention to get it merge-worthy.

**Comment by jkirschner-hashicorp** [comment]
Thanks @jakubgs - that was fast! We're giving it a read and will get back to you soon over on the PR.

**Comment by jakubgs** [comment]
I will be upgrading my Consul clusters to `1.9.8` tomorrow and try to apply my change to the `release/1.9.8` branch and try it out.

**Comment by jakubgs** [comment]
I have upgraded even further up to `1.10.1` and tried a dev build with my changes from #10701 and it worked flawlessly:
```
[WARN]  agent: Check socket connection failed: check=service-abc error="dial tcp 127.0.0.1:30305: connect: connection refused"
[WARN]  agent: Check is now warning: check=service-abc
[INFO]  agent: Synced check: check=service-abc
```
Looks good. One thing that makes me wonder is if I should also change this log message:
```
[WARN]  agent: Check failed but has not reached failure threshold: check=service-abc status=critical failure_count=1 failure_threshold=5
```
To also include `warning_threshold`.
