### ISSUE TITLE
Secondary Datacenter can't load trusted CA certs after Rotation (Vault CA)

### ISSUE THREAD

**Issue by sgtang** [hashicorp/consul#10682]
#### Overview of the Issue

Hi, we've been using `consul connect ca set-config` to rotate between root CA endpoints within our Vault instance. Currently our secondary datacenter node shows the following error whenever we start a new Envoy Connect proxy on it (after the rotation): `[2021-07-22 19:48:50.767][31869][warning][config] [source/common/config/grpc_subscription_impl.cc:107] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) public_listener:0.0.0.0:21000: Failed to load trusted CA certificates from <inline>` The proxy does not function if the CA certs aren't loaded.

We've tried restarting the Consul agent, the proxy, and the Consul servers in the primary datacenter.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with a primary and secondary datacenter with Connect enabled using Vault as the CA provider
2. Rotate the Root CA on the primary datacenter
3. Attempt to start a service and an Envoy sidecar proxy for that service in the secondary datacenter

### Operating system and Environment details

Ubuntu 18.04, Consul 1.9.6, Envoy 1.16.4

### Log Fragments

`[2021-07-22 19:52:57.686][32091][info][config] [source/server/listener_manager_impl.cc:888] all dependencies initialized. starting workers
[2021-07-22 19:52:57.686][32091][warning][config] [source/common/config/grpc_subscription_impl.cc:107] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) public_listener:0.0.0.0:21000: Failed to load trusted CA certificates from <inline>`

Consul logs from the secondary datacenter indicate no issues with CA replication:

```Jul 22 19:51:11 beef consul[31954]: 2021-07-22T19:51:11.855Z [INFO]  connect.ca.vault: Successfully renewed token for Vault provider
Jul 22 19:51:11 beef consul[31954]: 2021-07-22T19:51:11.855Z [INFO]  connect.ca.vault: Successfully renewed token for Vault provider
Jul 22 19:51:12 beef consul[31954]: 2021-07-22T19:51:12.098Z [INFO]  agent.server.connect: received new intermediate certificate from primary datacenter
Jul 22 19:51:12 beef consul[31954]: 2021-07-22T19:51:12.098Z [INFO]  agent.server.connect: received new intermediate certificate from primary datacenter
Jul 22 19:51:12 beef consul[31954]: 2021-07-22T19:51:12.109Z [INFO]  agent.server.connect: updated root certificates from primary datacenter
Jul 22 19:51:12 beef consul[31954]: 2021-07-22T19:51:12.109Z [INFO]  agent.server.connect: updated root certificates from primary datacenter
Jul 22 19:51:12 beef consul[31954]: 2021-07-22T19:51:12.109Z [INFO]  agent.server.connect: initialized secondary datacenter CA with provider: provider=vault
Jul 22 19:51:12 beef consul[31954]: 2021-07-22T19:51:12.109Z [INFO]  agent.server.connect: initialized secondary datacenter CA with provider: provider=vault
Jul 22 19:51:12 beef consul[31954]: 2021-07-22T19:51:12.138Z [INFO]  agent.server.connect: updated root certificates from primary datacenter
Jul 22 19:51:12 beef consul[31954]: 2021-07-22T19:51:12.138Z [INFO]  agent.server.connect: updated root certificates from primary datacenter
```

**Comment by dnephin** [comment]
Thank you for reporting this issue! I'm wondering if the underlying problem might be #8178, which we just recently fixed and was in the latest patch releases. That issue doesn't provide the error from Consul, but it does give a way to reproduce the problem. If you query the `http://127.0.0.1:8500/v1/agent/connect/ca/leaf/web` endpoint do you see a `CertPEM` field with multiple certificates where one of them is missing a newline between certificates ?

**Comment by sgtang** [comment]
@dnephin Thanks for the quick response, our `CertPem` field is indeed missing missing the trailing newline, and the format matches the one cited in the issue. Will implement one of the patch releases tomorrow and report back if the issue is fixed.

Thanks again.

**Comment by sgtang** [comment]
We upgraded our agents to 1.9.8 today which has resolved the CA rotation issues, we've tested a couple of rotations to new endpoints within Vault and they all went smoothly, existing proxies stayed up and new proxies also came up fine.

Thanks for the help!
