### ISSUE TITLE
Consul agent did not automatically de-register those services that failed service check

### ISSUE THREAD

**Issue by hanct** [hashicorp/consul#10703]
Hi,

I notice that the consul agent (which i start using consul agent -dev -node machine)   did not de-register those services that failed service check. What parameter should i pass to the command line when starting the consul agent, so that it can automatically does the de-register? 

Cos i notice that when there are services that failed the service check, the consul seem to also return the IPs of these failed services to the caller.

Is this a bug?

**Comment by jkirschner-hashicorp** [comment]
Hi @hanct,

When you say that consul is returning the IPs of failed services to the caller, what call are you using specifically (via command line / API / DNS)?

For reference:
- [Services with a failing health check will not be returned by DNS](https://www.consul.io/docs/discovery/services#checks)
- [Services listed via the Health API](https://www.consul.io/api-docs/health#list-nodes-for-service) will include failing services unless the `passing` parameter is `true`

**Comment by hanct** [comment]
Thanks. I think i finally manage to resolve. 
The call is via API.

Just add the below will resolve my issue.
spring.cloud.consul.discovery.health-check-critical-timeout=1m

**Comment by jkirschner-hashicorp** [comment]
I'm glad you were able to get things working!

Was there any part of the documentation that could have been clearer about what was needed?
