### ISSUE TITLE
In the consul Federation scenario, the main cluster is shut down abnormally, and the mesh gateway is abnormal after recovery

### ISSUE THREAD

**Issue by lemonit-eric-mao** [hashicorp/consul#10719]
#### Scene

Federation Between Kubernetes Clusters

Self built k8s, DC1, DC2    `Private cloud`

imageEnvoy: 'envoyproxy/envoy-alpine:v1.18.3'

imageK8S: 'hashicorp/consul-k8s:0.26.0'

image: 'hashicorp/consul:1.10.0'

kubernetes: 1.20.1

CenOS 7.9

helm install -f dc1-values.yaml consul hashicorp/consul -n dhc-consul --version "0.32.1" --wait
helm install -f dc2-values.yaml consul hashicorp/consul -n dhc-consul --version "0.32.1" --wait

---

#### Operation steps

dc1: 
-  master 1
-  worker 3

Execute `init 6` on each `worker` machine

---

![image](https://user-images.githubusercontent.com/68628461/127424058-2ef5aacf-2358-4014-86a8-200b606b0f55.png)

![image](https://user-images.githubusercontent.com/68628461/127424102-3e6df395-62b2-43b1-87f8-81caa38e7555.png)

![image](https://user-images.githubusercontent.com/68628461/127424146-cfc1c4ce-1d37-4416-a42b-93543bebe6af.png)

---

#### mesh-gateway Pod
![image](https://user-images.githubusercontent.com/68628461/127424390-e1451dbd-72a1-406a-804f-9eb33f4832c2.png)

**Comment by blake** [comment]
Hi @lemonit-eric-mao, can you clarify what you mean by the gateway being abnormal after recovery? Is the issue that Kubernetes never re-creates the gateway on worker01?

**Comment by jkirschner-hashicorp** [comment]
Hi @lemonit-eric-mao - just checking in again, are you able to provide any of the info requested above? Without that information, we don't have enough information to take further action.

**Comment by jkirschner-hashicorp** [comment]
Marking closed for now because we don't have enough information to take further action. You are welcome to reopen if you reply with the information requested above. Thanks!
