### ISSUE TITLE
Is it possible to access Consul DNS that has ACL enabled but without prepared queries?

### ISSUE THREAD

**Issue by gregory112** [hashicorp/consul#10723]
#### Feature Description

Currently after troubleshooting I realized that when ACL is enforced, queries to `.service.consul` and others will fail with NXDOMAIN. Turning off ACL then makes Consul DNS works as expected. Unfortunately, after some reading, CMIIW, to access Consul DNS you need to first create a prepared query first using the prepared query API, and then access the service from `.query.consul` domain.

If this is true, does that mean I have to register all services first using API before my other external services can discover those using Consul DNS? Is there a way to just allow Consul DNS to be accessible everywhere but with ACL enabled? Seems to be a chore if I have to create prepared queries everytime, especially knowing that Nomad does not seem to create one for me either.

#### Use Case(s)

Well, there are cases when my DNS is accessible only through local network and I have to use DNS SRV records for service discovery. Even this document gives an example of this: [https://learn.hashicorp.com/tutorials/consul/load-balancing-haproxy](https://learn.hashicorp.com/tutorials/consul/load-balancing-haproxy). If I want to implement something like the document describes, how to do it with ACL enabled? Without having to create/delete prepared queries all the time?

**Comment by jkirschner-hashicorp** [comment]
Hi @gregory112,

DNS queries can work with ACL enabled. It sounds like, in your case, DNS lookups are failing because the agents serving DNS requests lack the necessary privileges (granted by a token). Here's some [guidance on how to set up a token for DNS](https://learn.hashicorp.com/tutorials/consul/access-control-setup-production#token-for-dns).

Out of curiosity, is there documentation or guide(s) you were following to set up ACLs? And do you recall which pages you read that led you to believe accessing Consul DNS would require the use of prepared queries? Perhaps there's an opportunity to make the documentation clearer.

Let me know if this gets things working for you!

**Comment by gregory112** [comment]
@jkirschner-hashicorp 

That is what I thought at first. I thought it would work even with ACL enabled.

I have two Consul nodes, both acting as server (no clients). They have ACL enabled, but when `default_policy` is set to `allow`, DNS query works. But when it's set to `deny`, DNS query to either servers return NXDOMAIN.

I also have Consul to disallow stale requests by setting `dns_config.allow_stale = false`. I have also followed that documentation, and in that part it is said that

> Depending on your use case, the token used for DNS may need policy rules for nodes, services, and prepared queries. You should apply the token to the Consul agent serving DNS requests. When the DNS server makes a request to Consul, it will include the token in the request. Consul can either authorize or revoke the request, depending on the token's privileges.

From what I read, `query_prefix` policy grants the ability to make prepared queries. Also, it is said that
> When the DNS server makes a request to Consul, it will include the token in the request.

What is `it` refers to here? And what does it mean by `DNS server makes a request to Consul` ? I guess that means `Consul client which acts as DNS resolver server makes a request to Consul server`? Either way, I have set up my Consul cluster to have these policies:

```
agent_prefix "" {
  policy = "write"
}
node_prefix "" {
  policy = "write"
}
service_prefix "" {
  policy = "read"
}
# only needed if using prepared queries
query_prefix "" {
  policy = "read"
}
```

I also tried to set all of them to write and get the same result.

> And do you recall which pages you read that led you to believe accessing Consul DNS would require the use of prepared queries?
Well yes, the link that you provided actually. I was confused with reading that part, and by trying and trying I was led to believe that DNS queries are blocked by ACL and so prepared queries have to be used, hence, the availability of `query_prefix` policy.

**Comment by gregory112** [comment]
> Out of curiosity, is there documentation or guide(s) you were following to set up ACLs?

Well turns out, there is. And after rereading this documentation, I realized that I have to set up anonymous token too to allow DNS query. Turns out it is listed in this section, and marked as Optional (perhaps that's why I skipped that part a while ago): [https://learn.hashicorp.com/tutorials/consul/access-control-setup?utm_source=consul.io&utm_medium=docs#configure-the-anonymous-token-optional](https://learn.hashicorp.com/tutorials/consul/access-control-setup?utm_source=consul.io&utm_medium=docs#configure-the-anonymous-token-optional).

> Perhaps there's an opportunity to make the documentation clearer.

Well perhaps this doc: [https://www.consul.io/docs/discovery/dns](https://www.consul.io/docs/discovery/dns), which I regard as "the official manual of Consul DNS". Maybe also add how DNS would work if ACL is enabled in that manual. I didn't expect DNS to be blocked by ACL too. Currently it is scattered in a lot of placed in HashiCorp blogs. Blogs are great, but IMHO they are a bit uncategorized.

**Comment by jkirschner-hashicorp** [comment]
> I created a token from this policy and set the token as Consul agent token in all my Consul nodes. I also tried to set all of them to write and get the same result.

On each agent, you can specify an `agent` token and a `default` token. If a request doesn't specify a token, the `default` token is used if specified; without a `default` token, the `anonymous` token is used. DNS should work with the `default` agent token, even without the `anonymous` token.

When you say you set the "Consul agent token" on all Consul nodes, did you set the `agent` token or the `default` token? (How did you set the token?)

**Comment by jkirschner-hashicorp** [comment]
Thanks for the details on what caused the confusion. I've added the `type/docs` label to this issue as a reminder to revisit the docs based on our conversation!

**Comment by gregory112** [comment]
> When you say you set the "Consul agent token" on all Consul nodes, did you set the agent token or the default token? (How did you set the token?)

I meant agent token. I gave the agent a token that has all permissions set to write. Yes, you were right, I have to use default or anonymous token. I added `node_prefix ""` and `service_prefix ""` both read policies to anonymous token and now DNS works. I bet using default token works the same too.

> Thanks for the details on what caused the confusion. I've added the type/docs label to this issue as a reminder to revisit the docs based on our conversation!

Thank you, so I'll just leave this issue opened then?

**Comment by jkirschner-hashicorp** [comment]
> Thank you, so I'll just leave this issue opened then?

Yes - I'll keep it open for now as a reminder.

Glad you have things working!

**Comment by jkirschner-hashicorp** [comment]
Hi @gregory112,

Based on your feedback, we've added information on using DNS with ACLs to the DNS page:

https://user-images.githubusercontent.com/85913323/132924590-90f27ac0-5031-43b7-a604-b0e4d000cf0f.png

In the future, we also intend to include some policy examples.

Thanks for the feedback that helps us improve our docs!

**Comment by gregory112** [comment]
Thank you very much @jkirschner-hashicorp!
