### ISSUE TITLE
Consul agent does not have permission to /var/lib/consul directory

### ISSUE THREAD

**Issue by NickMRamirez** [hashicorp/consul#10726]
#### Overview of the Issue

When you run the Consul agent (not in server mode) as a Systemd service, you get a permission error.

#### Reproduction Steps

Steps to reproduce this issue, eg:

When you start Consul in "agent" mode using the following **/etc/consul.d/consul.hcl** file:

```
datacenter = "dc1"
server = false
data_dir = "/var/lib/consul/"
bind_addr = "192.168.50.22"
retry_join = ["192.168.50.21"]
enable_syslog = true
log_level = "INFO"
```

Then when the Consul agent starts up as a service: 

```
sudo systemctl enable consul
sudo systemctl start consul
```

It gives the following error:

```
failed to setup node ID: open /var/lib/consul/node-id: permission denied
```

The workaround is to set permissions on the directory:

```
sudo chown -R consul:consul /var/lib/consul
```
### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
$ sudo consul info
agent:
        check_monitors = 0
        check_ttls = 0    
        checks = 0        
        services = 0      
build:
        prerelease =
        revision = db839f18  
        version = 1.10.1     
consul:
        acl = disabled       
        known_servers = 1    
        server = false       
runtime:
        arch = amd64
        cpu_count = 2        
        goroutines = 52      
        max_procs = 2        
        os = linux
        version = go1.16.6   
serf_lan:
        coordinate_resets = 0
        encrypted = false    
        event_queue = 0      
        event_time = 2       
        failed = 0
        health_score = 0     
        intent_queue = 0     
        left = 0
        member_time = 5      
        members = 2
        query_queue = 0      
        query_time = 1 
```

</details>

<details>
  <summary>Server info</summary>

```
$ sudo consul info
Error querying agent: Get "http://127.0.0.1:8500/v1/agent/self": dial tcp 127.0.0.1:8500: connect: connection refused
```

</details>

### Operating system and Environment details

Ubuntu Bionic

```
$ uname -a
Linux consul-server 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jkirschner-hashicorp** [comment]
Hi @NickMRamirez: Did you follow some documentation to set this up using systemd? And did it talk through the creation of `/var/lib/consul` (with the right ownership)?

**Comment by NickMRamirez** [comment]
I can't tell where I got **/var/lib/consul** from. Maybe it had been the default value for `data_dir`? I must have got it from somewhere, but who knows. In any case, looking at the current documentation, and the default **consul.hcl** file, `data_dir` defaults to **/opt/consul**. 

Using **/opt/consul** works without any permission issue, so I will update my HCL file to use that. 

This solves my problem. Thanks!
