### ISSUE TITLE
master acl token - update docs to confirm correct value

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/consul#1072]
Reading through http://consul.io/docs/internals/acl.html and http://consul.io/docs/agent/options.html#acl_master_token a few times, and even after some small bits of testing, I am unsure what a correct value for the master token should be. Is this supposed to be the UUID, the name/label, or something else?

**Comment by slackpad** [comment]
Hi @ketzacoatl - you are right, we should beef up the documentation to make this more clear. I found this thread which gives some info about the format of the token from @armon:

https://groups.google.com/forum/#!topic/consul-tool/lN3jZRbS2-g

> If the `acl_master_token` is not supplied, then the servers do not create a master token. If they did,
there would be no way to programmatically provide it safely. When you provide a value, it can be
any string value. Using a UUID would ensure that it looks the same as the other tokens, but isn’t
strictly necessary.

**Comment by ketzacoatl** [comment]
Thanks for the assistance @slackpad!
