### ISSUE TITLE
Consul code change for implementing a customized feature in consul

### ISSUE THREAD

**Issue by VaradDeolankar** [hashicorp/consul#1073]
I am a newbie in Go programming and I want to modify the file that returns the service discovery information and make it return the data that i want. Obviously, I have to include my module of code within consul's code itself. Since, the code is massive, some help in figuring out where, as in, in which files I could possibly make this code change would be of much help. I really need this custom feature. Thanks in advance.

**Comment by slackpad** [comment]
Hi @VaradDeolankar are you sure you need to modify Consul itself? Could you build a service that wraps calls to Consul's existing APIs or possibly use additional information in Consul's KV store for your application?

**Comment by VaradDeolankar** [comment]
Thanks for the reply. Yes I'm sure. As that is the best solution to my problem.

**Comment by pratikbatua** [comment]
Hi @slackpad ,

To add to what @VaradDeolankar mentioned, 

We are planning to use Consul as an distributed service discovery mechanism within our infrastructure.
To make this happen, we want to modify the way consul responses to service requests. We can write our API/Code that overrides the way consul responds to service discovery requests.

Does consul provide any interface that we can implement to override default behavior?

We simply want to know the place in consul code which we need to modify or where we need to plugin our APIs.

Thanks
Pratik

**Comment by tgwizard** [comment]
Could you perhaps tell a bit more of what you want to do? It might be possible already using standard consul APIs, or other tools. I guess the place in the code you need to modify will depend on what you want to do as well.

**Comment by pratikbatua** [comment]
On the consul's http end point we want to implement service lookups so that service discovery happens in round robin fashion.

User will register for the service, service name : MYService and then different instance ,1 and 2.

When any other client sends a request for MyService We want to return,
MyService:1 or MyService:2 in round robin.

This is just one of the example but in general we want the place in code to override the service lookup behavior the way we want. We can implement our own algorithm for returning the services from the available service instances.

Thanks
Pratik

**Comment by ryanbreen** [comment]
You could still achieve that by wrapping the responses from Consul in another service, as @slackpad says.  There's no need to modify Consul itself to achieve that, and you're signing up for more of a development burden if you try to accomplish this by rolling a custom version of Consul.

**Comment by pratikbatua** [comment]
Creating a load balancer service on top of consul response could be one of the solution but its not ideal for our infrastructure as we have very less number of instances for single service (But have around 3000 services).

The primary reason behind moving to consul was leverage the benefit of widely distributed architecture where single node going out of the network creates minimal impact on the infrastructure.

We can't create dedicated load balancer for each service as it's not logical as per the service/instance #s we have. Creating a global load balancer will become a single point of failure for entire infrastructure of 3000 services. Also the complexity of the architecture will be increased.

The easiest and ideal solution would be modify the consul code to implement custom service discovery logic.

We don't want to drive load balancing from the client end as client doesn't know about other clients, requests and thus can't guarantee consistent behavior. Also for multiple request/response (for single service) synchronization, locking of resources on server is not an ideal solution.

Thanks
Pratik

**Comment by tgwizard** [comment]
We solve this by using consul-template to write an haproxy config for the services we want discoverable. We run this "service-discovery haproxy" on every machine that needs access to other services. All services thus go to the local haproxy, which knows to find the other services. There's no SPoF.

We also have dnsmasq that resolves `*.service` to `127.0.0.1`, for where the haproxy listens. That way we can do `curl http://user.service/users?id=1,2,3,4`, which goes to haproxy, which proxies to some other  node (or the same node), on some other port (or port 80).

**Comment by pratikbatua** [comment]
Our infrastructure is being used by 100 of applications and eventually 1000s machines across multiple data centers. Creating haproxy for each machine is not ideal for us as its virtually impossible more over it increases the complexity.

Having couple of haproxy takes away the benefit of distributed infrastructure and can introduce potential SPoF by haproxy (if all haproy instances are down or busy state or something else.. ) .

The easiest/effective/ideal solution is to add custom code in consul that overrides the service discovery logic. We may within consul can hit the http endpoint retrieve all services and return the selected one as response.

Can you pl. let us know the consul classes involved in service lookup(server side classes)?

thanks
Pratik

**Comment by highlyunavailable** [comment]
Correct me if I'm wrong @pratikbatua, but you say:

> User will register for the service, service name : MYService and then different instance ,1 and 2.
>
> When any other client sends a request for MyService We want to return, MyService:1 or MyService:2 in round robin.

Isn't this the same as just registering multiple instances of the same service on different machines? If so, why can't you use the existing mechanism of DNS returning a random instance of a service every time you query for that service name? E.g. if you have MyService on S1 and MyService on S2, Consul will pick the IP for S1 or S2 randomly every time you make a DNS request. That's the idea of picking a _random_ server rather than using round robin - over a large number of requests, random would average out to the same amount of traffic to each server.

Also, I'm not sure why there is specifically HTTP is mentioned so much here - DNS seems like a much more simple interface to look up a service by, unless you absolutely need the full list of service instances to pick from. Take a look a the [DNS interface documentation](https://www.consul.io/docs/agent/dns.html) - it might be exactly what you need.

**Comment by pratikbatua** [comment]
thank for your response @highlyunavailable .

Yes you are right. We have considered the DNS approach as it best fits our requirement.
Only concern I have is about support and ease available around https vs dns.

We have clients across multiple languages - java/c#/c++/kdb etc.. and may have more clients on other technologies as well.

As http end point is easy to implement and support is available across each language/technology in the market hence we preferred http over dns.

Thanks

**Comment by ryanuber** [comment]
@pratikbatua the languages you mention should have solid support for DNS client functionality, so if possible I would probably take that route. It will end up being much easier to report any issues you bump into if you stick with running the supported code base as well, especially at the scale you are talking about.

That said, there is no single class or interface, or place you can simply drop code in to modify the service discovery globally in Consul. The DNS and HTTP interfaces are a part of the Consul Agent, which is all located in the `command/agent` directory. You will need to dig through that code if you insist on making changes to Consul itself.

I'm going to close this one, but let us know if you need any other help. Thanks!
