### ISSUE TITLE
Consul socket: too many open files

### ISSUE THREAD

**Issue by cloudcafetech** [hashicorp/consul#10734]
Running Consul as POD with HA.

Getting  Vault (1.5.4) GUI error as follows ..

![image](https://user-images.githubusercontent.com/68260844/127595863-38c9f1e9-1e95-4b2b-88a6-01c3b7597142.png)

My host limits details as follows ...

```
[root@ip-172-31-4-11 ~]# ulimit
unlimited
[root@ip-172-31-4-11 ~]# ulimit -Hn
65535
[root@ip-172-31-4-11 ~]# ulimit -Sn
65535
[root@ip-172-31-4-11 ~]# cat /proc/sys/fs/file-max
400229
[root@ip-172-31-4-11 ~]# ulimit -n
65535
```

**Comment by jkirschner-hashicorp** [comment]
Hi @cloudcafetech - let us know if the [troubleshooting steps here for "too many open files"](https://www.consul.io/docs/troubleshoot/common-errors#too-many-open-files) help.

**Comment by cloudcafetech** [comment]
I already followed that docs (please see my initial starting comments) but not able to fix.

Remember I am running as a POD in Kubernetes.

**Comment by jkirschner-hashicorp** [comment]
Hi @cloudcafetech,

The message you're seeing on the Vault UI does not look like an error message that would have been returned from a remote server (the Consul backend). Instead, it looks like an error message generated by Vault in trying to contact the Consul backend store.

The troubleshooting steps I linked are for what to do when encountering that message from Consul. [This performance tuning / troubleshooting information from Vault](https://learn.hashicorp.com/tutorials/vault/performance-tuning?in=vault/operations#max-open-files) might be more suitable in this case.

If that doesn't work, I recommend opening a thread on [Vault's Discuss forum](https://discuss.hashicorp.com/c/vault/30) where other community members may have recommendations.
