### ISSUE TITLE
Ingress' link to docs = 404

### ISSUE THREAD

**Issue by DejfCold** [hashicorp/consul#10748]
**Old UI or New UI**
New UI

**Describe the problem you're having**
When opening Ingress Gateway service on the Upstreams tab, there's the following "warning":
```
Upstreams are services that may receive traffic from this gateway.
If you are not using Consul DNS, please make sure your Host: header uses the correct domain name
for the gateway to correctly proxy to its upstreams.
Learn more about configuring gateways in our documentation.
```
The last word `documentation` is a link to https://www.consul.io/docs/connect/ingress-gateways which doesn't exist on the Consul website.
![image](https://user-images.githubusercontent.com/12591578/127789468-5b693146-d817-4e5b-bc8d-3fcfe43807f6.png)

**Describe the solution you'd like**
Either link to a valid page (probably https://www.consul.io/docs/connect/gateways/ingress-gateway) or (re)create the missing one

**Comment by blake** [comment]
Hi @DejfCold, this link should point to https://www.consul.io/docs/connect/gateways/ingress-gateway. I'll submit a PR later to update this.
