### ISSUE TITLE
Service checks are not shown in lock session summary

### ISSUE THREAD

**Issue by dantheoptimist** [hashicorp/consul#10754]
#### Overview of the Issue

When using service checks on a session to lock a key/value, the service checks are not rendered correctly in the lock session summary.

#### Reproduction Steps

1. Create a session with a service check e.g. `curl -X PUT -d '{"Name": "myservice", "ServiceChecks":[{"ID":"myServiceCheck"}]}' http://localhost:8500/v1/session/create`
1. Lock a value using the session that was created e.g. `curl -X PUT -d '{"Application": "test", "host":"somehost", "port":1234}' http://localhost:8500/v1/kv/example/key?acquire=933fd1dd-83fd-e3be-dab4-f5dfab2e33eb`
1. View the key value in the UI by navigating to Key/Value -> example -> key and see the service check is rendered as a generic object obscuring the check ID.

![image](https://user-images.githubusercontent.com/763170/127872073-4792dd93-2d18-44d6-9e89-454e60278296.png)

### Consul info for both Client and Server

Client and server running 1.10.0

**Comment by dantheoptimist** [comment]
This looks to be due to the UI and tests expecting the response to be formatted as per the incorrect documentation noted in https://github.com/hashicorp/consul/issues/10752. 

It may be sufficient to use the ID field directly when joining on to the list of checks for most use cases, it would also be necessary to update the test data that covers this use case.

**Comment by kaxcode** [comment]
@dantheoptimist  thank you for reporting this. We've updated our API docs and made changes to our UI.
