### ISSUE TITLE
Documentation incorrect for service checks on sessions

### ISSUE THREAD

**Issue by dantheoptimist** [hashicorp/consul#10752]
#### Overview of the Issue

The API documentation at https://www.consul.io/api-docs/session suggest that service checks should be a list of string check ids similar to the other check fields. However, the code actually expects an object with an optional namespace in addition to the ID as per the code: https://github.com/hashicorp/consul/blob/21e855d860865f1472b3fdcb64a916e92bc83a9f/api/session.go#L39

`
type ServiceCheck struct {
	ID        string
	Namespace string
}
`

This looks like it's isolated to the section on parameters for create session as none of the examples on the remaining API calls use service checks but as a further item it may be beneficial to add a complete example.

**Comment by blake** [comment]
Hi @daneharrigan, thanks for bringing this to our attention. I've created PR #10759 to address this discrepancy.
