### ISSUE TITLE
Keys with TTL not working.

### ISSUE THREAD

**Issue by ThomasAlxDmy** [hashicorp/consul#1075]
Hi guys,

From what I read on the web and the commit history Consul supports KV with TTL since 5.0. The way it is supposed to work from my understanding is linking a session with a TTL to one or several keys using the `delete` option. When the Session will timeout the keys will get deleted. 

So I created keys with a session id and pass it to the `Put` Method: https://github.com/hashicorp/consul/blob/master/api/kv.go#L125.

However it uses `put` behind the scene that does not create the keys with session_id... https://github.com/hashicorp/consul/blob/master/api/kv.go#L170

Am I using it in the wrong way or is it just unsupported?

**Comment by highlyunavailable** [comment]
The comment above "Put" explains:
```
// Put is used to write a new value. Only the
// Key, Flags and Value is respected.
```

Normally, you'd use `Acquire` to associate a key with a session ID, but happily you do _not_ need to `Put`, then `Acquire` since `Acquire` will create the key if it does not exist. Replace your call to `Put` with a call to `Acquire` and it should work fine.

**Comment by ThomasAlxDmy** [comment]
@highlyunavailable Sweet that worked great! thanks. Also While I got you here may I ask for a feature request? Can we have a flag on put to write the data to consul regardless if there's a change? (right now it will only update if the value is different.)

**Comment by highlyunavailable** [comment]
I'm unsure what you mean by "write to consul regardless of changes". If you call Acquire, Put or any of the other methods, a request is made to Consul with the data you provide. The existing data is not fetched and diffed in any way. Can you explain what your expected behavior and the actual behavior is?

**Comment by ThomasAlxDmy** [comment]
Sure, So I implemented a system of watcher using blocking queries on a directory to get the list of changes. It happens that when I do a Acquire(since I changed to acquire) on an existing key with the same value (I haven't tried different value) the modified index does not change. However it works if I do delete + acquire.

**Comment by highlyunavailable** [comment]
You know, I think I misled you slightly here. Acquire _should_ return `false` if you try to acquire a key that's already acquired, which is the correct behavior since you've acquired it in the first place with your session.  In other words, your initial "create" operation should use `Acquire` to create the key and set the session all in 1 step, but then any subsequent operations to write data should use `Put`.

**Comment by ThomasAlxDmy** [comment]
What you're saying is I can't use Acquire to modify data? only to create? If I modify the data with a put will the session persists?

**Comment by highlyunavailable** [comment]
No, that's not what I'm saying.

I'm saying Acquire succeeding is conditional on the SessionID being blank. Don't think of Acquire as "Put + attach session", think of it as "Put only if no session is attached to the key at the time of the Acquire call".

Think of it like this:
```
if (kvPair.SessionID == nil) {
    write(data)
    return true
} else {
    return false
}
```

Put is an unconditional write, but doesn't write to SessionID. If you use Put to an already Acquired key, it _will not_ overwrite the session ID.

**Comment by ThomasAlxDmy** [comment]
Sweet that actually make sense. Thank you for all the information!

**Comment by highlyunavailable** [comment]
You're welcome!

**Comment by ryanuber** [comment]
Thanks for fielding this one @highlyunavailable!
