### ISSUE TITLE
External Node Serf Status Shows Failed

### ISSUE THREAD

**Issue by reskin89** [hashicorp/consul#10756]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I have an external node and service being registered with Terraform.  The service check passes via a terminating gateway, however the serf status is in a failing state regardless of configuration, and, as it is an external node, should not have a serf status in need of reporting.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create an external service with a terminating gateway for communication
2. Configure a health check that will pass
3. Deploy terminating gateway and apply service and node configurations via terraform

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>
Client info from terminating gateway (the service itself of course does not have one)

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = f55da930
	version = 1.9.3
consul:
	acl = enabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 80
	max_procs = 2
	os = linux
	version = go1.15.6
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 395
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 68048
	members = 10
	query_queue = 0
	query_time = 8
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 3c1c2267
	version = 1.9.5
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 3
	leader = true
	leader_addr = REDACTED
	server = true
raft:
	applied_index = 2075959
	commit_index = 2075959
	fsm_pending = 0
	last_contact = 0
	last_log_index = 2075959
	last_log_term = 210
	last_snapshot_index = 2064797
	last_snapshot_term = 210
	latest_configuration = REDACTED
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 210
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 262
	max_procs = 2
	os = linux
	version = go1.15.8
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 395
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 68048
	members = 10
	query_queue = 0
	query_time = 8
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 181
	members = 9
	query_queue = 0
	query_time = 2
```

</details>

### Operating system and Environment details
All Running Amazon Linux 2

### Log Fragments

No Relevant Logging Information

### Terraform Node configuration

```
resource "consul_node" "mynode" {
  name       = "mynode-${var.env}-${var.region}"
  address    = aws_route53_record.myr53record.fqdn
  datacenter = var.datacenter
  meta = {
    "external-node"  = "true"
    "external-probe" = "true"
    "region"         = var.datacenter
  }
}
```

**Comment by blake** [comment]
Hi @reskin89, could you provide the external service definition which you are registering into Consul, and the relevant terminating gateway configuration? That information would be helpful in trying to reproduce this issue.

Thank you.

**Comment by reskin89** [comment]
Sure @blake !

Here's the config for the service:

```
resource "consul_service" "myservice" {
  name       = "myservice-${var.env}"
  node       = consul_node.mynode.name
  port       = 443
  datacenter = var.datacenter
  tags       = ["myservice-${var.env}"]

  check {
    check_id                          = format("service:myservice-%s-%s", var.env, var.datacenter)
    name                              = format("myservice-%s-%s health check", var.env, var.datacenter
    status                            = "passing"
    http                              = format("https://%s/ping", aws_route53_record.myrecord.fqdn)
    tls_skip_verify                   = true
    method                            = "GET"
    interval                          = "5s"
    timeout                           = "1s"
    deregister_critical_service_after = "24h"
  }
}
```

The service check continues to pass without issue.


Terminating Gateway config:

```
resource "consul_config_entry" "myterminatinggateway" {
  name = "myservice-terminating-gateway"
  kind = "terminating-gateway"

  config_json = jsonencode({
    Services = [{ Name = "myservice" }]
  })
}
```

**Comment by blake** [comment]
Thanks @reskin89.

I'm still not able to reproduce the external node being created with a serf health check. Can you provide the output of `curl $CONSUL_HTTP_ADDR/v1/catalog/node/mynode-<env>-<dc>` as well?

Any additional logs or details you can share about your configuration would also be helpful. Thanks.

**Comment by reskin89** [comment]
No problem @blake .  Here's the output from that.  The logs don't really have any reference to this node at all.  Our configuration is pretty standard according to the "how to register an external node" documentation.  There's a terminating gateway that forwards traffic to an AWS ALB which fronts for some lambda functions.

Here's the output of the node from the catalog API:

```json
{
  "Node": {
    "ID": "",
    "Node": "mynode-dev-us-west-2",
    "Address": "REDACTED",
    "Datacenter": "us-west-2",
    "TaggedAddresses": null,
    "Meta": {
      "external-node": "true",
      "external-probe": "true",
      "region": "us-west-2"
    },
    "CreateIndex": 2074951,
    "ModifyIndex": 2074951
  },
  "Services": {
    "myservice": {
      "ID": "myservice",
      "Service": "myservice",
      "Tags": [
        "myservice-dev"
      ],
      "Address": "REDACTED",
      "Meta": {
        "external-source": "terraform"
      },
      "Port": 443,
      "Weights": {
        "Passing": 1,
        "Warning": 1
      },
      "EnableTagOverride": false,
      "Proxy": {
        "MeshGateway": {},
        "Expose": {}
      },
      "Connect": {},
      "CreateIndex": 2074954,
      "ModifyIndex": 2074954
    }
  }
}
```

**Comment by reskin89** [comment]
Just for some more info here, this is what `consul watch type=checks` shows for this external node status:

```json
{
    "Node": "myservice",
    "CheckID": "externalNodeHealth",
    "Name": "External Node Status",
    "Status": "critical",
    "Notes": "",
    "Output": "Node not live or unreachable",
    "ServiceID": "",
    "ServiceName": "",
    "ServiceTags": [],
    "Type": "",
    "Definition": {
      "Interval": "0s",
      "Timeout": "0s",
      "DeregisterCriticalServiceAfter": "0s",
      "HTTP": "",
      "Header": null,
      "Method": "",
      "Body": "",
      "TLSSkipVerify": false,
      "TCP": ""
    },
    "CreateIndex": 2228962,
    "ModifyIndex": 2228962
  }
```

I'm not sure why it has an empty check definition?

I have the same service registered in another region, with the same exact config, and it seems that the node health status just reflects the health check, i.e. my TCP/HTTP health check passes, the node health check in that region passes, it fails the node check in that region fails etc etc.

This region doesn't mirror that behavior (as is the reason for the issue being open).


Some more information about the setup:

* Dual Region Cloud
* an ESM Deployment in each region
* Each ESM deployment can only see its own region
* ESM Health Checks are passing just fine

The ESM Logs don't really have anything other than catalog fetches and how many nodes from each fetch it found.

**Comment by reskin89** [comment]
As an added note, I removed `external-probe: true`, deleted and then re-added the service and it seems okay now, however I'm wondering why that health check was failing at all, as the probe test itself passes if I test it manually.

**Comment by blake** [comment]
Hi @reskin89, thanks for the additional info. Previously I assumed there was a `serfHealth` check being registered for the external node, which Consul normally sets up for agents. I now see that this check is named `externalNodeHealth`, and is being registered by Consul ESM.

> it seems that the node health status just reflects the health check, i.e. my TCP/HTTP health check passes…

Based on my read of the Consul ESM code, it looks like the status of the externalNodeHealth check will be updated based on the result of an ICMP ping to the node.

https://github.com/hashicorp/consul-esm/blob/d152a60c4072cbae181f183c2431fab0a8da2279/coordinate.go#L266-L286

https://github.com/hashicorp/consul-esm/blob/d152a60c4072cbae181f183c2431fab0a8da2279/coordinate.go#L98-L99

> The ESM Logs don't really have anything other than catalog fetches and how many nodes from each fetch it found.

Which version of ESM are you using? Have you tried increasing the `log_level` in the ESM config to see if that generates more info as to why and when the node is being marked as unhealthy?
