### ISSUE TITLE
connect/ca: Vault Provider: Document and make the root CA TTL configuration

### ISSUE THREAD

**Issue by dnephin** [hashicorp/consul#10762]
Related to #10643

When the Vault root PKI is not already mounted, we mount it and set the `max_lease_ttl` to 1 year. I believe this effectively sets the Root CA expiration to 1 year. But we never document that it is set to this, and we don't allow the user to configure it.

1 year seems like a strange default, because we use 10 years for the Consul provider.

Related: `ttl` for generating the root https://www.vaultproject.io/api/secret/pki#ttl-2, which I believe is capped ta max_lease_ttl according to https://www.vaultproject.io/docs/secrets/pki#configure-a-ca-certificate

This issue is to:
1. document the current behaviour (which will likely remain the default)
2. allow the user to configure an expiration, and document that it is only used if the vault PKI is not already initialized.

**Comment by dschaaff** [comment]
The work around for those who want a longer root CA TTL is to create the Vault PKI backend yourself with lease TTLs to your desired length and then configure Consul to use it.

**Comment by FFMMM** [comment]
With https://github.com/hashicorp/consul/pull/11428 merged and coming in next https://github.com/hashicorp/consul/pull/11449, I'm going to close this issue.

Setting a ttl value for root certs will be in 1.11

Also the docs should be updated as part of https://github.com/hashicorp/consul/pull/11488
