### ISSUE TITLE
Login panel for consul

### ISSUE THREAD

**Issue by ashish235** [hashicorp/consul#1076]
Hi Team,

I must say I 'm a big fan of consul and I 'm using consul extensively for my entire platform for service discovery. I 'm also planning to move some key configurations to the consul's K/V store. However the issue here is the consul webpage on 8500 is open. Can the GUI be made authorized? I mean a login functionality be added it would be really helpful and will help keep my configurations confidential. Please let me know if I can expect it in the future releases or else I will have to work on some workarounds. 

Keep up the good work!!

Thanks.

**Comment by highlyunavailable** [comment]
By default, the Consul HTTP API is bound to 127.0.0.1, which means it is only accessible from the local server, not remotely at all unless you've exposed it to the world somehow. I assume you have, though, so there are 2 options:

1. If you're doing some type of internal portal (like I use at my company), use nginx as a proxy with another login mechanism upstream - e.g. [oauth2_proxy](https://github.com/bitly/oauth2_proxy).
2. If you need to lock down actual access to the data in Consul regardless of mechanism, you should use the [ACL system](https://www.consul.io/docs/internals/acl.html) to do so. The Consul Web UI has a field for putting in an ACL token, and if it's not filled in, just uses the Anonymous ACL. This does require you set your cluster(s) up for ACLs though.

**Comment by ryanuber** [comment]
@ashish235 what @highlyunavailable described is accurate. It's reasonable to add an authentication proxy layer like Apache or Nginx in front of Consul. It sounds like your needs are very basic, so keep in mind that there are also HTTP basic auth modules that work in the same way that the oauth modules do.

Hope that helps!

**Comment by ashish235** [comment]
Thanks @highlyunavailable  and @ryanuber. Cheers!

**Comment by ashish235** [comment]
I used nginx's http auth to achieve what I wanted.

**Comment by FritschAuctores** [comment]
Use ACL

https://learn.hashicorp.com/consul/advanced/day-1-operations/acl-guide#step-1-enable-acls-on-all-the-consul-servers

**Comment by aamir-mansoori** [comment]
> I used nginx's http auth to achieve what I wanted.

@ashish235 Could you pls explain how you achieved that?
