### ISSUE TITLE
If you write a proxy-defaults without name set the success message is confusing

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#10809]
#### Feature Description

Consul 1.10? introduced the ability to not set `Name = "global"` for proxy defaults configs, however when you write them with `consul config write` the success message looks weird:

```hcl
Kind = "proxy-defaults"
Config {
  protocol = "http"
}
```

```console
$ consul config write proxy-defaults.hcl
Config entry written: proxy-defaults/
```

Perhaps this could read

```
Config entry written: proxy-defaults
```

Or 

```
Config entry written: proxy-defaults/global
```

Which might help with knowing what to use when running `consul config read -kind proxy-defaults` since that command still requires the `-name global` flag.

**Comment by dnephin** [comment]
I wanted to make the name "global" implied for `proxy-defaults`, but that PR did not merge: #10067 . We did something similar with the new `mesh` config-entry, but that shouldn't have impacted the `proxy-defaults`. I suspect this has always worked this way.

The value being printed here comes directly from the parsed config (no round-trip through the API handler), so we can handle this entirely in the `GetName()` method for `api.ProxyConfigEntry` and `api.MeshConfigEntry`.
