### ISSUE TITLE
⭐ Help Consul improve its community engagement (meet with us)

### ISSUE THREAD

**Issue by jkirschner-hashicorp** [hashicorp/consul#10801]
The HashiCorp Consul team is thinking about how to improve how we engage with the rest of the Consul community. To do that, **we need your valuable perspective as a community member**!

If you're interested in sharing your **perspective on community engagement** with us, please **indicate your interest in a 45 minute, 1:1 Zoom conversation by filling out [this 3 minute survey](https://docs.google.com/forms/d/e/1FAIpQLSeVDlX5wiotLwCfWkc-RjJwX367cLTZWpKT9MKAj2Zl4UxVFQ/viewform)**. The survey helps ensure we speak with community members from a range of perspectives.

Thanks for your help and we look forward to our conversation!

**Comment by chrisboulton** [comment]
Hey @jkirschner-hashicorp - would love to participate but it looks like the survey form is only accessible to HashiCorp folks right now.

**Comment by jkirschner-hashicorp** [comment]
@chrisboulton : thanks for letting me know ... definitely not something I noticed when trying to open the link myself! You should be able to access it now.

**Comment by jkirschner-hashicorp** [comment]
Thank you to everyone who participated. I'll follow up with you in the future about changes we make based on the input you provided!
