### ISSUE TITLE
how to set consistency modes in Key/Value HTTP Endpoint and Catalog HTTP Endpoint?

### ISSUE THREAD

**Issue by juaby** [hashicorp/consul#1082]
in the doc, it tells that these endpoint support all consistency modes but not show how to

**Comment by armon** [comment]
@juaby See the "consistency mode" section here (https://consul.io/docs/agent/http.html). You just need to provide the `?stale` or `?consistent` query parameters in the request.

**Comment by juaby** [comment]
@armon thank you very much. next time I'll read doc more carefully

**Comment by asarkar** [comment]
@armon Just `?consistent` without any value, or `?consistent=true`?

**Comment by armon** [comment]
@asarkar no value is needed. As long as the flag is there, it will be respected.

**Comment by asarkar** [comment]
@armon, thanks for your response. This seems like an unusual way, since query params aren’t really command line flags. Why not just have `consistency=$mode`?

**Comment by armon** [comment]
@asarkar It could have been done that way, but that is not currently a flag the API supports.
