### ISSUE TITLE
possible provider batch deregister service api for agent endpoint?

### ISSUE THREAD

**Issue by juaby** [hashicorp/consul#1083]
let's say I have register a group service whose id begine from 1 to 1000 and I'd like deregister them all, is there a easy api to do so like batch deregister?

**Comment by ryanuber** [comment]
@juaby If the services were registered from configuration files, then simply removing the services from the configuration and sending the agent a HUP would do exactly as you mentioned. However, if they were registered from the API endpoints, then they would need to be deregistered one at a time.

**Comment by juaby** [comment]
@ryanuber thank you. I get it.
