### ISSUE TITLE
Use environment variables to configure addvertise_addrs.serf_lan and service.port

### ISSUE THREAD

**Issue by i0rek** [hashicorp/consul#1084]
I would like to configure the following options dynamically:

* addvertise_addrs.serf_lan
* service.port

I am running consul in a container and these values are determined on container boot. I can see three different ways to do that with the help of environment variablese: 

1) support command line flags for these options and populate them with these environment variables similar to every option that can be passed as parameter
2) introduce environment variable support in config files similar to packer templates
3) support specific environment variables to set the options directly like https://github.com/hashicorp/consul/pull/794

What do you think?

**Comment by ryanuber** [comment]
I think doing interpolation in Consul's config is probably overkill. My only concern really with adding the environment variables is that each one becomes a new special case, and Consul has quite a few options for the agent. The environment variables we use so far are mostly for client connection settings. Using a `config-dir` and writing a file at startup is probably the most common way to get this functionality currently (e.g., just write `{"advertise_addrs":{"serf_lan":"a.b.c.d"}}` to a file from a wrapper script in the config-dir at start and overwrite it on each subsequent start). Something like that might work for the time being.

**Comment by ryanuber** [comment]
Also, I'm not sure what you mean by `service.port` - are you thinking that would be used during service registration?

**Comment by i0rek** [comment]
Thanks for your response @ryanuber. I share your concern regarding the individual environment variables. Maybe I go with the wrapper script approach. I didn't consider that before. 

`service.port` was a mistake on my side. I mean the ports for the service registration. That could be as well handled in a wrapper script.
