### ISSUE TITLE
Host header autorewrite on terminating-gateway breaks some http flows

### ISSUE THREAD

**Issue by danieleva** [hashicorp/consul#10853]
#### Overview of the Issue
https://github.com/hashicorp/consul/pull/9042 added a very useful feature on terminating-gateway, inserting the required Host header for external services added by fqdn. That has a side effect of rewriting the host header even when it was already set by the client. 
In my case I have a single external node managing multiple services. My clients are setting the proper Host header when sending traffic into the mesh and the destination node was using it to determine which service was requested.
The autorewrite on terminating-gateway is replacing the header inserted by my clients with the external node fqdn and breaks my flows.
It would be awesome if the autorewrite feature was exposed as configurable in service definition or service-defaults, so it could be selectively enabled/disabled as needed.
#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Start an agent in dev mode
1. Register an external node and service: 
   ```json
    {
    "Node": "external",
    "Address": "foo.bar",
    "Service": {
        "ID": "sample",
        "Service": "sample",
        "Port": 5678
      }
   }
   ```
1. Set service-defaults to http: 
   ```hcl
   Kind      = "service-defaults"
   Name      = "sample"
   Protocol  = "http"
   ```
1. Assign the service to a terminaing-gateway: 
   ```hcl
   Kind = "terminating-gateway"
   Name = "terminating-gateway"
   Services = [
     { 
       Name = "sample" 
     }
   ]
   ```
1. Connect to the service via terminating-gateway, setting a host header: 
   ```
   curl --cert connect-cert.pem --key connect-key.pem --resolve sample.default.dc1.internal.[....].consul:8443:<terminating-gw-ip> https://sample.default.dc1.internal.[...].consul:8443  -H 'Host: my.desired.host'
   ```
1. The client sends: 
   ```
   > GET / HTTP/1.1
   > Host: my.desired.host
   > User-Agent: curl/7.64.1
   > Accept: */*
   ```
   The destination service receives: 
   ```
   > GET / HTTP/1.1
   > Host: foo.bar
   > User-Agent: curl/7.64.1
   > Accept: */*
   ```
### Consul info for both Client and Server

<details>
  <summary>Client/Server info</summary>

```
 consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = debb13e9
	version = 1.9.8
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 278
	commit_index = 278
	fsm_pending = 0
	last_contact = 0
	last_log_index = 278
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:2f52a7f7-c2a2-606c-a2d2-db96554fb262 Address:127.0.0.1:8300}]
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 12
	goroutines = 117
	max_procs = 12
	os = darwin
	version = go1.15.14
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

This happens on consul 1.9.5 and newer, I'm running linux amd64 but the issue is not platform specific

**Comment by jkirschner-hashicorp** [comment]
Hi @danieleva,

Thanks for reaching out. I've marked this as an enhancement request:
> It would be awesome if the autorewrite feature was exposed as configurable in service definition or service-defaults, so it could be selectively enabled/disabled as needed.

In the meantime, we have a workaround for you to consider. To bypass the header rewrite for the `sample` service, you could change its service-defaults to use `Protocol = "tcp"` instead of `"http"`. This would mean that only identity based (L4) intentions are available. Application aware (L7) intentions require the protocol to be http-based (not set to tcp). For more details on this, see our [intentions docs](https://www.consul.io/docs/connect/intentions).

**Comment by danieleva** [comment]
Hi, thanks for the quick reply.
Yeah I'm implementing the `tcp` workaround for now, luckily I don't need L7 intentions yet so I can keep running in L4 mode for some time.

**Comment by danieleva** [comment]
An update, we now need L7 features :) Not for intentions but for metrics. Having http response codes across the mesh in invaluable when troubleshooting. Is there any eta for this enhancement? 
We are running a patched custom binary to workaround the problem, but maintaining a patchset across versions is no fun :)

**Comment by danieleva** [comment]
:D thanks for this. I can finally stop porting my patch in our internal
build. 🎉
