### ISSUE TITLE
Token renewal by vault connect ca

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/consul#10862]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

We have been using vault as a connect ca provider, with the cluster managing renewal of a periodic token.  We are able to generate and issue tokens successfully.

Due to a permission policy issue, consul servers had a problem renewing its periodic vault token.  We observed this sent it into a tight loop of requests, generating 40k log messages in 1 min at the vault end about the failed renewal.  (We also didn't observe log entries about the failed renewal, but that may well be our own misconfiguration).

What is the expected behaviour in this situation?

### Consul info for both Client and Server

Consul 1.9.8 server on ubuntu 20.04

**Comment by jkirschner-hashicorp** [comment]
Possibly fixed by https://github.com/hashicorp/consul/pull/12607. Will post an update if that is confirmed or rejected.

**Comment by jkirschner-hashicorp** [comment]
This issue should be fixed by #12607. This issue will therefore not be experienced in the following Consul versions:

- 1.10 release series: 1.10.10+
- 1.11 release series: 1.11.5+
- All release series >= 1.12
