### ISSUE TITLE
api: some api client library methods mask the underlying error when non-200 status codes are received

### ISSUE THREAD

**Issue by dnephin** [hashicorp/consul#10865]
See #8816

#### Overview of the Issue

Copied from #8816

> Consul agent returns errors in plain text. Yet when this happens the api client still tries to decode them in JSON, failing, and hiding the real error message.

It seems like some methods in the `api` client library do properly check the error code with `requireOk`, where as others do not. The methods that do not properly check the error code will error with JSON decode errors when the HTTP response was not 200. This error masks the real underlying problem, making the api client library difficult to use.

**Comment by FFMMM** [comment]
We merged https://github.com/hashicorp/consul/pull/11054 to allow the error status code to be queried programmatically. 

Keeping this issue open until I take a pass over all `doRequest()` func calls and make sure they're wrapped in `requireHttpCodes()` or return a `StatusError` type

**Comment by FFMMM** [comment]
@dnephin with PR https://github.com/hashicorp/consul/pull/11158 I think we can close this issue. What do you think?

For the refactor discussed here https://github.com/hashicorp/consul/pull/11158#issuecomment-930436357 I can open an issue to track visibility.

**Comment by dnephin** [comment]
Sounds good!
