### ISSUE TITLE
can consul write stale when partition happends and no leader can be elected?

### ISSUE THREAD

**Issue by juaby** [hashicorp/consul#1086]
let's say in 3 server cluster and each one of them can't connect to others since network partition happens, then client connect to one server and this server provide read and write in local env temporarily and when network recover, drop all the local data and provider read/write service as a cluster

**Comment by highlyunavailable** [comment]
No, only reads can be stale. A "stale" (that is, non-linearizable) write would be violate all guarantees Consul provides about data.

**Comment by ryanbreen** [comment]
What he said. If you have follow-ups, I encourage you to bring them to the mailing list or IRC.
