### ISSUE TITLE
Cut a new release to support go 1.17

### ISSUE THREAD

**Issue by roopakv** [hashicorp/consul#10875]
We drafted a fix to support go 1.17 here: https://github.com/hashicorp/consul/pull/10869

Until a new release is cut go1.17 on homebrew is blocked :)

please cut a new consul release.

context: https://github.com/Homebrew/homebrew-core/pull/83413

**Comment by jkirschner-hashicorp** [comment]
Hi @roopakv,

Thank you for contributing that change!

The change has been merged and will be available in the 1.10 path release towards the end of this month.
