### ISSUE TITLE
How to resolve consul cluster not promote to leader 

### ISSUE THREAD

**Issue by JBOSSKUB** [hashicorp/consul#10887]
In my environment have 3 contanier but when once contaanier not join in cluster found container on cluster not promote to leader  and contanier out of cluster not rejoin to the cluster  ,  How to resolve this problem  Please help to expain for FIX this problem .

**Comment by jkirschner-hashicorp** [comment]
Hi @JBOSSKUB,

Can you provide the following information?

- What documentation page(s) were you following, if any? Where in the steps on those pages did you start having problems?
- What command did you use to start the Consul server agents?
- What are the contents of the agent configuration file used to start the Consul server agents? Please remove any information you consider confidential.
- Please provide the log output from the Consul servers? Please remove any information you consider confidential.

**Comment by jkirschner-hashicorp** [comment]
Hi @JBOSSKUB - just checking in again, are you able to provide any of the info requested above? Without that information, we don't have enough information to take further action.

**Comment by JBOSSKUB** [comment]
Sorry for reply rate , I'm didn't captured screen at the problem time  and we  already fix this problem  via  command join container in our cluster but  we don't know this my solution is long term or not , Your can suggest the solution for applied in our system ? 

example  consul  at the problem time as below ,

/ $ consul operator raft list-peers
Node          ID                                    Address             State                                       Voter  RaftProtocol
(unknown)     ea4012d0-2753-385d-83fc-5ccd8417b769  172.16.128.11:8300  follower                                    true   unknown
d4d6a49fac4e  061bf138-5c07-b28c-1b73-185ad99791d2  172.16.128.32:8300  follower                                    true   3
/ $
 
 error msg :   2021/08/20 05:01:07 [ERROR] raft: Failed to make RequestVote RPC to {Voter ea4012d0-2753-385d-83fc-5ccd8417b769 172.16.128.11:8300}: dial tcp 172.16.128.34:0->172.16.128.11:8300: connect: no route to host    2021/08/20 05:01:07 [WARN] serf: Failed to re-join any previously known node

**Comment by jkirschner-hashicorp** [comment]
Hi @JBOSSKUB,

What command did you use to start the Consul server agents? What are the contents of the agent configuration file used to start the Consul server agents? Please remove any information you consider confidential.

And what was the "`command join`" you ran that worked (allowed 172.167.128.11 to join the cluster)?

This information could help us understand why join failed based on the configuration file, but worked from the command line.
