### ISSUE TITLE
Envoy listener escape hatch for prepared query upstreams ignored in 1.10

### ISSUE THREAD

**Issue by gzavitz** [hashicorp/consul#10897]
#### Overview of the Issue

The `envoy_listener_json` field in the upstream configuration of a `prepared_query` destination is ignored in versions 1.10+. The cluster escape hatch does still work in 1.10.

#### Reproduction Steps

1. Run `consul agent -dev`
1. Create any prepared query
1. Register a service, then its sidecar configuration with Consul. Include an upstream to the previously created prepared query, including a listener escape hatch in `envoy_listener_json`.
1. Generate the bootstrap configuration for the sidecar and start Envoy with it
1. Observe both the agent trace xds logs and the config_dump admin interface to see that Consul is returning a default TCP proxy listener instead of the listener specified in the escape hatch.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 2
build:
	prerelease =
	revision = db839f18
	version = 1.10.1
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 49
	commit_index = 49
	fsm_pending = 0
	last_contact = 0
	last_log_index = 49
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:0fcc7360-f8c3-72c7-48b8-63a401d289ce Address:127.0.0.1:8300}]
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 125
	max_procs = 8
	os = linux
	version = go1.16.6
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
same as client info
```

</details>

### Operating system and Environment details

Running in Debian 10 Docker container using Consul downloaded from https://www.consul.io

### Log Fragments

https://gist.github.com/gzavitz/8e01f2565fb14dd6c2543456e5b364a1

**Comment by gzavitz** [comment]
Hi Chris, that's right -- `envoy_cluster_json` works in all 1.10.x releases while `envoy_listener_json` does not. Thanks for writing up the exact reproduction steps.

**Comment by kisunji** [comment]
Thanks for the report @gzavitz, the fix has been applied and should be out in the next patch release.
