### ISSUE TITLE
consul kv import @a-file.json change behavior since 1.10.0

### ISSUE THREAD

**Issue by rocwenlinux** [hashicorp/consul#10906]
#### Overview of the Issue

consul kv import @a-file.json change behavior since 1.10.0.  The 1.9.8 and older versions treat  "service/importtest/" (with slash at the end) as a key, but 1.10.x treat "service/importtest/" as "service/importtest", the tail slash is missing.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1.  prepare a json file for importing, named as test.json.  
```
[
	{
		"key": "service/importtest/",
		"flags": 0,
		"value": "MjAyMC4wMi4xNCAyMDo1Njo1Mw=="
	}
]
```
2. Run `consul kv import @test.json`
3. output
```
eric$ ~/Downloads/consul10.0 kv import @test.json
Imported: service/importtest
eric$ consul kv delete -recurse service/importtest
Success! Deleted keys with prefix: service/importtest
eric$ ~/Downloads/consul198 kv import @test.json
Imported: service/importtest/
```
### Operating system and Environment details

consul cluster running consul 1.9.5, Ubuntu server
consul cli running in MacOS 11.5.2, intel

**Comment by shantanugadgil** [comment]
I think there is a possible bug in the `consul kv export` as well, I checked with version 1.11.1.

The export of a recursive "folder" produces an entry with the trailing slash, like so:

```
consul kv export toplevel
[
        {
                "key": "toplevel/",
                "flags": 0,
                "value": ""
        },
        {
                "key": "toplevel/alpha",
                "flags": 0,
                "value": "c29tZXRoaW5nCg=="
        },
        {
                "key": "toplevel/bravo",
                "flags": 0,
                "value": "c29tZXRoaW5nCg=="
        }
...
]
```

For my case, the `"key": "toplevel/",` need not exist in the output at all, as it is NOT there as a separate key.

**Comment by blake** [comment]
Hi @shantanugadgil,

I'm not able to reproduce the behavior you described with Consul 1.9.13, 1.10.6, or 1.11.1, _unless_ I explicitly create the `foo/` key. For example:

```shell-session
$  consul kv export foo/
[]

$ consul kv put foo/a aaa
consul kv put foo/b bbb
consul kv put foo/c ccc
Success! Data written to: foo/a
Success! Data written to: foo/b
Success! Data written to: foo/c

$ consul kv export foo/
[
        {
                "key": "foo/a",
                "flags": 0,
                "value": "YWFh"
        },
        {
                "key": "foo/b",
                "flags": 0,
                "value": "YmJi"
        },
        {
                "key": "foo/c",
                "flags": 0,
                "value": "Y2Nj"
        }
]

$ consul kv get -detailed foo/
Error! No key exists at: foo/

$ consul kv put foo/
Success! Data written to: foo/

$ consul kv get -detailed foo/
CreateIndex      23075398
Flags            0
Key              foo/
LockIndex        0
ModifyIndex      23075398
Session          -
Value

$ consul kv export foo/
[
        {
                "key": "foo/",
                "flags": 0,
                "value": ""
        },
        {
                "key": "foo/a",
                "flags": 0,
                "value": "YWFh"
        },
        {
                "key": "foo/b",
                "flags": 0,
                "value": "YmJi"
        },
        {
                "key": "foo/c",
                "flags": 0,
                "value": "Y2Nj"
        }
]
```

Can you verify that your top-level key was not manually created through some other means? If it is present and you don't need it, you can safely remove it from the KV store without affecting the ability to retrieve the other keys from the CLI or UI.

**Comment by shantanugadgil** [comment]
@blake this indeed seems to be the case; when the `toplevel/` has been created separately, the weirdness happens.

I tried to reproduce the issue using the webui, and this gets all the more confusing as it violates WYSIWYG.

_I feel there is more buggy behavior that easily visible._

Steps to repro via webui:
Consul version: 1.11.1

1. in the webui, go to Key/Value
2. create key named `toplevel/` (with trailing slash)
3. click `toplevel` "folder"
4. click the blue `Create` button. 
5. I expect to see the combined boxes of `Key or folder` and `Value`, I see only the `Value` box. :open_mouth: 
6. Never mind, go back to Key/Value root, and create a key named `toplevel/alpha` with value `aaa`
7. This gets created correctly (what I was actually trying to do in step 6 and 7)

I feel, seeing only the `Value` box in step 6 is a bug!

Also, if I do fill in some data when I see the Value box in step 6, it gets saved correctly, but not visible in the webui anywhere

**Comment by jkirschner-hashicorp** [comment]
Thanks @shantanugadgil - I was able to reproduce using your steps and filed a new GH issue for that GUI behavior (#12073).

**Comment by ajay-bongane** [comment]
Getting error while importing consul key value pairs from json file.

Command used:
consul kv import @consul-kv.json

Json (its well formatted using intellij before using):
[
  {
    "key": "config/application,docker/application.yml",
    "flags": 0,
    "value": "c3ByaW5nOgogIHJhYmJpdG1xOgogICAgaG9zdDogcmFiYml0bXEKICBjbG91ZDoKICAgIGNvbnN1bDoKICAgICAgZGlzY292ZXJ5OgogICAgICAgIGluc3RhbmNlLWlkOiAke3NwcmluZy5hcHBsaWNhdGlvbi5uYW1lfS0ke3JhbmRvbS5pbnQoMTAwMCl9"
  }
]


Error:
Cannot unmarshal data: invalid character 'ÿ' looking for beginning of value

I know it's complaining about json format or maybe file encoding. But I tried everything to ensure json is correctly formatted.
Could someone please assist on how to get rid of this error?

Appreciate your help.
