### ISSUE TITLE
Documentation about DNS propogation/recursion 

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/consul#1098]
Hi,

It would be good for the docs to be clearer about the following which I've had to investigate via tcpdumps as I couldn't find anywhere.
1. Each consul client agent maintains its own DNS service, based on its current state.
2. Each consul client agent does not recurse automatically to the consul server agent either by port 8600 or by port 53
3. Therefore, adding recursors to the consul server agents is not enough, you have to add them to the consul client agents as well.

I had assumed that the consul agent by and large is a cache layer for a state maintained by the consul quorum, and that for DNS, if it did not recognise a record, it would recurse up to the quorum to find it. This didnt work - and its first choice is to recurse out to 8.8.8.8, something which isn't necessarily supported.

```
<muse>
```

As an aside would it make more sense for the consul agent to by default recurse to the consul quorum, and the consul quorum to default recurse to 8.8.8.8 instead? Distributed DNS requests, vs one place to configure everything I guess.

```
</muse>
```

**Comment by armon** [comment]
@gtmtech The clients are almost entirely stateless. Any query involving a ".consul" TLD is ultimately transformed into an RPC call to the servers, where as all other queries are forwarded to a resolver if specified.

**Comment by gtmtech** [comment]
Thanks - thats cool if it works that way, is it documented anywhere? I guess it is now via this issue :)

**Comment by ryanuber** [comment]
@gtmtech the docs do mention recursors, but this could probably use some clarification. If you have any cycles to submit a PR for the docs, that would be great to have! Otherwise, I'm tagging this as a docs enhancement, and will do a pass at some later point to add it. Thanks!

**Comment by aidanhs** [comment]
Just noting a +1 that this caused me confusion as well.

**Comment by i0rek** [comment]
We have docs now: https://www.consul.io/docs/agent/dns.html. Thanks for reporting!
