### ISSUE TITLE
Refuse to choose among multiple candidates for IP address

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/consul#1099]
On complex hosts, there may be more than one valid (non-loopback) IP address that Consul could choose to present to the cluster for inter-node communication.  Consul should refuse to automatically select one in this situation, because it could pollute the cluster information with a non-routable or otherwise incorrect IP address for that node if it guesses wrong.

**Comment by ryanuber** [comment]
Thanks for the suggestion, and agreed!
