### ISSUE TITLE
KV menu gone from the GUI in 1.10.1 and 1.10.2/Busted redirects?

### ISSUE THREAD

**Issue by avcercel** [hashicorp/consul#10997]
#### Overview of the Issue

In versions prior to 1.10.1, we had the possibility to select the KV Menu in the GUI. After we upgraded to 1.10.1, the menu is gone.

#### Reproduction Steps

Log on the GUI. The menu was on the lefthand side but it's no longer there in recent versions and, trying to craft the URI manually, I get some strange redirects.

If I craft the URI manually, such as https://hostname/ui/region/kv, I do end up in the right menu but if I select "deploy" or "namespaces", I get redirected to https://hostname/ui/acls/tokens. I just updated to the latest version today and no dice. Same situations.

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 3cb6eeed
	version = 1.10.2
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.2.85.174:8300
	server = true
raft:
	applied_index = 7212914
	commit_index = 7212914
	fsm_pending = 0
	last_contact = 95.63137ms
	last_log_index = 7212914
	last_log_term = 464
	last_snapshot_index = 7210738
	last_snapshot_term = 462
	latest_configuration = [{Suffrage:Voter ID:0b53004d-4f1d-db3c-da08-cc22c129edc3 Address:10.2.85.9:8300} {Suffrage:Voter ID:43c7a5da-464c-b121-176e-10a463990985 Address:10.2.85.174:8300} {Suffrage:Voter ID:266756f4-c2f2-cad1-409c-36ae35c03aec Address:10.2.85.106:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 464
runtime:
	arch = arm64
	cpu_count = 4
	goroutines = 169
	max_procs = 4
	os = linux
	version = go1.16.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 161
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 11
	member_time = 627309
	members = 22
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 3
	member_time = 164103
	members = 6
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

**Comment by johncowen** [comment]
Hi @avcercel 

Thanks for the report! I'm guessing this is the same issue as https://github.com/hashicorp/consul/issues/10944

There's a PR (#10916) up that should go some way to fixing this problem, there is a larger problem we need to look at tho, so the fix there is "revert to previous functionality", which would unblock folks like yourself in the short term.

**Comment by avcercel** [comment]
Thank you :)  we can close this if that's the fix and it would totally make sense.

**Comment by avcercel** [comment]
Hello @johncowen 

We just rolled 1.10.3 and while the KV has appeared, once you click on any of the directories from the KV menu, you end up in the tokens one.

Was this expected?

Thank you.

Alex
