### ISSUE TITLE
UI create button missing with acl

### ISSUE THREAD

**Issue by chris93111** [hashicorp/consul#11023]
#### Overview of the Issue

we have updated consul to 1.8 to 1.10.2 and now with acl write in sub kv , the button create is missing 

key_prefix "ansible/" {
  policy = "list"
}

key_prefix "ansible/role_vars/" {
  policy = "write"
}

![image](https://user-images.githubusercontent.com/27526373/133291041-f812b492-ec78-4064-86ee-085adac6eed4.png)

#### Reproduction Steps

consul with 1.10.2

create kv with token and sub acl 

### Consul info for both Client and Server

```
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 4
	services = 4
build:
	prerelease = 
	revision = 
	version = 1.10.2
consul:
	acl = enabled
	bootstrap = true
	known_datacenters = 2
	leader = true
	leader_addr = xxxxxxxx
	server = true
XXXXX

```

### Operating system and Environment details

redhat 7

**Comment by johncowen** [comment]
Hey @chris93111 👋 

Thanks for the report! I'm guessing this is the same issue as #10944 and #10997

There's a PR (#10916) up that should go some way to fixing this problem, there is a larger problem we need to look at tho, so the fix there is "revert to previous functionality", which would unblock folks like yourself in the short term.

**Comment by chris93111** [comment]
@johncowen ok thanks ! we wait
