### ISSUE TITLE
Support for "tag drift" between server and client representations

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#1102]
Typically we treat the client version of a service/check as authoritative and the source of truth. This simplifies the anti-entropy story and consistency as the edges always hold the truth. However, for some use cases, remote nodes need to modify the tags without the edge being aware. This is a problem today as the edges always "correct" the changes during anti-entropy. Supporting tag drift allows the clients to still manage register/deregister and the health checks but without overriding changes to tags on the servers. This enables some of these specialized use cases.

**Comment by ryanuber** [comment]
Interesting approach. @armon do you think this would basically just be a flag to disable tag sync during anti-entropy altogether? Sounds like the easiest way might be to just sync the tags if we are doing a registration, but not if we are ensuring later on.

**Comment by armon** [comment]
@ryanuber I think the flag would just nil-out the tags for the purpose of checking if the two service entries are the same. This way if the service registration is missing, then the client side tags are used. Otherwise, the service side tags are used.

**Comment by sfncook** [comment]
@armon Not to pester but is there anyway I can assist with this to ensure it makes it into the next release?  Or even to get it into a nightly build?

**Comment by slackpad** [comment]
This is merged and will go out in the next release.
