### ISSUE TITLE
Correct way to tune dead node timeout

### ISSUE THREAD

**Issue by ask0n** [hashicorp/consul#1108]
By default it takes about 15s to remove node from DNS service list, when it died (kill -9 on consul process). Is it possible to do something to lower this to 2-3 seconds?

**Comment by armon** [comment]
@bancore This is not currently possible, as it requires tuning the low-level parameters of Serf which are not exposed. We want to expose them eventually, but tuning them down increases the rate of false positives.

**Comment by bancore** [comment]
Even "TTL check" is helpless here?

**Comment by armon** [comment]
@bancore The TTL check is a different mechanism and can be set to a much lower value. The difference  is that the TTL check is managed by a running agent, while detecting if a different agent has failed requires the gossip protocol

**Comment by slackpad** [comment]
Closing this out as the TTL check provides a good solution.
