### ISSUE TITLE
msg="registry is not available"

### ISSUE THREAD

**Issue by Rakshithakrishna2** [hashicorp/consul#11094]
Hi all,
While using Ireland version,I am facing issues while running services with consul.
Scenario1: Initially( at new) when services like core-metadata, core-command, device services, application services etc are run with consul.
example: ./core-command -cp=consul.http://10.168.1.74:8500 --registry --confdir=./res ( after running the consul server).
It is able to register with consul.Scenario2: Now I Have changed to execute on different machine and have changed the host ip to that  respectively.
example: ./core-command -cp=consul.http://10.168.1.77:8500 --registry --confdir=./res
And run the service, now I find that the consul is defaulty taking the previous IP (10.168.1.74)and giving me error as "Registry not available".While debugging it, I found in this link - https://github.com/edgexfoundry/developer-scripts/pull/317 and export an environment variable : export EDGEX_STARTUP_DURATION="60"
![Screenshot from 2021-09-21 11-11-02](https://user-images.githubusercontent.com/88701371/134128900-e908bad7-6ddc-4bc4-8d45-429c32514b9b.png)

Still I am facing the same error.
Please find the image attached and kindly provide me the guidance.
Thank you.

**Comment by jkirschner-hashicorp** [comment]
Hi @Rakshithakrishna2,

As best as I can tell, the `"registry is not available"` error message is not being generated by Consul (it doesn't appear in the source code).

One thing you could check is whether Consul is accessible from `http://10.168.1.74:8500`, perhaps by seeing the output of `curl http://10.168.1.74:8500/v1/agent/members`. If you can't access that endpoint, perhaps Consul is not accessible at that IP address for some reason (or not running).

I'd recommend reposting your question on the repository for the edgexfoundry tool you are using.

Thanks!
