### ISSUE TITLE
Transparent proxy for the service that is outside of service mesh via Terminating gateway

### ISSUE THREAD

**Issue by Shige99011** [hashicorp/consul#11091]
Hi, I'm using Transparent Proxy (that's really good feature!) with the latest consul helm chart (0.32.1).

This is just a quick question.
Is it possible to access like Transparent proxy to an external service that is running outside of the service mesh via terminating gateway?
Currently it needs the upstream annotation with the service name and port like `'consul.hashicorp.com/connect-service-upstreams': 'external-service:9001'`
Then a service in the service mesh accesses to the external service by using local host address and the port like "http://127.0.0.1:9001/external-service".

Thanks for your help.

**Comment by blake** [comment]
Hi @Shige99011, this now supported as of [Consul 1.11.2](https://github.com/hashicorp/consul/blob/main/CHANGELOG.md#1112-january-12-2022).

IMPROVEMENTS:
* connect: Add support for connecting to services behind a terminating gateway when using a transparent proxy. [GH-12049]

After you associate the external service with the terminating gateway, apps in your mesh can reach it via transparent proxy by connecting to the IP address returned from the [virtual IP service lookup](https://www.consul.io/docs/discovery/dns#service-virtual-ip-lookups) for the service (e.g., `external-service.virtual.consul`).

**Comment by Shige99011** [comment]
Thanks for the notification!
