### ISSUE TITLE
dnsNames in csr for ingress should not include port

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/consul#11092]
#### Overview of the Issue

We are using consul connect with Nomad, and we have an ingress job looks like follows (with some other hosts omitted):
![image](https://user-images.githubusercontent.com/21690857/134071604-5d30c062-8566-48e1-a526-635acdd542ac.png)

Before we are using the builtin Connect CA provider, as we plan to migrate to using Vault as the Connect CA provider, we found an issue when consul is trying to obtain the cert for ingress:
```
[ERROR] agent.proxycfg: Failed to handle update from watch: service_id=_nomad-task-e4b4a015-8d2e-b6f3-3453-70043288bbd1-group-ingress-group-ingress-inbound id=leaf error="error filling agent cache: error issuing cert: Error making API request.
 
URL: PUT http://vault.service.consul:8200/v1/pki_consul_connect_int/sign/leaf-cert
Code: 400. Errors:
 
* subject alternate name ingress.service.consul:8080 not allowed by this role"
```

As the error suggest consul simply takes the value from `hosts` and put them in the csr. However the port should not be there in the dns names for csr if i understand correctly.

#### Reproduction Steps

1. Using a host with port in `hosts` when configuring ingress
2. using vault as Connect CA provider

Looks like the related part is here: https://github.com/hashicorp/consul/blob/959299077322953ce82ce0756ae9a8626ce907db/agent/proxycfg/ingress_gateway.go#L229

**Comment by blake** [comment]
Hi @fredwangwang, Consul 1.8.0 required the ingress port to be specified in the hosts value when using a non-standard port. This was fixed in Consul 1.8.1 by PR #8190, but the callout to include the port was not removed from either the Consul or Nomad documentation until last month (PR #10827 and hashicorp/nomad#11042).

If you are using a version of Consul newer than 1.8.0, you can safely remove the port from the `hosts` field in your job specification.

**Comment by fredwangwang** [comment]
Hi @blake  we are actually using consul 1.10.1 (sorry didn't include the version in the post)

And tried to remove the port it does not work. Here the detailed explain:

we have client side lb listen on port 29999, and we have ingress listen on port 8080. For our non mesh service to talk to mesh service, we have them going through clb (29999) instead of ingress directly for backwards compatibility. All clb does is forwarding req to ingress.

So our network flow:
srvA --> localhost:29999/srvB --> localhost:8080/srvB --> srvB in mesh.

Because we have the clb as the first layer, the `Host` header presented to ingress ended up being `localhost:29999` instead of `localhost:8080`, and ingress rejects the request due to the envoy host matching rule: https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_my_route_not_found.

So we still ended up needing the `localhost:29999`, along with some other non standard port domain names gets added to the hosts section.

**Comment by blake** [comment]
@fredwangwang Thanks for the additional information.

It sounds like you'll also want to override the HTTP Host header before sending the request to the ingress gateway. The exact configuration steps will vary depending on which gateway you are using as your CLB.

Here's an untested example of how you might override the Host header using nginx.

```nginx
server {
  listen       29999;
  server_name  _;

  location / {
    proxy_pass      https://127.0.0.1:8080;

    # Use HTTP/1.1 for proxying
    proxy_set_header Connection "";
    proxy_http_version 1.1;

    # Set host and SNI headers to 'ingress.service.consul' hostname
    proxy_set_header Host "ingress.service.consul";
    proxy_ssl_server_name on;
    proxy_ssl_name   "ingress.service.consul";

    # Disable TLS verification.
    # Change to 'on' if the nginx host trusts the Connect CA.
    proxy_ssl_verify off;
  }
}
```

**Comment by fredwangwang** [comment]
Hi @blake, there are some constraints we are facing that we need the original host header when sending to the services (be it `localhost:29999` or `some.domain.tld:12345`), so we cannot hardcode the host to just `ingress.service.consul`

**Comment by blake** [comment]
> …we need the original host header when sending to the services (be it localhost:29999 or some.domain.tld:12345), so we cannot hardcode the host to just ingress.service.consul

You can configure your CLB proxy to pass this host header to the Consul ingress, and correspondingly configure the ingress to route this hostname to the desired backend service.

Here's of an example of using nginx to pass the original host header to the backend proxy–in this case the ingress gateway–by setting the value of the HTTP `Host` header to the [`$host`](https://nginx.org/en/docs/http/ngx_http_core_module.html#variables) variable in nginx. See https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers for more info.

```nginx
server {
  listen       29999;
  server_name  myservice.example.com;

  location / {
    proxy_pass      https://127.0.0.1:8080;

    # Use HTTP/1.1 for proxying
    proxy_set_header Connection "";
    proxy_http_version 1.1;

    # Pass the value of the host header, myservice.example.com, to the backend proxy
    proxy_set_header Host $host;
    proxy_ssl_server_name on;
    proxy_ssl_name   $host;

    # Disable TLS verification.
    # Change to 'on' if the nginx host trusts the Connect CA.
    proxy_ssl_verify off;
  }
}
```

Configure the Consul ingress gateway to route requests for `myservice.example.com` to the correct backend service.

```hcl
ingress {
  tls {
    enabled = true
  }

  listener {
    port = [[ .http_port ]]
    protocol = "http"

    service {
      name = "example-service"
      hosts = ["myservice.example.com"]
    }

    service {
      name = "a-different-service"
      hosts = ["different-service.example.com"]
    }
  }
}
```

**Comment by jkirschner-hashicorp** [comment]
Hi @fredwangwang,

To confirm my understanding:
- Does everything work as you expect if you receive a signed cert from Vault with the SAN of `ingress.service.consul:8080` (when you're able to force `enforce_hostnames=false` in <=1.12.4)?
- If your ingress config still had `hosts = ["ingress.service.consul:8080"]`, but the CSR submitted to Vault had a SAN of `ingress.service.consul` (with the port stripped), would you expect this to work for your setup?

**Comment by fredwangwang** [comment]
> Does everything work as you expect if you receive a signed cert from Vault with the SAN of ingress.service.consul:8080 (when you're able to force enforce_hostnames=false in <=1.12.4)?

yes

> 

> If your ingress config still had hosts = ["ingress.service.consul:8080"], but the CSR submitted to Vault had a SAN of ingress.service.consul (with the port stripped), would you expect this to work for your setup?

yes. Cert does not care about port (which is in my issue title: `csr for ingress should not include port` ), but the route generated **need** to have the port: https://www.envoyproxy.io/docs/envoy/latest/faq/debugging/why_is_my_route_not_found

**Comment by jkirschner-hashicorp** [comment]
Hi @fredwangwang,

There's a [PR in progress](https://github.com/hashicorp/consul/pull/15320) that intends to address the challenge you shared in this Github issue.

Let us know if you have any concerns about that approach.
