### ISSUE TITLE
JsonReaderException while executing consul put request using WriteResult<KVTxnResponse>> Txn Consul, nuget Version=0.7.2.6

### ISSUE THREAD

**Issue by tavisca-vghatol** [hashicorp/consul#11093]
#### JsonReaderException while executing consul put request using WriteResult<KVTxnResponse>> Txn Consul, Version=0.7.2.6

A paragraph or two about the issue you're experiencing.
I'm using Consul, Version=0.7.2.6 nuget package. I'm trying to to use the Task<WriteResult<KVTxnResponse>> Txn(List<KVTxnOp> txn, WriteOptions q, CancellationToken ct = default); method from IKVEndpoint. I'm sending a List<KVTxnOp> of 64 elements as a parameter to this method. But I'm getting JsonReaderException. 
Exact exception details are as below:
![image](https://user-images.githubusercontent.com/16287165/134110189-fae98a41-ac0a-41cf-b14f-029bc06ec311.png)

This same request with List<KVTxnOp > of 64 elements was perfectly fine but recently facing this issue. Facing this issue always and not intermittently. So, to dig into further, instead of 64 KVTxnOp, I created a single List containing only single KVTxnOp and then it was working fine. After that I tried List of 10 KVTxnOp then also it worked fine. I tried list of 50 KVTxnOp then it failed again with same exception. And then lastly I tried with List of 40 KVTxnOp and then it worked fine.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 9be6dfc3
        version = 1.6.1
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 70
        max_procs = 8
        os = linux
        version = go1.12.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 26550190
        failed = 348
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1802547
        members = 599
        query_queue = 0
        query_time = 21
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 9be6dfc3
        version = 1.6.1
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.231.23.246:8300
        server = true
raft:
        applied_index = 12484029
        commit_index = 12484029
        fsm_pending = 0
        last_contact = 7.357847ms
        last_log_index = 12484029
        last_log_term = 34
        last_snapshot_index = 12474440
        last_snapshot_term = 34
        latest_configuration = [{Suffrage:Voter ID:0aae7569-de2a-1618-cda8-266f5b0b8a22 Address:10.231.23.15:8300} {Suffrage:Voter ID:fbe6ff32-6e12-4fe7-430c-3512602306c3 Address:10.231.23.246:8300} {Suffrage:Voter ID:f50c52d3-ce4a-99c5-4f8c-7812eb11b452 Address:10.231.24.87:8300}]
        latest_configuration_index = 7772078
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 34
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 114
        max_procs = 2
        os = linux
        version = go1.12.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 24
        failed = 5
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 142
        members = 8
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 58
        members = 3
        query_queue = 0
        query_time = 1
```

</details>

**Comment by tavisca-vghatol** [comment]
Hi @blake, 
We have checked the server logs but we could not find an error "request body too large".
I think issue is in client, and that's why request is not even sent to the server. Because if we see the exception stack trace, then the exception is occured in NetwonSoft.Json which is invoked by Consul.PutRequest. So request even not reached to httpClient, it broke even before that. This is my understanding, please correct me if I am missing something.

> Did something recently change in your environment, after which you began seeing this issue?
We analysed our environment, we found that payload size has increased may be this is is the primary reason for failure. But I would like to know the exact cause/location where it failed. Because as per my understanding it is failing at client side and not server side. Also blake could you please help me withthe max allowed size for List txn in **Task<WriteResult> Txn(List txn, WriteOptions q, CancellationToken ct = default);**

**Comment by blake** [comment]
Hi @tavisca-vghatol,

The Consul .NET library is not maintained by HashiCorp, but rather by a third party <https://github.com/G-Research/consuldotnet>. I recommend you open an issue in that repository if you suspect the error is due to an issue with that API client library.

**Comment by tavisca-vghatol** [comment]
Thank you @blake. I will open an issue in that library. Will close this issue.
