### ISSUE TITLE
Vagrant cluster demo doesn't work with vagrant 1.7.3

### ISSUE THREAD

**Issue by drawks** [hashicorp/consul#1111]
The Vagrant file provided in the vagrant-cluster demo doesn't work with vagrant 1.7.3.
https://github.com/hashicorp/consul/tree/master/demo/vagrant-cluster

It seems that the ubuntu precise base box doesn't have the hostnamectl command require for the hostname to be set in accordance with the config.

 This line:
`n1.vm.hostname = "n1"`

results in this error:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostnamectl set-hostname 'n1'

Stdout from the command:



Stderr from the command:

stdin: is not a tty
bash: line 2: hostnamectl: command not found
```

**Comment by ryanuber** [comment]
Fixed in #1112
