### ISSUE TITLE
ACL destroy endpoint always returns 200

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul#1114]
Consul returns a 200 when an ACL destroy request is made for an ACL token that does not exist. I believe this should return 404.

When requesting to destroy an invalid token ``dbc1fd24`` I am getting a 200 response back:
```
"PUT /v1/acl/destroy/dbc1fd24?token=9ae5fe1a-6b38-47e5-a0e7-f06b8b2fa645 HTTP/1.1" 200 4
```
This was tested against v0.5.2

**Comment by ryanuber** [comment]
Let's track this with #1115 as a "fix the ACL endpoint HTTP codes" issue, since they are closely related. Thanks!
