### ISSUE TITLE
Unable to create key via the UI in Consul 1.10.x without a management token

### ISSUE THREAD

**Issue by athill** [hashicorp/consul#11142]
#### Overview of the Issue
In the Key/Value interface, when logged in with a token without the `global-management` policy, the UI does not show  a "Create" button.

We divvy up the key/value space with targeted policies for various groups. Since upgrading to version 1.10.x, they can no longer add a new key via the UI. They are still able to edit existing keys via the UI and can also add a new key via the API.

#### Reproduction Steps

1. With a management token create a folder named "team1"
2. Add a policy granting write access to "team1"
    ```
    key_prefix "team1/" {
      policy = "write"
    }
    ```
3. Generate a token assigning that policy
4. Log in with that token via the user interface and try to add a key under `team1/`
5. There is no "Create" button

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

  Not applicable
</details>

<details>
  <summary>Server info</summary>
  While this shows 1.10.0 for the version, we also tried 1.10.2
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 27de64da
	version = 1.10.0
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.200.16.40:8300
	server = true
raft:
	applied_index = 64601317
	commit_index = 64601317
	fsm_pending = 0
	last_contact = 3.765343ms
	last_log_index = 64601317
	last_log_term = 276
	last_snapshot_index = 64586399
	last_snapshot_term = 276
	latest_configuration = [{Suffrage:Voter ID:cf7fcbf0-b725-96d2-1866-8256fc66c105 Address:10.200.16.40:8300} {Suffrage:Voter ID:e826f1d0-c0fd-ac50-b51c-1201d14ed5a7 Address:10.200.56.15:8300} {Suffrage:Voter ID:e5b62f14-dc23-3c7b-4edb-2b6abff875d9 Address:10.200.49.25:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 276
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 104
	max_procs = 4
	os = linux
	version = go1.16.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 53
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 991
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 502
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Deployed in Kubernetes using the the Hashicorp Helm chart

**Comment by jkirschner-hashicorp** [comment]
Hi @athill,

I believe that this same problem was reported in #11023 and #10944 - which were recently closed by PR #10916. The fix will be included in the next patch release (1.10.3).

If you continue to experience this issue after upgrading to 1.10.3, please reopen and let us know. Thanks!
