### ISSUE TITLE
ACL info endpoint always returns 200

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul#1115]
When requesting information for an invalid ACL Id, 200 is returned with a `null` string payload value. It seems counter-intuitive to use HTTP status codes for this operation.

I would expect that requesting info for a ACL would return a 404 if the ACL Id is not present and a 403 if I do not have permission to make the request. In both cases, 200 is returned.

This was tested against v0.5.2

**Comment by ryanuber** [comment]
Makes sense to me, thanks for reporting this!

**Comment by mkeeler** [comment]
Closing this as the new ACL implementation in 1.4.0-rc1 will return a 403 now. For security reasons we don't return 404s but you will no longer get a 200 for the new ACL endpoints.
