### ISSUE TITLE
Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages

### ISSUE THREAD

**Issue by sahapasci** [hashicorp/consul#11162]
#### Overview of the Issue

When installing consul package on debian 10 I got the error below;

> 
> E: Encountered a section with no Package: header
> E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages
> E: The package lists or status file could not be parsed or opened.

#### Reproduction Steps

1. `curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -`
2. `sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"`
3. `apt update`

Here is the last part of packages file which causes the error. It doesn't have correct structure.

```
Filename: pool/amd64/main/consul-enterprise_1.10.3+ent_amd64.deb
SHA1: bc998171471b95e01a6a637c75e6de832d37439e
SHA256: 81f3a1673227f546de0afde63899f815ce12bac325da8434e7725faf48341c28
Size: 41854160

```

when I delete the files under the directory /var/lib/apt/lists and run apt update I face the same error. 

[apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages.txt](https://github.com/hashicorp/consul/files/7239589/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages.txt)

**Comment by shughes-uk** [comment]
Appears to have regressed
```sh
$ apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
$ apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease
Hit:3 http://security.debian.org/debian-security buster/updates InRelease
Get:4 https://apt.releases.hashicorp.com buster InRelease [9497 B]
Get:5 https://apt.releases.hashicorp.com buster/main amd64 Packages [43.6 kB]
Fetched 53.1 kB in 0s (148 kB/s)
Reading package lists...
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages.lz4
E: The package lists or status file could not be parsed or opened.
```

**Comment by eggbean** [comment]
This seems to be happening again.

```
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_hirsute_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

**Comment by Murat0zer** [comment]
> Came here to report this same issue, and noting that it will occur with any `apt` commands. Deleting the linebreak between `Size` and `Filename` in this block fixes the problem:
> 
> ```
> $ tail -22 /var/lib/apt/lists/apt.releases.hashicorp.com_dists_buster_main_binary-amd64_Packages
> Package: consul
> Version: 1.10.3
> License: MPL-2.0
> Vendor: HashiCorp
> Architecture: amd64
> Maintainer: HashiCorp <support@hashicorp.com>
> Installed-Size: 102484
> Depends: openssl, passwd
> Section: default
> Priority: extra
> Homepage: https://www.consul.io/
> Description: Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure. Please submit issues to https://github.com/hashicorp/consul/issues
> Filename: pool/amd64/main/consul_1.10.3_amd64.deb
> SHA1: a84aa60aa64dc735f45c1d286f9b71590a96f6b3
> SHA256: 3946041cc3e585a3977b7821690d2d996c45738e90502ddb1d7e15e320006908
> Size: 38132392
> 
> Filename: pool/amd64/main/consul-enterprise_1.10.3+ent_amd64.deb
> SHA1: bc998171471b95e01a6a637c75e6de832d37439e
> SHA256: 81f3a1673227f546de0afde63899f815ce12bac325da8434e7725faf48341c28
> Size: 41854160
> ```

This works. You can find the line with \n$\n[^Package:] regex.

**Comment by kpenfound** [comment]
Hi all, I can confirm this is resolved again. We're working on improving our tooling to prevent this from happening again. Apologies for the inconvenience!

**Comment by shkkmo** [comment]
This is happening again, here's the offending section this time:

```
Package: nomad-enterprise
Version: 1.2.4+ent
License: unknown
Vendor: HashiCorp
Architecture: amd64
Maintainer: HashiCorp <support@hashicorp.com>
Installed-Size: 94193
Depends: openssl, passwd, iproute2
Section: default
Priority: extra
Homepage: https://www.nomadproject.io/
Description: Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications. Nomad is easy to operate and scale and has native Consul and Vault integrations. Please submit issues to https://github.com/hashicorp/nomad/issues
Filename: pool/amd64/main/nomad-enterprise_1.2.4+ent_amd64.deb
SHA1: 8efaa06cd375fb198a1cfed7d1ec989e51e4a55e
SHA256: e6f71acec867cd653ac84477fe889b421d7b6af9f11e602ada355dd7968f30a3
Size: 37284912

Filename: pool/amd64/main/consul-k8s_0.39.0_amd64.deb
SHA1: c1472db558d565e9325e85a55565a6ddfeb14acf
SHA256: f29d92ca16e35b048eb37239036c934ed9b5c98bd6d6940589827617f4b0dc5a
Size: 25041304
```

**Comment by apahne** [comment]
Same problem here. Just not with **buster**, but with **groovy**

E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_groovy_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.

**Comment by 1it** [comment]
Sadly, I have the same issue on **Ubuntu bionic**:

```
Get:6 https://apt.releases.hashicorp.com bionic/main amd64 Packages [46.8 kB]
Fetched 46.8 kB in 1s (88.1 kB/s)                            
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_bionic_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

**Comment by EpMAK** [comment]
> Sadly, I have the same issue on **Ubuntu bionic**:
> 
> ```
> Get:6 https://apt.releases.hashicorp.com bionic/main amd64 Packages [46.8 kB]
> Fetched 46.8 kB in 1s (88.1 kB/s)                            
> Reading package lists... Error!
> E: Encountered a section with no Package: header
> E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_bionic_main_binary-amd64_Packages
> E: The package lists or status file could not be parsed or opened.
> ```

![image](https://user-images.githubusercontent.com/11886903/151852566-4c7bc57e-365a-4e6a-806c-0481bd06755b.png)

I suppose, it's here. Checked after removing spacing line.

**Comment by bharvey-brt** [comment]
We are also encountering this issue on Ubuntu bionic.

`apt-get update` results in:

```
Fetched 252 kB in 2s (137 kB/s)                               
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_bionic_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

and we're seeing the same issue in the file as shown above:

```
Package: nomad-enterprise
Version: 1.2.4+ent
License: unknown
Vendor: HashiCorp
Architecture: amd64
Maintainer: HashiCorp <support@hashicorp.com>
Installed-Size: 94193
Depends: openssl, passwd, iproute2
Section: default
Priority: extra
Homepage: https://www.nomadproject.io/
Description: Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications. Nomad is easy to operate and scale and has native Consul and Vault integrations. Please submit issues to https://github.com/hashicorp/nomad/issues
Filename: pool/amd64/main/nomad-enterprise_1.2.4+ent_amd64.deb
SHA1: 8efaa06cd375fb198a1cfed7d1ec989e51e4a55e
SHA256: e6f71acec867cd653ac84477fe889b421d7b6af9f11e602ada355dd7968f30a3
Size: 37284912

Filename: pool/amd64/main/consul-enterprise_1.10.5+ent_amd64.deb
SHA1: 1021afd8306fec2dfc3d1b7bc2ba891e3b3f33b6
SHA256: ebd70eead2c29e533bf91801229277a9af554641ed7a95699b25ba1c9df06ad8
Size: 42044780
```

**Comment by gene1wood** [comment]
@jkirschner-hashicorp it looks like there was a regression as this closed issue just began occurring again such that Ubuntu users of the hashicorp PPA are getting 

```
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_bionic_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

would it make sense to re-open this issue (it's also reported over in hashicorp/terraform#30436 ) or should a new issue be opened in this consul repo?

**Comment by gene1wood** [comment]
Thanks to whoever at Hashicorp fixed this. It looks like it was fixed in the last 12 hours ( https://github.com/hashicorp/terraform/issues/30436#issuecomment-1026868100 ) as I'm not getting the error anymore.

**Comment by LemminatorGer** [comment]
`E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/deb.debian.org_debian_dists_bookworm_main_i18n_Translation-en
E: Die Paketliste oder die Statusdatei konnte nicht eingelesen oder ge?ffnet werden.`

have anybody the same problem ?
