### ISSUE TITLE
How to test time between  service  unavailable and unable to resolve with DNS

### ISSUE THREAD

**Issue by hacpai** [hashicorp/consul#1117]
What do I test the time that registered service with consul is not available until DNS can't resolve it?

**Comment by ryanuber** [comment]
I'm not sure I completely understand, but if Consul detects a service is unhealthy, it will immediately be excluded from DNS results. This can certainly be masked if there is a caching DNS server between the client and the Consul instance, but if you are querying consul directly, then there should be no noticeable time between a service entering an unhealthy state and its appearance in the DNS server results.

**Comment by slackpad** [comment]
Closing this as we never heard back. Please let us know if you still need help.
