### ISSUE TITLE
dns Package Introduces Vulnerability

### ISSUE THREAD

**Issue by ManavIBM** [hashicorp/consul#11176]
The package github.com/miekg/dns introduces a vulnerabiltiy

Details of vulnerability:

```
Overview
github.com/miekg/dns is a complete and usable DNS library.

Affected versions of this package are vulnerable to Insecure Randomness. It improperly generates random numbers because math/rand is used. The TXID becomes predictable, leading to response forgeries.

Remediation
Upgrade github.com/miekg/dns to version 1.1.25 or higher.
```

**Comment by mikemorris** [comment]
All currently maintained versions of Consul are using a newer version of this dependency in which the noted vulnerability has been patched.

[Consul 1.8.15 miekg/dns@1.1.26](https://github.com/hashicorp/consul/blob/release/1.8.15/go.mod#L66)
[Consul 1.9.8 miekg/dns@1.1.41](https://github.com/hashicorp/consul/blob/release/1.9.9/go.mod#L66)
[Consul 1.10.2 miekg/dns@1.1.41](https://github.com/hashicorp/consul/blob/release/1.10.2/go.mod#L65)
