### ISSUE TITLE
multiline argument for `-node` to cli `consul catalog services` has no error body

### ISSUE THREAD

**Issue by meshantz** [hashicorp/consul#11191]
#### Overview of the Issue

The error response under the circumstances given in "Reproduction Steps" below is missing a body (the part between the parentheses). More information should be given to help troubleshoot, as is done with other error conditions on this command.

This caused me a lot of confusion troubleshooting a script that substituted a shell variable that had an unnoticed linebreak at the end.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. in one terminal run the dev consul agent: `consul agent -dev`
2. in a second terminal run `consul catalog services "a
" (line break in quotes is important)
3. receive the error: "Error listing services for node: Unexpected response code: 400 ()"

Example session:
```
$ consul catalog services -node "a
> "
Error listing services for node: Unexpected response code: 400 ()
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = c976ffd2
        version = 1.10.3
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 127.0.0.1:8300
        server = true
raft:
        applied_index = 47
        commit_index = 47
        fsm_pending = 0
        last_contact = 0
        last_log_index = 47
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:714e8978-0cc3-827a-da27-c40c5fad3ec1 Address:127.0.0.1:8300}]
        latest_configuration_index = 0
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 12
        goroutines = 100
        max_procs = 12
        os = linux
        version = go1.16.7
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

Client and server are the same dev instance. Version 1.10.3

</details>

### Operating system and Environment details

WSL2, Ubuntu 20.04  
consul version 1.10.3

**Comment by jkirschner-hashicorp** [comment]
Hi @meshantz,

My understanding is that the current error message (without the newline) currently looks like:
```
$ consul catalog services -node "a"
No services match the given query - try expanding your search.
```

What do you wish the error message would have looked like?

**Comment by meshantz** [comment]
Something like
```
Invalid value for "node" argument
```
would have made sense to me.

**Comment by kisunji** [comment]
This certainly looks like a bug! We would expect something to be populated between the parentheses but it's not happening so I think there's some investigation to be done on the HTTP handler (how is it passing 400 without an error body? Maybe json marshalling issues?) cc @FFMMM

**Comment by jkirschner-hashicorp** [comment]
@kisunji : should we be URL encoding parameters that are included in the URL (and decoding on the other side)? Node names currently _can_ include invalid URI characters (see #7313, #4992), though that's not recommended practice.

**Comment by dhiaayachi** [comment]
Another option is to check if the value is altered by url encoding it and if it's the case return `Invalid value for "/node" argument` for example, but this won't help fixing https://github.com/hashicorp/consul/issues/7313 and https://github.com/hashicorp/consul/issues/4992
My vote go for url encode everything that is passed to a url and url decode it at the other end of the http call (server side). It's not a breaking change because the behaviour is already broken for the cases that the url encode alter the entry.

**Comment by kisunji** [comment]
Found that our changes to URL encode/decode actually didn't fix this issue; seems like go's http server rejects `%0A` (URL-encoded newline) specifically with `400 Bad Request` before our handlers even see the request.
