### ISSUE TITLE
Programmatic Consul Exec

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#1120]
I'm building some deployment orchestration based on consul but I would rather use the HTTP API rather than shelling out to consul just to create an exec job since I'm going to be running this as an internal service that builds and executes arbitrary deployment commands in a %-based manner (deploy to 10% of all servers, then if signoff is ok, 50%, ask for signoff, then finish all 100%). Is there any documentation around consul exec that explains how exactly it works and/or triggers the other agents to do something?

**Comment by armon** [comment]
@highlyunavailable It's not documented or available through the HTTP API since its a bit of a highly nuanced dance to get it to work. There is a lot of API calls due to the streaming nature of responses that makes it hard to package as a single convenient API call. That said, it *is* possible, we are just using the API under the hood, so take a look at the exec code. It's just not simple.

**Comment by highlyunavailable** [comment]
Yeah, it's not hard to understand once I read the code, I was just seeing if there was an actual spec to reference. Thanks!

**Comment by armon** [comment]
@highlyunavailable As a heads up, we do want to improve the performance of the system by allowing output to stream directly to the client instead of via KV. This will probably shift some things, but the current stuff should continue to work for backwards compatibility.

**Comment by highlyunavailable** [comment]
@armon I'm actually rebuilding the entire remote exec system in C# as part of my [Consul API](https://github.com/PlayFab/consuldotnet) so that I can do remote execution from an administration web site without the admin server having direct to set up direct connections (e.g. PowerShell remoting) to service instances, so any pointers on how you'd design it to be more performant without going through KV would be interesting.

**Comment by armon** [comment]
@highlyunavailable The idea is that the Consul agent would setup a temporary TCP listener and send that address as part of the exec payload. Then clients can connect and stream results back directly. Alternatively, a server based approach allows servers to act as brokers without going through K/V and using Raft.

**Comment by highlyunavailable** [comment]
@armon Ah okay, so that would be part of the Consul agent and would be handled entirely through it rather than leveraging the event system + storage like the current method does. I assume there'd be some sort of endpoint on the agent that the `consul exec` command would connect to in order to stream down the output from the TCP connection as well, or would you be setting up the TCP listener in Go directly inside the `consul exec` command?

**Comment by armon** [comment]
@highlyunavailable Likely it would be through the agent as you are saying. The exec process would not do the listening.

**Comment by highlyunavailable** [comment]
Excellent! Thanks for the info. I'll just finish implementing what I've got and switch it over in any new version of Consul that starts to use a new method.
