### ISSUE TITLE
Feature proposal: SRV lookup for bootstrapping and joining clusters

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul#1121]
I've been thinking about working on a PR that adds bootstraping via SRV for cluster discovery. etc2 has a similar feature and it works nice in cloud environments so you don't have to know the IPs when writing out the boot config.

I'm thinking it would add the following CLI switches:
```
    -join-srv <domain.com>
    -retry-join-srv <domain.com>
```

Where domain.com has SRV records setup as so:
```
_consul._tcp.domain.com. 300 IN   SRV 0 0 8300 consul0.domain.com.
_consul._tcp.domain.com. 300 IN   SRV 0 0 8300 consul1.domain.com.
_consul._tcp.domain.com. 300 IN   SRV 0 0 8300 consul2.domain.com.
```

So for example, when bootstrapping:
```
consul agent server --bootstrap-expect 3 --retry-join-srv domain.com 
```

And when joining an existing cluster:
```
consul agent --retry-join-srv domain.com
```

The logic would be to grab all the SRV records specified and treat them as individual IP addresses, as --join or --retry-join treats them.

Would such a PR be welcome? If so does the syntax and cli switch names seem reasonable?

**Comment by highlyunavailable** [comment]
You can already do `-join consul.example.com` today. The problem that all of these ideas run into is that `consul.example.com` needs to be resolvable from the DNS server the computer already has that is not Consul itself. If you add a record to your DNS server that points to a Consul server or a set of records that point to various servers, it should work fine to just `join` them directly.

**Comment by gmr** [comment]
True, but that won't work for bootstrapping against a DNS RR will it?

IE bootstrap-expect=3 and:

```
consul.domain.com. 300 IN A   8300 consul0.domain.com.
consul.domain.com. 300 IN A   8300 consul1.domain.com.
consul.domain.com. 300 IN A   8300 consul2.domain.com.
```

**Comment by gmr** [comment]
It looks like I wouldn't need to do SRV per se and more just add supporting a DNS RR to --join and --retry-join:

It appears that the resolution of DNS is handled inside the call on 
https://github.com/hashicorp/consul/blob/master/command/join.go#L57

The change would be to get all A records if a fqdn is passed in, and pass them in as if they were multiple arguments passed on the CLI.
