### ISSUE TITLE
Proposal: Treat DNS RR entries as multiple entries when joining a cluster

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul#1123]
This is a refinement of my previous issue (#1121).

I'd like to submit a PR that modifies https://github.com/hashicorp/consul/blob/master/consul/client.go#L185 to perform DNS resolution, returning all A records for the specified hostname and using the full list for joining. I believe this would allow for DNS to provide the discovery mechanism for bootstrapping a cluster.

So given a DNS RR such as:
```
consul.domain.com. 300 IN A   8300 192.168.1.1
consul.domain.com. 300 IN A   8300 192.168.1.2
consul.domain.com. 300 IN A   8300 192.168.1.3
```

And a command of ``consul agent -server --bootstrap-expect 3 --join consul.comain.com``, consul would be able to successfully bootstrap a cluster.

Would such a feature/pull-request be entertained?

I do something similar with etcd and SRV records:

I submit an AWS CloudFormation template that builds a stack of discovery CoreOS instances, adding them to Route53 in a DNS SRV RR and telling etcd to bootstrap by getting the addresses from Route53's SRV records. This way I do not have to carry around a static configuration of nodes to join when bootstrapping, which can be overly verbose with clusters of different sizes depending on the environment/VPC.

**Comment by armon** [comment]
@gmr This should be happening already! At the bottom of the stack, it ends here: https://github.com/hashicorp/memberlist/blob/master/memberlist.go#L156

**Comment by gmr** [comment]
Ugh my bad for not reading all the way through the code. Sorry for the noise.

**Comment by jason-riddle** [comment]
Just to clarify, does this happen with SRV records as well? Or only with A records?

**Comment by slackpad** [comment]
@jason-riddle looks like it's only using A records right now - I think it would need a few tweaks to work with SRV records.
