### ISSUE TITLE
Reverse Lookups to Recursor do not Resolve

### ISSUE THREAD

**Issue by mi-wood** [hashicorp/consul#1124]
Let's say I have node:
test.node.dc1.consul -> 10.4.0.2
and setting:
```
  "recursors": [
    "169.254.169.253" # Amazon provided
  ],
```
A records for .consul and recursed domains will resolve. PTR for IPs in consul will resolve, but I will get the following for any reverse lookup that should be recursed:
```
dig -x 216.58.219.238  @127.0.0.1

; <<>> DiG 9.8.1-P1 <<>> -x 216.58.219.238 @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15455
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;238.219.58.216.in-addr.arpa.	IN	PTR

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Jul 20 17:00:54 2015
;; MSG SIZE  rcvd: 45
```
The most I get in the log is: `2015/07/20 17:03:55 [DEBUG] dns: request for {238.219.58.216.in-addr.arpa. 12 1} (203.638µs)`

I've also tested this with 8.8.8.8 as the recursor. Hitting the authoritative directly resolves fine.

**Comment by armon** [comment]
Marked as bug, I think we aren't using upstream resolvers for PTR if we can't find the node.
