### ISSUE TITLE
Constant warning: skipping application of old log

### ISSUE THREAD

**Issue by fraenkel** [hashicorp/consul#1126]
We have noticed on our leader, we have the following snippet from the log. The cluster appears healthy but we are receiving the random error but the constant warning every minute.

We haven't been able to figure out what is causing this.

 2015/07/21 19:10:40 [WARN] raft: Skipping application of old log: 276
    2015/07/21 19:10:58 [INFO] agent.rpc: Accepted client: 127.0.0.1:37641
    2015/07/21 19:10:58 [ERR] agent.rpc: failed to decode request header: codec.decoder: Only encoded map or array can be decoded into a struct. (valueType: 2)
    2015/07/21 19:11:40 [WARN] raft: Skipping application of old log: 277
    2015/07/21 19:12:40 [WARN] raft: Skipping application of old log: 278
    2015/07/21 19:13:40 [WARN] raft: Skipping application of old log: 279
    2015/07/21 19:14:40 [WARN] raft: Skipping application of old log: 280
    2015/07/21 19:15:40 [WARN] raft: Skipping application of old log: 281
    2015/07/21 19:16:40 [WARN] raft: Skipping application of old log: 282
    2015/07/21 19:17:40 [WARN] raft: Skipping application of old log: 283
    2015/07/21 19:18:40 [WARN] raft: Skipping application of old log: 284
    2015/07/21 19:19:40 [WARN] raft: Skipping application of old log: 285
    2015/07/21 19:20:40 [WARN] raft: Skipping application of old log: 286
    2015/07/21 19:21:40 [WARN] raft: Skipping application of old log: 287
    2015/07/21 19:22:40 [WARN] raft: Skipping application of old log: 288
    2015/07/21 19:23:40 [WARN] raft: Skipping application of old log: 289
    2015/07/21 19:24:40 [WARN] raft: Skipping application of old log: 290

**Comment by armon** [comment]
@fraenkel This should go away, it can happen sometimes when a new leader takes over. Does this message persist forever?

**Comment by fraenkel** [comment]
@armon We have seen the Skipping message appear when the leadership changes.
The only time I have truly seen it go away was when we leave and join after rolling updates.
In theory, nothing should have changed.

Now that we have simplified our config and removed all the auto-join behavior, we haven't seen these messages for at least 1 day.

**Comment by systeminsightsbuild** [comment]
How long should it take to for these logs to go away? I am going 5 minutes now.

**Comment by systeminsightsbuild** [comment]
In our cluster the warning never ends
```
2016/03/11 07:15:06 [WARN] raft: Skipping application of old log: 371749
2016/03/11 07:15:07 [WARN] raft: Skipping application of old log: 371750
2016/03/11 07:15:10 [WARN] raft: Skipping application of old log: 371751
2016/03/11 07:15:11 [WARN] raft: Skipping application of old log: 371752
...
2016/03/12 12:17:47 [WARN] raft: Skipping application of old log: 420388
2016/03/12 12:17:50 [WARN] raft: Skipping application of old log: 420389
2016/03/12 12:17:51 [WARN] raft: Skipping application of old log: 420390
2016/03/12 12:17:52 [WARN] raft: Skipping application of old log: 420391
...
```

**Comment by WIZARD-CXY** [comment]
me too

**Comment by i0rek** [comment]
Closing this issue because I haven't heard it about it happening still. Feel free to create a new one if this is still the case.
