### ISSUE TITLE
add validation to the service-resolver subset filter

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#11281]
On config entry writes validate the [`Filter`](https://www.consul.io/docs/connect/config-entries/service-resolver#filter) field of `service-resolver` config entries to make sure they are actually valid [`go-bexpr`](https://github.com/hashicorp/go-bexpr) syntax.

This should be pretty easy and might just be sufficient to use `bexpr.CreateEvaluator(expression)` since invalid syntax will cause filter evaluation to usually fail with `Failed to create boolean expression evaluator`

**Comment by bisakhmondal** [comment]
Hi guys! I want to work on this issue.

If I understand correctly, we are expecting an additional syntax checking for every filter of the `ServiceResolverSubset` object, right?

https://github.com/hashicorp/consul/blob/daec73e76ca30d9d3e7e3a295041d4e4c7500cda/agent/structs/config_entry_discoverychain.go#L894-L912

Also, one thing I noticed, throughout the package we are checking emptyness of a map before iterating through it (Line 903). Just curious, has it been added intentionally for some sort of optimization (maybe `len` has less CPU instruction than `range`)?

Thanks!

**Comment by rboyer** [comment]
> Just curious, has it been added intentionally for some sort of optimization (maybe len has less CPU instruction than range)?

I think it's a harmless but completely unnecessary check. I think at the time I wrote that I possibly didn't recall if ranging a `nil` map would panic and guarded against that but never came back to double check if it's ok (it is).

**Comment by bisakhmondal** [comment]
Okay, sounds perfect. Thanks.
