### ISSUE TITLE
Consul KV returns  "No cluster leader" instead of key value

### ISSUE THREAD

**Issue by seeder** [hashicorp/consul#1129]
We have found that when consul cluster is without a leader, the K/V http call will return HTTP 200 "No cluster leader" when doing ?raw on a key instead of sending HTTP 50X :( , we also found that it is happy to send "rpc error" without setting correct HTTP code ( not 200 )

**Comment by armon** [comment]
Marked as enhancements. The status code situation is not great.

**Comment by i0rek** [comment]
This is fixed by now. Thanks for reporting!
