### ISSUE TITLE
Add "Tags" tab to gateways (just like exists for non-gateway services)

### ISSUE THREAD

**Issue by jkirschner-hashicorp** [hashicorp/consul#11322]
#### Feature Description

Consul allows specifying "[Tags](https://www.consul.io/docs/discovery/services#service)" for any service. However, the Consul UI only displays a "Tags" tab for standard services, not for gateways.

For this task, add the same tags that show up in a gateway service's instance listing:
![image](https://user-images.githubusercontent.com/85913323/137387050-717c6df9-d42d-421b-a6d3-0ce515db35e2.png)

... to a new "Tags" tab (when you click on a specific service instance) ...

![image](https://user-images.githubusercontent.com/85913323/137387128-84cbb13c-7646-411a-941d-ff34477235d1.png)

**Comment by jkirschner-hashicorp** [comment]
Hello Consul community members,

We would welcome a PR contributed by the community for this UI enhancement!

If you're interested, please comment here so anyone interested can stay informed.

**Getting started with Consul UI development**
To launch the UI in development mode, follow the directions in the [UI readme](https://github.com/hashicorp/consul/tree/main/ui/packages/consul-ui#installation).

When running the development app (make start), any changes you save in the website source files will be recompiled and reloaded in your browser pages pointed at the app (e.g., http://localhost:4200/ui/).

Please name your branch according to [these guidelines](https://github.com/hashicorp/consul/tree/main/ui/packages/consul-ui#branching) to ensure that the PR you submit triggers CI execution of the frontend test suite.

**Accessing a standard service's Tags tab**

1. Go to services in the left nav.
2. Click on a service that doesn't have a pill label for Ingress, Terminating, or Mesh Gateway.
3. Click on the Tags tab.

The Tags tab you add for gateway (ingress, terminating, mesh) services should work the same way (same steps to access, same data source, same design, etc).

**Comment by jkirschner-hashicorp** [comment]
Hi @chinmaym07,

Just checking in to see how things are going and whether you have any questions!

**Comment by chinmaym07** [comment]
Hey @jkirschner-hashicorp sorry for the delay here . 
I was occupied with some other commitments. I have created a PR & linked it with the issue . Please review.
