### ISSUE TITLE
reliability test

### ISSUE THREAD

**Issue by half-dead** [hashicorp/consul#1132]
We are considering to replace zookeeper with consul as our service discovery and configuration tool, so we need to run some reliability tests to make sure it won't cause any kind of crashing.

Our cluster size is over 500, nearly 1000 during rush hours.

Here are the things that we want to do:
1. monitor every node's living condition, see if there is any kind of flapping, and how frequent.
2. 50 QPS load test with service register/deregister, find out the max latency, and then 1k QPS.
3. same as 2nd with kv.
4. monitor cpu/disk io/network/memory status on every node.

Yet we haven't figure out how to measure the max latency(is it possible that we use the 'tags' attribute to store the registered time, then compare it to every node's current time at the exact time this service was synced) . Is there anyway to do this?

Any suggestion would be greatly appreciated.
Many thanks!

**Comment by armon** [comment]
@half-dead I recommend exporting the Consul telemetry (https://consul.io/docs/agent/telemetry.html) and using that to help monitor these various aspects of the system. Those will give pretty deep visibility into latency, flapping, network and resource utilization.

That said, doing 1K QPS of service registration is a rather strange use case for Consul, services typically don't flap that often. For the KV benchmarking take a look here: https://github.com/hashicorp/consul/tree/master/bench

**Comment by Kosta-Github** [comment]
Can you expose the telemetry data also via the HTTP API? Preferably as a stream sending the updates on the mentioned 10 secs interval...

**Comment by armon** [comment]
@Kosta-Github The telemetry cannot be exposed that way currently. It is really meant as a stream based "push" since Consul does not retain it, merely streaming it out to an external system. We could do something with web sockets and pushing of metrics, but it would be overly complex and not really the best approach.

**Comment by Kosta-Github** [comment]
Actually, I meant something like the stream based push. Maybe similar to the docker endpoint for container logs using a "TCP upgrade" for the connection: https://docs.docker.com/reference/api/docker_remote_api_v1.19/#get-container-logs

**Comment by half-dead** [comment]
@armon Some of the telemetry output I don't understand, do you have any documents?

**Comment by half-dead** [comment]
I have a question:
If we calls "/v1/agent/service/register" on a client, does it response immediately, or it waits that this service have synced to the majority of the servers and then response, or neither.

**Comment by ryanuber** [comment]
@half-dead the service registration from the agent HTTP endpoint will block until the registration has been committed in the Raft log. The response will always be 200 if the registration completes on the agent side, so the catalog sync is always best-effort and will be retried later on if needed.

**Comment by half-dead** [comment]
@ryanuber Are there any documents for the telemetry output?
And how can I measure the max latency when a new service registerd on one client, I mean, how long does it take to sync this service to all server nodes.
