### ISSUE TITLE
consul agent SerfHealth status is critical,register service status not update, this design is normal?

### ISSUE THREAD

**Issue by lindane** [hashicorp/consul#1133]
consul version 0.5.0

Clustered environment for three server, two agent.
server address: 192.168.2.100,192.168.2.101,192.168.2.102
agent address: 192.168.2.107(rhel64-mysql1),192.168.2.108(rhel64-mysql2)

1.Start consul, add to the cluster，as follows:
[root@rhel64-mysql1 ~]# consul members -rpc-addr=192.168.2.107:8400
Node           Address             Status  Type    Build  Protocol
rhel64-mysql1  192.168.2.107:8301  alive   client  0.5.0  2
rhel64-consul2   192.168.2.101:8301  alive   server  0.5.0  2
rhel64-consul1   192.168.2.100:8301  alive   server  0.5.0  2
rhel64-consul3   192.168.2.102:8301  alive   server  0.5.0  2
rhel64-mysql2  192.168.2.108:8301  alive   client  0.5.0  2

2.192.168.2.107,192.168.2.108 register 'mysql' service,‘mysql’ service and SerfHealth status is passing(192.168.2.107,192.168.2.108).

3.Kill consul agent for 192.168.2.107, 192.168.2.107 SerfHealth status is critical.'mysql' service status is passing.

4.192.168.2.107 'mysql' service stop,(ssh 192.168.2.107,Run the check script,return value is 2),/v1/health/service/mysql api return 'mysql' service status is passing.

issue: Kill consul agent for 192.168.2.107,SerfHealth status is critical,not run check script,'mysql' service status not update,status is panssing.This design is normal?192.168.2.107 SerfHealth status is critical,consul server should will 'mysql' service status update to Unknown?

**Comment by armon** [comment]
@lindane The health checks are run by the agent, so if the agent is killed it will be unable to run the mysql health check. The health of a service is transitively defined by the health of the node it is running on. So this is expected, the last known state of the mysql service was "passing", however the SerfHealth (e.g. agent / machine health) is "critical". That instance of mysql is thus considered unhealthy because the machine it is running on is unhealthy.

**Comment by nustiueudinastea** [comment]
@armon We were debating with our colleagues what would be the correct way to mark a consul service check in case the node disappears, and it seems to us that the most appropriate thing to do is to mark the service check as unknown(similar to Nagios behaviour). It avoids any confusions for users and it is the actual state of that check.

**Comment by raitech** [comment]
Hello!

@armon "The health of a service is transitively defined by the health of the node it is running on."

If service's health is transitively defined by the health of its node, why the services related to a 'critical' node aren't marked 'critical' (or 'unknown', as suggested) too?

I can see the same behavior with the 0.6.0 compilation, and it took me hours to detect it running Ansible contrib/inventory/consul_io.py script, that depends on the health of a service to tell if it is up or down - but don't check the health of the node itself.

Can I consider a mistake of that script to not check the node's health? (I'll do it by now for my current needs.)

Thank you, and a Happy New Year!

**Comment by armon** [comment]
@raitech The APIs and UI will show the last known status of the service health checks, e.g. they are not updated when the node is detected as having failed. However, DNS requests will not route to a service if the host is critical, and if you use the APIs with filter parameters `?passing=1` on endpoints that support it, then the filtering logic applies the transitive checks. Hope that helps!

**Comment by slackpad** [comment]
Closing this out - please email the list or re-open if you have any more questions.
