### ISSUE TITLE
Non RESTful calls in API

### ISSUE THREAD

**Issue by amouat** [hashicorp/consul#1134]
Hi,

I was just wondering about the `/v1/agent/check/deregister/<checkId>` endpoint (https://consul.io/docs/agent/http/agent.html#agent_check_deregister). It seems that it works via a normal GET request, which seems pretty non-RESTful to me. The major problem is that it is easy to hit such endpoints without realising you're about to change the system.

Was there a reason not to favour an API where services were deregistered by a DELETE request to a URL such as `/v1/agent/services/<checkid>`?

I feel like I'm missing something as I don't see any other issues about this.

**Comment by armon** [comment]
This is an unfortunate legacy hangover, which we are forced to support for the life of the V1 API. Not much to be said or done about it at this point.

**Comment by amouat** [comment]
Fair enough, feel free to close. I was just surprised not to find a mention of this elsewhere.

Couldn't you support both DELETE and /deregister though?

**Comment by armon** [comment]
We could, it would just add more complexity I feel.
