### ISSUE TITLE
Config Entry CAS for delete requests

### ISSUE THREAD

**Issue by nickethier** [hashicorp/consul#11372]
#### Feature Description

Consul Config Entries support supplying a modify index as the value for a `cas` parameter for update operations which if set only updates the entry if the current modify index matches the value. This enables isolated atomic updates of config entries. However these guarantees cannot be made with delete operations as they don't support a `cas` parameter.

#### Use Case(s)

The Consul API Gateway will update upstream service intentions to add and remove the gateway as a source when corresponding routes are created or deleted. In the deleted case, we need to remove the gateway from the intention's list of sources. If it is the only source then the intention should be deleted. However, we want to be sure the intention was not modified (ex. an additional source added) between the time it was read and deleted.

**Comment by boxofrad** [comment]
Hey @nickethier 👋🏻 Just a heads up that this feature has just been merged 🎉
