### ISSUE TITLE
Deregistering Service Doesn't Do Anything

### ISSUE THREAD

**Issue by saulshanabrook** [hashicorp/consul#1138]
So I have a bunch of services that I want to deregister. So I try the deregester API command:

```bash
$ http PUT '10.128.3.65:8500/v1/agent/service/deregister/birds'
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Mon, 27 Jul 2015 21:33:50 GMT
```

And in the `consul monitor -log-level trace` output in that host it shows it has recieved that command:

```
2015/07/27 21:37:11 [INFO] agent.rpc: Accepted client: 127.0.0.1:56106
2015/07/27 21:37:22 [DEBUG] agent: Service 'consul' in sync
2015/07/27 21:37:22 [INFO] agent: Deregistered service 'birds'
2015/07/27 21:37:22 [DEBUG] http: Request /v1/agent/service/deregister/birds (10.319249ms)
```

Except it still appears in the catalog:

```bash
$ http PUT '10.128.1.54:8500/v1/catalog/services'
HTTP/1.1 200 OK
Content-Length: 377
Content-Type: application/json
Date: Mon, 27 Jul 2015 21:38:24 GMT
X-Consul-Index: 22888
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0

{
    "birds": [
        "backend",
        "http"
    ],
    ...
```

**Comment by ryanuber** [comment]
Hey @saulshanabrook, are there multiple nodes in your cluster which provide the `birds` service? The catalog is a global view of the cluster and available services. If there are any nodes providing the `birds` service, then it will show up in catalog and health endpoint responses. If you deregister the service definitions from all of the agents, you should see the entry in the catalog go away.

**Comment by saulshanabrook** [comment]
Can I deregister it from all agents in one command? Or do I have to do that manually for each agent?

**Comment by majormoses** [comment]
@saulshanabrook I dont believe so with the catalog and agent api you must know which service a node/agent its registered on:
https://www.consul.io/docs/agent/http/agent.html
https://www.consul.io/docs/agent/http/catalog.html

what does `curl  -s -S 10.128.1.54:8500/v1/health/service/bird` look like?

Here is an example:
`curl -s -S http://10.60.1.76:8500/v1/health/service/account-service | jq .`
```json
[
  {
    "Node": {
      "Node": "ip-10-60-1-76.us-west-1.compute.internal",
      "Address": "10.60.1.76"
    },
    "Service": {
      "ID": "51f8bdad52e5:account_service-1:3213",
      "Service": "account-service",
      "Tags": null,
      "Address": "",
      "Port": 3213
    },
    "Checks": [
      {
        "Node": "ip-10-60-1-76.us-west-1.compute.internal",
        "CheckID": "service:51f8bdad52e5:account_service-1:3213",
        "Name": "Service 'account-service' check",
        "Status": "passing",
        "Notes": "",
        "Output": "HTTP/1.1 200 OK\r\nContent-Type: application/json;charset=utf-8\r\nCache-Control: no-cache\r\nX-Content-Type-Options: nosniff\r\nContent-Length: 93\r\n\r\n",
        "ServiceID": "51f8bdad52e5:account_service-1:3213",
        "ServiceName": "account-service"
      },
      {
        "Node": "ip-10-60-1-76.us-west-1.compute.internal",
        "CheckID": "serfHealth",
        "Name": "Serf Health Status",
        "Status": "passing",
        "Notes": "",
        "Output": "Agent alive and reachable",
        "ServiceID": "",
        "ServiceName": ""
      }
    ]
  }
]
```

to deregister you could do something like either of these:
* `curl -XPUT http://10.60.1.76/v1/agent/service/deregister/51f8bdad52e5:account_service-1:3213`
* `curl -XPUT http://10.60.1.19:8500/v1/catalog/deregister -d '{ "Datacenter": "dev", "Node": "ip-10-60-1-76.us-west-1.compute.internal", "ServiceID": 51f8bdad52e5:account_service-1:3213"}'`

**Comment by ryanuber** [comment]
It's not currently possible to deregister a service from many nodes in a single API call. If the service is expected to come and go, then normally the service registration/deregistration is coupled in some way to the life of the process (e.g. upstart or similar).

I'm going to close this out but feel free to comment if you need any further help.

**Comment by bhurlow** [comment]
@ryanuber thanks for clarifying here. So services cannot be deregistered from many nodes in a single call, is this the same for key/value pairs or no?

**Comment by ryanuber** [comment]
@bhurlow you can delete by prefix in the key/value store, so if your keys are nested under a common prefix that can be destroyed that would be the way to go.
