### ISSUE TITLE
[refactor] Use HTTP error-handling consistently across handlers

### ISSUE THREAD

**Issue by kisunji** [hashicorp/consul#11393]
In our handlers/endpoints we have many places where we explicitly write a status code header and a body message ([example](https://github.com/hashicorp/consul/blob/8f754aba141e6d914e1a36731f1e9c67002d2d99/agent/agent_endpoint.go#L613-L615)).

We also have custom error types like [`BadRequestError`](https://github.com/hashicorp/consul/blob/8f754aba141e6d914e1a36731f1e9c67002d2d99/agent/http.go#L55) which are propagated up from the handler and centrally handled in this [function](https://github.com/hashicorp/consul/blob/8f754aba141e6d914e1a36731f1e9c67002d2d99/agent/http.go#L435-L477).

Having two ways of doing things is a source of confusion and tech debt, especially in Go where error-handling becomes a pain point very quickly when you stray from `if err != nil { return err }`

Since our handler signatures are `func(resp, req) (interface{}, error)`, my vote goes towards idiomatic error handling (`return nil, err`) with defined HTTP error types. Developers working on handler logic should not be concerned about writing to response headers or body (unless there's some lower-level network handling required like streaming) and defer the handling to the HTTPServer middleware.

Further down, we could leverage Go's error-wrapping features for type/behaviour assertions so that we can define custom error types as required, fulfill an interface declared at our `consul/agent/http` layer like `HasStatusCode`, and confidently append error details in a call stack without worrying about breaking a type assertion or having to add a custom type to the top-level error multiplexing.

**Comment by dnephin** [comment]
Thanks for writing up this issue! Definitely agree it would be valuable to be consistent here.

I'd like to mention that this is also a problem for the HTTP response body (not just the status code). All of those handlers could write the response directly to `resp`, or they can return something as the first return value which will be JSON encoded.

It would definitely be a lot safer if the handlers had only one option, but there may be a few special cases  (like the monitor and metrics endpoints) where we need to stream a response.

To handle special cases, I think we might want a layered approach. Most endpoints implement an interface that doesn't give them direct access to the response, and we use an adapter to convert those to an interface  that does write things directly to a response. So each individual endpoint only has one option, but we still have the flexibility to do different things for endpoints that need to stream.

**Comment by Mathew-Estafanous** [comment]
Hey @dnephin, I’m thinking of trying to tackle this issue. I think I have general idea of what your suggesting with abstracting away the ability to directly write to ``resp``. I’m not quite sure what exactly how that abstraction would be built yet so do you think it would be fine to just go ahead and make changes to what @kisunji was suggesting? Later on I could try looking more into what you're suggesting.

**Comment by dnephin** [comment]
Hi @Mathew-Estafanous, I think that sounds good. This will be an area that I think we'll want to discuss quite a bit, so there may be lots of back-and-forth. I'd encourage you to open a draft PR early and get some early feedback to avoid going too far in any particular direction before we've had a chance to discuss. Thank you for looking into this issue!

**Comment by Mathew-Estafanous** [comment]
@kisunji I’m thinking about trying to finish up the rest of this issue, but I’m wondering if I should work on another issue until the rest of the team has had a chance to look over this.

**Comment by kisunji** [comment]
@Mathew-Estafanous I left a comment on your latest PR about refactoring (again) into a more general HTTP error type. It's a bit more open-ended so if you want to discuss how it might look, feel free to do that here or raise a PR (only if you have time and interest of course)

**Comment by Mathew-Estafanous** [comment]
> Out of scope for this PR but might be interesting for you to think about:
> 
> We have a bunch of custom error types now for common HTTP Status Codes - most of them have a `Reason string` field and a custom type assertion function in `http.go`. One downside of our approach is that any new status code we want to return requires the creation of a new error type and assertion func (as you've done with `EntityTooLargeError` in this PR)
> 
> Do you think we could refactor these into a more general HTTP error type?

@kisunji Ya I definitely noticed this since I had to create like 2 new error types and it could lead to some inconsistency. (ie. ``BadRequestError`` returns ``“Bad Request” + e.Reason`` while others return just the ``e.Reason``.)

There are 2 approaches that I can think of.

----
## 1st Approach

We could do a general HTTP type that contains the code and the reason (similar to ``CodeWithPayload``).
```go
type StatusCode struct {
    Code     int
    Reason string
}

func (s StatusCode) Error() string {
    return s.Reason
}
```
With this struct we’d just assert that the error is ``StatusCode`` within http.go and if it is we just use the Code and Reason to write to the response body. A benefit of this approach would mean we wouldn’t need to add a new error type for each new http status code. 

However, this approach is really just moving that responsibility (of defining the http status code) from the wrapper to the individual raw handlers.
```go
func (s *HTTPHandlers) FakeHandler(resp http.ResponseWriter, req *http.Request) (interface{}, error) {
     // Some code here...
    if err != nil {
        return nil, StatusCode{Code: http.StatusNotFound, Reason: “Ya...I can’t find it chief"}
    }
}
```

---
## 2nd Approach

Alternatively, we could try using Go’s error wrapping which would mean we won’t necessarily have to create a separate error type.
```go
type StatusError int

const (
	BadRequest StatusError = http.StatusBadRequest
	NotFound               = http.StatusNotFound
	Unauthorized = http.StatusUnauthorized
	Forbidden = http.StatusForbidden
	EntityTooLarge = http.StatusRequestEntityTooLarge
)

func (s StatusError) Error() string {
	switch s {
	case BadRequest:
		return "Bad Request"
	case NotFound:
		return "Not Found"
	case Unauthorized:
		return "Unauthorized"
	case Forbidden:
		return "Forbidden"
	case EntityTooLarge:
		return "Too Large"
	default:
		return "Internal Error"
	}
}
```

Then each handler will return a ‘regular’ error and wrap the ``StatusError`` with it.
```go
func (s *HTTPHandlers) FakeHandler(resp http.ResponseWriter, req *http.Request) (interface{}, error) {
	// Some code here...
	if err != nil {
		return nil, fmt.Errorf("%w: Ya...I can’t find it chief", NotFound)
	}
}
```

Now all the wrapper has to do is assert that the error is a ``StatusError`` then it can use the ``Error()`` for the reason and the actual error for the status code.
```go
if err, ok := err.(StatusError); ok {
     resp.WriteHeader(int(err))
     mt.Fprint(resp, err.Error())
}
```

This approach will still require that you create a new ``StatusError``, so it doesn’t completely remove the need to alter ``http.go``. However, it does simplify the process a little more.

**Comment by kisunji** [comment]
Ooh 1st approach is what I had in mind (I forgot about `CodeWithPayload` which isn't the most descriptive name 😆) but 2nd approach is interesting!

I think the wrapping in your example is backwards: `Ya...I can't find it chief` wraps `NotFound` which will fail the `err.(StatusError)` assertion.

It will work if we use `errors.Is`/`errors.As` but I think logically `NotFound` should be the outermost error layer and Go convention is to wrap left to right: `this message wraps: %w`.

**Comment by Mathew-Estafanous** [comment]
Oh ya whoops! I should have double checked my example code first. 😅 

I think something like this would work.
```go
var statusErr StatusError
if ok := errors.As(err, &statusErr); ok {
     resp.WriteHeader(int(statusErr))
     fmt.Fprint(resp, statusErr.Error())
}
```

> It will work if we use `errors.Is`/`errors.As` but I think logically `NotFound` should be the outermost error layer and Go convention is to wrap left to right: `this message wraps: %w`.

If I understand that correctly, then I think the change above would allow for it to remain ``%w: the error that is wrapped``. That way `NotFound` would stay as the outermost error layer.

**Comment by kisunji** [comment]
https://www.joeshaw.org/error-handling-in-go-http-applications/ This was an interesting read as well with similar "wrapping" but with sentinel errors instead of int-error hybrids.

`%w: the error that is wrapped` doesn't work because `%w` is the "inner error" that is wrapped:
```go
err := fmt.Errorf("%w: the error that is wrapped", NotFound)
err2 := errors.Unwrap(err)
fmt.Println(err2) 
// "not found"
```

So you might need some helper function to wrap an `error` with a `StatusError`.

But with that said, I think the first approach is the simplest (even at the cost of verbose) solution. I'm down to rename `CodeWithPayloadError` and remove `ContentType` since it doesn't seem that useful (and seems to be used incorrectly in some places).

You're welcome to brainstorm more elegant solutions though! It should be easy to use and hard to misuse.

PSA: I'll be away for vacation and won't respond for a bit

**Comment by Mathew-Estafanous** [comment]
Should I make it one large PR that changes how all error handling is or should it be  2/3 smaller PRs?

Also, ``CodeWithPayloadError`` does seem to be used incorrectly ins most cases; however, would it make sense to keep ContentType as an optional in the case that someone needs to return a json formatted error response?

If someone leaves ``ContentType`` as ``“”`` then the default ``text/plain`` will be used. Otherwise we use the provided content type.

**Comment by kisunji** [comment]
I think a small PR to start with would be good!

In most cases we want to return json formatted errors - I think some magic happens in https://github.com/hashicorp/consul/blob/c5d2bea92c244c65f62181cda1c1bf0eca9bca10/agent/http.go#L551-L586
where we default to `application/json` anyways and I don't think we have any valid use-case for wanting `text/plain`.

We should start with cleaning up the error handling here actually; if we can reduce the number of possible codepaths that an error can take it would help developers read the code more easily.

**Comment by Mathew-Estafanous** [comment]
> We should start with cleaning up the error handling here actually; if we can reduce the number of possible codepaths that an error can take it would help developers read the code more easily.

Ok sounds good. I’ll try to work on a PR for that as soon as I can. It might take me a little extra time since I’m starting to have less free time recently.

**Comment by kisunji** [comment]
I think leave `ContentType` alone for now; there may be other parts of the system using it but I'd like to make sure before removing.

No time pressure on you at all! We appreciate your contributions regardless.

**Comment by Mathew-Estafanous** [comment]
I found some time to hop back into this issue and I’m not too sure how I would shorted the codepath. 😅

It seems like that path can’t be shorted much more since we still need to look at ``ContentType`` as opposed to defaulting to json. Do you potentially have any ideas of how it would be shortened?

https://github.com/hashicorp/consul/blob/c5d2bea92c244c65f62181cda1c1bf0eca9bca10/agent/http.go#L551-L566
This path will handle errors based on whether it’s a ``CodeWithPayloadError`` or another type of error. Since we haven’t transitioned all the errors under one error type, I don’t think there is a way to unify this logic.

**Comment by kisunji** [comment]
Hey! Sorry I think I wasn't clear with my response to you.

I think we can either:
1. Identify valid uses of `"text/plain"`
2. Make a plaintext error type separate from `CodeWithPayloadError`
3. Replace usages of `CodeWithPayloadError` where `ContextType: "text/plain"` with the new type

OR:

1. Default `CodeWithPayloadError.ContentType` to `"application/json"` as you originally mentioned while allowing `"text/plain"` to override.

I think both are okay approaches!

One thing I found while poking around was that `handleErr` writes the `err.Error()` to the response body while `CodeWithPayloadError` writes the error message to `X-Consul-Reason` header (and not the body).

**Comment by kisunji** [comment]
Ah I figured out what's going on. There's endpoints where we have an error but still want to respond with data (not the error body itself) https://github.com/hashicorp/consul/blob/c5d2bea92c244c65f62181cda1c1bf0eca9bca10/agent/agent_endpoint.go#L1104

It looks like `CodeWithPayloadError` was designed to write errors to the header while allowing the body to still be a JSON representation of a service or health-check.

This means that `CodeWithPayloadError` is more accurately a `ResponseHeaderError` that has a specific use-case for some agent endpoints and we shouldn't reuse it as a general HTTP error.

We can instead make a new error type `HTTPError`/`StatusCodeError` with `Code` and `Reason` then replace all `NotFoundError` `BadRequestError` `UnauthorizedError` error types with a singular one that gets handled in one place.

Does that make sense?

**Comment by Mathew-Estafanous** [comment]
Ahh ok. That explains why it was writing to the response to the header.

Sounds good, I’ll try to start working on making the ``HTTPError`` type and transitioning the other errors.

**Comment by Mathew-Estafanous** [comment]
With the most recent PR being merged (soon), does this mean this issue can be closed or is there more to be done?

**Comment by kisunji** [comment]
There's a few places where we manually write errors to the header that I *hope* we can replace with the new types. But that could be its own spin-off issue 👍

**Comment by kisunji** [comment]
Will close after I merge both OSS and Enterprise PRs
