### ISSUE TITLE
When browsing topology view get error="context canceled" in Consul server logs

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#11407]
#### Overview of the Issue

When browsing topology view on Consul 1.10.3 occasionally (but pretty often, like click around for a couple seconds and you'll see them) get logs:

```
2021-10-24T23:02:27.511Z [INFO]  agent.http: Request cancelled: method=GET url=/v1/health/service/frontend?dc=dc1&index=22064 from=10.0.2.2:61163 error="context canceled"
2021-10-24T23:02:31.199Z [INFO]  agent.http: Request cancelled: method=GET url=/v1/health/service/backend?dc=dc1&index=22063 from=10.0.2.2:61161 error="context canceled"
2021-10-24T23:02:59.334Z [INFO]  agent.http: Request cancelled: method=GET url=/v1/health/service/frontend?dc=dc1&index=22064 from=10.0.2.2:61237 error="context canceled"
```

#### Reproduction Steps

1. Run consul server 1.10.3. Only one instance.
1. Set up a couple services
1. Browse the topology view, clicking back and forth
1. Will get errors in console that correspond to the server error logs
    ![image](https://user-images.githubusercontent.com/1034429/138616904-d1f27f10-76b3-4984-b21c-e47ef0507aee.png)

Weirdly I only see the `/v1/health` errors logged but these requests (`http://localhost:8500/v1/connect/intentions?dc=dc1&index=15736&filter=SourceName%20%3D%3D%20%22ingress-gateway%22%20or%20DestinationName%20%3D%3D%20%22ingress-gateway%22%20or%20SourceName%20%3D%3D%20%22*%22%20or%20DestinationName%20%3D%3D%20%22*%22`) were also being cancelled (see screenshot) but they don't show up in the logs

I'm not sure who's doing the cancelling here.

**Comment by lkysow** [comment]
Sure I can close. @dnephin one thing to note is that it looks like some endpoints aren't logging. e.g. `http://localhost:8500/v1/connect/intentions?dc=dc1&index=15736` didn't log.

**Comment by dnephin** [comment]
That is expected. Streaming is sadly only used for a single endpoint `service/health`, so all other requests will not have the new behaviour and will consume resources until the timeout (instead of when the request is cancelled).

**Comment by lkysow** [comment]
Gotcha, thanks for explaining!

**Comment by lkysow** [comment]
> It can be important to see these cancellation sometimes

I'm looking at this again and I'm not sure we shouldn't put these into debug. Because you're getting so many of these when just using the UI normally then I think they lose their meaning.

Or maybe is it possible to not log if the referrer is the UI somehow?
