### ISSUE TITLE
Add additional Envoy consecutive_5xx outlier ejection configuration

### ISSUE THREAD

**Issue by agrahamlincoln** [hashicorp/consul#11422]
#### Feature Description

**Background:**
Consul provides upstream configuration [`passive_health_check`](https://www.consul.io/docs/connect/proxies/envoy#passive_health_check) to allow a user to configure Envoy's outlier ejection `interval` and `consecutive_5xx` settings. [[Envoy Outlier Detection Documentation]](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto#envoy-v3-api-field-config-cluster-v3-outlierdetection-consecutive-5xx)

**The Feature:** Add additional configuration parameters to `passive_health_check` for other Envoy outlier ejection settings. Specifically `enforcing_consecutive_5xx` to allow users to disable/slow-down outlier ejection for consecutive_5xx 

#### Use Case(s)

In our use-case, we are connecting nginx (running on VMs) to proxy components in K8S. These "proxy" components are expected to respond to the user with 5xx if that upstream proxy component receives 5xx responses from it's upstream. ejecting the proxy component from our nginx sidecar can cause service outages for all users if one user somehow creates a traffic pattern that results in 5xx responses.

`[VM: nginx --> consul-sidecar-nginx ] ---envoy tunnel---> [K8s: consul-sidecar-proxy --> http-proxy]`

In this use-case, we want to disable outlier ejection so that our proxies are not ejected from the nginx envoy sidecar when it responds to the user with 5xx responses.

more specifically, the proxy we're using is part of a [jupyterhub](https://zero-to-jupyterhub.readthedocs.io/en/latest/) service. Users are able to generate 5xx responses in the upstream proxy by writing "bad" jupyter notebooks that cause 5xx errors to be sent back to the user in response. We want these users to get their 5xx responses, instead of receiving only a few and then causing the proxy to be ejected for all other users of jupyterhub.

**Comment by lkysow** [comment]
Hi Graham, I know this isn't exactly what you're asking for (to configure `enforcing_consecutive_5xx`) but just wondering if you want to simply disable outlier detection whether you can do something like:

```hcl
Kind = "service-defaults"
Name = "nginx"
Protocol = "http"
UpstreamConfig {
  Defaults {
    PassiveHealthCheck {
      MaxFailures = 4294967295 # max 32 bit unsigned int
    }
  }
}
```
