### ISSUE TITLE
DNS resolver does not set NXDOMAIN code if all service instances are unhealthy

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#1142]
We check if there are no service instances in the DNS parser (https://github.com/hashicorp/consul/blob/master/command/agent/dns.go#L482) before we do the filtering on health (https://github.com/hashicorp/consul/blob/master/command/agent/dns.go#L499).

This means we properly set the response code to `NXDOMAIN` if there are no instances, but we respond with no answers with `NOERROR` if all the instances are being filtered out. This should also be `NXDOMAIN` to avoid confusing recursive resolvers.

**Comment by ryanbreen** [comment]
Fixed via GH-1143.
