### ISSUE TITLE
Connect leaf certs issued from Vault CA don't contain full chain

### ISSUE THREAD

**Issue by krarey** [hashicorp/consul#11448]
#### Overview of the Issue

When issuing a leaf certificate for a service identity or auto-encrypt agent from a Vault CA, Consul builds the following certificate chain:
```
leaf cert +
issuing CA
```
https://github.com/hashicorp/consul/blob/977be7749397d4fb81eb173f54608f1bd7caf633/agent/connect/ca/provider_vault.go#L441-L462

In environments with more than one subordinate CA (i.e. the issuing intermediate was, itself, issued from another intermediate), this breaks the certificate chain, unless the second-tier intermediate is explicitly trusted on the host.

In stead of using the returned `issuing_ca` key, it would be ideal for Consul to use the `ca_chain` key from Vault's response, which contains a list of every CA certificate leading back to the root.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Set up a Vault environment with three PKI mounts:
1.1. Root CA
1.2 Intermediate CA A (Issuer = Root CA)
1.3. Intermediate CA B (Un-configured - used as the Consul Issuing CA)
2. Configure Consul to use Vault as its Connect PKI source.
```json
{
	"Provider": "vault",
	"Config": {
		"Address": "<Vault Addr>",
		"IntermediateCertTTL": "8760h",
		"IntermediatePKIPath": "<Intermediate CA B Mount>",
		"LeafCertTTL": "72h",
		"PrivateKeyBits": "2048",
		"PrivateKeyType": "rsa",
		"RootPKIPath": "<Intermediate CA A Mount>",
		"RotationPeriod": "2160h",
		"Token": "<...>"
	},
}
```
3. Check the cert chain returned for an issued mTLS or auto_encrypt agent certificate.

**Comment by rdxmb** [comment]
I have the problem that the consul-server-cert does not contain the the Root CA, but only the intermediate CA. Should this be fixed? 

crosslink: https://github.com/hashicorp/consul/issues/12386#issuecomment-1792528206
