### ISSUE TITLE
Server agent restarted as client agent does not get removed from peer set

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#1144]
Current if an agent joins as a server it will be added to the replication group automatically. If it is restarted as a client, it is not removed and could cause availability issues.

**Comment by i0rek** [comment]
I started a cluster with 3 servers, killed one of them and restarted as a client:

```
$ consul operator raft list-peers
Node  ID                                    Address          State     Voter  RaftProtocol
s1    a374994d-1689-141a-b166-10fcf3b57719  127.0.0.1:8101   leader    true   3
s3    5f701d85-a91d-318a-7fbc-2c4e738a8200  127.0.0.1:10006  follower  true   3
```

s2 was in this list before, but no longer is. As far as I understand, this bug is solved.
