### ISSUE TITLE
Option to force s3 path style on snapshot agent config

### ISSUE THREAD

**Issue by chihebeddine** [hashicorp/consul#11473]
#### Feature Description

We are planning to use the enterprise snapshot feature to backup consul to Minio.
Currently, the config does not have an option to force s3 path style:

[consul-s3-storage-options](https://www.consul.io/commands/snapshot/agent#s3-storage-options)

instead of backing up to **BUCKET.MINIO_URL**, it should backup to **MINIO_URL/BUCKET**

For informatin, this option exists in vault:

[vault-s3-force-path-option](https://www.vaultproject.io/docs/configuration/storage/s3#s3_force_path_style)

#### Use Case(s)

Snapshot agent to generic s3

**Comment by Amier3** [comment]
Hey @chihebeddine 

First off, I see this is your first issue so welcome to the Hashicorp community! 💯 

This would be a solid enhancement, but i'm curious to know if you've tried [virtual-host style requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html) which are supported by [minio](https://github.com/minio/minio/tree/master/docs/config#domain).

AWS has some [plans](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) to deprecate path style all-together ( although they aren't very clear on when ), so the longevity of this change would be in question.

**Comment by iFrozenPhoenix** [comment]
@Amier3 I would also think that this would be a valuable enhancement for consul as it would ease the setup. Virtual host style requests rely on additional dns configuration or in case of consul maybe on consuls capabilities itself.
Most of the current S3 compatible storage backends default to path style.

**Comment by Amier3** [comment]
@iFrozenPhoenix 
That's a good point, off the top of my head I don't think virtual host style would require any extra configuration on consuls' end, but it would require extra configuration on AWS's side. 

I don't think we'll be able to get to this in the near future, but I added the 'good-first-issue' label for anyone that wanted to pick this up and make a PR for it. @iFrozenPhoenix , if you'd like to pick it up I can point you to the relevant file and our contributing guide 👍

**Comment by iFrozenPhoenix** [comment]
@Amier3 if you could point me to the mentioned references I would try to take this task.

**Comment by nathancoleman** [comment]
Closing as this was addressed in #14385
