### ISSUE TITLE
Can web ui be accessable from other nodes?

### ISSUE THREAD

**Issue by yeasy** [hashicorp/consul#1148]
Seems I can only access the web ui on the node with the web ui.
When access from other nodes, the connection is refused.

**Comment by james147** [comment]
By default consul is unauthenticated and so only binds to localhost. If you
want to access the web ui from another host you have to tell it to bind to
another address (see [1] and [2]). Bear in mind that this exposes the whole
api to that interface so you may want to enable the acls as well.
Alternatively you can proxy the api/webui through a web server such as
nginx or apache.


[1] https://www.consul.io/docs/agent/options.html#addresses
[2] https://www.consul.io/docs/agent/options.html#_client

**Comment by ryanbreen** [comment]
Great answer, James. Thanks!

**Comment by yeasy** [comment]
How can we let consul bind to validated local ip address automatically without telling the exact value.

0.0.0.0 seems not work.

**Comment by james147** [comment]
I am using the following without issue:
{
  "addresses": {
    "http": "0.0.0.0"
  }
}

After you start consul what is the output of `lsof -nPi :8500` (assuming
you are on linux)?

**Comment by yeasy** [comment]
Great, how can i add this paramter as cli options?
consul agent -address 0.0.0.0?

**Comment by james147** [comment]
For the cli I think you want the `-http-addr` or `-client` options, though I have not tried them.

**Comment by yeasy** [comment]
Ok, i will try. I want the consul-ui be accessed from outside, by automatically detecting the public IP on the host.
thanks!

**Comment by james147** [comment]
I would be careful with doing it on a public ip, if you do not have acls enabled then you are exposing the whole api to the public unauthenticated. I would either enable acls on the cluster, or setup a proxy to do the authentication and only expose the proxy to the public.

**Comment by yeasy** [comment]
Yes, i am using a proxy.
Thanks for the reminder.
