### ISSUE TITLE
dns lookup fails for nodes registered with their FQDN

### ISSUE THREAD

**Issue by mfriedemann** [hashicorp/consul#1149]
Hey,

I want to report an issue with DNS node queries that arises when nodes register themselves with their FQDN, as is done for example in https://github.com/accumulo/docker-accumulo. In that setup, the nodes use a domain part of node.docker-accumulo.local, the zookeeper node would then be called zookeeper.node.docker-accumulo.local (and it would register itself with the consul under that node name).
The issue is that a dns query for the FQDN "zookeeper.node.docker-accumulo.local" strips off the domain and datacenter part, then identifies the query as a node query, and ends up looking for a node named "zookeeper", which doesn't exist.
If, instead, the query is modified to ask for "zookeeper.node.docker-accumulo.local.node.docker-accumulo.local" (notice the double "node.docker-accumulo.local"), it will again strip off domain, datacenter and "node" and arrive at the node name "zookeeper.node.docker-accumulo.local" which it finds and for which it reports the IP.

I currently work around this by specifying a -node argument with just the hostname part of the FQDNs, which ends up working fine, but it would be good if the internal node lookup would check against the case where the node is actually registered under that FQDN.

Thanks.

**Comment by tilgovi** [comment]
:+1: `os.Hostname()` is the default node name and that returns the FQDN. I was expecting that I could provide `node.dc1.consul` as the domain of my DHCP and that my node names would be resolvable in Consul, but alas.

**Comment by slackpad** [comment]
Originally thinking that we'd want to check for this at agent startup but that's going to be tricky. This hasn't been a common issue and you figured out to just include the base hostname, which is the right way to go.
