### ISSUE TITLE
A typo spotted in security acl-rules doc page

### ISSUE THREAD

**Issue by liugang-sd** [hashicorp/consul#11518]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
https://www.consul.io/docs/security/acl/acl-rules

github: consul/website/content/docs/security/acl/acl-rules.mdx

"Each team or business unit would use tokesn based on polcies that enforce several rules, for example:"

The word 'tokesn' and 'polcies' is misspelled.

please fix typo.

**Comment by blake** [comment]
Hi @liugang-sd, thanks for reporting these typos. They were fixed on 11/17/21 with PR #11590.
