### ISSUE TITLE
Question: When server becomes client - peers stays as it was - bug or feature ? 

### ISSUE THREAD

**Issue by sielaq** [hashicorp/consul#1153]
Hi

We had a funny incident. We used to have  3  servers and few clients for a quite some time - everything works fine. Suddenly one of the client became server for a while, due to human error.
Of course ``peers++`` has been change in cluster. When mistake was corrected back (server become client again) peers was unchanged  - even when ``consul members`` says that there are 3 servers (and no host is missing - because the left server is hidden now behind client)

of course leader election was not working that time, 
the cure was to set it back to server and do `consul force-leave` , and set it back to client.

Question: is it by design, or should this "special use case" (when server becomes client)
remove from peers entry to bring back leader election ?

**Comment by slackpad** [comment]
Hi @sielaq this is a bug that came up in another thread recently and is being tracked at #1144 - thanks for the report!
