### ISSUE TITLE
Namespace dropdown doesn't stay reflective of the namespace

### ISSUE THREAD

**Issue by chrisjohnson** [hashicorp/consul#11553]
### Overview of the Issue

When I navigate to https://consul.service.consul/ the namespace dropdown usually shows the namespace I was looking at last, however the URL doesn't reflect this namespace and none of the services or ACLs shown are from that namespace.

Once I select the namespace dropdown and then click on the namespace that the dropdown already showed as reflected, the URL updates (I see `~namespace-foo` in the url) and the lists of services and ACLs update to reflect the selected namespace.

In short, it seems like the *dropdown* is remembering the namespace I was looking at last, but nothing else does. 

### Describe the solution you'd like

Either the dropdown should always reflect the current *actually selected* namespace (which is almost always default when I first navigate to the UI) or the rest of the UI should apply the namespace filter and redirect you to the correct URL when you first land there.

### Consul Version

1.9.7+ent

If this is a known bug that has a known fix after 1.9.7 please point me to the issue/PR where it was resolved, I looked but couldn't find it.

**Comment by johncowen** [comment]
Hey Chris,

Could you let me know if you have a token specified and if so does that token 'belong' to the default namespace or a non default namespace?

In the meantime, let me check that version you are using. I know that lately we've changed how that namespace menu works slightly (it no longer stores any namespace values in your browser between sessions for example).

**Comment by chrisjohnson** [comment]
The token I'm logged in with is the bootstrap token which is in the default namespace as far as I can tell. The dropdown seems to follow whatever I last selected in the dropdown the last time I was in the UI.

I wouldn't be surprised if this was a resolved bug with the latest version(s), I just wanted to make sure we documented it as it's been following us for quite some time / several versions

**Comment by johncowen** [comment]
Thanks Chris, yeah so there have definitely been changes around there lately. There 'could' be a bug on 1.9 I'll need triple check. We definitely removed the 'save you last namespace in localStorage' thing which is what is remembering your last namespace (and what it did since we added namespaces up until now).

Thanks for the extra info, I'll look into it from here and come back here with info from my side for an FYI (or potentially a bug fix on 1.9.x) 👍

**Comment by johncowen** [comment]
Does seem to be a bug with 1.19x

**Comment by johncowen** [comment]
Hey @chrisjohnson 

Just a quick fyi that there's hopefully a fix up for this ^. Just to share the only way I could reproduce this reliably was to create a namespace via the UI and without then manually refreshing the page, play with the namespace menu. As soon as I had refreshed the UI again I couldn't reproduce. With this in mind, the bug and fix I made also made sense. Just thought I'd share 👍

**Comment by chrisjohnson** [comment]
Is there a scheduled 1.9.x release of this change or timeline I can look at
to know when I can use a new version?

**Comment by msiege2** [comment]
Hi, @chrisjohnson.  Currently the Consul team does not provide dates for patch releases in advance, however we attempt to stick to a 1-2 month timeframe between patch releases.  With that schedule in mind, our next patch release should be sometime in early to mid-January.

I hope this helps your planning.
