### ISSUE TITLE
Use OutgoingTLSWrapper for HTTP checks

### ISSUE THREAD

**Issue by coderanger** [hashicorp/consul#1156]
Would be nice to (optionally?) support the same TLS verification logic for HTTPS service checks as is used for other TLS connections. Specifically this comes up when using either an IP or localhost for a service check, but the certificate has some real public hostname on it.

**Comment by ryanuber** [comment]
Agreed, having the option to require verification or not would be a useful feature. Tagged as an enhancement!

**Comment by jlandure** [comment]
:+1:

**Comment by cvvs** [comment]
I have a similar problem, but we have to validate certs created with our private CA.

Would something like this work? https://github.com/cvvs/consul/commit/737f4c28df28fffca43c487a5fb7e106b88dd65c

**Comment by slackpad** [comment]
I think https://github.com/hashicorp/consul/issues/3364 gets pretty close to this (and checks can skip verify as well).
