### ISSUE TITLE
Should error on validation when upstream port the same as envoy public listener

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#11571]
#### Overview of the Issue

This registration doesn't error:

```hcl
service {
  name = "frontend"
  port = 6060
  connect {
    sidecar_service {
      port = 20000
      proxy {
        upstreams = [
          {
            destination_name = "backend"
            local_bind_port  = 20000
          }
        ]
      }
    }
  }
}
```

But it results in listeners:

```json
{
 "listener_statuses": [
  {
   "name": "public_listener:0.0.0.0:20000",
   "local_address": {
    "socket_address": {
     "address": "0.0.0.0",
     "port_value": 20000
    }
   }
  },
  {
   "name": "backend:127.0.0.1:20000",
   "local_address": {
    "socket_address": {
     "address": "127.0.0.1",
     "port_value": 20000
    }
   }
  }
 ]
}
```

Such that in one reproduction upstream requests couldn't be made.

When I tried to reproduce, I got hundreds of these errors in the logs, 20/second:

```
2021-11-15T00:21:43.511Z [ERROR] agent.envoy.xds: got error response from envoy proxy: service_id=backend-sidecar-proxy typeUrl=type.googleapis.com/envoy.config.listener.v3.Listener xdsVersion=v3 nonce=00001ed2 error="rpc error: code = Internal desc = Error adding/updating listener(s) frontend:127.0.0.1:21000: cannot bind '127.0.0.1:21000': Address already in use
"
```

But I never saw both listeners bound to the same port in the xds config, so not sure what the difference between my repro and the situation I saw in the wild.

Regardless if it's possibly then I think we could safely error out on service registration in this case?

### Consul info for both Client and Server

Consul 1.10.3

**Comment by jkirschner-hashicorp** [comment]
Tangentially related issue: https://github.com/hashicorp/consul/issues/8254 (Envoy proxies can be assigned overlapping ports)

**Comment by lkysow** [comment]
Closing this after looking back into it. The only situation where this can be an issue is if the final address+port of a service in the catalog is the same as the address+port of an upstream listener. This will only happen when running 2+ services on the same machine locally for testing, since otherwise the upstream listener will always be on `localhost` and the address of the service in the catalog will be the public IP for the service, not localhost.

In addition, this only occurs if you hardcode a port for the proxy which I was only doing to avoid #8254. Since that's now resolved I think this is too much of an edge case to bother fixing.
