### ISSUE TITLE
Health service nodes filter by states

### ISSUE THREAD

**Issue by marenzo** [hashicorp/consul#1164]
Currently, the endpoint "/v1/health/service/{service}" only supports one type of filtering - passing or not.
I'd like to be able to do a wider filtering, by all of the possible health types - critical, warning, etc..
For example: Having service X, which having a node that one of it tests is failing (in critical state) - "/v1/health/service/X?critical" should show me the critical node(s)

This is possible to implement ofc in the client, but I think this is a good feature that the api should support.

**Comment by marenzo** [comment]
After thinking a while, and sending the PR, maybe what I really want is the ability filtering only by passing/failing.
Instead of specifying what state, just asking for either passing or failing (failing means that at least one test is not passing).

WDYT?

**Comment by slackpad** [comment]
Hi @marenzo can you give a little more information about your intended use case? There are a lot of ways this could be done, but I think I'd want to understand what you are trying to do before we add features to Consul itself.

**Comment by kamaradclimber** [comment]
A use case for that would be to debug dead services on healthy servers.

For instance, if you have an elasticsearch cluster, some instances are dead (or reporting a unhealthy status which can happen in case of network partition), you want to go these instance servers and fix the issue.
If consul does list the unhealthy servers, that's hard to do.

**Comment by doublerebel** [comment]
Related: #356 `/v1/health/nodes` endpoint

**Comment by i0rek** [comment]
This issues has been open for quite some time and we didn't get to do this. Since we are still very busy I don't think we will ever get to do this ourselves. Which is why I am closing it now. If you want to provide a PR I would be happy to review and give feedback.
