### ISSUE TITLE
The demo docker-compose-cluster doesn't work

### ISSUE THREAD

**Issue by mircea-cm** [hashicorp/consul#11664]
#### The demo docker-compose-cluster doesn't work

Running the docker-compose.yml provided doesn't work

#### Reproduction Steps

1. run demo/docker-compose-cluster/docker-compose.yml

I keep getting the error **No private IPv4 address found**

**Comment by Amier3** [comment]
Hey @mircea-cm 

First off, welcome to the hashicorp community! 

We've broken out that demo directory into it's own project, linked [here](https://github.com/hashicorp/demo-consul-101) . The demo directory in this project is in the process of being deprecated ( see the linked issue above )
