### ISSUE TITLE
Unexpected response code: 403 (ACL not found)

### ISSUE THREAD

**Issue by hhandy** [hashicorp/consul#11674]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.
when my consul update from 1.4.4 to 1.6.9, I do the acl migrate reference this page https://www.consul.io/docs/upgrading/instructions/upgrade-to-1-6-x
first upgrage my slave datacenter, and my primay datacenter has not upgrage
I only changed the acl configuration file, but my slave datacenter not work

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. updata consul from 1.4.4 to 1.6.9
2. modify the slave datacenter acl configuration file
Before the change
`{
  "primary_datacenter": "dc1",
  "acl_datacenter": "dc2",
  "acl_default_policy": "deny",
  "acl_down_policy": "extend-cache",
  "acl_ttl": "360m",
  "acl_token": "111"
}
`
After the chage
{
  "primary_datacenter": "dc1",
  "acl": {
    "enabled": true,
    "default_policy": "deny",
    "down_policy": "extend-cache",
    "enable_token_replication": true,
    "enable_token_persistence": true,
    "token_ttl": "360m",
    "tokens": {
      "default": "111",
      "replication": "222"
    }
  }
}

3. restart the slave datacenter

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>
![image](https://user-images.githubusercontent.com/44293767/143675601-7be6bb81-22aa-4ea3-92c9-ab60a7244023.png)

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.
![image](https://user-images.githubusercontent.com/44293767/143675911-bf5f823d-917a-42ea-a061-be712f715f0b.png)

**Comment by hhandy** [comment]
i found my acl replication not working, but i can't find something worng in my acl configuration
![image](https://user-images.githubusercontent.com/44293767/143974029-674b74c6-8ddc-4794-ba9a-b993bdbd459f.png)

**Comment by Amier3** [comment]
@hhandy 

Sorry for the delayed response! Are you still experiencing this issue?

**Comment by jkirschner-hashicorp** [comment]
I'm marking this issue closed for now due to inactivity. @hhandy : Feel free to re-open if you are still experiencing this issue, or whether there are any UX improvements we could've made to make this easier to troubleshoot. We have a separate issue open to improve the "ACL not found" error to be more descriptive in the future.
