### ISSUE TITLE
"consul tls ca create" creates a world-readable private key

### ISSUE THREAD

**Issue by marco-m** [hashicorp/consul#11741]
#### Overview of the Issue

Hello,

`consul tls ca create` creates a private key file that is world-readable.

Instead, it should create it with permissions `0600`, to reduce the possibility of information disclosure (and subsequent elevation of privilege).

#### Details

What I did

```
$ consul tls ca create
==> Saved consul-agent-ca.pem
==> Saved consul-agent-ca-key.pem
```

What I was expecting:

```
$ ls -l consul-agent-ca*
-rw-------  consul-agent-ca-key.pem
-rw-r--r--  consul-agent-ca.pem
```

What I got instead:

```
$ ls -l consul-agent-ca*
-rw-r--r--  consul-agent-ca-key.pem
-rw-r--r--  consul-agent-ca.pem
```

Same happens for non-CA certificates, for example:

```
$ consul tls cert create -server
...
==> Using consul-agent-ca.pem and consul-agent-ca-key.pem
==> Saved dc1-server-consul-0.pem
==> Saved dc1-server-consul-0-key.pem
```

and

```
$ ls -l dc1-server-consul-0*
-rw-r--r--  dc1-server-consul-0-key.pem
-rw-r--r--  dc1-server-consul-0.pem
```

### Operating system and Environment details

macOS. I would expect the same on Linux and Unix-like systems.

**Comment by Amier3** [comment]
Hey @marco-m 

Thanks for letting us know about this! We'll keep an eye on this issue to get this fixed, but if you ( or anyone else that comes across this ) is willing, we'd happily welcome a PR for this! 

The relevant file that'd have to be changed can be found [here](https://github.com/hashicorp/consul/blob/main/command/tls/ca/create/tls_ca_create.go#L86-L89) and i'll also link our contributing doc [here](https://github.com/hashicorp/consul/blob/main/.github/CONTRIBUTING.md)
