### ISSUE TITLE
Ingress gateway metrics shown when they shouldn't be

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#11743]
#### Overview of the Issue

Ingress gateway metrics should not be shown. But if you navigate to an ingress gateway _through_ the topology view, its metrics will be shown.

Consul 1.10.4

In this video you can see that on initial load, no metrics are shown, but if you navigate to another service in the topology and then back to the ingress gateway, suddenly metrics appear. I'm pretty sure they're also not the ingress gateway metrics but actually the metrics from the frontend service but I'm not 100% sure about that.

https://user-images.githubusercontent.com/1034429/144783798-b40a2929-2ab2-4880-8ed6-1dea5447e572.mp4

**Comment by kaxcode** [comment]
Unable to replicate issue in v1.10.x and 1.11.x
