### ISSUE TITLE
consul agent logs not works properly on windows (empty file)

### ISSUE THREAD

**Issue by inorangestylee** [hashicorp/consul#11773]
#### Overview of the Issue

after start consul agent (as windows service) it creates an empty log file and not appends it with log messages.
Directory ACL checked. While in work consul agent obtain file handler (cant delete or append anything in logfile).

#### Reproduction Steps

Config:
```
...
    "log_level": "INFO",
    "log_file": "c:\\consul\\logs\\",
    "log_rotate_duration": "24h",
    "log_rotate_max_files": 14,
...
```

Steps to reproduce this issue, eg:

1. Start consul agent as windows service `c:\consul\consul.exe agent -config-file c:\consul\config\config.json` or `c:\consul\consul.exe agent -config-file c:\consul\config\config.json -log-file c:\consul\logs\`
1. Start `.\consul.exe monitor -log-level=INFO`
1. View log and compare monitor stdout

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
PS C:\consul> .\consul.exe info
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 2
build:
        prerelease =
        revision = a4f67ec2
        version = 1.8.15
consul:
        acl = enabled
        known_servers = 5
        server = false
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 56
        max_procs = 8
        os = windows
        version = go1.14.15
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 174
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 222538
        members = 324
        query_queue = 0
        query_time = 194
```

</details>

### Operating system and Environment details

OS Name:                   Microsoft Windows Server 2016 Standard (x64)
OS Version:                10.0.14393 N/A Build 14393

**Comment by kopetersen** [comment]
I have the same problem. I found a workaround though.
It´s more or less the same thing NSSM does when you use that.

If I install the service like below, I get a working log. So I guess the stream redirection is not working properly for Consul
`cmd.exe /C C:\Consul\consul.exe agent -config-dir=C:\Consul\config 2>&1`

On a sidenote, I have Nomad running on the same servers, and that logs just fine.

Consul info
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 2
        services = 3
build:
        prerelease =
        revision = c976ffd2
        version = 1.10.3
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 58
        max_procs = 2
        os = windows
        version = go1.16.7
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1892
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 96996
        members = 34
        query_queue = 0
        query_time = 2
```

**Operating system and Environment details**
OS Name: Microsoft Windows Server 2019 Standard (x64)
OS Version: 1809 Build 17763.2366

**Comment by kisunji** [comment]
1. What do you mean when you say "Start consul agent as windows service"? Are you using a service manager?
2. Does consul work as expected (without the log writes)?
3. Do you see any ERRORs in Consul's stdout?

I tried running the same commands on `cmd` as a local user in Windows 10 (using Consul 1.10.4) and logging to files was working as expected. The fact that the log file is being held by the process sounds strange.

**Comment by kopetersen** [comment]
Installing consul as a service running as SYSTEM, as decribed here: https://learn.hashicorp.com/tutorials/consul/deployment-guide#create-the-consul-service

This creates an empty logfile
`New-Service -Name Consul -BinaryPathName "C:\consul\consul.exe agent -config-dir=C:\consul\config"  -DisplayName Consul -Description "Consul" -StartupType "Automatic"` 


This logs to the file: (There should be a backtick on each side of > (Powershell escape char))
`New-Service -Name Consul -BinaryPathName "cmd.exe /C C:\consul\consul.exe agent -config-dir=C:\consul\config 2`>`&1"  -DisplayName Consul -Description "Consul" -StartupType "Automatic"`

And Consul is working just fine, despite an empty log
I have not seen any errors from consul

I tried running it as a user too, which worked just fine with logging.

**Comment by Amier3** [comment]
Hey @kopetersen!

We looked into this a bit more before and after the holidays but unfortunately we weren't able to replicate this. Considering that you discovered a work-around and the impact of the bug is relatively small, we're going to hold off on trying to dig deeper into this until a few more users experience this issue. 

I'll leave the issue open for now to make it more discoverable, let me know if you have any questions and sorry can't get you a good fix at the moment.

**Comment by Amier3** [comment]
UPDATE: We were able to replicate this after learning that one of our engineers experienced this problem when working on a related windows bug 💯 . We don't have a cause yet, but i'll keep this issue updated when we find a fix.

**Comment by kisunji** [comment]
Running Consul as a Windows Service and providing a `log-file` option currently creates a file successfully: https://github.com/hashicorp/consul/blob/752e3ec0b14ed18b3ce8fc146984ccb44d8a66ec/logging/logfile.go#L67

which suggests this is not a permissions issue.

After the file is created, there are no further writes which makes me suspect that our logger's `io.MultiWriter` (which by default contains stdout and the log file) is silently failing to write to stdout which makes the write to file fail: https://github.com/hashicorp/consul/blob/2dcc6966fe7b82bb81aad813fa42742e63d4784d/logging/logger.go#L107

**Comment by Amier3** [comment]
@inorangestylee 

When debugging windows services, where do you expect application logs to live? I know windows has a couple of ways of viewing logs like stdout, system diagnostics, and event viewer...so i'm curious to hear your thoughts on using a log file in general.

**Comment by kisunji** [comment]
Thank you @kopetersen for the hint that nomad logging was working on the same servers. It helped me find a simple fix for the issue: https://github.com/hashicorp/consul/pull/11960
