### ISSUE TITLE
Running 0.5.2 and tells me there is a newer version... 0.5.2

### ISSUE THREAD

**Issue by feniix** [hashicorp/consul#1177]
After it starts:

==> Newer Consul version available: 0.5.2

Is it a bug? am I doing something incorrectly?

**Comment by slackpad** [comment]
Hi @feniix any chance you are running your own build of Consul, or a non-official one? What does `consul version` report?

**Comment by feniix** [comment]
Hi @slackpad, no, I did not build consul, it is getting downloaded from mitchellh's bintray

see: 
```consul --version
Consul v0.5.2
Consul Protocol: 2 (Understands back to: 1)```

if it is any help:
`fc35735a636f0d5c9d62ae1c537c8b2e2ed1960fb34fe810f6b9431f7646e9f1  /usr/local/bin/consul`
```
ls -l /usr/local/bin/consul
-r-xr-xr-x. 1 root root 18245010 May 18 21:34 /usr/local/bin/consul
```

**Comment by slackpad** [comment]
Hmm - I can't reproduce this in any of my environments and we don't see this on our production 0.5.2 cluster. Your sha256 looks legit. The ping back uses https so it's hard to see directly, but you might want to `curl https://checkpoint-api.hashicorp.com/v1/check/consul?version=0.5.2` from one of those machines for sanity. I'll have to look around more to see how this could happen.

**Comment by feniix** [comment]
here from the same machine were consul is installed:

curl https://checkpoint-api.hashicorp.com/v1/check/consul?version=0.5.2
```json
{"product":"consul","current_version":"0.5.2","current_release":1431985741,"current_download_url":"https://consul.io/downloads.html","current_changelog_url":"https://github.com/hashicorp/consul/blob/v0.5.2/CHANGELOG.md","project_website":"http://www.consul.io","alerts":[]}```

**Comment by feniix** [comment]
hmmm this is super weird, I cannot reproduce anymore :+1:

**Comment by slackpad** [comment]
Yeah given what `consul --version` printed it's super hard to tell what's going on to cause that. Lemme know if you see it again and I'll try to debug it with you.

**Comment by feniix** [comment]
@slackpad sadly, I forgot to run an strace before and now when I run it with or without strace it does not do it any more. Otherwise I would have more info.
