### ISSUE TITLE
Sending SIGHUP to agent causes endless reloads

### ISSUE THREAD

**Issue by balexx** [hashicorp/consul#1178]
On some hosts, when sending a `kill -HUP`, the agent goes into an infinite loop reloading config:

```
==> Caught signal: hangup
==> Reloading configuration...
==> WARNING: LAN keyring exists but -encrypt given, using keyring
==> Caught signal: hangup
==> Reloading configuration...
==> WARNING: LAN keyring exists but -encrypt given, using keyring
==> Caught signal: hangup
==> Reloading configuration...
==> WARNING: LAN keyring exists but -encrypt given, using keyring
```

This is not reproducible on all hosts in our env, but where it does occur, it's consistently reproducible. We haven't been able to find anything special about these hosts so far.
Using `consul reload` the problem isn't reproducible.

**Comment by slackpad** [comment]
Looking through the code a bit it's not clear what's going on. If you see this happen can you run `strace` on the process to see if it is actually getting spammed with signals, or if it is somewhere further down?

**Comment by slackpad** [comment]
Haven't heard back on this one and couldn't reproduce, closing this out.
