### ISSUE TITLE
When registering the service with the balanced exposure registry address, there are multiple service instances, and only one health check succeeds

### ISSUE THREAD

**Issue by zhangdalei3745** [hashicorp/consul#11828]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create consul cluster use helm with 3 nodes.
2. expose consul-ui service.
3. use java sdk to register.
4. multi service instances with the same instance id, and unnormal health check state.
### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.
<img width="2559" alt="WX20211214-210456@2x" src="https://user-images.githubusercontent.com/84291178/146003708-b5030e23-1d8d-4823-98f7-ae24778020e5.png">

**Comment by Amier3** [comment]
Hey @zhangdalei3745 

I see this is your first issue here, so welcome to the consul community! 

We'll need a bit more information before we could help you with this. Could you provide us with the Helm Chart used to setup the cluster?  It might also be helpful to see a snippet of  the java code used to register the services

**Comment by zhangdalei3745** [comment]
1.this is consul helm chart values:

`global:
  enabled: true
  datacenter: dc1
  image: "hub.jdcloud.com/mesh/consul:1.10.0-jmsf"
  imageK8S: "hub.jdcloud.com/mesh/consul-k8s:0.26.0-jmsf"
  imagePullSecrets:
  - name: docker
  acls:
    manageSystemACLs: true
server:
  enabled: true
  replicas: 3
  bootstrapExpect: 3
  storage: 10Gi
  storageClass: jdcloud-lvm
  connect: false
client:
  enabled: false
# Values that configure the Consul UI.
ui:
  enabled: true
  service:
    enabled: true`
2. we use this [sdk，](https://github.com/spring-cloud/spring-cloud-consul/blob/main/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/TtlScheduler.java)
`public void run() {
            try {
                this.ttlScheduler.client.agentCheckPass(this.checkId);
                if (TtlScheduler.log.isDebugEnabled()) {
                    TtlScheduler.log.debug("Sending consul heartbeat for: " + this.checkId);
                }
            } catch (OperationException var3) {
                if (!this.ttlScheduler.heartbeatProperties.isReregisterServiceOnFailure() || !this.ttlScheduler.reregistrationPredicate.isEligible(var3)) {
                    throw var3;
                }

                TtlScheduler.log.warn(var3.getMessage());
                NewService registeredService = (NewService)this.ttlScheduler.registeredServices.get(this.serviceId);
                if (registeredService != null) {
                    if (TtlScheduler.log.isInfoEnabled()) {
                        TtlScheduler.log.info("Re-register " + registeredService);
                    }

                    this.ttlScheduler.client.agentServiceRegister(registeredService, this.ttlScheduler.discoveryProperties.getAclToken());
                } else {
                    TtlScheduler.log.warn("The service to re-register is not found.");
                }
            }

        }`
