### ISSUE TITLE
No name resolution at advertise parameter

### ISSUE THREAD

**Issue by andienase** [hashicorp/consul#1185]
I understand the problem with the private addresses for the bind parameter so I start the consul agent with the -bind paramter but with this I get an error for the advertise address

-> consul agent -node consul-s1-bind consul-s1 -config-file /home/consul/cfg/consul.cfg
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting raft data migration...
==> Starting Consul agent...
==> Error starting agent: Failed to start Consul server: Failed to start lan serf: Failed to parse advertise address!

The documentation says:
-advertise - The advertise address is used to change the address that we advertise to other nodes in the cluster. By default, the -bind address is advertised.

So ok I tried to tell him the same address as the bind address but it still not working:

-> consul agent -node consul-s1 -bind consul-s1 -advertise consul-s1 -config-file /home/consul/cfg/consul.cfg
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting raft data migration...
==> Starting Consul agent...
==> Error starting agent: Failed to parse advertise address: consul-s1

The name consul-s1 is resolved via LDAP and is pingable on the os (Linux/SLES 11). The node only starts when I commit the ip address to the advertise parameter.

-> consul agent -node consul-s1 -bind consul-s1 -advertise <ip-address> -config-file /home/consul/cfg/consul.cfg

**Comment by aidanhs** [comment]
Doesn't this require consul to be aware of NSS in order to be able to find the address on LDAP? Why not just use `-advertise $(dig +short consul-s1)`?

**Comment by highlyunavailable** [comment]
"Address" in this case is shorthand for "IP address" since Consul doesn't presuppose the existence of other DNS servers. @aidanhs method would work, or look up the address via some other method like checking the interfaces.

**Comment by andienase** [comment]
Sorry in the last command line the ip address after -advertise was missing.

-> consul agent -node consul-s1 -bind consul-s1 -advertise 10.10.10.10 -config-file /home/consul/cfg/consul.cfg

(ip only for example because I have currently no access to server)

What surprises me is that the name resolution is working at the -bind parameter?

**Comment by slackpad** [comment]
I'm going to close this out - we have documented these as addresses and don't intend to support host lookups in here (even if the path in Go happens to support them).

**Comment by mitom** [comment]
Would this have an effect in case servers changed IP addresses? As in, does this effectively control how do consul nodes reach out to each other (the member list)?

**Comment by AlexeySofree** [comment]
Yes, if IP changed (because of dhcpclient, a point-to-point protocol, for instance pppoe), then Consul still listening old IP address.
It shows `netstat`.

Other Consul servers can not connect no this server.

So pointed solution:
https://github.com/hashicorp/consul/pull/2563
doesn't work in this case - it's necessary to restart Consul with changed IP address.

**Comment by slackpad** [comment]
Consul handling IP address changes is tracked under https://github.com/hashicorp/consul/issues/1580.

**Comment by AlexeySofree** [comment]
Probably yes, but this doesn't help.

Let's demonstrate this.
Working cluster with 3 servers:
````
/root/temp/consul/consul members
Node           Address              Status  Type    Build  Protocol  DC
li.home.local  x.29.111.207:8301   alive   server  0.8.4  3         dc1
rhost.local    y.201.41.69:8301    alive   server  0.8.4  3         dc1
thost.net      z.234.37.183:8301   alive   server  0.8.4  3         dc1

/root/temp/consul/consul operator raft list-peers
Node           ID                                    Address              State     Voter  RaftProtocol
thost.net      dd6fbbf2-bead-fe16-a37b-2208e8bd8234  z.234.37.183:8300   leader    true   3
li.home.local  510841b8-7d15-dc78-a2b0-5dfaf72c23b0  x.29.111.207:8300   follower  true   3
rhost.local    0296831c-aa74-b47e-ded5-75450aff8943  y.201.41.69:8300    follower  true   3
````

The `li.home.local` uses this command for Consul running:
````
/root/temp/consul/consul agent -data-dir=/root/temp/consul/data -server -raft-protocol=3 -protocol=3 -advertise=x.29.111.207
````

IP address:
````
ip a | grep inet | grep ppp0
    inet x.29.111.207 peer a.b.c.d/32 scope global ppp0
````

I am changing IP address via:
````
ifdown ppp0; ifup ppp0

ip a | grep inet | grep ppp0
    inet o.29.106.101 peer a.b.c.d/32 scope global ppp0
````

Cluster members list reports old info:
````
/root/temp/consul/consul members
Node           Address              Status  Type    Build  Protocol  DC
li.home.local  x.29.111.207:8301   failed  server  0.8.4  3         dc1
rhost.local    y.201.41.69:8301    alive   server  0.8.4  3         dc1
thost.net      z.234.37.183:8301   alive   server  0.8.4  3         dc1
````


If I restart the `li.home.local` node with new IP address:
````
/root/temp/consul/consul agent -data-dir=/root/temp/consul/data -server -raft-protocol=3 -protocol=3 -advertise=o.29.106.101
````

I see a good state of cluster:
````
/root/temp/consul/consul members
Node           Address              Status  Type    Build  Protocol  DC
li.home.local  o.29.106.101:8301   alive   server  0.8.4  3         dc1
rhost.local    y.201.41.69:8301    alive   server  0.8.4  3         dc1
thost.net      z.234.37.183:8301   alive   server  0.8.4  3         dc1
````


So, that do you mean, saying
> Consul handling IP address changes
?

Without -bind option Consul listens on all interfaces, so IP address change does not play any role:
```
-bind - The address that should be bound to for internal cluster communications. This is an IP address that should be reachable by all other nodes in the cluster. By default, this is "0.0.0.0", meaning Consul will bind to all addresses on the local machine
````

````
netstat -nlp | grep consul
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN      12980/consul
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      12980/consul
tcp6       0      0 :::8300                 :::*                    LISTEN      12980/consul
tcp6       0      0 :::8301                 :::*                    LISTEN      12980/consul
tcp6       0      0 :::8302                 :::*                    LISTEN      12980/consul
udp        0      0 127.0.0.1:8600          0.0.0.0:*                           12980/consul
udp6       0      0 :::8301                 :::*                                12980/consul
udp6       0      0 :::8302                 :::*                                12980/consul
````
