### ISSUE TITLE
UI shows "All service checks passing" when proxy is not passing

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#11875]
#### Overview of the Issue

Consul 1.10.4

I see my service is having an error (the percentage should actually be 50% failing but that's another issue https://github.com/hashicorp/consul/issues/11814):

![image](https://user-images.githubusercontent.com/1034429/146462668-a1c27f9e-838f-4d35-999e-52e8ae77cf8d.png)

I click on the instance list and it says there are no service errors:

![image](https://user-images.githubusercontent.com/1034429/146462657-83e88a54-dd15-4427-9af5-b8f64fd3f23d.png)

I click into it anyway and see that the proxy is erroring:

![image](https://user-images.githubusercontent.com/1034429/146462678-88d2fc5f-4147-456b-971a-b06fdcca3141.png)

### Possible Resolution

I think it probably makes sense to show the proxy health checks at the instance list level and say that the service _is_ failing (if it has a proxy).

**Comment by jkirschner-hashicorp** [comment]
Per @johncowen, closed by https://github.com/hashicorp/consul/pull/12279
