### ISSUE TITLE
Sidecar proxy checks not showing up in UI until after a refresh

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#11873]
#### Overview of the Issue

Consul 1.11.1 (does not occur with 1.10.4)

I have a service with two instances, each instance has a sidecar proxy. When I view one instance I see the sidecar proxy checks as expected. When I then navigate to the other instance, the proxy checks aren't shown. Then when I refresh, the proxy checks appear. If I navigate back to the first instance, now its proxy checks aren't shown. See video:

https://user-images.githubusercontent.com/1034429/146455699-f0500a22-493a-4120-a705-9ee2a5ace63c.mp4

Service files for reproduction:

```hcl
service {
  name = "backend"
  port = 7000
  connect {
    sidecar_service {
      proxy {
      }
    }
}
```

```hcl
service {
  name = "backend"
  id = "backend-v2"
  port = 7001
  connect {
    sidecar_service {
      proxy {
      }
    }
  }
}
```

**Comment by johncowen** [comment]
Thanks for spotting and reporting this @lkysow 🙏 theres a fix incoming for this https://github.com/hashicorp/consul/pull/11903
