### ISSUE TITLE
"consul leave" sometimes exits with an error code 

### ISSUE THREAD

**Issue by pforman** [hashicorp/consul#1189]
While researching some stop-script behavior, I've noticed that "consul leave" can sometimes return a failure code rather than 0.  I can't reproduce this reliably, but I can trigger it given enough runs.

I'm testing with 0.5.2, on a current Amazon Linux AMI in EC2.

Here's what I occasionally see:

```
[root@ip-10-103-65-99 ~]# /etc/init.d/consul stop
Shutting down consul: Error leaving: client closed
```

This doesn't fail to leave the cluster, verifying with `consul members` from another host it all appears to work correctly.  However, the error code confuses the start/stop scripts, and doesn't seem to be correct behavior.

The log entries on DEBUG look basically identical, but I was also able to catch it with `strace` on and that was a bit more enlightening.

This gist has a complete run of a regular graceful leave and a "client closed" failure.  https://gist.github.com/pforman/43be9027507ba20e8722

The key seems to be that if a retry happens in the leave command, we eventually get a "client closed" failure.  The snippet below show the major difference I can find in those two traces. 

```
write(3, "\202\247Command\251handshake\243Seq\1\201\247Versio"..., 34) = 34
read(3, "\202\245Error\240\243Seq\1", 4096) = 13
read(3, 0xc20809c000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
write(3, "\202\247Command\245leave\243Seq\2", 20) = 20
```

So it seems like there may be a slight ordering problem in the leave code?  I'll look a bit deeper, but maybe someone who knows the code better can see the issue quickly.

**Comment by slackpad** [comment]
Closing this one out as we've redone the RPC path that leave takes (the old RPC client was removed and now it just uses the HTTP API), so this _should_ be fixed.
