### ISSUE TITLE
When I have multiple nodes, the anti-registration may not be successful

### ISSUE THREAD

**Issue by Jiang-boyang** [hashicorp/consul#11890]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

When I have multiple node nodes, the anti-registration may not be successful

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. my consul cluster  has 3 sever and 5 client
2. register Run `curl  --request PUT   --data '{"ID":"test_exporter_1","Name":"test_exporter","Tags":["primary","v1"],"Address":"127.0.0.1","Port":8000,"Meta":{"exporter_version":"4.0"},"Weights":{"Passing":10,"Warning":1}}' http://127.0.0.1:8500/v1/agent/service/register`
3. deregister run `curl -X PUT http://127.0.0.1:8500/v1/agent/service/deregister/test_exporter_1`
4. consul version : 1.9.5

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by blake** [comment]
Hi @Jiang-boyang, would you mind sharing the particular error message you are receiving when you attempt to deregister the service? Thanks.

**Comment by Jiang-boyang** [comment]
Sorry, my description may not be clear enough
I want to ask if there is a service that can deregister multiple clients through an API
So even if I have multiple clients, it will be much easier for me to deregister

**Comment by Jiang-boyang** [comment]
> 嗨@Jiang-boyang，您介意分享您在尝试取消注册服务时收到的特定错误消息吗？谢谢。

thank you for your reply

**Comment by Amier3** [comment]
Hey @Jiang-boyang 

Unfortunately there's not currently a way to de-register multiple clients through the API.  I'm going to close this issue for now, but feel free to create an enhancement request for this feature if you wish 👍
