### ISSUE TITLE
Golang Client does not support Node Lookups

### ISSUE THREAD

**Issue by mooijtech** [hashicorp/consul#11904]
Hello,

I want to lookup a node by the UUID using DNS: ```<node>.node[.datacenter].<domain>```
But I'm getting the following and see no support for it in the Golang Consul Client code:
```
ERRO[0015] Failed to send request: Post "https://22dwvI0Hvh6oXyU8omjihS99KVu.node.consul/internal/explosion": unsupported Consul DNS domain: must be either <name>.service[.<datacenter>].consul or <name>.query[.<datacenter>].consul
```

It's in the documentation: https://www.consul.io/docs/discovery/dns

It resolves via ```dig```: 
```
$ dig @127.0.0.1 -p 8600 22dwvI0Hvh6oXyU8omjihS99KVu.node.consul ANY

; <<>> DiG 9.16.23 <<>> @127.0.0.1 -p 8600 22dwvI0Hvh6oXyU8omjihS99KVu.node.consul ANY
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 23395
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;22dwvI0Hvh6oXyU8omjihS99KVu.node.consul. IN ANY

;; AUTHORITY SECTION:
consul.			0	IN	SOA	ns.consul. hostmaster.consul. 1640184489 3600 600 86400 0

;; Query time: 0 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Wed Dec 22 15:48:09 CET 2021
;; MSG SIZE  rcvd: 118
```

What am I missing?

Kind regards,
Marten Mooij

**Comment by mooijtech** [comment]
Note I'm using Consul Connect (API), the HTTPClient of the service doesn't support Node Lookups over DNS via the resolver:
https://github.com/hashicorp/consul/blob/main/connect/resolver.go#L227

**Comment by blake** [comment]
@mooijtech `ConsulResolver` only supports returning address for other Connect-enabled _services_ in Consul (see https://github.com/hashicorp/consul/blob/1683da6/connect/resolver.go#L17-L30). It does not support returning node IPs because Consul nodes/agents do not participate in the service mesh.

Would you mind sharing a bit more detail on what you're trying to achieve, and why that requires connecting to a node rather than a service address?

**Comment by mooijtech** [comment]
@blake I'm working on a new project which implements a HTTP API which is compatible with [ElasticSearch](https://www.elastic.co/elasticsearch/) (so I can make use of the official [go-elasticsearch](https://github.com/elastic/go-elasticsearch) client) but for the backend I'm using [Consul](https://www.consul.io/), [Nomad](https://www.nomadproject.io/), [MinIO](https://min.io/) and [Bluge](https://github.com/blugelabs/bluge) which is all written in Go.

For, for example a create index request I need to forward this request to the leader of my instances/nodes (services) which are registered in Consul and support Connect. Whoever acquires a lock for the leader key first becomes the leader and their service ID is the value.

I need to be able to communicate with the leader and after that all healthy nodes via DNS since I'm using the service for TLS. But the ```<service>.service[.datacenter].<domain>``` only returns a random node (and they don't support looking up via service ID), not the one(s) I want.

**Comment by mooijtech** [comment]
Any update on this?

**Comment by mooijtech** [comment]
As a workaround I am now using IP:Port over HTTP directly and using the default HTTP client instead of the Consul service one which means I'm no longer using DNS or TLS.

Only feature I'm missing (looking up a service registered to Consul by it's service ID) otherwise great library.

**Comment by mooijtech** [comment]
Any update on this? I'm now using Nomad to start my instances so I need DNS for getting the ports (and of individual instances).

**Comment by mooijtech** [comment]
The httpResolverFromAddr is unexported which means I can't implement this myself either.

**Comment by Amier3** [comment]
Hey @mooijtech,

Thanks for all the helpful context! Our team gets a holiday break from the 24th to Jan 3rd... so most of the team are just getting back into things this week. I'd give a couple days for us to get you an update on this.

**Comment by mooijtech** [comment]
Temporarily using a dynamic IP:Port address (still without DNS or TLS):
```go
// NewDefaultClient returns our go-explosion client which communicates with HashiCorp Consul.
func NewDefaultClient() (Client, error) {
	var address *string

	var client Client

	go func() {
		consulClient, err := consul.NewClient(consul.DefaultConfigWithLogger(Logger))

		if err != nil {
			Logger.Error("Failed to create Consul client: %s", err)
		}

		for {
			if client.IsClosed {
				break
			}

			serviceEntries, _, err := consulClient.Health().Connect("go-explosion", "", true, nil)

			if err != nil {
				Logger.Error("Failed to get service address.", err)
				break
			}

			if len(serviceEntries) > 0 {
				rand.Seed(time.Now().UnixNano())

				serviceEntry := serviceEntries[rand.Intn(len(serviceEntries))]

				newAddress := fmt.Sprintf("http://%s:%d", serviceEntry.Service.Address, serviceEntry.Service.Port)
				address = &newAddress

				Logger.Info("Updated client address to", "address", *address)
			}

			time.Sleep(time.Second * 5)
		}
	}()

	// Wait for the goroutine to update the client address.
	for address == nil {
		Logger.Debug("Waiting for client address to update...")
		time.Sleep(time.Second)
	}

	var err error

	client, err = NewClientWithAddress(address)

	if err != nil {
		return Client{}, err
	}

	return client, nil
}
```

**Comment by mooijtech** [comment]
Any update on this?

**Comment by blake** [comment]
Hi @mooijtech,

> serviceEntries, _, err := consulClient.Health().Connect("go-explosion", "", true, nil)

Querying the health endpoint is a perfectly reasonable solution to obtain a complete list of Connect-enabled nodes for a given service, given the API client does not provide a method to do this out of the box.

> Temporarily using a dynamic IP:Port address (still without DNS or TLS).

Could you elaborate as to why querying the HTTP API is not a long term solution for you? Is there a particular reason you would like to use DNS over the response you're retrieving from the HTTP API?

I'm also curious as to why TLS is not working. The HTTP query provides you a list of Connect-enabled endpoints for your service. You can initiate mTLS connections to these endpoints to secure the data in transit.

**Comment by mooijtech** [comment]
The Consul Service HTTP client (in Golang) handles the TLS for me but it only supports communicating over DNS (the resolver) so that's my problem I'm trying to explain. Can you explain how I would perform mTLS connections since connecting to IP:Port is not supported by the HTTP client?

**Comment by mooijtech** [comment]
And the DNS .service.consul only returns random instances, not the ones I want.

**Comment by mooijtech** [comment]
Ended up doing a stateless instance (any instance can answer any query) which also solves this.

**Comment by mooijtech** [comment]
If I have terabytes of data I need to be able to shard them across different nodes so I need to be able to contact individual nodes.

**Comment by mooijtech** [comment]
I have found a workaround by using [fabio](https://github.com/fabiolb/fabio) I register a urlprefix-/internal/23t1WL9GrZ4NbfkFy36CKU0fb4l/test and then send all requests to fabio and it reaches the internal endpoint with the UUID. Also now I have load balancing.
