### ISSUE TITLE
Add -reason flag to leave

### ISSUE THREAD

**Issue by aj-jester** [hashicorp/consul#1190]
Would there be any interest in adding/accepting a feature to add `-reason` flag to [leave](https://www.consul.io/docs/commands/leave.html) similar to [maint](https://www.consul.io/docs/commands/maint.html#_reason)?

This comes in handy when we initiate a `consul leave` from init scripts or if just the user wants to add a reason `consul leave -reason='node was going bonkers'`.

**Comment by slackpad** [comment]
This is an interesting idea but it might require some tricky plumbing down into Serf and back to propagate the message.

**Comment by slackpad** [comment]
I'm going to close this out as there hasn't been a lot of interest in this, and it's fairly tricky to plumb the message around since leave happens at the gossip layer. It's probably not worth the complexity.
