### ISSUE TITLE
Consul 1.1.0 deb package missing env file

### ISSUE THREAD

**Issue by m1keil** [hashicorp/consul#11911]
#### Overview of the Issue
Systemd unit file expects a `EnvironmentFile=/etc/consul.d/consul.env` which isn't being created by default, causing start to fail with `consul.service: Failed to load environment files: No such file or directory` error.

#### Reproduction Steps

Install Consul 1.11.0 from apt.releases.hashicorp.com and try to start it as a service with `systemctl start consul`.

### Operating system and Environment details

```
# uname -a
Linux ip-172-30-61-181 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments

```
systemd[1]: consul.service: Failed to load environment files: No such file or directory
systemd[1]: consul.service: Failed to run 'start' task: No such file or directory
systemd[1]: consul.service: Failed with result 'resources'.
systemd[1]: Failed to start "HashiCorp Consul - A service mesh solution".
```

**Comment by josegonzalez** [comment]
Probably should do `EnvironmentFile=-/etc/consul.d/consul.env` in the systemd file so that the file doesnt need to exist.

**Comment by m1keil** [comment]
btw it seems like the nomad package does include an (empty) envfile.

**Comment by Amier3** [comment]
Hey @m1keil  

First off, welcome to the consul community! 

This is an odd issue especially if the nomad package is working correctly but the consul one isn't, I tried to do a quick replication of the bug on an ubuntu VM following [these](https://learn.hashicorp.com/tutorials/consul/get-started-install) steps, but didn't have any luck  luck:

```
root@ip-172-31-89-157:/home/ubuntu# uname -a
Linux ip-172-31-89-157 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


root@ip-172-31-89-157:/home/ubuntu# systemctl status consul
● consul.service - "HashiCorp Consul - A service mesh solution"
     Loaded: loaded (/lib/systemd/system/consul.service; disabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-12-23 14:02:20 UTC; 51s ago
       Docs: https://www.consul.io/
   Main PID: 2347 (consul)
      Tasks: 7 (limit: 1147)
     Memory: 18.7M
     CGroup: /system.slice/consul.service
             └─2347 /usr/bin/consul agent -config-dir=/etc/consul.d/

Dec 23 14:02:20 ip-172-31-89-157 consul[2347]: 2021-12-23T14:02:20.432Z [INFO]  agent: Starting server: address=127.0.0.1:8500 network=tcp protocol=http
Dec 23 14:02:20 ip-172-31-89-157 consul[2347]: 2021-12-23T14:02:20.432Z [WARN]  agent: DEPRECATED Backwards compatibility with pre-1.9 metrics enabled. These metrics will be removed in a future version of Consul. Set `telemetry { disable_compat_1.9 = tr>
Dec 23 14:02:20 ip-172-31-89-157 consul[2347]: 2021-12-23T14:02:20.433Z [INFO]  agent: started state syncer
Dec 23 14:02:20 ip-172-31-89-157 consul[2347]: 2021-12-23T14:02:20.433Z [INFO]  agent: Consul agent running!
Dec 23 14:02:20 ip-172-31-89-157 consul[2347]: 2021-12-23T14:02:20.434Z [WARN]  agent.router.manager: No servers available
Dec 23 14:02:20 ip-172-31-89-157 consul[2347]: 2021-12-23T14:02:20.434Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
Dec 23 14:02:43 ip-172-31-89-157 consul[2347]: 2021-12-23T14:02:43.425Z [WARN]  agent.router.manager: No servers available
Dec 23 14:02:43 ip-172-31-89-157 consul[2347]: 2021-12-23T14:02:43.426Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
Dec 23 14:03:01 ip-172-31-89-157 consul[2347]: 2021-12-23T14:03:01.649Z [WARN]  agent.router.manager: No servers available
Dec 23 14:03:01 ip-172-31-89-157 consul[2347]: 2021-12-23T14:03:01.650Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
```

It also looks like the install was able to create the environment by default as well:

```
root@ip-172-31-89-157:/home/ubuntu# ls -l /etc/consul.d/
total 8
-rw-r--r-- 1 consul consul    0 Dec 15 21:18 consul.env
-rw-r--r-- 1 consul consul 5158 Dec 15 21:18 consul.hcl
```

I'll check with our release team and get their thoughts on this, in the meantime could you provide us with the consul.service file in `/lib/systemd/system`?  I'll note that if this is a bug, we might not be able to resolve it till after the holidays

**Comment by m1keil** [comment]
You are correct @Amier3, the issue is on our side. Apparently, our provision was wiping /etc/consul.d after package install. My apologies. 

I do wonder if a more sensible default as pointed by @josegonzalez is a better idea just in any case but there's no "bug" here. Closing.

**Comment by sawall** [comment]
I ended up here after using the deployment guide: https://learn.hashicorp.com/tutorials/consul/deployment-guide

It might make sense to @josegonzalez's suggested change in those docs.

**Comment by blake** [comment]
> I ended up here after using the deployment guide: https://learn.hashicorp.com/tutorials/consul/deployment-guide
> 
> It might make sense to @josegonzalez's suggested change in those docs.

This tutorial was updated yesterday to incorporate Jose's suggestion to have `.env` be an optional `EnvironmentFile`.
