### ISSUE TITLE
Edit kv in webui which key contains '@' cause 404

### ISSUE THREAD

**Issue by finchcn** [hashicorp/consul#11925]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Edit kv in webui which key contains '@' cause 404

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl -X PUT "http://localhost:8500/v1/kv/somepath/a@b:c" -d "123"` 
2. Open WebUI and click the key
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

Server OS: ubuntu
WebBrowser: Edge On Mac

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

I think the bug is url encode some char twice

**Comment by Amier3** [comment]
Hey @finchcn 

Welcome to the hashicorp community! 

I tried to reproduce this using the steps you provided but wasn't able to. On a fresh cluster I was able to successfully add the key with an '@' sign without error.

<img width="1777" alt="Screen Shot 2022-01-03 at 1 10 29 PM" src="https://user-images.githubusercontent.com/92801461/147964732-f774ec31-aba2-477d-adf7-7a72f4121862.png">


Could you provide us with: 

- The version of consul you're running  
- A screenshot of the error you're seeing 
- The output from `consul info` on the cluster seeing the error
