### ISSUE TITLE
services registered in local consul agent not store across all the members of consul servers

### ISSUE THREAD

**Issue by zffocussss** [hashicorp/consul#11922]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I have 5 consul clients,3 consul servers.which are  installed by helm chart

services registered in local client was not store across all the members of all consul servers

#### Reproduction Steps

Steps to reproduce this issue, eg:

on the consul client pod:
1. consul services register -name=http -port=8789
2. delete the consul-client pod and make it not restart
3. the service is missed in consul ui

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 2c56447e
	version = 1.11.1
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 52
	max_procs = 2
	os = linux
	version = go1.17.5
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 13
	members = 8
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 2c56447e
	version = 1.11.1
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.2.3.243:8300
	server = true
raft:
	applied_index = 1306
	commit_index = 1306
	fsm_pending = 0
	last_contact = 0
	last_log_index = 1306
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:5d8b9969-b499-92a2-b7b7-6b893f9084cf Address:10.2.3.243:8300} {Suffrage:Voter ID:0a7b41ea-b223-1978-97ec-564061db2caa Address:10.2.0.180:8300} {Suffrage:Voter ID:fc9e876c-1041-fb43-75af-bb2615f7769a Address:10.2.1.151:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 157
	max_procs = 2
	os = linux
	version = go1.17.5
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 13
	members = 8
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

k8s 1.20+

### Expected results
the services should be present even though the client is not present or restarted so that other application can find them

**Comment by zffocussss** [comment]
![image](https://user-images.githubusercontent.com/46145695/147562890-95476661-fec6-478e-93e4-4bf3bf6a44bb.png)

**Comment by blake** [comment]
This is expected behavior. See https://github.com/hashicorp/consul/issues/11438#issuecomment-997588133 for details.

**Comment by Amier3** [comment]
Closing this for now, @zffocussss feel free to re-open if you need us to provide some additional context 👍
