### ISSUE TITLE
Vault AuthMethods for Connect CA

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/consul#11921]
#### Overview of the Issue

We have Vault as our connect CA and are running 1.11.1.  I attempted to use the new AuthMethod settings to use the AWS instance profile to authenticate with vault.  I got an error that I hadn't provided the necessary parameters.  From looking at the code, it appears that the "extra" bits that vault cli does for an aws login are missing and so the only way to use this auth method is to manually construct the identity documents and so on.

Would a PR be welcome to add this?

I'd propose to extend the AWS leg of the current code in a similar way to the kubernetes leg (adding values to the Params map).  And it looks like the approach to determine them is already done here, so could be transplanted over:
https://github.com/hashicorp/vault/blob/a620c2dc8f82b91372521a149ce7e77b97587f9c/builtin/credential/aws/cli.go#L14

#### Reproduction Steps

PUT https://<consul-host>/v1/connect/ca/configuration

{
  "Provider": "vault",
  "Config": {
    "Address": "<vault>,
    "IntermediateCertTTL": "8760h0m0s",
    "IntermediatePKIPath": "pki/consul_connect",
    "RootPKIPath": "pki/root",
    "PrivateKeyType": "rsa",
    "PrivateKeyBits": 4096,
    "AuthMethod": { 
			"Type": "aws", 
			"MountPath": "global_aws", 
			"Params": { 
				"role": "role_consul_server",
				"region": "eu-west-1"
			} 
		}
  }
}

Code: 400. Errors:

* didn't supply required authentication values

**Comment by Amier3** [comment]
Hey @mr-miles 

Thanks for pointing this out, we'd definitely welcome a PR on this! I think you're correct it seems like all you'd have to do is read the extra params and write those to the URL. I'll link the auth method you'd need to change  [here](https://github.com/hashicorp/consul/blob/1b0b4f7c267e545e92c66a1598637dda33e4324e/agent/connect/ca/provider_vault.go#L765), as well as our [CONTRIBUTING.md ](https://github.com/hashicorp/consul/blob/main/.github/CONTRIBUTING.md). Let me know if you have any questions 👍

**Comment by mr-miles** [comment]
ok thanks - will put something together in that direction

**Comment by mark-rushakoff** [comment]
I lost a lot of time -- at least a day -- trying to debug what I was doing wrong when attempting to use the Vault CA provider with the GCP auth method. I copied the settings from my working Vault agent config, but it didn't work, of course.

I think I can work around this by retrieving a token from my Vault agent config, although I'd rather not be passing around another file containing a secret.

I imagine it will save others quite a bit of time, if the configuration docs were updated to clarify that this is a "low level" auth method.

**Comment by jkirschner-hashicorp** [comment]
Hi @mr-miles and @mark-rushakoff,

We're currently working on achieving parity between the auth details you need to provide in a Vault agent config versus Consul's Vault CA provider, such as for AWS and GCP auth methods. Going forward, we don't intend for the Vault CA provider to need additional fields beyond what the equivalent Vault agent config requires.

We'll link to a PR once available.

CC @cthain

**Comment by mr-miles** [comment]
smashing!  Looking forward to it already!! Thanks

**Comment by jkirschner-hashicorp** [comment]
Closed by https://github.com/hashicorp/consul/pull/15970!
