### ISSUE TITLE
Cannot bootstrap cluster on non-deterministic order of starting agents

### ISSUE THREAD

**Issue by ahmetalpbalkan** [hashicorp/consul#1193]
#question 

Hi, I am using the `progrium/consul:latest` docker image and creating VMs that has Consul agents running in them. However based on the order the VMs come up, sometimes Consul cannot reach consensus indefinitely.

Here's my topology:

> ### master-0 (10.0.0.4)
>* Args: `-server -node master0 -advertise 10.0.0.4 -bootstrap-expect 3`
>
>### master-1 (10.0.0.5)
>* Args: `-server -node master1 -advertise 10.0.0.5 -join 10.0.0.4 -join 10.0.0.6`
>
>### master-2 (10.0.0.6)
>* Args: `-server -node master2 -advertise 10.0.0.6 -join 10.0.0.4 -join 10.0.0.5`

I have the logs from 3 nodes at here: https://gist.github.com/ahmetalpbalkan/72808bd49799338d2c17

I start the containers of the agents with:
* all the Docker image ports mapped statically on the host
* `--restart=always`
* `/data` mounted to a persistent path on the host through Docker volumes

. Please note that, based on the order the VMs come up, this sometimes fails and sometimes succeeds

Can someone please help me understand what part am I doing wrong and why does the consul ring end up in this state? Thanks in advance.

**Comment by slackpad** [comment]
Hi @ahmetalpbalkan I think you might want to try the `-retry-join` option, as `-join` is a one-shot thing that won't try again. Take a look at this for more details - https://www.consul.io/docs/agent/options.html.

> -retry-join - Similar to -join but allows retrying a join if the first attempt fails. This is useful for cases where we know the address will become available eventually.

**Comment by ahmetalpbalkan** [comment]
@slackpad Thanks, I think you saved the day. `-join` docs mention how many times it will be tried at all. My expectation from this sort of distributed software was to have `-retry-join` as the default behavior.

![image](https://cloud.githubusercontent.com/assets/159209/9551800/36776b0e-4d68-11e5-8bf9-c53a77334b0b.png)
