### ISSUE TITLE
Latest Consul 1.11.1 rpm does not install on fips enabled systems- Digest mismatch

### ISSUE THREAD

**Issue by radioipcloud** [hashicorp/consul#11943]
Downloading Packages:
consul-1.11.1-1.x86_64.rpm                    24 MB/s |  30 MB     00:01
-----------------------------------------------------------------------------
Total                                         24 MB/s |  30 MB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                     1/1
  Running scriptlet: consul-1.11.1-1.x86_64                              1/1
  Running scriptlet: consul-1.11.1-1.x86_64                              1/2
  Upgrading        : consul-1.11.1-1.x86_64                              1/2
Error unpacking rpm package consul-1.11.1-1.x86_64
  Verifying        : consul-1.11.1-1.x86_64                              1/2
  Verifying        : consul-1.11.0-1.x86_64                              2/2
Installed products updated.

Failed:
             consul-1.11.1-1.x86_64

Error: Transaction failed

We are getting the issue when downloading the rpm directly and running rpm -i

 rpm -i ./consul-1.11.1-1.x86_64.rpm
warning: ./consul-1.11.1-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID a3219f7b: NOKEY
error: unpacking of archive failed on file /etc/consul.d/consul.env;61d5e857: cpio: Digest mismatch
error: consul-1.11.1-1.x86_64: install failed

best regards...

**Comment by kisunji** [comment]
Hello, could you provide some details about your OS and environment?

**Comment by radioipcloud** [comment]
Sorry about that i completely forgot.

RedHat 8.4. 

We deploy either on virtual box 6.1 or proxmox 6.2-15.

Best regards.

**Comment by kisunji** [comment]
Could you provide the mirror where you downloaded `consul-1.11.1-1.x86_64.rpm` as well? I tried manually installing with an RHEL EC2 instance and did not have any issues

**Comment by radioipcloud** [comment]
It is important to mention that the system was fips enabled otherwise the issue had not occured.

**Comment by radioipcloud** [comment]
Updating Subscription Management repositories.
YUM version: 4.4.2
cachedir: /var/cache/dnf
Last metadata expiration check: 0:00:12 ago on Wed 05 Jan 2022 07:02:48 PM EST.
Repo-id            : hashicorp
Repo-name          : Hashicorp Stable - x86_64
Repo-status        : enabled
Repo-updated       : Tue 21 Dec 2021 04:07:29 PM EST
Repo-pkgs          : 546
Repo-available-pkgs: 546
Repo-size          : 18 G
Repo-baseurl       : https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable
Repo-expire        : 172,800 second(s) (last: Wed 05 Jan 2022 09:00:05 AM EST)
Repo-filename      : /etc/yum.repos.d/hashicorp.repo

**Comment by radioipcloud** [comment]
Therefore, all in all, running on a fips enabled system...

if you perform **yum install consul-1.11.0** you will have no issues installing. 

Dependencies resolved.
================================================================================
 Package        Architecture   Version          Repository                 Size
================================================================================
Installing:
 consul         x86_64         1.11.0-1         radioip-hashicorp          37 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 37 M
Installed size: 100 M
Is this ok [y/N]: y
Downloading Packages:
consul-1.11.0.x86_64.rpm                         22 MB/s |  37 MB     00:01    
--------------------------------------------------------------------------------
Total                                            22 MB/s |  37 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: consul-1.11.0-1.x86_64                                 1/1 
  Installing       : consul-1.11.0-1.x86_64                                 1/1 
  Running scriptlet: consul-1.11.0-1.x86_64                                 1/1 
  Verifying        : consul-1.11.0-1.x86_64                                 1/1 
Installed products updated.

Installed:
  consul-1.11.0-1.x86_64                                                        

Complete!

**yum install consul** will install the latest consul-1.11.1-1 and it will generate an error.

These are the repro steps.

Comparison of the digests themselves of 1.11.0-1 and 1.11.1-1 are similar 

./consul-1.11.0-1.x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID a3219f7b: NOKEY
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA512 Signature, key ID a3219f7b: NOKEY
    MD5 digest: OK
 rpm --checksig -v ./consul-1.11.1-1.x86_64.rpm
./consul-1.11.1-1.x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID a3219f7b: NOKEY
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA512 Signature, key ID a3219f7b: NOKEY
    MD5 digest: OK

**Comment by radioipcloud** [comment]
Additionnal testing revealed the potential issue....

if you download from the repository with yum juts to see which rpm it will download :

- downloading the rpms using yum.
yum install --downloadonly --downloaddir=. consul-1.11.0
yum install --downloadonly --downloaddir=. consul

we now have two rpms ... we can unpack them with rpm ... a digest mismatch appear on consul.env in the latest consul.

rpm -ivh ./consul-1.11.0.x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:consul-0:1.11.0-1                ################################# [100%]


rpm -ivh ./consul-1.11.1-1.x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:consul-1.11.1-1                  ################################# [100%]
error: unpacking of archive failed on file /etc/consul.d/consul.env;61d6f6d4: cpio: Digest mismatch
error: consul-1.11.1-1.x86_64: install failed

**Comment by kisunji** [comment]
Our initial suspicion is that FIPS disables MD5, which may have been used for packaging 1.11.1. Our release team is looking into it to ensure future releases avoid MD5.

In the meantime, a workaround could be to pass `–nofiledigest` as a flag to `rpm` to skip the digest check.

**Comment by radioipcloud** [comment]
The 1.11.0 has an md5 digest. It's as if the consul.env was not signed properly. Or maybe you guys resign your rpm's later in your process.

**Comment by per-lind** [comment]
Possible related but on our installations on Centos 8 using repo https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable

No /etc/consul.d/consul.env is created an leaves the service unable to start. Issue is still present with 
`Installed Packages
Name         : consul
Version      : 1.11.2
Release      : 1
Architecture : x86_64
Size         : 100 M
Source       : consul-1.11.2-1.src.rpm
Repository   : @System
From repo    : Hashicorp-repo
Summary      : Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure.
URL          : https://github.com/hashicorp/consul
License      : MPL-2.0
Description  : Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure.`

`× consul.service - "HashiCorp Consul - A service mesh solution"
     Loaded: loaded (/usr/lib/systemd/system/consul.service; enabled; vendor preset: disabled)
     Active: failed (Result: resources) since Fri 2022-01-21 14:18:29 CET; 25min ago
       Docs: https://www.consul.io/
        CPU: 0

Jan 21 14:18:29 bn-p-syslog301 systemd[1]: consul.service: Scheduled restart job, restart counter is at 5.
Jan 21 14:18:29 bn-p-syslog301 systemd[1]: Stopped "HashiCorp Consul - A service mesh solution".
Jan 21 14:18:29 bn-p-syslog301 systemd[1]: consul.service: Start request repeated too quickly.
Jan 21 14:18:29 bn-p-syslog301 systemd[1]: consul.service: Failed with result 'resources'.
Jan 21 14:18:29 bn-p-syslog301 systemd[1]: Failed to start "HashiCorp Consul - A service mesh solution".`

This solves the problem
`
touch /etc/consul.d/consul.env
chown consul:consul /etc/consul.d/consul.env
`

**Comment by radioipcloud** [comment]
In 1.11.1, the consul.env was packaged in the rpm distributed but it had a digest mismatch.
error: unpacking of archive failed on file /etc/consul.d/consul.env;61d6f6d4: cpio: Digest mismatch

On 1.11.2 we have not seen the error but we deploy our own consul.env through our orchestration procedure so it's possible that we have not seen this error because of this fact.

thanks for the feedback @per-lind

**Comment by mdeggies** [comment]
Hey all- Sorry for the delay here. The issue is that we forgot to create the consul.env file which belongs [in this directory](https://github.com/hashicorp/consul/tree/main/.release/linux/package/etc/consul.d). We're working on a fix now and will make sure this change makes its way as a patch to all consul 1.11.x releases.

**Comment by mdeggies** [comment]
Update: We pushed up the empty consul.env file and made the EnvironmentFile optional to prevent errors stopping/starting the service if the file doesn't exist. These changes have been backported to all 1.9.x, 1.10.x, and 1.11.x releases and new linux package iterations have been published. Feel free to reach back out if you run into any further issues.

**Comment by mohd-akram** [comment]
The package is not updated in the RPM repo, it's currently at version 1.11.2-1.

**Comment by per-lind** [comment]
@mdeggies just did a fresh install on centos and are having the same problem. It looks like the RPM have not been published to the repo?

`Installed Packages
Name         : consul
Version      : 1.11.2
Release      : 1
Architecture : x86_64
Size         : 100 M
Source       : consul-1.11.2-1.src.rpm
Repository   : @System
From repo    : Hashicorp-repo
Summary      : Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed
             : infrastructure.
URL          : https://github.com/hashicorp/consul
License      : MPL-2.0
Description  : Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed
             : infrastructure.`

**Comment by jerrac** [comment]
I just ran into this issue on a fresh Ubuntu 18.04 install. Consul version 1.11.2. Manually adding the empty consul.env file in /etc/consul.d fixed it.
