### ISSUE TITLE
allow configuring tls version and cipher for envoy connect

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/consul#11966]
#### Feature Description

Envoy by default still allows TLS 1.0 for listeners, which has long been deprecated and is a potential security risk.
The minimum tls version, along with the supported ciphers, are configurable through the [tls_params](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlsparameters) option, however those configurations are not exposed through consul.

Requesting to expose those configurations in consul so we can tighten up the security for envoy connect tls communication.

#### Use Case(s)

Tighten up the security for connect tls.

cc @pavanrangain

**Comment by blake** [comment]
Thanks for filing this issue.

Work is currently in progress to allow configuring TLS cipher suites on ingress gateway listeners (#11576). In the future we would like to extend this support configuring min TLS ciphers for connections between sidecars.

**Comment by fredwangwang** [comment]
thanks @blake! will keep an eye on the updates

**Comment by idrennanvmware** [comment]
@mikemorris  - are all envoy sidecars supported now with this setting, or only Ingress?

**Comment by blake** [comment]
The PR that was merged only allows for conifguring TLS ciphers/versions on ingress gateways. Additional work is still needed to support a similar setting for sidecar proxies.
