### ISSUE TITLE
memberlist pushpull state size growing preventing new consul clients from joining cluster

### ISSUE THREAD

**Issue by bwaters** [hashicorp/consul#11970]
#### Overview of the Issue

New clients are unable to join the cluster successfully.  Upon inspection they have the error: 

[ERR] memberlist: failed to receive: Remote node state is larger than limit ({LARGENUMBER})

Or 

memberlist: Push/Pull with {HOSTNAME} failed: Remote node state is larger than limit ({LARGENUMBER})
 
Traced down the issue to StateLeft in memberlist not ever being purged.  Submitted PR to fix https://github.com/hashicorp/memberlist/pull/254

This Bug was introduced when StateLeft was added. https://github.com/hashicorp/memberlist/commit/237d410aa2bf83254678ef78dd638480780e54a2
https://github.com/hashicorp/consul/pull/7184

Affected versions are consul 1.7+

#### Reproduction Steps

1) Create  a new client (new name and ip address ) join it to the cluster.  
2) Do a graceful consul leave
Repeat ~100K times (with unique names / ip )

#### Consul versions where issue was observed.

Consul servers : 1.9.6
Consul clients: 
     1.10.0
     1.0.7 (Unable to receive large pushpulls from 1.10.0 nodes)

Not observed until months after 1.10.0 was added to cluster -- as it took time to build up the StateLeft list

**Comment by bwaters** [comment]
Please review the proposed fix hashicorp/memberlist#254 when StateLeft was introduced most comparisons of == StateDead were updated to n.DeadorLeft() but this one was missed.

**Comment by ryanmt** [comment]
Is there any intention to pull this back to 1.8/1.9? We see this quite a lot on the 1.8 series RN.

**Comment by kiendt07** [comment]
hi @bwaters can I ask how did you reproduce this issue? Specially how to do 100K gracefully leave effectively? Thank you.
