### ISSUE TITLE
consul can't run on Centos 7

### ISSUE THREAD

**Issue by mushixun** [hashicorp/consul#1198]
# uname -a
Linux test-srv01 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
# ./consul
Segmentation fault (core dumped)

**Comment by slackpad** [comment]
Hi @mushixun I can't seem to reproduce this crash. I used Vagrant to spin up the chef/centos-7.0 box and it seems to work fine (from a clean `vagrant up`):

```
sudo yum update
wget https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
sudo yum install unzip
unzip 0.5.2_linux_amd64.zip
```

```
[vagrant@localhost ~]$ uname -a
Linux localhost.localdomain 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[vagrant@localhost ~]$ ./consul
usage: consul [--version] [--help] <command> [<args>]

Available commands are:
    agent          Runs a Consul agent
    configtest     Validate config file
    event          Fire a new event
    exec           Executes a command on Consul nodes
    force-leave    Forces a member of the cluster to enter the "left" state
    info           Provides debugging information for operators
    join           Tell Consul agent to join cluster
    keygen         Generates a new encryption key
    keyring        Manages gossip layer encryption keys
    leave          Gracefully leaves the Consul cluster and shuts down
    lock           Execute a command holding a lock
    maint          Controls node or service maintenance mode
    members        Lists the members of a Consul cluster
    monitor        Stream logs from a Consul agent
    reload         Triggers the agent to reload configuration files
    version        Prints the Consul version
    watch          Watch for changes in Consul

[vagrant@localhost ~]$ sha256sum consul
fc35735a636f0d5c9d62ae1c537c8b2e2ed1960fb34fe810f6b9431f7646e9f1  consul
```

Can you provide more details and maybe confirm the version you are running (I've got the sha256 of the one I downloaded in the dump above). If that doesn't shed light you might want to fire up `gdb` and see if that yields any clues.

**Comment by mushixun** [comment]
Thanks for you reply，you are right，my question has solved,Thank you!!!

**Comment by slackpad** [comment]
Out of curiosity can you share what it was?

**Comment by loslosbaby** [comment]
$ uname -a
Linux zzz 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/*release|grep TTY
PRETTY_NAME="Ubuntu 15.10"
$ bin/consul
Segmentation fault (core dumped)
$

Ideas?  Not supported on 15.10?

**Comment by slackpad** [comment]
Hi @loslosbaby which version of Consul were you running on there?

**Comment by loslosbaby** [comment]
0.6.1 sorry forgot to include that :)

**Comment by loslosbaby** [comment]
Weird: I DL'd from releases.hashicorp.com (forever RHC) one one VM, got that working.  Spun two more VM's today, used the same URL (from RHC, to get 0.6.1) and I get the SEGV's.  Ok, do a sum on the machines:
working$ sum consul
34948 19939
seg1$ sum consul
45513 19882
seg2$ sum consul
45513 19882

I don't have the "working" zip file, I wget'd it into /tmp and its been boot-blasted a day ago+.  That's all I know :)

**Comment by loslosbaby** [comment]
Short and sweet:

$ strace ./consul
execve("./consul", ["./consul"], [/* 21 vars */]) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
$

**Comment by slackpad** [comment]
Hmm - I was able to set up a clean 15.10 box just now and it runs fine - must have gotten a corrupted download somehow. You can use our published shasums to make sure you've got a good binary - https://releases.hashicorp.com/consul/0.6.1/consul_0.6.1_SHA256SUMS.

**Comment by stretchkennedy** [comment]
I just spent half an hour scratching my head over this before I thought to try GDB, turns I'd grabbed the download link to the freebsd version by mistake :worried: 

Hopefully this saves someone some time in the future.

**Comment by murphy7801** [comment]
yeah just make sure you grab the right version seems to common fix.
