### ISSUE TITLE
Add docs page for `consul intention list` command

### ISSUE THREAD

**Issue by jkirschner-hashicorp** [hashicorp/consul#12036]
We have a CLI command for which there is currently no docs page: `consul intention list`. This page should follow the same format as similar CLI Command pages.

For context of how this was discovered, see https://github.com/hashicorp/consul/pull/12004#discussion_r782296004

**Comment by blake** [comment]
The docs page for this command was added in #9468, but hidden from the menu nav in #10180. The command can be re-added to the menu by removing this line 301.

https://github.com/hashicorp/consul/blob/09136441413fb3fe24bcd083b5d7332d6a9c6bed/website/data/commands-nav-data.json#L298-L302
