### ISSUE TITLE
Document precedence of config options

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/consul#1203]
There are a number of arguments that can be specified in multiple ways (CLI arg, config file option, or environment variable). It would be generally helpful if we had a standard order of precedence (which I think we already do) and documented this explicitly. For anything that doesn't follow the standard convention, we can document within that argument directly.

**Comment by brycefisher** [comment]
Yes!! I assume the cli arguments are top priority. Is that a correct assumption?

**Comment by ryanuber** [comment]
@brycefisher yep! In almost all cases, the hierarchy should be:

CLI argument > Environment variable > Config files (lexical order by file name when parsed)

During the parsing, usually sets are merged, and single-value options are replaced. Bools are overwritten only when they are specified "true" (e.g., false can't merge over true).

**Comment by brycefisher** [comment]
Thanks!!
