### ISSUE TITLE
Consul sends incorrect severity syslog messages

### ISSUE THREAD

**Issue by drTr0jan** [hashicorp/consul#12058]
#### Overview of the Issue

Consul sends incorrect severity syslog messages. All messages are with NOTICE severity.
It seems to log-facility is hardcoded in https://github.com/hashicorp/consul/blob/fabe54cbf1f04a699c6ac6e15bafef1f5a3a8cc2/logging/logger.go#L78

#### Reproduction Steps

Add to `consul.d/consul.hcl` file:
```
enable_syslog = true
```

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 3
build:
	prerelease = 
	revision = 
	version = 1.10.3
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.10.20.86:8300
	server = true
raft:
	applied_index = 11157177
	commit_index = 11157177
	fsm_pending = 0
	last_contact = 22.578622ms
	last_log_index = 11157177
	last_log_term = 32586
	last_snapshot_index = 11145948
	last_snapshot_term = 32586
	latest_configuration = [{Suffrage:Voter ID:3da039c3-eaae-db79-3f7d-6b23f1333a2e Address:10.10.20.86:8300} {Suffrage:Voter ID:c1bed5aa-021f-36fb-7f7f-94863dc08c9d Address:10.10.20.72:8300} {Suffrage:Voter ID:0acdf4f1-395b-bab9-6f8c-d74d79d7732a Address:10.10.20.87:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 32586
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 138
	max_procs = 8
	os = freebsd
	version = go1.17.2
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 378
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4643
	members = 3
	query_queue = 0
	query_time = 5
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2544
	members = 3
	query_queue = 0
	query_time = 5

</details>

### Operating system and Environment details

FreeBSD 13/stable

### Log Fragments

```
<133>1 2022-01-13T16:32:33.024371+00:00 dc01-consul consul 5949 - - 2022-01-13T16:32:33.024Z [INFO]  agent: Starting server: address=127.0.0.1:8501 network=tcp protocol=https 
<133>1 2022-01-13T16:32:33.024441+00:00 dc01-consul consul 5949 - - 2022-01-13T16:32:33.024Z [WARN]  agent: DEPRECATED Backwards compatibility with pre-1.9 metrics enabled. These metrics will be removed in a future version of Consul. Set `telemetry { disable_compat_1.9 = true }` to disable them. 
<133>1 2022-01-13T16:32:33.024508+00:00 dc01-consul consul 5949 - - 2022-01-13T16:32:33.024Z [INFO]  agent: Retry join is supported for the following discovery methods: cluster=LAN discovery_methods="aliyun aws azure digitalocean gce k8s linode mdns os packet scaleway softlayer tencentcloud triton vsphere" 
```
All log messages are gotten by syslog server with NOTICE severity (`<133>`).

**Comment by Amier3** [comment]
Hey @drTr0jan 

Thanks for pointing this out and the associated PR! We have a weekly meeting to review PRs so you should expect to hear back from us on #12079 early next week 👍

**Comment by dnephin** [comment]
Thank you for reporting this issue!

I am not all that familiar with syslog, so I had to look up the different facilities and levels. That information can be found here: https://en.wikipedia.org/wiki/Syslog#Facility. As I understand it, `facility` seems to be an identifier for the process sending the logs, and `level` is the severity.

What are you expecting to see for the facility?

The wikipedia page suggests that the syslog facility is for "Messages generated internally by syslogd", which seems like the wrong one for Consul. Maybe Consul should be using `user`, `daemon`, or one of `local0-local7` ? I'm not really sure what is normally expected for a process like Consul.

For the level, are you hoping to see the Consul log levels translated into equivalent severity in syslog? For example a WARN in consul would be a 4 "Warning" in syslog?  Or would you like to see all the logs at the same severity level in syslog, but for that level to be configurable?

Matching the Consul log level to the syslog severity level seems like it might be more correct.

**Comment by drTr0jan** [comment]
@dnephin, there's no problem with `facility`, it works great (via `config.SyslogFacility` AFAIK).

But there's a problem with `severity` (`level`). Consul log levels are not translated into equivalent severity in syslog. But It should be translated by design in `logging/syslog.go`, as you said, for example a WARN in consul would be a 4 "Warning" in syslog.

**Comment by dnephin** [comment]
Thank you for clarifying! I see the `levelPriority` map now in that code. So this does sound like a bug.
