### ISSUE TITLE
Force leave not working

### ISSUE THREAD

**Issue by wyhysj** [hashicorp/consul#1207]
Hi, accidentally add two servers (Original 3 server), and I want to force leave two server, but it won't working.

Still constantly send heartbeat to force-leave nodes

    2015/08/31 11:01:55 [INFO] Force leaving node: 10.10.16.240
    2015/08/31 11:01:58 [INFO] agent.rpc: Accepted client: 10.10.52.202:47266
    2015/08/31 11:01:58 [INFO] Force leaving node: 10.10.16.237
    2015/08/31 11:02:04 [ERR] raft: Failed to heartbeat to 10.10.16.240:8300: dial tcp 10.10.16.240:8300: connection refused
    2015/08/31 11:02:04 [ERR] raft: Failed to get log at index 261383: log not found
    2015/08/31 11:02:04 [ERR] raft: Failed to install snapshot 1468-415036-1440986556507: dial tcp 10.10.16.240:8300: connection refused
    2015/08/31 11:02:04 [ERR] raft: Failed to send snapshot to 10.10.16.240:8300: dial tcp 10.10.16.240:8300: connection refused
    2015/08/31 11:02:05 [ERR] raft: Failed to heartbeat to 10.10.16.237:8300: dial tcp 10.10.16.237:8300: connection refused
    2015/08/31 11:02:05 [ERR] raft: Failed to get log at index 261383: log not found
    2015/08/31 11:02:05 [ERR] raft: Failed to install snapshot 1468-415036-1440986556507: dial tcp 10.10.16.237:8300: connection refused
    2015/08/31 11:02:05 [ERR] raft: Failed to send snapshot to 10.10.16.237:8300: dial tcp 10.10.16.237:8300: connection refused
    2015/08/31 11:02:14 [ERR] raft: Failed to heartbeat to 10.10.16.240:8300: dial tcp 10.10.16.240:8300: connection refused
    2015/08/31 11:02:14 [ERR] raft: Failed to get log at index 261383: log not found
    2015/08/31 11:02:14 [ERR] raft: Failed to install snapshot 1468-415036-1440986556507: dial tcp 10.10.16.240:8300: connection refused
    2015/08/31 11:02:14 [ERR] raft: Failed to send snapshot to 10.10.16.240:8300: dial tcp 10.10.16.240:8300: connection refused
    2015/08/31 11:02:15 [ERR] raft: Failed to heartbeat to 10.10.16.237:8300: dial tcp 10.10.16.237:8300: connection refused
    2015/08/31 11:02:15 [ERR] raft: Failed to get log at index 261383: log not found
    2015/08/31 11:02:15 [ERR] raft: Failed to install snapshot 1468-415036-1440986556507: dial tcp 10.10.16.237:8300: connection refused
    2015/08/31 11:02:15 [ERR] raft: Failed to send snapshot to 10.10.16.237:8300: dial tcp 10.10.16.237:8300: connection refused

**Comment by slackpad** [comment]
Hi @wyhysj those failed servers are probably still in the Raft peers file. Can you see if removing them helps? See https://www.consul.io/docs/guides/outage.html for details about the peers.json file.

**Comment by wyhysj** [comment]
Thank you @slackpad , that resolves the problem.

**Comment by joelthompson** [comment]
Question on this -- according to #911, this should only be necessary if the quorom was lost. According to @wyhysj he originally had 3 servers, add 2 more, then removed those two. There should still be a quorum of the original 3 servers, right?

**Comment by sean-** [comment]
@joelthompson Provided the nodes had a chance to sync up before the other nodes were removed, yes, that is correct.  Raft requires, as a distributed finite state machine, continuity of quorum in order to make forward progress when adding log entries to Raft.  We have seen cases where servers will attempt to connect to failed servers that have been removed, but only when there are still outstanding entries in the Raft replay log that have yet to be received by the failed node.
