### ISSUE TITLE
testing: reduce verbosity of test failures

### ISSUE THREAD

**Issue by dnephin** [hashicorp/consul#12143]
Many of the tests in the `agent` and `agent/consul` are integration style tests that setup a full `Agent`, or full `Server`. These tests setup logging with the `Debug` level.

When one of these tests fail, the entire debug log is printed to stdout. I have found this makes tests difficult to debug for 2 reasons:
1. generally the most important thing we want to see is which assertion failed and where. This output is hidden in the hundreds of lines of debug logging output
2. if there are log lines relevant to the failure, they can be difficult to find. Generally I would expect those log lines to be at WARN or ERROR level. The hundreds of INFO and DEBUG lines add significant time to debug any test failure.

I propose we make the following change:
1. default the log level to `WARN`
2. add support for a `TEST_LOG_LEVEL` env var, which can be used to change the log level to DEBUG, INFO, or TRACE.

I believe that change would need to be made in at least these two places, but maybe there are more I'm not familiar with.

https://github.com/hashicorp/consul/blob/6cecd35e6e44de6cb94782613546c98fc2811f2a/agent/testagent.go#L162

https://github.com/hashicorp/consul/blob/6cecd35e6e44de6cb94782613546c98fc2811f2a/agent/consul/client_test.go#L510

The expected workflow for debugging a test would be:
1. read the test output, which should contain only the assertion failure text, and a few WARN and ERROR lines
2. if those lines do not provide enough information, re-run the test with `TEST_LOG_LEVEL=debug` to get more information. If this happens, it's a good signal that we should change the test to make it easier to debug without the full debug log. Generally by adding more information to assertions, or adding a few `t.Log` for information information that may be needed to debug a failure.

I believe this change will have the following positive benefits:
1. test failures should take less time to debug, because we'll spend less time reading hundreds of unrelated log lines
2. it will encourage writing better tests that are more explicit about why they failed
3. it should give us important signals about how useful our logs are. If we have WARN or ERROR logs that are at the wrong level, or if we're missing important warnings in our logs, we'll have a better opportunity to notice these problems.

This change should be quite small, most likely under 20 lines of test code to change.

**Comment by kisunji** [comment]
+1
