### ISSUE TITLE
Consul kv import from json is throwing json error

### ISSUE THREAD

**Issue by ajay-bongane** [hashicorp/consul#12171]
Getting error while importing consul key value pairs from json file.

Command used:
consul kv import @consul-kv.json

Json (its well formatted using intellij before using):
[
{
"key": "config/application,docker/application.yml",
"flags": 0,
"value": "c3ByaW5nOgogIHJhYmJpdG1xOgogICAgaG9zdDogcmFiYml0bXEKICBjbG91ZDoKICAgIGNvbnN1bDoKICAgICAgZGlzY292ZXJ5OgogICAgICAgIGluc3RhbmNlLWlkOiAke3NwcmluZy5hcHBsaWNhdGlvbi5uYW1lfS0ke3JhbmRvbS5pbnQoMTAwMCl9"
}
]

Error:
Cannot unmarshal data: invalid character 'ÿ' looking for beginning of value

I know it's complaining about json format or maybe file encoding. But I tried everything to ensure json is correctly formatted.
Could someone please assist on how to get rid of this error?

Appreciate your help.

**Comment by kisunji** [comment]
Hi @ajay-bongane, that error message indicates that your file is encoded as UTF-16.

It should be resolved if you save the file with UTF-8 encoding.

**Comment by ajay-bongane** [comment]
Changing the file encoding to UTF-8 helped. Thank you for the quick help.
