### ISSUE TITLE
Consul web UI: "Error while processing route: index s is undefined"

### ISSUE THREAD

**Issue by bryanhonof** [hashicorp/consul#12219]
#### Overview of the Issue

When loading the Consul web UI from firefox it throws me this page. I'm not sure if this has anything to do with my plugins/settings. Since I'm only facing this issue with Consul. No other products from the Hashistack does this, namely Nomad & Vault.

![Screenshot from 2022-01-28 14-50-13](https://user-images.githubusercontent.com/5932804/151559406-876f0bd5-ff19-4db7-acea-1ffc5fcf2d82.png)

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Open a (modified) FireFox instance
1. Go to http://consul.service.consul:8300
1. Wait :)
1. Notice the page mentioned above loaded

### Operating system and Environment details

NixOS + Home-manager. If my firefox config is of any help:
```nix
{
  programs.firefox = {
    enable = true;

    package = pkgs.firefox-wayland;

    extensions = with pkgs.nur.repos.rycee.firefox-addons; [
      bitwarden
      snowflake
      clearurls
      xbrowsersync
      decentraleyes
      ublock-origin
      https-everywhere
      simple-tab-groups
      multi-account-containers
      terms-of-service-didnt-read
    ];

    profiles.clean = {
      id = 42;
      isDefault = false;
      settings = { };
      bookmarks = { };
    };

    profiles.bjth = {
      bookmarks = { "nixos.org".url = "https://www.nixos.org"; };

      settings = {
        "privacy.firstparty.isolate" = true;
        "privacy.resistFingerprinting" = true;
        "privacy.trackingprotection.fingerprinting.enabled " = true;
        "privacy.trackingprotection.cryptomining.enabled" = true;
        "privacy.trackingprotection.enabled" = true;

        "browser.send_pings" = true;
        "browser.urlbar.speculativeConnect.enabled" = true;
        "browser.sessionstore.privacy_level" = 2;
        "browser.safebrowsing.downloads.remote.enabled" = false;
        "browser.startup.page" = 3;

        "dom.event.clipboardevents.enabled" = true;

        "media.eme.enabled" = false;
        "media.gmp-widevinecdm.enabled" = false;
        "media.navigator.enabled" = false;
        "media.ffmpeg.vaapi.enabled" = true;
        "media.ffvpx.enabled" = false;
        "media.navigator.mediadatadecoder_vpx_enabled" = true;
        "media.rdd-vpx.enabled" = true;

        "network.cookie.cookieBehavior" = 1;
        "network.http.referer.XOriginPolicy" = 2;
        "network.http.referer.XOriginTrimmingPolicy" = 2;
        "network.IDN_show_punycode" = true;
        "network.dns.disablePrefetch" = true;
        "network.dns.disablePrefetchFromHTTPS" = true;
        "network.predictor.enabled" = false;
        "network.predictor.enable-prefetch" = false;
        "network.prefetch-next" = false;

        "beacon.enabled" = false;
      };
    };
  };
}
  ```

### Log Fragments

https://gist.github.com/bryanhonof/c50798d134b8a95a8c04233099b7d6b6

**Comment by johncowen** [comment]
Hi @bryanhonof 

Thanks for the report!

Some background: Consul aims to provide a better experience for our long-polling live-updates for users using HTTP2 (taking advantage of HTTP2s multiplexed connections). Therefore, if allowed, we try to detect if you are running HTTP1 or HTTP2 on startup. There as a bug previous to 1.7.2 which didn't take into account anything that might disallow us from detecting that (which I'm guessing is detailed in the Firefox config you've provided here?)

It looks like you are running 1.7.2, so you should probably update to the last 1.7 version at least (currently 1.7.14). A fix for this exact problem was added in the version just after the version you are running (1.7.3) so at a minimum if you upgrade to that release that should solve your issue.

More details: https://github.com/hashicorp/consul/issues/7643 (specifically https://github.com/hashicorp/consul/issues/7643#issuecomment-616404968) and the corresponding fix https://github.com/hashicorp/consul/pull/7644

Let me know if that sorts your issue, if so we can close this

**Comment by bryanhonof** [comment]
Hey @johncowen 

I got to test out the latest release of `1.7` and this did indeed fix the problem. Thanks for the pointers and explanation :).
