### ISSUE TITLE
consul `maint` being blocking by ACLs

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#1223]
In the default-deny setup, it seems `consul maint` is not able to make progress even with the correct ACL tokens that have write permissions. Errors also occur on the server side for this.

/cc: @ryanuber @sean-

**Comment by ryanuber** [comment]
Looks like our tokens were only being used in query mode for `consul maint`. Above PR should fix that and thread the token through during check registration.

**Comment by sean-** [comment]
Back ported to 0.5.2 in my branch [``acl-maint``](https://github.com/sean-/consul/commit/81cbbcb6a1f5f0f010d4723305e7eb8db1c5f54f) if people in the future care or need this between now and 0.6 being released.
