### ISSUE TITLE
Bug UI parse kv error with read on prefix key

### ISSUE THREAD

**Issue by chris93111** [hashicorp/consul#12257]
Hello with policy key_prefix and read , the ui show racine kv, but she not work on recursive (403), is needed to put the full path of key in url for see the key, so it's not possible to parse kv in UI

The policy
key_prefix "service" {
  policy = "read"
}

http://consul-server/ui/datacenter/kv -> work see kv directory service

http://consul-server/ui/datacenter/kv/service/ -> denied 403

http://consul-server/ui/datacenter/kv/service/foo/bar/edit -> ok see value

one cluster consul 
Consul v1.11.1
Revision 2c56447e
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
rhel7.9

**Comment by johncowen** [comment]
Hi @chris93111 .

Thanks for dropping by! Could you upgrade to the current latest version of Consul (1.11.2) and let me know if you are still seeing the issue?

**Comment by chris93111** [comment]
@johncowen ok thanks i confirm quickly

**Comment by chris93111** [comment]
@johncowen yes is fixed with 1.11.2 thanks
