### ISSUE TITLE
Port discrepancy in documentation

### ISSUE THREAD

**Issue by johnalotoski** [hashicorp/consul#12253]
The documents refer to port usage in one place [here](https://www.consul.io/docs/connect/proxies/built-in#bind_port) as having a range starting at 20,000.  However, the link provided shows the linked option referencing the default as 21,000 [here](https://www.consul.io/docs/agent/options#sidecar_min_port).

Also, it appears the default consul port range for the sidecar min and max and expose min and max ports of 21,000 to ~22,000 range falls within the default dynamic port assignment range of nomad which is 20,000 to 32,000.  While nomad's dynamic port range is configurable as shown [here](https://www.nomadproject.io/docs/configuration/client#min_dynamic_port), it might be worth pointing that out in the docs since a collision between consul use of dynamic ports and nomad attempted use of dynamic ports will cause nomad to fail on job deployments as mentioned [here](https://github.com/hashicorp/nomad/issues/4285).

**Comment by blake** [comment]
Hi @johnalotoski,

Thanks for bringing this discrepancy to our attention. I created a PR to fix the docs on the Consul side.

I'll separately see about updating Nomad's docs for the [Connect integration](https://www.nomadproject.io/docs/integrations/consul-connect) to bring attention to this this conflict. Do you think it would be sufficient if we added a call out stating that Nomad's dynamic port range overlaps with the range used by Consul service mesh, and recommend operators configure [client.options.reserved.reserved_ports](https://www.nomadproject.io/docs/configuration/client#reserved_ports) on the Nomad clients to exempt the ports 21000-21255 and 21500-21755 from Nomad's dynamic port allocation range?

**Comment by johnalotoski** [comment]
Sure, that works, thanks!  In our case, we [bumped nomad's min range start](https://github.com/input-output-hk/bitte/blob/prem-prep/profiles/nomad/client.nix#L44-L54) by 2,000 to start at 22,000 and therefore no overlap.  Either way works.  Appreciate the update!
