### ISSUE TITLE
Find the HTTP api via dig

### ISSUE THREAD

**Issue by btrepp** [hashicorp/consul#1226]
Hi there.

I'm not sure if this is possible, but I would like to be able to find the HTTP api in my application by using a dig request.

Eg I may have a machine that can't run the consul agent, but I can get the DNS configured to point/resolve consul DNS queries.

In this case is there a way I could issue a SRV request to get the IP/Port of the HTTP API?. That way all my application would need to know on startup is to issue a DNS call to find consul, then use the HTTP api etc to read KEY/values it requires.

I won't use dig in my application, but if someone has an example of using it to find a consul agent via dns that would be great.

**Comment by slackpad** [comment]
Hi @btrepp if you plumb DNS like you've said here then you could find a Consul server using the built-in consul service, which would be something like http://consul.service.consul:8500/v1/...

**Comment by highlyunavailable** [comment]
Yep, what @slackpad said is what you could easily do.

Note that the HTTP API by default only binds to loopback, so if you want to run HTTP queries, you'll need to [rebind the HTTP address](https://www.consul.io/docs/agent/options.html#addresses).

I'm not sure what the port in the SRV record would be though for the `consul` service, but you could just assume it's on 8500 by default.

**Comment by slackpad** [comment]
Interesting detail @highlyunavailable - the port for the built in Consul service is set to the internal RPC port, not the HTTP server, so you're right you'd have to assume it's 8500 (or whatever it's configured for), or put it in KV, etc.

https://github.com/hashicorp/consul/blob/master/command/agent/agent.go#L170

**Comment by btrepp** [comment]
consul.service.consul was it :). Thanks.

Assuming 8500 is okay for now. Though It may be cool to add an api.service.consul endpoint?. That way we could discover everything about the key/value store, and query it from there.

**Comment by slackpad** [comment]
Yeah I'll think about if there's a clean way to do it. Since it's not exposed by default it might be confusing to always publish it.
