### ISSUE TITLE
Topology view should show cross-datacenter upstreams

### ISSUE THREAD

**Issue by chrisjohnson** [hashicorp/consul#12353]
### Overview of the Issue

We have a set of ingress gateways in one datacenter whose purpose is feed traffic into services in other datacenters. These are set up using service-resolvers with a `failover` block -- the point to services that don't exist in the local datacenter so it's always "failing over".

Currently the topology and routing views are very useful for same-datacenter traffic, but they do not reflect this traffic.

### Describe the solution you'd like

It would be nice if the topology view reflected this sort of cross-datacenter traffic. We're trying to teach our users to refer to the consul UI for learning about the networking and currently if you view the topology view of these ingress gateways they show no other services.

### Consul Version

1.9.7+ent

### Browser and Operating system details

MacOS firefox/chrome

### Screengrabs / Web Inspector logs

Picture of the services list showing that the ingress gateway has 2 upstreams

![image](https://user-images.githubusercontent.com/178144/154106141-d045054b-ffc3-488e-a506-62483351fce7.png)

Picture of the topology view which shows no upstreams

![image](https://user-images.githubusercontent.com/178144/154106208-46423683-c420-4b6a-aa16-39f59377bd0c.png)

However the upstreams view does list them (albeit with incorrect URLs -- since these services don't live in az-east datacenter)

![image](https://user-images.githubusercontent.com/178144/154106303-5ff3c2d8-d99f-4169-8bb8-cff8a0ba7a2b.png)

**Comment by johncowen** [comment]
Hey @chrisjohnson 

I'm just checking on your second problem here

> However the upstreams view does list them (albeit with incorrect URLs -- since these services don't live in az-east datacenter)

Would you be able to check the HTTP response (Web Inspector will give you this) 

`/v1/internal/ui/gateway-services-nodes/<your-gateway-name>?dc=<your-dc-name>`

You should see under `GatewayConfig.Addresses` in there with all the hostnames. I'm guessing these are incorrect in the HTTP response? If so I 'think' we can triage this portion of the issue here as a backend issue.

Let me know when you get a a moment, thanks!

**Comment by johncowen** [comment]
Awesome, thanks @chrisjohnson !

So if I understand correctly the `Gateway.Address` in that response is wrong?

```json
{"Addresses":["consentaur.ingress.integration-master.az-east.consul:443"]}
```

If that's the case, then maybe a separate issue might be best, let me know if that URL is incorrect/not what you are expecting and I can try and double check here first.

Separate from this of course is still the issue of showing cross-datacenter upstreams in the topology view.

**Comment by chrisjohnson** [comment]
Ok, so for example this is the upstreams page for `patient-hub-ingress-gateway-production`, found in the `production` namespace in the `az-east` datacenter. Here is the config entry for that ingress gateway:

```
$ consul config read -kind ingress-gateway -namespace=production -name patient-hub-ingress-gateway-production
{
    "Kind": "ingress-gateway",
    "Name": "patient-hub-ingress-gateway-production",
    "Namespace": "production",
    "TLS": {
        "Enabled": true
    },
    "Listeners": [
        {
            "Port": 443,
            "Protocol": "http",
            "Services": [
                {
                    "Name": "consentaur",
                    "Hosts": null,
                    "Namespace": "production"
                },
                {
                    "Name": "customs",
                    "Hosts": null,
                    "Namespace": "production"
                }
            ]
        }
    ],
    "CreateIndex": 3809210,
    "ModifyIndex": 3809210
}
```

And e.g. the service-resolver called `consentaur` that actually routes traffic cross-datacenter:

```
$ consul config read -kind=service-resolver -namespace=production -name=consentaur
{
    "Kind": "service-resolver",
    "Name": "consentaur",
    "Namespace": "production",
    "DefaultSubset": "active",
    "Subsets": {
        "active": {
            "Filter": "Service.Meta.dc_mode == active"
        },
        "passive": {
            "Filter": "Service.Meta.dc_mode == passive"
        }
    },
    "Failover": {
        "active": {
            "Namespace": "production",
            "Datacenters": [
                "at",
                "lc"
            ]
        }
    },
    "CreateIndex": 3809208,
    "ModifyIndex": 3809208
}
```

-----

Given that context, here's a dig against the consentaur ingress DNS name:

```
dig +short consentaur.ingress.production.az-east.consul
10.5.164.30
```

This correctly resolves to the *ingress gateway itself*. Given that, I would not expect *the upstream services that the ingress gateway talks to* to be defined as a DNS name that resolves to the ingress gateway itself. I would expect the Gateway.Address to return a list of DNS names (one for each datacenter configured in the failover) more like this:

```
consentaur.service.production.lc.consul
consentaur.service.production.at.consul
```

Alternatively it may be that the upstreams endpoint should be returning 4 records here? 1 for each of the 2 services in each of the 2 datacenters? I'm not entirely sure what makes sense there.

**Comment by johncowen** [comment]
Hey @chrisjohnson 

I reached out to one of my team mates who was involved in building this functionality out, I figured he'd be able to help better with this gateway address related query. 

Over to you @crhino 👍

**Comment by crhino** [comment]
👋 

> I would not expect the upstream services that the ingress gateway talks to to be defined as a DNS name that resolves to the ingress gateway itself. I would expect the Gateway.Address to return a list of DNS names (one for each datacenter configured in the failover) more like this:

The motivation behind that view in the Consul UI is to tell users how to ingress traffic for the specific services. So for your example, `consentaur.ingress.production.az-east.consul` is a DNS address that an application could use to send traffic to your `consentaur` service. The ingress gateway will use that specific address to route the HTTP requests appropriately. That is why the backing IP address is the ingress gateway, not the upstream service.

Does that make sense? Would love to hear your thoughts on making that clearer or other improvements!

**Comment by chrisjohnson** [comment]
> Does that make sense? Would love to hear your thoughts on making that clearer or other improvements!

Ok on reviewing and thinking this through, I think I do agree. It's not the upstream URL, it's the "how to reach that upstream through this gateway" URL. I do think a tooltip that says something to this effect "the URL for which you can reach customs through this gateway" when you mouse over the URL for the customs upstream would help the clarity on this page. I'm not sure if it's worth me opening a ticket over that or if you want to track it internally?

I still think the topology not reflecting this traffic at all is something that does need resolved but that's what the original ticket is about.

**Comment by johncowen** [comment]
> I still think the topology not reflecting this traffic at all is something that does need resolved but that's what the original ticket is about.

Yup, completely agree there

> I do think a tooltip that says something to this effect "the URL for which you can reach customs through this gateway" when you mouse over the URL for the customs upstream would help the clarity on this page.

That would be a great little improvement off the back of this I think. Feel free to open an issue if you want or not also, if you do you'll be notified when it gets closed (or I can try and remember to come back here and ping when we add that). Otherwise I'll be tracking this internally also.

So just to sum up and partly for my future self:

Main issue still stands (Topology view should show cross-datacenter upstreams) We need to show topology for ingress gateways, and at first glance this seems to be something we'd need at an API/backend level. I still need to look a little further at the topology view and how it should work to make sure this isn't a UI bug, pretty sure its a backend thing though.

The sub issue here is resolved, but we could do a much better job at messaging this as its not super clear what the data shown means (see Chris's suggestion above)

**Comment by chrisjohnson** [comment]
We upgraded to 1.10.9 and don't see this anymore so I'm going to assume this was just a 1.9.x issue
