### ISSUE TITLE
acl rules for key "_rexec/" can be bypassed by consul exec -prefix=anything_else

### ISSUE THREAD

**Issue by half-dead** [hashicorp/consul#1238]
We want to enable "consul exec" only on server side, allow all service registrations and k/v writes for all clients.
I can't find a way to do this under consul version 0.5.2, I think this maybe a design flaw.

**Comment by slackpad** [comment]
Hi @half-dead - can you configure your cluster so KV writes for the clients are default deny, and then just open up the KV space for the areas they should access? This should prevent them from choosing some other prefix to exec on.

**Comment by half-dead** [comment]
I can do that, but still, key "_rexec" {policy="deny"} and consul exec -prefix are contradictory, any chance this can be fixed?

**Comment by slackpad** [comment]
Hi @half-dead - I don't think I follow where the contradiction is - can you clarify or provide an example?

I was thinking something like this spec to deny exec (

```
"key": {
  "": {
    "policy": "deny"
  },
  "/some/client/namespace" : {
    "policy": "write"
  }
}
```

**Comment by slackpad** [comment]
Oh I see, you mean you can exec inside the allowed key space that the clients can write to.

In 0.6 you will be able to deny firing events, but it's pretty easy to forget to configure that and open up this hole. It seems like maybe if you aren't allowed to write to "_rexec" then you shouldn't be able to exec on any other prefix (kind of an implied extension of the ACL), plus we'd look at your ACL for the prefix as well. This might be a little subtle to explain, but it would work without a new ACL type. Alternative could be a first class exec ACL.

I'll ping @armon and @ryanuber for their thoughts on the interface for this.

**Comment by houtmanj** [comment]
It would indeed be nice to be-able to restrict which the use of exec using the ACL's. It would then make for a good replacement of our mcollective deploy stack. 

How about making exec an full member of the acl and allowing the acl's to limit the commands that the client can run. It wont help with scripts passed by stdin, but its a nice step to making sure only the deploy stack can run the deploy scripts remotely. 

exec "" {
policy = "deny"
}

exec "/usr/bin/yum update" {
  policy = "allow"
}

exec "/usr/local/bin/deploy_app *" {  # allow for some variance 
 policy = "allow"
}

**Comment by arobson** [comment]
@slackpad what's the latest on this one? I would really like to adopt Consul, but can't put it into production until we're able to prevent remote execution via this method.

**Comment by slackpad** [comment]
Hi @arobson this didn't make the cut for 0.6 (we've already got a huge scope) but we will try to get this into the next release, which should be turned around much more quickly than 0.5.2 -> 0.6 was.

**Comment by split3** [comment]
Indeed I would love to see this as well, almost something similar to like sudoers in which we can allow certain commands via a particular ACL.  The scope on this could easily grow very cumbersome as there are lots of options that I can see people wanting to have.

So is the current safe way in 0.6.x to make sure that no one can execute if the default policy is deny is just make sure the token doesn't have the _rexec allowed?

**Comment by slackpad** [comment]
@split3 for now you should disable writes to "_rexec" in the KV store *and* disable firing events (or at least disable firing the "_rexec" event). This will prevent agents from using some other prefix to do remote exec. You can also set https://www.consul.io/docs/agent/options.html#disable_remote_exec to prevent an agent from responding to any remote exec requests.

**Comment by rajkashikar** [comment]
I would like a few 'admin nodes' to execute commands on the whole cluster. How would I do that?  currently I am on 0.6.3

**Comment by slackpad** [comment]
@rajkashikar the admin nodes should be the only ones allowed to fire the "_rexec" event via ACLs and that should allow them to trigger execs and still have other nodes be able to carry out the exec operation.

**Comment by slackpad** [comment]
So as noted in https://github.com/hashicorp/consul/issues/1238#issuecomment-185015141 you can disable exec with ACLs by disabling the `_rexec` event. We are going to document this better, and in Consul 0.8 we will change the default for [`disable_remote_exec`](https://www.consul.io/docs/agent/options.html#disable_remote_exec) to `true` so you have to opt-in.
