### ISSUE TITLE
Telemetry including host in the metric name

### ISSUE THREAD

**Issue by scalp42** [hashicorp/consul#1241]
Hi folks,

I noticed that some of the metrics include the consul host:

```
consul.consul-i-8de39448.runtime.total_gc_pause_ns
consul.consul-i-8de39448.runtime.num_goroutines
```

vs

```
consul.consul.catalog.deregister
consul.consul.fsm.kvs.lock
```

Is there a way to not have Consul include the host in the metric (which makes it act as a different metric, later instead of former) ?

This way we dont have to rely on extracting the source host from the metricic using regexes.

**Comment by slackpad** [comment]
Hi @scalp42 it doesn't look like that's exposed via any Consul configuration right now. Unless that gets added, you'd have to make a mod here and build Consul:

https://github.com/hashicorp/consul/blob/master/command/agent/command.go#L572

**Comment by scalp42** [comment]
That's a bummer, the source should not be in the metric name (only a few of them have the metric name in it).

**Comment by nbrownus** [comment]
It's an artifact of how the telemetry library works. It would probably be trivial to port the fix for this from `vault`

https://github.com/hashicorp/vault/pull/419

**Comment by scalp42** [comment]
Having the hostname in the metric kill us and it ends up duplicating a shit ton of metrics (vs datadog where you would pay per host for example).
