### ISSUE TITLE
Allow keyring operations from clients

### ISSUE THREAD

**Issue by danieleva** [hashicorp/consul#12422]
#### Feature Description

All keyring operations via http api are restricted to consul servers. Hitting `/operator/keyring` on a client http port triggers an error because of https://github.com/hashicorp/consul/blob/main/agent/keyring.go#L236-L238.
I tried to walk git history to find the reason for that restriction, and I can't find anything explicit. The oldest commit I can find mentioning keyring operations is 4dd1b4247 from ages ago, and back in the days I think it made sense to have that restriction as there was no proper RPC forwarding for the operation, but that issue is long gone.
I did a quick test and built a modified binary removing the check, and it works just fine. I'm wondering if there is some other reason for the restriction, otherwise I'm going to submit a PR to remove it.

#### Use Case(s)

I need to setup an automated process to rotate gossip keys and I was building a dedicated tool for it. The process will have access to consul api via a consul agent running as client. The https interface for the servers is not accessible, and I'd like to keep it that way and not be forced to run the key rotation process next to the servers.

**Comment by jkirschner-hashicorp** [comment]
Hi @danieleva,

Thanks for reaching out and offering to contribute to Consul!

We discussed this internally and concluded that this is a fine change to make - go ahead and submit a PR at your convenience (and describe the testing you did in the PR description for the benefit of the reviewer).

We don't see any reason (engineering, security, etc) to only allow RPC forwarding of this request from server agents, it's fine to expand to forwarding from client agents as well by removing the code lines you linked to.

We agree that the linked code limiting only to servers predates RPC forwarding for this operation and is no longer necessary.

Thanks!

**Comment by danieleva** [comment]
Awesome, thank you for the quick reply :)
