### ISSUE TITLE
Why consul cluster changes leader rapidly

### ISSUE THREAD

**Issue by zhouzhongmi** [hashicorp/consul#1247]
I have four services in a cluster with consul version 0.5.2.
>server1: consul agent -server -bootstrap-expect 3 -config-dir=/etc/consul/ -data-dir=/home/htdocs/ -bind=10.127.65.93 -node=consul.test.com-65.93 -dc=bx-2
>server2: consul agent -server -bootstrap-expect 3 -config-dir=/etc/consul/ -data-dir=/home/htdocs/ -bind=10.127.65.84 -node=consul.test.com-65.84 -dc=bx-2
>server3: consul agent -server -bootstrap-expect 3 -config-dir=/etc/consul/ -data-dir=/home/htdocs/ -bind=10.127.3.11 -node=consul.test.com-3.11 -dc=bx-2
>server4: consul agent -server -bootstrap-expect 3 -config-dir=/etc/consul/ -data-dir=/home/htdocs/ -bind=10.127.3.12 -node=consul.test.com-3.12 -dc=bx-2

>cat /etc/consul/config.json 
{
        "data_dir": "/home/htdocs",
        "client_addr": "0.0.0.0",
        "ports": {
                "http": 8500
        },
        "recursor": "8.8.8.8",
        "disable_update_check": false
}

I registered to a node of the cluster with 400 services and checks. The leader begins to output  something like that (as bellow). I was confused why consul cluster changes leader so rapidly.
---------------------------
    2015/09/18 18:02:33 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.235903ms
    2015/09/18 18:02:34 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.25808ms
    2015/09/18 18:02:34 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.21919ms
    2015/09/18 18:02:36 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.257853ms
    2015/09/18 18:02:37 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.264037ms
    2015/09/18 18:02:42 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.275296ms
    2015/09/18 18:02:43 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.262698ms
    2015/09/18 18:02:43 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.201654ms
    2015/09/18 18:02:44 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.214846ms
    2015/09/18 18:02:46 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.18888ms
    2015/09/18 18:02:47 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.18885ms
    2015/09/18 18:02:47 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.193497ms
    2015/09/18 18:02:48 [WARN] raft: Failed to contact 10.127.3.11:8300 in 992.710706ms
    2015/09/18 18:02:49 [WARN] raft: Failed to contact 10.127.3.11:8300 in 500.257575ms
    2015/09/18 18:02:49 [WARN] raft: Rejecting vote from 10.127.3.11:8300 since we have a leader: 10.127.65.93:8300
    2015/09/18 18:02:49 [ERR] raft: peer 10.127.3.11:8300 has newer term, stopping replication
    2015/09/18 18:02:49 [INFO] raft: Node at 10.127.65.93:8300 [Follower] entering Follower state
    2015/09/18 18:02:49 [INFO] raft: aborting pipeline replication to peer 10.127.3.11:8300
    2015/09/18 18:02:49 [INFO] consul: cluster leadership lost
    2015/09/18 18:02:49 [INFO] raft: aborting pipeline replication to peer 10.127.65.84:8300
    2015/09/18 18:02:49 [INFO] raft: aborting pipeline replication to peer 10.127.3.12:8300
    2015/09/18 18:02:50 [WARN] raft: Heartbeat timeout reached, starting election
    2015/09/18 18:02:50 [INFO] raft: Node at 10.127.65.93:8300 [Candidate] entering Candidate state
    2015/09/18 18:02:51 [INFO] raft: Duplicate RequestVote for same term: 91
    2015/09/18 18:02:51 [WARN] raft: Election timeout reached, restarting election
    2015/09/18 18:02:51 [INFO] raft: Node at 10.127.65.93:8300 [Candidate] entering Candidate state
    2015/09/18 18:02:52 [INFO] raft: Node at 10.127.65.93:8300 [Follower] entering Follower state
    2015/09/18 18:02:52 [INFO] consul: New leader elected: consul.test.com-3.12
    2015/09/18 18:02:54 [WARN] raft: Rejecting vote from 10.127.3.11:8300 since we have a leader: 10.127.3.12:8300
    2015/09/18 18:03:06 [WARN] raft: Rejecting vote from 10.127.3.11:8300 since we have a leader: 10.127.3.12:8300
    2015/09/18 18:03:09 [WARN] raft: Rejecting vote from 10.127.3.11:8300 since we have a leader: 10.127.3.12:8300
    2015/09/18 18:03:09 [WARN] raft: Heartbeat timeout reached, starting election
    2015/09/18 18:03:09 [INFO] raft: Node at 10.127.65.93:8300 [Candidate] entering Candidate state
    2015/09/18 18:03:09 [INFO] raft: Node at 10.127.65.93:8300 [Follower] entering Follower state
    2015/09/18 18:03:09 [INFO] consul: New leader elected: consul.test.com-3.12
    2015/09/18 18:03:24 [INFO] memberlist: Suspect consul.test.com-3.11 has failed, no acks received
    2015/09/18 18:03:44 [INFO] memberlist: Suspect consul.test.com-3.11 has failed, no acks received
    2015/09/18 18:03:49 [INFO] memberlist: Marking consul.test.com-3.11 as failed, suspect timeout reached
    2015/09/18 18:03:49 [INFO] serf: EventMemberFailed: consul.test.com-3.11 10.127.3.11
    2015/09/18 18:03:49 [INFO] consul: removing server consul.test.com-3.11 (Addr: 10.127.3.11:8300) (DC: bx-2)
    2015/09/18 18:03:55 [INFO] serf: EventMemberJoin: consul.test.com-3.11 10.127.3.11
    2015/09/18 18:03:55 [INFO] consul: adding server consul.test.com-3.11 (Addr: 10.127.3.11:8300) (DC: bx-2)
    2015/09/18 18:04:07 [INFO] memberlist: Suspect consul.test.com-3.11 has failed, no acks received
    2015/09/18 18:04:12 [INFO] memberlist: Marking consul.test.com-3.11 as failed, suspect timeout reached
    2015/09/18 18:04:12 [INFO] serf: EventMemberFailed: consul.test.com-3.11 10.127.3.11
    2015/09/18 18:04:12 [INFO] consul: removing server consul.test.com-3.11 (Addr: 10.127.3.11:8300) (DC: bx-2)
    2015/09/18 18:04:22 [WARN] raft: Rejecting vote from 10.127.3.11:8300 since we have a leader: 10.127.3.12:8300
    2015/09/18 18:04:23 [WARN] raft: Rejecting vote from 10.127.3.11:8300 since we have a leader: 10.127.3.12:8300
    2015/09/18 18:04:24 [WARN] raft: Rejecting vote from 10.127.65.84:8300 since we have a leader: 10.127.3.12:8300
    2015/09/18 18:04:24 [WARN] raft: Heartbeat timeout reached, starting election
    2015/09/18 18:04:24 [INFO] raft: Node at 10.127.65.93:8300 [Candidate] entering Candidate state
    2015/09/18 18:04:24 [INFO] raft: Node at 10.127.65.93:8300 [Follower] entering Follower state
    2015/09/18 18:04:24 [INFO] consul: New leader elected: consul.test.com-3.12
    2015/09/18 18:04:25 [INFO] serf: EventMemberJoin: consul.test.com-3.11 10.127.3.11
    2015/09/18 18:04:25 [INFO] consul: adding server consul.test.com-3.11 (Addr: 10.127.3.11:8300) (DC: bx-2)
    2015/09/18 18:04:44 [INFO] memberlist: Suspect consul.test.com-3.11 has failed, no acks received
    2015/09/18 18:05:00 [INFO] memberlist: Suspect consul.test.com-3.11 has failed, no acks received
    2015/09/18 18:05:05 [INFO] memberlist: Marking consul.test.com-3.11 as failed, suspect timeout reached
    2015/09/18 18:05:05 [INFO] serf: EventMemberFailed: consul.test.com-3.11 10.127.3.11
    2015/09/18 18:05:05 [INFO] consul: removing server consul.test.com-3.11 (Addr: 10.127.3.11:8300) (DC: bx-2)
    2015/09/18 18:05:09 [INFO] serf: EventMemberJoin: consul.test.com-3.11 10.127.3.11
    2015/09/18 18:05:09 [INFO] consul: adding server consul.test.com-3.11 (Addr: 10.127.3.11:8300) (DC: bx-2)
    2015/09/18 18:05:12 [INFO] serf: EventMemberLeave: consul.test.com-65.84 10.127.65.84
    2015/09/18 18:05:12 [INFO] consul: removing server consul.test.com-65.84 (Addr: 10.127.65.84:8300) (DC: bx-2)
    2015/09/18 18:05:23 [INFO] serf: EventMemberLeave: consul.test.com-3.11 10.127.3.11
    2015/09/18 18:05:23 [INFO] consul: removing server consul.test.com-3.11 (Addr: 10.127.3.11:8300) (DC: bx-2)
---------------------------

**Comment by slackpad** [comment]
Hi @zhouzhongmi - are you running consul-template, or any other service that does a high number of watch queries against Consul? There are some known read performance issues that we are working to fix now - https://github.com/hashicorp/consul/issues/1150.

**Comment by zhouzhongmi** [comment]
Hi @slackpad - Thank you for your considering with my questions. I just running a consul cluster without consul-template. As I have registered about 400 services and checks, I suspect whether the 400 checks cause the problem. Each of my checks registered with a interval as 2 seconds by the HTTP method. Now I will try to register my services and checks randomly into the cluster and enlarge my cluster with more servers. Thank you very much. I'm looking forward to a more powerful version of consul.

**Comment by slackpad** [comment]
Closing this out as Consul 0.6.0 has been released, and it looks like you had a workaround.
