### ISSUE TITLE
Unable to download latest Consul release binary from releases.hashicorp.com

### ISSUE THREAD

**Issue by nahsi** [hashicorp/consul#12477]
#### Overview of the Issue
I've tried to download and install Consul version 1.11.4 on test environment, but I'm unable to do so.

Access from Russia is denied, I suspect Fastly is blocking Russia.

![image](https://user-images.githubusercontent.com/28529663/156145057-29db6482-5aa5-45e2-8146-16d44e65bd8a.png)

Here is a topic on HashiCorp discuss forums https://discuss.hashicorp.com/t/access-to-releases-hashicorp-com-is-denied/36348

**Comment by Amier3** [comment]
We're sorry, but because of the conflict underway in Ukraine, HashiCorp is prohibiting availability of our products and services in Russia and Belarus.
