### ISSUE TITLE
Consul 0.5.2 restart after Go GC panic

### ISSUE THREAD

**Issue by jsullivan3** [hashicorp/consul#1248]
A user running Consul 0.5.2 build with Go 1.4 reported a Consul service restart, and found the following panic in the error logs:

    fatal error: casgstatus: waiting for Gwaiting but is Grunnable
 
This error appears to be related to the following change in the Go 1.4 garbage collector:
[https://codereview.appspot.com/184030043/] (https://codereview.appspot.com/184030043/)
 
The user does not make use of Consul templates.
 
Thirteen services running on this node will be found by Consul.  Approximately fifty other services are configured to be checked by Consul but are not running, so they will be reported as unhealthy on this node.
 
Service discovery on this node was being performed via DNS.

**Comment by jsullivan3** [comment]
Error log is available here:

[https://gist.github.com/jsullivan3/7b50e95ea28888a67462#file-gistfile1-txt] (https://gist.github.com/jsullivan3/7b50e95ea28888a67462#file-gistfile1-txt)

**Comment by jsullivan3** [comment]
The vast majority of the service configurations appear as follows:
```
{
  "service": {
    "name": "foo",
    "tags": ["bar"],
    "port": 553
  },
  "check": {
    "id" : " foo ",
    "name" : " foo http check",
    "http": "http://localhost:553/ foo ",
    "interval": "60s",
    "service_id": " foo "
  }
}
```

**Comment by slackpad** [comment]
Going to close this out - we haven't seen any similar reports with newer versions of Go.
