### ISSUE TITLE
DNS with tag filtering is not working as expected

### ISSUE THREAD

**Issue by ltagliamonte-dd** [hashicorp/consul#12537]
using tags as filter over DNS protocol doesn't work as HTTP api.
How to reproduce the issue:

Start a local consul instance:
```
docker run -it --rm --name=dev-consul -p 8500:8500 -p 8600:8600 -e CONSUL_BIND_INTERFACE=eth0 consul
```
Create 3 endpoints (2 in us-1 and 1 in us-2)
```
for i in {0..1}
do
cat <<EOF > payload.json
{
  "Node": "foobar",
  "Address": "192.168.10.10",
  "Service": {
    "ID": "deploy${i}",
    "Service": "deployment-service-web",
    "Address": "192.168.1.40${i}",
    "Port": 8000,
    "Tags": ["us-1"]
  }
}
EOF
curl --request PUT --data @payload.json http://127.0.0.1:8500/v1/catalog/register
done

cat <<EOF > payload.json
{
  "Node": "foobar",
  "Address": "192.168.10.10",
  "Service": {
    "ID": "deploy2",
    "Service": "deployment-service-web",
    "Address": "192.168.1.402",
    "Port": 8000,
    "Tags": ["us-2"]
  }
}
EOF
curl --request PUT --data @payload.json http://127.0.0.1:8500/v1/catalog/register
```

by using the following http api:
`curl http://127.0.0.1:8500/v1/catalog/service/deployment-service-web`
you will correctly obtain 3 IPs

by using the following http api:
`curl http://127.0.0.1:8500/v1/catalog/service/deployment-service-web?tag=us-1`
you will correctly obtain 2 IPs

by using the following http api:
`curl  http://127.0.0.1:8500/v1/catalog/service/deployment-service-web?tag=us-2`
you will correctly obtain 1 IP

Using the DNS protocol doesn't seem to return the same output:
`dig +tcp @127.0.0.1 -p8600 deployment-service-web.service.consul` returns 1 IP from the whole set -> expected 3
`dig +tcp @127.0.0.1 -p8600 us-1.deployment-service-web.service.consul` returns 1 IP from the subset -> expected 2
`dig +tcp @127.0.0.1 -p8600 us-2.deployment-service-web.service.consul` returns 1 IP from the subset

**Comment by Amier3** [comment]
Hey @ltagliamonte-dd 

Thanks for bringing this to our attention. We'll look into this and keep you updated on what we find 👍

**Comment by jkirschner-hashicorp** [comment]
> Using the DNS protocol doesn't seem to return the same output:
dig +tcp @127.0.0.1 -p8600 deployment-service-web.service.consul returns 1 IP from the whole set -> expected 3

The example above you provided doesn't use tags and still only returns a single IP address. Is it fair to say that the problem you are experiencing is with the DNS interface generally (even without using tags in a DNS query)?

**Comment by ltagliamonte-dd** [comment]
@jkirschner-hashicorp thank you for replying, if you add endpoints without tags, the following query:
```
dig +tcp @127.0.0.1 -p8600 deployment-service-web.service.consul
```
returns 3 IPs, so I'm expecting the same behavior with or without tags.

**Comment by kisunji** [comment]
@ltagliamonte-dd Could you try using a SRV query:
```
❯ dig +tcp @127.0.0.1 -p 8600 deployment-service-web.service.consul SRV

; <<>> DiG 9.10.6 <<>> +tcp @127.0.0.1 -p 8600 deployment-service-web.service.consul SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30848
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;deployment-service-web.service.consul. IN SRV

;; ANSWER SECTION:
deployment-service-web.service.consul. 0 IN SRV	1 1 8000 192.168.1.401.
deployment-service-web.service.consul. 0 IN SRV	1 1 8000 192.168.1.400.
deployment-service-web.service.consul. 0 IN SRV	1 1 8000 192.168.1.402.

;; Query time: 0 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Wed Mar 16 15:06:48 EDT 2022
;; MSG SIZE  rcvd: 165
```

When we query for the default DNS A record, we consider it a query on the Node and not the services: https://github.com/hashicorp/consul/blob/0546bbe08a0c8d8c8933a941c75ec91231542378/agent/dns.go#L1337-L1343

If you peek in `serviceNodeRecords` you can see that it only takes the first CNAME and discards everything else. I'm not too familiar with DNS servers so I can't say if this is correct behavior or not but it explains why you were only seeing one address without SRV.

**Comment by ltagliamonte-dd** [comment]
thank you for following up, I still believe this is a bug or an undocumented behavior.

I'm assuming that the DNS protocol should behave as the REST protocol when it comes tag filtering.
Is there a reason why the DNS protocol doesn't behave as the REST protocol?

Without knowing all the internals I would assume that the following behaviors should be the same:
`A` type request for `deployment-service-web.service.consul`  **with the service having 3 IPs with no tags returns 3 IPs**
`A` type request for `deployment-service-web.service.consul` **with the service having 3IPs with tags returns 3 IPs**

Without knowing all the internals I would assume that:
`A` type request for `us-1.deployment-service-web.service.consul` **with a service that has 3IPs with 2 of this IPs tagged `us-1` would return 2 IPs.

All this examples work as expected using the REST api.

**Comment by kisunji** [comment]
I got a more detailed response from the team:
- The `Service.Address` you are using is not a valid IP address therefore Consul considers them to be hostnames.
- DNS A RR queries can only return 1 CNAME so the rest are dropped from the response.

If you use valid IP addresses as `Service.Address` the tag filtering will work as expected.

**Comment by ltagliamonte-dd** [comment]
@kisunji thank you for the follow up, I tried to replicate on my end with the setup i provided and I can confirm your analysis is correct, however my consul server installation in prod returns all the IPs associated to a service, so I retried with a much more realistic setup mirroring as much as i can my prod setup and the behavior works as expected, so we can close the issue.

I can't identify yet why in docker is not working.

For people interested this is a working setup, **not in docker**:
- Download the consul binary locally (I have it on my Desktop folder)

execute:
```
mkdir -p consul/data

cat <<'EOF' >> consul.json
{
  "enable_script_checks": false,
  "enable_local_script_checks": true,
  "skip_leave_on_interrupt": true,
  "disable_update_check": true,
  "discovery_max_stale": "48h",
  "disable_remote_exec": true,
  "http_config": {
    "allow_write_http_from": [
      "127.0.0.0/8",
      "::1/128"
    ]
  },
  "dns_config": {
    "allow_stale": true,
    "enable_truncate": true,
    "only_passing": true,
    "node_ttl": "1m",
    "service_ttl": {
      "*": "10s"
    },
    "use_cache": true,
    "cache_max_age": "5s",
    "enable_additional_node_meta_txt": false,
    "soa": {
      "expire": 86400,
      "min_ttl": 30,
      "refresh": 3600,
      "retry": 600
    }
  },
  "performance": {
    "raft_multiplier": 3
  },
  "ports": {
    "https": 8501
  },
  "telemetry": {
    "disable_hostname": true,
    "prometheus_retention_time": "60s"
  }
}
EOF

cat <<'EOF' >> init-consul.sh
#!/bin/bash
for i in {0..254}
do
cat <<EOP > payload.json
{
  "Node": "foobar",
  "Address": "192.168.10.10",
  "Service": {
    "ID": "deploy-${i}",
    "Service": "deployment-service-web",
    "Address": "192.168.1.${i}",
    "Port": 8000,
    "Tags": ["us-$(expr ${i} % 3)"]
  }
}
EOP
curl --request PUT --data @payload.json http://127.0.0.1:8500/v1/catalog/register
done
rm payload.json
EOF
```

run consul:
```
consul agent -server -client="0.0.0.0" -bind="0.0.0.0" -http-port=8500 -dns-port=8600 -data-dir=consul/data -recursor=1.1.1.1 -config-file=consul.json -enable-local-script-checks -ui -retry-interval=10s -advertise=127.0.0.1 -bootstrap-expect=1
```

in another shell:
```
bash init-consul.sh
```

Results:
**correctly return all the IPs**
```
dig @127.0.0.1 -p 8600 deployment-service-web.service.consul +edns +bufsize=4096 | grep ANSWER:
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 255, AUTHORITY: 0, ADDITIONAL: 1
```

**correctly return the subset of the IPs**
```
dig @127.0.0.1 -p 8600 us-0.deployment-service-web.service.consul +edns +bufsize=4096 | grep ANSWER:
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 85, AUTHORITY: 0, ADDITIONAL: 1
```

**correctly return the subset of the IPs**
```
dig @127.0.0.1 -p 8600 us-1.deployment-service-web.service.consul +edns +bufsize=4096 | grep ANSWER:
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 85, AUTHORITY: 0, ADDITIONAL: 1
```

**correctly return the subset of the IPs**
```
dig @127.0.0.1 -p 8600 us-2.deployment-service-web.service.consul +edns +bufsize=4096 | grep ANSWER:
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 85, AUTHORITY: 0, ADDITIONAL: 1
```
