### ISSUE TITLE
Cross DC dns queries are failing when a client with 1.10/1.11 version trying to query the other DC with version 1.9

### ISSUE THREAD

**Issue by ezraroi** [hashicorp/consul#12552]
#### Overview of the Issue

We have a setup with several DCs. We recently upgraded one of our DCs to version 1.11 while the other DCs were on 1.9.6.
We found out that when we are trying to resolve consul based DNS from the new cluster agent to a service in the 1.9.6 DC it is failing on timeout. 

We tested it also with 1.10 version. Only when we downgrade the new DC to 1.9.6 it started to work again.

#### Reproduction Steps

1. Create a cluster in version 1.9.X (`dc1`)
2. Create a cluster in version 1.10.X (`dc2`)
3. Join them in WAN
4. From one of the servers/nodes in `dc`, issue a dns query to port 8600 to resolve `consul.service.dc1.consul`
5. You will get error/timeout.

Error from the log:
```
failed: err="rpc error: code = Unavailable desc = all SubConns are in TransientFailure,
```

### Operating system and Environment details

Ubuntu 20

**Comment by Amier3** [comment]
@ezraroi 

Do you have streaming enabled in your 1.9 DC? If so, could you turn it off and see if you're still experiencing this issue.

**Comment by ezraroi** [comment]
Is this something i need to enable? or it is enables by default?

**Comment by ezraroi** [comment]
OK, i see it is enabled by default.
We will disable it and test

**Comment by ezraroi** [comment]
so we tested it, if we disable streaming in 1.10 it is working:
```
"use_streaming_backend": false,
  "rpc": {
    "enable_streaming": false
  }
```

**Comment by Amier3** [comment]
@ezraroi 

Glad it worked! Looks like you encountered a known issue we're currently working on. It's documented in our 1.10.1 changelog:

> KNOWN ISSUES: 
> 
> The change to enable streaming by default uncovered an incompatibility between streaming and WAN federation over mesh gateways causing traffic to fall back to attempting a direct WAN connection rather than transiting through the gateways. We currently suggest explicitly setting [use_streaming_backend=false](https://www.consul.io/docs/agent/options#use_streaming_backend) if using WAN federation over mesh gateways when upgrading to 1.10.1 and are working to address this issue in a future patch release.
> 

I'm going to close this for now since this is already being tracked.

**Comment by ezraroi** [comment]
Thanks, but we are not using mesh gateway, so it also to consul servers and not only mesh gateway
