### ISSUE TITLE
Watch event fires twice?

### ISSUE THREAD

**Issue by ssenaria** [hashicorp/consul#1256]
I have a simple event that writes to a file. When I trigger the event I see the file created. 

    {
        "watches": [
            {
                "name": "runme",
                "type": "event",
                "handler": "echo 'blah' > /tmp/samwashere"
            }
         ]
    }

If I run a curl to see a list of events, I see the event waiting in queue (is this correct?)

    curl http://172.20.10.103:8500/v1/event/list

If I restart consul, the event fires again (I confirmed by the timestamp of the file) and the event is now gone from the event list upon running another curl.

Is this correct?

**Comment by slackpad** [comment]
Hi @ssenaria this seems like a possible bug. When you say "restart consul" do you mean a config reload via https://www.consul.io/docs/commands/reload.html/SIGHUP?

**Comment by ssenaria** [comment]
service consul restart on a RH 6 system.

**Comment by slackpad** [comment]
Looks similar to https://github.com/hashicorp/consul/issues/571.

**Comment by slackpad** [comment]
Closing as a dup of #571.
