### ISSUE TITLE
website: the FAQ is incorrect about the use of LMDB

### ISSUE THREAD

**Issue by jeffawang** [hashicorp/consul#1261]
The Upgrading Specific Versions page in the documentation says that as of 0.5.1, LMDB has been replaced by BoltDB, but the Frequently Asked Questions page still mentions internal use of LMDB. I think it is out of date.

I'm not familiar enough with LMDB or BoltDB to make an appropriate change to the actual page, though.

**Comment by slackpad** [comment]
We are getting rid of LMDB for 0.6 so I'll clean this up while prepping for that.

**Comment by slackpad** [comment]
Fixed via https://github.com/hashicorp/consul/commit/ff1eec015f58157ca23c3bd6984d537bd757acd8.
