### ISSUE TITLE
Remove unnecessary custom retry logic associated with Consul's usage of the Vault API

### ISSUE THREAD

**Issue by clly** [hashicorp/consul#12613]
#### Feature Description

Once we've upgraded to a later version of protobuf we can also upgrade to a newer version of vault/api. This will pull in improvements but the biggest known win is that the vault LifetimeWatcher will automatically backoff on Vault errors and allow us to remove out our own backoff logic. The backoff logic was added in https://github.com/hashicorp/consul/pull/12607 to prevent thousands of requests to Vault if the authentication method becomes invalid.

The protobuf changes are completed: https://github.com/hashicorp/consul/issues/10471

**Comment by jkirschner-hashicorp** [comment]
@clly , @rboyer : Why upgrade to Vault API *1.1.1* specifically? If I understand correctly, we [currently use Vault 1.0.5](https://github.com/hashicorp/consul/blob/c7ef04c5979dbc311ff3c67b7bf3028a93e8b0f1/go.mod#L64). The [latest Vault API version is 1.8.2](https://pkg.go.dev/github.com/hashicorp/vault/api).

**Comment by clly** [comment]
Vault 1.1.1 was the lowest API version with the referenced changes. Consul could upgrade as high as it would like to go and I am on board with going to latest.

**Comment by jkirschner-hashicorp** [comment]
https://github.com/hashicorp/consul/pull/15970 updated the [Vault API to 1.8.2](https://github.com/hashicorp/consul/pull/15970/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R64) for Consul 1.15.0+.

This makes the backoff logic introduced by #12607 no longer necessary. It's a small internal cleanup to remove that unnecessary logic.
