### ISSUE TITLE
net.Dial.DualStack in agent/checks/check.go is Deprecated

### ISSUE THREAD

**Issue by fulviodenza** [hashicorp/consul#12629]
Hi, working on a different issue, I went through this deprecated field of net.Dial, which is DualStack.
As described in the documentation of the net package:

> // DualStack previously enabled [RFC 6555](https://rfc-editor.org/rfc/rfc6555.html) Fast Fallback
> // support, also known as "Happy Eyeballs", in which IPv4 is
> // tried soon if IPv6 appears to be misconfigured and
> // hanging.
> //
> // Deprecated: Fast Fallback is enabled by default. To
> // disable, set FallbackDelay to a negative value.
> DualStack bool

I think we don't need it anymore.

**Comment by Amier3** [comment]
Hey @fulviodenza 

Thanks for letting us know about this. Were you able to figure out the other issue you were working on? maybe the team could help with that 👍

**Comment by mkeeler** [comment]
Closing as the PR was merged.
