### ISSUE TITLE
advertise_addr overriding service address

### ISSUE THREAD

**Issue by jaredcurtis** [hashicorp/consul#1266]
We configure all hosts to use `advertise_addr` to publish the "public" IP and then each service will either use the "public" or in some cases the private address. I've seen in two cases now where the private address is not being advertised for the service. Any ideas as to why this could happen?

Restarts do not seem to make any difference and nothing obvious is in the logs. Here's the configuration for a host having the issue. 

```
$ consul --version
Consul v0.5.2
Consul Protocol: 2 (Understands back to: 1)
$ cat /etc/consul/config.json | python -m json.tool
{
    "addresses": {
        "http": "127.0.0.1"
    },
    "advertise_addr": "172.16.2.17",
    "client_addr": "0.0.0.0",
    "data_dir": "/opt/consul",
    "datacenter": "ZZZ",
    "disable_update_check": true,
    "log_level": "INFO",
    "node_name": "my_node_name",
    "retry_join": [
        "consul.service.ZZZ.consul"
    ],
    "server": false,
    "ui_dir": ""
}
$ cat /etc/consul/service_asterisk.json | python -m json.tool
{
    "service": {
        "address": "192.168.104.59",
        "checks": [],
        "id": "asterisk",
        "name": "asterisk",
        "tags": [
            "instance1-prd"
        ]
    }
}
```

**Comment by ryanuber** [comment]
@jaredcurtis is it possible there are any other configuration files at play, or any CLI args that might affect this? I copy-pasted your configs onto a test box and started Consul a few times with them, but I consistently see the 192.x address for the "asterisk" service.

It is also possible that this service definition can be updated from the `/v1/agent` API's. If the service has indeed been updated from the API at some point, then the service definition becomes cached in Consul's data-dir under the "services" sub-directory. I would check the data-dir/services directory (just cat the files, they are named by the MD5 of their service names) to see if something might be going on there.

Hope that helps!

**Comment by jaredcurtis** [comment]
Here's another new host that is displaying the problem. This host was just created and we didn't use the agent api to update services definition.

```[user@host-192-168-106-53 ~]$ ls /etc/consul/
config.json  service_gluster.json
[user@host-192-168-106-53 ~]$ cat /etc/consul/config.json | python -m json.tool
{
    "addresses": {
        "http": "127.0.0.1"
    },
    "advertise_addr": "172.16.1.145",
    "client_addr": "0.0.0.0",
    "data_dir": "/opt/consul",
    "datacenter": "YYY",
    "disable_update_check": true,
    "log_level": "INFO",
    "node_name": "gluster-data-save-prd-instance1-7h5crgqbrpjp",
    "retry_join": [
        "consul.service.YYY.consul"
    ],
    "server": false,
    "ui_dir": ""
}
[user@host-192-168-106-53 ~]$ cat /etc/consul/service_gluster.json | python -m json.tool
{
    "service": {
        "address": "192.168.106.53",
        "checks": [],
        "id": "gluster",
        "name": "gluster",
        "tags": [
            "prd"
        ]
    }
}
[user@host-192-168-106-53 ~]$ ps aux | grep consul
root      1687  0.0  0.0 108432  1048 ?        S    05:16   0:00 /bin/bash /etc/rc3.d/S95consul start
root      1691  0.0  0.0 130720   856 ?        S    05:16   0:00 runuser -s /bin/bash consul -c ulimit -S -c 0 >/dev/null 2>&1 ; /usr/local/bin/consul agent -pid-file /var/run/consul/consul.pid -config-dir /etc/consul
consul    1698  0.0  0.0 106056   892 ?        Ss   05:16   0:00 bash -c ulimit -S -c 0 >/dev/null 2>&1 ; /usr/local/bin/consul agent -pid-file /var/run/consul/consul.pid -config-dir /etc/consul
consul    1703  0.7  0.3 313072 13168 ?        Sl   05:16   5:24 /usr/local/bin/consul agent -pid-file /var/run/consul/consul.pid -config-dir /etc/consul
user   2756  0.0  0.0 103244   876 pts/2    S+   18:02   0:00 grep consul
```

**Comment by ryanuber** [comment]
@jaredcurtis can you show me how you are querying Consul for the service address? (DNS query with `dig`, HTTP request with `curl`, etc).

**Comment by jaredcurtis** [comment]
We're using DNS for service discovery at this time. Our DNS servers are configured as suggested in the docs.

Here's the output of an API and dns lookups

```
$ curl http://localhost:8500/v1/catalog/service/gluster?tag=prd | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
115   460  115   460    0     0  65959      0 --:--:-- --:--:-- --:--:-- 92000
[
    {
        "Address": "172.16.1.67",
        "Node": "host-192-168-106-44",
        "ServiceID": "gluster",
        "ServiceName": "gluster",
        "ServicePort": 0,
        "ServiceTags": [
            "prd"
        ]
    },
    {
        "Address": "192.168.104.63",
        "Node": "gluster-prd-instance2-wgfa4mp6klnx",
        "ServiceID": "gluster",
        "ServiceName": "gluster",
        "ServicePort": 0,
        "ServiceTags": [
            "prd"
        ]
    },
    {
        "Address": "192.168.104.64",
        "Node": "gluster-prd-instance1-penmkp2zxmx3",
        "ServiceID": "gluster",
        "ServiceName": "gluster",
        "ServicePort": 0,
        "ServiceTags": [
            "prd"
        ]
    }
]

$ host prd.gluster.service.consul
prd.gluster.service.consul has address 192.168.104.64
prd.gluster.service.consul has address 172.16.1.67

$ dig +short prd.gluster.service.consul
172.16.1.67
192.168.104.64
$ dig +short @localhost -p 8600 prd.gluster.service.consul
172.16.1.67
192.168.104.64
```

**Comment by ryanuber** [comment]
Is it possible you are running an old version of Consul on the server nodes? Comparing the output you pasted above from the `/v1/catalog/service/<id>` endpoint with what is in master, it looks like this might be a pre-0.5 server which would not have the `ServiceAddress` field, which I think is what you are looking for. By default, the AdvertiseAddr would be used, which could be an explanation for this.

Can you check the output of `consul members` and `consul members -wan` to see if you might have an old server or two somewhere?

**Comment by jaredcurtis** [comment]
We do have 5 systems running 0.4.1 but our cluster servers are all on 0.5.2.

**Comment by slackpad** [comment]
Hi @jaredcurtis are you still experiencing this issue - any updates? Thanks!

**Comment by jaredcurtis** [comment]
We've upgraded to 0.7.0 and I haven't seen the problem since.
