### ISSUE TITLE
DNS forward issue

### ISSUE THREAD

**Issue by rjordan** [hashicorp/consul#1267]
I am trying to forward consul dns requests though bind but am running into issues.

Consul v0.5.2

zone "consul" IN {
  type forward;
  forward only;
  forwarders { 127.0.0.1 port 8600; };
};

dig @127.0.0.1 -p 8600 server1.node.consul #NOERROR  
dig @127.0.0.1 -p 53 server1.node.consul #SRVFAIL 

Error message from the consul server is:  
2015/09/30 19:46:54 [WARN] dns: QName invalid: node.

It appears to be the extra dot causing it not to match, but I am unsure why this is happening. Hopefully I just have a misconfiguration, but am failing to see it.

**Comment by mumblez** [comment]
I have it working myself with similar configuration, only difference is I don't have "IN" on the first line, try 

zone "consul" {

instead, though I doubt it makes a difference. You also need to enable recursion if not already, (recursion yes;) and disable dnssec options.

Does it work if you resolve the consul servers themselves?
e.g.
dig @localhost -p 8600 consul.service.consul +short
dig @localhost -p 53 consul.service.consul +short

**Comment by rjordan** [comment]
dnssec-enabled no and recursion yes are both set in my named.conf.options file...

I removed the IN from the zone config, and same issue:

dig @localhost -p 8600 consul.service.consul +short
192.168.0.200

dig @localhost -p 53 consul.service.consul +short

**Comment by mumblez** [comment]
is bind definately resolving names?
could you confirm a normal name resolution.
Maybe bind logs (or default /var/log/syslog) might reveal something?

**Comment by rjordan** [comment]
\**modified*\*
dig @localhost -p 53 *server*.*domain*.org +short
192.168.0.200
dig @localhost -p 53 -x 192.168.0.200 +short
*server*.*domain*.org.

Forward and reverse seem to be fine.

**Comment by rjordan** [comment]
FOUND IT!

I had set dnssec-enabled: no in my options but further up I didn't see dnssec-validation auto, this must ALSO be set to no.

Thanks for the assistance!
