### ISSUE TITLE
can check script accept parameter in the check defintion?

### ISSUE THREAD

**Issue by huikang** [hashicorp/consul#1269]
Hi
Can my check script accept some parameter from consul such as?

{
  "check": {
    "id": "mem-util",
    "name": "Memory utilization",
    "script": "/usr/local/bin/check_mem.py  **2048**",
    "interval": "10s"
  }
}

**Comment by highlyunavailable** [comment]
It can.

Some of my check definitions were `/bin/curl -s -XGET 'http://localhost:9200/_nodes/hostname/health` and there's no difference between calling curl with params and calling a script with params.

**Comment by huikang** [comment]
Thanks.
