### ISSUE TITLE
Consul Raft State metrics disappear after prometheus retention period has passed

### ISSUE THREAD

**Issue by ADustyOldMuffin** [hashicorp/consul#12704]
#### Overview of the Issue

When monitoring a Consul cluster via prometheus over time, once the retention time is passed the metrics `consul_raft_state_leader` and `consul_raft_state_follower`  disappear.

Using these fields then becomes unreliable since the state of a raft cluster isn't expected to change often and thus its very likely that the metric won't change and go away.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a consul cluster with a `telemetry.prometheus_retention_period` as some value
2. observe `consul_raft_state_*` value
3. wait for retention period value
4. observe `consul_raft_state_*` missing

### Consul info for both Client and Server

Consul version - 1.2.4, but should be present on any other versions.

**Comment by ADustyOldMuffin** [comment]
I think that it might also be beneficial to offer a way to turn it off, as prometheus generally expects that once a metric is exposed its always present and any sort of queries where this is not true can fail (IE in our case we'd like to monitor leader and follower for alerts and dashboards but we can't due to the fact it goes away).

**Comment by ADustyOldMuffin** [comment]
I believe the location of the needed change is here https://github.com/hashicorp/consul/blob/ceee04f4c6ade82ffc432b6e61627142814e8862/lib/telemetry.go#L231-L242

**Comment by Amier3** [comment]
Hey @ADustyOldMuffin 

Thanks for raising this issue. It looks like we've fixed this in[ 1.9.0](https://github.com/hashicorp/consul/blob/main/CHANGELOG.md#190-november-24-2020) :

> telemetry: All metrics should be present and available to prometheus scrapers when Consul starts. If any non-deprecated metrics are missing please submit an issue with its name. [https://github.com/hashicorp/consul/issues/9198]

Before this change, metrics didn't initialized in prometheus until a value was changed. This meant that the  `consul_raft_state_leader` and` consul_raft_state_follower` metrics would disappear past the retention time until another leader election event. 

I'd advise checking out our [Upgrade Guide ](https://www.consul.io/docs/upgrading/instructions), and reaching out to our [community forum ](https://discuss.hashicorp.com/c/consul/29) if you hit any bumps along the way
