### ISSUE TITLE
Consul is returning unhealthy nodes

### ISSUE THREAD

**Issue by spanhotra** [hashicorp/consul#12728]
#### Overview of the Issue

Consul is returning unhealthy nodes, when one of the nodes die unexpectedly.
I expect it to return me only healthy nodes, and only fail when all the nodes are unhealthy or all are deregistered.

#### Reproduction Steps

I have created following services using docker.
1. Consul in dev mode
2. ConfigService [2 instances]
3. DataService [1 instances]
4. Kill 1 instance of ConfigService using `docker kill` 
5. ![image](https://user-images.githubusercontent.com/79205065/162398586-5aaa1717-e204-451f-8aac-160124dae05b.png)
6. Run DataService which consumes ConfigService
7. It will fail a few times, because a dead node is returned by consul

Consul is 

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 3
        checks = 3
        services = 3
build:
        prerelease =
        revision = 944e8ce6
        version = 1.11.4
consul:
        acl = disabled
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 127.0.0.1:8300
        server = true
raft:
        applied_index = 284
        commit_index = 284
        fsm_pending = 0
        last_contact = 0
        last_log_index = 284
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:3458e80d-d2b7-598c-3a47-2efa30a10e46 Address:127.0.0.1:8300}]
        latest_configuration_index = 0
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 131
        max_procs = 2
        os = linux
```

</details>

### Operating system and Environment details

OS: Windows Server 2019
Docker on Windows

### Log Fragments

![image](https://user-images.githubusercontent.com/79205065/162398258-684cf6bf-eaad-4f02-a65a-36986d273ede.png)

**Comment by blake** [comment]
Hi @spanhotra,

Would you mind providing a bit more information so that we can help you debug this issue?

1. Information about the registered checks for service `config-service-1`.

  `curl --get  $CONSUL_HTTP_ADDR/v1/agent/checks --data-urlencode "filter=ServiceName==\"config-service-1\""`

1. Additional information about how DataService is consuming ConfigService. Is it querying the service endpoints via DNS, HTTP, etc? If using the HTTP API, specific code examples will be helpful.

Thanks.

**Comment by spanhotra** [comment]
Hello @blake 

There was a flag `QueryPassing` in the .NET client which needed to be set to true.
` var result = await _client.Health.Service(serviceId, Options.DefaultQueryTag, Options.QueryPassing, queryOptions).ConfigureAwait(false); `

This has worked for me.

Apologies for keeping this open.
