### ISSUE TITLE
Service status icons not visable in Safari (desktop and mobile)

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/consul#12737]
### Overview of the Issue

Consul 1.12.0 beta1 seems to have a regression where the service status icons on the services page are not shown.

### Reproduction Steps

Steps to reproduce this issue/view the area for improvement, eg:

1. Run `consul agent -dev -client=0.0.0.0`
2. Visit the UI page at `ui/dc1/services`
3. the status icon in front of consul is an empty space (however mouse-over does show)

### Consul Version

```
consul -version
Consul v1.12.0-beta1
Revision 27cc4d8d
```

### Browser and Operating system details

tested on:
Safari Tech Preview Release 143 (Safari 15.4, WebKit 17614.1.7.7) macOS 12.3.1
Safari Version 15.4 (17613.1.17.1.13) macOS 12.3.1
Safari 15.5 (WebKit 605.1.15) iOS 15.5

### Screengrabs / Web Inspector logs

As viewed on iOS
![consul-1 12 0b1](https://user-images.githubusercontent.com/6336384/162645919-6d045af5-ed40-44ad-8297-c702df079757.jpg)

**Comment by johncowen** [comment]
Amazing thanks @tristanmorgan for the report! 🙇 Fix PRed ^ and should be in for the final release.
