### ISSUE TITLE
Add option to allow_stale only while no leader present

### ISSUE THREAD

**Issue by hugochinchilla** [hashicorp/consul#1273]
It would be very helpful to have an option to allow agents to reply the last known value for a service while a leader election is in progress.

Recently I had the case in which the leader went down and even though a new leader was elected in a fraction of a second it was time enought for my application to start throwing exceptions about service names not being resolvable, it would be great to have an option similar to `allow_stale` but not for scalability but for reliability, in that case **we could allow an agent to respond the last known value instead of an empty response, but only while the leader can't do it**.

**Comment by djenriquez** [comment]
+1

**Comment by DanyC97** [comment]
+1

**Comment by engine07** [comment]
+1

**Comment by gpaggi** [comment]
+1

**Comment by c4milo** [comment]
Isn't this achievable with dnsmasq?

**Comment by tlisonbee** [comment]
+1

**Comment by i0rek** [comment]
This is quite an edge case and since we are very busy with other things, nothing we are going to implement ourselves. If you want to provide a PR, I would be happy to review it. Thanks!
