### ISSUE TITLE
Thinking: DNS records associated with sessions

### ISSUE THREAD

**Issue by cruatta** [hashicorp/consul#1275]
After reading, https://www.consul.io/docs/guides/leader-election.html, I thought it might be really elegant to use DNS as a mechanism to discover nodes that are holding a session lock. For example, if I have a node that is holding "dbservice" like the one in the guide, if I did a dig on "dbservice.session.dc1.consul", it would return records to the nodes holding the lock. This is really high level thinking but I figured I'd put an issue in here to get feedback from the community and Hashicorp.

**Comment by ryanuber** [comment]
I think this could be a good idea, and we have been working on a framework to make these "fancy" kinds of DNS queries possible in a nice way! The basic thinking is that an opaque DNS name can have arbitrarily complex semantics behind the scenes. Stay tuned!

**Comment by slackpad** [comment]
There hasn't been much interest in this one so I'm going to close it out. The functionality @ryanuber was referencing is [prepared queries](https://www.consul.io/api/query.html).
