### ISSUE TITLE
Deleting a node from the member list

### ISSUE THREAD

**Issue by akmalabbasov** [hashicorp/consul#1276]
I'm testing consul in vagrant, and some on nodes have joined using `127.0.0.1` as their address. Now I want to join them using `-bind` option of the agent and using different address. But for now it's failing since the node with the same name is already registered. 
Is there any way to deleted a node from members list?
Thanks.

**Comment by slackpad** [comment]
Hi @akmalabbasov can you describe what's failing in a little more detail? There aren't any uniqueness checks on address that should cause things to fail.

**Comment by slackpad** [comment]
Closing since we never heard back.
