### ISSUE TITLE
HTTP check URLs (un)escaped incorrectly

### ISSUE THREAD

**Issue by JayH5** [hashicorp/consul#1277]
I have a service definition that looks like this:

``` json
{
  "service": {
    "name": "rabbitmq",
    "port": 5672,
    "check":
    {
      "http": "http://guest:guest@example.com:15672/api/aliveness-test/%2F",
      "interval": "10s",
      "timeout": "1s"
    }
  }
}
```

I can curl the health check URL locally and get an OK response.

I did a tcpdump on Consul's health check and the request path seems to be incorrectly encoded. GET requests to `/api/aliveness-test//` are observed (instead of `/api/aliveness-test/%2F`).

Despite the internal encoding of the path in Consul, the Consul web UI reports:
`HTTP GET http://guest:guest@example.com:15672/api/aliveness-test/%2F: 404 Object Not Found Output:...`

**Comment by Nirkus** [comment]
URL-emcoding the ```%``` character of the URL-encoded ```/``` character will probably do as a workaround for this issue (not verified):
```
{
  "service": {
    "name": "rabbitmq",
    "port": 5672,
    "check":
    {
      "http": "http://guest:guest@example.com:15672/api/aliveness-test/%252F",
      "interval": "10s",
      "timeout": "1s"
    }
  }
}
```
See also #889

**Comment by JayH5** [comment]
Hi @Nirkus,

Thanks for the response. Unfortunately, it doesn't work :cry:. It results in Consul just GETting `/api/aliveness-test/%252F`.

It's a good idea, though. I'll have a play around and see if I can get `net/http` to comply...

**Comment by JayH5** [comment]
Nope it looks like there is no support for paths containing `%2F` in `net/http`. There seems to be some support in Go 1.5 in `net/url`, see this [commit](https://github.com/golang/go/commit/874a605af0764a8f340c3de65406963f514e21bc).

**Comment by i0rek** [comment]
This problem is fixed now. I printed the request with httputil.DumpRequest():

```
GET /api/aliveness-test/%2F HTTP/1.1
Host: example.com:15672
Accept: text/plain, text/*, */*
User-Agent: Consul Health Check
```
