### ISSUE TITLE
Automatic ai 

### ISSUE THREAD

**Issue by godcontrol123123** [hashicorp/consul#12809]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by Amier3** [comment]
Hey @godcontrol123123 

Could you re-submit this issue with the required fields 'Feature Description' and 'Use Cases'  filled out? Thank you!
