### ISSUE TITLE
[middleware] `RequestRecorder` needs to report < 1ms calls as well

### ISSUE THREAD

**Issue by acpana** [hashicorp/consul#12813]
### overview

Today, the `RequestRecorder` records service RPC calls. If those take less than `< 0ms`, the recorder marks them as `0ms`.

### proposal

Make the `RequestRecorder` report the `elapsed` time for service calls that take less than `< 0ms` as decimal values, instead of 0.

#### testing

If you take this on, I'd kindly advise to start in a TDD fashion. Write a test in `metrics_test` to look at, say, `Status.Ping` RPC calls. These will almost always come at < 0ms so they will be reported as `0 ms`. Let the test fail, then do the necessary logic changes in `RequestRecorder.Record`.

#### docs

Today, the docs call this out. If this is worked on, please make the necessary changes in the docs as well.

**Comment by Gabrielopesantos** [comment]
Hello, I have never used consul but this seems an interesting issue. Can I take it?

**Comment by Gabrielopesantos** [comment]
Hello, I have opened up a draft pull request with a proposal for the issue but also looking for feedback on an issue that I am having. Let me know if I should make it ready to be reviewed. Thank you.
