### ISSUE TITLE
Dns Query: Service Address vs Advertise Address

### ISSUE THREAD

**Issue by Esya** [hashicorp/consul#1281]
Hi,

Because our consul cluster runs in a VPN, and some services need to be accessed from outside the VPN, we register them with a public ip, even though the node has an `advertise` address set to the ip on the VPN.

It works fine when we use Consul's HTTP API (We get the address fine), but when we do SRV Records we get something like this : 

```
;; ANSWER SECTION:
_sip._udp.service.consul. 15  IN  SRV 1 1 5063 ourserver.node.us.consul.
_sip._udp.service.consul. 15  IN  SRV 1 1 5060 ourserver.node.us.consul.
_sip._udp.service.consul. 15  IN  SRV 1 1 5062 ourserver.node.us.consul.
_sip._udp.service.consul. 15  IN  SRV 1 1 5061 ourserver.node.us.consul.
```

Then our SIP Server does a query to resolve `ourserver.node.us.consul`

```
;; ANSWER SECTION:
ourserver.node.us.consul. 30 IN A 10.50.0.8
```

And then it tries to connect to this private IP, while the service is registered with the public IP of the machine. What should we do here?

Thanks

**Comment by slackpad** [comment]
Hi @Esya - this is a weird one. It looks like maybe the advertise address isn't getting populated into the catalog correctly. Can you see what the output of the `/v1/catalog/nodes` HTTP endpoint shows for the address?

**Comment by slackpad** [comment]
Closing since we never heard back.
