### ISSUE TITLE
Consul UI glitch after upgrading to v1.12.0

### ISSUE THREAD

**Issue by chrisvanmeer** [hashicorp/consul#12850]
#### Overview of the Issue

Since the upgrade to Consul v.1.12.0 I experience a little graphical bug in Safari which only comes to light when I visit the Consul UI through an SSH port forwarding. Basically I setup an SSH tunnel to a management station and map that port 8500 to my local 8500 port. It appears that some of the shapes are not rendered.

#### Reproduction Steps

- When I visit the remote Consul UI (through SSH port forwarding) in Chrome, everything looks fine.  
- When I visit the remote Consul UI (through SSH port forwarding) in Safari, some of the shapes don't appear.
- When I install Consul locally in dev mode with UI enabled, I can visit the UI with Safari without the glitch.  

### Operating system and Environment details

- macOS version 12.3.1  
- Chrome version 100.0.4896.127  
- Safari version 15.4 (17613.1.17.1.13)

### Screenshots

Screenshots. On the left is a Chrome browser, on the right the Safari browser, both browsing the same address.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3852620/164977822-711f1099-e258-4721-bd6d-6576f1ef39f8.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3852620/164977835-68917e19-abab-4e18-b9ae-b96c3b82de28.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3852620/164977837-46e2085d-39b5-4db2-a0a3-178837e492d0.png">

**Comment by chrisvanmeer** [comment]
Awesome. Extra information. Even connecting directly to the IP address (without SSH tunnel forwarding) causes the same result in Safari. Verified on multiple systems. So with my logic that rules out a specific condition that this is caused by an SSH forwarding.

**Comment by david-yu** [comment]
HI @chrisvanmeer we just merged https://github.com/hashicorp/consul/pull/13183 which should address these issues in Safari. Please re-open after 1.12.1 is released and if you find that this issue is not addressed.
