### ISSUE TITLE
Use of closed network connection frequently on http monitoring

### ISSUE THREAD

**Issue by sobrinho** [hashicorp/consul#1287]
We seeing a lot of `use of closed network connection` on http monitoring and we don't know why.

We have a couple of checks like this:

``` json
{
  "check": {
    "id": "app",
    "name": "app",
    "http": "http://app.com/",
    "interval": "30s",
    "timeout": "5s"
  }
}
```

5 seconds is enough to application respond, it usually takes around 30ms to respond.

The application is running on the same machine besides the public domain usage and we are running on linode where the router is smart enough to redirect to the same machine without going to the public network, example:

```
root@app:/etc/consul.d# traceroute app.com
traceroute to app.com (xx.xx.xx.xx), 30 hops max, 60 byte packets
 1  xxx.members.linode.com (xx.xx.xx.xx)  0.031 ms  0.013 ms  0.014 ms
```

Every time the failure happens, the next check works.

It has a inconsistent timeframe but at least 1 request per hour fails making the monitoring too noise to be meaningful.

What information do you guys need to debug the problem? It is a problem on my configuration?

_PS: This problem is happening in exactly the same way in different machines and even for different apps in the same machine._

_PS: I'm using Atlas to be notified about these failures._

**Comment by SPARTAN563** [comment]
Seeing the same issue on one of our clusters - checks are conducted locally on each node by a Consul agent running there:

```json
{
  "services": [
    {
      "name": "app-api",
      "tags": ["secondary", "production"],
      "port": 80,
      "checks": [
        {
          "http": "http://localhost:80/api/v1/cron/status",
          "interval": "30s",
          "timeout": "5s"
        }
      ]
    }
  ]
}
```

Again, average response time of `/api/v1/cron/status` is around `10ms` however we see a significant amount of noise relating to the `use of a closed network connection`. I suspect this has something to do with Go trying to reuse the same socket for subsequent HTTP requests (ala `Keep-Alive`).

In the mean time we are testing the use of `cURL` for these checks until this problem can be rectified (if that is possible). It has the added benefit of allowing us to quickly see response times associated with the checks as well.

```
curl --max-time 5 -o /dev/null -I -s -w \"Response Code: %{http_code}\nResponse Time: %{time_total}s\n\" 'http://localhost:80/api/v1/cron/status
```

**Comment by wuub** [comment]
@SPARTAN563 watch out for checks that are not idempotent and change output each time you run them. Depending on your https://www.consul.io/docs/agent/options.html#check_update_interval and number of services in your cluster, you could be causing enormous number of writes to the K/V.

**Comment by SPARTAN563** [comment]
Thanks for that, will keep it in mind going forward.

**Comment by sobrinho** [comment]
If that's an expect exception in Go (doesn't seem to me), consul could just retry the request when it happens.

**Comment by theckman** [comment]
I ran in to this issue as well. It triggered due to a misconfiguration in our checks. For the interval and timeout keys, we provided numbers (`10`) instead of a string like `"10s"`. Looking at your configuration it's not the exact same cause, but it may be related in some way.

**Comment by slackpad** [comment]
I think we can probably close this out similar to #1320, but lets look in https://github.com/hashicorp/consul/issues/1287#issuecomment-152003503 first and make sure there's no way to sneak in a very short interval.

**Comment by slackpad** [comment]
The concern from @theckman is captured on https://github.com/hashicorp/consul/issues/1495, so we can close this out.

**Comment by aleksejlopasov** [comment]
Solved
These errors had been detected in debug log
```hcl
2018-06-12T16:20:22.597+0300 [DEBUG] plugin.terraform-provider-google_v1.14.0_x4: 2018/06/12 16:20:22 [ERR] plugin: plugin server: accept unix /tmp/plugin543074790: use of closed network connection
2018-06-12T16:20:22.600+0300 [DEBUG] plugin: plugin process exited: path=/home/olopa/Documents/Projects/Terraform/compute_engine/.terraform/plugins/linux_amd64/terraform-provider-google_v1.14.0_x4
```
Perhaps terraform creates a socket in /tmp for every plugin or smth like this.
Unix /tmp/plugin543074790 was owned by root and I tried to access it using non-root account. That explains why one plugin works while the other does not.
The ticket may be closed
Thanks
