### ISSUE TITLE
can not access token ModifyIndex

### ISSUE THREAD

**Issue by unixchina** [hashicorp/consul#12889]
### Overview of the Issue

A paragraph or two about the issue you're experiencing / suggestion for
improvement.

### Reproduction Steps

This is my token infomation:

[
{
"AccessorID": "a65e20a8-541e-3e4a-f995-2fb18c86f4c9",
"SecretID": "2dc069c1-5efa-37ff-781b-xxxx",
"Description": "[k/v,services: wirte]",
"Roles": [
{
"ID": "4608cbff-d642-d860-0c71-b549cc5e87a1",
"Name": "admins"
}
],
"Local": false,
"CreateTime": "2022-04-27T17:57:58.133234281+08:00",
"Hash": "y2y/6zGNKrMsRnaTKGGfofW05a91LQH9O41qWK/G9r0=",
"CreateIndex": 27512,
"ModifyIndex": **30424**
},
{
"AccessorID": "748bf148-70a2-d153-6cfc-3b32c8b35c5f",
"SecretID": "343d91a3-4f80-fd4f-f8cd-xxxx",
"Description": "consul server agent token",
"Policies": [
{
"ID": "b3643514-ee5e-3746-953d-bac7f9bba2aa",
"Name": "consul-servers"
}
],
"Local": false,
"CreateTime": "2022-04-28T18:37:25.976479041+08:00",
"Hash": "ItV92ZeMwy+nXdVCraP8HMXSy0FwezaGswS6JPtroA0=",
"CreateIndex": 30398,
"ModifyIndex": 30419
},
... ...

when I access token api url :
curl --header "X-Consul-Token: ${my bootrap token
}" 'http://127.0.0.1:8500/v1/acl/tokens?dc=dc1&index=**30424**'

no response, and I found just **could not access the max ModifyIndex** number.

![图片](https://user-images.githubusercontent.com/39405629/165874496-9a918681-a34e-492b-baa8-ae60bdeb61a3.png)

Who can help me why did this happen?

### Consul Version

Consul v1.12.0
Revision 09a8cdb4
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

I just have one consul server in my datacenter

### Browser and Operating system details
centos7.9.2009
chrome: 99.0.4844.82
firefox: 94.0.2 (64 )

**Comment by Amier3** [comment]
Hey @unixchina 

Closing this one as a duplicate. We'll help you out over in https://github.com/hashicorp/consul/issues/12888
