### ISSUE TITLE
how to get data from other data center by intranet ip reg consul

### ISSUE THREAD

**Issue by hzxgo** [hashicorp/consul#12906]
#### Feature Description
I have two data centers(dc1, dc2), data centers join wan by extranet ip.
In dc1, all servers reg dc1 local consul by intranet ip
In dc2, all servers reg dc2 local consul by intranet ip
In this way, dc2 servers can access to get data by rpc from dc1 servers?

Consul version:
v1.9.8

data center1:
consul start-up: consul agent -server -ui -bootstrap-expect=1 -data-dir=/data/consul -dc=dc1 -node=srv1 -bind=192.168.1.5 -advertise=52.81.180.x -client=0.0.0.0
reg services(reg consul addr: 192.168.1.5) :  go.micro.srv.basic,  go.micro.srv.order
in dc1, order server can get data from basic server by rpc.

data center2: 
consul start-up: consul agent -server -ui -bootstrap-expect=1 -data-dir=/data/consul -dc=dc2 -node=srv2 -bind=172.17.0.2 -advertise=49.234.57.x -client=0.0.0.0
reg services(reg consul addr: 172.17.0.2) :  go.micro.srv.user
dc2 join dc1: consul join -wan 52.81.180.x
test result: dc2 user server can not get data from dc1 basic server.
If dc1 and dc2 bind extranet ip, all server reg  extranet ip consul can fix it.

How can dc2 server get data from dc1 server by intranet ip reg consul?

**Comment by Amier3** [comment]
Hey @hzxgo 

Could you ask this question in our community forum? We'd be happy to help you out there, but we try to keep github for bug reports & feature requests.
