### ISSUE TITLE
Consul configuration state

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/consul#1292]
A command such as `consul config`, for example, would give us the current state of the configuration for that running agent, and would output all of the  [options](https://www.consul.io/docs/agent/options.html) with its values specified. This would be especially useful for instances where there are multiple JSON files with the same configuration options and CLI commands. Even though this state can be deduced by the ordering and merging rules, it would be way easier for the operator to have a complete view of the final config state similar to information given with `consul info` without looking at various places and seeing which final value is being used.

**Comment by wuub** [comment]
You can get current config and member info by here: localhost:8500/v1/agent/self
`curl localhost:8500/v1/agent/self | python -m json.tool`

**Comment by cleung2010** [comment]
Awesome, thanks!
