### ISSUE TITLE
Add Consul vs Eureka comparison to website

### ISSUE THREAD

**Issue by philsttr** [hashicorp/consul#1295]
It would be great if the [Consul vs Other Software](https://www.consul.io/intro/vs/index.html) section of the website included a comparison of Consul vs [Eureka](https://github.com/Netflix/eureka/wiki).

@armon provided a quick summary in the [google group](https://groups.google.com/d/msg/consul-tool/fsLGavCv-j8/xGH2f6XACgAJ)...

> Could you please file a ticket? We can hopefully get this done in more detail, but in gist:
> 
> Eureka:
> - AP (weak consistency), state is replicated with “best effort”
> - Services are registered with one server, which attempts to replicate to other servers
> - Service registrations have a TTL, and clients must heartbeat
> - Reads are routed to any server, can be stale or missing data
> - Scales well due to low coordination, especially when server failures relatively rare
> - Fails if all servers down
> 
> Consul
> - CP (strong consistency), state is replicated using Raft
> - Services registered with any server, but written via Raft to a quorum
> - Registrations have complex health checks, including gossip failure detection instead of heartbeating
> - Reads routed to any server, consistent by default but stale reads can be requested
> - Stale reads scale well, Consistent reads scale to tens of thousands per second
> - Consistency offers locking and cluster coordination
> - Lots more features (health checking, locking, KV, federation, ACLs)
> - Fails if a majority of servers down
> 
> Hope that helps!
> 
> Best Regards,
> Armon Dadgar

**Comment by joneepenk** [comment]
is this so hard? it's over a year and still open with no comment.

**Comment by slackpad** [comment]
Hi @joneepenk sorry we haven't gotten to this - it's not hard but there's a large backlog of small things like this and limited resources, so we have to focus our resources on higher priority things. Hopefully the summary above helps in the meantime.

**Comment by andChow** [comment]
@philsttr which is the best chooice in Distributed Systems? spring cloud supported the both.

**Comment by Xiaoshuai** [comment]
still open
