### ISSUE TITLE
Event must have leader info or HTTP API for Agent /v1/agent/self must also include Leader info

### ISSUE THREAD

**Issue by adpande** [hashicorp/consul#1297]
Hi,
We want to trigger an external API form a watch. Even if the watch is configured on all the nodes, the API should get triggered only once per event. For this we are checking first if the agent is a leader or not. If the agent is leader then only it will trigger the API else not.

To achieve this we have to make two api calls to local agent
- /v1/status/leader
- /v1/agent/self

and then compare the two to find out if the agent receiving that event is a leader. This logic is implemented in watch trigger script.

It would be good if we can add a extra boolean field in event info json or in  "/v1/agent/self" API that will also tell that the agent getting that event is a leader.

something like "Leader":true

I am a bit new to Consul so correct me if I am wrong.

**Comment by slackpad** [comment]
Hi @adpande - it still seems like it would be subject to race conditions if different agents are seeing if they are the leader and then reacting (such as if leadership changes right in that time), even if one call had both pieces of information. It seems like you might want to make a more robust synchronization mechanism to make sure the API is only hit once. One idea I had is possibly having the contenders try to lock a key based on the event name with `?cas=0` or something similar (https://www.consul.io/docs/agent/http/kv.html)?

**Comment by slackpad** [comment]
Closing this out - putting the lock logic inside the watch script is a good way to go for this one.
