### ISSUE TITLE
how to trigger handler for a specific state only?

### ISSUE THREAD

**Issue by huikang** [hashicorp/consul#1298]
Hi,
I have defined a service in my consul cluster, like this
```
{
            "name": "www",
            "tags": ["www"],
            "check": {
                "id": "www",
                "name": "www Status",
                "script": "curl 127.0.0.1",
                "interval": "2s"
            }
        },
```
Now I want to take some action only if the check fails. My watch definition is
```
"watches": [
        {
            "type": "checks",
            "service": "www",
            "handler": "service httpd restart"
        }
    ]
```
I found that even if the service status is changing from "critical" to "passing", the handler will be triggered. How can I only trigger the handler if the status of the service is critical? Thanks.

**Comment by akmalabbasov** [comment]
AFAIK, it's not possible, since you can only specify service or state for a watch, not both of them. Let me know if you have a solution for this.

**Comment by slackpad** [comment]
Hi @huikang unfortunately now it's only possible to specify one or the other, as @akmalabbasov said. You do get the result that's being watched over stdin into your handler though, so you can do filtering there with some scripting.
