### ISSUE TITLE
HTTP service check: 406 Not Acceptable Output

### ISSUE THREAD

**Issue by ptecza** [hashicorp/consul#12998]
#### Overview of the Issue

A proper HTTP output from my Elasticsearch node causes a critical state of the node check in Consul. I guess that a reason can be that validation of HTTP headers done by Consul is case-sensitive.

#### Reproduction Steps

1. Create a cluster with 3 client nodes and 3 server nodes
2. Create a following Consul agent configuration for Elasticsearch service at the client node:
```
$ sudo vim /etc/consul.d/elk.hcl
services {
  id   = "elasticsearch"
  name = "elasticsearch"
  port = 9200

  checks = [
    {
      id = "elasticsearch"
      http = "http://localhost:9200/_nodes/_local/http"
      method = "GET"
      body = "\"total\":1,\"successful\":1,\"failed\":0"
      interval = "10s"
      timeout = "5s"
      status = "passing"
      success_before_passing = 3
      failures_before_warning = 1
      failures_before_critical = 3
    }
  ]
}
```
3. Reload Consul agent at the client node:
```
$ sudo consul reload
```
4. Get the critical state checks of Consul at the client node:
```
curl -s http://localhost:8500/v1/health/state/critical |jq -r
[
  {
    "Node": "elk-node-1",
    "CheckID": "elasticsearch",
    "Name": "Service 'elasticsearch' check",
    "Status": "critical",
    "Notes": "",
    "Output": "HTTP GET http://localhost:9200/: 406 Not Acceptable Output: {\"error\":\"Content-Type header [] is not supported\",\"status\":406}",
    "ServiceID": "elasticsearch",
    "ServiceName": "elasticsearch",
    "ServiceTags": [],
    "Type": "http",
    "Interval": "10s",
    "Timeout": "10s",
    "ExposedPort": 0,
    "Definition": {},
    "CreateIndex": 8954058,
    "ModifyIndex": 8954314
  }
]
$
```
5. Verify Elasticsearch node health at the client node:
```
$ curl -s -v http://localhost:9200/_nodes/_local/http ; echo
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9200 (#0)
> GET /_nodes/_local/http HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< X-elastic-product: Elasticsearch
< Warning: 299 Elasticsearch-7.16.2-2b937c44140b6559905130a8650c64dbd0879cfb "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html to enable security."
< content-type: application/json; charset=UTF-8
< content-length: 749
<
* Connection #0 to host localhost left intact
{"_nodes":{"total":1,"successful":1,"failed":0},"cluster_name":"elk-cluster","nodes":{"GNCXLKgfTuW_f5OA12kszg":{"name":"elk-node-1","transport_address":"10.10.10.21:9300","host":"10.10.10.21","ip":"10.10.10.21","version":"7.16.2","build_flavor":"default","build_type":"deb","build_hash":"2b937c44140b6559905130a8650c64dbd0879cfb","roles":["data","data_cold","data_content","data_frozen","data_hot","data_warm","ingest","master","ml","remote_cluster_client","transform"],"attributes":{"ml.machine_memory":"8363880448","xpack.installed":"true","transform.node":"true","ml.max_open_jobs":"512","ml.max_jvm_size":"1073741824"},"http":{"bound_address":["[::]:9200"],"publish_address":"10.10.10.21:9200","max_content_length_in_bytes":104857600}}}}
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 1
        check_ttls = 0
        checks = 2
        services = 2
build:
        prerelease =
        revision = 09a8cdb4
        version = 1.12.0
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 55
        max_procs = 2
        os = linux
        version = go1.18.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5272
        members = 23
        query_queue = 0
        query_time = 1
```
</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 09a8cdb4
        version = 1.12.0
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.10.10.11:8300
        server = true
raft:
        applied_index = 11238778
        commit_index = 11238778
        fsm_pending = 0
        last_contact = 35.80923ms
        last_log_index = 11238781
        last_log_term = 2
        last_snapshot_index = 11223409
        last_snapshot_term = 2
        latest_configuration = [{Suffrage:Voter ID:e4fe42ba-36fe-93d9-27f4-9aba6156a846 Address:10.10.10.12:8300} {Suffrage:Voter ID:ab61adbf-bd43-4c02-26d6-c9a1d791d8bb Address:10.10.10.11:8300} {Suffrage:Voter ID:3262a0bf-2c13-fffe-d781-d277a752c68f Address:10.10.10.13:8300}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 251
        max_procs = 2
        os = linux
        version = go1.18.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5272
        members = 23
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 3
        members = 3
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

Both Consul server and client nodes are Ubuntu 18.04 boxes:
```
$ lsb_release -rc
Release:        18.04
Codename:       bionic
```

**Comment by blake** [comment]
Hi @ptecza,

Consul is marking the health check at critical because Elasticsearch is returning a 406 status code. This behavior is documented for the HTTP health check at <https://www.consul.io/docs/discovery/checks#http-interval>.

> The status of the service depends on the HTTP response code: any 2xx code is considered passing, a 429 Too ManyRequests is a warning, and anything else is a failure.

The error from Elastic search states that the `content-type` header is not correct.

> {\"error\":\"Content-Type header [] is not supported\",\"status\":406}

Without looking at the code, I suspect that Consul is sending the blank `Content-Type` header because you have specified a message to be sent in the request `body`, but have not set the `Content-Type` header to `application/json`.

After reviewing the Elasticsearch docs for the [Nodes info API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html#cluster-nodes-info-api-request) and it does not seem like the API requires a request body to be sent. I suspect the request will succeed after remove the `body` parameter from your HTTP check. For example:

```hcl
services {
  id   = "elasticsearch"
  name = "elasticsearch"
  port = 9200

  checks = [
    {
      id = "elasticsearch"
      http = "http://localhost:9200/_nodes/_local/http"
      method = "GET"
      interval = "10s"
      timeout = "5s"
      status = "passing"
      success_before_passing = 3
      failures_before_warning = 1
      failures_before_critical = 3
    }
  ]
}
```

Can you try this out and report back whether this resolves the issue?

**Comment by ptecza** [comment]
Hello @blake 

Thanks a lot for your detailed reply! The check you proposed above is passing, of course. To be honest, I used `body` option for my check, because I was thinking that it can help me to verify if Elasticsearch response includes a proper string. Pardon my misunderstanding! :)

But now I have a next question. Is it possible to create more precise HTTP check in Consul? I'm affraid that 200 OK response code is not enough to me. I'd like to check also HTTP response body. Is Consul able to do it or I need to create a simple shell script for this task?

**Comment by jkirschner-hashicorp** [comment]
@ptecza: where did you learn about the `body` option for the health check? There may be an opportunity to clarify in the docs that, when setting the body, we also recommend setting the associated `Content-Type` header. But to do that, I want to make sure I understand where in the docs you encountered / learned about the `body` parameter and how to use it.

**Comment by ptecza** [comment]
Hello @blake 

Thanks again for your comprehensive response! I wanted to check if Elasticsearch returns me `"total":1,"successful":1,"failed":0` string. Seems that your script is doing what I need. Thank you very much! :)

BTW, what's your opinion about adding such kind of checking to Consul? I was inspired by Monit which can do it, for example:
```
  check process elasticsearch with pidfile /var/run/elasticsearch/elasticsearch.pid
    start program = "/bin/systemctl start elasticsearch.service" with timeout 60 seconds
    stop program  = "/bin/systemctl stop elasticsearch.service"
    if failed
      host localhost port 9200
      protocol HTTP
      method GET
      request "/_nodes/_local/http"
      with content = '"_nodes":\{"total":1,"successful":1,"failed":0\}'
      timeout 10 seconds
```

**Comment by blake** [comment]
Hi @ptecza, I can see how having this additional functionality would be valuable. If you are interested in seeing this supported in Consul, I recommend opening a separate GitHub issue for this feature request so that we can discuss and track interest in adding this functionality.

**Comment by ptecza** [comment]
Hello @blake 

Great! I'm glad to hear it. I'll open an appropriate GitHub issue soon :)

**Comment by ptecza** [comment]
I think that it's time to close it. Thanks again for your support! :)
