### ISSUE TITLE
Extra debug log data to assist finding misbehaving nodes

### ISSUE THREAD

**Issue by nickwales** [hashicorp/consul#1303]
We had an issue where a node was making a huge number of session requests resulting in performance issues on the server cluster. 

This time we could work out from the requests which node was making the calls however in a situation where that is not obvious having the node name which is creating the request in the debug log would be extremely useful. 

Right now a request entry looks like:

    2015/10/13 21:36:20 [DEBUG] http: Request /v1/kv/vault-prod-1/core/lock?index=61722103&wait=15000ms (15.514288777s)

Adding node info like this would be my recommendation:

    2015/10/13 21:36:20 [DEBUG] [<node_name>] http: Request /v1/kv/vault-prod-1/core/lock?index=61722103&wait=15000ms (15.514288777s)

**Comment by slackpad** [comment]
Fixed via https://github.com/hashicorp/consul/pull/1448.
