### ISSUE TITLE
Allow change default endpoint for server join in case of aws

### ISSUE THREAD

**Issue by obeyler** [hashicorp/consul#13085]
#### Feature Description
Consul allow to join consul cluster by using  tag on aws vm instance. (https://www.consul.io/docs/install/cloud-auto-join) In case of AWS cloud provider, unfortunately the default endpoint can not be set.
I make a PR https://github.com/hashicorp/go-discover/pull/194  on go-discover who give this opportunity. 
If  you can validate this PR and update to the new go discover inside consul...

#### Use Case(s)
Sometime default aws endpoint have to be change (example in case of outscale cloud provider who share same api with aws but differs from endpoint: https://docs.outscale.com/en/userguide/Regions-Endpoints-and-Availability-Zones-Reference.html)

**Comment by Amier3** [comment]
Hey @obeyler 

Thanks for making this and the associated [PR](https://github.com/hashicorp/go-discover/pull/194) . We'll keep the discussions for this on the PR

**Comment by obeyler** [comment]
PI The associated PR is merged :-)

**Comment by obeyler** [comment]
@Amier3 please reopen this issue,
 The go-discover associated PR is merged but consul hasn't yet updated his dependencies.
