### ISSUE TITLE
Range filter at API level for querying keys or values with specified depth

### ISSUE THREAD

**Issue by DanielYWoo** [hashicorp/consul#13113]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Suppose we have a tree like
```
root
  key1
    key11
    key12
  key2
    key21
    key22
  key3
```
I cannot query a list of the direct children of root (root/key1, root/key2, root/key3), I need something like GET v1/kv/root?keys=true&depth=1
I have 300 keys under the root, and each of them has 10000 child keys in the subtree in some hierarchy way. I should be able to get the 300 keys, without the child keys at all depths, which is 3 million keys.

I can use the separator to hack it but it's very cumbersome.

I guess Consul is using flat keys, not stored in a hierarchical way, so it might be somehow difficult to implement this API in the core, but at least, please provide a range filter at the API level to limit the result set.  e.g., a depth parameter.

#### Use Case(s)

To traverse children of a key, just one level or two levels.

**Comment by Amier3** [comment]
Hey @DanielYWoo 

Thanks for making this feature request! You're correct that keys are not stored in a hierarchical way, so it would be a big undertaking to change that. I do think it's reasonable that we could provide a range filter to limit results though.

With KV feature requests, I like to quote the following from our KV docs:

> Consul KV allows users to store indexed objects, though its main uses are storing configuration parameters and metadata. Please note that it is a simple KV store and is not intended to be a full featured datastore (such as DynamoDB) but has some similarities to one. 

So when evaluating feature requests we have to look at it's use case through the lenses of storing configuration, metadata, etc. That being said I do think this has valid networking use cases, but I don't think we'd be able to take this up anytime soon.  For now, i'll change the title to reflect the preferred solution here ( range filter limiting ) and add a label to encourage a PR from our community 😄.

**Comment by DanielYWoo** [comment]
We understood your point when we chose Consul, and we are not using Consul like Cassandra or Dynamo, we use Consul solely for application configuration, we just put all application-level configurations into Consul in 40+ data centers, and some configuration often changes, and we have applications to detect, compare, validate changes, and we also have a service similar to Consul Sync. These kinds of usage cause a lot of pressure to Consul, so any optimizations help a lot. I also have two PRs recently in Spring Cloud Consul to optimize the pressure to Consul. Maybe we are just one of the few companies hitting the wall first.
Anyway, close it as we don't have a plan for it, I will try something else. Thanks for the detailed explanation ;-)
