### ISSUE TITLE
agent service registration check not called

### ISSUE THREAD

**Issue by rogeralsing** [hashicorp/consul#1312]
I am unable to get the service checks to work on Windows.

I have this endpoint, which I replies "ok" when I hit the URI with a get:

![endpointworks](https://cloud.githubusercontent.com/assets/647031/10540242/9e983d66-7406-11e5-8dae-5324f5c3aab4.png)

If I then register a service in Consul like so:

![intervalnotworking](https://cloud.githubusercontent.com/assets/647031/10540321/374847a4-7407-11e5-99fe-8eaf746a6730.png)

The service is registered and I can check healthstatus etc via the rest api.
But, my check HTTP endpoint is never hit, I have tried with small values, large values etc on the `Interval`. 
Nothing happens, and eventually the `TTL` expires the service.

Is it me holding this wrong or is there an issue when running Consul on Windows ?(single node cluster for dev)

**Comment by ryanbreen** [comment]
We run lots of http checks from Windows, so I can confirm it works. 

I don't believe your check config is valid because it has interval, ttl, and http params. An http check should just be http and interval: https://www.consul.io/docs/agent/checks.html

**Comment by rogeralsing** [comment]
Ohhh.. works like a charm now.
Thanks!

Closing this
