### ISSUE TITLE
Dash docset

### ISSUE THREAD

**Issue by johntdyer** [hashicorp/consul#1314]
It would be nice if there were a Dash docset for Consul for offline reference ( https://kapeli.com/docsets )

**Comment by blalor** [comment]
I’d really like to see the work I did for #555 be expanded and made a part of the Consul project.  The Consul api is complex enough that we’d really benefit from robust docs like http://docs.consul.apiary.io/.

**Comment by nrshrivatsan** [comment]
:100:  :+1:

**Comment by slackpad** [comment]
Closing this out as we don't have plans to do this at this time.
