### ISSUE TITLE
DNS Interface returns **all** services on A requests (not only available ones)

### ISSUE THREAD

**Issue by frntn** [hashicorp/consul#1325]
## Context

In my consul-enabled infrastructure I have a neo4j cluster.

Each 3 member of the neo4j cluster runs a consul agent in client mode and defines 3 services : 
* `neo4j`
* `neo4j-master`
* `neo4j-slave`

In the consul-ui I can see the services are defined correctly as the checks are ok on : 
* the three nodes for neo4j
* the master node for neo4j-master
* the slave nodes for neo4j-slave

But...

## What I do

When trying to access the `neo4j-master` using the DNS interface I get all 3 ip addresses of the nodes.
Same thing for `neo4j-slave` service

## What I get

```bash
curl -s http://127.0.0.1:8500/v1/catalog/services
{
  "neo4j": [ ],
  "neo4j-master": [],
  "neo4j-slave": []
}

dig +short neo4j.service.consul 
10.x.x.1
10.x.x.2
10.x.x.3

dig +short neo4j-master.service.consul 
10.x.x.1
10.x.x.2
10.x.x.3

dig +short neo4j-slave.service.consul 
10.x.x.1
10.x.x.2
10.x.x.3
```

## What I expected

```bash
dig +short neo4j.service.consul 
10.x.x.1
10.x.x.2
10.x.x.3

dig +short neo4j-master.service.consul 
10.x.x.1

dig +short neo4j-slave.service.consul 
10.x.x.2
10.x.x.3
```

Am I wrong expecting this behavior ?

**Comment by frntn** [comment]
In the getting started we can read the following : 

> As you can see, an A record was returned with the IP address of the node on which the service is available.

By `available` do you mean `declared` ? Because that the behavior I actually have right now...

**Comment by frntn** [comment]
Finally find out : 
**services in `warning` state are considered available.**

I had to adapt my checks to exit with status code `> 1` to get the expected behavior.

**Comment by slackpad** [comment]
@frntn and in case anyone else looks at this ticket there's also a https://www.consul.io/docs/agent/options.html#only_passing config option that controls this.

**Comment by frntn** [comment]
Oh great ! That's good to know. 
Thx
