### ISSUE TITLE
alt_domain doesn't accept an FQDN only a single-word string

### ISSUE THREAD

**Issue by jebotz** [hashicorp/consul#13307]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Consul's alt_domain config parameter doesn't accept an FQDN only a single-word string

This may be intended behavior, but if so it isn't documented as far as I can tell.  The docs speak of
"domain" and a domain in common parlance can have dots in it.

#### Reproduction Steps

When...
```
  alt_domain="foo"
```
then
```
  nslookup something.service.foo localhost
```
works (I have port 53 nat-ed to 8600).  But...
```
  alt_domain="foo.com"
  nslookup something.service.foo.com localhost 
```
returns
```
  ** server can't find something.service.foo.com: REFUSED
```
### Consul info for both Client and Server

Consul v1.11.4
Revision 944e8ce6

**Comment by Amier3** [comment]
@jebotz 

It's always fun when the issue seems to randomly fix itself 😆 . I'm going to close this out for now as ' not planned ', but feel free to re-open if this issue crops up again.
