### ISSUE TITLE
v0.5.2 updatedeps isn't pulling in gox

### ISSUE THREAD

**Issue by ch-acctg** [hashicorp/consul#1330]
If you run make updatedeps instead of having make later fetch:

---
Installed Go for linux/amd64 in /var/lib/jenkins/workspace/sg.consul/label/jessie/go
Installed commands in /var/lib/jenkins/workspace/sg.consul/label/jessie/go/bin
+ cd /var/lib/jenkins/workspace/sg.consul/label/jessie/go-pkg/src/github.com/hashicorp/consul
+ git checkout v0.5.2
HEAD is now at 9a9cc93... Adding dep
+ make updatedeps
--> Installing build dependencies
github.com/armon/circbuf (download)

github.com/armon/go-metrics (download)
github.com/hashicorp/consul-migrate (download)

github.com/hashicorp/raft (download)
github.com/hashicorp/go-msgpack (download)

github.com/hashicorp/raft-boltdb (download)
github.com/boltdb/bolt (download)

github.com/hashicorp/raft-mdb (download)

github.com/armon/gomdb (download)
github.com/armon/go-radix (download)

github.com/hashicorp/golang-lru (download)
github.com/hashicorp/hcl (download)

github.com/hashicorp/go-multierror (download)
github.com/hashicorp/errwrap (download)
github.com/hashicorp/memberlist (download)

github.com/hashicorp/serf (download)

github.com/hashicorp/yamux (download)

github.com/inconshreveable/muxado (download)

github.com/hashicorp/go-checkpoint (download)
github.com/hashicorp/go-cleanhttp (download)

github.com/hashicorp/go-syslog (download)
github.com/hashicorp/logutils (download)
github.com/hashicorp/scada-client (download)

github.com/hashicorp/net-rpc-msgpackrpc (download)
github.com/miekg/dns (download)

github.com/mitchellh/cli (download)
Fetching https://golang.org/x/crypto/ssh/terminal?go-get=1

Parsing meta tags from https://golang.org/x/crypto/ssh/terminal?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh/terminal": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh/terminal?go-get=1
get "golang.org/x/crypto/ssh/terminal": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
github.com/mitchellh/mapstructure (download)
github.com/ryanuber/columnize (download)

--> Updating build dependencies

+ make
--> Installing build dependencies
--> Running go fmt
command/agent/check.go

command/agent/http_test.go
command/agent/ui_endpoint_test.go
bash: cannot set terminal process group (27109): Inappropriate ioctl for device
bash: no job control in this shell
==> Getting dependencies...

==> Removing old directory...
==> Building...
bash: gox: command not found
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 127
Build step 'Execute shell' marked build as failure

**Comment by slackpad** [comment]
Fixed this in master via https://github.com/hashicorp/consul/commit/7db346886528fe463cf9bbfd2f6f70acc17666d3.
