### ISSUE TITLE
publish new version of api

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/consul#13305]
#### Feature Description

Publish a new version of api https://pkg.go.dev/github.com/hashicorp/consul/api that supports customized tls version for ingress gateway.

#### Use Case(s)

https://github.com/hashicorp/nomad/pull/13184
to consume the api functionality in dependent project.

**Comment by rboyer** [comment]
`github.com/hashicorp/consul/api@v1.13.0` is live now with [those fields](https://pkg.go.dev/github.com/hashicorp/consul/api@v1.13.0#GatewayTLSConfig)

**Comment by fredwangwang** [comment]
thanks!
