### ISSUE TITLE
Consul check that times out does not provide any body or diagnostic information

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#1332]
If a Consul check (Script and HTTP verified) time out waiting for the check, they do not provide any notice in the output. The check does properly go into the critical state, but it is not clear to an operator why that is the case. We should include something like "Consul check timed out after 30s"

**Comment by i0rek** [comment]
There is a message now indicating the timeout: https://github.com/hashicorp/consul/blob/sweet_cipher/agent/checks/check.go.
