### ISSUE TITLE
Website header is overlapping content

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/consul#1334]
<img width="924" alt="screen shot 2015-10-25 at 5 50 22 pm" src="https://cloud.githubusercontent.com/assets/408570/10718110/f9104c0c-7b40-11e5-9e8c-4713c071b76f.png">
<img width="1421" alt="screen shot 2015-10-25 at 5 50 27 pm" src="https://cloud.githubusercontent.com/assets/408570/10718111/f915f3e6-7b40-11e5-9c3f-affafe6f0382.png">

**Comment by slackpad** [comment]
Original context here:

> @TannerFilip reported on https://webcompat.com/issues/1806 a bug about Header which isn't readable on Firefox (and Same on Internet explorer).
> This patch fixes the bug.
> webcompat/web-bugs#1806

So my patch will re-break it on FF and IE, if there's a fix that satisfies those it would be good to get in here.

**Comment by ryanbreen** [comment]
Having as weak CSS as I do, I shouldn't have merged that patch.  My bad.
