### ISSUE TITLE
ACL are not getting enabled

### ISSUE THREAD

**Issue by AjeetK** [hashicorp/consul#1347]
I have setup consul on a single instance. The web-ui was working fine when I started the consul by the following command
>consul agent -server -bootstrap -data-dir /tmp/consul -ui-dir /home/ubuntu/dist/ -client=X.X.X.X' 

Where X.X.X.X is the private IP of my instance.
When I included acl_datacenter option in the /etc/consul.d/bootstrap/config.json file. The ACL are not getting enabled.
I also tried to include acl_datacenter in /etc/consul/server/config.json file but still ACL are not getting enabled.

**Comment by armon** [comment]
@AjeetK You need to have Consul read the configuration files, either using the `-config` or `-config-dir` parameters so that it will load those JSON files.
