### ISSUE TITLE
Support for establishing the contactable IP address on join?

### ISSUE THREAD

**Issue by wrouesnel** [hashicorp/consul#1348]
While deploying consul to my datacenter, I found a whole bunch of nodes kept flapping. The problem turns out to be that consul is simply picking the first IP address to advertise, rather then inspecting which IP it's using to communicate with the server instances. This IP is an internal, unrouteable one from the VM system (old, but highlights the problem).

To fix this at the moment I'm having to add some custom scripting to set the advertise IP for these nodes, but it would be far better if consul would check the routable IP when joining if no advertise is set, and use the one which is _probably_ the one I want it to.

This is the routing table I end up with on some of my hosts:

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
192.168.100.64  0.0.0.0         255.255.255.192 U     0      0        0 br25
192.168.101.64  0.0.0.0         255.255.255.192 U     0      0        0 br25
192.168.97.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.1.0.0        192.168.100.65  255.255.0.0     UG    0      0        0 br25
192.168.0.0     192.168.100.65  255.255.0.0     UG    0      0        0 br25
0.0.0.0         192.168.101.65  0.0.0.0         UG    0      0        0 br25
```

The 192.168.97.0 address doesn't go anywhere, all connections end up coming from 192.168.100.64. There doesn't seem to be an easy way to sort this out except at deployment time or possibly by hacking my init scripts.

EDIT: The workaround is fairly ugly at the moment - template consul.json based on the result of a shell command to get the IP address and route to the host I'm joining.

**Comment by mvryan** [comment]
I have run into this issue recently also. 
If there were simply a self check to verify it can be reached on that port and if not fail rather than the more complicated to debug flapping problem.

**Comment by slackpad** [comment]
Consul now refuses to start if it's ambiguous which address it should use, and we've integrated https://github.com/hashicorp/go-sockaddr templates for more advanced automatic determination of addresses by range, interface name, etc. so closing this out.
