### ISSUE TITLE
Some Consul metrics are reported with a doubled prefix: consul.consul....

### ISSUE THREAD

**Issue by maxb** [hashicorp/consul#13494]
Consul includes a `metrics_prefix` setting, which is added as a prefix to every metric name, through the built-in functionality of the underlying https://github.com/armon/go-metrics library.

The default value is set here: https://github.com/hashicorp/consul/blob/edbf19f4e88e81cda0fa52bbbb463cf1d686fe12/agent/config/default.go#L129

As you can see, the default value is `consul`. Most of the metrics defined throughout Consul therefore are defined expecting this will be added - e.g.: https://github.com/hashicorp/consul/blob/9e986c62e4d6500e10422f941d159a2327adbeca/agent/consul/session_ttl.go#L152-L155

However some of them are defined ignoring that this prefixing behaviour exists - e.g.: https://github.com/hashicorp/consul/blob/1e02460bd1a5655093928ea2927901a71a37060a/agent/consul/usagemetrics/usagemetrics_oss.go#L73

with the result that when the operator of the Consul cluster gets to see the above metric, it is actually called `consul.consul.state.kv_entries` - or, given the name mapping applied to metrics when using Prometheus, `consul_consul_state_kv_entries`.

This is confusing, and the discrepancy is not mentioned in the docs - <https://www.consul.io/docs/agent/telemetry> - which document metrics without the unintentional doubling - just `consul.state.kv_entries`.

This mistake should be corrected - but there are compatibility concerns. I am willing to create a PR - this issue is for the purpose of discussing the compatibility mechanism prior to implementation.

I am proposing to duplicate the approach already in use for the `consul.http.` -> `consul.api.http.` transition - write both metrics for an overlap period, and allow transitional control via the config file option `telemetry { disable_compat_1.9 = true }`.

A question for HashiCorp release management people: I see Consul 1.13.0-alpha1 has been released - can the initial steps, i.e.:

* Adding new correctly named versions of the metrics
* Adding new config option `telemetry { disable_compat_1.13 }` with initial default value `false`
* Declaring old `consul.consul.*` metrics deprecated and to be removed in a future version

still target 1.13 at this point, or do they need to target 1.14?

**Comment by maxb** [comment]
The above-mentioned PR #13497 is not intended to be merged, as it contains no compatibility handling, but serves to display the metrics code needing changes.

**Comment by Amier3** [comment]
Hey @maxb 

Thanks for the detailed write-up on this issue and the quick PR. The team will meet together tomorrow to talk about and i'll make sure we get some info back to you on how we'd like to go about fixing this... 

To answer your release question, this would very likely be targeted for 1.14.  It's unlikely we would add in a potentially breaking change between the alpha and general release ( unless it was a security issue ), and targeting the next release will give us time to evaluate if we need to bungle these changes with #13495 #13498

**Comment by maxb** [comment]
> if we need to bungle these changes with #13495 #13498

Although all of these changes are in the general area of metrics, I believe the solution to each has little bearing on the others.

This one in particular, is a separate unit of work entirely within `hashicorp/consul` - whereas the other two are likely to need some work done in `armon/go-metrics` as well.

**Comment by maxb** [comment]
I raised this via my company's HashiCorp Customer Success Manager and was told a fix is on the way internally within HashiCorp, so I guess you don't need anything more from me here.

It looks like some work has already taken place, in the auto-associated PR.
