### ISSUE TITLE
Allow Disabling Retries in consul watch Command

### ISSUE THREAD

**Issue by smreichling** [hashicorp/consul#1350]
I'm finding that a frequent use case I have for `consul watch` is just to check the current state of a kv prefix, without registering a command, something like:
```
consul watch --type keyprefix --prefix "some/prefix"
```
I do this in some nagios check scripts which essentially verify that the state of data in consul is what I expect it to be.

As long as the Consul cluster is operational, this works fine, but if it's down for whatever reason this command hangs indefinitely since it enters a retry loop. It'd be nice if there was a "quick fail" command line arg which prevents the retry and simply exits with a non-zero exit code if there's any problem performing the request.

I'm aware of consulate and it's ability to lookup keys/prefixes in the consul kv but so far as I can tell there is no way to get it to spit out the ModifyIndex of a key which I need for my use case. `consul watch`'s output works perfectly, save the retry problem.

**Comment by macb** [comment]
Not to detract from the enchancement suggestion but it seems like you might be better served accessing the HTTP API for the KV.
```
curl http://127.0.0.1:8500/v1/kv/some/prefix?recurse
```

Would dump:
```
[  
  {
    "Value": null,
    "Flags": 0,
    "Key": "some/prefix/somekey1",
    "LockIndex": 2,
    "ModifyIndex": 42,
    "CreateIndex": 24
  },
{
    "Value": null,
    "Flags": 0,
    "Key": "some/prefix/somekey2",
    "LockIndex": 2,
    "ModifyIndex": 42,
    "CreateIndex": 24
  }
]
```

The only thing that seems inconsistent from the view `watch` gives you is there is no `Session` information.

**Comment by smreichling** [comment]
Good point, using curl actually works perfect for what I need. Thanks for the idea!

In that case, I no longer have a use case that requires this feature. I'll go ahead and close the issue.
