### ISSUE TITLE
HTTP API - Health/state should have a 'failing' status

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/consul#1355]
According to the docs: "The supported states are any, unknown, passing, warning, or critical. The any state is a wildcard that can be used to return all checks."

I think we should have a '**failing**' state (or similar) that joins warning+critical. This could be useful for the watches functionality, because you can track both states in a single watch ( so you can make a watch that send notifications via mail, for example).

What do you think?
Thank you in advance and keep up the good work guys, really awesome product.

**Comment by ryanuber** [comment]
This could be useful. Maybe a good way of doing it would be to add some query parameter that you could specify multiple times, such that you can get a combination of whatever health status you need. The main problem is that this doesn't fit well with the current `/v1/health/state/<state>` endpoint, but maybe there are improvements we can make there. Marking as an enhancement for now, thanks!

**Comment by slackpad** [comment]
Closing this out since there hasn't been a ton of interest in it from the community. Watch scripts can see everything and post-filter.
