### ISSUE TITLE
Consul v1.12.2 - rpc error making call: i/o deadline reached 

### ISSUE THREAD

**Issue by ngcmac** [hashicorp/consul#13695]
####  Overview of the Issue

After upgrade to Consul v1.12.2, we start seeing on the clients a lot of these errors:

[ERROR] agent.client: RPC failed to server: method=ConnectCA.Roots server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=Intention.Match server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=ConfigEntry.ResolveServiceConfig server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=DiscoveryChain.Get server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"

Although Consul is throwing the erros,  everything seems to work ok.
We use Consul with ACL + TLS + Connect enabled + Nomad
Downgrading to Consul v1.11.3 (our previous version) the errors stop.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 2
	services = 2
build:
	prerelease =
	revision = 19041f20
	version = 1.12.2
	version_metadata =
consul:
	acl = enabled
	known_servers = 3
	server = false
runtime:
	arch = arm64
	cpu_count = 4
	goroutines = 117
	max_procs = 4
	os = linux
	version = go1.18.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 21
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 7
	member_time = 87554
	members = 16
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 4
	services = 4
build:
	prerelease =
	revision = 19041f20
	version = 1.12.2
	version_metadata =
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = xxx.xxx.xxx.xxx:8300
	server = true
raft:
	applied_index = 8198113
	commit_index = 8198113
	fsm_pending = 0
	last_contact = 0
	last_log_index = 8198113
	last_log_term = 189
	last_snapshot_index = 8188080
	last_snapshot_term = 189
	latest_configuration = [{Suffrage:Voter ID:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX Address:xxx.xxx.xxx.xxx:8300} {Suffrage:Voter ID:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX Address:xxx.xxx.xxx.xxx:8300} {Suffrage:Voter ID:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX Address:xxx.xxx.xxx.xxx:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 189
runtime:
	arch = arm64
	cpu_count = 2
	goroutines = 378
	max_procs = 2
	os = linux
	version = go1.18.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 21
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 7
	member_time = 87556
	members = 16
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 123
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

AWS EC2, Debian11 / Ubuntu Server 20.04 (amd64/amr64)

### Log Fragments

[ERROR] agent.client: RPC failed to server: method=ConfigEntry.Get server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=ConnectCA.Roots server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=ConfigEntry.ResolveServiceConfig server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=Intention.Match server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=DiscoveryChain.Get server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=ConfigEntry.ResolveServiceConfig server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=ConfigEntry.ResolveServiceConfig server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=Intention.Match server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=ConfigEntry.Get server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=ConfigEntry.ResolveServiceConfig server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.client: RPC failed to server: method=ConnectCA.Roots server=xxx.xxx.xxx.xxx:8300 error="rpc error making call: i/o deadline reached"

**Comment by Amier3** [comment]
Hey @ngcmac 

Thanks for reporting this issue! [v1.12.2](https://github.com/hashicorp/consul/releases/tag/v1.12.2) fixed another reported [issue](https://github.com/hashicorp/consul/issues/13303) that was emitting this same `io deadline reached` message, so i'm wondering if this is another manifestation of the same problem. 

Are all your servers/clients upgraded to v1.12.2?

**Comment by seanamos** [comment]
I'm seeing exactly the same thing on `v1.12.2`. Our edge proxy is traefik using its native Consul Connect integration. Regularly in the traefik and consul logs there `io deadline reached` errors.

From the traefik side:
```
{"@level":"error","@message":"Watch errored","@module":"consulcatalog.watch","@timestamp":"2022-07-11T12:51:14.297545Z","error":"Unexpected response code: 500 (rpc error making call: i/o deadline reached)","retry":5000000000,"type":"connect_roots"}
{"@level":"error","@message":"Watch errored","@module":"consulcatalog.watch","@timestamp":"2022-07-11T13:01:22.656641Z","error":"Unexpected response code: 500 (rpc error making call: rpc error making call: i/o deadline reached)","retry":5000000000,"type":"connect_roots"}
```

I can't see any actual impact though, everything seems to be working.

**Comment by Amier3** [comment]
@seanamos @ngcmac 

It might be helpful to see the full, timestamped logs that capture before and after this error message to understand what might be happening. It would also be helpful to see the agent config for one of the clients.

**Comment by chrisboulton** [comment]
We ran into this in our test environments today and had to pretty quickly roll back to v1.11. We mostly noticed them around the service health and discovery chain RPCs for our Connect integrated services. I agree they mostly seem to be around the caching layer, with messages such as:

```
agent.client: RPC failed to server: method=DiscoveryChain.Get server=xx:8300 error="rpc error making call: i/o deadline reached"
agent.cache: handling error in Cache.Notify: cache-type=compiled-discovery-chain error="rpc error making call: i/o deadline reached" index=37080582

agent.cache: handling error in Cache.Notify: cache-type=health-services error="rpc error making call: i/o deadline reached" index=37072324
agent.client: RPC failed to server: method=Health.ServiceNodes server=xxx:8300 error="rpc error making call: i/o deadline reached"
```

**Comment by MagicRB** [comment]
I'm still getting this on 1.12.3, goes away after a restart.

**Comment by alt-dima** [comment]
I also have those errors in version 1.13.1
```
│ 2022-08-12T20:59:07.862Z [ERROR] agent.client: RPC failed to server: method=DiscoveryChain.Get server=10.150.14.197:8300 error="rpc error making call: i/o deadline reached"                                                                             │
│ 2022-08-12T20:59:07.862Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=compiled-discovery-chain error="rpc error making call: i/o deadline reached" index=589824                                                                       │
│ 2022-08-12T20:59:08.203Z [ERROR] agent.client: RPC failed to server: method=DiscoveryChain.Get server=10.150.14.197:8300 error="rpc error making call: i/o deadline reached"                                                                             │
│ 2022-08-12T20:59:08.203Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=compiled-discovery-chain error="rpc error making call: i/o deadline reached" index=589824                                                                       │
│ 2022-08-12T20:59:09.818Z [ERROR] agent.client: RPC failed to server: method=Internal.PeeredUpstreams server=10.150.14.197:8300 error="rpc error making call: i/o deadline reached"                                                                       │
│ 2022-08-12T20:59:09.818Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=peered-upstreams error="rpc error making call: i/o deadline reached" index=1                                                                                    │
│ 2022-08-12T20:59:10.932Z [ERROR] agent.client: RPC failed to server: method=DiscoveryChain.Get server=10.150.14.197:8300 error="rpc error making call: i/o deadline reached"                                                                             │
│ 2022-08-12T20:59:10.933Z [WARN]  agent.cache: handling error in Cache.Notify: cache-type=compiled-discovery-chain error="rpc error making call: i/o deadline reached" index=589824
```

**Comment by jameshartig** [comment]
We're also seeing this issue with 1.13.1 with the `Catalog.NodeServices` method

**Comment by jameshartig** [comment]
I believe this was caused by #11500. When the stream's `FirstReadTimeout` is less than the server's `blockingQuery` timeout then the stream is closed with an `i/o deadline exceeded` error. This could be caused because there's jitter on both sides and if the client-side jitter was randomly less than the servers then the client will time out before the server. Ideally the client's read timeout should be set based on the maximum possible jitter. @wjordan does that seem plausible?

**Comment by jameshartig** [comment]
I verified the above fix on our dev environment. We saw no `RPC failed to server` for the last 12 hours after deploying that fix.

**Comment by kisunji** [comment]
Thank you @jameshartig for the investigation and quick fix 🕵️ 
It will be backported to the next patch versions of 1.12 and 1.13

**Comment by jofowler** [comment]
I own the code for a Go client that uses the Hashicorp consul Go api. We are currently encountering this error a lot. I see that a fix will be out soon. Is there a change that I could make on the client side to avoid this error? If so, which timeout value would I need to change and what should I change it to? Thanks.

**Comment by havedill** [comment]
> Could very well be that, i got this error between agents in two different geographic locations with an unstable link

Could this occur on agents that have a stable link, but across a far distance? I have a dev cluster on 1.13.2, which supposedly has the fix, but i still get i/o deadline reached when interacting with the consul dashboard/api

I'm using a raft_mulitplier of 1. I wonder if i need to increase that

**Comment by kisunji** [comment]
> > Could very well be that, i got this error between agents in two different geographic locations with an unstable link
> 
> Could this occur on agents that have a stable link, but across a far distance? I have a dev cluster on 1.13.2, which supposedly has the fix, but i still get i/o deadline reached when interacting with the consul dashboard/api. Most our agents/leaders are in chicago, but we have another few that live off in London/Germany
> 
> I'm using a raft_mulitplier of 1. I wonder if i need to increase that

Are both clients and servers on 1.13.2? RPC timeouts can technically still happen with large enough clusters if they exceed 7 seconds while building a response.

A similar issue was raised in https://github.com/hashicorp/consul/issues/14732. In 1.13.3 we introduced `rpc_client_timeout` [docs] which defaults to 60s (over 7s) and can be tuned with no impact to raft stability (https://developer.hashicorp.com/consul/docs/agent/config/config-files#rpc_client_timeout)
