### ISSUE TITLE
Child namepsaces

### ISSUE THREAD

**Issue by gfonseca-tc** [hashicorp/consul#13704]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Vault supports having child namespaces and it makes much easier and cleaner to do multi tenancy. It makes no sense to me that vault supports it and Nomad and Consul doesn't. I've already opened [an issue](https://github.com/hashicorp/nomad/issues/13650) requesting this feature in Nomad repo so I'm also doing it here in the hope all three products will have this feature available in the future. The feature is basically allowing a namespace tree to be created, separating them by slashes like vault does.

#### Use Case(s)

In complex architectures the need of data segregation can be very important and being able to separate everything by namespace with the same names would be very different. The approach we use currently is to have a naming standard that allows us to match the child namespaces in vault to others in nomad and consul. It's not easy to handle and quite complicated to automate. Having the namespace feature the same in all products would be a great achievement!

**Comment by Amier3** [comment]
Hey @gfonseca-tc 

Thanks for this proposal! I really like this idea. We try to solve the overall problem of [multi-tenancy](https://learn.hashicorp.com/tutorials/consul/consul-admin-partitions?in=consul/enterprise) with our [Enterprise](https://www.hashicorp.com/products/consul?utm_source=oss&utm_medium=header-nav&utm_campaign=consul) and [Cloud](https://cloud.hashicorp.com/products/consul) product with namespaces and [admin partitions](https://www.consul.io/docs/enterprise/admin-partitions). Namespaces can be used the same way as Vault and can also include KV metadata defined in the namespace config -- then groups of namespaces can be nested under an admin partition to achieve the use case you describe in this post. 

Still, that doesn't solve the problems of syncing namespaces across products or segregating beyond one level ( partition --> namespace1 <--> namespace2   ). It might be difficult to get name-spacing the **exact same** as Vault, but we could potentially map partitions to top-level parent namespaces in Vault. I'll talk with the team and let you know our broader thoughts on this soon.

**Comment by david-yu** [comment]
Will go ahead and close as there currently is no plan to provide child namespaces within Consul as Admin Partitions and namespaces currently the majority of multi-tenancy use cases. I will also say that Vault namespaces are not scoped to a single network and can be scoped to multiple networks, whereas with Consul we use namespaces within the same network. So there is a difference in scope in terms of how Consul and Vault use namespaces.
