### ISSUE TITLE
deregister checks when serf ReconnectTimeout reached

### ISSUE THREAD

**Issue by half-dead** [hashicorp/consul#1370]
under consul 0.5.2
When Serf ReconnectTimeout reached, the node will be removed from the cluster, but the checks associated with this node weren't deregistered.

**Comment by half-dead** [comment]
@slakpad please take a look at this

**Comment by slackpad** [comment]
Hi @half-dead do you have any logs or other debugging info related to this? I haven't been able to reproduce this.

**Comment by half-dead** [comment]
Thanks for the response, I can't reproduce this under v0.5.2 or v0.6.1either, closing now.
