### ISSUE TITLE
Consul binds to docker iface

### ISSUE THREAD

**Issue by xmackex** [hashicorp/consul#1372]
Hello, I've been following docs related to consul bootstrap but unfortunately faced weird issue with IP binding. I have docker launched on my machine (with 1 container running and 5000 port exposed).

Consul cersion:
```
# consul -v
Consul v0.5.2
Consul Protocol: 2 (Understands back to: 1)
```
I start consul with a simple command:
```
# consul agent  -config-dir /etc/consul.d/bootstrap
```
 My /etc/consul.d/bootstrap/config.json:

```
{
    "bootstrap": true,
    "server": true,
    "datacenter": "test-1",
    "data_dir": "/var/consul",
    "encrypt": "X4SYOinf2pTAcAHRhpj7dA==",
    "log_level": "INFO",
    "enable_syslog": true
}
```
Network:
```
# ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.32.0.159
# ifconfig docker0
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.17.42.1
```

After command run I see:
```
# rm -rf /var/consul/*
# consul agent  -config-dir /etc/consul.d/bootstrap
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting raft data migration...
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'master.bkstg.com'
        Datacenter: 'test-1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 172.17.42.1 (LAN: 8301, WAN: 8302)
```
```
# netstat -tulpn | grep 8300
tcp        0      0 172.32.0.159:8300       0.0.0.0:*               LISTEN      4786/consul
```

So I wonder if I'm missing something or this is a bug.

**Comment by ryanuber** [comment]
Hi @xmackex,

Can you confirm that just the one config file is in use? Maybe try starting with `-config-file=/etc/consul.d/bootstrap/config.json`. If there are any `bind_addr` settings, that can affect the address that the internal server RPC layer will bind to. Consul shouldn't be picking this address all on its own for this purpose.

**Comment by slackpad** [comment]
@xmackex did you figure this one out? Please re-open if you are still having trouble!
