### ISSUE TITLE
SDK forces the usage of namespace

### ISSUE THREAD

**Issue by Pyr0ss** [hashicorp/consul#13829]
When I run  golang in kubernetes and use the golang sdk to register a service, it forces the usage of "ns" in the query, which is a Consul Enterprise feature. This results in the call failing : **Unexpected response code: 400 (Bad request: Invalid query parameter: "ns" - Namespaces are a Consul Enterprise feature)**. The Namespace in Config is set automatically when I'm not setting it, but I would like it to not be set so that _ns=..._ doesn't appear in the query url.
When run locally there is no issue, the issue appears only when executing the code from inside kubernetes.

**Comment by Amier3** [comment]
Hey @Pyr0ss 

Thanks for reporting this bug. Could you re-submit this report with the required bug template? It helps us get the necessary info needed to figure out what's going on.
