### ISSUE TITLE
acl: how to deny deregister

### ISSUE THREAD

**Issue by anklos** [hashicorp/consul#1383]
I use docker image `gliderlabs/docker-consul` to set up a single consul and have the consul.json config like below:

``` json
{
  "datacenter": "redbook1",
  "acl_master_token": "redbook",
  "acl_datacenter": "redbook1",
  "acl_default_policy": "deny",
  "data_dir": "/data",
  "ui_dir": "/ui",
  "client_addr": "0.0.0.0",
  "ports": {
    "dns": 53
  },
  "recursor": "8.8.8.8",
  "disable_update_check": true
}
```

So most things work as expected (i.e cannot register service without token, cannot update key/value without proper rules), except:
1. I can still deregister node without token on UI.
2. I can still see all the nodes and services without token on UI.

Is it possible to deny those requests from ACL? Thanks!

**Comment by highlyunavailable** [comment]
As per the [ACL System](http://www.consul.io/docs/internals/acl.html) documentation, ACLs are currently only supported for the K/V store and Services.

So no, at this time, it's not possible to do what you want. I believe the Hashicorp guys have stated it's on the roadmap for the future but it's not available right now.

**Comment by slackpad** [comment]
Service discovery ACLs were added in https://github.com/hashicorp/consul/pull/1024 and are part of the upcoming Consul 0.6. Deregister isn't currently covered so I'll mark this as an enhancement.

**Comment by anklos** [comment]
Thanks!

**Comment by cleung2010** [comment]
How come the UI on the demo (http://nyc3.demo.consul.io/ui/#/nyc3/nodes/nyc3-server-1) not have the "Deregister" button? Is it because it's running an older version of Consul/UI before #364 was implemented?

**Comment by slackpad** [comment]
Hi Calvin - yes we are in the process of updating it. The demo has some
extra branding for Digital Ocean so we need to update a fork with those
changes and the latest ui code.

On Wed, Dec 2, 2015 at 8:37 AM, Calvin Leung Huang <notifications@github.com

**Comment by zeldal** [comment]
Is there any1 working for this issue? Since 0.6 is out and it still doesnt control deregister request. we need this before production deployment, i will make fix for our deployments and pull here.

**Comment by slackpad** [comment]
Hi @zeldal this didn't make it into 0.6.1 but we will try to get it into the next release.

**Comment by zeldal** [comment]
We are gonna make some protections with different tools to avoid this for now. I will be eager to upgrade newer version when this is fixed. 
Best regards.

**Comment by fatlazycat** [comment]
Hi, any plans to release this shortly ? Unfortunately given the nature of SSL certs it's going to be wide open in my company and would like to lock this down.

**Comment by rbrutas** [comment]
+1 on the need to deny node de-registration from the UI

**Comment by antimack** [comment]
+1 same to me, need to disable "deregister" in the UI for anonymous ACL

**Comment by zhwmega** [comment]
Version 0.6.4. ACL can't control the "deregister" button in the UI?

**Comment by bbanzai** [comment]
+1 giving persons an acl to manage their configuration values on a kv tree also allows them to deregister nodes.  If these nodes drive consul-template it could cause havoc in an environment.  deregister could be, in the short-term, limited to only the master token (but should not affect consul agent behavior).

**Comment by danlsgiga** [comment]
+1 for this feature. Deregister is a very powerful option to have it wide open.
For now I'm working around it commenting out the HTML code for the ui to disable showing the button, but this is ugly.

**Comment by claudio-viola** [comment]
This is needed!

**Comment by jwbennet** [comment]
It appears that the demo Consul instance at demo.consul.io is returning a 403 whenever you attempt to deregister a node.  How does that work at the moment if this is still an open issue?

**Comment by slackpad** [comment]
@jwbennet that setup is behind a proxy.

**Comment by jwbennet** [comment]
I see, thank you for the information.  Is there any documentation on endpoints which should be disabled behind the proxy like that until proper ACLs are in place?  I'm assuming at least "/v1/catalog/deregister" to handle this for the UI and probably "/v1/agent/force-leave/<node>".  The "/v1/agent/maintenance" endpoint also seems like it could be problematic as well unless it is handled by one of the other ACLs?

**Comment by claudio-viola** [comment]
Did this change make it into 0.7.0?

**Comment by slackpad** [comment]
@claudio-viola it didn't make it into 0.7.0 - it's high on the list for a follow-on release.

**Comment by claudio-viola** [comment]
thanks for letting us know @slackpad !

**Comment by slackpad** [comment]
Support for this was added in 0.7.2 on an opt-in basis and will be opt-out in 0.8 - https://www.consul.io/docs/internals/acl.html#version_8_acls.
