### ISSUE TITLE
Repository error

### ISSUE THREAD

**Issue by larry-s** [hashicorp/consul#13850]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

I am getting an error when trying to install Consul using apt.

Steps to reproduce this issue, eg:

On a fresh Linux VM
- run `curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -`
- run `sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"`

I get the error:
```
Get:7 https://apt.releases.hashicorp.com bionic/main amd64 Packages [60.2 kB]
Err:7 https://apt.releases.hashicorp.com bionic/main amd64 Packages
  File has unexpected size (59610 != 60177). Mirror sync in progress? [IP: 18.67.93.22 443]
  Hashes of expected file:
   - Filesize:60177 [weak]
   - SHA256:a2afda73be1111aa3f414543890bc6ae8773381fcac8f06021375a67f39b1057
   - SHA1:0f5597236bb05bd521d083f3c5e5e961d05a22f0 [weak]
   - MD5Sum:953b236496acaed0bb7a82a9919f3a03 [weak]
  Release file created at: Thu, 21 Jul 2022 23:29:34 +0000
Hit:8 https://packagecloud.io/sensu/stable/ubuntu bionic InRelease
Fetched 11.2 kB in 3s (3209 B/s)
Reading package lists... Done
E: Failed to fetch https://apt.releases.hashicorp.com/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (59610 != 60177). Mirror sync in progress? [IP: 18.67.93.22 443]
   Hashes of expected file:
    - Filesize:60177 [weak]
    - SHA256:a2afda73be1111aa3f414543890bc6ae8773381fcac8f06021375a67f39b1057
    - SHA1:0f5597236bb05bd521d083f3c5e5e961d05a22f0 [weak]
    - MD5Sum:953b236496acaed0bb7a82a9919f3a03 [weak]
   Release file created at: Thu, 21 Jul 2022 23:29:34 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Operating system and Environment details

  Operating System: Ubuntu 18.04.6 LTS
            Kernel: Linux 4.15.0-189-generic
      Architecture: x86-64

**Comment by vandrham** [comment]
I am facing the same issue:

```
Get:8 http://ppa.launchpad.net/ansible/ansible/ubuntu focal/main amd64 Packages [1132 B]
Fetched 30.3 kB in 1s (30.9 kB/s)
Reading package lists...
E: Failed to fetch https://apt.releases.hashicorp.com/dists/bullseye/main/binary-amd64/Packages.bz2  File has unexpected size (59610 != 59791). Mirror sync in progress? [IP: 18.66.171.113 443]
   Hashes of expected file:
    - Filesize:59791 [weak]
    - SHA256:d4694c4b7214c34aaf2160e2ab3654eb214ed8dbdfb9dd1232e42d689515b6e0
    - SHA1:dcd12b77b5eec4e64a0e76bc4be0525f380d97ca [weak]
    - MD5Sum:cda80130e9a53f896b8042a617cb7eb4 [weak]
   Release file created at: Thu, 21 Jul 2022 20:31:55 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by bognerf** [comment]
Same issue here (Ubuntu 18.04)

```
Fehl:9 https://apt.releases.hashicorp.com bionic/main amd64 Packages
  Datei hat eine unerwartete Größe (59610 != 60177). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 18.64.79.88 443]
  Hashes of expected file:
   - Filesize:60177 [weak]
   - SHA256:a2afda73be1111aa3f414543890bc6ae8773381fcac8f06021375a67f39b1057
   - SHA1:0f5597236bb05bd521d083f3c5e5e961d05a22f0 [weak]
   - MD5Sum:953b236496acaed0bb7a82a9919f3a03 [weak]
  Release file created at: Thu, 21 Jul 2022 23:29:34 +0000
Es wurden 11,2 kB in 1 s geholt (9.137 B/s).             
Paketlisten werden gelesen... Fertig
E: Fehlschlag beim Holen von https://apt.releases.hashicorp.com/dists/bionic/main/binary-amd64/Packages.bz2 Datei hat eine unerwartete Größe (59610 != 60177). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 18.64.79.88 443]
   Hashes of expected file:
    - Filesize:60177 [weak]
    - SHA256:a2afda73be1111aa3f414543890bc6ae8773381fcac8f06021375a67f39b1057
    - SHA1:0f5597236bb05bd521d083f3c5e5e961d05a22f0 [weak]
    - MD5Sum:953b236496acaed0bb7a82a9919f3a03 [weak]
   Release file created at: Thu, 21 Jul 2022 23:29:34 +0000

```

**Comment by HSerg** [comment]
Same issue (Ubuntu 22.04 LTS “Jammy Jellyfish”)
```
E: Failed to fetch https://apt.releases.hashicorp.com/dists/jammy/main/binary-amd64/Packages.gz  File has unexpected size (73402 != 73182). Mirror sync in progress? [IP: 18.67.65.48 443]
   Hashes of expected file:
    - Filesize:73182 [weak]
    - SHA256:7dbcbbbcc1ba7149977ccb613f3827a34d8cdcfea61bb1001d5b3ad99f12c6be
    - SHA1:686e1ca422515e3a4f321b1b7626a917512982a2 [weak]
    - MD5Sum:4dd974f67d4ae1b1275ef0d0766f4e99 [weak]
   Release file created at: Thu, 21 Jul 2022 20:31:58 +0000
   ```

**Comment by mherrmann** [comment]
Another one on Debian bullseye

```
E: Failed to fetch https://apt.releases.hashicorp.com/dists/bullseye/main/binary-amd64/Packages.bz2  File has unexpected size (60177 != 59791). Mirror sync in progress? [IP: 99.86.240.40 443]
   Hashes of expected file:
    - Filesize:59791 [weak]
    - SHA256:d4694c4b7214c34aaf2160e2ab3654eb214ed8dbdfb9dd1232e42d689515b6e0
    - SHA1:dcd12b77b5eec4e64a0e76bc4be0525f380d97ca [weak]
    - MD5Sum:cda80130e9a53f896b8042a617cb7eb4 [weak]
   Release file created at: Thu, 21 Jul 2022 20:31:55 +0000
```

**Comment by fitzy101** [comment]
For what it’s worth, we no longer use this repository and mirror the required binaries on s3 to avoid this kind of problem in production deployments.

**Comment by vandrham** [comment]
@fitzy101 then why is this the recommended way to install packer on linux?
https://learn.hashicorp.com/tutorials/packer/get-started-install-cli?in=packer/docker-get-started

**Comment by sathieu** [comment]
@vandrham This is a temporary problem and would probably be fixed soon.

See older reference, like here: https://discuss.hashicorp.com/t/corrupt-package-files-for-buster-in-apt-repository/34716/6

**Comment by Amier3** [comment]
Hey ya'll 

This should be fixed now. Please let me know if you're still experiencing this issue

**Comment by jeenx** [comment]
Not sure if related by I get a 404 on this
```
Err https://apt.releases.hashicorp.com trusty/main amd64 Packages
  HttpError404
W: Failed to fetch https://apt.releases.hashicorp.com/dists/trusty/main/binary-amd64/Packages  HttpError404
```

**Comment by larry-s** [comment]
@Amier3 It is working now thank you.

**Comment by twistedpair** [comment]
Hey, @Amier3 , seeing this same issue today in the Hashicorp repos

```
Get:11 https://apt.releases.hashicorp.com jammy/main i386 Packages [31.3 kB]       
Err:11 https://apt.releases.hashicorp.com jammy/main i386 Packages                 
  File has unexpected size (31295 != 31290). Mirror sync in progress? [IP: 18.161.21.14 443]
  Hashes of expected file:
   - Filesize:31290 [weak]
   - SHA256:a1aba716abdbf9f2e3bc13d25734ff9fcc58a399698795ebc98f7cec76146d2e
   - SHA1:20e1b9792e678e5223d1387e4e5effaf5a4ca24f [weak]
   - MD5Sum:647502cff7f79ac8a4641b6519696b30 [weak]
  Release file created at: Wed, 03 May 2023 21:28:51 +0000
```

**Comment by simonhyll** [comment]
I'm seeing this issue as well
`Failed to fetch https://apt.releases.hashicorp.com/dists/jammy/main/binary-amd64/Packages.gz  File has unexpected size (102889 != 102738). Mirror sync in progress? [IP: 52.222.214.123 443]`

**Comment by draft13** [comment]
Just appeared to me: 

```
Get:3 https://apt.releases.hashicorp.com jammy/main i386 Packages [31.3 kB]                                                                                                                                               
Err:3 https://apt.releases.hashicorp.com jammy/main i386 Packages                                                                                              
  File has unexpected size (31295 != 31290). Mirror sync in progress? [IP: 18.64.174.53 443]
  Hashes of expected file:
   - Filesize:31290 [weak]
   - SHA256:a1aba716abdbf9f2e3bc13d25734ff9fcc58a399698795ebc98f7cec76146d2e
   - SHA1:20e1b9792e678e5223d1387e4e5effaf5a4ca24f [weak]
   - MD5Sum:647502cff7f79ac8a4641b6519696b30 [weak]
  Release file created at: Wed, 03 May 2023 21:28:51 +0000

```

**Comment by nabsource** [comment]
seeing the same

```
E: Failed to fetch https://apt.releases.hashicorp.com/dists/jammy/main/binary-amd64/Packages.gz  File has unexpected size (102889 != 102738). Mirror sync in progress? 
Hashes of expected file:
 - Filesize:102738 [weak]
 - SHA256:fa1fde8ae1f30ae1d81e20c2d54e2cf70afd9263be47b880bf40fe83daa002ec
 - SHA1:c39acfab9043117be7397658f5e87c1b8115af5b [weak]
 - MD5Sum:74ce22f314f12cc869dcdd23898c9357 [weak]
Release file created at: Wed, 03 May 2023 21:28:51 +0000
```

**Comment by dylan2intel** [comment]
The same issue reproduced.
`12:06:19  #9 3.694 Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [25.6 kB]
12:06:19  #9 3.725 Fetched 27.1 MB in 3s (8617 kB/s)
12:06:19  #9 3.725 Reading package lists...
12:06:19  #9 4.417 E: Failed to fetch https://apt.releases.hashicorp.com/dists/jammy/main/binary-amd64/Packages.gz  File has unexpected size (102889 != 102738). Mirror sync in progress? [IP: 10.7.211.16 912]
12:06:19  #9 4.417    Hashes of expected file:
12:06:19  #9 4.417     - Filesize:102738 [weak]
12:06:19  #9 4.417     - SHA256:fa1fde8ae1f30ae1d81e20c2d54e2cf70afd9263be47b880bf40fe83daa002ec
12:06:19  #9 4.417     - SHA1:c39acfab9043117be7397658f5e87c1b8115af5b [weak]
12:06:19  #9 4.417     - MD5Sum:74ce22f314f12cc869dcdd23898c9357 [weak]
12:06:19  #9 4.417    Release file created at: Wed, 03 May 2023 21:28:51 +0000
12:06:19  #9 4.417 E: Some index files failed to download. They have been ignored, or old ones used instead.
12:06:19  #9 ERROR: executor failed running [/bin/sh -c curl https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg &&      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com/ $(. /etc/os-release;echo $VERSION_CODENAME) main" > /etc/apt/sources.list.d/hashicorp.list &&      apt-get update && apt-get install --fix-missing --fix-broken -y terraform packer &&      rm -f /etc/apt/sources.list.d/hashicorp.list &&      apt-get clean &&      rm -rf /var/lib/apt/lists/*]: exit code: 100
12:06:19  ------
12:06:19   > [stage-3  4/16] RUN  curl https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg &&      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com/ $(. /etc/os-release;echo $VERSION_CODENAME) main" > /etc/apt/sources.list.d/hashicorp.list &&      apt-get update && apt-get install --fix-missing --fix-broken -y terraform packer &&      rm -f /etc/apt/sources.list.d/hashicorp.list &&      apt-get clean &&      rm -rf /var/lib/apt/lists/*:
12:06:19  ------
12:06:19  executor failed running [/bin/sh -c curl https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg &&      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com/ $(. /etc/os-release;echo $VERSION_CODENAME) main" > /etc/apt/sources.list.d/hashicorp.list &&      apt-get update && apt-get install --fix-missing --fix-broken -y terraform packer &&      rm -f /etc/apt/sources.list.d/hashicorp.list &&      apt-get clean &&      rm -rf /var/lib/apt/lists/*]: exit code: 100
12:06:19  make[2]: *** [script/terraform/CMakeFiles/build_terraform.dir/build.make:57: script/terraform/CMakeFiles/build_terraform] Error 1
12:06:19  make[1]: *** [CMakeFiles/Makefile2:6858: script/terraform/CMakeFiles/build_terraform.dir/all] Error 2
12:06:19  make: *** [Makefile:95: all] Error 2`

**Comment by draft13** [comment]
It has been resolved for me now.

**Comment by dylan2intel** [comment]
> It has been resolved for me now.

How did you workaround it? thx.

**Comment by draft13** [comment]
> > It has been resolved for me now.
> 
> How did you workaround it? thx.

No change on my part; just stopped receiving the error. The only thing I did was wait nearly 24 hours.

**Comment by dylan2intel** [comment]
> > > It has been resolved for me now.
> > 
> > 
> > How did you workaround it? thx.
> 
> No change on my part; just stopped receiving the error. The only thing I did was wait nearly 24 hours.

What a patient guy, anyway at least it works for you 👍
I doubt if it is cache issue especially behind an internal proxy?

**Comment by david-yu** [comment]
Hi there, our GPG keys for apt and RPM were revoked and regenerated. Please see https://support.hashicorp.com/hc/en-us/articles/13177506317203-Security-Alert-HashiCorp-Response-to-CircleCI for more details. I hope this helps.
