### ISSUE TITLE
Consul Service Address Resolution with `advertise_addr_wan`

### ISSUE THREAD

**Issue by evan2645** [hashicorp/consul#1386]
I am using consul between three datacenters. All hosts have 1:1 NAT to the internet. It is desirable to use private addresses when hosts are in the same datacenter, and WAN addresses when the host is in a remote datacenter. Consul provides a knob `advertise_addr_wan`, and the documentation suggests that it serves this purpose:
```
However, in some cases all members of all datacenters cannot be on the same
physical or virtual network, especially on hybrid setups mixing cloud and private
datacenters. This flag enables server nodes gossiping through the public network
for the WAN while using private VLANs for gossiping to each other and their client
agents.
```
We have correctly set the `advertise_addr_wan` on all hosts, yet the service resolution stuff doesn't seem to pay attention to it... i.e. querying for ZK hosts in a different datacenter returns private addresses instead of the WAN address we've configured. Am I missing something here? Is this only applicable to server nodes which are gossiping with the other DC's? We set this value on all clients... not having this automatic translation in Consul is causing us a good deal of pain at the moment

**Comment by highlyunavailable** [comment]
> Is this only applicable to server nodes which are gossiping with the other DC's?

Yep, that's it. That setting only controls the WAN pool advertise address which only servers participate in.

**Comment by evan2645** [comment]
Hmm that's unfortunate. How does everyone here feel about this? Would it be
disruptive to prefer `advertise_addr_wan` as a service address when queried
from an external DC? What if it was configurable? This is a big need for
me... Willing to make some contribution

**Comment by evan2645** [comment]
Clarification: service address when not explicitly defined
