### ISSUE TITLE
Documentation refers to an S3 bucket that's unavailable

### ISSUE THREAD

**Issue by ruffin** [hashicorp/consul#13868]
#### Overview of the Issue

The documentation here refers to an S3 bucket containing enterprise binaries with built-in licenses. That bucket is no longer available, so those references to built-in licenses can be removed, and documentation can instead point to https://releases.hashicorp.com/ .

https://github.com/hashicorp/consul/blob/43b548d4c1bcfe738ac224a8264158c2cc8eb9db/website/content/docs/enterprise/license/overview.mdx#binaries-with-built-in-licenses

**Comment by Amier3** [comment]
Thanks for pointing this out @ruffin!
