### ISSUE TITLE
consul-ui单独运行失败

### ISSUE THREAD

**Issue by jqClub** [hashicorp/consul#13876]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

### Overview of the Issue

consul-ui单独运行失败

### Reproduction Steps

1.cd ui/packages/consul-ui
2.yarn install
3.yarn start
![image](https://user-images.githubusercontent.com/27038856/180768092-a042dffd-acab-48af-a416-d1cd2a7d6a0d.png)

### Describe the solution you'd like

运行失败

### Consul Version

Consul v1.12.2

### Browser and Operating system details

ember-cli: 3.20.2
node: 14.20.0
os: darwin x64

### Screengrabs / Web Inspector logs

If you think it's worthwhile, include appropriate screengrabs showing the
error/area for improvement. Try to include the URL bar of the browser so we
can see the current URL where the error manifests. Please be careful to
obfuscate any sensitive information either in the URL or in the browser page
itself.

**Comment by Amier3** [comment]
Hey @jqClub 

Are you attempting to access the Consul UI? If you're running a `consul agent -dev` cluster, the UI is enabled automatically and you can access just by going to localhost:8500/ui . If you're running a production cluster, you will have to configure the UI in your agent config. See t[his documentation](https://www.consul.io/docs/agent/config/config-files#ui_config_enabled) for more information 👍

**Comment by jqClub** [comment]
I just want to run the Consul-UI alone In the local，Don't run anything else（我只想在本地单独运行ui界面，而不启动其他）。
This is the document that runs separately：https://github.com/hashicorp/consul/tree/main/ui/packages/consul-ui，这个是单独运行文档
![image](https://user-images.githubusercontent.com/27038856/180892445-fc3f4847-6179-45d2-ae39-1d9e9b7fa1b7.png)

**Comment by Amier3** [comment]
@jqClub 

Oh I see. Thanks for the clarification. I was able to build the UI roughly using the same steps ( had to run `yarn start` instead of `make start`, but it looks like you did that already ) . I think at some point your local git repo got corrupted. Does running `git status` give you that same " Not a git repository " error message?

**Comment by jqClub** [comment]
I found the problem and dealt with it。I should be use git clone，but not Direct download。
