### ISSUE TITLE
please add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/consul#1390]
Perhaps something like

```
Copyright 2013-2015 HashiCorp <hello@hashicorp.com>
```

or

```
Copyright 2013-2015 HashiCorp (http://www.hashicorp.com)
```

Thanks.

**Comment by rbg** [comment]
https://github.com/hashicorp/consul/blob/master/LICENSE

**Comment by onlyjob** [comment]
There is no copyright statement in `LICENSE` or anywhere in the code.
