### ISSUE TITLE
feature request: can describe a service

### ISSUE THREAD

**Issue by davideuler** [hashicorp/consul#1391]
I hope we can add description in a service definition, so that it would be easier for developer to understand what does a service do.

**Comment by ryanuber** [comment]
That seems reasonable, thanks!

**Comment by wendigo** [comment]
Is there contribution guide? I would like to implement this :)

**Comment by slackpad** [comment]
Going to close this out as there hasn't been a ton of interest in this since the issue was created, and it's not on our roadmap to add it. We'd take a PR for it.
