### ISSUE TITLE
Update service tags not having expected effect

### ISSUE THREAD

**Issue by rexm** [hashicorp/consul#1392]
For scenarios where I have a service already-registered, and need to change the tags, I've tried doing a PUT to agent/service/register and catalog/register per the HTTP API, trying to 'overwrite' the existing service ID with the same values, but a different Tags array.

I get a 200 OK back from the HTTP API... and I've modified this issue because at first I thought it was not having any effect at all but it seems like maybe there was just a delay - I now see the tags when I do a GET against the catalog, *but* the Consul UI doesn't reflect the updated tags; and consul-template doesn't seem to react to the change. Am I doing something wrong, or is this behavior normal?

**Comment by slackpad** [comment]
It should work if you use the agent API - there's a brief delay but the agent will sync the changes back up to the servers. If you change the tags in the catalog they will get overwritten when the agent syncs again unless you use the new `enableTagOverride` option that was added in Consul 0.6.0, see https://www.consul.io/docs/agent/services.html. Please re-open this if you are still having trouble!
