### ISSUE TITLE
API behavior change in /v1/health/node/:node

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#1395]
I was testing my Consul.NET API against 0.6.0-rc1 and I noted that there's a behavior change that was causing my tests to fail in `/v1/health/node/:node` _only_ for nodes that don't exist and wanted to find out if it was a new or unexpected behavior.

> 0.5.2

```
$ curl -sD - localhost:8500/v1/health/node/foobar
HTTP/1.1 200 OK
Content-Type: application/json
X-Consul-Index: 11
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Mon, 09 Nov 2015 17:14:07 GMT
Content-Length: 2

[]
```

> 0.6.0rc1

```
$ curl -sD - localhost:8500/v1/health/node/foobar
HTTP/1.1 200 OK
Content-Type: application/json
X-Consul-Index: 11
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Mon, 09 Nov 2015 17:14:26 GMT
Content-Length: 4

null
```

The behavior in 0.5.2 is to return an empty JSON array and in 0.6.0-rc1 it returns a JSON null (not even an empty array).

I couldn't see anything in the [current tests](https://github.com/hashicorp/consul/blob/master/api/catalog_test.go#L239-L247) that would suggest this is correct either - the test checks for `len(0)` and that should fail with null unless there's some ~Magical JSON Unmarshaling~ happening. Either way, this might break other third party APIs that don't use Go's unmarshaling if this is being masked.

**Comment by slackpad** [comment]
Thanks @highlyunavailable - this wasn't intended so I'll get a fix in and look through the other endpoints.

**Comment by highlyunavailable** [comment]
None of the other tests on my end fail, so it might be just this one. Thanks for the quick response, though!

**Comment by slackpad** [comment]
Yeah it's down in the new state store code, we initialized the return slices to `nil` and appended vs. calling `make` on them (even for an empty one) so there are probably other places where this is happening. I think the existing test is definitely marshalling magic because of the way Go treats `nil` slices as empty and allows `append` on them. Should be simple to find and fix, though.

**Comment by slackpad** [comment]
I think a similar issue is the cause of #1406 - in that case a `Checks` member of the returned structure is `null` instead of an empty list.

**Comment by highlyunavailable** [comment]
Confirmed that #1414 fixes this issue. Thanks!

**Comment by slackpad** [comment]
Thanks for checking again!
