### ISSUE TITLE
Cilium Mesh Integration

### ISSUE THREAD

**Issue by yuriy-yarosh** [hashicorp/consul#13973]
#### Feature Description

Cilium already has a sidecar-free [envoy based](https://github.com/cilium/proxy) L7 [service mesh](https://docs.cilium.io/en/v1.12/gettingstarted/servicemesh/l7-traffic-management/), and some basic [istio integration](https://docs.cilium.io/en/v1.12/gettingstarted/istio/) for mTLS as well. Cilium can replace [kube-proxy](https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#kubeproxy-free) for leaner deployments as well.

I'm not a huge fan of istio and Cilium envoy config uses CRD's: [CiliumEnvoyConfig](https://github.com/cilium/cilium/blob/master/pkg/k8s/apis/cilium.io/v2/register.go#L166) and [CiliumClusterwideEnvoyConfig](https://github.com/cilium/cilium/blob/master/pkg/k8s/apis/cilium.io/v2/register.go#L152).

It would be great to enhance the existing Envoy sidecar injection with the respective Cilium Envoy configs and replace consul-connect envoy with the cilium one.

Cilium uses a proxy per node injection model, instead of common sidecars.
It's also possible to deploy with a complete sidecar-free mesh.

[Reference](https://isovalent.com/blog/post/2021-12-08-ebpf-servicemesh/).

Respective sidecar-free mesh is GA from 1.12.0 Cilium release.

#### Use Case(s)

1) Lightweight consul-connect cilium enabled distributions with minimum or no sidecar overhead.
2) Possible sidecar-free deployments just on Cilium

**Comment by david-yu** [comment]
Hi folks, thanks for the feedback. Although Cilium Mesh here is explicitly mentioned in the issue, a more native integration that does not require Cilium is a preferred approach to achieve what is desired for a lightweight sidecar free deployment. I will go ahead and close in favor of https://github.com/hashicorp/consul/issues/15882 where we will be tracking sidecarless support for Consul Service Mesh.
