### ISSUE TITLE
Lack of KV access logs

### ISSUE THREAD

**Issue by shpoont** [hashicorp/consul#1402]
Currently it is impossible to know who accessed and changed kv values

**Comment by slackpad** [comment]
Related to #414, depending on how things are implemented.

Current workaround is to use something like https://github.com/Cimpress-MCP/git2consul to handle the history and just use Consul for delivery.

**Comment by CVTJNII** [comment]
That's an okay workaround for auditing writes but not for reads.  I currently need to know if anything is reading from a deprecated cluster in preparation of turning it off, so access logs would be super useful.

**Comment by i0rek** [comment]
Auditing is something that we are working on for Consul Enterprise.
