### ISSUE TITLE
Service-bound checks

### ISSUE THREAD

**Issue by akmalabbasov** [hashicorp/consul#1403]
Hi, 
In case the service consist of several nodes(hbase), what's the behaviour of the service-bound checks. Will each of node run check, or will it run just once.
Thank you

**Comment by highlyunavailable** [comment]
Each check is run locally by the consul agent on that node. Checks are scoped to run per service instance - that is, each hbase server is a single instance of the hbase service. So to answer your question, each node will run the check.
