### ISSUE TITLE
Add "Consul vs. Aurora" details page

### ISSUE THREAD

**Issue by breerly** [hashicorp/consul#1405]
Aurora offers many similar features to Consul - a quick reference for those comparing the overlap would be greatly helpful.

Thoughts?

**Comment by highlyunavailable** [comment]
Can you link to Aurora? If we're talking about https://aurora.apache.org/ it doesn't seem to do much the same thing at all.

**Comment by breerly** [comment]
That's the one.

Is Service Discovery not offered? I thought that it was.

**Comment by highlyunavailable** [comment]
Service discovery is certainly a service that Consul offers, so yeah, you're right that service discovery is in the picture, but it uses Zookeeper for that:

> Service Registration
> 
> Aurora announces services to Apache ZooKeeper for discovery by clients like Finagle.

Zookeeper is also already covered by the "vs" documentation, this time in Consul itself: https://www.consul.io/intro/vs/zookeeper.html

**Comment by breerly** [comment]
That's probably a good point. Perhaps this issue will come up when people search for this :)
