### ISSUE TITLE
key names vs. url-encoding

### ISSUE THREAD

**Issue by Nirkus** [hashicorp/consul#1409]
Hey,

I had the rather unusual idea to encode URL route configuration in the consul key-value store.
So, the mapping of key to value would be route to service name, something like:
`"/v9/"` => `"other-backend"`

As kv store key names are just URL path suffixes, I tried to URL-encode my slashes.

1)
A key name of `"%2Fv9%2F"` seems to be URL-unescaped by consul and result in the key name `"/v9/"`, which created a "directory" containing a single key using the uploaded value as its name.

While I can understand that `"%2F"` is un-escaped by consul before creating the key, using the uploaded value as the name of an empty key is somewhat strange.

2)
A key name of `"%252Fv9%252F"` actually results in a key named `"%2Fv9%2F"` being created with the uploaded value as its value. Unfortunately, the API returns that key name without URL-escaping it first:

```
$ curl -s http://testhost.example.com:8500/v1/kv/service/someservice/routes/?recurse | json_pp
[
   {
      "Key" : "service/someservice/routes/%2Fv9%2F",
      "CreateIndex" : 297596,
      "Flags" : 0,
      "ModifyIndex" : 297596,
      "Value" : "dGVzdHZhbHVl",
      "LockIndex" : 0
   }
]
```

`GET`ing the key returned above reults in a `301`, since consul un-escapes `"%2F"` into `"/"` before looking up the key.

```
curl -i -s http://testhost.example.com:8500/v1/kv/service/someservice/routes/%2Fv9%2F 
HTTP/1.1 301 Moved Permanently
Location: /v1/kv/service/someservice/routes/v9/
Date: Thu, 12 Nov 2015 17:13:16 GMT
Content-Length: 76
Content-Type: text/html; charset=utf-8

<a href="/v1/kv/service/someservice/routes/v9/">Moved Permanently</a>.
```

The key redirected to does not exist:

```
$ curl -i -s http://testhost.example.com:8500/v1/kv/service/someservice/routes/v9/
HTTP/1.1 404 Not Found
X-Consul-Index: 297596
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Thu, 12 Nov 2015 17:15:25 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

```

Requesting that key using `"service/someservice/routes/%252Fv9%252F"` actually works.

```
$ curl -s http://testhost.example.com:8500/v1/kv/service/someservice/routes/%252Fv9%252F | json_pp 
[
   {
      "Value" : "dGVzdHZhbHVl",
      "ModifyIndex" : 297596,
      "LockIndex" : 0,
      "Flags" : 0,
      "Key" : "service/someservice/routes/%2Fv9%2F",
      "CreateIndex" : 297596
   }
]

```

So, I guess, key components should be URL-escaped before returning them in the API.

**Comment by highlyunavailable** [comment]
Historically there have been a bunch of slash problems with the KV store, mostly by people trying to use RabbitMQ: #1277 #889

https://github.com/hashicorp/consul/issues/889#issuecomment-97302425 is the best explanation of the problem.

**Comment by i0rek** [comment]
This is now working as described in here: https://github.com/hashicorp/consul/issues/1277#issuecomment-588903941.
