### ISSUE TITLE
RFC2782 compliant SRV records on prepared queries

### ISSUE THREAD

**Issue by JqckB** [hashicorp/consul#14143]
#### Feature Description

On Consul services, we have access to SRV record that let us discover the port of the service.
On federated clusters, we are using a lot prepared queries, SRV records are provisioned on `name.query.consul` but not on the RFC2782 compliant format `_service._protocol.query[.datacenter][.consul]`.

Here is an exemple of "quick-win" of not having RFC 2782 SRV records available for prepared queries : https://stackoverflow.com/questions/50951464/haproxy-srv-record-load-balancing-using-consul-dns-prepared-queries

Exemple : 

 - Prepared query from API : 

```
  {
    "ID": "d81dedbe-22bf-7ff9-64a2-25bc47928715",
    "Name": "",
    "Session": "",
    "Token": "",
    "Template": {
      "Type": "name_prefix_match",
      "Regexp": "^(.*)$",
      "RemoveEmptyTags": false
    },
    "Service": {
      "Service": "${match(1)}",
      "Failover": {
        "NearestN": 3,
        "Datacenters": []
      },
      "OnlyPassing": false,
      "IgnoreCheckIDs": [],
      "Near": "",
      "Tags": [],
      "NodeMeta": {},
      "ServiceMeta": {},
      "Connect": false
    },
    "DNS": {
      "TTL": "30s"
    },
    "CreateIndex": 773489,
    "ModifyIndex": 773489
  }
```

 - DNS : 

```
debian@admin:~$ dig +short ran-staging.service.consul SRV
1 1 80 ran-staging-01-dc1.node.staging-dc1.consul.
debian@admin:~$ dig +short ran-staging.query.consul SRV
1 1 80 ran-staging-01-dc1.node.staging-dc1.consul.
debian@admin:~$ dig +short _ran-staging._tcp.service.consul SRV
1 1 80 ran-staging-01-dc1.node.staging-dc1.consul.
debian@admin:~$ dig +short _ran-staging._tcp.query.consul SRV
debian@admin:~$
```

#### Use Case(s)

The prepared queries needs to have this format for some applications (like HAProxy server-template SRV).

**Comment by jkirschner-hashicorp** [comment]
This capability will be included in the Consul 1.15.0 release.
