### ISSUE TITLE
How to turn off  Sidecar "public listener"

### ISSUE THREAD

**Issue by shanliu** [hashicorp/consul#14176]
```
registration := new(consulapi.AgentServiceRegistration)
	registration.Name = "test"
	registration.ID = id
	registration.Port = 0
	registration.Address = ""
	registration.Connect = &consulapi.AgentServiceConnect{
		//Native: true,
		SidecarService: &consulapi.AgentServiceRegistration{
			Name:    "test111",
			Port:    0,//invalid
			Address: "",
			Proxy: &consulapi.AgentServiceConnectProxyConfig{
				Upstreams: []consulapi.Upstream{
					{
						DestinationName: "test1",
						LocalBindPort:   38082,
					},
				},
			},
		},
	}
```

//The registered service does not listen to the port, I hope the sidecar proxy does not start "public listener"
//How to configure Connect.SidecarService ?
//When configuring Connect.SidecarService.Port = 0, it is reset to 2100*

**Comment by huikang** [comment]
@shanliu , if provided port is 0 or -1, consul will auto-assign a port:

https://github.com/hashicorp/consul/blob/d46b515b640e11d3dcc29501754c277d1f7df046/agent/sidecar_service.go#L117-L123

Therefore, I don't think you can have a sidecar proxy without opening a listen port. Could you elaborate a bit on your use cases? Thanks.

**Comment by shanliu** [comment]
> @shanliu , if provided port is 0 or -1, consul will auto-assign a port:
> 
> https://github.com/hashicorp/consul/blob/d46b515b640e11d3dcc29501754c277d1f7df046/agent/sidecar_service.go#L117-L123
> 
> Therefore, I don't think you can have a sidecar proxy without opening a listen port. Could you elaborate a bit on your use cases? Thanks.

Background task Services
not listening on any port...
