### ISSUE TITLE
Add command for viewing/editing raft/peers.json?

### ISSUE THREAD

**Issue by msabramo** [hashicorp/consul#1417]
It occurred to me while writing an internal runbook for Consul that one thing I feel is important to check is the `raft/peers.json` file.

E.g.: I often end up doing:

```
cat /opt/consul/data/raft/peers.json
```

and if I were to find that this file contained `null` in it, then I would probably want to edit it and add back in my nodes.

Should there be some tooling around this, so it's not quite as manual?

**Comment by slackpad** [comment]
This is related to https://github.com/hashicorp/consul/issues/1374.

**Comment by CpuID** [comment]
Big +1

**Comment by CpuID** [comment]
One thing to consider here - should manipulating the raft peers.json be a local operation? or a cluster wide operation? For example, removing a stale node, should such a remove command be executed on all relevant nodes individually?

**Comment by slackpad** [comment]
We've got the most common operation covered now where you can remove a stale peer without messing with peers.json at all. For recovery during an outage where there's no longer a leader, it'll require some more work to support that case, but the `consul operator` command provides a good framework to add more functionality in the future.
