### ISSUE TITLE
Consul 1.13.1 enabled TLS for gRPC with defaults - undocumented

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/consul#14211]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A config that set `tls.defaults` previously did not enable TLS for `gRPC`. In Consul v1.13.1 this now changed and TLS is enabled for gRPC. 

It might be better to document this change in behavior in https://www.consul.io/docs/upgrading/upgrade-specific#grpc-tls because this change affects all Envoy proxies - which then are unable to get their configuration. 

My current workaround is to not use the `tls.defaults` section but to define `tls.https` and `tls.internal_rpc` instead. 

#### Reproduction Steps

1. Use Consul v1.12.x and configure `tls.defaults` and `ports.grpc`
2. Notice that gRPC does not use TLS
3. Upgrade to Consul v1.13.x
4. Notice that gRPC now uses TLS

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 1
	check_ttls = 1
	checks = 5
	services = 5
build:
	prerelease = 
	revision = c6d0f9ec
	version = 1.13.1
	version_metadata = 
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 172.16.17.131:8300
	server = true
raft:
	applied_index = 15586386
	commit_index = 15586386
	fsm_pending = 0
	last_contact = 36.823399ms
	last_log_index = 15586386
	last_log_term = 2367
	last_snapshot_index = 15584110
	last_snapshot_term = 2366
	latest_configuration = [{Suffrage:Voter ID:cab38c65-078e-d527-f390-024cb6bfe86e Address:172.16.17.131:8300} {Suffrage:Voter ID:bdfb08f6-6e49-bd49-dbb9-cd5979f90458 Address:172.16.17.134:8300} {Suffrage:Voter ID:d40c7c52-e298-d4e7-36f0-9bb9d939ee66 Address:172.16.17.128:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2367
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 423
	max_procs = 4
	os = linux
	version = go1.18.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 50
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 52098
	members = 16
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3083
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 1
	check_ttls = 1
	checks = 5
	services = 5
build:
	prerelease = 
	revision = c6d0f9ec
	version = 1.13.1
	version_metadata = 
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 172.16.17.131:8300
	server = true
raft:
	applied_index = 15586386
	commit_index = 15586386
	fsm_pending = 0
	last_contact = 36.823399ms
	last_log_index = 15586386
	last_log_term = 2367
	last_snapshot_index = 15584110
	last_snapshot_term = 2366
	latest_configuration = [{Suffrage:Voter ID:cab38c65-078e-d527-f390-024cb6bfe86e Address:172.16.17.131:8300} {Suffrage:Voter ID:bdfb08f6-6e49-bd49-dbb9-cd5979f90458 Address:172.16.17.134:8300} {Suffrage:Voter ID:d40c7c52-e298-d4e7-36f0-9bb9d939ee66 Address:172.16.17.128:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2367
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 423
	max_procs = 4
	os = linux
	version = go1.18.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 50
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 52098
	members = 16
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3083
	members = 3
	query_queue = 0
	query_time = 1

```

</details>

### Operating system and Environment details

Ubuntu 22.04.1 LTS on amd64

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by ahjohannessen** [comment]
@EtienneBruines I think I am in the same situation as you. I tried to upgrade from 1.12.3 to 1.13.1 and getting logs like this from consul clients:

```shell
Server.Serve failed to complete security handshake from "127.0.0.1:38386": tls: first record does not look like a TLS handshake
```

Could you please show what you have defined for tls.https and tls.internal_rpc for clients and servers?

I have tried to do this on test clients:
```json
    "auto_encrypt": {
        "tls": true
    },
    "tls": {
        "defaults": {
            "ca_file": "/etc/consul/certs/consul-agent-ca.pem",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": true,
            "verify_outgoing": true
        },
        "https": {
            "verify_incoming": false
        },
        "internal_rpc": {
            "verify_incoming": false,
            "verify_server_hostname": true
        }
    }
   // Elided stuff
```
and this on test servers:

```json
    "tls": {
        "defaults": {
            "ca_file": "/etc/consul/certs/consul-agent-ca.pem",
            "cert_file": "/etc/consul/certs/server.pem",
            "key_file": "/etc/consul/certs/server-key.pem",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": true,
            "verify_outgoing": true
        },
        "https": {
            "verify_incoming": false
        },
        "internal_rpc": {
            "verify_incoming": false,
            "verify_server_hostname": true
        }
    },
    "auto_encrypt": {
        "allow_tls": true
    }
   // Elided stuff
```

**Comment by EtienneBruines** [comment]
@ahjohannessen Whatever I had as `defaults`, I renamed to `https` and then copied it once more for `internal_rpc`. In your case, that'd be something like this:

```json
{
  "tls": {
        "https": {
            "ca_file": "/etc/consul/certs/consul-agent-ca.pem",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": false,
            "verify_outgoing": true
        },
       "internal_rpc": {
            "ca_file": "/etc/consul/certs/consul-agent-ca.pem",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": false,
            "verify_outgoing": true,
            "verify_server_hostname": true
        }
    }
}
```

**Comment by ahjohannessen** [comment]
I have this in server:

```json
    "tls": {
        "https": {
            "ca_file": "/etc/consul/certs/consul-agent-ca.pem",
            "cert_file": "/etc/consul/certs/server.pem",
            "key_file": "/etc/consul/certs/server-key.pem",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": false,
            "verify_outgoing": true
        },
        "internal_rpc": {
            "ca_file": "/etc/consul/certs/consul-agent-ca.pem",
            "cert_file": "/etc/consul/certs/server.pem",
            "key_file": "/etc/consul/certs/server-key.pem",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": true,
            "verify_outgoing": true,
            "verify_server_hostname": true
        }
    }
    ...
        "ports": {
        "dns": 8600,
        "grpc": 8502,
        "http": 8500,
        "https": 8501,
        "serf_lan": 8301,
        "serf_wan": 8302,
        "server": 8300
    }
    ...
        "addresses": {
        "dns": "127.0.0.1",
        "grpc": "127.0.0.1",
        "http": "127.0.0.1",
        "https": "192.168.81.100"
    }
```

Servers seem to start up and work, but clients are having issues with envoy. I am using it with Nomad.

Clients:

```json
    "auto_encrypt": {
        "tls": true
    },
    "enable_local_script_checks": false,
    "tls": {
        "https": {
            "ca_file": "/etc/consul/certs/consul-agent-ca.pem",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": false,
            "verify_outgoing": true
        },
        "internal_rpc": {
            "ca_file": "/etc/consul/certs/consul-agent-ca.pem",
            "tls_min_version": "TLSv1_2",
            "verify_incoming": false,
            "verify_outgoing": true,
            "verify_server_hostname": true
        }
    }
   ...
       "ports": {
        "dns": 8600,
        "grpc": 8502,
        "http": 8500,
        "https": -1,
        "serf_lan": 8301,
        "serf_wan": 8302,
        "server": 8300
    }
    ...
        "addresses": {
        "dns": "127.0.0.1",
        "grpc": "127.0.0.1",
        "http": "127.0.0.1",
        "https": "127.0.0.1"
    }
```
Envoy is reporting this:

```shell
DeltaAggregatedResources gRPC config stream closed since 45s ago: 14, upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

This is a mess.

**Comment by ahjohannessen** [comment]
When using Nomad and Consul Connect using my setup envoy integration seems to fail. I tried to migrate from 1.12.3 that is not using tls stanza to 1.13.1 using the tls stanza. Nomad is set to communicate with consul on 127.0.0.1:8500, however something breaks as the consul logs show TLS issues.

**Comment by pruiz** [comment]
It looks like having autoencrypt.tls=true enables TLS on gRPC, even when ports.https is not enabled.

This is a behavior change on v1.13 which breaks backwards compatibility. :(

**Comment by ahjohannessen** [comment]
@pruiz Right on, that seems to be the issue.

**Comment by EtienneBruines** [comment]
> It looks like having autoencrypt.tls=true enables TLS on gRPC, even when ports.https is not enabled.
> 
> This is a behavior change on v1.13 which breaks backwards compatibility. :(

Even without `auto_encrypt.tls` we experience issues - so not sure if that one is related.

**Comment by jkirschner-hashicorp** [comment]
Thank you all for flagging this and sharing agent configuration snippets that helped the Consul team investigate this.

Our understanding is that there are two distinct, but related, issues reported by different posters here. Both issues are related to changes to TLS for gRPC configuration in Consul 1.13. We've [documented both in the 1.13 upgrade docs](https://www.consul.io/docs/upgrading/upgrade-specific#service-mesh-compatibility). I'll look into adding a notice to the changelog as well.

### Problem 1: Service mesh deployments using auto-encrypt or auto-config

The first issue occurs if using auto-encrypt or auto-config, which we now [call out in our 1.13 upgrade documentation](https://www.consul.io/docs/upgrading/upgrade-specific#service-mesh-deployments-using-auto-encrypt-or-auto-config). We are working on a fix (special thanks to @pruiz for the jump-start on that) for an upcoming 1.13 patch release. In the meantime, we're not aware of a workaround This issue is separately captured in more detail on #14253 and at the aforementioned docs link.

### Problem 2: Service mesh deployments without the HTTPS port enabled on Consul agents

The second issue occurs if the HTTPS port was not enabled on pre-1.13 Consul agents. This was an issue of documentation clarity. We just [updated the 1.13 upgrade documentation to clarify who is affected and what to do about it](https://www.consul.io/docs/upgrading/upgrade-specific#grpc-tls). This can be avoided by [making the newly documented agent config updates](https://www.consul.io/docs/upgrading/upgrade-specific#modify-the-consul-agent-s-tls-configuration).

@EtienneBruines encountered this problem, rather than problem 1, which is why their configuration change (using `tls.https` and `tls.internal_rpc` instead of `tls.defaults`) worked.

**Comment by EtienneBruines** [comment]
Thanks for the write-up @jkirschner-hashicorp :smile: 

Since the docs were updated regarding this issue, I think this issue can now be closed / marked as completed.

**Comment by jkirschner-hashicorp** [comment]
We've now updated the changelog to include this info (and link to the relevant 1.13 upgrade docs for more info). Refer to: https://github.com/hashicorp/consul/pull/14279.

We wanted to finish that before closing out this GH issue. Thanks everyone!
