### ISSUE TITLE
Consul Lock does not work as expected with the datacenter option

### ISSUE THREAD

**Issue by Deeksha282528** [hashicorp/consul#14212]
Using -datacenter option in the consul lock to specify the datacenter throws an error "Lock acquisition failed: failed to create session: Unexpected response code: 500 (rpc error making call: rpc error making call: apply failed: Missing node registration)"

Reproduction Steps

Steps to reproduce this issue, eg:
1. consul lock test1 echo test - works totally fine. 
Output - test
2. consul lock -datacenter=xyz test2 echo test - Does not work 
Output - "Lock acquisition failed: failed to create session: Unexpected response code: 500 (rpc error making call: rpc error making call: apply failed: Missing node registration)"

**Comment by huikang** [comment]
@Deeksha282528 , I tested with the latest consul version, and it works fine

```
consul lock -datacenter dc2 test2 echo test 
test

consul version
Consul v1.14.0-dev
Revision 92bcdb9a9+CHANGES
```

What version of consul did you test with?

**Comment by Deeksha282528** [comment]
@huikang I have tested with 
`Consul v1.12.3`

**Comment by Deeksha282528** [comment]
We have tested the  `consul lock -datacenter xyz test2 echo test ` command with the version 
`Consul v1.14.0-dev
Revision 9675faeab`

The similar issue for your reference [https://github.com/hashicorp/consul/issues/4886](url)

Please note that the command works fine when the datacenter specified is same as the datacenter that you are testing in. 
If the testing datacenter and the specified datacenter is different then we get an error 

`Lock acquisition failed: failed to create session: Unexpected response code: 500 (rpc error making call: rpc error making call: apply failed: Missing node registration)`

**Comment by Deeksha282528** [comment]
Hi, Is there any update on this?

**Comment by huikang** [comment]
I don't have any issue in running the same command across datacneters

two datacenters are federated

```
consul members  -wan                          
Node          Address              Status  Type    Build      Protocol  DC   Partition  Segment
server-1.dc1  192.168.1.165:8302   alive   server  1.14.0dev  2         dc1  default    <all>
server-1.dc2  192.168.1.166:8302   alive   server  1.14.0dev  2         dc2  default    <all>
```

```
 consul lock -datacenter dc2 test2 echo test 
test
```

One thing you may want to try is to create some kv pair in one dc and then check if you can read the kv pair from the other dc.

**Comment by Deeksha282528** [comment]
I have tried with KV pair and it works. But the lock is not.

**Comment by huikang** [comment]
@Deeksha282528 , could you provide the steps to reproduce? Thanks.

**Comment by Deeksha282528** [comment]
@huikang Below are the steps to reproduce
we have two dc namely zbk and ybk
Case 1 : Create a Key value pair in the zbk region and access it from ybk region using -datacenter option. This works perfectly fine
1. Create a key value pair in zbk
2. access the kv from ybk
`consul kv get -datacenter zbk testreboot`

Case 2: Create a Consul lock with -datacenter option does not work
1. Create a consul lock in zbk 
`consul lock testacq echo test`
2. Query/access the consul lock in ybk
`consul lock -datacenter zbk testacq  echo test
Lock acquisition failed: failed to create session: Unexpected response code: 500 (rpc error making call: rpc error making call: apply failed: Missing node registration)`

I have attached screenshots for your reference.

<img width="1432" alt="Screenshot 2022-11-15 at 11 37 13" src="https://user-images.githubusercontent.com/111052518/201899520-46738a93-2d1a-4163-879b-2735ec00df5b.png">

**Comment by huikang** [comment]
@Deeksha282528 , I can reproduce the error and will look into it. Thanks for reporting.
