### ISSUE TITLE
consul doesnt support v1/catalog/datacenter endpoint if using nginx proxy

### ISSUE THREAD

**Issue by JeevanAleti** [hashicorp/consul#14243]
When upgrading consul to 1.12.3 using nginx proxy method, the UI doesnt reload and shows 404 error for v1/catalog/datacenters endpoint

### Reproduction Steps

Steps to reproduce this issue/view the area for improvement, eg:

1. use official consul image v1.12.3 or 1.8.0
2. setup consul using nginx load balamcer
              
         upstream consul {
                  zone consul 2m;
                 server consul:8500 resolve;
            }
              
           location = /consul {       
              port_in_redirect off;
              rewrite /.* /ui redirect;
           }	
	
            location /consul/ {	       
	            port_in_redirect off;
	            rewrite /.* /ui redirect;
            }		
          location ~ ^/consul/.* {
          #auth_basic           "Administrator Area";
          #auth_basic_user_file conf/.htpasswd;
			
			# This will change "Location" and "Refresh" header fields
			# in the proxied server response
			proxy_redirect / /consul;
			# apply substitution in javascript files also
			sub_filter_types application/x-javascript;
			sub_filter_types text/html;	                
	
			sub_filter '"/v1/' '"/consul/v1/*';
			sub_filter_once off;
		
			rewrite ^/consul/(.*) /$1 break;
			proxy_pass http://consul;
		}
		location /ui {       
				include conf/proxy-inc.conf;
                proxy_pass          http://consul/ui;
        }`

### Consul Version 1.12.3 or 1.8.0

![image](https://user-images.githubusercontent.com/33988954/185241268-43a5f1e2-1aca-41e6-9bf0-8bde5b51f266.png)

**Comment by blake** [comment]
Hi @JeevanAleti,

Instead of using `sub_filter` to rewrite `/v1` to `/consul/v1`, you might want to consider the solution proposed in issue #11627. I believe it will work more reliably.

**Comment by JeevanAleti** [comment]
Thank you Blake, the above solution works perfectly fine. Thanks again.
