### ISSUE TITLE
Provide command to clear queued/running operations/locks

### ISSUE THREAD

**Issue by msabramo** [hashicorp/consul#1427]
I have a Consul cluster with 2.8 million garbage `vault/core/leader` entries (resulting from a bug in some older versions of Vault - https://github.com/hashicorp/vault/issues/679) that hurts Consul KV and UI performance (operations apparently take too long and timeout because of the number of keys that have to be crawled - https://github.com/hashicorp/consul/issues/1407). 

After some discussion, the suggestion came up to try doing a DELETE to `/kv?recurse`. 

This unfortunately never completed and seems to still be running or queued and preventing all other operations from succeeding, making Consul unusable (@wwalker noticed this bad behavior as well in hashicorp/consul#1278). 

Ideally there would be something I could to do to get Consul out of this state and back to a usable state, without having to reinitialize the cluster and lose data. 

Cc: @sudarkoff

**Comment by msabramo** [comment]
I had the idea of doing using the session API and it looked promising, but `/session/destroy` failed with `timed out enqueuing operation`:

```
CORP\marca@consul02:/var/log$ http consul02:8500/v1/session/list
HTTP/1.1 200 OK
Content-Length: 211
Content-Type: application/json
Date: Thu, 19 Nov 2015 05:50:28 GMT
X-Consul-Index: 45734953
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0

[
    {
        "Behavior": "release",
        "Checks": [
            "serfHealth"
        ],
        "CreateIndex": 45734568,
        "ID": "ac83629b-f8d1-1765-712b-a0ff61647aeb",
        "LockDelay": 15000000000,
        "Name": "Vault Lock",
        "Node": "consul01.corp.surveymonkey.com",
        "TTL": "15s"
    }
]

CORP\marca@consul02:/var/log$ http PUT consul02:8500/v1/session/destroy/ac83629b-f8d1-1765-712b-a0ff61647aeb
HTTP/1.1 500 Internal Server Error
Content-Length: 29
Content-Type: text/plain; charset=utf-8
Date: Thu, 19 Nov 2015 05:51:05 GMT

timed out enqueuing operation
```

**Comment by slackpad** [comment]
Closing this one as it should be addressed by https://github.com/hashicorp/consul/issues/1418 and https://github.com/hashicorp/consul/issues/1278.
