### ISSUE TITLE
Provide HTTP API that gives count of # of keys

### ISSUE THREAD

**Issue by msabramo** [hashicorp/consul#1428]
I have a Consul cluster with 2.8 million garbage `/vault/core/leader` entries (resulting from a bug in some older versions of Vault - https://github.com/hashicorp/vault/issues/679) that hurts Consul KV and UI performance (operations apparently take too long and timeout because of the number of keys that have to be crawled - https://github.com/hashicorp/consul/issues/1407). 

I had no idea that I had accumulated this huge number of keys until things got slow and started timing out and then @slackpad recognized the symptoms and suggested running `strings state.bin | grep vault/core/leader | wc -l` to count the number of keys.

To prevent this in the future I'd like to set up monitoring (e.g.: Nagios, Zabbix, etc.) that can watch the number of keys. It would be best if the Consul HTTP API had a method that exposed the # of keys.

Looking at https://www.consul.io/docs/agent/http/status.html, I wonder if something like `/v1/status/keys` would make sense. It could look something like this:

```
$ http :8500/v1/status/keys
HTTP/1.1 200 OK
...
Content-Type: application/json
Date: Thu, 19 Nov 2015 15:07:15 GMT
X-Consul-Index: 4018
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0

{
    "count": 2856123
}
```

or maybe it makes more sense to live under the `/kv` API and then maybe it could support returning the count of keys under a certain prefix?

```
$ http :8500/v1/kv/vault/core/leader?count
HTTP/1.1 200 OK
...
Content-Type: application/json
Date: Thu, 19 Nov 2015 15:07:15 GMT
X-Consul-Index: 4018
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0

{
    "count": 2856123
}
```

Cc: @sudarkoff

**Comment by msabramo** [comment]
For folks who need the number of keys without specific support in the API, you can do client-side filtering with [the amazing jq](https://stedolan.github.io/jq/):

```
$ curl -s 'http://consul01.corp.surveymonkey.com:8500/v1/kv/?keys' | jq '. | length'
4
```

Presumably, built-in support in the Consul API would be better because it would be easier, wouldn't require a tool like jq, and hopefully it could be more efficient -- if Consul keeps a count of the number of keys and can quickly respond back with that count rather than doing an expensive operation to enumerate all the keys.

**Comment by msabramo** [comment]
Bump

**Comment by shikloshi** [comment]
+1

**Comment by ChipV223** [comment]
Hi @msabramo !

If the goal is to get a count of Vault secrets that are stored in the Consul backend, we actually have a guide in the Vault Learn portal that goes into detail on how to accomplish with the Consul KV API: https://learn.hashicorp.com/tutorials/vault/inspecting-data-consul

I'll go ahead and close this, but feel free to respond if you have additional questions!
