### ISSUE TITLE
Long values not rendered correctly in UI

### ISSUE THREAD

**Issue by schmunk42** [hashicorp/consul#1429]
See screenshot
<img width="1294" alt="bildschirmfoto 2015-11-19 um 13 45 25" src="https://cloud.githubusercontent.com/assets/649031/11271062/f31ad736-8ec3-11e5-8d16-89b1278c249c.png">

Running latest docker image.

**Comment by slackpad** [comment]
Related to https://github.com/hashicorp/consul/issues/1769, though we should make a pass through everything wrt. long names in the UI.

**Comment by slackpad** [comment]
Actually there are other open issues for wrap-bugs, so I'll close this as a dup of #1769 since that captures KV as well.
