### ISSUE TITLE
Move from aeScaling to rateScaling

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#1431]
While adding network coordinates we created a new `rateScaledInterval()` function which chooses a periodic interval for an event based on a desired aggregate "events/second" rate across the entire cluster. We should consider switching existing `aeScale()` calls over to this, since it lets us provide a more direct expression of the way we want to limit the quantity as the cluster size grows.

**Comment by slackpad** [comment]
This got done for server rebalancing, we will revisit others on a case-by-case basis, but we don't need to keep this open.

**Comment by c4milo** [comment]
@slackpad is this rebalancing process documented somewhere? (sorry for commenting on closed issues)

**Comment by banks** [comment]
@c4milo not in public docs right now but you can get an idea what it does from the code comments: https://github.com/hashicorp/consul/blob/d42c743c84eab122fd7526bca6d7033fd1d179bf/agent/router/manager.go#L293-L304
