### ISSUE TITLE
Allow reap to be configurable

### ISSUE THREAD

**Issue by mindscratch** [hashicorp/consul#1435]
The "reap" occurs every 72 hours, it would be beneficial to allow it to be configurable. For instance, when deploying consul on Mesos with Marathon (and no persistence when an instance restarts), being able to reap sooner would help.

**Comment by DanyC97** [comment]
+1

However this request is been made a looong time ago but unfortunately it didn't get much attention

**Comment by slackpad** [comment]
Closing this as a dup of #544. We will get this in the next release - sorry for the delay!
