### ISSUE TITLE
allow service updates

### ISSUE THREAD

**Issue by StefanPanait** [hashicorp/consul#1438]
Currently there is no way to update a service, only to re-create it via (/v1/agent/service/register).

Allowing services to be updated without having to provide the details that already exist would be useful.

For example: 

Registrator is great for automating registration/deregistration but it does not resolve the problem of knowing when the service inside of the container (docker) is actually ready to serve. The service init code could update the service properties to delcare itself as ready without needing to provide meta data and everything else that registrator scrapes automatically.

**Comment by ryanuber** [comment]
A health check is better suited to this use case. If you bind a health check to the service, its initial status is by default `critical`. This would exclude the service from DNS queries and API calls with passing filters. Once the health check begins passing there is no update required.

**Comment by slackpad** [comment]
Health checks look like a good fit for the use case above. I'll close this out for now. Please re-open if you would like to discuss further.
