### ISSUE TITLE
not able to get consul UI 

### ISSUE THREAD

**Issue by hridyeshpant** [hashicorp/consul#1439]
HTTP error code from Consul: 0 error

This is an error page for the Consul web UI. You may have visited a URL that is loading an unknown resource, so you can try going back to the root.

In Host Machine:  
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                          NAMES
e9b552503f5c        server              "/bin/consul agent -s"   8 minutes ago       Up 8 minutes        0.0.0.0:8300-8302->8300-8302/tcp, 0.0.0.0:8400->8400/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp, 0.0.0.0:8301-8302->8301-8302/udp, 8600/tcp, 0.0.0.0:8600->53/udp   server_test

curl http://localhost:8500/v1/agent/self?pretty
curl: (7) Failed to connect to localhost port 8500: Connection refused

** Inside Docker container 
ps
PID   USER     TIME   COMMAND
    1 root       0:03 /bin/consul agent -server -config-dir=/config -bootstrap -ui-dir=/ui

**Comment by hridyeshpant** [comment]
when trying to debug http://localhost:8500 link usinf develpoer tool, i could see below error message
 >> http://localhost:8500/v1/catalog/datacenters net::ERR_CONNECTION_REFUSED

**Comment by ryanuber** [comment]
@hridyeshpant does the curl succeed from inside of the container? If so this may be a docker networking issue. Otherwise, can you share the configuration?

**Comment by hridyeshpant** [comment]
@ryanuber sorry for the late reply.
i am using docker setup from https://github.com/gliderlabs/docker-consul/blob/master/0.6/consul-server/Dockerfile

**Comment by ryanuber** [comment]
Can you share your full configuration? It might also help to run a `netstat -lnp | grep 8500` and share that result.

**Comment by slackpad** [comment]
Closing this out for now - if you are still having trouble please re-open.

**Comment by saytik** [comment]
hi.

I am having the same issue.
I make a clean run of consul agent -server with docker:

> PN=consul-new
> docker stop $PN && docker rm -f  $PN
> docker run -d \
>    --name $PN \
>    -p 8500:8500 \
>    -v /data/consul_data:/consul/data \
>    consul:1.4.0 agent -server  -bootstrap-expect=1

> # docker logs consul-new
> BootstrapExpect is set to 1; this is the same as Bootstrap mode.
> bootstrap = true: do not enable unless necessary
> ==> Starting Consul agent...
> ==> Consul agent running!
>            Version: 'v1.4.0'
>            Node ID: 'c64ac7ef-4601-a8e3-f21b-bf547716f157'
>          Node name: '06f91a63a4a5'
>         Datacenter: 'dc1' (Segment: '<all>')
>             Server: true (Bootstrap: true)
>        Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
>       Cluster Addr: 172.17.0.5 (LAN: 8301, WAN: 8302)
>            Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false
> 
> ==> Log data will now stream in as it occurs:
> 
>     2018/12/27 10:32:45 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:c64ac7ef-4601-a8e3-f21b-bf547716f157 Address:172.17.0.5:8300}]
>     2018/12/27 10:32:45 [INFO] raft: Node at 172.17.0.5:8300 [Follower] entering Follower state (Leader: "")
>     2018/12/27 10:32:45 [INFO] serf: EventMemberJoin: 06f91a63a4a5.dc1 172.17.0.5
>     2018/12/27 10:32:45 [INFO] serf: EventMemberJoin: 06f91a63a4a5 172.17.0.5
>     2018/12/27 10:32:45 [INFO] consul: Handled member-join event for server "06f91a63a4a5.dc1" in area "wan"
>     2018/12/27 10:32:45 [INFO] consul: Adding LAN server 06f91a63a4a5 (Addr: tcp/172.17.0.5:8300) (DC: dc1)
>     2018/12/27 10:32:45 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
>     2018/12/27 10:32:45 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
>     2018/12/27 10:32:45 [INFO] agent: Started HTTP server on 127.0.0.1:8500 (tcp)
>     2018/12/27 10:32:45 [INFO] agent: started state syncer
>     2018/12/27 10:32:53 [ERR] agent: failed to sync remote state: No cluster leader
>     2018/12/27 10:32:54 [WARN] raft: Heartbeat timeout from "" reached, starting election
>     2018/12/27 10:32:54 [INFO] raft: Node at 172.17.0.5:8300 [Candidate] entering Candidate state in term 2
>     2018/12/27 10:32:54 [INFO] raft: Election won. Tally: 1
>     2018/12/27 10:32:54 [INFO] raft: Node at 172.17.0.5:8300 [Leader] entering Leader state
>     2018/12/27 10:32:54 [INFO] consul: cluster leadership acquired
>     2018/12/27 10:32:54 [INFO] consul: New leader elected: 06f91a63a4a5
>     2018/12/27 10:32:54 [INFO] consul: member '06f91a63a4a5' joined, marking health alive
>     2018/12/27 10:32:57 [INFO] agent: Synced node info

**On UI i see consul error:**

> HTTP error code from Consul: 0 error
> This is an error page for the Consul web UI. You may have visited a URL that is loading an unknown resource, so you can try going back to the root.
 
Also, UI works  from container inside
