### ISSUE TITLE
having trouble removing nodes from consul

### ISSUE THREAD

**Issue by eladapps** [hashicorp/consul#1440]
when removing nodes using the cli command the node is deleted but after a while it comes back to life.
i'm using version 0.4.1 should i upgrade it?

**Comment by ryanuber** [comment]
@eladapps is the node actually still alive? If you are using the force-leave command, and the member is actually still up and running, it will eventually re-join the cluster. If the remote node is still running, shutting it off and making sure it has left should make this permanent. See the docs [here](https://consul.io/docs/commands/force-leave.html) for more detailed info.

**Comment by eladapps** [comment]
The node is long dead. And  machine hasb been turned off. But somehow it
gets back again. And im seeing tons of messages in the consul.log

**Comment by ryanuber** [comment]
Upgrading would certainly eliminate a huge number of bugs, but I'm not sure exactly if this was covered. If you give that a try, set the log_level to DEBUG, and if you still see the issue, a gist of the logs from the servers would be very helpful.

**Comment by slackpad** [comment]
Closing this as we never heard back. Please let us know if you still need help.
