### ISSUE TITLE
Go client README up to date?

### ISSUE THREAD

**Issue by mindscratch** [hashicorp/consul#1442]
The [README](https://github.com/hashicorp/consul/blob/master/api/README.md) for the Go client says it supports the Consul API up to version 0.3. However, it shows support for Sessions which I thought were added in 0.5.

Does the client work with Consul 0.5.2?

**Comment by highlyunavailable** [comment]
Yes it does. That's a doc bug.

**Comment by mindscratch** [comment]
I submitted PR #1443
