### ISSUE TITLE
Go client usage?

### ISSUE THREAD

**Issue by mindscratch** [hashicorp/consul#1444]
What's the recommended method for using the Go client? Should I put a copy of the "api" directory into `$GOPATH/src/github.com/hashicorp/consul/api`? If so, would I then just `import github.com/consul./api` in my code?

**Comment by mindscratch** [comment]
Yes.

**Comment by highlyunavailable** [comment]
Alternatively, just use the usual import mechanism in Go of `import "github.com/hashicorp/consul/api"` and let `go get` it'll grab the latest at the time. You'll probably want to vendor it if you want a specific version of the API though.
