### ISSUE TITLE
How to specify service in consul api to delete the following service

### ISSUE THREAD

**Issue by ThorManager** [hashicorp/consul#14463]
Because there are many duplicate names in my services, but the serivces are different, how can I delete the corresponding services under services?
![image](https://user-images.githubusercontent.com/96821352/188118179-2a7cf242-7cda-4ea6-8024-b286dcb5d15f.png)
If you use api, you directly specify the service name. If you directly specify the service name to delete, the same name in a service will also be deleted.

**Comment by jkirschner-hashicorp** [comment]
Hi @ThorManager,

Service instances are registered with a service name and service ID. All service instances with the same service name are considered to be the same "service".

It sounds like you have many service instances registered with service name `port-server`, even though they really aren't meant to be the same service. To fix this, you can unregister individual service instances using their unique service ID with the Agent API's [service deregister endpoint](https://www.consul.io/api-docs/agent/service#deregister-service) or [corresponding CLI command](https://www.consul.io/commands/services/deregister).

How did you register these services?

It looks like the service ID for the service instance in your screenshot is `10.9.30.22`:

![image](https://user-images.githubusercontent.com/85913323/188333519-4623ffc8-9538-49a9-86a2-b414e023b1a1.png)

**Comment by ThorManager** [comment]
Different services may have the same registered name. For example, port server has 10.9.30.22, and other services also have 10.9.30.22

**Comment by jkirschner-hashicorp** [comment]
Why give different services the same service name?

Consul assumes that services with the same name are the same service.

**Comment by jkirschner-hashicorp** [comment]
Hi @ThorManager,

I haven't heard from you in a few weeks. I'm marking this closed for now, but feel free to re-open / re-comment if you still have questions.

It sounds like you are using the same service name to represent different services. I'm interested in learning why that approach was taken. And if there was documentation you followed that didn't make it clear that Consul assumes different services will have different service names, let us know!
