### ISSUE TITLE
Loading animation does not work on Firefox

### ISSUE THREAD

**Issue by takeda** [hashicorp/consul#1449]
It looks like the loading animation does not display correctly on Firefox (tested on consul 0.5.2), FF displays a broken image in its place.

This appears to be caused by consul sending wrong mimetype:

$ curl -I http://127.0.0.1:8500/ui/static/loading-cylon-purple.svg
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 983
Content-Type: text/plain; charset=utf-8
Last-Modified: Fri, 13 Nov 2015 21:56:09 GMT
Date: Tue, 24 Nov 2015 21:55:54 GMT

The mimetype that should be used for SVG is image/svg+xml

**Comment by ryanuber** [comment]
Thanks for the report!

**Comment by takeda** [comment]
Looks like this was already fixed in 0.6.0:

$ curl -I http://127.0.0.1:8500/ui/static/loading-cylon-purple.svg
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 983
Content-Type: image/svg+xml
Last-Modified: Thu, 17 Dec 2015 23:06:19 GMT
Date: Fri, 18 Dec 2015 16:57:46 GMT
