### ISSUE TITLE
Enable ACL permission denied

### ISSUE THREAD

**Issue by GITHUBTOXZ** [hashicorp/consul#14494]
Hello, in a cluster, there are three clusters of one client. When you see the output log of consult, you will see that the access is denied.
Consult version: 1.10.3
![image](https://user-images.githubusercontent.com/40156185/188608191-d2911d00-e424-479c-8d9a-98af6f8a6c71.png)

consul_client_1 | 2022-09-06T10:03:27.437Z [ERROR] agent.client: RPC failed to server: method=Catalog.Register server=172.21.0.1:8300 error="rpc error making call: Permission denied"

**Comment by jkirschner-hashicorp** [comment]
Hi @GITHUBTOXZ,

Can you share your server agent configuration (with any sensitive details scrubbed)?

I suspect you have ACLs enabled with the default policy set to `deny`. When the Consul client agent reaches out to the server to update its network coordinates, the client isn't presenting an ACL token that allows the update to succeed on the server. The Consul client needs to have an "agent" token specified. Refer to the [ACL tutorial](https://learn.hashicorp.com/tutorials/consul/access-control-setup-production#apply-individual-tokens-to-agents) for more info.

Newer versions of Consul (1.12+) should provide a more descriptive error than just "Permission denied", so ACL issues like this should be easier to troubleshoot once you upgrade from 1.10.3.

**Comment by GITHUBTOXZ** [comment]
Upgrade the consult version to 1.13.1"
![image](https://user-images.githubusercontent.com/40156185/188776746-199ff0a0-55cb-45f6-b113-1c3830a27c1b.png)

I think the permissions are not enough. The super administrator policy is given, but there are still new problems:
![image](https://user-images.githubusercontent.com/40156185/188777133-78f3a638-f614-445e-ba6c-438efaf73402.png)

**Comment by jkirschner-hashicorp** [comment]
Hi @GITHUBTOXZ,

Can you share your Consul server and client configurations (with any sensitive information redacted)? And which tutorial and/or documentation are you using to try to set this up? This information would help me provide better guidance.

I see two separate error messages in your screenshots.

The error message `Permission denied: token with AccessorID '00....002' lacks permission 'node:write' on 'consul_client_1'` means that client agent `consul_client_1` doesn't have an ACL token with sufficient permissions to perform necessary internal operations against the Consul API. It actually doesn't have an ACL token at all: AccessorID `00...002` is the "anonymous" token that's used when no token is explicitly provided, and (by default) has no permissions. Try setting [`acl.tokens.agent`](https://www.consul.io/docs/agent/config/config-files#acl_tokens_agent) in the config for `consul_client_1` with an ACL token that has `node:write` privileges for `consul_client_1`.

The error message `node name consul_client_1 is reserved by node a5...ab with name consul_client_1 (172.21.0.4)` suggests that multiple Consul client agents have been started with the name `consul_client_1`. Each Consul client agent in the datacenter must have a unique name.

**Comment by GITHUBTOXZ** [comment]
Hi @jkirschner-hashicorp
Thank you for your answer. The default anonymous does not give permission. After I set the permission, no error appears
