### ISSUE TITLE
Shorter DNS Resolve Path  xx.service.consul -> xx.consul

### ISSUE THREAD

**Issue by AlessandroEmm** [hashicorp/consul#1454]
Hey there 

Is it possible to get rid of the service subdomain? In my setup i don't have no need for it and I'd like to switch over from a etcd/skydns based setup where this was the default. :-)

Thanks!
Alessandro

**Comment by armon** [comment]
@AlessandroEmm We use it to disambiguate between a service, node, or prepared query lookup. Otherwise the query is ambiguous as it could be any of those three, and we prefer explicit and non-ambiguous behavior.

**Comment by AlessandroEmm** [comment]
I see your point but I'd like to expose services not only "internally" like between the containers/nodes but also externally, where this would just clutter up the URL.
Is there a possibility to configure a different domain structure just for the services?

**Comment by armon** [comment]
@AlessandroEmm Unfortunately no. Consul is not really intended to serve public DNS requests, but you could probably hook something up with BIND to customize the DNS names.

**Comment by AlessandroEmm** [comment]
What if i'd create PR to allow for a separate DNS Server that hosts all services directly with the domain - would there be a chance for a merger?
