### ISSUE TITLE
leader election fails

### ISSUE THREAD

**Issue by psihodelik** [hashicorp/consul#1455]
I manged to reproduce steps to get cluster to fail to elect leader.
Thing is that it looks to me that this is not suppose to happen.

Setup I have : 
-3 server nodes and 2 client nodes
-server nodes bootstrapped with expect-bootstrap=3
-data volume persisted on server 
-sever and client nodes part of ASG on AWS with max number 1 so that
it always brings new server or client machine in case of termination (in which case it would get
get another IP and data volume).

Reproducing inconsistent state steps:
1. kill one of server machines
--->it will show failed state in consul gui
--->new machine will come up and eventually be registered as new server
--->gui will show 3 server nodes in working state, 1 in failed state and 2 client nodes
2.now kill another of server nodes
--->new machine will come up but cluster will not be able to elect leader
--->not sure now but it seems that without bringing new machine up cluster is already down

After inspecting peers.json I could see all good machines there and failed machines as well.

since quorum for 3 server cluster is 2 nodes, having 2 working nodes and 2 failed 
in peers.json should not fail the cluster but it seems to be doing so.

Steps to recover cluster are:
1. edit peers.json on all machines and remove failed nodes
2. restart all servers and clients

What I think is main issue is that quorum of 2 nodes for 3 server cluster
is somehow lost if peers.json have more then 1 failed node included in list together with 2 working nodes.

Also I was wondering if there is way to reduce 72 hours for failed nodes to some other value.
For setup I have failed nodes will come back in some minutes (in case of reboot) or will never come back.
Ability to  to set a value for removing failed nodes to something as low as 10 minutes
would make above setup more firm.

**Comment by highlyunavailable** [comment]
There's a fundamental misunderstanding what "quorum" means here, I think. This is completely normal, and what you're doing is creating a quorum of four machines (eventually) and killing two of them. A node in a "failed" state is still part of a quorum - you need to actually remove it from the quorum with (`consul force-leave`)[https://consul.io/docs/commands/force-leave.html].

In your steps:
Step 1 has a 3 node cluster, you've failed one node so you have a 3 node cluster with 2 active (this is fine).
Step 2 puts the cluster into an outage state, you've killed 2 of the 3 nodes so N/2+1 no longer exists, the remaining machine can't handle it solo.

Check out (a post I made about this in another issue)[https://github.com/hashicorp/consul/issues/605#issuecomment-142675769] as well as the [consensus protocol](https://consul.io/docs/internals/consensus.html) information page.

**Comment by doublerebel** [comment]
Very useful link to 605, but I think this issue can be closed?

**Comment by slackpad** [comment]
Agree - closing this out - please use the mailing list if you have any more questions @psihodelik. This issue tracks making the reap interval configurable - https://github.com/hashicorp/consul/issues/1435.
