### ISSUE TITLE
Changing bootstrap_expect at runtime

### ISSUE THREAD

**Issue by omgold** [hashicorp/consul#1458]
I am wondering if the minimum number of expected servers, that can be specified in the config file by the value 'bootstrap_expect' can be changed at runtime, without restarting the server. I have a usage scenario, where I occasionally would like to reduce of expand the set of consul servers or move the servers over to a different set of nodes (without losing availability). Is this possible? If I understand the manual correctly, bootstrap_expect is not part of the reloadable configuration.

**Comment by highlyunavailable** [comment]
You don't need to, really. The _only_ time bootstrap_expect is used is when the server starts for the very first time and attempts to join a Raft cluster that has not initialized yet. Once a quorum is already created for the first time, the bootstrap_expect setting has no effect, even on subsequent restarts of the server. If you want to reduce/expand node counts or move nodes around, just follow the [adding/removing servers](https://consul.io/docs/guides/servers.html) guide.

**Comment by omgold** [comment]
Thanks for your answer. That's interesting. So this means on a join and graceful leave the number of expected servers for quorum is automatically adjusted? 

One more, minor question that turns up, though, is what about the role of the agent (client or server), can this be changed without restart? Actually, the situation I am considering is that a server to join has already an agent running in client mode. Can that role change be done without disrupting the client service?

**Comment by highlyunavailable** [comment]
Right, the quorum is just "n/2+1" where n is the number of Consul Servers in that datacenter.

No, you cannot switch between server and client without restarting.

**Comment by slackpad** [comment]
Closing this out as we never heard back. There are some changes being discussed over in https://github.com/hashicorp/raft/pull/117 that might eventually allow for non-voting members (you still won't be able to go from client to server on the fly), so stay tuned to that!
