### ISSUE TITLE
Consul UI error while getting HTTP/1.1 200 OK

### ISSUE THREAD

**Issue by sflint** [hashicorp/consul#1460]
I am able to get the entire cluster to work on vangrant machines locally.  I have 3 servers and 1 client. I finished bootstaping and added nodes to cluster.  I have the configuration files setup to see the ui at "/home/ansible/dist".

config file: 

{
    "server": false,
    "datacenter": "aws-west-2",
    "data_dir": "/var/consul",
    "client_addr" : "10.0.1.106",
    "ui_dir": "/home/ansible/dist",
    "encrypt": "F5dVJ1T1JXKKdUDlKOTkBw==",
    "log_level": "INFO",
    "enable_syslog": true,
{% set ip_list = [] %}
{% for host in groups['consul_server'] %}
{% if host != inventory_hostname %}
{% if ip_list.append(host) -%}{% endif %}
{% endif %}
{% endfor %}
    "start_join" : ["{{ ip_list|join('","') }}"],
    "bind_addr" : "{{inventory_hostname}}",
    "node_name" : "{{inventory_hostname}}"
}

I have confirmed the UI code has been downloaded and unzip at the following location "/home/ansible/"  this lead to the creation of "/home/ansible/dist"

This is all built using ansible and the ansible user. I have repeated the same playbooks in my QA environment.  I am running on AWS and have a VPC setup for security.  I am running an ELB(elastic load balancer) in front of the client machine that forwards from 80 -> 8500.  My ELB check is passing as it just pings /ui/.   There is a leader elected as I have tailed all log files.   This is the error I see when looking at the TCP DUMP from the client machine.   

.....&uxHTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 19919
Content-Type: text/html; charset=utf-8
Last-Modified: Fri, 13 Jun 2014 17:21:44 GMT
Date: Tue, 01 Dec 2015 20:03:53 GMT

https://gist.github.com/sflint/1e925aea1fcfb0d6e48d

I am not able to re produce this error or scenario on my local vagrant setup.

**Comment by slackpad** [comment]
Hi @sflint - that error is embedded into the index.html and is displayed client-side if it has problems making requests to the Consul server. From the looks of things, 200 response code and getting the index page back, it looks like things are working. Can you try things via a web browser and see how that goes?

**Comment by sflint** [comment]
From the web it just times out.   Here is the ELB address.  It is opened and forwarding 80 -> 8500

consul-ui-1252177438.us-west-2.elb.amazonaws.com/ui/

**Comment by slackpad** [comment]
Hmm - is it possible that your security setup doesn't allow traffic in both directions between Consul and ELB and it's throwing out the responses (though I'm not sure how it would ever get a TCP connection established if that was the case)? Consul's web server should bind to your supplied `client_addr` (10.0.1.106) so the ELB needs to be able to reach that. It looks like you have things configured correctly on the Consul side.

**Comment by sflint** [comment]
@slackpad  Than you so much for your help.  This came down to a subnet issue.  I am not sure why it would get a 200 back at all if it was on the wrong subnet, but it did.  I have since resolved the issue by creating another load balancer and placing it on the right subnet.

**Comment by slackpad** [comment]
Glad it's working!
