### ISSUE TITLE
Consul is silently failing , when run as single node in a DC.

### ISSUE THREAD

**Issue by rahul8590** [hashicorp/consul#1464]
Currently, I am running consul on a single node in DC (as a test run) . The UI is not displaying any services or nodes mentioned in the config file.  Initially it used to display those services.  Only after digging through the logs , it seems like its trying to run leader election every now and then and since no leader is elected, it seems to have failed. 
Is there a way to tell consul , not to run leader election if its executed a single node ?

**Comment by keyan** [comment]
@rahul8590: Yup, https://www.consul.io/docs/agent/options.html#_bootstrap

**Comment by slackpad** [comment]
Closing this out - please re-open if you are still having trouble. Bootstrap is the way to go for a single node (which is only recommended for development, not production). Consul 0.6.3 also added a `-dev` mode that makes this even easier.
