### ISSUE TITLE
[question] Why services in Consul are registered with an agent?

### ISSUE THREAD

**Issue by tongda** [hashicorp/consul#1466]
Hi guys,

I am a little confused by the service registering and discovery mechanism.

When registering, I have to give the node id. When I am in the node specified in the request, I can use `curl http://localhost:8500/v1/agent/services` to get all registered services. When I am in another node, when I do the same query, I got an empty dict. Also, `curl localhost:8500/v1/catalog/services` only contains `consul` service.

However, I used *consul-template* to update nginx config when services topology changed, and it worked well, even in the node that is not the one that services registered.

Could anyone explain the reason behind this scene?

**Comment by keyan** [comment]
@tongda Could you provide the output for the `curl`s as well as your Consul and Consul-template `config` files?

**Comment by tongda** [comment]
@keyan Thanks for your reply. Here's the logs:

I have got 2 nodes consul cluster.

```shell
vagrant@lb:~$ consul members
Node     Address             Status  Type    Build  Protocol  DC
lb       172.20.20.100:8301  alive   client  0.5.2  2         dc1
manager  172.20.20.20:8301   alive   server  0.5.2  2         dc1
```

When I try to query services from master, it works well.

```shell
vagrant@lb:~$ curl -v http://172.20.20.20:8500/v1/agent/services
* Hostname was NOT found in DNS cache
*   Trying 172.20.20.20...
* Connected to 172.20.20.20 (172.20.20.20) port 8500 (#0)
> GET /v1/agent/services HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 172.20.20.20:8500
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 16 Dec 2015 15:01:44 GMT
< Content-Length: 182
<
* Connection #0 to host 172.20.20.20 left intact
{"consul":{"ID":"consul","Service":"consul","Tags":[],"Address":"","Port":8300},"test-service-1":{"ID":"test-service-1","Service":"test-service-1","Tags":null,"Address":"","Port":0}}
```

But if I query services from slave, services are missing.

```
vagrant@lb:~$ curl -v http://localhost:8500/v1/agent/services
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/agent/services HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8500
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 16 Dec 2015 15:01:50 GMT
< Content-Length: 2
<
* Connection #0 to host localhost left intact
{}
```

I guess that a `service` is bound with an `agent`. But I'm not sure.

**Comment by slackpad** [comment]
Hi @tongda - what's happening is that services are registered with the agents, either through agent configuration files or the agent API as you've used in these examples. The agents then periodically sync their configuration up with the Consul servers. From there, service information _for all nodes in the cluster_ is then available via the catalog (https://www.consul.io/docs/agent/http/catalog.html) and health (https://www.consul.io/docs/agent/http/health.html) apis, or via DNS queries. If you query the agent API you'll only see services configured on that agent, but basically everything else (like consul-template) queries these other endpoints to discover services.

You can find more details here - https://www.consul.io/docs/internals/anti-entropy.html. Hope this helps!

**Comment by tongda** [comment]
@slackpad That's helpful! Thanks.
