### ISSUE TITLE
Upgrade Ember and modernize code

### ISSUE THREAD

**Issue by taras** [hashicorp/consul#1472]
I have an apprentice who needs a real project to work on to level up his skills. I would like to work with him upgrading this codebase to latest version of Ember and to EmberCLI. 

Do you have any objections to this? Would you be open to merging such a PR?

/cc @pearkes @tiwilliam

**Comment by pearkes** [comment]
Thanks for the great suggestion @taras!  Appreciate the work you do in the Ember community, too. The codebase for the UI has definitely lagged behind Ember releases substantially, and could use a dose of love.

However, I have a few worries about a large scale refactor and upgrade. Don't want to be too discouraging but want to be clear and respect your time.

- The current automated tests are _very_ shallow and don't cover a ton of the use cases. Upgrading and testing changes would require a lot of knowledge about UX for this UI and comparison with a full active instance of it. Something like http://demo.consul.io shows a set of the various states, but still lacks certain features (locks, ACLs).
- This UI is relied upon for critical infrastructure changes so there's not a lot of room for error and iteration – we can't push breaking changes to things like k/v, full stop
- The packaging and dist scripts for our current release process are not npm backed, which might be a headache
- We have some bandwidth and Ember folks internally who can spend time reviewing this, but we can't make it a priority unfortunately, so timelines might be long there.

The intent here is really great, and I don't want to act like this isn't necessary, but just wanted to be up front that this requires a lot of Consul understanding and has some hidden complexity. If you're comfortable with that, you're welcome to work on a WIP of this and we can give you some early feedback.

Thanks again for thinking of the project.

**Comment by taras** [comment]
@pearkes thank you for the detailed explanation - it's helpful in planning the mentoring and the process to make this code merge-able.

> The current automated tests are very shallow and don't cover a ton of the use cases. Upgrading and testing changes would require a lot of knowledge about UX for this UI and comparison with a full active instance of it. Something like http://demo.consul.io shows a set of the various states, but still lacks certain features (locks, ACLs).

Having some automated tests is helpful. We'll aim to not modify the HTML output to make it possible for you to run your test suite to verify the application. We're going to add acceptance tests to the application, so you'll have more tests when we're finished but it'll require manual checking on your part when we're finished.

> This UI is relied upon for critical infrastructure changes so there's not a lot of room for error and iteration – we can't push breaking changes to things like k/v, full stop

We can keep this project fairly low risk and aim to have code ready for you to review. Your team can use the new app when you're ready.

> The packaging and dist scripts for our current release process are not npm backed, which might be a headache

This should be fine. We'll copy the Ember App code into a new EmberCLI project. With EmberCLI, we can run `ember build` which will generate 2 files: `vendor.js` and `application.js`. The only change that you'll need to make will be to copy the files into the main repo and link to these new files. 

> We have some bandwidth and Ember folks internally who can spend time reviewing this, but we can't make it a priority unfortunately, so timelines might be long there.

Our goal will be to upgrade the application to use all of the latest best practices in a new EmberCLI project. We'll speak to the demo API(likely via a proxy). You should be able to test the application by setting up a more complete cluster and point to it's API.

> Just wanted to be up front that this requires a lot of Consul understanding and has some hidden complexity

It would be difficult to go all the way with this project without your team being onboard to work with us, so we'll just do what we can.Refactoring the app into the latest best practices on EmberCLI seems like a fairly straight forward project. We can aim to have all of the features implemented that are currently visible on the demo site. The result will be a repo that'll build the app and talk to the demo API. At that point, you can take that code and integrate into your application when it becomes a priority.

What do you think?
