### ISSUE TITLE
rpc_hold_timeout has been reused for client RPC call timeout

### ISSUE THREAD

**Issue by dclaisse** [hashicorp/consul#14732]
#### Overview of the Issue

Since versions 1.11.9, 1.12.1 and 1.13.0, there is now a timeout for client RPC calls (PR #11500).
This PR reused [rpc_hold_timeout](https://www.consul.io/docs/agent/config/config-files#rpc_hold_timeout) that defaults to 7s.

This timeout can be too low in some cases, such as fetching list of nodes from a big (~10k nodes) remote datacenter with high latency (350 ms in my case).

Issue is that while I'd like to increase client RPC timeout, I shouldn't have to mess with `rpc_hold_timeout` which has not the same role at all as per documentation (timeout for internal RPC calls during leader (re)election).

#### Reproduction Steps

1. Create a "faraway" cluster with 10k client nodes and high latency to reach it, and federate it to a local cluster
1. Run on a local consul agent `curl http://localhost:8500/v1/catalog/nodes?dc=faraway`
1. If request takes more than 7s, you'll receive an error: `"rpc error making call: i/o deadline reached"`

### Consul info for both Client and Server

Consul version 1.12.4 on both sides.

### Operating system and Environment details

Not relevant for this issue.

### Log Fragments

On local agent:
```
[ERROR] agent.client: RPC failed to server: method=Catalog.ListNodes server=x.x.x.x:8300 error="rpc error making call: i/o deadline reached"
[ERROR] agent.http: Request error: method=GET url=/v1/catalog/nodes?dc=faraway from=y.y.y.y:35670 error="rpc error making call: i/o deadline reached"
```

**Comment by dnlopes** [comment]
I just hit this issue. My consul-replicate daemon was hitting the timeout and I had to increase the hold-timeout as a workaround. It's OK as a workaround, but I wonder if this will have other impacts that I can't foresee.

**Comment by kisunji** [comment]
The fix for this issue has been merged to main and will be available in the next releases for versions:
```
1.14.0
1.13.3
1.12.6
1.11.11
```

it exposes a new config called `limits.rpc_client_timeout` which defaults to 60s and can be tuned separately from `rpc_hold_timeout`.
