### ISSUE TITLE
agent: failed to sync remote state: No cluster leader

### ISSUE THREAD

**Issue by mastachunco** [hashicorp/consul#1474]
Sorry I am new to Consul and I am having an issue that could be a bug, not sure. So I have a Cluster of 5 servers running 5.0 and I wanted to upgrade to 5.2. In order to test it I installed 5.2 on a 6th server and I joined it to the 5 node cluster. I can dump the member list on the new server and I can see the server in the peers.json of the other 5 clusters.

However, on the new server in the logs after booting I see the following:

Dec  7 18:29:49 ip-172-1-3-121 consul[1556]: raft: EnableSingleNode disabled, and no known peers. Aborting election.
Dec  7 18:29:59 ip-172-1-3-121 consul[1556]: agent.rpc: Accepted client: 127.0.0.1:33843
Dec  7 18:30:07 ip-172-1-3-121 consul[1556]: agent: (LAN) joined: 2 Err: <nil>
Dec  7 18:30:07 ip-172-1-3-121 consul[1556]: agent: failed to sync remote state: No cluster leader
Dec  7 18:30:32 ip-172-1-3-121 consul[1556]: agent: failed to sync remote state: No cluster leader
Dec  7 18:30:52 ip-172-1-3-121 consul[1556]: agent: failed to sync remote state: No cluster leader
Dec  7 18:31:19 ip-172-1-3-121 consul[1556]: agent: failed to sync remote state: No cluster leader
Dec  7 18:31:37 ip-172-1-3-121 consul[1556]: agent: failed to sync remote state: No cluster leader
Dec  7 18:32:03 ip-172-1-3-121 consul[1556]: agent: failed to sync remote state: No cluster leader
Dec  7 18:32:07 ip-172-1-3-121 consul[1556]: agent.rpc: Accepted client: 127.0.0.1:33845
Dec  7 18:32:33 ip-172-1-3-121 consul[1556]: agent: failed to sync remote state: No cluster leader
Dec  7 18:32:58 ip-172-1-3-121 consul[1556]: agent: failed to sync remote state: No cluster leader

Any help or ideas would be appreciated as I am not sure what I did wrong, any additional information that would be helpful please let me know.

**Comment by c4milo** [comment]
I would use the mailing list for this kind of questions instead. You will have a higher chance of getting help from the community.

**Comment by mastachunco** [comment]
Thanks, I discovered my issue on my own, stupid iptables was rejecting some of the traffic. Allowing the traffic resolved the issue sorry for the trouble.

**Comment by akkhil2012** [comment]
In my case it was peers.json file located at /data_dir/raft/ which is supposed to have list of all peers was
coming as null
