### ISSUE TITLE
Registering a service with a check

### ISSUE THREAD

**Issue by calvinirwin** [hashicorp/consul#1477]
Hi,

I am trying to register a service by posting to the /v1/catalog/register endpoint but i cant seem to get it working and I think it is because I am not sure exactly how the JSON should be formatted.  I have tried posting numerous different variations of the JSON from the Services and Checks pages in the documentation but nothing worked until I posted the following to an agent node:

{
	"Datacenter": "dc1",
	"Node": "366ba0496caa",
	"Address": "172.17.0.1",
	"Service": {
		"ID": "agent-read",
		"Service": "agent-read",
		"Tags": null,
		"Address": "172.17.0.3",
		"Port": 50001
	},
	"Checks": [
		{
			"Node": "366ba0496caa",
			"CheckID": "service:agent-read",
			"Name": "Service 'agent-read' check",
			"ServiceID": "agent-read",
			"ServiceName": "agent-read",
			"Interval": "10s",
			"id": "api",
			"name": "HTTP API on port 50001",
			"http": "http: //192.168.1.1:50001/health"
		}
	]
}

It responds with a 200 and a "true" response text value so it looks like it took it.  The node shows up in the web management tool but is deregistered once the agent syncs to the server node.  Is there a guide on getting this working via the http endpoint or am I trying to do something that the system does not support (but it looks like it does)?  Basically I would like any of my services to register themselves with consul and setup a health check when they come online.

Thanks

Calvin

**Comment by slackpad** [comment]
Hi @calvinirwin - you should use the agent API to register the services that are running on a given agent. The agent will take care of syncing the service with the catalog, as well as tying that service to the node that the agent is running on. That way if the node becomes unhealthy, the service will get marked as unhealthy as well. It's pretty rare to write to the catalog directly - usually you use the agent API (or configuration files on the agent) to register services and then let the agent sync them up.

There's an example here - https://www.consul.io/docs/agent/http/agent.html, please see the "/v1/agent/service/register" section. Hope that helps!

**Comment by calvinirwin** [comment]
This works great - can't believe i missed it in the docs.  Thanks so much!
