### ISSUE TITLE
Allow limiting DNS to a single response

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#1481]
It turns out that some implementation of `getaddrinfo` apply a sort to the returned results which breaks the randomization, as a predictable host is always selected. The simplest way to work around this is to only return a single random response, such that the client is forced to use that. Given a low TTL and native health checks, this should be fairly resilient. Additionally, most stub resolvers do not make use of the additional records and use the first record regardless.

See this thread for context: https://groups.google.com/forum/#!topic/consul-tool/AGgPjrrkw3g

**Comment by fusiondog** [comment]
I've created a pull request to address this issue. https://github.com/hashicorp/consul/pull/1583

**Comment by SuperQ** [comment]
Yes, we noticed this issue as well.  I tracked it back to a really terrible decision in RFC 3484 Rule 9[0].  RFC 6724[1] fixes the flaw in the 3484 specs, but libc doesn't seem to have caught up yet.

[0]: https://www.ietf.org/rfc/rfc3484.txt
[1]: https://tools.ietf.org/html/rfc6724

**Comment by sean-** [comment]
Fixed in #1712.
