### ISSUE TITLE
Consul 0.5.2 client can't register service to consul 0.6 servers?

### ISSUE THREAD

**Issue by rbrutas** [hashicorp/consul#1482]
consul.log on client;

    2015/12/09 14:17:39 [INFO] agent: Joining cluster...
    2015/12/09 14:17:39 [INFO] agent: (LAN) joining: [consul_cluster_ips]
    2015/12/09 14:17:39 [INFO] agent: (LAN) joined: 1 Err: <nil>
    2015/12/09 14:17:39 [INFO] agent: Join completed. Synced with 1 initial agents
    2015/12/09 14:17:39 [INFO] agent: Synced service 'app'
    2015/12/09 14:17:54 [INFO] agent: Synced check 'service:app'
==> Newer Consul version available: 0.6.0

checking the cluster catalog;

$ curl <ip>:8200/v1/catalog/services
{"consul":[]}

$ dig service.app.consul

;service.app.consul.		IN	A

the service.app.consul is not registered.

acl rule for the app;

  {
    "ModifyIndex": 7422,
    "CreateIndex": 7422,
    "Rules": "{ \"key\": { \"\": { \"policy\": \"read\" }, \"app/\": { \"policy\": \"write\" } },  \"service\": { \"\": {  \"policy\": \"read\" }, \"app\": { \"policy\": \"write\" } } }",
    "Type": "client",
    "Name": "app",
    "ID": "****"
  }

**Comment by slackpad** [comment]
Hi @rbrutas I'll try to reproduce this locally and see what's going on. Are there any related log entries on your Consul servers around the time the agent is trying to register the service?

**Comment by slackpad** [comment]
Hi @rbrutas one other thing - that `curl` call will need to use a capable token to read the service back (the app token has sufficient rights as you've defined it) if the anonymous token doesn't have read permissions to all services - see https://www.consul.io/docs/upgrade-specific.html. That might be it and "app" is just getting filtered for the anonymous token.

**Comment by rbrutas** [comment]
thanks @slackpad 

the only reference i see on the cluster logs;
    
    2015/12/09 14:17:28 [INFO] agent.rpc: Accepted client: 127.0.0.1:44348
    2015/12/09 14:17:39 [INFO] serf: EventMemberJoin: app-<dc_name>-1 <ip_address>
    2015/12/09 14:18:28 [INFO] agent.rpc: Accepted client: 127.0.0.1:44356

I am running the curl on one of the consul cluster node.

**Comment by ryanuber** [comment]
Hey @rbrutas,

It sounds like you are seeing the effects of the new ACL enhancements in Consul 0.6. By default, service discovery is not wide-open as it was in the past. Instead, the services, nodes, and almost everything else in the `/v1/catalog` endpoints are filtered using the privileges of the ACL token being used. You can restore the exact same functionality that Consul 0.5.x had by configuring the "anonymous" ACL token, as outlined [here](https://consul.io/docs/upgrade-specific.html) in the 0.6 ACL Enhancements section.

I would also recommend reading the section about "Blacklist mode and Service Discovery" on the [ACL documentation](https://consul.io/docs/internals/acl.html) as it has a few good details to know about the new system.

Hope that helps!

**Comment by rbrutas** [comment]
thank you all. this has been resolved.
