### ISSUE TITLE
[consul.aio] ClientSession.close was never awaited

### ISSUE THREAD

**Issue by kidrahahjo** [hashicorp/consul#14834]
#### Overview of the Issue
During teardown, consul tries to close the active session but since `ClientSession.close` is in async function, it has to be awaited in order for the session to be closed.

#### Reproduction Steps

```python
# script.py
from consul.aio import Consul

client = Consul()
```

After running this script, you'll run into the following warning:
```bash
RuntimeWarning: coroutine 'ClientSession.close' was never awaited
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb609145b80>
```

**Comment by subodhk01** [comment]
Strange no one ever commented on this

**Comment by neilyoung** [comment]
Having the same... Using aiortc. No idea what
