### ISSUE TITLE
CONSUL_RPC_ADDR not used in 0.6.0

### ISSUE THREAD

**Issue by tzz** [hashicorp/consul#1487]
According to the docs `CONSUL_RPC_ADDR` should work but it doesn't seem to:

```console
% echo $CONSUL_RPC_ADDR
10.10.10.2:8400

% consul members
Error connecting to Consul agent: dial tcp 127.0.0.1:8400: getsockopt: connection refused

% consul members -rpc-addr=$CONSUL_RPC_ADDR
Node       Address              Status  Type    Build  Protocol  DC
myhost    10.10.10.2:8301   alive    client  0.6.0  2         mydc

% consul --version
Consul v0.6.0
Consul Protocol: 3 (Understands back to: 1)
```

**Comment by slackpad** [comment]
Hi @tzz this is a weird one :-) I looked through the code and the support is there and I can't seem to reproduce this locally (it respects the environment variable). What platform are you running on? Does `env` show the variable?

**Comment by tzz** [comment]
Oh damn this was a confusion between a `K=V` format file (to be used by Docker) and trying to use it for environment variables, which does not `export` them.  Sorry for the trouble, Consul is working as designed, and thanks for the quick response.

**Comment by slackpad** [comment]
np!

**Comment by tzz** [comment]
For anyone looking to solve this in the future, the answer is to use `set -a` which will auto-export all the variables defined (and then turn it off with `set +a`):

```bash
set -a
source /my/environment/file
set +a
```
