### ISSUE TITLE
Not finding gox after downloading for v0.6.0

### ISSUE THREAD

**Issue by ch-acctg** [hashicorp/consul#1488]
Hi, we do:
```
+ git checkout v0.6.0
HEAD is now at 46499d6... Release v0.6.0
+ make updatedeps
--> Installing build dependencies
github.com/mitchellh/gox (download)
github.com/mitchellh/iochan (download)
...
github.com/ryanuber/columnize
+ make
--> Installing build dependencies
--> Running go fmt
bash: cannot set terminal process group (27029): Inappropriate ioctl for device
bash: no job control in this shell
==> Getting dependencies...
==> Removing old directory...
==> Building...
bash: gox: command not found
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 127
```
We seem to not be able to find gox after make grabs it with go, so any ideas?

**Comment by slackpad** [comment]
Hi @ch-acctg - haven't seen that before - it looks like there are some strange bash errors in there. If you do `github.com/mitchellh/gox` does that work?

**Comment by ch-acctg** [comment]
Adding go-pkg/bin to PATH gets me gox.  Interesting, I never had to do that before to build consul.

**Comment by slackpad** [comment]
Ok cool - yeah this is the first release to require `gox` and I don't think there were any other go-built tools required in the path in previous releases. Please let me know if you run into any other issues!
