### ISSUE TITLE
Consul fails to check for updates on IPv6-only hosts

### ISSUE THREAD

**Issue by AndersBlomdell** [hashicorp/consul#1491]
Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=linux&signature=7e0642c2-ab35-9df1-a402-65f219639208&version=0.5.1-dev: dial tcp 54.235.97.72:443: i/o timeout
# ping -c 1 -6 hashicorp.com

PING hashicorp.com(2400:cb00:2048:1::6819:f722 (2400:cb00:2048:1::6819:f722)) 56 data bytes
64 bytes from 2400:cb00:2048:1::6819:f722 (2400:cb00:2048:1::6819:f722): icmp_seq=1 ttl=60 time=16.1 ms
# ping -c 1 -6 checkpoint-api.hashicorp.com

ping: checkpoint-api.hashicorp.com: No address associated with hostname

**Comment by i0rek** [comment]
This is working now, thanks for reporting!

```
curl -6 hashicorp.com
* Rebuilt URL to: hashicorp.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::ffff:18.185.93.202...
* TCP_NODELAY set
* Connected to hashicorp.com (::ffff:18.185.93.202) port 80 (#0)
```
