### ISSUE TITLE
Checks on dynamic ports

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/consul#1492]
According to the docs I can define a check like this:

```
{
  "check": {
    "id": "api",
    "name": "HTTP API on port 5000",
    "http": "http://localhost:5000/health",
    "interval": "10s",
    "timeout": "1s"
  }
}
```

How can I do this when I dont know the port in advance? (e.g. its a container with a runtime-assigned port, e.g. mesos managed containers)

**Comment by gtmtech** [comment]
Duplicate of #1176  - which would be really useful.

**Comment by slackpad** [comment]
Closing this one as a duplicate.
