### ISSUE TITLE
Integer TTL behavior

### ISSUE THREAD

**Issue by ariscn** [hashicorp/consul#1495]
I'm using Consul 0.6.0 via python-consul.

I created a service with a TTL health check. The check was created with a TTL of 60. This succeeded in Consul, but I was unable to use the `v1/agent/check/pass/<service_id>` (or warning) endpoint - it returned 200 OK, but the health check remained critical.

The problem turned out to be that I used an integer TTL (60) instead of a string TTL ('60s'). However, Consul silently allowed this and exhibited the behavior above. Consul should either fail at the time of service creation, or assume seconds, depending on project convention.

Ref: https://github.com/cablehead/python-consul/issues/83

**Comment by i0rek** [comment]
Thank you for reporting. I understand that this was frustrating at the time that happened, but now we cannot do anything about it anymore. Thanks again!
