### ISSUE TITLE
Live demo referenced in Web UI documentation not working

### ISSUE THREAD

**Issue by berendt** [hashicorp/consul#1497]
The live demo referenced in the Web UI documentation available at http://www.consul.io/intro/getting-started/ui.html is not working like expected.

The link to the live demo is https://atlas.hashicorp.com/hashicorp/infrastructures/consul-demo.

```
Sorry, the page /hashicorp/infrastructures/consul-demo could not be found.

This error could mean one of two things:

The resource doesn't exist
The resource exists, but requires proper authorization to access
If someone has linked you to this resource, ensure that they have given you proper permissions to access it.
```

**Comment by pshima** [comment]
Hi @berendt,

Sorry about the issue with the URL.  I have a PR out to get this fixed.  https://github.com/hashicorp/consul/pull/1504

The correct URL for the demo is: https://atlas.hashicorp.com/hashicorp/environments/consul-demo

We will get this corrected in the getting started guide and thanks for creating this issue.

**Comment by pshima** [comment]
This has been fixed on the live website.  Thanks again for reporting this, closing this issue.
