### ISSUE TITLE
Using module on Atlas -- how to set keys?

### ISSUE THREAD

**Issue by ErikEvenson** [hashicorp/consul#1500]
What `key_name` and `key_path` should I use for terraform builds on Atlas?  For example: how to get the module example (https://terraform.io/intro/getting-started/modules.html) to work via an Atlas Terraform plan/apply.

**Comment by varun06** [comment]
If I am understanding your question correctly, you can have a `variables.tf` and define your variables in that file. Then modules can access them as ${var.key_name} and ${var.key_path}

**Comment by ErikEvenson** [comment]
Right -- except the file won't be available on Atlas at `key_path`.

**Comment by slackpad** [comment]
Hi @ErikEvenson take a look at https://github.com/sethvargo/atlas-demo - that's got an end-to-end demo with Consul that should be helpful (though be careful it is set up to allow open access for demo-ing). There are some ssh examples for key handling in there.

/cc @sethvargo

**Comment by sethvargo** [comment]
@slackpad @erikdubbelboer here are some more examples:

- https://github.com/sethvargo/terraform-workshop-atlas
- https://github.com/hashicorp/best-practices

**Comment by slackpad** [comment]
Closing this out for now - please email the list or re-open if you have more questions.
