### ISSUE TITLE
ui zip supplied on the consul website appears broken

### ISSUE THREAD

**Issue by far-blue** [hashicorp/consul#1502]
the UI zip available on the consul.io website at https://www.consul.io/downloads.html (linking to https://releases.hashicorp.com/consul/0.6.0/consul_0.6.0_web_ui.zip) only appears to have the index.html file and static folder which seems wrong.

**Comment by slackpad** [comment]
Hi @far-blue that should be everything:

```
workpad:Downloads james$ unzip consul_0.6.0_web_ui.zip
Archive:  consul_0.6.0_web_ui.zip
  inflating: index.html
   creating: static/
  inflating: static/application.min.js
  inflating: static/base.css
  inflating: static/base.css.map
  inflating: static/bootstrap.min.css
  inflating: static/consul-logo.png
  inflating: static/favicon.png
  inflating: static/loading-cylon-purple.svg
```

The last release inadvertently had a sub-folder called "dist" that we removed for this release:

```
workpad:Downloads james$ unzip consul_0.5.2_web_ui.zip
Archive:  consul_0.5.2_web_ui.zip
   creating: dist/
 extracting: dist/.gitkeep
  inflating: dist/index.html
   creating: dist/static/
  inflating: dist/static/application.min.js
  inflating: dist/static/base.css
  inflating: dist/static/base.css.map
  inflating: dist/static/bootstrap.min.css
  inflating: dist/static/consul-logo.png
  inflating: dist/static/favicon.png
  inflating: dist/static/loading-cylon-purple.svg
```

But the contents are all there, just without that sub-folder. Sorry if that caused some confusion!

**Comment by far-blue** [comment]
Ah, yes, that would explain it :) I'd written a docker image that extracted and used the dist folder which, of course, broke with 0.6.0 and when I looked in the git repo I noticed other folders such as the javascript folder and figured the release was broken. thanks for clarifying thingg!

**Comment by slackpad** [comment]
Since a few people have asked about this I went ahead and updated the documentation to give people a heads up - https://github.com/hashicorp/consul/commit/ec5d9463bcc4ff6c3b34739998ffc2f65a0d9305.
