### ISSUE TITLE
Cluster peering disregards `advertise_addr_wan` and `advertise_addr_wan_ipv4`

### ISSUE THREAD

**Issue by quinndiggitypolymath** [hashicorp/consul#15051]
I have been unable to have Consul respect `advertise_addr_wan` and `advertise_addr_wan_ipv4` in the tokens generated via `consul peering generate-token`.

The base64 encoded json token contents always contain the `advertise_addr` / advertise_addr_ipv4`, which is unreachable from the remote cluster:
```
ServerAddresses: [ '__internal_lan_ip__:8502', '__internal_lan_ip__:8502', '__internal_lan_ip__:8502' ]
```

On the cluster initiating the connection (with the generated token), the following is logged:
```
error: desc = \"transport: Error while dialing dial tcp __remote_internal_lan_ip__:8502: i/o timeout
error managing peering stream
rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp __remote_internal_lan_ip__:8502: i/o timeout
```

The proper address can be forced by editing the token:
```
let x = JSON.parse(atob('...'))
x[0] = '__external_wan_ip__:8502';
...
x[N] = '__external_wan_ip__:8502';
console.log(btoa()JSON.stringify(x)))
```
however, after the initial peering is successful, the `__internal_lan_ip__` from servers on either side are synced and replace the forced `__external_wan_ip__`; immediately afterwards, the peering connection fails

**Comment by huikang** [comment]
@quinndiggitypolymath , thanks for reporting. I'd like to gather more  information to reproduce the error.
- What kind of environment do you run consul cluster, VM or k8s?
- What are the values of `advertise_addr_wan` and `advertise_addr_wan_ipv4` in your server agent file? It would ideal if you could provide any other information related to address or port in the config file.

**Comment by quinndiggitypolymath** [comment]
- consul `1.13.2`
- linux, mix of bare metal/vm, and mix of arm64 + amd64
- `advertise_addr_wan = "{{ GetInterfaceIP \"external0\" }}"`
- `advertise_addr_wan_ipv4 = "{{ GetInterfaceIP \"external0\" }}"` (have also tried disabling this, as `ipv6.disable=1` kernel parameter is set and `advertise_addr_wan_ipv6` has no value)

`external0` has a publicly reachable WAN address assigned to it and can receive traffic on the interface without issue / firewall is configured correctly, while `internal0` is on the `10.0.0.0/16` subnet; they are distinct interfaces, `consul info` shows the addresses are being deduced correctly from the templated `advertise_addr_` values

addresses:
```
dns   = "127.0.0.1 {{ GetInterfaceIP \"internal0\" }}"
http  = "127.0.0.1"
https = "127.0.0.1 {{ GetInterfaceIP \"internal0\" }} {{ GetInterfaceIP \"external0\" }}"
#grpc  = "127.0.0.1 {{ GetInterfaceIP \"internal0\" }} {{ GetInterfaceIP \"external0\" }}" # suffers from the same issue
grpc  = "0.0.0.0"                                                                                                            # suffers from the same issue
```

ports:
```
ports = {
  dns              = 8600
  http             = -1 # disabled
  https            = 8501
  grpc             = 8502
  serf_lan         = 8301
  serf_wan         = 8302
  server           = 8300
  sidecar_min_port = 21000
  sidecar_max_port = 21255
  expose_min_port  = 21500
  expose_max_port  = 21755
}
```

full mtls/https/encrypted serf on all listeners, certificate verification enabled strictly, everything else otherwise is working

**Comment by quinndiggitypolymath** [comment]
sorry, forgot to include:
```
bind_addr = "0.0.0.0"
client_addr = "127.0.0.1"
```
