### ISSUE TITLE
no obvious way to configure consul-ui to point to a consul server

### ISSUE THREAD

**Issue by far-blue** [hashicorp/consul#1506]
Although the consul-ui readme mentions it can be served from any web server, it appears that the code assumes that web server will be running on the same domain as a consul agent. Is there any reason this is not something that can be configured? E.g. by fetching a config.json file dropped into the root folder or a script element in the index.html file that provides a base url?

Or is this something already available but just not documented?

**Comment by far-blue** [comment]
I've added a pull request (#1702) with a basic fix for this. I'm not sure I'm happy with how users can customise the consul host address (by editing the var in the html file) so all thoughts and suggestions welcome :)

**Comment by slackpad** [comment]
Closing since #1702 was merged. I can't think of a more elegant way to do this, and at least you've got the changes consolidated to one spot. Thanks!
