### ISSUE TITLE
transport: Error while dialing failed to find Consul server for global address

### ISSUE THREAD

**Issue by quinndiggitypolymath** [hashicorp/consul#15087]
Consul `1.13.3` - the following is being logged from server nodes on a regular cadence (once per minute, approximately)

```
{
  "@level": "warn",
  "@message": "[core]grpc: addrConn.createTransport failed to connect to {__DATACENTER_NAME__-__INTERNAL_LAN_ADDRESS__:8300 leader <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing failed to find Consul server for global address \\\"__DATACENTER_NAME__-__INTERNAL_LAN_ADDRESS__:8300\\\"\". Reconnecting...",
  "@module": "agent",
  "@timestamp": "..."
}
```
Where `__DATACENTER_NAME__` is the agent's `datacenter` setting and `__INTERNAL_LAN_ADDRESS__` is its `advertise_addr` / `advertise_addr_ipv4` value.

It seems there _may_ be regressions in the more recent version of consul around `advertise_addr` / `advertise_addr_ipv4` / `advertise_addr_wan` / `advertise_addr_wan_ipv4`, or otherwise around binding multiple addresses via templated `addresses.*` (ie. `https = "127.0.0.1 {{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/16\" | attr \"address\" }} {{ GetAllInterfaces | include \"name\" \"^interface0\" | attr \"address\" }}"`) causing the incorrect address to be compared against (wan vs lan).

Looking at https://github.com/hashicorp/consul/blob/main/agent/grpc-internal/resolver/resolver.go#L71 and comparing with `members.json` from `consul debug`, as well as going off the changes that were needed for https://github.com/hashicorp/consul/issues/15051 , it seems that the wan address may be the ones being compared against in the query for nodes' lan address, resulting in no matches:

`cat members.json | jq -r .[].Addr`
```
__WAN_IP_1__
...
__WAN_IP_N__
```

There is no trace of nodes' lan addresses in `members.json`

**Comment by quinndiggitypolymath** [comment]
`consul operator raft list-peers`
```
Node                   ID                                    Address          State     Voter  RaftProtocol
__HOSTNAME_1__  aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa  __INTERNAL_LAN_ADDRESS_1__:8300   leader  true   3
...
__HOSTNAME_N__  aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa  __INTERNAL_LAN_ADDRESS_N__:8300  follower  true   3
```


`consul members`
```
Node                                   Address          Status  Type    Build   Protocol  DC         Partition  Segment
__HOSTNAME_1__                  __INTERNAL_LAN_ADDRESS_1__:8301   alive   server  1.13.3  2         __DATACENTER_NAME__  default    <all>
...
__HOSTNAME_N__                  __INTERNAL_LAN_ADDRESS_N__:8301   alive   server  1.13.3  2         __DATACENTER_NAME__  default    <all>
```



`consul members -wan`
```
Node                             Address              Status  Type    Build   Protocol  DC         Partition  Segment
__HOSTNAME_1__.__DATACENTER_NAME__  __EXTERNAL_WAN_ADDRESS_1__:8302   alive   server  1.13.3  2         __DATACENTER_NAME__  default    <all>
...
__HOSTNAME_N__.__DATACENTER_NAME__  __EXTERNAL_WAN_ADDRESS_N__:8302   alive   server  1.13.3  2         __DATACENTER_NAME__  default    <all>
```



`consul info | grep 8300`
```
	leader_addr = __INTERNAL_LAN_ADDRESS_1__:8300
	latest_configuration = [{Suffrage:Voter ID:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa Address:__INTERNAL_LAN_ADDRESS_1__:8300} ... {Suffrage:Voter ID:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa Address:__INTERNAL_LAN_ADDRESS_N__:8300}]

```

**Comment by quinndiggitypolymath** [comment]
Additionally, this is essentially the same configuration as in https://github.com/hashicorp/consul/issues/15051#issuecomment-1283384313

`failed to find Consul server for global address` and `returns server metadata for a server with the specified globally unique address` leads me to believe the use of `server.Addr.String()` (ie. https://github.com/hashicorp/consul/blob/main/agent/metadata/server.go#L43 ) might disregard any of the scenarios where:

- NAT for WAN addresses mean nodes are reliant on their `advertise_addr_wan`
- entirely separate LAN/WAN interfaces, or distinct firewall rules based on incoming/destination addresses
- the use of vpn/tunnels beneath consul enforces similar such restrictions/mandate use of addresses specifically as configured

**Comment by huikang** [comment]
@quinndiggitypolymath , could you try the 1.13.x branch? I think the backport PR is missing in the v1.13.3 release

**Comment by huikang** [comment]
cc @freddygv

**Comment by quinndiggitypolymath** [comment]
Yeah, I was surprised that https://github.com/hashicorp/consul/pull/15067 didn't make it into the release yesterday; do you know if there will be another point release cut prior to next month?

On a different note, I receive `Error while dialing failed to find Consul server for global address` on clusters without peering enabled, so I don't know if that fix itself is relevant to this issue; https://github.com/hashicorp/consul/pull/15067/files only alters the node address selection strategy within `agent/consul/peering_backend.go`, but I am seeing this on clusters that are entirely sans-peering

**Comment by quinndiggitypolymath** [comment]
If my hunch is correct, https://github.com/hashicorp/consul/pull/15067 will resolve the generated peering tokens specifying unreachable LAN addresses for remote nodes to connect to, but as mentioned https://github.com/hashicorp/consul/issues/15051#issue-1414060888 I suspect that the following will still be true:

> however, after the initial peering is successful, the __internal_lan_ip__ from servers on either side are synced and replace the forced __external_wan_ip__; immediately afterwards, the peering connection fails

:point_up: I believe this specific behaviour to be a symptom of https://github.com/hashicorp/consul/pull/14285 as, if the internal `globally unique address` for a node is using LAN addresses but the `server.Addr.String()` uses WAN (ie. https://github.com/hashicorp/consul/blob/main/agent/grpc-internal/resolver/resolver.go#L78 ), then `globally unique address` isn't actually unique and _could_ collide with other datacenters that are using similar internal CIDR blocks where servers on either side both have the same LAN address (but different WAN, of course)

**Comment by quinndiggitypolymath** [comment]
Which, to be unambiguous, is why I am under the impression there may be regressions around `advertise_addr` / `advertise_addr_ipv4` / `advertise_addr_wan` / `advertise_addr_wan_ipv4` (or otherwise around binding multiple addresses via templated `addresses.*`) in the more recent versions of consul - this error is new (to me) since versions `> 1.11`

**Comment by huikang** [comment]
@quinndiggitypolymath , I tested with the `main` branch and `release/1.14.x` branch, both contains the fixing PR and work fine. The reason is that when replicating the server address, we are sending the correct tagged address https://github.com/hashicorp/consul/blob/d714003ddaf06b7403935d674e36108c14cdd5b9/agent/consul/autopilotevents/ready_servers_events.go#L235-L242

So once the connection is established, the server address reconciliation should work as expected.

PS. The release team cut the v1.13.3 around noon on the release day, but the fixing PR was back-ported at night. Therefore, it missed the train. I think we shall have 1.14-GA and next v1.13.4 very soon.

**Comment by huikang** [comment]
@quinndiggitypolymath , my last experiment results were wrong. The PR (#15108 ) to fix the bug is submitted.

**Comment by quinndiggitypolymath** [comment]
Just following up on this - still seeing this issue on `1.13.6`:

`consul peering list`:
```
Error listing peerings: Unexpected response code: 500 (rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing failed to find Consul server for global address \"__DATACENTER_NAME__-__INTERNAL_LAN_ADDRESS__:8300\"")
```
and in the logs:
```
{"@level":"error","@message":"Request error","@module":"agent.http","@timestamp":"2023-02-02T00:06:17.777911Z","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing failed to find Consul server for global address \\\"__DATACENTER_NAME__-__INTERNAL_LAN_ADDRESS__:8300\\\"\"","from":"127.0.0.1:32976","method":"GET","url":"/v1/peerings"}
```
