### ISSUE TITLE
Consul homepage example makes no sense

### ISSUE THREAD

**Issue by vizanto** [hashicorp/consul#1510]
It looks slick, but:

Why do you get back a big JSON structure with `"Value": "YmFy"` after a `curl -X PUT -d 'bar'`?!

Shouldn't you get 'bar' back? :-)

**Comment by slackpad** [comment]
Hi @vizanto it's base64 encoded! I added another step to that example that makes it clear :-) This is explained in more detail in this example - https://www.consul.io/intro/getting-started/kv.html. Thanks for opening a bug - I was confused when I saw this the first time, too.

**Comment by slackpad** [comment]
![image](https://cloud.githubusercontent.com/assets/673509/11863323/dee88378-a447-11e5-8c26-842f8a00902f.png)
