### ISSUE TITLE
Doc Problem: stastd_addr config option is incorrect

### ISSUE THREAD

**Issue by dbeckham** [hashicorp/consul#1512]
The `statsd_addr` option at https://www.consul.io/docs/agent/options.html#statsd_addr says, "This provides the address of a statsd instance", but it actually requires an address and port in the form of `1.2.3.4:1234`.  If it were simply stated as *This provides the address and port of a statsd instance in the format `localhost:port`*, it would be far less ambiguous, as well as not using address to mean more than one thing.

**Comment by slackpad** [comment]
Thanks - we will fix this!

**Comment by dbeckham** [comment]
Awesome, thank you.

**Comment by slackpad** [comment]
Fixed via https://github.com/hashicorp/consul/pull/1533.
