### ISSUE TITLE
Consul 1.13.x watch filter is broken

### ISSUE THREAD

**Issue by sfuerte** [hashicorp/consul#15169]
#### Overview of the Issue

A simple watch with filter by service name works just fine in 1.12 and below:

```sh
$ consul version
Consul v1.12.6
Revision 950fcb85

# /tmp/handler.sh is defined as per below
$ consul watch -type=service -service=my_service /tmp/handler.sh

# after minor reformatting
$ jq '. | length' /tmp/test
2
```

using the same watch in the same cluster under Consul 1.13 would generate the `/tmp/test` file with two blocks of "New Service" in it:
- the first one the same as above (i.e. the correct one),
- and the second with every other service available in the cluster and not matching the `my_service` name;

#### Reproduction Steps

Steps to reproduce this issue, eg:

```sh
# /tmp/handler.sh
#!/bin/bash

echo "New service:" >> /tmp/test
read x
echo $x >> /tmp/test
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
$ consul version
Consul v1.13.3
Revision b29e5894
Build Date 2022-10-19T19:49:59Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 2
build:
	prerelease =
	revision = b29e5894
	version = 1.13.3
	version_metadata =
consul:
	acl = enabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 73
	max_procs = 4
	os = linux
	version = go1.18.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 48044
	members = 17
	query_queue = 0
	query_time = 6
```

</details>

<details>
  <summary>Server info</summary>

```sh
$ consul members | grep -E "(Type|server)" | awk '{ print $4 "\t" $5 }'
Type	Build
server	1.10.0
server	1.10.0
server	1.10.0
```

</details>

### Operating system and Environment details

```sh
$ lsb_release -d
Description:	Debian GNU/Linux 11 (bullseye)

$ uname -rvmso
Linux 5.19.0-0.deb11.2-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1~bpo11+1 (2022-10-03) x86_64 GNU/Linux
```

Nothing fancy in agent JSON config (some of the params are removed for obvious reasons.
<details>
  <summary>/etc/consul.d/agent.json</summary>

```json
{
    "datacenter": "...",
    "bind_addr": "{{ GetInterfaceIP \"ens3\" }}",
    "client_addr": "0.0.0.0",
    "data_dir": "/var/lib/consul",
    "server": false,
    "log_level": "info",
    "node_meta": {
...
    },
    "encrypt": "...",
    "retry_join": [...],
    "connect": {
        "enabled": true
    },
    "domain" : "...",
    "primary_datacenter": "...",
    "acl": {
        "enabled": true,
        "default_policy": "deny",
        "down_policy": "extend-cache",
        "enable_token_persistence": true,
        "enable_token_replication": true,
        "tokens": {
            "agent": "...",
            "default": "..."
        }
    },
    "ports": {
        "http": 8500,
        "https": 8501,
        "grpc": 8502
    },
    "tls": {
        "defaults": {
            "ca_file": "/etc/consul.d/certs/ca.pem",
            "cert_file": "/etc/consul.d/certs/cert.pem",
            "key_file": "/etc/consul.d/certs/key.pem",
            "verify_incoming": true,
            "verify_outgoing": true
        },
        "internal_rpc": {
            "verify_server_hostname": true
        }
    }
}
```
</details>

**Comment by huikang** [comment]
@sfuerte , I noticed that your server version is 1.10.0, which is a bit low than the client and out of support. Could you try upgrading the server and see if you can reproduce.

I tested with the main branch, which produces the correct result - one update per service change.

**Comment by sfuerte** [comment]
@huikang , thanks for the quick response! 
Unfortunately, the Consul servers aren't controlled by us and can't influence that part. 

On the another hand, when doing `consul watch`, won't it get it from local agent only, or still polls the server directly?

**Comment by huikang** [comment]
> On the another hand, when doing consul watch, won't it get it from local agent only, or still polls the server directly?

`consul watch` sends blocking query to servers. So the server with the very old version may cause the issue.

**Comment by sfuerte** [comment]
I see. Thanks for the info. 
If you confirm the feature works as expected in 1.13 server, I guess we can close the issue then.
