### ISSUE TITLE
Feature Request: `consul maint` should return non-zero

### ISSUE THREAD

**Issue by nicholascapo** [hashicorp/consul#1520]
The current easiest way to tell if a node is in maintenance mode requires parsing the output of `consul maint`.
This makes it rather difficult to use in shell scripts.

I propose that `consul maint` return non-zero if the node is in maintenance mode, and zero otherwise.
This is in addition to the normal output.

Nicholas

**Comment by nicholascapo** [comment]
Also if a reason is provided, the output of `consul maint` has no strings that can be easily parsed.

Example:
```
$ consul maint --enable
$ consul maint
Node:
  Name:   hostname
  Reason: Maintenance mode is enabled for this node, but no reason was provided. This is a default message.

$ consul maint --disable

$ consul maint --enable --reason foo
$ consul maint
Node:
  Name:   hostname
  Reason: foo
```

**Comment by i0rek** [comment]
@vamage thank you for your contribution! I am closing this because I don't understand why a successful command should return anything but 0. If you still feel strongly about this change, I am happy to reopen if you can explain your reasoning.
