### ISSUE TITLE
Using consul rtt command with https

### ISSUE THREAD

**Issue by sboily** [hashicorp/consul#1521]
Hello,

It seems it's impossible to use rtt command with a consul using only https.

Unable to look up agent info: Get http://127.0.0.1:8500/v1/agent/self: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

It looks like there is no option to pass SSL configuration.
Can you confirm ?

Thank you

**Comment by ryanuber** [comment]
Hey @sboily, you should be able to use the `CONSUL_HTTP_SSL=1` environment variable to control this. You can also use `CONSUL_HTTP_SSL_VERIFY=0` if you need to skip verification.

Admittedly I had to go code diving for this answer so we should definitely make it easier to find in the docs and CLI usage. Thanks for reporting this.

**Comment by sboily** [comment]
Hello @ryanuber, thank you it works :+1:

**Comment by sboily** [comment]
I open a PR #1522, i think there is another variable like passing certificate ?

**Comment by slackpad** [comment]
Docs got updated in #1522.
