### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Twitter1268** [hashicorp/consul#15228]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

### Overview of the Issue

A paragraph or two about the issue you're experiencing / suggestion for
improvement.

### Reproduction Steps

Steps to reproduce this issue/view the area for improvement, eg:

1. Visit the UI page at `/ui/services`
1. Click .... then click...etc.
1. View error/area.

### Describe the solution you'd like

If this is an improvement rather than a bug, a clear and concise description
of what you want to happen. How have you seen this problem solved in other
UIs?

### Consul Version

This can be found either in the footer of the UI (Consul versions pre 1.10) or
at the top of the help menu that is in the top right side of the UI.

### Browser and Operating system details

Browser, Browser Version, OS, and any other information you can provide about the environment that may be relevant.

### Screengrabs / Web Inspector logs

If you think it's worthwhile, include appropriate screengrabs showing the
error/area for improvement. Try to include the URL bar of the browser so we
can see the current URL where the error manifests. Please be careful to
obfuscate any sensitive information either in the URL or in the browser page
itself.

**Comment by jkirschner-hashicorp** [comment]
Hi @Twitter1268,

Can you post a screenshot of the problem you see in the GUI?

It sounds like you looked at the `/ui/services` page and see some kind of error when you click. We'll need more details about the situation so we can help.

And is this report based on Consul versions pre-1.10 only? Or have you observed this in more recent versions of Consul also?

I also see that this is your first post on the Consul Github - welcome to the Consul community!

**Comment by jkirschner-hashicorp** [comment]
Hi @Twitter1268,

I'm closing this issue for now because I don't have enough information to respond. If you are still experiencing an issue, please reply with more information and reopen the issue. Thank you!
