### ISSUE TITLE
Large number of error message RPC deadlines after the introduction of rpc_client_timeout

### ISSUE THREAD

**Issue by blockmar** [hashicorp/consul#15246]
#### Overview of the Issue

Large number of error message regarding RPC deadlines after the introduction of https://github.com/hashicorp/consul/pull/14965

Both from Consul agents and from agents in other languages such as Spring Cloud Consul (Java)

Our configuration remains unchanged since 1.13.2 since this is a patch update.

```
Nov  3 15:48:09 ip-10-X-X-X.ec2.internal consul[2124]: agent.client: RPC failed to server: method=Catalog.ListServices server=10.X.Y.Y:8300 error="rpc error making call: i/o deadline reached"
```

```
com.ecwid.consul.v1.OperationException: OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='rpc error making call: i/o deadline reached')
```

Our systems still seem to be working as expected but our logs are getting filled with messages like the two examples above. This risks hiding real issues and triggering false alarms and causing alarm fatigue.

#### Reproduction Steps

Upgrade from Consul 1.13.2 to 1.13.3

### Consul info for both Client and Server

_No access to a token allowed to perform `agent:read`_

### Operating system and Environment details

Ubuntu Linux 20.04

### Log Fragments

```
Nov  3 15:48:09 ip-10-X-X-X.ec2.internal consul[2124]: agent.client: RPC failed to server: method=Catalog.ListServices server=10.X.Y.Y:8300 error="rpc error making call: i/o deadline reached"
```

```
com.ecwid.consul.v1.OperationException: OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='rpc error making call: i/o deadline reached')
```

**Comment by huikang** [comment]
Hi, @blockmar , thanks for reporting the issue.

> Both from Consul agents and from agents in other languages such as Spring Cloud Consul (Java)

Just want to clarify that if all agents are upgraded to 1.13.3? Could you elaborate a bit on "agents in other languages such as Spring Cloud Consul (Java)"?

**Comment by blockmar** [comment]
No problem, all participating Consul instances are running 1.13.3 and where updated at the same time by rotating servers, replacing them one by one. All where previously running 1.13.2.

My reference to agents in other languages was that we use Spring Cloud Consul in our services.
https://github.com/spring-cloud/spring-cloud-consul

They in turn use this API library https://github.com/Ecwid/consul-api

But that in turns seem to talk to Consul over HTTP. So the underlying error message is probably received from Consul itself over HTTP as well, as an 500 Internal server Error with cause  `rpc error making call: i/o deadline reached`.

So in my opinion the Java code is not really the cause of the issue here.

```
	@Override
	public Response<Map<String, List<String>>> getCatalogServices(CatalogServicesRequest catalogServicesRequest) {
		HttpResponse httpResponse = rawClient.makeGetRequest("/v1/catalog/services", catalogServicesRequest.asUrlParameters());

		if (httpResponse.getStatusCode() == 200) {
			Map<String, List<String>> value = GsonFactory.getGson().fromJson(httpResponse.getContent(),
					new TypeToken<Map<String, List<String>>>() {
					}.getType());
			return new Response<Map<String, List<String>>>(value, httpResponse);
		} else {
			throw new OperationException(httpResponse);
		}
	}
```

**Comment by tunhvn** [comment]
We have the same issue with Spring Cloud Consul and Consul 1.13.3

`
2022-11-11 14:22:12.983 ERROR 1 --- [TaskScheduler-1] o.s.c.c.discovery.ConsulDiscoveryClient  : Error watching Consul CatalogServices

com.ecwid.consul.v1.OperationException: OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='rpc error making call: i/o deadline reached')
	at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:151) ~[consul-api-1.4.5.jar!/:na]
	at com.ecwid.consul.v1.ConsulClient.getCatalogServices(ConsulClient.java:400) ~[consul-api-1.4.5.jar!/:na]
	at org.springframework.cloud.consul.discovery.ConsulCatalogWatch.catalogServicesWatch(ConsulCatalogWatch.java:135) ~[spring-cloud-consul-discovery-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
`

**Comment by huikang** [comment]
@blockmar , thanks for the info. You are right: your Java code is essentially calling the `/v1/catalog/services`.

I am doing the following steps and observe only scattered lines of `error="rpc error making call: i/o deadline reached"`

1. start a consul server and client agent 1.13.2
2. upgrade both to 1.13.3 and change the `rpc_client_timeout` to 1s
3. I use a modified consul server 1.13.3 with added time.sleep in handling catalog register
4. Send an http request to the client agent to list catalog (the client agent will send a RPC request to server agent)

```
2022-11-12T00:36:31.385-0500 [ERROR] agent.client: RPC failed to server: method=Catalog.Register server=192.168.1.165:8300 error="rpc error making call: i/o deadline reached"
2022-11-12T00:36:31.386-0500 [WARN]  agent: Syncing service failed.: service=svc-test.1 error="rpc error making call: i/o deadline reached"
2022-11-12T00:36:31.386-0500 [ERROR] agent.anti_entropy: failed to sync changes: error="rpc error making call: i/o deadline reached"
2022-11-12T00:36:31.386-0500 [DEBUG] agent: Node info in sync
2022-11-12T00:36:32.387-0500 [ERROR] agent.client: RPC failed to server: method=Catalog.Register server=192.168.1.165:8300 error="rpc error making call: i/o deadline reached"
2022-11-12T00:36:32.387-0500 [WARN]  agent: Syncing service failed.: service=svc-test.1 error="rpc error making call: i/o deadline reached"
2022-11-12T00:36:32.387-0500 [ERROR] agent: failed to sync changes: error="rpc error making call: i/o deadline reached"
```

After that, I can only see the error message periodically due to anti-entropy sync up from the client agent. These are all expected. Could you provide more context from your client agent log message around the line containing`"rpc error making call: i/o deadline reached"`? Thanks.

**Comment by blockmar** [comment]
@huikang Sorry for my late reply. I'm afraid that you lost me a bit here. I think I need to understand the background.

You are basically saying that the message we are seeing event when making http requests to Consul is due to RPC client timeouts between the Consul http web server (the consul agent on localhost) and other parts of consul?

Did I understand you correctly?

When updating to 1.13.3 we did not update our config and thus have not set any value for `rpc_client_timeout`. According to the documentation the default timeout is 60 sec. This would mean that any http request we send should "wait" for 60 sec before receiving this error message, is that correct?

If my assumptions are correct that would mean that we have severe time-out issues in our environment. It might be possible but we have not experienced any other service degradation or similar. But if you agree with my reasoning I will investigate.

As to you reference about "expected" messages of i/o deadline reached, are there any reasons why these would appear as a response when calling Consul using http? That would seem odd to me.

**Comment by kisunji** [comment]
Just to be clear, are you saying in 1.13.2 you were not seeing i/o timeouts but as of 1.13.3 they are appearing frequently?

I'm not too familiar with the Spring Consul library - do you know if the call you are making to `/v1/catalog/services` is blocking or non-blocking [docs](https://developer.hashicorp.com/consul/api-docs/features/blocking)? If you are passing `?index=` then it indicates intent to block.

**Comment by tornstam** [comment]
We have exactly the same issue. Everything works in 1.13.3 and after that we get the same error messages.

**Comment by blockmar** [comment]
> onException(statusCode=500, statusMessage='Internal Server Error', statusContent='rpc error making call: i/o deadline reached')
> 	at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:151) ~[consul-api-1.4.5.jar!/:na]

Looks like most calls include an `index` parameter. Here are some samples from the Java lib. Nit 100% sure where the 2 second wait comes from.
```
http://localhost:8500/v1/catalog/services?wait=2s&token=<retracted>
http://localhost:8500/v1/catalog/services?wait=2s&index=16165&token=<retracted>
http://localhost:8500/v1/catalog/services?wait=2s&index=18905&token=<retracted>
```

**Comment by kisunji** [comment]
I have a WIP PR I hope will address the issue: https://github.com/hashicorp/consul/pull/15541

It's interesting that Spring Consul users have reported this since 1.13.3 (unless @tornstam is not using it?). I'm assuming the unconventionally short `?wait=2s` that seems to be a default in Spring Consul is triggering some edge case with jitter more frequently.
