### ISSUE TITLE
Protocol version in consul -v  vs consul members 

### ISSUE THREAD

**Issue by scalp42** [hashicorp/consul#1531]
I've looked at the doc and I can't find the answer.

We upgraded our Consul cluster to `0.6.0` last night and there's some confusion related to protocol versions:

```
root@consul-i-c7296503 # consul -v
Consul v0.6.0
Consul Protocol: 3 (Understands back to: 1)
```

Consul protocol shows up at `3` but if we run `consul members` anywhere, they all show up as `2`:

```
Node            Address            Status  Type    Build  Protocol  DC
i-1b08c3c1      10.52.42.90:8301   alive   client  0.6.0  2         chef
i-45e2b881      10.52.32.75:8301   alive   client  0.6.0  2         chef
i-88c6ab51      10.52.22.136:8301  alive   client  0.6.0  2         chef
i-1808c3c2      10.52.42.231:8301  alive   client  0.6.0  2         chef
i-81c6ab58      10.52.22.163:8301  alive   client  0.6.0  2         chef
i-9ce0ba58      10.52.32.28:8301   alive   client  0.6.0  2         chef
i-5d3a0899      10.52.32.129:8301  alive   client  0.6.0  2         chef
i-ac914876      10.52.42.5:8301    alive   client  0.6.0  2         chef
i-e74b313e      10.52.22.151:8301  alive   client  0.6.0  2         chef
i-069952dc      10.52.41.194:8301  alive   client  0.6.0  2         chef
i-20076af9      10.52.21.91:8301   alive   client  0.6.0  2         chef
i-794a10bd      10.52.31.34:8301   alive   client  0.6.0  2         chef
i-00d6e2c4      10.52.32.133:8301  alive   client  0.6.0  2         chef
i-d4d0e410      10.52.32.158:8301  alive   client  0.6.0  2         chef
i-6ebb85aa      10.52.32.199:8301  alive   client  0.6.0  2         chef
i-9c6d2945      10.52.22.107:8301  alive   client  0.6.0  2         chef
i-34fb9ef0      10.52.32.139:8301  alive   client  0.6.0  2         chef
i-7ec5a0ba      10.52.32.18:8301   alive   client  0.6.0  2         chef
i-9bdb4342      10.52.22.228:8301  alive   client  0.6.0  2         chef
i-19db43c0      10.52.22.100:8301  alive   client  0.6.0  2         chef
i-014fe1d8      10.42.22.30:8301   alive   client  0.6.0  2         chef
i-989e0941      10.42.22.84:8301   alive   server  0.6.0  2         chef
i-b0f4316a      10.42.42.202:8301  alive   server  0.6.0  2         chef
i-c7296503      10.42.32.34:8301   alive   server  0.6.0  2         chef
i-6a2965ae      10.42.32.57:8301   alive   client  0.6.0  2         chef
i-7af732a0      10.42.42.101:8301  alive   client  0.6.0  2         chef
...add plenty more
```

Thanks in advance for the insight!

**Comment by slackpad** [comment]
Hi @scalp42 yeah this is a little confusing. Here's a list thread that talked about what's going on:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/dGTynOIQ33M/1ioEh-S5DgAJ

> This is correct and sorry it's a little confusing. To make a 0.5.x upgrade easier, we made 0.6 advertise that it speaks version 2 but that it understands version 3. This keeps older versions happy, but when a 0.6 instance sees that another version understands protocol version 3 it will automatically start sending it network coordinates and other 0.6-specific messages. No one will ever claim to speak version 3. 

I'll take this to either update the documentation or make the output of `consul version` a little clearer about the protocol, since several people have been confused about it. Glad to see you upgrade everything to 0.6.0!

**Comment by scalp42** [comment]
@slackpad got it! 

Thanks for the quick answer :smile: 

Closing.

**Comment by slackpad** [comment]
I'll keep this open as a reminder for me to document.

**Comment by slackpad** [comment]
We updated the docs and the version output.
