### ISSUE TITLE
Inbound Peering Control Plane Traffic includes Follower Nodes in Cluster Endpoints

### ISSUE THREAD

**Issue by DanStough** [hashicorp/consul#15338]
#### Overview of the Issue

Peering control plane traffic is established between the respective Leader Servers in peered clusters. When `PeerThroughMeshGateways` is enabled in the Mesh config entry, this traffic can be mistakenly routed to Follower servers on the accepting side because that mesh gateway has all the server addresses in the Envoy endpoint configuration. This doesn't cause an error with peering over mesh gateways because peering is designed so that Follower servers will hang up on dialing requests, and the dialing Leader will retry. 

This is less of a bug and more issues with sub-optimal performance and [dead-code that is not performing as designed](https://github.com/hashicorp/consul/blob/bf0f61a87884d444d472b981099163856658d3ea/agent/xds/endpoints.go#L299-L303). A successful PR will refactor the code to allow only the leader node in the mesh gateway inbound cluster.

#### Reproduction Steps

1. Run ./run.sh to set up a peering between two clusters through mesh gateways ([reference repo](https://github.com/DanStough/consul-scenarios/tree/main/scenario-peering-mesh-gw)). You will also need to manually run the commands after the `exit 0` in the script to complete the peering connection. 
2. Add two servers:
   1. `consul agent -log-level trace -config-file config_dc1-server2.hcl 1>./logs/dc1-server2.log &.`
   1. `consul agent -log-level trace -config-file config_dc1-server3.hcl 1>./logs/dc1-server3.log &.`
1. Observer the mesh gateway has all server gRPC addresses in its cluster endpoints.
  1. `http://localhost:19004/clusters?format=json`

**Comment by DataDavD** [comment]
hey @DanStough I'm gonna try and work on this issue. 

Note, if anyone comes along wanting to work on this/submit PR/etc. feel free. I'm a bit slow right now after moving across the country.

**Comment by DanStough** [comment]
That would be awesome, @DataDavD!  This is not a priority right now, so it's all yours. 

I realized I forgot to include the setup script - I am adding a link back in the original issue.

**Comment by DataDavD** [comment]
@DanStough thank you! Just forewarning you I'll probably be back with some questions as I'm not very familiar with consul....trying to improve my Go while helping the community and getting familiar with consul/HashiCorp software 👍 

thanks again!

**Comment by DataDavD** [comment]
👋 hey, just giving an update. I've been busy during holidays/end of year and didn't get to look into this yet. I may not get to it until end of Jan so if someone comes along and what's to work on this feel free 👍

**Comment by arthurgavazza** [comment]
Hey, anyone working on this? I'm looking for a good issue. I don't know much about consul but I'm eager to learn more and help the community

**Comment by DataDavD** [comment]
Hey I think you should be good to take this. I got sidetracked with work (and life things) and haven't been able to dig into those so plz do 🙌

**Comment by DanStough** [comment]
From https://github.com/hashicorp/consul/pull/17000#issuecomment-1540941847, we decided this issue wasn't appropriate for the `good first issue` label and doesn't have a good ROI to continue with. 

> The original issue is still valid, but thinking through a solution with some other Consul folks, I vastly underestimated the amount of work needed. It's my fault for tagging the issue with the good first issue label, and I apologize if you sunk time in this under that assumption.
>
>For a solution, we need to address two concerns:
>
>Which IP addresses represent a leader? As mentioned in the comment above, this isn't part of the service instance metadata.
Triggering an xDS update when the leader changes position. This requires a new watch in the proxyconfg package.
That said, I'll say it's your call if you'd like to keep working on this issue, but IMHO it isn't worth the effort for the small performance gain. If you're out, I'll close the original issue with a comment to the effect "won't fix right now".
