### ISSUE TITLE
Be more specific about TCP checks in Changelog

### ISSUE THREAD

**Issue by luisbosque** [hashicorp/consul#1536]
Ey guys,

A little bit silly request probably. But it would be nice being more specific in the changelog about the socket check type and highlighting that it's a TCP one.

I've spent some time trying to get TCP check working in 0.5.2 because my "tcp" changelog search didn't return an info. Part of my fault for not looking for "socket".

Cheers

**Comment by slackpad** [comment]
Hi @luisbosque good call! That language originally came from a more general version which supported other socket types but it eventually just became about TCP. Tweaked it in https://github.com/hashicorp/consul/commit/a1b69c6546b17abc3c2a37bfa27a8814beaef704. Thanks!
