### ISSUE TITLE
Any plans to add built in checks besides script, tcp, http?

### ISSUE THREAD

**Issue by jareksm** [hashicorp/consul#1538]
Or the ability to easily extend consul with additional built in system checks.

It's pretty easy to write scripts/programs to check memory, cpu etc and I have wrote few of this programs in go. But it would be nice if there was an API and I could write this checks into Consul itself instead of me running this programs every few seconds.

Another feature request is to add something from nagios world and have a script/check fail pre defined number of times before it turns to warning or critical. Instead of me trying to write this logic into every single script.

Ideally the way I look at it is, if a builtin check that checks available memory and swap runs every 5 seconds and it fails with critical 3 times in a row, it triggers warning, if it does it 5 times in a row, it goes to critical. An ok check resets everything.

It should eliminate or at least limit flip flopping or any temporary issues. I have not looked at the code in consul yet, as my Go level is basic right now.

**Comment by highlyunavailable** [comment]
TTL checks are what you want: https://consul.io/docs/agent/checks.html

A TTL check means that you have to call the Consul API or it will consider the check to be "failed" (a sort of dead man's switch style check.)

The "max_failures" sort of behavior has been requested already in #1208 as well. Currently it doesn't exist, though.

**Comment by slackpad** [comment]
Hi @jareksm I don't think we will add many more check types as scripts allow for basically anything, and it keeps Consul's core simpler and easier to maintain. With TTLs and #1208 covering the other request I'm going to close this one, but please let me know if you still have questions.
