### ISSUE TITLE
Add support to set circuit breaker config and outlier detection config for Ingress Gateway

### ISSUE THREAD

**Issue by shweshi** [hashicorp/consul#15401]
#### Feature Description

I would like to set outlier detection and circuit breaker config in the Ingress Gateway. By default ingress gateway is using the default envoy configuration (because it's not provided explicitly). 

#### Use Case(s)

Ingress gateway is used to accept requests from the outside of service mesh and forwarding the requests to the services inside service mesh.
Consider the following scenario:
--> ingress gateway --> cart-service

Currently after 5 consecutive 5xx (default) the cart-service is ejected by the ingress gateway. It would be useful to provide an option to change this default configuration.

I couldn't find an option to do that.. the escape hatch override options is also not availabel for ingress gateway.. there is an issue about it. (https://github.com/hashicorp/consul/issues/8722)

Is there any other to set these configurations?

**Comment by huikang** [comment]
Consul supports [envoy circuit break config](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking) in its [ingress gateway config entry](https://developer.hashicorp.com/consul/docs/connect/config-entries/ingress-gateway#defaults).

What is the envoy config you need to change the default behavior? Do you have a link to it on the envoy page? Thanks.

**Comment by shweshi** [comment]
@huikang This is the [envoy outlier detection config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto#envoy-v3-api-field-config-cluster-v3-outlierdetection-consecutive-5xx) i want to change. Is there a way to change it in ingress gateway?

**Comment by huikang** [comment]
@shweshi , thanks for the link. I will look into it.
