### ISSUE TITLE
Add fully provisioned cluster demo using Vagrant

### ISSUE THREAD

**Issue by jzohrab** [hashicorp/consul#1540]
The [Getting Started documentation](https://www.consul.io/intro/getting-started/join.html) describes setting up a cluster manually.  It would be nice to also provide a full Vagrant demo that provides the same setup.

Some others have provided [similar examples like this](http://www.andyfrench.info/2015/08/setting-up-consul-cluster-for-testing.html), but it would be good to have these examples as part of the canonical source code, and also one that follows the existing documentation, so that it is a single source of information.  This would also help with tutorials, etc.

I've started this work already in a branch (https://github.com/jzohrab/consul/commits/full_vagrant_demo), but am having some trouble with it.  In that branch, the demo is at `demo/vagrant-cluster-complete/`.  See the README.md in that directory for the two issues I'm stuck with.

**Comment by jzohrab** [comment]
Resolved some troubles in that branch, will try to wrap this up soon and submit a PR.

**Comment by jzohrab** [comment]
Opened PR https://github.com/hashicorp/consul/pull/1566 for this issue.

**Comment by hdeadman** [comment]
It would be really helpful to see a cluster demo with three servers using the bootstrap_expect=3. The older demos I have seen are using one bootstrap=true to get the cluster started and from what I understand you shouldn't have to do that. I am having trouble getting three vagrant VMs to talk to each other over the private host only network. I am binding, advertising and specifying the host network IPs (192.168.33.35-37) for consul every which way (and I have opened all the consul ports for tcp/udp in iptables) but I still get an error where it looks like the servers are trying to talk on the default NAT'd network that is only good for getting out to internet (and not to other VMs).

[ERR] raft: Failed to make RequestVote RPC to 10.0.2.15:8300: dial tcp 10.0.2.15:8300: getsockopt: connection refused. 

Are there issues when boxes have multiple networks?  I might be able to contribute a demo that used vagrant and puppet to provision a consul cluster if I can get it working.

**Comment by jzohrab** [comment]
The PR #1566 does this without the bootstrap expect as I was doing the PR following the existing docs.  I think it would be possible to add another demo with this, but we'd need some extra scripts that get run manually, I think, whereas the PR is a simple "vagrant up" and you're done.  @hdeadman if you post a branch I can look at it as well.

**Comment by v6** [comment]
// , I would be interested in this, too.

**Comment by i0rek** [comment]
We have a vagrant and docker swarm example now: https://github.com/hashicorp/consul/tree/master/demo.
