### ISSUE TITLE
How to update the service tags?

### ISSUE THREAD

**Issue by subchen** [hashicorp/consul#1545]
In [service document](https://consul.io/docs/agent/services.html), that says:
```
The enableTagOverride can optionally be specified to disable the anti-entropy 
feature for this service. If enableTagOverride is set to TRUE then external agents 
can update this service in the catalog and modify the tags. 
```

But I cannot find any api to update a exist service. 

The APIs `agent/service/register` and `catalog/register` will create a new service and cannot update the service.

Then, how to update a service tags?

**Comment by slackpad** [comment]
Hi @subchen you'd use the https://www.consul.io/docs/agent/http/catalog.html#catalog_register API to register the service again with the same information except for the tags. It can definitely be used to update an existing service (it's also what the agents use during anti-entropy to sync up changes).

**Comment by slackpad** [comment]
Please let me know if you have any trouble updating!

**Comment by subchen** [comment]
Thanks for your explanations. 
That's OK for me to update a server using `catalog/register` API although the API looks like only for register.

**Comment by dotw** [comment]
how to reopen this issue? I need an API only update the tags with others untouched

**Comment by cripperzprodigy** [comment]
> how to reopen this issue? I need an API only update the tags with others untouched

similar here.

**Comment by liduan2000** [comment]
> how to reopen this issue? I need an API only update the tags with others untouched

I need this too. Hope they will add this feature
