### ISSUE TITLE
/bin/sh: check-http: command not found

### ISSUE THREAD

**Issue by feythin** [hashicorp/consul#1546]
I install consul with version 0.5.2 and 0.6.0 ; both healthcheck with a  "/bin/sh: check-http: command not found " . where is the check-http command ?  on other server , this is ok . and I check the md5sum of consul binary and it is the same number.

Any suggestion?
thanks in advance~

v1/health/checks/dingding-10000

{
Node: "mesos22",
CheckID: "service:mesos22:mesos-322cbd66-e70a-4a0d-8bf5-61e21d02c7fa-S3.8e22978a-118b-45e7-ab1c-3f99c367e800:10000",
Name: "Service 'dingding-10000' check",
Status: "critical",
Notes: "",
Output: "/bin/sh: check-http: command not found ",
ServiceID: "mesos22:mesos-322cbd66-e70a-4a0d-8bf5-61e21d02c7fa-S3.8e22978a-118b-45e7-ab1c-3f99c367e800:10000",
ServiceName: "dingding-10000",
CreateIndex: 0,
ModifyIndex: 0
}

**Comment by slackpad** [comment]
Hi @feythin can you provide an example of how you are configuring the health check?

**Comment by feythin** [comment]
@slackpad 
so sorry not give the configure informations。
I use consul as the backend registry of registrator .  and my service is in docker container.  So I set the docker start environment with the following settings。
```
SERVICE_10000_CHECK_HTTP=/dingding/track.jsp
SERVICE_10000_CHECK_INTERVAL=15s
SERVICE_10000_CHECK_TIMEOUT=2s
```

**Comment by slackpad** [comment]
@feythin can I see the JSON that you are giving to Consul to configure the check? Thanks!

**Comment by slackpad** [comment]
Hi @feythin I'm going to close this out. If you weren't able to figure out what's going on, I'd suggest asking the registrator folks. It looks like it is somehow registering a script instead of an http check.
