### ISSUE TITLE
Immutably upgrade consul

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/consul#1551]
I want to upgrade a consul cluster using immutable infrastructure methods. As such I have "images" with new consul software installed on them.

The documented upgrade procedure assume that you upgrade a product in-place rather than do it immutably. 

The documented add/remove node procedure is more useful for the immutable upgrade - as such I can easily remove a node, and then add a node back in (or vice versa).

However, according to the documentation, there is no way of telling when a new node is "caught up", other than to compare the last_log_index across a whole cluster to ensure it is the same. However in a highly dynamic environment with many consul updates happening, how are you supposed to do this? Is there an easier way, other than telling if the last_log_index is approximately in the same vicinity as the other nodes? Thanks

**Comment by slackpad** [comment]
Related to https://github.com/hashicorp/consul/issues/1092.

**Comment by shilov** [comment]
@gtmtech what did you end up doing? I'm weighing the same options you mentioned.

**Comment by gtmtech** [comment]
I wrapped ansible around terraform, and used ansible investigatory techniques to work out the maximum last_log_index, and then upgrade each server, and wait to see the last_log_index had crept up to the one previous recorded, before taking out the next. It seems to work fine - I've already rolling released a consul cluster about 50 times now.

What I should do to be even more water-tight though, is to upgrade the server, wait for consul to come online, and then check the max last_log_index across the cluster, and ensure that the new server has surpassed that figure. That would be even better.

I figure this is no worse than stopping a server, upgrading, and then starting it again anyway.

I thought hashicorp were one of the main proponents of immutable infrastructure though, so surprised they dont have more on this in their own productset..

**Comment by slackpad** [comment]
@gtmtech we will look into making this easier, or at least better documenting the process.

**Comment by shilov** [comment]
@gtmtech thanks for the response, much appreciated.

**Comment by kayvonghaffari** [comment]
Quick question: Why use `last_log_index` instead of `commit_index` (or both)? What's the difference between the two? Thanks!

**Comment by slackpad** [comment]
This was added in Consul Enterprise 0.8.0 via https://www.consul.io/docs/guides/autopilot.html#upgrade-migrations and the underlying health API is in open source Consul - https://www.consul.io/docs/guides/autopilot.html#server-health-checking.
