### ISSUE TITLE
Make consul to return internal IP of a service for same-datacenter nodes

### ISSUE THREAD

**Issue by migueleliasweb** [hashicorp/consul#1555]
Explanation: I work in a company that owns a half hundred of small instances at a host provider and some bigger (bare metal) ones at another provider. Some services are hosted among the smaller instances and some on bare metal servers for better reliability.

If I choose to use service discovery I would only get the same ip address no matter which node is asking for it. If some bare-metal node asked for a specific service that runs on the same datacenter, I would be very happy to know that Consul can responde to this node with a internal IP for this service.

Note: The internal network runs over a gigabit connection

**Comment by slackpad** [comment]
Hi @migueleliasweb if they are in the same datacenter from a Consul perspective, how would Consul know when to provide which address, or are you thinking you'd group them into two datacenters? There's a PR in review that might be useful if it's the latter - https://github.com/hashicorp/consul/pull/1547 - this would let you use the configured WAN addresses if you are going DC to DC and the LAN addresses internally.

**Comment by migueleliasweb** [comment]
Hey @slackpad , the idea was all about improving inner-datacenter comunication, you are indeed right.The #1547 PR might solve this.

**Comment by slackpad** [comment]
Closing this out as we shipped WAN address translation in 0.6.4 which should address the request here!
