### ISSUE TITLE
UI node view nodes UI looks bad when you have long host names

### ISSUE THREAD

**Issue by sandywater** [hashicorp/consul#1558]
This is on a retina Mac Book Pro.  The service number gets pushed outside the `ember-view ember-list-item-view`

**Comment by doertedev** [comment]
![bildschirmfoto von 2016-04-22 16-22-44](https://cloud.githubusercontent.com/assets/1579335/14744351/c69c6532-08a6-11e6-97d7-c46330abab96.png)
Servicenames also kinda problematic...

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
