### ISSUE TITLE
consul and atlas integration x509 error

### ISSUE THREAD

**Issue by sboily** [hashicorp/consul#1563]
Hello,

I have this error on my consul, it seems it's new.

[ERR] scada-client: failed to dial: x509: certificate signed by unknown authority

On atlas i can't see my consul.
Running on consul 0.6.0. I migrated from 0.5.2.

Thank you.
Sylvain

**Comment by slackpad** [comment]
Hi @sboily can you try a command like this from that machine to see if openssl can connect:

`openssl s_client -connect scada.hashicorp.com:7223 -tls1_2 -CApath /etc/ssl/certs </dev/null`

There weren't any major SCADA-related changes in 0.6, though Consul keeps that connection open so you may have seen it during the upgrade because it was the first chance to connect in a while.

**Comment by sboily** [comment]
Hello,

I'm running a debian jessie, and the result of the command is :

CONNECTED(00000003)
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/serialNumber=RlUJkxnL21tPDK-hCoN5WyrI6GDuCqiE/OU=GT33562476/OU=See www.rapidssl.com/resources/cps (c)14/OU=Domain Control Validated - RapidSSL(R)/CN=*.hashicorp.com
   i:/C=US/O=GeoTrust, Inc./CN=RapidSSL CA
 1 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
 2 s:/C=US/O=GeoTrust, Inc./CN=RapidSSL CA
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFMzCCBBugAwIBAgIDFPdyMA0GCSqGSIb3DQEBCwUAMDwxCzAJBgNVBAYTAlVT
MRcwFQYDVQQKEw5HZW9UcnVzdCwgSW5jLjEUMBIGA1UEAxMLUmFwaWRTU0wgQ0Ew
HhcNMTQwOTAxMDE0MzQ2WhcNMTYwOTAzMDUzODQyWjCBvjEpMCcGA1UEBRMgUmxV
Smt4bkwyMXRQREstaENvTjVXeXJJNkdEdUNxaUUxEzARBgNVBAsTCkdUMzM1NjI0
NzYxMTAvBgNVBAsTKFNlZSB3d3cucmFwaWRzc2wuY29tL3Jlc291cmNlcy9jcHMg
KGMpMTQxLzAtBgNVBAsTJkRvbWFpbiBDb250cm9sIFZhbGlkYXRlZCAtIFJhcGlk
U1NMKFIpMRgwFgYDVQQDDA8qLmhhc2hpY29ycC5jb20wggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDA1lw0Rm1R9m2RZ01Xnlk7Xa5PAFxUxpU3khbQJzuo
hZufQojbwWhcApEezgGzbw3p6S2BwVx06RPhgwOMAi0t+bAOhbueUKfkR430wUJz
z0Vo8MQz3oMtTiGAr9D1vMootAxIGO5GiTuK0ZvRd3WISDJ3GJbTJnI6pZ08XH/Z
2JrIsIAVtvi2MJ+Zx3U7Oxzp3DZyqZYO9gus+Gg5Q1StrWHYXstZBG8e6GiTnz+r
z2QWy+GsFfwna9+l7JtpD4zlqJIQEttQv7so6N/10fMuVodq+boYSzxaQQdxBH42
SoRUeTzhbn5KXOaX92nU4p5WvmsTjqQf6gMiRxNC+mxZAgMBAAGjggG5MIIBtTAf
BgNVHSMEGDAWgBRraT1qGEJK3Y8CZTn9NSSGeJEWMDAOBgNVHQ8BAf8EBAMCBaAw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMCkGA1UdEQQiMCCCDyouaGFz
aGljb3JwLmNvbYINaGFzaGljb3JwLmNvbTBDBgNVHR8EPDA6MDigNqA0hjJodHRw
Oi8vcmFwaWRzc2wtY3JsLmdlb3RydXN0LmNvbS9jcmxzL3JhcGlkc3NsLmNybDAd
BgNVHQ4EFgQU0kLYyLLhwvXBnfgDhaKGviA0R0MwDAYDVR0TAQH/BAIwADB4Bggr
BgEFBQcBAQRsMGowLQYIKwYBBQUHMAGGIWh0dHA6Ly9yYXBpZHNzbC1vY3NwLmdl
b3RydXN0LmNvbTA5BggrBgEFBQcwAoYtaHR0cDovL3JhcGlkc3NsLWFpYS5nZW90
cnVzdC5jb20vcmFwaWRzc2wuY3J0MEwGA1UdIARFMEMwQQYKYIZIAYb4RQEHNjAz
MDEGCCsGAQUFBwIBFiVodHRwOi8vd3d3Lmdlb3RydXN0LmNvbS9yZXNvdXJjZXMv
Y3BzMA0GCSqGSIb3DQEBCwUAA4IBAQAmT0n41SfRwHJTm9flZEcr5L+AKgRU2J0V
xHlFCN4qUQaWzX3hAPbZ0vv8ub7f1h8gbV8nFVqwpXqPQ2S+YOOjXFPG2L1aoMjD
0/vIoSf7taxJwMjdi6uGCRHbB/gTDqP3ai3PRP1P+i7hpBuL/tHPYGXfyX30GJTu
tZBhBgiW4e86zFhsa7t90WT8hm7Hn1jkQ4j1mD0PQyxRoHjHgZwJKUHipvJzLwCu
/Nvh8ei8Wqv2tU/ib2UXWpuAA6mb3sZk7CmZ9W4Rxw7cq3MkfqdgQXZRMLsWg1lT
RetxJ9KtEOrjiKiaJzUAm9NsTW6FxUZM0P8hvDwzETEfwwky4EIn
-----END CERTIFICATE-----
subject=/serialNumber=RlUJkxnL21tPDK-hCoN5WyrI6GDuCqiE/OU=GT33562476/OU=See www.rapidssl.com/resources/cps (c)14/OU=Domain Control Validated - RapidSSL(R)/CN=*.hashicorp.com
issuer=/C=US/O=GeoTrust, Inc./CN=RapidSSL CA
---
No client certificate CA names sent
---
SSL handshake has read 3690 bytes and written 421 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 46AB88CF296D992288F72F6EEA6A5421920616E8A89E4899771897D81FEF8E3BA2A2347FC70FF4DDA95F7994A4674CF0
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1451998828
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
DONE

**Comment by sboily** [comment]
ok with dpkg-reconfigure ca-certifcates, checked all certificates and it's ok !
Thanks.

**Comment by slackpad** [comment]
Thanks for the update, @sboily. Are you ok to close this one down?

**Comment by sboily** [comment]
Oh yes sorry.

**Comment by slackpad** [comment]
np - thanks!
