### ISSUE TITLE
if we watch a key, what happens when a key is deleted?

### ISSUE THREAD

**Issue by mqliang** [hashicorp/consul#1564]
We could watch a key, but how can I decide the key has been deleted/expired when watch?  For create/modify action, it's not hard to decide.

* `CreateIndex == ModifyIndex`: we get a create action when watch
* `CreateIndex != ModifyIndex ` : we get a modify action when watch

But how can we decide a delete/expired action?

**Comment by slackpad** [comment]
Hi @mqliang if you are using the HTTP API the watch should still work and you'll get a 404 response code if the key is deleted. There's still the X-Consul-Index header in that response so you can continue watching for that key again.

**Comment by mqliang** [comment]
@slackpad Great thanks! Recently we are developing a distribute system using consul as our K/V storage.  

* How about TTL expired? Is it the same as deletion(a 404 response code with X-Consul-Index)?
* Is there any way we can know the previous value if we get a modify/delete/expire action when watch? 

Is there any documentation?

**Comment by slackpad** [comment]
@mqliang for TTL expiration it depends on how your session is set up when you create it (https://www.consul.io/docs/agent/http/session.html). If you set the session's Behavior to "release" then it should clear the session component of the key, making it look like a modify action, leaving the Session field of the key empty when you query it. If you set the Behavior to "delete" it should look like a delete action.

The main documentation for KV is here - https://www.consul.io/docs/agent/http/kv.html. Though if you are making a distributed system you probably can benefit from Consul's built-in lock functionality, take a look at these guides:

* https://www.consul.io/docs/guides/leader-election.html
* https://www.consul.io/docs/guides/semaphore.html

In addition, Consul's Go client API has some pretty nice wrappers that implement these types of operations and provide the watching for you, closing a channel when a lock is lost so it's simple to interface with the rest of your application:

* https://github.com/hashicorp/consul/blob/master/api/lock.go
* https://github.com/hashicorp/consul/blob/master/api/semaphore.go

**Comment by slackpad** [comment]
Sorry I missed your last question. Consul doesn't keep any history of values for KV entries so you'd have to manage that in some other way.

**Comment by mqliang** [comment]
Great thanks for your patient explanation.
