### ISSUE TITLE
PUT method error

### ISSUE THREAD

**Issue by kassymhan** [hashicorp/consul#15686]
agent.http: Request error: method=PUT url=/v1/session/renew/session_id from=127.0.0.1:57160 error="Session id"

**Comment by jkirschner-hashicorp** [comment]
Just double-checking, was `session_id` in that URL the literal string `session_id`? Or a hexademical UUID for the session (such as `/v1/session/renew/adf4238a-882b-9ddc-4a9d-5b6758e4159e`)?

Which version of Consul are you using?

Does the session appear if you call the List Sessions endpoint? https://developer.hashicorp.com/consul/api-docs/session#list-sessions

**Comment by Hanmask21** [comment]
session id was hexademical

**Comment by Hanmask21** [comment]
@jkirschner-hashicorp  
There isn't  id
Answer on session/list :
`[{"ID":"4c9837fe-eea1-04d9-df86-d12d7fdda9b2","Name":"","Node":"ax51-host167","LockDelay":15000000000,"Behavior":"delete","TTL":"900s","NodeChecks":["serfHealth"],"ServiceChecks":null,"Cr
eateIndex":87311077,"ModifyIndex":87311077},{"ID":"4de5f375-66c9-f84f-e108-6a850002b09b","Name":"","Node":"ax161-host13","LockDelay":15000000000,"Behavior":"delete","TTL":"900s","NodeChec
ks":["serfHealth"],"ServiceChecks":null,"CreateIndex":87942738,"ModifyIndex":87942738}]#`
