### ISSUE TITLE
Darkmode for Consul WebGUI

### ISSUE THREAD

**Issue by ncecere** [hashicorp/consul#15726]
#### Feature Description

Darkmode or Dark theme for consul Web UI

#### Use Case(s)

Save vision of users when accessing web ui in dimly lit rooms.  while this may sound funny it is still true.

**Comment by shweshi** [comment]
+1 for the feature.

 While consul brings dark mode. I am building an alternate consul UI with Dark Mode and some other useful features such as node deregistration which is not available in consul UI and JSON view of different configuration.
Try it out https://github.com/shweshi/consul-power-ui
