### ISSUE TITLE
DNS output should be in the Authoritative Section for all queries except the zone

### ISSUE THREAD

**Issue by kdhingra307** [hashicorp/consul#15739]
Hi, I have been trying to delegate consul agent on sub-domain using bind9 as shown below

example.net (bind 9*) ---> sub.example.net (bind9) ----> consul.sub.example.net(consul agent)

While trying to set this up, i constantly was getting `formatt` on bind9 while my subdomain routing on bind9* has been working fine without any issue. 

If we query consul agent for soa record,
```
dig ns.consul. @127.0.0.1 -p 8600 soa

; <<>> DiG 9.10.6 <<>> ns.consul. @127.0.0.1 -p 8600 soa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25753
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ns.consul.			IN	SOA

;; ANSWER SECTION:
consul.			0	IN	SOA	ns.consul. hostmaster.consul. 1670521497 3600 600 86400 0
```

For instance, querying google produces the following output

```
; <<>> DiG 9.10.6 <<>> ns.google.com soa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23325
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ns.google.com.			IN	SOA

;; AUTHORITY SECTION:
google.com.		10800	IN	SOA	ns1.google.com. dns-admin.google.com. 493557487 900 900 1800 60

;; Query time: 421 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
```

This following altercation breaks the bind9 as it is not able to validate the authority and returns the query of `xyz.consul.sub.example.net` to the primary nameserver. 

Bind9 reports the following error
```
DNS format error from 127.0.0.1#8600 resolving ns.consul.sub.example.net/SOA for client 127.0.0.1#40994: reply has no answer
FORMERR resolving 'ns.consul.example.net/SOA/IN': 127.0.0.1#8600
```

## P.S.
> I am new to consul and dns, so i am particularly not sure if this actually is a bug or coincidence as moving the soa output from answer section to authority section fixed the bind error and delegation worked successfully. If it actually is a bug, i would like to provide a patch for it as i have it running (just need to add one condition.. like the soa output should be in answer section only if query is zone name)

   ```
; <<>> DiG 9.10.6 <<>> google.com soa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53962
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 9

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	SOA

;; ANSWER SECTION:
google.com.		60	IN	SOA	ns1.google.com. dns-admin.google.com. 493557487 900 900 1800 60

;; AUTHORITY SECTION:
google.com.		45506	IN	NS	ns3.google.com.
google.com.		45506	IN	NS	ns4.google.com.
google.com.		45506	IN	NS	ns1.google.com.
google.com.		45506	IN	NS	ns2.google.com.

```

#### Reproduction Steps

- Try to perform delegation at the sub-domain level ( and trying to access it through root name server)

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
`consul info` is taking too long on my system. 

Consul v1.15.0-dev
Revision 692a6fdec+CHANGES
Build Date 2022-12-03T18:17:06Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

```

</details>

### Operating system and Environment details

- linux, amd64

**Comment by max19931** [comment]
Is your zone configuration:

zone "consul.sub.example.net" IN {
  type forward;
  forward only;
  forwarders { 127.0.0.1 port 8600; };
};

Also your service xyz are hosted under xyz.service.consul not just xyz.consul.

**Comment by kdhingra307** [comment]
@max19931 yes, the services are hosted as `xyz.service.consul`

i tried both configuration
- using forwarding
- running consul on port 53

**Comment by kdhingra307** [comment]
Closing as no longer using consul
