### ISSUE TITLE
Official Windows Production Support?

### ISSUE THREAD

**Issue by donaldquixote** [hashicorp/consul#1576]
Many seem to be using Consul on Windows, but both the documentation and the service startup stdout state outright that you should not run Consul on Windows in production.

My memory is hazy, but I recall a conversation somewhere stating that the only roadblock to this was that due diligence has not yet been done in the testing realm. Is that the case or is there something else going on?

Is official windows production support on the roadmap?

**Comment by ryanuber** [comment]
@donaldquixote it's mostly correct that Consul hasn't been battle-tested as much on Windows as it has been on Linux (or at least not that we have seen). The Consul agents shouldn't have much trouble running in client-only mode on Windows hosts. The main concern is around the servers, which need to maintain the state of the whole cluster. We generally still recommend that all Consul servers should be run on Linux, but there have been significant improvements to the state store and on-disk storage in Consul that might alleviate many of the issues faced previously, though we haven't dedicated cycles to verifying that yet.

We do want Consul to run reliably on Windows, and that support will likely be at an official capacity by the time 1.0 is out. We just aren't there yet.

Let me know if you have any other questions!

**Comment by donaldquixote** [comment]
Thanks @ryanuber. Is there a ballpark ETA for 1.0? I know there is plenty to keep everyone busy. I'm just gathering as much info as I can to present to my managers.

Thanks again.

**Comment by mitchellh** [comment]
@donaldquixote 1.0 will likely be 2016. I would say that thisshouldn't hold you back though, 0.6 is in use by some extremely large organizations and we're highly confident in it.

**Comment by donaldquixote** [comment]
Thanks @mitchellh. I personally have confidence in it, but we have a unique case of needing to straddle both the cloud and on-prem worlds, so we will either be redistributing Consul with our software or asking customers to install and run it on-prem, and we have a requirement to target Windows and Linux. Even with a list of large adopters, I can't imagine the customer being happy with "Windows is not recommended as a Consul server" printing every time a server goes up.

Anyway, thanks again, and keep it up. I'm excited to start working with Vault over Consul. :)

**Comment by cosborne83** [comment]
As a small addition to this, it would also be nice if as part of official Windows production support, Consul could be run natively as a Windows service (i.e. _without_ having to resort to using e.g. [nssm](https://github.com/hashicorp/consul/issues/758))

**Comment by donaldquixote** [comment]
Hi again @ryanu, @mitchellh. I following up to see if official Windows support for server is still likely to land in 2016. Our use cases keep piling up :)

Thanks.

**Comment by rajinders** [comment]
@ryanu, @mitchellh   I have a client which is mostly windows. We are using AWS. We use packer, terraform already. We have under utilized windows servers I can use to start using Consul and Vault. I used chocolatey packages created by you guys to install consul as a service. I see a warning about lack of production support for consul on windows. A guide for consul on windows along with official support will help for sure.

**Comment by slackpad** [comment]
Sorry for the delay in rolling the change out, but that "not recommended" message will go away in the next release of Consul - it's already removed in master.

**Comment by FrankHassanabad** [comment]
Good to see the "not recommend" message going away!
 
There is some battle testing and bugs coming out of windows for v0.6.4 at the company I'm with at the moment.

One bug that is detrimental to longevity of running on windows is this boltdb issue:
https://github.com/hashicorp/consul/issues/2203

**Comment by daviddodsworth** [comment]
Just wondering what is the current state of Windows support for the Consul Agent running in Server mode?  Is this a supported and stable configuration for v0.7?  

Is 1.0 still coming out this year?

@mitchellh @ryanuber @slackpad

**Comment by mitchellh** [comment]
@daviddodsworth I'll let others comment on Windows support with server mode.

1.0 is no longer likely coming out this year as we're working on some important stability improvements we've found from our biggest users (really, really massive scale) and we want to see those in production for some time. It is still a high priority target though. :)

**Comment by MarkPieszak** [comment]
It looks like consul has Windows support now correct? It has the install file for Windows etc.

I'm noticing that even when I add it to my %PATH% ( `C:\consul.exe` ) in my case, I just dropped it right on the C: drive. It still shows up as an unrecognized command.

I'm running on Windows7 on this machine currently, is that potentially the problem?

**Comment by JohanKlijn** [comment]
Is a release date of Consul 1.0 already available which includes support for running consul as a service on Windows?

**Comment by slackpad** [comment]
We don't yet have a firm date for 1.0, but we removed the warning about Windows when Consul starts in version 0.7.0. There are lots of folks running Consul on Windows in production, and there aren't any known instabilities on Windows. This has been much easier to ensure now that Consul is pure Go (since 0.6.0), and doesn't rely on a special build that's compiled on Windows - we use Go's cross compiler to target Windows just like any other platform.
