### ISSUE TITLE
Github latest should point to current latest not most recently released

### ISSUE THREAD

**Issue by Rumbles** [hashicorp/consul#15787]
#### Overview of the Issue

Your current latest release on github points to https://github.com/hashicorp/consul/releases/tag/v1.12.8 which is the most recently released version of consul, but the actual latest should be https://github.com/hashicorp/consul/releases/tag/v1.14.2 as it has been for the last few weeks as that is the most recent release on the current release. Unless I am missing something and you are recommending people downgrade?

#### Reproduction Steps

N/A it's a github config issue

**Comment by jkirschner-hashicorp** [comment]
By default, Github assumes "latest" is by release date rather than versioning. I just manually marked 1.14.2 as latest. I'll follow up with the team to check if there's some easy process change when we have a new release to keep the actual latest release marked "latest".
