### ISSUE TITLE
Specifying -ui without -ui-dir doesn't enable 301 redirect

### ISSUE THREAD

**Issue by justinclayton** [hashicorp/consul#1578]
Now that this is actually possible, sounds like that redirect should be switching on the value of -ui, not -ui-dir. PR hopefully coming soon to resolve.

**Comment by BrianHicks** [comment]
We're running into this as well. Here's a minimal config file to demonstrate the problem:

```
{
    "bootstrap_expect": 1,
    "server": true,
    "ui": true,
    "data_dir": "tmp/consul",
    "log_level": "INFO"
}
```
