### ISSUE TITLE
Failed to Apply CA Operation: operation=set-roots-config

### ISSUE THREAD

**Issue by reskin89** [hashicorp/consul#15824]
#### Overview of the Issue

We are using Vault as a CA, all has been well up until a few days ago, the envoy proxies are failing to validate the CA, and we are experiencing an error in our server logs:
```
Dec 16, 2022 @ 17:37:53.505 connect.ca: updated root certificates from primary datacenter
Dec 16, 2022 @ 17:37:53.566 2022-12-16T17:37:53.566Z [WARN]  agent.fsm: Failed to apply CA operation: operation=set-roots-config
```

We're seeing this error roughly every 15 minutes

#### Reproduction Steps

Unsure at this time, but it has caused a mesh wide failure of communications

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 3
	services = 2
build:
	prerelease =
	revision = 3cb6eeed
	version = 1.10.2
consul:
	acl = enabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 135
	max_procs = 1
	os = linux
	version = go1.16.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 99
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1064363
	members = 123
	query_queue = 0
	query_time = 3323
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 94542765
	version = 1.12.4
	version_metadata =
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 3
	leader = false
	leader_addr = REDACTED:8300
	server = true
raft:
	applied_index = 50453721
	commit_index = 50453721
	fsm_pending = 0
	last_contact = 13.915293ms
	last_log_index = 50453721
	last_log_term = 599
	last_snapshot_index = 50443835
	last_snapshot_term = 599
	latest_configuration = [{Suffrage:Voter ID:fb271478-4fbd-4b94-bcec-6dd44ac225d1 Address:REDACTED:8300} {Suffrage:Voter ID:9476a523-5a9c-4af1-8068-1370412e2c11 Address:96.103.24.142:8300} {Suffrage:Voter ID:e883f188-8807-496a-8147-b51d4c0462cb Address:REDACTED:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 599
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 3167
	max_procs = 2
	os = linux
	version = go1.18.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 99
	failed = 2
	health_score = 0
	intent_queue = 0
	left = 223
	member_time = 1064364
	members = 347
	query_queue = 0
	query_time = 3323
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 860
	members = 9
	query_queue = 0
	query_time = 2
```

</details>

### Operating system and Environment details

Running on EC2 in AWS, Amazon Linux 2

### Log Fragments

```
Dec 16, 2022 @ 17:37:53.505 connect.ca: updated root certificates from primary datacenter
Dec 16, 2022 @ 17:37:53.566 2022-12-16T17:37:53.566Z [WARN]  agent.fsm: Failed to apply CA operation: operation=set-roots-config
```

**Comment by jkirschner-hashicorp** [comment]
Hi @reskin89,

A few follow-up questions that may help here:

- What is Vault version (for the Vault cluster with the PKI secrets engines Consul is using)?
- Can you share your connect CA configuration from both the primary datacenter and the secondary datacenter that's experiencing the mesh communication failure?
- Are you experience the mesh communication failure in a single secondary datacenter? Or multiple/all secondary datacenters?
- Is mesh communication working in the primary datacenter?
- Have you changed anything in your connect CA configuration recently?

**Comment by reskin89** [comment]
I'm checking on all of this.

* communication in the primary datacenter is operational.
* communication failures seem to be in secondary datacenters only at the moment
* we have not changed our connect CA config recently 
* I am waiting on our team that manages our vault to let me know the version, and if it was updated recently
* Connect configs below

connect config from primary:
```json
"connect": {
        "ca_config": {
            "PrivateKeyBits": 2048,
            "PrivateKeyType": "rsa",
            "address": "https://REDACTED:443",
            "intermediate_pki_path": "pki/sed_smesh_inter_prod_us-east-2",
            "root_pki_path": "pki/sed_smesh",
            "token": "REDACTED"
        },
        "ca_provider": "vault",
        "enabled": true
    }
```

secondary:
```json
"connect": {
        "ca_config": {
            "PrivateKeyBits": 2048,
            "PrivateKeyType": "rsa",
            "address": "https://REDACTED:443",
            "intermediate_pki_path": "pki/sed_smesh_inter_prod_us-east-1",
            "root_pki_path": "pki/sed_smesh",
            "token": "REDACTED"
        },
        "ca_provider": "vault",
        "enabled": true
    }
```

**Comment by reskin89** [comment]
Vault Enterprise 1.11.5

It was upgraded a month ago and I'm wondering if that messed with the CA

**Comment by jkirschner-hashicorp** [comment]
Refer to this [known issue using Vault 1.11+ as Consul's CA provider](https://support.hashicorp.com/hc/en-us/articles/11308460105491) as soon as possible. Let me know if it seems to be the likely cause of your observations.

We recently released fixes for that known issue on Consul 1.12 - 1.14. I see that you're on Consul 1.12.4. The fix is in Consul 1.12.8. If you can't upgrade yet, and that known issue is the cause, the article above includes a workaround you could use in the interim.

**Comment by jkirschner-hashicorp** [comment]
I'm not sure whether the WARN message `agent.fsm: Failed to apply CA operation: operation=set-roots-config` is related to the known issue I linked. But the mention of "Vault Enterprise 1.11.5" and mesh communication issues makes me suspect that's possible. The main thing to check (as described in that linked article) is the remaining intermediate CA lifetime compared to its `IntermediateCertTTL` (which defaults to 1 year in your case because your config doesn't override it).

**Comment by reskin89** [comment]
we're right around that time frame too, I'm looking into it and am thinking this is the issue as well.

**Comment by reskin89** [comment]
I believe we can close this.  I'll re-open if this doesn't fix it but looks to be the root cause as best as I can tell.
