### ISSUE TITLE
7080 over TCP but UDP probes failed, network may be misconfigured

### ISSUE THREAD

**Issue by kcmvp** [hashicorp/consul#15823]
run a very sample from local mac os

2022/12/17 01:09:47 [ERR] memberlist: Failed to send gossip to [::]:7080: write udp [::]:7082->[::]:7080: sendto: no route to host
2022/12/17 01:09:47 [ERR] memberlist: Failed to send gossip to [::]:7081: write udp [::]:7082->[::]:7081: sendto: no route to host
2022/12/17 01:09:47 [WARN] memberlist: Was able to connect to [fe80::6900:e9e1:706a:4806]:7080 over TCP but UDP probes failed, network may be misconfigured
2022/12/17 01:09:48 [ERR] memberlist: Failed to send UDP ping: write udp [::]:7082->[::]:7080: sendto: no route to host
2022/12/17 01:09:48 [ERR] memberlist: Failed to send indirect UDP ping: write udp [::]:7082->[::]:7081: sendto: no route to host
2022/12/17 01:09:48 [DEBUG] memberlist: Stream connection from=[::1]:57472
2022/12/17 01:09:48 [DEBUG] memberlist: Failed to join 127.0.0.1:7081: read tcp 127.0.0.1:57471->127.0.0.1:7081: i/o timeout
2022/12/17 01:12:28 [WARN] memberlist: Was able to connect to [fe80::6900:e9e1:706a:4806]:7080 over TCP but UDP probes failed, network may be misconfigured

**Comment by jkirschner-hashicorp** [comment]
That error message usually indicates that a Consul agent's LAN gossip port was reachable over TCP, but not UDP. Gossip preferentially uses UDP, only using TCP as a fallback.

Have you checked whether local UDP traffic is allowed to those ports?

**Comment by jkirschner-hashicorp** [comment]
Since I haven't heard back yet, I'm closing this for now. Feel free to re-open!

**Comment by kcmvp** [comment]
run into this issue again. I used a customize port 5848, and got below message

5848 over TCP but UDP probes failed, network may be misconfigured


I test the port with nc:  it works.
nc -vnzu 127.0.0.1 5848
Connection to 127.0.0.1 port 5848 [udp/*] succeeded!

**Comment by anurag-appperfect** [comment]
sane issue for me as well, does anyone able to resolve it?
