### ISSUE TITLE
Support yml?

### ISSUE THREAD

**Issue by pigping88** [hashicorp/consul#15853]
Support yml? such as:
```
spring:
    cloud:
       ....
```

**Comment by jkirschner-hashicorp** [comment]
Hi @pigping88,

Can you provide more information on where you'd like Consul to support YAML that it doesn't currently, and your motivation for that change?

Consul agent configuration supports JSON and HCL. Service mesh configuration entries support JSON, HCL, and Kubernetes YAML.

**Comment by jkirschner-hashicorp** [comment]
Hi @pigping88,

I haven't heard back from you yet, so I'm closing this for now until clarification is provided. We can re-open once clarification is provided. Thanks!
