### ISSUE TITLE
can use like a.b.com dns lookup？

### ISSUE THREAD

**Issue by renrenfree** [hashicorp/consul#1587]

**Comment by slackpad** [comment]
Hi @renrenfree can you add a little more detail about what you are looking to do? You can configure the domain that Consul responds to using https://www.consul.io/docs/agent/options.html#_domain.

**Comment by renrenfree** [comment]
Thank you @slackpad . My issue is that "I want to use consul as a dns server but not with 'service' or 'node' in a full domain" https://www.consul.io/docs/agent/dns.html  .  How to config ?  
I want to use a domain like 'www.github.com'

**Comment by shilov** [comment]
`service` and `node` have special meaning to consul. There's no way of accomplishing what you're asking without modifying the source, not a great idea. If you're really intent on doing this, I would look at dnsmasq or bind first.

**Comment by slackpad** [comment]
Hi @renrenfree, @shilov is correct that there's currently no way to configure Consul to support other name formats. You could look at using consul-template to populate your BIND or dnsmasq config (or even a /etc/hosts file).
