### ISSUE TITLE
GRPC TLS port missing in doc

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/consul#15894]
Hello guys,

From the [documentation](https://developer.hashicorp.com/consul/docs/install/ports) the `grpc tls port 8503` is missing. I only found it in the [release](https://github.com/hashicorp/consul/releases/tag/v1.14.0) and fortunately [here](https://developer.hashicorp.com/consul/docs/agent/config/config-files#grpc_tls_port).

**Comment by dttung2905** [comment]
Hi @jkirschner-hashicorp I could help with adding the missing doc :pray:
