### ISSUE TITLE
Consul doesn't build on SmartOS

### ISSUE THREAD

**Issue by yruss972** [hashicorp/consul#159]
I tried building Consul on a SmartMachine in Joyent Public Cloud. This is my first time working with go software so please excuse me if I'm missing something that should be obvious.

SmartOS build       joyent_20131120T074720Z
Image               base64 14.1.0
go version devel +f8b50ad4cac4 Mon Apr 21 17:00:27 2014 -0700 + solaris/amd64 
go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="solaris"
GOOS="solaris"
GOPATH="/root/go"
GORACE=""
GOROOT="/opt/local/go"
GOTOOLDIR="/opt/local/go/pkg/tool/solaris_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0"
CXX="g++"
CGO_ENABLED="0"

 # go get github.com/hashicorp/consul
 # github.com/armon/gomdb
github.com/armon/gomdb/mdb.c:39 6c: No such file or directory: sys/types.h

 # cd /root/go/src/github/hashicorp/consul
 # make
--> Installing build dependencies
--> Running go fmt
command/force_leave_test.go
command/agent/agent_endpoint_test.go
command/agent/catalog_endpoint_test.go
command/agent/dns_test.go
command/agent/health_endpoint_test.go
command/agent/kvs_endpoint_test.go
command/agent/local_test.go
command/agent/rpc_client_test.go
command/agent/status_endpoint_test.go
command/agent/ui_endpoint_test.go
consul/catalog_endpoint_test.go
consul/client_test.go
consul/health_endpoint_test.go
consul/internal_endpoint_test.go
consul/kvs_endpoint_test.go
consul/leader_test.go
consul/server_test.go
testutil/wait.go
--> Installing dependencies to speed up builds...
 # github.com/armon/gomdb
../../armon/gomdb/mdb.c:39 6c: No such file or directory: sys/types.h
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

The sys/types.h file exists in /usr/include
 # ls -l /usr/include/sys/types.h
-rw-r--r-- 1 root bin 18137 Nov 20 10:08 /usr/include/sys/types.h

I tried modifying GOGCCFLAGS to include "-I/usr/include" but "go env" wouldn't recognize the environment variable or else it reset it :?

I change CGO_ENABLED to 1 and tried make again but got an error which baffles me:

 # export CGO_ENABLED=1
 # make
--> Installing build dependencies
--> Running go fmt
--> Installing dependencies to speed up builds...
 # runtime/cgo
Undefined                       first referenced
 symbol                             in file
_cgo_sys_thread_start               $WORK/runtime/cgo/_obj/gcc_util.o
ld: fatal: symbol referencing errors. No output written to $WORK/runtime/cgo/_obj/_cgo_.o
collect2: error: ld returned 1 exit status
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MerlinDMC** [comment]
As a sidenote:

For a golang toolchain on Illumos/SmartOS with cgo wesolows has been doing some great work:
https://github.com/wesolows/golang-old (1.4)
https://github.com/wesolows/golang (1.5)
(You'll need a SmartOS host that is from December 2014 or newer because of some fixes in the system includes)

Those repositories have cgo support patched in and work well so far. (I'm running consul on SmartOS)

**Comment by jim80net** [comment]
Awesome. Thanks for the update MerlinDMC!

**Comment by klynton** [comment]
With the release of [2014Q4](http://www.perkin.org.uk/posts/pkgsrc-2014Q4-lts-signed-packages-and-more.html) Consul will now build on the base* boxes.

**Comment by cmacrae** [comment]
Has anyone had any luck building Consul on recent SmartOS base images?  
CGO is now supported on SmartOS and Go 1.5.1 is in Joyent's official repo's:
```
$ go version
go version go1.5.1 solaris/amd64
```
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="solaris"
GOOS="solaris"
GOPATH=""
GORACE=""
GOROOT="/opt/local/go"
GOTOOLDIR="/opt/local/go/pkg/tool/solaris_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
I'm writing an Ansible role to deploy/orchestrate Consul, and my primary development platform is SmartOS. When trying to build, as instructed in the README, the following errors are thrown:
```
# github.com/fsouza/go-dockerclient/external/github.com/Sirupsen/logrus
../../fsouza/go-dockerclient/external/github.com/Sirupsen/logrus/text_formatter.go:28: undefined: IsTerminal
# github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/system
../../fsouza/go-dockerclient/external/github.com/docker/docker/pkg/system/stat_unsupported.go:16: s.Mtimespec undefined (type *syscall.Stat_t has no field or method Mtimespec)
# github.com/mitchellh/cli
../../mitchellh/cli/ui.go:79: undefined: terminal.IsTerminal
../../mitchellh/cli/ui.go:81: undefined: terminal.ReadPassword
```

**Comment by slackpad** [comment]
Hi @cmacrae if you are building the latest master then there's no longer a CGO dependency, but it looks like there's no Solaris support for those terminal functions (see https://github.com/golang/go/issues/13085, which links to several issues). I think at the current time you'd have to do some surgery on those dependencies in order to build on this platform. For the CLI dependency you could probably remove the `IsTerminal` branch of that `if` in ui.go since Consul doesn't use that. For Docker I'm less sure, though you could take out Docker check support from Consul's command/agent/check.go (and unit test) since that's the only place it is used. Sorry this is ugly at the moment, but it looks like things are still being sorted out on the Go side.

**Comment by cmacrae** [comment]
Thanks @slackpad! Managed to get it to build with your tips :+1:   
I'll break this out into an optional step in my Ansible role using a patch from the changes I made to get it to build.  

I'll likely be doing automated builds, and host a zipped archive for the amd64 binary for Solaris (more specifically, illumos/SmartOS) systems on my personal domain: http://cmacr.ae/consul/solaris_amd64.zip
Mostly for my own convenience, but, others can grab it too, if they so wish :)

**Comment by doublerebel** [comment]
@cmacrae thanks for this, very helpful.

I would like to get Consul [into pkgsrc](https://pkgsrc.joyent.com/docs/creating/), I see [hashicorp/vault](https://github.com/hashicorp/vault) is [already present](http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/devel/hs-vault/README.html).  Is there anyone here who can help fasttrack the process?

**Comment by cmacrae** [comment]
That'd be great! @jperkin would be the best person to talk to regarding
this. But I'm not sure how "ethical" the patches are that I'm using.

**Comment by benjamin-bergia** [comment]
I would also be interested by a package for smartos.
By the way @cmacrae I gave a try to your binary and it works seamlessly on 15.3.0.
Thank you for sharing.

**Comment by cmacrae** [comment]
No problem @benjamin-bergia :)
I could make a pkgsrc port for it, and submit it for review. But, like I say, I'm not sure how reasonable the patches are.

**Comment by dekobon** [comment]
Is it possible to get an official downloadable binary available on the Consul site for SmartOS before it gets added to pkgsrc?

**Comment by cmacrae** [comment]
@dekobon I doubt it, SmartOS is not an officially supported platform for Consul

**Comment by doublerebel** [comment]
@cmacrae I've spoken to my contact at Joyent, we may be able to get Consul in sooner than later.

**Comment by cmacrae** [comment]
@doublerebel Awesome news!

**Comment by dekobon** [comment]
@cmacrae Who's your contact at Joyent? I'm also with Joyent.

**Comment by dekobon** [comment]
@doublerebel - sorry the previous comment was for you.

**Comment by doublerebel** [comment]
@dekobon Oh excellent!  Robby Andrews.  Mentioned that some of you were interested in Consul inclusion, so he was right :)

**Comment by Chewyrobbo** [comment]
@doublerebel have you hung out on #consul on IRC yet?

**Comment by doublerebel** [comment]
@Chewyrobbo no, just #smartos and #joyent.  Just joined #consul now. Thanks!

**Comment by mamash** [comment]
@cmacrae Can you share the patches, any way you're comfortable with? I'm with Joyent and working on pkgsrc.

**Comment by cmacrae** [comment]
@mamash Sure :) Just on my way into the office at the moment, I'll share them once I'm in

**Comment by cmacrae** [comment]
@mamash So, patches are necessary to both [mitchellh/cli](https://github.com/mitchellh/cli) & [hashicorp/consul](https://github.com/hashicorp/consul).  

Here are the patch files, pretty much just stripping stuff out:  
- [mitchellh_cli_solaris.patch](https://gist.github.com/cmacrae/1343683fd0be35e733dd)
- [hashicorp_consul_solaris.patch](https://gist.github.com/cmacrae/ddcadaf8517b929af84b)

**Comment by MerlinDMC** [comment]
@cmacrae looks like your patch to cli will not ask for input via stdin anymore if `secret=true`. You removed the bit that does read the input without replacing it.

**Comment by cmacrae** [comment]
@MerlinDMC Thanks for pointing this out - these patches were chucked together quickly one evening after work, and I haven't had time to review them properly. Given the fact that this now seems to be moving toward to an official pkgsrc port at Joyent, I trust that those involved will address any issues posed by my hasty patching ;)

**Comment by MerlinDMC** [comment]
https://gist.github.com/MerlinDMC/57d6043067e0bad8e2af

I'm not happy with the `ReadPassword()` ... and I hate the fact that the IOCTL syscalls are used everywhere and not implemented on Illumos but this patches $GOPATH/src tree does provide a consul binary that can run as an agent at least - I didn't test much more.

**Comment by doublerebel** [comment]
@MerlinDMC thanks for this, I'm able to get hashicorp/vault almost built as well.  Looking now at patching both vault and consul to use [bgentry/speakeasy](https://github.com/bgentry/speakeasy) for cross-platform getpasswd support.

**Comment by mamash** [comment]
I was able to get a crude pkgsrc package done with the above patches, but it still requires one of the patches applied manually.

In order to land in pkgsrc though, I will need to break out all the 30+ Go dependencies into their separate packages, because pkgsrc doesn't like build-time source fetching and the embedded deps files would clash over PLIST entries with other Go packages as support for such grows in pkgsrc.

**Comment by doublerebel** [comment]
@mamash that's a great start, thanks for the help.  I'm also working on vault and consul-template, which have similar and related dependencies.  Is there anything we can do about the projects' structure to make the builds simpler?  When compiled, the end result is just one binary that needs one config file.

**Comment by slackpad** [comment]
Hey all - it looks like @jen20 got a CLI change merged yesterday that fixes the syscall issue:

https://github.com/mitchellh/cli/pull/25

And the Docker client must have gotten fixed upstream:

https://twitter.com/jen20/status/684450871606939648

I'll take this and add solaris to the list of built flavors.

**Comment by cmacrae** [comment]
Awesome! Thanks @slackpad & @jen20 :+1:

**Comment by mamash** [comment]
Thanks guys! I updated the pkgsrc definition for Consul, it will show up in the standard Joyent 2015Q4 build (soon).

**Comment by cmacrae** [comment]
Excellent, thanks @mamash!
