### ISSUE TITLE
Register node with /catalog endpoint. not able to find nodes when using /v1/health/service/<service> or /v1/catalog/service/<service>

### ISSUE THREAD

**Issue by mg03** [hashicorp/consul#1590]
HI

I am using /v1//catalog/register to register say service "svc123" and two nodes with their ips in consul.

Now when I use /v1/health/service/svc123  - i get no nodes in the response. I get an empty list

I thought of using /v1/catalog/service/svc123 - even here I get no nodes in the response. same as above - empty list

The issue is I cannot use consul agent . No consul agents are being installed ( dont know why)

Given above constraint, is there a way to register a service with it nodes using the /v1/catalog/register endpoint and then use a endpoint to get the list of nodes registered with the service? Is there such an endpoint?

Regards

**Comment by slackpad** [comment]
Hi @mg03 can you provide some examples of the registration requests you are doing? If I can see how you are interfacing with Consul we should be able to figure out what's going on.

This use of Consul should be possible, though it's highly recommended to run Consul agents on each machine. With agents they manage many of the details for you, like checking the health of node and automatically keeping the catalog up to date.

**Comment by mg03** [comment]
Hi James

I am using the python client for consul.

For example , im doing the following to test:
import consul
conn = consul.Consul(host="172.31.10.8",port="8500",token="6678179e-3972-58e3-2ca5-ca4715d77134")
svc = {"Service": "svctestwatch", "ID": "svc123"}
check1={"Node": "node1", "CheckID": "service:svc123","Name": "Redis health check","Notes": "Script based health check","Status": "passing", "ServiceID": "svc123"}
conn.catalog.register("node1","1.2.3.4",service=svc,check=check1) <----this returns true and the ui shows node registered
check2={"Node": "node2", "CheckID": "service:svc123","Name": "Redis health check","Notes": "Script based health check","Status": "passing", "ServiceID": "svc123"} 
conn.catalog.register("node2","5.6.7.8",service=svc,check=check2) <------ <----this returns true and the ui shows node registered

i,s = conn.catalog.service("svc123")
print s   <---- This is an empty array , this should give me the nodes in the service

**Comment by slackpad** [comment]
@mg03 sorry for the late reply on this one :-( Did you figure out what was happening here?

**Comment by mg03** [comment]
no , since then we have upgraded consul multiple times so i think we are good :)
