### ISSUE TITLE
Get services by multiple tags

### ISSUE THREAD

**Issue by luisbosque** [hashicorp/consul#1594]
Hi,

A service can have multiple tags.
Also, as documented in https://www.consul.io/docs/agent/http/catalog.html#catalog_service it's possible to get the list of services filtered by a tag. 
Are there plans to allow filtering that search by multiple tags?

**Comment by slackpad** [comment]
Hi @luisbosque - closing this as a dup of https://github.com/hashicorp/consul/issues/294 - please take a look at that issue for more context, specifically https://github.com/hashicorp/consul/issues/294#issuecomment-170177259. Thanks!
