### ISSUE TITLE
Unable to start from backup

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/consul#1596]
After making a snapshot of a 0.5.2 cluster, I am unable to start a new 0.6.1 cluster with the same data directory (snapshotted, and restored to a new disk).

Here's the directory structure:

```
/data # tree .
.
├── checkpoint-signature
├── lost+found
├── raft
│   ├── peers.json
│   ├── raft.db
│   └── snapshots
│       ├── 4922-689021-1452684429613
│       │   ├── meta.json
│       │   └── state.bin
│       └── 4922-697217-1452701949422
│           ├── meta.json
│           └── state.bin
├── serf
│   ├── local.keyring
│   ├── local.snapshot
│   ├── remote.keyring
│   └── remote.snapshot
└── tmp
    └── state295659803
        ├── data.mdb
        └── lock.mdb
```

command:

```
/bin/consul agent -config-dir=/etc/consul/config -encrypt=xxx  -log-level=trace
==> WARNING: LAN keyring exists but -encrypt given, using keyring
==> WARNING: WAN keyring exists but -encrypt given, using keyring
==> WARNING: Expect Mode enabled, expecting 3 servers
==> Starting Consul agent...
Killed
```

config:

```
cat /etc/consul/config/config.json 
{
  "server": true,
  "bootstrap_expect": 3,

  "client_addr": "0.0.0.0",
  "data_dir": "/data",
  "ui_dir": "/ui",
  "skip_leave_on_interrupt": true,
	"dns_config": {
		"allow_stale": false
	},

  "ca_file": "/etc/consul/ssl/ca.cert",
  "cert_file": "/etc/consul/ssl/consul.cert",
  "key_file": "/etc/consul/ssl/consul.key",
  "verify_incoming": true,
  "verify_outgoing": true
}
```

```
/bin/consul version
Consul v0.6.1
Consul Protocol: 3 (Understands back to: 1)
```

Is there some way to validate the data, see if it got corrupted somehow?

**Comment by slackpad** [comment]
Hi @JeanMertz is there any more information about why it's dying (possibly getting OOM-killed if you look in syslog)? We've seen one user with a huge amount of data have trouble because Consul can't page to disk like it used to be able to - https://github.com/hashicorp/consul/issues/1579.

**Comment by JeanMertz** [comment]
ouch, that was indeed it. Our Kubernetes pod was set to a 256MB limit (which worked on 0.5.2). Now that I've increased it to 512MB, things work as expected.

Sad face for it taking so long for me to post this, as that would've saved me a couple of hours :disappointed: 

Thank you for helping out @slackpad!

**Comment by slackpad** [comment]
@JeanMertz np and glad you got things working again!
