### ISSUE TITLE
Document that consul-k8s-control-plane >=1.0.0 requires gRPC port in Release notes

### ISSUE THREAD

**Issue by bondido** [hashicorp/consul#15998]
#### TODO 

We should document that consul-k8s 1.0.x and above requires gRPC port to be enabled in the release notes. 

#### From consul-k8s issue (#1826)
Hi,
I run consul-k8s on kubernetes cluster with external (outside of kubernetes) consul servers - just to provide simple k8s services discoverability with consul.

Syncer connects to consul API using HTTP protocol.

After upgrading from version 0.49.2 to version =>1.0.0 consul-k8s-control-plane is no longer able to connect to "consul side".

I know that the parameter that we used until 0.49.2 (-http-addr) is no longer available, so I tried to switch to **-addresses** and **-http-port** pair but it seems like syncer ignores **-http-port** - not trying to use HTTP to connect to consul API and keep using TCP port 0 (Consul servers: addresses=[**127.0.0.1:0**]).

```
consul-k8s-control-plane sync-catalog -addresses='127.0.0.1' -http-port='8500' -use-tls=false -to-k8s=false -to-consul=true
[INFO]  consul-server-connection-manager: trying to connect to a Consul server
[INFO]  consul-server-connection-manager: discovered Consul servers: addresses=[127.0.0.1:0]
[INFO]  consul-server-connection-manager: current prioritized list of known Consul servers: addresses=[127.0.0.1:0]
[ERROR] consul-server-connection-manager: connection error: error="failed to switch to Consul server \"127.0.0.1:0\": target sub-connection is not ready (state=TRANSIENT_FAILURE)"
```

If I provide -grpc-port parameter (and have GRPC enabled on consul servers) - syncer starts connecting to consul OK (Consul servers: addresses=[**127.0.0.1:8502**])

```
consul-k8s-control-plane sync-catalog -addresses='127.0.0.1' -http-port='8500' -grpc-port="8502" -use-tls=false -to-k8s=false -to-consul=true
[INFO]  consul-server-connection-manager: trying to connect to a Consul server
[INFO]  consul-server-connection-manager: discovered Consul servers: addresses=[127.0.0.1:8502]
[INFO]  consul-server-connection-manager: current prioritized list of known Consul servers: addresses=[127.0.0.1:8502]
[INFO]  consul-server-connection-manager: connected to Consul server: address=127.0.0.1:8502
```

Is there any way to force syncer to use HTTP instead of GRPC protocol to connect to consul API?
Or maybe I need to switch to GRPC (unfortunately I don't have it turned on by default in my consul servers configuration) ?

Or maybe -http-port should be enough to use HTTP and I should report it as a bug? I didn't find any mention of gRPC requirement in documentation nor in `consul-k8s-control-plane sync-catalog --help` output.

**Comment by webmutation** [comment]
Hello, I recently run into an issue where a deployment from a year ago is running fine with just port 8500, but now on a new deployment with consul image 1.15.2 and chart version 1.1.1 it does not work to connect to the externalServers with just 8500

Can you clarify if gRPC can be disabled altogether in the latest versions of Consul, or if it s a requirement that both http 8500 
and gRPC 8502 are open, or is there a way to disable it and use only HTTP

**Comment by gusse** [comment]
I too ran into this... Not really nice that it isn't mentioned in any of the docs clearly. Wasted half a day because of this 🙈
