### ISSUE TITLE
Github latest label applied to older release

### ISSUE THREAD

**Issue by Rumbles** [hashicorp/consul#16093]
I automatically attempt to track the `latest` label of consul and I had a PR today that downgrades my consul releases from `1.14.3` which was marked as latest until yesterday, to `1.12.9`

However, since`1.12.9` was released, `1.14.4` has been released, which is, I believe, the real `latest` release

Is there a reason why the latest label is not tracking the most recent branch, or the most recently released version?

**Comment by jkirschner-hashicorp** [comment]
By default, Github assumes "latest" is by release date rather than versioning. I just manually marked 1.14.4 as latest. I'll follow up with the team to check if there's some easy process change when we have a new release to keep the actual latest release marked "latest".

**Comment by jkirschner-hashicorp** [comment]
Related to https://github.com/hashicorp/consul/issues/15787
