### ISSUE TITLE
consul ignoring recursor setting

### ISSUE THREAD

**Issue by DanielDent** [hashicorp/consul#1615]
I have tried using both the -recursor command line flag and the recursors file. I have another service discovery layer that is provided by a DNS server on 127.0.0.1 which I'd like to use to bootstrap the consul nodes. But consul doesn't seem to want to use it.

I get lines like the following in my logs:
"    2016/01/15 12:42:14 [WARN] memberlist: Failed to resolve host2.local: lookup host2.local on 8.8.8.8:53: no such host
    2016/01/15 12:42:14 [WARN] memberlist: Failed to resolve host3.local: lookup host3.local on 8.8.8.8:53: no such host"

**Comment by slackpad** [comment]
Hi @DanielDent the recursor sessions are used when Consul is acting as a DNS server but those errors look like Consul itself is having a hard time resolving those addresses. I think this might be a problem with the way DNS is configured on the host where Consul is running.
