### ISSUE TITLE
Binary Distribution License

### ISSUE THREAD

**Issue by donaldquixote** [hashicorp/consul#1616]
We would like to redistribute Consul and Vault to customers for on-prem deployments. The license attached to your source has some statements saying this is allowed, but our legal team says that the license document only covers the source, and since no license document is included with the binaries you provide, we don't know what license covers them. Can we redistribute binaries built by Hashicorp, or will we need to build them ourselves? Can you include license documents in the archive files you provide on your website?

Thanks.

**Comment by slackpad** [comment]
Hi @donaldquixote - you are right that the current license covers binaries you build. I'll check with folks here and see how we cover binaries we build.

**Comment by donaldquixote** [comment]
Thanks @slackpad. Any new information on this?

**Comment by armon** [comment]
@donaldquixote The license in the repository covers the binaries we provide as well. We are not planning on including the license in the archives themselves.
