### ISSUE TITLE
Add gossip grouping for segmented network topologies

### ISSUE THREAD

**Issue by horsehay** [hashicorp/consul#1618]
### Overview

It's been brought up several times that users with segmented network topologies have problems with Consul due to the gossip protocol expecting all members to exist in a flat, open network topology so that they can all communicate freely. The suggested solution is to use the Data Center specifier to separate segments, even though they are not separate Data Centers. This is a  workaround, but is a good framework for adding another layer of supporting segmentation by groups.
### Details

A configuration for "gossip-group(s)" would be available. When specified, gossip members would only attempt to perform health checks on members with matching gossip groups.

Consul servers would essentially be members of every group. This would not affect services, or other consul functionality.

**Comment by cruatta** [comment]
Serious thumbs up for this. What I'd like to see are some configuration options in Consul to list what CIDR ranges the node is allowed to gossip with and then that node ignores gossip traffic from all other nodes not in those ranges.

At first glance, this feature seems like something that would need to be implemented at the Serf level and then exposed to Consul. Should an issue be filed there as well?

**Comment by c4milo** [comment]
Yes! In companies with a lot of teams and apps this makes a lot of sense.

**Comment by deltaroe** [comment]
Just to throw another idea out there. I'm not sure the gossip protocol is strictly necessary for consul to function and having an option to turn it off entirely could also solve this issue. 

As best as I understand it the serf layer serves three functions: discovering the consul servers, publishing some events such as server election changes, and to cross monitor agents. 

Having a full mesh was a non-starter in our environment so we've gone to essentially writing our own agent that makes the registration api calls against the consul servers. It would have been nice to still be able to utilize the consul agent itself and all the tooling already built around it without having to have the gossip protocol. 

A method of finding the consul servers will still be needed (we're going to use DNS, an ELB and the ACL system to secure it), but it would also be entirely possible for the consul server value to be just a seed and the other consul servers could be discovered (and maybe cached for later process startups) via that seed. 

This would put more load on the consul servers and cross agent monitoring would be lost (maybe replaced with a server based TTL?), but that may be fine.

**Comment by c4milo** [comment]
@deltaroe, it does failure detection too, as far as I know, and it is core to the whole distributed architecture. I wouldn't recommend trying to avoid it. Are you sure Consul is the tool you need?

**Comment by slackpad** [comment]
The gossip protocol integration goes pretty deep in Consul, so I don't think we'd ever completely disable it. In addition to the things listed by @deltaroe it's part of `consul exec`, it's how we manage protocol versioning and communication between agents, cross-monitoring of agents is tied into how sessions work, etc. I don't have a time frame at the moment, but we are looking into some possible options for supporting different network topologies within the same cluster.

**Comment by bfgoodrich** [comment]
I realize that it's less efficient, but is it possible to create an lightweight proxy that would allow the server to communicate on behalf of clients that are not able to communicate directly to another client (but both communicate to the same consul server?)

**Comment by slackpad** [comment]
This was added in Consul Enterprise in version 0.8.0 at the WAN level via "network areas" - see https://www.consul.io/docs/guides/areas.html.

**Comment by jadametz** [comment]
@slackpad We're happy to see this functionality added in `0.8.0`. Does the `post-0.9` tag indicate that this functionality will be making its way to the open source version at that time?

**Comment by slackpad** [comment]
Hi @jadametz we don't have plans to release this as open source at this time. The post-0.9 tag meant that we were planning on implementing this after the 0.9.x series but we moved it up to 0.9.3.

**Comment by slackpad** [comment]
This has been implemented for 0.9.3 as a feature in Consul Enterprise. Please see https://www.consul.io/docs/guides/segments.html for details.
