### ISSUE TITLE
Feature request: specify IP range(s) to use for binding

### ISSUE THREAD

**Issue by DanielDent** [hashicorp/consul#1620]
-bind - .... "By default, this is "0.0.0.0", meaning Consul will use the first available private IP address."

It would be nice to have an option such as -bind-ranges where users can specify the CIDRs for interfaces which are acceptable to bind to.

With some SDN implementations, it's common to have multiple private IP ranges available on a node. But only some of those interfaces will be on a network which is reachable by all the other nodes in the cluster. Having this configuration option would avoid the need to create a pre-startup script which does introspection of the node to identify an appropriate bind address.

**Comment by ryanuber** [comment]
There is a related discussion in Nomad here: https://github.com/hashicorp/nomad/pull/223. The TL;DR is that it may be more consistent to allow binding to a named interface, though we are still thinking about the best solution.

**Comment by DanielDent** [comment]
Sorry I missed that issue in my search. I'll jump in on that thread. Thanks.

**Comment by DanielDent** [comment]
Oh, that issue was on nomad, that's why I missed it. I guess this issue is equally applicable to both projects.

**Comment by llevar** [comment]
+1 for this. Also please support interface name instead of address.

**Comment by sean-** [comment]
@DanielDent / @llevar : Please give the latest code in `master` a twirl.  The syntax for supporting IP addresses or getting the first "usable" IP address on an interface is included below and can be passed to any address parameter within Consul (e.g. `-bind` or `bind_addr`, or any other `*_addr`-like parameter):

```
-bind='{{ GetInterfaceIP "eth0" }}'
-bind='{{ GetAllInterfaces | include "network" "10.0.0.0/8" }}'
```

There is now a configurable template language for examples and docs) behind this that you can use to create a customizable heuristic that should allow you to get whatever it is that you need from your environment when using an immutable image (see [hashicorp/go-sockaddr/template](https://godoc.org/github.com/hashicorp/go-sockaddr/template) and [cmd/sockaddr](https://github.com/hashicorp/go-sockaddr/tree/master/cmd/sockaddr#sockaddr-eval).
