### ISSUE TITLE
consul lock doesn't preserve arguments containing spaces

### ISSUE THREAD

**Issue by grddev** [hashicorp/consul#1621]
For example, `consul lock ls "my file"` will execute `ls my file`, rather than `ls "my file"`. This can be worked around by escaping the arguments one more time `consul lock ls "\"my file\""`. It seems difficult to change this behavior (in a backwards compatible manner) at this point, but I still think the problem is worth pointing out.

**Comment by slackpad** [comment]
Closing per https://github.com/hashicorp/consul/pull/1845#issuecomment-230582637.
