### ISSUE TITLE
api.Client in consul/api should be an interface, not a struct

### ISSUE THREAD

**Issue by avishai-ish-shalom** [hashicorp/consul#1622]
Making api.Client an interface rather than a struct will help with testing programs that use consul/api.
Of course, same applies to Catalog, etc.

**Comment by blalor** [comment]
Yep.  I end up generating my own mocks when I write code using the Consul API.  https://github.com/bluestatedigital/riemann-consul-receiver/tree/master/consul-mocks

**Comment by avishai-ish-shalom** [comment]
Changing api.Client to interface will break all programs using consul/api since `*api.Client` will have to change to `api.Client`. We should probably add newly named interfaces and transition to them while still supporting old API. @armon ?

**Comment by slackpad** [comment]
Hi @avishai-ish-shalom we'd definitely have to do this in a phased manner to avoid breaking folks. Will take a look at how much effort this is.

**Comment by blalor** [comment]
If implemented, I'd like to see the interface implementation extended to the various methods of api.Client, like ACL(), Agent(), etc.

**Comment by magiconair** [comment]
I've commented on the topic in https://github.com/hashicorp/consul/pull/2799#issuecomment-298303009. Looking forward to some feedback since this affects this issue as well.

**Comment by magiconair** [comment]
Closing per https://github.com/hashicorp/consul/pull/2799#issuecomment-298419581
