### ISSUE TITLE
Locked Key is overwritten when call to PUT /v1/kv/<key> has no session value

### ISSUE THREAD

**Issue by ctx0104** [hashicorp/consul#1623]
Hi,

Good day. I'm running version 0.6.2. 

When I set a key with a lock, the lock can be ignored and the value of the key is replaced when I make another call to set with a blank session. 

Example:
1) curl -XPUT http:/localhost/v1/session/create ---> "sessionID"
2) curl -XPUT http://localhost/v1/kv/test?acquire="sessionID" -d 'donteraseme'
3) curl -XPUT http://localhost/v1/kv/test -d 'erased'

The third call has a blank session but it still replaces the value of the locked key. I think I remember that on prior versions, a locked key cannot be overwritten unless the same sessionID is used.

Am I misremembering this? Is this intended behavior or is this a bug?  

Any help/info would be much appreciated. Thanks.

**Comment by slackpad** [comment]
Hi @ctx0104 this is the intended behavior and things have been this way in previous versions of Consul (https://www.consul.io/docs/internals/sessions.html):

> To be clear, this locking system is purely advisory. There is no enforcement that clients must acquire a lock to perform any operation. Any client can read, write, and delete a key without owning the corresponding lock. It is not the goal of Consul to protect against misbehaving clients.

So you have to use the locking primitives in the proper ways in order to protect the integrity of the keys.

The only recent change to locking behavior came in 0.6.0:

> A KV lock acquisition operation will now allow the lock holder to update the key's contents without giving up the lock by doing another PUT with `?acquire=<session>` and providing the same session that  is holding the lock. Previously, this operation would fail.

Hope that helps!

**Comment by ctx0104** [comment]
Got it. Thanks!
