### ISSUE TITLE
Add embedded Lua to Consul

### ISSUE THREAD

**Issue by avishai-ish-shalom** [hashicorp/consul#1625]
Adding embedded Lua to Consul will allow:
* Custom prepared queries, e.g. fallback to another service
* Low latency updates by eliminating read-update cycles
* Custom endpoints allowing views over stored data, reducing the number of HTTP queries (e.g. when using consul-template)

**Comment by balexx** [comment]
+1

**Comment by ebuchman** [comment]
sounds like you are proposing the idea of "smart contracts", as they are known in the world of blockchains, especially ethereum. problem is, if lua computations are going through consensus, we have to use a strictly deterministic subset of lua else consensus could fail

**Comment by avishai-ish-shalom** [comment]
I suggest we start with read only mode and not provide any guarantees. just run the lua code server side and return the results. should be good enough for most use cases. the next step would be to add guarantees (modify index, etc)

**Comment by marenzo** [comment]
+1

**Comment by slackpad** [comment]
Hi @avishai-ish-shalom - thanks for opening an issue. We don't have any plans to add a Lua (or different) embedded interpreter at this time. We've been adding some super basic static query capability via [prepared queries](https://www.consul.io/docs/agent/http/query.html), but that's much easier to reason about vs. a full in-core script interpreter. This would be a major increase in complexity for Consul's core, and we have nearer-term things we'd like to work through first. Having scripting for data views would be pretty neat, I agree, but this isn't something we can support right now :-)
