### ISSUE TITLE
Binay version for Solaris Intel 64 bits

### ISSUE THREAD

**Issue by ofbizbrazil** [hashicorp/consul#1627]
Hi all,

I am trying to execute the binary version of Consul into my Solaris, but I got several addresses errors on its execution.

Is there any binary version for Intel hardware? Please my Solaris info:
```
System = SunOS
Release = 5.10
KernelID = Generic_150401-24
Machine = i86pc
```

Log error:
```
bash-3.2$ ./consul
runtime: address space conflict: map(0xc820000000) = 0xfffffd7ffef4e000
fatal error: runtime: address space conflict

runtime stack:
runtime.throw(0xde3220, 0x1f)
        /opt/go/src/runtime/panic.go:527 +0x99 fp=0xfffffd7fffdff238 sp=0xfffffd7fffdff220
runtime.sysMap(0xc820000000, 0x100000, 0x0, 0x11ae278)
        /opt/go/src/runtime/mem_bsd.go:81 +0x139 fp=0xfffffd7fffdff278 sp=0xfffffd7fffdff238
runtime.mHeap_SysAlloc(0x118e280, 0x100000, 0x1185e14)
        /opt/go/src/runtime/malloc.go:426 +0x160 fp=0xfffffd7fffdff2f8 sp=0xfffffd7fffdff278
runtime.mHeap_Grow(0x118e280, 0x8, 0x0)
        /opt/go/src/runtime/mheap.go:628 +0x63 fp=0xfffffd7fffdff350 sp=0xfffffd7fffdff2f8
runtime.mHeap_AllocSpanLocked(0x118e280, 0x1, 0x4642ca)
        /opt/go/src/runtime/mheap.go:532 +0x5de fp=0xfffffd7fffdff3a8 sp=0xfffffd7fffdff350
runtime.mHeap_Alloc_m(0x118e280, 0x1, 0xfffffd0000000015, 0xfffffd7fffdff400)
        /opt/go/src/runtime/mheap.go:425 +0x1b5 fp=0xfffffd7fffdff3d8 sp=0xfffffd7fffdff3a8
runtime.mHeap_Alloc.func1()
        /opt/go/src/runtime/mheap.go:484 +0x41 fp=0xfffffd7fffdff408 sp=0xfffffd7fffdff3d8
runtime.systemstack(0xfffffd7fffdff428)
        /opt/go/src/runtime/asm_amd64.s:278 +0xc1 fp=0xfffffd7fffdff410 sp=0xfffffd7fffdff408
runtime.mHeap_Alloc(0x118e280, 0x1, 0x10000000015, 0x411058)
        /opt/go/src/runtime/mheap.go:485 +0x63 fp=0xfffffd7fffdff458 sp=0xfffffd7fffdff410
runtime.mCentral_Grow(0x1196ef8, 0x0)
        /opt/go/src/runtime/mcentral.go:190 +0x93 fp=0xfffffd7fffdff4c0 sp=0xfffffd7fffdff458
runtime.mCentral_CacheSpan(0x1196ef8, 0x1186dc0)
        /opt/go/src/runtime/mcentral.go:86 +0x4d4 fp=0xfffffd7fffdff508 sp=0xfffffd7fffdff4c0
runtime.mCache_Refill(0xfffffd7fff04f000, 0x15, 0x413528)
        /opt/go/src/runtime/mcache.go:118 +0xd8 fp=0xfffffd7fffdff540 sp=0xfffffd7fffdff508
runtime.mallocgc.func2()
        /opt/go/src/runtime/malloc.go:614 +0x2b fp=0xfffffd7fffdff560 sp=0xfffffd7fffdff540
runtime.systemstack(0xfffffd7fffdff5f8)
        /opt/go/src/runtime/asm_amd64.s:278 +0xc1 fp=0xfffffd7fffdff568 sp=0xfffffd7fffdff560
runtime.mallocgc(0x180, 0xd0e6e0, 0x0, 0x800000000)
        /opt/go/src/runtime/malloc.go:615 +0x88e fp=0xfffffd7fffdff638 sp=0xfffffd7fffdff568
runtime.newobject(0xd0e6e0, 0x11862c0)
        /opt/go/src/runtime/malloc.go:763 +0x42 fp=0xfffffd7fffdff660 sp=0xfffffd7fffdff638
runtime.malg(0x8000, 0x1186600)
        /opt/go/src/runtime/proc1.go:2196 +0x27 fp=0xfffffd7fffdff698 sp=0xfffffd7fffdff660
runtime.mpreinit(0x1186dc0)
        /opt/go/src/runtime/os3_solaris.go:189 +0x1f fp=0xfffffd7fffdff6b0 sp=0xfffffd7fffdff698
runtime.mcommoninit(0x1186dc0)
        /opt/go/src/runtime/proc1.go:114 +0x109 fp=0xfffffd7fffdff6f8 sp=0xfffffd7fffdff6b0
runtime.schedinit()
        /opt/go/src/runtime/proc1.go:57 +0x82 fp=0xfffffd7fffdff740 sp=0xfffffd7fffdff6f8
runtime.rt0_go(0xfffffd7fffdff778, 0x1, 0xfffffd7fffdff778, 0x0, 0x0, 0x1, 0xfffffd7fffdff980, 0x0, 0xfffffd7fffdff989, 0xfffffd7fffdff9a0, ...)
        /opt/go/src/runtime/asm_amd64.s:109 +0x144 fp=0xfffffd7fffdff748 sp=0xfffffd7fffdff740
```
Tks,

**Comment by slackpad** [comment]
Hi @ofbizbrazil - is this an official binary from https://releases.hashicorp.com/consul/0.6.3/ or from some place else? Now that Consul is 100% pure Go it should be easier to tweak the build settings if your platform is slightly different than our standard build.

**Comment by ofbizbrazil** [comment]
Yes, I downloaded the file consul_0.6.3_solaris_amd64.zip from official site and I got this error.

Is there any version for Intel version?

Tks,

**Comment by slackpad** [comment]
That should be Intel but it's 64-bit. I'm not super well-versed in Solaris but is there any chance you are on a 32-bit machine?

**Comment by ofbizbrazil** [comment]
no, it's a 64 bits version as you can see in my first post. 

Have you compiled for a sparc or intel version your binary?

**Comment by ofbizbrazil** [comment]
no, it's a 64 bits version as you can see in my first post. 

Have you compiled for a sparc or intel version your binary?

**Comment by ofbizbrazil** [comment]
no, it's a 64 bits version as you can see in my first post. 

Have you compiled for a sparc or intel version your binary?

**Comment by ofbizbrazil** [comment]
no, it's a 64 bits version as you can see in my first post. 

Have you compiled for a sparc or intel version your binary?

**Comment by ofbizbrazil** [comment]
no, it's a 64 bits version as you can see in my first post. 

Have you compiled for a sparc or intel version your binary?

**Comment by ofbizbrazil** [comment]
no, it's a 64 bits version as you can see in my first post. 

Have you compiled for a sparc or intel version your binary?

**Comment by jen20** [comment]
Hi, could you post the output of `isainfo -kv`? Your initial post shows a 32 bit processor. The released binaries for Consul are for 64-bit intel architectures.

**Comment by slackpad** [comment]
Hi @ofbizbrazil - were you able to check if you were on 64-bit?

**Comment by ofbizbrazil** [comment]
Yes, I am. Please see console output:
```
bash-3.2$ isainfo -kv
64-bit amd64 kernel modules
```

**Comment by ofbizbrazil** [comment]
I tried to install again, and got the same error:

See log:
> bash-3.2$ ./consul
> runtime: address space conflict: map(0xc820000000) = 0xfffffd7ffef4e000
> fatal error: runtime: address space conflict
> 
> runtime stack:
> runtime.throw(0xde3220, 0x1f)
>         /opt/go/src/runtime/panic.go:527 +0x99 fp=0xfffffd7fffdff238 sp=0xfffffd7fffdff220
> runtime.sysMap(0xc820000000, 0x100000, 0x0, 0x11ae278)
>         /opt/go/src/runtime/mem_bsd.go:81 +0x139 fp=0xfffffd7fffdff278 sp=0xfffffd7fffdff238
> runtime.mHeap_SysAlloc(0x118e280, 0x100000, 0x1185e14)
>         /opt/go/src/runtime/malloc.go:426 +0x160 fp=0xfffffd7fffdff2f8 sp=0xfffffd7fffdff278
> runtime.mHeap_Grow(0x118e280, 0x8, 0x0)
>         /opt/go/src/runtime/mheap.go:628 +0x63 fp=0xfffffd7fffdff350 sp=0xfffffd7fffdff2f8
> runtime.mHeap_AllocSpanLocked(0x118e280, 0x1, 0x4642ca)
>         /opt/go/src/runtime/mheap.go:532 +0x5de fp=0xfffffd7fffdff3a8 sp=0xfffffd7fffdff350
> runtime.mHeap_Alloc_m(0x118e280, 0x1, 0xfffffd0000000015, 0xfffffd7fffdff400)
>         /opt/go/src/runtime/mheap.go:425 +0x1b5 fp=0xfffffd7fffdff3d8 sp=0xfffffd7fffdff3a8
> runtime.mHeap_Alloc.func1()
>         /opt/go/src/runtime/mheap.go:484 +0x41 fp=0xfffffd7fffdff408 sp=0xfffffd7fffdff3d8
> runtime.systemstack(0xfffffd7fffdff428)
>         /opt/go/src/runtime/asm_amd64.s:278 +0xc1 fp=0xfffffd7fffdff410 sp=0xfffffd7fffdff408
> runtime.mHeap_Alloc(0x118e280, 0x1, 0x10000000015, 0x411058)
>         /opt/go/src/runtime/mheap.go:485 +0x63 fp=0xfffffd7fffdff458 sp=0xfffffd7fffdff410
> runtime.mCentral_Grow(0x1196ef8, 0x0)
>         /opt/go/src/runtime/mcentral.go:190 +0x93 fp=0xfffffd7fffdff4c0 sp=0xfffffd7fffdff458
> runtime.mCentral_CacheSpan(0x1196ef8, 0x1186dc0)
>         /opt/go/src/runtime/mcentral.go:86 +0x4d4 fp=0xfffffd7fffdff508 sp=0xfffffd7fffdff4c0
> runtime.mCache_Refill(0xfffffd7fff04f000, 0x15, 0x413528)
>         /opt/go/src/runtime/mcache.go:118 +0xd8 fp=0xfffffd7fffdff540 sp=0xfffffd7fffdff508
> runtime.mallocgc.func2()
>         /opt/go/src/runtime/malloc.go:614 +0x2b fp=0xfffffd7fffdff560 sp=0xfffffd7fffdff540
> runtime.systemstack(0xfffffd7fffdff5f8)
>         /opt/go/src/runtime/asm_amd64.s:278 +0xc1 fp=0xfffffd7fffdff568 sp=0xfffffd7fffdff560
> runtime.mallocgc(0x180, 0xd0e6e0, 0x0, 0x800000000)
>         /opt/go/src/runtime/malloc.go:615 +0x88e fp=0xfffffd7fffdff638 sp=0xfffffd7fffdff568
> runtime.newobject(0xd0e6e0, 0x11862c0)
>         /opt/go/src/runtime/malloc.go:763 +0x42 fp=0xfffffd7fffdff660 sp=0xfffffd7fffdff638
> runtime.malg(0x8000, 0x1186600)
>         /opt/go/src/runtime/proc1.go:2196 +0x27 fp=0xfffffd7fffdff698 sp=0xfffffd7fffdff660
> runtime.mpreinit(0x1186dc0)
>         /opt/go/src/runtime/os3_solaris.go:189 +0x1f fp=0xfffffd7fffdff6b0 sp=0xfffffd7fffdff698
> runtime.mcommoninit(0x1186dc0)
>         /opt/go/src/runtime/proc1.go:114 +0x109 fp=0xfffffd7fffdff6f8 sp=0xfffffd7fffdff6b0
> runtime.schedinit()
>         /opt/go/src/runtime/proc1.go:57 +0x82 fp=0xfffffd7fffdff740 sp=0xfffffd7fffdff6f8
> runtime.rt0_go(0xfffffd7fffdff778, 0x1, 0xfffffd7fffdff778, 0x0, 0x0, 0x1, 0xfffffd7fffdff980, 0x0, 0xfffffd7fffdff989, 0xfffffd7fffdff9a0, ...)
>         /opt/go/src/runtime/asm_amd64.s:109 +0x144 fp=0xfffffd7fffdff748 sp=0xfffffd7fffdff740

**Comment by lfreeman** [comment]
I have same problem on the Solaris server

isainfo -kv
64-bit amd64 kernel modules

**Comment by ofbizbrazil** [comment]
Is possible to compile the source code to Solaris 10?

**Comment by lfreeman** [comment]
I don't sure if Go is ported to Solaris 10.
[](https://golang.org/doc/go1.3#solaris)

**Comment by ofbizbrazil** [comment]
Hi guys,  did you get any news about it?

**Comment by ofbizbrazil** [comment]
Hi guys,  did you get any news about it?

**Comment by slackpad** [comment]
Ah interesting - I couldn't find any definitive documentation on Go's support for Solaris 10 but given your link that seems like the problem (even though that's an older version of Go). I found this old thread that looked like someone is working on it, but it didn't seem like it got finished - https://groups.google.com/forum/#!topic/golang-nuts/L0-c65zZM6Q. I don't think there's much we can do on our side for this one - you could try building Consul with Go 1.6 (and we will have an official build soon that uses this version of Go).

**Comment by slackpad** [comment]
We will continue to try newer versions of Go, but there's nothing we can do in Consul for this.

**Comment by jen20** [comment]
To clarify (I believe it has been done on the downloads page now) - the port of Go was done by Joyent and is to Illumos, _not_ to Solaris. Regrettably when upstreaming it the Go team picked the wrong name. Consul works correctly on Illumos-derived operating systems, but it is unlikely to work on Solaris, especially older revisions.
