### ISSUE TITLE
API dependency vulnerability: GO-2023-1571

### ISSUE THREAD

**Issue by davissp14** [hashicorp/consul#16329]
#### Overview of the Issue
There's a vulnerability warning coming from the `golang.org/x/net` dependency specified within the API package.

Vulnerability reference:
https://pkg.go.dev/vuln/GO-2023-1571

Go mod reference:
https://github.com/hashicorp/consul/blob/main/api/go.mod#L42

**Comment by david-yu** [comment]
This was addressed in https://github.com/hashicorp/consul/pull/16263, and will be released in 1.15.0, 1.14.x, and 1.13.x. Thank you.
