### ISSUE TITLE
Broken link in Consul Connect Overview documentation page

### ISSUE THREAD

**Issue by chefgs** [hashicorp/consul#16332]
#### Overview of the Issue

- Consul connect overview documentation page has broken link for the below documentation page for `Getting Started With Consul for Kubernetes`
- Getting `page not found` while clicking the link

---

#### Reproduction Steps

Steps to reproduce this issue,

1. Open the Consul Connect overview [page](https://developer.hashicorp.com/consul/docs/connect)
2. Navigate to section [Getting started with Consul Service Mesh](https://developer.hashicorp.com/consul/docs/connect#getting-started-with-consul-service-mesh) 
3. Click on the link [Getting Started With Consul Service Mesh for Kubernetes](https://developer.hashicorp.com/consul/tutorials/gs-consul-service-mesh?utm_source=docs/service-mesh-deploy)

**Comment by blake** [comment]
Hi @chefgs, this issue seems to be resolved although I'm not yet sure what PR resolved the issue. Can you confirm whether this link is now working for you?

**Comment by chefgs** [comment]
@blake Yes, this issue has been resolved now, and I could navigate to "Get Started with Consul on Kubernetes" documentation link.
