### ISSUE TITLE
Consul UI K/V store is not visible in Microsoft Edge browser

### ISSUE THREAD

**Issue by StefanScherer** [hashicorp/consul#1633]
I'm using Consul UI on Win10/Win2016TP4 in have problems using the key/value tab there.
## Microsoft IE 11

<img width="1155" alt="ie11" src="https://cloud.githubusercontent.com/assets/207759/12448122/46bda978-bf74-11e5-93ce-b05a6629bcb5.png">
## Microsoft Edge

Opening the same KV in Edge shows nothing.

<img width="1082" alt="edge" src="https://cloud.githubusercontent.com/assets/207759/12448277/2fdd672e-bf75-11e5-806f-70c3c6484e20.png">

Adding another key just shows this key in the edit field, but does not appear on the left.

<img width="1086" alt="edgeanother" src="https://cloud.githubusercontent.com/assets/207759/12448326/79bca814-bf75-11e5-9b83-467b04fae671.png">

I've seen a similar issue on Win2012R2 with IE and switched to Chrome there.

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so this should get cleaned up in the refactor!
