### ISSUE TITLE
Consul cli won't use socket 

### ISSUE THREAD

**Issue by cvvs** [hashicorp/consul#1638]
I'm trying to use a socket address with consul on Cent6 to mitigate some security concerns. The config passes configtest and the consul agent creates the socket as expected:
```
{
    "bootstrap": false,
    "server": false,
    ...
    "addresses": { "rpc": "unix:///var/lib/consul/rpc.sock" },
    "unix_sockets": { "user":"consul", "mode":"0700" }
}
```

However, when I attempt to run `consul info` using my shiny new socket, the consul agent tries to use TCP.
    
    [cvvs@lv426 ~]$ export CONSUL_RPC_ADDR=unix:///var/lib/consul/rpc.sock 
    [cvvs@lv426 ~]$ ./consul info
    Error connecting to Consul agent: dial tcp: unknown port tcp////var/lib/consul/rpc.sock
    [cvvs@lv426 ~]$ ./consul -v
    Consul v0.6.3

I'm assuming this is a stupid user error, but it's not obvious to me what I'm doing wrong. Suggestions?

**Comment by slackpad** [comment]
Hi @cvvs if you just use `/var/lib/consul/rpc.sock` it should work. It keys off the leading slash to pick unix mode. Sorry for the late reply and please re-open if you are still having any issues!
