### ISSUE TITLE
[question] Do I have to add every server from every datacenter in a WAN pool manually?

### ISSUE THREAD

**Issue by tiagoalves83** [hashicorp/consul#1642]
So, I have 2 DCs: "dc1" and "dc2" with 3 servers each.  
The DCs are bootstraped OK, each one in its own LAN pool. 
I want to "connect" both DCs (WAN pool). 
So I thought if I just add any server from dc2 to the WAN pool of any server in DC1 all servers from both DCs would be added to the same WAN pool. But it seems consul "connects" just the 2 servers. Is that the expected behavior ?

Example:
DC1: 
node1-dc1 - 172.17.0.1
node2-dc1 - 172.17.0.2
node3-dc1 - 172.17.0.3

DC2:
node1-dc2 - 172.17.0.4
node2-dc2 - 172.17.0.5
node3-dc2 - 172.17.0.6
```
node1-dc1: # consul agent -server -bootstrap-expect 3 -dc1
node2-dc1: # consul agent -server -dc1 -join 172.17.0.1
node3-dc1: # consul agent -server -dc1 -join 172.17.0.1

node1-dc2: # consul agent -server -bootstrap-expect 3 -dc2
node2-dc2: # consul agent -server -dc2 -join 172.17.0.4
node3-dc2: # consul agent -server -dc2 -join 172.17.0.4

node1-dc2: # consul join -wan 172.17.0.1
node1-dc2: # consul members -wan
```
I believe that the last command `consul members -wan` should return all 6 servers from both datacenters, but it is returning just 2: node1-dc1 and node1-dc2.

**Comment by highlyunavailable** [comment]
You must join each server to the WAN pool explicitly, but once it has joined the WAN pool the membership of the WAN pool will be gossiped to all members of the WAN pool - that is, if you have `172.17.0.1` and `172.17.0.4` talking in the WAN pool, joining `172.17.0.2` to the WAN pool via `172.17.0.1` will also inform `172.17.0.4` about it.

**Comment by tiagoalves83** [comment]
Is there any way I can auto join all server nodes from one DC to the same WAN pool when anyone of them were joined? 
I am thinking of always join servers to both pools when bootstrapping: `consul agent -server -dc DC-N -join SAME-DC-IP -join-wan MAIN-DC-IP`. or `consul agent -server -bootstrap-expect N -dc DC-N -join-wan MAIN-DC-IP` when bootstrapping new DCs.
Do you have a better approach?

**Comment by highlyunavailable** [comment]
Mine way was a little more complicated: I queried the AWS API for servers with the tag K/V "role: consul-server" and joined to the first one I got that wasn't the server that was joining based on IP. I used join-wan to the same IP, so each DC then had its own isolated WAN pool.

Once those were set up I'd join DC1 and DC2's WAN pools manually. I only ever had to do that once because once I'd made the 2 WAN pools aware of each other they kept each other in sync via gossip, and I never had to join-wan across a WAN link.

**Comment by tiagoalves83** [comment]
Can you post a sample of your solution? 
How to make 2 WAN pools talking to each other without adding every member to the same pool ? (did I get it right ?!?)

Right now, I am doing this:
```
docker run -d --name node2 -h node2 gliderlabs/consul-server -dc dc1 -bootstrap-expect 3
docker run -d --name node3 -h node3 gliderlabs/consul-server -dc dc1 -join 172.17.0.2 -join-wan 172.17.0.2
docker run -d --name node4 -h node4 gliderlabs/consul-server -dc dc1 -join 172.17.0.2 -join-wan 172.17.0.2
docker run -d --name node5 -h node5 gliderlabs/consul-server -dc dc2 -bootstrap-expect 3 -join-wan 172.17.0.2
docker run -d --name node6 -h node6 gliderlabs/consul-server -dc dc2 -join 172.17.0.5 -join-wan 172.17.0.2
docker run -d --name node7 -h node7 gliderlabs/consul-server -dc dc2 -join 172.17.0.5 -join-wan 172.17.0.2
```

**Comment by highlyunavailable** [comment]
I can't, but I'll just edit your solution:

```
docker run -d --name node2 -h node2 gliderlabs/consul-server -dc dc1 -bootstrap-expect 3
docker run -d --name node3 -h node3 gliderlabs/consul-server -dc dc1 -join 172.17.0.2 -join-wan 172.17.0.2
docker run -d --name node4 -h node4 gliderlabs/consul-server -dc dc1 -join 172.17.0.2 -join-wan 172.17.0.2
docker run -d --name node5 -h node5 gliderlabs/consul-server -dc dc2 -bootstrap-expect 3 -join-wan 172.17.0.2
docker run -d --name node6 -h node6 gliderlabs/consul-server -dc dc2 -join 172.17.0.5 -join-wan 172.17.0.5
docker run -d --name node7 -h node7 gliderlabs/consul-server -dc dc2 -join 172.17.0.5 -join-wan 172.17.0.5
docker exec node5 /bin/consul join -wan 172.17.0.2
```

Output from my machine:
```
$ docker exec node5 /bin/consul members -wan
Node       Address          Status  Type    Build  Protocol  DC
node2.dc1  172.17.0.2:8302  alive   server  0.6.3  2         dc1
node3.dc1  172.17.0.3:8302  alive   server  0.6.3  2         dc1
node4.dc1  172.17.0.4:8302  alive   server  0.6.3  2         dc1
node5.dc2  172.17.0.5:8302  alive   server  0.6.3  2         dc2
node6.dc2  172.17.0.6:8302  alive   server  0.6.3  2         dc2
node7.dc2  172.17.0.7:8302  alive   server  0.6.3  2         dc2
```

If I add another node: `docker run -d --name node7 -h node8 gliderlabs/consul-server -dc dc2 -join 172.17.0.5 -join-wan 172.17.0.5`

I now get:

```
Node       Address          Status  Type    Build  Protocol  DC
node2.dc1  172.17.0.2:8302  alive   server  0.6.3  2         dc1
node3.dc1  172.17.0.3:8302  alive   server  0.6.3  2         dc1
node4.dc1  172.17.0.4:8302  alive   server  0.6.3  2         dc1
node5.dc2  172.17.0.5:8302  alive   server  0.6.3  2         dc2
node6.dc2  172.17.0.6:8302  alive   server  0.6.3  2         dc2
node7.dc2  172.17.0.7:8302  alive   server  0.6.3  2         dc2
node8.dc2  172.17.0.8:8302  alive   server  0.6.3  2         dc2
```

If I stop node 5: `docker stop node5`

Then:

```
docker exec node2 /bin/consul members -wan
Node       Address          Status  Type    Build  Protocol  DC
node2.dc1  172.17.0.2:8302  alive   server  0.6.3  2         dc1
node3.dc1  172.17.0.3:8302  alive   server  0.6.3  2         dc1
node4.dc1  172.17.0.4:8302  alive   server  0.6.3  2         dc1
node5.dc2  172.17.0.5:8302  left    server  0.6.3  2         dc2
node6.dc2  172.17.0.6:8302  alive   server  0.6.3  2         dc2
node7.dc2  172.17.0.7:8302  alive   server  0.6.3  2         dc2
node8.dc2  172.17.0.8:8302  alive   server  0.6.3  2         dc2
```

**Comment by slackpad** [comment]
@highlyunavailable is right - you have to join each sever to at least one other member of the WAN pool at startup. It's very similar to how the LAN pool works, and it's based on another instance of Serf under the hood, basically. If you can use the Atlas join feature it will join to the WAN pool for your servers - https://www.consul.io/docs/agent/options.html#_atlas_join.

**Comment by tiagoalves83** [comment]
Thank you @slackpad @highlyunavailable
