### ISSUE TITLE
[API Gateway] Support running on Nomad

### ISSUE THREAD

**Issue by Esity** [hashicorp/consul#16421]
### Is your feature request related to a problem? Please describe.
No issues

### Feature Description
My current team/company is working on Scaling out Nomad because it is great :)

With that, I would love to see consul-api-gateway support running on Nomad since it is also a Hashicorp product. Is this something we could support?

### Use Case(s)
For users/teams all in on Hashicorp, it would be nice to allow for consul-api-gateway on other hashi products like Nomad

**Comment by Esity** [comment]
What is the status of this?

**Comment by blake** [comment]
@Esity We're actively working on supporting Consul API Gateway on Nomad and are targeting having this available around the release of Consul 1.18.

**Comment by Shackelford-Arden** [comment]
@blake Just so I set proper expectations, would this mean that the Docker images for `consul-api-gateway` will be prepared to officially support Nomad as well? I've been told that as of right now, they are tailed specifically for K8s (though I don't necessarily see how that might be, given the contents of the current [Dockerfile](https://github.com/hashicorp/consul-api-gateway/blob/main/Dockerfile).

**Comment by ivantopo** [comment]
Hello people :wave:  just wondering if there is an updated timeline for this? It is sad that ingress gateways have been deprecated but we can't migrate out of them until support for API gateways lands in nomad :confused:

**Comment by david-yu** [comment]
Hi everyone. Consul API Gateway on Nomad is now officially supported with the Nomad 1.8.0 GA. A prescriptive job specification on [hashicorp-guides/consul-api-gateway-on-nomad](https://github.com/hashicorp-guides/consul-api-gateway-on-nomad) along with a supporting [tutorial](https://developer.hashicorp.com/nomad/tutorials/integrate-consul/deploy-api-gateway-on-nomad) on how to securely deploy Consul API gateway on Nomad. Will go ahead and close this issue.
