### ISSUE TITLE
consul acl token read -self broken in 1.15.0

### ISSUE THREAD

**Issue by dani** [hashicorp/consul#16431]
#### Overview of the Issue

In my scripts, I check if I already have a valid consul token, to ask vault for a new one when it's not the case. For this, I used to run
```
consul acl token read -self
```
Since I've upgraded to 1.15.0, this command fails and ask for an accessor-id. The help output (consul acl token read help) still mention -self as a valid option, to use our current http token instead of providing an accessor-id

**Comment by david-yu** [comment]
Thanks for reporting @dani, this should come in the Consul 1.15.1 patch release in a few weeks.
