### ISSUE TITLE
Issue when joining with port

### ISSUE THREAD

**Issue by strarsis** [hashicorp/consul#1643]
A consul agent is started like this to join a cluster:
````
consul agent -config-dir /etc/consul.d/ -join <consul-server-hostname>
````
This works.

Now also the port is specified (maybe a different port should be used or just for being explicit):
````
consul agent -config-dir /etc/consul.d/ -join <consul-server-hostname>:8500
````
This fails and an unrelated error message is logged:
````
[...] | ==> Joining cluster...
[...] | ==> received invalid msgType (72), expected pushPullMsg (6) from=<ip of consul-server-hostname>:8500
[...] | [...] INFO exited: consul-agent (exit status 1; not expected)
````

Thank you and
with best regards

**Comment by slackpad** [comment]
Hi @strarsis the problem here is that you need to use the port number for the LAN cluster (8301) not the Consul client port (8500). It's trying to connect and getting an unexpected message back. If you use 8301 for a LAN join, or 8302 for a WAN join this should work.
