### ISSUE TITLE
check_update_interval ignored

### ISSUE THREAD

**Issue by strarsis** [hashicorp/consul#1644]
A consul server is started by following command:
````
consul -server -bootstrap-expect 1 -data-dir ./data -config-dir /etc/consul.d
````

In /etc/consul.d/config.json:
````
{
  "check_update_interval": "0s"
}
````

But during startup still this message is logged:
````
==> Newer Consul version available: 0.6.3
````
Consul is started inside a container with no state being preserved, 
so this cannot be a cached result either.

Or is consul always checking for updates at startup (not afterwards in intervals)?

Thank you and 
with best regards

**Comment by ks888** [comment]
I guess you misunderstand the meaning of a `check_update_interval` option.
https://www.consul.io/docs/agent/options.html#check_update_interval

**Comment by slackpad** [comment]
Hi @strarsis if you wan to disable update checks, this is the option to set - https://www.consul.io/docs/agent/options.html#disable_update_check.

**Comment by strarsis** [comment]
They are very similar, thanks. :smile:
