### ISSUE TITLE
consul - multiple ip address

### ISSUE THREAD

**Issue by Veluu** [hashicorp/consul#1652]
I have a consul cluster with 5 consul servers and multitude consul agents (consul ver 0.5.2)

All consul servers run in 192.168.1.0/24 with several other agents.
There are also consul agents in 192.168.2.0/24 and 192.168.3.0/24 networks.

So far everything runs great. There are no problems.

Now, I need to add additional IPs from the other subnets. To be more specific. A few consul servers/agents which are in 192.168.1.0/24 will get additional IPs from 192.168.2.0/24 and 192.168.3.0/24. Whenever I add additional IPs on host myconsulserver-2 I ocassionally get the following warnings from various hosts

```
2016/01/27 14:55:53 [WARN] dns: node 'myconsulserver-2' failing health check 'serfHealth: Serf Health Status', dropping from service 'myservice-1'
2016/01/27 14:55:53 [INFO] memberlist: Marking myconsulserver-2 as failed, suspect timeout reached
2016/01/27 14:55:53 [INFO] consul: member 'myconsulserver-2' failed, marking health critical
```

and in consul gui I see that all services at myconsulserver-2 are failing. I don't see any data packet loss. All consul instances from 192.168.1.0/24 have bind_addr parameter set to the respective address from their primary network - 192.168.1.0/24. I don't understand why the node with many addresses starts flapping. In consul monitor -log-level=debug I can't notice anything suspicious.

**Comment by slackpad** [comment]
Hi @Veluu are all these subnets routable from any host in the cluster? Consul requires a fully connected mesh so is is possible that some set of servers can't see each other for routing or even firewall reasons?

**Comment by Veluu** [comment]
Yes, all the subnets mentioned above are routable. Firewall rules are empty thus it's not the problem.

**Comment by slackpad** [comment]
Hi @Veluu one other thing to check, is it possible that you need to update the advertise address https://www.consul.io/docs/agent/options.html#_advertise? This will default to the bind address, but maybe the other address is the routable one? Issues of this type are almost always to do asymmetry in the ability of nodes to contact each other in the cluster.

**Comment by Veluu** [comment]
Ok indeed there was some network problem. After solving the "hidden" network issue everything runs as it should.

**Comment by slackpad** [comment]
Thanks for the update!
