### ISSUE TITLE
broken empty retry join

### ISSUE THREAD

**Issue by muayyad-alsadi** [hashicorp/consul#1653]
hi,

when I have a server.json like this

```
{
...
  "retry_join": [],
...
}
```

I got periodic logs like this

```
    2016/01/27 16:07:02 [INFO] agent: (LAN) joining: []
    2016/01/27 16:07:02 [WARN] memberlist: Failed to resolve : lookup : no such host
```

**Comment by slackpad** [comment]
Hi @muayyad-alsadi there's an explicit check to prevent this and I wasn't able to reproduce this behavior - https://github.com/hashicorp/consul/blob/master/command/agent/command.go#L489-L491. Is it possible you've got some other configuration file with an empty item in that list?

**Comment by muayyad-alsadi** [comment]
I'll retry to reproduce again

**Comment by slackpad** [comment]
Closing this out as I wasn't able to repro. Please let me know if you can get a config that does this.
