### ISSUE TITLE
[1.15.1] After update Consul Client states "No known consul servers", cannot load Node Overview in GUI

### ISSUE THREAD

**Issue by Sidicer** [hashicorp/consul#16599]
#### Overview of the Issue

After upgrading Consul Servers and Client from 1.13.2 to 1.15.1 we are facing issue, where the Client is visible in `consul members` list and in "Nodes" (in GUI), but when trying to view the info about the client within GUI it doesn't load.

```sh
# docker exec consul consul members (within server)
Node              Address             Status  Type     Build   Protocol  DC             Partition  Segment
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
client-name client-address alive     client  1.15.1  2               dc-name  default    <default>

# docker exec consul consul members (within client)
Node              Address             Status  Type     Build   Protocol  DC             Partition  Segment
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
client-name client-address alive     client  1.15.1  2               dc-name  default    <default>
```

Web console shows `GET http://server-ip-address:8500/v1/internal/ui/node/client-ip-address?dc=datacenter-name net::ERR_BLOCKED_BY_CLIENT` as well as the client has ERR LOGS which state `agent.router.manager: No servers available` & `agent.anti_entropy: failed to sync remote state: error="No known Consul servers"` 

We have tried restarting the client, leaving and rejoining the datacenter, but that did not resolve the issue.

This seems like an issue with the GUI, as we have not lost our prometheus targets that we are getting from Consul and Registered Services are still shown for the client

---

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Update consul servers from 1.13.2 to 1.15.1
2. Update consul client from 1.13.2 to 1.15.1
3. View consul logs
4. View web browser console

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```hcl
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 2
        services = 3
build:
        prerelease = 
        revision = 7c04b6a0
        version = 1.15.1
        version_metadata = 
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 64
        goroutines = 55
        max_procs = 64
        os = linux
        version = go1.20.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1562
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 41472
        members = 92
        query_queue = 0
        query_time = 1

```

```json
{
  "encrypt": "<redacted>",
  "node_name": "client-fqdn",
  "datacenter": "datacenter-name",
  "retry_join": ["1-server-ip","2-server-ip","3-server-ip"],
  "log_level": "warn",
  "node_meta": {
    "service": "undefined",
    "type": "undefined"
  }
}

```

</details>

<details>
  <summary>Server info</summary>

```hcl
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 2
build:
        prerelease = 
        revision = 7c04b6a0
        version = 1.15.1
        version_metadata = 
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = <redacted>
        server = true
raft:
        applied_index = 2804884
        commit_index = 2804884
        fsm_pending = 0
        last_contact = 58.695594ms
        last_log_index = 2804884
        last_log_term = 1591
        last_snapshot_index = 2802423
        last_snapshot_term = 1591
        latest_configuration = [{Suffrage:Voter ID:98cbb857-bdbc-b92b-1ffa-83663077b4de Address:<redacted>} {Suffrage:Voter ID:703f61a7-7dc6-4c27-5200-84401e064eca Address:<redacted>} {Suffrage:Voter ID:c3c60b4b-803c-910e-2bf3-47afed806f0b Address:<redacted>}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 1591
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 459
        max_procs = 4
        os = linux
        version = go1.20.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1562
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 41472
        members = 92
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 73
        members = 3
        query_queue = 0
        query_time = 1

```

```json
{
  "encrypt": "<redacted>",
  "node_name": "server-fqdn",
  "datacenter": "datacenter-name",
  "retry_join": ["1-server-ip","2-server-ip","3-server-ip"],
  "ui_config": {
    "enabled": true
  },
  "log_level": "warn",
  "node_meta": {
    "service": "consul",
    "type": "critical"
  }
}

```

</details>

### Operating system and Environment details

Debian 11 Bare-Metal Servers running Consul in Docker

### Log Fragments

```sh
# docker exec consul consul members (within server)
Node              Address             Status  Type     Build   Protocol  DC             Partition  Segment
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
client-name client-address alive     client  1.15.1  2               dc-name  default    <default>

# docker exec consul consul members (within client)
Node              Address             Status  Type     Build   Protocol  DC             Partition  Segment
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
server-name server-address alive     server  1.15.1  2               dc-name  default     <all>
client-name client-address alive     client  1.15.1  2               dc-name  default    <default>

# Web Console Output:
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

# Client Logs:
2023-03-10T11:35:02.775Z [WARN]  agent.router.manager: No servers available
2023-03-10T11:35:02.775Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
```

**Comment by huikang** [comment]
@Sidicer , there will be some UI bug fix in the upcoming patch release of 1.15.2. But still want to get more info from you to rule out any other possibility:

- In your client log, does `[ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"` appear repeatedly or just once? 
> 
> Client Logs:
> 2023-03-10T11:35:02.775Z [WARN]  agent.router.manager: No servers available
> 2023-03-10T11:35:02.775Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"

- `consul members ` returns the client agent looks good. What does the api endpoint of server (i.e., `curl http://127.0.0.1:8500/v1/catalog/nodes`) return? Is the client agent included in the result?

- Can you still register services or create kv at the client agent?

Thanks.

**Comment by huikang** [comment]
@Sidicer thanks for the detailed info. Based on your description, the client agent works as expected: in effect registering service uses the same RPC communication to server agents as kv, so client agent can talk to the server agents.

I will leave this open until we verify the upcoming release solves the UI issue. (Or if you like, you could try the build from main branch before the v1.15.2 is available)

**Comment by Sidicer** [comment]
Thank you for the suggestion, as we currently have no testing environments I will not be trying out the main branch on our production servers. Will wait for v1.15.2 and can update you here if our issues have been resolved with it.

**Comment by Sidicer** [comment]
Upgrading server node to `1.15.2` has fixed the UI "Overview" issue mentioned above, but sadly after upgrading a client node to `1.15.2` - we still get Console Errors when going to `UI -> Nodes -> Client-Node`
The error within browser console:
```
:8500/v1/internal/ui/node/consul-client-fqdn?dc=datacenter:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```
![image](https://user-images.githubusercontent.com/9251667/229153439-3a2a1560-373e-4078-ba28-cbddc6b1c722.png)

**Comment by huikang** [comment]
Hi, @Sidicer , I can see both server and client agents in a quick setup.

<img width="503" alt="Screen Shot 2023-03-31 at 11 04 50 AM" src="https://user-images.githubusercontent.com/463631/229157935-852a81f6-cdbb-43e6-b0f9-a92a12518cf3.png">


The error message you posted seems related to this [one](https://www.keycdn.com/support/how-to-solve-err-blocked-by-client)

**Comment by huikang** [comment]
> Although, will we be seeing changes in version 1.16.1 to the CSS/HTML/JS Naming within UI so that Ad-Blockers would not try and hide UI ?

cc @blake @david-yu @jkirschner-hashicorp for the above question
