### ISSUE TITLE
UI not starting with ui_dir in config file

### ISSUE THREAD

**Issue by bscott** [hashicorp/consul#166]
I cannot get the UI to start using the ui_dir directive in the config file, only via as a command line flag.

**Comment by cleung2010** [comment]
I am encountering this issue. I Can enable the UI on the servers. However on a consul client, requests to `http://localhost:8500` and `http://localhost:8500/ui/` gives me a 301. Running Consul 0.5.2. on all nodes.

```
$ curl -v http://127.0.0.1:8500
* Rebuilt URL to: http://127.0.0.1:8500/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8500 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:8500
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: /ui/
< Date: Fri, 20 Nov 2015 22:24:56 GMT
< Content-Length: 39
< Content-Type: text/html; charset=utf-8
< 
<a href="/ui/">Moved Permanently</a>.

* Connection #0 to host 127.0.0.1 left intact
```

The `config.json` on the client:
```
{
        "data_dir": "/var/lib/consul",
        "datacenter": "qas",
        "log_level": "INFO",
        "start_join": [<servers>],
        "ui_dir": "/var/lib/consul/ui/dist"
}
```

Removed start_join servers, but a `consul members` is able to give me back a list of members. Nothing suspicious in the consul logs either, all logs are INFO.

**Comment by slackpad** [comment]
Hi @cleung2010 - there's no difference in the client vs. server code path that I can see for the server. If you do a `curl http://localhost:8500/v1/agent/self?pretty` does your `UiDir` look correctly configured in there? Is it possible you've got another JSON file that's stomping on the one above?

**Comment by cleung2010** [comment]
`"DataDir": "/var/lib/consul",`
`"UiDir": "/var/lib/consul/ui/dist"`

```
$ ls -lha /var/lib/consul/ui/dist
total 40K
drwxr-xr-x 3 root root 4.0K May 12  2015 .
drwxr-xr-x 3 root root 4.0K Nov 20 22:14 ..
-rw-r--r-- 1 root root    0 May  1  2014 .gitkeep
-rw-r--r-- 1 root root  28K May 12  2015 index.html
drwxr-xr-x 2 root root 4.0K May 12  2015 static
$ ls -lha /etc/consul/
total 12K
drwxr-xr-x  2 root root 4.0K Nov 20 22:14 .
drwxr-xr-x 94 root root 4.0K Nov 20 22:14 ..
-rw-r--r--  1 root root  332 Nov 20 22:14 config.json

```

**Comment by slackpad** [comment]
Actually - I get a 301 when running that `curl` command locally as well. It kicks you over to the /ui/ page which should serve up index.html. If you tell `curl` to follow the redirect it should work - `curl -L -v http://127.0.0.1:8500`.

**Comment by cleung2010** [comment]
I get a 200, but the response contains this:

```
<p>This is an error page for the Consul web UI. You may have visited a URL that is loading an
unknown resource, so you can try going back to the <a href="#">root</a>.</p>
```

When I `curl -v http://127.0.0.1:8500` on the server nodes I get a 200 and `Consul Agent` on the response

**Comment by slackpad** [comment]
Hmm - that's actually part of the static index.html page - so it looks like that might be getting served up properly by Consul's web server:

https://github.com/hashicorp/consul/blob/master/ui/index.html#L44-L45

> When I `curl -v http://127.0.0.1:8500` on the server nodes I get a 200 and Consul Agent on the response

I don't follow what you mean by "Consul Agent on the response" there. Is that not serving up the same index.html?

**Comment by hridyeshpant** [comment]
i am also getting same issue 

HTTP error code from Consul: 0 error
This is an error page for the Consul web UI. You may have visited a URL that is loading an unknown resource, so you can try going back to the root.
>>
inside the host => curl -v -L http://localhost:8500/ui/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 8500 failed: Connection refused
* Failed to connect to localhost port 8500: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8500: Connection refused

but when running same command ionside the contaier

**Comment by cleung2010** [comment]
@slackpad I mean this:
```
$ curl -v localhost:8500
* Rebuilt URL to: localhost:8500/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8500
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 23 Nov 2015 17:45:24 GMT
< Content-Length: 12
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
Consul Agent
```

I also get a 200 and the same response on the body of the client if I do not specify `ui_dir`. However, as soon as I enable it I get a 301 on both the root and `/ui` endpoints. Why does root `/` redirect to `/ui`, is that intended or is that a side-effect on some misconfiguration on my part?

**Comment by cleung2010** [comment]
Noticed that `curl -v -L localhost:8500/` serves `index.html` but it's still in template form, meaning that it's not parsed before being rendered:
```
<button {{ action "reset" }} {{ bind-attr class=":btn :btn-danger" }}>Reset Defaults</button>
```

The security group on AWS allows TCP inbound connection from 0.0.0.0/0 to 8500. Networking seems fine too. 
```
$ sudo lsof -i :8500
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
consul  3777 consul    8u  IPv4  17365      0t0  TCP localhost:8500 (LISTEN)
```
```
$ sudo iptables -L -nv
Chain INPUT (policy ACCEPT 16638 packets, 1674K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 14625 packets, 2196K bytes)
 pkts bytes target     prot opt in     out     source               destination         
```
```
$ netstat -natlp
(No info could be read for "-p": geteuid()=1001 but you should be root.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:40267           0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:8400          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      -               
tcp        0      0 10.66.30.190:38856      10.66.12.149:8300       TIME_WAIT   -               
tcp        0    476 10.66.30.190:22         10.87.65.5:51004        ESTABLISHED -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::8301                 :::*                    LISTEN      -               
tcp6       0      0 :::111                  :::*                    LISTEN      -               
tcp6       0      0 :::46644                :::*                    LISTEN      -               
tcp6       0      0 :::53                   :::*                    LISTEN      -    
```

**Comment by cleung2010** [comment]
@slackpad @hridyeshpant Got it working by adding this to my `config.json`:
```
{
    "addresses": {
        "http": "0.0.0.0"
    },
...
}
```
As explained in #599 the client binds the HTTP address to localhost by default so within the client you're able to curl the `/ui` endpoint, but you'll just get `connection refused` if you try to resolve it from the outside. 

I'd suggest to update the docs on the Web-UI page so that it explicitly states that the default config only enables the UI within `localhost`.

**Comment by hridyeshpant** [comment]
@cleung2010 
it is not working for me . i am running consul in local box and trying to access in same box.
>>docker run test -bootstrap -ui-dir /ui
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: '200d4ea560f4'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 0.0.0.0 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 172.17.0.12 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2015/12/17 14:47:53 [INFO] serf: EventMemberJoin: 200d4ea560f4 172.17.0.12
    2015/12/17 14:47:53 [INFO] serf: EventMemberJoin: 200d4ea560f4.dc1 172.17.0.12
    2015/12/17 14:47:53 [INFO] raft: Node at 172.17.0.12:8300 [Follower] entering Follower state
    2015/12/17 14:47:53 [INFO] consul: adding server 200d4ea560f4 (Addr: 172.17.0.12:8300) (DC: dc1)
    2015/12/17 14:47:53 [INFO] consul: adding server 200d4ea560f4.dc1 (Addr: 172.17.0.12:8300) (DC: dc1)
    2015/12/17 14:47:53 [ERR] agent: failed to sync remote state: No cluster leader
    2015/12/17 14:47:55 [WARN] raft: Heartbeat timeout reached, starting election
    2015/12/17 14:47:55 [INFO] raft: Node at 172.17.0.12:8300 [Candidate] entering Candidate state
    2015/12/17 14:47:55 [INFO] raft: Election won. Tally: 1
    2015/12/17 14:47:55 [INFO] raft: Node at 172.17.0.12:8300 [Leader] entering Leader state
    2015/12/17 14:47:55 [INFO] consul: cluster leadership acquired
    2015/12/17 14:47:55 [INFO] consul: New leader elected: 200d4ea560f4
    2015/12/17 14:47:55 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2015/12/17 14:47:55 [INFO] consul: member '200d4ea560f4' joined, marking health alive
    2015/12/17 14:47:55 [INFO] agent: Synced service 'consul'
==> Newer Consul version available: 0.6.0

my config file 
>>
        "data_dir": "/var/consul",
        "ui_dir": "/ui",
        "log_level": "INFO",
        "server": true,
        "dns_config": {
                "allow_stale": false
        },
        "addresses": {
        "http": "0.0.0.0"
        }
}

and i am using setup from >>https://ewegithub.sb.karmalab.net/EWE/docker/tree/master/stratus/consul/server

in local box outside the container 
>> curl -v -L 172.17.0.12:8500
* Rebuilt URL to: 172.17.0.12:8500/
* Hostname was NOT found in DNS cache
*   Trying 172.17.0.12...

but inside the container, i am able to get page using curl -v -L localhost:8500

**Comment by cleung2010** [comment]
@hridyeshpant Can you check the port mapping for that container with `docker ps`? Perhaps port 8500 is mapped to some other port on the host. https://ewegithub.sb.karmalab.net/EWE/docker/tree/master/stratus/consul/server is not accessible for me.

**Comment by hridyeshpant** [comment]
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                  NAMES
b3459a09f0bd        test                "/bin/consul agent -s"   5 hours ago         Up About a minute   8300-8302/tcp, 8400/tcp, 8500/tcp, 8301-8302/udp, 8600/tcp, 8600/udp   admiring_curie

**Comment by gvenka008c** [comment]
I am facing the issues in access the consul UI. Here is how I am starting it

```
consul agent -ui -ui-dir /tmp/consul_web/ -server -bootstrap-expect 1 -data-dir /tmp/consul -node=agent-one -bind=xx.xxx.xx.xxx -config-dir /etc/consul.d

```

```
 #curl -v http://xx.xxx.xx.xxx:8500
* About to connect() to 127.0.0.1 port 8500 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8500 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8500
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: /ui/
< Date: Tue, 19 Jul 2016 16:06:14 GMT
< Content-Length: 39
< Content-Type: text/html; charset=utf-8
<
<a href="/ui/">Moved Permanently</a>.

* Connection #0 to host 127.0.0.1 left intact
```

Please suggest. Let me know if any details required. Thanks.

**Comment by slackpad** [comment]
@gvenka008c that's the correct behavior - Consul is trying to redirect you to /ui/ which is the location of the web UI. If you add a `-L` to your `curl` command it will follow the redirect.

**Comment by gvenka008c** [comment]
@slackpad Thanks. When I try to hit the URL http://xx.xxx.xxx.xx:8500/ui/ from the browser, it says "Failed to Open Page". I have opened the ports on the server but still the same problem.

```
# netstat -an | grep 8500
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN
```

**Comment by gvenka008c** [comment]
@slackpad I started consul with -client argument and that fixed the issues.

```

consul agent -ui -ui-dir /tmp/consul_web/ -server -bootstrap-expect 1 -data-dir /tmp/consul -node=agent-one -bind=xx.xxx.xxx.xx -config-dir /etc/consul.d -client 0.0.0.0

```
