### ISSUE TITLE
If you're using `-config-dir` an empty `.json` file in there is bad news.

### ISSUE THREAD

**Issue by darron** [hashicorp/consul#1661]
I remember finding this a long time ago but I forgot to register it as a bug. Was talking with @slackpad last week and remembered.

I ran into it when a service that was writing config files failed and wrote a blank file into the folder - Consul then fails to start up - tries to parse and craps out.

Example output here:

https://gist.github.com/darron/7275837c7734041c5a4a

Not sure if it's something y'all can fix - guard against - but if it's possible that would likely be pretty awesome.

Thanks for the great software!

**Comment by MrMMorris** [comment]
This is kind of related to https://github.com/hashicorp/consul/issues/1221 as well. Empty files causing issues.

**Comment by slackpad** [comment]
Fixed in https://github.com/hashicorp/consul/pull/1703.

@MrMMorris I think #1221 is a different issue where we are truncating on the write side.

**Comment by darron** [comment]
Thanks for fixing this @slackpad and @alistanis - appreciate that!

**Comment by alistanis** [comment]
No problem @darron! Thanks for merging it @slackpad!
