### ISSUE TITLE
Add support for simple typing or other validation of values [Feature Request]

### ISSUE THREAD

**Issue by timmytofu** [hashicorp/consul#1663]
It would be nice if I could constrain a key to a particular type of value (integer, string, etc.), or to provide a way to do some pre-commit validation (I could write a regex, for example) to add a failsafe layer of sanity checking to the tools I write around consul.

**Comment by slackpad** [comment]
Hi @timmytofu I definitely see the appeal of enforcing this inside Consul itself, though I would hesitate to add this kind of functionality to the core - it's super difficult to hit everybody's use cases and we don't want to put any kind of complicated scripting capability in the KV set path. One option that might be a good alternative would be to use something like https://github.com/Cimpress-MCP/git2consul and enforce your policies on the input side with pre-merge checks / etc. just like you'd manage source code.

Will keep this open to think about it some more, but I think in general we'd lean towards doing this kind of enforcement outside of consul.

**Comment by slackpad** [comment]
Hi @timmytofu I'm going to close this out. We haven't had a ton of interest in this from the community, and I think it would add a lot of complexity to do well (configuration, run time performance, multi-key transactions, etc.). It's super nice on the Consul side that it can treat values as binary blobs and shuttle them around without having to parse them.
