### ISSUE TITLE
Support for ACL wildcard rules?

### ISSUE THREAD

**Issue by ezjacob-maheim** [hashicorp/consul#1664]
Is it possible to create ACLs with read capabilities within a key but only write capability for keys within a certain folder. So example
```
key "" {
  policy = "read"
}
key "teamname/*/*/envars/" {
  policy = "write"
}
```
basically the ACL can only edit envars that are under "teamname/$app/$environment/envars/"

**Comment by slackpad** [comment]
Hi @ezjacob-maheim Consul uses the most specific rule by looking for the policy with the longest prefix match, so a setup like that should work. Unfortunately, we don't support wildcards so you'd need to make policies for each team/app/environment. Hope that helps!

**Comment by ptusch** [comment]
Is there a specific reason why this is not implemented aside from "we don't support it"?
It seems like a reasonable feature and has good applications I think.

I don't want to create a key value store policy tree to protect my key value store. That's redundant.
