### ISSUE TITLE
Reverse dns not working

### ISSUE THREAD

**Issue by JrCs** [hashicorp/consul#1669]
Hi,

I'm using:
>Consul v0.6.3
>Consul Protocol: 3 (Understands back to: 1)

In my `resolv.conf` i have
>nameserver 172.17.0.1

which is the ip of the docker bridge interface.

I bind the consul dns to this interface with this docker run options:
```-p 172.17.0.1:53:8600 -p 172.17.0.1:53:8600/udp```

Normal resolution work:
```bash
$ dig prometheus.service.consul

; <<>> DiG 9.10.2-P4 <<>> prometheus.service.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34230
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;prometheus.service.consul.	IN	A

;; ANSWER SECTION:
prometheus.service.consul. 0	IN	A	172.17.0.38

;; Query time: 0 msec
;; SERVER: 172.17.0.1#53(172.17.0.1)
```
But reverse not:
```bash
$ dig -x 172.17.0.38

; <<>> DiG 9.10.2-P4 <<>> -x 172.17.0.38
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 1426
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;38.0.17.172.in-addr.arpa.	IN	PTR

;; Query time: 0 msec
;; SERVER: 172.17.0.1#53(172.17.0.1)
```

**Comment by darron** [comment]
@JrCs Consul isn't really designed to do reverse lookups. It's generally only setup to resolve domains names with `.consul` in them.

This might work:

1. Install dnsmasq - set it to query Consul - but only for `.consul` domain names.
2. Use dnsmasq facility for reverse DNS records as detailed here:

http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

Search for `--ptr-record` - also detailed here:

https://onemoretech.wordpress.com/2011/01/27/dnsmasq-reverse-lookups/

You could use Consul Template to write the specific configuration needed and drop it into a configuration folder.

I haven't done this with PTR records - but we use Consul with dnsmasq and it works well.

**Comment by JrCs** [comment]
It's seems a little overkill. Perhaps SkyDns is better in this case.

**Comment by sean-** [comment]
`consul` does respond to reverse DNS (`PTR`) queries and this does appear to be working as expected.  Using the node `consul1` as an example, forward lookups for its `A` record work:

```
% dig @127.0.0.1 -p 8600 consul1.node.dc1.consul. A

; <<>> DiG 9.10.3-P3 <<>> @127.0.0.1 -p 8600 consul1.node.dc1.consul. A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24583
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;consul1.node.dc1.consul.	IN	A

;; ANSWER SECTION:
consul1.node.dc1.consul. 0	IN	A	172.16.139.133

;; Query time: 2 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Sat Jan 30 13:46:22 UTC 2016
;; MSG SIZE  rcvd: 80
```

`consul1`'s reverse DNS query works as expected:

```
% dig @127.0.0.1 -p 8600 133.139.16.172.in-addr.arpa. PTR

; <<>> DiG 9.10.3-P3 <<>> @127.0.0.1 -p 8600 133.139.16.172.in-addr.arpa. PTR
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1566
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;133.139.16.172.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
133.139.16.172.in-addr.arpa. 0	IN	PTR	consul1.node.dc1.consul.

;; Query time: 1 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Sat Jan 30 13:46:41 UTC 2016
;; MSG SIZE  rcvd: 109
```

I'd suspect something amiss with the docker bridge because the exact - albeit paraphrased - `dig` command also works as expected.

```
% dig @127.0.0.1 -p 8600 -x 172.16.139.133

; <<>> DiG 9.10.3-P3 <<>> @127.0.0.1 -p 8600 -x 172.16.139.133
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7035
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;133.139.16.172.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
133.139.16.172.in-addr.arpa. 0	IN	PTR	consul1.node.dc1.consul.

;; Query time: 2 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Sat Jan 30 13:50:53 UTC 2016
;; MSG SIZE  rcvd: 109
```

If you have additional details, please feel free to reopen this issue.

**Comment by darron** [comment]
Ah - thanks @sean- I didn't know it did that. Learn something new everyday.

**Comment by sean-** [comment]
Your suggestion to use `dnsmasq` for reverse DNS is a good one because if you do, simply add an additional `server` option to get reverse DNS.  To extend the example above, add the following to your `dnsmasq` config:

```
server=/139.16.172.in-addr.arpa/127.0.0.1#8600
```

**Comment by scalp42** [comment]
The issue is that you end up with hundred of server directives unless I'm mistaken @sean-

**Comment by sean-** [comment]
There's certainly some validity to that statement since you would need one `server` entry in `dnsmasq.conf` per RFC 1918 network, but that is reasonably bounded.  For instance, you can put one server entry for `10.0.0.0/8`, one for `192.168.0.0/16`, etc.  It gets a little goofy with the example I provided because `172.16/12`'s max IP address extends to `172.31.255.255`.  This, however, is one of the perks of `dnsmasq`'s other config directives, `rev-server`, which handles this situation nicely:

```
# [snip]
server=/consul/127.0.0.1#8600
rev-server=10.0.0.0/8,127.0.0.1#8600
rev-server=172.12.0.0/12,127.0.0.1#8600
rev-server=192.168.0.0/16,127.0.0.1#8600
# [snip]
```

There are more netblocks that could be loaded in here, but that's the gist of how you'd handle this.

```
% sockstat -4 | grep dnsm
nobody   dnsmasq    8147  4  udp4   *:53                  *:*
nobody   dnsmasq    8147  5  tcp4   *:53                  *:*
% dig @127.0.0.1 -p 53 -x 172.16.139.133

; <<>> DiG 9.10.3-P3 <<>> @127.0.0.1 -p 53 -x 172.16.139.133
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27261
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;133.139.16.172.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
133.139.16.172.in-addr.arpa. 0	IN	PTR	consul1.node.dc1.consul.

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Jan 31 03:19:35 UTC 2016
;; MSG SIZE  rcvd: 109
```

**Comment by JrCs** [comment]
@sean it's works with node but not for service.
If i try a reverse resolution with a node it works and return the name of the node, but i want reverse resolution for service (get the ip(s) of containers that running the service). Is it possible ?

**Comment by slackpad** [comment]
Hi @JrCs - Consul only implements reverse lookups by nodes, using the node catalog under the hood. For the lookup you described it sounds like you could simply query for <name>.service.consul, which will contain a list of IPs running that service.
