### ISSUE TITLE
consul is not removing terminated aws ec2 instances

### ISSUE THREAD

**Issue by anhcuong** [hashicorp/consul#1671]
I was setting up a cluster using consul (3 master nodes and consul agent running on all other machines). I observed that consul did not update/deregister the nodes machines if I terminated those nodes from aws console UI. 

Consul works fine and updates successfully if I restart all the consul masters. Not sure it's consul's right behaviour since our system dashboard using Consul to update the running servers ip.

**Comment by slackpad** [comment]
Hi @anhcuong if you terminate the machines without giving the node a chance to gracefully leave, the cluster will detect it as failed and reap it after 72 hours. You can use the force-leave command to boot out a failed node sooner - https://www.consul.io/docs/commands/force-leave.html.
