### ISSUE TITLE
statsite_prefix docs wrong - doesn't explain how it's used with statsd 

### ISSUE THREAD

**Issue by dbeckham** [hashicorp/consul#1672]
The `statsite_prefix` configuration option is used by both the statsd integration and the statsite 
integration, but the documentation only mentions statsite.  The statsd integration was added in 72524e911d01b89205ea29ceaa3dbd8c2ed4d52d and documentation was updated in 5f140f197203d7be39f2da7a381272beaf4e777b.

It would be far less confusing to create a separate configuration option for statsd, or deprecate `statsite_prefix` for a more generic option name, but at the moment, the docs just need fixing.

The current documentation says:

> `statsite_prefix` The prefix used while writing all telemetry data to statsite. By default, this is set to "consul".

In addition to noting that it is used by both statsite and statsd, any user of statsd will ask Does it allow the use of periods?", which it does.

A possible rewritten version:

> `statsite_prefix` The prefix used when writing any telemetry data to statsite or statsd. By default, this is set to "consul". For statsd, periods denote metric hierarchy and are sent as is. e.g. `consul.dc01`

**Comment by i0rek** [comment]
This is cleaned up now, the option was renamed to `metrics_prefix`: https://www.consul.io/docs/agent/options.html#telemetry-metrics_prefix.
