### ISSUE TITLE
statsite_prefix used by both statsite and statsd, but name is statsite specific

### ISSUE THREAD

**Issue by dbeckham** [hashicorp/consul#1673]
In change 72524e911d01b89205ea29ceaa3dbd8c2ed4d52d, a new configuration option, `statsite_prefix`, was added to allow users to customize the metric prefix sent to statsite, but due to the way that the go-metrics library works, it also happens to configure the statsd prefix as well.  It's not clear whether this was intended or not, but it is an important need for statsd users and good that it is supported. However, the configuration option name is badly named.

There should be a per-integration setting like `statsite_prefix` or `statsd_prefix`, or the current option should be deprecated for a generic prefix option like `stats_prefix`. 

FYI, I created a separate issue to update the documentation for current versions, whether this change is implemented in the future or not: #1672

**Comment by slackpad** [comment]
This was renamed to `metrics_prefix` in https://github.com/hashicorp/consul/pull/3498.
