### ISSUE TITLE
wait parameter in blocking queries doesn't work

### ISSUE THREAD

**Issue by Kaign** [hashicorp/consul#1681]
assume that `X-Consul-Index`=4 , then  
 `$ curl -v http://127.0.0.1:8500/v1/catalog/service/consul?index=4&wait=10s`  
will always wait for 5minutes (if no changes). No matter what value of the `wait` parameter. Consul is launched with `-dev` flag

**Comment by slackpad** [comment]
Hi @Kaign you need to quote your URL for it to work properly (look in curl's output and you'll see the wait parameter isn't making it in). This will work:

`curl -v "http://127.0.0.1:8500/v1/catalog/service/consul?index=4&wait=10s"`
