### ISSUE TITLE
Turn on skip_leave_on_interrupt by default for server agents

### ISSUE THREAD

**Issue by wuub** [hashicorp/consul#1687]
I think we could greatly improve consuls resiliency for new users if `skip_leave_on_interrupt` was set to `true` by default for consul `server`s (unless explicitly specified otherwise  in config).

Current behaviour of shrinking quorum / clean peers.json is a bit user hostile :)

**Comment by sean-** [comment]
@wuub Agreed, and thank you for that suggestion (I stubbed my toe on this earlier today, in fact).  The default behavior was changed in #1909 .  Where appropriate, we are very receptive to input regarding smoothing out operator and administrator user experience.  Cheers!
