### ISSUE TITLE
Consul can't handle HTTP(S) variable correctly (yet)

### ISSUE THREAD

**Issue by dfduarte** [hashicorp/consul#1689]
Hello guys! This is related to some old problems, as: #132, #583 and #15.

I've a AWS infrastrutucture, that stands behind a firewall within a closed VPC. To talk to outside, these instances need to use a SQUID http proxy.

Ok, I set the HTTP(S)_proxy variables, and all works perfecly, but Consul can't be able to connect to SCADA servers, and reach ATLAS to do the cluster catalog.

There is a way to make this work, or this isn't possible?

**Comment by slackpad** [comment]
Hi @dfduarte - the SCADA/Atlas connection isn't HTTP, it's a TLS-secured TCP session with the https://github.com/hashicorp/yamux stream multiplexer running over that. There's an `atlas-endpoint` configuration directive or `SCADA_ENDPOINT` environment variable you can use to set the endpoint for address. I'm not a Squid expert but can you set it up with some additional configuration to proxy the TLS connection and set the endpoint to contact Squid?

**Comment by slackpad** [comment]
It would need to proxy through to `scada.hashicorp.com:7223.

**Comment by vasu1124** [comment]
would it be possible for consul to use https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_tunneling for establishing a SCADA connection via proxy?

**Comment by slackpad** [comment]
SCADA is deprecated so closing this out.
