### ISSUE TITLE
Creating an ACL token with “-secret” option breaks the consul security (?)

### ISSUE THREAD

**Issue by neo3matrix** [hashicorp/consul#16904]
#### Overview of the Issue

I needed my own UUID set as a token secretID in consul.  If "-secret" option is used in command `consul acl token create` while creating  an ACL token, the token gets created successfully but consul no longer asks for authentication either via UI OR via CLI (e.g. curl command doesn't need any token to access anything consul - Key/val store, nodes, services can easily be accessed and modified as if there is NO ACL in place).

#### Reproduction Steps

1. Deploy a basic docker-based Consul cluster on 3 nodes (without enabling ACL).

2. Update consul config file using the following configuration:
```
acl = {
    enabled = true
    default_policy = “allow”
    enable_token_persistence = true
    tokens {
       default = "my-custom-token"
   }
}
```
3. Restart all server containers.
4. Run `consul acl bootstrap` and it generates the bootstrap secretID.
5. Accessing consul either via external CLI (like curl) OR U,I now prompts for an ACL token to log in. (expected behavior)
6. Logged in to the UI or CLI using the secretID copied in step 5.
7. Now, create a new ACL token using the `consul acl token create` command with the “-secret” flag, as follows:

```
consul acl token create \ 
-description “cluster-wide access” \ 
-policy-id 00000000-0000-0000-0000-000000000001 \ 
-secret=(any-predefined-UUID-value) \ 
-token=(bootstrap SecretID from step#4)
```
After executing step#7, the new token is successfully created with a secretID assigned with the provided secret, as expected.
However, if I go back to the UI or CLI (even after logging out of the Consul UI), I no longer need to log in with any token. 
Any curl command towards the consul cluster can easily be successful without passing any token. Same goes for UI. I can fetch/modify  key/value either via UI or curl without any tokens - as if consul was never ACL enabled.
This behavior suggests (to me) that the “-secret” flag breaks all authentication/ACL logic.

**In contrast,**

- if I don’t pass the “-secret” flag in the consul acl token create command in step#7, Consul creates a token with a new secretID assigned by Consul. The UI and outside CLI commands like curl still require an ACL token (either secretIDs), which is the expected behavior.

- Similarly, if I try to create a token from the UI, it also creates a Consul-generated secretID for a new token, and the system still expects me to log in with either secretIDs, or the curl command fails if I don’t provide any ACL tokens. 

Only step#7 seems to be causing the security issue.

### Consul info for both Client and Server
consul version tested:
1. v1.10.1
2. latest (as of today)
Both these versions show same behavior.

### Operating system and Environment details
CentOS 7

#### Final notes:
I have seen the ["-secret" option ](https://developer.hashicorp.com/consul/commands/v1.10.x/acl/token/create#secret) in the HashiCorp documentation way before v1.10. It's been there since long time.  I haven't seen anyone has encountered this issue. 
May be I am doing something wrong? 
if so, what's that? Can someone please help me?
Is anyone also have seen this issue before?
Please check and help.

**Comment by jkirschner-hashicorp** [comment]
Are the following steps necessary for the reproduction?

- Step 1: Doing the initial deployment without the ACL system enabled
- Steps 5-6: Using the bootstrap token to do something before you try step 7

And just to confirm, is the value for `acl.tokens.default` definitely different than the bootstrap token? Just want to make sure that step 7 isn't converting the secret ID used as the `default` token into something with bootstrap privileges.

**Comment by blake** [comment]
Hi @neo3matrix, I replied to your [forum post](https://discuss.hashicorp.com/t/creating-an-acl-token-with-secret-option-breaks-the-consul-security/52413/2 with details on why you are seeing this behavior. Is it okay if we continue this discussion on that forum post?

**Comment by jkirschner-hashicorp** [comment]
Two people just checked this internally and confirmed that Consul is behaving as expected in response to the `-secret` flat.

An agent's `acl.tokens.default` token is used for any request against that agent that doesn't include a token in the request.

If the agent's `acl.tokens.default` has the same value the `-secret` flag in step 7, that would explain why any unauthenticated (no user-provided token) request works -- it ultimately uses the `acl.tokens.default` token. @blake gave more detail on this in the Discuss post.

If `acl.tokens.default` has a **different** value than the `-secret` flag in step 7, unauthenticated requests just get whatever permissions that default token has.

---

I'm going to close this issue on Github for now. As @blake suggested, we can continue the discussion on Discuss!

We're also open to any feedback on anything (including docs) that could help when working with the ACL system, such as with the `acl.agent.default` token.
