### ISSUE TITLE
consul operator raft list-peers doesn't actually use the -id flag

### ISSUE THREAD

**Issue by jameshartig** [hashicorp/consul#16955]
#### Overview of the Issue

```
consul operator raft transfer-leader --id="<id of new leader>"
```
Doesn't actually set the leader to the sent id.

---

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 3 server nodes
2. Run `consul operator raft list-peers` and pick a non leader
3. Run `consul operator raft transfer-leader --id="<id of new leader>"`
4. Observe random leader chose instead.

```
curl --request POST "http://127.0.0.1:8500/v1/operator/raft/transfer-leader?id=c4a1bc71-d25b-d271-083e-f843628dd112"
```
Works fine.

#### Code Details

In `command/operator/raft/transferleader/transfer_leader.go` the flag is setup `c.flags.StringVar(&c.id, "id", "", "The ID of the node to transfer leadership to.")` but it's never used. I think this is because there isn't an `id` field in `api.QueryOptions` that we can pass along to `RaftLeaderTransfer`. I'm willing to work on this but it's unclear what the solution should be. Should `RaftLeaderTransfer` just accept an optional `id string` parameter? That seems like it would be a breaking change. Should we instead add a `RaftLeaderTransferToID` method that has the new parameter and then the command would use one or the other based on the flag?

**Comment by dhiaayachi** [comment]
Thank you for reporting this @jameshartig!

Your assessment is right, the id is not threaded correctly to the API call. The fix should be fairly simple if you are willing to work on it it's much appreciated!

I think the best approach is to add an extra parameter (`id string`) to the API call in here, and add it to the request query parameters as it's done for example in [here](https://github.com/hashicorp/consul/blob/46212cc5706aaa0bce4ac8c5c1d32ff2509bfc27/api/operator_raft.go#L90-L90) for `RaftRemovePeerByAddress`. That extra parameter could be then used to pass the id from the command line call.

Let me know if you are willing to submit a PR for this, and I can answer any questions you have and review it when ready.

**Comment by jameshartig** [comment]
@dhiaayachi Great! Is it okay that `RaftLeaderTransfer`'s signature will change which is technically a breaking change? Do we just need to include that in the changelog? I can work on a PR for this either this week or early next week.

**Comment by dhiaayachi** [comment]
> @dhiaayachi Great! Is it okay that `RaftLeaderTransfer`'s signature will change which is technically a breaking change? Do we just need to include that in the changelog? I can work on a PR for this either this week or early next week.

Yes we definitely need to include that in a changelog. I think it's okay to change though. 

Thank you again for reporting this, looking forward to review your fix, let me know when it's up.
