### ISSUE TITLE
Consul agent -atlas . Not able to start consul and view infrastructure state

### ISSUE THREAD

**Issue by CruzanCaramele** [hashicorp/consul#1696]
I am building an AMI with packer. I have my configuration for consul at the point of creating the AMI for both server and client as below : 
1.) consul_clent.conf:
```
description "Consul client"

start on vagrant-ready or runlevel [2345]
stop on runlevel [!2345]

respawn

console log

script
  if [ -f "/etc/service/consul" ]; then
    . /etc/service/consul
  fi

  # Make sure to use all our CPUs, because Consul can block a scheduler thread
  export GOMAXPROCS=`nproc`

  exec /usr/bin/consul agent \
   -data-dir="/tmp/consul" \
   -config-dir="/etc/consul.d" \
   -atlas={{ atlas_username }}/{{ atlas_environment }} \
   -atlas-join \
   -atlas-token="{{ atlas_token }}" \
   ${CONSUL_FLAGS} \
   >>/var/log/consul.log 2>&1
end script
```

2.) consul_server.conf : 
```
description "Consul"

start on vagrant-ready or runlevel [2345]
stop on runlevel [!2345]

respawn

console log

script
  if [ -f "/etc/service/consul" ]; then
    . /etc/service/consul
  fi

  # Make sure to use all our CPUs, because Consul can block a scheduler thread
  export GOMAXPROCS=`nproc`

   exec /usr/bin/consul agent \
   -server \
   -data-dir="/tmp/consul" \
   -atlas={{ atlas_username }}/{{ atlas_environment }} \
   -atlas-join \
   -atlas-token="{{ atlas_token }}" \
   -bootstrap-expect {{ consul_server_count }} \
   -config-dir="/etc/consul.d" \
   ${CONSUL_FLAGS} \
   >>/var/log/consul.log 2>&1
end script
```

I then use terraform to launch the AMI. In terraform I use a consul_upstart,sh file as below:
```

#!/bin/bash

sed -i -- "s/{{ atlas_username }}/${atlas_username}/g" /etc/init/consul.conf
sed -i -- "s/{{ atlas_token }}/${atlas_token}/g" /etc/init/consul.conf
sed -i -- "s/{{ atlas_environment }}/${atlas_environment}/g" /etc/init/consul.conf
sed -i -- "s/{{ consul_server_count }}/${consul_server_count}/g" /etc/init/consul.conf
service consul restart

echo "Consul environment updated"

exit 0
```

I am able to create an environment and aslo  have a successful plan and apply in Atlas but I cannot get consul to show me the status of the infracture on atlas. At first it stated I need to run **consul agent -atlas atlasusername/environment** . However when i ran that command from my local computer within the directory where i had all my terraform files, i got an error stating **Must specify data directory using -data-dir** .
So again on my local computer with the terraform directory, i ran the command ** consul agent -data-dir="/tmp/consul" -atlas atlasusername/environment** . However consul still does not show the state of my infrastructure on Atlas.
Please any help or advice on this will be much appreciated.

**Comment by slackpad** [comment]
HI @CruzanCaramele can you include some logs from your Consul server as it starts up? It might also be good to add `-log-level=debug` so we can see what's going on.

**Comment by CruzanCaramele** [comment]
hi @slackpad , the consul server does not start up at all, am unsure why that is

**Comment by slackpad** [comment]
Hi @CruzanCaramele usually you configure something like upstart to run Consul and keep it running. Here's a repository with sample scripts for configuring Consul using Packer on Ubuntu, including a sample upstart configuration: https://github.com/hashicorp/best-practices. Hope that helps!

**Comment by slackpad** [comment]
I'm going to close this out, general questions about Consul are better handled on the mailing list.
