### ISSUE TITLE
Backport fix for proxycfg to 1.14.x

### ISSUE THREAD

**Issue by luckymike** [hashicorp/consul#16980]
#### Overview of the Issue

Service Mesh users are currently warned not to upgrade to Consul 1.15.x due to the open issue with leaf certs #16779. A recent fix for service mesh configuration #16529 is only available in 1.15.1. Given the instructions not to upgrade to 1.15, this fix should be backported to 1.14 ASAP.

**Comment by aetimmes** [comment]
#16529 is the fix we need backported to 1.14.x; #16779 is the reason we can't use 1.15.x.

**Comment by kisunji** [comment]
My apologies, I misunderstood this issue. [1.15.2](https://github.com/hashicorp/consul/releases/tag/v1.15.2) has been released with the fix for #16779 so it should be an acceptable upgrade path but I'll re-open this for the reason @aetimmes outlined

**Comment by jkirschner-hashicorp** [comment]
We're also in the process of updating the upgrade docs for 1.15, given the many reports confirming that upgrading from 1.15.0/1 to 1.15.2 resolved the leaf cert renewal issue.

Docs PR: https://github.com/hashicorp/consul/pull/17020

**Comment by david-yu** [comment]
Will go ahead and close as it was backported to 1.14.x. https://github.com/hashicorp/consul/pull/17030
