### ISSUE TITLE
Docker health check with docker 1.10

### ISSUE THREAD

**Issue by gdiazlo** [hashicorp/consul#1706]
Hello

Checks with docker 1.10 doesn't work using consul 0.6.3 from releases.hashicorp.com.

I think the current consul release has a version of go-dockerclient which has this issue:

https://github.com/fsouza/go-dockerclient/issues/455

In consul/command/agent/check.go line 621, when calling  c.dockerClient.StartExec, it fails with the error:

"Unable to start Exec: Unrecognized Input header" that seems to come from the go-dockerclient.

I guess recompiling the consul binary again will use the newest go-dockerclient, fixing the issue, but i haven't tested it.

**Comment by slackpad** [comment]
Hi @gdiazlo thanks for opening an issue. I noticed this too during some local testing so I've got a test environment that does it and will see if the newer library version fixes the issue.

**Comment by sweco-seponr** [comment]
status on this?

**Comment by gdiazlo** [comment]
We recompiled consul 0.6.3 with a new version of the go-dockerclient to fix this. I guess in the next release will be fixed. Not sure if the contributors plan to recompile current versions with the newest go-dockerclient.

**Comment by slackpad** [comment]
Confirmed the latest client fixes this so teeing up a change to pull that in,
