### ISSUE TITLE
I hope to be able to load both key simultaneously

### ISSUE THREAD

**Issue by notdragonfly** [hashicorp/consul#17062]
I hope to be able to load two keys simultaneously. How can I write my yaml? Currently, I am using one key and can reload it. These two keys are in the same folder, and I hope to be able to load them simultaneously，

spring:
 cloud:
    consul:
      host: 127.0.0.1
      port: 8101
      config:
        enabled: true
        default-context: routermgr
        format: YAML
        data-key: database

I also have a common key and I hope to load it simultaneously

**Comment by jkirschner-hashicorp** [comment]
Hi @notdragonfly,

Judging by the YAML, this seems like a question specific to Spring Cloud's integration with Consul. I recommend reposting there to get a response from that project's maintainers: https://github.com/spring-cloud/spring-cloud-consul/issues

**Comment by jkirschner-hashicorp** [comment]
I'll close this question for now given that it seems related to Spring Cloud Consul, but feel free to re-open / reply if needed.

**Comment by notdragonfly** [comment]
thx
