### ISSUE TITLE
Client agent takes up a lot of memory

### ISSUE THREAD

**Issue by dominikschulz** [hashicorp/consul#1718]
Some consul agents in our cluster take up a lot of memory (>2GB) after running a few days.

The cluster has about 30-50 members and is running 0.6.0 and 0.6.3 agents.

**Comment by Niks-JJ** [comment]
Hi, 
I too need to know if there is any hardware resource requirement to set up consul. I am in initial stage to design it for our project.So need to know approximate memory requirements etc.
Can someone please post.

**Comment by slackpad** [comment]
@dominikschulz if these are agents running as servers then this could depend on the amount of data you are storing, such as in the KV store. If they are client agents, then this would be an unusual amount of memory. Please let me know and then we can debug from there.

**Comment by kendrickm** [comment]
I'm also seeing this issue, the consul command is `/usr/local/bin/consul agent` so it should be running in agent mode. After about 30 days of uptime, the agent is using >1gig memory.

**Comment by slackpad** [comment]
Hi @kendrickm it depends on whether the `-server` command line option or `server` JSON config option is specified. Can you please double check that in your configuration?

**Comment by kendrickm** [comment]
We have ` "server": false` in one of the json config files

**Comment by kendrickm** [comment]
Some example data, I restarted the consul agent 3 days ago when I last commented. 
Here is a memory graph 
![image](https://cloud.githubusercontent.com/assets/1149330/13337967/798fe9ee-dbd3-11e5-8f31-8e9ba384ffd4.png)

We're not even actively using consul-agents yet so I can't imagine this memory growth is expected.

**Comment by slackpad** [comment]
Interesting - 76 MB isn't way out of family but it does look like it's still growing.

The best way to debug this is to grab a heap profile. Is there any chance you can turn on debugging in your setup via https://www.consul.io/docs/agent/options.html#enable_debug and then capture some heap stats by pulling http://localhost:8500/debug/pprof/heap?debug=1. If you put that in a gist we can take a look.

**Comment by kendrickm** [comment]
@slackpad https://gist.github.com/kendrickm/2cbe991ed44c30ca7783 

Since the agent had to get restarted to pick up the config option, I can pull the stats again next week after the memory has had time to increase back up.

**Comment by kendrickm** [comment]
![image](https://cloud.githubusercontent.com/assets/1149330/13402390/e2fe99c2-dec4-11e5-834f-58e58f3ae783.png)
https://gist.github.com/kendrickm/c0d6a038ef798b15d19c


The file is much bigger this time so hopefully it didn't get cut off in the gist

**Comment by panda87** [comment]
@slackpad I don't know how but in one of my env which have only 50~ agents, consul service takes 1GB of memory, and we currently use it mostly for DNS.
The installed version is 0.6

**Comment by panda87** [comment]
@slackpad do you have any updates on this issue?

**Comment by slackpad** [comment]
It looks like there are 6k goroutines - I bet you got hit by this - https://github.com/hashicorp/memberlist/pull/71. We should be able to confirm this if you can fetch the output of http://consul.service.consul.:8500/debug/pprof/goroutine?debug=1 with debugging turned on.

**Comment by panda87** [comment]
@slackpad pls look me attached graphs for the last 2 weeks goroutines metrics of my consul servers.
<img width="1260" alt="screen shot 2016-03-11 at 12 01 28 am" src="https://cloud.githubusercontent.com/assets/3185476/13686046/6aa2c36c-e71c-11e5-93c6-241784f64a3a.png">
Do you think that the PR above solve this problem?
Do you want to see another metrics?

**Comment by panda87** [comment]
It seems my UDP ports on the firewall were closed and now I opened 8301-8302 for UDP.
Do I need to see the number of gorutines decreasing?

**Comment by slackpad** [comment]
@panda87 if you had UDP closed you would have hit this bug. Fixing the firewall won't cause the goroutines to go down, but if you restart the agent it should stop leaking them. The PR will fix this issue, and I'm also about to release a test version of Consul with this fix (it'll be announced on the mailing list in a few minutes).

**Comment by panda87** [comment]
Do you think this fix will be added to consul 0.6.4?

**Comment by slackpad** [comment]
Yes - it has already been merged and will be part of the release.
