### ISSUE TITLE
Key value PUT through HTTP RESTAPI  :  405 Method Not Allowed

### ISSUE THREAD

**Issue by Niks-JJ** [hashicorp/consul#1719]
Hi Guys,

Consul documentation for Key Value Http end points does not clearly spicify how to give input JSON. I am able to put key values through command line but not able to do the same through REST API.

curl -X PUT -d 'test' http://localhost:8500/v1/kv/Database/Audit/ConnectString   : works

Want to do the same throgh REST API

Tried below

PUT method to end point  http://localhost:8500/v1/kv/Database/Audit/ConnectString1

JSON
{
  "plaintext":  "test2"
  
}

instead of plaintext tried Value too. But getting  405 Method Not Allowed. I am sure I am doing something silly. GET works fine though.

**Comment by Niks-JJ** [comment]
Tried with passing master token too
X-Consul-Token   XXXXX in header. Still same error 
405 Method Not Allowed

**Comment by slackpad** [comment]
Hi @Niks-JJ the `curl` command you gave is using the same REST API you are attempting to use in your application code (showing things are good on the Consul side). It looks like you are not selecting the PUT verb somehow (I bet you are doing a POST, which is a common mistake). If you set that it should work like the `curl` call.

**Comment by Niks-JJ** [comment]
Oh Yes, Absolutely right. Thanks. Worked by changing to PUT.
