### ISSUE TITLE
Consul Web UI: Need to make it password enabled

### ISSUE THREAD

**Issue by Niks-JJ** [hashicorp/consul#1720]
Hi Guys,
I am new to consul and just setting it up.
Both web UI and 1 server consul set up is working fine.

Is there a way to secure web ui through any token or pasword.

Right now web UI is directly available at 

http://localhost:8500/

**Comment by polds** [comment]
We have HAProxy sitting in front with Basic Auth over HTTPs.

**Comment by highlyunavailable** [comment]
When I ran a Consul Web UI I just used nginx and https://github.com/bitly/oauth2_proxy to provide authentication.

**Comment by slackpad** [comment]
Hi @Niks-JJ we don't plan on adding any auth built-in - proxying it with another web server as @polds and @highlyunavailable have suggested is definitely the way to go.

**Comment by jacohend** [comment]
@slackpad I think serving both UI and API over the same port kinda complicates this, though. 

+1 for even basic auth, it's silly to need to set up a whole proxy just to provide basic access control for a full-feature cluster orchestration service

**Comment by polds** [comment]
Well doing our own proxy (HAProxy) actually let us use Consul K/V to store the hashed passwords of users and use Consul Template to write the haproxy.cfg file to include the basic auth users. So Consul controls access to itself.

**Comment by inferiorhumanorgans** [comment]
I agree this is a bit silly to not do basic auth as proxying isn't quite there yet (ex: doesn't work under a subdirectory)

**Comment by yhamouni** [comment]
Hello world,
i have recently started working with consul, and i am trying to use ACLs to conrol access, could you please help me !! :)
thank's for your help

**Comment by marcuschaney** [comment]
Are we still reliant on a third party products to provide auth via Consul's web UI??

**Comment by deepakjotwani** [comment]
> We have HAProxy sitting in front with Basic Auth over HTTPs.

How can we achieve it any links
