### ISSUE TITLE
After opening the ACL, using the deregister API to delete the consul_id prompted success, but the page still shows

### ISSUE THREAD

**Issue by tangguangliang** [hashicorp/consul#17218]
After opening the ACL, using the deregister API to delete the consul_id prompted success, but the page still shows
```bash
 ./consul services deregister -id=18500030010-39300
Error deregistering service "": Unexpected response code: 404 (Unknown service ID "18500030010-39300". Ensure that the service ID is passed, not the service name.)
```

**Comment by jkirschner-hashicorp** [comment]
Hi @tangguangliang,

Can you clarify what "opening the ACL" means? Did you mean the User Interface?

Which Consul version are you using?

Have you double-checked that a service still exists with ID "18500030010-39300"? If so, how?

**Comment by tangguangliang** [comment]
Sorry, I may know the reason when I use 
```
. /consul services deregister -id=17200010001-39256
```
 I also checked the logs and found that the logs are reporting errors
```
agent: Check deregistration blocked by ACLs: check=service. 17200010001-39256 accessorID="anonymous token"
```
 I only used the default bootstrap token, I need to create an additional role and token
