### ISSUE TITLE
Catalog search performance

### ISSUE THREAD

**Issue by kaskavalci** [hashicorp/consul#1724]
Hi,

We cannot search services by their ID, only by name. We can filter with tags. However, Consul gets the service data from [go-memdb](https://github.com/hashicorp/go-memdb) and creates a list from it. Tags are filtered in the end. 

Unfortunately this approach is very slow if we have high number of inquiries with services > 1M. We need to find a particular service and its information with a high request rate. 

Here is the data I've collected, time elapsed during one service search using Tags field (all services have only 1 tag, an identifier) with Catalog endpoint. 

| # of Nodes / # of Services | 1.000 | 10.000 | 100.000 | 500.000 |
| --- | --- | --- | --- | --- |
| 1 Node | 2,94 x 10<sup>5</sup> ns | 5,08 x 10<sup>6</sup> ns | 5,74 x 10<sup>7</sup> ns | 5,01 x 10<sup>8</sup> ns |
| 100 Nodes | 5,57 x 10<sup>5</sup> ns | 8,24 x 10<sup>6</sup> ns | 1,00 x 10<sup>8</sup> ns | 6,07 x 10<sup>8</sup> ns |
| 1.000 Nodes | 5,35 x 10<sup>5</sup> ns | 7,89 x 10<sup>6</sup> ns | 9,64 x 10<sup>7</sup> ns | 5,29 x 10<sup>8</sup> ns |
| 10.000 Nodes | 5,10 x 10<sup>5</sup> ns | 6,14 x 10<sup>6</sup> ns | 9,44 x 10<sup>7</sup> ns | 6,68 x 10<sup>8</sup> ns |

It appears number of nodes services are registered to is not an issue but sheer number of services are. Interestingly it appears to grow exponentially.

Do you plan to have performance optimizations in the future? Can you provide an explanation why it grows exponentially? go-memdb has O(k) complexity and loop that creates a list from db entries is O(n). I couldn't see the hot-point there.

Thanks.

**Comment by slackpad** [comment]
Hi @kaskavalci thanks for opening an issue. I bet we are getting hit in here - https://github.com/hashicorp/consul/blob/v0.6.3/consul/state/state_store.go#L1306. This pulls all the checks for the node in the inner loop around services. We can profile to confirm but this seems like a reasonable thing to optimize.

Just to double check, are you hitting the health endpoint during your testing above?

**Comment by kaskavalci** [comment]
Hi @slackpad thanks for your response. In fact we are hitting here https://github.com/hashicorp/consul/blob/v0.6.3/consul/state/state_store.go#L1271 . We used Consul to retrieve a particular service with a given tag. We would like to use ID here but there is no such API for that. Thus, we embedded a custom ID into tags. But this is not practical after few ten-thousand services.

It seems here there is a lookup by ID https://github.com/hashicorp/consul/blob/master/consul/state/state_store.go#L728 but I'm haven't tested its performance. Just to confirm, does `memdb` not let us to perform lookup by ID?

**Comment by slackpad** [comment]
It will allow a lookup if there's an index - those are defined here -https://github.com/hashicorp/consul/blob/master/consul/state/schema.go. It looks like there is a service index on the checks table, so I need to go back through this logic and see why we are pulling them all and filtering. It should be pretty easy to add an index if needed.

**Comment by david-yu** [comment]
Will go ahead and close as this issue is relatively old and the codebase has changed quite significantly since.
