### ISSUE TITLE
Multiple updates in blocking query

### ISSUE THREAD

**Issue by Kaign** [hashicorp/consul#1725]
Here I found that watch doesn't have to fire on every single change https://github.com/hashicorp/consul/issues/523#issuecomment-66164544
I think this is relevant to a simple blocking query too, but would like somebody to approve it?

**Comment by slackpad** [comment]
Hi @Kaign that's correct. Watches are really using blocking queries under the hood and that's where this behavior comes from. It's possible for a single query wakeup to summarize several changes that occurred together (or to wake up when there was no change).
