### ISSUE TITLE
check's output update in consul server after check's definition change

### ISSUE THREAD

**Issue by Veluu** [hashicorp/consul#1730]
consul 0.6.3
I'm running a simple service with a simple check. The definition goes as follows

```
{
  "service": {
    "name": "myservice",
    "check": {
      "interval": "5s",
      "tcp": "127.0.0.1:2234"
    }
  }
}
```

I'm checking with consul monitor if everything is fine

```
2016/02/17 19:12:56 [DEBUG] agent: check 'service:myservice' is passing
2016/02/17 19:13:01 [DEBUG] agent: check 'service:myservice' is passing
2016/02/17 19:13:03 [DEBUG] agent: Service 'myservice' in sync
2016/02/17 19:13:03 [DEBUG] agent: Check 'service:myservice' in sync
2016/02/17 19:13:06 [DEBUG] agent: check 'service:myservice' is passing
```

Looks ok. Now let's say I want to change the type of check. Let's make it a script check.

```
{
  "service": {
    "name": "myservice",
    "check": {
      "interval": "5s",
      "script": "pgrep -f myservice"
    }
  }
}
```

After I changed the definition of the check I launched reload of consul agent

```
2016/02/17 19:13:19 [DEBUG] agent: pausing 3.527371289s before first invocation of pgrep -f myservice
2016/02/17 19:13:19 [INFO] agent: Synced service 'myservice'
2016/02/17 19:13:19 [DEBUG] agent: Check 'service:myservice' in sync
2016/02/17 19:13:23 [DEBUG] agent: check 'service:myservice' script 'pgrep -f myservice' output: 1572
2016/02/17 19:13:23 [DEBUG] agent: Check 'service:myservice' is passing
2016/02/17 19:13:28 [DEBUG] agent: check 'service:myservice' script 'pgrep -f myservice' output: 1572
```

Yeah, it works but the problem is that I can't see the change in consul web ui at my consul servers.
If I reload consul agent for the second time

```
2016/02/17 19:13:55 [DEBUG] agent: pausing 1.244994276s before first invocation of pgrep -f myservice
2016/02/17 19:13:55 [INFO] agent: Synced service 'myservice'
2016/02/17 19:13:55 [DEBUG] agent: Check 'service:myservice' in sync
2016/02/17 19:13:56 [DEBUG] agent: check 'service:myservice' script 'pgrep -f myservice' output: 1572
```

Nothing special has happened here so far but I see the change in consul web ui at my consul servers. At first I thought it's some kind of bug in consul but I realised that my mate added **check_update_interval variable** set to **2h** in configuration. When I got rid of this 2h everything run smoothly at first reload.

My question is why the second consul reload actually sends the updated output to consul server even though the check_update_interval indicates it shouldn't do it. Not untill 2 hours later as the state of the check has never changed.

**Comment by slackpad** [comment]
Hi @Veluu I think this possibly a dup of https://github.com/hashicorp/consul/issues/1057 - will take a look.

**Comment by slackpad** [comment]
This is a dup of #1982.
