### ISSUE TITLE
consul_server_isLeader gauge always zero

### ISSUE THREAD

**Issue by jjtimmons** [hashicorp/consul#17320]
#### Overview of the Issue

When running a 3-node cluster on 1.15.2 I'm always seeing the cluster's `consul_server_isLeader` gauge's value at `0` across all servers -- even the leader. Example below:

```bash
[ec2-user@ip-172-31-82-248 ~]$ curl -s http://127.0.0.1:8500/v1/status/leader
"172.31.82.248:8300"
[ec2-user@ip-172-31-82-248 ~]$ curl -s http://127.0.0.1:8500/v1/agent/metrics?format=prometheus | grep isLeader
# HELP consul_ip_172_31_82_248_ec2_internal_server_isLeader consul_ip_172_31_82_248_ec2_internal_server_isLeader
# TYPE consul_ip_172_31_82_248_ec2_internal_server_isLeader gauge
consul_ip_172_31_82_248_ec2_internal_server_isLeader 1
# HELP consul_server_isLeader Tracks if the server is a leader.
# TYPE consul_server_isLeader gauge
consul_server_isLeader 0
```

Interestingly `consul_ip_172_31_82_248_ec2_internal_server_isLeader` is right (1). I looked thru the original PR that added this metric and the code itself but nothing has jumped out yet: https://github.com/hashicorp/consul/pull/13304/files

---

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 5e08e229
	version = 1.15.2
	version_metadata =
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 172.31.82.248:8300
	server = true
raft:
	applied_index = 1638
	commit_index = 1638
	fsm_pending = 0
	last_contact = 0
	last_log_index = 1638
	last_log_term = 5
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:500a399a-9a96-6db8-1093-8fdb77b248cc Address:172.31.82.248:8300} {Suffrage:Voter ID:5ecf1435-30e0-913d-5a24-11e0a4f8d104 Address:172.31.88.59:8300} {Suffrage:Voter ID:e20cb420-402a-31d5-b2bd-2196c04068c9 Address:172.31.84.16:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 5
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 180
	max_procs = 1
	os = linux
	version = go1.20.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 10
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 10
	members = 3
	query_queue = 0
	query_time = 1
```

```
server = true
bootstrap_expect = 3

telemetry {
  prometheus_retention_time = "1h"
}
```

</details>

### Operating system and Environment details

Amazon Linux

### Log Fragments

From server getting membership

```
May 11 23:09:52 ip-172-31-82-248.ec2.internal consul[29129]: 2023-05-11T23:09:52.422Z [INFO]  agent.server: cluster leadership acquired
```

**Comment by jjtimmons** [comment]
@huikang I think you have the most context. Do you see anything obviously wrong w/ my set up above to where this wouldn't be expected to be emitted? Eg the fact that `consul_ip_172_31_82_248_ec2_internal_server_isLeader` is set to `1` makes me think that maybe it being `0` is expected and that it's `1` only in that long-form metric

**Comment by huikang** [comment]
Hi, Josh, when you query the metric `consul_sever_isLeader`, you need to put the server name in the metric, like `consul_consul_server_0_isLeader`

I think there is some conflict in the code in showing the metrics
![Screenshot 2023-05-12 at 10 56 14 AM](https://github.com/hashicorp/consul/assets/463631/20e5acb5-656f-40c2-a91b-d0efc8b1421f)

**Comment by huikang** [comment]
<img width="673" alt="Screenshot 2023-05-12 at 2 15 20 PM" src="https://github.com/hashicorp/consul/assets/463631/568e8328-f011-45eb-8824-a869c67f6acd">

This metrics is unique to individual consul agent, so we need add the server name to the metrics. To avoid any further ambiguity leading to customer's confusion, I think we need to remove the metric `consul_sever_isLeader` from being reported because it is always 0 across all agents.

**Comment by huikang** [comment]
> I'm not sure that the metric is useable if we have to know apriori what the server's name is. If we can filter and/or aggregate using server as a label/tag, that would be helpful I think

Yes, that's true. In one of my dashboard, I use `"sum({__name__=~\".+server_isLeader\"})",` to determine if the cluster has one and only one leader. But I agreed with you this metric should not have the server name in metric name.

Will look into it.

**Comment by huikang** [comment]
This is where the isLeader metrics is defined:

https://github.com/hashicorp/consul/blob/8bb16567cd92c76080f0cc48a6e5405bfd068fad/agent/setup.go#L272-L277

Maybe we should strip the server prefix from the gauge:

https://github.com/hashicorp/consul/blob/8bb16567cd92c76080f0cc48a6e5405bfd068fad/agent/setup.go#L330-L339
