### ISSUE TITLE
Failed nodes aren't removed from http api service catalog

### ISSUE THREAD

**Issue by empath** [hashicorp/consul#1739]
I have a node in a failed state.  It's Serf Health Status is reported as critical.

It is still returned in the service catalog via the http api.  It seems to be removed from DNS discovery however.

Is this expected behavior?  It seems somewhat confusing if so.  Is there a way to filter the catalog api call to return only healthy nodes?

**Comment by jzohrab** [comment]
A Vagrant file demo giving an example: https://github.com/jzohrab/consul_demo (also submitted to this code in PR https://github.com/hashicorp/consul/pull/1566/).

This demo creates two services on node n2, "web" which is healthy, and "web_unhealthy" which has status "critical".

Healthy service dig and curl:
```
vagrant@n1:~$ dig @127.0.0.1 -p 8600 web.service.consul SRV +short
1 1 80 agent-two.node.dc1.consul.
vagrant@n1:~$ curl http://localhost:8500/v1/catalog/service/web          
[{"Node":"agent-two","Address":"172.20.20.11","ServiceID":"web","ServiceName":"web" ... }]
```

Unhealthy service dig and curl:
```
vagrant@n1:~$ dig @127.0.0.1 -p 8600 web_unhealthy.service.consul SRV +short
vagrant@n1:~$ curl http://localhost:8500/v1/catalog/service/web_unhealthy
[{"Node":"agent-two","Address":"172.20.20.11","ServiceID":"web_unhealthy","ServiceName":"web_unhealthy", ... }]
```

Is this expected behaviour?

**Comment by jzohrab** [comment]
A different http api endpoint seems to give the data needed for accurate service discovery:

```
vagrant@n1:~$ curl http://localhost:8500/v1/health/service/web?passing
[{"Node":{"Node":"agent-two","Address":"172.20.20.11","CreateIndex":7,"ModifyIndex":14},"Service":{"ID":"web","Service":"web","Tags":["rails"],"Address":"","Port":80,"EnableTagOverride":false,"CreateIndex":8,"ModifyIndex":8},"Checks":[{"Node":"agent-two","CheckID":"ping","Name":"ping","Status":"passing","Notes":"","Output":"","ServiceID":"","ServiceName":"","CreateIndex":10,"ModifyIndex":14},{"Node":"agent-two","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","CreateIndex":7,"ModifyIndex":7}]}]

vagrant@n1:~$ curl http://localhost:8500/v1/health/service/web_unhealthy?passing
[]
```

This seems to sort-of contradict the official docs at https://www.consul.io/intro/getting-started/services.html, which imply that HTTP API and DNS are equivalent.  If needed, I can submit a PR with notes to the docs.

**Comment by slackpad** [comment]
Hi - you are correct that the [health endpoint](https://www.consul.io/docs/agent/http/health.html#health_service) is the right way to filter for only healthy nodes. I added a note about this to the intro.
