### ISSUE TITLE
Can consul support limiting the number of registered services or nodes？

### ISSUE THREAD

**Issue by luzejia** [hashicorp/consul#17413]
#### Feature Description

I use consul to be a multi-tenant service registry, assign a token to each tenant, and give the token different read and write permissions.

I want to be able to limit the number of services or nodes registered in consul, in order to prevent a large number of wrong registrations due to program bugs and other reasons, exhausting the resources on the machine.

**Comment by huikang** [comment]
@jkirschner-hashicorp @blake , does consul currently support this?

**Comment by blake** [comment]
@huikang Consul does not support assigning resource quotas to tokens to control the number of resources a token can create in Consul.

**Comment by huikang** [comment]
@blake , thanks for confirming!

**Comment by luzejia** [comment]
@huikang @blake Thanks!
