### ISSUE TITLE
Option for `consul reload` to apply cluster-wide

### ISSUE THREAD

**Issue by enspritz** [hashicorp/consul#17421]
#### Feature Description and Use Case
I desire a way to run `consul reload` once at the CLI and have all Consul instances reload their configurations. This could apply to just all server instances, or perhaps all instances no matter their run modes, as long as Consul detects and applies changes in configuration files on all such instances in one fell swoop.

We use configuration management tooling to place service definitions under `consul.d`. Consul picks up changes to these files on reload and restart; we do it live with `consul reload`. But in order for all Consul server instances to detect and pick up changes, it seems currently necessary to:
```bash
export CONSUL_HTTP_ADDR=https://10.0.0.1:8500
consul reload
export CONSUL_HTTP_ADDR=https://10.0.0.2:8500
consul reload
export CONSUL_HTTP_ADDR=https://10.0.0.3:8500
consul reload
...    # Ad Nauseum. Tedious, and prone to human error.
```
Well, if I am to suggest a concrete technical approach, how about:
```bash
consul reload -cluster    # One and done.
```

**Comment by jkirschner-hashicorp** [comment]
Hi @enspritz,

I think you can accomplish the same thing today by enabling config auto-reload: https://developer.hashicorp.com/consul/docs/agent/config/config-files#auto_reload_config

All config options that work with the `consul reload` command will also be reloaded automatically when changed in the config file(s) on disk if `auto-reload-config` is `true`.

**Comment by jkirschner-hashicorp** [comment]
If this would fit your needs, let us know if there are good places we could mention this in the documentation. It seems like you may have looked for something within Consul that already does this, but didn't come across auto-reload-config in that searching.

**Comment by enspritz** [comment]
Hi Jared @jkirschner-hashicorp 
Thanks for this. Yes its entry didn't stand out in the docs, and I don't know how many times my eyes must have passed over it. But it indeed appears to effect my desired outcome.
