### ISSUE TITLE
Register a service using REMOTE_ADDR, get response

### ISSUE THREAD

**Issue by Vanuan** [hashicorp/consul#1745]
Is it possible to use /v1/catalog/register to use REMOTE_ADDR?

My use case is CI testing:
- start up some service to be tested
- register a service using an address that is provided by socket's REMOTE_ADDR (since I don't know which interface would be routable), generate a unique name for it
- get service info back
- provide service info to the testing server (which doesn't know about consul and isn't using its DNS)
- wait for the testing server to test the service to be tested
- deregister a service (auto deregister a service if not reachable for some time)

Are there any other solutions to the use case above?

**Comment by Vanuan** [comment]
Probably it doesn't make sense to register a service on a machine which doesn't have a consul agent.
But maybe it makes sense as a fallback (if a consul agent is down).

**Comment by slackpad** [comment]
Hi @Vanuan this is a bit of an unusual use case for Consul but it seems like it should be possible. Why not run a Consul agent on the machine where the test service is running? That will make sure things get cleaned up if the machine goes away, etc.

**Comment by slackpad** [comment]
Hi @Vanuan the Consul agent is part of the same failure domain as the machine it's running on so it doesn't make sense to fallback to another agent. If I understand your use case it seems like running an agent in CI alongside the service being tested is the way to go, and it makes sure things get cleaned up when all that gets torn down. I'll close this out for now but feel free to re-open or email the list if you have more questions.

**Comment by Vanuan** [comment]
Yeah, I've just opened a socket to remote server and used socket.client_addr.
