### ISSUE TITLE
Valid Characters for DNS discoverability [ Docker ]

### ISSUE THREAD

**Issue by devotox** [hashicorp/consul#1746]
```
    2016/02/21 02:54:03 [INFO] agent: Synced service 'doctify-dev:doctify-server:443'
    2016/02/21 02:54:03 [WARN] Service name "platform_server-80" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
```

my container name is doctify-server ... so im wondering why its naming the service after the image name rather than the container name

**Comment by slackpad** [comment]
Hi @devotox I think that can be controlled through registrator (which I assume is what you are using here). Please take a look at http://gliderlabs.com/registrator/latest/user/services/.
