### ISSUE TITLE
consul 0.6.3 service policy question

### ISSUE THREAD

**Issue by rbrutas** [hashicorp/consul#1753]
hello,

as part of consul upgrade to 0.6.+ we have to update the service policy on each rule to "write" from "read", sample rules below;

old rule;
```
"Rules": "{ \"key\": { \"\": { \"policy\": \"read\" }, \"test_acl/\": { \"policy\": \"write\" } },  \"service\": { \"\": {  \"policy\": \"read\" }, \"test_acl\": { \"policy\": \"write\" } } }",
```
new rule;
```
"Rules": "{ \"key\": { \"\": { \"policy\": \"read\" }, \"test_acl/\": { \"policy\": \"write\" } },  \"service\": { \"\": {  \"policy\": \"write\" }, \"test_acl\": { \"policy\": \"write\" } } }",
```

a concern came up that by changing the ACL this way it would allow any application to overwrite, delete, etc any other applications service registration? Leaving it to "read" prevents the apps from registering. I can't find any documentation that discuss about it.

**Comment by slackpad** [comment]
Hi @rbrutas you are correct that a wide-open write access to services will allow any application to disrupt any other. The documentation on this is here https://www.consul.io/docs/internals/acl.html (see "Blacklist mode and Service Discovery") and a little bit on here - https://www.consul.io/docs/upgrade-specific.html.

The best strategy is to give each agent a token that lets it write only to services that run on that agent and will be registered, and to give it read access to anything it needs to use (write access will imply read access). If you wanted a default read environment you could also let something like the anonymous token access to read all services and then give agent-specific tokens to control write access. Hope that helps! I'll close this out but feel free to re-open or post a question on the list if you need more help.
