### ISSUE TITLE
Allow SOA record content customization via config file

### ISSUE THREAD

**Issue by Ashald** [hashicorp/consul#1755]
From what I understand, it's handled here: https://github.com/hashicorp/consul/blob/master/command/agent/dns.go#L265

I ended up in en environment, where I have following setup:
Bind A --(delegates `consul.`)--> Bind B --(forwards `consul.`) --> Consul

In this case Consul returns `SOA` pointing to `ns.consul.` which doesn't work for us for obvious reasons.
OTOH if we had an option to set this value in config file that would be an easy thing to set.

If this is OK I can _try_ to contribute this as a PR. Although I don't have any experience with Go I hope I will be able to figure it out. :)

**Comment by slackpad** [comment]
Hi @Ashald thanks for opening an issue. I need to do a little research on this one to make sure I understand all the implications. Will follow up.

**Comment by Ashald** [comment]
@slackpad here is a PR that implement this feature: https://github.com/hashicorp/consul/pull/1798

Nothing big - just an optional extra option. Please let me know what you think about the PR.

**Comment by slackpad** [comment]
Closing this per https://github.com/hashicorp/consul/pull/1798#issuecomment-246722652.
