### ISSUE TITLE
Consul s390 builds support

### ISSUE THREAD

**Issue by Esity** [hashicorp/consul#17585]
## Proposal
Start building Consul binaries for S390. I believe there is already a build process for s390 and vault that exists
This is needed for running Hashicorp things on mainframe

## Attempted Solutions
We have a process to manually create builds for s390 but want an official Hashicorp pattern

Similar to https://github.com/hashicorp/nomad/issues/17440

![image](https://github.com/hashicorp/consul/assets/1851830/8c0d1dae-a2cd-43d6-a437-076559c49fcd)

**Comment by david-yu** [comment]
Thanks @Esity for filing. We are planning according to provide build support only for os390x on VMs. Will update you as we make more progress, as we currently are heads down on 1.16 GA.

**Comment by Esity** [comment]
@david-yu 

yeah this is only around running consul on VMs in mainframe land. We have nomad running containers on mainframe, it is really slick but we can't integrate with our enterprise nomad or consul due to lack of enterprise binaries

Do we have any rough timeframes?

**Comment by ioioioioioioioioioioioioio** [comment]
It would be great if HashiCorp prioritized this. Speaking from support for large financial institutions and peers in the industry... Nomad, Consul, Terraform, and Vault have all been compiled and validated on s390x architecture including optimizing with different compile parameters. Before you had to gcc compile the golang compiler but now golang is permanently supported on s390x architecture. HashiCorp is missing out on new client and revenue opportunities by not providing standard support on s390x. Once compiled on s390x architecture, you can run the binaries in the following locations on either traditional IBM mainframes or their next-gen enterprise Linux server called the LinuxONE. HashiCorp would open up a tremendous market to themselves by taking this action. In essence, they would be enabling majority of the Fortune 100, financial institutions/banks, insurance businesses, and telcos to easily containerize and modernize their mainframe platforms and help them migrate into a more cloud-native infrastructure.  You'd also create multi-architecture support where some workloads can run on the x86 ISA and others can run on the s390x ISA and benefit from the different chipsets. By simply supporting the s390x architecture you open the following patterns where your stack can run. Not only should you consider providing this support but you should then market to companies using mainframes. I can think of at least 10 fortune 100 companies that would be interested.

- Baremetal zLinux partition (SUSE, RHEL, Ubuntu, Alma, or Rocky) on a mainframe server
- VM inside Baremetal zLinux partition in KVM mode on a mainframe server
- VM inside z/VM operating system partition on a mainframe server
- Docker image inside z/CX (Container Extensions) inside the z/OS operating system on a mainframe server
- Baremetal s390x partition (SUSE, RHEL, Ubuntu, ALMA, or Rocky) on a LinuxONE server
- VM inside Baremetal s390x partition in KVM mode on a LinuxONE server

**Comment by david-yu** [comment]
os390x is now available for VMs on Consul Enterprise. Unfortunately we don't intend to introduce on OSS or support other runtimes at this time. I'll go ahead and close. Thank you for filing the issue!

**Comment by ioioioioioioioioioioioioio** [comment]
Team successfully enabled IBM to purchase HashiCorp, so now this s390x support will be available in full, including Nomad. Issue closed.

**Comment by mohsin-shaikh01** [comment]
hello @david-yu is there any workarounds happened ? to run vault on linux s390x arch
