### ISSUE TITLE
consul crashing every few minutes

### ISSUE THREAD

**Issue by romansky** [hashicorp/consul#1765]
Not sure whats going on, trying to debug, set `"log_level": "debug"` and `"enable_debug": true` but not seeing any debug information in agent's stdout..
How to investigate?

**Comment by slackpad** [comment]
Hi @romansky can you post whatever you do see in the logs in a gist so we can see maybe where it's getting to when it crashes?

**Comment by romansky** [comment]
@slackpad sorry to report that after investigation one side of the VPN was not configured to accept traffic from the subnet inside of it, it would pass traffic into it though. It was confusing because the it was working from the other side.. my bad!

**Comment by slackpad** [comment]
np - glad you figured it out!
