### ISSUE TITLE
Improvement: better tag formatting in Consul UI

### ISSUE THREAD

**Issue by Ashald** [hashicorp/consul#1767]
In `Services` section when selecting a service that has a lot of different tags the right panel showing them in a plain multiline list which makes it hard to distinguish between them. See attached screenshot for an example.

![screen shot 2016-02-27 at 12 06 42](https://cloud.githubusercontent.com/assets/397987/13374177/ab42643a-dd4a-11e5-8db2-21d8d7c18acc.png)

I'm not sure what would be the best way to display them but maybe something like a 'text wrapped into box' as here http://getbootstrap.com/components/#available-variations in Example section.

**Comment by jonmoter** [comment]
It would also be great if clicking on one of the tags caused it to filter by that tag.

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
