### ISSUE TITLE
Fix: agent names list doesn't fit into service box in expanded view mode in Consul UI

### ISSUE THREAD

**Issue by Ashald** [hashicorp/consul#1768]
In `Services` section when clicking `expand` button having a lot of agents providing a service list of names doesn't fit into service box. See screenshot for an example.

![screen shot 2016-02-27 at 12 17 16](https://cloud.githubusercontent.com/assets/397987/13374228/56ce491c-dd4c-11e5-9c1b-3f52a7acb074.png)

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
