### ISSUE TITLE
Fix: Consul UI breaks with very long/deep hierarchies in K/V

### ISSUE THREAD

**Issue by Ashald** [hashicorp/consul#1769]
This example uses artificial hierarchy but we have something very similar in with the real data.

The main issues:
1) In key details on the right side path value doesn't fit into the UI box
2) Due to (1) horizontal scrollbar appears
3) When clicking on `add new key` the input is shifted and incredibly small

See screenshots for examples.

![screen shot 2016-02-27 at 12 23 59](https://cloud.githubusercontent.com/assets/397987/13374279/a49e0a0a-dd4d-11e5-87c7-d3f528153bd2.png)
![screen shot 2016-02-27 at 12 25 22](https://cloud.githubusercontent.com/assets/397987/13374281/a4a94c8a-dd4d-11e5-9fd8-f82b0d531621.png)
![screen shot 2016-02-27 at 12 25 36](https://cloud.githubusercontent.com/assets/397987/13374280/a4a8d7e6-dd4d-11e5-82b7-a5bbfc216db7.png)

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!

**Comment by pshima** [comment]
Running in to this issue.  Wondering if this was resolved or marked as closed with intention to fix in the future.

**Comment by slackpad** [comment]
Hey @pshima we are close to starting a rework of the UI, so this was closed with the intention to obsolete with a new version of the UI :-)
