### ISSUE TITLE
Is it possible to have an https service check

### ISSUE THREAD

**Issue by devotox** [hashicorp/consul#1770]
I tried and this didnt work

```
SERVICE_3000_CHECK_HTTPS=/api/status
```

but if i use

```
SERVICE_3000_CHECK_HTTP=/api/status
```

it fails because it is only listening on an https server

**Comment by slackpad** [comment]
Hi @devotox are you using Consul Registrator? Consul only has checks of type "http" but these can hit https endpoints. I'm not super familiar with Registrator, but you might want to try `SERVICE_3000_CHECK_HTTP=https://api/status`. If that doesn't work, I'd take this up with the Registrator folks.
