### ISSUE TITLE
Error in status validation when registering service w/ health check

### ISSUE THREAD

**Issue by shilov** [hashicorp/consul#1775]
The API client returns an error when a service registration includes a health check with a status that is set to `unknown`

Ex:

    reg := &api.AgentServiceRegistration{
        Name:    "service-name",
        Port:    9999,
        Address: "127.0.0.1",
        Check: &api.AgentServiceCheck{
            TTL:    "60s",
            Status: "unknown",
        },
    }

[Returns this error (link to code)](https://github.com/hashicorp/consul/blob/master/command/agent/agent_endpoint.go#L220):

> "Status for checks must 'passing', 'warning', 'critical', 'unknown'"

That is because [structs.ValidStatus(s string)](https://github.com/hashicorp/consul/blob/master/consul/structs/structs.go#L60) does not consider "unknown" to be a valid status.

Is the intended behavior to allow `unknown` or does the error message need to be corrected to exclude it?

Would be happy to make a pull request to implement the change if this is indeed invalid behavior.

**Comment by slackpad** [comment]
Hi @shilov it looks like the "unknown" state is an old thing that was deprecated back in the 0.4.x series. We should probably just remove all references to it - it looks like it's only used in a dns_test.go unit test, and there's a reference in api/health.go. I'd be happy to take a PR if you are interested!
