### ISSUE TITLE
stale request intermittently fails during leader election

### ISSUE THREAD

**Issue by dropje86** [hashicorp/consul#1780]
During a failure or node leave of the leader we sometimes experience hickups in requests, even though we query **with** the stale parameter set.

reproduce:

``` python
#!/usr/bin/env python

import requests
import time

leader = ""

with requests.Session() as session:
    while True:
        try:
            r = session.get('http://localhost:8500/v1/health/service/<service>?tag=<tag>&passing&stale')
            if r.status_code is not 200:
                print("Request failed: {}".format(r.status_code))
                print("Response: {}".format(r.content))
            l = session.get('http://localhost:8500/v1/status/leader')
            if leader == l.content:
                continue
            leader = l.content
            print("leader: {}".format(leader))
            time.sleep(0.01)
        except KeyboardInterrupt:
            exit()
```

Every now and then it seems the connection is aborted or the client still tries to reconnect to the failed node (getting a connection refused). We're trying to work around this by letting the application retry on failure but imho it should be the agent's responsibility to query a different node when using stale lookups.

Here's output tested with stopping the active leader:

``` shell
leader: "10.40.31.164:8300"
Request failed: 500
Response: rpc error: EOF
leader: ""
leader: "10.40.31.166:8300"
leader: ""
Request failed: 500
Response: rpc error: stream closed
leader: rpc error: stream closed
Request failed: 500
Response: rpc error: failed to get conn: dial tcp 10.40.31.166:8300: getsockopt: connection refused
leader: rpc error: failed to get conn: dial tcp 10.40.31.166:8300: getsockopt: connection refused
leader: "10.40.31.166:8300"
leader: ""
leader: "10.40.31.165:8300"
```

**Comment by slackpad** [comment]
Hi @dropje86 not all requests are safe for the agent to retry but we can take a look and see if we can improve this. We've special-cased some common retry scenarios that we know are safe, though we've usually done that in the client library, not the agent. Will take a look.

**Comment by favoretti** [comment]
@slackpad Any updates on this in the meantime? :)

**Comment by slackpad** [comment]
We made some fixes under https://github.com/hashicorp/consul/pull/2175 and https://github.com/hashicorp/consul/pull/3662 that should fix this.
