### ISSUE TITLE
Multiple tag filters for ad-hoc queries w/HTTP endpoints (catalog, health)

### ISSUE THREAD

**Issue by doertedev** [hashicorp/consul#1781]
OHAI.

Am I under the correct assumption, that [this](https://github.com/hashicorp/consul/blob/master/api/catalog.go#L144) means the tag filter for the HTTP API endpoint `/v1/catalog/service/<service>` only supports one tag filter? This would explain the problems that I'm having right now: I'm writing my services with tags for both the region and environment but filtering for both fails.

`https://localhost:8500/v1/catalog/service/zookeeper?tag=region-us-east-1` 5 results,
`https://localhost:8500/v1/catalog/service/zookeeper?tag=region-us-east-1&tag=env-internal` 5 results,
`https://localhost:8500/v1/catalog/service/zookeeper?tag=env-internal` 1 result,
`https://localhost:8500/v1/catalog/service/zookeeper?tag=env-internal&tag=region-us-east-1` 1 result.

Second get's ignored if I'm seeing this correctly.

Can we integrate multiple tag filters? Or accept a json array in the URl? Or do we already and I cannot seem to articulate my query properly? Or do you say "prepared query || gtfo"?

Thinking out loud:
When using prepared queries for all those, I'd either have to create a prepared query for all possible combinations of `["environment", "region", "service"]` which would right now be 350 prepared queries for us r/n and we just started implementing consul. And another would be to create them session-bound and removing them immediately after sessionclose, which in one swing (one ansible discovery round-trip) would create overhead. I think. Haven't benched prepared queries yet (which is the reason I filed this here).

Thanks in advance,
a tableflipping german. Prost.

**Comment by doertedev** [comment]
Just found https://github.com/hashicorp/consul/issues/294 ... So I guess its "prepared statements" then?

**Comment by slackpad** [comment]
Hi @doertedev sorry I think the idea of multiple tags for ad-hoc queries over HTTP endpoints like catalog are still worth considering, and got lost in #294.

**Comment by doertedev** [comment]
What do you think about JSON values? (e.g. `?tag=[eu-west-1,production]`?)

**Comment by slackpad** [comment]
@doertedev I don't think I'd want to put JSON in there, the `?tag=&tag=...` kind of syntax seems like the most natural.

**Comment by doertedev** [comment]
What about negation? That's why I thought about JSON.

**Comment by slackpad** [comment]
I'd still like to avoid JSON - we could using the prepared query syntax of `!` which would have a minimal amount of URL encoding, or we could do something like `?not-tag=`.

**Comment by doertedev** [comment]
The only thing that really sounds wrong to me is using one URL parameter multiple times. This would maybe break third party software that constructs the URL. Anything else? Sure.

**Comment by leftyftw** [comment]
Isn't the "standard" array notation `?tag[]=value1&tag[]=value2&tag[]=value3`.  I believe that would suffice in this instance.  Would love to see this ability.

**Comment by senthilkumar-kj** [comment]
@doertedev please see this comment - https://github.com/hashicorp/consul/issues/294#issuecomment-98857436 and this stackoverflow answer - http://stackoverflow.com/a/24728298/205585

This is the most common way and for negation we could do "!" like it is done in prepared queries or nt-tag query as @slackpad suggested.

**Comment by ffledgling** [comment]
Bump. I was looking for this and the docs I found do not explicitly mention that this is not possible at the moment. Would be neat to have this on an ad-hoc basis :)

**Comment by vanderhoofen** [comment]
It's 2018 now and the first thing my devs ask me is "how can I filter on multiple tags?"  Prepared Queries create a bad user experience for such a lightweight request

**Comment by KrolikROJER** [comment]
Any news?

**Comment by abhaychaware** [comment]
Any update/example/documentation/roadmap on this ?

**Comment by adilyse** [comment]
This is now available in v1.3.0, released yesterday. Thanks for the feedback, which helps us make a better product!
