### ISSUE TITLE
Forward messages to external service

### ISSUE THREAD

**Issue by TMaster** [hashicorp/consul#1783]
Hi,

I started to use consul in my development environment, my environment layout consist on several Consul agents running on linux machines and consul agents running on windows servers (most of my work is in .NET environment so I work with Windows servers and run the consul as Windows Service).

Since I use windows service I'm unable to get feedback on remote execution like reload, maintenance ect'.
I wonder if there is a way to forward the messages consul agent emits to external service.
For example I would like to subscribe to a topic (command perhaps or serf info for operators) in WAMP and the consul agent will stream the information to my monitoring application.

Does consul support this kind of thing, if not can we make it?

Thanks

**Comment by slackpad** [comment]
Hi @TMaster a lot of things that happen in Consul can be pulled via blocking HTTP queries, so it should be possible to write tools to watch for changes and feed these into other systems pretty easily and efficiently. Were you looking specifically for operation actions like `consul reload`, though? I think that kind of information is mostly in our text logs at the moment.

**Comment by highlyunavailable** [comment]
If you use a Windows Service Runner (e.g. NSSM (See https://github.com/hashicorp/consul/issues/758) then you can easily redirect stdout to a text file and use normal text file streamers to collect the data. I've run a pretty extensive Windows Consul infrastructure and that's how I did it.

**Comment by TMaster** [comment]
Both solutions seems good enough, I do use NSSM so I can use the log file, which should be good enough (with a good filter ... to remove all the raft data).

But there is one think I do not understand, I know there is a [monitor command](https://www.consul.io/docs/commands/monitor.html) So it seems that the logic of streaming the agent's log exist, so I wonder if there is a way to collect the data myself (on runtime, as requested) instead of listening to a bunch of endpoints or parsing a log file (which is indeed a nice alternative).

Thanks

**Comment by slackpad** [comment]
@TMaster the monitor command is using an internal RPC interface that's subject to change, and is mostly intended for operators to do interactive debugging with an elevated log level. It's not intended as a general streaming log API.

**Comment by TMaster** [comment]
OK, so I should watch for changes in the KV store \ listen to Events to know that something happen and react to that.

Thank you.

**Comment by slackpad** [comment]
Sounds good.
