### ISSUE TITLE
No information is provided as to when to use -protocol=PREVIOUS

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/consul#1787]
The docs say that you should use -protocol=PREVIOUS in a backwards incompatible upgrade.

However, at no point in the release notes is this indicated if it needs to happen. Maybe it doesnt yet?

There are however BACKWARDS INCOMPATIBILITIES sections in the release notes.

I am confused about upgrading e.g. from 0.5.2 to 0.6.3, whether consul servers need to be upgraded with this flag or not.

Is there an expectation that the release notes will clearly specify when the protocol is upgraded and we would have to use this flag?

Thanks

**Comment by slackpad** [comment]
Hi @gtmtech - exactly, we'd call that out in the release notes and in https://www.consul.io/docs/upgrade-specific.html. For the case of 0.5.2 to 0.6.x we did change the protocol version but we designed Consul to "auto upshift" and start using new features automatically, so you don't need to manually pin protocol versions during that upgrade.
