### ISSUE TITLE
`docker pull consul` fails

### ISSUE THREAD

**Issue by jtzemp** [hashicorp/consul#17916]
#### Overview of the Issue

`docker pull consul` fails. The `latest` tag seems to have been deleted.

See consul:latest on docker hub: https://hub.docker.com/_/consul/tags?page=1&name=latest

---

#### Reproduction Steps

This fails:
```
% docker pull consul
Using default tag: latest
Error response from daemon: manifest for consul:latest not found: manifest unknown: manifest unknown
```

Using a specific tag works:
```
% docker pull consul:1.15 
1.15: Pulling from library/consul
0cdfa0c98ed7: Pull complete 
c801cd11fe9f: Pull complete 
22a94576a2c5: Pull complete 
526efeb2dda8: Pull complete 
3eebd9195ac9: Pull complete 
0974e12eb94a: Pull complete 
Digest: sha256:9989877349983f8b5340ad9e4b1b4e0b4cbcceb4bfbfa4cd9ef084da6a493924
Status: Downloaded newer image for consul:1.15
docker.io/library/consul:1.15
```

**Comment by david-yu** [comment]
Hi @jtzemp please use `hashicorp/consul:latest` instead. We have removed support for official images as per the announcement here: https://github.com/docker-library/docs/pull/2283 and https://github.com/hashicorp/consul/releases/tag/v1.15.0. Will close as this is as designed.
