### ISSUE TITLE
One consul server amongst 3 report "no cluster leader"

### ISSUE THREAD

**Issue by kamaradclimber** [hashicorp/consul#1791]
In a three consul server setup, I encounter the weird behavior on one server:
- `curl A:8500/v1/status/leader` returns B
- B is up and `consul info` shows he is the leader
- any request to the catalog sent to A fails with an code 500 (body is "No cluster leader")
- any request to the catalog sent to B (or C) works as expected
- A is seen as alive by B (in `consul members`)
- `consul monitor` on A shows a lot of error with "No cluster leader"

It seems that node A is not in good shape but can't seem able to recover.

What do you think?

**Comment by kamaradclimber** [comment]
Context:
- all consul servers are using 0.6.3
- the serf pool is small (735 nodes)

Configuration on node A is:
```
{
  "acl_datacenter": "par",
  "acl_default_policy": "deny",
  "acl_master_token": "xxxx",
  "acl_ttl": "300s",
  "addresses": {
    "http": "0.0.0.0"
  },
  "advertise_addr": "10.71.6.142",
  "bootstrap_expect": 3,
  "client_addr": "0.0.0.0",
  "data_dir": "/var/lib/consul",
  "datacenter": "hk5",
  "disable_update_check": true,
  "domain": "consul",
  "enable_syslog": true,
  "node_name": "A",
  "ports": {
    "dns": 8600,
    "http": 8500,
    "rpc": 8400,
    "serf_lan": 8301,
    "serf_wan": 8302,
    "server": 8300
  },
  "retry_join": [
    "C",
    "B",
    "A"
  ],
  "retry_join_wan": [
    [other datacenters servers]
  ],
  "server": true,
  "statsd_addr": "localhost:8125",
  "ui_dir": "/opt/consul-ui/current",
  "verify_incoming": false,
  "verify_outgoing": false
}
```

**Comment by slackpad** [comment]
Hi @kamaradclimber if you run `consul members` on A does it show any of the other nodes?

**Comment by kamaradclimber** [comment]
Thanks @slackpad for your answer. Sadly I've fixed the issue a few days ago by restarting the process.

**Comment by slackpad** [comment]
Ok thanks for the update. We will try to look through the code and reason about this one.

**Comment by slackpad** [comment]
We've done a ton of Raft work for 0.7. Without more detail I don't think we will be able to chase this down, so closing this. We can open a new issue if we see this again and can get more detail.
