### ISSUE TITLE
retry_join and start_join config option array doesn't allow for single quotes

### ISSUE THREAD

**Issue by bogdanr** [hashicorp/consul#1792]
I have the following config:
```
{
    "bootstrap": false,
    "server": true,
    "advertise_addr": "172.31.56.104",
    "datacenter": "CloudHero",
    "data_dir": "/var/consul",
    "encrypt": "__this_is_a_placeholder__",
    "retry_join": ['172.31.48.25', '172.31.50.235'],
    "log_level": "INFO",
    "enable_syslog": false
}
```
Starting consul with it returns this error:
`Error decoding '/etc/consul.d/server.json': invalid character '\'' looking for beginning of value`

Changing to `"retry_join": ["172.31.48.25", "172.31.50.235"]` where double quotes are used makes things work properly but that makes generating the config from jinja templates a lot more complicated.

**Comment by lord2800** [comment]
JSON doesn't support single quotes for strings.

**Comment by bogdanr** [comment]
Yes, the problem is jinja doesn't output valid json.
One possible solution is to use `replace("'", '"')` as a filter in jinja in order to make the json valid.

Thanks for the answer.
