### ISSUE TITLE
Consul default docker tag is not there anymore

### ISSUE THREAD

**Issue by SaraMohamedSamir** [hashicorp/consul#17973]
#### Overview of the Issue

We used to use the default tag of consul images in docker hub (latest) but we notice today the the tag is not there anymore.

I used the following:
`docker pull docker.io/consul:latest` 

but it fails with the following error: 
`
Error response from daemon: manifest for consul:latest not found: manifest unknown: manifest unknown
`

same error happened when I used `docker pull consul` : 

```
Using default tag: latest
Error response from daemon: manifest for consul:latest not found: manifest unknown: manifest unknown
```

It only worked when we hardcode the version, for us this is not handy and we always prefer to use the lates version tag.

**Comment by david-yu** [comment]
Hi @SaraMohamedSamir Please use hashicorp/consul:latest instead. We have removed support for official images as per the announcement here: https://github.com/docker-library/docs/pull/2283 and https://github.com/hashicorp/consul/releases/tag/v1.15.0. Will close as this is as designed.

**Comment by pounct** [comment]
`docker pull hashicorp/consul ` it work but you change if you like run it:
`>docker pull hashicorp/consul
Using default tag: latest
latest: Pulling from hashicorp/consul
c926b61bad3b: Pull complete
efc8a1d2f957: Pull complete
3b486c237dc0: Pull complete
3f8c1df34bc2: Pull complete
6e68caf2684c: Pull complete
4f4fb700ef54: Pull complete
5b9ed4bc931c: Pull complete
Digest: sha256:0bdb01ea0114b9939e442f9a28eccf2ac5aeb58b63ff26d478ca95e87de11ba3
Status: Downloaded newer image for hashicorp/consul:latest
docker.io/hashicorp/consul:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview hashicorp/consul`
`docker run -d -p 8500:8500 -p 8600:8600/udp --name=badger hashicorp/consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
f9203cd03539206aa767d9aaebd22ea8617bff5f94f934c75d39eb407c77af5d`
