### ISSUE TITLE
source-less minified javascripts

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/consul#1797]
There are some source-less minified .js and .css files committed to source tree:

  https://github.com/hashicorp/consul/tree/master/ui/javascripts/libs

Minified code is equivalent of pre-compiled binaries -- un-readable, non-modifiable and non-distributable in [Debian](http://debian.org). It is a bad practice to commit binaries to VCS. 

Moreover minification is unnecessary and a potential security risk. 
Read more in https://wiki.debian.org/onlyjob/no-minification

Please replace all minified files with their original (non-minified) sources.

Thanks.

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we will take a look at this as part of the refactor (the build will likely be much different).
