### ISSUE TITLE
Use YAML for configuration instead of JSON

### ISSUE THREAD

**Issue by Ashald** [hashicorp/consul#1799]
Although JSON has a number of pros it also has a number of cons that people nowadays find discouraging. This includes but not limited to absent support for comments, being more machine friendly rather than human friendly (a lot of 'boilerplate' syntax, trailing-comma thing etc).

Actually this applies not only to Consul but also to other Hashicorp products as well.

Not only I felt myself in such a situation but also heard a lot of complaints from other people using or trying to use Hashicorp products.

Using YAML instead of JSON have a number of huge advantages:
1) It's 100% backward compatible with JSON
2) Includes comments support
3) Closer to regular text in native languages and hence more human-friendly format

IDK whether there are good libs in Golang that will make the migration easy but I think it will definitely worth it.
On a side note I need to mention that docs will need an update to as [AFAIK] in YAML terms 'map/dict' should be used instead of 'object' as in JSON.

**Comment by slackpad** [comment]
Hi @Ashald thanks for opening an issue. I'm going to close this as a "dup" of #895 - we eventually plan to support https://github.com/hashicorp/hcl which has the benefits you cite, but is more inline with our other tools.

**Comment by Ashald** [comment]
@slackpad Do you have it in roadmap already with some ETA or it's still not decided? Thanks!

**Comment by slackpad** [comment]
Hi @Ashald no ETA yet, unfortunately.
