### ISSUE TITLE
will consul support service attributes from registrator in its catalog/service object?

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#1805]
I want to use registrator to pass some key-value attributes, but no place to hold these in consul, is there plan to support this? thank!

**Comment by slackpad** [comment]
Hi @hehailong5 this is currently being requested under - https://github.com/hashicorp/consul/issues/1107. Not registrator-specific, but the ability to add service metadata.

**Comment by slackpad** [comment]
Also https://github.com/hashicorp/consul/issues/697, which I'll close against #1107 as well.

**Comment by hehailong5** [comment]
Hi,

  I'm confused with the consul client. the intro page says the consul 
server nodes have some extra functionalities, does it imply that the 
consul server could also act as client as well? and the cluster setting-up 
guide does not include starting the consul client as a mandatory step, i 
am wondering what exactly the consul client is used for?

Br,
Allen



发件人:         James Phillips <notifications@github.com>
收件人:         hashicorp/consul <consul@noreply.github.com>, 
抄送:   hehailong5 <he.hailong5@zte.com.cn>
日期:   2016/03/11 14:24
主题:   Re: [consul] will consul support service attributes from 
registrator in its catalog/service object? (#1805)



Also #697, which I'll close against #1107 as well.
―
Reply to this email directly or view it on GitHub.

--------------------------------------------------------
ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by slackpad** [comment]
Hi Allen,

That's correct that Consul servers have all the functionality of the Consul
client. In a typical cluster you will run 3 to 5 Consul servers and then
run the Consul agent in client mode on the rest of the nodes in your
cluster. Service registration is done against the clients and they take
care of syncing the state back to the Consul servers. Additionally, the
Consul clients keep track of where the Consul servers are so none of the
applications on that node have to manage that. Finally, the clients all
ping each other as part of the gossip protocol so they form a distributed
failure detector to check the health of all nodes in the cluster, and to
keep track of which nodes are present.

Hope that helps!

-- James

**Comment by hehailong5** [comment]
Hi James,

Thanks for the explanation.
I still get some other questions, please help clarify as well.

1. Regarding service registration, as the consul client is the only 
contact point, I understand more than one node should be configured to run 
as consul client to avoid the single point of failure situation. in this 
case (having multiple consul clients), how do I configure my consul 
registration tool? usually it requires to specify only one endpoint. what 
if this endpoint is down? will it automatically forward the registration 
request to an alive consul client in the cluster?

2. If I register a HTTP health check in the consul, is it the consul 
server or the consul client that will do the actual checking?

3. is there a watchdog implemented in consul cluster? say initially I have 
3 consul servers running in the cluster, if one of them goes down and then 
goes online, will it be automatically re-joined in the cluster? 


Best Regards,

Allen



发件人:         James Phillips <notifications@github.com>
收件人:         hashicorp/consul <consul@noreply.github.com>, 
抄送:   hehailong5 <he.hailong5@zte.com.cn>
日期:   2016/03/22 06:50
主题:   Re: [consul] will consul support service attributes from 
registrator in its catalog/service object? (#1805)



Hi Allen,

That's correct that Consul servers have all the functionality of the 
Consul
client. In a typical cluster you will run 3 to 5 Consul servers and then
run the Consul agent in client mode on the rest of the nodes in your
cluster. Service registration is done against the clients and they take
care of syncing the state back to the Consul servers. Additionally, the
Consul clients keep track of where the Consul servers are so none of the
applications on that node have to manage that. Finally, the clients all
ping each other as part of the gossip protocol so they form a distributed
failure detector to check the health of all nodes in the cluster, and to
keep track of which nodes are present.

Hope that helps!

-- James

On Sun, Mar 13, 2016 at 7:12 PM, hehailong5 <notifications@github.com>
wrote:

> Hi,
>
> I'm confused with the consul client. the intro page says the consul
> server nodes have some extra functionalities, does it imply that the
> consul server could also act as client as well? and the cluster 
setting-up
> guide does not include starting the consul client as a mandatory step, i
> am wondering what exactly the consul client is used for?
>
> Br,
> Allen
>
>
>
> 发件人: James Phillips <notifications@github.com>
> 收件人: hashicorp/consul <consul@noreply.github.com>,
> 抄送: hehailong5 <he.hailong5@zte.com.cn>
> 日期: 2016/03/11 14:24
> 主题: Re: [consul] will consul support service attributes from
> registrator in its catalog/service object? (#1805)
>
>
>
> Also #697, which I'll close against #1107 as well.
> D
> Reply to this email directly or view it on GitHub.
>
> --------------------------------------------------------
> ZTE Information Security Notice: The information contained in this mail
> (and any attachment transmitted herewith) is privileged and confidential
> and is intended for the exclusive use of the addressee(s). If you are 
not
> an intended recipient, any disclosure, reproduction, distribution or 
other
> dissemination or use of the information contained is strictly 
prohibited.
> If you have received this mail in error, please delete it and notify us
> immediately.
>
> ―
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/consul/issues/1805#issuecomment-196108129
>.
>
―
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub

--------------------------------------------------------
ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by slackpad** [comment]
Hi @hehailong5, sorry for the delay on this one:

> 1. Regarding service registration, as the consul client is the only
contact point, I understand more than one node should be configured to run
as consul client to avoid the single point of failure situation. in this
case (having multiple consul clients), how do I configure my consul
registration tool? usually it requires to specify only one endpoint. what
if this endpoint is down? will it automatically forward the registration
request to an alive consul client in the cluster?

Usually you just run one Consul client per node, and have all applications on that node talk to their local client. That client will manage connecting to the Consul servers for you. Since the Consul client is in the same failure domain as the rest of the software on that node (the computer itself could fail), there's no need to have more redundancy at that level. Running the Consul client under a process manager that will restart it on failure should be sufficient.

> 2. If I register a HTTP health check in the consul, is it the consul
server or the consul client that will do the actual checking?

The client does the actual checking, and forwards the status to the servers.

> 3. is there a watchdog implemented in consul cluster? say initially I have
3 consul servers running in the cluster, if one of them goes down and then
goes online, will it be automatically re-joined in the cluster?

Yes it should re-join. There are some configuration options that could affect its ability to rejoin, such as https://www.consul.io/docs/agent/options.html#_rejoin, https://www.consul.io/docs/agent/options.html#leave_on_terminate, and https://www.consul.io/docs/agent/options.html#skip_leave_on_interrupt, but in general a restarted agent should reconnect with the cluster.
