### ISSUE TITLE
bind public ip

### ISSUE THREAD

**Issue by eshujiushiwo** [hashicorp/consul#1811]
Hey guys
I`m tring to test consul cluster through two different dc.
So consul should connect each other with public ip.
what should i do?
Can i just "-bind=public ip"?
I got a error "Error starting agent: Failed to start Consul server: Failed to start RPC layer: listen tcp xxxx:8300: bind: cannot assign requested address  "

Thanks

**Comment by slackpad** [comment]
Answered on the mailing list. Please do not double-post questions to Github issues and the mailing list at the same time.

**Comment by 4F2E4A2E** [comment]
@slackpad please add the link to the mailing list next time, thanks.

**Comment by slackpad** [comment]
Sorry about that - https://groups.google.com/d/msg/consul-tool/Z8BTNGEjLhs/O1B8V8bEJAAJ.
