### ISSUE TITLE
A problem about consul i/o

### ISSUE THREAD

**Issue by eshujiushiwo** [hashicorp/consul#1812]
Hey guys
I set consul cluster using -advertise=xxxxx ("public ip")

And i found a error in the logs
  2016/03/09 02:32:38 [ERR] memberlist: Failed TCP fallback ping: read tcp 172.31.62.62:3085->xxxxx:8301: i/o timeout 
    2016/03/09 02:32:38 [INFO] memberlist: Suspect t1 has failed, no acks received
    2016/03/09 02:32:40 [WARN] raft: Failed to contact xxxxx:8300 in 500.25ms  
    2016/03/09 02:53:50 [WARN] memberlist: Refuting a suspect message (from: t1)
    2016/03/09 02:53:51 [WARN] raft: Election timeout reached, restarting election
    2016/03/09 02:53:51 [INFO] raft: Node at xxx:8300 [Candidate] entering Candidate state
    2016/03/09 02:53:52 [WARN] raft: Election timeout reached, restarting election
    2016/03/09 02:53:52 [INFO] raft: Node at xxx:8300 [Candidate] entering Candidate state
    2016/03/09 02:53:53 [INFO] raft: Election won. Tally: 2
    2016/03/09 02:53:53 [INFO] raft: Node at xxx:8300 [Leader] entering Leader state
    2016/03/09 02:53:53 [INFO] consul: cluster leadership acquired
    2016/03/09 02:53:53 [INFO] consul: New leader elected: t2
    2016/03/09 02:53:53 [INFO] raft: pipelining replication to peer xxxxxxxx:8300
    2016/03/09 02:53:57 [WARN] raft: Failed to contact xxxxxxxx:8300 in 500.217446ms
    2016/03/09 02:53:57 [WARN] raft: Failed to contact quorum of nodes, stepping down  

And i telnet xxxx 8300/8301  ,it`s ok.
and i check 8301 8302 udp with nmap it`s ok too.
Could u pls give me some advises?
Thanks

**Comment by eshujiushiwo** [comment]
And i run consul with
" nohup consul agent -server -data-dir /data/consultest -node=t1 -ui-dir /data/consul/static -advertise=public ip -dc=dc1  &"
" nohup consul agent -server -data-dir /data/consultest -node=t2 -ui-dir /data/consul/static -advertise=public ip -dc=dc1  &"

**Comment by slackpad** [comment]
Replied on the list.

**Comment by egidijus** [comment]
@slackpad which list?

**Comment by slackpad** [comment]
Sorry about that - https://groups.google.com/d/topic/consul-tool/IxMtq51mcsk/discussion.
