### ISSUE TITLE
consul members command

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/consul#18152]
Hello guys,

While doing `consul members`, it's very useful to know who is the leader on each datacenters.
Having `-detailed` option doesn't provide this information.

An another thing that is useful is to have `-dc` filter. It's useful especially when we have multiple datacenter federated.
Can you guys make it happen?

**Comment by huikang** [comment]
- To find leader you can use the `consul raft` [subcommand](https://developer.hashicorp.com/consul/commands/operator/raft): `consul operator raft list-peers`

> An another thing that is useful is to have -dc filter. It's useful especially when we have multiple datacenter federated.
Can you guys make it happen?

Are you proposing something like `consul members -wan -dc dc-name`?

**Comment by Lord-Y** [comment]
@huikang Thx for the `raft/operator` command.
For the 2nd command that's exactly what I'm talking about.

**Comment by huikang** [comment]
@Lord-Y , let me see if I can have something quickly.
