### ISSUE TITLE
Get Metrics Of Consul For Monitoring

### ISSUE THREAD

**Issue by nhproject** [hashicorp/consul#1822]
Hi,

We're using Telegraf as our metrics collector. In order to collect Consul metrics, we're using statsd.
We're getting all the metrics and it works well.
I attached a snapshot from our metrics DB so you'll be able to see some of the metrics we're getting:

<img width="580" alt="screen shot 2016-03-10 at 15 51 45" src="https://cloud.githubusercontent.com/assets/15214994/13671353/263bfc82-e6d8-11e5-9b00-48bded8e037c.png">

Now, I would like to investigate some specific metrics in order to produce appropriate alerts when needed, but I have no idea where can I find what I'm looking for:
1. Number Of Consul Machines In The Cluster
2. Number Of Nodes (number of machines appears when executing: consul members)
3. Leader State
4. Latency
5. Services State

I'd be happy for any help regarding the above list !

Thanks

Nitz

**Comment by rom-stratoscale** [comment]
+1

I think in general, it would really nice to get a documentation regarding all metrics (telemetries) which are exposed. Currently have to read the code and check datadog plugin to understand.

**Comment by BRMatt** [comment]
Agreed, it'd be really helpful to have some guidance on this. We managed to put together a basic dashboard, but it's hard to know what other metrics/readings indicate a healthy/unhealthy cluster.

![](http://cl.ly/1h411S2b260l/Image%202016-03-10%20at%202.19.11%20pm.png)

This [post by datadog](https://www.datadoghq.com/blog/monitor-consul-health-and-performance-with-datadog/) has a bit of insight, but it seems their agent is collecting some custom metrics to generate some of their visualizations.

There's also [this presentation](https://blog.froese.org/2016/01/23/service-discovery-in-the-cloud-with-consul/) by one of their engineers that shows how they diagnosed some capacity problems with their consul leaders.

**Comment by slackpad** [comment]
Added a "Key Metrics" section on here that we will keep up to date - https://www.consul.io/docs/agent/telemetry.html.
