### ISSUE TITLE
Docs Request: Move ACL to another datacenter

### ISSUE THREAD

**Issue by Ashald** [hashicorp/consul#1826]
Assuming that I have a number of datacenters (4 in my case) - let's say `A`, `B`, `C` and `D`.
Initially I set up datacenter `A` as the ACL one. Now I need to move ACLs to the datacenter `B`. How do I do this without downtime and preserving all the configured ACLs?

Thanks.

**Comment by slackpad** [comment]
Hi @Ashald this thread might be helpful for you - https://github.com/hashicorp/consul/issues/1186. It's not something we've vetted or officially supported, so we would need to do some work and testing for a procedure for this.

**Comment by Ashald** [comment]
Thank!
