### ISSUE TITLE
Error installing consul on MacOSX with homebrew

### ISSUE THREAD

**Issue by suchkultur** [hashicorp/consul#1828]
I am trying to install `consul`as described in the [getting started guide](https://www.consul.io/intro/getting-started/install.html) using `brew cask install consul`.

This throws an error on my system: `Error: Cask 'consul' definition is invalid: Bad header line: parse failed`

The same error occurs when trying `brew cask info consul` and `brew cask audit consul`.

`brew cask cat consul`tells me:

```
cask 'consul' do
  version '0.6.3'
  sha256 '6dff4ffc61d66aacd627a176737b8725624718a9e68cc81460a3df9b241c7932'

  # hashicorp.com was verified as official when first introduced to the cask
  url "https://releases.hashicorp.com/consul/#{version}/consul_#{version}_darwin_amd64.zip"
  appcast 'https://github.com/hashicorp/consul/releases.atom',
          checkpoint: '5ac89b32dd4234f5a7af642046cf8b053e704559b522e11c4672550638e5fbda'
  name 'Consul'
  homepage 'https://www.consul.io/'
  license :mpl

  binary 'consul'
end
```

I already did `brew update` and `brew cleanup` before. The `brew doctor` command doesn't tell me about any errors.

Any suggestions?

---

I just tried the non-cask variant. This seems to work:

```
$> brew install consul
==> Downloading https://homebrew.bintray.com/bottles/consul-0.6.3.el_capitan.bottle.tar.gz
######################################################################## 100,0%
==> Pouring consul-0.6.3.el_capitan.bottle.tar.gz
==> Caveats
If consul was built with --with-web-ui, you can activate the UI by running
consul with `-ui-dir /usr/local/Cellar/consul/0.6.3/share/consul/web-ui`.
==> Summary
🍺  /usr/local/Cellar/consul/0.6.3: 2 files, 19.3M
```

**Comment by slackpad** [comment]
Hi @suchkultur I think this is related to having an old Homebrew installation. These steps got things working for me:

https://github.com/caskroom/homebrew-cask/issues/15930#issuecomment-165849003

**Comment by HienNguyen711** [comment]
Try `brew cask install consul-cli`
