### ISSUE TITLE
Warn if invalid service name according to RFC-1123 and RFC-2782

### ISSUE THREAD

**Issue by sean-** [hashicorp/consul#1830]
Similar to the error installed in nomad#915, Consul should warn when a service name is registered that is invalid.  Valid service names are only allowed to begin and end in alphanumeric characters, may contain alphanum or hyphens, and must be shorter than64 characters in length.

**Comment by slackpad** [comment]
Since there are non-DNS users using services like this already, we've decided to not do this. Folks were concerned this would be a noisy change, and it's not worth adding a configuration to disable the warning.
