### ISSUE TITLE
Empty vendored prometheus packages

### ISSUE THREAD

**Issue by kamilchm** [hashicorp/consul#1835]
Is there any reason to exclude prometheus client source from vendor?

I'm trying to build consul package for NixOS in automated way, scanning dependecies but ignoring `vendor` and using it as is. When I do that my build fails because missing `github.com/prometheus/client_golang/prometheus`.

It looks like it should be included with source files or removed from `vendor` and moved to `Godeps`?

**Comment by slackpad** [comment]
Hi @kamilchm I don't think Consul itself depends on Prometheus (it is referenced by go-metrics but not used by Consul). Can you provide a little more detail about which error you are seeing?

**Comment by kamilchm** [comment]
I was trying to build consul with other custom build tool. Everything works fine when I ignore builds for {{vendor}} dir.
