### ISSUE TITLE
Incorrect error message displayed

### ISSUE THREAD

**Issue by nitinbodke** [hashicorp/consul#1838]
My "/tmp" directory had "consul" binary, leftover from "consul" installation.
Executed following command from the path where I copied it:

``` script
[admin@localhost local]$ consul agent -server -bootstrap-expect 1 \
>     -data-dir /tmp/consul -node=agent-one -bind=10.0.2.15 \
>     -config-dir /etc/consul.d
```

Expected: 
Consul should differentiate between "consul" binary and directory.
And should give proper error message.

Actual Result:

``` script
==> CRITICAL: Deprecated data folder found at "/tmp/consul/mdb"!
==> Consul will refuse to boot with this directory present.
==> See https://www.consul.io/docs/upgrade-specific.html for more information.
```

**Comment by mckennajones** [comment]
@slackpad What should the expected behavior be in this case? Should consul error out if the -data-dir points to a consul binary?

**Comment by slackpad** [comment]
We should stat the `-data-dir` and give a "not a directory" message if `IsDir()` is `true`.

**Comment by slackpad** [comment]
Despite what I said in https://github.com/hashicorp/consul/pull/2529#issuecomment-263389938, during some testing with this change merge I realized I think we were auto-creating the directory, so this might be a regression. @kyhavlov will take a look; pulling into the 0.7.2 release milestone.
