### ISSUE TITLE
Filtering a service based on multiple tags?

### ISSUE THREAD

**Issue by gt-tech** [hashicorp/consul#1841]
I have a service registered with 2 different service instance id with some variations in tag, see below on how it looks like

```
[{
	"Node": "app-registry-discovery-node1",
	"Address": "x.x.x.x",
	"ServiceID": "api-server-8000",
	"ServiceName": "api-server",
	"ServiceTags": ["dev", "provider-abc"],
	"ServiceAddress": "someserver.domain.com",
	"ServicePort": 8000
}, {
	"Node": "app-registry-discovery-node1",
	"Address": "x.x.x.x",
	"ServiceID": "api-server-8001",
	"ServiceName": "api-server",
	"ServiceTags": ["dev", "provider-xyz"],
	"ServiceAddress": "someserver.domain.com",
	"ServicePort": 8001
}]
```

If I fire a request to filter the service with filtering by just one tag it works fine ....
http://consul-server/v1/catalog/service/api-server?tag=dev - works
http://consul-server/v1/catalog/service/api-server?tag=provider-abc - works

http://consul-server/v1/catalog/service/api-server?tag=dev&tag=junk - still works but shouldn't since there's no service that has both the provided tags, it just filters on tag: dev?

Surprisingly continuing with previous example - 
http://consul-server/v1/catalog/service/api-server?tag=junk&tag=provider-abc- doesn't work so it seems that filtering is only done by the first value of "tag" in query parameters.

What's the best way to filter a specific service instance with filtering done using more than one "tags", if i am guessing it's possible.

**Comment by slackpad** [comment]
Hi @gt-tech this is currently not possible via those endpoints (see https://github.com/hashicorp/consul/issues/1781 and https://github.com/hashicorp/consul/issues/294). The only way to do this currently is using [prepared queries](https://www.consul.io/docs/agent/http/query.html) but those require a little state to be set up beforehand (create the query for multiple tags and then execute it). Closing this as a dup - please watch #1781 for updates on the other endpoints!
