### ISSUE TITLE
I want to replace domain name service.consul with mine app.local

### ISSUE THREAD

**Issue by sachinkarale** [hashicorp/consul#1842]
I am using progrium/consul docker image with gliderlabs/registrator  docker image on ubuntu .. what are the steps to change domain name.

**Comment by slackpad** [comment]
Hi @sachinkarale you can change `.consul` by configuring this option - https://www.consul.io/docs/agent/options.html#_domain. The `.service` is part of Consul's interface and can't be changed, but you can change the part after that.

**Comment by sanfx** [comment]
Hello James (@slackpad) ,

I have changed configuration for all consul client and servers to contain domain set to nyc and restarted all consul server and agent but I do not get the result of dig neither with .consul nor with .nyc ..

**Comment by jkirschner-hashicorp** [comment]
Hi @sanfx - I see that you opened https://github.com/hashicorp/consul/issues/11526 about this. We'll follow up there. Thanks!
