### ISSUE TITLE
failing only for consul service watches

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/consul#1850]
If you wanted to run a handler any time a service goes into the critical state, but only those times (and not when the service is healthy).. is there a way to do this currently via consul configs? or is a "failingonly" needed as a complement to the "passingonly"?

**Comment by slackpad** [comment]
Hi @ketzacoatl you are correct this currently isn't built-in. You'd have to look at all the edges and filter in your watch script, or we'd have to add some extra controls to the watch.

**Comment by ketzacoatl** [comment]
Adding a ``-failingonly` would be a nice compliment to the `-passingonly`. If I were to filter in the watch script, does consul pass some data to the watch script?

**Comment by slackpad** [comment]
Consul will pass your watch handler JSON data on stdin, so for a service watch you'll get the same structure as the endpoint - https://www.consul.io/docs/agent/http/health.html#health_service.

**Comment by ketzacoatl** [comment]
AH, very cool, thank you for the reference @slackpad!

**Comment by slackpad** [comment]
Closing this out as there's a way to get the behavior in the watch handler.
