### ISSUE TITLE
health check not working

### ISSUE THREAD

**Issue by shakisha** [hashicorp/consul#1853]
I have got the follow service configuration:

----------
{
  "service": {
    "name": "asterisk",
    "port": 5060,
    "checks": [
      {
        "id": "asterisk",
        "name": "Is asterisk running?",
        "script": "/usr/local/bin/asterisk_check.sh",
        "interval": "10s"
      }
    ]
  }
}
-------------

and this is asterisk_check.sh:

------------
#!/bin/bash
if pgrep "asterisk" > /dev/null
then
echo running
exit 0
else
echo not running
exit 1
fi
-------

but for some reason consul stays in this status:
> [INFO] agent: Synced service 'asterisk'

I cannot understand why is not executing the script, neither giving error in debug console.

**Comment by slackpad** [comment]
Hi @shakisha that log line is normal - that's what the agent prints when it is syncing the status of the check up to the Consul servers. Your check definition looks ok - what does the status of the check show with [this API](https://www.consul.io/docs/agent/http/health.html#health_service)?

For your case it would be something like http://127.0.0.1/v1/health/service/asterisk

**Comment by shakisha** [comment]
Hi Slackpad, thanks for your answer, i've already fixed it and i was closing the issue. 
My mistake was a bad check made, i've used the ones provided by nagius plugin and everything worked like a charm, thank you a lot
