### ISSUE TITLE
Consul leader election between data centers

### ISSUE THREAD

**Issue by nejtr0n** [hashicorp/consul#1856]
I spend a lot of time trying to make my consult available to elect leader through multiple datacenters.
Is it possible?

**Comment by slackpad** [comment]
Hi @nejtr0n this currently isn't possible. Each datacenter maintains its own pool of servers that have their own Raft-based quorum. Once the different datacenters are WAN-joined the servers can forward queries so any datacenter can access the information in another, but there's a different leader in each datacenter. This guide has more details - https://www.consul.io/docs/internals/architecture.html. Hope that helps!
