### ISSUE TITLE
latest version of Consul is not available as a rpm

### ISSUE THREAD

**Issue by taronien** [hashicorp/consul#18574]
Hello,
Latest version of Consul is 1.16.1
On https://developer.hashicorp.com/consul/downloads / Linux / CentOS/RHEL the installation procedure is still based on hashicorp.repo

```
 sudo yum install -y yum-utils
 sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
 sudo yum -y install consul
```
but latest version available is 1.13.2 (I'm currently on a centos 8, didn't check others)

Is it possible that you upgrade rpm version ?
Thanks

**Comment by david-yu** [comment]
Closing as we should now have resolve issues related to RPMs not being available. Please let us know if that is not the case.
