### ISSUE TITLE
Document a procedure for renaming DCs

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#1858]
Carry over from here - https://groups.google.com/d/msgid/consul-tool/b80a40ef-6b02-47d2-9bee-3014135ade22%40googlegroups.com?utm_medium=email&utm_source=footer. We should document some steps to do this.

**Comment by jeffbyrnes** [comment]
Is there any way to change the datacenter name & _not_ lose what’s stored in Consul’s K/V store? Specifically, I have Vault using Consul as its backing store, and I need to change the datacenter name.

**Comment by danlsgiga** [comment]
Same here... tried changing the datacenter name and completely lost access to the cluster. I have couple ACLs and even the master token was not working at all. Had to revert the name back to regain access.

**Comment by gvenka008c** [comment]
@slackpad @here I got into the same issue. Renamed the datacenter name and restarted the service. But lost access to the cluster. What would be the best steps we can follow to rename the datacenter name without affected the running cluster?

**Comment by c4milo** [comment]
@slackpad, any update on this issue?

**Comment by guidoiaquinti** [comment]
What about providing an abstraction layer that can be used to rename the `datacenter` name at runtime? I might be oversimplifying but to change datacenter name from A to B without downtime we could do something like:

1) execute `consul datacenter --alias A B`
2) change is propagated to the servers in the RAFT ring and the command is returned. From now on, all catalog/KV queries with `dc=B` are transparently renamed on the fly to `dc=A`
3) modify the agent configuration on all the clients to register to cluster B + service restart. All the clients are now registered using the new name
4) modify the agent configuration on all the servers to register as cluster B. All the nodes in the cluster are now registered using the new name 
5) we verify that there aren't anymore queries to `dc=A`
6) we drop the alias

**Comment by joewilliams** [comment]
@guidoiaquinti's procedure looks awesome and would work great for our use case as well.

**Comment by i0rek** [comment]
This is nothing that we have time to actively work on. There is however a similar mechanism to switch domains with `alt-domain`, just throwing it out there. If you want to provide a PR I would be happy to look at it and give feedback.

**Comment by nahsi** [comment]
For anyone interested, I found out that renaming datacenter in configuration and restarting ALL consul agents (including servers) at the same time just works. Catalog is working, vault and other k/v data is there.

I've tested without TLS and ACL though.
