### ISSUE TITLE
translate_wan_addrs for services?

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/consul#1862]
I noticed that if I try to ping a service DNS from a different datacenter I get the private IP, not its wan advertised address. Does node only work for this?

**Comment by slackpad** [comment]
Hi @JoeOrtiz it's in the service lookup path as well - https://github.com/hashicorp/consul/blob/master/command/agent/dns.go#L688. Do you have https://www.consul.io/docs/agent/options.html#translate_wan_addrs set to `true` on the agent that's servicing that DNS request?

**Comment by JoeOrtiz** [comment]
I do, internally it works:

PING gitlab.service.consul (10.20.4.90) 56(84) bytes of data.
64 bytes from i-2cf8XXX.node.us-west-2-XXXXXX-tools.consul (10.20.4.90): icmp_seq=1 ttl=64 time=0.392

Externally:

 root  /  work  ping gitlab.service.us-west-2-XXXXX-tools.consul
PING gitlab.service.us-west-2-xxxxx-tools.consul (10.20.4.90): 56 data bytes
^C
--- gitlab.service.us-west-2-xxxxx-tools.consul ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss


Both provide that. And I do have both translate_wan_addrs on both.

Maybe I should be pinging it through different ones ?

**Comment by slackpad** [comment]
Is it possible the WAN address isn't set properly on that node (it was unusual to configure this for a non-server node before Consul 0.6.4)? If you look at http://127.0.0.1:8500/v1/catalog/node/i-2cf8XXX does it show the WAN address you expect under `TaggedAddresses['wan']`?

**Comment by slackpad** [comment]
Never heard back - please ping back if you are still having issues.
