### ISSUE TITLE
Terraform example doesn't complete

### ISSUE THREAD

**Issue by DaveBlooman** [hashicorp/consul#1866]
Going through the terraform example, i encountered this error using the provided AMI.  I tried editing the `install.sh`, but it seems that once it finishes the first if statement, it tries to execute `service.sh` before installation has finished.

``` sh
module.consul.aws_instance.server.0 (remote-exec): Reading package lists... 94%
module.consul.aws_instance.server.0 (remote-exec): Reading package lists... 99%
module.consul.aws_instance.server.0 (remote-exec): Reading package lists... 99%
module.consul.aws_instance.server.0 (remote-exec): Reading package lists... 99%
module.consul.aws_instance.server.0 (remote-exec): Reading package lists... 99%
module.consul.aws_instance.server.0 (remote-exec): Reading package lists... Done
module.consul.aws_instance.server.0 (remote-exec): Starting Consul...
module.consul.aws_instance.server.0 (remote-exec): using upstart
module.consul.aws_instance.server.0 (remote-exec): start: Unknown job: consul
Error applying plan:

1 error(s) occurred:

* Script exited with non-zero exit status: 1
```

**Comment by slackpad** [comment]
Hi @DaveBlooman thanks for the report - we will take a look!

**Comment by moofish32** [comment]
@slackpad -- I have some time this weekend to verify and resolve if you are not working this already. I most likely introduced the issue.

**Comment by moofish32** [comment]
@DaveBlooman -- can you provide some additional details? 

Terraform version (mine is - 0.6.14)
The variable settings that differ from the defaults?

I have run terraform with a stock AWS Account in us-east-1 and us-west-2 (after subscribing to ubuntu AMIs). The only variables I have set are key name and key path.

```
State path: terraform.tfstate

Outputs:

  server_address = ec2-xx-xx-xx-xx.compute-1.amazonaws.com
```

**Comment by viroos** [comment]
I have the same issue. I probably managed to narrow down the issue a little bit:
root@ip-10-0-2-39:/home/ubuntu/scripts# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

root@ip-10-0-2-39:/home/ubuntu/scripts# init-checkconf /etc/init/consul.conf 
ERROR: File /etc/init/consul.conf: syntax invalid:
init:consul.conf:28: Unknown stanza

root@ip-10-0-2-39:/home/ubuntu/scripts# cat /etc/init/consul.conf 
description "Consul agent"

start on started networking
stop on runlevel [!2345]

respawn
# This is to avoid Upstart re-spawning the process upon `consul leave`
normal exit 0 INT

script
  if [ -f "/etc/service/consul" ]; then
    . /etc/service/consul
  fi

  # Make sure to use all our CPUs, because Consul can block a scheduler thread
  export GOMAXPROCS=`nproc`

  # Get the local IP
  BIND=`ifconfig eth0 | grep "inet addr" | awk '{ print substr($2,6) }'`

  exec /usr/local/bin/consul agent \
    -config-dir="/etc/consul.d" \
    -bind=$BIND \
    ${CONSUL_FLAGS} \
    >>/var/log/consul.log 2>&1
end script

I hope it helps.

**Comment by moofish32** [comment]
@viroos 

Direct from master I can build in a stock account. What is the error that terraform provides?

```
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: .terraform/terraform.tfstate

Outputs:

server_address = xxxxxx.us-west-2.compute.amazonaws.com
```

```
ubuntu@ip-172-31-38-121:~$ consul members
Node              Address             Status  Type    Build  Protocol  DC
ip-172-31-38-121  172.31.38.121:8301  alive   server  0.6.4  2         dc1
ip-172-31-43-170  172.31.43.170:8301  alive   server  0.6.4  2         dc1
ip-172-31-46-145  172.31.46.145:8301  alive   server  0.6.4  2         dc1
```

Terraform v0.7.4

We should probably update this to 0.7 but I think I saw a PR coming for that already.

**Comment by msawicki-stratoscale** [comment]
Thank you for the answer. Actually I used your example in my tfs. It was about two weeks ago. terraform apply worked without any issues. But the problem was that consul service was not started.

Could you provide link to PR?

**Comment by moofish32** [comment]
As for the PR I can't seem to find it quickly. The only change to make is to replace 0.6.4 [here](https://github.com/hashicorp/consul/blob/master/terraform/shared/scripts/install.sh#L15) with 0.7.0

I am confused on the error you are referencing still. If I build this here is my cli outputs matching yours:

```
ubuntu@ip-172-31-49-158:~$ cat /etc/issue
Ubuntu 14.04.3 LTS \n \l

ubuntu@ip-172-31-49-158:~$ init-checkconf /etc/init/consul.conf
File /etc/init/consul.conf: syntax ok
```

```
ubuntu@ip-172-31-49-158:~$ consul members
Node              Address             Status  Type    Build  Protocol  DC                          
ip-172-31-49-130  172.31.49.130:8301  alive   server  0.6.4  2         dc1
ip-172-31-49-158  172.31.49.158:8301  alive   server  0.6.4  2         dc1                         
ip-172-31-60-210  172.31.60.210:8301  alive   server  0.6.4  2         dc1                         
```

It appears the us-east-1 ami is slightly different version of Ubuntu, but I don't think that should be causing this problem.

**Comment by viroos** [comment]
I'm in eu-central-1 region.
The strange thing is that I manage to fix this issue by removing empty newlines (based on some stackoverflow post about upstart file syntax issues)...

I would like to try reproduce it but probably I won't manage to take care of it this week.

**Comment by slackpad** [comment]
There's been some recent cleanup on the TF examples and they are working, please reopen if you still see any issues!
