### ISSUE TITLE
Add keyring operations to the HTTP API

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#1867]
The keyring ops available [here](https://www.consul.io/docs/commands/keyring.html) should be available via an HTTP endpoint. Any automation around these now requires scripting command line ops or using undocumented client RPC methods (which we'd like to turn down).

https://github.com/hashicorp/consul/pull/1408

**Comment by ryanuber** [comment]
Just a quick note - I believe we did this because the HTTP interface was commonly exposed, and originally had no HTTPS support. It would be nice to warn/log or deny plain HTTP requests for keyring operations.

**Comment by slackpad** [comment]
This is now https://www.consul.io/api/operator/keyring.html. We didn't end up doing the HTTP deny part since HTTPS support is available, and that seems like too much of a special case.
