### ISSUE TITLE
Question about WAN configurations with many partitions

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [hashicorp/consul#1871]
Suppose I have n+1 deployments, each deployment forms a LAN DC consisting of a 3-server consul cluter, plus a bunch of other things colocated with consul agents.  1 deployment is a "central" deployment, and the other n are "children" deployments.  The requirement is that everything should obviously be able to resolve everything within its own DC.  In addition, the central DC should be able to resolve everything in every child DC, and each child DC must be able to resolve services in the central DC, but children do not need to be able to resolve addresses amongst one another.  Crucially, we have network ACLs set up so that none of the children deployments can have any traffic to/from any of the other children.

We think we can accomplish this by telling each child consul cluster to WAN join the central consul cluster.  Is there any risk in doing this, or if n is large, will the ACLs create a problem?  Do all the servers end up being part of a common WAN gossip pool where most things can't talk to most things?

We've tried this with n=2.  Everything worked as expected, except I assumed that from CHILD_DC_1 I would be able to `nslookup` service addresses in CHILD_DC_2, but just not ping those things.  However, the `nslookup` doesn't even work.  Is that okay/expected?  Or is it a sign that with large n, WAN gossip will break down and the central cluster won't be able to resolve things in the child deployment and/or the child clusters will not be able to resolve things in the central deployment?

**Comment by slackpad** [comment]
Hi @Amit-PivotalLabs, your statement _ all the servers end up being part of a common WAN gossip pool where most things can't talk to most things_ is spot on with respect to what will happen.  Unfortunately the current WAN semantics require the servers to be a fully connected mesh. This will kind of work with a few servers, but the ones that can't talk to each other will start declaring other servers failed and they will start dropping in and out of the WAN pool of servers.

We hope to have a better solution for this type of application but it's a ways away. Is there any way you can allow TCP/UDP on 8302 among just your Consul servers? If you do that, you should be able to look up things like `service.dc2.consul` from `dc1`.

**Comment by Amit-PivotalLabs** [comment]
@slackpad thanks for your incredibly fast response!  It will depend on the user whether they are willing to poke these holes in their ACLs, I suspect some will not.  Anyways, the clarification was very helpful.

Cheers,
Amit

**Comment by Amit-PivotalLabs** [comment]
@slackpad what would you have in mind for WAN semantics to support this use case?  This is something we would be happy to submit a PR for.  Is it a ways away due to complexity, priority, both?

**Comment by b** [comment]
Raft, like similar strong consensus protocols, is poorly suited to WAN deployment. For a good example of how to address federation across datacenters have a look at the use of Serf in [Nomad](https://www.hashicorp.com/blog/nomad.html)

**Comment by Amit-PivotalLabs** [comment]
@b if I understand correctly, WAN in Consul just pertains to joining nodes in a particular gossip pool; Serf is the gossip protocol implementation.  I believe the Raft consensus does not apply to WAN.

**Comment by b** [comment]
If Serf has been integrated with Consul for this that's great to know.

**Comment by bfgoodrich** [comment]
+1 for WAN not requiring every consul client be in a full mesh.

**Comment by blacked** [comment]
+1

**Comment by lhoss** [comment]
+1

**Comment by vincepii** [comment]
Can ACLs help to achieve what is required here? https://www.consul.io/docs/internals/acl.html

**Comment by slackpad** [comment]
Consul Enterprise added this in version 0.8.0 via "network areas" - see https://www.consul.io/docs/guides/areas.html.
