### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by trong** [hashicorp/consul#1872]
Consul 0.6.3, Linux amd64

I use self-signed certificates for HTTPS/2 in the private network. Health checks are failed with error:
```
Get https://X.X.X.X:1234/health: x509: certificate signed by unknown authority
```

**Comment by slackpad** [comment]
Hi @trong please take a look at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/consul-tool/03WSqxvspno. Hope that helps, and feel free to re-open or continue on that thread if you have any questions.
