### ISSUE TITLE
Consul reload makes new sockets for the same watchers.

### ISSUE THREAD

**Issue by 123BLiN** [hashicorp/consul#1874]
Hello all,
I have Consul v0.6.3. On agent we have next configuration:

- 1 keyprefix watcher
- 49 service type watchers
```
"watches": [
{
  "type": "keyprefix"
...
  "type": "service"
```
After some number of consul reload in log I start to see:
```
2016/03/24 14:28:43 [ERR] agent: Failed to invoke watch handler '/xxx': pipe2: too many open files
2016/03/24 14:28:43 [ERR] agent: Failed to invoke watch handler '/xxx': fork/exec /bin/bash: too many open files
2016/03/24 14:28:43 [ERR] agent: Failed to invoke watch handler 'xxx': fork/exec /bin/bash: too many open files
2016/03/24 14:28:43 [ERR] agent: Failed to invoke watch handler 'xxx': fork/exec /bin/bash: too many open files
2016/03/24 14:28:43 consul.watch: Watch (type: service) errored: Get http://0.0.0.0:8500/v1/health/service/xxx: EOF, retry in 5s
2016/03/24 14:32:38 [ERR] agent: Failed to invoke watch handler 'xxx': fork/exec /bin/bash: too many open files

```
I have try to check current number of open files:
```
# ls -l /proc/19062/fd
total 0
lrwx------. 1 consul consul 64 Mar 22 21:47 0 -> socket:[19713370]
lrwx------. 1 consul consul 64 Mar 22 21:47 1 -> socket:[18225069]
lrwx------. 1 consul consul 64 Mar 22 21:47 10 -> socket:[18225087]
lrwx------. 1 consul consul 64 Mar 24 13:49 100 -> socket:[18226053]
lrwx------. 1 consul consul 64 Mar 24 14:59 1000 -> socket:[19710958]
lrwx------. 1 consul consul 64 Mar 24 14:59 1001 -> socket:[19710943]
lrwx------. 1 consul consul 64 Mar 24 14:59 1002 -> socket:[19710981]
lrwx------. 1 consul consul 64 Mar 24 14:59 1003 -> socket:[19710959]
lrwx------. 1 consul consul 64 Mar 24 14:59 1005 -> socket:[19710960]
```
1014 total:
```
# ls -l /proc/19062/fd | wc -l
1014
```
So I have killed the consul and run it again:
```
# ls -l /proc/2815/fd | wc -l
127
```
than after consul reload:
```
# ls -l /proc/2815/fd | wc -l
227
```
one more time:
```
# ls -l /proc/2815/fd | wc -l
327
```
and after 9-th reload same picture in logs as above.
watchers are configured with config files.

Any help would be very much appreciated.
Thanks,
Roman

**Comment by slackpad** [comment]
Hi @123BLiN - when there are watches outstanding a `consul reload` doesn't kill them right away, but they should be killed as the queries hit their max wait time. If you wait > 5 minutes does the number of sockets start to drop?

**Comment by 123BLiN** [comment]
Hello, thank you very much for the info!
I'm closing this ticket if you think this is correct behaviour. 
In our case we tried to dynamically change number of service watchers based on number of current services, but due to this we moved to blocking queries.
