### ISSUE TITLE
Support  automatic registration of consul KV data when a node is registered/deregistered...

### ISSUE THREAD

**Issue by sean-** [hashicorp/consul#1879]
It would be very useful for configuration management systems if there was a way to register or deregister K/V entries upon joining/leaving a cluster.

https://groups.google.com/d/topic/consul-tool/rZngeFt79Ww/discussion

**Comment by slackpad** [comment]
This could be a powerful feature for metadata, and might be an alternative to that portion of https://github.com/hashicorp/consul/issues/154. It wouldn't provide the searching capabilities, but it would allow for extra data to be associated with a node for management purposes.

One way this could work:

1. Agents get configured with a KV prefix for their metadata, as well as a dictionary to populate as part of their configuration. We could have a per-agent KV prefix, or a cluster-wide prefix and we append `/nodename` to that so there's less configuration (but it's less flexible). The node record registered in the catalog will have a pointer to where a node's metadata is in the KV tree.

2. The agent syncs up its KV blob during anti-entropy, like its other data. If the servers were wiped out and rebuilt, this data would all repopulate from the agents.

3. There's a /v1/agent API that can be used to change this data programmatically and changes will be synced up.

4. To avoid tag override type confusion, we should probably always make this subtree match what the agent is holding.

5. When a node is deregistered, we delete the subtree for that node automatically as well.

**Comment by brettswift** [comment]
👍 

I came across this idea when I was experimenting with consul_template.   My nodes are managed by puppet, and so is consul.   

We auto populate some metadata via hiera and roles/profiles.    What this means is we could leverage some of the metadata there in a consul_template - to give something like HA Proxy config files more context,  or even to serve up a datacenter inventory website to show people what is out there etc. 

Without this,  I guess that is probably doable if we integrate with the key/value API, and every "node" could be a key itself, with a list of metadata keys under it..   but it seems better suited to have metadata within the  nodes consul config itself - especially when working with CM tools.

**Comment by aldgagnon** [comment]
+1 for this. 

I'd like to see this feature implemented on the Service side. It would be incredibly useful.

**Comment by slackpad** [comment]
Instead of tying to KV we ended up adding this as first-class node metadata via https://www.consul.io/docs/agent/options.html#node_meta. This shows up and can be used to query via the catalog and health APIs.
