### ISSUE TITLE
Getting Coordinate/Node update blocked by ACLs after consul upgrade to consul from 1.13.6 to 1.15.2

### ISSUE THREAD

**Issue by uttammeena** [hashicorp/consul#18815]
#### Overview of the Issue

---
Upgrade done
consul: from 1.13.6 to 1.15.2
consul-k8s: from 0.49.2 to 1.1.1

Post upgrade we are seeing these 2 warn message frequently: -
Node info update blocked by ACLs
Coordinate update blocked by ACLs

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
Output from client 'consul info' command here
```

```
Client agent HCL config
```

</details>

<details>
  <summary>Server info</summary>

```
Output from server 'consul info' command here
```

```
Server agent HCL config
```

</details>

### Log Fragments

{
	"id": "AgAAAYqVGthIDM_8gAAAAAAAAAAYAAAAAEFZcVZHdWhHQUFBcTZhZ1N0UmZiR1FBTQAAACQAAAAAMDE4YTk1MWItMWRlNi00ZGU4LWI3MTgtOTI4Y2RkMDMzMDM5",
	"content": {
		"timestamp": "2023-09-14T19:11:19.112Z",
		"host": "ip-10-89-128-9.eu-west-1.compute.internal-development",
		"service": "consul",
		"message": "Coordinate update blocked by ACLs",
		"attributes": {
			"log": {
				"level": "WARN"
			},
			"module": "agent",
			"accessorID": "6d5b1de1-ae03-7b21-00e8-5a37a6cfe208",
			"timestamp": "2023-09-14T19:11:19.112148Z"
		}
	}
}

**Comment by linuxoid69** [comment]
I have same problem

**Comment by uttammeena** [comment]
It requires agent-token for each consul node
I am able to get rid of these WARN after having updating the partition to 0
```
consul:
  server:
    updatePartition: 0
```
