### ISSUE TITLE
Telemetry hostname missing

### ISSUE THREAD

**Issue by sstarcher** [hashicorp/consul#1886]
I have telemetry turned on via

```
{
  "telemetry": {
    "statsite_address": "statsite:8125",
    "disable_hostname": false
  }
}
```

The statsite data is being shipped to influxdb.  I was expecting the data to contain the hostname, but the value is `timers.consul.raft.rpc.processHeartbeat.rate`

I also attempted to specify the node name via -node which functioned as expected, but the metric was still `timers.consul.raft.rpc.processHeartbeat.rate` and did not contain the node name.

**Comment by sstarcher** [comment]
I believe this is my misunderstanding.  It looks like info like `timers.consul.raft.rpc.processHeartbeat.rate` is global data.  I do see gauges appending the hostname `gauges.consul.ip-10-0-20-39.ec2.internal.runtime.num_goroutines
`

If that is correct I'll close this ticket.

**Comment by slackpad** [comment]
Hi @sstarcher - this is an odd one - Raft uses the `go-metrics` global so it _should_ pick up Consul's settings. Will have to dig a little to see what's going on here.

**Comment by slackpad** [comment]
Ah ok - closing per https://github.com/hashicorp/consul/issues/1886#issuecomment-204067538.
