### ISSUE TITLE
Feature Request: Prefix K/V operations based on ACL

### ISSUE THREAD

**Issue by ChrisAubuchon** [hashicorp/consul#1887]
At ACL creation time allow a K/V prefix to be defined. The prefix would be prepended to the key path of all K/V requests using the ACL and stripped from the beginning of the of the K/V path in the responses.

This would essentially amount to a chroot based on the ACL.

My main use case is for the agent ACL to have a clean namespace by giving the agent ACL a prefix (say `/agent`) without requiring all apps to use the prefix.

**Comment by sean-** [comment]
Hi @ChrisAubuchon , that's an interesting idea that we will consider.  Thanks for suggesting this.

**Comment by i0rek** [comment]
Namespaces arrived in Consul Enterprise 1.7.0!
