### ISSUE TITLE
Restart instances - causes consul not to reflect new ips

### ISSUE THREAD

**Issue by mytwilight** [hashicorp/consul#1889]
Hello

I am using consul in AWS environment. the consul configuration gets stored with node and service details with id as private ip address of the instance. Everything works ok. 

if I restart the instances, the instance's public and private ips change. As nodes and services configurations are stored with old ips, consult does not work and gives connection errors.

Is there any way that I can load the node and services automatically and update the configs.

Regards

**Comment by slackpad** [comment]
Hi @mytwilight do you know how you have https://www.consul.io/docs/agent/options.html#leave_on_terminate configured? With Consul agents (other than servers) it's generally desirable to have them leave when they shutdown and re-join when they start back up again, which should cleanly handle the transition to the new IPs.

**Comment by slackpad** [comment]
Closing against https://github.com/hashicorp/consul/issues/1580.

**Comment by kinnalru** [comment]
@slackpad what happens when consul agent(not server) terminated without posibility to send Leave command(kill -9) and rejoins with new ip?
