### ISSUE TITLE
Multiple health checks for a service - and/or config 

### ISSUE THREAD

**Issue by abhimanyuvarma** [hashicorp/consul#1892]
When I specify multiple checks for a service - is there a way i can specify that if atleast one health check is passing , the service should be in passing state . Currently it checks both chk1 and chk2 should not be in critical state for the service to be in passing/warning state. Is there a way I can specify that if either of chk1 or chk2 is passing , then the service should be in atleast warning/passing state .Only if both are in critical state , the service would be in critical state.

"checks": [ {
"id": "chk1",
      "name": "health1",
      "http": "http://abc.com",
      "interval": "15s"  
  },
  {"id": "chk2",
      "name": "health2",
      "http": "http://xyz.com",
      "interval": "15s"
    }
]

**Comment by slackpad** [comment]
Hi @abhimanyuvarma there's no built-in support for this in Consul. The best way to implement something like this is to put the logic into a script check and summarize the overall passing/warning/critical state to Consul via its return code. Hope that helps!
