### ISSUE TITLE
Consul API Gateway timeouts after 15s

### ISSUE THREAD

**Issue by wisniewski-dominik** [hashicorp/consul#19022]
#### Overview of the Issue

We are running Consul on our GKE cluster. We have Consul API Gateway deployed and configured and a couple of services (GKE Pods) running as part of Consul Service Mesh (with transparent proxy enabled). One of our services which is exposed via the Consul API Gateway (using HttpRoute) responds slowly (it can be 10 seconds but also 300 seconds to return the response). The issue is that Consul API Gateway terminates the connection to the service after 15 seconds. 

We have tried to configure/change the default (Envoy) timeout setting for Consul API Gateway using various *timeout* parameters for the following Consul configuration entries: 
1. [Proxy Defaults](https://developer.hashicorp.com/consul/docs/connect/config-entries/proxy-defaults)
2. [Service Defaults](https://developer.hashicorp.com/consul/docs/connect/config-entries/service-defaults)
3. [Service Router](https://developer.hashicorp.com/consul/docs/connect/config-entries/service-router)
4. [Service Resolver](https://developer.hashicorp.com/consul/docs/connect/config-entries/service-resolver)

The above Consul configuration entries allow setting various *timeout* parameters, but they do not configure or work with Consul API Gateway properly. 

Currently, I am looking at [Envoy Extensions](https://developer.hashicorp.com/consul/docs/connect/proxies/envoy-extensions), but I am not sure if I can use this feature to change Consul API Gateway configuration - I guess this is more about Mesh Services, and not Consul gateways. Can you, please, confirm my doubts?

I am also not sure if I can use [Escape Hatch Overrides](https://developer.hashicorp.com/consul/docs/connect/proxies/envoy#escape-hatch-overrides) to reconfigure Consul API Gateway. The Escape Hatch mechanism looks quite complex to me, so I do not want to dig into it, if this is not going to work for Consul API Gateway anyway. Can you, please, confirm my doubts?

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Deploy Consul 1.16.1 on a GKE cluster We use Consul Helm Chart v1.2.1. 
2. Create an application responding slowly (in more than 15 seconds) and deploy it into Consul Service Mesh with transparent proxy feature enabled. 
3. Crete a Gateway CRD for your Consul API Gateway deployment.
4. Create an HttpRoute CRD to expose the application through the Consul API Gateway.
5. Try to access the application through the Consul API Gateway. After 15 seconds, we consistently are getting: "HTTP 504 Gateway Timeout" with message "upstream request timeout".

### Operating system and Environment details

- Consul 1.16.1, Helm Chart v1.2.1
- GCP GKE cluster
- I can provide more Environment details but I think this is not relevant here.

Please suggest any solution.

**Comment by oliver-buckley-salmon-db** [comment]
Hi,
This is critically important for us, so please can it be prioritised?

**Comment by oliver-buckley-salmon-db** [comment]
Thanks @Jeff-Apple, that's great news.

**Comment by cthain** [comment]
Envoy extensions and escape hatch overrides are not support for Consul API Gateway at this time. Envoy extensions may be supported in the future since this is our recommended solution for customizing Envoy configuration. It is unlikely that we will ever support escape hatches since they are complicated and error prone.

**Comment by Lord-Y** [comment]
@wisniewski-dominik We've been having the same problem and were able to fix it.
Here is our config
ingress-gateway => service router production-internal => service resolver backoffice => service-defaults backoffice

In the service router production-internal, the important setting is https://developer.hashicorp.com/consul/docs/connect/config-entries/service-router#routes-destination-requesttimeout to avoid the 15s timeout.

Hope that will help you.

**Comment by wisniewski-dominik** [comment]
Thanks, we also were able to configure it successfully. The ticket can be closed as resolved.
