### ISSUE TITLE
Runtime error on Windows Consul 0.6.3

### ISSUE THREAD

**Issue by calvn** [hashicorp/consul#1903]
The consul agent in that node is experiencing serf health flapping issue. There were instances where the consul UI showed that the service health checks on that node were passing, but the serf health status was critical. There were runtime errors that occurred, so I suspect it might be related.

[consul-error.log.log.txt](https://github.com/hashicorp/consul/files/196464/consul-error.log.log.txt)

**Comment by slackpad** [comment]
Hi @cleung2010 thanks for the report. The only similar issue I've seen is https://github.com/hashicorp/consul/issues/1248, which we never got to the bottom of.

**Comment by slackpad** [comment]
Hi @calvn haven't seen any similar reports to this one. Have you seen this again with any of the newer versions of Consul built with newer Go versions?

**Comment by slackpad** [comment]
Haven't seen anything else related to this one, closing it out.

**Comment by calvn** [comment]
Hey @slackpad sorry for the delayed response, the issue was no longer being reported on our end so it's good to close.
