### ISSUE TITLE
Feature Request: Allow searching keys/values from the GUI

### ISSUE THREAD

**Issue by rom-stratoscale** [hashicorp/consul#1905]
Would be really useful. 
Not always we remember the names of the keys or want to know a current value.

**Comment by slackpad** [comment]
Hi @rom-stratoscale - this would require some Consul API support to do properly. Consul currently doesn't care about or index the values, so it's not likely we'd search those, and we currently don't have an index that can do general searches over keys, so we'd need to think about the best way to support something like this.

**Comment by awmanoj** [comment]
agree with @slackpad. i needed the same functionality and i was able to setup something to help me by combining `consul template`, `elastic search` and `elasticui` (an `angularjs` based UI over ES). It's a `quick & dirty` solution - done with minimal coding - within couple of hours. 

https://github.com/awmanoj/consul-search

**Comment by slackpad** [comment]
We are going to close this one out - this adds considerable complexity to Consul and hasn't had a ton of community interest. It looks like there's a nice workaround for folks who really need it using external tools.
