### ISSUE TITLE
surprised by the  packaging way of consul!

### ISSUE THREAD

**Issue by sunfaces** [hashicorp/consul#1913]
Hi all ，
    I've  found  that all your assets、static resource and go sources are packaging into  a  single binary file! so can you tell me how to packaging in that way? 
   Thanks~

**Comment by slackpad** [comment]
Hi @sunfaces please take a look at these spots, which have all the details:

https://github.com/hashicorp/consul/blob/master/GNUmakefile#L53-L58

https://github.com/hashicorp/consul/blob/master/command/agent/bindata_assetfs.go

https://github.com/hashicorp/consul/blob/ea62d297565a1fec78bfa66e43beeecb504d13d5/command/agent/http.go#L283

It's all based on https://github.com/elazarl/go-bindata-assetfs.

Hope that helps!
