### ISSUE TITLE
Charset instruction in 'application/json' response

### ISSUE THREAD

**Issue by maxnasonov** [hashicorp/consul#1921]
What do you think about adding "charset=utf-8" to the api responses? I do understand that is not standard http://www.iana.org/assignments/media-types/application/json, but it is still a common practice, isn't it?
Motivation for me is to work around python-consul issue when requests library fails to determine the encoding gracefully for large responses when it is not explicitly given.

**Comment by slackpad** [comment]
Hi @maxnasonov - this looks pretty reasonable and I found some examples in the wild. It seems from the spec that it's harmless to add.

**Comment by slackpad** [comment]
Hi, this never made it on the roadmap, and it's not a very high priority for us. We would gladly review a PR for this functionality, but we are going to close this issue since it's not something we are going to implement ourselves.
