### ISSUE TITLE
Session.RenewPeriodic returns even if session is not expired

### ISSUE THREAD

**Issue by deadok22** [hashicorp/consul#1922]
In case doneCh is closed, Session.RenewPeriodic attempts to destroy a session and returns regardless of whether the session was actually destroyed.

Session.RenewPeriodic should only return when session destroy succeeds, or TTL expires.

**Comment by slackpad** [comment]
Hi @deadok22 `Session.RenewPeriodic` is almost always run as goroutine, so the destroy is a best effort and Consul will clean up after the TTL otherwise. Is there a specific use case you are trying to address?

**Comment by deadok22** [comment]
Hi @slackpad!

I'm doing leader election with Consul and I wanted to use a return from ```Session.RenewPeriodic``` as a signal that the leadership is lost in case it was held. 

I can still achieve the desired behavior if I wrap around the close signal and abdicate before sending the actual close signal to ```Session.RenewPeriodic```.

**Comment by slackpad** [comment]
Hi @deadok22 we actually do that with a separate routine that's waiting on the key itself:

https://github.com/hashicorp/consul/blob/master/api/lock.go#L353-L380

That's kind of a more direct check (like if the operator deleted the key but the session was still around, etc.). When the lock is lost, then we stop updating the session, but don't care about its return:

https://github.com/hashicorp/consul/blob/master/api/lock.go#L153-L159

Hope that helps!
