### ISSUE TITLE
consul exec should not escape quotes on windows platform

### ISSUE THREAD

**Issue by jirkafajfr** [hashicorp/consul#1923]
I am running following configuration:
- chf01-pmtrm05 - consul 0.6.4 / CentOS 7.2
- chf01-pmweb20 - consul 0.6.4 / Windows Server 2012 R2

```
consul exec echo '"Hi"'
    chf01-pmtrm05: Hi
    chf01-pmtrm05:
==> chf01-pmtrm05: finished with exit code 0
    chf01-pmweb20: \"Hi\"
    chf01-pmweb20:
==> chf01-pmweb20: finished with exit code 0
```

when i am trying to pass quotes which should be evaluated by bash/cmd on target machine. Windows version ends up escaping quotes which is not correct.

**Comment by slackpad** [comment]
Closing this against https://github.com/hashicorp/consul/issues/2999.
