### ISSUE TITLE
stdin for consul exec doesn't work on windows

### ISSUE THREAD

**Issue by jirkafajfr** [hashicorp/consul#1924]
I am running following configuration:
- chf01-pmtrm05 - consul 0.6.4 / CentOS 7.2
- chf01-pmweb20 - consul 0.6.4 / Windows Server 2012 R2

```
echo 'echo Hi' | consul exec -
    chf01-pmtrm05: Hi
    chf01-pmtrm05:
==> chf01-pmtrm05: finished with exit code 0
    chf01-pmweb20: 'C:\Users\vagrant\AppData\Local\Temp\rexec223480077' is not recognized as an internal or external command,
    chf01-pmweb20: operable program or batch file.
    chf01-pmweb20:
==> chf01-pmweb20: finished with exit code 1
```

windows version is trying to execute name of key instead of command itself

**Comment by slackpad** [comment]
Closing this against https://github.com/hashicorp/consul/issues/2999.

**Comment by slackpad** [comment]
The stdin version still does shell escaping, but as of #3509 you can pass `-shell=false` to `consul exec` to get it to pass your arguments without any shenanigans.
