### ISSUE TITLE
consul cluster never synchronizes

### ISSUE THREAD

**Issue by gdean123** [hashicorp/consul#1929]
Hi Hashicorp,

During our deployment of consul clusters, we validate that the cluster is working and synchronized by comparing the last_log_index to the commit_index, as reported by ConsulRPCClient.Stats(). As indicated by issue https://github.com/hashicorp/consul/issues/1092, it seems like if those numbers match then the node has successfully synchronized with the cluster.

Unfortunately, we are seeing a strange issue where the commit index stays at 0 forever, while the last log index is at 327 (so they never match). We hypothesize that for the commit index to stay at 0 forever, no leader election could ever have occurred since it seems like that alone bumps the commit index by ~10. If this is true, then we are surprised to see that the last log index is higher than the commit index since the node should reject writes in the absence of a leader. What do you think might be going on here?

Right after we see that the last_log_index is 327 and the commit_index is 0, consul writes this error message: [WARN] raft: Failed to get previous log: 575 log not found (last: 229411). This seems to indicate a discrepancy between the response from the stats RPC endpoint and the consul log, if we are correctly interpreting 229411 as the last_log_index. We also don't understand why this node would be trying to fetch log 575 if it already knows about all of the logs up through 229411.

```
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
2016/03/16 18:41:48 [WARN] raft: Failed to get previous log: 575 log not found (last: 229411)
2016/03/16 18:41:49 [WARN] raft: Failed to get previous log: 574 log not found (last: 229411)
2016/03/16 18:41:49 [WARN] raft: Failed to get previous log: 560 log not found (last: 229411)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
2016/03/16 18:41:50 [WARN] raft: Failed to get previous log: 573 log not found (last: 229411)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
2016/03/16 18:41:53 [WARN] raft: Failed to get previous log: 572 log not found (last: 229411)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
ConsulRPCClient.Stats() returns "commit_index":"0","last_log_index":"327" (not synced)
2016/03/16 18:41:58 [WARN] raft: Failed to get previous log: 571 log not found (last: 229411)
```

Thanks,
George & @kkelani

**Comment by slackpad** [comment]
Hi @gdean123 and @kkelani - I'm wondering if somehow you've got a rogue server with `-bootstrap` that's started itself as a leader and is sending bogus AppendEntries calls to cluster members that were part of an earlier quorum with an index way ahead, and where log compaction for 327 happened long ago.

Can you give some more details about your setup, what kind of steps you are performing when this happens, and maybe link some gists with more complete logs from the new server and one of the existing ones?

**Comment by kkelani** [comment]
Hi @slackpad. Thanks for the response. We have limited logs and info because this is occurring from one of the users of our application however here is the info that we know:

- The setup is a 3-node cluster and started with `-bootstrap-expect`
- The user was performing an application upgrade which triggered a rolling deploy
- The following logs are from a client that was connected to the cluster which contains event logs
- After a certain amount of time, if the client is unable to verify sync (by comparing the commit_index and the last_log_index) with the cluster, the client will kill the consul agent and then retry.

Gist: https://gist.github.com/kkelani/97147077b5f1d26cc477c0cbdaca6873

Thanks
@christianang & @kkelani

**Comment by slackpad** [comment]
Hi @kkallday thanks for the info. I get a 404 with that gist - can you please take a look at the URL? Thanks!

**Comment by kkallday** [comment]
Hey - sorry about that. The link was broken due to my username change. This link should work: https://gist.github.com/kkallday/97147077b5f1d26cc477c0cbdaca6873

**Comment by zankich** [comment]
Hey @slackpad did the gist help uncover any useful information? We are still experiencing this bug.

**Comment by slackpad** [comment]
Sorry for the delay - it's still not clear what's going on. Can you compare the Raft peers.json contents on all the servers involved and see if they match up?

**Comment by slackpad** [comment]
Closing this as we never heard back. Please let us know if you still need help.
