### ISSUE TITLE
`consul join` / retry_join doesn't know how to lookup mDNS names on Linux

### ISSUE THREAD

**Issue by EvanKrall** [hashicorp/consul#1932]
In my home setup, I'm using mDNS for my boxes' identities so I don't have to bother setting up a name server. On Linux with [e]gibc, if you add mdns4_minimal to your nsswitch.conf, most programs will look up `*.local` hostnames with mDNS.

However, consul appears not to respect this:

```
$ consul join storage1.local
Error joining the cluster: lookup storage1.local on 192.168.1.1:53: no such host
```

I suspect this is because consul is not dynamically linked against libc:

```
$ ldd `which consul`
    not a dynamic executable
```

I notice [these fine people](https://github.com/hashicorp/mdns) have written a golang mdns library. Maybe that could be incorporated?

**Comment by slackpad** [comment]
Hi, this never made it on the roadmap, and it's not a very high priority for us. We would gladly review a PR for this functionality, but we are going to close this issue since it's not something we are going to implement ourselves.
