### ISSUE TITLE
Using consul api imports "testing"

### ISSUE THREAD

**Issue by chnrxn** [hashicorp/consul#1933]
I have a skeletal main.go that simply uses api.DefaultConfig(), thus importing the consul/api package, and `go run main.go -h` shows all the `-test.*` flags. How can they be excluded?

```
package main
import (
	"flag"
	"log"

	"github.com/hashicorp/consul/api"
)
func init() {
	flag.Parse()
}
func cons(src interface{}) {
	api.DefaultConfig()
}
```

**Comment by slackpad** [comment]
Hi @chnrxn I tried to reproduce this but couldn't. Here's the main I used:

```
package main

import (
        "flag"

        "github.com/hashicorp/consul/api"
)

func main() {
        flag.Parse()
}

func cons(src interface{}) {
        api.DefaultConfig()
}
```

And I get this output:

```
$ go run main.go -h
Usage of /var/folders/q_/fvcn55l55cl01tst9rvynlmc0000gn/T/go-build505670756/command-line-arguments/_obj/exe/main:
exit status 2
```

Doing a `grep` looks like only unit tests pull in the package:

```
$ grep -rl \"testing\" api/*
api/acl_test.go
api/agent_test.go
api/api_test.go
api/catalog_test.go
api/coordinate_test.go
api/event_test.go
api/health_test.go
api/kv_test.go
api/lock_test.go
api/prepared_query_test.go
api/semaphore_test.go
api/session_test.go
api/status_test.go
```

I bet there's some other package in your app that's importing `testing`. If that's not the case, can you please re-open this and attach a test case the compiles and shows the issue? Thanks!

**Comment by chnrxn** [comment]
Hi James, 

The issue is seen when compiling with tag v0.6.4 but not in master. We have just deployed consul 0.6.4 to our cluster, hence compiling our tools against the same version.

We have also vendored 0.6.4 in our own source repo.

Do you have a recommended rev/tag for us to update to, while keeping compatibility with 0.6.4?

Thanks!

**Comment by slackpad** [comment]
Ah ok - that makes total sense (I was testing with master). Here's the Serf change where the fix came in - https://github.com/hashicorp/serf/pull/373.

I looked through the changes to /consul/api since 0.6.4 and there's nothing there so far that would break compatibility with 0.6.4, so you should be able to use current HEAD `7247076` to avoid this issue. Sorry for the trouble.
