### ISSUE TITLE
Seeing more consul members that expected

### ISSUE THREAD

**Issue by Lax77** [hashicorp/consul#1939]
In the same Security Group (On the Open stack cloud provider) I happened to have multiple clusters running, e.g.: Cluster1 (having a master and couple of workers) and Cluster2(with a master and couple of workers), to begin with consul in each cluster sees its own members. After a while of running some how Consul on Cluster1 end up seeing the members from other cluster(cluster2).

When I run cluster members --detailed on Cluster1, I end up seeing members more than what Cluster1 supposed to see.  One more thing is all these clusters within same security group are also being spawned with same datacenter name. 

Is this expected behavior? if I were launching multiple clusters within same security group, should I be using different data center name? Also why does I see more consul members only after many days/weeks of launching my cluster?

**Comment by slackpad** [comment]
Hi @Lax77 Consul tries really hard to keep the cluster together for nodes with the same datacenter. A super common way that merges happen like this is when IP addresses are reused. If you want to separate the clusters within the same network you should definitely assign them different datacenters, and good measure is to set them up with different encryption keys. Hope that helps!
