### ISSUE TITLE
HTTP API enhancement to get detailed /v1/catalog/services?

### ISSUE THREAD

**Issue by atomantic** [hashicorp/consul#1943]
Is there a way to call `/v1/catalog/services` and get the contents of `/v1/catalog/service/{name}` as the array value in the output?

For example, current behavior is:
```
curl /v1/catalog/services
{"consul":[],"app":[]}
```
```
curl /v1/catalog/service/app
[
   {
      "ServicePort" : 4104,
      "Address" : "172.17.0.3",
      "Node" : "671635e38ff0",
      "ServiceAddress" : "172.17.0.5",
      "ServiceName" : "app",
      "ServiceTags" : null,
      "ServiceID" : "app-2c4c225bc31c"
   }
]
```

is there a way to get this?

```
curl /v1/catalog/services
{"consul":[
...
],"app":[
   {
      "ServicePort" : 4104,
      "Address" : "172.17.0.3",
      "Node" : "671635e38ff0",
      "ServiceAddress" : "172.17.0.5",
      "ServiceName" : "app",
      "ServiceTags" : null,
      "ServiceID" : "app-2c4c225bc31c"
   }
]}
```

**Comment by slackpad** [comment]
Hi @atomantic there's currently not an endpoint that will emit the services in one big data structure like that. It currently takes an initial query to get the list of services followed by a separate query per service. What kind of use case are you thinking the full query would be useful for?

**Comment by atomantic** [comment]
I have a service-status dashboard UI, sort of like the consul UI--but at a higher level and with specific buttons to request verbose status output of each service. I'd like to query the consul catalog to get a list of all services running with their endpoints so I can automate building the list of available services.

I actually need to go up one more level so this might not be the right way to go about it anyway--I'm just investigating now. We have a lot of service stacks and my status dashboard is a UI that displays status of services across product stacks, which means several consul clusters. So in effect, I need to setup a registry of registries to be able to query that and get all the services beneath each stack. I'm looking for the least number of API queries to get that information :)

**Comment by slackpad** [comment]
I see. It sounds like you will be able to get something workable with the current APIs - please let me know if you have any more questions!

**Comment by erik-stephens** [comment]
Chiming in with my use case: as a load balancer, I'd like to query all active ServiceAddress & ServicePort in one shot so that round-trips to consul can be minimized.
