### ISSUE TITLE
DNS interface behavior during leader re-election

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/consul#1945]
Hello.

I have a consul cluster(5 masters + about 20 clients), all running 0.6.4. I use consul dns service(native one, not HTTP one) a lot and all hosts provide some kind of services. So on all nodes default dns servers in resolv.conf are consul ones(consul use recursors for external resolving).

So, my current problem is what if cluster decides to do a re-election for some reason:
```
Apr 12 13:58:17 vm105525 consul[23747]: dns: request for {db-profile-stage.node.flops.consul. 1 1} (968.781µs) from client 10.7.14.243:42582 (udp)
Apr 12 13:58:17 vm105525 consul[23747]: dns: request for {db-profile-stage.node.flops.consul. 28 1} (299.199757ms) from client 10.7.14.243:48575 (udp)
Apr 12 13:58:18 vm105525 consul[23747]: raft-net: Failed to decode incoming command: read tcp 10.7.66.144:8300->10.7.14.243:36188: read: connection reset by peer
Apr 12 13:58:18 vm105525 consul[23747]: dns: rpc error: rpc error: No cluster leader
```

All dns requests while re-election in progress are failing and it's like 1-2 seconds of the downtime.

Does this expected? If so, what should I do to make sure my services survive re-election?

**Comment by sc0rp10** [comment]
+1

**Comment by Oloremo** [comment]
Workaround explained in #1888
