### ISSUE TITLE
Enable a client token to destroy itself

### ISSUE THREAD

**Issue by joelthompson** [hashicorp/consul#1946]
I'd like to be able to have a client destroy its own token. Currently, destroying a token requires knowing both the ID of the token to destroy as well as a management token ID. I don't want to destroy the token on the client node (because that would expose the management token to the client node), which means I need to do the destroy on a highly trusted node that's joined to the Consul cluster (either a Consul server itself, or some other central management node if one exists).

It just feels wrong that, to destroy a token for what could be a very security-insensitive service, it requires getting access to a very security-sensitive secret. It's yet another place where I could make a mistake and accidentally leak this data.

**Comment by ChipV223** [comment]
Hi @joelthompson !

In case you were not aware, with the new ACL system introduced with the release of Consul v1.4.0, you now can set a ttl for an ACL token during its create via the `consul acl token create` CLI command. You read more about this [here](https://www.consul.io/commands/acl/token/create) in our documentation

I'll go ahead and close this, but do reach out if you have any additional questions!
