### ISSUE TITLE
How to list multi services with wildcard

### ISSUE THREAD

**Issue by wxjs33** [hashicorp/consul#1953]
Is there any way to list multi services with wildcard?
Example:
List "\*.web.service.consul"
Need to list apache.web.service.consul and nginx.web.service.consul

How to do it, thanks

**Comment by wxjs33** [comment]
Is there any way to do that?

**Comment by slackpad** [comment]
Hi @wxjs33 that should be possible with this endpoint - https://www.consul.io/docs/agent/http/catalog.html#catalog_service.

http://localhost:8500/v1/catalog/service/web?tag=apache
http://localhost:8500/v1/catalog/service/web?tag=nginx
