### ISSUE TITLE
Consul cluster restart not elect new leader

### ISSUE THREAD

**Issue by panda87** [hashicorp/consul#1958]
Hi

I have a situation the I have aws test env which is scheduled, which means that it automatically taken down every night and weekends and start on every morning (not include weekends)

I already built the env with Terraform, but now when I test this scenario of start the env, im getting this

```
2016/04/18 12:07:56 [ERR] agent: failed to sync remote state: No cluster leader
2016/04/18 12:08:11 [ERR] agent: coordinate update error: No cluster leader
```

I read some issues which opened and the outage documentation page but I still not understand how my consul cluster could be re setup again with leader election, but without the need to manually modify the peers.json file?

My conf file is pretty basic, but for my tests and after I read the issues I added the following fields:

```
"start_join": ["10.10.1.44", "10.10.2.150", "10.10.1.29"],
"skip_leave_on_interrupt": true,
"leave_on_terminate": true,
```

But nothing changed.
Im using version 0.6.0

Thanks
D.

**Comment by moofish32** [comment]
@panda87 I assume your private IP addresses are changing on restart unless you have configured ENIs to control private IP space. If managing IPs is your issue you can use a null resource like [here]( https://github.com/hashicorp/best-practices/blob/6a6fa8d3730309dc4e526668d19edd2e2427d3c8/terraform/modules/aws/data/consul/consul.tf#L73-L98) to get the desired behavior you are after. You will obviously have to tweak that example a bit to fit your needs. I would remove the start_join and configure the null resource to join on change of private IPs. 

The other option is try out Atlas.

**Comment by panda87** [comment]
Thanks @moofish32, but you may didn't understand my question, so thanks, I will clear it up.
I already setup my env, including the consul cluster.
My scheduling process runs only after Terraform finished to setup the env.

**Comment by moofish32** [comment]
@panda87 - do you have sample code for what you are trying to do? I am confused on where the code snippets above line up to your process.

**Comment by panda87** [comment]
I don't have the finish script that stop \ start all the instances in the VPC, but it's simple.
Currently In doing that manually from aws console, just for the tests.
The procedure is that once I create a certain VPC as my production env, and once I have it, I run a script from remote server that response on the scheduling of the instances in the VPC.
The code \ errors above are from Consul after I stop it's instances (cluster) and then start it again to see how the Consul cluster is behave.
Unfortunately, when the start again the VPC including Consul cluster, the leader is not elected, and then Im getting the `no cluster leader` error.

**Comment by moofish32** [comment]
@panda87 - I'll cautiously warn you that I think the path you are on is probably not in line with best practices (but you would have to get somebody from Hashicorp to verify). 

If you log into the instances (consul servers) and manually join the nodes does it work?

Also if the env is automated with Terraform, why not just Terraform destroy and Terraform apply to automate the tear down and setup each day?

**Comment by panda87** [comment]
@moofish32 - I know that this scenario is not expected and not by design, but still, I want to make sure whether this scenario I can work with or not.
Second, my env is pretty big with many components, part of them are still not fully automated, so I prefer to keep the env and not rebuild it every morning.

**Comment by hehailong5** [comment]
I was facing the same issue until I clean up the dirs specified by -data-dir

**Comment by moofish32** [comment]
@panda87 - I'm happy to keep attempting to help. @hehailong5 has an interesting suggestion. 

However this might be a better convo to move the google groups forum versus an issue here?

**Comment by slackpad** [comment]
@panda87 did you figure out a solution for this?

**Comment by panda87** [comment]
Yes, thanks
I also think it's been resolved in version 8.x
