### ISSUE TITLE
catalog/services details dissapears

### ISSUE THREAD

**Issue by sanjoyb** [hashicorp/consul#1960]
I have a 3 nodes consul cluster. Each has a configuration

```
"server": true,
"datacenter": "dc-1",
"data_dir": "/data",
"log_level": "INFO",
"enable_syslog": true,
"start_join": ["ip1", "ip2", "ip3"],
"bootstrap_expect": 3,
```

"ports": {
            "dns": 5353,
            "http": 8080
         }

All of the nodes are part of the clusters. At this point 
/v1/status/leader
/v1/status/peers 
/v1/catalog/services 
show correct information.

Now, I stop the first node (ip1). One of the other node becomes leader. Upon querying /v1/catalog/services on other 2 nodes start returning empty result.
- Connection #0 to host 10.16.3.141 left intact
  {
  "consul": []
  }

When I bring back the first node, after sometime the api started returning all services again.  The issue is reproducible consistently. It also does not happen when I bring down nodes with ip2 or ip3. It happens only for the first node in the start_join list.

Any help in understanding the issue ?

Thanks,
Sanjoy

**Comment by slackpad** [comment]
Hi @sanjoyb thanks for reporting an issue - this is an odd one. Can you provide some logs from when this happens? It would be interesting to see if something is happening to the quorum.

**Comment by slackpad** [comment]
Closing this as we never heard back. Please let us know if you still need help.
