### ISSUE TITLE
Can't see metrics from prometheus in consul UI: agent.ui_metrics_proxy: target URL path is not allowed:

### ISSUE THREAD

**Issue by makuartur** [hashicorp/consul#19662]
Cant't view metrics of my services in consul UI (403 error)
<img width="959" alt="image" src="https://github.com/hashicorp/consul/assets/58103928/6c7863fd-4cd8-4e63-8491-295ca6828b49">
```
root@consul-master3:/etc/consul.d# uname -r
5.15.0-88-generic
root@consul-master3:/etc/consul.d# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@consul-master3:/etc/consul.d#
```
Consul version:
```
root@consul-master3:/etc/consul.d# consul version
Consul v1.17.0
Revision 4e3f428b
Build Date 2023-11-03T14:56:56Z
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
root@consul-master3:/etc/consul.d#

```
Consul server config:
```
root@consul-master3:/etc/consul.d# cat /etc/consul.d/consul.hcl
connect {
  enabled=true
}
ports {
  grpc = 8502
}
server=true
retry_join=["consul-master1:8301", "consul-master2:8301", "consul-master3:8301"],
bootstrap_expect=3
ui_config {
  enabled = true
  metrics_provider = "prometheus"
  metrics_proxy {
    base_url = "http:/prometheus1:9090"
  }
}
log_level = "debug"
log_file = "/var/log/consul.log"
encrypt = "s0YeZsTlnWqyckTMp4XG2r9Nxl3fDt2o1UWwRffYUuo="
client_addr = "0.0.0.0"
bind_addr = "0.0.0.0"
data_dir = "/opt/consul"

root@consul-master3:/etc/consul.d#

```
Prometheus version running on another server (prometheus1):
```
root@prometheus1:/home/makuartur# prometheus --version
prometheus, version 2.31.2+ds1 (branch: debian/sid, revision: 2.31.2+ds1-1ubuntu1.22.04.2)
  build user:       team+pkg-go@tracker.debian.org
  build date:       20230502-12:17:56
  go version:       go1.18.1
  platform:         linux/amd64
root@prometheus1:/home/makuartur#
```
log from consul server after some curling:
`2023-11-16T14:41:48.310Z [ERROR] agent.ui_metrics_proxy: target URL path is not allowed: base_url=http:/prometheus1:9090 path=/api/v1/query target_url=http:/prometheus1:9090/api/v1/query path_allowlist=["/api/v1/query", "/api/v1/query_range"]
2023-11-16T14:41:48.310Z [DEBUG] agent.http: Request finished: method=GET url="/v1/internal/ui/metrics-proxy/api/v1/query?query=sum(rate(envoy_cluster_upstream_rq_completed%7Bconsul_destination_service%3D%22backend%22%2Cconsul_destination_datacenter%3D%22dc1%22%2Cconsul_destination_namespace%3D%22default%22%7D%5B15m%5D))%20by%20(consul_source_service%2Cconsul_source_datacenter%2Cconsul_source_namespace)&time=1700143978.532" from=127.0.0.1:49040 latency="477.419µs"
2023-11-16T14:41:48.333Z [ERROR] agent.ui_metrics_proxy: target URL path is not allowed: base_url=http:/prometheus1:9090 path=/api/v1/query target_url=http:/prometheus1:9090/api/v1/query path_allowlist=["/api/v1/query", "/api/v1/query_range"]
2023-11-16T14:41:48.333Z [DEBUG] agent.http: Request finished: method=GET url="/v1/internal/ui/metrics-proxy/api/v1/query?query=sum(rate(envoy_cluster_upstream_rq_completed%7Bconsul_destination_service%3D%22backend%22%2Cconsul_destination_datacenter%3D%22dc1%22%2Cconsul_destination_namespace%3D%22default%22%7D%5B15m%5D))%20by%20(consul_source_service%2Cconsul_source_datacenter%2Cconsul_source_namespace)&time=1700143978.532" from=127.0.0.1:49052 latency="299.192µs"
`
curl example:
`curl -vvv http://consul-master3:8500/v1/internal/ui/metrics-proxy/api/v1/query?query=sum(rate(envoy_cluster_upstream_rq_completed%7Bconsul_destination_service%3D%22backend%22%2Cconsul_destination_datacenter%3D%22dc1%22%2Cconsul_destination_namespace%3D%22default%22%7D%5B15m%5D))%20by%20(consul_source_service%2Cconsul_source_datacenter%2Cconsul_source_namespace)&time=1700143978.532';`
What am I doing wrong?

**Comment by huikang** [comment]
Are you able to retrieve consul metrics from the Prometheus UI?

`2023-11-16T14:41:48.310Z [ERROR] agent.ui_metrics_proxy: target URL path is not allowed: ` this line looks suspicious.

**Comment by nickwales** [comment]
Hard to tell if this is the problem but it looks like you're missing a forward slash in the URL

    base_url = "http:/prometheus1:9090" 

should be

    base_url = "http://prometheus1:9090"

**Comment by makuartur** [comment]
> Hard to tell if this is the problem but it looks like you're missing a forward slash in the URL
> 
> ```
> base_url = "http:/prometheus1:9090" 
> ```
> 
> should be
> 
> ```
> base_url = "http://prometheus1:9090"
> ```

i am such an idiot, i guess you are right, thank you very much
