### ISSUE TITLE
register watches through API

### ISSUE THREAD

**Issue by fdhex** [hashicorp/consul#1967]
Is it possible to register watches through an API call?

We have dynamic services registration/deregistration and would like to monitor their status. Initially we used checks watches, but this does not really work for hosted service (e.g. the node fails, but the checks status stays green...). If not through the API, what would be the optimal way to achieve this?

**Comment by slackpad** [comment]
Hi @fdhex the best way to monitor service status is to register checks with your service using the [Agent API](https://www.consul.io/docs/agent/http/agent.html). If you query Consul via DNS the node's health is always factored in, so services for an unhealthy node will not be returned. Similarly, when pulling service health from the HTTP APIs, the node-level health checks are also included in the response so you can filter appropriately. You are correct that the health status for the service might show healthy, but it's always possible to factor in the node's health, too. That way you can see the state of everything at the time the node died. Hope that helps!
