### ISSUE TITLE
KEY/VALUE is in-accessible on my BareOS machine

### ISSUE THREAD

**Issue by NileshTembhre** [hashicorp/consul#1968]
Hi,
I have following RACE machine.
rdcesx13193.race.sas.com (BIRD Daily RPM Image (Fri) - BIRD Daily RPM Gold Image (Fri))

* STEPS TO REPRODUCE:
1) Hit following consul url:
http://rdcesx13193.race.sas.com:8500
2) It will take user to:
http://rdcesx13193.race.sas.com:8500/ui/#/va-1000-16w33-dailyfribosimg-bcisas/services
3) Now click on 'KEY/VALUE' button.
4) It throws 500 error:
HTTP error code from Consul: 500 Internal Server Error

This is an error page for the Consul web UI. You may have visited a URL that is loading an unknown resource, so you can try going back to the root.

Otherwise, please report any unexpected issues on the GitHub page.
---------------------------------------------------------------------------------------

Could you please help?

Thanks and regards,
Nilesh

**Comment by slackpad** [comment]
Hi @NileshTembhre - unfortunately I'm not aware of any details about this Consul configuration. Can you please contact the folks that provided this instead?

If you have access to the Consul logs and enable debug mode it may shed light on where the 500 error is coming from. If it looks like a core Consul issue and you can get repro steps/logs please feel free to open up another issue.
