### ISSUE TITLE
consul in production

### ISSUE THREAD

**Issue by yagnik** [hashicorp/consul#1987]
Hey @sean- @slackpad, we are looking to use consul in production but constantly hear that it may not be production ready. Will it be possible for you to share some large organizations which are using it in prod for us to touch base with. Would love to hear your opinion on the same too.

For reference we are looking ~ 6k vm running right now and moving to multiple docker containers per host very soon across 3 data centres. 

I'm fairly certain this question has been asked a billion times so I apologize in advance if it's already answered somewhere.

**Comment by slackpad** [comment]
Sorry this got lost in the shuffle! Here are some large users sharing their experiences:

1. https://blog.froese.org/2016/04/08/srecon-running-consul-at-scale/
2. https://www.youtube.com/channel/UC-AdvAxaagE9W2f0webyNUQ/search?query=consul

There are a ton of companies using Consul in production at very large scale (some in the 10s of thousands of nodes). See also https://www.hashicorp.com/products/consul/ and/or reach out to hello@hashicorp.com if you'd like to talk to folks here directly.

**Comment by yagnik** [comment]
thanks!
