### ISSUE TITLE
Deprecate child process reaping

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#1988]
Now that we've got an [official Consul image](https://hub.docker.com/_/consul/) that does child process reaping via [dumb-init](https://github.com/Yelp/dumb-init), we should remove the child process reaping features baked into Consul itself. These work properly, but they have complex interactions with Consul's other uses of child processes, so they present a maintenance headache going forward.

**Comment by jippi** [comment]
👎 people still may opt out of that option and roll their own image, where the reaping would be beneficial

**Comment by slackpad** [comment]
Hi @jippi it's definitely true that not everybody will want to use the official image, but it's pretty simple to configure something outside of Consul to do the reaping in your own container, so we will document that. The [reap lock](https://github.com/hashicorp/go-reap/blob/master/reap_unix.go#L23-L29) is just plain ugly and it's super easy to forget to do it in the code and introduce subtle errors, so that doesn't seem worth the liability. Adding reaping inside the container was basically just a matter of including `dumb-init` and adding a [single line](https://github.com/hashicorp/docker-consul/blob/master/0.6/docker-entrypoint.sh#L1) to the entrypoint, which is a lot cleaner.

**Comment by jippi** [comment]
@slackpad alright, kill it with fire then :)
