### ISSUE TITLE
HTTP error code from Consul

### ISSUE THREAD

**Issue by egeoghan** [hashicorp/consul#1994]
I just created a consul cluster and all of the instances are running fine.  When I go to access the DNS name from the ELB I receive this message :

HTTP error code from Consul:500 Internal Server Error
This is an error page for the Consul web UI. You may have visited a URL that is loading an unknown resource, so you can try going back to the root.

Otherwise, please report any unexpected issues on the GitHub page.

It appears the issue is as a result of this consul log :

2016/04/27 17:06:19 [ERR] agent: failed to sync remote state: No cluster leader

**Comment by ryanuber** [comment]
The Consul UI can't function without an active leader. You can check the status of the server members using the `consul members` command, and the `/v1/status/leader` API endpoint. You may also be interested in the [bootstrapping guide](https://www.consul.io/docs/guides/bootstrapping.html).

Hope that helps!
