### ISSUE TITLE
getsockopt: connection refused

### ISSUE THREAD

**Issue by rogerhill01234** [hashicorp/consul#1995]
I am running two consul servers. When I try to join them in a cluster, I get this error:

getsockopt: connection refused

$ consul join 10.204.42.21
Error connecting to Consul agent: dial tcp 127.0.0.1:8400: getsockopt: connection refused

I also tries --rpc-addr option but no success.

**Comment by swade1987** [comment]
did you manage to resolve this?

**Comment by slackpad** [comment]
Please re-open or ask on the mailing list if you still have any issues.

**Comment by shotdog** [comment]
not  boostrap  server mode  please set the parameter   **-client 127.0.0.1**  like as 

**consul agent -server -bind=192.168.1.2  -node=agent-n2 -datacenter=dc1 -data-dir=/usr/consul -config-dir=/etc/consul.d &** 


the after 


**consul join n1**
