### ISSUE TITLE
Clear local storage on 403

### ISSUE THREAD

**Issue by centromere** [hashicorp/consul#1997]
If you have and old ACL token in LocalStorage, you'll get a 403 error. There is currently no straightforward way of clearing LocalStorage other than opening up a JavaScript console and executing `localStorage.clear()`.

Could there be a button on the 403 page which does this?

**Comment by slackpad** [comment]
Hi @centromere thanks for opening an issue - this one is being tracked over at https://github.com/hashicorp/consul/issues/1655.
