### ISSUE TITLE
`dns_config.only_passing` clarification

### ISSUE THREAD

**Issue by BSick7** [hashicorp/consul#1998]
The `dns_config.only_passing` is a little ambiguous in the docs as it refers to 
> ...all defined healthchecks for the service are in a passing or warning state (i.e. not critical).

The nomenclature indicates `passing` which is in line with the source code, but not with the docs.

```
func (nodes CheckServiceNodes) Filter(onlyPassing bool) CheckServiceNodes {
	n := len(nodes)
OUTER:
	for i := 0; i < n; i++ {
		node := nodes[i]
		for _, check := range node.Checks {
			if check.Status == HealthCritical ||
				(onlyPassing && check.Status != HealthPassing) {
				nodes[i], nodes[n-1] = nodes[n-1], CheckServiceNode{}
				n--
				i--
				continue OUTER
			}
		}
	}
	return nodes[:n]
}
```

I have a need to have non-critical nodes report dns records.  When turned on, the following node statuses would be considered "healthy": `unknown`, `passing`, `warning`.

This is stemming from our desire to use warning as a notification to atlas without claiming a node is unhealthy.  

If there is a better way to accomplish this, please advise.

Otherwise, does my proposal seem plausible to build a PR?

**Comment by slackpad** [comment]
Hi @BSick7 we noticed an error in the docs and fixed it earlier today (!) - here's the change:

https://github.com/hashicorp/consul/commit/c6bde826a45dc0002f12d094645109916a856f85

If you leave `only_passing` in its default state or set it to `false` it should have this exact behavior:

> I have a need to have non-critical nodes report dns records. When turned on, the following node statuses would be considered "healthy": unknown, passing, warning.

Sorry for any confusion :-)

**Comment by BSick7** [comment]
Thanks!
:beers:

**Comment by slackpad** [comment]
Awesome - please let me know if you run into any trouble with this approach.
