### ISSUE TITLE
Consul agent seems to be using http_proxy for health checks

### ISSUE THREAD

**Issue by gamefundas** [hashicorp/consul#1999]
In my Consul cluster hosted on AWS all my health checks are using the http_proxy (set in the environment) and this causes constant flapping. Strangely this is inconsistent behavior at the same time as not all checks fail. Some of them get through and others result in 403 forbidden error. This results in the service flipping online/offline every few minutes. My application is a Spring boot app with Consul agent running in client mode on the same host. This is then configured to talk to the Consul servers (3 node EC2 cluster).

Is there a way for me to configure Consul to ignore my http_proxy environment settings as they are needed for my Spring boot app but I don't want consul to pick them up and route health check traffic through the internet.

I can post my server and client configurations if needed.

**Comment by slackpad** [comment]
Hi @gamefundas can you unset `HTTP_PROXY` for Consul completely, or do some checks need it and others don't? Right now we are using Golang's HTTP transport which does pick the settings out of the environment.

**Comment by gamefundas** [comment]
I forgot to update the thread but yes unsetting the proxy variable helped. Thanks
