### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/consul#2000]
Version bump is needed because Nomad-0.3.2 [vendored unreleased snapshot](https://github.com/hashicorp/nomad/issues/1127) of Consul which caused practical problem downstream.

Thanks.

**Comment by onlyjob** [comment]
6 weeks passed. Would you please kindly tag a minor release so we could update Nomad in Debian?

**Comment by onlyjob** [comment]
This problem is hindering build of Nomad-0.4.0 on Debian. Please tag new release, seriously.

**Comment by slackpad** [comment]
Hi @onlyjob sorry we are in the middle of finishing up a major release and can't run a minor release cycle at this time.

**Comment by onlyjob** [comment]
Fair enough, just remember to tag and vendor by tags please.

I suppose Nomad will have to wait for few weeks until new version of Consul is released...

**Comment by ariscn** [comment]
Any update on when the 0.7.0 release will land?

**Comment by slackpad** [comment]
Consul 0.7 has shipped.
