### ISSUE TITLE
Incorrect validation of proxy-defaults update

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/consul#20064]
#### Overview of the Issue

I am seeing an error in recognising the default protocol that is configured, when validating configuration updates through the api.

This is trapping k8s in a loop when it goes to reconcile config entries from CRDs.

However a manual PUT request with the same config gets the same error, so I believe this is a consul issue and independent of k8s.

In our setup, proxy-defaults sets a default protocol of http and we specify tcp explicitly for the (one or two) services that use it in their service-defaults.

#### Reproduction Steps

k8s consul-connect-injector error log:

```
2023-12-27T11:38:16.528Z	INFO	controller.proxydefaults	config entry does not match consul	{"request": "consul/global", "modify-index": 2951827}
2023-12-27T11:38:16.568Z	ERROR	Reconciler error	{"controller": "proxydefaults", "controllerGroup": "consul.hashicorp.com", "controllerKind": "ProxyDefaults", "ProxyDefaults": {"name":"global","namespace":"consul"}, "namespace": "consul", "name": "global", "reconcileID": "4ee1fc9d-abde-4392-b5c9-0594c3d3db90", "error": "updating config entry in consul: Unexpected response code: 500 (rpc error making call: discovery chain \"api-mock\" uses a protocol \"tcp\" that does not permit advanced routing or splitting behavior)"}
```

A manual PUT request with the same config gets the same error, so I believe this is a consul issue and independent of k8s

GET https://consul/v1/config/proxy-defaults/global

```
{
	"Kind": "proxy-defaults",
	"Name": "global",
	"Config": {
		"envoy_extra_static_clusters_json": "xxx",
		"protocol": "http"
	},
	"TransparentProxy": {},
	"MeshGateway": {},
	"Expose": {},
	"AccessLogs": {},
	"Meta": {
		"consul.hashicorp.com/source-datacenter": "xxx",
		"external-source": "kubernetes"
	},
	"Hash": 6318623746536045320,
	"CreateIndex": 336,
	"ModifyIndex": 2951827
}
```

api-mock does not have any specified defaults

GET https://consul/v1/config/service-defaults/api-mock return 404

I expect it to pick up the default protocol specified in proxy-defaults.

### Consul info for both Client and Server

Consul: 1.17.1, 5 server nodes
Env: EKS 1.27

**Comment by vijayraghav-io** [comment]
@mr-miles , The service inherits protocol from proxy-defaults if service-defaults does not have protocol defined. This can be verified in another way i.e. through service definition. Below is the detailed steps to verify :

1. **Add proxy-defaults config entry** 
    curl --location --request PUT 'http://xxx.xxx.xx.xx:8500/v1/config' \
           --header 'Content-Type: application/json' \
           --data '{
                  "Kind": "proxy-defaults",
                   "Name": "global",
                  "Config": {
                     "protocol":"http"
                   }
          }
    '

2. **Register the service 'api-mock'**
    curl --location --request PUT 'http://xxx.xxx.xx.xx:8500/v1/agent/service/register' \
           --header 'Content-Type: application/json' \
           --data '{
                         "ID": "api-mock01",
                         "Name": "api-mock",
                         "Port": 80,
                         "Kind": "mesh-gateway"
                }'

3. **Read service definition from catalog/service endpoint -  Get /v1/catalog/service/_service-name_**
     curl --location 'http://xxx.xxx.xx.xx:8500/v1/catalog/service/api-mock'
     The response for above request - 
     [
    {
        "ID": "e7c9d9c5-60d0-08f6-77e6-20d180f0d5cf",
        "Node": "VijayRaghavendras-MacBook-Pro.local",
        "Address": "127.0.0.1",
        "Datacenter": "dc1",
        "TaggedAddresses": {
            "lan": "127.0.0.1",
            "lan_ipv4": "127.0.0.1",
            "wan": "127.0.0.1",
            "wan_ipv4": "127.0.0.1"
        },
        "NodeMeta": {
            "consul-network-segment": "",
            "consul-version": "1.18.0"
        },
        "ServiceKind": "mesh-gateway",
        "ServiceID": "api-mock01",
        "ServiceName": "api-mock",
        "ServiceTags": [],
        "ServiceAddress": "",
        "ServiceWeights": {
            "Passing": 1,
            "Warning": 1
        },
        "ServiceMeta": {},
        "ServicePort": 80,
        "ServiceSocketPath": "",
        "ServiceEnableTagOverride": false,
        **"ServiceProxy": {**
            "Mode": "",
            **"Config": {
                "protocol": "http"
            },**
            "MeshGateway": {},
            "Expose": {}
        },
        "ServiceConnect": {},
        "ServiceLocality": null,
        "CreateIndex": 31,
        "ModifyIndex": 36
    }
]

As we can see in above response ServiceProxy.Config gets the values from proxy-defaults.


The config/service-defaults endpoint gets the service-default values from store directly. Only the explicitly defined service-defaults (i.e. registered through put request on config/service-defaults/_service-name_ ) are only stored in the store. The inherited proxy-default values are not stored, hence 404 error while trying to GET on this end point. 

To conclude - getting 404 on config/service-defaults/_service-name_  does not confirm that the service does not use the default protocol defined in proxy-defaults.
The `MergeNodeServiceWithCentralConfig()` method which merges the proxy-defaults and service-defaults is called from ConfigSource.startSync() as well. Ref - https://github.com/hashicorp/consul/blob/9c8e9cebaafd2225f695255c053c54ab6753b048/agent/proxycfg-sources/catalog/config_source.go#L156

**Comment by mr-miles** [comment]
Hi @vijayraghav-io thanks for looking into this, and apologies the steps to reproduce this weren't completely clear.

I am able to reproduce the problem against a fresh install like this:

**1. Add proxy-defaults config entry**

```
curl --location --request PUT 'http://127.0.0.1:8500/v1/config' \
--header 'Content-Type: application/json' \
--data '{ 
"Kind": "proxy-defaults",
"Name": "global",
"Config": {
"protocol":"http"
}
}
'
```

**2. Add service-router config entry**
(as per https://developer.hashicorp.com/consul/docs/connect/config-entries/ingress-gateway#http-listener-with-path-based-routes - which unfortunately seems to have dropped off in a docs refactor though the anchor is still on the igw page)

```
curl --location --request PUT 'http://127.0.0.1:8500/v1/config' \
--header 'Content-Type: application/json' \
--data '{ 
"Kind": "service-router",
"Name": "api",
"Routes":[{"Match":{"HTTP":{"PathPrefix":"/testservice"}},"Destination":{"Service":"testservice"}}]
}
'
```

**3.  Re-submit the same proxy-default entry**
This is what consul-k8s will do if it thinks there may be a difference

```
curl --location --request PUT 'http://127.0.0.1:8500/v1/config' \
--header 'Content-Type: application/json' \
--data '{ 
"Kind": "proxy-defaults",
"Name": "global",
"Config": {
"protocol":"http"
}
}
'
```

Results in this error:

```
[ERROR] agent.http: Request error: method=PUT url=/v1/config from=127.0.0.1:46648 error="discovery chain \"api\" uses a protocol \"tcp\" that does not permit advanced routing or splitting behavior"
```

The problem that I see is that this error prevents consul-k8s controller from completing its reconciliation and so it gets stuck in a loop constantly attempting to correct the config entry and failing.

**Comment by vijayraghav-io** [comment]
Hi @mr-miles , just trying to think from different perspective, since its consul > 1.16 and consul on K8s, if any settings related to API Gateway is causing the issue.

**Comment by mr-miles** [comment]
Thanks @vijayraghav-io - just in case it wasn't clear, I was able to reproduce that error without k8s or api gateway.  I believe the correct behaviour is that the third curl statement returns successful.

**Comment by vijayraghav-io** [comment]
Thanks @mr-miles for clarification, able to reproduce now with latest steps you provided (.i.e. "service-router" , i was still trying with service-defaults as earlier), looking into it.

**Comment by reneeckstein** [comment]
Hi @vijayraghav-io 

A different way to reproduce the issue in Kubernetes.
Updating Consul from v1.17.0 to v1.17.1 (helm chart v1.3.1) ok EKS 1.28
with the following proxydefaults

```
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
  namespace: consul
spec:
  config:
    protocol: http
  meshGateway:
    mode: local
```

After the successful upgrade of all Consul components, check the state of the proxydefaults custom resource, it says "Unknown" and can't sync any longer.

status while executing `kubectl -n consul get proxydefaults global`
```
status:
  conditions:
  - lastTransitionTime: "2024-01-08T22:05:25Z"
    message: 'updating config entry in consul: Unexpected response code: 500 (rpc
      error making call: service "servicexyz-v1" has protocol "tcp", which is incompatible
      with L7 intentions permissions)'
    reason: ConsulAgentError
    status: Unknown
    type: Synced
  lastSyncedTime: "2024-01-08T12:19:49Z"
```

**Comment by vijayraghav-io** [comment]
Hi @reneeckstein ,
To summarize,  the issue is occurring when proxy-defaults is applied for 2nd time on same running consul instance. 
This normally is not an issue,  unless some other config entry like service-router is applied in between / before 2nd time proxy-dexaults is applied.

Hence during upgrade as well, as proxy-defaults is applied for 2nd time (I guess after some other configuration entry is also applied) and the error occurred.

I am looking into this to find the root cause.

**Comment by vijayraghav-io** [comment]
Hi @reneeckstein , @mr-miles ,

One of the methods inside assemblyChain() was expecting Protocol to be defined directly under service-defaults instead of inside the Config map, like this ->
curl --location --request PUT 'http://localhost:8500/v1/config' \
--header 'Content-Type: application/json' \
--data '{
    "Kind": "proxy-defaults",
    "Name": "global",
    **"Protocol":"http"**
}
'

instead of 

curl --location --request PUT 'http://localhost:8500/v1/config' \
--header 'Content-Type: application/json' \
--data '{
    "Kind": "proxy-defaults",
    "Name": "global",
    **"Config": {
               "Protocol":"http"
    }**
}
'

May be as a temporary fix or to verify you can try by providing Protocol directly in service-defaults request body (instead of nesting it inside Config map).
Anyway have updated the code and raised PR to be able to read the Protocol from both possible definitions.

**Comment by vijayraghav-io** [comment]
To add, better explanation for root cause:

1. Though we were defining the Proxy-Defaults with Protocol Http (using Config: {"protocol":"http"}), internally the discoveryChain module was treating Protocol as "tcp" (the default value is "tcp" , if no Protocol is defined in Proxy-defaults or Service-defaults request).

2. When we are doing GET request on Proxy-defaults, we are just getting values stored in store. (where discoveryChain module is Not involved).

3. Also when we provide service-defaults as config entry, if protocol is not provided in request body, protocol should be fetched from proxy-defaults. This was not happening but directly default value of tcp was assigned, if protocol not provided in service-defaults config entry.

**Comment by david-yu** [comment]
Thanks for filing and the investigation @vijayraghav-io. We started working on fixing this in this PR before finding this issue: https://github.com/hashicorp/consul/pull/20481. Thank you for the PR and working through this with @mr-miles

**Comment by vijayraghav-io** [comment]
Hi @david-yu,
Thankyou! for the response and comment.
