### ISSUE TITLE
Configure serf_wan and serf_lan on different addresses

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/consul#2007]
I was trying to bind serf_wan on the public address of the servers and serf_lan on the private, but I don't see any way of doing this.

Is there any way to configure these two on different addresses?

**Comment by slackpad** [comment]
Hi @jorgemarey not currently, sorry about that.

**Comment by moofish32** [comment]
@jorgemarey -- I don't have a test environment up and the failing tests do not appear related to my change. Is there anyway you can help test by building locally?
