### ISSUE TITLE
Web UI assumes Consul is served at /

### ISSUE THREAD

**Issue by devth** [hashicorp/consul#2011]
I'm running Consul on Kuberntes with a private/internal Service, meaning it doesn't get an external IP. K8S provides a way for devs to access these services through a proxy. I can run:

```bash
$ kubectl proxy --port 8001
```

Then hit the service at the url:

```
http://localhost:8001/api/v1/proxy/namespaces/prod/services/consul-svc:http
```

The initial page loads, but then it renders a 404. Looking in Chrome Dev Tools, I see it's trying to make client-side XHRs to an API, e.g.

```
/v1/catalog/datacenters
```

This isn't valid when using the proxy. It needs to be:

```
http://localhost:8001/api/v1/proxy/namespaces/prod/services/consul-svc:http/v1/catalog/datacenters
```

(I verified this works).

Client: `0.6.4`
Server: `0.6.4`

**Comment by slackpad** [comment]
Hi @devth if you rebuild the UI locally you can tweak this setting to set a different path - https://github.com/hashicorp/consul/blob/master/ui/index.html#L12-L17. That should fix the static front end and get it pointed at the right place. Hope that helps!

**Comment by devth** [comment]
@slackpad thanks, I'll give that a try!
