### ISSUE TITLE
Enhancement Request for AzureRM - VNET to VNET connection

### ISSUE THREAD

**Issue by clintonm9** [hashicorp/consul#2013]
Would be nice to be able to connect two different vnets.

I think this is the documentation:
https://msdn.microsoft.com/en-us/library/azure/mt130661.aspx

Currently I have to use the Powershell command 'New-AzureRmVirtualNetworkGatewayConnection' to do this.

aside: the ConnectionType is Vnet2Vnet with a sharedkey, and I dont see it in the documentation.

**Comment by slackpad** [comment]
Hi @clintonm9 I think you may have created this in the wrong project. Was this intended for Terraform?
