### ISSUE TITLE
How to create a Semaphore through HTTP API

### ISSUE THREAD

**Issue by half-dead** [hashicorp/consul#2016]
I've read this [documentation](https://www.consul.io/docs/guides/semaphore.html), and I'm having the same confusion with #1940 .

Can we create a semaphore through HTTP API? or it can only be created through Go API currently?

**Comment by highlyunavailable** [comment]
Both "Locks" and "Semaphores" are implementations using the K/V and session primitives that the Consul HTTP API exposes, so no, a semaphore is not a thing you can create through the HTTP API. 

The document you linked describes the _implementation_ of a distributed Semaphore, the concept of which can be created in any language that can communicate with the Consul HTTP API. If you're using Go, the easiest way is to use the Go API, but other languages' APIs should provide this functionality as well.
