### ISSUE TITLE
Consul website has issues on Windows and IE

### ISSUE THREAD

**Issue by clstokes** [hashicorp/consul#2017]
This may just be because I'm working in a VM, but I tried across two VMs and had the same issue.

On Windows with Internet Explorer, the header links on the Consul website do not work. Perhaps related, the header has some overlapping layers causing display issues with the Consul logo at the top left.

![screencast 2016-04-04 12-45-33](https://cloud.githubusercontent.com/assets/293763/14261138/2e44ae2a-fa64-11e5-9590-78d144e08627.gif)

The pixelation in the gif is just poor rendering with my gif tool, but the logo weirdness is a valid issue.

**Comment by captainill** [comment]
@clstokes definitely an issue! Submitted a pull request to fix.
