### ISSUE TITLE
Warning about service tag not being discoverable via DNS

### ISSUE THREAD

**Issue by djlindstr** [hashicorp/consul#2019]
https://www.consul.io/docs/agent/services.html

The documentation says:

> The tags property is a list of values that are opaque to Consul but can be used to distinguish between "master" or "slave" nodes, different versions, or any other service level labels.

Further down on the same page it says:

> Consul exposes service definitions and tags over the DNS interface. DNS queries have a strict set of allowed characters and a well-defined format that Consul cannot override. While it is possible to register services or tags with names that don't match the conventions, those services and tags will not be discoverable via the DNS interface. It is recommended to always use DNS-compliant service and tag names.
>
>DNS-compliant service and tag names may contain any alpha-numeric characters, as well as dashes. Dots are not supported because Consul internally uses them to delimit service tags.

This is contradictory. Specifically, using tags for versions (such as v1.0.1) results in a warning in the logs:

>    2016/05/03 12:42:18 [WARN] Service tag "v1.0.1" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.

DNS queries is not the only way to find the tags associated with a service. The Catalog HTTP Endpoint documentation has an example where a tag "v1" is returned. It would make just as much sense to return "v1.0.1".

I suggest to remove the warning in the logs about tags not being discoverable via DNS.

Client: `0.6.4`
Server: `0.6.4`

**Comment by slackpad** [comment]
That's fair - we should drop it to DEBUG level.

**Comment by slackpad** [comment]
Fixed via https://github.com/hashicorp/consul/commit/74a8fbef063a52fbe986fb0117021d233267dee2.
