### ISSUE TITLE
replication

### ISSUE THREAD

**Issue by goverdhanr55** [hashicorp/consul#2026]
I am just started playing with consul, I have setup a 3 server cluster, the three servers joined each other, and elected a leader.

I am using this for service discovery, and registered the services with one of the follower servers in the cluster. 

However the data is not getting replicated to other servers in the cluster. If i kill the follower which has the data, I am loosing all the data.

Below is the command I used to start the servers

./consul agent  -server \
                -data-dir=/data/consul -node=`hostname`_consul -bind=$HOST_IP -advertise=$HOST_IP -ui -client=$HOST_IP \
                -bootstrap-expect 3 \
                -encrypt <key>
                -retry-join $Peer_IP \
                -retry-join $Peer_IP \

Am I missing  something? Do I need to add any other configuration for the data to be replicated?

I am using Consul v0.6.4.

In consul info this is what I see for the leader

raft:
        applied_index = 80
        commit_index = 80
        fsm_pending = 0
        last_contact = never
        last_log_index = 80
        last_log_term = 1
        last_snapshot_index = 0
        last_snapshot_term = 0
        num_peers = 2
        state = Leader
        term = 1

This for the follower where I loaded the data.

raft:
        applied_index = 85
        commit_index = 85
        fsm_pending = 0
        last_contact = 44.081724ms
        last_log_index = 85
        last_log_term = 1
        last_snapshot_index = 0
        last_snapshot_term = 0
        num_peers = 2
        state = Follower
        term = 1

The applied index is 85 for the follower and 80 for the leader. So they are not in sync. In the logs I see the below warnings, not sure if this is any isue

 2016/05/05 14:05:11 [WARN] Service name "ms_xxx_yyy_zzz" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.

**Comment by slackpad** [comment]
Hi @goverdhanr55 it is probably just the time between running the two commands that's causing the difference there where it looks like it isn't caught up. The last contact time looks healthy in the output above.

I think this is probably the problem:

> registered the services with one of the follower servers in the cluster.

You are registering services for that particular server, so when it goes away they get deregistered. Instances of services belong to the agent where they are registered. Does that make sense?

**Comment by slackpad** [comment]
I see this got resolved on the mailing list here - https://groups.google.com/forum/#!msg/consul-tool/r2omPSG1Dmo/nRYG-AcbOAAJ.
