### ISSUE TITLE
Suggestion: ACL lookup ID should not be the credential

### ISSUE THREAD

**Issue by daveadams** [hashicorp/consul#2027]
I'm working on planning out my organization's use of ACLs across a number of applications, and it strikes me that it would be useful if there were a unique, unchanging ID associated with an ACL that was not the same as the credential (token) itself, which could function as the ID for API calls, etc.

Currently, ACLs have Name attributes, but those can change and do not have to be unique. And there's no way to reliably refer to an ACL except by the token UUID, which itself is the credential, meaning I cannot develop any tools to manage ACLs safely without storing the tokens unless I rely on the Name field as a key and hope that no mistakes are ever made by my tools or by other administrators in allowing duplicate names.

I'm not sure if the general argument is clear, so let me know if you need examples of situations where a separate ID value would be useful. Thanks.

**Comment by slackpad** [comment]
@daveadams thanks for the suggestion - I agree this would be super useful. I think Vault has a similar concept via "token accessors".

**Comment by alexandrustaetu** [comment]
Hello,

Is there anything I can contribute on this issue? I'd be interested to have available so we can implement afterwards token operations via cli. ( #3862 )

Thanks,
Alex.

**Comment by mkeeler** [comment]
Closing this as the new ACL implementation in 1.4.0-rc1 implements this exactly. Every token now has a Secret ID and an Accessor ID. For management purposes the Accessor ID is used. The Secret ID is what gets provided to the RPC/HTTP APIs to authorize access.
