### ISSUE TITLE
Does consul plan to natively support Kubernetes API-gateway ?

### ISSUE THREAD

**Issue by LeoFVO** [hashicorp/consul#20332]
#### Feature Description
Kubernetes is introducing **[API-gateway](https://gateway-api.sigs.k8s.io/)** to improve gateway concern natively inside Kubernetes.
Looking at **services-mesh**, it seems to be highly related and the **migration to support natively Kubernetes API-gateway is a must-have for future generation of services-mesh tools**.

I'm asking: do you plan the Gateway API to become the default API for all Consul traffic management in the future ?

If, yes:
Will this change create a breaking changes in Consul ?

**Comment by vijayraghav-io** [comment]
I guess there is related issue - https://github.com/hashicorp/consul/issues/18543

**Comment by david-yu** [comment]
Hi @LeoFVO Could you describe your use case a bit more? Are you looking to leverage Gateway API for Consul API gateway traffic (north-south) or for Consul Service mesh (east-west) traffic? We already implement the former for gateway traffic but for mesh we are looking for interest from users on https://github.com/hashicorp/consul/issues/18543. Our long term plan is to support GAMMA but we first need to re-work our catalog to make sure it aligns with GAMMA configuration models.

**Comment by david-yu** [comment]
Will go ahead and close since there was no response. Please see https://github.com/hashicorp/consul/issues/18543 for further questions around GAMMA for mesh use cases.
