### ISSUE TITLE
gossip not work between inside docker and outside

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2035]
Hi, I am running the consul client in the docker container and consul servers outside, it looks like the client could gossip the servers while the server failed to gossip the client with making tcp connection to port 8301 i/o timeout.   the client in the container could reach the outside via snat, I suppose the snat could recognize the response packet the other way around as well, but it didn't. any idea about how to make the consul cluster work in this case?

thank you!

**Comment by slackpad** [comment]
Hi @hehailong5 can you describe your network setup a bit?

**Comment by slackpad** [comment]
Closing this as we never heard back. Please let us know if you still need help.
