### ISSUE TITLE
1.17.2 - terminating gateway broken by xds changes

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/consul#20360]
Upgraded to 1.17.2 via the helm chart and am seeing the terminating gateway is broken by #19954 

agent/xds/clusters.go:1626 incorrectly restricts envoy to looking at URI SANs that match the hostname provided in config.  

However certificates will have a DNS SAN with the hostname value.  As a result outbound TLS connections fail on certificate errors.

I believe the fix is to use SanType: envoy_tls_v3.SubjectAltNameMatcher_DNS

Working config pre-upgrade (1.17.1):
![image](https://github.com/hashicorp/consul/assets/590320/f6e5f1f9-8c89-49ea-8f92-2f192462e7f3)

Failing config from 1.17.2:
![image](https://github.com/hashicorp/consul/assets/590320/b727d530-3055-4391-8d10-eb0b79916e8e)

**Comment by david-yu** [comment]
Closing, as this is addressed by https://github.com/hashicorp/consul/pull/20417, this will be released in the next set of patch releases likely around March timeframe.
