### ISSUE TITLE
Can't curl key values locally for backup

### ISSUE THREAD

**Issue by AjeetK** [hashicorp/consul#2036]
I am using single instance for consul. Everything is working fine, the web-ui, ACL etc. But when I try to access the all the key values locally using `curl` command the response is `404 not found` even if the key value is already there and can be seen in `web-ui`.

`Config.json` file

```
{
    "bootstrap": true,
    "server": true,
    "log_level": "DEBUG",
    "enable_syslog": true,
    "datacenter": "dc1",
    "addresses" : {
      "http": "P.P.P.P"
    },
    "bind_addr": "P.P.P.P",
    "node_name": "P.P.P.P",
    "data_dir": "/home/ubuntu/consuldata",
    "ui_dir": "~/dist",
    "acl_datacenter": "dc1",
    "acl_master_token": "xxxxxxxxxxxxxxxxxxxxx",
    "acl_default_policy": "deny",
    "encrypt": "pXoaLOJ816mO+da8y8zrsg=="
}
```
where `P.P.P.P` is the private IP and `xxxxxxxxxxxxxxxxxxx` is the `master token`.

I have started consul by the following command
`consul agent -config-dir ~/server -ui-dir ~/dist -bootstrap true -client=P.P.P.P`

After running this the `web-ui` is working fine and I am able to create `ACL` and `key-value`
Now am trying to get all the key value pairs by the following command
`curl -v http://P.P.P.P:8500/v1/kv/?recurse`

Following is the output
```
* Hostname was NOT found in DNS cache
*   Trying P.P.P.P...
* Connected to P.P.P.P (P.P.P.P) port 8500 (#0)
> GET /v1/kv/?recurse HTTP/1.1
> User-Agent: curl/7.35.0
> Host: P.P.P.P:8500
> Accept: */*
>
< HTTP/1.1 404 Not Found
< X-Consul-Index: 488
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Tue, 10 May 2016 13:08:44 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host P.P.P.P left intact
```

where `P.P.P.P` is the private IP of the consul instance.

Following is the output of `netstat -tlpn`

```
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22                  0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      1339/consul
tcp        0      0 P.P.P.P:8300              0.0.0.0:*               LISTEN      1339/consul
tcp        0      0 P.P.P.P:8301              0.0.0.0:*               LISTEN      1339/consul
tcp        0      0 P.P.P.P:8302              0.0.0.0:*               LISTEN      1339/consul
tcp        0      0 127.0.0.1:8400          0.0.0.0:*               LISTEN      1339/consul
tcp        0      0 0.0.0.0:80                  0.0.0.0:*               LISTEN      -
tcp        0      0 P.P.P.P:8500              0.0.0.0:*               LISTEN      1339/consul
tcp6       0      0 :::22                   :::*                    LISTEN      -
```

I have tried the `curl` command on each of these addresses on which consul is listening but getting the same error.

**Comment by slackpad** [comment]
Hi @AjeetK since you are using ACLs with default-deny, you need to supply a token `curl -v http://P.P.P.P:8500/v1/kv/?recurse\&token=token` to the request in order to read back the KV entries. The web UI is doing this for you if you set the ACL there. Hope that helps!
