### ISSUE TITLE
Consul server leadership takeover.

### ISSUE THREAD

**Issue by chilumbugeorge** [hashicorp/consul#2037]
We went to upgrade our consul instances in the cluster. Our cluster has 3 servers, and several clients.

We have upgraded two of our servers, with only the leader remaining to be upgraded. Our concern is that if we try to upgrade the leader, we face about 4-5 seconds of downtime, which we cannot afford...or at least we wanna try to avoid. I did some online readings and could not find any documentation that talks about leader takeover. Is there a way we can achieve leader takeover in Consul so that one of the already upgraded servers can become leader (without any downtime) while we proceed to upgrade the old leader?

**Comment by slackpad** [comment]
Hi @chilumbugeorge when you take down the current leader (or restart it if you are upgrading in place) Consul will perform a leader election and one of the new servers will be elected (or possibly the old leader if you are restarting in place). There's unfortunately no way to avoid the leader election time. It's good to make your apps retry during periods with no leader, and we are working to make the Consul agent do that as well (lock monitors now retry, and we have some upcoming changes to make other places retry as well). Hope that helps!

**Comment by slackpad** [comment]
Related mailing list discussion - https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/svPaxcanZyQ/w1oopNyLOAAJ.
