### ISSUE TITLE
Deleting keys always returns True

### ISSUE THREAD

**Issue by dmyerscough** [hashicorp/consul#2038]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `Consul v0.6.4 - Consul Protocol: 3 (Understands back to: 1)`

### `consul info` for both Client and Server
Client:
```
N/A
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = 26a0ef8c
	version = 0.6.4
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	server = true
raft:
	applied_index = 10960
	commit_index = 10960
	fsm_pending = 0
	last_contact = never
	last_log_index = 10960
	last_log_term = 14
	last_snapshot_index = 8206
	last_snapshot_term = 4
	num_peers = 2
	state = Leader
	term = 14
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 72
	max_procs = 1
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 9
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 8
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Three CentOS machines setup in AWS

### Description of the Issue (and unexpected/desired result)

Deleting keys always returns True even for non-existing keys

### Reproduction steps

```
$ curl -X DELETE "http://localhost:8500/v1/kv/web/doesnotexist"
true
```
### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @dmyerscough Consul's currently designed such that DELETEs for KV entries always succeeds whether they key exists or not so those requests are idempotent. Is there a particular use case this was causing you trouble with?

**Comment by dmyerscough** [comment]
Hi @slackpad this isn't causing any problems, it was just a little off to me.. I can add additional logic around this.
