### ISSUE TITLE
This mark checks as critical if the serfCheck fails.

### ISSUE THREAD

**Issue by sorenmat** [hashicorp/consul#2042]
We have had incidents in production where a consul node seems to be in an 'incorrect' state.
Where the serfCheck failed, but the service checks where green. Upon investigation it turned out that
the node was completely terminated in AWS.
We could reproduce this by `kill -9 consul_pid & service consul stop` which would result in the serfCheck to fail because of a missing heartbeat. But consul didn't 'clean up' the services because it was dead.

https://github.com/hashicorp/consul/pull/2015
The code in this PR fixes this problem, by marking checks on the same node as critical if the serfCheck fails.
I do however have no idea on how to test this, feedback very welcome :)

Affected versions:

Client: `0.6.3`
Server: `0.6.3`

**Comment by slackpad** [comment]
Discussion here - https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/5Xpd4e-yunk/FjbJWZX5CAAJ.

**Comment by slackpad** [comment]
Closing per the thread listed above. Once https://github.com/hashicorp/consul/issues/802 is implemented this will be easier to consume since Consul's AND-ing logic will be computed and exposed via an API.
