### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bogdanov1609** [hashicorp/consul#2043]
### `consul version` for both Client and Server

Client: `Consul v0.6.4`
Server: `Consul v0.6.4`
### `consul info` for both Client and Server

Server:

```
agent:
    check_monitors = 0
    check_ttls = 0
    checks = 0
    services = 1
build:
    prerelease =
    revision = 26a0ef8c
    version = 0.6.4
consul:
    bootstrap = true
    known_datacenters = 1
    leader = true
    server = true
raft:
    applied_index = 13072
    commit_index = 13072
    fsm_pending = 0
    last_contact = never
    last_log_index = 13072
    last_log_term = 1
    last_snapshot_index = 8214
    last_snapshot_term = 1
    num_peers = 0
    state = Leader
    term = 1
runtime:
    arch = amd64
    cpu_count = 2
    goroutines = 70
    max_procs = 2
    os = linux
    version = go1.6
serf_lan:
    encrypted = true
    event_queue = 0
    event_time = 12
    failed = 1
    intent_queue = 0
    left = 0
    member_time = 47
    members = 5
    query_queue = 0
    query_time = 4
serf_wan:
    encrypted = true
    event_queue = 0
    event_time = 1
    failed = 0
    intent_queue = 0
    left = 0
    member_time = 1
    members = 1
    query_queue = 0
    query_time = 1
```
### Operating system and Environment details

Server and client are equal:
Ubuntu 14.04.1 LTS
Kernel 3.19.0-58-generic
KVM virtual machine running in OpenStack
ipv6-only 
### Reproduction steps

The consul client crashed while executing command `consul join <server>`.
But we cant reproduce crash after start consul again. 
### Log Fragments or Link to [gist](https://gist.github.com/)

Stderr log:
[gist]https://gist.github.com/bogdanov1609/71b8a08b8b3a2e0951ad37d54ef6aab9
Stdout before panic:
https://gist.github.com/bogdanov1609/ce8ca98102c68bbbd2694ecfb7116e99

**Comment by slackpad** [comment]
Fixed in https://github.com/hashicorp/consul/issues/2125.
