### ISSUE TITLE
Documentation for HTTP query parameters

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul#2065]
I haven't been able to find any documentation for query parameters for the HTTP API, such as `?passing`. Maybe such documentation already exists and I just cannot find it, but if not then it would be great to document this functionality.

**Comment by slackpad** [comment]
Hi @joshuaspence can you please be more specific about which endpoints need clarified? The health endpoint's "?passing" documentation is here, for example:

https://www.consul.io/docs/agent/http/health.html#health_service

**Comment by joshuaspence** [comment]
Ah so it is. It is not documented on https://www.consul.io/docs/agent/http/catalog.html#catalog_service

**Comment by slackpad** [comment]
It's not supported for the catalog endpoint - it's only available with the health endpoint, which is similar to the catalog but filtered through the lens of health checks.

**Comment by joshuaspence** [comment]
Ah right. Thanks for the clarification.
