### ISSUE TITLE
fail to reboot the cluster

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2073]
Hi,

I bootstrap a cluster using -bootstrap-expect way. after running for a while, I stopped the cluster by manually killing each member. I then start to bootstrap it using the same way, when the last member joins in, the log shows:

```
2016/05/28 03:09:59 [ERR] agent: coordinate update error: No cluster leader
2016/05/28 03:10:01 [WARN] raft: Rejecting vote request from 172.16.1.4:8300 since our last index is greater (2002, 1981)
2016/05/28 03:10:02 [WARN] raft: Rejecting vote request from 172.16.1.4:8300 since our last index is greater (2002, 1981)
2016/05/28 03:10:04 [WARN] raft: Rejecting vote request from 172.16.1.4:8300 since our last index is greater (2002, 1981)
2016/05/28 03:10:05 [WARN] raft: Rejecting vote request from 172.16.1.4:8300 since our last index is greater (2002, 1981)
```

why this happens? and usually how to reboot a cluster?

**Comment by nMustaki** [comment]
You should read this issue from start to finish : #454 (Servers can't agree on cluster leader after restart)
and only then the documentation : https://www.consul.io/docs/guides/outage.html

**Comment by slackpad** [comment]
Closing this as we never heard anything else - let us know if you still need help.
