### ISSUE TITLE
Output health check status to external system 

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul#2077]
We are using Consul with AWS autoscaling groups. In some cases we are also putting the autoscaling groups behind an ELB and an thus use ELB health checks to replace failing instances, however we have many ASGs without an associated ELB.

Amazon provides an `aws autoscaling set-instance-health` command for updating an EC2 instance's health programmaticly (see http://docs.aws.amazon.com/autoscaling/latest/userguide/healthcheck.html#as-configure-healthcheck). I could probably write a Consul watch handler to integrate with AWS, but it would be great if there was a solution native to Consul.

**Comment by slackpad** [comment]
Hi @joshuaspence writing a watch handler is probably the best way to do this, since you can basically run any script and have that script notified when things change. I don't think we'd do a deeper integration with any specific API since there are so many options.
