### ISSUE TITLE
TCP check port scanning support.

### ISSUE THREAD

**Issue by slawekjaranowski** [hashicorp/consul#2078]
It is sometime problematic if check open connection and close it without sending data.
Many applications may don't work correctly in case of opening connection without data transmision.

Option for only scanning port without sending any data to them will be useful.

**Comment by slackpad** [comment]
Thanks for opening an issue. We haven't had much community interest in this I think mostly because folks can use script checks if their applications have special requirements. Closing this out for now as we'd rather not take on additional configuration and complexity.
