### ISSUE TITLE
Support DNS lookups to "meta" DCs

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#208]
We can support special meta-dc's that have special meanings. Examples:
* 'global' - Do a lookup across all DCs
* 'any' - Returns results from first DC to respond

**Comment by split3** [comment]
+1
This functionality would be very useful, we have multiple data centers and a client might not actually know which datacenter that service resides in and thus would want to have local return if available, but then the others if not.

**Comment by mfischer-zd** [comment]
An easy workaround would be to use a regular DNS server to serve a CNAME record outside the .service.consul domain.  For example, a query for "frobinator.service.local" against the local DNS resolver could result in a CNAME answer for "frobinator.dc1.service.consul".  

What do you think of this?  Doing so would keep Consul out of the complex business of managing foreign service endpoints.

**Comment by jefferai** [comment]
@mfischer-zd then you have to implement and configure some other piece of software to do this, when Consul already knows where things live.

**Comment by DanyC97** [comment]
Has been done any progress on this ?

thanks!

**Comment by StephenTallamy** [comment]
Any updates on this? Is a solution likely to hit a release version soon? I have this same requirement - I want my DNS names to resolve to nodes in my local data center unless Consul detects an outage for all nodes in my local data center and then it will resolve to nodes in a remote data center. At this point I don't need rules around which data center it fails over to, although later this could be beneficial.

**Comment by armon** [comment]
We are getting closer, but still looking like a Consul 0.6 or 0.7 feature.

**Comment by StephenTallamy** [comment]
Thanks @armon - what's the release timescale on those?

**Comment by armon** [comment]
@StephenTallamy No hard deadlines. Consul 0.6 likely next month, and 0.7 in Q4.

**Comment by split3** [comment]
Will this functionality help with DNS forwarding? Currently it seems as though it isn't possible to use DNS forwarding with multiple data centers as you'll only get back the services from the DC that is queried.  We have currently 2 data centers (these are real data centers in different parts of the country) and multiple environments in each data center (dev, qa, perf, prod, etc).

So it seems that setting up DNS forward to work in this situation is essentially not possible without this feature.

**Comment by armon** [comment]
@split3 Correct! You will be able to query multiple DCs at the same time.

**Comment by slackpad** [comment]
The "local" use case is covered here https://github.com/hashicorp/consul/issues/1229 and in its linked issues. The multi-DC aspect of this is now supported with prepared queries, released in 0.6.0:

https://www.consul.io/docs/agent/http/query.html
