### ISSUE TITLE
after call each server `consul leave` in the consul cluster, fail to elect a leader again.

### ISSUE THREAD

**Issue by zackshen** [hashicorp/consul#2080]
Hi:
       i am doing a test. i run consul in three server

        Node  Address             Status  Type    Build  Protocol  DC
        n1    172.16.13.160:8301  alive   server  0.6.4  2         dc1
        n2    172.16.13.161:8301  alive   server  0.6.4  2         dc1
        n3    172.16.13.162:8301  alive   server  0.6.4  2         dc1

then, i login to each server and call `consul leave`.
after this,  i want to start the cluster again, but the cluster can not elect a leader

login 172.16.13.161

    # consul join 172.16.13.160

login 172.16.13.162

    # consul join 172.16.13.160

login 172.16.13.160

    # consul members

    Node  Address             Status  Type    Build  Protocol  DC
    n1    172.16.13.160:8301  alive   server  0.6.4  2         dc1
    n2    172.16.13.161:8301  alive   server  0.6.4  2         dc1
    n3    172.16.13.162:8301  alive   server  0.6.4  2         dc1

error log like below:

    [ERR] agent: failed to sync remote state: No cluster leader
    [ERR] agent: failed to sync remote state: No cluster leader

server - 172.16.13.160

{
  "datacenter": "dc1",
  "data_dir": "./data",
  "log_level": "INFO",
  "node_name": "n1",
  "server": true,
  "bind_addr": "172.16.13.160",
  "bootstrap_expect": 3,
  "addresses": {
      "http": "0.0.0.0"
  },
  "ui_dir": "./ui"
}

server - 172.16.13.161

{
  "datacenter": "dc1",
  "data_dir": "./data",
  "log_level": "INFO",
  "node_name": "n2",
  "server": true,
  "bind_addr": "172.16.13.161",
  "bootstrap_expect": 3,
  "addresses": {
      "http": "0.0.0.0"
  },
  "ui_dir": "./ui"
}
`

server - 172.16.13.162
`
{
  "datacenter": "dc1",
  "data_dir": "./data",
  "log_level": "INFO",
  "node_name": "n3",
  "server": true,
  "bind_addr": "172.16.13.162",
  "bootstrap_expect": 3,
  "addresses": {
      "http": "0.0.0.0"
  },
  "ui_dir": "./ui"
}

after join, i found `null` in the file ${data_dir}/raft/peers.json, 
is it a bug ??? @armon @slackpad

**Comment by slackpad** [comment]
Hi @zackshen running the leave on all the servers is putting the cluster into an outage state, so it is expected that it cannot recover without intervention. The first leave should leave things still operating (2 servers left). Once you run the next leave, the quorum of servers can process the leave, but the cluster with 1 remaining server has lost quorum and can no longer process any changes (such as to add new servers). You'd need to manually restore the contents of your peers.json (see https://www.consul.io/docs/guides/outage.html), or re-bootstrap the cluster by temporarily running a single server in `-bootstrap` mode and then joining the other two servers afterwards to form a new cluster.

**Comment by slackpad** [comment]
Generally you'll want to just reboot servers without them doing a leave and they should re-join the cluster when they come back.

**Comment by zackshen** [comment]
Hi @slackpad running consul in three server, when reboot one server would not affect the cluster, until leave all the consul then need us to recover manually.   do i understand right ???

**Comment by slackpad** [comment]
That's correct - with three servers rebooting one (even the leader) won't require any operator intervention. Losing two or more at one time will cause an outage. If you have five servers it can handle two down at once.

**Comment by zackshen** [comment]
@slackpad  thank you very much!
