### ISSUE TITLE
error running consul server in 1.18.0: failed to configure SCADA provider user's home directory path: $HOME is not defined

### ISSUE THREAD

**Issue by star3am** [hashicorp/consul#20889]
#### Overview of the Issue

Consul 1.18.0 does not start, and gives error:
failed to init scada: failed to configure SCADA provider: failed to retrieve user's home directory path: $HOME is not defined

Consul 1.17.3 starts up fine

---

#### Reproduction Steps

Install Consul 1.18.0 and issue start consul sudo service consul start
I used Ubuntu 22.04 ARM64

Steps to reproduce this issue, eg:

Install Consul https://releases.hashicorp.com/consul/1.18.0/consul_1.18.0_linux_arm64.zip
Start Consul
==> failed to init scada: failed to configure SCADA provider: failed to retrieve user's home directory path: $HOME is not defined

$HOME is defined
$ env | grep HOME
HOME=/home/vagrant

Install Consul https://releases.hashicorp.com/consul/1.17.3/consul_1.17.3_linux_arm64.zip
Start Consul
Consul Starts fine

```
primary_datacenter = "dc1"
client_addr = "0.0.0.0"
bind_addr = "0.0.0.0"
advertise_addr = "10.9.99.10"
data_dir = "/var/lib/consul"
datacenter = "dc1"
disable_host_node_id = true
disable_update_check = true
leave_on_terminate = true
log_level = "INFO"
server = true
ports = {
  grpc  = 8502
  dns   = 8600
  http  = 8500
  https = 8501
}
connect {
  enabled = true
  # enable_mesh_gateway_wan_federation = true
}
enable_central_service_config = true
protocol = 3
raft_protocol = 3
recursors = [
  "8.8.8.8",
  "8.8.4.4",
]
server_name = "hashiqube0.service.consul"
ui_config {
  enabled = true
}
# https://lvinsf.medium.com/monitor-consul-using-prometheus-and-grafana-1f2354cc002f
# https://grafana.com/grafana/dashboards/13396-consul-server-monitoring/
# https://developer.hashicorp.com/consul/docs/agent/telemetry
telemetry {
  prometheus_retention_time = "24h"
  disable_hostname = true
}
```

</details>

### Operating system and Environment details

Linux ARM64

### Log Fragments

==> failed to init scada: failed to configure SCADA provider: failed to retrieve user's home directory path: $HOME is not defined

**Comment by iammati** [comment]
I'm struggling with the exact same error on:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
on AMD64

Using Consul 1.18.0, installed using HashiCorp's apt repository in order to install it. 😭

**Comment by gevorg15** [comment]
Same issue on Amazon LInux 2 using the hashicorp repo to install consul.  1.18 fails to start with same error as original poster to this issue.

**Comment by lethargosapatheia** [comment]
I get a very similar error once I upgrade to 1.18:
> consul[56044]: ==> failed to init scada: failed to configure SCADA provider: failed to read credential file: open /home/consul/.config/hcp/cred_file.json: permission denied

The difference is probably related to the fact that the home directory path is configured, in that it exists in /etc/passwd:
```
consul:x:998:998::/home/consul:/bin/false
```
but the home directory doesn't exist at all. I've never needed it until now.
This is tested on Ubuntu 22.04 and consul is directly installed on the host.

**Comment by robmit68** [comment]
Hello  downgraded to 1.17.3 restore services and running no issues in ubuntu 23.10
