### ISSUE TITLE
Fix typo in the documentation: acl.token.dns

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/consul#20949]
It should be`acl.tokens.dns`

https://developer.hashicorp.com/consul/docs/security/acl/tokens/create/create-a-dns-token#apply-the-token-with-a-command

![image](https://github.com/hashicorp/consul/assets/139780495/70cd9332-5cb0-43a6-aba8-70b27075150c)

**Comment by jkirschner-hashicorp** [comment]
I suppose it should be `set-agent-token` instead (since that's the name of the command). This seems like a copy-paste error from the name of the agent config field (which, you're right, should be acl.tokens.dns`).
