### ISSUE TITLE
multiple service configuration error

### ISSUE THREAD

**Issue by arturmon** [hashicorp/consul#20991]
With these settings, the consul does not start and an error is displayed. although this is exactly what is written in the documentation for setting up Multiple service.
https://developer.hashicorp.com/consul/docs/services/configuration/services-configuration-reference#multiple-service-definitions

```
{
  "node_name": "consul-server",
  "server": true,
  "bootstrap" : true,
  "ui_config": {
    "enabled" : true,
    "metrics_provider" : "prometheus",
    "metrics_proxy" : {
      "base_url" : "http://prometheus:9090"
    }
  },
  "ports": {
    "grpc" : 8502
  },
  "dns_config": {
    "enable_truncate": true,
    "udp_answer_limit": 100
  },
  "datacenter": "dc1",
  "data_dir": "/consul/data",
  "bind_addr": "0.0.0.0",
  "client_addr": "0.0.0.0",
  "log_level":"INFO",
  "addresses": {
    "http" : "0.0.0.0"
  },
  "connect": {
    "enabled": true
  },
  "service": [
    {
      "name": "haproxy",
      "tags": ["primary"],
      "address": "haproxy",
      "port": 80
    },
    {
      "name": "redis",
      "tags": ["db"],
      "address": "redis",
      "port": 6379
    }
  ]
}
```

Error:
```
2024-04-17 21:17:22 ==> failed to parse /consul/config/server.json: 1 error(s) decoding:
2024-04-17 21:17:22 
2024-04-17 21:17:22 * 'service' expected a map, got 'slice'
```

**Comment by blake** [comment]
@arturmon Multiple services must be defined under a `services` block. You currently have `service` in your configuration which expects a single service definition, not an array/list of service definitions.

Renaming the key from `service` to `services` should be sufficient to resolve this error.

**Comment by arturmon** [comment]
@blake thank you, I really didn't notice ((
