### ISSUE TITLE
Watch command still splits on spaces despite quotes around handler path on Windows

### ISSUE THREAD

**Issue by iforapsy** [hashicorp/consul#2102]
### `consul version` for both Client and Server

Client: v0.6.3
Server: v0.6.3
### Operating system and Environment details

Windows Server 2012 R2
### Description of the Issue (and unexpected/desired result)

Consul watch works if the handler path has spaces but there are no command-line arguments

```
PS C:\> C:\consul\consul.exe watch -type service -service my-service -tag my-tag 'C:\Program Files\Foo\HelloWorld.exe'
Hello world!
```

Command-line arguments to the handler work when the handler path does not have spaces.

```
PS C:\> C:\consul\consul.exe watch -type service -service my-service -tag my-tag 'C:\Windows\Foo\HelloWorld.exe -bar baz'
Hello world!
```

It understandably fails when there are command-line arguments and spaces in the handler path because there's no way for Consul can tell the difference between the handler path and the arguments.

```
PS C:\> C:\consul\consul.exe watch -type service -service my-service -tag my-tag 'C:\Program Files\Foo\HelloWorld.exe -bar baz'
'C:\Program' is not recognized as an internal or external command, operable program or batch file.
Error executing handler: exit status 1
```

However, it still fails if I add quotes around the handler path to remove any ambiguity.

```
PS C:\> C:\consul\consul.exe watch -type service -service my-service -tag my-tag '"C:\Program Files\Foo\HelloWorld.exe" -bar baz'
'C:\Program' is not recognized as an internal or external command, operable program or batch file.
Error executing handler: exit status 1
```

Adding quotes around the handler path works on Ubuntu 14.04.

```
$ consul watch -type service -service my-service -tag my-tag '"/home/ubuntu/hello world" -bar baz'
Hello world!
```

After much frustration, I was able to work around this problem by adding a caret "^" in front of the space.

```
PS C:\> C:\consul\consul.exe watch -type service -service my-service -tag my-tag 'C:\Program^ Files\Foo\HelloWorld.exe -bar baz'
Hello world!
```

Still, it is very unintuitive that quotes around the handler path do not have their expected function on Windows.

**Comment by slackpad** [comment]
Hi @iforapsy looking at this further it's all related to how the Windows shell handles quotes for command line arguments. All this processing happens before Consul is executed, so I don't think there's anything we could do in Consul itself to fix this. The caret appears to be a reasonable solution to escape the spaces.
