### ISSUE TITLE
Querying WAN address via DNS interface

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul#2103]
Is it possible to query WAN addresses via the DNS interface?  I am running `dig @consul.mydomain.com consul.service.consul` and Consul always responds with the LAN addresses of the nodes.

**Comment by slackpad** [comment]
Hi @joshuaspence there's a setting on the *agent* to do this called [`translate_wan_addrs`](https://www.consul.io/docs/agent/options.html#translate_wan_addrs).

**Comment by joshuaspence** [comment]
Yep, I did set that option but it didn't seem to affect anything.

**Comment by joshuaspence** [comment]
This is my Consul configuration:

```
{
    "advertise_addr": "REDACTED",
    "advertise_addr_wan": "REDACTED",
    "bootstrap_expect": 3,
    "client_addr": "0.0.0.0",
    "data_dir": "/mnt/consul",
    "datacenter": "ap-southeast-2",
    "enable_syslog": true,
    "log_level": "WARN",
    "node_name": "REDACTED",
    "ports": {
        "dns": 53
    },
    "server": true,
    "start_join": [
        "consul.REDACTED"
    ],
    "telemetry": {
        "statsd_address": "REDACTED"
    },
    "translate_wan_addrs": true,
    "ui": true
}
```

**Comment by slackpad** [comment]
This setting needs to be present on the agent where the DNS query is taking place, not necessarily the node you are looking up the address for. Is that true in this case?

**Comment by joshuaspence** [comment]
Oh, so Consul isn't even present on the machine from which I am running the DNS query. Basically, I wanted to open up Consul to our office IP address such that we can do `ssh consul.service.consul` and have it just work.

**Comment by slackpad** [comment]
I see - whichever agent the office DNS will hit would need to be configured with this option to get that to work. It would also need to be in a different Consul datacenter in order to choose the WAN address. This feature was intended primarily for an agent on every node vs. a shared DNS server, but it seems like it should be possible to get this to work, maybe by having these folks hit a special agent.
