### ISSUE TITLE
Consul running on Docker HTTP health check returns “connection reset by peer”

### ISSUE THREAD

**Issue by Painyjames** [hashicorp/consul#2109]
We are running consul through docker (official image). All works fine but the issue is that when we are trying to hit an http endpoint it fails miserably. Funny thing is that if we do an tcp health check it works completely fine. It works as well when we use wget through the script healthcheck, but we'd rather not go this way.

Here's the error:

> 2016/06/10 10:29:42 [WARN] agent: http request failed 'https://10.1.24.68:5012/status': Get https://10.1.24.68:5012/status: read tcp 10.3.2.11:55549->10.1.24.68:5012: read: connection reset by peer

I'm also assuming that the error it's being logged [here](https://github.com/hashicorp/consul/blob/14ec46b3cf8edf6fdd3f4bda8deacdfb6d4e9a73/command/agent/check.go#L426). The thing is we tried this running consul on windows locally and having it to hit http://localhost:5012/status , which odd enough works. In this case we are not using https though, could that be a certificate issue? 
I've added our CA root certificate to both /etc/ssl/certs/ca-certificates.crt and /usr/share/local/ca-certificates.crt. As I said, it seems to be fine when I'm hitting the endpoint using wget but who knows how consul/go do https requests.

Any idea?

**Comment by RehanSaeed** [comment]
+1

**Comment by rikwasmus** [comment]
Is your certificate valid for the _ip_ is the question? I've only got consul to play nice with HTTPS checks when they are indeed fully valid for the way you connect to them (so, a cert for a specific DNS name will not be valid if you connect on bare ip of course).

**Comment by slackpad** [comment]
Consul's CA configuration for cluster communication doesn't apply to health checks. There is now a way to skip TLS verification for health checks that may help in cases like this:

> By default, a valid SSL certificate is expected. Certificate verification can be turned off by setting the `tls_skip_verify` field to true in the check definition.
