### ISSUE TITLE
Add cli options for setting ports besides http

### ISSUE THREAD

**Issue by dbresson** [hashicorp/consul#2111]
Currently, http-port is the only port that can be set via cli arguments. Please add the other ports. I'm currently having to maintain my own docker image just so I can set the DNS port to 53 since I can't do it via command line arguments.

**Comment by sweeneyb** [comment]
I have a PR out for this, as I'm hitting it, too.  I'm not so sure why my tests are failing, though.  Run individually, the test seems to pass.

https://github.com/hashicorp/consul/commit/f33fde77a5c99bb65dab23603a28fd637ab5a960
