### ISSUE TITLE
Cannot Recycle Node Names Until Reaping

### ISSUE THREAD

**Issue by JohanTan** [hashicorp/consul#2113]
### `consul version` for both Client and Server
Client: `0.6.4`
Server: `0.6.4`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        known_servers = 7
        server = false
runtime:
        arch = amd64
        cpu_count = 16
        goroutines = 33
        max_procs = 16
        os = linux
        version = go1.6
serf_lan:       
        encrypted = true
        event_queue = 0
        event_time = 6272
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 402
        members = 77
        query_queue = 0
        query_time = 3
```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        server = true
raft:
        applied_index = 32110444
        commit_index = 32110444
        fsm_pending = 0
        last_contact = 7.072066ms
        last_log_index = 32110444
        last_log_term = 16308
        last_snapshot_index = 32106118
        last_snapshot_term = 16308
        num_peers = 6
        state = Follower
        term = 16308
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 658
        max_procs = 1
        os = linux
        version = go1.6
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 6279
        failed = 0
        intent_queue = 0
        left = 1
        member_time = 407
        members = 79
        query_queue = 0
        query_time = 3
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 2
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details
Ubuntu 14.04 trusty 64-bit

### Description of the Issue (and unexpected/desired result)
When running consul client in a new node to replace one of the old node which share the same hostname, I tried to run `consul leave` from old node. However, consul-agent could be started on the new node. Digging into upstart logs it showed the following error msg.

My guess is node name has to be unique, even among the nodes that are in the "left" state. After the 72 hour wait, when left nodes were finally reaped, can the consul-agent from new nodes be started with their hostnames as-is.

Is there way to manually reap left nodes, or make sure the uniqueness of node names don't apply to left nodes?

### Reproduction steps
Described above.

### Log Fragments or Link to [gist](https://gist.github.com/)
```
==> Starting Consul agent...
==> Error starting agent: Failed to start Consul client: Failed to start lan serf: Failed to create memberlist: Failed to start TCP listener. Err: listen tcp 10.1.8.22:8301: bind: cannot assign requested address
```

**Comment by tiwilliam** [comment]
Your error seems to be thrown from `bind`, this usually means that the requested address isn't available or already in use on your host. It's weird that it works after 72 hours but I can't see the connection to the host you replace. Can you verify that it's not already in use and that you can bind to this address?

You can eliminate Consul if you see the same error from `nc`:
```
nc -l 10.1.8.22 8301
```

**Comment by slackpad** [comment]
Closing as we haven't heard back (thanks for the help @tiwilliam)! Please let me know if you are still running into issues.
