### ISSUE TITLE
Feature request: Notify systemd after agent has joined cluster

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/consul#2121]
On a system where a client or server needs to use the Consul agent, one would naturally declare a dependency on the Consul agent's startup on its own.  That way it can arrange for Consul to be available before it starts up.  

However, a predicate satisfied solely on Consul starting is insufficient, because a service manager will consider Consul up from the moment it successfully launches.  There then exists a race between Consul joining the cluster and the dependent service launching.  If the dependent service starts too soon, it will fail to resolve Consul services and look up keys.

So, if systemd is managing system startup, it would be useful for Consul to emit an event via sd_notify() after the agent has successfully joined the cluster.   That way one could set Consul's `type` in the Unit file to `notify` and defer starting dependent services until Consul is truly ready to accept queries.

Some useful code may be found at https://github.com/coreos/go-systemd/blob/7b2428fec40033549c68f54e26e89e7ca9a9ce31/daemon/sdnotify.go

**Comment by dredzik** [comment]
Any news on when will this become available?

**Comment by magiconair** [comment]
I'll pick this one up after the next release.
