### ISSUE TITLE
How does the check or the server replicate from one agent to another agent ?

### ISSUE THREAD

**Issue by wenhx8** [hashicorp/consul#2126]
when the agent is  failed which has several checks ,  before recover the agent , how can i do?

**Comment by sean-** [comment]
Hello @wenhx8 , the Consul Agent is the source of truth for checks.  If the Agent has failed, its checks will also be in a failed state until the Agent comes back.  If you have something more specific that you would like to see discussed, please let us know with more detail.  Cheers.
