### ISSUE TITLE
Remove base64 automagic for binary data

### ISSUE THREAD

**Issue by mcandre** [hashicorp/consul#2134]
Please don't try to be quite so helpful--treating all data as binary creates an awkward API in which values are base64 encoded by default, creating more work for users to decode the values.

For most configuration data, UTF-8 strings are all that is required. For binary data, users could on their own perform base64 encoding/decoding; or they may even desire another encoding algorithm.

**Comment by slackpad** [comment]
Hi @mcandre Consul doesn't have any knowledge of the data being stored in the KV entries, so it makes JSON APIs difficult if there are values that can break encoding. You can use the ?raw query parameter to get a single key from /v1/kv without any of the encoding.

**Comment by mcandre** [comment]
Right. I'm saying that the interface is needlessly confusing. If someone wants to put binary data in a key value store, they're welcome to use base64 or whatever String encoding scheme they wish. But by implicitly handling both raw strings and binary data as base64 strings, really makes the interface harder to use. If someone really needs binary support, let them manage the base64 encoding/decoding outside of Consul.

**Comment by slackpad** [comment]
I appreciate that, but it's super common for folks to put even things as simple as JSON into values, which would break Consul's KV APIs that return multiple KVs via JSON as well. This adds an extra step to decode, but avoids tons of issues people would run into with this common use case.
