### ISSUE TITLE
Interaction between nomad, consul health checks, and vault

### ISSUE THREAD

**Issue by dbresson** [hashicorp/consul#2138]
I'm not sure where the actual flaw falls, but Vault's health endpoint returns a 429 by default for standby servers, which consul counts as a warning and so continues to serve up the standby as a valid server to dns queries. If you use the vault.service.consul name for advertising and discovery, this causes a potentially infinite redirect.

Vault's health endpoint accepts standbycode query string parameter for changing that default, but when nomad is given "/v1/sys/health?standbycode=503" as the http check path, consul ends up with the "?" escaped: "/v1/sys/health%3Fstandbycode=503".

I'm not sure whether the unnecessary escaping is happening in Nomad or Consul, but these 3 systems should play nicely together.

**Comment by mterron** [comment]
As of Vault 0.6.0, it also registers active.vault.service.consul name that you can use to advertise and always point to the active instance and standby.vault.service.consul that points to the standby instances in addition to the vault.service.consul that has all of them together  @dbresson

**Comment by dbresson** [comment]
That's handy to know, though the tag prevents it from matching my cert so it doesn't help me. That aside, not being able to add a query string to a health check is still a legitimate issue.

**Comment by sean-** [comment]
@dbresson Thanks for the report.  This is actually an issue that belongs with Vault, not Consul, but I'm happy to resolve the issue here.  Could you let us know what version of Vault you're using?

**Comment by dbresson** [comment]
0.5.3, though I don't see how it's an issue with Vault. The url escaping is happening either in Nomad or Consul.

**Comment by dbresson** [comment]
OK, I dug into the code and discovered the problem is on the nomad side.
