### ISSUE TITLE
atlas_infrastructure directive not authenticating for consul servers, but command line flag works

### ISSUE THREAD

**Issue by micahhausler** [hashicorp/consul#2143]
When filing a bug, please include the following:

### `consul version` for both Client and Server

Server:  v0.6.4

### `consul info` for both Client and Server

Server:
```
consul info -rpc-addr=172.17.0.2:8400
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = 26a0ef8c
	version = 0.6.4
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	server = true
raft:
	applied_index = 0
	commit_index = 0
	fsm_pending = 0
	last_contact = never
	last_log_index = 0
	last_log_term = 0
	last_snapshot_index = 0
	last_snapshot_term = 0
	num_peers = 0
	state = Follower
	term = 0
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 58
	max_procs = 2
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1

```

### Operating system and Environment details

```
$ uname -a
Linux ba50c5db869a 4.5.0-coreos-r1 #2 SMP Thu May 26 22:21:06 UTC 2016 x86_64 Linux
```
os: CoreOS 1010.5.0
container: `gliderlabs/consul-server:0.6`

### Description of the Issue (and unexpected/desired result)
When I start a server with the `atlas_infrastructure` directive in my config file, consul is unable to authenticate with the atlas service. When I use the same configuration file but add the `-atlas my/infrastructure` flag, it authenticates.

### Reproduction steps
Start consul server without `-atlas`.

### Log Fragments 
<img width="1680" alt="screen shot 2016-06-23 at 10 45 52 am" src="https://cloud.githubusercontent.com/assets/791000/16308048/85815f42-3931-11e6-896b-86245e34cf8c.png">

<img width="1684" alt="screen shot 2016-06-23 at 10 41 59 am" src="https://cloud.githubusercontent.com/assets/791000/16308054/8c909712-3931-11e6-8aef-718ed126d9c3.png">

**Comment by slackpad** [comment]
Hi @micahhausler this looks like it might be a typo - the failing case uses "sukid" and the passing case uses "skuid" :-)

**Comment by micahhausler** [comment]
derp. Thanks
