### ISSUE TITLE
consul ui:  duplicate and rename key/directory

### ISSUE THREAD

**Issue by EvertMDC** [hashicorp/consul#2145]
Hello,

I was wondering if it was technically possible to create a 'duplicate' button on the ui so you can clone a directory of keys in the key-value section to something else.
On the same line, would a 'rename' be possible?

I don't mind taking some time to implement this but I'd need to get some help on where to get started.
Would this be considered easy for those who know the code?

Best regards

**Comment by slackpad** [comment]
HI @EvertMDC we are close to what's needed to support this via https://github.com/hashicorp/consul/pull/2028, but I think we'd need to add support for something like `copy-tree` and `move-tree` operations via K/V transactions, then the UI would be simple and reliable. We've had a couple requests for these operations from other folks as well.

**Comment by EvertMDC** [comment]
Hello @slackpad . That's great. I actually didn't find it because I searched on 'ui'.
I went through the code quickly and it seemed like a lot of work already, thank you.

Support for something like copy-tree and move-tree would indeed be interesting for a lot of people in my opinion. It would allow to easily switch between two configurations or test some settings while making a sort of local backup of the current state.

**Comment by chuck-wood** [comment]
+1 here, this would make it a lot easier to transition to Consul.

**Comment by cornfeedhobo** [comment]
I'd love a rename option right now

**Comment by Farfad** [comment]
+1

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!

**Comment by EvertMDC** [comment]
Hello @slackpad . Great to hear that. Where can we follow this progress?

**Comment by slackpad** [comment]
It'll be here on Github so watching the project will show what's going on with the new UI!

**Comment by marioluan** [comment]
@slackpad any progress with this feature?

**Comment by daygr** [comment]
Is there a reason this was closed? Still seems like a valid request.

**Comment by johncowen** [comment]
Hey @daygr 👋 

This is definitely something we can talk about adding to the new UI as an enhancement. We've recently moved any issues relating to the old UI to the `archived/webui` label, but I'm going to add the `ui` label here so we can consider this as part of a enhancement/feature for the new ui.

Thanks for the comment on here!

John

**Comment by jakubgs** [comment]
Still not doable via UI or CLI.
