### ISSUE TITLE
why does the registered service  auto Deregistered?

### ISSUE THREAD

**Issue by wenhx8** [hashicorp/consul#2147]
when i use http api  to register service,the url like  "http://xxxx:xx/v1/catalog/register",the body below:
{
  "Datacenter": "testwen",
  "Node": "agent-four",
  "Address": "10.0.209.56",
  "Service": {
      "ID": "redis56",
    "Service": "redis_register",
    "Tags": [
      "master",
      "v1"
    ],
    "Port": 18100
  }
}
,why does the registered service  auto Deregistered?
Consul log is below:
2016/06/28 11:01:28 [INFO] agent: Deregistered service 'redis56'

**Comment by slackpad** [comment]
Hi @wenhx8 you should use the [Agent API](https://www.consul.io/docs/agent/http/agent.html#agent_service_register), not the Catalog API to register services. [This thread](https://github.com/hashicorp/consul/issues/1188#issuecomment-185977469) has a little more background info on why it's getting deregistered. Hope that helps!

**Comment by wenhx8** [comment]
thx.
The Catalog API document should be  illustrated,
I think that it is better for user to use the Catalog API  .
