### ISSUE TITLE
Service names with a period in them don't resolve in DNS interface.

### ISSUE THREAD

**Issue by darron** [hashicorp/consul#215]
The service name has a period in it:

http://shared.froese.org/2014/0616230937xhyod.jpg

It doesn't resolve:

`dig octodev.io.service.dc1.consul SRV @127.0.0.1 -p 8600`

https://gist.github.com/darron/ea3e366daa60e546feb7

There's no period in this one:

http://shared.froese.org/2014/0616231213j0b29.jpg

Works like a charm:

`dig nyr.service.dc1.consul SRV @127.0.0.1 -p 8600`

https://gist.github.com/darron/6d400d86b8005e9b8a96

This is probably to be expected and I wasn't super surprised when I looked through the docs here: http://www.consul.io/docs/agent/dns.html

Maybe too easy to break things - could a warning be thrown when you add a service name with a period?

**Comment by slackpad** [comment]
The warning was added and through the sands of time has evolved into a debug message. Closing this out.
