### ISSUE TITLE
[ERROR] agent.dns: error serializing DNS results: error="no data"

### ISSUE THREAD

**Issue by jzhao20230918** [hashicorp/consul#21508]
hello,

When I was debuging an issue with envoy I checked consul logs with "journalctl -u consul.service -r" and got lots of error messages as following:
`Jul 03 06:38:14 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:38:14.375Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:38:07 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:38:07.871Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:38:04 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:38:04.369Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:38:04 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:38:04.334Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:38:04 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:38:04.317Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:57 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:57.868Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:57 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:57.853Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:54 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:54.314Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:54 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:54.301Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:47 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:47.850Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:44 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:44.266Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:37 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:37.847Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:34 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:34.262Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:34 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:34.219Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:34 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:34.202Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:34 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:34.188Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:27 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:27.844Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:27 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:27.829Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:24 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:24.184Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:17 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:17.826Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:14 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:14.181Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:14 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:14.161Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:14 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:14.135Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:07 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:07.810Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:37:04 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:37:04.132Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:36:57 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:36:57.807Z [ERROR] agent.dns: error serializing DNS results: error="no data"
Jul 03 06:36:54 ip-10-4-0-215 consul[3984668]: 2024-07-03T06:36:54.128Z [ERROR] agent.dns: error serializing DNS results: error="no data"
`
How can I fix it? Thanks a lot.

**Comment by oavril** [comment]
Hello,

I have exactly the same problem.
I was on version 1.18.2, and even after an upgrade to version 1.19, this message persists.

For example, if I try to resolve this:
<tag>.<service name>.service.consul.<domain>

the korum log reports this message.

I welcome your feedback.

**Comment by oavril** [comment]
Hi,

with version 1.19.0 you can apply this solution : 
https://developer.hashicorp.com/consul/docs/release-notes/consul/v1_19_x

adding this in config files on server correct the problem :
`"experiments": [ "v1dns" ],`

**Comment by jzhao20230918** [comment]
> Hi,
> 
> with version 1.19.0 you can apply this solution : https://developer.hashicorp.com/consul/docs/release-notes/consul/v1_19_x
> 
> adding this in config files on server correct the problem : `"experiments": [ "v1dns" ],`

Thank you. Would it break the transparent proxy function with Nomad?

**Comment by jmurret** [comment]
Hi, this is fixed in main and also will be released in consul 1.19.2

**Comment by jameshartig** [comment]
@jmurret Thank you for the quick fix!

**Comment by jmurret** [comment]
@hferreira23 This experiment was removed in 1.19.2.

**Comment by ChrisNoSim** [comment]
Thanks for the fix. When will the new version be available here in that archive, because we depend on it (at the moment)? 

https://archive.releases.hashicorp.com/debian/buster/amd64/main/
