### ISSUE TITLE
community: How to backup data periodically

### ISSUE THREAD

**Issue by BSick7** [hashicorp/consul#2150]
This isn't a bug, but an extension of a conversation that happened on a vault issue https://github.com/hashicorp/vault/issues/1273.

@jefferai recommended I make my suggestion here.

I created a logical backup utility https://github.com/BSick7/envoy that will dump the consul k/v store into a filesystem and archive into a tar.gz file. This github repo includes automated releases to "GitHub Releases".

**Comment by JensRantil** [comment]
See also https://groups.google.com/d/msg/vault-tool/fQE4KW9gCSc/L2aUstnaNgoJ.

**Comment by astrostl** [comment]
While pointers to years-old mailing list posts and various third-party tooling projects beats nothing, I find Consul (and Consul-backed Vault) to be a difficult proposition for selling a corporate production environment. It looks like this issue has been tagged as DOCS, which is where I would start: formal documentation on disaster recovery, not just single-node-in-a-cluster recovery. On a long enough timeline, Godzilla eating your entire region or a hostile/incompetent actor destroying all your nodes becomes more of a likelihood than a possibility.

**Comment by slackpad** [comment]
Hi @astrostl we are working on a new shapshot/restore API right now and should have some more details soon; it will make DR much easier. There are improvements to make still, but we also updated https://www.consul.io/docs/guides/outage.html with information on how to recover from multiple server outages as part of the 0.7 release. Once we have the new API we will update this with more detailed DR recovery info with a totally new cluster + a snapshot.

**Comment by astrostl** [comment]
My first priority is recovery from a total loss, not a partial loss.

A snashot API and DR documentation sounds wonderful. Looking forward to it!

**Comment by razor-1** [comment]
The new snapshot API is great. However, there are keys that Vault uses during runtime that affect operation after a restore (ref https://groups.google.com/forum/#!topic/vault-tool/kEPvBTpAqh4). So only relying on the backup mechanism of the Vault backend doesn't seem like the right approach.  Could there be a documented approach here, at least with Consul, that would be supported and work going forward?  This would help Vault adoption by allowing a full DR plan to be developed.

**Comment by fproulx-pbox** [comment]
We are also very much interested in having a zero downtime snapshot strategy for disaster recovery. 

Forum posts seem to say that dropping /sys/core/lock and /sys/core/leader works, but that seems like a hack...

**Comment by jaydipdave** [comment]
Consul snapshot works flawlessly, but it works well when you are restoring data to the same servers (vault and consul).  

I use https://github.com/colebrumley/consul-kv-backup utility. Works well, the only thing is when you restore the data you need to delete "vault/core/lock" and "vault/core/leader" entries from the "backup.json" file.
 
I also like https://github.com/shaneramey/vault-backup/blob/master/vault-dump.py, but it needs some testing and improvement. 

I recommend, using inbuilt consul snapshot and consul-kv-backup both for a perfect backup plan. The backup size is hardly few MBs.
Consul backup:
```
# Snapshot
curl -k https://consul:8500/v1/snapshot -o snapshot.tgz

# KV backup
consul-kv-backup --addr consul  --scheme https --port 8500 --insecure backup > backup.json
```
Consul restore:
```
# Snapshot
curl -k -XPUT --data-binary @snapshot.tgz  https://consul:8500/v1/snapshot

# KV backup
./consul-kv-backup --addr consul --scheme https --port 8500 --insecure restore backup.json
```

**Comment by jaydipdave** [comment]
Consul snapshot works flawlessly, but it works well when you are restoring data to the same servers (vault and consul).  

I use https://github.com/colebrumley/consul-kv-backup utility. Works well, the only thing is when you restore the data you need to delete "vault/core/lock" and "vault/core/leader" entries from the "backup.json" file.
 
I also like https://github.com/shaneramey/vault-backup/blob/master/vault-dump.py, but it needs some testing and improvement. 

I recommend, using inbuilt consul snapshot and consul-kv-backup both for a perfect backup plan. The backup size is hardly few MBs.
Consul backup:
```
# Snapshot
curl -k https://consul:8500/v1/snapshot -o snapshot.tgz

# KV backup
consul-kv-backup --addr consul  --scheme https --port 8500 --insecure backup > backup.json
```
Consul restore:
```
# Snapshot
curl -k -XPUT --data-binary @snapshot.tgz  https://consul:8500/v1/snapshot

# KV backup
./consul-kv-backup --addr consul --scheme https --port 8500 --insecure restore backup.json
```

**Comment by slackpad** [comment]
Thanks @jaydipdave there are also CLI commands you can use instead of the API directly - https://www.consul.io/docs/commands/snapshot.html.

**Comment by slackpad** [comment]
Closing this against https://github.com/hashicorp/consul/issues/2583, which captures the forward docs work left to do.
