### ISSUE TITLE
TCP node check

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/consul#2152]
### `consul version` for both Client and Server

Client:0.6.4
Server: 0.6.4
### `consul info` for both Client and Server

Server:

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        server = true
raft:
        applied_index = 4177652
        commit_index = 4177652
        fsm_pending = 0
        last_contact = 40.064884ms
        last_log_index = 4177652
        last_log_term = 1177
        last_snapshot_index = 4170989
        last_snapshot_term = 1152
        num_peers = 5
        state = Follower
        term = 1177
runtime:
        arch = amd64
        cpu_count = 12
        goroutines = 104
        max_procs = 2
        os = linux
        version = go1.6
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 272
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 325
        members = 31
        query_queue = 0
        query_time = 12
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```
### Operating system and Environment details

Ubuntu 14.04 x64
### Description of the Issue (and unexpected/desired result)

I'm running 30 nodes cluster(5 masters), all 0.6.4, one DC, all in same LAN. And rely heavily on a Consul DNS service.
From time to time, I have strange issues with nodes ping, like:
https://gist.github.com/Oloremo/159469469c20e2bcc1a8942f32bd5a65

In a log above I lost node "psql1-liveclasses" for 12 seconds. Which is a lot. I'm not 100% what cause this disconnections, but I believe what single UDP check is not reliable.
Does Consul has a TCP nodes check? Or check re-try? What do you think about allow  "allow_stale" option work for this case too?

With a single node behind dns name I'd really prefer a stale answer, then no answer at all.

Problem: Single UDP check breaks whole cluster(dns service)
Expected: TCP check of a node before full cluster re-election.
### My Research

So, checked the source code to get my answers

https://github.com/hashicorp/consul/blob/v0.6.4/vendor/github.com/hashicorp/memberlist/state.go#L218-L327
There is a 4 steps in node check:
1) Send a UDP ping, wait for timeout
2) If timeout reached - log "Failed UDP ping" - as I have in my log.
3) Take a random live node and send UDP ping from it. Consul doesn't log the result of this ping(!)
4) If option DisableTcpPings is False AND protocol version is 3 and above - send a TCP ping and log it. I don't have this in my logs, so I clearly doesn't have a TCP check in my env.

Please correct me if I'm wrong, I'm completely new to GO.

Now lets check why it doesn't trigger TCP check.
DisableTcpPings is False by default and I didn't override it in my config.
https://github.com/hashicorp/consul/blob/v0.6.4/vendor/github.com/hashicorp/memberlist/config.go#L180

So, only protocol version left.
`consul -v` tells me
`Consul Protocol: 3 (Understands back to: 1)`

but consul members tells me what all nodes operate with protocol 2.
And we have this issue describing this situation as normal: https://github.com/hashicorp/consul/issues/1531

Now I'm really wondering if it's really true and how to check if my nodes speak with v3.
### Reproduction steps

None
### Log Fragments or Link to [gist](https://gist.github.com/)

https://gist.github.com/Oloremo/159469469c20e2bcc1a8942f32bd5a65

**Comment by slackpad** [comment]
Hi @Oloremo you are correct that the protocol version thing is a little confusing but if you are using 0.6.4 everywhere then it's definitely using the TCP fallback ping, there's no debug logging around those, unfortunately. 

The most likely cause for outages like this is when low end cloud instances (t2.micro and similar) get overloaded and experience periods lasting tens of seconds with heavy packet loss. We've got some [changes teed up in master](https://github.com/hashicorp/consul/pull/2101) designed to combat this by preventing one bad node from being able to mark a bunch of others as failed. This should be shipping soon in 0.7. We've also got some work in progress on a retry under the hood when servicing DNS requests - https://github.com/hashicorp/consul/pull/2002. Hopefully these changes can help make things more robust for you.

**Comment by Oloremo** [comment]
@slackpad Thanks you for a quick reply.
I really glad to hear what some work is done towards this issues, but about logging, there is TCP ping log here: https://github.com/hashicorp/consul/blob/v0.6.4/vendor/github.com/hashicorp/memberlist/state.go#L292 and I wonder why I can see it in my logs

**Comment by slackpad** [comment]
@Oloremo I just meant that there's no debug logging for that when it sends the ping :-) If it sends the ping but ends up hearing back over UDP from the indirect pings it won't print that final message, and the log message you linked should only happen if there's a socket error. If you can run a local build you could probably supplement with some extra logging or telemetry to confirm this.

**Comment by rgardam** [comment]
@slackpad I think this is the same as https://github.com/hashicorp/consul/issues/916 right?

Did you see my last comment on this topic?

**Comment by slackpad** [comment]
Closing this has #916 is indeed similar and we've done work in the Consul 0.7.x series to help limit what can happen across the cluster if a node is CPU starved and starts failing network probes.
