### ISSUE TITLE
Proposal: One-off commands through `consul lock`

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/consul#2154]
**Usecase:** I have a shell command I'd like to execute once on a bunch of Consul agent hosts. I only want a concurrency level of X to not choke the system. This sounds like a perfect usecase for a semaphore. However, implementing semaphore for a shell script is [cumbersome](https://www.consul.io/docs/guides/semaphore.html). `consul lock` supports semaphore, but it will restart my shell command over and over again.

**Proposal:** Add a `consul lock -oneoff` parameter that acquires a semaphore, executes the command and then exits. What do you think?

**Workaround:** I could use the restarting `consul lock my-script.sh` and have my script do something like:

```
#!/bin/sh

# Check if file XXX exists. If so, sleep 5 seconds (to not spin CPU) and then quit.
# Create the file XXX
# Run my command
```

**Comment by JensRantil** [comment]
A different workaround is to have the script kill the `consul agent lock` command (using something like `$PPID`) when it's done.

**Comment by jippi** [comment]
name wise `-once` would be more consistent - i like the idea though :)

**Comment by JensRantil** [comment]
;) I'm totally fine with `-once`.

**Comment by JensRantil** [comment]
I got started implementing a shell semaphore (with `jq` dependency) https://gist.github.com/JensRantil/4173e4f1ecf031f3f263e5a1c2f5f861 Gave up after a while.

**Comment by slackpad** [comment]
Hi @JensRantil have you looked at the [`consul lock`](https://www.consul.io/docs/commands/lock.html) command? If I understand your use case correctly I think it does exactly what you are looking for :-)

`consul lock -n=<concurrency> /some/lock/prefix yourscript.sh`

This will run up to `n` at any given time and will simply execute the command and then exit.

**Comment by JensRantil** [comment]
@slackpad Slackpad. Rereading the documentation I now see that the `consul lock` command doesn't restart a command! 👍  Closing this!
