### ISSUE TITLE
service have error tag on ui

### ISSUE THREAD

**Issue by ianwoolf** [hashicorp/consul#2155]
i have to service"test" and "Test". "test" have tag "zzz",  and "Test" have tag "test358".  

but the service have to tag on ui "/ui/#/dc/scrvices/test", service "test" and "Test" both have tag "zzz" and "test358".

api "/v1/catalog/services" and its return:

```
{
    Test: ["test358"],
    test: ["zzz"]
}
```

service "test" have tag "zzz",  service "Test" have tag "test358"

but the api /v1/internal/ui/services return have error: service "test" and "Test" both have tag "zzz" and "test358"

p.s:

```
i notice the return of  "/v1/internal/ui/services" have error(service and tag).
```

**Comment by ianwoolf** [comment]
/v1/catalog/service/test has return error, it return info of service "Test"
[
{
Node: "mjq-pivot-cdn-cc04-data01",
Address: "10.183.229.38",
ServiceID: "test",
ServiceName: "test",
ServiceTags: [
"zzz"
],
ServiceAddress: "",
ServicePort: 0,
ServiceEnableTagOverride: false,
CreateIndex: 2493,
ModifyIndex: 2493
},
{
Node: "mjq-pivot-cdn-cc04-data03",
Address: "10.183.229.40",
ServiceID: "Test",
ServiceName: "Test",
ServiceTags: [
"test358"
],
ServiceAddress: "",
ServicePort: 0,
ServiceEnableTagOverride: false,
CreateIndex: 2238,
ModifyIndex: 2370
},
.....

**Comment by slackpad** [comment]
Interesting - this is probably due to the same name, different capitalization.

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
