### ISSUE TITLE
Feature: Allow ACL to deny listing nodes / acl_default_policy should affect nodes

### ISSUE THREAD

**Issue by EugenMayer** [hashicorp/consul#2163]
When configuring the consul-server like this:

```
{
  "acl_datacenter": "stable",
  "acl_default_policy": "deny",
  "acl_down_policy": "deny"
  "datacenter": "stable",
  "data_dir": "/consul/data",
  "ui": true,
  "log_level": "INFO",
  "node_name": "consul",
  "client_addr" : "0.0.0.0",
  "server": true,
  "bootstrap": true,
  "encrypt":"GdKfGQLlnziTxh/Vt4DW4A==
  "acl_master_token:"474238df-2199-4e67-a1e6-638bdb8f6740"
}
```

so using a blacklist for everything, i can still list all nodes

```
curl http://consul:8500/v1/catalog/nodes
{"consul":[] .... others}%
```

without providing a token - so using the anonymous token. Even if i add a explicit rule (which should not be needed)

```
node "" {
   policy="deny"
}
```

Still the same results. Same goes for listing nodes and anything else. I cannot list any KV though - so that is secured ( or add any ACL with the anon token ).
# Proposal
- Also disallow listing nodes when default acl is deny
- Allow ACLs to disallow node listing similar to services
### Meta informations

```
consul --version
Consul v0.6.4
Consul Protocol: 3 (Understands back to: 1)
```

**Comment by solomongifford** [comment]
This would essentially allow for a lite multitenancy.  Definitely need with this.

**Comment by rbrutas** [comment]
👍  we definitely need this, i thought this was added on the latest release 0.7.1 :(
