### ISSUE TITLE
v1/health/state/passing is not protected by ACL

### ISSUE THREAD

**Issue by EugenMayer** [hashicorp/consul#2166]
Excactly the setup from #2163

```
curl http://consul:8500/v1/health/state/passing  | grep fpm
"CheckID":"fpm55","Name":"fpm TCP on port 9055","Status":"passing","Notes":"","Output":"TCP connect localhost:9055: Success",
```

while services are not listed at all

```
curl http://consul:8500/v1/catalog/services
{"consul":[]}%
```

Those curl commands have been run on the same instance, remotely on a consul port running a container - so not credentials whatever

**Comment by EugenMayer** [comment]
Further tests applied, health/service/<service> works as supposed

    curl http://consul:8500/v1/health/service/fpm55
    []%

while

    curl http://localhost:8500/v1/health/service/fpm55\?token\=386887ed-0f8d-a89d-abfb-ca0067edb918

Lists the service status. So this one is protected - probably just the state/passing (and others) are onprotected

**Comment by slackpad** [comment]
Hi @EugenMayer this code path looks identical to the others. Is it possible that `fpm55` is a node-level check, not associated with any service?

**Comment by EugenMayer** [comment]
@slackpad how would i check this for sure - not wanting to confuse you. What i do to register this service is

    echo '{"service": {"name": "fpm55","address":"php", "port": 9055, "tags": ["primary"]}, "check": {"id": "fpm55", "name": "fpm TCP on port 9055","tcp": "localhost:9055","interval": "10s","timeout": "1s"}}' > /etc/consul.d/php55.json

And then i restart consul to pick up the service. The node does not have any checks. You should even see this issue in the node-list:

https://goo.gl/vj7Fyf

As you see, i can see the services when selecting the node. As you see, since the UI has yet no token, you see all nodes have 0 services ( on the left side ) listing the services looks like this https://goo.gl/ixSxej

It should be pretty easy to reproduce and you see this issue gets visible from different angles.

**Comment by slackpad** [comment]
Ok that looks like a service-level check - will write a unit test and chase it down from there.

**Comment by kyhavlov** [comment]
I tried and couldn't reproduce this with a service-level check; node level check filtering was added in 0.7.2 with the `acl_enforce_version_8` option. If someone can provide a clear repro case for this we can reopen the issue.
