### ISSUE TITLE
Empty service name as given in documentation is not allowed in code

### ISSUE THREAD

**Issue by misham** [hashicorp/consul#2167]
I am following the example given here: https://www.consul.io/docs/internals/acl.html

I am setting the `service` flag to in my server config:

```
...
"service": {
      "": {
          "policy": "write"
      }
}
...
```

And I'm getting an error: `Failed reloading services: Failed to register service '': Service name missing`

According to the following line in the code, this is correct error: 
 https://github.com/hashicorp/consul/blob/master/command/agent/agent.go#L741

I'm not sure if the code or the docs are wrong, but trying to figure out how to declare a blank ACL policy that allows

**Comment by slackpad** [comment]
Hi @misham it looks like you are using the ACL language as part of the service definition in your agent config which isn't possible. ACLs are managed using the [ACL endpoint](https://www.consul.io/docs/agent/http/acl.html), and the policies in the guide you referenced go into the `Rules` field when creating or updating tokens.

**Comment by misham** [comment]
I was trying to define it as part of the config for each of the 3 server nodes.  Here's an example of a setup I'm experimenting with:  https://gist.github.com/misham/bc8afd9f1ecde8454d3c13857789fb42

I'd like to define some of these rules globally, so I don't have to bring them up over an API call but they're just baked in.

**Comment by slackpad** [comment]
By design (since ACLs don't belong to the agent but are part of the state on the servers) we don't allow them to be defined statically. The K/V store works in a similar way. You'll need something like a shell script to set these up when you create your cluster for the first time. You can use `anonymous` for the token ID to create a default policy that applies when no token is present, such as to allow any service to be read.

**Comment by misham** [comment]
I see.  So anything to do with creating ACL tokens or managing access via ACLs has to be done via the API?

Curious about the drivers behind this as I'm trying to understand the context better.

Thank you

**Comment by slackpad** [comment]
The ACLs don't belong to any particular agent, so they are maintained in the state that the Consul servers manage, so it doesn't make sense to define them along with an agent's configuration. The agent's configuration is responsible for the services running on that agent, but things like ACLs and K/V entries are managed by the servers, so their lifecycle is handled through APIs. The servers also do all ACL enforcement - none of that is in the client agents. Hope that helps!

**Comment by misham** [comment]
Oh ok, so I think I didn't explain very well where I'm defining the config.  My test system is configured as follows:

* 3 Consul servers each on their own instance
* 2 Consul agents running on separate instances that will house an application and a worker each, respectively

The config [I shared in the gist](https://gist.github.com/misham/bc8afd9f1ecde8454d3c13857789fb42) is on each of the 3 Consul servers.

Each of the 2 Consul agents has the following config:

```json
{
    "server": false,
    "bind_addr": "10.0.0.18",
    "acl_datacenter": "test-1",
    "datacenter": "test-1",
    "acl_token": "1234",
    "data_dir": "/opt/consul-data",
    "log_level": "INFO",
    "enable_syslog": true,
    "start_join": ["10.0.0.10", "10.0.0.11", "10.0.0.12"],

    "services": [
        {
            "id": "app01",
            "name": "app",
            "address": "10.0.0.18",
            "port": 80,
            "enableTagOverride": false,
            "checks": [
                {
                    "name": "app",
                    "http": "http://10.0.0.18",
                    "interval": "60s",
                    "timeout": "1s"
                }
            ]
        }
    ]
}
```

I would like to define a global set of ACL rules, starting with `service` as defaults.  Then, each individual agent will have startup scripts to get an ACL token for a specific action, which will create the needed ACL rules as well.

Hopefully this makes sense.

Also, I haven't found any good guides for how to use ACLs based on their design or good walkthroughs with examples.  If you have anything like that, would really appreciate it if you could share.

Thank you for responding so quickly as well.

**Comment by slackpad** [comment]
Sorry for the delay in getting back to this - we just released a rewrite of the ACL guide - https://www.consul.io/docs/guides/acl.html.
