### ISSUE TITLE
Consul node IP not getting deleted even after graceful exit (setting leave_on_terminate": true )

### ISSUE THREAD

**Issue by sakshigeminisys** [hashicorp/consul#2169]
Hi Guys

I am running a containerized version of consul single node cluster with volumes attached. When I bring this single node cluster up for the first time, the leader is elected successfully. I see the following entry is added in the peers.json 
["172.17.4.162:8300"] ==> this is correct as 172.17.4.162 is IP of my container.
Now, I remove this container and make sure that it exits gracefully as I have set **"leave_on_terminate": true** in my configuration file. After exit, the peers.json returns **null**. Up to this point, everything seems good. Now, when I restart the consul single node cluster, the IP assigned to the new container is now ["172.17.4.170:8300"] and this is added in peers.json successfully and this is the only value exisitng in peers.json.
In spite of this, consul deployment fails. The new node somehow tries to connect to the previous IP "172.17.4.162" hat has already been deleted from peers.json. 

Consul version that I am using: 
root@consul:/# consul --version
Consul v0.6.4
Consul Protocol: 3 (Understands back to: 1)

Here are the logs: 
2016/07/06 20:10:50 [INFO] serf: EventMemberJoin: consul 172.17.4.170
2016/07/06 20:10:50 [INFO] serf: EventMemberJoin: consul.dc1 172.17.4.170
2016/07/06 20:10:50 [INFO] raft: Node at 172.17.4.170:8300 [Follower] entering Follower state
2016/07/06 20:10:50 [INFO] consul: adding LAN server consul (Addr: 172.17.4.170:8300) (DC: dc1)
2016/07/06 20:10:50 [INFO] consul: adding WAN server consul.dc1 (Addr: 172.17.4.170:8300) (DC: dc1)
2016/07/06 20:10:50 [ERR] agent: failed to sync remote state: No cluster leader
2016/07/06 20:10:52 [WARN] raft: Heartbeat timeout reached, starting election
2016/07/06 20:10:52 [INFO] raft: Node at 172.17.4.170:8300 [Candidate] entering Candidate state
2016/07/06 20:10:52 [INFO] raft: Election won. Tally: 1
2016/07/06 20:10:52 [INFO] raft: Node at 172.17.4.170:8300 [Leader] entering Leader state
2016/07/06 20:10:52 [INFO] consul: cluster leadership acquired
2016/07/06 20:10:52 [INFO] consul: New leader elected: consul
2016/07/06 20:10:52 [INFO] raft: Disabling EnableSingleNode (bootstrap)
2016/07/06 20:10:52 [INFO] raft: Added peer 172.17.4.162:8300, starting replication
2016/07/06 20:10:52 [INFO] raft: Removed peer 172.17.4.162:8300, stopping replication (Index: 18)
2016/07/06 20:10:52 [INFO] consul: member 'consul' joined, marking health alive
2016/07/06 20:10:53 [INFO] agent: Synced service 'consul'
2016/07/06 20:10:55 [ERR] raft: Failed to heartbeat to 172.17.4.162:8300: dial tcp 172.17.4.162:8300: getsockopt: no route to host
2016/07/06 20:10:55 [ERR] raft: Failed to AppendEntries to 172.17.4.162:8300: dial tcp 172.17.4.162:8300: getsockopt: no route to host
2016/07/06 20:10:58 [ERR] raft: Failed to heartbeat to 172.17.4.162:8300: dial tcp 172.17.4.162:8300: getsockopt: no route to host

Could anyone help me find the reason?

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @sakshigeminisys we don't recommend a single node cluster, as even replacing the server will cause an outage. You are recovering correctly, though, by putting the new server into the peers.json. There are references in the Raft log to the configuration with the old IP, and that's what's causing the trouble here. We've got a fix for this coming in 0.7.0 which will make it respect the peers.json's configuration as final. That said, we hope you run at least 3 servers for any production situation :-)

**Comment by sakshigeminisys** [comment]
Hi Guys

I am using single node containerized version of consul. 
Unlike hosts, the container IP changes everytime whenever we either restart it or stop-start it. 
Now, the peers.json stores the IP of this container (server node) as it is a single node consul setup. 
I am also setting "skip_leave_on_interrupt": false and "leave_on_terminate": true in the consul config file. 
**ISSUE:** The peers.json is not updated in case the ip of the container changes (i.e. whenever the container restarts or stop/start). It still contains the older IP values and the new IP gets appended in the file. 
As per the consul documentation, if we set "leave_on_terminate": true in consul config, peers.json should be updated with a null value whenever  "docker stop" is issued on this container. But, in my case, no null is written in the file. Instead, the new IP gets appended in peers.json and hence result in failure in leader election.

what could lead to this behavior? any pointers???

The consul version that I am using : 
Consul v0.6.4
Consul Protocol: 3 (Understands back to: 1)

The config file : 
{
	"data_dir": "/data",
	"ui_dir": "/ui",
	"client_addr": "0.0.0.0",
	"datacenter":"dc1",
	"ports": {
		"dns": 53
	},
	"addresses": {
                "http": "0.0.0.0"
        },
	"recursor": "8.8.8.8",
	"disable_update_check": true,
        "skip_leave_on_interrupt": false,
	"leave_on_terminate": true,
	"acl_datacenter":"dc1",
	"acl_default_policy": "deny",
"acl_master_token": "ao_secret"
}
