### ISSUE TITLE
Automatic server controller

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2171]
This is a placeholder issue for a server controller feature that is in the early design phase. Some [context here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/52TihXInmzw/UC5I8bbKAgAJ).

**Comment by pradeepnss** [comment]
Hi, Would this be part of the 0.7 release ?

**Comment by slackpad** [comment]
Hi @pradeepnss this won't be in the 0.7 release but should make it into one of the following releases.

**Comment by slackpad** [comment]
This shipped in 0.8.0 as [Autopilot](https://www.consul.io/docs/guides/autopilot.html).
