### ISSUE TITLE
Error in docs, checking before submitting PR

### ISSUE THREAD

**Issue by akbarahmed** [hashicorp/consul#2176]
The incorrect documentation applies to the following Consul versions:

Consul version: `0.6.4` through `master` HEAD

The incorrect documentation can be seen at the following URL:

**Documentation Page**: https://www.consul.io/docs/agent/http/catalog.html#catalog_register

The example JSON shows `TaggedAddresses` nested inside of `Service`. However, the `type RegisterRequest struct` has TaggedAddresses` at the top level of `RegisterRequest`.

Please see:

**Ref**: https://github.com/hashicorp/consul/blob/v0.6.4/consul/structs/structs.go
**Ref**: https://github.com/hashicorp/consul/blob/master/consul/structs/structs.go

If this is in fact an error in the example JSON, I'll issue a PR.

**Comment by slackpad** [comment]
Hi @akbarahmed you are correct - that's an error. Appreciate the offer for a PR!

**Comment by akbarahmed** [comment]
@slackpad I'll work on submitting the PR before Sunday. Knee deep in some complicated code...so I'll get this done when I need a breather.

BTW, thanks for releasing Consul. We're loving it.
