### ISSUE TITLE
Show current cluster leader in cli

### ISSUE THREAD

**Issue by quulah** [hashicorp/consul#2180]
Would be nice if the current leader would show up in some consul command.

_consul info_ will tell if that node is the leader, perhaps _consul members_ could mark the leader with an asterisk.

**Comment by slackpad** [comment]
Hi @quulah indeed - this is a duplicate of https://github.com/hashicorp/consul/issues/2180. I think we can add a column to `consul members` for this. Thanks for opening an issue.

**Comment by quulah** [comment]
Great, thanks. Though the duplicate link seems to refer to this issue.
