### ISSUE TITLE
consul rest api ?

### ISSUE THREAD

**Issue by Kenovo** [hashicorp/consul#2181]
Hello,
can i access the consul REST API on all consul servers or juste on the bootsrap servers ?
can i install multiple bootsrap servers in the same datacenter ?

(i want to avoid consul rest api spof)

**Comment by slackpad** [comment]
Hi @Kenovo generally you run the local agent on each machine and have your applications talk to their local agent (localhost:8500). Consul will take care of forwarding requests up to the servers for you behind the scenes. This way, the rest api is coupled to the same failure domain as the node running the agent, and with multiple Consul servers you won't have a SPOF. If you do happen to need to make requests against a server you can choose any server. It will forward to the leader automatically if needed. Hope that helps!
