### ISSUE TITLE
Connect services across datacenters with mesh gateways

### ISSUE THREAD

**Issue by xzhaoxz** [hashicorp/consul#21854]
There are 6 machines A1 A2 A3, B1 B2 B3. A1 A2 A3 network is interconnected, B1 B2 B3 network is interconnected, A3 B3 network is interconnected, and the rest of the networks are not interconnected. Now two single-node consul clusters are deployed on A1 B1 respectively, and a service service-a2 serverice-b2 is used on A2 B2 to register services with A1 B1 respectively through consul client. A mesh gateway is deployed on A3 B3 to connect the two data centers through envoy proxy. It enables service-a2 serverice-b2 to access each other. Can you give the specific configuration on each machine?

**Comment by rboyer** [comment]
Github issues are not a support forum. Please use our forums for this type of assistance: https://discuss.hashicorp.com/c/consul
