### ISSUE TITLE
Critical Golang vulnerability in envconsul v0.13.2

### ISSUE THREAD

**Issue by noahtrilling** [hashicorp/consul#21879]
There are several open issues created for critical Golang vulnerabilities in envconsul 0.13.2 and 0.13.1 that have gone ignored and unresolved.

[Critical Golang vulnerability in v0.13.2](https://github.com/hashicorp/envconsul/issues/362)

There are commits merged into main that update the Golang version, but no new release has been created.

[update go version to 1.22.4](https://github.com/hashicorp/envconsul/commit/38dbfeda48aeeac519beeaada22803bd443651fe)

According to the CODEOWNERS file, the Consul team owns envconsul.

[envconsul CODEOWNERS](https://github.com/hashicorp/envconsul/blob/main/.github/CODEOWNERS#L2)

Since the issues in the envconsul repository appear to be unmonitored, I am creating an issue here to have the vulnerabilities addressed. Please create a new release of envconsul to resolve the Golang vulnerabilities cited in the envconsul issues.

**Comment by dduzgun-security** [comment]
Hi @noahtrilling , thanks for bringing this to our attention. We'll address them soon in the envconsul repository. I'll go ahead and close this as it's a duplicate of the https://github.com/hashicorp/envconsul/issues/362. 

For future reporting of vulnerabilities, we recommend using the `security@hashicorp.com` mailing list the have faster replies as described in our guide https://www.hashicorp.com/trust/security/vulnerability-management. 

Thanks again.
