### ISSUE TITLE
does consul support TXT and AAAA record formats as a dns server?

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2189]
version: 0.6.4

**Comment by kwilczynski** [comment]
@hehailong5 you mean, whether it can serve TXT (which would be custom) and AAAA resource records for a node? Only AAAA is supported at the moment, and it does not support custom resource-records. As per [dns.go#L386-L390](https://github.com/hashicorp/consul/blob/master/command/agent/dns.go#L386-L390). Also related: https://github.com/hashicorp/consul/issues/1470

**Comment by slackpad** [comment]
Closing based on @kwilczynski's response.
