### ISSUE TITLE
consul health check is problem !

### ISSUE THREAD

**Issue by yeyincai** [hashicorp/consul#2194]
service register to  consul ,and add health-check url,look for  consul-health tcp status ,many tcp on TIEM-WAIT, Cause the program is not available ，why?

使用consul注册服务，并且添加了健康检查url，查看consul的健康检查的tcp状态，很多tcp状态都是time_wait，导致服务器挂了，为什么?

**Comment by slackpad** [comment]
Hi @yeyincai can you provide any more details about what's going on? Is your service down and Consul's health checking causing many TCP sockets to accumulate in TIME_WAIT, or is your service working properly and there's something causing Consul to stop functioning? Thanks!

**Comment by slackpad** [comment]
Closing since we haven't heard back. Please @-me if you still need help!
