### ISSUE TITLE
Docs on setting up consul web ui need to be enhanced 

### ISSUE THREAD

**Issue by vikasmb** [hashicorp/consul#2198]
Consul UI getting started [page](https://www.consul.io/intro/getting-started/ui.html) mentions only that
"To set up the self-hosted UI, start the Consul agent with the -ui parameter:" is mentioned.

This might lead the reader to think that no other steps are required apart from specifying the -ui parameter option during startup. Actual process is to 
1) Download the consul web ui from https://www.consul.io/downloads.html.
2) Unzip it to a directory.
3) Specify the directory created in step2 as the value for "-ui-dir" property during consul startup
4) Include "-ui" parameter during startup.

It would be great if the docs clearly mentioned the above four steps in the setting up of self-hosted UI to help new users of Consul get started quickly.

**Comment by slackpad** [comment]
Hi @vikasmb that's no longer the case after Consul 0.6.0. We build the UI contents into the Consul binary so `-ui` is all you need. We support the old method with `-ui-dir` for backward compatibility and because some people tweak the UI locally for various things. Hope that helps!
