### ISSUE TITLE
ACL Rule Spec Validation

### ISSUE THREAD

**Issue by ramukima** [hashicorp/consul#2206]
I am able to add rules (make sure both do not exist at the same time) using the UI with following specifications:
1. key "foo/bar" {policy = "read"}  - This returns a token say "valid-rule"
2. key foo/bar {policy = read} - This returns a token say "invalid-rule"

UI does not complain of any issues in both cases and accepts both requests. Confirmed that none of the above are rejected by the server.

When trying to access the folder foo/bar using token "valid-rule" token, I see that the ACL is enforced. However, trying to access the folder foo/bar/ using token "invalid-rule" does not show the results.

I tested first with rule (1) in place, and then after updating the rule (1) with the rule (2) as well. 

Since rule (2) is not going to work in any case, Consul should reject such a rule upfront to avoid troubleshooting problems.

**Comment by mkeeler** [comment]
Closing this as the new ACL system will ensure the rules compile prior to policy creation/updating.

One thing to note is that these additional checks do not apply to the legacy/deprecated ACL system.
