### ISSUE TITLE
Feature: Vault integration for consul TLS / gossip key

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/consul#2209]
Consul requires certain encryption keys and CA infrastructure.  This would be conveniently stored in a Vault instance, this this feature request is to allow Consul to fetch its gossip key and TLS keys out of Vault.

This does create a chicken/egg when using Consul as a back-end to Vault, so the consul 'servers' would generally need to rely on a different 'non-consul' version of Vault, while the rest of the environment uses a consul-ized vault.

**Comment by jhmartin** [comment]
Noting that the chicken/egg is less likely now as Vault has its own built-in consul leader and storage mechanism.

**Comment by david-yu** [comment]
Our recommendation for users on K8s is to use the Vault Secrets Backend: https://developer.hashicorp.com/consul/docs/k8s/deployment-configurations/vault. For VMs, you could also utilize the KV store and PKI to help with TLS ([example](https://developer.hashicorp.com/consul/tutorials/vault-secure/vault-pki-consul-secure-tls)) and storage of Consul specific credentials. Will go ahead and close, but please file additional feature requests with more details to help us better understand which use cases to consider.
