### ISSUE TITLE
Documentation unclear on CONSUL_RPC_ADDR

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/consul#2210]
https://www.consul.io/docs/agent/options.html states 
```You can also place the desired values in CONSUL_RPC_ADDR and CONSUL_HTTP_ADDR environment variables.``` and then ```For TCP addresses, these should simply be an IP address without the port. For example: 10.0.0.1, not 10.0.0.1:8500. Ports are set separately in the ports structure. ```

Yet, when specifying the address sans-port, a dial error is returned:
```
/ # echo $CONSUL_RPC_ADDR
172.x.x.x
/ # consul members
Error connecting to Consul agent: dial tcp: missing port in address 172.x.x.x
```

This is in Consul 0.6.4 inside the official Consul docker image.
Adding the port number works around the error.

**Comment by swade1987** [comment]
@jhmartin should this issue not be https://github.com/hashicorp/docker-consul ?

**Comment by jhmartin** [comment]
@swade1987 The docker image does not document nor transform CONSUL_RPC_ADDR -- docker generically passes through the environment to Consul.  I believe that makes it a Consul doc issue rather than something related to the Docker image. 

I referenced the Docker image to describe in what environment Consul was running.
