### ISSUE TITLE
DNS SRV returnning wrong hostnames

### ISSUE THREAD

**Issue by janisz** [hashicorp/consul#2218]
Client: `0.6.4`
Server: `0.6.4`

### Description of the Issue (and unexpected/desired result)
When obtaining services with DNS SVR backed with prepared query. Returned hostnames could not be resolved by Consul.

### Reproduction steps

1. Create prepared query
```json
{
  "ID":"01e751dd-3386-5e9c-f2d1-160799d7c8da",
  "Name":"",
  "Session":"",
  "Token":"",
  "Template":{
    "Type":"name_prefix_match",
    "Regexp":""
  },
  "Service":{
    "Service":"${name.full}",
    "Failover":{
      "NearestN":2,
      "Datacenters":[
        "dc1",
        "dc2"
      ]
    },
    "OnlyPassing":false,
    "Tags":null
  },
  "DNS":{
    "TTL":""
  },
  "CreateIndex":5143303,
  "ModifyIndex":7721140
}
```

```
 dig @agent.dc1.consul -p 8600 my-service.query.consul. SRV

;; ANSWER SECTION:
my-service.query.consul. 0	IN	SRV	1 1 31529 my-hostname-from-dc2.node.dc1.consul.

```

```
 dig @agent.dc1.consul -p 8600 my-hostname-from-dc2.node.dc1.consul. A
```
returns no results.

Problem lies in consul adding `<dc>.consul` from agent performing query not the agent service is located.

**Comment by janisz** [comment]
I see 2 possible hotfixes

1. Falback to other DC if not found service in local DC: [command/agent/dns.go#L394](https://github.com/hashicorp/consul/blob/ab1654758f3e216ef0035ba3ae2defaccb772747/command/agent/dns.go#L394)
2. Somehow return proper DC suffix for node: [command/agent/dns.go#L747](https://github.com/hashicorp/consul/blob/master/command/agent/dns.go#L747)

**Comment by maxvt** [comment]
Looks like you have the same issue as me. Please take a look at https://github.com/hashicorp/consul/pull/2219
