### ISSUE TITLE
DNS prepared query failover: does not translate WAN addresses, SRV returns incorrect datacenter

### ISSUE THREAD

**Issue by maxvt** [hashicorp/consul#2220]
Consul version is 0.6.4 for both client and server, running on Ubuntu 14.04.

### Description of the Issue (and unexpected/desired result)
When a DNS prepared query fails over to a different datacenter, the result does not translate WAN addresses despite configuration and SRV query returns incorrect datacenter as part of the "hostname".

### Reproduction steps
Multiple datacenters with translate WAN enabled. Prepared query that includes a fail over to other datacenters. Service is only available in some datacenters; perform the prepared query using the DNS interface from a datacenter where the service is not available.

A failing test for this scenario and a tentative fix are included in https://github.com/hashicorp/consul/pull/2219

### Log Fragments or Link to [gist](https://gist.github.com/)
```
-- ~ $ dig my-service.query.consul SRV

; <<>> DiG ---Ubuntu <<>> my-service.query.consul SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: -
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;my-service.query.consul.		IN	SRV

;; ANSWER SECTION:
my-service.query.consul.	0	IN	SRV	1 1 8200 correct-hostname.node.wrong-datacenter.consul.

;; ADDITIONAL SECTION:
correct-hostname.node.wrong-datacenter.consul. 0 IN	A	ip-address-local-to-wrong-datacenter

;; Query time: 5 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jul 27 22:08:32 UTC 2016
```

This looks similar to https://github.com/hashicorp/consul/issues/2218.

**Comment by slackpad** [comment]
Fixed in #2219 via #2271.
