### ISSUE TITLE
agent/service/register ignores Name and ID fields of Check

### ISSUE THREAD

**Issue by WoZ** [hashicorp/consul#2223]
I'm trying to register service with checks specified as described below:

```
# curl -X PUT --data '{"ID": "s.2", "Name": "s", "Address": "127.0.0.1", "Port": 12345, "Check": {"ID": "s.2.porthealth", "Name": "Port availability check", "Notes": "Some notes", "HTTP": "http://127.0.0.1:8080", "Interval": "10s", "TTL": "15s"}}' http://localhost:8500/v1/agent/service/register
```

I'm awaiting to see Name of check "s.2.porthealth" and ID "s.2.porthealth" as described in documentation. Instead of that I see ID that was generated by consul itself. Name was generated too.

```
# curl http://localhost:8500/v1/agent/checks?pretty
{
    "service:s.2": {
        "Node": "napp",
        "CheckID": "service:s.2",
        "Name": "Service 's' check",
        "Status": "passing",
        "Notes": "Some notes",
        "Output": "",
        "ServiceID": "s.2",
        "ServiceName": "s",
        "CreateIndex": 0,
        "ModifyIndex": 0
    }
}
```
#### `consul version` for both Client and Server

Client: `0.6.3`
Server: `0.6.3`

**Comment by slackpad** [comment]
Hi @WoZ the automatic ID creation is an intentional part of the API, though that name behavior is confusing. We should make this a little more flexible.

You can use https://www.consul.io/docs/agent/http/agent.html#agent_check_register in the meantime to add checks to services with custom IDs and names.

**Comment by user31459** [comment]
Hi @slackpad 

The behavior is the same using the agent API and definitely doesn't match the documentation. Adding a service via v1/agent/service/register:

```json
{
  "id":"xxx-service-id",
  "name":"xxx-service-name",
  "address":"192.168.170.128",
  "port":31877,
  "check": {
    "id":"xxx-service-id-31877",
    "name":"xxx-service-name-31877",
    "http":"http://192.168.170.128:31877/v1/check",
    "interval":"4s"
 }
}
```
Ends up being registered as:

![consul](https://cloud.githubusercontent.com/assets/13365164/22879315/c19960c8-f1dd-11e6-9e41-8a5438be78ec.png)

Version tested: 0.7.3

**Comment by gaochunmeng** [comment]
I found the same problem 。View code found in func AddService 
`for i, chkType := range chkTypes {
		checkID := fmt.Sprintf("service:%s", service.ID)
		if len(chkTypes) > 1 {
			checkID += fmt.Sprintf(":%d", i+1)
		}
		check := &structs.HealthCheck{
			Node:        a.config.NodeName,
			CheckID:     types.CheckID(checkID),
			Name:        fmt.Sprintf("Service '%s' check", service.Service),
			Status:      structs.HealthCritical,
			Notes:       chkType.Notes,
			ServiceID:   service.ID,
			ServiceName: service.Service,
		}
		if chkType.Status != "" {
			check.Status = chkType.Status
		}
		if err := a.AddCheck(check, chkType, persist, token); err != nil {
			return err
		}
	}`

**Comment by slackpad** [comment]
Fixed in https://github.com/hashicorp/consul/issues/3047.
