### ISSUE TITLE
hi , I would like to know is there any way to setup basic auth for consul or not , thanks would appreciate response 

### ISSUE THREAD

**Issue by akssagar** [hashicorp/consul#2230]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @akssagar basic auth isn't supported. Please see https://groups.google.com/forum/#!topic/consul-tool/_P7kI3-bFqs for some different options. Hope that helps!
