### ISSUE TITLE
Consul UI HTTPS

### ISSUE THREAD

**Issue by luckyraul** [hashicorp/consul#2231]
Hi, 

I created my cluster with such parameters

```
consul_1     |             Server: true (bootstrap: true)
consul_1     |        Client Addr: 0.0.0.0 (HTTP: -1, HTTPS: 8500, DNS: 8600, RPC: 8400)
consul_1     |       Cluster Addr: IP (LAN: 8301, WAN: 8302)
consul_1     |     Gossip encrypt: true, RPC-TLS: true, TLS-Incoming: true
consul_1     |              Atlas: (Infrastructure: 'xxxx/infrastructure' Join: true)
```

And I can't use UI on https port 8500 with error 'ERR_BAD_SSL_CLIENT_AUTH_CERT'

I guess it requires ssl client cert to answer. 

How I can handle this situation to enable view ui without disabling TLS-Incoming: true ?

**Comment by slackpad** [comment]
Hi @luckyraul you are correct I don't think this is supported without a client cert. I'm not sure the best way to fix this, will need to think it through a bit. The only workaround I can think of at the moment would be to put a proxy webserver in front that will present a cert to Consul.

**Comment by slackpad** [comment]
Fixed in https://github.com/hashicorp/consul/issues/2969.
