### ISSUE TITLE
Bind docs inaccurate

### ISSUE THREAD

**Issue by ariscn** [hashicorp/consul#2234]
From https://www.consul.io/docs/agent/options.html#_bind:

> By default, this is "0.0.0.0", meaning Consul will use the first available private IPv4 address.

This is incorrect, setting bind to 0.0.0.0 (or accepting the default) results in Consul binding to all private interfaces.

**Comment by kbroughton** [comment]
Similarly, following the docs at https://hub.docker.com/_/consul/ 
the curl to localhost:8500 does not work as stated unless -client=0.0.0.0 is added

as per
https://github.com/gliderlabs/docker-consul/issues/100
