### ISSUE TITLE
Consul warning makes service fail

### ISSUE THREAD

**Issue by juliangamble** [hashicorp/consul#2243]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:
### `consul version` for both Client and Server

Client: `0.6.4`
Server: `0.6.4`
### `consul info` for both Client and Server

Client:

```
agent:
        check_monitors = 3
        check_ttls = 0
        checks = 4
        services = 5
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 56
        max_procs = 2
        os = linux
        version = go1.6
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 2814
        failed = 10
        intent_queue = 0
        left = 22
        member_time = 9993
        members = 84
        query_queue = 0
        query_time = 1

```

Server:

```
agent:
        check_monitors = 3
        check_ttls = 0
        checks = 4
        services = 5
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 56
        max_procs = 2
        os = linux
        version = go1.6
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 2814
        failed = 10
        intent_queue = 0
        left = 22
        member_time = 9993
        members = 84
        query_queue = 0
        query_time = 1

```
### Operating system and Environment details

Linux version 3.10.0-327.18.2.el7.x86_64 (mockbuild@x86-020.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Fri Apr 8 05:09:53 EDT 2016
### Description of the Issue (and unexpected/desired result)

A warning on a service makes the overall service fail.  

![failing on warning](https://cloud.githubusercontent.com/assets/261616/17401470/3a084ebe-5a91-11e6-8f97-b1fc892b542f.png)

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
