### ISSUE TITLE
Consul as a multi site LB ?!!

### ISSUE THREAD

**Issue by Kenovo** [hashicorp/consul#2245]
I'am thinking about the possibility of having a Consul cluster on multi sites and a consul template with a DNS server to have a multi site load balancing DNS with no SPOF.
i want to use a DNS server to allow other servers with no consul agents to join the services discovered by consul.
The hole idea is to get a Loadbalancing on different sites (multi datacenters) with no SPOF to allow a very high availability
.
What do you think about the idea ? is it technically doable ?

**Comment by jippi** [comment]
@Kenovo you mean like https://github.com/containous/traefik - just minus the consul-template? :)

**Comment by Kenovo** [comment]
Im looking for an architecture with no SPOF, thats why i want to use DNS and not a server ..

**Comment by slackpad** [comment]
Hi @Kenovo this is probably a better question for the mailing list. Lots of people configure HA load balancing setups with Consul + consul-template + some load balancer. If you have agents you can use things like https://github.com/eBay/fabio as well.
