### ISSUE TITLE
brew cask install consul

### ISSUE THREAD

**Issue by dmitrybelyakov** [hashicorp/consul#2254]
Following your website's documentation: ['Install consul'](https://github.com/hashicorp/consul/blob/master/website/source/intro/getting-started/install.html.markdown#os-x)

```
brew cask install consul
```

gives me:

```
Error: No available Cask for consul. Did you mean one of:
consul-cli     consul-web-ui
```

Did I mean the former?

**Comment by slackpad** [comment]
Hi @dmitrybelyakov the instructions were out of date and have now been updated under - https://github.com/hashicorp/consul/pull/2104.
