### ISSUE TITLE
Barrier implementation best practise

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/consul#2277]
A barrier is a common orchestration abstraction used by different processes to wait until they've all reached the same point in execution. The Consul documentation documents how a lock and/or semaphore should be implemented. It would be interesting to read about best-practises for implementing a barrier. See this as a feature request for that.

**Comment by slackpad** [comment]
Interesting question!

**Comment by JensRantil** [comment]
Inspiration: https://github.com/apache/curator/blob/8499680187d1f1061ca8597886e9f869bf637321/curator-recipes/src/main/java/org/apache/curator/framework/recipes/barriers/DistributedBarrier.java

**Comment by slackpad** [comment]
Closing this out since this never made it on the roadmap and there hasn't been much additional community interest. We'd definitely take a docs PR if someone wants to take a crack at it.
