### ISSUE TITLE
bench: outdated results

### ISSUE THREAD

**Issue by gyuho** [hashicorp/consul#2290]
Hi, I am looking for consul performance data, and these seem outdated.
- https://github.com/hashicorp/consul/blob/master/bench/bench-aws.json#L56
- https://github.com/hashicorp/consul/blob/master/bench/results-0.3.md

Could you provide new results with latest releases?

Thanks!

**Comment by slackpad** [comment]
Indeed - we need to re-run these!

**Comment by slackpad** [comment]
Got these working again and re-ran them - https://github.com/hashicorp/consul/blob/master/bench/results-0.7.1.md.
