### ISSUE TITLE
Fix link in CHANGELOG.md - Outage Recovery Guide

### ISSUE THREAD

**Issue by CpuID** [hashicorp/consul#2291]
Currently points to http://localhost:4567/docs/guides/outage.html - should be https://www.consul.io/docs/guides/outage.html

Introduced by https://github.com/hashicorp/consul/commit/ee5740847ce80f6493e670953de0bdb0a9ec67e0

cc @slackpad :)

**Comment by slackpad** [comment]
Oops - good catch!
