### ISSUE TITLE
Consul LAN/WAN Gossip

### ISSUE THREAD

**Issue by Kenovo** [hashicorp/consul#2292]
Hello,
could you please explain to me the difference between Consul LAN goosip protocol and the Consul WAN gossip ? could i connect two datacenters with LAN Gossip Protocol to have a kind of multi-datacenter DNS Loadbalancing provided by Consul DNS Service ? What kind of problemes could a such configuration create ?

Thank you,

**Comment by sitano** [comment]
LAN and WAN gossip use same protocol SWIM implemented in memberlist package with the Serf vector clocks blah-blah on top of it. Read docs.
https://www.consul.io/docs/internals/gossip.html
http://sitano.github.io/2015/10/06/abt-consul-outage/

**Comment by slackpad** [comment]
Here's the thread I think @sitano was referencing:

https://groups.google.com/forum/#!searchin/consul-tool/armon$20latency%7Csort:relevance/consul-tool/y1bFnMntF7M/cpM6Pw9BEAAJ

That has the upper limit of what's considered a LAN. We don't have native multi-DC load balancing, though you can get multi-DC failover via prepared queries - https://www.consul.io/docs/agent/http/query.html. Some folks use something like consul-template to configure a load balancer that feeds traffic across multiple DCs.

This has the best concise summary of LAN vs. WAN gossip - https://www.consul.io/docs/internals/architecture.html.
