### ISSUE TITLE
Consul "Too many open files"

### ISSUE THREAD

**Issue by rom-stratoscale** [hashicorp/consul#2297]
### `consul version` for both Client and Server

consul version
Consul v0.6.4
Consul Protocol: 3 (Understands back to: 1)
### `consul info` for both Client and Server

Client:

```
```

agent:
    check_monitors = 1
    check_ttls = 24
    checks = 25
    services = 26
build:
    prerelease = 
    revision = 26a0ef8c
    version = 0.6.4
consul:
    bootstrap = false
    known_datacenters = 1
    leader = true
    server = true
raft:
    applied_index = 34461140
    commit_index = 34461140
    fsm_pending = 0
    last_contact = 0
    last_log_index = 34461140
    last_log_term = 9
    last_snapshot_index = 34459060
    last_snapshot_term = 9
    num_peers = 2
    state = Leader
    term = 9
runtime:
    arch = amd64
    cpu_count = 12
    goroutines = 940
    max_procs = 12
    os = linux
    version = go1.6
serf_lan:
    encrypted = false
    event_queue = 0
    event_time = 59
    failed = 0
    intent_queue = 0
    left = 0
    member_time = 13
    members = 17
    query_queue = 0
    query_time = 1
serf_wan:
    encrypted = false
    event_queue = 0
    event_time = 1
    failed = 0
    intent_queue = 0
    left = 0
    member_time = 1
    members = 1
    query_queue = 0
    query_time = 1
### Operating system and Environment details

cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
### Description of the Issue (and unexpected/desired result)

We have a 6 nodes cluster, 3 servers and 3 agents.
After about 2 weeks, we got "Too many open files" error from consul.

Lsof on the process shows 1016 sockets of .....
consul  23357 root 1004u     sock       0,6      0t0 597329747 protocol: TCPv6
consul  23357 root 1005u     sock       0,6      0t0 597343336 protocol: TCPv6
consul  23357 root 1006u     sock       0,6      0t0 597334887 protocol: TCPv6
consul  23357 root 1007u     sock       0,6      0t0 597329748 protocol: TCPv6
consul  23357 root 1008u     sock       0,6      0t0 597348827 protocol: TCPv6
consul  23357 root 1009u     sock       0,6      0t0 597346719 protocol: TCPv6
consul  23357 root 1010u     sock       0,6      0t0 597345329 protocol: TCPv6
consul  23357 root 1011u     sock       0,6      0t0 597347573 protocol: TCPv6
consul  23357 root 1012u     sock       0,6      0t0 597343338 protocol: TCPv6
consul  23357 root 1013u     sock       0,6      0t0 597338083 protocol: TCPv6
consul  23357 root 1014u     sock       0,6      0t0 597338084 protocol: TCPv6
consul  23357 root 1015u     sock       0,6      0t0 597345365 protocol: TCPv6
consul  23357 root 1016u     sock       0,6      0t0 597351517 protocol: TCPv6
consul  23357 root 1017u     sock       0,6      0t0 597334888 protocol: TCPv6
consul  23357 root 1018u     sock       0,6      0t0 597358708 protocol: TCPv6
consul  23357 root 1019u     sock       0,6      0t0 597364342 protocol: TCPv6
consul  23357 root 1020u     sock       0,6      0t0 615035456 protocol: TCPv6
consul  23357 root 1021u     sock       0,6      0t0 606345724 protocol: TCPv6
consul  23357 root 1022u     sock       0,6      0t0 605353804 protocol: TCPv6
consul  23357 root 1023u     sock       0,6      0t0 597426725 protocol: TCPv6

They do not appear in netstat output:

[root@node0 ~]# netstat -nalp | grep consul
tcp        0      0 1.107.64.5:8300         0.0.0.0:\*               LISTEN      23357/consul  
tcp        0      0 1.107.64.5:8301         0.0.0.0:\*               LISTEN      23357/consul  
tcp        0      0 1.107.64.5:8302         0.0.0.0:\*               LISTEN      23357/consul  
tcp        0      0 1.107.64.5:8300         1.107.68.238:63112      ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:63476        1.107.68.238:8300       ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:57593        1.107.70.6:8300         ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:53771        1.107.68.238:8300       ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:8300         1.107.66.246:64438      ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:8300         1.107.70.6:53135        ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:8300         1.107.86.150:62080      ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:50892        1.107.70.6:8300         ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:63455        1.107.68.238:8300       ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:8300         1.107.68.238:63110      ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:8300         1.107.86.182:57326      ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:8300         1.107.68.238:63111      ESTABLISHED 23357/consul  
tcp        0      0 1.107.64.5:8300         1.107.68.238:63109      ESTABLISHED 23357/consul  
tcp6       0      0 :::8400                 :::\*                    LISTEN      23357/consul  
tcp6     129      0 :::8500                 :::\*                    LISTEN      23357/consul  
tcp6       0      0 :::53                   :::\*                    LISTEN      23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52814         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53674         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53581         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52815         ESTABLISHED 23357/consul  
tcp6       0      0 ::1:8500                ::1:64429               ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:55101         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52860         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:54481         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53580         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53044         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:57896         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53509         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53469         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:56848         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:59430         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52869         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:57472         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:64792         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52754         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52808         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:64077         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52674         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53014         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53088         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52859         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:55095         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53520         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:56314         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52685         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:60740         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53012         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52681         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:54535         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52684         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:57080         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:55594         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53002         ESTABLISHED 23357/consul  
tcp6       0      0 ::1:8500                ::1:64695               ESTABLISHED 23357/consul  
tcp6       0      0 ::1:8500                ::1:64098               ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:57118         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:55591         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52816         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52809         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53007         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:57127         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:55930         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:63398         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:57151         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:56302         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:54382         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:64089         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53216         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52682         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:56300         ESTABLISHED 23357/consul  
tcp6       0      0 ::1:8500                ::1:64270               ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53519         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:52755         ESTABLISHED 23357/consul  
tcp6       0      0 127.0.0.1:8500          127.0.0.1:53508         ESTABLISHED 23357/consul  
udp        0      0 1.107.64.5:8301         0.0.0.0:\*                           23357/consul  
udp        0      0 1.107.64.5:8302         0.0.0.0:\*                           23357/consul  
udp6       0      0 :::53                   :::\*                                23357/consul        

consul monitor is stuck.

Any idea how we should proceed with understanding the issue? 

Thanks

**Comment by rom-stratoscale** [comment]
@slackpad who can assist us please? We keep this setup up and running and need some advice to extract more relevant data from it. 
Thanks

**Comment by slackpad** [comment]
Hi @rom-stratoscale do you have any clients that are connecting to the http API and could possibly be leaking connections? This issue looks related and has some diagnostic steps to try - https://github.com/hashicorp/consul/issues/688#issuecomment-164824007.

**Comment by arie-stratoscale** [comment]
@slackpad it seems most connection don't show a remote port in the lsof. They just read:
consul  8566 root 1020u     sock       0,6      0t0 255716323 protocol: TCPv6

**Comment by slackpad** [comment]
Closing this out but please let us know if you are still seeing any issues. In the meantime we've added a non-pooled config you can use the with Go API to avoid keeping connections open -
 https://github.com/hashicorp/consul/blob/v0.8.3/api/api.go#L229-L237.

**Comment by youngerliucn** [comment]
@slackpad
I also meet this question, but I use consul binary from https://www.consul.io/
Could you give me some ideas?
