### ISSUE TITLE
Consul UI show nonexistent node. Deregister button doesnt remove such node

### ISSUE THREAD

**Issue by terbooter** [hashicorp/consul#2298]
Setup cluster of 3 consul servers on 3 hosts.
Enable UI on first host.
Change hostname on second host and restart consul on this host.
`consul members` shows right info - 3 alive servers.
But web ui shows 4 nodes. 3 "green" and one (with old hostname) "red".
"Deregister" button removes "red" node 
But after 30 seconds this "red" node appears in nodes list again

This ghost node can be elected as leader.

```
consul monitor
2016/08/22 11:33:59 [INFO] consul: New leader elected: sd-701
2016/08/22 11:33:59 [INFO] consul: New leader elected: sd-701
2016/08/22 11:33:59 [INFO] consul: New leader elected: sd-701
2016/08/22 11:33:59 [INFO] consul: New leader elected: sd-833
2016/08/22 11:33:59 [INFO] consul: New leader elected: sd-833
2016/08/22 11:33:59 [INFO] consul: New leader elected: sd-833
```

But non exist in members list

```
root@sd-789:/# consul members
Node      Address               Status  Type    Build  Protocol  DC
ex1        1.1.1.1:8301     alive   client  0.6.4  2         dc1
sd-701   1.1.1.3:8301    alive   server  0.6.4  2         dc1
sd-789   1.1.1.4:8301    alive   server  0.6.4  2         dc1
```

Only force-leave from console removes this ghost node

```
root@sd-789:/# consul force-leave sd-833
root@sd-789:/# consul monitor

2016/08/22 11:33:59 [INFO] consul: New leader elected: sd-833
2016/08/22 11:33:59 [INFO] consul: New leader elected: sd-833
2016/08/22 11:36:31 [INFO] agent.rpc: Accepted client: 127.0.0.1:60730
2016/08/22 11:42:45 [INFO] agent.rpc: Accepted client: 127.0.0.1:39846
2016/08/22 11:42:45 [INFO] Force leaving node: sd-833
2016/08/22 11:42:53 [INFO] agent.rpc: Accepted client: 127.0.0.1:40044
```

After `force-leave` ghost node from console UI works correctly

**Comment by slackpad** [comment]
Similar to https://github.com/hashicorp/consul/issues/2172.

**Comment by sebamontini** [comment]
I have a similar behaivour with ec2 instances that are being rotated in a ASG. if I do a `consul members` everything shows ok, but in the UI the old nodes (old EC2 instances that no longer exists) are still being showed as failing.

any ideas?

**Comment by slackpad** [comment]
Closing this out against #1580, which is related to IP address and name changes.
