### ISSUE TITLE
"services" link in UI displays services aggregated by name rather than individual instances

### ISSUE THREAD

**Issue by bitmask777** [hashicorp/consul#2302]
Clicking on the services button in the UI (in both Open Source and Enterprise/Atlas versions) shows services aggregated by name even though service IDs are unique. 

For example, given the following two services:

1) name="MyService" ID="1" tags=["a", "b"]
2) name="MyService" ID="2" tabs=["a", "c"]

When these two services are registered on the same node, after clicking on the services button in the UI the dashboard will display the consul service and only _one_ other service: represented by a single icon labeled "MyService". Clicking the "MyService" icon displays, among some other things, a "tags" section which displays the aggregation of unique tags for all instances of "MyService". In this case the tags list would be "a, b, c". 

I find this behavior confusing. I suggest that it be changed so that clicking on the services button lists all unique (i.e. unique value in the ID field) service instance registrations. So, in this case, two "MyService" icons. Clicking on any one of those should show the tags unique to that instance registration ("MyService" with ID=1 would show a tag list of "a, b", but "MyService" with ID=2 would show a tag list of "a, c").

With the current UI, I see no way to get a comprehensive view of all service instances DC-wide, or to view their instance-specific metadata (tags). I suppose I could work around this by naming each service uniquely ("MyService1", "MyService2"), but the [docs](https://www.consul.io/docs/agent/http/agent.html#agent_service_register) state that only ID must be unique and that name "collisions" are permissable.

**Comment by jsosulska** [comment]
Apologies for the long tail on this issue. 
This has since been updated in the UI. Now, there are service drill downs that also provide per instance views. This functionality can be seen on demo.consul.io, with the "consul" service.
