### ISSUE TITLE
Issues with hardcoded 2s DNS timeout

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [hashicorp/consul#2309]
Hi all,

Several of our users have experienced issues with the hard-coded 2s DNS timeout in how Consul serves DNS.  Some of this has to do with how we operate Consul, some has to do with Consul itself.  For plenty of context, you can take a look at [this thread](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/SYZBMTB6PKIPHWB2ZOE5FNOAJKUL7KVA/).

Would you folks be interested in a PR along [these lines](https://github.com/Pivotal-Pierre-Delagrave/consul/commit/c8c4b9d344ce94317d8554c85da7dc12f32e8cb2)?  If so, how would this fit into Consul's release cadence, i.e. what's the time scale to go from PR to patch release?

Thanks,
Amit

/cc @Pivotal-Pierre-Delagrave @zankich @keymon

**Comment by slackpad** [comment]
Hi @Amit-PivotalLabs something like this seems pretty reasonable. Consul 0.7 should ship shortly and I'm trying to avoid new stuff at this point, but this should be able to make it into a point release following that one.

**Comment by Amit-PivotalLabs** [comment]
Thanks! We'll probably submit a PR soon.
