### ISSUE TITLE
DNS recursion happens even if the record exists in the local cluster

### ISSUE THREAD

**Issue by akadoya** [hashicorp/consul#2328]
with consul v0.6.3 recursor option, I am experiencing the issue that dns recursions issued by consul servers are causing cpu loads to its recursor dns servers.

I thought recursor would be used only if the record doesn't exist in the local cluster, but it seems like queries are sent to the recursor servers no matter what.
I am getting the similar messages with the issue #1800 , however in my case I am getting answers from localhost when I use dig command to query the reverse record.(I am using dnsmasq for zone forwardings and consul servers has other consul cluster's servers as recursors)
>Aug 31 23:35:48 <dev consul server> consul[26421]: dns: all resolvers failed for {xx.xx.xx.xx.in-addr.arpa. 12 1} from client <prod consul server>:10927 (udp)

```
root@ <prod consul server>:~# dig @127.0.0.1 -p 8600 xx.xx.xx.xx.in-addr.arpa.

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> @127.0.0.1 -p 8600 xx.xx.xx.xx.in-addr.arpa.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33164
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available                                       <<<<<  sending queries to the other dns servers

;; QUESTION SECTION:
;43.186.20.172.in-addr.arpa.	IN	A

;; ANSWER SECTION:
43.186.20.172.in-addr.arpa. 0	IN	PTR	vntp-003.node.prod.local.                      <<< This node exists as a local cluster member.

;; Query time: 1 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Wed Aug 31 23:40:56 UTC 2016
;; MSG SIZE  rcvd: 117


root@vconsul-001:~# dig @127.0.0.1 -p 53 xx.xx.xx.xx.in-addr.arpa.

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> @127.0.0.1 -p 53 xx.xx.xx.xx.in-addr.arpa.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49771
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;43.186.20.172.in-addr.arpa.	IN	A

;; ANSWER SECTION:
xx.xx.xx.xx.in-addr.arpa. 0	IN	PTR	vntp-003.node.prod.local.

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Aug 31 23:41:15 UTC 2016
;; MSG SIZE  rcvd: 117
```

Is this behavior because I have dnsmasq and consul? isn't consul recursor supposed to work only if the record doesn't exist locally??
(I needed to configure both of recursors and dnsmasq's zone forwarding to make external services' record resolvable)

**Comment by slackpad** [comment]
Hi @akadoya this is the same thing that was happening in #1228 and should now be fixed by #2444.
