### ISSUE TITLE
Consul VS Zookeeper?

### ISSUE THREAD

**Issue by junneyang** [hashicorp/consul#2331]
What's the different bteween Consul  and Zookeeper?

**Comment by moofish32** [comment]
@junneyang -- not really sure this is a github issue. A couple of good resources: 
* [SE Radio Podcast](http://www.se-radio.net/2016/08/se-radio-episode-264-james-phillips-on-service-discovery/)
* [Consul Doc](https://www.consul.io/intro/vs/zookeeper.html)
* [second google hit](https://technologyconversations.com/2015/09/08/service-discovery-zookeeper-vs-etcd-vs-consul/)

**Comment by junneyang** [comment]
@moofish32    thanks
