### ISSUE TITLE
Multiple lock holders on flaky network

### ISSUE THREAD

**Issue by sixtus** [hashicorp/consul#2332]
Hi,

we use 0.6.4 on Linux and we now managed several times to have multiple lock holders (yes, on the same lock).

It seems to be triggered by flaky network, I can't reproduce it.

Here is the consul info of the leader (the issue is already fixed though)

$ consul info
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        bootstrap = false
        known_datacenters = 6
        leader = true
        server = true
raft:
        applied_index = 103011340
        commit_index = 103011340
        fsm_pending = 0
        last_contact = 0
        last_log_index = 103011340
        last_log_term = 15275
        last_snapshot_index = 103008406
        last_snapshot_term = 15275
        num_peers = 2
        state = Leader
        term = 15275
runtime:
        arch = amd64
        cpu_count = 12
        goroutines = 95
        max_procs = 3
        os = linux
        version = go1.6
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 1243
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 1696
        members = 5
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 2097
        members = 16
        query_queue = 0
        query_time = 1

As this results in downtime of our production system, we did not spend the time on capturing logs yet, but rather just restarted the multiple lock holders. Sorry.

**Comment by slackpad** [comment]
Hi @sixtus thanks for the report - this isn't something we've seen before. Based on what you've provided so far I'd guess that perhaps you are having your session get expired due to the flaky network and possibly the application holding the lock isn't properly monitoring and realizing that the lock is lost. Are you using `consul lock` or integrating directly with Consul's API?

**Comment by slackpad** [comment]
Closing this as we never heard back. Please let us know if you still need help.
