### ISSUE TITLE
Consul Server logs ACL tokens in clear text

### ISSUE THREAD

**Issue by Ashald** [hashicorp/consul#2334]
*This bug concerns only Consul Server component so I didn't fill any of Client details*

### `consul version` for Server
Server: `v0.6.4`

### `consul info` for Server
Server:
```
agent:
       	check_monitors = 0
       	check_ttls = 0
       	checks = 0
       	services = 1
build:
       	prerelease =
       	revision = 26a0ef8c
       	version = 0.6.4
consul:
       	bootstrap = false
       	known_datacenters = 7
       	leader = false
       	server = true
raft:
       	applied_index = 2857722
       	commit_index = 2857722
       	fsm_pending = 0
       	last_contact = 5.829639ms
       	last_log_index = 2857722
       	last_log_term = 8823
       	last_snapshot_index = 2856617
       	last_snapshot_term = 8823
       	num_peers = 2
       	state = Follower
       	term = 8823
runtime:
       	arch = amd64
       	cpu_count = 4
       	goroutines = 637
       	max_procs = 4
       	os = linux
       	version = go1.6
serf_lan:
       	encrypted = true
       	event_queue = 0
       	event_time = 64
       	failed = 0
       	intent_queue = 0
       	left = 0
       	member_time = 204
       	members = 14
       	query_queue = 0
       	query_time = 1
serf_wan:
       	encrypted = true
       	event_queue = 0
       	event_time = 1
       	failed = 2
       	intent_queue = 0
       	left = 0
       	member_time = 520
       	members = 21
       	query_queue = 0
       	query_time = 1
```

### Operating system and Environment details
CentOS 7

### Description of the Issue (and unexpected/desired result)

*Short version:* ACL tokens are showed in clear text in Consul Server logs.
*Long version:* we noticed few situations where ACL tokens where shown in logs in clear text. Such as:
1) No cluster leader:
```
consul: 2016/09/06 10:01:05 [ERR] consul.acl: Failed to get policy for 'TOKEN': No cluster leader
consul: 2016/09/06 10:59:37 [ERR] consul.acl: Failed to get policy for 'TOKEN': rpc error: failed to get conn: rpc error: lead thread didn't get connection
```
2) No connection to ACL datacenter
```
consul: 2016/09/12 16:21:25 [ERR] consul.acl: Failed to get policy for 'TOKEN': rpc error: failed to get conn: dial tcp 192.168.12.10:8300: getsockopt: connection refused
```

There were few others situations when tokens are logged as well.

I edited out the token values and replaced them with TOKEN in examples above.
Those tokens were both supplied as "acl_token" in agent configuration files or used in web UI.
Both "regular" and "root" tokens where displayed.

*Expected behavior:*
Tokens are edited out or their hashes are displayed (md5? sha1? whatever)
`acl_master_token` token is never displayer in logs.

### Reproduction steps
Try to execute some operation with ACL enabled when there is no cluster leader.

### Log Fragments or Link to [gist](https://gist.github.com/)
Log samples included above. I can provide more on request.

**Comment by slackpad** [comment]
Hi @Ashald thanks for opening an issue (sorry about the late response on your PR, working through a lot of things in parallel here).

We ended up removing all the token logging here - https://github.com/hashicorp/consul/commit/e83172792386fd473dd3220c7e6ea38fe18936b0#diff-c7c6050c04c9988e6d2824b655764d9c, so I think this issue should be cleared up in Consul 0.7. What I'd like to do for tokens eventually is log a token accessor, which allows operators to query info about the token without getting access to the token itself.

**Comment by Ashald** [comment]
Thanks for the quick response! Hope to see Consul 0.7 soon! ;)
