### ISSUE TITLE
Add possibility to register a health check by service

### ISSUE THREAD

**Issue by sokie** [hashicorp/consul#2339]
Currently we can only register a health check for a specific `service_id` or for all. It would be nice to be able to add a check by service name ( which may have more than one node registered to it ).

**Comment by sokie** [comment]
Example:
![2nodes](https://cloud.githubusercontent.com/assets/1364089/18516249/82116b06-7a98-11e6-99eb-b8c197572f82.png)
We should be able to register a health check for all auth-clients ( 1 and 2 ), instead of having to register the service for each ( eg. auth-client-c89c5be.... AND auth-client-cface6f98dd... )

**Comment by slackpad** [comment]
Thanks for opening an issue. This is a nice shortcut but creates a lot of ambiguity about service IDs and service names (already a point of confusion for some), so it would make the API harder to use. Even though it's a little more registration work, we'd like to keep things simple and map checks directly.
