### ISSUE TITLE
Blocking query skips updates

### ISSUE THREAD

**Issue by jvinod** [hashicorp/consul#2342]
I am using a blocking query (long poll) to receive updates on a key.  What I observe is that sometimes, if there  are consecutive Puts on the same key, then the long poll does not return once for every update but may coalesce updates and return with the highest ModifyIndex.

Is this the desired behavior?

To clarify:

```
// Do consecutive updates to the same key
consulApi.Put(key, ...)
pair, .. := consulApi.Get(key) // Assume pair.ModifyIndex=100 
consulApi.Put(key, ...)
pair, .. := consulApi.Get(key) // Assume pair.ModifyIndex=101

```

```
// In a different go routine do a long poll and wait for changes under prefix. "key" is under prefix.
opts := &api.QueryOptions{WaitIndex: waitIndex,}
for {
            pairs, meta, err := consulApi.List(prefix, opts)
             for _, pair := range pairs {
                          // PROBLEM: pair.ModifyIndex==101 ; pair.ModifyIndex==100 is never returned. 
              }
              opts.WaitIndex = meta.LastIndex
}            
```
### `consul version` for Server
Server: `0.6.4`

**Comment by slackpad** [comment]
Hi @jvinod this is as designed. Here's a common way this can happen:

1. You do an initial query and are current through index 100.
2. A change is made and you wake up and get 101.
3. While your app is looping around to re-query, two more changes are made.
4. You app re-queries against 101 and immediately wakes up and gets index 103.

Consul doesn't have enough state internally to send you the key contents at index 102 any more, so it just gives you the latest. The only guarantee that Consul makes is that you will get woken up if there's a change, but not that you will get woken up for *each* change. Hope that helps!
