### ISSUE TITLE
Allow all nodes to initialize with the same command line args, including -join and -bootstrap-expect

### ISSUE THREAD

**Issue by leonj1** [hashicorp/consul#2345]
When installing and starting Consul using Chef its non-trivial to start an initial Consul node and then use -join for all others. Attempting to start a server with -join terminates immediately if the target is not there. While obvious why it fails, any reason not to add retry logic here? The goal to allow a Chef-run or other mechanism to start it on that target host. Yes, I could raise a PR, but thought best to ask in case this was already discussed and advised against. If not Chef, how are others deploying Consul, other than manually.

**Comment by jhmartin** [comment]
There is -retry-join that adds that logic::

> 
-retry-join - Similar to -join but allows retrying a join if the first attempt fails. This is useful for cases where we know the address will become available eventually.

https://www.consul.io/docs/agent/options.html

**Comment by daveadams** [comment]
Seconding the recommendation for using retry-join. We successfully use the same init script for all our Consul servers and agents in all our datacenters, dynamically generated with Ansible in our case, though it would be suitable for a pre-baked cloud image or even a static deployment.

**Comment by leonj1** [comment]
This is perfect, thanks!
