### ISSUE TITLE
session-invalidation time is not equal to TTL 

### ISSUE THREAD

**Issue by zhaojigang** [hashicorp/consul#2347]
I create a session with ttl=30s, but  this session invalidated about 60 seconds later, I'm a little confused, can you explain why??

**Comment by slackpad** [comment]
Hi @zhaojigang this behavior comes from here:

https://github.com/hashicorp/consul/blob/master/consul/session_ttl.go#L76-L81

TTLs are internally doubled, so only the lower bound is guaranteed by Consul.

**Comment by zhaojigang** [comment]
Thank you very much!!!
