### ISSUE TITLE
Do not fail on start when an unknown configuration key is encountered.

### ISSUE THREAD

**Issue by pszymczyk** [hashicorp/consul#2348]
Hi

I would like to introduce new configuration flag `fail_on_unknown_configuration_key` which indicates how Consul behave on startup when unknown configuration key is encountered. If set to `false` unknown configuration keys will be ommited, if set to `true` failed on startup.

I think this option is very usefull: if set to `true` Consul cluster is less prone on configuration mistakes, especially when configuration is distributed by some configuration management tools like Chief or Puppet.

**Comment by daveadams** [comment]
I think Consul's current behavior is safer. If there is an invalid configuration key in your configuration, it is likely it's a misspelling or just something out of place, which means a configuration value you intended to set it _not_ being set, and so Consul will be running but with the wrong configuration. If the key that's misspelled is something security related, you could be unknowingly running in an insecure state.

If you've automated your configuration, you should be deploying configuration changes carefully to non-production systems first to sanity check for stuff like this, and you should also have monitoring in place to detect that a critical service like Consul isn't running.

Additionally, most (maybe all) config management systems provide a way to specify a command to run to validate a configuration before a start or restart. Consul provides a command that will check a config file or directory for errors: `consul configtest`. You should include a check using consul configtest in your config management specification to check for syntax problems.

**Comment by slackpad** [comment]
Hi @pszymczyk thanks for opening an issue an PR but I have to agree this is kind of an anti-pattern. There are good tools for pre-vetting config, and depending on where the typo is you might end up in a dangerous state so it's much safer to have Consul bail out when given a bad config. As @daveadams hinted, you should be able to use https://www.consul.io/docs/commands/configtest.html even as part of Chef or Puppet to stop early.

**Comment by pszymczyk** [comment]
@daveadams @slackpad thanks for feedback, I will try to implements `consul configtest` before restart Consul process.
