### ISSUE TITLE
CLI formatting conventions aren't consistent

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2350]
Make all CLI flag formatting consistent per https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/3YgF9IBKWYU/A8CLj7FJFgAJ.

**Comment by mckennajones** [comment]
Based on that conversation I'm not sure if the consensus was to use spaces or equal signs. I'm up to tackling this though.

**Comment by slackpad** [comment]
@mckennajones awesome! I think the `=` matches more of what's there and is clearer when reading documentation.

**Comment by slackpad** [comment]
Fixed by #2362.
