### ISSUE TITLE
Status .btn of the .topbar is not updated to .btn-warning or .btn-success when status change

### ISSUE THREAD

**Issue by XavM** [hashicorp/consul#236]
The status .btn of the .topbar is not updated to .btn-warning or .btn-success when status change

I understand that it could be intended that the UI does not poll for changes, but it can lead to ambiguity when ones navigates after some health status have changed.

Please see :  

![image](https://cloud.githubusercontent.com/assets/1206754/3452494/07ef0f6c-01b5-11e4-9ed0-aeeb9cc7f226.png)

**Comment by pearkes** [comment]
Unfortunately until we poll, as you said, this is going to be tough to do properly. I'd say we'll implement polling before updating that section of the view. Thanks!
