### ISSUE TITLE
Hard coded limit for KV entries should be configurable

### ISSUE THREAD

**Issue by gpaggi** [hashicorp/consul#2363]
Consul version: v0.6.4, but affects any version after May 6, 2014

In https://github.com/hashicorp/consul/commit/8f37f967e0fc677fa54c9beea988dc331e35718f the size for the KV entries was hard limited to 512KB.

When using Consul as remote state storage for Terraform that limit is easily reached with middle sized environments.

Would it be possible to have that limit configurable in the Consul server config?

Thanks!

**Comment by slackpad** [comment]
Hi @gpaggi it's probably not a good idea to increase this by much more as this limit is designed to help keep Raft log entries to a reasonable size. It might be a better approach to have Terraform support compressing the state and/or breaking things up across multiple keys.

**Comment by gpaggi** [comment]
Hi @slackpad, I was indeed thinking about the effect of big values would have on replication just after I submitted this. I'll open one at TF to check there what can be done.
Since Consul now supports transactions for updating multiple keys, perhaps splitting the state could be the way to go.

**Comment by slackpad** [comment]
Thanks for opening the issue over on TF. I'll close this out for now. The txn limit is similar:

https://github.com/hashicorp/consul/blob/master/command/agent/txn_endpoint.go#L149-L155

So TF would likely need to grab a lock, update the state across multiple keys with several calls, and then release the lock.
