### ISSUE TITLE
consul under swarm mode some times fail re-join

### ISSUE THREAD

**Issue by muradm** [hashicorp/consul#2374]
### `consul version` for both Client and Server

`Consul v0.7.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)`
### Operating system and Environment details

ubuntu 16.04 LTS
docker 1.12.1 - 1.13.0-dev
### Description of the Issue (and unexpected/desired result)

Running consul cluster under docker swarm mode. Since servers run as tasks in global mode, tasks are very transient. They may update/restart, and new task is always new container. **leave_on_terminate** used to mitigate transient behavior of task. So that at any point in time if task existed due to some reason, node supposed to be deregistered from cluster. When new instance of task is fired by swarm mode, fresh new server expected to join the cluster. Expected behavior observed until some point, when fresh new server cannot join cluster. When this happens, members try to negotiate leadership. But fresh new node cannot keep up with sync:
`2016/09/30 03:49:53 [WARN] raft: Failed to get previous log: 6340 log not found (last: 6339)
2016/09/30 03:50:53 [WARN] raft: Failed to get previous log: 6347 log not found (last: 6346)
2016/09/30 03:51:53 [WARN] raft: Failed to get previous log: 6358 log not found (last: 6357)`
Always remains one log behind?
Could it be that newly coming node acquires same IP address as previous which just left?
### Reproduction steps

In docker swarm mode create overlay network:
`docker network create -d overlay --subnet 10.100.0.0/16 test-net`
1. Bootstrap server:
   `docker service create --name consul-bootstrap --log-driver syslog --log-opt tag=consul \
   --network test-net --publish 8501:8500 \
   --env 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' --env CONSUL_BIND_INTERFACE=eth2 \
   encom/consul:v5 agent -server -datacenter=lab-dc -domain=lab \
   -recursor=8.8.8.8 -recursor=8.8.4.4 -ui -log-level=info -client 0.0.0.0 \
   -bootstrap-expect 3`
2. Seed cluster:
   `docker service create --name consul --mode global --update-delay 120s --log-driver syslog --log-opt tag=consul \
   --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
   --network test-net --publish 8500:8500 --publish 53:8600/udp \
   --env 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' --env CONSUL_BIND_INTERFACE=eth2 consul \
   agent -server -datacenter=lab-dc -domain=lab \
   -recursor=8.8.8.8 -recursor=8.8.4.4 -client=0.0.0.0 -retry-join consul-bootstrap -ui -log-level=info`
3. Destroy bootstrap:
   `docker service rm consul-bootstrap`
4. Update join arguments:
   `docker service update --args "agent -server -datacenter=lab-dc -domain=lab -recursor=8.8.8.8 -recursor=8.8.4.4 -client=0.0.0.0 -retry-join tasks.consul -ui -log-level=info" consul`

Rejoin one of nodes few times using:
- service docker restart
- kill -TERM 

At some point cluster will fail.

**Comment by hehailong5** [comment]
according to the https://www.consul.io/docs/guides/outage.html
you may need to edit the peers.json file in the case that IPs have changed.

**Comment by muradm** [comment]
Actually IPs do not change. As mentioned above, every start docker swarm service task, it is new containers, having unique name and hostname. See the logs:

```
2016-09-30T07:22:53.120066+04:00 lab3 consul[9295]:     2016/09/30 03:22:53 [INFO] serf: EventMemberLeave: 2f74fbbffdd2 10.100.0.2
2016-09-30T07:22:53.120377+04:00 lab3 consul[9295]:     2016/09/30 03:22:53 [INFO] consul: Removing LAN server 2f74fbbffdd2 (Addr: tcp/10.100.0.2:8300) (DC: lab-dc)
2016-09-30T07:22:53.120554+04:00 lab3 consul[9295]:     2016/09/30 03:22:53 [INFO] consul: member '2f74fbbffdd2' left, deregistering
2016-09-30T07:23:07.578830+04:00 lab3 consul[9295]:     2016/09/30 03:23:07 [INFO] serf: EventMemberJoin: 1ec48b592c2f 10.100.0.2
2016-09-30T07:23:07.579001+04:00 lab3 consul[9295]:     2016/09/30 03:23:07 [INFO] consul: Adding LAN server 1ec48b592c2f (Addr: tcp/10.100.0.2:8300) (DC: lab-dc)
```

It says `EventMemberLeave: 2f74fbbffdd2 10.100.0.2` and then `EventMemberJoin: 1ec48b592c2f 10.100.0.2` after task is restarted. As far as I understand members are identified by `-node` or if not provided `hostname`. So join shall not fail since new hostname assigned. But as you may see, since swarm landscape didn't change, new container gets same IP as previous one. May it be the source of problem?

**Comment by slackpad** [comment]
Hi @muradm `2016/09/30 03:49:53 [WARN] raft: Failed to get previous log: 6340 log not found (last: 6339)` is usually ok because the leader will send a snapshot to get the follower caught up. Does the cluster eventually stabilize or does it get stuck in an endless loop of those?

**Comment by muradm** [comment]
Hi @slackpad, no it never comes back to normal, cluster needs to be bootstrapped from scratch. I waited an hour or two,  logs continue same as in Log Fragments.

**Comment by muradm** [comment]
Today tried again. It seems that the problem occurs if left host comes back with same IP address.
```
docker exec consul.0.7efno6nqrrjehjuknxa5lomkw consul members
Node          Address           Status  Type    Build  Protocol  DC
18ee4505378d  10.100.0.43:8301  left    server  0.7.0  2         lab-dc
97df84f8ed30  10.100.0.43:8301  left    server  0.7.0  2         lab-dc
9a9c55e976ba  10.100.0.36:8301  alive   server  0.7.0  2         lab-dc
bfa7f0ddd6e5  10.100.0.5:8301   alive   server  0.7.0  2         lab-dc
e430aece1e8b  10.100.0.43:8301  left    server  0.7.0  2         lab-dc
ed663bbded3e  10.100.0.43:8301  left    server  0.7.0  2         lab-dc
```
After some activities (for instance docker restart so that tasks respawn with different IP) to make restarting node get different IP address, then it recovers.

**Comment by galindro** [comment]
@muradm did you solved this problem? I've noticed the same issue in my environment. Besides it, there are some other problem: when you restart the host for some reason, the docker daemon doesn't send sig term to the consul-server docker task, therefore, it not properly leave the cluster. After the host is up, a new task is created with a different VIP address. 

As soon as I have persistent storage for /consul/data, the node can't join to the cluster and to old node persists in the cluster.

IMHO, hashicorp team must change the way consul adds/removes it nodes for properly work in docker swarm mode (1.12.x / 1.13.x).

**Comment by muradm** [comment]
@galindro no, I could not solve the problem. It could be done with too much effort overhead (creating many many scripts to handle such situations). So I gave up for some reasons:

* Initially consul is not designed to run dynamic environment, which is actually logical, since it is supposed to be reference point for everything else. Thus, trying to fight the design is quite hard. IMHO, just like one won't put database cluster in docker swarm, one should not try putting consul into swarm.
* On the other hand, docker swarm mode is a kind of competition for consul, since it provides service discovery and even load balancing via DNS and VIP addressing. Which is far more than what consul does.
* docker swarm mode service concept does not match (or interfere with concepts in consul), trying to fit docker services into consul service catalog causes other issues.
* If one decides to run consul outside the docker swarm mode cluster, there is a problem that consul cannot reach services within overlay network, which again makes consul more useless.
* etc. etc.

Giving up consul, we are losing basically three things:
* Health checks - docker actually started supporting [HEALTHCHECK in Dockerfile](https://docs.docker.com/engine/reference/builder/#healthcheck)
* KV store - here, one would look for another solution other than KV, at least I could not find reliable alternative that can be used within docker swarm mode. 
* Service catalog - em hm.. :) no alternative as well...

But since docker swarm mode provides so much out of the box, for me it was more reasonable to focus on alternatives for missing parts, rather than fighting design issues and trying to fit consul into docker swarm. And actually it was easier..

Probably it will be possible to run consul more or less reliably with --attachable flag coming in 1.13 of docker. This flag will allow connecting standalone docker containers (i.e. not docker service containers) to overlay networks. I tested it months back on first RCs of 1.13, and it was promising, but 1.13 was very unstable and still not released to repos.

**Comment by galindro** [comment]
@muradm I want to use consul for ceph: https://github.com/ceph/ceph-docker

I'm trying to build a ceph cluster in AWS with docker. As far ceph is running outside swarm (network=host), I'll put consul outside it too with network=host too. Or maybe I could try etcd...

Tks for quick reply

**Comment by slackpad** [comment]
We've got the groundwork in place at the Raft layer to track servers with a unique ID that's independent of their IP and even node name so this should get fixed in the next major release of Consul (0.8) or shortly after.

**Comment by slackpad** [comment]
@galindro Currently shooting for early March.

**Comment by hehailong5** [comment]
Hi @slackpad, does it mean the recovery policy would change? the peers.json with ips will be abandoned? currently my script is dependent on the ip based peers.json for all the recovery scenarios. hopefully it would still work till then.

**Comment by galindro** [comment]
@hehailong5 did your script could recover failed scenarios in Docker swarm mode? Could you share it?

**Comment by rvrignaud** [comment]
@slackpad Hi. Is this possible get reference of the raft layer issue / PR to be able to track it ? Thanks

**Comment by slackpad** [comment]
Hi @rvrignaud the Raft work is done under https://github.com/hashicorp/raft/tree/library-v2-stage-one and integrated with Consul. The autopilot work for 0.8 switched Consul to the new Raft APIs that manage server identity by UUID instead of IP, now we need to test changing IP addresses and make sure everything is handled properly up in Consul. We will update this issue with any cleanups.

**Comment by slackpad** [comment]
Closing this as a dup of #457.

**Comment by slackpad** [comment]
Closing this in favor of https://github.com/hashicorp/consul/issues/1580.
