### ISSUE TITLE
Consul doesn't send telemetry to configured statsd_address

### ISSUE THREAD

**Issue by stephansnyt** [hashicorp/consul#2378]
I've seen the same problem on 0.7.0 and 0.6.4, giving both versions and infos below.

### `consul version` for Server
Server: 
```Consul v0.7.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)```

```Consul v0.6.4
Consul Protocol: 3 (Understands back to: 1)```

### `consul info` for Server


Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 'a189091
        version = 0.7.0
consul:
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 10.224.170.5:8300
        server = true
raft:
        applied_index = 54
        commit_index = 54
        fsm_pending = 0
        last_contact = never
        last_log_index = 54
        last_log_term = 5
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:10.224.170.5:8300 Address:10.224.170.5:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 5
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 55
        max_procs = 1
        os = linux
        version = go1.6.3
serf_lan:
        encrypted = false
        event_queue = 1
        event_time = 5
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

```
agent:                                                                                                                         [0/87]
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        bootstrap = true
        known_datacenters = 1
        leader = true
        server = true
raft:
        applied_index = 17
        commit_index = 17
        fsm_pending = 0
        last_contact = never
        last_log_index = 17
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        num_peers = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 54
        max_procs = 1
        os = linux
        version = go1.6
serf_lan:
        encrypted = false
        event_queue = 1
        event_time = 3
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details
* Google compute engine
* image centos-7-v20160921
* machine type n1-standard-1 (1 vCPU, 3.75 GB memory)

### Description of the Issue (and unexpected/desired result)
Consul does not send any data to `statsd_address`. I tried to observe this at first with a collectd agent with statsd plugin configured, and when that didn't work I tried to look exactly at the port using netcat: `nc -k -l 9898`

I configured a `statsite_address` and confirmed that I data was sent to that address with netcat.

### Reproduction steps

```
# cat basic_config.json
{
  "datacenter": "east-aws",
  "data_dir": "/opt/consul/data",
  "log_level": "TRACE",
  "node_name": "foobar",
  "server": true,
  "bootstrap": true,
  "telemetry": {
     "statsd_address": "127.0.0.1:9898",
     "statsite_address": "127.0.0.1:9999"
  }
}
[root@packertest consul]# /usr/local/bin/consul agent -config-file basic_config.json
```

In two other termianls, try 

* `nc -k -l 9898`
* `nc -k -l 9999`

Observe that 9999 receives metrics data and 9898 does not:
```
# nc -k -l 9999
consul.packertest.runtime.total_gc_runs:24.000000|g
consul.memberlist.gossip:0.013546|ms
...
```

### Log Fragments or Link to [gist](https://gist.github.com/)
```
# /usr/local/bin/consul agent -config-file basic_config.json | tee /var/log/consul.log
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.0'
         Node name: 'foobar'
        Datacenter: 'east-aws'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 10.224.170.5 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2016/09/30 14:48:44 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:10.224.170.5:8300 Address:10.224.170.5:8300}]
    2016/09/30 14:48:44 [INFO] serf: EventMemberJoin: foobar 10.224.170.5
    2016/09/30 14:48:44 [INFO] serf: EventMemberJoin: foobar.east-aws 10.224.170.5
    2016/09/30 14:48:44 [INFO] raft: Node at 10.224.170.5:8300 [Follower] entering Follower state (Leader: "")
    2016/09/30 14:48:44 [WARN] serf: Failed to re-join any previously known node
    2016/09/30 14:48:44 [INFO] consul: Adding LAN server foobar (Addr: tcp/10.224.170.5:8300) (DC: east-aws)
    2016/09/30 14:48:44 [WARN] serf: Failed to re-join any previously known node
    2016/09/30 14:48:44 [INFO] consul: Adding WAN server foobar.east-aws (Addr: tcp/10.224.170.5:8300) (DC: east-aws)
    2016/09/30 14:48:51 [ERR] agent: failed to sync remote state: No cluster leader
    2016/09/30 14:48:53 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2016/09/30 14:48:53 [INFO] raft: Node at 10.224.170.5:8300 [Candidate] entering Candidate state in term 6
    2016/09/30 14:48:53 [DEBUG] raft: Votes needed: 1
    2016/09/30 14:48:53 [DEBUG] raft: Vote granted from 10.224.170.5:8300 in term 6. Tally: 1
    2016/09/30 14:48:53 [INFO] raft: Election won. Tally: 1
    2016/09/30 14:48:53 [INFO] raft: Node at 10.224.170.5:8300 [Leader] entering Leader state
    2016/09/30 14:48:53 [INFO] consul: cluster leadership acquired
    2016/09/30 14:48:53 [INFO] consul: New leader elected: foobar
    2016/09/30 14:48:53 [DEBUG] consul: reset tombstone GC to index 66
    2016/09/30 14:48:56 [DEBUG] agent: Service 'consul' in sync
    2016/09/30 14:48:56 [INFO] agent: Synced node info
    2016/09/30 14:50:20 [DEBUG] agent: Service 'consul' in sync
    2016/09/30 14:50:20 [DEBUG] agent: Node info in sync
```

**Comment by slackpad** [comment]
Hi @stephansnyt, Consul's statsd client currently uses UDP, so if you use `nc -k -u -l 9898` you'll see some telemetry. It looks baked in here, so we'd probably need to plumb another config variable to support TCP - https://github.com/armon/go-metrics/blob/master/statsd.go#L96-L101.

**Comment by slackpad** [comment]
If we don't make this configurable, we should update the documentation to make this behavior more clear.

**Comment by stephansnyt** [comment]
The documentation is quite clear. I just happened to miss that detail. Sorry!
