### ISSUE TITLE
consul watch not working with unix socket for http

### ISSUE THREAD

**Issue by hcstestacc** [hashicorp/consul#2385]
Server: 0.7.0
### Operating system and Environment details

Ubuntu 14.04
### Description of the Issue (and unexpected/desired result)

I run consul server listening on unix sockets for http and rpc. I can demonstrate reliable connectivity to them using the cli for rpc and nc for http over the sockets. When I added a watch to my consul server though, I now get the following in my logs:

`2016/10/03 23:01:48 consul.watch: Watch (type: keyprefix) errored: Get http://%2Fvar%2Frun%2Fconsul%2Fconsul_http.sock/v1/kv/cfg?recurse=: dial tcp: lookup /var/run/consul/consul_http.sock: invalid domain name, retry in 20s`

For some reason, even though http/rpc addresses are being set to unix:///var/run/consul/consul_<http/rpc>.sock - the watch is trying to dial in to an http address.
### Reproduction steps

Run consul with a config like:

```
{
  "addresses": {
    "http": "unix:///var/run/consul/consul_http.sock",
    "rpc": "unix:///var/run/consul/consul_rpc.sock"
  },
  "bind_addr": "10.0.0.29",
  "bootstrap": true,
  "datacenter": "mydc",
  "data_dir": "/opt/consul/data",
  "log_level": "INFO",
  "server": true,
  "watches": [
    {
      "type": "keyprefix",
      "prefix": "cfg",
      "handler": "/opt/consul/myhndl.sh"
    }
   ]
}
```

Watch the logs try to make the watch connect via tcp instead of over unix socket.

Is there something I'm missing in the config for my watch?

**Comment by tomalok** [comment]
I think I've just encountered something similar...  But in my case, I've disabled http (set the port to -1)
```
    "ports": {
         "http": -1,
         "https": 8500
    },
```
I'm able to `consul watch -type nodes watch-handler-script` just fine (I've exported `CONSUL_HTTP_SSL='1'`) but when I try to put watches into the config, I'm getting
```
2016/10/06 00:15:44 consul.watch: Watch (type: nodes) errored: Get https://0.0.0.0:-1/v1/catalog/nodes: dial tcp: invalid port -1, retry in 2m5s
```
It'd be nice if it could just use HTTPS and I could keep HTTP turned off -- though a unix socket would be even better...

**Comment by hcstestacc** [comment]
Oh yes, I also had the same behaviour when I exported `CONSUL_HTTP_ADDR=unix:///var/run/consul/consul_http.sock` too :(

**Comment by tomalok** [comment]
Trying `"http": 8499` (had to completely restart consul, reload wasn't good enough)...
```
2016/10/06 00:42:55 consul.watch: Watch (type: nodes) errored: Get https://0.0.0.0:8499/v1/catalog/nodes: http: server gave HTTP response to HTTPS client, retry in 5s
```
So, now it's trying to talk HTTPS to the HTTP port...

**Comment by tomalok** [comment]
explicitly setting `CONSUL_HTTP_ADDR=https://127.0.0.1:8500` didn't work either.  Back to the https://0.0.0.0:-1/...  error.
