### ISSUE TITLE
translate_wan_addrs not working for DNS?

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/consul#2390]
I thought this worked before, but since I upgraded to the new version 0.7.0 it always gives me the public IP address in different datacenters.

Although via consul template, I can get the public IP, but not in DNS anymore, and in the catalog it does show properly:

```
[
  {
    "Node": "i-20414138",
    "Address": "52.38.X.X",
    "TaggedAddresses": {
      "lan": "10.20.0.124",
      "wan": "52.38.X.X"
    },
    "ServiceID": "i-20414138.node.us-west-2-exe-tools:jenkins:8080",
    "ServiceName": "jenkins",
    "ServiceTags": [
      "tools",
      "us-west-2",
      "us-west-2a",
      "m1.xlarge",
      "exe-tools"
    ],
    "ServiceAddress": "10.20.0.124",
    "ServicePort": 8080,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 262851,
    "ModifyIndex": 262851
  }

```

It does work if I ping i-20414138.node.us-west-2-exe-tools.consul but not jenkins.service.us-west-2-exe-tools.consul it always gets the private IP.

**Comment by JoeOrtiz** [comment]
I've just checked on the consul-template if they still showed the wan IPs, while I did test this initially with consul 0.7.0 in a whole new datacenter on this version. I see that now while that hasn't been touched at all, it isn't showing the wan IPs, just the private IPs, and this was working before.

**Comment by slackpad** [comment]
Hi @JoeOrtiz it looks like that service has `"ServiceAddress": "10.20.0.124"` defined. If that's set then it won't do address translation, it will always report that. If you register the service and leave that blank I think it should work.

https://github.com/hashicorp/consul/blob/master/command/agent/dns.go#L765-L770

**Comment by slackpad** [comment]
We should make a note about this in the documentation.

**Comment by JoeOrtiz** [comment]
Hi @slackpad , this was indeed the problem. I can confirm it now works.

This was due to registrator, we had passing --ip, once this was removed, this works as intended.

Although this causes a problem now with the consul HTTP healthchecks, since consul does a GET on it, since there is no IP for $SERVICE_IP, those health checks will fail. Is there anyway to tell consul to use its own local lan IP, as the lan and wan IP show up properly, but not its service IP, so it can't run it's health check. 

I am a little afraid to enable in registrator the --internal option, but not too sure if this will mean it will register that now as the SERVICE_IP, and then I would lose my wan/lan capabilities.

**Comment by jsosulska** [comment]
This looks to have been addressed several years ago. Closing.
