### ISSUE TITLE
docs: catalog/service/<service> doesn't describe entire response

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#2393]
The description of the [`/v1/catalog/service/<service>` api endpoint](https://www.consul.io/docs/agent/http/catalog.html#catalog_service) describes the response JSON body as:

```
[
  {
    "Node": "foobar",
    "Address": "10.1.10.12",
    "ServiceID": "redis",
    "ServiceName": "redis",
    "ServiceTags": null,
    "ServiceAddress": "",
    "ServicePort": 8000
  }
]
```

This is an actual response from a consul v0.7.0 server:

```
[
  {
    "Node": "Floyd-Pepper.local",
    "Address": "127.0.0.1",
    "TaggedAddresses": {
      "lan": "127.0.0.1",
      "wan": "127.0.0.1"
    },
    "ServiceID": "consul",
    "ServiceName": "consul",
    "ServiceTags": [],
    "ServiceAddress": "",
    "ServicePort": 8300,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 4,
    "ModifyIndex": 5
  }
]
```

None of the fields are described in the documentation; it's not clear what the difference is between `Address` and `ServiceAddress`, and when each should be used.  

`ServiceTags` is documented as being `null`, when the apparent empty-value is `[]`.

`TaggedAddresses`, `ServiceEnableTagOverride`, `CreateIndex`, and `ModifyIndex` are neither documented nor included in the example.  Some of these actually feel like "leaks" that needn't be exposed to the caller, but I feel that they should at least be acknowledged in the documentation.  

I think the lack of references to the various addresses is particularly confusing.

**Comment by slackpad** [comment]
@blalor thanks for opening an issue and sorry for the confusion. We will get this cleaned up!

**Comment by slackpad** [comment]
Fixed via https://github.com/hashicorp/consul/pull/2520.
