### ISSUE TITLE
Consul Check Ouput is Empty

### ISSUE THREAD

**Issue by ankurgla22** [hashicorp/consul#2398]
I am using Consul v0.6.4.

I have added check to run a script periodically

{
  "ID": "WemoSwitch1",
  "Name": "Wemo Power Switch",
  "Script": "/var/www/wemo.sh",
  "Interval": "120s"
}

When I add this check, it start showing output of the script.
But after some time (around 2 min), it start showing blank output and status of check is "passing" all the time.

Any idea??

**Comment by slackpad** [comment]
Hi @ankurgla22 that sounds like a problem with your script. If you are still having this problem, please open an issue an include a link to logs from your agent with debug level set. Thanks!
