### ISSUE TITLE
Add ability to filter based on tag(s) in Consul UI

### ISSUE THREAD

**Issue by pz7** [hashicorp/consul#2400]
This is a feature request.

Could you please add ability to filter in by the tag(s) in the Consul UI?

As of now it is very cumbersome to browse the nodes individually for the specific service to find out which tags they have.

Thanks!

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll take a look at this feature as part of that.

**Comment by milipili** [comment]
Did you find someone? :)

**Comment by eliasbrange** [comment]
@slackpad Any update on this? Is it in the backlog to be able to filter on tags? It's a feature we really really need.

Our usecase is that we have indiviual webservers per customer, and right now we are registering every webserver as a service called `webserver` with a tag `customer=NAME`. However, without being able to filter on tags makes it very hard to find the health for a specific customer in the UI.

What's your opinion on doing like that with tags versus registering each webserver as `webserver-NAME` without using tags?

**Comment by peimanja** [comment]
any update on this one?

**Comment by milipili** [comment]
Well there is a new UI but I don't know how good it can be
https://demo.consul.io/ui/dc1/services

**Comment by johncowen** [comment]
Hi @peimanja 

As @milipili said we released a new UI a while ago, and you can now search services by tags. There are more improvements specifically related to this coming down the line also.

Thanks,

John

P.S. @milipili 

> Did you find someone? :)

yes 😁
