### ISSUE TITLE
Consul service panics on journalctl restart

### ISSUE THREAD

**Issue by xytis** [hashicorp/consul#2404]
The same vulnerability as with docker: https://github.com/docker/docker/issues/19728
### `consul version` for Client

Client: `Consul v0.6.3`
### `consul info` for Client

Client:

```
agent:
    check_monitors = 0
    check_ttls = 0
    checks = 1
    services = 1
build:
    prerelease =
    revision = c933efde
    version = 0.6.3
consul:
    known_servers = 5
    server = false
runtime:
    arch = amd64
    cpu_count = 24
    goroutines = 48
    max_procs = 2
    os = linux
    version = go1.5.3
serf_lan:
    encrypted = false
    event_queue = 0
    event_time = 62
    failed = 0
    intent_queue = 0
    left = 0
    member_time = 601
    members = 34
    query_queue = 0
    query_time = 1
```
### Description of the Issue (and unexpected/desired result)

consul daemon restarts when journald is restarted
### Reproduction steps

`systemctl restart systemd-journald.service`

**Comment by rbjorklin** [comment]
We've also encountered this problem. Not sure if it matters but we've been running consul as a service too.

    [Unit]
    Description=replicated key—value store
    After=network-online.target
    [Service]
    User=consul
    ExecStart=/usr/local/bin/consul agent -config-file /etc/consul.d/config.json
    KillSignal=SIGINT
    [Install]
    WantedBy=default.target

**Comment by rbjorklin** [comment]
Reading through the thread over at the Docker project this issue might have been resolved in Consul >= 0.7.0 because Consul was built with golang >= 1.6. #1963 

Will try this out and report back.

**Comment by xytis** [comment]
In addition to golang update such line has to exist:
https://github.com/hashicorp/nomad/issues/1798

**Comment by mckennajones** [comment]
Was unable to reproduce the issue on consul version 0.7.0. However, it still seems like a good idea to add the code that ignores sigpipe signals, so I created a quick PR.
