### ISSUE TITLE
how to config the consul to be able to respond to "service name" only DNS request?

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2406]
It looks like the shortest query string would be "<service name>.service.consul". is it possible to make the ".service.consul" preconfigured so as we can use only the <service name> as the query string? just like the search option does in resolv.conf?

**Comment by dbresson** [comment]
If you know about adding the search option to resolv.conf, why don't you just do that?

**Comment by slackpad** [comment]
The search option will work but can end up being inefficient and result in multiple round trips to DNS. We don't have any way to shortcut to just the service prefix, unfortunately, and that's probably not a feature we'd want to add in Consul because it can lead to ambiguous parsing in the DNS code.
