### ISSUE TITLE
Error starting agent: Failed to get advertise address: -join

### ISSUE THREAD

**Issue by soumyasmruti** [hashicorp/consul#2409]
Consul wouldn't start and keeps on giving this error.

**Comment by slackpad** [comment]
@soumyasmruti that looks like you have a bad command line with something along the lines of `-advertise -join`. Please make sure you are not passing an empty advertise address in to Consul.

**Comment by soumyasmruti** [comment]
No the address we are passing to is perfectly fine, its giving response when pinged separately.

**Comment by slackpad** [comment]
Hi @soumyasmruti I don't think the address is bad, it looks like you have a bad command line for Consul. If you run Consul like this you get a similar error:

```
consul agent -data-dir=/tmp/foo -advertise -join
==> Starting Consul agent...
==> Error starting agent: Failed to parse advertise address: -join
```

**Comment by soumyasmruti** [comment]
["consul agent -server -data-dir /config -config-dir /config -advertise $(curl -s {ip-address}/latest/meta-data/local-ipv4) -join {ip-address} -node $(curl -s {ip-address}/latest/meta-data/hostname | cut -d\".\" -f1) -ui"]

**Comment by slackpad** [comment]
Hard to say, but I suspect `$(curl -s {ip-address}/latest/meta-data/local-ipv4)` is evaluating to an empty string. I'd try `echo $(curl -s {ip-address}/latest/meta-data/local-ipv4)` to see what it looks like. Also, perhaps there's some kind of race where this is running before your network interface comes up. I've seen folks have issues like that in the past.
