### ISSUE TITLE
Documentation on consul.io tracks HEAD of master, not current release version

### ISSUE THREAD

**Issue by sampointer** [hashicorp/consul#2410]
This leads to ambiguity and wasted time. For example, as of the filing date of this issue `consul kv` is listed as a valid command (https://www.consul.io/docs/commands/kv.html) and yet that functionality does not exist in the release version: 0.7.0.

**Comment by slackpad** [comment]
Hi @sampointer sorry for the confusion on that one - added a note to the `consul kv` command about which versions it was added, that was an oversight. We've been working to label all new features with their versions.
