### ISSUE TITLE
Can I have multiple ports listening for dns?

### ISSUE THREAD

**Issue by juliangamble** [hashicorp/consul#2414]
### `consul version` for both Client and Server

Client: `0.6.4`
Server: `0.6.4`
### `consul info` for both Client and Server

Client:

```
agent:
        check_monitors = 3
        check_ttls = 0
        checks = 4
        services = 5
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 56
        max_procs = 2
        os = linux
        version = go1.6
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 2814
        failed = 10
        intent_queue = 0
        left = 22
        member_time = 9993
        members = 84
        query_queue = 0
        query_time = 1

```

Server:

```
agent:
        check_monitors = 3
        check_ttls = 0
        checks = 4
        services = 5
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 56
        max_procs = 2
        os = linux
        version = go1.6
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 2814
        failed = 10
        intent_queue = 0
        left = 22
        member_time = 9993
        members = 84
        query_queue = 0
        query_time = 1

```
### Operating system and Environment details

Linux version 3.10.0-327.18.2.el7.x86_64 (mockbuild@x86-020.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Fri Apr 8 05:09:53 EDT 2016
### Description of the Issue (and unexpected/desired result)

I've got this in my `settings.json`

```
  "ports" : { "dns" : 53 },
```

I want to do this:

```
  "ports" : { "dns" : 53, "dns" : 50325 },
```

because we have limited IP range connectivity, but I want to keep the standard port as well. 

My question is: **Can I have multiple ports listening for dns?**

**Comment by slackpad** [comment]
Hi @juliangamble not currently, this would be an enhancement.

**Comment by jippi** [comment]
I would just use Consul DNS on its default port, and use dnsmasq or otherwise to bind to different ports that forwards it upstream to the single Consul DNS port :) less complexity in Consul and more flexibility in how it actually works for you

**Comment by slackpad** [comment]
Going to close this one out - agree with @jippi that there are other ways to implement this, and it hasn't been a common request. It's definitely good to keep Consul config complexity down if possible, and addresses and ports are already very complex to configure.
