### ISSUE TITLE
Consul watch fires event even before event is triggered

### ISSUE THREAD

**Issue by sobertooth** [hashicorp/consul#2415]
Hey Guys, 
Whenever I try to create an event type watch, the watch itself runs the query without waiting for the event to be triggered. 

Client: 0.7.0
Server: 0.7.0

consul watch -type=event -name=runme -datacenter="redis" "whoami"

Is this default behaviour?

**Comment by slackpad** [comment]
Hi @sobertooth that's correct right now - it will fire the script on the initial query. There's a tool called sifter that works around this - https://github.com/darron/sifter, and we have an open issue #571 that's tracking this.
