### ISSUE TITLE
How to understands network coordinates

### ISSUE THREAD

**Issue by janisz** [hashicorp/consul#2416]
Is tere any reference paper  for network tomography. I want to understand wont Error, Height and Vec are. How are they calculated? What they mean? And how can I use them. Why Vec has 8 elements?

Here are my tries to convert cordinates to 3d map https://gist.github.com/janisz/995b38e15376ac407b6ab47f4343ed17

**Comment by slackpad** [comment]
See https://www.serf.io/docs/internals/coordinates.html if you are curious about the details and the reference papers.
