### ISSUE TITLE
registered services on one node never sync to other nodes in cluster

### ISSUE THREAD

**Issue by paccer-cn** [hashicorp/consul#2419]
I create one 3-node cluster, however the service registered on one node never sync to other 2 nodes
### `consul version` for both Client and Server

Server : 0.7.0
### `consul info` for both Client and Server

Server 1:
agent:
        check_monitors = 16
        check_ttls = 0
        checks = 16
        services = 17
build:
        prerelease =
        revision = 'a189091
        version = 0.7.0
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.3.0.5:8300
        server = true
raft:
        applied_index = 90949
        commit_index = 90949
        fsm_pending = 0
        last_contact = 78.608861ms
        last_log_index = 90949
        last_log_term = 8
        last_snapshot_index = 90244
        last_snapshot_term = 4
        latest_configuration = [{Suffrage:Voter ID:10.3.0.4:8300 Address:10.3.0.4:8300} {Suffrage:Voter ID:10.3.0.6:8300 Address:10.3.0.6:8300} {Suffrage:Voter ID:10.3.0.5:8300 Address:10.3.0.5:8300}]
        latest_configuration_index = 1
        num_peers = 2
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 8
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 82
        max_procs = 1
        os = linux
        version = go1.6.3
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 5
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 19
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1

Server 2/3:
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 'a189091
        version = 0.7.0
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 10.3.0.5:8300
        server = true
raft:
        applied_index = 90936
        commit_index = 90936
        fsm_pending = 0
        last_contact = 0
        last_log_index = 90936
        last_log_term = 8
        last_snapshot_index = 90205
        last_snapshot_term = 4
        latest_configuration = [{Suffrage:Voter ID:10.3.0.4:8300 Address:10.3.0.4:8300} {Suffrage:Voter ID:10.3.0.6:8300 Address:10.3.0.6:8300} {Suffrage:Voter ID:10.3.0.5:8300 Address:10.3.0.5:8300}]
        latest_configuration_index = 1
        num_peers = 2
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 8
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 75
        max_procs = 1
        os = linux
        version = go1.6.3
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 5
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 19
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
### Operating system and Environment details

Ubuntu 16.04 LTS
### Log Fragments or Link to [gist](https://gist.github.com/)

Server 2/3
    2016/10/18 03:37:20 [DEBUG] agent: Node info in sync
    2016/10/18 03:37:33 [DEBUG] memberlist: Initiating push/pull sync with: 10.3.0.4:8301
    2016/10/18 03:37:56 [DEBUG] memberlist: TCP connection from=10.3.0.4:42978
    2016/10/18 03:38:03 [DEBUG] memberlist: Initiating push/pull sync with: 10.3.0.4:8301
    2016/10/18 03:38:16 [DEBUG] memberlist: TCP connection from=10.3.0.6:58702
    2016/10/18 03:38:33 [DEBUG] memberlist: Initiating push/pull sync with: 10.3.0.4:8301
    2016/10/18 03:38:44 [DEBUG] agent: Service 'consul' in sync
    2016/10/18 03:38:44 [DEBUG] agent: Node info in sync
    2016/10/18 03:38:46 [DEBUG] memberlist: TCP connection from=10.3.0.6:58710
    2016/10/18 03:39:03 [DEBUG] memberlist: Initiating push/pull sync with: 10.3.0.4:8301
    2016/10/18 03:39:16 [DEBUG] memberlist: TCP connection from=10.3.0.6:58718
    2016/10/18 03:39:26 [DEBUG] memberlist: TCP connection from=10.3.0.4:43094
    2016/10/18 03:39:33 [DEBUG] memberlist: Initiating push/pull sync with: 10.3.0.4:8301

**Comment by slackpad** [comment]
Hi @paccer-cn Consul won't actually sync the services to the other nodes. Each agent has its own set of services and those sync back to the Consul servers. Please see https://www.consul.io/docs/internals/architecture.html and https://www.consul.io/docs/internals/anti-entropy.html for more details.
