### ISSUE TITLE
Unable to deregister nodes

### ISSUE THREAD

**Issue by Crapworks** [hashicorp/consul#2420]
Client: `0.7.0`
Server: `0.7.0`

Hi! We are using consul on OpenStack, where Instances are often created and destroyed. We have a custom API that handles creation/destruction of such instances. Since it takes a while until consul deregisteres absent agents automatically, I've decided to couple the destroy via API with a deregister call to the consul API. Unfortunately, this has no effect:

``` bash
curl 'http://<consul-server>:8500/v1/catalog/deregister?dc=<datacenter>&token=' -X PUT --data '{"Datacenter":"<datacenter>","Node":"<nodename>"}'
true
```

But the node is still there when I list the nodes via `/v1/catalog/nodes`. It also doesn't work via the UI. After deregistering the node disappears (I guess the ui is not reloading here, just removing the element from the DOM) but when I reload it is back again. 

Just to be clear, the vm with the agent is already destoyed at that point and the agent is marked as not reachable. Is this the intended behaviour? If yes, how can I successfully deregister an client nodes via the API?

[edit]
The services that were registered on those agents are successfully deregistered when I deregister the node. And they stay unregistered as well. It is just the node that stays in the catalog.

**Comment by slackpad** [comment]
Hi @Crapworks you can use https://www.consul.io/docs/agent/http/agent.html#agent_force_leave or https://www.consul.io/docs/commands/force-leave.html to kick the dead node from the cluster early. That will remove it from the members list and the catalog.
