### ISSUE TITLE
Inter DC key search 

### ISSUE THREAD

**Issue by sobertooth** [hashicorp/consul#2424]
Hey Guys, 
I have 2 Datacenters running consul and joined by WAN. 
I'm using consulate - the python API for consul. 

From one of the servers I hit  a find query for a key on the other DC. Both DCs are joined. 

**var = consul.kv.find("ha-live?dc=dc2")**

Whenever this is triggered - I get this error message. 
2016/10/19 19:43:24 [WARN] consul.rpc: RPC request for DC 'dc2?recurse=None', no path found
2016/10/19 19:43:24 [ERR] http: Request GET /v1/kv/ha-live?dc=dc2?recurse=None, error: No path to datacenter from= 127.0.0.1:39528

Both the UIs are listening on LAN IPs and are reachable from each server. 
Can someone explain this behaviour? 
Is the syntax correct?

**Comment by jippi** [comment]
looks like a API Client issue, `dc2?recurse=None` sounds like `?dc=dc2` is not interpreted correctly?

**Comment by slackpad** [comment]
Hi @sobertooth I think @jippi is right here. Haven't used consulate too much myself, but it looks like the datacenter gets configured for the client itself, not per-call - https://github.com/gmr/consulate/blob/master/consulate/__init__.py#L51.

**Comment by sobertooth** [comment]
Thanks Guys! I'll let follow it up with the consulate guys :)
