### ISSUE TITLE
how to configure the build system to not build in parallel ?

### ISSUE THREAD

**Issue by toralf** [hashicorp/consul#2425]
app-admin/consul ~0.7.0 seems to be a package with does not respect -j1 under a Gentoo build system - at least it spawns a lot of "go" processes - any chance to convince it to be polite to other cpu users ? ;)

The back ground is that I do maintain a tinderbox for QA purpose for Gentoo Linux - that machine has 12 cpus and is running usually with a load of 10.9 - which works most of the time as long as every technical user just uses 1 cpu

**Comment by slackpad** [comment]
I think we'd have to plumb an environment variable for this and add an option to `gox` in scripts/build.sh. PRs welcome :-)

**Comment by talonx** [comment]
I was thinking of taking the argument to -j and pushing it to the -parallel option of gox, but there seems to be no easy way to retrieve the value of the arg passed with j before GNU make 4.2 - http://git.savannah.gnu.org/cgit/make.git/tree/NEWS?h=4.2 There is a roundabout way described here - http://blog.jgc.org/2015/03/gnu-make-insanity-finding-value-of-j.html

Another environment variable, of course, would be easy to do but it would violate the Principle of Least Astonishment, IMHO.

**Comment by slackpad** [comment]
We are going to close this out as we haven't had a ton of interest in this, and we don't really want to add more complexity to the makefile (we've been actively trying to cut it down).
