### ISSUE TITLE
Docker health checks continue to run after deregistering the check and the service

### ISSUE THREAD

**Issue by racktear** [hashicorp/consul#2426]
I run a single-node Consul 0.7 and use it to monitor containers.

I register the containers as services with a python script and create simple health checks in Consul that run shell scripts inside the containers. (by specifying DockerContainerID in the check)

After deregistering the check, the service, and removing the container I start to see errors in docker logs like this:

```
time="2016-10-20T11:51:21.643349307Z" level=error msg="Error setting up exec command in container 9701fd6c853149ec859d47f0f6a8eb61_1: No such container: 9701fd6c853149ec859d47f0f6a8eb61_1"
```

When I enable debug logs in Consul, I see this:

```
2016/10/20 11:51:21 [DEBUG] agent: Error while creating Exec: No such container: 9701fd6c853149ec859d47f0f6a8eb61_1
```

Apparently Consul continues to check service health even when the service and health check has been deregistered. And it continues forever, until the restart of consul server.

I have verified that there are actually no registered health checks left in my experiment. Both in the UI and using REST API. Here is how it looks:

```
$ http localhost:8500/v1/health/state/any
HTTP/1.1 200 OK
Content-Length: 461
Content-Type: application/json
Date: Thu, 20 Oct 2016 11:52:09 GMT
X-Consul-Index: 39
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0

[
    {
        "CheckID": "serfHealth",
        "CreateIndex": 5,
        "ModifyIndex": 5,
        "Name": "Serf Health Status",
        "Node": "aca2d4b45628",
        "Notes": "",
        "Output": "Agent alive and reachable",
        "ServiceID": "",
        "ServiceName": "",
        "Status": "passing"
    },
    {
        "CheckID": "service:docker",
        "CreateIndex": 4,
        "ModifyIndex": 4,
        "Name": "Service 'docker' check",
        "Node": "aca2d4b45628",
        "Notes": "",
        "Output": "HTTP GET http://docker1:2375/_ping: 200 OK Output: OK",
        "ServiceID": "docker",
        "ServiceName": "docker",
        "Status": "passing"
    }
]
```

PS: the problem reproduces on 0.6.4 as well.

**Comment by atoulme** [comment]
@racktear I see the code changes in Consul pointing at a fix: https://github.com/hashicorp/consul/pull/3295

We are upgrading to 0.9.3 to adopt those changes. Note you will need to set enable_check_scripts to true in your configuration.

**Comment by slackpad** [comment]
Ah thanks @atoulme - will close this out!
