### ISSUE TITLE
Provide ModificationTimestamp for kv

### ISSUE THREAD

**Issue by gimlet2** [hashicorp/consul#2429]
In some cases would be great to know somehow when some kv pair was created or update. For example for cases when you want to clear you kv storage from old values.

**Comment by slackpad** [comment]
Hi @gimlet2 this gets into thorny issues with clocks being out of sync, etc, so we've avoided timestamps in our APIs. The `ModifyIndex` values are monotonically increasing, so you could use set a key externally with a timestamp from the source of your choice and use that key's `ModifyIndex` to judge before/after for other keys. We probably won't add something like this, though, unless there's a super compelling use case.
