### ISSUE TITLE
Duplicate IPs in cluster causing unaffected nodes to flap

### ISSUE THREAD

**Issue by ross** [hashicorp/consul#2430]
### `consul version` for both Client and Server

Client: `0.6.4`
Server: `0.6.4`
### Operating system and Environment details

ubuntu precise
### Description of the Issue (and unexpected/desired result)

We were seeing a service flaps on hosts across the fleet which were resulting in haproxy restarts once a minute. It was tracked down to a pair of nodes with duplicate ip addresses causing ~500k memberlist "problems" an hour across all of the nodes in that datacenter.

```
...
2016/10/23 00:31:28 [WARN] memberlist: Refuting a suspect message (from: <dup-ip-host1>)
2016/10/23 00:46:45 [WARN] memberlist: Refuting a suspect message (from: <dup-ip-host1>)
2016/10/23 01:11:54 [WARN] memberlist: Refuting a suspect message (from: <dup-ip-host1>)
2016/10/23 01:24:48 [WARN] memberlist: Refuting a suspect message (from: <dup-ip-host1>)
2016/10/23 01:44:06 [WARN] memberlist: Refuting a suspect message (from: <dup-ip-host1>)
2016/10/23 01:59:32 [WARN] memberlist: Refuting a suspect message (from: <dup-ip-host2>)
...
```

It seems fine for that error message to be printed under the circumstances and obviously those two nodes would be non-functional. 

What's not clear and seems like an issue is that when other nodes would see the problematic pair (and log messages like the above) they'd go unhealthy when they were otherwise fine. For some services this didn't matter too much, it was brief etc, but for others (listed in HAProxy) it was a huge issue resulting in loads of restarts.
### Reproduction steps

Bringing up two nodes with duplicate ip address would likely be a good start.
### Log Fragments or Link to [gist](https://gist.github.com/)

> TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

We 💀 ed the duplicate ips and haven't seen it since. Sorry didn't get any trace/debug logging while it was on-going.

**Comment by slackpad** [comment]
Will take a look - agree this shouldn't affect other nodes that don't have dup-ed IPs.

**Comment by slackpad** [comment]
Hi @ross wanted to clarify did you see any health flaps _for_ nodes that were not part of this pair with duplicate IPs, or were you just seeing memberlist messages across the whole fleet related to those two nodes? The latter would be expected as the nodes fight it out, and we could see consul template being busy if quiescence wasn't set. We'd definitely not expect the former where some node outside of this pair actually has its own health affected by this.

**Comment by ross** [comment]
> Hi @ross wanted to clarify did you see any health flaps for nodes that were not part of this pair with duplicate IPs, or were you just seeing memberlist messages across the whole fleet related to those two nodes?

We were seeing consul-template restarts on nodes that matched up with the memberlist messages in the logs on that node. So somelb-ab12cd56 would log those messages and at the same point in time the restart command would fire. This happened frequently enough that things were restarting as quickly as we'd allow them. 

The conflicting nodes were just test/dev nodes that had no services on them, included in the lb's template or otherwise. I wasn't expecting the health/membership of those 2 nodes to cause consul-template to think it needs to re-generate a template and restart the services. Is that what you're saying is expected in this case?

**Comment by slackpad** [comment]
> The conflicting nodes were just test/dev nodes that had no services on them, included in the lb's template or otherwise. I wasn't expecting the health/membership of those 2 nodes to cause consul-template to think it needs to re-generate a template and restart the services. Is that what you're saying is expected in this case?

Ok that is still odd. I'd expect to see memberlist messages in many nodes in the cluster related to these two nodes (and flapping in any services on those nodes), but I wouldn't expect any flapping for unrelated nodes or services.

**Comment by ross** [comment]
> I'd expect to see memberlist messages in many nodes in the cluster related to these two nodes

To be clear we would see the memberlist messages in lots of places, pretty much everywhere, but it appears that the person who found it found that the restart times line up with the memberlist messages on that node. I suppose that could be coincidence, but wanted to include it in case it helps to track down what's up.

**Comment by skottler** [comment]
We ran into a slight variation of this issue today with the same behavior. `consul monitor` showed a host failing and then a different one pointing with the same IP like so:

```
2016/12/13 10:08:33 [INFO] serf: EventMemberFailed: host1 10.0.0.1
2016/12/13 10:08:49 [INFO] serf: EventMemberJoin: host1 10.0.0.1
2016/12/13 10:08:56 [INFO] serf: EventMemberJoin: host2 10.0.0.1
```

As you can see the same IP was joined twice across two different nodes. I'm not sure whether the ID/IP tuple is treated as globally unique, but having the same IP joined several times in the same cluster is likely problematic. The one counter case I could see to that is in something like VPC or an overlay network where IPs are themselves are unique only to a specific logical network.

**Comment by i0rek** [comment]
It is no longer possible to boot start different nodes and join the same datacenter. Joining the same IP however is working, provided separate ports are provided to run the agent. Closing this because it doesn't seem relevant anymore. 

Please open a new issue if you are still having this problem.
