### ISSUE TITLE
How to set up client side HA

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2432]
since the -node requires to be unique, suppose I want to scale a component to 3 instances to achieve the HA, I can only run one consul client instance as the interface. so is it possible to set up consul client HA?

**Comment by slackpad** [comment]
Hi @hehailong5 it is not recommended to run the client HA. Consul supports an HA server configuration by running 3 or more servers which provides HA for the cluster, but each node only needs one client agent. The client agent is in the same failure domain as the rest of the node (if the node shuts down, for example), so it doesn't add much to have multiple Consul clients on one machine. Running a process supervisor to restart the Consul client if it were to exit should be sufficient.

**Comment by hehailong5** [comment]
@slackpad, I am not asking for running multiple consul client instances on one machine, this makes no sense obviously. actually I have a domain specific component coupled with a consul client and I want to deploy it onto a 3-nodes HA cluster. the problem is that the node name (specified by -node) for these 3 consul client instances can not be the same, otherwise 2 of them would fail to start because of the name conflict. if I name them with different names, we don't have HA anymore.

**Comment by slackpad** [comment]
@hehailong5 sorry for the misunderstanding on my part. I think you would want to register a [Consul service](https://www.consul.io/docs/agent/services.html) with the same name on each of these nodes, then clients would look up <name>.service.consul and would be given the IP of one of the three instances as long as they are alive. Does that make sense or am I still misunderstanding the use case?

**Comment by hehailong5** [comment]
Hi @slackpad, I am using the agent api ([Agent](https://www.consul.io/docs/agent/http/agent.html)) to perform the service create/update/delete as suggested in the official doc. Suppose in a 3-nodes HA cluster, client1 runs on node1, client2 runs on node2 and client3 runs on node3. in a typical HA scenario, suppose the first create request hits on node1, and the client1 creates the serviceA via the agent interface. suppose a subsequent update request on serviceA hits on node2, the client2 does NOT recognize serviceA because it was registered by client1, thus the update request would return with nothing done. If the client2 performs the update via the catalog interface ([Catalog](https://www.consul.io/docs/agent/http/catalog.html)) since all the services are there, the ANTI-ENTROPY would overwrite the update with the copy from client1 within one minute. the update performed by client2 still not work. 
Hopefully I made this clear.

**Comment by slackpad** [comment]
Hi @hehailong5 the agent API should only be used by processes on the node where that agent runs. For example, you'd run serviceA and it would always use 127.0.0.1:8500/v1/agent/ to create/update/delete the info for itself. The agent on that node will sync the catalog information for the services _on that node_, so there won't be any interference between the nodes. So the instance of your service on node1 will register with its local agent, which will sync the catalog on the Consul servers for the instance of the service on node1. You never want to have your service talk to the Agent API on another node, and everything should work fine (always talk to 127.0.0.1:8500/v1/agent/...).

**Comment by hehailong5** [comment]
Hi @slackpad, yes, in my case, the process is running on the same node where the consul agent runs, and the process always talks to 127.0.0.1:8500. I just want all the process instances manage the same a single view for each service, that's exactly what HA requires. how about this, when the create request comes to node1, the registration process on the node1 asks the client1 on the node1 to register serviceA via 127.0.0.1:8500/v1/agent; after a while, a update request on serviceA come into the cluster, and the HA infrastructure chooses node2 to serve this request, the registration process on the node2 then asks the client2 on the node2 to update serviceA, how to do it? so that any query request via Catalog api from other client will get the updated  serviceA??

**Comment by slackpad** [comment]
@hehailong5 are you trying to do something like update service tags from some external request?

**Comment by hehailong5** [comment]
@slackpad not limited to update, how to delete serviceA from client2 that created by client1, so that the serviceA will be completely removed from catalog?

**Comment by hehailong5** [comment]
as the subject states, I am just trying to set up consul client HA.

**Comment by slackpad** [comment]
The best way to achieve that is to register a TTL check or something like that and use the new `deregister_critical_service_after` field on the check (see https://www.consul.io/docs/agent/checks.html). As soon as the health check fails Consul will stop giving other clients the IP of the dead instance, after `deregister_critical_service_after` time passes, the Consul agent will deregister the service. This way, instances of your HA service don't need to know about each other in any way.

**Comment by hehailong5** [comment]
sorry @slackpad, I don't understand why this would achieve the HA. a create, update example would help :)

**Comment by cmingxu** [comment]
I did the same as @slackpad suggestion.

**Comment by hehailong5** [comment]
@cmingxu , @slackpad could you please explain more about this way? in my understanding, if I register serviceA via client1 with "deregister_critical_service_after", I still can not modify serviceA via client2. if the ttl expires, it does not exist in the catalog anymore. what all these are to do with the HA?

**Comment by hehailong5** [comment]
Hi, I am still struggling with this, any feedback? thanks a lot!

**Comment by slackpad** [comment]
Hi @hehailong5 I'm not sure I follow the concern. In the example above, "serviceA" will be deleted automatically after the service dies, so client2 doesn't need to be concerned with it.

**Comment by hehailong5** [comment]
Hi @slackpad, the services and consul clients are running on different nodes. the registrator running on the service node contacts with one consul client each time to send the add/update/delete request. the goal is to achieve the consul client side HA. is that possible?

![image](https://cloud.githubusercontent.com/assets/17330257/21336790/b5a22054-c6a2-11e6-8938-7e0c5803cc45.png)

**Comment by slackpad** [comment]
Hi @hehailong5 I see - Consul isn't designed for client side HA like this.

You'd want to run the Consul client on the same machine with serviceA and registrator in the example above. It's in the same failure domain as those pieces (such as if the machine itself fails) so you already have single points of failure for that instance of serviceA. If you have an HA setup for serviceA, you'd need another instance of that + registrator + the Consul client on a separate machine, and that Consul client would be independent (along with those other pieces). We didn't design for client side HA for Consul since there are always other single points of failure for a given instance of a service.

**Comment by sdvdxl** [comment]
@slackpad I think if I have multiple clients in the cluster and want to use lb(nginx) for load balancing, client1 might be used for registration and client2 might be used for anti-registration, then it won't work properly. And I find that if client1 fails, all the services on client1 will disappear, which is not really high available, and it should automatically move that node's information to another available node. Is there no such function now? Was it deliberately designed that way? Are there any improvements to that or are there any other solutions?

**Comment by jhmartin** [comment]
@sdvdxl 
> Services and client are running on different nodes
This is the key point that is causing you difficulty. The consul client is intended to run on the same node as the services. Running the client on the same node as services enables all of the HA functionality. Attempting to separate them is 'hard mode' and requires you to do a lot of extra work to duplicate the functionality fo the client.

**Comment by wenfei3** [comment]
@slackpad 
I have encountered the same confusion about client side HA.Thanks for your detailed answer.
