### ISSUE TITLE
Web UI Error: 

### ISSUE THREAD

**Issue by jaystramel** [hashicorp/consul#2433]
I'm having difficulty running the web UI for 0.7.0. The browser is able to download the resources, but get the GET request to `/v1/coordinate/nodes?dc=ct-whse&token=` fails and generates the following error in the log:

```
[ERR] http: Request GET /v1/coordinate/nodes?dc=ct-whse&token=<hidden>, error: rpc error: rpc: can't find service Coordinate.ListNodes from=127.0.0.1:32790
```
### `consul version` for both Client and Server

Server: `Consul v0.7.0`
### `consul info` for both Client and Server

Server:

```
gent:
    check_monitors = 3
    check_ttls = 0
    checks = 3
    services = 2
build:
    prerelease = 
    revision = 'a189091
    version = 0.7.0
consul:
    bootstrap = false
    known_datacenters = 1
    leader = false
    leader_addr = 192.168.1.76:8300
    server = true
raft:
    applied_index = 252507000
    commit_index = 252507000
    fsm_pending = 0
    last_contact = 4.389865ms
    last_log_index = 252507000
    last_log_term = 155272
    last_snapshot_index = 252503325
    last_snapshot_term = 155272
    latest_configuration = [{Suffrage:Voter ID:192.168.1.76:8300 Address:192.168.1.76:8300} {Suffrage:Voter ID:192.168.1.166:8300 Address:192.168.1.166:8300} {Suffrage:Voter ID:192.168.0.202:8300 Address:192.168.0.202:8300} {Suffrage:Voter ID:192.168.1.131:8300 Address:192.168.1.131:8300} {Suffrage:Voter ID:192.168.1.130:8300 Address:192.168.1.130:8300} {Suffrage:Voter ID:192.168.1.147:8300 Address:192.168.1.147:8300} {Suffrage:Voter ID:192.168.0.55:8300 Address:192.168.0.55:8300} {Suffrage:Voter ID:192.168.0.240:8300 Address:192.168.0.240:8300}]
    latest_configuration_index = 252502554
    num_peers = 7
    protocol_version = 1
    protocol_version_max = 3
    protocol_version_min = 0
    snapshot_version_max = 1
    snapshot_version_min = 0
    state = Follower
    term = 155272
runtime:
    arch = amd64
    cpu_count = 6
    goroutines = 84
    max_procs = 6
    os = linux
    version = go1.6.3
serf_lan:
    encrypted = false
    event_queue = 0
    event_time = 19579
    failed = 0
    health_score = 0
    intent_queue = 0
    left = 1
    member_time = 20241
    members = 24
    query_queue = 0
    query_time = 1
serf_wan:
    encrypted = false
    event_queue = 0
    event_time = 1
    failed = 0
    health_score = 0
    intent_queue = 0
    left = 0
    member_time = 3958
    members = 7
    query_queue = 0
    query_time = 1
```
### Operating system and Environment details

Ubuntu 12.04.4 LTS
### Description of the Issue (and unexpected/desired result)

The Web UI does not load because the GET request to the API fails.
### Reproduction steps

This error happens every time I try to access the Web UI on any server.
### Log Fragments or Link to [gist](https://gist.github.com/)

```
    2016/10/24 17:37:16 [DEBUG] http: Request GET /v1/catalog/datacenters (249.863µs) from=127.0.0.1:39440
    2016/10/24 17:37:16 [DEBUG] http: Request GET /v1/internal/ui/nodes?dc=ct-whse&token=<hidden> (7.137144ms) from=127.0.0.1:39442
    2016/10/24 17:37:16 [ERR] http: Request GET /v1/coordinate/nodes?dc=ct-whse&token=<hidden>, error: rpc error: rpc: can't find service Coordinate.ListNodes from=127.0.0.1:39443
    2016/10/24 17:37:16 [DEBUG] http: Request GET /v1/coordinate/nodes?dc=ct-whse&token=<hidden> (2.072528ms) from=127.0.0.1:39443
```

**Comment by slackpad** [comment]
Hi @jaystramel what version of Consul is running on your servers?

**Comment by slackpad** [comment]
Closing this since we didn't hear back, but this looks like your Consul servers are running a version of Consul older than 0.6.

**Comment by nikonyrh** [comment]
### Version info

Consul Docker image from https://hub.docker.com/r/library/consul/:

```
Consul build:
        prerelease =
        revision = 2c77151
        version = 0.8.5
```

Other consul instances are still running 0.5.2, which I'm about to upgrade.

### Operating system and Environment details

AWS Ubuntu 14.04.5, 3.19.0-80-generic, Docker version 17.05.0-ce, build 89658be
Docker image startup command: `docker run -e SERVICE_IGNORE=1 -d -h node-name -p 8300-8302:8300-8302/tcp -p 8300-8302:8300-8302/udp -p 8400:8400 -p 8500:8500 consul:0.8.5 agent -server -client 0.0.0.0 -advertise 192.168.1.205 -join 192.168.1.96 -ui`
Browser: Chrome 59.0.3071.115 on Windows 10

### Description of the Issue (and unexpected/desired result)

Oddly this worked fine on an other datacenter, but now with same Docker image and start-up scripts I cannot access the UI. Logs say:

```[ERR] http: Request GET /v1/coordinate/nodes?dc=dc1&token=<hidden>, error: rpc error: rpc: can't find service Coordinate.ListNodes from=10.0.2.193:61837```

**Comment by slackpad** [comment]
> Other consul instances are still running 0.5.2, which I'm about to upgrade.

The Coordinate.ListNode API was added in 0.6.0, so the upgrade should fix this one.
