### ISSUE TITLE
[idea/question] treat failed consul server nodes as a more severe failure (don't remove from catalog automatically?)

### ISSUE THREAD

**Issue by wuub** [hashicorp/consul#244]
Short story: 
I stopped (forcefully) one of our 5 consul server VMs and migrated it to a different host node, with 4 remaining servers everything was working fine (obviously :))

What I forgot to do, was start the migrated VM afterwards [duh].

AFAICT after some time consul (0.3.0) removed the failed consul server service/node from the catalog, I don't know if raft peer set was shrunk at the same time, what I do know is that everything looked green and A-Ok in Consul UI. 

On the one hand this automatic reap is documented, consistent and helpful behaviour, on the other it feels somewhat dangerous when consul servers are involved. 

Maybe failed consul server nodes should be left in the catalog until someone force-leave them? 
Or maybe we should just monitor our consul's peer set more closely?

What do you think?

**Comment by hoffoo** [comment]
:+1 for configuration option

**Comment by slackpad** [comment]
In Consul 0.8 we introduced https://www.consul.io/docs/guides/autopilot.html#dead-server-cleanup which tries to balance things by making it as safe as possible by keeping a failed server in for the 72 hours but kicking it immediately if a new replacement server is introduced.
