### ISSUE TITLE
UI multiple view DC

### ISSUE THREAD

**Issue by Evgen787** [hashicorp/consul#2441]
Hi, a have problem with multiply view DC, when i access to DC1 ui, i cant access to DC2( in main page ui multiple view dc).

HTTP error code from Consul: 403 Forbidden

error in node in DC1:
http: Request GET /v1/internal/ui/nodes?dc=**dc2**&token=, error: rpc error: ACL not found from=127.0.0.1:37293

The problem with AСL?
Consul 0.7

**Comment by slackpad** [comment]
Hi @Evgen787 this looks like you don't have an ACL configured in your web ui that's correct for dc2 (the `?token` parameter is empty).
