### ISSUE TITLE
clusert mode issue with changing IPs

### ISSUE THREAD

**Issue by mperriere** [hashicorp/consul#2442]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:
### `consul version` for both Client and Server

Client: `v0.6.4`
Server: `v0.6.4`
### `consul info` for both Client and Server

Client:

```
consul info -rpc-addr=10.199.255.8:8400
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        server = true
raft:
        applied_index = 7204
        commit_index = 7204
        fsm_pending = 0
        last_contact = 0
        last_log_index = 7204
        last_log_term = 7
        last_snapshot_index = 0
        last_snapshot_term = 0
        num_peers = 2
        state = Leader
        term = 7
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 73
        max_procs = 1
        os = linux
        version = go1.6
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 7
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 9
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 4
        members = 1
        query_queue = 0
        query_time = 1
```

Server:

```
consul info -rpc-addr=10.199.255.8:8400
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        server = true
raft:
        applied_index = 7204
        commit_index = 7204
        fsm_pending = 0
        last_contact = 0
        last_log_index = 7204
        last_log_term = 7
        last_snapshot_index = 0
        last_snapshot_term = 0
        num_peers = 2
        state = Leader
        term = 7
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 73
        max_procs = 1
        os = linux
        version = go1.6
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 7
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 9
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 4
        members = 1
        query_queue = 0
        query_time = 1

```
### Operating system and Environment details

Amazon Linux AMI 2016.03.3 x86_64 HVM GP2
(based on centos 7).
### Description of the Issue (and unexpected/desired result)

We have setup a consul cluster on AWS, and we have an issue with IP.
We use an AWS autoscale group to manage the 3 nodes. It's a kind of loadbalancer that detect issues on nodes, kill them, and create a new one.
The setup is automated with terraform + ansible.

We have a manual step for cluster initiatlization:
Node1:
/opt/consul/bin/consul agent -server -data-dir=/opt/consul/data/10.196.255.8 -bootstrap-expect 3 -bind=10.199.255.8
Node2:
/opt/consul/bin/consul agent -server -data-dir=/opt/consul/data/10.196.255.24 -bind=10.199.255.24
Node3:
/opt/consul/bin/consul agent -server -data-dir=/opt/consul/data/10.196.255.40 -bind=10.199.255.40
-> ok, the cluster is sync'ed and working properly
The data (raft, serft) is located on a persistent disk.
If we restart one node, the cluster is able to join the missing node properly.

Here is the issue:
when we loose a node for any reason, the new node created by the autoscale group comes with a new IP address. The 2 remaining nodes are looking for the old IP, and don't know who is that new IP address. That's a problem because in a AWS EC2 environment we never know what the IP of a new node will be.
Is there a way to allow a node with a new IP to join automatically (without atlas) an existing cluster?

Our solution is to setup 3 persistant IP on a secondary network iface, and to bind consul on it, but it generated sides effects (not possible to use the AWS load balancer anymore).

Our config (same config for the 3 nodes):
{
  "ui": true,
  "disable_remote_exec": true,
  "data_dir": "/opt/consul/data",
  "log_level": "INFO",
  "node_name": "consul-23e7fd35",
  "server": true,
  "bind_addr": "10.199.255.8",
  "datacenter": "aws_dev",
  "bootstrap": false,
  "bootstrap_expect": 3,
  "ports": {
    "dns": 8600,
    "http": 8500,
    "https": -1,
    "rpc": 8400,
    "serf_lan": 8301,
    "serf_wan": 8302,
    "server": 8300
  },
  "rejoin_after_leave": true,
  "leave_on_terminate": true,
  "disable_update_check": false,
  "retry_join": [
    "10.199.255.40",
    "10.199.255.24"
  ]
}
Note that retry_join list the 2 other IP, not the IP of the instance itself.
### Log Fragments or Link to [gist](https://gist.github.com/)

log indicate unable to join old IP

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by spanktar** [comment]
We use the AWS EC2 api to seed this value when the new instance comes up:

    # Get initial values
    AZS=( ${availability_zones} )
    declare -a RESULTS=()
    DESIRED_SEEDS=$((${min_cluster_size_consul} / $${#AZS[@]} + 1))

    echo "> DESIRED SEEDS: $DESIRED_SEEDS"

    # Loop through each AZ to find instance IPs
    for zone in "$${AZS[@]}"; do

        echo "> Get Consul seeds from AWS $zone"
        NUM_SEEDS=0
        while [ $NUM_SEEDS -lt $DESIRED_SEEDS ]; do
            SEEDS=`aws ec2 describe-instances --filters \
                "Name=availability-zone,Values=$zone" \
                "Name=instance-state-name,Values=running" \
                "Name=tag:Consul,Values=Server" \
                "Name=tag:Environment,Values=${environment}"`
            NUM_SEEDS=`echo $SEEDS | jq '.Reservations[].Instances | length'`

            if [[ $NUM_SEEDS == "" ]]; then NUM_SEEDS=0; fi

            echo "> NUM_SEEDS: $NUM_SEEDS"
            sleep 1
        done

        RESULTS+=( `echo $SEEDS | jq -r '.Reservations[].Instances[].PrivateIpAddress'` )

    done

    RETRYJOIN="-retry-join=$${RESULTS[0]}$(printf " -retry-join=%s" "$${RESULTS[@]:1}")"
    echo "> RETRYJOIN: $RETRYJOIN"

**Comment by slackpad** [comment]
Closing this in favor of https://github.com/hashicorp/consul/issues/1580.
