### ISSUE TITLE
Startup gives meaningless error

### ISSUE THREAD

**Issue by juliangamble** [hashicorp/consul#2443]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:
### `consul version` for both Client and Server

Client: `0.6.4`
Server: `0.6.4`
### `consul info`

Client:

```

```
### Operating system and Environment details

Redhat
### Description of the Issue (and unexpected/desired result)

When starting the consul server with an incorrect input - it gives a meaningless startup error. 
### Reproduction steps

Suppose you start consul with 

```
/bin/consul/scripts/start.sh agent -advertise $(hostname -i)
```

But unintentionally  - on one of your servers - the output of `hostname -i` changes from

```
10.1.2.3
```

to this

```
fe80::4a0:3bff:fed8:ef09%eth0 10.42.16.32
```

Yet on consul startup - it still gives the error

  -data-dir incorrectly set

when that was set in the `settings.json` file. Ie the startup error is meaningless, and points you to an incorrect root cause - when in fact the error was caused by a script adding an extra space in a parameter. 

(Assumption that this script is provisioned to a pipeline of servers created via terraform and packer). 

My expectation is that where there is a bunch of misconfigured parameters - consul will throw an error saying:

```
Here is the command line you entered
/bin/consul #$#$#some garbage$#$#
 - is that what you intended? Perhaps you meant something in this format?
```

**Comment by brianshumate** [comment]
This seems to be an issue with option handling and `-data-dir incorrectly set` is the error that is dropped into when options are incorrectly specified.

Case in point, I can also reproduce this with:

```
consul agent 🌮 -dev                               
==> Must specify data directory using -data-dir
```

or

```
consul agent lacroix -data-dir=/tmp
==> Must specify data directory using -data-dir
```

**Comment by pearkes** [comment]
This is much better now do to upstream changes we benefited from. The taco example:

```
$ consul agent 🌮 -dev
==> config: Unknown extra arguments: [🌮 -dev]
```
