### ISSUE TITLE
When a new healthcheck is added to host/service that is in passing state; make it passing as default

### ISSUE THREAD

**Issue by takeda** [hashicorp/consul#2450]
### `consul version` for both Client and Server
Client: `0.7.0`
Server: `0.7.0`

When a host/service is in passing state adding a new health check will take the host/service out until consul will do the check. This is especially bad for infrequent checks (like once an hour).

If host/service was passing all health checks it makes sense to just assume new health check is passing on reload, to prevent unnecessary outages and changes in consul state.

**Comment by highlyunavailable** [comment]
You can set Initial Health Check Status to `passing`, which may help here - see https://www.consul.io/docs/agent/checks.html for more info.

**Comment by takeda** [comment]
I'm talking about scenario when consul config is reloaded, if and before adding a health check everything was passing the new health check should be also passing. If consul just started it should be failing by default. What you are suggesting could work, but it is is just an ugly workaround for that issue and requires extra work (make first change with passing, reload consul, wait until healtcheck is performed, change config to remove the setting and reload consul again).

I suppose the behavior could be simplified to: when a new health check is added during consul reload it should be passing by default, unless default health check status is specified.

**Comment by ChipV223** [comment]
Hi @takeda !

Others have stated, setting the initial check status to `passing` would useful in this scenario. 

I'll go ahead and close this, but do reach out if you have any additional questions!
