### ISSUE TITLE
Warning healthcheck should also be passing

### ISSUE THREAD

**Issue by takeda** [hashicorp/consul#2452]
Currently `warning` health checks are not listed when querying for nodes in `passing` state.

This behavior makes the `warning` state somewhat useless, because in order to also get nodes in `warning` state one has to query for it explicitly.

Perhaps new query state should be created e.g. `passing-only` which would have the old behavior and have `passing` to include both `passing` and `warnng`.

**Comment by bdclark** [comment]
I discovered the same thing today when testing node and service checks resulting in `warning`.

DNS queries seem to give a list of "non-failing" services (those in `warning` and `passing` state), which I now realize isn't the same as the "passing" param on `/v1/health/service/<service>` (returns only `passing`).

So, in order for a health query to give results similar to a DNS query, I'd need to stop using the "passing" param, then add extra filtering logic in my applications to filter-out services in `critical` state.

As @takeda said, it would be helpful if a param (or params) existed to include "non-failing" services... ie. both `passing` and `warning`.

**Comment by slackpad** [comment]
This is closely related to https://github.com/hashicorp/consul/issues/802.

**Comment by bluebob** [comment]
+1 for takeda's comment. We're using consul-template and it's causing us some grief when a "degraded" node gets deconfigured from a cluster because the service status on that node has slipped to 'warning'.
If you want an example, Elasticsearch data nodes. It's handy to know when they're approaching full disks, but you definitely don't want ES to mark the node as dead and try and migrate all it's data!
Any progress folks?

**Comment by jkirschner-hashicorp** [comment]
Hi @takeda, @bdclark, @bluebob, and others,

If I understand correctly, you were looking for a way to get a list of nodes or services which are in either the `passing` or `warning` states (just exclude `critical`).

As of version 1.5, the node and service health endpoints support [filtering expressions](https://www.consul.io/api-docs/features/filtering) to filter the query's results based on field values (like `Status`):
- `/v1/health/node/:node`'s [`filter`](https://www.consul.io/api-docs/health#filtering) query parameter
- `/v1/health/service/:service`'s [`filter`](https://www.consul.io/api-docs/health#filter-1) query parameter

This functionality was implemented in [this PR](https://github.com/hashicorp/consul/pull/5579).

For example, the below should return all non-critical services:
```
curl --get \
    http://127.0.0.1:8500/v1/health/service/my-service
    --data-urlencode 'filter=Status == "passing" or Status == "warning"'
```
