### ISSUE TITLE
Bump max_stale for DNS

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2460]
After getting feedback from the community we realized we should have bumped the max_stale default for DNS at the same time we defaulted allow_stale. Setting this to 72 hours would favor availability, which is probably the right experience out of the box. You could go a weekend without a leader and still serve DNS queries as long as you had some server(s) available.

**Comment by slackpad** [comment]
Originally thought 72 hours would be sufficient, but perhaps we could default to "indefinite", with possibly some warning at a reasonable threshold.

**Comment by scalp42** [comment]
For what it's worth, you can also leverage consul-template and create an /etc/hosts.consul file for example as a backup.
