### ISSUE TITLE
Support HEAD request for http check

### ISSUE THREAD

**Issue by kamaradclimber** [hashicorp/consul#2473]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `0.7.0`

### Description of the Issue (and unexpected/desired result)

When using http health checks (https://www.consul.io/docs/agent/checks.html), many application have large variable output leading to #1244.
Most application we use (couchbase for instance) don't have a clean health endpoint so we use some statistics endpoint (/pools/default/buckets/ for instance).

It would be convenient to be able to configure the http health check to perform HEAD requests instead of GET.

**Comment by slackpad** [comment]
This was added by https://github.com/hashicorp/consul/issues/3106.
