### ISSUE TITLE
Feature: Implement LD_PRELOAD shim for transparent DNS interfacing

### ISSUE THREAD

**Issue by amiryal** [hashicorp/consul#2482]
Hi,

Consul documentation has [a guide on forwarding DNS](https://www.consul.io/docs/guides/forwarding.html), which includes a number of methods to make applications resolve `.consul` addresses through a Consul agent. I would like to suggest to implement another method, based on how [torsocks](https://gitweb.torproject.org/torsocks.git/tree/README.md) and [srv-shim](https://github.com/disasters/srv-shim) work, which is by implementing a small wrapper library around various libc functions (e.g. `connect(2)` or `gethostbyname(3)`), which would handle connections to `.consul` addresses transparently, without requiring any change to the application or a system-wide change.

Example usage:

    LD_PRELOAD=/path/to/libconsulwrapper.so curl http://web.service.consul/example

**Comment by amiryal** [comment]
It might be easy to patch [resolv_wrapper](https://cwrap.org/resolv_wrapper.html) to use `nameserver 127.0.0.1` on port number 8600 instead of 53. (Look for `htons(53)` in its source code.)

How much is this practice advisable for a production application?

**Comment by slackpad** [comment]
Hi @amiryal thanks for opening an issue. I think this would require us to build platform-specific C code to work and we really don't want to give up Consul current status as pure Go, which makes it much easier to support multiple platforms. This kind of interface could be done as a separate project which shims these interfaces and uses the Consul API under the hood to talk to the local agent; that's probably a better approach here.
