### ISSUE TITLE
Consul built-in assets missing font files

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2485]
If you do a `wget -r` against the internal UI there are some missing assets:

```
--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.eot
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.

--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.eot?
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.

--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.woff
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.

--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.ttf
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.

--2016-11-08 14:54:37--  http://localhost:8500/ui/fonts/glyphicons-halflings-regular.svg
Reusing existing connection to localhost:8500.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-11-08 14:54:37 ERROR 500: Internal Server Error.
```

We should fix this and add a check to the ui build to catch these.

**Comment by brianshumate** [comment]
I took a look at this because I'd like to fix it, but it looks like *GLYPHICONS Halflings* icons / icon font are [licensed in a manner](https://glyphicons.com/license/) that is incompatible with open source projects.

From the **You must not** list:

> include icons in open-source projects, since this license is not compatible with most of the open-source licenses

**Comment by slackpad** [comment]
Hmm - let's audit to see where we use them. Maybe we can get rid of them completely as a way forward.

**Comment by brianshumate** [comment]
Sounds good! I would also be happy to find a more open source friendly alternative and implement them as well.

**Comment by brianshumate** [comment]
They're apparently included under a [special provision](http://getbootstrap.com/components/) with Bootstrap:

> Glyphicons Halflings are normally not available for free, but their creator has made them available for Bootstrap free of cost. As a thank you, we only ask that you include a link back to Glyphicons whenever possible.

They are referenced in our minified Bootstrap CSS in `ui/static/bootstrap.min.css`, but it does not appear that we actually use them:

```
pwd
/Users/brian/src/hashicorp/consul
grep -r --exclude="bootstrap*" glyphicon .
```

We could remove the `@font-face` entries from the static minified `bootstrap.min.css` for an instant resolution of this issue, but to avoid this going forward, we'd have to [customize Bootstrap](http://getbootstrap.com/customize/) further and deselect the Glyhicons component.

**Comment by slackpad** [comment]
Trimming our bootstrap build sounds like the way to go.
