### ISSUE TITLE
[FEAT] Allow embedding consul

### ISSUE THREAD

**Issue by purpleidea** [hashicorp/consul#2487]
Thanks for all your work on consul. I think it would be very advantageous to the project if it was embeddable.

### `consul version` for both Client and Server
Client: `git master`
Server: `git master`

### Operating system and Environment details
GNU/Linux

### Description of the Issue (and unexpected/desired result)
Etcd now supports embedding the server itself into your code bases. I think this would be a welcome addition to consul. Documentation on the etcd equivalent here:
https://godoc.org/github.com/coreos/etcd/embed

Thanks,
James

**Comment by slackpad** [comment]
The work in https://github.com/hashicorp/consul/pull/3037 will help greatly in moving us in this direction.

**Comment by purpleidea** [comment]
FYI: we embed etcd in https://github.com/purpleidea/mgmt/ currently, but it would be fairly straight forward to make consul a pluggable alternative if someone is interested in doing the work. The client-only portion is even more straight forward and could be a good first step. Ping if interested.

**Comment by magiconair** [comment]
I'm on it.

**Comment by purpleidea** [comment]
@magiconair Ping me in #mgmtconfig IRC on Freenode if you'd like to discuss more. Alternatively, open an issue on https://github.com/purpleidea/mgmt/ to discuss if you prefer this sort of medium.

**Comment by magiconair** [comment]
I'd like to keep the discussion here where other people can see and search for it as well. Also, I'm probably not on your timezone :)

In the end it'll look like this:

```go
c := &agent.Config{...}
a := agent.Agent{Config: c}
a.Start()
defer a.Stop()
```

You'll have multiple ways of generating the `Config` object but that won't change the way you use it.

**Comment by magiconair** [comment]
See also the discussion on #2217

**Comment by vtolstov** [comment]
any news ?

**Comment by vtolstov** [comment]
so o embed consul server i need to create config and start agent?

**Comment by gaoxinge** [comment]
@vtolstov Below code may work:

```go
package main

import "github.com/hashicorp/consul/agent"

func main() {
	a := agent.NewTestAgent(t, t.Name(), "")
	defer a.Shutdown()

	// do things that you want with consul
}
```

- [proxy_test](https://github.com/hashicorp/consul/blob/master/connect/proxy/proxy_test.go#L27)
- [connect_ca_endpoint_test](https://github.com/hashicorp/consul/blob/master/agent/connect_ca_endpoint_test.go#L24)

**Comment by mkeeler** [comment]
FWIW you could embed it similarly to how the CLI command starts an agent. 

https://github.com/hashicorp/consul/blob/master/command/agent/agent.go

However, I wouldn’t recommend this. The agent makes many assumptions about its life cycle like that many long running Go routines will end when the main process ends. So you cannot restart an agent in-process without leaking go routines

**Comment by vtolstov** [comment]
this is only agent thing, but i need to embed server (kv)

**Comment by mkeeler** [comment]
An agent is either a server or client depending on the configuration given. I guess it would also be possible to embed only the server. In theory you just need to call [`github.com/hashicorp/consul/agent/consul.NewServerLogger`](https://godoc.org/github.com/hashicorp/consul/agent/consul#NewServerLogger) with valid arguments.

The same caveats apply though of leaking go routines and such.

**Comment by jsosulska** [comment]
Hi All,

Apologies for raising an old issue, but wanted to provide some closure here.

As Consul has matured, it's become too complicated to simply embed in other codebases. There is a large effort in making this work consistently, and on a whole, the Consul team doesn't feel that embedding Consul is the right choice to support moving forward. 

As @mkeeler pointed out:
> The agent makes many assumptions about its life cycle like that many long running Go routines will end when the main process ends. So you cannot restart an agent in-process without leaking go routines.

Currently the only thing that is supported as a standalone package is [github.com/hashicorp/consul/api](https://pkg.go.dev/github.com/hashicorp/consul/api?tab=versions).

Happy coding!

**Comment by purpleidea** [comment]
> As Consul has matured, it's become too complicated to simply embed in other codebases. There is a large effort in making this work consistently, and on a whole, the Consul team doesn't feel that embedding Consul is the right choice to support moving forward.

@jsosulska That's a pretty disappointing thing to hear. While it's unfortunate this hasn't progressed further, it makes it clear hashicorp is distancing itself from "community" wishes here, and from a technical POV I think the decision not to pursue this reflects badly on the project.

I probably shouldn't say anything, but everyone is using etcd anyways, so I guess I'll just abandon my efforts to support consul.

**Comment by vtolstov** [comment]
yes, etcd is more suitable choice for raft kv. in current situation consul have no benefit for developers.
