### ISSUE TITLE
Local health endpoint

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul#2488]
I want to use Consul to provide healthchecks for Amazon ELBs. Basically, I wanted to set the ELB healthcheck to query an instance's health by hitting some Consul HTTP endpoint. The [`/v1/agent` endpoint](https://www.consul.io/docs/agent/http/agent.html) seems close to what I want, but there doesn't seem to be a `/v1/agent/service/<service_id>/health` endpoint. Does such an endpoint exist (maybe I am looking in the wrong place)?

**Comment by slackpad** [comment]
Hi @joshuaspence we don't currently have an agent-level endpoint to pull the health of an agent. There's https://www.consul.io/docs/agent/http/health.html#health_node but that'll end up going up to the Consul servers, and the HTTP status code doesn't indicate the state of the health checks. This looks like a possible dup of https://github.com/hashicorp/consul/issues/1468.

**Comment by brumschlag** [comment]
+1
How can I use consul with an ELB? I want to have the elb take out the instance if I put it in maintenance mode.

**Comment by joshuaspence** [comment]
Would the upstream be interested in a pull request for this functionality?

**Comment by kamaradclimber** [comment]
We would definitely be interested by having /v1/agent/service/<service id>/health return 200, 419 or 500.

That would allow to configure complex checks on consul side and expose a very simple interface for our loadbalancer (which would delegate healthchecks to consul).

**Comment by kadaan** [comment]
I wanted the same functionality, so I developed a sidecar that can be used to accomplish this: [Consulate](https://github.com/kadaan/consulate)  The first version is done and I'm testing it in my dev environment this week.  Would love any feedback!
