### ISSUE TITLE
'consul lock' can leave orphanned child processes when exiting on a signal

### ISSUE THREAD

**Issue by mattghali** [hashicorp/consul#2489]
When the `consul lock` is used, it accepts many signals which will cause it to exit. However, it will only pass TERM on to children it is managing before exiting (see [consul/commands.go](https://github.com/hashicorp/consul/blob/master/commands.go#L195-L211)).

This causes orphans when the process exits on a signal besides TERM, for instance HUP. The end result is multiple processes running where `consul lock` was being used to specifically limit their concurrency.

Please consider passing all signals that cause `consul` to exit along to children, when possible.

**Comment by mattghali** [comment]
This could be the same issue as [1210](https://github.com/hashicorp/consul/issues/1210) is raising.

**Comment by slackpad** [comment]
Closing this against https://github.com/hashicorp/consul/issues/2999.
