### ISSUE TITLE
incorrect logo with Solaris name

### ISSUE THREAD

**Issue by ikozhukhov** [hashicorp/consul#2493]
Please update download page.
you have mistake - illumos logo point to Solaris name.
more correct - move Solaris -> illumos and leave illumos logo for consistency

Best regards,
-Igor
(illumos developer)

**Comment by sethvargo** [comment]
I think we fixed this @slackpad? At least, we merged those changes to middleman-hashicorp.

**Comment by ikozhukhov** [comment]
yes - it fixed on site, thanks

**Comment by slackpad** [comment]
Oh I see - I thought it was the other way around. Closing this out.
