### ISSUE TITLE
Deprecate CLI RPC interface

### ISSUE THREAD

**Issue by kyhavlov** [hashicorp/consul#2502]
Some CLI commands still use the RPC interface instead of HTTP under the hood, and we want to make this consistent so that everything goes through HTTP using the api package.

### Commands still using RPC:

- [x]  force-leave (/v1/agent/force-leave)
- [x] info (/v1/agent/self)
- [x] join (/v1/agent/join/)
- [x] keyring (needs HTTP endpoint)
- [x] leave (needs HTTP endpoint)
- [x] members (/v1/agent/members)
- [x] monitor (needs HTTP endpoint)
- [x] reload (needs HTTP endpoint)

### New HTTP endpoints:

- [x] /v1/keyring
  - [x] /v1/keyring/install
  - [x] /v1/keyring/list
  - [x] /v1/keyring/remove
  - [x] /v1/keyring/use
- [x] /v1/agent/leave
- [x] /v1/agent/monitor
- [x] /v1/agent/reload

**Comment by slackpad** [comment]
Moving forward to capture the rest of the work by 0.8.
