### ISSUE TITLE
can not join the cluster use the agent parameter -client

### ISSUE THREAD

**Issue by shotdog** [hashicorp/consul#2505]
I am running two consul servers. When I try to join them in a cluster, I get this error:

getsockopt: connection refused

$ consul join 192.168.99.2
Error connecting to Consul agent: dial tcp 127.0.0.1:8400: getsockopt: connection refused

the boot the consul agent like this 

**consul agent -server -bootstrap-expect=1 -bind=192.168.99.2 -client=192.168.99.2 -data-dir=/usr/consul -config-dir=/etc/consul.d -node=agent-n2 -datacenter=dc1**

**consul agent -server -bind=192.168.99.3 -client=192.168.99.3 -data-dir=/usr/consul -config-dir=/etc/consul.d -node=agent-n2 -datacenter=dc1**

consul join 192.168.99.2  

the ip 192.168.99.3  is my local ip address   

the result error is : 

> Error connecting to Consul agent: dial tcp 127.0.0.1:8400: getsockopt: connection refused

but  I use the next command is success join the cluster

**consul agent -server -bind=192.168.99.3 -client=127.0.0.1 -data-dir=/usr/consul -config-dir=/etc/consul.d -node=agent-n2 -datacenter=dc1**

why ?

**Comment by slackpad** [comment]
The `consul join` command is trying to connect to the client listener on the `-client` address. Generally we don't recommend setting `-client` to anything that's exposed outside the machine. If you wanted to get the join to work in the first case, use `consul join -rpc-addr=192.168.99.2:8400`.

**Comment by dilipmevada** [comment]
How to resolve this error?
C:\Consul>consul join 192.168.xx.xxx
Error joining address '192.168.xx.xxx': Unexpected response code: 500 (1 error(s) occurred:

* Failed to join 192.168.xx.xxx: dial tcp 192.168.xx.xxx:8301: i/o timeout)
Failed to join any nodes.

**Comment by slackpad** [comment]
Hi @dilipmevada that looks like the server you are trying to join to maybe has a firewall blocking port 8301, or that Consul on that machine isn't listening on the interface you are expecting (check your bind configuration for Consul).
