### ISSUE TITLE
Keep alive timeout while connecting Atlas to my AWS consul infrastructure

### ISSUE THREAD

**Issue by nidhishopback** [hashicorp/consul#2514]
Hi,

I have setup my own consul cluster on AWS EC2 and have connected to consul  Atlas using a token.

I can see the infrastructure loads up fine, but doesnt refresh on its own.

Can see the following errors in debug logs : 
```
2016/11/17 02:53:47 [ERR] yamux: keepalive failed: i/o deadline reached
2016/11/17 02:53:47 [ERR] scada-client: failed to accept connection: keepalive timeout
```

 I have the following inbound rules set up in my security group : 
```
Custom TCP Rule --- TCP  --- 7223  ---- 52.1.112.239/32
Custom TCP Rule   --- TCP  --- 7223 --- 52.203.124.152/32
```

What am I missing here? If I am not wrong, the infrastructure should auto refresh every few seconds, but in the screenshot attached, it doesnt happen unless I reload the infrastructure manually on environments page.

Thanks,
Nidhi
![screen shot 2016-11-17 at 11 23 02 am](https://cloud.githubusercontent.com/assets/21728733/20375174/5c6dcd8e-acb8-11e6-80d9-51779e9f8424.png)

**Comment by slackpad** [comment]
Hi @nidhishopback the hosted Consul Enterprise in Atlas is now deprecated and will be discontinued on March 7, 2017. You can check out https://atlas.hashicorp.com/help/consul/alternatives for more details.

Not sure if you are still experiencing this issue, but my guess is that's it's a different IP than you've set here. Also, only a subset of the data auto-refreshes in Atlas, so it may depend on what you are looking at. Feel free to shoot an email to support (at) hashicorp.com if you are still having trouble.
