### ISSUE TITLE
Add a CRC + validation to UDP gossip messages

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2519]
We've seen some cases in the wild where UDP corruption happened in gossip messages because UDP's checksum isn't the greatest. We should add a CRC to our gossip payloads down in memberlist and pull via vendoring into Serf and Consul.

**Comment by ciprian108** [comment]
Hi,
This a long time ago added feature; however, while using consul v1.2.1, I don't see that the gossip packets have CRC; also, I saw that the sending of CRC is conditioned by counterpart having protocol version 5; but, looking at my nodes:
_Consul v1.2.1
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)_
How can I make consul messages be protected with CRC?

Thanks,
Ciprian.

**Comment by blake** [comment]
Hi @ciprian108,

> Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

This is referring to Consul's RPC [protocol](https://www.consul.io/docs/agent/options#_protocol) version, which is different from the protocol version used by memberlist.

I believe this change should be present in Consul 1.2.x, so I'm not sure why you're not seeing the CRC checksum. Someone from the Consul engineering team should be able to provide more insight into that issue.

**Comment by ciprian108** [comment]
Hi @blake,
You are right; I noticed later on that there is CRC for the larger UDP segments, not for the short 'ping' ones; now, in our case, the corruption happens actually in TCP; and to me it seems that TCP doesn't have any CRC.
