### ISSUE TITLE
v1/health/state inconsistent results

### ISSUE THREAD

**Issue by jijojv** [hashicorp/consul#2522]
I have a cluster with 3 server nodes and 8 clients doing a handful of checks

The count of checks using
curl -s localhost:8500/v1/health/state/any?consistent=true | jq . | grep CheckID -c
returns 33, 24, 26 on the 3 server nodes.

Is this a bug and is there a better way to dump the health states of all the checks in a  dc in a consistent manner ?

```
consul info
agent:
	check_monitors = 4
	check_ttls = 0
	checks = 4
	services = 1
build:
	prerelease =
	revision = 26a0ef8c
	version = 0.6.4
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	server = true
raft:
	applied_index = 201524
	commit_index = 201524
	fsm_pending = 0
	last_contact = never
	last_log_index = 201524
	last_log_term = 523
	last_snapshot_index = 196935
	last_snapshot_term = 523
	num_peers = 0
	state = Leader
	term = 523
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 81
	max_procs = 24
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 17
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 132
	members = 11
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 11
	members = 1
	query_queue = 0
	query_time = 1

```

**Comment by slackpad** [comment]
> num_peers = 0

Hi @jijojv it looks like your servers aren't properly connected together if the peer count is 0. That should show as 2 for a 3 server cluster. Is there anything in the logs related to Raft?

**Comment by jijojv** [comment]
Hi @slackpad. I was not getting a leader election in the past and no checks were getting rpc errors, probably related to https://github.com/hashicorp/consul/issues/993 so i had added bootstrap_expect 1 on one of the nodes based on the comments.

Tried different combinations, finally had to  rm -rf /var/lib/consul everywhere  add readd bootstrap_expect 3 to get a consistent result and now i do see num_peers 2. 

Thanks a lot.
