### ISSUE TITLE
How to tell if a node is a member of a cluster?

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul#2524]
I am wanting to write some sort of sanity check script for our hosts which are running Consul, using [Serverspec](http://serverspec.org/). Currently we just do this:

```
describe 'consul' do
  context service('consul') do
    it { should be_enabled }
    it { should be_running }
  end

  context command('consul configtest -config-dir /etc/consul') do
    its(:exit_status) { should eq 0 }
  end

  context port(8500) do
    it { should be_listening.on('127.0.0.1').with('tcp') }
  end
end
```

I am wanting to add a test which verifies that the agent has successfully connected to the cluster, but I am not sure if there is any `consul` command which allows me to do this?

**Comment by joshuaspence** [comment]
Running `consul operator raft -list-peers` seems to work, but is this the best solution? Can I rely on this command failing (exiting with a non-zero status) if the agent is not a member of a cluster:

```
> consul operator raft -list-peers
Operator "raft" subcommand failed: Unexpected response code: 500 (No known Consul servers)
```

**Comment by rbrutas** [comment]
will this work?
```
describe command('consul members |grep " server "') do
  its(:stdout) { should match /server/ }
end
```

**Comment by slackpad** [comment]
Hi @joshuaspence the best way to do this is probably to query https://www.consul.io/docs/agent/http/health.html#health_node for the node name and make sure its `serfHealth` check is passing. This verifies that the agent is part of the cluster, the servers are aware of it and have logged it into the catalog, and that the rest of the cluster things that agent is alive.
