### ISSUE TITLE
why api.Put(Acquire) doesn't return QueryMeta?

### ISSUE THREAD

**Issue by Kane-Sendgrid** [hashicorp/consul#2534]
Is there any reason why Put/Acquire don't return QueryMeta? There are some scenarios, especially with locks when it might be useful.

**Comment by slackpad** [comment]
Hi @Kane-Sendgrid that old KV API doesn't have a structure that allows us to add new fields. We added this information in the return response for https://www.consul.io/docs/agent/http/kv.html#txn, so you can use that.
