### ISSUE TITLE
Consul memory growing indefinitely under load test on KV

### ISSUE THREAD

**Issue by jacob-koren** [hashicorp/consul#2535]
1. I'm running load test against a single node cluster (server agent with data-dir). 
2. The load is around 2000 req/sec on the KV store (PUT/GET). 
3. I noticed that no matter how much memory I give the container, consul will reach this limit and therefore the container will be killed.
4. It seems that consul saves all the KV data in memory.

### `consul version`
Server: consul:0.7.1 (official docker image)

### Configuration:
`{
  "id": "/consul-performance/consul",
  "args": [
    "agent",
    "-server",
    "-data-dir=/consul/data",
    "-ui",
    "-retry-join=consul.consul-performance.marathon.mesos",
    "-retry-max=10",
    "-client=0.0.0.0",
    "-bootstrap-expect=1"
  ],
  "env": {
    "CONSUL_BIND_INTERFACE": "eth0",
    "CONSUL_LOCAL_CONFIG": "{\"telemetry\": { \"statsite_address\": \"consul-performancestatsite.marathon.l4lb.thisdcos.directory:8135\"},\"leave_on_terminate\": true,\"ports\":{\"http\": 10163,\"dns\": 10166,\"server\": 10164,\"serf_wan\": 10162,\"serf_lan\": 10161,\"rpc\": 10165}}",
    "GOGC": "50"
  },
  "instances": 0,
  "cpus": 2,
  "mem": 512,
  "disk": 0,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "docker": {
      "image": "consul:0.7.1",
      "forcePullImage": false,
      "privileged": false,
      "network": "HOST"
    }
  },
  "healthChecks": [
    {
      "protocol": "HTTP",
      "path": "/v1/status/leader",
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ],
  "portDefinitions": [
    {
      "protocol": "tcp",
      "port": 10163
    },
    {
      "protocol": "tcp",
      "port": 10161
    },
    {
      "protocol": "tcp",
      "port": 10162
    },
    {
      "protocol": "tcp",
      "port": 10164
    },
    {
      "protocol": "tcp",
      "port": 10166
    },
    {
      "protocol": "tcp",
      "port": 10165
    }
  ],
  "requirePorts": true
}`

### Operating system and Environment details
DC/OS mesos

**Comment by slackpad** [comment]
Hi @jacob-koren Consul does store all of the KV data in memory. It uses disk for the Raft log and snapshots, but all of the current working set for the state store is in memory, so this is expected if you are adding more and more keys to the store. I'll tag this as a docs issue because I don't have a good place to point to that explains that, and we should make that clear in the docs.

**Comment by jacob-koren** [comment]
So consul is entirely in memory DB? What do you mean by "current working set"?

**Comment by slackpad** [comment]
It's entirely in-memory. I was just making a distinction between the Raft log which has all the changes since the last Raft snapshot vs. in-memory which is the current state of everything.

**Comment by alexeyknyshev** [comment]
@slackpad If I add & remove some keys to consul KV over a long period (say P = 1 month) of time while in any time (say T) in period P I have nearly constant count of keys, do I have to expect memory footprint grow trend?

Thanks in advance

**Comment by brianshumate** [comment]
Thanks for the issue report; documentation around memory usage was updated in #2535, and this will be closed now.
