### ISSUE TITLE
Raft tries to connect to wrong IP during leader election

### ISSUE THREAD

**Issue by thecodeassassin** [hashicorp/consul#2539]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `0.7.1`
Server: `0.7.1`

### `consul info` for both Client and Server
Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 'a9455cd
	version = 0.7.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr =
	server = true
raft:
	applied_index = 0
	commit_index = 0
	fsm_pending = 0
	last_contact = never
	last_log_index = 1
	last_log_term = 1
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:10.240.0.3:8300 Address:10.240.0.3:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Candidate
	term = 176
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 60
	max_procs = 1
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 13
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Ubuntu 14.04 LTS

### Description of the Issue (and unexpected/desired result)

Expected: Working leader election, being able to actually use consul. **The IP of this server is 10.2.0.2**.

Result:

RAFT leader election fails, tries to reach other servers on invalid IP addresses. No way to update these addresses. The IP addresses in /etc/consul.conf are correct.

```
 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.240.0.3:8300 10.240.0.3:8300}: dial tcp 10.240.0.3:8300: getsockopt: connection timed out
```

I don't even know where these IP's are coming from. This issue started appearing when trying to upgrade consul to 0.7.1 on all our nodes. Version 0.6.4 works as expected.

Upstart config:

http://tca0.nl/Gpq

### Reproduction steps

Start consul with the following config:

http://tca0.nl/WRZ

### Log Fragments or Link to [gist](https://gist.github.com/)

Server log: http://tca0.nl/oAk

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
In any case, you may want to track down that IP and make sure you don't have a rogue server that joined at some point, you'll want to run at least 3 servers for HA, and `set bootstrap_expect` to 3.

If you don't need any of your cluster data, stopping all servers, removing the Consul data directory, and then starting them up should fix this. If you need data on the servers, then following the recovery steps for "Failure of Multiple Servers in a Multi-Server Cluster" in the Outage Guide should help - https://www.consul.io/docs/guides/outage.html. Consul 0.7.1 still supports the peers.json file for manually setting up the correct peer IPs and ports.

**Comment by thecodeassassin** [comment]
@slackpad i am now trying a 3 node setup with 0.7.1. I'll let you know. But in any case that doesn't explain why it's trying to contact nodes on a non-existing IP i think.

**Comment by slackpad** [comment]
If you have any backups or the data dir pre-upgrade we might be able to look in there and see where the IP came from.

**Comment by thecodeassassin** [comment]
@slackpad not possible, i create new machine images for every upgrade and replace the nodes with them.

**Comment by slackpad** [comment]
Hmm - my only theory so far is that you had an old IP in the Raft peers. Do you have any logs around from the old machines?

**Comment by thecodeassassin** [comment]
@slackpad This is still happening as of Consul 0.7.2. I create a fresh consul installation with packer and i don't start it. Then when i bootstrap the nodes the wrong ip addresses show up and consul cannot start the leader selection. I cannot explain where these 10.132.x.x ip's are coming from 😕 

```
    2017/01/16 15:51:58 [WARN] raft: Election timeout reached, restarting election
    2017/01/16 15:51:58 [INFO] raft: Node at 10.2.0.4:8300 [Candidate] entering Candidate state in term 15
    2017/01/16 15:51:59 [ERR] raft: Failed to make RequestVote RPC to {Voter 10.132.0.3:8300 10.132.0.3:8300}: dial tcp 10.132.0.3:8300: getsockopt: connection timed out
```

```
{
      "ui": true,
    "start_join": ["10.2.0.4","10.2.0.3","10.2.0.2"],
  "retry_join_wan": [],
  "retry_interval_wan": "30s",
  "retry_max_wan": 0,
  "disable_remote_exec": true,
  "domain": "consul.",
  "data_dir": "/opt/consul/data",
  "dns_config": {
    "allow_stale": false,
    "max_stale": "5s",
    "node_ttl": "0s",
    "service_ttl": {
            "*": "0s"
          },
    "enable_truncate": false,
    "only_passing": false
  },
  "log_level": "INFO",
  "node_name": "consul-server-staging-001",
  "server": true,
  "bind_addr": "10.2.0.4",
  "advertise_addr": "10.2.0.4",
  "datacenter": "mycujoo-eu-staging",
  "bootstrap_expect": 3,
  "encrypt": "OZq1T+HBWauWc2HUkv58nA==",
  "ports": {
    "dns": 8600,
    "http": 8500,
    "https": -1,
    "rpc": 8400,
    "serf_lan": 8301,
    "serf_wan": 8302,
    "server": 8300
  },
  "http_api_response_headers": {
        "Access-Control-Allow-Origin": "*"
  },
  "rejoin_after_leave": false,
  "leave_on_terminate": true,
  "disable_update_check": false

}
```

**Comment by slackpad** [comment]
@thecodeassassin when its in that state (even if it can't elect a leader) do those addresses show up in `consul members` on the servers?

**Comment by thecodeassassin** [comment]
No they don't show up anywhere but in the logs. The weird thing is that when i change the network to 10.132, 10.133 or anything else with three digits in the second octet it does work. it seems to be a bug with parsing the ip addresses or something.

**Comment by lievendp** [comment]
I'm having a similar problem where RAFT is referring to an old ip from a non-server member.
leave & join of the member doesn't help as RAFT still refers to the member's previously known ip.
The ip's in my case come from an overlay network.
How does RAFT find the ip's of the "members" of the cluster and how can I force it to re-resolve this hostname / ip?

output consul info on the server: (note, 1 server and 1 client in my dev setup)
...
consul:
        bootstrap = true
        known_datacenters = 1
        leader = false
        leader_addr = 
        server = true
...
        latest_configuration = [{Suffrage:Voter ID:10.0.0.4:8300 Address:10.0.0.4:8300}]

consul members however show perfectly the right ip's:

/ # consul members
Node                  Address        Status  Type    Build  Protocol  DC
kvm-centos7-docker-a  10.0.0.5:8301  alive   server  0.7.2  2         intracontainer
kvm-centos7-docker-b  10.0.0.9:8301  alive   client  0.7.2  2         intracontainer

Just RAFT doesn't want to update the ip. 

workaround:
clean consul data folder and basically restart anew.
stopping / starting the consul containers without removing raft data will lead to the same issue.

**Comment by s4s0l** [comment]
@lievendp running consul in docker swarm mode is hard:) 

I confirm that this happens. when -bootstrap-expect=1 and consul is running in docker with persistence enabled, when consul container gets a new IP (after restart, update of swarm service etc) It refuses to pick itself as a leader, in logs it looks like:

```
   2017/03/13 13:06:53 [INFO] raft: Node at 192.168.42.10:8300 [Candidate] entering Candidate state in term 188
    2017/03/13 13:06:54 [ERR] agent: failed to sync remote state: No cluster leader
    2017/03/13 13:06:56 [ERR] raft: Failed to make RequestVote RPC to {Voter 192.168.42.5:8300 192.168.42.5:8300}: dial tcp 192.168.42.5:8300: getsockopt: no route to host
```
there is not much you can do with it:/ 

```
/ # consul operator raft -list-peers -stale=true
Node       ID                 Address            State     Voter
(unknown)  192.168.42.5:8300  192.168.42.5:8300  follower  true
``` 
Remove peer does not work as there is no leader.

**Comment by lievendp** [comment]
@s4s0l But I'm not running docker swarm. :-)
basically it's more like a no-redundancy scenario, right.

**Comment by chuck-wood** [comment]
Just chiming in that this is still present in 0.8.1. Only known fix is to wipe out data folder, which as you can imagine is quite frustrating. My machine was previously 192.168.0.102, which I saved into the config file.

Now, on a different day, my machine got a different IP (192.168.0.104). I updated the config file again.

When I start Consul, it recognizes the new IP but is also still trying to get 102's vote. This happens even with bootstrap_expect set to 1. Does Raft just absolutely have to have at least one other machine's vote to elect a leader?

```
==> WARNING: BootstrapExpect Mode is specified as 1; this is the same as Bootstrap mode.
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v0.8.1'
           Node ID: '45b7c929-3e29-7c92-177e-caca0a7ce198'
         Node name: 'cw'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 192.168.0.104 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2017/05/01 14:06:48 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:192.168.0.102:8300 Address:192.168.0.102:8300}]
    2017/05/01 14:06:48 [INFO] raft: Node at 192.168.0.104:8300 [Follower] entering Follower state (Leader: "")
    2017/05/01 14:06:48 [INFO] serf: EventMemberJoin: cw 192.168.0.104
    2017/05/01 14:06:48 [WARN] serf: Failed to re-join any previously known node
    2017/05/01 14:06:48 [INFO] consul: Adding LAN server cw (Addr: tcp/192.168.0.104:8300) (DC: dc1)
    2017/05/01 14:06:48 [INFO] serf: EventMemberJoin: cw.dc1 192.168.0.104
    2017/05/01 14:06:48 [WARN] serf: Failed to re-join any previously known node
    2017/05/01 14:06:48 [INFO] consul: Handled member-join event for server "cw.dc1" in area "wan"
    2017/05/01 14:06:55 [ERR] agent: failed to sync remote state: No cluster leader
    2017/05/01 14:06:57 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2017/05/01 14:06:57 [INFO] raft: Node at 192.168.0.104:8300 [Candidate] entering Candidate state in term 48
    2017/05/01 14:06:59 [ERR] raft: Failed to make RequestVote RPC to {Voter 192.168.0.102:8300 192.168.0.102:8300}: dial tcp 192.168.0.102:8300: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by slackpad** [comment]
Similar to https://github.com/hashicorp/consul/issues/2374 and https://github.com/hashicorp/consul/issues/2954, need to pull these into one issue.

**Comment by slackpad** [comment]
Closing this in favor of https://github.com/hashicorp/consul/issues/1580.

**Comment by bkannadassan** [comment]
Hi All,

  I have the same issue with consul-helm official release, I see that consul members doesn't show this ip but its trying to requestVote which fails. Please let me know how to get it working ?. I don't see this ip anywhere.

rgds
Balaji Kamal Kannadassan

**Comment by stdin** [comment]
Ran into the same issue with docker swarm. After days of research and reading countless threads and bug reports, I still don't have a solution to this problem.
