### ISSUE TITLE
Web UI fails when trying to edit or show key named "GOOGLE_ANALYTICS_ID"

### ISSUE THREAD

**Issue by ezolenko2** [hashicorp/consul#2545]
### `consul version` for both Client and Server
Client: `0.7.1`
Server: `0.7.1`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = 'a9455cd
        version = 0.7.1
consul:
        known_servers = 5
        server = false
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 43
        max_procs = 1
        os = linux
        version = go1.7.3
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 6
        member_time = 94
        members = 16
        query_queue = 0
        query_time = 1
```

Server:
```
```

### Operating system and Environment details
CentOS 7, on EC2 instance.

### Description of the Issue (and unexpected/desired result)
When trying to create or show key named `GOOGLE_ANALYTICS_ID`, UI fails with `Received error while processing: error` when creating or `HTTP error code from Consul: 0 error` if trying to view key created by other means.

### Reproduction steps
Go to KEY/VALUE page, type GOOGLE_ANALYTICS_ID and click CREATE.

### Log Fragments or Link to [gist](https://gist.github.com/)
There is nothing interesting in logs on the machine that runs the UI.

**Comment by ezolenko2** [comment]
Other kinds of keys can be created, viewed and edited normally.

**Comment by slackpad** [comment]
Hi @ezolenko2 I can't reproduce this, and Consul nor the UI code has anything related to Google Analytics. Is it possible you have a content filter / ad blocker / or some proxy in the middle?

**Comment by ezolenko2** [comment]
Ah, indeed. I have ublock origin and it blocks something. Disabling ad blocking makes everything work. User error. :)
