### ISSUE TITLE
Sets server to expect bootstrap mode

### ISSUE THREAD

**Issue by shotdog** [hashicorp/consul#2550]
what mean "Sets server to expect bootstrap mode" ?   
like this  consul agent -bootstap-expect=0 -server

**Comment by slackpad** [comment]
Hi @shotdog can you point to where you saw that? I'm not sure exactly what the context is for your question. "bootstrap mode" generally refers to `-bootstrap-expect=N` where the servers will wait for N to come online before bootstrapping themselves.

**Comment by shotdog** [comment]
When I started agent server bootstrap-expect=3 is specified, if I have launched 2 server agent use "**consul agent -bootstap-expect=3 -server -data-dir=/consul -config-dir=/etc/consul.d -bind=192.168.99.2 -node=agent1 -datacenter=dc1 -ui** "but I find new elections to produce a leader. Not the? Why "**bootstrap-expect=N**" is it when I started server agent N to start the election to generate a new leader?

**Comment by slackpad** [comment]
The `-bootstrap-expect` setting only applies when you have a fresh cluster that has never been bootstrapped before. After they have boostrapped (even if they are restarted) then this setting doesn't take effect anymore. It's basically only useful for totally new clusters of Consul servers. Hope that helps!
