### ISSUE TITLE
When my application use consul, how to avoid a single point of failure?

### ISSUE THREAD

**Issue by shotdog** [hashicorp/consul#2554]
When my application uses consul, how to avoid a single point of failure?
like this 
For example, one of my java projects using  consul client SDK, I started a local consul agent client. If my local consul agent client down, it won't have a single point of failure? So where did I see the consul documentation? How do I solve this problem? Thank you！

**Comment by slackpad** [comment]
Hi @shotdog please take a look at these mailing list posts which should help:

https://groups.google.com/forum/#!searchin/consul-tool/phillips$20failure$20domain%7Csort:relevance/consul-tool/0_fEPrbtT5g/r8c5Fk-tGgAJ

https://groups.google.com/forum/#!searchin/consul-tool/single$20point$20of$20failure%7Csort:relevance/consul-tool/_ZQVD4txyzM/oFRWpW7kCQAJ

The short answer is that as long as you have 3 or more Consul servers, Consul won't have a single point of failure. Having on Consul client on each node in your environment doesn't make things less resilient, as it's in the same failure domain as that host.
