### ISSUE TITLE
We need full DNS functional

### ISSUE THREAD

**Issue by westsouthnight** [hashicorp/consul#2559]
### `consul version`
Client: Latest 0.7.1
Server: Lstest 0.7.1

### `consul info` for both Client and Server
Client:
```
all right =)
```

Server:
```
all right =)
```

### Operating system and Environment details

Ubuntu 16.04

### Description of the Issue (and unexpected/desired result)

I want to have Public DNS domain with sub zone service.domain.com resolved correctly from Consul Service Discovery by external DNS requests.

### Reproduction steps

I try to use multiple configurations, and no have good or any manual how to do its works without recursors, rewriting and other not work magic.

Maximum what i can to do, that it - forward requests to consul via "forward only" rules, from dnsmasq/bind/unbound 

Im configure a reverse zones, and all what need and can search in public manuals.

And yes, my Service Discovery services can be resolved by public services, but not accessible main records in Bind

Second way, with two zones in Bind
```
main: domain.com with local DB
secondary: service.domain.com with forward only to Consul 
```
not work too.

###

Somebody have way to configure it properly?

**Comment by slackpad** [comment]
Hi this is probably a better question for the Consul mailing list, you'll get better exposure there.
