### ISSUE TITLE
ACL replication not working in 0.7.1

### ISSUE THREAD

**Issue by cliff-ops** [hashicorp/consul#2562]
Versions:

Client: Consul v0.7.1
Server: Consul v0.7.1

OS: CentOS Linux release 7.2.1511

added the following on all server agent in the authoritative ACL datacenter as well as the non-authoritative ACL datacenter. I also attempted adding it to only the non-authoritative datacenter.
Restarted all server nodes in all DCs after making changes

"acl_replication_token": xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
"acl_down_policy": "extend-cache"

With log level set to TRACE I see the following in the logs on my non-authoritative ACL datacneter Consul server agents  every minute:

2016/12/01 14:16:41 [WARN] consul: ACL replication error (will retry if still leader): failed to retrieve remote ACLs: rpc error: ACL not found

I see nothing on the authoritative on the Consul server agents running in my authoritative ACL datacenter even with the log level set to TRACE.

It is unclear what that error message means or what might be the cause. I do have existing ACLs and I can see them in the UI.  When I curl the replication endpoint I see the following:

curl -s localhost:8500/v1/acl/replication | jq '.'
{
  "Enabled": true,
  "Running": true,
  "SourceDatacenter": "JPN",
  "ReplicatedIndex": 0,
  "LastSuccess": "0001-01-01T00:00:00Z",
  "LastError": "2016-12-01T22:36:51Z"
}

Also the docs don't really indicate what the acl_replication_token parameter should be. Is this the master token? Should it be another management token set up for just this purpose?

**Comment by slackpad** [comment]
Hi @cliff-ops - you don't need to set that in the ACL datacenter, just all the remote datacenters. The ACL datacenter doesn't do replication and won't show anything special if it's enabled there.

The token you supply can be the master token, or another management token. Since any management token can see all other ACL tokens, it doesn't really make a difference which. That `ACL not found` error makes it seem like the `acl_replication_token` isn't valid, so maybe you need to create that with /v1/acl/create?

**Comment by cliff-ops** [comment]
HI @slackpad, thank you for clarifying the about the management token, that makes sense.
I created a fresh management token and I found the following:

"failed to sync ACL changes: ACL rule compilation failed: Failed to parse ACL rules: key 'key acltest' expected start of object ('{') or assignment ('=')

That must have been buffered for some time since it wasn't present when I initially commented here. As soon as I deleted that key sync started working for me. 

Just to clarify am I still bounded by the TTL's of the cached tokens in the event of a network partition correct? Do we still need to increase the TTLs on the cached token to account for loss of connectivity to the the ACL datacenter? Previously since using a default deny we would bump the TTLs up to something reasonably high. Is this no longer needed with ACL sync? Its not clear from the docs how the interaction of these three related directives relate:

acl_replication_token: "xxxxx-xxxxx-xxxxx-xxxxx"
"acl_down_policy": "extend-cache
"acl_ttl": "300s"

**Comment by slackpad** [comment]
There's some subtle stuff with the TTLs that was tricky to explain :-) With ACL replication you can be less sensitive to the TTL setting in the ACL datacenter. Even if it gets bumped from cache, if there's a partition and replication is turned on and `extend-cache` set, then it will be paged into cache from the replicated ACL data thats available locally now. In that case, the local datacenter's TTL setting will set the cache lifetime of those paged-in entries. After the ACL datacenter comes back up, it will take that TTL before any items in the cache from replicated data to get kicked out and re-fetched from the ACL datacenter.

**Comment by cliff-ops** [comment]
I see. So during a partition when the TTLs expire it will just be refreshed from the local sync'd copy until the ACL datacenter Consul server is again reachable? Is that correct?

**Comment by slackpad** [comment]
Actually during a partition with `extend-cache` it doesn't respect the TTLs at all, so this mainly applies to things that weren't in the cache before the partition, or things that get evicted from the cache during the partition due to a fixed cache size.

**Comment by cliff-ops** [comment]
That sounds contrary  to the documentation though:

https://www.consul.io/docs/internals/acl.html

"If there's a partition or other outage affecting the authoritative datacenter, and the acl_down_policy is set to "extend-cache", tokens will be resolved during the outage using the replicated set of ACLs. An ACL replication status endpoint is available to monitor the health of the replication process.

Locally-resolved ACLs will be cached using the acl_ttl setting of the non-authoritative datacenter, so these entries may persist in the cache for up to the TTL, even after the authoritative datacenter comes back online."

**Comment by slackpad** [comment]
> That sounds as though the TTLs are respected and that when they expire if the network partition is still in effect it will refresh from the local ACL copy which tops the TTLs back up no?

Ah you are right - sorry I misremembered that. Looking through the code again it will expire based on the TTL and re-up the cache using the replicated data. Any original stuff from the ACL datacenter will expire and get replaced from the local replica, and anything that wasn't in the cache before the partition will come from the local replica. As TTLs expire, the local TTL setting will determine how things re-up, and how long something cached from the local replica can live after the partition heals.

**Comment by cliff-ops** [comment]
Ok this makes sense. When you say:

"As TTLs expire, the local TTL setting will determine how things re-up, "

The local replica can continuously re-up the TTLs on the expired token from the local replica as long as the ACL datacenter is unreachable though right? In other words its not a one time operation?

Thanks

**Comment by slackpad** [comment]
> The local replica can continuously re-up the TTLs on the expired token from the local replica as long as the ACL datacenter is unreachable though right? In other words its not a one time operation?

That's correct - there's no time limit for an outage if you've got replication set up and activated with `extend-cache`.

**Comment by cliff-ops** [comment]
Excellent. This is a great feature. Thanks for taking the time time to answer my questions. I appreciate it.
