### ISSUE TITLE
UI: "action bar" for manual node/service management

### ISSUE THREAD

**Issue by spro** [hashicorp/consul#257]
I've found myself wanting to deregister services from within the UI more than a few times, especially while debugging a new setup. @pearkes pointed out that an "action bar" would be a good way to fit these sorts of actions so I've mocked up the simplest possible version of what that could look like:
![2014-07-22-122231_517x391_scrot](https://cloud.githubusercontent.com/assets/211613/3663708/c0fb873a-11d5-11e4-8682-599aff34dc90.png)

Is this something you want? If so, what actions should be supported? Here's what I'm thinking so far:

Nodes:
* Deregister
* Register *?*

Services:
* Deregister
* Register *?*

Checks:
* Mark passing
* Mark warning
* Mark critical
* Register *?*

**Comment by pearkes** [comment]
Looks like we got a deregister button in #379. Going to say this is fixed in the short term, though there may still be room for an action bar like thing.
