### ISSUE TITLE
SSL certificate reload without restart

### ISSUE THREAD

**Issue by Afterglow** [hashicorp/consul#2584]
I posted on the google groups and was directed here so here goes.

We use anchor by the openstack project to issue some of our remote nodes not within our own network with short lived SSL certificates. The result is that we have to restart consul frequently to pick up the new certificates. Is there any means to reload the SSL certificates without restarting consul completely? If not would this be considered as a feature request?

https://groups.google.com/forum/#!msg/consul-tool/SdHt8UJ8b_g/RpVnnGt5AAAJ

thanks!
Paul

**Comment by tniswong** [comment]
Would very much like to see this implemented ala reloadable configuration. I.e. Send a SIGHUP to reload TLS Cert/Key/CA's.

This enables automated cert rotation sans downtime, an effective compliment to the Autopilot Pattern via ContainerPilot.

**Comment by freman** [comment]
This explains why our vault + consul hasn't been behaving.

**Comment by shayangz** [comment]
For what is worth, I would vote for the timing/priority of this work being pushed forward. Full restart is very disruptive.

**Comment by freman** [comment]
Yeh that'd be nice, my confusion came from the fact that I'd written a nice tool to manage the certificates and had figured out the vault reload process and copied that to consul figuring "this is all hashicorp, they'd do it the same way" then 30 days later all my stuff stops working :(

Ok *googles* oh, it's consul reload... tweak all the things... 30 days later, same issue.

More *googles* oh, it's not currently possible without restart... this conversation :(

**Comment by tniswong** [comment]
Yeah. We worked around it by scripting a coordinated cluster failure/outage recovery...

https://www.consul.io/docs/guides/outage.html

**Comment by shayangz** [comment]
@slackpad: now that 0.9 is out the door do you think this can get on the roadmap?

**Comment by SoMuchToGrok** [comment]
This feature is especially important when using nomad with TLS. Basically a must-have for me at this point.

Currently, the built-in consul -> nomad health check is over HTTPS. When root CAs are rolled, the consul agent will also need a restart in order to refresh its trust anchors. Without the consul trust anchors being refreshed, the nomad health checks will fail.

Nomad is currently implementing this:
https://github.com/hashicorp/nomad/pull/3479

**Comment by slackpad** [comment]
We shall draft off of Nomad's work for this one :-)

**Comment by tniswong** [comment]
No love for this one? :(

**Comment by freman** [comment]
Literally causing us to abandon vault and ssl

**Comment by l33t0** [comment]
Any updates?

**Comment by freman** [comment]
Pretty sure I could have forked and patched it by now... just sayin...

**Comment by banks** [comment]
@freman PRs are welcome! :)

We're aware this is high on people's wishlist, as always we have a juggling act with various prorities. Thanks for your patience.

**Comment by SoMuchToGrok** [comment]
To add some more input to this ticket, I think it would be incredibly useful if this was extended to include refreshing the root CA as well, not just the server certificate.

**Comment by patelpu94** [comment]
Any update on this?

**Comment by jwasinger** [comment]
Is anybody working on this?  I can take it on.

**Comment by tristanmorgan** [comment]
The PR by @akshayganeshen is working well in a test environment for me but I need an Enterprise (pro) release of this for my client.

**Comment by banks** [comment]
Thanks again for the patience folks. We are still working towards this as a TODO item.

I hope my [comment on the PR](https://github.com/hashicorp/consul/pull/4204#issuecomment-421317837) is helpful context.

**Comment by kikitux** [comment]
@tristanmorgan enterprise feedback have different channels, please feel free to reach me at alvaro hashicorp.com

**Comment by lmb** [comment]
We're currently evaluating Consul, and this issue has popped up. We use short-ish lived certificates and can't afford to refresh these manually.

What are the chances of Step 1 in the comment from @banks happening without the fancier stuff?

**Comment by banks** [comment]
@lmb the plans around TLS are being worked on now. Rebuilding this one way while in the misdst of designing a better overall solution doesn't seem like the wisest use of the resources we have but the next major release cycle has the whole TLS setup firmly in it's sights and will result in _at least_ basic reloading working in a way that is compatible with our future plans -- hopefully more!

**Comment by i0rek** [comment]
We merged support for reloading TLS config into master: https://github.com/hashicorp/consul/pull/5419.
