### ISSUE TITLE
Question: security code review

### ISSUE THREAD

**Issue by chiel1980** [hashicorp/consul#2586]
Hi,

Did you guys ever did a security review on your code by an external party?
And if yes, are you willing to share these results or can we find it back in some specifc commits?
We are scheduling a code review by an external security company and if you want, we would like to share these results with you/the community as feedback to improve the product (if anything has been found) :)

Michiel

**Comment by slackpad** [comment]
Hi @chiel1980 I don't know of any 3rd party security review that we have to share. We do ask if you can please give us a first look privately via security@hashicorp.com so we can review the findings and address any critical issues before they are publicly disclosed. Thanks!
