### ISSUE TITLE
Script check for external service

### ISSUE THREAD

**Issue by r04r** [hashicorp/consul#259]
The documentation [mentions](http://www.consul.io/docs/guides/external.html) that for external services you have to access `catalog/register` directly, but this cannot register script checks. How can one register a script check for an external service? So far all my attempts result in the check being registered with the main node, and not the node for the external service.

**Comment by raboof** [comment]
@jmcarbo in consul-externalservice, "All checks are defined and run from the consul node attached to the running consul-externalservice instance". How does that compare to registering the external service with its health check to that node?

**Comment by mterron** [comment]
I think @raboof  point is right. If the consul-externalservice node goes down all the external services go down too.
I understand the reasoning for not adding scripted health check for external services, but a TTL would solve most of this problems cleanly. I could register an external service with a TTL and then it is my responsibility to do the checking and update consul with the result.

**Comment by raboof** [comment]
My plan now is to write a small component (sort of like consul-externalservice) that performs and registers a check directly to the registry, sort of acting as an "agent-lite" (not joining the serf cluster itself)... but it's not a big priority for us right now, so don't hold your breath ;).

**Comment by sethvargo** [comment]
Hey all,

As mentioned, this is outside of Consul's architecture and is better done by an external tool that uses consul to coordinate. Thanks!
