### ISSUE TITLE
Log message for new consul version does not match other patterns for logging

### ISSUE THREAD

**Issue by majormoses** [hashicorp/consul#2601]
### `consul info` for both Client and Server
Client:
```
$ /opt/consul/0.7.0/consul version
Consul v0.7.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

Server:
```
$ /opt/consul/0.7.0/consul version
Consul v0.7.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

### Operating system and Environment details
Ubuntu 14.04 LTS

### Description of the Issue (and unexpected/desired result)
When you have a node that is not running the latest code it is logged in /var/log/upstart/consul.log by default. This log message `==> Newer Consul version available: 0.7.1 (currently running: 0.7.0)` does not include the typical log format `DATE TIME [LOG_LEVEL] COMPONENT: MESSAGE` 

### Reproduction steps
spin up consul with an older version than latest.

## Code in question
I am not very proficient in go so apologies in advance:

This is the line of code that emits the message: https://github.com/hashicorp/consul/blob/04f8e5adc03d5bf688b9ff954e7bf0b1a8324f9b/command/agent/command.go#L597

This feels like it should be writing it out correctly:
https://github.com/hashicorp/consul/blob/04f8e5adc03d5bf688b9ff954e7bf0b1a8324f9b/command/agent/command.go#L599-L606

Am I missing something obvious?

**Comment by slackpad** [comment]
Hi @majormoses this is part of the init logging, please see #1446.
