### ISSUE TITLE
Add AWS policy specifics to docs

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2602]
We should have specific guidance on what IAM rights are required for our AWS features:

* EC2 auto join
* Consul snapshot agent

It would be good to list the specific IAM rights required and possibly a policy example snippet for these.

**Comment by moofish32** [comment]
For EC2 auto join, based on this line of [code](https://github.com/hashicorp/consul/blob/master/command/agent/command.go#L489)

This is the following Terraform snippet I have been using:

```hcl
data "aws_iam_policy_document" "describe_ec2" {
  statement {
    sid = "1" 
    actions = [ "ec2:DescribeInstances" ],
    effect = "Allow",
    resources = [ "*" ]
  }
}

data "aws_iam_policy_document" "assume_role" {
  statement {
    actions = [ "sts:AssumeRole" ]
    effect = "Allow",
    principals = {
      type = "Service"
      identifiers =  [ "ec2.amazonaws.com" ] 
    }
  }
}

resource "aws_iam_instance_profile" "consul_profile" {
  name_prefix = "consul_profile-"
  roles       = ["${aws_iam_role.consul_server.name}"]
}

resource "aws_iam_role" "consul_server" {
  name_prefix        = "consul_server-"
  path               = "/"
  assume_role_policy = "${data.aws_iam_policy_document.assume_role.json}"
}

resource "aws_iam_role_policy" "describe_ec2" {
  name   = "describe-instances"
  role   = "${aws_iam_role.consul_server.id}"
  policy = "${data.aws_iam_policy_document.describe_ec2.json}"
}
```

You may need to add some lifecycle settings depending on your update process.

**Comment by jkirschner-hashicorp** [comment]
Example IAM policy document for Consul snapshot agent was added in PR #4758 and can be found on [the snapshot agent command docs page](https://www.consul.io/commands/snapshot/agent#s3-required-permissions).

**Comment by jkirschner-hashicorp** [comment]
EC2 auto join permissions were added in [this commit from Jan 2017](https://github.com/hashicorp/consul/commit/748e308ac462d342764c4958499d672cd6dc0162) and can be found on the [cloud auto-join docs page](https://www.consul.io/docs/install/cloud-auto-join#authentication-precedence).
