### ISSUE TITLE
Consul k/v long key name.

### ISSUE THREAD

**Issue by MAS150MD200** [hashicorp/consul#2606]
Server: consul_0.7.1_linux_amd64

Server:
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 1
	services = 3
build:
	prerelease = 
	revision = 'a9455cd
	version = 0.7.1
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 10.101.12.6:8300
	server = true
raft:
	applied_index = 182212
	commit_index = 182212
	fsm_pending = 0
	last_contact = never
	last_log_index = 182212
	last_log_term = 3
	last_snapshot_index = 180323
	last_snapshot_term = 3
	latest_configuration = [{Suffrage:Voter ID:10.101.12.6:8300 Address:10.101.12.6:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 3
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 57
	max_procs = 4
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 1
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1

### Operating system and Environment details
OS - Centos 6.5

### Description of the Issue (and unexpected/desired result)
I'm using Consul as a key/value store and found out that Consul k/v GUI unable to handle long key names. I use Google Chrome browser. You can see my issue on this screen capture: 
https://yadi.sk/i/IDW5ugKX34AJmz

### Reproduction steps
Just try to add key with following name:
"cache.command.cache-suspended.accounts-GetMultipleCommand.execution.isolation.semaphore.maxConcurrentRequests"

**Comment by slackpad** [comment]
Hi @MAS150MD200 thanks for opening an issue. Closing this as a dup of https://github.com/hashicorp/consul/issues/1769.
