### ISSUE TITLE
consul UI is not working after changing consulHost in index.html

### ISSUE THREAD

**Issue by rightzang** [hashicorp/consul#2609]
Hello.
consul UI setted on consul server is working well.
However, For some reason, I want to run another webserver and I thought it's possible to divide consul UI and consul server after seeing consulHost variable in index.html(consul UI)
But, After setting consulHost="consul Server address", consul UI webpage just shows error page after progress animation.
How can I fix this issue ? How can I do debugging ?
surely, I know about HTTPProxy or Tunneling. 
But, I don't want to use it. I want to change consulHost variable dynamically.

Please help me. Thanks in advance.

**Comment by rightzang** [comment]
I think ember is not working well.
I can see console log : GET 
XHR 
http://xxx.xxx.xxx.xxx:8500/v1/catalog/datacenters
but I can see any response value.
But, When I try to connect to same consul server via curl . it works well.

**Comment by wzs1234566** [comment]
I'm having the same issue. Could you share with me how you resolved this issue?
