### ISSUE TITLE
X-Consul-Index is not independent for each service for /v1/health/service/ http api

### ISSUE THREAD

**Issue by thomassun** [hashicorp/consul#2616]
### `consul version` for both Client and Server
Client: v0.7.1
Server: v0.7.1

### `consul info` for both Client and Server
Client:
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease = 
	revision = 'a9455cd
	version = 0.7.1
consul:
	known_servers = 4
	server = false
runtime:
	arch = amd64
	cpu_count = 12
	goroutines = 38
	max_procs = 12
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 27
	members = 7
	query_queue = 0
	query_time = 1

Server:
agent:
		check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = 'a9455cd
	version = 0.7.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.0.16.44:8300
	server = true
raft:
	applied_index = 98365
	commit_index = 98365
	fsm_pending = 0
	last_contact = 0
	last_log_index = 98365
	last_log_term = 39
	last_snapshot_index = 90251
	last_snapshot_term = 39
	latest_configuration = [{Suffrage:Voter ID:10.0.16.44:8300 Address:10.0.16.44:8300} {Suffrage:Voter ID:10.0.1.18:8300 Address:10.0.1.18:8300} {Suffrage:Voter ID:10.0.1.19:8300 Address:10.0.1.19:8300} {Suffrage:Voter ID:10.0.2.188:8300 Address:10.0.2.188:8300} {Suffrage:Voter ID:10.0.0.22:8300 Address:10.0.0.22:8300}]
	latest_configuration_index = 19453
	num_peers = 4
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 39
runtime:
	arch = amd64
	cpu_count = 16
	goroutines = 154
	max_procs = 16
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 27
	members = 7
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1

### Operating system and Environment details
Centos 7.2 with kernel 3.10.0-327.el7.x86_64
### Description of the Issue (and unexpected/desired result)
when do block query via http api by providing query parameter "index" to watch one service in /v1/health/service/, any other service updates will get the query exits with same value, I expect each service may have it's own index to indicate if itself has been updated.  

### Reproduction steps
issue command in a terminal: curl /v1/health/service/myservice?index=<index no>
reload a consul agent with no relevant to mservice,  the curl block query exit with a new index number returned in response head

**Comment by slackpad** [comment]
Hi @thomassun thanks for opening an issue. This is a dup of https://github.com/hashicorp/consul/issues/1244 so linking and closing this one.
