### ISSUE TITLE
Consul UI freezes and gives Ember error when selecting a specific Node 

### ISSUE THREAD

**Issue by stenio123** [hashicorp/consul#2619]
### `consul version` for both Client and Server
Client: 0.7.2
Server: 0.7.2

(same behavior happened with 0.7.1)

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 'a9afa0c
	version = 0.7.2
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 45
	max_procs = 2
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 19
	members = 6
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 'a9afa0c
	version = 0.7.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.228.35.76:8300
	server = true
raft:
	applied_index = 336
	commit_index = 336
	fsm_pending = 0
	last_contact = 25.157299ms
	last_log_index = 336
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:10.228.32.92:8300 Address:10.228.32.92:8300} {Suffrage:Voter ID:10.228.35.76:8300 Address:10.228.35.76:8300} {Suffrage:Voter ID:10.228.34.182:8300 Address:10.228.34.182:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 82
	max_procs = 2
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 19
	members = 6
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Amazon Linux AMI release 2016.09 (based on RHEL 5.x and 6) 

### Description of the Issue (and unexpected/desired result)
Consul cluster with 3 nodes
Mongo replicaset with 3 nodes

When I open the Consul UI, I can select the services without a problem, and it shows the Health checks:
![screen shot 2016-12-28 at 10 52 35 pm](https://cloud.githubusercontent.com/assets/3443868/21537014/6931d958-cd50-11e6-8f16-d28cc8b2e3f3.png)

However when I select a specific node, the UI freezes:
![screen shot 2016-12-28 at 10 53 24 pm](https://cloud.githubusercontent.com/assets/3443868/21537019/7dd82952-cd50-11e6-8db6-5d7f40741c68.png)

When opening Chrome dev tools, I see this error:
![screen shot 2016-12-28 at 10 54 49 pm](https://cloud.githubusercontent.com/assets/3443868/21537024/aedeb6e2-cd50-11e6-8ba1-15a73d34063a.png)

Note that I can reach the API endpoint /v1/catalog/node/<node>:
![screen shot 2016-12-28 at 10 55 40 pm](https://cloud.githubusercontent.com/assets/3443868/21537032/cb1a3db8-cd50-11e6-9a5e-0f1e567e2afd.png)

This behavior happens if I use **atlas_join** or if I use **retry_join_ec2**.
**If I switch to version 0.6.2 using atlas_join it works without issues**.
### Reproduction steps
Config file for server:
```
{
  "bootstrap_expect": 3,
  "client_addr": "0.0.0.0",
  "data_dir": "/var/lib/consul",
  "enable_syslog": true,
  "log_level": "DEBUG",
  "node_name": "consul-i-0ada6114c8d15aca7-stenio",
  "performance": {
    "raft_multiplier": 1
  },
  "ports": {
    "dns": 8600,
    "http": 8500,
    "rpc": 8400,
    "serf_lan": 8301,
    "serf_wan": 8302,
    "server": 8300
  },
  "retry_join_ec2": {
    "tag_key": "Consul-Membership",
    "tag_value": "uk-dev-stenio"
  },
  "server": true,
  "statsd_addr": "127.0.0.1:8125",
  "ui": true,
  "verify_incoming": false,
  "verify_outgoing": false
}
```
Executed by initctl as:
`exec(*["/opt/consul/0.7.1/consul", "agent", "-config-file=/etc/consul/consul.json", "-config-dir=/etc/consul/conf.d"])`

Config file for client:

```
{
  "client_addr": "0.0.0.0",
  "data_dir": "/var/lib/consul",
  "enable_syslog": true,
  "log_level": "DEBUG",
  "node_name": "mongo-i-0889ee9c7bb38e8a1-stenio",
  "ports": {
    "dns": 8600,
    "http": 8500,
    "rpc": 8400,
    "serf_lan": 8301,
    "serf_wan": 8302,
    "server": 8300
  },
  "retry_join_ec2": {
    "tag_key": "Consul-Membership",
    "tag_value": "uk-dev-stenio"
  },
  "server": false,
  "verify_incoming": false,
  "verify_outgoing": false
}
```

Executed as:
`exec(*["/opt/consul/0.7.1/consul", "agent", "-config-file=/etc/consul/consul.json", "-config-dir=/etc/consul/conf.d"])`

### Log Fragments or Link to [gist](https://gist.github.com/)

Client:
https://gist.github.com/stenio123/710159a8e26efd2b23f7e22b01982b9a

Server:
https://gist.github.com/stenio123/f0196e0305cbb50d4fb01be0903a7270

**Comment by slackpad** [comment]
Hi @stenio123 this is almost always a cached javascript issue. If you clear your cache or do a shift-reload it should fix it. Please ping back if that didn't fix it.
