### ISSUE TITLE
Support standby servers

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#262]
Based on conversations from the mailing list, it would be interesting to support stand by servers. Basically a "server count" would be targeted, and clients could specify a special "standby" flag. If the number of available servers drops below the target, a healthy client could be promoted to server standing.

This would only happen in the happy path: graceful leaves with a quorum available. Doing so under duress would open up safety issues.

**Comment by ryanuber** [comment]
@armon is this partially solved by the new `consul lock -n` semaphore?

**Comment by armon** [comment]
Not quite, since it doesn't allow a client to "upgrade" to a server.

**Comment by slackpad** [comment]
Done - https://www.consul.io/docs/guides/autopilot.html#redundancy-zones.
