### ISSUE TITLE
 error "output: /C: /C: is a directory" on windows

### ISSUE THREAD

**Issue by 756445638** [hashicorp/consul#2622]
I have this error on windows.
######################################################
 2016/12/30 14:18:25 [DEBUG] agent: Node info in sync
    2016/12/30 14:18:26 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:26 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:27 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:27 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:28 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:28 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:29 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:29 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:30 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:30 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:31 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:31 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:32 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:32 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:33 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:33 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:34 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
    2016/12/30 14:18:34 [WARN] agent: Check 'service:agent' is now critical
    2016/12/30 14:18:36 [DEBUG] agent: check 'service:agent' script 'ping baidu.com' output: /C: /C: is a directory
######################################################

**Comment by slackpad** [comment]
Hi @756445638 that looks like error output from your script itself. Please check your script and make sure it runs on its own - there's probably an issue there. Hope that helps!

**Comment by 756445638** [comment]
ok.I will try later!!

**Comment by dave-johnson** [comment]
I get the same error doing a "consul exec echo test", but I only get the error on my local machine.   The other two are running in a VM.   All boxes are running Windows 10.

> $ consul exec echo test
    DJohnson0916: /C: /C: is a directory
    DJohnson0916:
==> DJohnson0916: finished with exit code 126
    Win10-001: test
    Win10-001:
==> Win10-001: finished with exit code 0
    Win10-002: test
    Win10-002:
==> Win10-002: finished with exit code 0
3 / 3 node(s) completed / acknowledged

**Comment by slackpad** [comment]
Hmm - Consul pulls in the `SHELL` environment variable. Is that set differently on your boxes?

**Comment by dave-johnson** [comment]
Well, this is embarrassing.   I had my "consul agent" command in a .sh file and running powershell on my local box.   On the VM boxes the command is in a .bat file and running it from a command prompt.   If I run my the .bat on my local box, then "consul exec" returns the correct results on all boxes.    Where is the emoji for "hide my face in shame"?

If it helps, I don't have a SHELL environment variable on any of the boxes.   If I open a "git bash" prompt, then SHELL is "/usr/bin/bash"

**Comment by slackpad** [comment]
No worries - thanks for the update!
