### ISSUE TITLE
Where are ACL Tokens in ACL Data Center

### ISSUE THREAD

**Issue by huyjack178** [hashicorp/consul#2623]
Hi, after reading ACL, I was confused about where ACL Tokens are stored in ACL Data Center, in any Data Center or somewhere? Are there any replications between secured servers in ACL Data Center?

**Comment by huyjack178** [comment]
Anyone can answer me?

**Comment by slackpad** [comment]
Hi @huyjack178 the canonical set of ACL tokens are stored on the Consul servers in the `acl_datacenter`, similar to how KV values are stored in their state store, with changes to ACLs going through Raft.

If you enable https://www.consul.io/docs/internals/acl.html#replication, then Consul servers outside the `acl_datacenter` keep a replicated set of ACL tokens in their state stores which can be used in the event of an outage or partition from the `acl_datacenter`. Hope that helps!
