### ISSUE TITLE
Can a service have tens of thousands of checks？

### ISSUE THREAD

**Issue by celeskyking** [hashicorp/consul#2626]
hi,
I use the same name registration service tens of thousands of TTL service, but when the TTL update is always blocked, after a period of time will return to the content: "CheckID xxxxx does not have associated TTL" and the 500, Is there a problem with my scene?

**Comment by slackpad** [comment]
Hi @celseyking I don't think this is enough information to figure out what's happening. Can you share some details about your Consul and some logs from when this happens? There's no inherent limit for checks.

**Comment by celeskyking** [comment]
Hi @slackpad  
I'm sorry, I think it is my personal use of the error. We cluster more than 10,000 nodes, and the cluster nodes will often change, resulting in often registered service, in the DeregisterCriticalServiceAfter function before we do not deregister the service. The program we run for about a year, and now the situation is to request the registration service, the request timeout, simply traced the reason is because the request time locked for too long, I moved to a new cluster There is no such a situation.
thanks.

**Comment by slackpad** [comment]
Thanks for the update.
