### ISSUE TITLE
UI: Consul and UI Metadata

### ISSUE THREAD

**Issue by mtchavez** [hashicorp/consul#263]
Does it make sense to display some metadata on the currently running versions of consul and the UI version? Thinking the output from `consul info` might be useful as well somewhere in the UI per consul node.

Further Consul info per agent would be a nice to have ie. what is shown in the `consul members` output. Could be useful to know that agent's `build` and `protocol` from that output.

If there is a consensus on a any of this I would be glad to implement these.

**Comment by sethvargo** [comment]
Hey all,

We are actively searching for a full time engineer to own the Consul UI. If you are interested, apply here: https://www.hashicorp.com/jobs/
