### ISSUE TITLE
Serf keyring operations write to disk in Consul dev mode

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#2630]
Server version: `Consul v0.7.2`
Client version: N/A

### Operating system and Environment details
Windows 8.1, development done locally

### Description of the Issue (and unexpected/desired result)
I ran into the following issue while implementing the `/v1/operator/keyring` API for my Consul.NET API - it seems that using the serf keyring calls in dev mode writes to the disk, which breaks testing in new and fun ways.

Expected result: Restarting the server in dev mode deletes all encryption keys except that which is specified in the config file.

Actual result: Serf writes installed encryption keys to a local directory which is preserved in dev mode.

### Reproduction steps
I'm running Consul as follows: `consul.exe agent -dev -config-file test_config.json` and test_config.json contains the following:

```json
{
    "log_level": "TRACE",
    "bind_addr": "127.0.0.1",
    "server": true,
    "bootstrap": true,
    "acl_datacenter": "dc1",
    "acl_master_token": "yep",
    "acl_default_policy": "allow",
    "encrypt": "OSvH5y8K4Lc9qaof5YUpwg=="
}
```

If I start Consul with the command above and in another prompt run `consul.exe  keyring -list`, I get, as expected:

```
==> Gathering installed encryption keys...
==> Done!

WAN:
  OSvH5y8K4Lc9qaof5YUpwg== [1/1]

dc1 (LAN):
  OSvH5y8K4Lc9qaof5YUpwg== [1/1]
```

If I add another one, e.g. `consul.exe  keyring -install 7a9OTTuJHbTdatQ/pRlw2g==` I get, as expected:

```
==> Installing new gossip encryption key...
==> Done!
```

However, this creates a `./serf` directory with `local.keyring` and `remote.keyring` in it.

If I restart the server, which, as a reminder _is in Dev mode_ so it doesn't write to disk or keep state, and then do `consul.exe  keyring -list` I get:

```
==> Gathering installed encryption keys...
==> Done!

WAN:
  OSvH5y8K4Lc9qaof5YUpwg== [1/1]
  7a9OTTuJHbTdatQ/pRlw2g== [1/1]

dc1 (LAN):
  OSvH5y8K4Lc9qaof5YUpwg== [1/1]
  7a9OTTuJHbTdatQ/pRlw2g== [1/1]
```

**Comment by mckennajones** [comment]
@slackpad Since dev mode is not supposed to write to disk at all, should the `keyring -install` command even be supported in dev mode?

**Comment by slackpad** [comment]
Yeah that should probably just fail outright in dev mode.
