### ISSUE TITLE
consul session have renewed in TTL, But session is disappear

### ISSUE THREAD

**Issue by linking12** [hashicorp/consul#2648]
consul version:0.7
consul client: java consul-api-1.2.1;
The session ttl is 180s, and i renew session by sessionId in 2s
but session also disappeared.
can someone help me?

**Comment by linking12** [comment]
consul verson is 0.7

**Comment by slackpad** [comment]
Hi @linking12 sessions will expire if the TTL is exceeded or if any of the health checks they are tied to fail - it sounds like you are servicing the TTL in time - can you double check any health checks? By default it will be tied to the `serfHealth` check for the node that created the session.

**Comment by linking12** [comment]
@slackpad  I do not have any health check code in my program
I think use renew session is enough. is that true? as you say, it will be tied to the serfHealth check for the node that created the session.
I think selfHealth checked will be success, because my consul deployment is server agent and there is no network interrupt

**Comment by linking12** [comment]
i have found the reason. 
the reason is when i request rest api to consul return error. and make next TTL scheduler is failed.
this is my fault. thanks @slackpad
