### ISSUE TITLE
how to make the server perform the health check

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2662]
I use the /v1/catalog/register to register service with a non-existence node in the post body, so that the registration won't be removed by the Anti-Entropy. but in this way, we lose the health check. does the server support performing health check?

**Comment by slackpad** [comment]
Hi @hehailong5 Consul doesn't have a way for servers to perform health checks for a node that's registered manually in the catalog. Consul's design puts all health checking with the agent, so this would be a fairly large change to Consul (and would have scalability concerns).

The https://github.com/hashicorp/consul/issues/259 issue has some thoughts on a solution for this via an external process. If such a process had built-in support for HA using Consul's leader election in the KV store then it could be made pretty reliable.
