### ISSUE TITLE
Consul keeps making RPC connections to server rejoined as client

### ISSUE THREAD

**Issue by duijf** [hashicorp/consul#2670]
### `consul version` for both Client and Server
Client: `v0.7.1`
Server: `v0.7.1`

### `consul info` for both Client and Server

Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 3
build:
        prerelease =
        revision = 'a9455cd
        version = 0.7.1
consul:
        known_servers = 5
        server = false
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 44
        max_procs = 2
        os = linux
        version = go1.7.3
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 187
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 95
        members = 19
        query_queue = 0
        query_time = 1
```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 2
build:
        prerelease =
        revision = 'a9455cd
        version = 0.7.1
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 192.168.1.13:8300
        server = true
raft:
        applied_index = 6638918
        commit_index = 6638918
        fsm_pending = 0
        last_contact = 0
        last_log_index = 6638918
        last_log_term = 4584
        last_snapshot_index = 6632387
        last_snapshot_term = 4584
        latest_configuration = [{Suffrage:Voter ID:192.168.1.1:8300 Address:192.168.1.1:8300} {Suffrage:Voter ID:192.168.1.8:8300 Address:192.168.1.8:8300} {Suffrage:Voter ID:192.168.1.13:8300 Address:192.168.1.13:8300} {Suffrage:Voter ID:192.168.1.6:8300 Address:192.168.1.6:8300} {Suffrage:Voter ID:192.168.1.9:8300 Address:192.168.1.9:8300}]
        latest_configuration_index = 6635748
        num_peers = 4
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 4584
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 138
        max_procs = 2
        os = linux
        version = go1.7.3
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 187
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 95
        members = 19
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 3
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

Setup has 19 nodes; 5 of them are servers, the rest function as clients. There is a mix of Ubuntu 16.04 and 14.04 as both clients and servers.

### Description of the Issue (and unexpected/desired result)

After removing a server node and rejoining it as a client, error messages end up in the logs of other client nodes in the cluster.

### Reproduction steps

1. Create a consul cluster with 5 servers and a number of clients
2. Issue a `consul leave` command to one of the servers (in our case `192.168.1.2`). Also `rm -r /var/log/consul`
3. Start a consul agent as a server on a *different, never before seen* node, join it to the cluster. (This might not be needed, but it is what we did)
4. Start the consul agent on `192.168.1.2`, this time as a client.
5. Errors fill the logs of the other clients, see below

```
2017/01/24 11:55:46 [ERR] consul: RPC failed to server 192.168.1.2:8300: rpc error: failed to get conn: dial tcp 192.168.1.2:8300: getsockopt: connection refused
2017/01/24 11:55:46 [ERR] agent: coordinate update error: rpc error: failed to get conn: dial tcp 192.168.1.2:8300: getsockopt: connection refused
```

Another type of error that comes up:

```
2017/01/24 11:54:25 [ERR] consul: RPC failed to server 192.168.1.2:8300: rpc error: failed to get conn: dial tcp 192.168.1.2:8300: getsockopt: connection refused
2017/01/24 11:54:25 [ERR] http: Request GET /v1/status/peers, error: rpc error: failed to get conn: dial tcp 192.168.1.2:8300: getsockopt: connection refused from=127.0.0.1:57769
```

It seems that Consul agents are still trying to connect to the node's RPC port. This shouldn't happen, since it is running as a client (and the other clients are aware of this). Hypothesis: it has to do with long running loops [like these](https://github.com/hashicorp/consul/blob/acbc2289a3c2ae9dd08d9d8526d6f533c99d7a54/command/agent/agent.go#L891) not updating the servers they connect to.

I haven't provided more detailed logging, since it the rest of the log output doesn't seem related to this issue. Please let me know if you require more information.

**Comment by slackpad** [comment]
Hi @duijf thanks for opening an issue. Those long running loops use a method under the hood that actively chooses new servers, and stays up-to-date as servers come and go, so that doesn't seem like the issue here.

Do you have any logs from the server when you did the `consul leave`? If the leave didn't work correctly I could maybe see something like this happening.

**Comment by duijf** [comment]
Hey @slackpad, thanks for the response. 

I don't have access to the logs from that exact server, since we were re-imaging it. Here is the log from another consul server in the cluster:

```
2017/01/23 14:15:49 [INFO] serf: EventMemberLeave: frontend 192.168.1.2
2017/01/23 14:15:49 [INFO] consul: Removing LAN server frontend (Addr: tcp/192.168.1.2:8300) (DC: dc 1)
2017/01/23 14:15:49 [INFO] raft: Updating configuration with RemoveServer (192.168.1.2:8300, ) to [{ Suffrage:Voter ID:192.168.1.1:8300 Address:192.168.1.1:8300} {Suffrage:Voter ID:192.168.1.8:8300 Address :192.168.1.8:8300} {Suffrage:Voter ID:192.168.1.13:8300 Address:192.168.1.13:8300} {Suffrage:Voter ID:19 2.168.1.6:8300 Address:192.168.1.6:8300}]
2017/01/23 14:15:49 [INFO] raft: Removed peer 192.168.1.2:8300, stopping replication after 6617741
2017/01/23 14:15:49 [INFO] raft: aborting pipeline replication to peer {Voter 192.168.1.2:8300 192.1 68.1.2:8300}
2017/01/23 14:15:49 [INFO] consul: member 'frontend' left, deregistering
2017/01/23 14:15:55 [WARN] raft: Rejecting vote request from 192.168.1.2:8300 since we have a leader : 192.168.1.8:8300
2017/01/23 14:16:03 [WARN] raft: Rejecting vote request from 192.168.1.2:8300 since we have a leader : 192.168.1.8:8300
2017/01/23 14:16:13 [WARN] raft: Rejecting vote request from 192.168.1.2:8300 since we have a leader : 192.168.1.8:8300
2017/01/23 14:16:19 [WARN] raft: Rejecting vote request from 192.168.1.2:8300 since we have a leader : 192.168.1.8:8300
2017/01/23 14:16:28 [WARN] raft: Rejecting vote request from 192.168.1.2:8300 since we have a leader : 192.168.1.8:8300
```

At this point, we shut it down for re-imaging. Do the warnings indicate the leave didn't go as it should have?

**Comment by duijf** [comment]
@slackpad Is there any further info I can provide here? Should I try to reproduce this? Or is that unproductive since you think it was an operator error?

**Comment by slackpad** [comment]
Hi @duijf sorry for the delayed response on this one :-) This is a pretty edge case so it's probably not worth more time chasing this down. We did find a couple places in Serf where we weren't taking on a node's metadata (whether or not you are a server is in the Serf tags) so this also is likely fixed now.
