### ISSUE TITLE
Blocking Query Performance

### ISSUE THREAD

**Issue by huyjack178** [hashicorp/consul#2672]
I heard about Blocking Query very first time when I study Consul. I had just known about web socket to support watching before. I don't know the reason why Consul uses Blocking Query to watch K/V change and doesn't use websocket. Is there any comparison between them, which one is better for network?

**Comment by slackpad** [comment]
Hi @huyjack178 in Consul's case your application makes HTTP requests to the local Consul agent, but that runs internally over a multiplexed TCP connection to one of the Consul servers. Similar to websockets (at least between the Consul agent and the server) there's a bunch of requests flowing over the same connection. The traffic between the application and the local Consul agent is usually over a loopback interface. There's a little more on this discussed on https://github.com/hashicorp/consul/issues/1815. I don't know enough details about websockets to give more info than that, but I hope this helps!

**Comment by huyjack178** [comment]
@slackpad thank for the reply, I have seen that there is only one TCP connection between agent and server. But how about application to agent? Is there many HTTP Request for Blocking Query to watch key/value change?

**Comment by slackpad** [comment]
@huyjack178 yes on the application side it makes a new request each time it sets up a blocking query. That side isn't set up for something like websockets with a persistent connection (other than client libraries keeping HTTP connections open across a few requests kind of thing).
