### ISSUE TITLE
expose node's datacenter in catalog API

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#2686]
Consul v0.7.3

for https://github.com/hashicorp/consul-template/issues/862

Please expose the Node's Datacenter as an attribute in Catalog API responses.  This will make it easier for API consumers (specifically consul-template users) to filter out nodes in the local datacenter when iterating over services or nodes in all datacenters.

**Comment by slackpad** [comment]
Closing as a duplicate of #2713.
