### ISSUE TITLE
[ERR] memberlist: Push/Pull on local nodes using advertised ip after -wan registration

### ISSUE THREAD

**Issue by dhdanno** [hashicorp/consul#2689]
Build: 0.7.3, running in AWS across different regions.

I have 2x datacenters with 3x nodes each. 

I start consul with a bind-address of the local subnet, and an advertise-wan address of the external ip.

I join each group of 3 nodes successfully using their local private ip's.

I then join dc1 to dc2 by telling each node in dc1 to join dc2 with the -wan flag

Everything seems to work fine. all nodes report correctly, local members are aware of each other via private ip, and -wan members are known by their public ip.

But the logs will occasionally say:
```[ERR] memberlist: Push/Pull with nodeX.dcX failed: dial tcp <public_ip>:8302: i/o timeout```

This is because after i've registered node0.dc1 with other nodes in the other datacenter... my local node tries to communicate with its other local nodes using the public ip that was registered... but it should be using the private ip... considering its actually local to it.

Presumably these same queries silently succeed when hitting actually reachable wan addresses...

So, is this a problem? Everything else seems to work fine. Have i configured anything incorrectly or is this a bug?

**Comment by slackpad** [comment]
Hi @dhdanno - do you only see that error for other server nodes within the same datacenter? The local nodes will probe each other on the local network on the WAN side, too, using the public address. It might be that you are only binding to the private interface (seems like you must have a NAT for the WAN communications to be working). Something like https://www.consul.io/docs/agent/options.html#_serf_wan_bind might help here to bind to the public interface instead (though I'm not sure if that'll break with NAT).

**Comment by dhdanno** [comment]
Yes the error only occurs for other server nodes within the same datacenter. And yes, I am only binding to the private address, since this is EC2, the public address is NAT'd.

**Comment by slackpad** [comment]
@dhdanno did setting the `serf_wan_bind` get things working for you?

**Comment by slackpad** [comment]
Closing this out as the `serf_wan_bind` should fix this and we didn't hear back. Please let us know if you still need help.
