### ISSUE TITLE
Consul Health Check Push vs Pull

### ISSUE THREAD

**Issue by mradulmodi** [hashicorp/consul#2693]
I wanted to know what must be an ideal model to preform healthchecks using consul. How is currently consul doing it, I have questions on following lines : 

- Suppose we have a 5 consul server and 100 services registered for health check is the load equally distributed for health check ( 20 services per consul server)
- Are the health check calls to servers asynchronous in nature
- How much should be the ideal load for health check. Let's say if I have only one consul server how many services can I register for health checks
- If I am not wrong current model has Consul server pulling the healthcheck data from servers via a script or HTTP Call. Can we have a push model were servers keep updating there healthcheck status to consul. If so which would be better.

Thanks in advance for the help

**Comment by slackpad** [comment]
Hi @mradulmodi Consul is designed such that you run the Consul agent on each node in the cluster and the agent actually performs the health checks locally, and pushes updates to the Consul servers only when things change. This lets Consul scale to 10s of thousands of nodes in a cluster without having to have the servers need to scale to actually perform all those health checks. When you query Consul for the health status of a service, that query is routed to the Consul servers which give a consistent view based on the latest updates they have gotten from the agent. There's a video that talks about this in detail - https://www.youtube.com/watch?v=tzk2HaOZ5nY. Hope that helps!
