### ISSUE TITLE
Consul Download Page Links 

### ISSUE THREAD

**Issue by Deric4** [hashicorp/consul#2701]
Not sure if this a browser issue or not, but  right clicking and selecting "copy link address" the link addresses for downloads include an unexpected parameter. 

[https://releases.hashicorp.com/consul/0.7.3/consul_0.7.3_linux_amd64.zip?_ga=1.155656443.1500592528.1473795963](https://releases.hashicorp.com/consul/0.7.3/consul_0.7.3_linux_amd64.zip?_ga=1.155656443.1500592528.1473795963)

I've tried both chrome and safari and both produce the different link. 

Wasn't sure if this was expected since I've not encountered it when downloading previous versions of consul.

**Comment by talonx** [comment]
Looks like a Google Analytics tracking link. But the download should happen anyway, irrespective of whether it's present or not.

**Comment by Deric4** [comment]
@talonx you are correct, it does work. Some of my ansible playbooks didn't like it but its an easy workaround.
