### ISSUE TITLE
consul runs as root no matter what

### ISSUE THREAD

**Issue by FlorinAndrei** [hashicorp/consul#2703]
### `consul version` for both Client and Server
Same for servers and clients:
```
Consul v0.7.2
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

### Operating system and Environment details
Ubuntu 16.04

### Description of the Issue (and unexpected/desired result)
Trying to run consul under a dedicated system user account. I've created `/lib/systemd/system/consul-server.service` with the content:

```
[Unit]
Description=Consul server process
After=network.target
User=consul
Group=consul

[Service]
Type=simple
WorkingDirectory=/var/consul
ExecStart=/usr/local/bin/consul agent -config-dir /etc/consul.d/server
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

I've created the `consul` user and group. But consul still runs as root:

```
# ps axu | grep consul | grep -v grep
root     15193  0.5  0.7  44240 30944 ?        Ssl  Jan28  38:07 /usr/local/bin/consul agent -config-dir /etc/consul.d/server
```

### Reproduction steps
```
service consul-server start
```

**Comment by slackpad** [comment]
Hi - this is likely a problem with the systemd script. I'm not an expert there, but I think the `User` and `Group` go in the `Service` section. Hope that helps!

**Comment by FlorinAndrei** [comment]
That is indeed the case. Moving those two statements to the `Service` section fixed it. Thanks!
