### ISSUE TITLE
ConsulTestServer should have configurable timeouts.

### ISSUE THREAD

**Issue by janisz** [hashicorp/consul#2705]
### `consul version` for both Client and Server
Client: 0.7.3
Server: 0.7.3

### Operating system and Environment details
Travis

### Description of the Issue (and unexpected/desired result)
Consul Test Server sometimes fails to start on Travis infrastructure and fails with error:
```
--- FAIL: TestRegisterServices_MultipleRegistrations (33.02s)
	<autogenerated>:12: err: Missing tagged addresses
```
### Reproduction steps
Run tests for: https://github.com/allegro/marathon-consul they usually pass on fast machine but often fails on Travis due to Consul Test Server problems. https://github.com/allegro/marathon-consul/issues/171

**Comment by tugbabodrumlu** [comment]
I also have the same problem with my tests, they are sporadically failing with this error.

**Comment by slackpad** [comment]
Did you pick up https://github.com/hashicorp/consul/commit/14c6d009cc103e730c8cc91661846f7f79d364c3? That ended making this a lot more reliable.

**Comment by janisz** [comment]
It looks like this patch solves problem. Now tests on my local machine takes 2-3 times more. Used to take about 30s but now it's from 10s to 100s. Any idea why?

**Comment by kaskavalci** [comment]
I agree with @janisz , tests take much more time now. Is it possible to minimize this?

**Comment by janisz** [comment]
This is still an issue in 0.7.5. My tests tooks from [20 seconds](https://travis-ci.org/allegro/marathon-consul/builds/207016255#L186) to [150 seconds](https://travis-ci.org/allegro/marathon-consul/builds/207016419#L195).

@slackpad How can I tune this to work better and be more predictable?

**Comment by janisz** [comment]
Tried to set
```go
c.DisableCheckpoint = true
c.Performance.RaftMultiplier = 1
```
but it didn't help

**Comment by pszymczyk** [comment]
@janisz I don't know what exactly is going under the hood when you set `raft_multiplier` to 1 but it speed up my project. Ten invocations of starting Consul with `raft_multiplier` set to 1 took 17s and the same 10 invocations with `raft_multiplier` set to 5 took ~1m. I've prepared some test which shows difference, you can run it on your local machine:

https://github.com/pszymczyk/embedded-consul/commit/dd01686e59d314389ded726da4b49bd8a57c28da

**Comment by slackpad** [comment]
This change should have fixed the root cause of this error - https://github.com/hashicorp/consul/pull/2826. Are you still seeing this with Consul 0.8?

**Comment by janisz** [comment]
I updated to consul 0.8 and this error haven't occurred yet.

**Comment by slackpad** [comment]
Going to close this out. @magiconair is in the process of trying to make things more robust in the tests.
