### ISSUE TITLE
How can I config consul to get remote data center's nodes or key value by http api ?

### ISSUE THREAD

**Issue by vincentshow** [hashicorp/consul#2711]
I have two dc and there're two servers in dc_jx, while one server in dc_jx_test.Consul config in one of servers in dc_jx is
```
{
"datacenter":"dc_jx",
"data_dir":"./consul-data",
"log_level":"TRACE",
"node_name":"win_1",
"client_addr":"0.0.0.0",
"bind_addr":"192.168.23.1",
"serf_wan_bind":"172.18.70.71",
"advertise_addr_wan":"172.18.70.71",
"translate_wan_addrs":true
}
```
The bind_addr above is used to communicate with others within dc_jx, and serf_wan_bind as long as advertise_addr_wan are used to communicate across dc. However, when I telnet port 8300 on this server, it show me only 192.168.23.1:8300 is passed while the serf_wan_bind 172.18.70.71:8300 is fail.

And the info I get on the sever of dc_jx_test is:

```
[root@localhost consul]# ./consul members -wan
Node                              Address                   Status   Type     Build    Protocol    DC
centos_test.dc_jx_test    10.110.68.14:8302    alive      server   0.7.1    2                dc_jx_test
win_1.dc_jx                     172.18.70.71:8302    alive      server  0.7.1    2                 dc_jx
```

```
[root@localhost consul]# curl http://localhost:8500/v1/catalog/datacenters
["dc_jx_test","dc_jx"]
```

```
[root@localhost consul]# curl http://localhost:8500/v1/kv/jx/redis?dc=dc_jx_test
[root@localhost consul]# curl http://localhost:8500/v1/kv/jx/redis?dc=dc_jx
rpc error: failed to get conn: dial tcp 172.18.70.71:8300: getsockopt: connection refused
```

```
[root@localhost consul]# curl http://localhost:8500/v1/catalog/nodes?dc=dc_jx_test
[{"ID":"4031bdb1-c690-3be5-e9d1-dab4c00fa831","Node":"centos_test","Address":"10.110.68.14","TaggedAddresses":{"lan":"10.110.68.14","wan":"10.110.68.14"},"Meta":{},"CreateIndex":4,"ModifyIndex":798}]
```

```
[root@localhost consul]# curl http://localhost:8500/v1/catalog/nodes?dc=dc_jx
rpc error: failed to get conn: dial tcp 172.18.70.71:8300: getsockopt: connection refused
```

It seems that the serf_wan_bind above has no effect in the situation of across dc. What can I do to get this work?

**Comment by aprice** [comment]
Not sure what you mean "serf_wan_bind above has no effect in the situation of across dc" - it's using the address you gave it to reach out cross-DC, based on your own quoted error "failed to get conn: dial tcp 172.18.70.71:8300". Are you sure that the nodes are able to reach that port cross-DC (e.g. firewall rules allow it)?

**Comment by vincentshow** [comment]
OK, let's check my consul conf, both 192.168.23.1 and 172.18.70.71 are different intranet ip of my pc
{
"datacenter":"dc_jx",
"data_dir":"./consul-data",
"log_level":"TRACE",
"node_name":"win_1",
"client_addr":"0.0.0.0",
"bind_addr":"192.168.23.1",
"serf_wan_bind":"172.18.70.71",
"advertise_addr_wan":"172.18.70.71",
"translate_wan_addrs":true
}
As I know, with the config above, consul will use 192.168.23.1 in lan while 172.18.70.71 in wan to communicate with others. Is this true? However, when I open cmd in my pc to telnet port 8300 which will be used between different dcs, 192.168.23.1:8300 is available but 172.18.70.71:8300 is not.

**Comment by aprice** [comment]
Same question - do your firewall rules allow ingress on 172.18.70.71:8300?

**Comment by vincentshow** [comment]
I telnet 172.18.70.71:8300 in local machine whose ip is 172.18.70.71, does this have anything to do with firewall? Even I turned off firewall, it was not available yet. Put another way, what I want is that the "bind_addr" has the same strategy with "client_addr", that is when I set bind_addr to 0.0.0.0, consul can listen 8300 port no matter what the ip the caller use. How do I set the consul config to get this work?Any advice will be appreciate, thanks

**Comment by slackpad** [comment]
Hi sorry this didn't get attention sooner. We updated https://www.consul.io/docs/guides/datacenters.html a bit which may help. Also, between the servers on the WAN you need 8300/tcp for RPC traffic and 8302/tcp and 8302/udp for WAN gossip (https://www.consul.io/docs/agent/options.html#ports-used). Hope that helps!
