### ISSUE TITLE
problem in building consul V0.7.3

### ISSUE THREAD

**Issue by MahmudFadaly** [hashicorp/consul#2720]
i finished building consul last release successfully 
i installed Go package V1.7 and set GOPATH and GOROOT correctly 

but when i tried to build old release consul-v0.7.3  it didnt work its give me error during building 
sh: 1: /home/consul/tutorialspoint/sample/src/github.com/hashicorp/consul/script                         s/build.sh: Permission denied
GNUmakefile:22: recipe for target 'bin' failed
make: *** [bin] Error 126
consul@consul:~/tutorialspoint/sample/src/github.com/hashicorp/consul$
consul@consul:~/tutorialspoint/sample/src/github.com/hashicorp/consul$ GNUmakefile:22: recipe for target 'bin' failed
GNUmakefile:22:: command not found

**Comment by sielaq** [comment]
I also build with go 1.7.4-r1 and all is fine:
https://github.com/eBayClassifiedsGroup/KomPaaS/blob/master/Dockerfile

**Comment by slackpad** [comment]
Hi @MahmudFadaly that looks like you are failing at the `mkdir` command (https://github.com/hashicorp/consul/blob/v0.7.3/GNUmakefile#L22) which means your user doesn't have the permissions to create that directory. Hope that helps!
