### ISSUE TITLE
Blocking KV queries can block longer than requested

### ISSUE THREAD

**Issue by sgrimm-sg** [hashicorp/consul#2727]
### Consul version

Client: `0.7.4`
Server: `0.7.4`

### Consul info

Client/server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = '1c442cb
	version = 0.7.4
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 192.168.1.138:8300
	server = true
raft:
	applied_index = 12
	commit_index = 12
	fsm_pending = 0
	last_contact = never
	last_log_index = 12
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:192.168.1.138:8300 Address:192.168.1.138:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 52
	max_procs = 4
	os = darwin
	version = go1.7.5
serf_lan:
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Seeing this in production (Ubuntu 16.04.1 on various sizes of EC2 instances) but can consistently reproduce it with `consul agent -dev` and `curl` on OS X Sierra on a Macbook Pro laptop, so it doesn't seem to be environment-specific.

### Description of the Issue (and unexpected/desired result)

Blocking queries against the KV store can take significantly longer to return results than requested. I regularly see it take between 1% and 10% longer than requested (the variance appears random) and have seen more than that on occasion.

This is an issue for us because we have some Consul clients using the HTTP API from the far side of an internal load balancer that times out idle HTTP requests. To minimize load we'd ideally like to use as long a wait time as possible without exceeding the firewall's time limit, but we end up having to specify wait times substantially lower than that to make sure the added time doesn't put us over the limit.

As problems go this isn't an urgent one, but the variance is large enough that it seems likely to be a symptom of some deeper issue.

### Reproduction steps

On a host that's otherwise fairly idle:

```
consul agent -dev
```

Then put a key in the KV store:

```
consul kv put foo bar
```

And watch for changes:

```
curl 'http://localhost:8500/v1/kv/foo?index=5&wait=100s'
```

On a system with nothing else significant going on, the expected behavior would be that this would respond in 1 minute and 40 seconds, plus a fraction of a second for scheduling latency and so on. This is on the local host so network quality shouldn't be an issue.

In reality, it typically takes several seconds longer, and there's a lot of variance (see log fragments). The extra time seems to be roughly proportional to the wait time in the request: `wait=10s` may give you a result in 10.5 seconds, whereas `wait=100s` might take 105 seconds. Or, given the variance, it might randomly take 101 seconds or 115 seconds.

### Log Fragments

This is from a `-dev` server just so I can eliminate network delays as a source of trouble, but like I mentioned above, it also happens on a non-dev production cluster. Not including the periodic internal "in sync" log messages here.

```
    2017/02/09 18:08:19 [DEBUG] http: Request GET /v1/kv/foo?index=5&wait=100s (1m44.139438301s) from=127.0.0.1:56277
    2017/02/09 18:10:16 [DEBUG] http: Request GET /v1/kv/foo?index=5&wait=100s (1m45.527934583s) from=127.0.0.1:56296
    2017/02/09 18:11:58 [DEBUG] http: Request GET /v1/kv/foo?index=5&wait=100s (1m42.680742559s) from=127.0.0.1:56309
    2017/02/09 18:13:38 [DEBUG] http: Request GET /v1/kv/foo?index=5&wait=100s (1m40.019639251s) from=127.0.0.1:56329
    2017/02/09 18:15:22 [DEBUG] http: Request GET /v1/kv/foo?index=5&wait=100s (1m43.426584704s) from=127.0.0.1:56347
    2017/02/09 18:17:06 [DEBUG] http: Request GET /v1/kv/foo?index=5&wait=100s (1m44.278647944s) from=127.0.0.1:56361
    2017/02/09 18:18:47 [DEBUG] http: Request GET /v1/kv/foo?index=5&wait=100s (1m41.175481756s) from=127.0.0.1:56393
```

**Comment by slackpad** [comment]
Hi @sgrimm-sg this is working as designed. There's a random jitter applied to the max time here:

https://github.com/hashicorp/consul/blob/master/consul/rpc.go#L380-L381

This is designed so that if there's something like a partition event and a bunch of queries all come in at about the same time, with the same wait time (or just the default wait time), they won't all stay phase-aligned, which spreads the load out.

We should update https://www.consul.io/docs/agent/http.html to make this more clear, so this isn't surprising.

**Comment by slackpad** [comment]
Thanks for the awesome, detailed bug report btw :-)

**Comment by slackpad** [comment]
> This is an issue for us because we have some Consul clients using the HTTP API from the far side of an internal load balancer that times out idle HTTP requests. To minimize load we'd ideally like to use as long a wait time as possible without exceeding the firewall's time limit, but we end up having to specify wait times substantially lower than that to make sure the added time doesn't put us over the limit.

I didn't catch that part in my first read - indeed the wait time is more of a `min` and you currently can't express a hard `max` very easily. The current algorithm can add up to your supplied `wait / 16`, so you can use that as the true upper bound. It would be possible to maybe add a new parameter that controls this, though this hasn't been a common ask, so I'm not sure it's worth the additional complexity.

**Comment by sgrimm-sg** [comment]
No need for a new config option. The reasoning makes total sense. As 
long as I understand why it's happening and (especially) what the 
expected upper bound is, that's good enough to let me get my settings 
right. Can't argue with the idea of mentioning this in the 
documentation, though. Thanks for the quick response!
