### ISSUE TITLE
consul agent graceful leave does not work

### ISSUE THREAD

**Issue by mikezh15** [hashicorp/consul#2728]
### `consul version` for both Client and Server
Client: `v0.7.0`
Server: `v0.7.0`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 1
        check_ttls = 0
        checks = 9
        services = 9
build:
        prerelease =
        revision = 'a189091
        version = 0.7.0
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 18
        goroutines = 99
        max_procs = 18
        os = linux
        version = go1.6.3
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 3
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 12
        members = 4
        query_queue = 0
        query_time = 1
```

Server:
```
agent:
        check_monitors = 2
        check_ttls = 0
        checks = 8
        services = 15
build:
        prerelease =
        revision = 'a189091
        version = 0.7.0
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 192.168.0.12:8300
        server = true
raft:
        applied_index = 11364
        commit_index = 11364
        fsm_pending = 0
        last_contact = never
        last_log_index = 11364
        last_log_term = 3
        last_snapshot_index = 8203
        last_snapshot_term = 3
        latest_configuration = [{Suffrage:Voter ID:192.168.0.12:8300 Address:192.168.0.12:8300} {Suffrage:Voter ID:192.168.0.13:8300 Address:192.168.0.13:8300} {Suffrage:Voter ID:192.168.0.11:8300 Address:192.168.0.11:8300}]
        latest_configuration_index = 1
        num_peers = 2
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 3
runtime:
        arch = amd64
        cpu_count = 6
        goroutines = 188
        max_procs = 6
        os = linux
        version = go1.6.3
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 3
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 12
        members = 4
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

### Description of the Issue (and unexpected/desired result)
According to consul document on "leave_on_terminate", the default behavior of consul client is graceful leave when TERM signal is received. But the client is in "failed" status instead of "left"

### Reproduction steps
1. start consul cluster with 4 nodes: 3 servers + 1 client. leave_on_terminate is default value(not configured) for all nodes/agents.
2. register and start any service an all nodes
3. stop consul client with terminate signal. 
4. show consul members for any server nodes, the client node is shown as "failed" status. The service on client node is still passing status.
### Log Fragments or Link to [gist](https://gist.github.com/)
consul client log when a term signal is received:
==> Caught signal: terminated
==> Gracefully shutting down agent...
    2017/02/10 01:10:47 [INFO] consul: client starting leave
    2017/02/10 01:10:47 [DEBUG] http: Shutting down http server (127.0.0.1:8500)
    2017/02/10 01:10:47 [INFO] agent: requesting shutdown
    2017/02/10 01:10:47 [INFO] consul: shutting down client
    2017/02/10 01:10:47 [WARN] serf: Shutdown without a Leave
    2017/02/10 01:10:47 [ERR] dns: error starting tcp server: accept tcp 127.0.0.1:53: use of closed network connection
    2017/02/10 01:10:47 [INFO] manager: shutting down
    2017/02/10 01:10:47 [INFO] agent: shutdown complete

**Comment by slackpad** [comment]
Hi @mikezh15 the default for `leave_on_terminate` changed for servers in Consul 0.7 - please see the docs here - https://www.consul.io/docs/agent/options.html#leave_on_terminate:

> leave_on_terminate If enabled, when the agent receives a TERM signal, it will send a Leave message to the rest of the cluster and gracefully leave. The default behavior for this feature varies based on whether or not the agent is running as a client or a server (prior to Consul 0.7 the default value was unconditionally set to false). On agents in client-mode, this defaults to true and for agents in server-mode, this defaults to false.

**Comment by mikezh15** [comment]
@slackpad I terminated the client-mode agent instead of server-mode agent. According to consul document on "leave_on_terminate", the default behavior of consul client is graceful leave when TERM signal is received. But the client is in "failed" status instead of "left". I also try to enable leave_on_terminate on a client agent explicitly, it does not work as well.

**Comment by slackpad** [comment]
The behavior of leave on terminate is often dependent on the process supervisor and its behavior. Since the leave can take a few seconds to process, the supervisor will sometimes kill Consul before it can carry it out, so it's not a super reliable mechanism. Consul 0.8 added a [dead server cleanup](https://www.consul.io/docs/guides/autopilot.html#dead-server-cleanup) feature that protects the cluster even if the leave wasn't clean (this is necessary in case a server just dies as well).

**Comment by sebamontini** [comment]
@slackpad does the new Dead Server Cleanup feature works both for server and clients?
we have pretty much the same issue, the 3 consul servers are fine, but the clients are an autoscaling group of spot instances so the tend to die all the time, and most of the time the leave_on_terminate=true doesn't work. Would migrating to 0.8 and enabling autopilot help us with this type of issue?

**Comment by slackpad** [comment]
Hi @sebamontini autopilot only works for servers since that's the only type of Consul agent it's critical to manage from Consul's POV. One way we thought might be good to solve your issue is to let you configure the reap time from the agents. This way you can run your spot instances and configure them with a reap time of like 60 seconds or something and they will age out automatically rapidly. If that sounds like it would be useful for you please open a new issue and we can see about getting that in.

**Comment by torian** [comment]
@slackpad That'd be a really interesting feature to add. Environments with highly ephemeral instances would greatly benefit from this.

**Comment by sebamontini** [comment]
actually, just opened up #2982
