### ISSUE TITLE
Leader Replication

### ISSUE THREAD

**Issue by huyjack178** [hashicorp/consul#2738]
I have read about consensus protocol and I am confused about why Leader attempts to replicate data to a quorum of followers. Can anyone answer me?

**Comment by slackpad** [comment]
Hi @huyjack178 having a quorum of followers commit each entry ensures that the cluster can carry on without losing data if a server fails (even the leader). You may want to look at https://raft.github.io/ to get a feel for how the Raft consensus protocol works. Hope that helps!
