### ISSUE TITLE
Doesn't elect leader with bootstrap_expect == 1

### ISSUE THREAD

**Issue by kshep** [hashicorp/consul#274]
From my reading of the docs, if I want to spin up a single node cluster for testing, I should be able to just set boostrap_expect to 1 in the config. If I do so, the node won't elect itself leader. I can force this by setting bootstrap to true.

At https://github.com/hashicorp/consul/blob/master/consul/server.go#L255

... should EnableSingleNode be set to true if s.config.BootstrapExpect == 1?

**Comment by kunalvjti** [comment]
I seem to be getting the same error with a single server (consul agent -server -bootstrap-expect 1 -advertise=159.203.x.y -data-dir /tmp/consul)
 2015/10/29 17:13:27 [INFO] consul: cluster leadership acquired
    2015/10/29 17:13:27 [INFO] consul: New leader elected: LB-demo
    2015/10/29 17:13:27 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2015/10/29 17:13:27 [INFO] raft: Added peer 172.17.42.1:8300, starting replication
    2015/10/29 17:13:27 [INFO] raft: Removed peer 172.17.42.1:8300, stopping replication (Index: 1335)
    2015/10/29 17:13:27 [INFO] raft: Node at 159.203.x.y:8300 [Follower] entering Follower state
    **2015/10/29 17:13:27 [ERR] consul: failed to wait for barrier: leadership lost while committing log**
    2015/10/29 17:13:27 [INFO] consul: cluster leadership lost

And hence i get this error when i query anything with consul: [ERR] agent: failed to sync remote state: No cluster leader
Any idea why this might be happening ?

**Comment by slackpad** [comment]
@kunalvjti did you figure this one out? It looks like there's another server it is connecting to, losing quorum.

**Comment by sandstrom** [comment]
If anyone else ends here after trying to boot a `bootstrap-expect 1` cluster for testing etc. I solved it by removing the atlas stuff (not needed in development anyway).
