### ISSUE TITLE
service health check status is always "passing" on a "failed" agent 

### ISSUE THREAD

**Issue by mikezh15** [hashicorp/consul#2740]
step to reproduce the problem:
1. create 4 nodes consul cluster: 3 server nodes + 1 client node
2. stop the consul agent on client node
3. show health status by heath http api, all the health check of client node is always in "passing" status.

I guess the health check status is not updated once the consul agent is "failed" as the health check can not  get performed.  Is this the design intention?  
Q1: When a agent is failed, the status of all the services registered with the agent should be "unknown" as the health checks are not executed, right? 
Q2: will the "failed" agent node ip address be returned when consul dns resolves a "passing" service name on the failed node?

**Comment by hvindin** [comment]
I get the feeling this would exhibit more logical behaviour if this where merged: #2474

I'be found that this show up as healthy a lot of the time purely due to a very very low bar for 'healthy' being set.

**Comment by slackpad** [comment]
When the agent fails all of the health checks registered on the agent will retain their last state, but the Consul servers will automatically mark that agent's node-level `serfHealth` check as failed. When doing DNS lookups for a service, Consul considers the service-level checks *and* the node-level checks, so this will keep that node's services from being returned as healthy. Hope that helps!
