### ISSUE TITLE
What's the maximum of agents alive in single DC?

### ISSUE THREAD

**Issue by skygragon** [hashicorp/consul#2741]
or is there a best practice to limit the number of server/client agents??

**Comment by skygragon** [comment]
Am I understanding it correctly?
1. only the "server agent" maintains the cluster status, which means only the "servers" (3~5 nodes) need exchange cluster status among them.
2. the "client agent" is stateless, and its only job is to periodically reports individual status to "servers". 

But I'm not sure about those:
3. will lots of "client agents"(e.g. hundreds or thousand) affects the performance? I see "servers" are still maintaining all clients info, even after client is left. 
4. is there any talk among "clients"?

**Comment by slackpad** [comment]
Hi @skygragon thanks for opening an issue - these guides will help answer your questions:

1. https://www.consul.io/docs/internals/architecture.html
2. https://www.consul.io/docs/internals/anti-entropy.html
3. https://www.consul.io/docs/internals/gossip.html

Consul is designed to handle 10s of thousands of agents in a cluster. The agents perform health checks of their services locally and sync changes to the servers in a very efficient manner. The clients do talk to each other as part of the gossip protocol which lets them check the health of each other and detect failed agents. Hope that helps!
