### ISSUE TITLE
force-leave should also remove voter from raft configuration if node is not in server mode anymore

### ISSUE THREAD

**Issue by stefreak** [hashicorp/consul#2742]
### `consul version` for both Client and Server
Client: `v0.7.2`
Server: `v0.7.2`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 1
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 'a9afa0c
	version = 0.7.2
consul:
	known_servers = 7
	server = false
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 44
	max_procs = 1
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 14
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 110
	members = 11
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 1
	check_ttls = 0
	checks = 1
	services = 2
build:
	prerelease =
	revision = 'a9afa0c
	version = 0.7.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 192.168.2.16:8300
	server = true
raft:
	applied_index = 733
	commit_index = 733
	fsm_pending = 0
	last_contact = 46.584898ms
	last_log_index = 733
	last_log_term = 1556
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:192.168.2.13:8300 Address:192.168.2.13:8300} {Suffrage:Voter ID:192.168.2.10:8300 Address:192.168.2.10:8300} {Suffrage:Voter ID:192.168.2.14:8300 Address:192.168.2.14:8300} {Suffrage:Voter ID:192.168.2.11:8300 Address:192.168.2.11:8300} {Suffrage:Voter ID:192.168.2.19:8300 Address:192.168.2.19:8300} {Suffrage:Voter ID:192.168.2.20:8300 Address:192.168.2.20:8300} {Suffrage:Voter ID:192.168.2.17:8300 Address:192.168.2.17:8300} {Suffrage:Voter ID:192.168.2.16:8300 Address:192.168.2.16:8300} {Suffrage:Voter ID:192.168.2.18:8300 Address:192.168.2.18:8300} {Suffrage:Voter ID:192.168.2.15:8300 Address:192.168.2.15:8300}]
	latest_configuration_index = 601
	num_peers = 9
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 1556
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 66
	max_procs = 1
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 14
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 110
	members = 11
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Ubuntu 16.04

### Description of the Issue (and unexpected/desired result)
I wanted to migrate the consul server agents to a new set of servers. Because the raft remembers the old servers for 72 hours this led to an outage (cannot elect leader anymore with only 5 servers because 10 allowed voters).

Now I have the old servers, running as client, and want to remove them from the raft configuration. consul force-remove exits with 0, but does nothing.

### Reproduction steps

1. Change configuration of a server to client.
2. Restart consul.
3. Execute consul force-leave <name of node that has just been restarted>
4. consul info | grep latest_configuration still contains the force-left node.

### Known Workarounds

Known work arounds:
Change the node to a server again, start it, wait for it to join the cluster, then stop. Force-leave will work correctly now.

If the server cannot be brought up anymore, the only options left are to either
- wait 72 hours
or
- `consul operator raft -remove-peer -address="<address>:8300"`
 (consul operator feels scary though)

### Log Fragments or Link to [gist](https://gist.github.com/)

Upon requet I can also add a trace log.

**Comment by slackpad** [comment]
Hi @stefreak are you giving the node name to the `force-leave` command? A common mistake is to give an IP, and we need to fix that so it gives better feedback. Also, if your cluster is in an outage state then the `force-leave` won't be able to remove the servers, as server configuration changes to the Raft quorum require a leader to process. If you can't get the servers back you'd need to run the steps in https://www.consul.io/docs/guides/outage.html.

**Comment by stefreak** [comment]
Yes I am giving the node name.
Also, the cluster is not in outage state while I am running force-leave.

**Comment by stefreak** [comment]
I found another workaround: `consul operator raft -remove-peer -address="192.168.2.14:8300"` removed the server from raft configuration.

**Comment by stefreak** [comment]
I personally would still expect force-leave to also remove the raft peer, even when it's now a client and not a server.

**Comment by slackpad** [comment]
> I personally would still expect force-leave to also remove the raft peer, even when it's now a client and not a server.

Ah ok I didn't catch that - if they are back in the cluster as clients then we wouldn't get the event that kicks it out of the quorum. The operator command is the right way to kick them out. I'll tag this as docs to add some more explanation around `force-leave`. We are also working on some automation in Consul 0.8 that'll remove dead servers automatically.

**Comment by stefreak** [comment]
OK, thanks!
