### ISSUE TITLE
Question about resetting peers.json

### ISSUE THREAD

**Issue by jacob-koren** [hashicorp/consul#2744]
I'm running consul in DC/OS and I want a way to reset the peer's information in the situation that too many nodes left the cluster ungracefully and no leader can be elected due to quorum problems.

Reloading the peers.json file requires node restart (not just reload). So I thought about wrapping the official consul image and run it with an init system like https://github.com/Yelp/dumb-init. That way consul will not run as process 1 inside the container and restarting the consul process does not mean restarting the whole container. 

Is there an endpoint for restart operation? A signal that triggers restart?

**Comment by jippi** [comment]
Hi @jacob-koren 

Have you seen https://www.consul.io/docs/commands/operator.html ?

**Comment by jacob-koren** [comment]
Is the operator endpoint requires a leader? because I'm talking about a situation that there is no leader...

**Comment by slackpad** [comment]
Hi @jacob-koren if you are running the https://www.consul.io/docs/guides/outage.html steps and setting peers.json, that requires a full restart of the Consul process, unfortunately. This would be a pretty major change to Consul to perform on the fly with a `consul reload` or `HUP`, so I don't think this would be something we'd change at this time.
