### ISSUE TITLE
Error while using consul on azure Virtual machine

### ISSUE THREAD

**Issue by worksamp** [hashicorp/consul#2745]
While running command "consul agent -dev" on any of the azure virtual machine with windows server 2012 r2 operating system I am getting following error: 
Failed to start Consul server: Failed to start RPC layer: listen tcp 127.0.0.1:8300: bind: An attempt was made to access a socket in a way forbidden by its access permission.

Even after opening port 8300,8301,8302,8303,8304, I am getting the same error. I have tried many options but none is working . I have even opened port 127.0.0.1:8300 separately, still it's not working.

**Comment by slackpad** [comment]
Hi @worksamp did you figure this out? It looks like possibly a permissions error for the user Consul is running as?

**Comment by slackpad** [comment]
Closing this since we didn't hear back. Please let us know if you still need help.

**Comment by BvdVen** [comment]
I've the same problem with Consul v1.3.0, on my local machine it works fine but when I try to run consul on a Windows Virtual Machine (not on Azure) I get the same error.

I tried to run the cmd.exe and powershell as administrator, but it doesn't make any difference.

**Comment by jsprojects2** [comment]
Hi,

I am trying to run the consul service in windows 2012 server, I ran the following command from command prompt

sc create "Consul_Service" binPath="C:\Microservices Tool\consul\consul.exe agent -config-dir=C:\Microservices Tool\consul\consul_configA.json" start=auto

the consul.exe is installed in the window sercive.

after that i am running the following command 

sc start consul_service

the consul service is unable to run, it is throwing an error

Windows could not start the Consul_Service service on Local Computer.

Error 1067: The process terminated unexpectedly.

Please kindly give us a suggestion to make it working. or do i missed something during installation or any other info.
