### ISSUE TITLE
Out of date info on consul.io download page for 0.7.5

### ISSUE THREAD

**Issue by grossws** [hashicorp/consul#2746]
Download page [1] contains info, links and checksums for `0.7.4`.

[1]: https://www.consul.io/downloads.html

**Comment by slackpad** [comment]
We will change that right after we announce the release this morning. Thanks!

**Comment by grossws** [comment]
Sorry for inconvenience, I've received update throught package manager and thought that release was several days ago.

**Comment by slackpad** [comment]
No worries. I had staged the release last night on our releases server, so something must be RSS-ing that. The download page is updating now.
