### ISSUE TITLE
[Feature Request] Expose telemetry via JSON API

### ISSUE THREAD

**Issue by jeroenjacobs1205** [hashicorp/consul#2747]
Instead of forcing people to use a specific metric collector (eg: statsd), why can't Consul just expose telemetry via a JSON API? That way it can be parsed by any metric collector (Telegraf JSON input module, or collectd curl-JSON module).

**Comment by slackpad** [comment]
Hi @jeroenjacobs1205 this is captured in https://github.com/hashicorp/consul/issues/817.
