### ISSUE TITLE
Release downloads as .tar.gz or tar.xz

### ISSUE THREAD

**Issue by joonas-fi** [hashicorp/consul#276]
First off, thanks for Consul! I'm just getting to know it - looks promising.

One thing tho, why release the downloads as .zip ( http://www.consul.io/downloads.html )? I can understand the Windows version as .zip, but it seems like an additional hassle to "apt-get install unzip" just to install Consul, since all other projects seem to use .tar.gz or .tar.xz (even xz seems to be installed by default in my box, unzip hells to the no)

p.s. I like the decision to embed Go runtime inside consul binary to minimize external dependencies. It's hassle-free (except for the .zip format ;) ) to download and drop consul in /usr/bin.

p.p.s. I'm a long time fan of Vagrant. Keep it real, HashiCorp. :)

**Comment by xbx** [comment]
Just for the record. ".tgz" format releases are now available for download

**Comment by Kentzo** [comment]
@xbx Doesn't seem to be true, https://releases.hashicorp.com/consul/ is all .zip

**Comment by xbx** [comment]
@kentzo, you're right. But it seems to be true only for consul-template and envconsul.

://releases.hashicorp.com/consul-template

**Comment by dfredell** [comment]
That is confusing, some of hashicorp's deliverables are in tar.gz and others in zip. I agree with @joonas-fi all of my dockers start with a update of the repo, install unzip, then trash the repo cache. All just to get consul, consul-template, and containerpilot. It would be nice if consul was in tar.gz just like consul-template.
