### ISSUE TITLE
Enhancement Idea: per-datacenter ACL entries

### ISSUE THREAD

**Issue by daveadams** [hashicorp/consul#2763]
# Summary
For a variety of use cases, it would be useful to be able to specify per-datacenter rules in ACL policies. For example, given three Consul datacenters dc1, dc2, and dc3, you might want to grant token1 read access to the prefix `config/` in all three datacenters, but you might only want token2 to be able to read `config/` in dc2 or dc3, but not dc1. Currently there's no way to specify this, and a token that can read from `config/` in dc1 can read from that prefix in any other datacenter connected to the WAN pool.

# API coverage

While this seems like a pretty clear feature request for the KV API and probably the service and query APIs, I'm not sure how or if it makes sense for the event, operator, keyring APIs also covered by the ACL policy.

# Syntax

Syntax for this feature is an important consideration. There are lots of factors to consider and I'm sure I won't think of them all. Consider this just an example for clarity's sake:

There could be a `datacenters` attribute in addition to the existing `policy` attribute for an ACL entry:

    key "config/" {
      policy = "read"
      datacenters = ["dc2","dc3"]
    }

If not specified the `datacenters` attribute would probably default to the list of all datacenters which could be specified explicitly as `datacenters = ["*"]`.

It would also be nice to be able to exclude specific datacenters, perhaps like this:

    key "special/" {
      policy = "write"
      exclude_datacenters = ["dc3"]
    }

That would allow writing to the `special/` prefix from all datacenters except dc3. By default the `exclude_datacenters` property would be an empty list.

# Other Considerations

How these policies combine with inheritence might get complicated, and that might argue for a simpler and more explicit implementation than what I described above. But hopefully this can serve as a starting point for discussion.

**Comment by slackpad** [comment]
Follow on from [ML discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/5jhyKt3yTx8/a2EYCdRHDgAJ).

**Comment by aprice** [comment]
This seems perfect to me, at least for cases where data centers in consul are used to separate multiple environments (dev, QA, production) with different access control requirements.

I would agree that services and kv are the primary targets for this, not sure about queries - are queries DC local or are they global?

Does Consul accept PRs? I could work on an implementation for this.

**Comment by aprice** [comment]
It looks like none of the catalog read methods check ACL at all, so for services I think it would just be register & deregister that this would apply to.

**Comment by daveadams** [comment]
@aprice To answer your question, prepared queries are DC-local. And yes, PRs are accepted very readily in my experience.

**Comment by mkeeler** [comment]
Closing this one as the new ACL system in 1.4.0 allows for datacenter scoped policies which should satisfy this request. If there are further requests please feel free to open more issues.
