### ISSUE TITLE
Add support for UDP health checks

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/consul#2765]
Consul currently allows `tcp` health checks to be defined, but there doesn't seem to be a `udp` health check. #1796 addresses this, but it has grown stale.

**Comment by TaylorMutch** [comment]
Yeah this would be a really big help for services I help run. Would be interesting to see if this gets traction again.

**Comment by i0rek** [comment]
The Pr has been closed due to inactivity and I will close this issue too. If there is still interest I would be happy to review a PR for it.
