### ISSUE TITLE
Consul crashes when reloading config while joining

### ISSUE THREAD

**Issue by iconara** [hashicorp/consul#2769]
(Consul version and details at the bottom)

### Description of the Issue (and unexpected/desired result)

When a Consul client is starting up and you ask it to reload its config it will crash. The crucial moment seems to be if you do it before it has joined the cluster.

We install Consul with Chef and have various mechanisms that will automatically ask Consul to reload its config when it's changed during the Chef run. On the initial run of a new node Consul is installed and started and then in different Chef recipes additional config like the services and checks that run on the node are generated in quick succession.

We've set things up so that Consul will be started as soon as it's installed, but we will wait as long as possible before reloading the config, so that all config changes are captured in one reload. However, it's still only a second or two between when Consul is started and the reload happens. If Consul hasn't managed to join the cluster by then it will crash, the reload will fail and the whole Chef run fails.

I don't know if you're supposed to be able to send `HUP` to the process while it's starting up, but I also don't know if there is any way to determine when it is safe to do it. We have a fairly standard init script for Consul, and I would be happy with a workaround that was a command or two that could determine that Consul was ready, so that I could wait for that before exiting from the start action.

### Reproduction steps

In one terminal run a loop that will ask Consul to reload its config over and over again:

```
$ while true; do pkill -HUP consul; done
```

In another start Consul:

```
$ consul agent -config-dir /etc/consul.d
```

The config contains `start_join` with three servers, so starting the agent will automatically join, and `log_level` set to `TRACE` to try to get as much debugging info as possible.

The server will never start. It will crash at some point before or while joining the cluster, see below.

### Log Fragments

Most of the time Consul only prints the first of these lines before crashing, but once in a while two of them, and on some attempts it prints all three. If you're less aggressive with the reload loop it usually manages to get to the third line, but as long as it gets the `HUP` signal around the same time as it prints that line it will crash.

```
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
```

### `consul version` for both Client and Server
Client: `Consul v0.7.2`
Server: `Consul v0.7.2`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 2
	check_ttls = 0
	checks = 3
	services = 1
build:
	prerelease =
	revision = 'a9afa0c
	version = 0.7.2
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 36
	max_procs = 1
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 24932
	failed = 0
	health_score = 0
	intent_queue = 1
	left = 0
	member_time = 44638
	members = 105
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 3
	check_ttls = 0
	checks = 3
	services = 2
build:
	prerelease =
	revision = 'a9afa0c
	version = 0.7.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.121.28.30:8300
	server = true
raft:
	applied_index = 130682964
	commit_index = 130682964
	fsm_pending = 0
	last_contact = 5.728643ms
	last_log_index = 130682964
	last_log_term = 1881
	last_snapshot_index = 130676160
	last_snapshot_term = 1881
	latest_configuration = [{Suffrage:Voter ID:10.82.178.178:8300 Address:10.82.178.178:8300} {Suffrage:Voter ID:10.121.28.30:8300 Address:10.121.28.30:8300} {Suffrage:Voter ID:10.96.40.88:8300 Address:10.96.40.88:8300}]
	latest_configuration_index = 113275068
	num_peers = 2
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 1881
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 365
	max_procs = 1
	os = linux
	version = go1.7.3
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 24932
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 10
	member_time = 44638
	members = 115
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 594
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

AWS Linux 2016.03

```
$ uname -r
4.4.8-20.46.amzn1.x86_64
```

**Comment by slackpad** [comment]
Hi @iconara do you happen to have any logs from the crash (any panic output would be super helpful if you can link as a gist).

**Comment by iconara** [comment]
All that are in the logs is what is in the issue above (under "Log Fragments"), there's really no more output.

**Comment by slackpad** [comment]
Hmm does the process just exit with no other info or does it hang?

**Comment by iconara** [comment]
It exits. Have you tried my reproduction steps, could you reproduce it?

**Comment by slackpad** [comment]
I tried reproducing locally on MacOS with Consul 0.8 and didn't see it - I can give it a try with 0.7.2 on Linux to see if that does it.

**Comment by magiconair** [comment]
I've been working on that specific codepath recently and can have a look.

**Comment by slackpad** [comment]
Pulling this out of the project as this will likely get addressed in the next few releases as we continue the config refactor, but it won't make it for 0.9.0.

**Comment by i0rek** [comment]
I tried the reproduction steps and this is no longer an issue. Thanks for reporting!
