### ISSUE TITLE
Maintenance for a failed node

### ISSUE THREAD

**Issue by Moshem123** [hashicorp/consul#2772]
### `consul version` for both Client and Server
Client: `Consul v0.7.2`
Server: `Consul v0.7.2`

### `consul info` for both Client and Server
Client:
```
not available...
```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 'a9afa0c
        version = 0.7.2
consul:
        bootstrap = false
        known_datacenters = 3
        leader = true
        leader_addr = 10.6.0.122:8300
        server = true
raft:
        applied_index = 415932
        commit_index = 415932
        fsm_pending = 0
        last_contact = never
        last_log_index = 415932
        last_log_term = 2
        last_snapshot_index = 409610
        last_snapshot_term = 2
        latest_configuration = [{Suffrage:Voter ID::8300 Address:10.6.0.122:8300} {Suffrage:Voter ID:10.6.0.178:8300 Address:10.6.0.178:8300} {Suffrage:Voter ID:10.6.0.61:8300 Address:10.6.0.61:8300}]
        latest_configuration_index = 1
        num_peers = 2
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 97
        max_procs = 2
        os = linux
        version = go1.7.3
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 85
        failed = 2
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 251
        members = 9
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 159
        members = 9
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details
RHEL Fedora \ Amazon Linux

### Description of the Issue (and unexpected/desired result)
Hey, is there a way to list a node in maintenance mode when I can't access it?
It's a node I can't access right now, but in the future, I need consul to work on it, and it's already installed.
When i try `consul maint -http-addr=my_node_ip:8500 -enable`
from my dc server, I get:
`Error querying Consul agent: Get http://my_node_ip:8500/v1/agent/self: dial tcp my_node_ip:8500: getsockopt: no route to host`

### Reproduction steps
Turn off a node, and from the DC server, try to put it into maintenance mode

**Comment by slackpad** [comment]
Hi @Moshem123 Consul's maintenance mode does require a running agent on the node in order to be toggled. If the agent is down, Consul will automatically set its `serfHealth` check to failing, which is equivalent to what maintenance mode would do, though, so this node is marked unhealthy, won't be returned in DNS queries, etc. Hope that helps!
