### ISSUE TITLE
Failed to invoke watch handler /tmp/script.sh exit status 126

### ISSUE THREAD

**Issue by ggleason** [hashicorp/consul#2773]
Have a watch handler that runs checks the health status of services and runs a script to restart the container if it fails the health check.  The problem I am seeing is the watch handler does not run the script but instead has this error.

Failed to invoke watch handler /tmp/script.sh exit status 126

What is this exit codes meaning?

Consul Server Version - 0.6.4
Consul Template - 0.14.0

**Comment by brianshumate** [comment]
Hi there,

An exit status of 126 means that the command invoked is not executable. This is a problem with your script, but not Consul. Ensure that your script has the proper permissions / execute bit set and that should resolve the error.

**Comment by brianshumate** [comment]
Hi,

I hope my explanation on this was helpful for you. I am going to close this now.

**Comment by ggleason** [comment]
Yes it helped a bunch sorry I didn’t update it was caused by the line endings in the script were set to windows instead of unix.


Thanks

**Comment by VishLeo** [comment]
Am having exit status 125.
`Failed to invoke watch handler '/home/vishal/data/manage_watches.sh': exit status 125`

Where can I find details about all these exit statuses??

**Comment by brianshumate** [comment]
You can learn more details about them in the Linux Documentation Project Advanced Bash Scripting Guide in the [Exit Codes With Special Meanings](http://www.tldp.org/LDP/abs/html/exitcodes.html) section or in the Bash Hackers Wiki [Exit Status](http://wiki.bash-hackers.org/dict/terms/exit_status)

Exit status 125 is reserved and typically used by programs for their own exit meanings, so you'll need to find the relevant documentation for whatever program(s) you are executing in `manage_watches.sh` and determine what 125 means from that.
