### ISSUE TITLE
Document CLI arguments and settings for production consul cluster please

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/consul#2778]
The online documentation for consul agent CLI gives many pages about many issues, but there is no real "here's how we recommend you set up a production consul cluster page". (I've read this> https://www.consul.io/docs/guides/bootstrapping.html and is incomplete I think)

consul agent --help gives

```
-advertise=addr
-advertise-wan=addr
-atlas=org/name
-atlas-join
-atlas-token=token
-atlas-endpoint=1.2.3.4
-bootstrap
-bind=0.0.0.0
-http-port=8500
-bootstrap-expect=0
-client=127.0.0.1
-config-file=foo
-config-dir=foo
-data-dir=path
-dev
-recursor=1.2.3.4
-dc=east-aws
-datacenter=east-aws
-encrypt=key
-join=1.2.3.4
-join-wan=1.2.3.4
-retry-join=1.2.3.4
-retry-interval=30s
-retry-max=0
-retry-join-ec2-region
-retry-join-ec2-tag-key
-retry-join-ec2-tag-value
-retry-join-gce-project-name
-retry-join-gce-zone-pattern
-retry-join-gce-tag-value
-retry-join-gce-credentials-file
-retry-join-wan=1.2.3.4
-retry-interval-wan=30s
-retry-max-wan=0
-log-level=info
-node=hostname
-node-meta=key:value
-protocol=N
-rejoin
-server
-syslog
-ui
-ui-dir=path
-pid-file=path
```

Virtually none of these are documented in this page:

https://www.consul.io/docs/agent/basics.html

If this isnt the right page, can the page include a link to all the options as it is the page referred to by agent CLI options. If it is the right page, could we have a more comprehensive list of which args go with which configurations and what they do and examples?

For example, which args and settings are standard in a production consul cluster setup? It would be useful to have a page on this, because otherwise you go through 3 months of consul usage before you realise you should be adding dns caching settings for when the cluster cant find itself because of the fallacies of distributed computing etc. resulting in sporadic downtime otherwise.

**Comment by slackpad** [comment]
Hi @gtmtech thanks for opening an issue - we definitely have plans to do this!

**Comment by jsosulska** [comment]
As the related PR has been merged, and the learn guides [production checklist](https://learn.hashicorp.com/consul/datacenter-deploy/production-checklist) and [deployment guide](https://learn.hashicorp.com/consul/datacenter-deploy/deployment-guide) have been created/updated, closing this ticket.
