### ISSUE TITLE
consul operator doesn't work as documented.

### ISSUE THREAD

**Issue by rhyas** [hashicorp/consul#2782]
Version 0.7.5

When a cluster blows up and fails to elect a leader, the Outage documentation says you are supposed to be able to remove the problem nodes with the `consul operator raft -remove-peer -address="<ip>:8300"' command. This command fails when there is no leader with:

Operator "raft" subcommand failed: Unexpected response code: 500 (No cluster leader)

Even using the -stale=true option fails because of no leader.

This option should either be removed from the documentation, or fixed to work as documented.

Also, the peers.json option for recovery, only works if the hosts in question have a local raft database that lists the peers in it. This should also explicitly called out. If it is a new node, that has never participated in the raft cluster, the server will fail to start with a peers.json in place.

**Comment by slackpad** [comment]
Hi @rhyas thanks for opening an issue. We can definitely improve the documentation around this - the `remove-peer` command only works if there's a leader, so a full outage does require a `peers.json` recovery.

**Comment by ThatJames** [comment]
@slackpad your documentation now produces usage errors when copied verbatim. Please explain the peers.json recovery as I am unable to bring up the server node now

**Comment by slackpad** [comment]
The peers.json recovery is documented here - https://www.consul.io/docs/guides/outage.html#manual-recovery-using-peers-json.

**Comment by brianshumate** [comment]
Thanks for the issue report!

I added a point of clarification to docs in #2782 and will close this now.
