### ISSUE TITLE
Consul v0.6.4: consul reload deregistering services (still facing similar to #1173 )

### ISSUE THREAD

**Issue by p1nkrock** [hashicorp/consul#2783]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]` Consul v0.6.4

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Operating system and Environment details
Linux - x86_64
### Description of the Issue (and unexpected/desired result)
This issue is similar to #1173
Due to multiple triggering of reloads, one of the service gets deregistered.

In issue #1173, it was posted that it got fixed in 0.6 release. But we still face this issue in 0.6.4 release.

![02-03-2017 11-57-18](https://cloud.githubusercontent.com/assets/20436461/23495845/ebfea1d2-ff40-11e6-8c97-738be1e40c1e.png)

The unfortunate part is the service doesnt even know that it got deregistered. Is there any mechanism thought of where it informs the service about the deregistration?

### Reproduction steps
trigger multiple reloads, one of the sync thread will lead to deregistration of service.

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by p1nkrock** [comment]
@wuub @armon @slackpad 
Please help in resolving this issue.

**Comment by wuub** [comment]
@p1nkrock are those reloads by any chance running on consul server in bootstrap mode as your log suggests?

How many consul servers are you running in your deployment?

**Comment by p1nkrock** [comment]
Only one consul server running with bootstrap mode.

**Comment by wuub** [comment]
I would not be surprised if this is a root of your problem (bootstrap mode). If you're creating any kind of production deployment you should really consider using at least 3 consul servers, and turning bootstrap off is necessary https://www.consul.io/docs/guides/bootstrapping.html

**Comment by p1nkrock** [comment]
It is recommended to have 3 or 5 servers for high availability but it is not mandatory. Hence the above quoted issue should not occur even in single server case. 

Here, we had to do multiple reloads because of watch registration from various applications. We write watch jsons to a consul config directory and trigger reload as there is no Consul Endpoint where watches can be registered thru HTTP calls. Its either thru config file or consul watch command.

We have a workaround now where we queue these watch registrations for a certain interval and then trigger reload. Cons for this workaround is the delay for processes to know the state of other processes.
