### ISSUE TITLE
Is there load balance at server side?

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2789]
I learn from the doc that all the RPC requests will be forwarded to the leader, does the non-leader instance not handle the client RPC request at all?

**Comment by slackpad** [comment]
Hi @hehailong5 you can let non-leader servers answer queries for better read scaling if you use the relaxed consistency modes - see https://www.consul.io/docs/agent/http.html#consistency-modes and https://www.consul.io/docs/agent/options.html#dns_config. Hope that helps!
