### ISSUE TITLE
404 on the RPC link in the docs

### ISSUE THREAD

**Issue by dweomer** [hashicorp/consul#2794]
When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: n/a
Server: n/a

### `consul info` for both Client and Server
Client: n/a
Server: n/a

### Operating system and Environment details
n/a

### Description of the Issue (and unexpected/desired result)
Navigating through the docs on consul.io, I clicked on the "[RPC Protocol](https://www.consul.io/docs/agent/rpc.html)" link and encountered a 404.

### Reproduction steps
Point your browser at https://www.consul.io/docs/agent/rpc.html

### Log Fragments or Link to [gist](https://gist.github.com/)
n/a

**Comment by dweomer** [comment]
![screenshot 2017-03-09 11 54 43](https://cloud.githubusercontent.com/assets/1033444/23765960/4ca4b9ac-04c0-11e7-82bf-7844ce351ed1.png)

**Comment by slackpad** [comment]
@dweomer sorry about that - this interface is deprecated and will be going away in Consul 0.8, but I added the page back with a deprecation notice for now.

**Comment by dweomer** [comment]
@slackpad Thank you for the temporary fixed link. Would you have handy some links to understand the reasoning behind the deprecation? (I haven't been keeping up with Consul development).

**Comment by slackpad** [comment]
@dweomer this is an old interface that didn't use HTTP and only supported a subset of Consul's operations, and didn't have good support for things like ACLs. We expanded the normal HTTP interface to support everything that was in the RPC interface, and made things work in a standard way, so this is easier to support and keep in sync vs. supporting the old RPC interface as well. The operations equivalent to the RPC interface are in https://www.consul.io/docs/agent/http/agent.html and https://www.consul.io/docs/agent/http/operator.html#keyring.
