### ISSUE TITLE
DNS resolution does not work on vault service when querying from accross DC

### ISSUE THREAD

**Issue by rbrutas** [hashicorp/consul#2804]
Client: v0.7.5
Server: v0.7.5

on the same dc i can query dns fine;

$ dig vault.service.consul +short
#.#.#.226
#.#.#.227
#.#.#.225
$ dig active.vault.service.consul +short
96.#.#.225

but when querying from across DC it doesn't work, however i can query the consul service and vault nodes;

$ dig consul.service.dc1.consul +short
#.#.#.137
#.#.#.136
#.#.#.138

$ dig vault-stage-dc1.node.dc1.consul +short
#.#.#.227

but does NOT return anything for vault service;

dig vault.service.dc1.consul
dig active.vault.service.dc1.consul

**Comment by slackpad** [comment]
Hi @rbrutas did you figure this out? I can't think of anything that would cause this if you have the WAN connection set up, which is looks like you do. It could be possibly be ACLs if your agents in DC2 don't have a token w/read access to the "vault" service.

**Comment by slackpad** [comment]
Closing this as we never heard back - please let us know if you still need help.
