### ISSUE TITLE
Getting repeated: "memberlist: Push/Pull" errors

### ISSUE THREAD

**Issue by bitmask777** [hashicorp/consul#2811]
I'm seeing the following line repeatedly in the Consul logs:

`2017/03/10 10:40:41 [ERR] memberlist: Push/Pull with *hostnameRemoved* failed: dial tcp *ipRemoved*:8301: i/o timeout`

However, the node is green in the Consul UI and serf health status reports "agent alive and reachable" .

Should this be cause for concern, or can I safely ignore these messages?

Thanks,
Robert

**Comment by ChipV223** [comment]
Hi @bitmask777 !

Sorry no one has responded to you. That particular error message could point to a number of issues related to the network. I'm going to try to broadly point to some options, but I understand that it may not resolve your particular issue (noticing a lot of folks are following this thread).

 * This is the [Serf LAN port](https://www.consul.io/docs/agent/options#serf_lan_port) so I'd check that you're binding to the appropriate interface for that. I'd expect this to be the private IP in most scenarios. I would also recommend check if the [Serf WAN port](https://www.consul.io/docs/agent/options#serf_wan_port) as well as the [other required ports](https://www.consul.io/docs/install/ports) are available for both outgoing and incoming traffic

* Ensure the machines in question can handle network traffic they are experiencing, and that they are not constrained by CPU usage on the machine. Not being able to respond to network call this could be either of those.

* Use go-sockaddr syntax, which Consul supports, to bind to the write interface in an environment where your network interfaces are dynamic or less well known. See #4090 for a known issue to expand the docs on that.
