### ISSUE TITLE
Unable to remove nodes from clusters. Bring back the damned peers.json file

### ISSUE THREAD

**Issue by ThatJames** [hashicorp/consul#2817]
Consul is unable to enter a leadership mode as there are "dead" peers it tries to connect to. Unable to use the consul operator command as it requries a leader.

Consul version 0.7.3

**Comment by snowsky** [comment]
Have you tried force-leave on nodes?

**Comment by slackpad** [comment]
Hi @ThatJames you are correct that the operator commands only work if you have a leader. If not, the peers.json recovery method is still available - it's documented here:

https://www.consul.io/docs/guides/outage.html#manual-recovery-using-peers-json
