### ISSUE TITLE
feature request: NAT traversal

### ISSUE THREAD

**Issue by zh99998** [hashicorp/consul#2831]
currently consul seems can't work in network environment behind NATP.

**Comment by jhmartin** [comment]
A core design requirement of Consul is that each agent be able to directly reach each other agent for purposes of gossiping and healthchecking. NAT is incompatible with that.

**Comment by slackpad** [comment]
Consul 0.8 added support for "network areas" which help with this at the WAN level - see https://www.consul.io/docs/guides/areas.html. We also support some basic address translation via https://www.consul.io/docs/agent/options.html#translate_wan_addrs.
