### ISSUE TITLE
Too many open connections (files) on Consul agent process. Adds about 500 daily, eventually leading to Consul crash

### ISSUE THREAD

**Issue by bufhall** [hashicorp/consul#2836]
### `consul version` for both Client and Server
Client: `Consul v0.7.5`
Server: `Consul v0.7.5`
### Operating system and Environment details
ubuntu v14
### Description of the Issue (and unexpected/desired result)
The Consul Agents gain about 500 new open connections daily as determined by lsof -p {console agent}
After about 2 1/2 days consul crashes due to reaching its open file limit of 1024.
Analyzing the open files there are hundreds of open connections like the following as determine by lsof -p. 
consul  31286 root  280u  IPv6 143415038      0t0    TCP ip-xx-xx-x-xxx.region.instance.consul:8500->ip-yy-yy-y-yyy.region.instance.nomad:36054 (ESTABLISHED)

the server that consul has open connections to is a nomad client server instance.

### Reproduction steps
restart consul after 2 1/2 days will result in too many open files.

### Log Fragments or Link to [gist](https://gist.github.com/)
lsof -p {console agent}
consul  31286 root  280u  IPv6 143415038      0t0    TCP ip-xx-xx-x-xxx.region.instance.consul:8500->ip-yy-yy-y-yyy.region.instance.nomad:36054 (ESTABLISHED)
...

**Comment by slackpad** [comment]
Hi @bufhall does it look to you like the connections are coming from Nomad itself for its integration with Consul? What version of Nomad is running?

**Comment by bufhall** [comment]
See example connections that are stuck open and growing daily. This is generated by running lsof -p on consul server against agent process. The nomad version is v0.5.4. In the connections below ip-10-15-1-251 is the consul server and ip-10-15-1-184 is the nomad client.

consul  31286 root   81u  IPv6 143427120      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:47650 (ESTABLISHED)
consul  31286 root   82u  IPv6 143425258      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:52423 (ESTABLISHED)
consul  31286 root   83u  IPv6 143426520      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:33065 (ESTABLISHED)
consul  31286 root   84u  IPv6 143426480      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:57712 (ESTABLISHED)
consul  31286 root   85u  IPv6 143425299      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:55756 (ESTABLISHED)
consul  31286 root   87u  IPv6 143426483      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:57748 (ESTABLISHED)
consul  31286 root   88u  IPv6 143426571      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:37040 (ESTABLISHED)
consul  31286 root   89u  IPv6 143426756      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:51390 (ESTABLISHED)
consul  31286 root   91u  IPv6 143427732      0t0    TCP ip-10-15-1-251.cn-north-1.compute.internal:8500->ip-10-15-1-184.cn-north-1.compute.internal:37423 (ESTABLISHED)

**Comment by bufhall** [comment]
We can close this issue. A micro service running from the nomad client was making a connection to Consul without closing the connection.

**Comment by slackpad** [comment]
Thanks for the follow up and glad you narrowed it down!
