### ISSUE TITLE
Specify disable_update_check in commandline parameters

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/consul#2838]
### `consul version` for both Client and Server
Client: `Consul v0.7.5`
Server: `Consul v0.7.5`

### Operating system and Environment details
Linux: Debian 8 x86_84, CentOS 7

### Description of the Issue (and unexpected/desired result)
With reference to:
https://www.consul.io/docs/agent/options.html#disable_update_check

Is it possible to specify the disable update check via cmd line parameters?

* I have a use case where the Consul clients are started using cmd line arguments rather than a config file.

Regards,
Shantanu

**Comment by slackpad** [comment]
Hi @shantanugadgil this is currently only available via config files.

**Comment by slackpad** [comment]
We currently don't have plans to add this but would welcome a PR for it. Thanks!

**Comment by DmitryFromDubna** [comment]
Hello, is it possible to disable automatic updates for Consul by specifying CHECKPOINT_DISABLE environment variable? Thank you!
