### ISSUE TITLE
Make force-leave more proactive

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#2841]
We should set things up so that if the agent is still around and a `force-leave` is done, the agent will actually leave the cluster. Right now if you `force-leave` a dead agent everything is fine, but if the agent is still alive it'll come back, which is not what operators expect.

**Comment by vincentshow** [comment]
@slackpad Which version this feature will be supported in?

**Comment by slackpad** [comment]
@vincentshow this currently isn't planned. I think a lot of the need for this is eliminated by https://www.consul.io/docs/guides/autopilot.html#dead-server-cleanup, which gets rid of the need to force-leave servers.

**Comment by slackpad** [comment]
I'm thinking we won't add any more complexity here, closing this out.
