### ISSUE TITLE
 Nodes in the same datacenter should be on a single LAN.

### ISSUE THREAD

**Issue by wangping886** [hashicorp/consul#2851]
why  for the datacenter NYC3's client and server everyone has a different public IP in https://demo.consul.io/ui/#/nyc3/nodes.

**Comment by slackpad** [comment]
Hi @wangping886 that's just an artifact about how these demo machines are set up. You are correct that usually you'd have a private network for the LAN.

**Comment by wangping886** [comment]
If my  client and  server will don't have public ip but in the same datacenter.  Can i deploy client and  server in different public ip ?if allow,i start my every ageny by -bind public ip ?as my webserver is in different public ip.

**Comment by wangping886** [comment]
Don't  have  the same public ip

**Comment by slackpad** [comment]
You could bind Consul to the public IP, or you could provide the public IP of your web server as the `Address` when you define your service - https://www.consul.io/docs/agent/http/agent.html#agent_service_register. The `Address` lets you specify an address for your service that's different from where Consul is listening.
