### ISSUE TITLE
API: Connections to API Endpoints Remain in established state.

### ISSUE THREAD

**Issue by jrasell** [hashicorp/consul#2852]
### `consul version` for both Client and Server
Client: `0.7.5`
Server: `0.7.5`

### Operating system and Environment details
Issue was reproduced both locally running dev flag (mac) and on a "cloud" cluster running Debian8 with full configuration setup.

### Description of the Issue (and unexpected/desired result)
When hitting the Consul API through the Golang client the established TCP connection is never closed. This results in the application exponentially increasing the number of go routines in use as well as the number of established TCP connections between the application and consul.

The desired result is that we are able to frequently poll the API, and once the response is returned, the TCP connection is closed.

### Reproduction steps
The following go code snippet will create the ConsulClient and hit an arbitrary endpoint, then printing out the response and the number of go routines running whilst running on a loop:
```shell
package main

import (
	"fmt"
	"runtime"
	"strconv"

	consul "github.com/hashicorp/consul/api"
)

func test() {
	config := consul.DefaultConfig()
	config.Address = "localhost:8500"
	c, _ := consul.NewClient(config)

	resp, _ := c.Status().Leader()
	fmt.Printf("%v\n", resp)
	fmt.Printf("%v\n", strconv.FormatInt(int64(runtime.NumGoroutine()), 10))
}

func main() {
	for {
		test()
	}
}
```

Running above code snippet I get to 7348 go routines before the application crashes.

### Log Fragments
Print statement fragment from running the code snippet above after a number of runs:
```
127.0.0.1:8300
746
127.0.0.1:8300
748
127.0.0.1:8300
750
127.0.0.1:8300
752
127.0.0.1:8300
754
127.0.0.1:8300
756
127.0.0.1:8300
758
```

`lsof -i` sample output:
```
replicato 27653 rasellj  541u  IPv4 0x6eb924c94e7170d9      0t0  TCP localhost:54660->localhost:fmtp (ESTABLISHED)
replicato 27653 rasellj  542u  IPv4 0x6eb924c94c008d99      0t0  TCP localhost:54663->localhost:fmtp (ESTABLISHED)
replicato 27653 rasellj  543u  IPv4 0x6eb924c94e3e4f39      0t0  TCP localhost:54668->localhost:fmtp (ESTABLISHED)
replicato 27653 rasellj  544u  IPv4 0x6eb924c94f9f9f39      0t0  TCP localhost:54672->localhost:fmtp (ESTABLISHED)
replicato 27653 rasellj  545u  IPv4 0x6eb924c94f22fa59      0t0  TCP localhost:54678->localhost:fmtp (ESTABLISHED)
replicato 27653 rasellj  546u  IPv4 0x6eb924c94f9fe669      0t0  TCP localhost:54680->localhost:fmtp (ESTABLISHED)
```

**Comment by slackpad** [comment]
Hi @jrasell closing this out based on the discussion on #2853. There's a configuration that doesn't reuse connections (https://github.com/hashicorp/consul/blob/master/api/api.go#L202-L209):

```
// DefaultNonPooledConfig returns a default configuration for the client which
// does not pool connections. This isn't a recommended configuration because it
// will reconnect to Consul on every request, but this is useful to avoid the
// accumulation of idle connections if you make many client objects during the
// lifetime of your application.
func DefaultNonPooledConfig() *Config {
	return defaultConfig(cleanhttp.DefaultTransport)
}
```

I think using that with your API client should give you the behavior you are after.
