### ISSUE TITLE
is  acl_master_token support changing by modify acl_master_token in config.json?

### ISSUE THREAD

**Issue by wangping886** [hashicorp/consul#2863]
consul version for both Client and Server

Server: Consul v0.7.5

The acl_master_token is only installed when a server acquires cluster leadership. If you would like to install or **change the acl_master_token,** set the new value for acl_master_token in the configuration for all servers .  
is it support changing? when i change  the  acl_master_token  in my config.json ,the old   acl_master_token and new  acl_master_token will exist

**Comment by slackpad** [comment]
Hi @wangping886 please see https://www.consul.io/docs/guides/acl.html#enabling-acls, specifically:

> Bootstrapping the ACL system is done by providing an initial acl_master_token which will be created as a "management" type token if it does not exist. The acl_master_token is only installed when a server acquires cluster leadership. If you would like to install or change the acl_master_token, set the new value for acl_master_token in the configuration for all servers. Once this is done, restart the current leader to force a leader election.

You currently have to force a leader election to get the change to take effect.
