### ISSUE TITLE
Recommend retry_join explicitly in docs

### ISSUE THREAD

**Issue by nh2** [hashicorp/consul#2867]
I just lost a lot of time in my automatic deployment because I accidentally used `start_join` instead of `retry_join`: because the machines don't come up all at perfectly the same time (join race condition), I ended up with:

```
raft: no known peers, aborting election
```

and

```
agent: failed to sync remote state: No cluster leader
```

* Please add to the [docs of `start_join`](https://www.consul.io/docs/agent/options.html#start_join) something like
  > For automatic deployments, `retry_join` might be more appropriate.
* Please add to the [docs of `-join`](https://www.consul.io/docs/agent/options.html#_join) something like
  > For automatic deployments, `-retry-join` might be more appropriate.
* Please add to https://www.consul.io/docs/guides/bootstrapping.html a mention of `retry_join`.

Thanks!

**Comment by slackpad** [comment]
Sorry for the lost time and thanks for the suggestions - this is a good idea!
