### ISSUE TITLE
Feature: Service check flap detection

### ISSUE THREAD

**Issue by therealgambo** [hashicorp/consul#2890]
#### Feature

Occasionally we have services where their states are flapping causing slight disruptions to the overall availability of our platform. From what I can see Consul doesn't provide any flap detection (Please correct me if I'm wrong) at the moment for service health checks.

It would be an excellent feature for Consul to have, seeing as (if configured) most services will have health checks configured with Consul, putting it in the ideal position for it to handle flap detection.

When services health checks are registered, one could simply provide the flap-threshold and time-span on which it needs to exceed before the service is marked as critical. The same threshold and time-span could also be used to indicate when a service is no longer flapping, marking the service as passing.

I'm not sure how up to date this document is, but [this is how Nagios tackles it.](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/flapping.html)

**Comment by rajendrakumara** [comment]
Any idea when this enhancement is going to be part of consul.

Thanks

**Comment by rhamon** [comment]
Any eyes still on this?
Cheers!

**Comment by thepolina** [comment]
+1

**Comment by Wing924** [comment]
+1

**Comment by wangke1020** [comment]
+1

**Comment by rhamon** [comment]
bump

**Comment by h4m24** [comment]
+1

**Comment by matusvalo** [comment]
+1

**Comment by ajaajalee** [comment]
+1

**Comment by donparapidos** [comment]
+1

**Comment by rhamon** [comment]
+1

**Comment by mdbecker** [comment]
+1

**Comment by scrichar** [comment]
@kyhavlov when is this gonna be in consul, cause i need it, and you are the best and stuffffff, do you take bribes ?

**Comment by unicell** [comment]
Wondering with https://github.com/hashicorp/consul/pull/5739 if that satisfies all the original ask. Shipped in Consul 1.7 I believe.

https://www.consul.io/docs/agent/checks.html#success-failures-before-passing-critical

**Comment by therealgambo** [comment]
I believe it should @unicell - Thanks for the update.
