### ISSUE TITLE
Can type CatalogNode be changed to embed type ServiceEntry instead?

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2902]
The current struct:

type CatalogNode struct {                                                                                                              
     Node     *Node                                                                                                                     
     Services map[string]*AgentService                                                                                                  
} 

didn't group service by instances and neither include the checks info.

changing to below one would be much more convenient:

type CatalogNode struct {                                                                                                              
     Node     *Node                                                                                                                     
     Services map[string]*ServiceEntry                                                                                                 
} 

of course a new ServiceEntry type excluding the Node field needs to be introduced in this case

**Comment by slackpad** [comment]
Hi @hehailong5 this would involve a deeper change in Consul itself because not all the node endpoints return the checks. Are there particular API operations you were looking to work this way?

**Comment by hehailong5** [comment]
I have to issue a health query to get the checks info when the node watch return.  this would do anyway at least. never mind.
