### ISSUE TITLE
no WAN support for GCE join

### ISSUE THREAD

**Issue by lobeck** [hashicorp/consul#2907]
There seems to be no support for WAN joining when using RetryJoinGCE.

I've already documented this here: https://groups.google.com/forum/#!searchin/consul-tool/gce|sort:date/consul-tool/ak-1Lq6uCfo/ZDHOoKj-CwAJ

After another look through the code, there seems to be no support for it yet. The data retrieved from GCE is just passed into JoinLAN, but nothing WAN related is attempted.

So the nodes will just ignore other nodes with a different DC value and you'll end up with separated clusters.

Manually passing the server IPs to join_wan is also no option, as the nodes are automatically managed and therefore not easily retrievable. Setting up loadbalancers with target pools is also not feasible, as this would require one loadbalancer per region and too much overhead.

**Comment by slackpad** [comment]
Hi @lobeck that's correct - we need to sweep through all the cloud joiners and add WAN support (we will likely refactor a bit and make them work more like plugins so we don't have to duplicate code). The WAN join flooding feature added in 0.8 helps in the short term:

> WAN Join Flooding: A new routine was added that looks for Consul servers in the LAN and makes sure that they are joined into the WAN as well. This catches up up newly-added servers onto the WAN as soon as they join the LAN, keeping them in sync automatically. [GH-2801]

But you are right - we need to find the servers via the APIs and WAN join them to get the initial joins to work, and to make things simple to operate.

**Comment by lobeck** [comment]
Great! Thanks for the quick response on this. The join flooding sounds like a possible workaround for now, but i guess it won't work, as the nodes will get filtered due to not matching DCs. But i'll give it a try.

**Comment by slackpad** [comment]
The join flooding is specifically designed with the WAN in mind. Basically if you orchestrate an initial WAN join between two DCs, it'll make server _every_ server in each local DC is WAN-joined as well. This means you can add new servers on either side and they will get WAN-joined by their peer servers on the LAN.

**Comment by lobeck** [comment]
Sounds great, just need to find a proper way to do the initial join, as all clusters are instances groups and i therefore have no immediate control over them.

But the concept sounds awesome.

**Comment by slackpad** [comment]
This was added via https://github.com/hashicorp/consul/pull/3406.
