### ISSUE TITLE
Consul log error

### ISSUE THREAD

**Issue by Rameshera** [hashicorp/consul#2913]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`

Consul v0.7.4
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

Server: `[server version here]`

Consul v0.7.4
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

### Description of the Issue (and unexpected/desired result)

Consul agent unable to sync and getting below logs from consul. Can you please suggest.

 tail -f /var/log/consul
    2017/04/14 18:00:12 [INFO] agent: Synced check 'cb2f7ea8b44bc73372ae4672fc3532b2dda32b2c'
    2017/04/14 18:00:13 [INFO] agent: Deregistered service '_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance'
    2017/04/14 18:00:13 [INFO] agent: Deregistered check '7324a7783e0edf66299086ff2edfdfb061635360'
    2017/04/14 18:00:13 [INFO] agent: Deregistered check 'cb2f7ea8b44bc73372ae4672fc3532b2dda32b2c'
    2017/04/14 18:00:17 [INFO] agent: Synced service '_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance'
    2017/04/14 18:00:17 [INFO] agent: Synced check '7324a7783e0edf66299086ff2edfdfb061635360'
    2017/04/14 18:00:17 [INFO] agent: Synced check 'cb2f7ea8b44bc73372ae4672fc3532b2dda32b2c'
    2017/04/14 18:00:18 [INFO] agent: Deregistered service '_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance'
    2017/04/14 18:00:18 [INFO] agent: Deregistered check '7324a7783e0edf66299086ff2edfdfb061635360'
    2017/04/14 18:00:18 [INFO] agent: Deregistered check 'cb2f7ea8b44bc73372ae4672fc3532b2dda32b2c'
    2017/04/14 18:00:22 [INFO] agent: Synced service '_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance'
    2017/04/14 18:00:22 [INFO] agent: Synced check '7324a7783e0edf66299086ff2edfdfb061635360'
    2017/04/14 18:00:22 [INFO] agent: Synced check 'cb2f7ea8b44bc73372ae4672fc3532b2dda32b2c'
    2017/04/14 18:00:23 [INFO] agent: Synced check '7324a7783e0edf66299086ff2edfdfb061635360'
    2017/04/14 18:00:23 [INFO] agent: Deregistered service '_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance'
    2017/04/14 18:00:23 [INFO] agent: Deregistered check '7324a7783e0edf66299086ff2edfdfb061635360'
    2017/04/14 18:00:23 [INFO] agent: Deregistered check 'cb2f7ea8b44bc73372ae4672fc3532b2dda32b2c'
    2017/04/14 18:00:27 [INFO] agent: Synced service '_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance'
    2017/04/14 18:00:27 [INFO] agent: Synced check 'cb2f7ea8b44bc73372ae4672fc3532b2dda32b2c'
    2017/04/14 18:00:27 [INFO] agent: Synced check '7324a7783e0edf66299086ff2edfdfb061635360'

**Comment by slackpad** [comment]
Hi @Rameshera - this might be better to file over in Nomad - it looks like a possible issue with the Consul integration there, and I know there's some ongoing work to improve that right now.

**Comment by Rameshera** [comment]
Thanks for quick response!!! 

i have 3 nodes in the cluster and running nomad consul and vault. I have self signed certificates in master and copied over to other nodes. master is working fine but other two servers and getting consul errors as mentioned above.

**Comment by Rameshera** [comment]
I tried to deregister but nu luck. Also identified, no nomad jobs are running but nomad is trying to connect config server. not sure why it is trying continuously. Below are th elogs:


tail -f /var/log/nomad
   2017/04/14 18:08:53.873931 [ERR] client.consul: error reaping services in consul: 1 error(s) occurred:

* Put http://127.0.0.1:8500/v1/agent/service/deregister/_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
   2017/04/14 18:09:01.091359 [ERR] client.consul: error reaping services in consul: Get http://127.0.0.1:8500/v1/agent/services: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
   2017/04/14 18:09:01.807311 [INFO] fingerprint.consul: consul agent is unavailable
   2017/04/14 18:09:01.815667 [INFO] client: node registration complete
   2017/04/14 18:09:08.947520 [ERR] client.consul: error reaping services in consul: Get http://127.0.0.1:8500/v1/agent/services: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
   2017/04/14 18:09:17.848840 [INFO] fingerprint.consul: consul agent is available
   2017/04/14 18:09:18.734137 [INFO] client: node registration complete
   2017/04/14 18:09:30.045290 [ERR] client.consul: error reaping services in consul: Get http://127.0.0.1:8500/v1/agent/services: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
^C
[root@tdigweblogic027 anchors]# curl http://127.0.0.1:8500/v1/agent/services
{"_nomad-client-nomad-client-http":{"ID":"_nomad-client-nomad-client-http","Service":"nomad-client","Tags":["http"],"Address":"10.24.96.29","Port":4646,"EnableTagOverride":false,"CreateIndex":0,"ModifyIndex":0},"_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance":{"ID":"_nomad-executor-bc367d88-cbf1-8cd4-c9ab-637bba610887-instance-config-server-instance-config-instance","Service":"config-server-instance","Tags":["config-instance"],"Address":"10.24.96.29","Port":8887,"EnableTagOverride":false,"CreateIndex":0,"ModifyIndex":0},"_nomad-server-nomad-http":{"ID":"_nomad-server-nomad-http","Service":"nomad","Tags":["http"],"Address":"10.24.96.29","Port":4646,"EnableTagOverride":false,"CreateIndex":0,"ModifyIndex":0},"_nomad-server-nomad-rpc":{"ID":"_nomad-server-nomad-rpc","Service":"nomad","Tags":["rpc"],"Address":"10.24.96.29","Port":4647,"EnableTagOverride":false,"CreateIndex":0,"ModifyIndex":0},"_nomad-server-nomad-serf":{"ID":"_nomad-server-nomad-serf","Service":"nomad","Tags":["serf"],"Address":"10.24.96.29","Port":4648,"EnableTagOverride":false,"CreateIndex":0,"ModifyIndex":0},"consul":{"ID":"consul","Service":"consul","Tags":[],"Address":"","Port":8300,"EnableTagOverride":false,"CreateIndex":0,"ModifyIndex":0},"vault:10.24.96.29:8200":{"ID":"vault:10.24.96.29:8200","Service":"vault","Tags":["standby"],"Address":"10.24.96.29","Port":8200,"EnableTagOverride":false,"CreateIndex":0,"ModifyIndex":0}}[root@tdigweblogic027 anchors


Can any one please advise? 
Thanks,
Ramesh

**Comment by Rameshera** [comment]
Restarted the node and clear the consul logs. :)
