### ISSUE TITLE
watch on v1/catalog/node/<node> will return per any changes on other nodes

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2927]
I remember the v1/catalog/service/<service> also have the same issue in old release. same would be required to fix this one.

**Comment by slackpad** [comment]
Hi @hehailong5 are you still seeing this in Consul 0.7.3 and later? This was fixed in that release.

**Comment by hehailong5** [comment]
yes, it was happening in 0.7.5

**Comment by slackpad** [comment]
Do you have any more details? With the changes in 0.7.3 you should not get extra wakeups for changes to existing nodes. There are some cases where adding or removing nodes could cause wakeups still. Do you have a lot of nodes coming and going?

**Comment by hehailong5** [comment]
Hi,

We found only using Go Api would reproduce this issue, both for service and node endpoints. sending query URL via postman didn't see this. So I guess you guys forgot fixing the go apis accordingly.

**Comment by slackpad** [comment]
Interesting - @hehailong5 can you provide a small sample of how you are setting up the query using the Go API?

**Comment by hehailong5** [comment]
`func (n *Node) StartWatch(outCh chan<- map[string]*consulapi.AgentService) {

        queryOptions := &consulapi.QueryOptions{
                WaitIndex: 0,
                WaitTime:  n.waitTime * time.Second,
        }

        for {
                select {
                case <-n.stopCh:
                        n.log.Infof("[%s]Recieve message on the stopCh, return from Node watcher", n.nodeName)
                        return
                default:
                }

                n.log.Infof("[%s]Start to watch node endpoint", n.nodeName)
                out, qm, err := agt.WatchNode(n.nodeName, queryOptions)
                n.log.Infof("[%s]Watch node return", n.nodeName)

                if err != nil {
                        n.log.Errorf("[%s]Watch node returned with error:%v", n.nodeName, err)
                        n.ErrCh <- err
                        return
                }

                n.log.Infof("[%s]Send node to upstream", n.nodeName)
                timeAfter := time.NewTimer(time.Duration(n.upstreamTimeOut) * time.Second)
                select {
                case outCh <- out.Services:
                        n.log.Infof("[%s]Node was sent to upstream", n.nodeName)
                        queryOptions.WaitIndex = qm.LastIndex
                case <-timeAfter.C:
                        n.log.Warnf("[%s]Upstream has not fetched the node within %d seconds, abandon this change notification", n.nodeName,
n.upstreamTimeOut)
                }
                timeAfter.Stop()
        }

}

func (agent *Agent) WatchNode(nodeName string, queryOptions *consulapi.QueryOptions) (*consulapi.CatalogNode, *consulapi.QueryMeta, error) {
        var (
                err       error
                queryMeta *consulapi.QueryMeta
                node      *consulapi.CatalogNode
        )

        if agent.catalogEP == nil {
                return nil, nil, fmt.Errorf("Catalog endpoint is nil")
        }

        for {
                node, queryMeta, err = agent.catalogEP.Node(nodeName, queryOptions)
                if err != nil {
                        agent.logWriter.Errorf("Watch on catalog/node/%s returned with error:%v", nodeName, err)
                        return nil, nil, err
                }

                if queryMeta.LastIndex == queryOptions.WaitIndex {
                        continue
                }

                //              if len(node.Services) == 0 {
                //                      continue
                //              }

                break
        }
        return node, queryMeta, nil
}`

**Comment by hehailong5** [comment]
B.T.W, changes on node would cause the node list watch return also. the "changes" I made is simply adding a new service to a node.

**Comment by hehailong5** [comment]
Hi, looks like 0.8.3 fixed this.

**Comment by hehailong5** [comment]
Hi, as I mentioned before, the postman works fine when communicating with 0.7.5 server, the go client doesn't work. so I suspect the problem is in the consul api. but the testing proved me wrong, I compiled the go client with 0.8.3 and tested it with 0.7.5 server, the same still happened. looks like both go api and server need to be upgraded to fix this issue. is that the fact?

**Comment by slackpad** [comment]
> B.T.W, changes on node would cause the node list watch return also. the "changes" I made is simply adding a new service to a node.

Ah ok - adding a new service to a node can sometimes trigger a wakeup. The wakeup logic is done in the radix tree structure by tracking which nodes were changed in the tree, and adding and removing nodes can sometimes trigger changes to intermediate nodes (especially when there's not a lot of data in the tree, this tends to happen less often in trees with a lot of data). Since blocking queries will also time out after 10 minutes and return with no new data, the application is basically required to deal with the index not changing, so we opted to keep the algorithm simpler rather than add additional complexity to track adds and deletes (or filter on the server). If you see a spurious wakeup when an existing node is changed, that's definitely a bug, but if you see a spurious wakeup after an add/delete that's normal given how things are currently implemented.

**Comment by hehailong5** [comment]
Hi,

this was happening in 0.8.4 again, and the node watch was returned in the case that "queryMeta.LastIndex > queryOptions.WaitIndex" and the returned data is a empty list. 

b.t.w, there was no adding or deleting any node, we just add/delete services upon a given exiting node.

**Comment by hehailong5** [comment]
Hi,

in my testing, some nodes with different node names have same node meta, if consul takes node meta into consideration when waking up the watches?

**Comment by pearkes** [comment]
Modifying node metadata should return trigger for watches against a node. With that in mind I will close this as I believe that is what is causing it to return in your case.
