### ISSUE TITLE
ignore agent flag ??

### ISSUE THREAD

**Issue by godjil** [hashicorp/consul#2935]
hostname -f
nginx.dev.crm.rambler.tech

pgrep -fla consul
6669 /usr/bin/consul agent -config-dir=/etc/consul -pid-file=/var/run/consul.pid -dev -bind=10.16.13.203 -data-dir=/var/lib/consul -ui-dir=/var/lib/consul_ui -datacenter crm_dev -disable-host-node-id

 /etc/consul/consul-ui.json 
{
  "addresses": {
    "http": "127.0.0.1"
  }
}

cat /etc/consul/client.json    

{
  "log_level": "DEBUG",
  "server": false,
  "disable_update_check": true
}

 /etc/consul/server.json 

{
    "start_join" : [
        "consul00.dev.crm.rambler.tech:8301",
        "consul01.dev.crm.rambler.tech:8301",
        "consul02.dev.crm.rambler.tech:8301"
    ]
}

consul members
Node                            Address            Status  Type    Build  Protocol  DC
back.dev.crm.rambler.tech       10.16.13.208:8301  alive   server  0.8.1  2         crm_dev
bstat.dev.crm.rambler.tech      10.16.13.12:8301   alive   server  0.8.1  2         crm_dev
db10.dev.crm.rambler.tech       10.16.64.159:8301  alive   server  0.8.1  2         crm_dev
front.dev.crm.rambler.tech      10.16.13.236:8301  alive   server  0.8.1  2         crm_dev
kassa-api.dev.crm.rambler.tech  10.16.13.162:8301  alive   server  0.8.1  2         crm_dev
nadelyaev.dev.crm.rambler.tech  10.16.13.138:8301  alive   server  0.8.1  2         crm_dev
nginx.dev.crm.rambler.tech      10.16.13.203:8301  alive   server  0.8.1  2         crm_dev
queue.dev.crm.rambler.tech      10.16.13.235:8301  alive   server  0.8.1  2         crm_dev
rakhaev.dev.crm.rambler.tech    10.16.13.139:8301  alive   server  0.8.1  2         crm_dev
storage.dev.crm.rambler.tech    10.16.13.243:8301  alive   server  0.8.1  2         crm_dev
subs.dev.crm.rambler.tech       10.16.13.237:8301  alive   server  0.8.1  2         crm_dev

**Comment by slackpad** [comment]
Hi the flag that's getting you is `-dev`. That always puts the agent in server mode and is designed to quickly stand up a server for development. Hope that helps!
