### ISSUE TITLE
Deleting a content of a root folder in KV store removes the folder itself too

### ISSUE THREAD

**Issue by IevgenKabanets** [hashicorp/consul#2941]
To clarify the description of a bug, here's how we _design_ the layout of KV store we use:
`v1/kv/apps/<app_name>/<key>`
or 
`v1/kv/apps/<app_name>/<some_folder>/<key>`
Here, **root** folder is `apps`, which contains KVs for apps. 

### Operating system and Environment details
Run on Swarm cluster in coreOS.

### Description of the Issue (and unexpected/desired result)
When attempting to delete `/v1/kv/apps/<app_name>` using either _golang API_ (aka `kv.Delete(key)` or `kv.DeleteTree(prefix)`) or plain _cURL_ with -XDELETE on `v1/kv/apps/<app_name>/?recurse`, we end up with whole `/v1/kv/apps/` being deleted. 

Weirdly enough, it works from UI with _"Delete folder"_. But when capturing requests to Consul UI, resulting cURL looks exactly the same:
`curl -i -XDELETE 'http://localhost:8500/v1/kv/apps/<app_name>/?recurse'`
But when run from terminal - removes whole `/apps` folder, not `/apps/<app_name>`.

### Expected result
Removal of a nested folder and its content, not the whole root folder.

### Reproduction steps
cURL or wrap around Consul golang API.

### `consul version` for both Client and Server
`0.8.1`

### `consul info` for both Client and Server
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 'e9ca44d
	version = 0.8.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.0.0.5:8300
	server = true
raft:
	applied_index = 13269
	commit_index = 13269
	fsm_pending = 0
	last_contact = 18.667161ms
	last_log_index = 13269
	last_log_term = 7
	last_snapshot_index = 8194
	last_snapshot_term = 7
	latest_configuration = [{Suffrage:Voter ID:10.0.0.7:8300 Address:10.0.0.7:8300} {Suffrage:Voter ID:10.0.0.4:8300 Address:10.0.0.4:8300} {Suffrage:Voter ID:10.0.0.5:8300 Address:10.0.0.5:8300} {Suffrage:Voter ID:10.0.0.6:8300 Address:10.0.0.6:8300} {Suffrage:Voter ID:10.0.0.3:8300 Address:10.0.0.3:8300}]
	latest_configuration_index = 77
	num_peers = 4
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 7
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 96
	max_procs = 4
	os = linux
	version = go1.8.1
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 4
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 4
	members = 6
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 13
	members = 6
	query_queue = 0
	query_time = 1
```

**Comment by slackpad** [comment]
Hi @IevgenKabanets Consul really doesn't have a first-class notion of folders, keys just have a prefix and some of the APIs can work with a "/" separator. It looks like you are creating `apps/<app_name>/<some_folder>/<key>` so there aren't actually any intermediate "folder" keys. If you create `apps/` and `apps/<app_name>/` keys with empty values as "folder" keys, then things should work as you expect.

**Comment by slackpad** [comment]
Please let me know if that didn't work. Closing this out for now.

**Comment by IevgenKabanets** [comment]
@slackpad we used, as I've put in description, exactly the layout of 
`apps/<app_name>/keys`.
End goal - remove `/<app_name>/key{1,2,3}`, not the whole `/apps`.

And would be nice to understand why UI works, while same curl request - won't.

**Comment by slackpad** [comment]
Hi @IevgenKabanets I can't tell from the layout if you created an `apps/` key or just made `apps/<app_name>/<some_folder>/<key>` directly - that's the crucial difference. If you just did the latter then there is no "folder" for `apps/`, since Consul doesn't really track folders, and it will look like the lower-level delete will blow away the root folder. If you separately create the `apps/` it should not get removed by the lower-level delete.
