### ISSUE TITLE
restarting servers with new `acl_master_token` value does not deprecate access via old master token

### ISSUE THREAD

**Issue by jf** [hashicorp/consul#2942]
As per subject. I am using the latest 0.8.1, just testing this on 3 servers right now.

### `consul info`

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 'e9ca44d
	version = 0.8.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = ip-for-server-1:8300
	server = true
raft:
	applied_index = 267126
	commit_index = 267126
	fsm_pending = 0
	last_contact = 71.634045ms
	last_log_index = 267126
	last_log_term = 80
	last_snapshot_index = 262154
	last_snapshot_term = 61
	latest_configuration = [{Suffrage:Voter ID:ip-for-server-1:8300 Address:ip-for-server-1:8300} {Suffrage:Voter ID:ip-for-server-3:8300 Address:ip-for-server-3:8300} {Suffrage:Voter ID:ip-for-server-2:8300 Address:ip-for-server-2:8300}]
	latest_configuration_index = 2356
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 80
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 76
	max_procs = 2
	os = linux
	version = go1.8.1
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 47
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 139
	members = 5
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Ubuntu 16.04

### Description of the Issue (and unexpected/desired result)

https://www.consul.io/docs/guides/acl.html says that "If you would like to install or change the acl_master_token, set the new value for acl_master_token in the configuration for all servers. Once this is done, restart the current leader to force a leader election."

I've done this already, and while the new `acl_master_token` does get recognized, I can also use the **old** value for `acl_master_token` to run commands like `consul members` too. _In fact_, each change in `acl_master_token` seems to only add to the list of acceptable master tokens. I am not expecting this, and I do not think that this is / should be expected too.

### Reproduction steps

1. set up 3 servers in a cluster, with the following

`/usr/local/bin/consul agent -server -data-dir=/var/consuldata -node=<nodename> -config-dir=/etc/consul.d -datacenter=some-dc-name`

/etc/consul.d/server.json:
```
{
	"bootstrap_expect": 3,
	"start_join": ["ip-for-server-1", "ip-for-server-2", "ip-for-server-3"],

	"acl_datacenter": "some-dc-name",
	"acl_default_policy": "deny",
	"acl_down_policy": "extend-cache"
}
```

/etc/consul.d/acl-master-token.json:
```
{ "acl_master_token": "some token value" }
```

2. Try running `consul members` and you should see that the ACLs are in effect. Verify that `consul members -token="some token value"` it works.

3. verify that `consul members -token="next token value"` does *not* work

4. edit `/etc/consul.d/acl-master-token.json` on all servers to change the token value to "next token value", and restart all servers

5. Verify that `consul members -token="some token value"` **still** works. Now verify that `consul members -token="next token value"` works too.

**Comment by slackpad** [comment]
Hi @jf this is currently working as designed, though we definitely should make the documentation more clear. Right now we don't have enough information to automatically deprecate the old master token, and if we did it would probably take folks by surprise who are trying to rotate the token. As things are implemented now, you'd need to delete the old master token using the ACL API in order to fully revoke it.

**Comment by jf** [comment]
I see. Thanks, @slackpad for explaining!

**Comment by jsosulska** [comment]
Provided feedback to the Education team to update the bootstrap guide to highlight deleting the master token during the guide.

**Comment by jsosulska** [comment]
Closing this topic. Needed last step to the workflow jf posted is to delete the token [via API](https://www.consul.io/api-docs/acl/tokens#delete-a-token
)
