### ISSUE TITLE
RFC: maintenance mode for a service across all nodes

### ISSUE THREAD

**Issue by steve-jansen** [hashicorp/consul#2943]
As an operator of a Nomad cluster using Consul for service discovery between applications, I would like the ability to place all instances of the `foo` service into maintenance mode across all current and future nodes so that I can temporarily return an empty list of service instances from discovery queries (DNS, catalog API, etc)

The [`consul maint`CLI command](https://www.consul.io/docs/commands/maint.html) and [agent API for maintenance](https://www.consul.io/api/agent.html) is scoped to a node today.  This doesn't make as much sense as we move from VMs running specific services/roles, toward a Nomad cluster with varied services on each node.   Moreover, services may hop nodes in our Nomad cluster for a variety of reasons: auto-scaling of hosts, blue/green host deploys.   Setting maintenance mode on a specific service/node combination seems futile in this context of Nomad.

Is it practical and valuable to allow maintenance mode at the scope of an entire node, a specific node/service combination, and also a service across all nodes?

**Comment by steve-jansen** [comment]
May relate to #786.

**Comment by slackpad** [comment]
I'll /cc @magiconair on this one as he's been thinking about some more dynamic ways to change state centrally in the catalog vs. having the agents drive all the changes. This is a good use case to think about.

**Comment by i0rek** [comment]
I  am going to close this with the very same comment from https://github.com/hashicorp/consul/issues/786#issuecomment-588918927:

> We haven't gotten around to do this one yet and I doubt we will in the future because it is not something that is frequently requested. If you want to provide a PR I would be happy to give you feedback!
