### ISSUE TITLE
Question about operator health check

### ISSUE THREAD

**Issue by jacob-koren** [hashicorp/consul#2944]
In the documentation, you listed the conditions for the server to be considered healthy. But you didn't specify if all conditions must be met or just some of them.
https://www.consul.io/docs/guides/autopilot.html#server-health-checking
I assume that the node considered healthy if ALL the conditions are met. Right?

**Comment by slackpad** [comment]
It's ALL - we should update the docs.

**Comment by brianshumate** [comment]
Fixed in #3012
