### ISSUE TITLE
consul exec shows 0/0 node(s) completed / acknowledged

### ISSUE THREAD

**Issue by thatsk** [hashicorp/consul#2946]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```
{
    "bootstrap": false,
    "server": false,
    "datacenter": "dc1",
    "data_dir": "/var/consul",
	"log_level": "INFO",
    "enable_syslog": true,
	"advertise_addr" : "172.20.20.20", 
	"retry_join": ["172.20.20.10", "172.20.20.11", "172.20.20.12"]
}
Server:
```
[Server `consul info` here]
```
{
    "ui" : true,
    "server": true,
    "datacenter": "dc1",
    "data_dir": "/var/consul",
	"log_level": "INFO",
    "enable_syslog": true,
	"client_addr" : "0.0.0.0",
	"advertise_addr" : "172.20.20.10"
}
### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.
![error](https://cloud.githubusercontent.com/assets/15324013/25316992/12528922-288e-11e7-8a88-a5b5add4a791.png)

**Comment by jf** [comment]
This is *not* a bug. With effect from 0.8.0, `consul exec` is disabled by default (https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#080-april-5-2017)

**Comment by slackpad** [comment]
Thanks @jf that's correct - you have to opt-in to `consul exec` now, see https://www.consul.io/docs/agent/options.html#disable_remote_exec for the config option to turn it back on.
