### ISSUE TITLE
Documentation fix: https://www.consul.io/docs/agent/options.html#acl_ttl

### ISSUE THREAD

**Issue by jf** [hashicorp/consul#2950]
Apologies if this isn't the best place (I don't know of a better place!) to report this, but the writeup for https://www.consul.io/docs/agent/options.html#acl_ttl seems wrong:

`... This setting has a major performance impact: reducing it will cause more frequent refreshes while increasing it reduces the number of caches.`

I think it should be `... while increasing it reduces the number of refreshes.`?

**Comment by slackpad** [comment]
Yep this is confusing!

**Comment by brianshumate** [comment]
Fixed in #3011
