### ISSUE TITLE
KV acls do not seem to work

### ISSUE THREAD

**Issue by jf** [hashicorp/consul#2953]
When filing a bug, please include the following:

### `consul version` for both Client and Server

Client: `Consul v0.8.1`
Server: `Consul v0.8.1`

### `consul info` for both Client and Server

(**NOTE** I had to use the `acl_master_token` here on the client in order to get the info. Wasn't sure how else to get this info.)

Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 'e9ca44d
        version = 0.8.1
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 37
        max_procs = 2
        os = linux
        version = go1.8.1
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 52
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 167
        members = 4
        query_queue = 0
        query_time = 1
```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 'e9ca44d
        version = 0.8.1
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 172.31.30.185:8300
        server = true
raft:
        applied_index = 11809
        commit_index = 11809
        fsm_pending = 0
        last_contact = 14.5167ms
        last_log_index = 11809
        last_log_term = 2
        last_snapshot_index = 8193
        last_snapshot_term = 2
        latest_configuration = [{Suffrage:Voter ID:n.n.n.46:8300 Address:n.n.n.46:8300} {Suffrage:Voter ID:n.n.n.185:8300 Address:n.n.n.185:8300} {Suffrage:Voter ID:n.n.n.25:8300 Address:n.n.n.25:8300}]
        latest_configuration_index = 1
        num_peers = 2
        protocol_version = 2
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 80
        max_procs = 2
        os = linux
        version = go1.8.1
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 52
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 167
        members = 4
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

Ubuntu 16.04 on servers, Ubuntu 14.04 on client

### Description of the Issue (and unexpected/desired result)

Despite setting a rule `key "" { policy = "read" }` for **both** the anonymous token, as well as another token, I am not able to read from the kv if I do not use `acl_master_token`

### Reproduction steps

Set up a cluster of consul servers with `acl_master_token` enabled, and `acl_default_policy` of `deny`. Now put some values into the kv store.

On any server:

kv_read.json:
```
{
        "Name": "nonanonymous token",
        "Type": "client",
        "Rules": "service \"\" { policy = \"write\" } node \"\" { policy = \"write\" } kv \"\" { policy = \"read\" }"
}
```
`curl -X PUT -d @kv_read.json http://localhost:8500/v1/acl/create?token=<acl_master_token>`

On the client, try to read the kv store with this token:

`consul kv get -recurse -token=<generated_token_id_from_above>`

You will get an empty response. IF, however, you pass it the `acl_master_token`, you will get the values from the kv store.

**Comment by slackpad** [comment]
Wow I had to stare at this to figure out what was happening. The ACL policy needs `key` instead of `kv`, so this should work:

```
{
        "Name": "nonanonymous token",
        "Type": "client",
        "Rules": "service \"\" { policy = \"write\" } node \"\" { policy = \"write\" } key \"\" { policy = \"read\" }"
}
```

You should have gotten that feedback when the ACL was created. Marking as a bug.

**Comment by jf** [comment]
aaaargh! Thank you, @slackpad for your help there. Sorry, but I can't believe this... Things work now. Thank you!

**Comment by slackpad** [comment]
No worries and sorry for the trouble.

I'm going to kick this back open - Consul should have given you an error like `unknown policy type "kv"` so this wasn't so obtuse.

**Comment by jf** [comment]
Sure. Great and yes, rule validation would be great!

**Comment by jf** [comment]
On another note... would it be possible to use single quotes somehow somewhere in there? either in the outer quotes, or the inner quotes. It's harder/more inconvenient to type/read when it comes to those rules, if you get what I mean.

**Comment by slackpad** [comment]
> On another note... would it be possible to use single quotes somehow somewhere in there? either in the outer quotes, or the inner quotes. It's harder/more inconvenient to type/read when it comes to those rules, if you get what I mean.

Unfortunately not I think since JSON and HCL both want double quotes, so there's some escaping required. The UI is currently the easiest way to manage ACLs since you can just work with the policy HCL in there. We will also add an ACL CLI command that works similarly, so you don't need to wrap the policy in JSON.

**Comment by jf** [comment]
Yeah... I was hoping to be able to bend the rules a bit. i.e. "accept JSON with single quotes too", or "HCL with single quotes too".

> We will also add an ACL CLI command that works similarly, so you don't need to wrap the policy in JSON.

ok. Look forward to seeing what that will look like and hopefully that makes things easier! I assume the rules will still need to be wrapped (hey, this is the shell!), but at least there is no double-wrapping. Assuming something like this, where only one layer of wrapping:

`consul acl put -token=<> -rules='service "" { policy = "write" } node "" { ... }'`

**Comment by slackpad** [comment]
> `consul acl put -token=<...> ... -rules='service "" { policy = "write" } node "" { ... }'`

^ that's exactly what I was thinking :-)

**Comment by SimonRichardson** [comment]
I was looking for a way in to contribute and took a glance at this (if you don't mind!).

@slackpad Is this not an issue with hcl, where by additional properties are not decoded are effectively ignored. So in this case `"kv"` will be ignored because the [Policy struct](https://github.com/hashicorp/consul/blob/master/acl/policy.go#L17) doesn't know or care about "kv" in this instance. 

Possible solutions is to make hcl more strict around this, but there might have consequences for users of hcl (it could break backwards compatibility if anyone relies on overloading structs for decoding). It could mean a more stricter configuration tool, especially around catching typos etc. Alternatively make a list of known pitfalls that might occur and just check the rules to see if it occurs? 

Any guidance would be great.

**Comment by slackpad** [comment]
@SimonRichardson haven't had a chance to dig into this yet. It does seem like the decoder could have an option to produce errors for parts of the file that never mapped into the struct. I'd probably take a look at Terraform that heavily uses HCL to see what patterns are used there.

**Comment by SimonRichardson** [comment]
Perfect, I'll have a look over there.

**Comment by slackpad** [comment]
I'm going to close this against https://github.com/hashicorp/consul/issues/2206 which already captures ACL rule validation.
