### ISSUE TITLE
consul cluster with a spot-instance

### ISSUE THREAD

**Issue by Moshem123** [hashicorp/consul#2954]
### `consul version` for both Client and Server
0.8.1

### Operating system and Environment details
amazon-linux

### Description of the Issue (and unexpected/desired result)

I have a cluster of 3 servers running 0.8.1.

One of the servers is a spot-instance which makes the IP not stable, meaning it could change without notice.
So when I try to rejoin the cluster with this server, first I need to change the bind address on the server's config.json, and then it won't elect a leader since it's looking for the previous ip (10.2.1.178) while the new ip (10.2.1.155) is entering candidate state.

log:
https://gist.github.com/Moshem123/559625748d534e6d8da82efdcca8d71f

What can I do to resolve it?

Thanks.

**Comment by slackpad** [comment]
Hi @Moshem123 if you get your servers onto Raft protocol version 3 then the server identities will be managed by uuid instead of IP - https://www.consul.io/docs/upgrade-specific.html#raft-protocol-version-compatibility. Can you try your setup with that and see how it goes?

**Comment by slackpad** [comment]
See also https://github.com/hashicorp/consul/issues/2374, which is a very similar issue.

**Comment by slackpad** [comment]
Closing this as a dup of #457.

**Comment by slackpad** [comment]
Closing this in favor of https://github.com/hashicorp/consul/issues/1580.
