### ISSUE TITLE
Datadog metrics integration is poorly implemented

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/consul#2972]
Consul has dogstatsd support, but it doesn't use it idiomatically.  Instead of using proper dimensional tags, Consul uses a unidimensional flat metric name.  This makes them impossible to aggregate and/or filter by a scope tag, as one would naturally do in other Datadog queries and dashboards.

Here are a few examples illustrating how the metrics could be refactored to use tagging:

* `consul.catalog.service.query.<ServiceName>` -> `consul.catalog.service.query`, `<service:ServiceName>`
* `serf.queries.<QueryName>` -> `serf.queries`, `<query:QueryName>`

This sort of functionality is also needed for proper Prometheus integration, as discussed in #817.

**Comment by jippi** [comment]
@mfischer-zd if you want a quick work-around, you can add the consul metrics to https://github.com/seatgeek/statsd-rewrite-proxy and run it in front of datadog statsd and get what you want :) i use it for nomad atm to work around the same issue

**Comment by slackpad** [comment]
This should be addressed by https://github.com/hashicorp/consul/pull/3369.
