### ISSUE TITLE
interval and timeout for http health check

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#2977]
"By default, HTTP checks will be configured with a request timeout equal to the check interval, with a max of 10 seconds. It is possible to configure a custom HTTP check timeout value by specifying the timeout field in the check definition. "

Can I understand the interval can be set up to 10 seconds, numbers more than 10 will be treated as 10?
And if the timeout not set, it will be the same as the interval?
What's the maximum number can be set for timeout? is there also 10 seconds limit? asking this because the number specified in the testing actually not take effect.

**Comment by slackpad** [comment]
Hi @hehailong5 here's the logic for the timeout:

https://github.com/hashicorp/consul/blob/v0.8.1/command/agent/check.go#L379-L386

We need to make the documentation (and possibly the code) easier to interpret :-)

**Comment by i0rek** [comment]
We changed the logic slightly and fixed the docks. Thank you for reporting!
