### ISSUE TITLE
Consul Server loses leader when its deployed with a old IP

### ISSUE THREAD

**Issue by blee1170** [hashicorp/consul#2979]
### `consul version` for both Client and Server
Client: `0.8.1`
Server: `0.8.1`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 2
	check_ttls = 0
	checks = 3
	services = 2
build:
	prerelease =
	revision = 'e9ca44d
	version = 0.8.1
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 112
	max_procs = 2
	os = linux
	version = go1.8.1
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 782
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 4
	member_time = 6824
	members = 58
	query_queue = 0
	query_time = 6
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 'e9ca44d
	version = 0.8.1
consul:
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = 10.49.48.19:8300
	server = true
raft:
	applied_index = 376274
	commit_index = 376274
	fsm_pending = 0
	last_contact = 54.473249ms
	last_log_index = 376274
	last_log_term = 3284
	last_snapshot_index = 368835
	last_snapshot_term = 3284
	latest_configuration = [{Suffrage:Voter ID:10.49.48.41:8300 Address:10.49.48.41:8300} {Suffrage:Voter ID:10.49.48.19:8300 Address:10.49.48.19:8300} {Suffrage:Voter ID:10.49.48.18:8300 Address:10.49.48.18:8300}]
	latest_configuration_index = 341090
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 3284
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 802
	max_procs = 8
	os = linux
	version = go1.8.1
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 782
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 3
	member_time = 6824
	members = 57
	query_queue = 0
	query_time = 6
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 3
	member_time = 132
	members = 9
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
CentOS 7. 
### Description of the Issue (and unexpected/desired result)
When we re-deploy consul server a new instance occasionally gets the same IP as a server that has left. When we do a wan join (automatic now in consul 0.8.0) that new deployment looses the leader. The rest of the cluster is okay, but I have to create a peers list in order to get the new node back into the cluster.
### Reproduction steps
1. Consul cluster deployed with three instances.
1. Bring new instance up.
1. Terminate a old instance.
1. Bring another new instance up. It gets the same IP as the terminated one.
1. Check the leader, it should be listed. (curl localhost:8500/v1/status/leader)
1. Consul join -wan to the other cluster.
1. Check the leader, it should not have one. (curl localhost:8500/v1/status/leader)

**Comment by blee1170** [comment]
Looks like the issue was not having raft at protocol 3. Setting that seems to have fixed the problem.

**Comment by slackpad** [comment]
> Looks like the issue was not having raft at protocol 3. Setting that seems to have fixed the problem.

Makes sense - when you go to version 3 then Consul uses UUIDs to manage the Raft quorum instead of IPs.
