### ISSUE TITLE
ECONNRESET when querying dns using tcp

### ISSUE THREAD

**Issue by dgvncsz0f** [hashicorp/consul#299]
N.B.: This only happens when using _TCP_!!!

I'm using _dnsmasq_ as a proxy for the _consul_ cluster and I
noticed some queries take a long time to complete when using
_TCP_:

    for _ in $(seq 1 10); do dig +tcp @10.30.124.165 leela.service.ita.consul.locaweb.com.br; done | grep -i query.time
    ;; Query time: 3 msec
    ;; Query time: 1 msec
    ;; Query time: 2 msec
    ;; Query time: 2 msec
    ;; Query time: 2 msec
    ;; Query time: 7043 msec
    ;; Query time: 2 msec
    ;; Query time: 2 msec
    ;; Query time: 2 msec
    ;; Query time: 2 msec

After some investigation, I noticed some random `ECONNRESET` on
the first `read` operation, as shown by the following _strace_
output [this is consistent but unfortunately random]:

    10.30.124.165 # strace -r -e connect,read -f -p $(pidof dnsmasq)
    Process 32550 attached - interrupt to quit
    Process 19959 attached
    [pid 19959]      0.000000 read(11, "\0", 1) = 1
    [pid 19959]      0.000223 read(11, "9", 1) = 1
    [pid 19959]      0.000097 read(11, "\245\375\1\0\0\1\0\0\0\0\0\0\5leela\7service\3ita\6c"..., 57) = 57
    [pid 19959]      0.000811 connect(12, {sa_family=AF_INET, sin_port=htons(8600), sin_addr=inet_addr("10.30.124.165")}, 16) = 0
    [pid 19959]      0.000262 read(12, 0x7fff742d57ac, 1) = -1 ECONNRESET (Connection reset by peer)
    [pid 19959]      0.158183 connect(12, {sa_family=AF_INET, sin_port=htons(8600), sin_addr=inet_addr("10.30.124.166")}, 16) = 0
    [pid 19959]      0.000182 read(12, 0x7fff742d57ac, 1) = -1 ECONNRESET (Connection reset by peer)
    [pid 19959]      1.446975 connect(12, {sa_family=AF_INET, sin_port=htons(8600), sin_addr=inet_addr("10.30.124.167")}, 16) = 0
    [pid 19959]      0.000213 read(12, 0x7fff742d57ac, 1) = -1 ECONNRESET (Connection reset by peer)
    [pid 19959]      2.996397 connect(12, {sa_family=AF_INET, sin_port=htons(8600), sin_addr=inet_addr("10.30.124.168")}, 16) = 0
    [pid 19959]      0.000238 read(12, "\1", 1) = 1
    [pid 19959]      0.001334 read(12, "\203", 1) = 1
    [pid 19959]      0.000070 read(12, "\245\375\205\0\0\1\0\6\0\0\0\0\5leela\7service\3ita\6c"..., 387) = 387
    [pid 19959]      0.000863 read(11, "", 1) = 0
    Process 19959 detached
         0.000695 --- SIGCHLD (Child exited) @ 0 (0) ---
         0.000155 read(8, "\5\0\0\0\0\0\0\0\0\0\0\0", 12) = 12^C

    10.30.124.165 # dig +tcp @10.30.124.165 leela.service.ita.consul.locaweb.com.br | grep -i query.time
    ;; Query time: 4607 msec

I managed to create a very simple C program that is able to
reproduce the problem [at least on my servers]:

    #include <sys/types.h>
    #include <sys/socket.h>
    #include <stdlib.h>
    #include <netdb.h>
    #include <stdio.h>
    #include <unistd.h>
    #include <string.h>
     
    void check (const char *msg, ssize_t sz)
    {
      if (sz == (ssize_t) -1)
      {
        perror(msg);
        exit(-1);
      }
    }
     
    int main (int argc, char *argv[])
    {
      (void) argc;
      struct linger linger = {0, 0};
      char buffer[2048];
      struct addrinfo hints;
      struct addrinfo *result, *rp;
      int fd = -1;
     
      memset(&hints, 0, sizeof(struct addrinfo));
      hints.ai_family    = AF_UNSPEC;
      hints.ai_socktype  = SOCK_STREAM;
      hints.ai_flags     = AI_PASSIVE;
      hints.ai_protocol  = 0;
      hints.ai_canonname = NULL;
      hints.ai_next      = NULL;
     
      getaddrinfo(argv[1], argv[2], &hints, &result);
      for (rp = result; rp != NULL; rp = rp->ai_next)
      {
        if ((fd = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol)) < 0)
        { continue; }
        setsockopt(fd, SOL_SOCKET, SO_LINGER, &linger, sizeof(linger));
        if (connect(fd, rp->ai_addr, rp->ai_addrlen) == 0)
        { break; }
        close(fd);
      }
      if (fd < 0)
      { return(0); }
      freeaddrinfo(result);
     
      check("write(fd, \"\\0\", 1)", send(fd, "\0", 1, 0));
      check("write(fd, \"<\", 1)", send(fd, "<", 1, 0));
      check("write(fd, ..., 60)",
            send(fd, "\335\224\1\0\0\1\0\0\0\0\0\0\10webleela\7service\3ita\6consul\7locaweb\3com\2br\0\0\1\0\1", 60, 0));
      check("read(fd, ...#1, 1)", recv(fd, buffer, 1, 0));
      check("read(fd, ...#2, 1)", recv(fd, buffer, 1, 0));
      check("read(fd, ..., 2048)", recv(fd, buffer, 2048, 0));
     
      return(0);
    }

Compiling and running:

    $ gcc -oclient <file-with-that-code>
    $ time sh -c 'while ./client 10.30.124.165 8600; do sleep 0.1; done'
    read(fd, ...#1, 1): Connection reset by peer

    real 0m3.256s
    user 0m0.000s
    sys 0m0.004s

I'm thinking this has something to do with the server closing the
connection prematurely or trusting too much on
`SO_LINGER`. Likely the solution is something along the lines, supposing the code is just closing the connection [pseudo-code]:

    -- remove this
    socket.close fd

    -- and instead something like this
    socket.shutdown fd SHUT_WR
    loop
      n, e0 = recv fd
      break if n <= 0 || e0 != NULL
    e1 = close fd
    return ((e0, e1) == (NULL, NULL) ? SUCCESS : FAILURE)

Interestingly enough, I cannot reproduce this problem using
_dig_. However, the _strace_ output shows it sends/receives the
data using a different pattern.

Maybe it should be better to file this against the go dns
library. Anyway, let me know what you think!

Thanks!

P.S.: Following is my _dnsmasq_ config file:

    $ cat /etc/dnsmasq.d/listen.conf 
    listen-address=10.30.124.165
    listen-address=127.0.0.1
     
    all-servers
    log-queries

    $ cat /etc/dnsmasq.d/consul.conf
    server=/ita.consul.locaweb.com.br/10.30.124.165#8600
    server=/ita.consul.locaweb.com.br/10.30.124.166#8600
    server=/ita.consul.locaweb.com.br/10.30.124.167#8600
    server=/ita.consul.locaweb.com.br/10.30.124.168#8600
    server=/ita.consul.locaweb.com.br/10.30.124.169#8600
    server=/ita.consul.locaweb.com.br/10.30.124.170#8600

**Comment by slackpad** [comment]
Closing this out since we've updated everything since this was reported. Please re-open if you see it again.
