### ISSUE TITLE
Build Test fails with numerous errors

### ISSUE THREAD

**Issue by jean-christophe-manciot** [hashicorp/consul#2990]
### ```consul tag```
v0.8.1

### Operating system and Environment details
Ubuntu 16.10
go 1.8.1 

### Description of the Issue (and unexpected/desired result)
```
ERR] consul: 'Node 10216' and 'Node 10210' are both in bootstrap mode. Only one node should be in bootstrap mode, not adding Raft peer.
```
```
[ERR] consul: failed to reconcile member: {Node 10216 127.0.0.1 20219 map[wan_join_port:20220 role:consul dc:dc1 id:2478742f-fae5-c6d6-0f53-bcb55654e246 vsn_max:3 vsn:2 vsn_min:2 port:20221 bootstrap:1 raft_vsn:2 build:0.8.0c.d:] alive 1 5 2 2 5 4}: leadership lost while committing log
2017/04/29 10:49:30 
[ERR] consul: failed to reconcile: leadership lost while committing log
```
```
[ERR] memberlist: Failed to send gossip to 127.0.0.1:20249: write udp 127.0.0.1:20255->127.0.0.1:20249: use of closed network connection
```
```
[ERR] agent: failed to sync changes: ACL not found
```
```
[ERR] autopilot: error updating cluster health: error getting server raft protocol versions: No servers found
```
```
[ERR] consul.acl: Failed to get policy from ACL datacenter: No path to datacenter
```
```
[ERR] scada-client: failed to handshake: invalid token
```
```
[ERR] dns: error starting tcp server: accept tcp 127.0.0.1:20991: use of closed network connection
```
```
[ERR] dns: recurse failed: read udp 127.0.0.1:60286->127.0.0.1:44050: i/o timeout
2017/04/29 10:50:15 
[ERR] dns: all resolvers failed for {apple.com. 255 1} from client 127.0.0.1:53905 (udp)
```
```
[ERR] consul: failed to reconcile: raft is already shutdown
```
```
[DEBUG] Error in inspecting check result : Unable to query exec info
```
```
[DEBUG] Error in executing health checks: Couldn't Start Exec
```
... and so on

### Reproduction steps: \<username\> to be replaced with yours
        echo --------------------------------------
        echo Constraining build to only linux/amd64
        echo --------------------------------------
        sudo -u <username> -H sed -i 's|"386 amd64 arm"|"amd64"|g' scripts/build.sh
        sudo -u <username> -H sed -i 's|"solaris darwin freebsd linux windows"|"linux"|g' scripts/build.sh

        echo ---------
        echo Compiling
        echo ---------
        sudo -u <username> -H make

        echo -------
        echo Testing
        echo -------
        sudo -u <username> -H make test

### Log Fragments or Link to [gist](https://gist.github.com/)
[build.log.txt](https://github.com/hashicorp/consul/files/966013/build.log.txt)

**Comment by slackpad** [comment]
Hi @jean-christophe-manciot we have a number of tests which are timing-sensitive and need a fairly powerful computer to run reliably. We are in the process of refactoring the tests and test framework, so please stay tuned to the work @magiconair has been doing as this will improve. I'll close this out since it's is being tracked internally.
