### ISSUE TITLE
Question about creating a service with more than one instance?

### ISSUE THREAD

**Issue by tekpig** [hashicorp/consul#2994]
Now I want to register a service by agent mode.

First, it belongs to service 'provider'.

Second, it belongs to sub-service 'sms'.

Third, it has its instance name, such as '1'.

Can I do it as follow?

{
  "ID": "1",
  "Name": "provider/sms",
  "Tags": [
    "primary",
    "v1"
  ],
  ......
}

Then, how can I list all the sub-services which belongs to 'provider'?

Thanks!

**Comment by slackpad** [comment]
Hi @tekpig we currently don't have a hierarchy for services, and we don't recommend a name with a "/" character which won't work with DNS, so you may want to use tags for this. If the name is "provider" and you add the tag "sms" you could query for sms.provider.service.consul via DNS. This endpoint would let you see all the variants - https://www.consul.io/api/catalog.html#list-services.

That said, "provider" is a pretty high level name, so you might want to just use "sms" for the service name. #1779 tracks having more of a hierarchy, but that's currently not on the roadmap. Hope that helps!
