### ISSUE TITLE
Many leader elections since version 0.7.5

### ISSUE THREAD

**Issue by cshabi** [hashicorp/consul#3014]
**consul version for both Client and Server**
Client: v0.7.5
Server: v0.7.5

**consul info:**
Server:
agent:
       	check_monitors = 1
       	check_ttls = 0
       	checks = 1
       	services = 2
build:
       	prerelease =
       	revision = '21f2d5a
       	version = 0.7.5
consul:
       	bootstrap = false
       	known_datacenters = 3
       	leader = true
       	leader_addr = Leader IP:8300
       	server = true
raft:
       	applied_index = 1015719113
       	commit_index = 1015719113
       	fsm_pending = 0
       	last_contact = 0
       	last_log_index = 1015719113
       	last_log_term = 66387
       	last_snapshot_index = 1015718616
       	last_snapshot_term = 66387
       	latest_configuration = [{Suffrage:Voter ID:Leader IP:8300 Address:Leader IP:8300} {Suffrage:Voter ID:Follower1 IP:8300 Address:Follower1 IP:8300} {Suffrage:Voter ID:Follower2 IP:8300 Address:Follower2 IP:8300}]
       	latest_configuration_index = 1010920262
       	num_peers = 2
       	protocol_version = 1
       	protocol_version_max = 3
       	protocol_version_min = 0
       	snapshot_version_max = 1
       	snapshot_version_min = 0
       	state = Leader
       	term = 66387
runtime:
       	arch = amd64
       	cpu_count = 24
       	goroutines = 14174
       	max_procs = 24
       	os = linux
       	version = go1.7.5
serf_lan:
       	encrypted = true
       	event_queue = 0
       	event_time = 44308
       	failed = 3
       	health_score = 0
       	intent_queue = 0
       	left = 1
       	member_time = 58976
       	members = 2190
       	query_queue = 0
       	query_time = 942
serf_wan:
       	encrypted = true
       	event_queue = 0
       	event_time = 1
       	failed = 0
       	health_score = 0
       	intent_queue = 0
       	left = 0
       	member_time = 37
       	members = 10
       	query_queue = 0
       	query_time = 1

**Operating system and Environment details**
ubuntu 12.04
clients: ubuntu16.04/14.04/12.04
              centos 5.9/5.7

**Description of the Issue (and unexpected/desired result)**
Since upgrading to version 0.7.5 I experience leader changes very often (4-3 times in an hour) in all datacenter at the same time, as seen in the statics sent from the servers to collectd. 
each datacenter has 3 consul servers and between to 900-2600 physical clients.
The logical consul datacenters represent 3 physical datacenters that we own. 2 of them running 1Gig and on of them is 10Gig. All servers and network appliances are within the same room and we don't experience latency/connectivity issues.

While running `consul monitor --log-level debug` on the leader of dc2, during an election this is what I see:

2017/05/07 05:48:10 [WARN] raft: Failed to contact Follower1 IP:8300 in 720.908689ms
2017/05/07 05:48:10 [WARN] raft: Failed to contact Follower2 IP:8300 in 720.670891ms
2017/05/07 05:48:10 [WARN] raft: Failed to contact quorum of nodes, stepping down
2017/05/07 05:48:10 [INFO] raft: Node at Leader IP:8300 [Follower] entering Follower state (Leader: "")
2017/05/07 05:48:10 [INFO] consul: cluster leadership lost
2017/05/07 05:48:10 [INFO] raft: aborting pipeline replication to peer {Voter Follower2 IP:8300 Follower2 IP:8300}
2017/05/07 05:48:11 [INFO] raft: aborting pipeline replication to peer {Voter Follower1 IP:8300 Follower1 IP:8300}
2017/05/07 05:48:11 [WARN] consul.coordinate: Batch update failed: node is not the leader
2017/05/07 05:48:11 [WARN] raft: Heartbeat timeout from "" reached, starting election
2017/05/07 05:48:11 [INFO] raft: Node at Leader IP:8300 [Candidate] entering Candidate state in term 66387
2017/05/07 05:48:12 [DEBUG] raft: Votes needed: 2
2017/05/07 05:48:12 [DEBUG] raft: Vote granted from Leader IP:8300 in term 66387. Tally: 1
2017/05/07 05:48:12 [DEBUG] raft: Vote granted from Follower1 IP:8300 in term 66387. Tally: 2
2017/05/07 05:48:12 [INFO] raft: Election won. Tally: 2
2017/05/07 05:48:12 [INFO] raft: Node at Leader IP:8300 [Leader] entering Leader state
2017/05/07 05:48:12 [INFO] raft: Added peer Follower1 IP:8300, starting replication
2017/05/07 05:48:12 [INFO] raft: Added peer Follower2 IP:8300, starting replication
2017/05/07 05:48:12 [INFO] consul: cluster leadership acquired
2017/05/07 05:48:12 [INFO] consul: New leader elected: Leader fqdn
2017/05/07 05:48:12 [INFO] raft: pipelining replication to peer {Voter Follower1 IP:8300 Follower1 IP:8300}
2017/05/07 05:48:12 [INFO] raft: pipelining replication to peer {Voter Follower2 IP:8300 Follower2 IP:8300}
2017/05/07 05:48:12 [DEBUG] consul: reset tombstone GC to index 1015717914
2017/05/07 05:48:12 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:12 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:12 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:12 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader
2017/05/07 05:48:13 [DEBUG] serf: messageUserEventType: consul:new-leader

Also, when looking at logs in clients registered to dc2 I see this messages reporting on many other clients:
[WARN] memberlist: ignoring alive message for 'client hostname': Member 'client hostname' part of wrong datacenter 'dc1' 
while the 'client hostname' is configured to the right dc(which is dc1). not sure why clients in dc1 will try to update clients/servers in dc2.
Important to say that all of our config files are managed by a CM system so errors in the confing were already eliminated.
when running `consul monitor --log-level debug` on consul server in dc2 i see this message:
[DEBUG] consul.prepared_query: Skipping unknown datacenter 'dc2' in prepared query

**this is the config on clients in dc2:**
{
  "data_dir": "/consul",
  "disable_remote_exec": true,
  "disable_update_check": true,
  "log_level": "WARN",
  "dns_config": {
    "allow_stale": true,
    "max_stale": "5s",
    "enable_truncate": true
  },
  "datacenter": "dc2",
  "start_join": [
    "Consul server1 in dc2",
    "Consul server2 in dc2",
    "Consul server3 in dc2"
  ],
  "advertise_addr": "Client's IP"
}

**config on clients in dc1:**
{
  "data_dir": "/consul",
  "disable_remote_exec": true,
  "disable_update_check": true,
  "log_level": "WARN",
  "dns_config": {
    "allow_stale": true,
    "max_stale": "5s",
    "enable_truncate": true
  },
  "datacenter": "dc1",
  "start_join": [
    "Consul server1 in dc1",
    "Consul server2 in dc1",
    "Consul server3 in dc1"
  ],
  "advertise_addr": "Client's IP"
}

**config on servers:**
{
  "data_dir": "/consul",
  "disable_remote_exec": true,
  "disable_update_check": true,
  "log_level": "WARN",
  "dns_config": {
    "allow_stale": true,
    "max_stale": "5s",
    "enable_truncate": true
  },
  "datacenter": "dc1",
  "start_join": [
    "Consul server1 in dc X",
    "Consul server2 in dc X",
    "Consul server3 in dc X"
  ],
  "server": true,
  "statsd_addr": "statsd:8125",
  "statsite_prefix": "consul_dc1",
  "bootstrap_expect": 3,
  "performance": {
    "raft_multiplier": 1
  },
  "ui_dir": "/var/lib/consul/ui",
  "client_addr": "0.0.0.0",
  "advertise_addr": "Client's IP"
}

**Regarding network:**
Seems like the applicative side is not doing well:
when running consul rtt within the same datacenter:
` consul rtt consul_server1 consul_server2`
Estimated consul_server1 <-> consul_server2 rtt: 0.816 ms (using LAN coordinates)

`ping consul server2`
PING consul_server2 (IP) 56(84) bytes of data.
64 bytes from consul_server2 (IP): icmp_req=1 ttl=63 time=0.096 ms
64 bytes from consul_server2 (IP): icmp_req=2 ttl=63 time=0.098 ms

**Please advise on what to do next**

**Comment by slackpad** [comment]
> Since upgrading to version 0.7.5

Which version were you on previously?

> I experience leader changes very often (4-3 times in an hour) in all datacenter at the same time, as seen in the statics sent from the servers to collectd.
each datacenter has 3 consul servers and between to 900-2600 physical clients.

Do you mean that you see failures in multiple Consul datacenters that are correlated in time? That's super strange as there shouldn't be any Raft crossover at that level (could be some common load thing, though).

**Comment by cshabi** [comment]
Thanks @slackpad for replying

We were running on version 0.6

yes, I can attach a graph describing the problem. The data shown on the graph is from the metrics sent to collectd : serf.events.consul_new-leader.count
thats how it looks on all datacenters:


![](https://s3.amazonaws.com/uploads.hipchat.com/36193/1604578/69nSaGHRlwWbQec/consul.png)

dc1 and dc2 run on a 1Gig facility and dc3 on 10Gig.

When we saw this behavior we started collecting system health metrics such as cpu idle/wait memory usage, network utilization etc and we couldn't see any weird behavior. What we did see was a decrease in usage since upgrading.

**Comment by slackpad** [comment]
Having a correlated set of leader elections across different Consul datacenters seems like maybe you've got some kind of process doing a huge number of Consul reads at that time, or maybe some kind of workload that occurs on those datacenters at the same time affecting the Consul machines themselves or the network. It's super hard to say without exploring the telemetry around that time. Can you confirm within each datacenter the network is healthy between the servers when this occurs (no lost packets / TCP retransmits)?

**Comment by cshabi** [comment]
I run some tests during the election in one DC:
ping: no packet loss, latency around 0.100 
rtt: between 1.020 to 0.800 ms during election (normally around 0.300)

Here is some telemetry data from around the leader election time:
**total_gc_runs with the NonNegativeDerivative function:**

![screen shot 2017-06-01 at 12 10 37](https://cloud.githubusercontent.com/assets/18681497/26672840/5d6b8ff0-46c3-11e7-8c87-0587bffdcc87.png)

**new_leader.count:**
![screen shot 2017-06-01 at 12 14 24](https://cloud.githubusercontent.com/assets/18681497/26672984/ebbf1592-46c3-11e7-823d-05693d01548d.png)

**consul.raft.commitTime in ms:**
![screen shot 2017-06-01 at 12 21 41](https://cloud.githubusercontent.com/assets/18681497/26673257/e82dd9c6-46c4-11e7-870b-cbed8a7e240b.png)

**consul.raft.leader.lastContact in ms:**
![screen shot 2017-06-01 at 12 29 52](https://cloud.githubusercontent.com/assets/18681497/26673577/0c6c6ebe-46c6-11e7-80a6-e7716e9a5b3e.png)

**rpc cross-dc:**
![screen shot 2017-06-01 at 12 39 24](https://cloud.githubusercontent.com/assets/18681497/26673955/5ea3f5ac-46c7-11e7-90f5-f49fcb94676e.png)

**consul.raft.replication.appendEntries in ms: **
![screen shot 2017-06-01 at 12 46 04](https://cloud.githubusercontent.com/assets/18681497/26674205/4db36a6a-46c8-11e7-9b5f-bbdbee100d0c.png)

**consul.raft.leader.dispatchLog in ms:**
![screen shot 2017-06-01 at 12 51 06](https://cloud.githubusercontent.com/assets/18681497/26674394/027d7f30-46c9-11e7-8b97-cc05f92baf5c.png)


Is there anything else from the telemetry you think we should keep track on?

**Comment by slackpad** [comment]
Ah interesting - from that appendEntries spike it looks like something is doing a huge number of writes. If you look in telemetry for "fsm" that should give you an idea of what kind of write it is - each type of object emits its own telemetry: fsm.kvs, fsm.register (for catalog), etc.

**Comment by cshabi** [comment]
Thanks @slackpad but I couldn't find the fsm metrics. Here is what I do see under fsm:

<img width="231" alt="screen shot 2017-06-27 at 10 18 29" src="https://user-images.githubusercontent.com/18681497/27575313-016b9812-5b22-11e7-87a1-784c9032233b.png">

**Comment by preetapan** [comment]
@slackpad AFAICT from searching the raft code base the only metrics that start with "raft.fsm" are apply/snapshot/restore.

**Comment by slackpad** [comment]
Sorry for the late reply - these would be under a name like `consul.consul.fsm.kvs` You can see some examples here https://demo.consul.io/v1/agent/metrics?pretty.

**Comment by cshabi** [comment]
Thanks @slackpad, but this endpoint doesn't return anything when queuing my servers:

http://<consul_server>:8500/v1/agent/metrics?pretty

**Comment by slackpad** [comment]
Hi @cshabi that endpoint was added in Consul 0.9.1.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
