### ISSUE TITLE
Consul server cannot sync check service?

### ISSUE THREAD

**Issue by huyjack178** [hashicorp/consul#3016]
I use consul server to check service but result can not be synced, client can do this. Please help

**Comment by slackpad** [comment]
Please take a look at the new [ACL guide](https://www.consul.io/docs/guides/acl.html) and let us know if you are still stuck. You can register your service with an ACL token that has the right permissions - https://www.consul.io/docs/guides/acl.html#service-rules:

> Service rules come into play when using the Agent API to register services or checks. The agent will check tokens locally as a service or check is registered, and Consul also performs periodic anti-entropy syncs, which may require an ACL token to complete. To accommodate this, Consul provides two methods of configuring ACL tokens to use for registration events:
> 1. Using the acl_token configuration directive. This allows a single token to be configured globally and used during all service and check registration operations.
> 2. Providing an ACL token with service and check definitions at registration time. This allows for greater flexibility and enables the use of multiple tokens on the same agent. Examples of what this looks like are available for both services and checks. Tokens may also be passed to the HTTP API for operations that require them.

**Comment by huyjack178** [comment]
@slackpad  It works like a charm, thank you so much
