### ISSUE TITLE
consul API requests with index parameter are taking ages

### ISSUE THREAD

**Issue by vaLski** [hashicorp/consul#3031]
Client: Consul v0.7.5
Server: Consul v0.7.5

Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 3
build:
        prerelease = 
        revision = '21f2d5a
        version = 0.7.5
consul:
        known_servers = 5
        server = false
runtime:
        arch = amd64
        cpu_count = 48
        goroutines = 77
        max_procs = 48
        os = linux
        version = go1.7.5
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 222
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 13913
        members = 582
        query_queue = 0
        query_time = 17
```
Server:
```
agent:
        check_monitors = 1
        check_ttls = 0
        checks = 1
        services = 2
build:
        prerelease = 
        revision = '21f2d5a
        version = 0.7.5
consul:
        bootstrap = false
        known_datacenters = 5
        leader = true
        leader_addr = *snip*:8300
        server = true
raft:
        applied_index = 894647634
        commit_index = 894647634
        fsm_pending = 0
        last_contact = 0
        last_log_index = 894647634
        last_log_term = 28988
        last_snapshot_index = 894641590
        last_snapshot_term = 28988
        latest_configuration = *snip*
        latest_configuration_index = 484895378
        num_peers = 4
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 28988
runtime:
        arch = amd64
        cpu_count = 16
        goroutines = 8672
        max_procs = 16
        os = linux
        version = go1.7.5
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 222
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 13913
        members = 582
        query_queue = 0
        query_time = 17
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1478
        members = 22
        query_queue = 0
        query_time = 3
```

### Operating system and Environment details

centos 6 
5 consul servers per dc
Multiple consul agents per dc

### Description of the Issue (and unexpected/desired result)

Consul watches make requests to the consul api with index= parameter set.

For unknown to me reason such api calls are taking ages to be serviced and are eventually timing out.  

```
time curl -s 'http://127.0.0.1:8500/v1/kv/consul-template/shared?index=866401642&recurse=' >> /dev/null

real    5m9.797s
user    0m0.004s
sys     0m0.009s
```

If i retry the same api call with curl and remove the index= parameter results are immediately serviced  

```
time curl -s 'http://127.0.0.1:8500/v1/kv/consul-template/shared?recurse=' >> /dev/null
real    0m0.454s
user    0m0.005s
sys     0m0.001s
```

### Reproduction steps

agents got similar keyprefix watch configuration

```
{
        "watches": [{
                "type": "keyprefix",
                "prefix": "consul-template/prd",
                "handler": "/usr/local/consul/bin/sgh"
        }]
}
```

Agents occasionally log the following 
 
```
20170510T130557.629390:     2017/05/10 08:05:57 consul.watch: Watch (type: keyprefix) errored: Get http://127.0.0.1:8500/v1/kv/consul-template/prd?index=866401642&recurse=: read tcp 127.0.0.1:48746->127.0.0.1:8500: read: connection timed out, retry in 3m0s
```

Servers got multiple logs similar to the one listed above for different KV prefixes and paths used as keys or trees by consul-template

```
2017/05/10 09:08:44 [DEBUG] http: Request GET /v1/kv/pub/server/priv/addr?index=486052160&recurse=&stale=&wait=60000ms (1m0.503012992s) from=127.0.0.1:41504
```

I can see that consul raft leaders in each dc are taking multiple cores (400/500% cpu usage)  even consul-template is started with -max-stale 10m on cmd line and max_stale = "5m" /etc/consul-template/configs/global.hcl. Interestingly stale= is blank in the raft leaders logs.

Is that a normal operation or serious performance issue?

**Comment by slackpad** [comment]
Hi @vaLski when you supply an `index` Consul does a [blocking query](https://www.consul.io/api/index.html#blocking-queries) which waits to respond until the underlying data changes (or a 10 minute timer expires). That's totally normal behavior and is a performance optimization that's a good alternative to polling. Hope that helps!

**Comment by vaLski** [comment]
In that case why the consul watches are logging errors thus triggering exponential backoffs

Is that a normal behavior for the consul watches?

```
20170510T140201.085358:     2017/05/10 09:02:01 consul.watch: Watch (type: keyprefix) errored: Get http://127.0.0.1:8500/v1/kv/consul-template/prd?index=866403342&recurse=: read tcp 127.0.0.1:44926->127.0.0.1:8500: read: connection timed out, retry in 5s
20170510T140406.397355:     2017/05/10 09:04:06 consul.watch: Watch (type: keyprefix) errored: Get http://127.0.0.1:8500/v1/kv/consul-template/prd?index=866403342&recurse=: read tcp 127.0.0.1:36782->127.0.0.1:8500: read: connection timed out, retry in 20s
20170510T140626.685371:     2017/05/10 09:06:26 consul.watch: Watch (type: keyprefix) errored: Get http://127.0.0.1:8500/v1/kv/consul-template/prd?index=866403342&recurse=: read tcp 127.0.0.1:48744->127.0.0.1:8500: read: connection reset by peer, retry in 45s
20170510T140911.933374:     2017/05/10 09:09:11 consul.watch: Watch (type: keyprefix) errored: Get http://127.0.0.1:8500/v1/kv/consul-template/prd?index=866403342&recurse=: read tcp 127.0.0.1:37526->127.0.0.1:8500: read: connection timed out, retry in 1m20s
20170510T141302.333406:     2017/05/10 09:13:02 consul.watch: Watch (type: keyprefix) errored: Get http://127.0.0.1:8500/v1/kv/consul-template/prd?index=866403342&recurse=: read tcp 127.0.0.1:57424->127.0.0.1:8500: read: connection reset by peer, retry in 2m5s
20170510T141707.581323:     2017/05/10 09:17:07 consul.watch: Watch (type: keyprefix) errored: Get http://127.0.0.1:8500/v1/kv/consul-template/prd?index=866403342&recurse=: read tcp 127.0.0.1:53586->127.0.0.1:8500: read: connection timed out, retry in 3m0s
20170510T142207.869432:     2017/05/10 09:22:07 consul.watch: Watch (type: keyprefix) errored: Get http://127.0.0.1:8500/v1/kv/consul-template/prd?index=866403342&recurse=: read tcp 127.0.0.1:53532->127.0.0.1:8500: read: connection reset by peer, retry in 3m0s
```

**Comment by slackpad** [comment]
Sorry I missed that - I don't think that's normal. The `connection reset by peer` makes it seems like something is breaking the connections. Are there any network issues, or intervening firewall kind of things that might be messing with connections?

**Comment by vaLski** [comment]
Each consul client have firewall with connection tracking  but access to consul ports is wide open. Moreover messages appear on different occasion and random intervals which make me think that this is not a firewall related issue or issue with CT.

network issues are on the table as such logs appear on all clients. HoweverI do not think that this is the problem too as we do not observe any packet loss or service interruptions/malfunctions on other services hosted on these nodes (nginx/apache/ftp/etc)

On consul server side monitor with TRACE does not log IP addr of the API blocking query caller so I can track lifecycle of new/existing session on server side and eventually see how it is terminated.

Any hints?

**Comment by slackpad** [comment]
These connections will sit without any kind of hearbeat for minutes at a time - is there a chance these get actively closed by your firewall due to a timeout kind of thing?

**Comment by vaLski** [comment]
It might be a firewall issue or a sysctl knob on network timeouts but still wondering why time intervals look different for each incorrectly terminated/timed out session. 

Point me to the right direction if I am getting this wrong. So you are saying that once such index session is established, absolutely no data is further transfered on that session (heartbeats of any type) unless change/event occurs? Wondering what would "minutes at a time" be.  Is it a static value? 

Otherwise as far as I can understand communication flow looks something similar like this is that correct?

consul-template ->  consul:http -> consul-server-raft-member:http [-> consul-server-raft-leader:http]

So there is a chance for connection to be broken on each arrow of the "picture" even on the consul-template to consul part even on the loopback interface if something is incorrectly configured. Also call to leader is optional or obligatory in case of index usage? As far as I can understand if stale is set and stale header settings are satisfied call to raft leader in [] is omitted so we call any consul server.

In that case still curious what would be the right method to determine on server which exact client connection timed out and on the client side to which exact server the session timed out. Perhaps debugging for the api calls should be extended so I can log the caller on server side and the server I am communicating with on the client side.

Do you think that this is the right way to debug this future?

**Comment by slackpad** [comment]
Your understanding of the RPC flow is correct. From a given Consul agent, all of it's HTTP requests result in RPC requests over a single multiplexed TCP connection to one of the servers, which then may forward the RPC to the leader in a similar fashion if stale isn't allowed. If you turn on stale queries then you can eliminate the hop to the leader, and then I'd use something like `tcpdump` or `wireshark` on an agent to watch the TCP connections to the HTTP endpoint on 8500 and the server RPC port on 8300 and look for them getting closed.

**Comment by BruceWangNo1** [comment]
I have encounterned the same problem. Should I just leave it alone? @vaLski @slackpad 
```
2019/07/12 11:31:58 [ERR] consul.watch: Watch (type: service) errored: Get http://127.0.0.1:8500/v1/health/service/go.micro.tea.web.wiki?index=18: dial tcp 127.0.0.1:8500: connect: connection refused, retry in 5s
```

**Comment by vaLski** [comment]
@BruceWangNo1 As far as I can understand from the log you provided:

- you have a watch service watch waiting for go.micro.tea.web.wiki changes
- this watch relies on the consul agent
- all of a sudden your consul agent died for some reason
- your watch started throwing errors (connection refused) because of that

The current "issue" I initially reported turned out not to be an issue at all but rather how blocking queries are functioning.

Watches are long pooling HTTP requests which gets answered whenever there is a change.

If there is no change for particular time interval than this long pooling HTTP request is timing out and is restarted again by the one who is running the watcher.

In your case the question is why consul stopped working so your watch started throwing connection refused. Without the local consul agent you can't do `consul watch`

**Comment by BruceWangNo1** [comment]
@vaLski Thank you for the reply. There is indeed something wrong with the web srv as you have suggested. As a matter of fact, there is a Timeout field in struct registry.Options in "github.com/micro/go-micro/registry" wrongly set to time.Second * 5 in the web srv. After I commented it out, the error logs are no longer there to see.

**Comment by ajaykumar-gbi** [comment]
@BruceWangNo1 , the solution you provided above:

```
As a matter of fact, there is a Timeout field in struct registry.Options in "github.com/micro/go-micro/registry" wrongly set to time.Second * 5 in the web srv. After I commented it out, the error logs are no longer there to see.
```

Can you point where to configure that. I am also facing the same issue.
