### ISSUE TITLE
[question] How to make Consul FIPS 140-2 compliant?

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/consul#3039]
### `consul version` for both Client and Server
Client: 0.8.3
Server: 0.8.3

### Operating system and Environment details
CentOS 7

### Description of the Issue and Query
I have searched a lot and concluded that HashiCorp tools are not FIPS 140-2  compliant. (yet?)
* I have been searching for FIPS compliance in the other repos as well; Nomad/Vault

The only reference of 140-2 I found  was a call out by @sethvargo 
https://groups.google.com/forum/#!searchin/consul-tool/fips%7Csort:relevance/consul-tool/0uqAFhuvgKw/A8WFax85AQAJ

So, the query is:
Is Consul FIPS 140-2 (I assume not) and how to make it so?

This is of course with the intent of using this in AWS GovCloud.
* I will also be cross-posting this for Nomad

Thanks and Regards,
Shantanu

**Comment by slackpad** [comment]
Closing similar to https://github.com/hashicorp/nomad/issues/2639.
