### ISSUE TITLE
Make a pre-comiled arm64 build

### ISSUE THREAD

**Issue by Knight1** [hashicorp/consul#3042]
### `consul version` for both Client and Server
Version: 'v0.8.2-42-g4edd1dc-dev (4edd1dc)'

### Operating system and Environment details
aarch64

### Description of the Issue (and unexpected/desired result)

There is only a pre-compiled arm version for Consul available the arm64/aarch64 versions is missing. I was able to build it with go 1.8.1 without any errors on a Thunder X.

### Fix
Please make a pre-compiled arm64 version from Consul available unter the download section.

Thanks!

**Comment by magiconair** [comment]
I'll have a look. This should be simple.

**Comment by Knight1** [comment]
Thank you :)
