### ISSUE TITLE
Add Sub Navigation to HTTP API docs

### ISSUE THREAD

**Issue by andrewwatson** [hashicorp/consul#305]
It would be easier to find things on this page if it was broken into multiple pages or there was a sub-nav and name anchors...
http://www.consul.io/docs/agent/http.html

**Comment by ryanuber** [comment]
Didn't even realize there was an issue for this, but this is done in master, and deployed to consul.io!

**Comment by blalor** [comment]
It doesn't really work, tho.  Clicking "/v1/agent/self" doesn't take you to the description of that endpoint, only to the thing you just clicked on.

**Comment by ryanuber** [comment]
@blalor good catch. We actually *do* have the proper anchors and links, but I think this is a regression. I opened hashicorp/middleman-hashicorp#6 for this. Thanks!
