### ISSUE TITLE
Documentation issue on List Nodes for Service

### ISSUE THREAD

**Issue by mpermar** [hashicorp/consul#3055]
On the "List Nodes for Service" section for the [Health](https://www.consul.io/api/health.html) endpoint, the uri path is "/health/service/:service". 

I imagine that is incorrect as that seems to be the health service uri.

**Comment by slackpad** [comment]
Hi @mpermar the docs are correct for that one. In this case the health of the service is expressed in terms of the list of nodes that provide that service and their associated health checks.

**Comment by mpermar** [comment]
Hi @slackpad. They are indeed. Sorry about the noise.
