### ISSUE TITLE
Allow to filter by service all health checks in state

### ISSUE THREAD

**Issue by mpermar** [hashicorp/consul#3056]
Currently you can get a list of health checks in a state. That is good but in an installation that has tons of services from different teams it is actually very noisy when you care only about your little service. 

I think it would be nice to have a service query parameter for filtering on /health/state/:state queries.

**Comment by slackpad** [comment]
Hi @mpermar please take a look at https://www.consul.io/api/health.html#list-nodes-for-service (there's a `?passing` parameter on there that lets you filter by state, though that's going to become more flexible under #2212). Hope that helps!

**Comment by mpermar** [comment]
Hi @slackpad . Thanks for the reference. "passing" attribute does not help just for the same reason which #2112 explains as conter-intuitive, i.e. there is no way to grab only the nodes that are not passing all checks.

/health/state/:state has that but lacks any filtering. That's why I was hoping for a /health/state/:state?service=database for example

**Comment by slackpad** [comment]
@mpermar indeed - making that better is captured in #2112!
