### ISSUE TITLE
Is it required to run a cluster in a separate VM?

### ISSUE THREAD

**Issue by campanagerald** [hashicorp/consul#3064]
Is it required to run a cluster in a separate VM?

**Comment by magiconair** [comment]
@campanagerald to do what? testing, production?

**Comment by slackpad** [comment]
Hi @campanagerald it's not required to run Consul in a separate VM. Consul is often run on the host operating system, even when running things like containers, and things like its DNS and HTTP interfaces are exposed to applications through the host's configuration. Hope that helps!
