### ISSUE TITLE
ACL not working when using http api

### ISSUE THREAD

**Issue by zozowind** [hashicorp/consul#3069]
### `consul version` for both Client and Server
Server: `0.8.3`

### ACL setting
ACL A：23xxxxxx-xxxx-xxxx-xxxx-xxxxxxa5c872 type management
ACL B:  36xxxxxx-xxxx-xxxx-xxxx-xxxxxx6bddb7 type client
```
    #ACL B
    "service": {
        "": {
             "policy": "write"
        }
```
### Result
* Using A：  http://localhost:8500/v1/catalog/service/testService?token=23xxxxxx-xxxx-xxxx-xxxx-xxxxxxa5c872 
Get the right data.

* Using B or without token Get empty array

* Get the same test result through web ui

**Comment by slackpad** [comment]
Hi @zozowind I couldn't reproduce this. It looks like your policy is missing a closing brace - can you please double check that it's properly formatted?

**Comment by zozowind** [comment]
Thanks for quick replying.
sorry for missing the closeing brace, here is the full acl code.
```
{
    "key": {
        "hd_api_gateway/": {
            "policy": "write"
        }
    },
    "service": {
        "": {
             "policy": "write"
        }
    }
}
```
Actually when I use version 0.7.5, it's fine, so I doubt if there are some changes in acl checks. Thanks

**Comment by zozowind** [comment]
I'm missing the node read policy, it worked fine after add it. And thanks a lot.
```
{
    "key": {
        "hd_api_gateway/": {
            "policy": "write"
        }
    },
    "node": {
        "": {
             "policy": "read"
        }
    },
    "service": {
        "": {
             "policy": "write"
        }
    }
}
```
