### ISSUE TITLE
consul nomad cluster showing nomad-client status failed

### ISSUE THREAD

**Issue by thatsk** [hashicorp/consul#3081]
When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
0.8.1
Server: `[server version here]`
0.8.1
### `consul info` for both Client and Server
Client:
[Client `consul info` here]
```
{
    "bootstrap": false,
    "server": false,
    "datacenter": "nomad-intro",
    "data_dir": "/var/consul",
    "log_level": "INFO",
    "enable_syslog": true,
    "advertise_addr" : "192.168.1.7",
    "bind_addr" : "192.168.1.7",
    "start_join": ["192.168.1.4", "192.168.1.5", "192.168.1.6"],
    "disable_remote_exec": false
}

Server:
```
[Server `consul info` here]
```
{
    "ui": true,
    "bootstrap_expect": 3,
    "server": true,
    "datacenter": "nomad-intro",
    "data_dir": "/var/consul",
    "log_level": "INFO",
    "enable_syslog": true,
    "bind_addr": "192.168.1.4",
    "client_addr" : "0.0.0.0",
    "start_join": ["192.168.1.5","192.168.1.6"],
    "disable_remote_exec" : false
}

### Operating system and Environment details
centos7
### Description of the Issue (and unexpected/desired result)
Deployed 6 node cluster of consul nomad and docker.
why its showing server1 nomad client is failing even it is working fine.
client node does not show any services like nomad or consul.
is there any configuration mistake please tell me

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).
```

![1](https://cloud.githubusercontent.com/assets/15324013/26544794/cdb404f8-4480-11e7-805c-913225ac73c4.png)
![2](https://cloud.githubusercontent.com/assets/15324013/26544793/cdb022de-4480-11e7-98ae-a7bd2140d03c.png)

**Comment by slackpad** [comment]
Hi @thatsk it looks like Consul is doing a GET on /v1/agent/servers on the Nomad client, which looks like a valid endpoint per https://www.nomadproject.io/docs/http/agent-servers.html. I'd open a GitHub issue over on the Nomad project, because this doesn't look like a problem in Consul. That endpoint should not be returning a 501.
