### ISSUE TITLE
Consul repair services

### ISSUE THREAD

**Issue by veryjollyroger** [hashicorp/consul#3083]
Is there any way to make consul perform some actions in case some service is failing? It could be much more useful than just see information about failing services especially when repair means 'restart service' or something like that.  
I wish to make something like:
{
  "service": {
    "name": "redis",
    "checks": [
      {
           "id": "redis",
           "name": "Redis Status",
           "notes": "Check redis every 10 seconds",
           "ttl": "30s"
      }
    ],
    "repair": {
        "script": "/usr/local/bin/rapair_redis.py"
      }
  }
}

**Comment by davidgibbons** [comment]
This doesn't seem like the functionality you would want built into consul but something you could easily do with a polling script that checks for that consul service stats via api and performs the action you want.

**Comment by veryjollyroger** [comment]
davidgibbons, what do you mean by polling script? I don't really see any points not to want this functionality in consul. If it can check if service is running, why wouldn't it try to do something with it if it fails?

**Comment by slackpad** [comment]
Hi @veryjollyroger thanks for opening an issue. At this time, we are probably not going to add actions like this inside of Consul itself so we can avoid taking on a lot of complexity in Consul's core. We'd end up having to manage the lifetime of repair processes and add additional plumbing to make their status available to operators. Some processes might take a long time to complete, or even need to run on a different machine (like for a database failover), so this is a pretty huge surface area to do well. Many of these types of things are better done through process supervisors or even systems like Nomad.

Consul has support for things like https://www.consul.io/api/index.html#blocking-queries so it's possible to create external tooling that senses status changes and takes actions without even having to poll.
