### ISSUE TITLE
C# ConfigureFromEnvironment IndexOutOfRangeException when no port specified in CONSUL_HTTP_ADDR

### ISSUE THREAD

**Issue by MichaelLogutov** [hashicorp/consul#3085]
Consul nuget package 0.7.2.3

When setting environment variable CONSUL_HTTP_ADDR to some IP without port I've got this error when trying to create client with default constructor

```
[IndexOutOfRangeException: Index was outside the bounds of the array.]
   Consul.ConsulClientConfiguration.ConfigureFromEnvironment(UriBuilder consulAddress) +1124
   Consul.ConsulClientConfiguration..ctor() +59
   Consul.ConsulClientConfigurationContainer..ctor() +49
   Consul.ConsulClient..ctor(Action`1 configOverride, Action`1 clientOverride, Action`1 handlerOverride) +86
```

**Comment by highlyunavailable** [comment]
This package is not maintained by the Hashicorp guys - please file this bug over at https://github.com/PlayFab/consuldotnet .

**Comment by MichaelLogutov** [comment]
Sorry for the delay.
New issue on package repo here (if anyone interested): https://github.com/PlayFab/consuldotnet/issues/89
