### ISSUE TITLE
WSDL configuration

### ISSUE THREAD

**Issue by sandeepdingria** [hashicorp/consul#3086]
Hi All

how to put WSDL corresponding to services in Consul. So that any client can go to consul UI and refer/download WSDL from consul UI. Also how to define multiple operation inside one service.

Thanks

If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @sandeepdingria we don't have any plans for anything WSDL-specific in Consul, but this is a good use of Consul's KV store. You can make a KV namespace that's keyed by service name and store the WSDL document there (eg. `service/<name>/wsdl`). Users can browse these using the UI, and if they have a standard format then it's easy for clients to get at them to using the KV HTTP API or `consul kv get`command. We have plans to eventually add KV attributes to services themselves under https://github.com/hashicorp/consul/issues/1107, so with that you can bind them a little closer, but KV should be fine for this use case.

If you have different endpoints for a given service, you can register it multiple times under the same service name but with different tags. Then users can look up `<tag>.<name>.service.consul` depending on what they need. Hope that helps!
