### ISSUE TITLE
Fix nodes count

### ISSUE THREAD

**Issue by toothlessfairy** [hashicorp/consul#3092]
I've got one service running on two nodes but in UI it says that "4 passing" for this service (rocs2 service on the picture). Is there any way to fix that?
![consul](https://cloud.githubusercontent.com/assets/29101396/26640198/bc2a7f7c-462f-11e7-9001-f48e2b6db49c.png)

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
