### ISSUE TITLE
Watches for critical check state launches handlers when checks go to passing state

### ISSUE THREAD

**Issue by toothlessfairy** [hashicorp/consul#3096]
I have a watch in my consul config that supposed to be launched when service checks (actually I have only one check) turns critical:
	"watches": [
    {
        "type": "checks",
        "state": "critical",
        "handler": "notepad"   
    }]
(never mind notepad, it's just for testing)
but notepad starts even when check state goes from critical to passing. Is this behavior OK or I'm doing something wrong?

This watch config I got from https://github.com/hashicorp/consul/issues/2146#issuecomment-228935061

**Comment by slackpad** [comment]
Hi @toothlessfairy the watch handler will get run once initially and then called later when things go critical. The script will get some JSON passed into it as input (see https://www.consul.io/docs/agent/watches.html#type-checks for an example), so you can use that to skip that initial update. Hope that helps!
