### ISSUE TITLE
consul cluster incorrect behaviour when quorum should not be reached

### ISSUE THREAD

**Issue by osadalakmal** [hashicorp/consul#3098]
### `consul version` for both Client and Server
Client:  `v0.8.3`
Server: `v0.8.3`

### `consul info` for both Client and Server
Server:
```
/ # consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = ea2a82b
	version = 0.8.3
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 172.16.238.15:8300
	server = true
raft:
	applied_index = 864
	commit_index = 864
	fsm_pending = 0
	last_contact = 48.817423ms
	last_log_index = 864
	last_log_term = 5
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:592aa52d-9421-819e-c33a-b79663375875 Address:172.16.238.13:8300} {Suffrage:Voter ID:96a9f2b6-eeaf-d222-e29d-7a65cc87be8c Address:172.16.238.15:8300} {Suffrage:Voter ID:bbafbf64-1c25-9f7d-00c2-883bc6f7735f Address:172.16.238.14:8300} {Suffrage:Voter ID:1353543a-09bf-dc6e-cd93-6a9d60ed33f7 Address:172.16.238.10:8300} {Suffrage:Voter ID:cc0ae08c-7b34-1ec9-f353-6f3080ba041b Address:172.16.238.11:8300} {Suffrage:Nonvoter ID:1a68284b-bace-c535-3c00-923784fbe09b Address:172.16.238.12:8300}]
	latest_configuration_index = 863
	num_peers = 4
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 5
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 114
	max_procs = 4
	os = linux
	version = go1.8.1
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 4
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 12
	members = 6
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 21
	members = 6
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Using docker alpine based images from docker hub

### Description of the Issue (and unexpected/desired result)

Starting with a cluster with 6 containers, when 4 containers are killed we expected the last two servers would be unable to achieve quorum.

Instead they seem to just keep on waiting for the last leader to re-appear and not decluster/become unavailable

### Reproduction steps

use https://gist.github.com/osadalakmal/3e94498886e0f4637054fecfccdb94ca for bringing up the containers for the cluster. Then kill four containers.

**Comment by slackpad** [comment]
Hi @osadalakmal, I think this is expected behavior:

> Instead they seem to just keep on waiting for the last leader to re-appear and not decluster/become unavailable

It's not recommended to have an even number of servers, and with 6 servers you can only tolerate 2 server failures, so if you terminate 4 servers then the remaining two will attempt to elect a leader but not be able to because there's no longer a quorum of servers left to perform an election. Can you explain what you were expecting to happen?

**Comment by osadalakmal** [comment]
> It's not recommended to have an even number of servers, 
This is not a very plausible scenario for us since we have to maintain DC symmetry. We usually deploy 2N servers if we have 2 data centres with N servers in each DC. afaiu Raft doesn't impose any restriction that the number of participants have to be an odd number and the only requirement is that a quorum of servers commits a given log entry

 > Can you explain what you were expecting to happen?
I was expecting to see `consul info` and `consul operator raft list-peers` to tell me that there is no cluster formed now. Instead it keeps on outputting the same info as when there were three servers.

**Comment by jinquanni** [comment]
Hi, @slackpad @osadalakmal , i have a simliar question,

consul version for  Server
Server: v0.8.3

Starting with a cluster with 6 server nodes, Then leave 4 servers. It seems  like that the  cluster elector a new  leader and work fine! 
when we say  " with 6 servers you can only tolerate 2 server failures" , the failures means “left” or “failed”? 


[root@node-17:/home/msb/consul]$ ./consul members 
Node     Address            Status  Type    Build  Protocol  DC
server   10.10.10.171:8301  alive   server  0.7.5  2         dc1
server2  10.10.10.172:8301  alive   server  0.7.5  2         dc1
server3  10.10.10.173:8301  left    server  0.7.5  2         dc1
server4  10.10.10.174:8301  left    server  0.7.5  2         dc1
server5  10.10.10.175:8301  left    server  0.7.5  2         dc1
server6  10.10.10.176:8301  left    server  0.7.5  2         dc1

[root@node-17:/home/msb/consul]$ ./consul operator raft -list-peers
Node     ID                 Address            State     Voter
server   10.10.10.171:8300  10.10.10.171:8300  follower  true
server2  10.10.10.172:8300  10.10.10.172:8300  leader    true

[root@node-17:/home/msb/consul]$ curl http://10.10.10.171:8500/v1/status/leader
"10.10.10.172:8300"

**Comment by slackpad** [comment]
> Starting with a cluster with 6 server nodes, Then leave 4 servers. It seems like that the cluster elector a new leader and work fine!

@jinquanni You can reduce the cluster from 6 to 4 if you leave them one at a time since that will reduce the quorum requirements as each server leaves. You can terminate 4 though and still get a leader.

**Comment by slackpad** [comment]
> This is not a very plausible scenario for us since we have to maintain DC symmetry. We usually deploy 2N servers if we have 2 data centres with N servers in each DC. afaiu Raft doesn't impose any restriction that the number of participants have to be an odd number and the only requirement is that a quorum of servers commits a given log entry

That's true, Raft will work with an even number, but the extra servers increase the majority requirements so don't buy you extra fault tolerance. For example, if you have 4 servers can can still only handle the loss of 1 server, which is the same as if you had 3 servers.

It's tricky to apportion your servers if you only have 2 availability zones, as it will always be possible to lose half of your servers in one go. For that I'd probably run a different cluster (different Consul datacenter) in each one and join them together.

> I was expecting to see consul info and consul operator raft list-peers to tell me that there is no cluster formed now. Instead it keeps on outputting the same info as when there were three servers.

As part of Raft, changes to the Raft configuration (known set of servers) go through the consensus process, so it's not possible to make any changes to that during an outage.  There's a relatively new endpoint https://www.consul.io/api/operator/autopilot.html#read-health that will give you information about the live status of the cluster, and will return a "no leader" error if there'e currently no cluster leader and you are in an outage.
