### ISSUE TITLE
consul kv get error goes to stdout instead of stderr

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/consul#3100]
When I get an error from `consul kv get` the error is written to stdout, which means that the error text appears to be the data I asked for. The error should go to stderr instead so it not confused with data.

For example when wrapping `consul` with bash I not only have to check the exit code but I also need to replace the output value with some other value that is not invalid data. I also lose the error messages from logs because I am capturing stdout in a variable.

/cc @evanphx

**Comment by slackpad** [comment]
@cbednarski this should be fixed by https://github.com/hashicorp/consul/pull/2548 as of 0.8.0 - are you seeing this on the latest version of Consul?

**Comment by cbednarski** [comment]
Oops, thanks for the details @slackpad! Looks like we're on 0.7.5. We'll update.
