### ISSUE TITLE
Failed to read key _rexec

### ISSUE THREAD

**Issue by mrinal93** [hashicorp/consul#3148]
I have been facing the following issue intermittently while using the exec feature of consul across DCs

`Failed to read key '_rexec/eadba90c-f9be-a258-1bd8-c51d9a14d091/<node name>/out/00004': Unexpected response code: 500
Failed to read results: Unexpected response code: 500
`
Re-running the command usually helps fix the issue. Could it be because of some network issue with the datacenters?
Consul version: Consul v0.7.1

Operating system and Environment details
CentOS 6.7

**Comment by slackpad** [comment]
Hi that looks like you might be running into connectivity issues from that agent to the Consul servers. Is there anything in the Consul logs when this happens?

**Comment by slackpad** [comment]
Closing since we never heard back.
