### ISSUE TITLE
Running Consul agent as a Windows service  

### ISSUE THREAD

**Issue by ptarpan** [hashicorp/consul#3155]
### `consul version` for both Client and Server
Client: `0.8.1`
Server: `0.8.1`

### `consul info` for both Client and Server
Client: single Windows 7 (agent) node with the following config: 
```
"datacenter": "$DATACENTER",
"bind_addr": "$INSTANCE_PRIV_IP",
"data_dir": "$CONSUL_DATA_DIR",
"log_level": "DEBUG",
"node_name": "$NODE_NAME",
"server": false,
"retry_join": ["$CONSUL_URL"]
```

Server: three Docker containers running on three nodes (one Consul container per node) with the following args:   
```
agent -server -ui -config-dir ${CONSUL_CFG_DIR} -domain ${TLD} ${CONSUL_RECURSORS} -datacenter ${INSTANCE_REGION} -advertise ${INSTANCE_PRIV_IP} -client 0.0.0.0
```

### Operating system and Environment details
Windows 7 Enterprise - 64bit 
### Description of the Issue (and unexpected/desired result)
Consul agent fails to run as a service on Windows. Tried "sc" and "nssm". Both result in an error. There is no hint in the (Windows) syslog as to what is failing exactly. Note: running Consul inline (i.e. not as a service) works fine. 

### Reproduction steps
* Setup/use an existing Linux Consul master cluster. 
* Add a Windows service that runs a Consul agent on Windows 7 and joins the cluster using the client config above.  

### Log Fragments or Link to [gist](https://gist.github.com/)
```
SERVICE_NAME       : consul-agent
TYPE               : 10  WIN32_OWN_PROCESS
STATE              : 1  STOPPED
WIN32_EXIT_CODE    : 1066  (0x42a) -> service-specific error 
SERVICE_EXIT_CODE  : 3  (0x3)
CHECKPOINT         : 0x0
WAIT_HINT          : 0x0
```

**Comment by slackpad** [comment]
@ptarpan is anything output to Consul's log when this happens?

**Comment by mterron** [comment]
NSSM output redirection should show something. Have you set that up?

**Comment by MichaelLogutov** [comment]
Have you updated nssm? After recent windows update nssm needs to be updated

**Comment by slackpad** [comment]
Closing since we never heard back.
