### ISSUE TITLE
Support Casbin as the authorization backend

### ISSUE THREAD

**Issue by hsluoyz** [hashicorp/consul#3159]
[Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I think it's more powerful than the current ACL way, what do you think? Thanks.

**Comment by slackpad** [comment]
Hi thanks for opening an issue. We don't have plans to integrate with Casbin at this time.
