### ISSUE TITLE
Register and deregister services from different nodes

### ISSUE THREAD

**Issue by toothlessfairy** [hashicorp/consul#3169]
I need to be able to deregister service not from the agent it was registered. 
If I register service from local agent, I can't deregister it from another agent even if I try to do this using catalog entry (service appears back after deregistration).
But If I try to register service in catalog direclty it disappears from catalog in a few seconds.
So is there a way to deregister service not from the agent that it has been registered with?

**Comment by slackpad** [comment]
Hi @toothlessfairy there's currently not a way to do that. If the agent where the service was registered is gone, then the catalog can be used, but if that agent is still around then it will sync the service back via [anti-entropy](https://www.consul.io/docs/internals/anti-entropy.html). You'd need to use the Agent API on the agent where it is registered, or use something like `deregister_critical_service_after` in a [health check](https://www.consul.io/docs/agent/checks.html) for that service to get it to auto-remove itself.
