### ISSUE TITLE
Feature Request: Pushbullet Support.

### ISSUE THREAD

**Issue by UnR34L** [hashicorp/consul#3170]
Could we please have support for Pushbullet.

**Comment by slackpad** [comment]
Hi @UnR34L thanks for opening an issue. I don't see us doing this in core, but this looks like a good project to be built outside of Consul, using Consul's APIs like blocking queries. You might want to look at some of the existing alerting systems that talk to Consul, like https://github.com/kyhavlov/consul-alerting.
