### ISSUE TITLE
Change host-based UUIDs to opt-in

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3171]
We've had a high number of users struggle to deploy newer versions of Consul with host-based UUIDs because of various edge cases of how the host IDs work in Docker, on specially-provisioned machines, etc. We need to change the sense of this to opt-in instead of opt-out by changing the default for [`-disable-host-node-id`](https://www.consul.io/docs/agent/options.html#_disable_host_node_id) to `true`.

**Comment by preetapan** [comment]
Won't this break people not running in containers if they relied on host based node ids for anything? e.g. nagios alerts if consul agent on a host is down. 
Perhaps the documentation should make it clear that node-ids are an implementation detail, and not to be relied upon for external systems (monitoring tools etc)

**Comment by slackpad** [comment]
If they relied on host-based IDs they'd have to opt back in, so we will document this as a breaking change for 0.9 that people need to consider when they upgrade. I think for the vast majority of users they are using the node name for things like alerts. The host-based IDs case really just made Consul + Nomad easier to use together because both would use the same IDs for a node, so we can document how to configure them for that.

**Comment by nugend** [comment]
Should an issue be opened in the nomad project to highlight this? FWIW, I'm starting to use Nomad and have been using Consul for a while and am really not sure how the host ID actually surfaces in regular usage of either or what would be affected if this wasn't set when using Nomad.

**Comment by slackpad** [comment]
Hi @nugend Nomad is making a similar default change over on https://github.com/hashicorp/nomad/pull/2735. If you can use host-based IDs, then Nomad and Consul will use the same UUID, so when you see which Nomad node a job is running on you could `ssh <uuid>.node.consul`, for example. It's a pretty subtle benefit, so we decided to make this opt-in because host-based IDs caused folks trouble in other areas.

**Comment by nugend** [comment]
Thanks. Sometimes it's just a little hard to get a handle on some of the concepts from the docs alone.

**Comment by Nmishin** [comment]
hi @slackpad 
previously I have a Consul and clients 0.8.4 version, after pugrade Consul server to the 1.3.1 version I sow in logs errors something like that:
` consul: RPC failed to server 10.10.9.5:8300: rpc error: rpc error making call: failed inserting node: Error while renaming Node ID: "e1d3e56d-9226-bf3a-571d-2a7e500c37dd": Node name dev-test-zcwf is reserved by node de084f26-6488-71a8-812f-e5f680ef4a17 with name dev-test-zcwf` 
As I understand `dev-test-zcwf` node was recreated with the same name, but a new id, what should I do with this?
Do I need set `-disable-host-node-id` to false for preventing randomly generated node id? 
Thanks.
