### ISSUE TITLE
Unix sockets fails with 'invalid user' when cross-compiling

### ISSUE THREAD

**Issue by jonhadfield** [hashicorp/consul#3184]
Version: Consul v0.8.4-68-g42f60b04-dev (42f60b04+CHANGES)

After cross-compiling for Linux amd64 on MacOS, and using unix sockets, the agent fails to start with:
`==> Error starting agent: Failed setting up HTTP socket: invalid user specified: consul
`
Printing err returns: 'Lookup requires cgo'

This is due to use of cgo here: https://github.com/hashicorp/consul/blob/master/agent/util.go#L116

I realise this isn't an issue the project can fix, but maybe worth a mention in the documentation.
Apologies if it is mentioned and I've missed it.

**Update:** 
The pre-compiled binary for 64-bit Linux downloaded from here also has the same issue when run on 64-bit Linux: https://www.consul.io/downloads.html.
The issue goes away when compiling from source on the same architecture as the target.

**Comment by slackpad** [comment]
We can also take a quick look to see if there's an alternative. We definitely don't want to introduce `cgo`.

**Comment by jonhadfield** [comment]
[This page](https://dominik.honnef.co/posts/2013/12/go-stdlib-cgo/) has some useful info and suggests at least one other library within consul, e.g. crypto/x509, may also cause issues for some users.
IMHO, the simplest solution is:
- provide binaries that have been built on the same architecture as the target, i.e., avoid cross-compilation
- document this issue in the FAQs and build guide
- return a useful error where this issue is encountered (https://github.com/hashicorp/consul/issues/3188 covers the user.Lookup() issue)

**Comment by magiconair** [comment]
I'm not sure whether that's still relevant. Did you try `CGO_ENABLED=0` ?

**Comment by jonhadfield** [comment]
Just tried that with CGO_ENABLED=0 (compiled on linux amd64 for target linux amd64) and it results in the same error:
`user: Lookup requires cgo`
Note: that's _with_ the PR as, without it, if user.Lookup() returns an error, it always returns: 
`invalid user specified: xxxxx`

**Comment by whit537** [comment]
Permalinking to avoid rot ...

> This is due to use of cgo here:

https://github.com/hashicorp/consul/blob/42f60b04bba2e4391e9a95a218c873986ebeea6b/agent/util.go#L116

> This script

https://github.com/hashicorp/consul/blob/410e96108a216ec4a429966d23e1f1be78cee87f/scripts/build.sh#L6
