### ISSUE TITLE
Watch handlers are not being stopped on reload (regression in 0.8.4)

### ISSUE THREAD

**Issue by preetapan** [hashicorp/consul#3185]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `0.8.4`
Server: `0.8.4`

### Description of the Issue (and unexpected/desired result)
Found when working on issue #3018. The file descriptor bug described there still exists. However, prior to 0.8.4, when `consul reload` is called , any existing watch handlers were closed. After 0.8.4, the old handlers are not stopped, and each new consul reload increases the number of handlers by n, if the config had n handlers to start with. 
### Reproduction steps
Configure a single watch handler that echoes to stdout, and start consul agent. Run consul reload a few times, you will notice multiple lines of output to stdout. This is because the previous watch handler is not stopped when reload is called. This can cause problems with users using watch handlers to restart services or count updates to keys, because it keeps linearly increasing with the number of calls to consul reloadl
### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
@preetapan this should be fixed by #3189, I think.
