### ISSUE TITLE
Consul watch for service with no node associated

### ISSUE THREAD

**Issue by toothlessfairy** [hashicorp/consul#3192]
I have a cluster with consul and some service that must be running on any machine in this cluster. When this service dies on one machine the handler should be invoked to start this service on other machine. So my question is: is there a way to create a check not associated with any node but for the whole cluster? I can't create this check using agent endpoint cause I need something to check for this service to work for any number or any set of nodes available on my cluster

**Comment by preetapan** [comment]
@toothlessfairy could you leverage the (service)[https://www.consul.io/docs/agent/watches.html#type-service] check? Your service should have a healthcheck configured. You can make a handler that's monitoring the output of the returned json (don't set the passingonly param). When it returns failing checks, it means that service has died and your handler can take the appropriate action (issue command to start the service again somewhere else). 

Another option might be to leverage [events] (https://www.consul.io/docs/agent/watches.html#event). You could issue an event using the appropriate end point when you see the service check fail, and then create a watch on the event to issue a restart. That seems more complicated than the first method though

**Comment by slackpad** [comment]
Consul runs the health checks on the node where the service is registered; it doesn't have a way for the Consul servers to perform checks on behalf of some other node in the cluster. Having some process that you run in your cluster that uses Consul's APIs or watches is the best way to accomplish this. You can use things like `consul lock` to run multiple of these processes if you need to for high availability.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
