### ISSUE TITLE
When one consul host down and rejoin, the service registered on this host have problem on  'Check pass state'

### ISSUE THREAD

**Issue by wujianfeirun** [hashicorp/consul#3197]
On this situation,  the service always keep 'pass' state, even though the service do not send 'Check pass'  request anymore.

**Comment by slackpad** [comment]
Hi @wujianfeirun please take a look at this thread which explains what's going on - https://github.com/hashicorp/consul/issues/258#issuecomment-49810564. Hope that helps!
