### ISSUE TITLE
Dev mode Consul with ACL fails to sync services registered on Agent with Catalog

### ISSUE THREAD

**Issue by jackyshalom** [hashicorp/consul#3198]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:
I am working with dev mode with only one server.

### `consul version` for both Client and Server
Server: `[0.7.2]`

### `consul info` for both Client and Server

Server:
```
[agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 3
build:
        prerelease =
        revision = 'a9afa0c
        version = 0.7.2
consul:
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 10.75.110.16:16300
        server = true
raft:
        applied_index = 7400
        commit_index = 7400
        fsm_pending = 0
        last_contact = never
        last_log_index = 7400
        last_log_term = 4
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:10.75.110.16:16300 Address:10.75.110.16:16300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 4
runtime:
        arch = amd64
        cpu_count = 6
        goroutines = 52
        max_procs = 6
        os = linux
        version = go1.7.3
serf_lan:
        encrypted = false
        event_queue = 1
        event_time = 4
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
]
```

### Operating system and Environment details
Linux invpbg992 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
### Description of the Issue (and unexpected/desired result)

When working with consul with "bootstrap_expect": 1 and ACL.
Registering services using Agent end-point, fail to sync to catalog due to consul: dropping service "****" from result due to ACLs .
 I was registering the service both with master token ("amc") or specific write token ("amdocs-sd-read-write-token") for the service, but none of those worked.
 

[
    {
        "ID": "33ccf0b1-6d13-2b4d-7e68-cb79c73815f6",
        "Name": "*******",
        "Type": "client",
        "Rules": "{\"service\":{\"com-amdocs-dev-amc\":{\"policy\":\"write\"}}}",
        "CreateIndex": 15,
        "ModifyIndex": 585
    },
    {
        "ID": "****",
        "Name": "Master Token",
        "Type": "management",
        "Rules": "",
        "CreateIndex": 5,
        "ModifyIndex": 5
    },
    {
        "ID": "anonymous",
        "Name": "Anonymous Token",
        "Type": "client",
        "Rules": "",
        "CreateIndex": 4,
        "ModifyIndex": 4
    }
]
 

### Reproduction steps
1. register service on agent with master/write token specific to the service prefix:

curl -X PUT -d @service.json http://127.0.0.1:16500/v1/agent/service/register?token=<master or com-amdocs-dev-amc policy ACL token>

2. The result i get when i am doing lookup of the services on the agent

curl http://localhost:16500/v1/agent/services?pretty
{
    "com-amdocs-dev-amc-amcdaemonservice:3000": {
        "ID": "com-amdocs-dev-amc-amcdaemonservice:3000",
        "Service": "com-amdocs-dev-amc-amcdaemonservice",
        "Tags": [
            "application=tc",
            "command=daemonactivation"
        ],
        "Address": "localhost",
        "Port": 3000,
        "EnableTagOverride": false,
        "CreateIndex": 0,
        "ModifyIndex": 0
    },
    "com-amdocs-dev-amc-avi": {
        "ID": "com-amdocs-dev-amc-avi",
        "Service": "com-amdocs-dev-amc-avi",
        "Tags": [
            "specific",
            "v1"
        ],
        "Address": "127.0.0.1",
        "Port": 8000,
        "EnableTagOverride": false,
        "CreateIndex": 0,
        "ModifyIndex": 0
    },
    "consul": {
        "ID": "consul",
        "Service": "consul",
        "Tags": [],
        "Address": "",
        "Port": 16300,
        "EnableTagOverride": false,
        "CreateIndex": 0,
        "ModifyIndex": 0
    }
}

3. But doing the lookup on the catalog retrieves only the consul service  

> curl http://localhost:16500/v1/catalog/services?pretty?token=<master token>
{"consul":[]}

### Log Fragments or Link to [gist](https://gist.github.com/)

Running in /fndusers/fnd/users/amctest/consul/scripts

********  Staring Server ******** 

==> WARNING: BootstrapExpect Mode is specified as 1; this is the same as Bootstrap mode.
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.2'
         Node name: 'amctest@server1'
        Datacenter: 'amdocs-dc1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 16500, HTTPS: -1, DNS: 16600, RPC: 16400)
      Cluster Addr: 10.75.110.16 (LAN: 16301, WAN: 16302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2017/06/27 11:33:32 [INFO] raft: Restored from snapshot 4-8192-1498492490703
    2017/06/27 11:33:32 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:10.75.110.16:16300 Address:10.75.110.16:16300}]
    2017/06/27 11:33:32 [INFO] raft: Node at 10.75.110.16:16300 [Follower] entering Follower state (Leader: "")
    2017/06/27 11:33:32 [INFO] serf: Ignoring previous leave in snapshot
    2017/06/27 11:33:32 [INFO] serf: EventMemberJoin: amctest@server1 10.75.110.16
    2017/06/27 11:33:32 [WARN] serf: Failed to re-join any previously known node
    2017/06/27 11:33:32 [INFO] consul: Adding LAN server amctest@server1 (Addr: tcp/10.75.110.16:16300) (DC: amdocs-dc1)
    2017/06/27 11:33:32 [INFO] serf: Ignoring previous leave in snapshot
    2017/06/27 11:33:32 [INFO] serf: EventMemberJoin: amctest@server1.amdocs-dc1 10.75.110.16
    2017/06/27 11:33:32 [WARN] serf: Failed to re-join any previously known node
    2017/06/27 11:33:32 [INFO] consul: Adding WAN server amctest@server1.amdocs-dc1 (Addr: tcp/10.75.110.16:16300) (DC: amdocs-dc1)
    2017/06/27 11:33:32 [DEBUG] agent: restored service definition "com-amdocs-dev-amc-avi" from "../data/services/a2a0c07fe8ea104c4c04d1e58f48c7b7"
    2017/06/27 11:33:32 [DEBUG] agent: restored service definition "com-amdocs-dev-amc-amcdaemonservice:3000" from "../data/services/f6cb0523fb7a4f0355498d49a6b89bcc"
    2017/06/27 11:33:32 [DEBUG] Service tag "application=tc" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2017/06/27 11:33:32 [DEBUG] Service tag "command=daemonactivation" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2017/06/27 11:33:39 [ERR] agent: failed to sync remote state: No cluster leader
    2017/06/27 11:33:40 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2017/06/27 11:33:40 [INFO] raft: Node at 10.75.110.16:16300 [Candidate] entering Candidate state in term 5
    2017/06/27 11:33:40 [DEBUG] raft: Votes needed: 1
    2017/06/27 11:33:40 [DEBUG] raft: Vote granted from 10.75.110.16:16300 in term 5. Tally: 1
    2017/06/27 11:33:40 [INFO] raft: Election won. Tally: 1
    2017/06/27 11:33:40 [INFO] raft: Node at 10.75.110.16:16300 [Leader] entering Leader state
    2017/06/27 11:33:40 [INFO] consul: cluster leadership acquired
    2017/06/27 11:33:40 [INFO] consul: New leader elected: amctest@server1
    2017/06/27 11:33:40 [DEBUG] consul: reset tombstone GC to index 12433
    2017/06/27 11:33:43 [DEBUG] consul: dropping service "com-amdocs-dev-amc-avi" from result due to ACLs
    2017/06/27 11:33:43 [DEBUG] consul: dropping service "com-amdocs-dev-amc-amcdaemonservice:3000" from result due to ACLs
    2017/06/27 11:33:43 [DEBUG] agent: Service 'consul' in sync
    2017/06/27 11:33:43 [INFO] agent: Synced service 'com-amdocs-dev-amc-avi'
    2017/06/27 11:33:43 [INFO] agent: Synced service 'com-amdocs-dev-amc-amcdaemonservice:3000'
    2017/06/27 11:33:43 [DEBUG] agent: Node info in sync
    2017/06/27 11:35:04 [DEBUG] consul: dropping service "com-amdocs-dev-amc-amcdaemonservice:3000" from result due to ACLs
    2017/06/27 11:35:04 [DEBUG] consul: dropping service "com-amdocs-dev-amc-avi" from result due to ACLs
    2017/06/27 11:35:04 [INFO] agent: Synced service 'com-amdocs-dev-amc-amcdaemonservice:3000'
    2017/06/27 11:35:04 [DEBUG] agent: Service 'consul' in sync
    2017/06/27 11:35:04 [INFO] agent: Synced service 'com-amdocs-dev-amc-avi'
    2017/06/27 11:35:04 [DEBUG] agent: Node info in sync

**Comment by slackpad** [comment]
Hi @jackyshalom it looks like your curl syntax might not be passing the token correctly:

`curl http://localhost:16500/v1/catalog/services?pretty?token=`

This should be:

`curl 'http://localhost:16500/v1/catalog/services?pretty&token='`

The `&` can be tricky with the shell, so I quoted the example as well. Hope that helps!
