### ISSUE TITLE
Consul's DNS parser allows junk between the DC and the consul subdomain

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3200]
This captures an issue that came in from [Google groups](https://groups.google.com/forum/#!msg/consul-tool/nwSoU6E5RuM/PO0bUNivDwAJ). It looks like Consul quietly drops anything after the DC and before the Consul subdomain:

```
$: dig @127.0.0.1 -p 8600 consul-server0.node.eu-west-2.consul
;; ANSWER SECTION:
consul-server0.node.eu-west-2.consul. 5 IN A    172.26.2.14

$: dig @127.0.0.1 -p 8600 consul-server0.node.eu-west-2.randomstring.consul
;; ANSWER SECTION:
consul-server0.node.eu-west-2.randomstring.consul. 5 IN A 172.26.2.14

$: dig @127.0.0.1 -p 8600 consul-server0.node.eu-west-2.moregarbage.randomstring.consul
;; ANSWER SECTION:
consul-server0.node.eu-west-2.moregarbage.randomstring.consul. 5 IN A 172.26.2.14
```

Consul should parse this strictly and return an NXDOMAIN error for the cases with junk. I couldn't reproduce this anywhere other than between the DC and the Consul subdomain.

**Comment by corford** [comment]
Hi James

For the fix, it's important that it still allows subdomains if they're set intentionally via the -domain cli flag. E.g. in our case, we use <nodename>.node[.dc].prod.consul for our production cluster and <nodename>.node[.dc].test.consul for our test cluster.

**Comment by corford** [comment]
Just circling back to see if there has been any progress on this? Worried that the longer it's left, the more pain it risks causing people when the bug's squashed (e.g. misconfigured service discovery that currently works thanks to the bug).

**Comment by magiconair** [comment]
I can have a look at this.

**Comment by magiconair** [comment]
The `dispatch` method first strips off the domain before continuing with the parsing, AFAICT.

https://github.com/hashicorp/consul/blob/v1.0.0/agent/dns.go#L360-L488

However, it seems the implementation is a bit too flexible and considers the last element before the `node`, `service`, ... element the datacenter and ignores the rest.

**Comment by corford** [comment]
Thanks very much @magiconair Fix seems good and looking forward to this landing in 1.0.1
