### ISSUE TITLE
Service appear and disappear

### ISSUE THREAD

**Issue by mynameisgv** [hashicorp/consul#3209]
Version 0.8.3.

This issue is similar to #3122

I see the agent showing with the services/checks in ui and then disappearing. This keeps happening every few seconds.
Is there a fix for this.
in the agent box, when i do consul members, it is listing properly. 
But logs show that the sync is happening constantly. 

Thanks

**Comment by mynameisgv** [comment]
In the server/master logs in see
2017/06/30 15:50:48 [INFO] consul: member 'node1' joined, marking health alive
    2017/06/30 15:51:48 [INFO] consul: member 'node1' left, deregistering
    2017/06/30 15:52:48 [INFO] consul: member 'node1' joined, marking health alive
    2017/06/30 15:53:48 [INFO] consul: member 'node1' left, deregistering
    2017/06/30 15:53:48 [INFO] consul: member 'node1' joined, marking health alive
    2017/06/30 15:54:48 [INFO] consul: member 'node1' left, deregistering

**Comment by slackpad** [comment]
Hi @mynameisgv this is almost always caused by not having full mesh connectivity on 8301/tcp and 8301/udp in your cluster. On `node1` do the logs mention anything about refuting suspect messages?

**Comment by mynameisgv** [comment]
Hello,

I was able to find a workaround. i have had this issue 3 times now and all 3 times the server name under which it was registered was changed from SERVERNAME to servername.(upper to lower)
IP address of the host was same. So everytime this happens now, i stop consul  on those servers for 72 hrs and wait for both nodes to disappear in consul members. then i got register again.


Thanks.

**Comment by slackpad** [comment]
Ok thanks for the follow up!

**Comment by HisenWu** [comment]
### I have the same problem. The log at the `leader node` is shown as: 
```
[INFO] consul: member 'Console-Nginx02-1.1.1.1' left, deregistering
[INFO] consul: member 'console-nginx02-1.1.1.1' joined, marking health alive
```
In order to solve the problem quickly, avoid to wait 72 hrs. I modified the `node_name` field in the configuration file, Change to another name. Different from `Console-Nginx02-1.1.1.1` and `console-nginx02-1.1.1.1`.

### Registration of the nodes and services, try to avoid just the case distinction, reduce unnecessary problems.
