### ISSUE TITLE
Chained CNAME resolution fails

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#321]
Consul only does a single level of CNAME resolution, but this may not be enough for services like RDS.

**Comment by begriffs** [comment]
I am also encountering this problem when trying to use an RDS external service. What is the priority on this issue, any plans to incorporate the above fix?

**Comment by armon** [comment]
@begriffs Should be an easy enough fix, we'll try to make sure its in 0.5.1

**Comment by begriffs** [comment]
Thanks a lot.
