### ISSUE TITLE
Consul Web-UI crops on upright screens

### ISSUE THREAD

**Issue by dreh23** [hashicorp/consul#3213]
I have an upright screen - the Web-UI is not using the whole screen it crops at around the half and the list of jobs are in a scrollable sub window. Consul should dynamically allocate the whole screen. This is a minor - but annoying issue.

```
Consul v0.8.1

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Mozilla Firefox 54.0 (64-bit)
Google Chrome Version 59.0.3071.10
```

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!

**Comment by johncowen** [comment]
Hey @dreh23 👋 

This was something the UI team has recently had a particular interest in, I was wondering if you'd had time to try out the new Consul UI to see if thats improved matters?

FYI the team are currently looking at standardising on ways to do more CSS testing (and CSS regression testing) to cater for as many user setups as possible ( @noelledaley )

Thanks,

John
