### ISSUE TITLE
[Question] Can we use consul kv put cli use Transaction

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/consul#3214]
Can we use consul kv put cli use Transaction?

I just found http api  /txn

**Comment by slackpad** [comment]
Hi @linuxgood1230 currently there's not a command to do that - /v1/txn is only available as an API, but not a CLI. There's https://www.consul.io/docs/commands/kv/import.html, but that adds the keys individually so the write isn't atomic. We'd welcome a PR to add /v1/txn support to that command, but don't have any plans to do that right now on our roadmap.
