### ISSUE TITLE
Waiting for Consul Reload completion

### ISSUE THREAD

**Issue by rjeze** [hashicorp/consul#3215]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `0.6.3`
Server: `0.6.3`

### Operating system and Environment details
Windows 7, .Net 4.5

### Description of the Issue (and unexpected/desired result)
I am using consul cli to reload the configuration. Is there any way I can watch the successful completion consul reload ?

**Comment by RajeshKumar1990** [comment]
you can go to http://localhost:8500 to see the consul ui. If u added any new service u can see it there and can also check the health of the node and services anytime u want.Please make sure that u have given -ui flag when u run the consul.
Hope this helps.....

**Comment by slackpad** [comment]
Hi @rjeze you can look in Consul's logs to see this (or use `consul monitor`). In addition, the reload command should return a 0 if the reload succeeds. Hope that helps!
