### ISSUE TITLE
Can same node act as client and server

### ISSUE THREAD

**Issue by RajeshKumar1990** [hashicorp/consul#3219]
I am new in using consul.Its seems very interesting to learn it.My doubt is, can a same node act as client and server.First i started the node as client like this  
`consul agent  -ui  -data-dir=C:/tmp/consul -node=agent-two -bind=172.20.20.113 -config-dir=C:/etc/consul.d`

Then when i started the server like this 

`consul agent -server -data-dir=C:/tmp/consul -node=agent-three -bind=172.20.20.113 -config-dir=C:/etc/consul.d`
I m getting the following error 
```
==> Starting Consul agent...
==> Error starting agent: Failed to start Consul server: Failed to start LAN Serf: Failed to create
memberlist: Could not set up network transport: Failed to start TCP listener on "192.168.0.113" port
8301: listen tcp 192.168.0.113:8301: bind: Only one usage of each socket address (protocol/network 
address/port) is normally permitted.
```
I know the reason for this error as the client already is using the port.
Is there any workaround.Thanks.

**Comment by edef1c** [comment]
The server already provides the "client" functionality. There's no need to run two processes.

**Comment by RajeshKumar1990** [comment]
okay..Thanks.....I will close the issue.

**Comment by chrissound** [comment]
How should a single server daemon be setup though?

Having just the server daemon running: `[ERR] agent: failed to sync remote state: No cluster leader`

The web UI also has an error of:

```
500 (The backend responded with an error)
Consul returned an error. You may have visited a URL that is loading an unknown resource, so you can try going back to the root. If your ACL token was not found you can reset it, and then you will be redirected to the settings page to enter a new ACL token.
```

**Comment by danbst** [comment]
@edef1c well in some cases you really really want 2 consuls on same node. Citing nomad docs:

> An important requirement is that each Nomad agent talks to a unique Consul agent. Nomad agents should be configured to talk to Consul agents and not Consul servers. If you are observing flapping services, you may have multiple Nomad agents talking to the same Consul agent. 

So I wanted to run all of consul server, nomad server and nomad agent on each node in cluster, but ended up with starting a separate consul client (4 services in total on each node) because of this requirement.

Back to original question, all I had to do was to change ports for second consul agent:
```
          bind_addr = aws_private_ip;
          retry_join = [ "${aws_private_ip}:8301" ];
          # ### retry join works only if you don't override ports
          #   retry_join = [ "provider=aws tag_key=... tag_value=..." ];
          ports = {
              dns = 8610;
              http = 8611;
              https = 8612;
              serf_lan = 8613;
          };
```
