### ISSUE TITLE
question about the ModifyIndex for a service

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#3224]
What's the scope the ModifyIndex is incremented? per agent or per cluster?
I have two bunch of services, one is registered via client and the other via server, I want to know if the ModifyIndex for them is handled separately or globally.

**Comment by preetapan** [comment]
ModifyIndex and CreateIndex come from the raft layer and are per cluster, not per agent. 

When you register using the /agent endpoint (I am assuming that's what you meant when you say registering via client) it syncs that up with the cluster to reconcile its state with the global state. According to the docs, this is preferred over using the [ /catalog](https://www.consul.io/api/catalog.html#register-entity) endpoints.

**Comment by hehailong5** [comment]
OK. I got it. thank you for the clarity
