### ISSUE TITLE
Client: No API service registration possible

### ISSUE THREAD

**Issue by discointheair** [hashicorp/consul#3227]
### `consul version` for both Client and Server
Client:  v0.8.4
Server: v0.8.4

### `consul info` for both Client and Server
**Client:**
agent:
	check_monitors = 5
	check_ttls = 0
	checks = 5
	services = 5
build:
	prerelease = 
	revision = f436077
	version = 0.8.4
consul:
	known_servers = 2
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 59
	max_procs = 2
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 155
	members = 3
	query_queue = 0
	query_time = 1

**Server:**
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = f436077
	version = 0.8.4
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.2.31.66:80
	server = true
raft:
	applied_index = 50532
	commit_index = 50532
	fsm_pending = 0
	last_contact = 19.739886ms
	last_log_index = 50532
	last_log_term = 3
	last_snapshot_index = 49152
	last_snapshot_term = 3
	latest_configuration = [{Suffrage:Voter ID:10.XX.XX.6:80 Address:10.XX.XX.6:80} {Suffrage:Voter ID:10.XX.XX.2:80 Address:10.XX.XX.2:80}]
	latest_configuration_index = 1
	num_peers = 1
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 3
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 65
	max_procs = 2
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 155
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2
	members = 2
	query_queue = 0
	query_time = 1

### Operating system and Environment details
Redhat, docker 1.10.3

### Description of the Issue (and unexpected/desired result)

My Consul Client has an own agent ACL key with write permissions to any kind of object (key, service, node, agent) defined like this:

```
	"service": {
	 "": {
		 "policy": "write"
	 }
```
 
When I start the client and there is a json file for a service registration, then the service is available in consul like expected.

If I use the API (/v1/agent/services) at the client node with the client ACL token to put the same service definition there is an error message (with trace level):
[ERR] http: Request PUT /v1/agent/service/register, error: Permission denied from=10.XX.XX.XX:23758

curl --header X-Consul-Token: ClientToken --request PUT --data @/tmp/payload.json https://10.XX.XX.9:443/v1/agent/service/register

When I use the server master ACL token (or any other client token) at the client node the service will be available:

curl --header X-Consul-Token: MasterToken --request PUT --data @/tmp/payload.json https://10.XX.XX.9:443/v1/agent/service/register

curl --header X-Consul-Token: OtherClientToken --request PUT --data @/tmp/payload.json https://10.XX.XX.9:443/v1/agent/service/register

ACL keys for the client:
```
{	"acl_agent_master_token":"ClientToken",
	"acl_agent_token":"ClientToken",
	"acl_token":"ClientToken" 
}
```

The strange things /questions for me:
-Why the service can be registered with a json at startup and not via API with the same ClientToken?
-Why and at which point is the error msg thrown? 
-Why it is possible to register the service with MasterToken or any other client token but not with the own token of the client?
-How can I prevent that a foreign OtherClientToken can connect to my own client – I think that’s maybe possible with ACL rules.
 

### Reproduction steps
-Run a Consul server with "acl_default_policy":"deny"
-Create a client ACL key but allow all (for simplicity) 
-Start a client with the client ACL token (acl_agent_master_token, acl_agent_token, acl_token), a json file service definition and join the consul server.
 -> The service has to be registered now.
-Take the same service definition but use the API at the client to register it with Client ACL token 
 -> There should be the error message in the client log and the service is not registered
-Do the same with the Master token
 -> There should be no error message and the service is registered.
-Clone the ClientToken and use the CloneClientToken to register the Service.
 -> There should be no error message and the service is registered.

### Log Fragments or Link to [gist](https://gist.github.com/)

**ACL at the Client:**
```
{	"acl_agent_master_token":"ClientToken",
	"acl_agent_token":"ClientToken",
	"acl_token":"ClientToken" 
}
```
**ACL at the Servers:**
```
{
  "acl_master_token":"MasterToken",
  "acl_default_policy":"deny",
  "acl_down_policy":"deny"
}

```
**Rules for Client Token**
`{ "key": { "/": { "policy": "write" } }, "service": { "": { "policy": "write" } }, "node": { "": { "policy": "write" } }, "agent": { "": { "policy": "write" } }, "session": {"": {"policy": "write"}},"event": { "": { "policy": "write" } }, "query": {"": {"policy": "write"}}}`

**Service for Client startup**
```
{
	"service": {
		"name": "iamhere",
		"address": "1.2.3.4",
		"port": 443,
		"enableTagOverride": false,
		"checks": [
			{
				"script": "curl 127.0.0.1:443 >/dev/null 2>&1",
				"interval": "10s"
			}
		]
	}
}
```

**Service for API payload**
```
{
	"id": "iamthere",
	"name": "iamthere",
	"address": "1.2.3.5",
	"port": 443,
	"enableTagOverride": false,
	"checks": [
		{
			"DeregisterCriticalServiceAfter": "2m",
			"script": "curl 127.0.0.1:443 >/dev/null 2>&1",
			"interval": "10s"
		}
	]
}
```

**curl to put the service**
curl -s -k --header X-Consul-Token: ClientToken --request PUT --data @/tmp/payload.json https://10.XX.XX.9:443/v1/agent/service/register

**Comment by discointheair** [comment]
If so is confused about my config please read my question here:
[Consul and heterogeneous network](https://groups.google.com/forum/#!topic/consul-tool/vM0wfYowyIU)

**Comment by slackpad** [comment]
Hi @discointheair the `acl_agent_master_token` is a special token that has a fixed ACL policy associated with it - https://www.consul.io/docs/guides/acl.html#acl-agent-master-token. There's a special case in the agent's ACL lookup path that gives back this policy if the `acl_agent_master_token` is given, so it's not getting the policy you created for that token when you use it. You'd want to set `acl_agent_master_token` to something else to avoid this. Hope that helps!

**Comment by discointheair** [comment]
Hi @slackpad 
Thank you. After using v0.9 the problem was not there anymore.
Will check this in three weeks after my holidays.
