### ISSUE TITLE
I closed the app but still the service check is success

### ISSUE THREAD

**Issue by RajeshKumar1990** [hashicorp/consul#3232]
I use golang for my API app.I added the service running in cluster of two nodes in consul  where both acts as server where one of them acts as a client as well.
node1 server+client 192.168.0.113(server running in 8010 port)
node2 server 192.168.0.91(server running in 8030 port)
 But when i close the application running in 192.168.0.113:8010 , the services are not updated still showing that the service health check on 192.168.0.113 is passed.
![consul](https://user-images.githubusercontent.com/22511293/27903039-7eaf43b0-626a-11e7-9249-ab70a7038739.JPG)

May i know what went wrong.Thanks

**Comment by mterron** [comment]
Did you define a healthcheck?

**Comment by RajeshKumar1990** [comment]
Yes....
Here is my config.d file 
{
	"services":[
		{
			"id":"id1",
			"name":"Employee",
			"tags":["urlprefix-/v1/employee"],
			"address":"192.168.0.91",		
			"port":8030,
			"enableTagOverride":false,
			"checks":[
				{
					"id":"api",
					"name":"HTTP API on  port 5000",
					"http":"http://192.168.0.113:9998/health",
					"interval":"2s",
					"timeout":"1s"	
				}
		     ]
		},
		{
			"id":"id2",
			"name":"Auth",
			"tags":["urlprefix-/v1/auth"],
			"address":"192.168.0.113",		
			"port":8010,
			"enableTagOverride":false,
			"checks":[
				{
					"id":"api1",
					"name":"HTTP API on  port 5000",
					"http":"http://192.168.0.113:9998/health",
					"interval":"2s",
					"timeout":"1s"	
				}
		     ]
		},
		{
			"id":"id3",
			"name":"Common",
			"tags":["urlprefix-/v1/common"],
			"address":"192.168.0.113",		
			"port":8010,
			"enableTagOverride":false,
			"checks":[
				{
					"id":"api2",
					"name":"HTTP API on  port 5000",
					"http":"http://192.168.0.113:9998/health",
					"interval":"2s",
					"timeout":"1s"	
				}
		     ]
		},
		{
			"id":"id4",
			"name":"Permission",
			"tags":["urlprefix-/permission"],
			"address":"192.168.0.113",		
			"port":8010,
			"enableTagOverride":false,
			"checks":[
				{
					"id":"api3",
					"name":"HTTP API on  port 5000",
					"http":"http://192.168.0.113:9998/health",
					"interval":"2s",
					"timeout":"1s"	
				}
		     ]
		},
				{
			"id":"id5",
			"name":"Permission",
			"tags":["urlprefix-/redirect"],
			"address":"192.168.0.113",		
			"port":8010,
			"enableTagOverride":false,
			"checks":[
				{
					"id":"api4",
					"name":"HTTP API on  port 5000",
					"http":"http://192.168.0.113:9998/health",
					"interval":"2s",
					"timeout":"1s"	
				}
		     ]
		}
	]
}
Thanks

**Comment by mterron** [comment]
you are always querying http://192.168.0.113:9998/health. As long as that is up, all your apps will show up as up.

**Comment by magiconair** [comment]
You are using the fabio health endpoint which will be OK as long as fabio is up. Your service needs to provide its own `/health` (or similar) endpoint.

**Comment by RajeshKumar1990** [comment]
thanks @magiconair ..Understood clear and well.Implemented /health endpoint in my service and now working as it should.....I am closing this issue.
Once again thanks......

**Comment by magiconair** [comment]
Glad you found it.
