### ISSUE TITLE
Update golang.org/x/sys/unix package 

### ISSUE THREAD

**Issue by kbhute-ibm** [hashicorp/consul#3240]
Hi,

While running`make test` for Consul 0.8.5 on s390x architecture, it fails due to unavailability of s390x files in vendor/golang.org/x/sys/unix. Could anyone please update golang.org/x/sys/unix package inside Consul vendor/ folder?

Thanks in advance.

**Comment by magiconair** [comment]
on it

**Comment by magiconair** [comment]
```
 $ GOOS=linux GOARCH=s390x go build
$ file consul
consul: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, not stripped
```

**Comment by kbhute-ibm** [comment]
Thanks @magiconair for quick response.
