### ISSUE TITLE
Change the web UI to pass ACLs via header vs. query parameter

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3247]
Consul can consume a header for the token and this is a safer way to do it.

**Comment by slackpad** [comment]
See https://www.consul.io/api/index.html#authentication.

**Comment by johncowen** [comment]
Hi @slackpad 👋 

Hopefully you've had a chance to try out our new UI! It now uses `X-Consul-Token` header instead of via a query param.

Funnys aside, hope the new gig is going well! Feel free to close this one for me, or I'll close myself over the next few days if not.

Ta

😄

**Comment by slackpad** [comment]
Hey @johncowen indeed - the new UI is looking awesome! I love all the activity going on / user feedback / iteration, too - it's so nice to see the UI alive and well :-D
