### ISSUE TITLE
Expect mode cannot be enabled when dev mode is enabled

### ISSUE THREAD

**Issue by akd31** [hashicorp/consul#3255]
I am trying to run consul on openshift container platform. I am using official consul docker image. I use CONSUL_LOCAL_CONFIG environment variable to get a 3 node consul cluster.

My json file like this : {
"data_dir": "/var/consul",
"log_level": "INFO",
"node_name": "node1",
"server": true,
"ui": true,
"bootstrap_expect": 3
}

I got an error like " Expect mode cannot be enabled when dev mode is enabled". How can I disable dev mode via using CONSUL_LOCAL_CONFIG variable?

**Comment by slackpad** [comment]
Hi @akd31 you only get dev mode if you run the container with no arguments. If you do something like `docker run consul agent` with that config things should work fine, as it'll skip the default entrypoint from https://github.com/hashicorp/docker-consul/blob/master/0.X/Dockerfile#L71-L74. Hope that helps!

**Comment by akd31** [comment]
Thanks for reply. I actually knew what you mention about. However, openshift container platform doesn't let me start container with args. I figured it out though. After starting container I add args to container deployment config and restart container then it works.
