### ISSUE TITLE
localhost.localdomain hostname showing in UI

### ISSUE THREAD

**Issue by alkalinecoffee** [hashicorp/consul#3260]
### `consul version` for both Client and Server
Client: `0.8.5`
Server: `0.8.5`

### `consul info` for both Client and Server
Client:
```
agent:
  check_monitors = 0
  check_ttls = 0
  checks = 2
  services = 2
build:
  prerelease =
  revision = 2c77151
  version = 0.8.5
consul:
  known_servers = 3
  server = false
runtime:
  arch = amd64
  cpu_count = 2
  goroutines = 39
  max_procs = 2
  os = linux
  version = go1.8.3
serf_lan:
  coordinate_resets = 0
  encrypted = true
  event_queue = 0
  event_time = 771
  failed = 0
  health_score = 0
  intent_queue = 0
  left = 5
  member_time = 101
  members = 13
  query_queue = 0
  query_time = 5
```

Server:
```
agent:
  check_monitors = 0
  check_ttls = 0
  checks = 1
  services = 2
build:
  prerelease =
  revision = 2c77151
  version = 0.8.5
consul:
  bootstrap = false
  known_datacenters = 1
  leader = false
  leader_addr = xxx.xxx.xxx.124:8300
  server = true
raft:
  applied_index = 196329
  commit_index = 196329
  fsm_pending = 0
  last_contact = 87.211151ms
  last_log_index = 196329
  last_log_term = 6414
  last_snapshot_index = 188426
  last_snapshot_term = 6414
  latest_configuration = [{Suffrage:Voter ID:20885c43-0bb8-6738-a004-c78a2f6ee717 Address:xxx.xxx.xxx.124:8300} {Suffrage:Voter ID:0e24d000-2b41-7355-a80d-4d133e8f5391 Address:xxx.xxx.xxx.116:8300} {Suffrage:Voter ID:83a8ef18-06c2-4755-84cf-60a5ff1788bd Address:xxx.xxx.xxx.70:8300}]
  latest_configuration_index = 15939
  num_peers = 2
  protocol_version = 3
  protocol_version_max = 3
  protocol_version_min = 0
  snapshot_version_max = 1
  snapshot_version_min = 0
  state = Follower
  term = 6414
runtime:
  arch = amd64
  cpu_count = 2
  goroutines = 130
  max_procs = 2
  os = linux
  version = go1.8.3
serf_lan:
  coordinate_resets = 0
  encrypted = true
  event_queue = 0
  event_time = 771
  failed = 0
  health_score = 0
  intent_queue = 0
  left = 5
  member_time = 101
  members = 13
  query_queue = 0
  query_time = 5
serf_wan:
  coordinate_resets = 0
  encrypted = true
  event_queue = 0
  event_time = 1
  failed = 0
  health_score = 0
  intent_queue = 0
  left = 0
  member_time = 14
  members = 3
  query_queue = 0
  query_time = 1
```

### Operating system and Environment details
Amazon linux in AWS

### Description of the Issue (and unexpected/desired result)
A previous cluster member named `localhost.localdomain` still appears in the UI.  It's been about a week since this node was removed, and does not appear as a member with `consul members`.  No node with this IP exists in our VPC.  Refreshing the member's page in the UI shows changes in the tomography graph with metrics against the other cluster members, so some connection is happening to pull this data.  What might be noteworthy is that the member was named `localhost.localdomain`, which is perhaps due to the consul service starting up before the network was up.  Maybe some sort of loopback confusion is occurring?

### Reproduction steps
Unable to reliably replicate at this time.  

### Log Fragments or Link to [gist](https://gist.github.com/)
Nothing in the logs appear for this node.

### What I'm seeing from the CLI:

The member IP (xxx.xxx.xxx.208) does not appear in the member list:
```
$ consul members
ip-xxx-xxx-xxx-100  xxx.xxx.xxx.100:8301  alive   client  0.8.5  2         aws
ip-xxx-xxx-xxx-105  xxx.xxx.xxx.105:8301  alive   client  0.8.5  2         aws
ip-xxx-xxx-xxx-116  xxx.xxx.xxx.116:8301  alive   server  0.8.5  2         aws
ip-xxx-xxx-xxx-124  xxx.xxx.xxx.124:8301  alive   server  0.8.5  2         aws
ip-xxx-xxx-xxx-153  xxx.xxx.xxx.153:8301  alive   client  0.8.5  2         aws
ip-xxx-xxx-xxx-19   xxx.xxx.xxx.19:8301   alive   client  0.8.5  2         aws
ip-xxx-xxx-xxx-192  xxx.xxx.xxx.192:8301  left    client  0.8.5  2         aws
ip-xxx-xxx-xxx-194  xxx.xxx.xxx.194:8301  left    client  0.8.5  2         aws
ip-xxx-xxx-xxx-247  xxx.xxx.xxx.247:8301  alive   client  0.8.5  2         aws
ip-xxx-xxx-xxx-29   xxx.xxx.xxx.29:8301   left    client  0.8.5  2         aws
ip-xxx-xxx-xxx-38   xxx.xxx.xxx.38:8301   left    client  0.8.5  2         aws
ip-xxx-xxx-xxx-50   xxx.xxx.xxx.50:8301   left    client  0.8.5  2         aws
ip-xxx-xxx-xxx-70   xxx.xxx.xxx.70:8301   alive   server  0.8.5  2         aws
```

### What I'm seeing in the UI:

<img width="531" alt="screen shot 2017-07-11 at 3 26 48 pm" src="https://user-images.githubusercontent.com/1434559/28086546-64cad6bc-664d-11e7-9251-22e608234e43.png">

<img width="780" alt="screen shot 2017-07-11 at 3 19 22 pm" src="https://user-images.githubusercontent.com/1434559/28086363-c09a02de-664c-11e7-802a-58128ba07f4e.png">

<img width="354" alt="screen shot 2017-07-11 at 3 19 33 pm" src="https://user-images.githubusercontent.com/1434559/28086371-c49f03c0-664c-11e7-95e6-c9650307e85d.png">

**Comment by slackpad** [comment]
Hi @alkalinecoffee this is a weird one - if that member doesn't appear in `consul members` then it should get reaped after 72 hours. If you deregister it via https://www.consul.io/api/catalog.html#deregister-entity does it come back again?

**Comment by alkalinecoffee** [comment]
Hi @slackpad, thanks for the response.  I ended up force-leaving the `localhost` node on my own (it never was reaped on its own).  It hasn't been back since.

I've updated our init scripts to ensure networking is fully up before starting the consul service, and so far have not seen this issue come back.  We've also since updated to the latest consul version.

Suggesting we close this issue.

**Comment by slackpad** [comment]
Sounds good - thanks for the follow up!
