### ISSUE TITLE
Script healthcheck using DockerContainerID: Old container id gets stuck in consul configuration

### ISSUE THREAD

**Issue by perjg** [hashicorp/consul#3265]
### `consul version` for both Client and Server

Server:
```
Consul v0.8.5
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

Client: We are using the Consul API via curl.

### `consul info` for both Client and Server

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 6
	services = 7
build:
	prerelease =
	revision = 2c77151
	version = 0.8.5
consul:
	bootstrap = true
	known_datacenters = 1
	leader = false
	leader_addr = 172.18.0.4:8300
	server = true
raft:
	applied_index = 23143
	commit_index = 23143
	fsm_pending = 0
	last_contact = 43.524551ms
	last_log_index = 23143
	last_log_term = 29
	last_snapshot_index = 16384
	last_snapshot_term = 27
	latest_configuration = [{Suffrage:Voter ID:172.18.0.2:8300 Address:172.18.0.2:8300} {Suffrage:Voter ID:172.18.0.3:8300 Address:172.18.0.3:8300} {Suffrage:Voter ID:172.18.0.4:8300 Address:172.18.0.4:8300}]
	latest_configuration_index = 8
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 29
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 74
	max_procs = 2
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 29
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 51
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 63
	members = 3
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Atomic Host, running in docker with consul:latest

### Description of the Issue (and unexpected/desired result)

Unable to register new id for Docker health check.

We are running a service in a docker container that has a health check shell script. the script just prints "OK" on the console and exits.

To register it, we used the following API call:

```
curl -X PUT \
  http://192.168.1.44:8500/v1/agent/service/register \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
  "ID": "test-service",
  "Name": "test-service",
  "Tags": [],
  "Check": {
    "DeregisterCriticalServiceAfter": "90m",
    "Script": "/test-service/healthcheck.sh",
    "DockerContainerID": "e81c2124e25d",
    "Interval": "10s",
    "TTL": "15s"
  }
}
'
```

e81c2124e25d was the programatically extracted ID of the docker container. This worked fine, and console UI showed "OK" in the health check.

When making changes to the service and rebuilding the docker container, the ID changes.

To test with the new id, I called:

```
curl -X PUT http://192.168.1.44:8500/v1/agent/service/deregister/test-service
```

Then I called register again with just the DockerContainerId field changed to f14e4553d8b3.

After that, the Consul UI shows:

No such container: e81c2124e25d

Meaning that it is somehow still trying to use the old ID. 

I tried to call the Docker API directly, with the correct ID:

```
curl -X POST \
  http://192.168.1.44:4243/containers/f14e4553d8b3/exec \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
	"AttachStdin": false,
	"AttachStdout": true,
	"AttachStderr": true,
	"DetachKeys": "ctrl-p,ctrl-q",
	"Tty": false,
	"Cmd": [
		"/test-service/healthcheck.sh"
	]
}'
```

And it works properly. If I call the Docker API with the old ID, It gives "No such container: e81c2124e25d", so it seems like Consul is indeed executing the health check with old data.

**Comment by perjg** [comment]
Inside the consul1 agent where the check is registered, I had a look in the checks directory:

/consul/data/checks # cat 0a23f9d21e4f491c1ff0cf6b3f7d8484
{"Check":{"Node":"consul1","CheckID":"service:test-service","Name":"Service 'test-service' check","Status":"critical","Notes":"Health check","Output":"","ServiceID":"test-service","ServiceName":"test-service","ServiceTags":null,"CreateIndex":0,"ModifyIndex":0},"ChkType":{"CheckID":"","Name":"","Status":"","Notes":"Health check","Script":"/test-service/healthcheck.sh","HTTP":"","Header":null,"Method":"","TCP":"","Interval":30000000000,"DockerContainerID":"f14e4553d8b3","Shell":"/bin/bash","TLSSkipVerify":false,"Timeout":10000000000,"TTL":15000000000,"DeregisterCriticalServiceAfter":300000000000},"Token":"31cc87202ccc42

This seems to indicate that the correct id is indeed registered with Consul, but it still shows the wrong one in the UI, and shows the service as cricital

**Comment by magiconair** [comment]
Do you have multiple instances of the same service? I'm asking since `Name` and `ID` are the same in your service registration.

**Comment by perjg** [comment]
@magiconair No, there is only one instance of that service running.

**Comment by magiconair** [comment]
Thanks. I have a suspicion about the root cause. Working in that area of the code right now. I'll have a look.

**Comment by magiconair** [comment]
Found it.
