### ISSUE TITLE
Consul cluster is not created properly on ECS

### ISSUE THREAD

**Issue by vasgab** [hashicorp/consul#3269]
### `consul version` for both Client and Server
Client: 0.8.5
Server: 0.8.5

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Operating system and Environment details
Amazon Linux AMI 2017.03.b x86_64 ECS HVM

### Description of the Issue (and unexpected/desired result)
I'm trying to create a consul cluster of 3 servers on ECS (EC2 container service) with terraform. Everything is created but seems the consul servers can't join and see each other. 
I can see the 3 EC2 instances running a container each one. This is the cmd and port mapping values passed to the container:
"command": [
        "consul",
        "agent",
        "-server",
        "-data-dir=/tmp",
        "-datacenter=dc0",
        "-bootstrap-expect=3",
        "-ui",
        "-retry-join-ec2-tag-key=aws:autoscaling:groupName",
        "-retry-join-ec2-tag-value=ecs-asg"
      ],
      "portMappings": [
           {
               "containerPort": 8500,
               "hostPort": 8500,
               "protocol": "tcp"
           },
           {
               "containerPort": 8301,
               "hostPort": 8301,
               "protocol": "tcp"
           },
           {
               "containerPort": 8400,
               "hostPort": 8400,
               "protocol": "tcp"
           },
           {
               "containerPort": 8300,
               "hostPort": 8300,
               "protocol": "tcp"
           }
       ]

### Reproduction steps
I'm supposed to go to http://instance-ip:8500/ui and see consul web with all the servers running, but it is showing a blank page with no information. 
Any help is really appreciated.
Thanks.

### Log Fragments or Link to [gist](https://gist.github.com/)
I can ssh to any of the containers and this is what I get running docker logs container-id:

==> Starting Consul agent...
==> WARNING: Expect Mode enabled, expecting 3 servers
==> Consul agent running!
           Version: 'v0.8.5'
           Node ID: '47c2ea06-79c3-c12d-7b2e-541ab2c7485a'
         Node name: '5e29a93c96ae'
        Datacenter: 'dc0'
            Server: true (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 172.17.0.2 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2017/07/12 20:48:12 [INFO] raft: Initial configuration (index=0): []
    2017/07/12 20:48:12 [INFO] raft: Node at 172.17.0.2:8300 [Follower] entering Follower state (Leader: "")
    2017/07/12 20:48:12 [INFO] serf: EventMemberJoin: 5e29a93c96ae 172.17.0.2
    2017/07/12 20:48:12 [INFO] serf: EventMemberJoin: 5e29a93c96ae.dc0 172.17.0.2
    2017/07/12 20:48:12 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
    2017/07/12 20:48:12 [INFO] consul: Adding LAN server 5e29a93c96ae (Addr: tcp/172.17.0.2:8300) (DC: dc0)
    2017/07/12 20:48:12 [INFO] consul: Handled member-join event for server "5e29a93c96ae.dc0" in area "wan"
    2017/07/12 20:48:12 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
    2017/07/12 20:48:12 [INFO] agent: Started HTTP server on 127.0.0.1:8500
    2017/07/12 20:48:12 [INFO] agent: Joining cluster...
    2017/07/12 20:48:12 [INFO] agent: No EC2 region provided, querying instance metadata endpoint...
    2017/07/12 20:48:13 [INFO] agent: Discovered 3 servers from EC2
    2017/07/12 20:48:13 [INFO] agent: (LAN) joining: [172.31.11.180 172.31.3.255 172.31.6.46]
    2017/07/12 20:48:13 [INFO] serf: EventMemberJoin: 9c203ac2d138 172.17.0.2
    2017/07/12 20:48:13 [INFO] consul: Adding LAN server 9c203ac2d138 (Addr: tcp/172.17.0.2:8300) (DC: dc0)
    2017/07/12 20:48:13 [INFO] serf: EventMemberJoin: a7503ddb62e8 172.17.0.2
    2017/07/12 20:48:13 [INFO] agent: (LAN) joined: 3 Err: <nil>
    2017/07/12 20:48:13 [INFO] agent: Join completed. Synced with 3 initial agents
    2017/07/12 20:48:13 [INFO] consul: Adding LAN server a7503ddb62e8 (Addr: tcp/172.17.0.2:8300) (DC: dc0)
    2017/07/12 20:48:13 [INFO] consul: Found expected number of peers, attempting bootstrap: 172.17.0.2:8300,172.17.0.2:8300,172.17.0.2:8300
    2017/07/12 20:48:13 [ERR] consul: Failed to bootstrap cluster: Found duplicate ID in configuration: 172.17.0.2:8300
    2017/07/12 20:48:13 [WARN] memberlist: Got ping for unexpected node '9c203ac2d138' from=172.17.0.2:8301
    2017/07/12 20:48:14 [WARN] memberlist: Got ping for unexpected node 9c203ac2d138 from=172.17.0.2:43288
    2017/07/12 20:48:14 [WARN] memberlist: Got ping for unexpected node '9c203ac2d138' from=172.17.0.2:8301
    2017/07/12 20:48:14 [ERR] memberlist: Failed fallback ping: EOF
    2017/07/12 20:48:14 [INFO] memberlist: Suspect 9c203ac2d138 has failed, no acks received
    2017/07/12 20:48:14 [WARN] memberlist: Got ping for unexpected node 'a7503ddb62e8' from=172.17.0.2:8301
    2017/07/12 20:48:15 [WARN] memberlist: Got ping for unexpected node a7503ddb62e8 from=172.17.0.2:43290
    2017/07/12 20:48:15 [ERR] memberlist: Failed fallback ping: EOF
    2017/07/12 20:48:16 [INFO] memberlist: Suspect a7503ddb62e8 has failed, no acks received
    2017/07/12 20:48:17 [WARN] memberlist: Got ping for unexpected node '9c203ac2d138' from=172.17.0.2:8301
    2017/07/12 20:48:18 [INFO] memberlist: Marking 9c203ac2d138 as failed, suspect timeout reached (0 peer confirmations)
    2017/07/12 20:48:18 [INFO] serf: EventMemberFailed: 9c203ac2d138 172.17.0.2
    2017/07/12 20:48:18 [INFO] consul: Removing LAN server 9c203ac2d138 (Addr: tcp/172.17.0.2:8300) (DC: dc0)
    2017/07/12 20:48:18 [WARN] memberlist: Got ping for unexpected node 9c203ac2d138 from=172.17.0.2:43292
    2017/07/12 20:48:18 [ERR] memberlist: Failed fallback ping: EOF
    2017/07/12 20:48:19 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:48:20 [INFO] memberlist: Suspect 9c203ac2d138 has failed, no acks received
    2017/07/12 20:48:20 [WARN] memberlist: Got ping for unexpected node 'a7503ddb62e8' from=172.17.0.2:8301
    2017/07/12 20:48:21 [WARN] memberlist: Got ping for unexpected node a7503ddb62e8 from=172.17.0.2:43294
    2017/07/12 20:48:21 [ERR] memberlist: Failed fallback ping: EOF
    2017/07/12 20:48:21 [INFO] memberlist: Marking a7503ddb62e8 as failed, suspect timeout reached (0 peer confirmations)
    2017/07/12 20:48:21 [INFO] serf: EventMemberFailed: a7503ddb62e8 172.17.0.2
    2017/07/12 20:48:21 [INFO] consul: Removing LAN server a7503ddb62e8 (Addr: tcp/172.17.0.2:8300) (DC: dc0)
    2017/07/12 20:48:22 [WARN] raft: no known peers, aborting election
    2017/07/12 20:48:24 [INFO] memberlist: Suspect a7503ddb62e8 has failed, no acks received
    2017/07/12 20:48:42 [ERR] agent: coordinate update error: No cluster leader
    2017/07/12 20:48:42 [INFO] serf: attempting reconnect to a7503ddb62e8 172.17.0.2:8301
    2017/07/12 20:48:48 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:49:11 [ERR] agent: coordinate update error: No cluster leader
    2017/07/12 20:49:12 [INFO] serf: attempting reconnect to a7503ddb62e8 172.17.0.2:8301
    2017/07/12 20:49:12 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:49:35 [ERR] agent: coordinate update error: No cluster leader
    2017/07/12 20:49:42 [INFO] serf: attempting reconnect to a7503ddb62e8 172.17.0.2:8301
    2017/07/12 20:49:46 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:50:07 [ERR] agent: coordinate update error: No cluster leader
    2017/07/12 20:50:10 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:50:12 [INFO] serf: attempting reconnect to 9c203ac2d138 172.17.0.2:8301
    2017/07/12 20:50:32 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:50:42 [ERR] agent: coordinate update error: No cluster leader
    2017/07/12 20:50:42 [INFO] serf: attempting reconnect to 9c203ac2d138 172.17.0.2:8301
    2017/07/12 20:51:03 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:51:12 [ERR] agent: coordinate update error: No cluster leader
    2017/07/12 20:51:12 [INFO] serf: attempting reconnect to a7503ddb62e8 172.17.0.2:8301
    2017/07/12 20:51:32 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:51:41 [ERR] agent: coordinate update error: No cluster leader
    2017/07/12 20:51:42 [INFO] serf: attempting reconnect to 9c203ac2d138 172.17.0.2:8301
    2017/07/12 20:52:05 [ERR] agent: failed to sync remote state: No cluster leader
    2017/07/12 20:52:12 [INFO] serf: attempting reconnect to a7503ddb62e8 172.17.0.2:8301
    2017/07/12 20:52:16 [ERR] agent: coordinate update error: No cluster leader
    2017/07/12 20:52:28 [ERR] agent: failed to sync remote state: No cluster leader

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @vasgab I don't have any experience with ECS, but I'd check these two things:

```
Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
Cluster Addr: 172.17.0.2 (LAN: 8301, WAN: 8302)
```

The client address is where the UI would be, and it looks like that's not being set to be visible outside the machine. See https://www.consul.io/docs/agent/options.html#_client.

The cluster address is what the agents use to communicate between each other, I'd make sure that address looks like it's on the right network for your containers. That's configured with https://www.consul.io/docs/agent/options.html#_bind.

Hope that helps!

**Comment by jwarder** [comment]
I get the same issue with 172.17.0.2 as the cluster address This the local IP address of the container, this seems to be a bug using -retry-join "provider=aws tag_key=xxx tag_value=xxx" I'm pretty sure this should return the host IP address using the AWS metadata API? I'm using Consul 1.0.0

**Comment by magiconair** [comment]
@jwarder this is the retry-join code from go-discover. This works as expected for the test cases we have. Should ECS behave differently?

https://github.com/hashicorp/go-discover/blob/master/provider/aws/aws_discover.go
