### ISSUE TITLE
'exec' creates local privilege escalation concern

### ISSUE THREAD

**Issue by alexhudson** [hashicorp/consul#327]
The new exec command is pretty cool, but it should have a couple warning signs against it: particularly for those people who literally download the binary, stick it on their system and run it under root. For those, 'exec' looks an awful lot like an easy way to grab a root shell on all the cluster nodes.

Running consul under a reduced-privilege user helps but isn't perfect. Is the cert requirement for RPC TLS basically the security barrier here? Feels like it should be documented if so.

**Comment by kaelumania** [comment]
@awheeler See my comment in https://github.com/hashicorp/consul/issues/532, there I propose a mechanism that makes `exec` more safe.

**Comment by kaelumania** [comment]
@armon SSH provides a similar solution, for example see http://binblog.info/2008/10/20/openssh-going-flexible-with-forced-commands/

**Comment by slackpad** [comment]
We changed exec to opt-out in Consul 0.8.

**Comment by slackpad** [comment]
ACLs have since been added to control registration, even at the agent level.
