### ISSUE TITLE
Consul 0.0.85's kv http api has different behaviors in dev mode and server mode.

### ISSUE THREAD

**Issue by magicliang** [hashicorp/consul#3279]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Server: `0.0.85`
### Operating system and Environment details

macOS Sierra 10.12.5

### Description of the Issue (and unexpected/desired result)

If you try to put a value via KV api, you see different response text.
In dev mode, you have "true\n", in server mode, you have "true".

### Reproduction steps

1 consul agent -dev
2  curl -i -H "Content-Type: application/json" -X PUT http://localhost:8500/v1/kv/abc -d '{
  "http_if_terminated": true,
  "id": "1c4425ef-63f7-4918-8b2e-438f45b21ab5",
  "retries": 5,
  "preserve_host": false,
  "created_at": 1493967933394,
  "upstream_connect_timeout": 60000,
  "upstream_url": "http://localhost:6789/",
  "upstream_send_timeout": 60000,
  "https_only": false,
  "upstream_read_timeout": 60000,
  "strip_uri": true,
  "name": "service-with-consul",
  "hosts": [
    "localhost"
  ]
}'
3 check the response 
4 consul agent -server -bootstrap-expect 1 -data-dir=/tmp/consul  -node=n1 -bind=172.21.120.122 -client 0.0.0.0 -ui -dc=dc0
5 repeat step 2-3. 
If you use curl api, you will a "true\n" in dev mode response and "true%" in server mode response. But if you use Java http client to try this, you will see "true\n" and "true". I don't know if there are some charset issue with curl, but I am sure dev mode will mislead developer who writes code in dev mode and deploys code in server mode.

Sorry for my poor english.

**Comment by slackpad** [comment]
Hi @magicliang this is a feature :-) Since dev mode is often used interactively we append a newline to help make it easier to see the output of tools like `curl`. Since most folks writing code are parsing the JSON this hasn't caused issues. You are right in this kv API but we won't be making more that return raw booleans vs JSON so this should be less of an issue going forward.

**Comment by magicliang** [comment]
I tried some JSON validater that "true\n" is not a valid json value. Even it is in some case, I think this behavior difference should be documented.

**Comment by lord2800** [comment]
JavaScript disagrees with your JSON validator:
```
> JSON.parse("true\n")
true
```

**Comment by magicliang** [comment]
thanks for the classification.
