### ISSUE TITLE
Max connected agents

### ISSUE THREAD

**Issue by xinuc** [hashicorp/consul#3300]
Hi,

just asking, is there any practical or theoretical limit of connected consul agents?

In our use case, we have an agent for every pod created in kubernetes custer,
so potentially we will have thousands of agents connected into the consul cluster.

Thanks.

**Comment by slackpad** [comment]
Hi @xinuc there's no hard upper limit. As long as your servers can handle the read/write loads you should be fine with thousands of agents. We have folks in the 10's of thousands of agents territory in a single datacenter. Hope that helps!

**Comment by xinuc** [comment]
Thanks for the answer.

Appreciate it.
