### ISSUE TITLE
Feature request: HTTP Endpoint for WatchHandler

### ISSUE THREAD

**Issue by HadarGreinsmark** [hashicorp/consul#3305]
Currently when a new watch is triggered, you can specify a handler that [execute an executable](https://github.com/hashicorp/consul/blob/master/agent/watch_handler.go)
 when changes are made. The executable get the trigger message through a JSON object on stdin. It would be nice to have an additional handler that specify an HTTP endpoint, similar to health checks.

As for an example configuration like this:
```
{
  "type": "key",
  "key": "foo/bar/baz",
  "http": "https://localhost:5000/watch",
}
```
the WatchHandler would send this when triggered:
```
POST /watch HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Content-Length: 140
X-Consul-Index: 123

{
  "Key": "foo/bar/baz",
  "CreateIndex": 1793,
  "ModifyIndex": 1793,
  "LockIndex": 0,
  "Flags": 0,
  "Value": "aGV5",
  "Session": ""
}
```

The connection could `keep-alive` for a long time, if the server is agreeing on it.

Inspiration: https://developers.google.com/drive/v3/web/push
I would be willing to implement this.

**Comment by HadarGreinsmark** [comment]
@slackpad

**Comment by preetapan** [comment]
@HadarGreinsmark we talked about this internally, and this is a good addition to consul. Thanks for volunteering to implement this. 

One suggestion as you start work on this - We would like the endpoint's behavior be configurable. For example don't support just POST but allow the http method to be configurable. Take a look at  https://www.consul.io/docs/agent/options.html#http_config with its sub keys for a canonical example on how to set up configuration. For this feature, we could make the url, method, headers, and keep-alive time configurable to start, and that gives us a starting point to add more options if use cases demand it in the future.

**Comment by HadarGreinsmark** [comment]
Good to hear that! I'll start to implement this in the end of next week.

**Comment by p1nkrock** [comment]
@HadarGreinsmark Is the implementation done for HTTP Watch Endpoint?

**Comment by HadarGreinsmark** [comment]
Yes @p1nkrock , it is sort of done as I see it. The pull request just has to be reviewed and merged.
