### ISSUE TITLE
mDNS support

### ISSUE THREAD

**Issue by kung-foo** [hashicorp/consul#331]
Is there any plan to expose the mDNS support from serf in consul?

**Comment by depeele** [comment]
+1, mDNS for "hands-free" bootstrapping would be awesome!

**Comment by cruatta** [comment]
+1 for mDNS bootstrapping!

**Comment by mmathes** [comment]
+1 mDNS bootstrapping would be great

**Comment by r4fek** [comment]
+1

**Comment by geovanisouza92** [comment]
+1

I though in build a little raspberry pi cluster, and consul w/ mdns could be awesome to manage it.

**Comment by F21** [comment]
Any update on this one? Using atlas for consul discovery is pretty nice, but it would be even more awesome if agents can easily discover servers using mdns so that we don't need to rely on an external service.

**Comment by ryedin** [comment]
This would be great, guys.

**Comment by ryanuber** [comment]
There hasn't been any work done in this space in Consul, but there is a pull request open in Serf for taking an alternate SRV record approach (hashicorp/serf#310), which would make this feature more generally applicable. At this point, still no plans, but we have a few things brewing.

**Comment by fpletz** [comment]
+1

**Comment by fadenb** [comment]
So what's the plan for this issue? Will it be implemented? If yes, any timetable available?

**Comment by gaieges** [comment]
+1 .. use case is also within docker containers in a subnet

**Comment by ben-bensdevzone** [comment]
+1 Hi guys! This feature would certainly be of great interest and very much appreciated.

**Comment by levilovelock** [comment]
+1!

**Comment by F0rth** [comment]
+1

**Comment by mier85** [comment]
+1

**Comment by NightBlues** [comment]
+1

**Comment by losmat** [comment]
+1

**Comment by icochico** [comment]
+1

**Comment by sethvargo** [comment]
Hi all,

This never made it on the roadmap, and it's not a very high priority for us. We would gladly review a PR for this functionality, but we are going to close this issue since it's not something we are going to implement ourselves.
