### ISSUE TITLE
ACL's Not Respecting acl_agent_token

### ISSUE THREAD

**Issue by nocode99** [hashicorp/consul#3314]
### Issue
Could be my lack of understanding ACL's, but it seems my configuration is not respecting the `acl_agent_token` on the client side.  Since we use consul as our Vault backend, I'm trying to configure consul ACL so that end users can't delete any vault data/configurations as well as services.  **Edit*: Seems this is applying to everything from the client side.  I noticed my checks were not showing in the UI until I edited `Node` to "write" permissions on the anonymous token.

### `consul version` for both Client and Server
Client: `0.9.0`
Server: `0.9.0`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 3
        check_ttls = 0
        checks = 5
        services = 1
build:
        prerelease = 
        revision = b79d951
        version = 0.9.0
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 65
        max_procs = 2
        os = linux
        version = go1.8.3
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 101
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 91498
        members = 12
        query_queue = 0
        query_time = 16
```

Server:
```
agent:
        check_monitors = 3
        check_ttls = 0
        checks = 4
        services = 0
build:
        prerelease =
        revision = b79d951
        version = 0.9.0
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 13.13.13.13:8300
        server = true
raft:
        applied_index = 90708914
        commit_index = 90708914
        fsm_pending = 0
        last_contact = 15.972509ms
        last_log_index = 90708914
        last_log_term = 264
        last_snapshot_index = 90707266
        last_snapshot_term = 264
        latest_configuration = [{Suffrage:Voter ID:12.12.12.12:8300 Address:12.12.12.12:8300} {Suffrage:Voter ID:13.13.13.13:8300 Address:13.13.13.13:8300} {Suffrage:Voter ID:14.14.14.14:8300 Address:14.14.14.14:8300}]
        latest_configuration_index = 59977729
        num_peers = 2
        protocol_version = 2
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 264
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 138
        max_procs = 2
        os = linux
        version = go1.8.3
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 101
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 91498
        members = 12
        query_queue = 0
        query_time = 16
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details
Ubuntu 16.04

### Description of the Issue (and unexpected/desired result)
I have clients configuring a service and they cannot register even though the `acl_agent_token` is given `write` permissions to `Service`.  It seems the `acl_agent_token` is not being respected in my config and was instead using the Anonymous access instead.  Here is an example:

**Anonymous Token**
```
{
  "agent": {
    "": {
      "policy": "read"
    }
  },
  "key": {
    "": {
      "policy": "read"
    }
  },
  "node": {
    "": {
      "policy": "read"
    }
  },
  "service": {
    "": {
      "policy": "read"
    }
  }
}
```

**Agent Token**
```
{
  "agent": {
    "": {
      "policy": "write"
    }
  },
  "key": {
    "": {
      "policy": "write"
    }
  },
  "node": {
    "": {
      "policy": "write"
    }
  },
  "service": {
    "": {
      "policy": "write"
    }
  },
  "session": {
    "": {
      "policy": "write"
    }
  }
}
```

### Reproduction steps
For troubleshooting, I added a bunch of other configs in the ACL that probably were not needed.  With the configuration above, I would see [RPC errors](https://gist.github.com/nocode99/ecc6bb314051d30831bd1a6994b1b40b#file-debug-log)

While it says `Service 'app' in sync`, there would be no service registered for my app available.  If I change `Service: "write"` in the Anonymous Token policy, these errors go away.  The consul server's don't have problems registering themselves as a service.

### Client Config
```
$ cat acl.json
{
    "acl_agent_token": "{{ acl_agent_token }}",
    "acl_datacenter": "dc1",
    "acl_down_policy": "extend-cache"
}
$ cat config.json 
{
    "advertise_addr": "x.x.x.x",
    "client_addr": "0.0.0.0",
    "datacenter": "dc1",
    "data_dir": "/opt/consul",
    "log_level": "INFO",
    "node_name": "app",
    "server": false,
    "enable_script_checks": true
}
```

### Server config
$ cat acl.json
{
    "acl_master_token": "root",
    "acl_default_policy": "allow",
    "acl_agent_token": "{{ acl_agent_token }}",
    "acl_datacenter": "dc1",
    "acl_down_policy": "extend-cache"
}
$ cat config.json
{
    "advertise_addr": "x.x.x.x",
    "bootstrap_expect": 3,
    "ui": true,
    "client_addr": "0.0.0.0",
    "datacenter": "dc1",
    "data_dir": "/opt/consul",
    "log_level": "INFO",
    "node_name": "consul-server",
    "server": true,
    "enable_script_checks": true
}
```

### Log Fragments or Link to [gist](https://gist.github.com/nocode99/ecc6bb314051d30831bd1a6994b1b40b)

**Comment by slackpad** [comment]
Hi @nocode99 the `acl_agent_token` is only used internally by the agent, not to cover any actions done by the user on that agent. Please take a look at https://www.consul.io/docs/guides/acl.html#acl-agent-token which explains this a little more.

If you want to allow for a limited set of actions for users of an agent without them needing a token, you can set the `acl_token` on that agent, which is passed along as the default. This is explained a bit in https://www.consul.io/docs/guides/acl.html#set-agent-specific-default-tokens-optional-.

The agent policy you posted above isn't restrictive at all, though, so I might need some more information on your use case to make sure I understand exactly what you are trying to do.

**Comment by nocode99** [comment]
Hi @slackpad so if a client has service and health checks configured with the agent, they are technically run as a user?

**Comment by slackpad** [comment]
They can supply a token when they register, and that will be used, if they don't supply a token it will use the `acl_token` if that's there, then the `anonymous` token, and finally the default policy will apply (usually deny). You can think of the `acl_token` on an agent like a special `anonymous` policy for that particular agent, since it gets passed along as the token if the user doesn't supply one.
