### ISSUE TITLE
data/raft/raft.db contains plain text passwords

### ISSUE THREAD

**Issue by igortroy** [hashicorp/consul#3315]
### consul version
Server: 0.7.2

### Operating system
RHEL 7

### Description of the Issue

a previous commit to Consul accidentally inserted a sensitive parameter with a plain-text value.
the parameter itself has since been deleted and inserted again - this time with a different key and an encrypted value.
the original key was then verified no longer existing, in Consul.

however, on the Server /data/raft/raft.db still contains the old value, in plain sight.

is there a way to remove this entry from raft.db, or reset this part/clear the commit log?
preferably without rebooting or reinstalling the server since this is a live environment.

**Comment by slackpad** [comment]
Hi @igortroy if you run a https://www.consul.io/docs/commands/snapshot.html then Consul will trim the Raft log, but it will retain some log entries from before the snapshot to make it easier to bring up servers that have some of the log without having to send a full snapshot. If you do enough writes then eventually your bad entry will be pushed out of that window and you should be good (then you could run a couple snapshots manually to clear any of those that have the password).

Unfortunately, there's no direct way to do this, so you'd need to write a little script to write for a few 10s of thousands of times to do this - you could write to the same KV entry over and over. If you roll all your servers for fresh ones (or take each server down, move its data-dir away, and then bring ip back up) they will be populated with snapshots as well, and shouldn't have the bad raft log entry, but that's pretty cumbersome to do. Hope that helps!
