### ISSUE TITLE
[questions] Consul ACL Token Rotation

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/consul#3319]
Do we have any best practices on how to rotate the ACL token for consul? The reason being the containers that are scheduled by nomad and register from within the container requires this token to be updated and do we have any recommendations to handle this?

**Comment by slackpad** [comment]
Hi @vrenjith we just added a new API that will go out in Consul 0.9.1 that'll allow you to update the ACL tokens programmatically - https://www.consul.io/api/agent.html#update-acl-tokens. You can call this on the fly to rotate tokens!
