### ISSUE TITLE
consul client address configs are not parseable via go-socketaddr

### ISSUE THREAD

**Issue by preetapan** [hashicorp/consul#3322]
```
$docker run --name=dev-consul consul agent -dev -client='{{ GetInterfaceIP "eth0" }}'
==> Starting Consul agent...
==> Error creating agent: Invalid DNS bind address: Failed to parse IP: {{ GetInterfaceIP "eth0" }}
``` 
looks like we don't use the `go-socketaddr` library to [parse this arg](https://github.com/hashicorp/consul/blob/19eae3d14b57f75dddf2177c457d7e33d9d4aa10/agent/config.go#L1016-L1016). We do for [bind addr](https://github.com/hashicorp/consul/blob/master/agent/agent.go#L228-L266). This should be consistent for both.

**Comment by gwydirsam** [comment]
We ran into something similar -- 

```
==> WARNING: Expect Mode enabled, expecting 3 servers
==> Starting Consul agent...
==> Error creating agent: Invalid DNS bind address: Failed to parse IP: {{GetPrivateIP}}
```

The error checking [here](https://github.com/hashicorp/consul/blob/master/agent/agent.go#L198) is being run before the templates are resolved [here](https://github.com/hashicorp/consul/blob/master/agent/agent.go#L231)
