### ISSUE TITLE
Issue with 'enable_script_checks' with Consul v0.9.0 - Terraform Consul Module

### ISSUE THREAD

**Issue by FraserPol** [hashicorp/consul#3323]
### `consul version` for both Client and Server

`$ consul --version
Consul v0.9.0`

### `consul info` for both Client and Server
Client:

```
$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = b79d951
	version = 0.9.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	server = true
raft:
	applied_index = 45
	commit_index = 45
	fsm_pending = 0
	last_contact = 0
	last_log_index = 45
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 91
	max_procs = 1
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3
	members = 3
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

### Description of the Issue (and unexpected/desired result)

Using [this](https://www.terraform.io/intro/getting-started/modules.html) cluster example with [these](https://www.consul.io/intro/getting-started/checks.html) checks I am getting the following output;

2017/07/26 01:28:11 [INFO] Caught signal:  hangup
2017/07/26 01:28:11 [INFO] Reloading configuration...
2017/07/26 01:28:11 [ERR] Reload config failed:  1 error(s) occurred:

Remote side ended the monitor! This usually means that the
remote side has exited or crashed.

### Reproduction steps

```terraform get 

terraform apply

ssh into consul-0

vim /etc/consul.d/config.json

{
"log_level" : "trace",
"enable_script_checks" : true
}

consul validate /etc/consul.d/config.json
Configuration is valid!

consul reload

2017/07/26 01:27:08 [INFO] Caught signal:  hangup
2017/07/26 01:27:08 [INFO] Reloading configuration...

Confirm cluster is still up and responding by running consul members and consul monitor

echo '{"check": {"name": "ping",
  "script": "ping -c1 google.com >/dev/null", "interval": "30s"}}' \
  >/etc/consul.d/ping.json

consul reload

Error reloading: Unexpected response code: 500 (1 error(s) occurred:

* Failed to reload configs: Failed reloading checks: Failed to register check 'ping': Check types that exec scripts are disabled on this agent &{ ping     ping -c1 google.com >/dev/null  map[]   30s   false 0s 0s 0s})
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Logs are no longer than 2 lines included above.

**Comment by slackpad** [comment]
Hi @FraserPol the `enable_script_checks` configuration option isn't currently reloadable by `consul reload` (you can see a list of what is available at https://www.consul.io/docs/agent/options.html#reloadable-configuration). For that setting to take effect you'll need to restart the consul agent, or have that config file present before the agent starts. Hope that helps!

**Comment by FraserPol** [comment]
@slackpad got it working, thanks!
