### ISSUE TITLE
error restoring snapshot

### ISSUE THREAD

**Issue by pvmarius** [hashicorp/consul#3326]
Hi 
We are running into an error trying to restore a snapshot:

```
time consul snapshot restore test.snap
Error restoring snapshot: Unexpected response code: 500 (Raft error when restoring snapshot: timed out enqueuing operation)

real	3m14.793s
user	0m0.704s
sys	0m4.228s
```

and then a different error

```
time consul snapshot restore test.snap
Error restoring snapshot: Put http://127.0.0.1:8500/v1/snapshot: EOF

real	5m36.831s
user	0m0.180s
sys	0m4.668s
```

Config:
 - consul 0.9.0
 - single node cluster 
 - instance AWS m4.large and m4.xlarge (initially)
 - snapshot size ~ 3.8GB on disk / compressed
 - OS Amazon Linux AMI 2017.03

Workaround:

 - used AWS i3.large instance
 - mounted /tmp and /var/lib/consul on the nvme disk
   ```
   /dev/nvme0n1p1 on /tmp type ext4 (rw,relatime,data=ordered)
   /dev/nvme0n1p2 on /var/lib/consul type ext4 (rw,relatime,data=ordered)
   ```
 - run the restore again
   ```
   time consul snapshot restore test.snap
   Restored snapshot

   real	1m37.715s
   user	0m0.440s
   sys	0m3.980s
   ```
Issue seems to be the fixed timeout here: 
- https://github.com/hashicorp/consul/blob/master/snapshot/snapshot.go#L187-L191

Is it possible to make this timeout configurable ?

Thanks

**Comment by slackpad** [comment]
Seems like we should be able to plumb that down.
