### ISSUE TITLE
list of all consul metrics

### ISSUE THREAD

**Issue by toothlessfairy** [hashicorp/consul#3331]
Is there somewhere a list of all metrics that Consul can send to statsd? Is there a way to add some metrics? I need to monitor info about cpu/memory/disk usage on each node.

**Comment by slackpad** [comment]
Hi @toothlessfairy currently we've documented key metrics here https://www.consul.io/docs/agent/telemetry.html but Consul does emit others that we are in the process of cleaning up and documenting as well. These are all metrics about Consul itself, though, so for things like cpu/memory/disk usage you'd probably need to look for a different process you can run and gather those - Consul doesn't have a way to pull in additional metrics.

**Comment by ChipV223** [comment]
@toothlessfairy : Closing this as we've recently updated the [telemetry section](https://www.consul.io/docs/agent/telemetry.html) to include all metrics that Consul can send to statsd.
