### ISSUE TITLE
Cannot HTTP GET recursive decoded data

### ISSUE THREAD

**Issue by sronsiek** [hashicorp/consul#3334]
Consul 0.9.0 running in official docker container image:

Create  some data:
```
consul kv put foo/bar '{"nice":"json"}'
consul kv put foo/bar2 '{"more":"json"}'
consul kv put foo/bar3 '{"last":"json"}'
```

Retrieve all data below the 'foo' key using the cli client:
```
consul kv get -recurse foo
foo/bar:{"nice":"json"}
foo/bar2:{"more":"json"}
foo/bar3:{"last":"json"}
```

Nice!  Now using the http interface:
```
curl -XGET 'http://myHost:8500/v1/kv/foo/bar
[{"LockIndex":0,"Key":"foo/bar","Flags":0,"Value":"eyJuaWNlIjoianNvbiJ9","CreateIndex":3534,"ModifyIndex":3534}]
```

Add the 'raw' flag to get the decoded value:
```
 curl -XGET 'http://myHost:8500/v1/kv/foo/bar?raw=1'
{"nice":"json"}
```

Do the recursive request:
```
curl -XGET 'http://myHost:8500/v1/kv/foo?recurse=1'
[{"LockIndex":0,"Key":"foo/bar","Flags":0,"Value":"eyJuaWNlIjoianNvbiJ9","CreateIndex":3534,"ModifyIndex":3534},{"LockIndex":0,"Key":"foo/bar2","Flags":0,"Value":"eyJtb3JlIjoianNvbiJ9","CreateIndex":3537,"ModifyIndex":3537},{"LockIndex":0,"Key":"foo/bar3","Flags":0,"Value":"eyJsYXN0IjoianNvbiJ9","CreateIndex":3538,"ModifyIndex":3538}]
```

Get the decoded data by adding the 'raw' parameter as before:
```
curl -XGET 'http://myHost:8500/v1/kv/foo?recurse=1&raw=1'
[{"LockIndex":0,"Key":"foo/bar","Flags":0,"Value":"eyJuaWNlIjoianNvbiJ9","CreateIndex":3534,"ModifyIndex":3534},{"LockIndex":0,"Key":"foo/bar2","Flags":0,"Value":"eyJtb3JlIjoianNvbiJ9","CreateIndex":3537,"ModifyIndex":3537},{"LockIndex":0,"Key":"foo/bar3","Flags":0,"Value":"eyJsYXN0IjoianNvbiJ9","CreateIndex":3538,"ModifyIndex":3538}]
```

This does not work as expected. Trying the separator + recursive options also has no effect, so perhaps only the first parameter is processed?

I would have thought recursive retrieval of values is a common use-case!

**Comment by magiconair** [comment]
Try `curl -XGET 'http://myHost:8500/v1/kv/foo?recurse` without the `=1`. `recurse` is a boolean flag. It's existence is enough although we could make this more resilient. If you run `consul agent -dev` or `consul monitor --log-level=DEBUG` you can see the actual requests being made. However, `raw` and `recurse` together don't work like `consul kv get -recursive`. I need to dig a bit for this.

**Comment by slackpad** [comment]
Hi @sronsiek currently the `raw` implementation only dumps the first key. For multiple keys it's not clear how they would be separated in the response so it's not really supported and left to outside tools to do that.

**Comment by roblapp** [comment]
So there is no way to recursively get the raw values in one HTTP request?

**Comment by 4n70w4** [comment]
the same issue

**Comment by yan9yan9** [comment]
the same issue
