### ISSUE TITLE
KV deleted by unknown reason?

### ISSUE THREAD

**Issue by gunli** [hashicorp/consul#3335]
Hi all,
I create 2 kv records as below
```
./consul kv put -http-addr=10.239.160.181:8500 service/tglog/cfg/1000 '{"mgrport":9000,"hbinterval":10000,"svcinterval":60000,"ossinterval":60000,"qosinterval":60000,"kcpcfg":{}}'

./consul kv put -http-addr=10.239.160.181:8500 service/tglog/cfg '{"mgrport":9000,"hbinterval":10000,"svcinterval":60000,"ossinterval":60000,"qosinterval":60000,"kcpcfg":{}}'
```

and then I write a program read them every 1 minute (`curl http://10.239.160.181:8500/v1/kv/service/tglog/cfg?recurse` ), it works well (I mean it returns me 2 records) at the beginning, but about 30 minute later,  I found key `service/tglog/cfg` was deleted by unknown reason.

```
[user00@/data/home/user00/tglogservice/trunk/example]$curl http://10.239.160.181:8500/v1/kv/service/tglog/cfg?recurse     
[{"LockIndex":0,"Key":"service/tglog/cfg","Flags":0,"Value":null,"CreateIndex":891529,"ModifyIndex":913912}]

[{"LockIndex":0,"Key":"service/tglog/cfg","Flags":0,"Value":null,"CreateIndex":891529,"ModifyIndex":913912},{"LockIndex":0,"Key":"service/tglog/cfg/1000","Flags":0,"Value":"eyJtZ3Jwb3J0Ijo5MDAwLCJoYmludGVydmFsIjoxMDAwMCwic3ZjaW50ZXJ2YWwiOjYwMDAwLCJvc3NpbnRlcnZhbCI6NjAwMDAsInFvc2ludGVydmFsIjo2MDAwMCwia2NwY2ZnIjp7fX0=","CreateIndex":912701,"ModifyIndex":914348},{"LockIndex":0,"Key":"service/tglog/cfg/1001","Flags":0,"Value":"eyJtZ3Jwb3J0Ijo4MDAwLCJoYmludGVydmFsIjoxMCwib3NzaW50ZXJ2YWwiOjYwLCJxb3NpbnRlcnZhbCI6NjAsImtjcGNmZyI6e319","CreateIndex":871510,"ModifyIndex":891512}]
```

My question is that how can I find out what's wrong with that deleted key, is there some log record the operations relative with it ?

The version of my consul is consul_0.8.5_linux_amd64.zip.

Thanks.

**Comment by magiconair** [comment]
You can run `consul monitor --log-level=DEBUG` to record activity. Are you sure that you're the only client that is talking to the server?

**Comment by gunli** [comment]
@magiconair Thank you, I will turn the log level to DEBUG and try again.

**Comment by gunli** [comment]
I'm sorry, It's my fault, I used libcurl in a wrong way.

In my code, I reuse all my easy curl handles in the run time, but I forget to call (curl_easy_setopt(m_curl, CURLOPT_CUSTOMREQUEST, NULL);) to restore the HTTP method, I make a PUT request (by call curl_easy_setopt(m_curl, CURLOPT_CUSTOMREQUEST, "PUT"); ) to upate a KV record, it works well, and then I make a GET request to get the KV with the same curl handle, because of forgetting restore the HTTP method, it actually send a PUT request to the server, which made the KV be set to an empty object.
