### ISSUE TITLE
dns issue with Consul

### ISSUE THREAD

**Issue by ansham22** [hashicorp/consul#3336]
Hi Channel,

I am trying to debug an issue with dns as I have bind servers installed which are forwarding the query to consul agent locally and agent talks to five node consul cluster. First I need to understand, how does an agent dns query consul server as to which server is bound to answer is the leader?

Now sometimes in my dns server I get servfail for consul domain due to which my applications get in hung state as they wait for domain to be resolved and they don't get any answer for dns queries. I need to get dns logging on consul. How do i get this on. How can I debug this error where consul dns is causing issues. Please help

**Comment by cw-pratik** [comment]
You car try starting the monitor with a debug level. You can do this by running this command

`consul monitor --log-level=debug`

**Comment by slackpad** [comment]
Hi @ansham22 debug logging as pointed out by @cw-pratik is the way to go. Please let us know if you still need help.
