### ISSUE TITLE
Cannot connect to Consul (Hashicorp) which is running in VM ware

### ISSUE THREAD

**Issue by utk31** [hashicorp/consul#3338]
I am having a windows 10 system with Ubuntu running in the VMWare Player. Now I have started the consul agent using consul agent -dev command on the Ubuntu VM but I'm unable to ping the port 8500 (consul port on VM) from my windows machine.

PS I am able to ping jenkins which is installed on the same VM machine easily.

Is there something specific if we need to do to connect to the Consul running on the VM system. I have added the port 8500 to the firewall exceptions port but still unable to connect. Do I have to put other ports also?

**Comment by slackpad** [comment]
Hi @utk31 you probably need to set the client to bind to an IP that's reachable outside the VM (or 0.0.0.0 which isn't a good production config but ok for just trying things out) - https://www.consul.io/docs/agent/options.html#_client. Hope that helps!
