### ISSUE TITLE
cant not access web ui using curl

### ISSUE THREAD

**Issue by zzsoszz** [hashicorp/consul#3344]
### `consul version` for both Client and Server
Client: `0.9.0`
Server: `0.9.0`

### `consul info` for both Client and Server
Client:
```
 ./consul agent -ui  -data-dir data -bind=192.168.33.33 -node=client
```

Server:
```
 ./consul agent -ui  -server  -bootstrap-expect=1   -data-dir data  -bind=192.168.33.11 -node=server01
```

### Operating system and Environment details
centos 7 
### Description of the Issue 
cant not access web ui using curl(or browser)  on server01
[root@ninghao-dev ~]# curl http://127.0.0.1:8500/ui
<a href="/ui/">Moved Permanently</a>.

**Comment by slackpad** [comment]
Hi @zzsoszz if you add the `-L` option to `curl` it will follow that redirect and should work fine. Hope that helps!
