### ISSUE TITLE
Script check causes service flapping

### ISSUE THREAD

**Issue by fatmcgav** [hashicorp/consul#3366]
I've encountered a strange error with Consul script checks, whereby it causes the service to start flapping. 

I've got a Consul agent running on our MQ servers, and was attempting to add RabbitMQ health checking using an existing Sensu monitoring script. 

However the service now alternates between healthy and critical. 
E.g:
>2017/08/07 11:38:05 [DEBUG] agent: Service 'mq' in sync
2017/08/07 11:38:05 [DEBUG] agent: Check 'service:mq:1' in sync
2017/08/07 11:38:05 [DEBUG] agent: Check 'service:mq:2' in sync
2017/08/07 11:38:07 [DEBUG] agent: check 'service:mq:1' script '/opt/sensu/embedded/bin/check-rabbitmq-alive.rb ' output: CheckRabbitMQAlive OK: RabbitMQserver is alive
2017/08/07 11:38:07 [DEBUG] agent: Check 'service:mq:1' is passing
2017/08/07 11:38:07 [DEBUG] agent: check 'service:mq:2' script '/opt/sensu/embedded/bin/check-rabbitmq-node-health.rb ' output: CheckRabbitMQNodeHealth OK: Server is healthy
2017/08/07 11:38:07 [DEBUG] agent: Check 'service:mq:2' is passing
2017/08/07 11:38:43 [DEBUG] memberlist: Initiating push/pull sync with: 10.107.50.66:8301
2017/08/07 11:39:07 [DEBUG] agent: check 'service:mq:1' script '/opt/sensu/embedded/bin/check-rabbitmq-alive.rb ' output:
2017/08/07 11:39:07 [WARN] agent: Check 'service:mq:1' is now critical
2017/08/07 11:39:07 [DEBUG] agent: Service 'mq' in sync
2017/08/07 11:39:07 [INFO] agent: Synced check 'service:mq:1'
2017/08/07 11:39:07 [DEBUG] agent: Check 'service:mq:2' in sync
2017/08/07 11:39:07 [DEBUG] agent: check 'service:mq:2' script '/opt/sensu/embedded/bin/check-rabbitmq-node-health.rb ' output:
2017/08/07 11:39:07 [WARN] agent: Check 'service:mq:2' is now critical
2017/08/07 11:39:07 [DEBUG] agent: Service 'mq' in sync
2017/08/07 11:39:07 [DEBUG] agent: Check 'service:mq:1' in sync
2017/08/07 11:39:07 [INFO] agent: Synced check 'service:mq:2'

My service config looks like:
```
{
    "service": {
        "checks": [
            {
                "interval": "30s",
                "name": "RabbitMQ Alive",
                "script": "/opt/sensu/embedded/bin/check-rabbitmq-alive.rb "
            },
            {
                "interval": "30s",
                "name": "RabbitMQ Node Health",
                "script": "/opt/sensu/embedded/bin/check-rabbitmq-node-health.rb "
            }
        ],
        "enableTagOverride": false,
        "id": "mq",
        "name": "mq",
        "port": 5672,
        "tags": [
            "amqp",
            "rabbitmq"
        ]
    }
}
```

Running the same checks manually, I am never able to reproduce a failure to return an output :( 

I've even gone as far as strace'ing the running Consul process, and the only difference I can see between a 'successful' check and a 'failed' check is that the failed check seems to stop after loading `"/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb"`.
Strace files can be provided if they would be useful. 

### `consul version` for both Client and Server
Client: `v0.6.4`
Server: `v0.6.4`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 2
        check_ttls = 0
        checks = 2
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 38
        max_procs = 1
        os = linux
        version = go1.6
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 468
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 7728
        members = 101
        query_queue = 0
        query_time = 1

```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 26a0ef8c
        version = 0.6.4
consul:
        bootstrap = false
        known_datacenters = 5
        leader = false
        server = true
raft:
        applied_index = 6434296
        commit_index = 6434296
        fsm_pending = 0
        last_contact = 67.578209ms
        last_log_index = 6434296
        last_log_term = 41555
        last_snapshot_index = 6431556
        last_snapshot_term = 41555
        num_peers = 2
        state = Follower
        term = 41555
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 314
        max_procs = 1
        os = linux
        version = go1.6
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 468
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 7728
        members = 101
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 815
        members = 15
        query_queue = 0
        query_time = 1

```

### Operating system and Environment details
CentOS 7, 3 node Consul cluster

**Comment by slackpad** [comment]
Hi @fatmcgav not sure how much we can do with this one as it seems like it might be something with that check script. Is there any additional logging you can enable there?

**Comment by fatmcgav** [comment]
@slackpad

There's no additional logging in the script.

However the script itself is working perfectly happily with our sensu monitoring.

Also, we applied the same health check to a different consul cluster and different set of RabbitMQ nodes, and didn't see this flapping behaviour...

So not sure what's going on there tbh...

**Comment by slackpad** [comment]
We've done some cleanup work to make sure you can't end up with multiple instances of the same check running at the same time, and it's now possible to run w/o a shell, but those don't seem related. I'm going to close this out as likely something with the script itself, as we haven't seen similar reports and that seems like the most likely thing here. If there's some way we can help please let us know.
