### ISSUE TITLE
Consul watches don't work when consul is run as a system user with no login

### ISSUE THREAD

**Issue by knizami** [hashicorp/consul#3368]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `0.8.5`
Server: `0.8.5`
Centos 7.3

### Description of the Issue (and unexpected/desired result)
When running consul as consul:consul where user has no home directory and is created as a system user, the watches don't run and exit with status 1.  When the same watches are run as user root they run fine.  I haven't been able to isolate the cause of this issue but it appears to be related to the need for the user to have login enabled?  What is the guidance on running consul as a non root user?  Does the user need a home directory / login with a shell defined?  Are there any other requirements?

### Reproduction steps
configure watch to run simple test script that just reads stdin and echos it back out as user consul:consul:
consul:x:996:992:consul.io user:/var/lib/consul:/sbin/nologin
script fails to run, exit 1
run same script as user root
script runs successfully

**Comment by slackpad** [comment]
Hi @knizami currently you need a user with a shell in order to run watches. Cleaning this up is being tracked under https://github.com/hashicorp/consul/issues/2999.
