### ISSUE TITLE
Can't get access to UI on external IP

### ISSUE THREAD

**Issue by winmasta** [hashicorp/consul#3371]
### `consul version` for both Client and Server
Client: `0.9.0`
Server: `0.9.0`

### `consul info` for both Client and Server
Client:
```
not affected clients
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = b79d951
	version = 0.9.0
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 165.227.84.225:8300
	server = true
raft:
	applied_index = 28
	commit_index = 28
	fsm_pending = 0
	last_contact = 0
	last_log_index = 28
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:165.227.84.225:8300 Address:165.227.84.225:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 80
	max_procs = 2
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
ubuntu 16.04.3
### Description of the Issue (and unexpected/desired result)
trying to open webui from external addres but cant when binding ui to external ip
also have tried ui on localhost and 8500 port mapping with iptables to localhost
### Reproduction steps
docker run -d --net=host --name=consul -p 8500:8500 -v /etc/consul.d:/consul/config -v /etc/consul.d/ssl:/etc/consul.d/ssl consul agent -ui -bind=165.227.84.225 -client=165.227.84.225
### Log Fragments or Link to [gist](https://gist.github.com/)
there is nothing about UI in logs

**Comment by slackpad** [comment]
Hi @winmasta for your example command with `-client=165.227.84.225` the UI should be available at that address. Are you running Docker for Mac or Windows where the containers run in some environment other than the host?

**Comment by slackpad** [comment]
Closing since we never heard back.
