### ISSUE TITLE
Bootstrapping using `--retry-join` and `-bootstrap-expect` fails.

### ISSUE THREAD

**Issue by kelseyhightower** [hashicorp/consul#3374]
### `consul version` for both Client and Server
Client: 
```
Consul v0.9.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

Server:
```
Consul v0.9.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

### `consul info` for both Client and Server
Client:
```
Same as server
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = b79d951
	version = 0.9.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 
	server = true
raft:
	applied_index = 0
	commit_index = 0
	fsm_pending = 0
	last_contact = never
	last_log_index = 0
	last_log_term = 0
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = []
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 0
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 68
	max_procs = 2
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 1
	left = 0
	member_time = 2
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Ubuntu 16.04-lts

### Description of the Issue (and unexpected/desired result)

Bootstrapping using with `--retry-join` and `-bootstrap-expect` fails.

### Reproduction steps

Create three machines and start consul using the following command:

```
/usr/local/bin/consul agent \
  -advertise=X.X.X.X \
  -bind=0.0.0.0 \
  -bootstrap-expect=3 \
  -client=0.0.0.0 \
  -data-dir=/var/lib/consul \
  -retry-join-gce-project-name hightowerlabs \
  -retry-join-gce-tag-value consul \
  -server \
  -ui
```

### Log Fragments or Link to [gist](https://gist.github.com/)

[ns-1 server logs](https://gist.github.com/kelseyhightower/8b7f376ad0b47ff4f71964610bef0299)
[ns-2 server logs](https://gist.github.com/kelseyhightower/eda294faa34481f3c8d73c251afa38bf)
[ns-3 server logs](https://gist.github.com/kelseyhightower/e270ac1e1e180e8a0fc36e28cbfc50e2)

**Comment by slackpad** [comment]
Hi @kelseyhightower it looks from the logs that each server is only able to join one server (probably itself):

> Aug 09 04:08:17 ns-2 consul[2772]:     2017/08/09 04:08:17 [INFO] agent: (LAN) joined: 1 Err: <nil>

So it's not seeing three servers any trying to bootstrap. Is it possible that network ACLs prevent these servers from communicating on 8301/tcp and 8301/udp?

**Comment by kelseyhightower** [comment]
Looks like my default network did not have any of the [consul ports open](https://www.consul.io/docs/agent/options.html#ports). Once I added them everything is working as expected.
