### ISSUE TITLE
Consul connects to itself on port 8300

### ISSUE THREAD

**Issue by failattu** [hashicorp/consul#339]
There's not that much info only thing we could find: 

```text
2014/09/15 16:15:18 [ERR] consul.rpc: multiplex conn accept failed: WSARecv tcp "Insert Computer Ip here":8300: An existing connection was forcibly closed by the remote host.
```
Again Windows server 2008 r2, windows server 2012 and Windows server 2012 R2 and newest version of Consul.

**Comment by failattu** [comment]
@ryanuber Sorry not working with Consul anymore so no I haven't

**Comment by ryanuber** [comment]
I'm going to close this for now. If this comes up again feel free to let us know, thanks!
