### ISSUE TITLE
Cloud Auto-Join with provider aws fails to elect leader

### ISSUE THREAD

**Issue by dictvm** [hashicorp/consul#3390]
### `consul version` for both Client and Server
Servers: `Consul v0.9.2`

### `consul info` for both Client and Server

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 75ca2ca
	version = 0.9.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 
	server = true
raft:
	applied_index = 0
	commit_index = 0
	fsm_pending = 0
	last_contact = never
	last_log_index = 0
	last_log_term = 0
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = []
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 0
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 66
	max_procs = 2
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6
	members = 5
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 14
	members = 5
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Ubuntu 16.04, running in systemd, using [this systemd unit-file](https://gist.github.com/dictvm/966352f93b770b2bd3545f0a0f787a1b). (Just to avoid confusion: The `$IP` env variable is substituted with the instance's private IP address during provisioning.) 

Note: I have forced the RAFT protocol version for testing purposes. The issue also remains when using the default settings.

### Description of the Issue (and unexpected/desired result)
I've setup 5 consul nodes across 3 AWS Availability Zones (eu-west-1-{a-c}). Each node should find the other using the newly introduced `-retry-join 'provider=$cloudprovider tag_key=foo tag_value=bar'` feature. The nodes find each other but fail to elect a leader with no precise error message. The full log is in [this gist](https://gist.github.com/dictvm/33f665cc70d4c616d493dcdc11e09432). 

### Reproduction steps
Configure 5 consul servers in a Cloud like AWS. Configure them to use the new [Cloud Auto-Join](https://www.consul.io/docs/agent/options.html#cloud-auto-joining) functionality to get the nodes IP addresses via a specific tag. Then start each nodes' consul instance and tail the log.

**Comment by slackpad** [comment]
Hi @dictvm did you specify the [`bootstrap_expect`](https://www.consul.io/docs/agent/options.html#_bootstrap_expect) option? It looks like you need to add that to get the servers to bootstrap once they all see each other.

**Comment by dictvm** [comment]
@slackpad No, I didn't, according to the docs I assumed that it wasn't necessary. However, after adding `-bootstrap-expect=5` and reprovisioning the servers, Consul still can't establish a quorum to elect a leader. [Here's the log](https://gist.github.com/dictvm/86154cd5d383a35d125c9542df40108f) with the new configuration.

**Comment by dictvm** [comment]
Turns out, I was just stupid. I now have a working 5 node cluster that elects a leader without any issues. Sorry for the hassle.
