### ISSUE TITLE
Provide current Primary key in API

### ISSUE THREAD

**Issue by dstufft** [hashicorp/consul#3393]
Currently when using the HTTP API, it does not appear possible to determine which key is the current primary key of a Consul cluster, the only data that appears to be listed about each key is how many nodes have it installed.

It would be useful to show this information to enable automated key rollover without needing to maintain state about which key you last enabled as the primary key.

**Comment by i0rek** [comment]
#8522 adds the primary keys to `v1/operator/keyring`.
