### ISSUE TITLE
ACLs Disabled

### ISSUE THREAD

**Issue by rradkris** [hashicorp/consul#3394]
Hi, 

    I've installed Consul 0.9.1 on a 3 node kubernetes cluster. Further, I can be able to access the Consul UI and trying to enable the ACL and placed. So, I did the following.

- Login to each consul node (kubeclt exec -it consul-x /bin/sh)
- Place the following json configuration (master.json) in the consul data directory (/consul/data) 
 {
  "acl_datacenter":"dc1",
  "acl_default_policy":"allow",
  "acl_down_policy":"allow",
  "acl_master_token":"CB774863-AAA9-3AED-92CF-6B29520A247"
 }
-  Reboot the consul nodes one by one. (#reboot)
-  Once the nodes are rebooted, login to the consul UI.
-  set the "ACL TOKEN" in the settings. 

The ACL is not enabled after performing all these steps. so, I wanted to know the following,

- Is the data directory (/consul/data) correct ?
- Anything wrong with the steps followed above to enable ACL ?
- It would be great, if someone help me to figure out the problem.

**Comment by preetapan** [comment]
@rradkris Agent configuration should be in the config directory `/consul/config`, or can be passed in via command line when you start the container. Adding config files to the data directory has no effect.

Also see our [containers guide](https://www.consul.io/docs/guides/consul-containers.html) for more documentation.
