### ISSUE TITLE
consul web UI show unnormally

### ISSUE THREAD

**Issue by wlibo666** [hashicorp/consul#3398]
I run consul normally,and then register some service (grpc).  maybe service's information is too many,it shows tagraggery.

it shows same on IE,firefox,chrome like link: [http://static.scloud.letv.com/wcy/consule.png](http://static.scloud.letv.com/wcy/consule.png)

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
