### ISSUE TITLE
consul migrate

### ISSUE THREAD

**Issue by wangping886** [hashicorp/consul#3418]
i have  3 old consul server (192.168.1.2,192.168.1.3,192.168.1.4). and make 3 mirrors . i make 3 new consul sever (192.168.100.55,192.168.100.56,192.168.100.57)by 3 mirrors .only ip different from old consul server . now  i start new consul sever ,that  3 new consul sever can't  elect leader.  

in new consul server 's console i run :consul info   shows:
**raft:
	applied_index = 1245223
	commit_index = 0
	fsm_pending = 0
	last_contact = never
	last_log_index = 1252113
	last_log_term = 166
	last_snapshot_index = 1245223
	last_snapshot_term = 166
	latest_configuration = [{Suffrage:Voter ID:192.168.1.3:8300 Address:192.168.1.3:8300} {Suffrage:Voter ID:192.168.1.2:8300 Address:192.168.1.2:8300} {Suffrage:Voter ID:192.168.1.4:8300 Address:192.168.1.4:8300}]**

**what should i do to change raft's latest_configuration  to new consul sever's ip so that new consul sever can elcet leader** by useing new consul sever's ip;   i   intend to use curl   --request DELETE \/v1/operator/raft/peer?address=1.2.3.4:5678  to delete raft's data , because no consul leader it failed.

**Comment by wangping886** [comment]
is my description not  enough clear ? i want know how to do  to change raft's latest_configuration to new consul sever's ip .  and my consul version is 0.7.5

**Comment by wangping886** [comment]
192.168.1.3:run consul leave  192.168.1.4:run consul leave

**Comment by slackpad** [comment]
Hi @wangping886 the snapshot option should work well. You can also perform the steps in https://www.consul.io/docs/guides/outage.html#manual-recovery-using-peers-json to fix up the IPs. In newer versions of Consul (0.9.3 with -raft-protocol=3 and 1.0.0 where Raft protocol defaults to 3), Consul will automatically fix up these IPs for you. See #1580. Hope that helps!
