### ISSUE TITLE
consistency modes in Key/Value HTTP PUT calls

### ISSUE THREAD

**Issue by danielBreitlauch** [hashicorp/consul#3427]
The documentation says there are no consistency modes for http key value PUTs to the consul agent.
I don't know if this is intentional but there are good use cases to put data into the local agents kv without waiting until it is replicated to the leaders.

We use the kv store for state saving purposes and there we have a lot of state updates over time. But it is not necessary to have all the state updates instantly everywhere. It would be helpful to have an option to signal the consul agent that it is fine to not persist them directly to the leaders. This way some values are updated locally very often but the agent can forward these changes at lower intervals.

API wise this would be doable by just enabling stale calls for PUT/DELETE just like GET already supports.

**Comment by slackpad** [comment]
Hi @danielBreitlauch thanks for opening an issue. Unfortunately, Consul clients don't store any KV state; all KV requests internally go up to the Consul servers as an RPC call. There's not really a good mechanism for this in Consul, and it would be a fairly complicated addition, so I don't think this is something we'd add at this time.
