### ISSUE TITLE
Web UI CSS Text overlapping  with multiple Tags assigned to a service 

### ISSUE THREAD

**Issue by md2k** [hashicorp/consul#3429]
### `consul version` for both Client and Server
Client: `Consul v0.9.2`
Server: `Consul v0.9.2`

### Description of the Issue (and unexpected/desired result)
This is visual presentation issue occur when multiple tags assigned to a service.
Tags unable to fit into a service block and overlap other parts of UI below of affected service.
Link to the image how it looks: https://www.dropbox.com/s/ai59yp1dw6dobf5/Screenshot%202017-08-30%2011.16.07.png?dl=0

### Reproduction steps
To reproduce simply add 5-10 tags long enough or more.

Maybe it is better to add additional parameters to affected `<ul></ul>` block to avoid overlap and keep possibility to scroll over tags in same time?
Affected block is
```
<ul class="list-inline sub">....</ul>
```

it is enough to add additional css parameters to it:
```
    height: inherit;
    width: inherit;
    text-overflow: clip;
    white-space: nowrap;
    margin-right: 10px;
```

And this block will look like by this screenshot: https://www.dropbox.com/s/7ps8eywpm4i1f5i/Screenshot%202017-08-30%2011.22.40.png?dl=0

Field with tags can be scrolled left<->right if necessary.
Probably not best way from Web Design perspective, but much better than how text may overlap above other parts of UI.

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
