### ISSUE TITLE
Consul 0.8.3 servers consuming a large amount of memory

### ISSUE THREAD

**Issue by adamwg** [hashicorp/consul#3433]
### `consul version` for both Client and Server
Client: `v0.8.3`
Server: `v0.8.3`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 0
        check_ttls = 1
        checks = 1
        services = 1
build:
        prerelease =
        revision = ea2a82b
        version = 0.8.3
consul:
        known_servers = 5
        server = false
runtime:
        arch = amd64
        cpu_count = 24
        goroutines = 36
        max_procs = 24
        os = linux
        version = go1.8.1
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 27
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 489
        members = 36
        query_queue = 0
        query_time = 1
```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = ea2a82b
        version = 0.8.3
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.124.57.11:9300
        server = true
raft:
        applied_index = 5593569
        commit_index = 5593569
        fsm_pending = 0
        last_contact = 16.614255ms
        last_log_index = 5593569
        last_log_term = 5173
        last_snapshot_index = 5581077
        last_snapshot_term = 5173
        latest_configuration = [{Suffrage:Voter ID:10.124.57.11:9300 Address:10.124.57.11:9300} {Suffrage:Voter ID:10.124.59.141:9300 Address:10.124.59.141:9300} {Suffrage:Voter ID:10.124.59.142:9300 Address:10.124.59.142:9300} {Suffrage:Voter ID:10.124.59.143:9300 Address:10.124.59.143:9300} {Suffrage:Voter ID:10.124.59.144:9300 Address:10.124.59.144:9300}]
        latest_configuration_index = 5593453
        num_peers = 4
        protocol_version = 2
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 5173
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 70
        max_procs = 4
        os = linux
        version = go1.8.1
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 27
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 486
        members = 36
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 238
        members = 5
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

Ubuntu 14.04.5

TLS is enabled and required:
```
  "verify_incoming": true,
  "verify_incoming_rpc": true,
  "verify_outgoing": true,
  "verify_server_hostname": false,
```

### Description of the Issue (and unexpected/desired result)

We have a consul cluster with five servers running consul 0.8.3. On these nodes, consul is using over 7GB of memory, and since the machines have 8GB and no swap sometimes the consul processes end up dying. If they die while writing out a raft snapshot, a partial snapshot gets left behind on disk and eventually we run out of disk space as well, causing our cluster to become unavailable.

We have consul 0.7.x clusters with similar usage that consume significantly less memory (<100MB). The only significant difference, other than the consul version, is that our 0.8.3 clusters require client TLS.

Is this increased memory usage a known/expected issue in newer versions of consul?

### Log Fragments

* [Lightly redacted consul log from when it ran out of memory](https://awg.nyc3.digitaloceanspaces.com/consul-oom.log)
* [/debug/pprof/heap?debug=1 from consul server](https://awg.nyc3.digitaloceanspaces.com/heap.pprof)

**Comment by adamwg** [comment]
An update here: today we noticed that our consul 0.8 servers have approximately doubled their memory usage (to 12-13GB) sometime in the past couple of weeks. Our utilization has likely increased somewhat over that time as well, so it's possible that the memory usage is increasing with request volume.

Any more info I can gather to help debug this? Any suggestions on how we can mitigate the memory usage?

**Comment by slackpad** [comment]
Hi @adamwg this is a weird one - the heap dump looks like a lot of data in the state store around KV. I don't know of any memory leaks in that version of Consul. Are your Raft snapshots roughly growing by the same amount? It might also be interesting to get another heap dump after the doubling so we can look there for patterns.

**Comment by adamwg** [comment]
Thanks for the quick response @slackpad!

Our raft snapshots are currently 3.2GB. Unfortunately, we don't have any monitoring around them so I'm not sure if that's changed recently.

A heap dump from today [can be found here](https://rtwo.nyc3.digitaloceanspaces.com/consul-2017-09-22.heap.pprof).

**Comment by adamwg** [comment]
Following up on this:

After some further investigation we determined that the high memory usage was related to our usage pattern. There were two factors:

1. One of the services registered with consul had large health-check output, which consul was storing in snapshots. Using an endpoint with smaller output for health checks and reducing the check frequency helped some.

2. One of our processes was periodically dumping a somewhat large volume of KV data into consul. This data would get cleaned up later, but it made the raft snapshots large for a time. Reducing the frequency with which this process dumped data greatly mitigated the memory usage.

Given these discoveries, I think we're safe to close this as being caused mostly or entirely by our usage.

**Comment by slackpad** [comment]
Thanks for the follow up @adamwg!
