### ISSUE TITLE
kv api to support get and increment by 1 in transaction

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#3434]
Hi,

I notice that the operations defined in single transaction have no way to interact with each other, and I need to define a transaction with two operations: Get and Set, and the value for Set is from the result of Get. is that possible?

**Comment by slackpad** [comment]
Hi @hehailong5 unfortunately there's not a way to do this in a single operation. You can use the `cas` verb in a txn or https://www.consul.io/api/kv.html#cas to safely do this in two steps. Hope that helps!
