### ISSUE TITLE
consul reload 

### ISSUE THREAD

**Issue by ixufeng** [hashicorp/consul#3435]
I modified the configuration  file (v0.9.2)
```
"enable_script_checks" = true
```
then exec *consul reload* but not  works

unless exec *consul leave* and restart,it will works

**Comment by wangping886** [comment]
Not all configuration options are reloadable. See the Reloadable Configuration section on the agent options page for details on which options are supported.
refer  https://www.consul.io/docs/commands/reload.html

**Comment by ixufeng** [comment]
Really so，thanks a lot, I @wangping886
