### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DanielCharczynski** [hashicorp/consul#3438]
It happened on windows
Consul 0.7.2 working as an client

\local.snapshot: The process cannot access the file because it is being used by another process.
    2017/06/20 19:14:42 [INFO] serf: EventMemberFailed: WPPLD0001200 10.87.111.169
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x934246]

goroutine 13 [running]:
panic(0xd4af60, 0xc082008080)
        /goroot/src/runtime/panic.go:481 +0x3f4
bufio.(*Writer).WriteString(0x0, 0xc082121fa0, 0x18, 0x3, 0x0, 0x0)
        /goroot/src/bufio/bufio.go:660 +0x46
github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf.(*Snapshotter).appendLine(0xc0820a66c0, 0xc082121fa0,
0x18, 0x0, 0x0)
        /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf/snapshot.go:321 +0x161
github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf.(*Snapshotter).tryAppend(0xc0820a66c0, 0xc082121fa0, 0
x18)
        /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf/snapshot.go:312 +0x49
github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf.(*Snapshotter).processMemberEvent(0xc0820a66c0, 0x2, 0
xc0822936d0, 0x1, 0x1)
        /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf/snapshot.go:259 +0x55a
github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf.(*Snapshotter).stream(0xc0820a66c0)
        /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf/snapshot.go:215 +0x7a4
created by github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf.NewSnapshotter
        /gopath/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/serf/serf/snapshot.go:129 +0x726
PS C:\consul>

**Comment by slackpad** [comment]
Hi @DanielCharczynski thanks for opening an issue - "The process cannot access the file because it is being used by another process." - is it possible you've got multiple agents running at the same time somehow?

**Comment by slackpad** [comment]
Closing this as we never heard back. It's always bad form to panic, but in this case it looks like there are multiple instances of an agent running, so that's a pretty unusual case, and we haven't seen other reports of this. Letting the agent crash and get restarted is probably the best course of action here vs. logging an error and not being able to write Serf snapshots.
