### ISSUE TITLE
Make consul.service.consul accessible on macos sierra

### ISSUE THREAD

**Issue by 4iAmAve** [hashicorp/consul#3442]
Hi,

I am using a mac with macos Sierra and want to use service discovery through consul and want all services to run under *.service.consul. Yet, this doesn't work so easily under Sierra as it is on like Ubuntu. Is there a guide or can anyone tell me, how to get this up and running on Sierra.

Thanks in advance.

Regards

**Comment by slackpad** [comment]
Hi @4iAmAve unfortunately we don't have any Mac DNS expertise to help here. This might get better visibility from the community if posted to the mailing list. Sorry about that.
