### ISSUE TITLE
Service maintenance mode

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#345]
Support a simple mechanism to flip a service into a maintenance mode to prevent routing traffic. Likely this is just an agent API which maps to a temporary health check set to the "critical" state with the relevant notes attached. We can even support a TTL mechanism to flip out of maintenance mode to protect against a buggy client that leaves this mode on.

**Comment by ryanuber** [comment]
Done in #606! We don't support a TTL mechanism yet, so it's currently possible for a buggy client to leave maintenance mode enabled. If we introduce a TTL, I could also see needing to have the ability to remove the TTL while maintenance mode was still enabled in case things go wrong, or updating the TTL to extend it. Not sure if that would be helpful or confusing to a user.
