### ISSUE TITLE
Unable to print Consul version, getting  "Consul unknown-unknown"

### ISSUE THREAD

**Issue by anujajakhade** [hashicorp/consul#3453]
I have built Consul v0.9.2 on x86, the build and test cases are running successfully. 
However if  I try to print the Consul version. I am getting below output instead of 0.9.2

> 
> Consul unknown-unknown
> Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
> 

Have i missed some steps?

**Comment by magiconair** [comment]
Pls run `make dev` to see the full command. It will run `go build -tags consul` and set the version using linker flags. The most notable thing is that you need to add `-tags consul`. We removed that in #3422.
