### ISSUE TITLE
Can't get retry-join with gce provider to work

### ISSUE THREAD

**Issue by grobinson-blockchain** [hashicorp/consul#3454]
### Description of the Issue (and unexpected/desired result)

I'm trying to migrate an existing Consul cluster to use cloud auto-joining on Google Compute Engine. 

However, when attempting to start consul, I get the following error:

    /opt/consul/0.9.2/bin/consul agent -config-dir=/etc/consul/conf.d -log-level=trace
    ==> WARNING: LAN keyring exists but -encrypt given, using keyring
    ==> WARNING: WAN keyring exists but -encrypt given, using keyring
    ==> WARNING: Expect Mode enabled, expecting 3 servers
    ==> Starting Consul agent...
    ==> Joining cluster...
    ==> 1 error(s) occurred:

    * Failed to resolve provider=gce project_name=xxx tag_value=consul-server credentials_file=/etc/consul/gce-credentials-file.json: lookup provider=gce project_name=xxx tag_value=consul-server credentials_file=/etc/consul/gce-credentials-file.json: no such host

with this configuration file:

    {
      "acl_datacenter": "europe-west1",
      "acl_default_policy": "deny",
      "acl_down_policy": "extend-cache",
      "acl_master_token": "xxx",
      "acl_token": "xxx",
      "advertise_addr": "xxx",
      "advertise_addr_wan": "xxx",
      "bind_addr": "0.0.0.0",
      "bootstrap_expect": 3,
      "data_dir": "/var/consul",
      "datacenter": "europe-west1",
      "dns_config": {
        "allow_stale": true,
        "enable_truncate": true,
        "service_ttl": {
          "*": "15s"
        },
        "udp_answer_limit": 3
      },
      "enable_debug": false,
      "enable_script_checks": true,
      "encrypt": "xxx",
      "leave_on_terminate": false,
      "log_level": "info",
      "retry_interval": "15s",
      "retry_join": [
        "provider=gce project_name=xxx tag_value=consul-server credentials_file=/etc/consul/gce-credentials-file.json"
      ],
      "server": true,
      "start_join": [
        "provider=gce project_name=xxx tag_value=consul-server credentials_file=/etc/consul/gce-credentials-file.json"
      ],
      "telemetry": {
        "disable_hostname": true,
        "statsd_address": "127.0.0.1:8125"
      },
      "ui_dir": "/usr/local/share/consul/ui"
    }

running consul 0.9.2:

    /opt/consul/0.9.2/bin/consul version
    Consul v0.9.2
    Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

**Comment by magiconair** [comment]
The `go-discover` syntax is only supported for `retry_join`. Pls remove the entry from `start_join` and try again since this is being interpreted as a hostname and hence fails.

**Comment by slackpad** [comment]
Closing since we never heard back.

**Comment by ashwini-tal** [comment]
@magiconair Could you please let me know what to provide in the tag_value parameter in the "retry_join" for gce provider. Also, with tag_value, does it mean Compute Engine labels?
