### ISSUE TITLE
Bug: Connection leak (FIN_WAIT2) on Windows

### ISSUE THREAD

**Issue by justenwalker** [hashicorp/consul#3459]
### `consul version` for both Client and Server
Client: `0.8.5`
Server: `0.8.5`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 4
        services = 9
build:
        prerelease =
        revision = 2c77151
        version = 0.8.5
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 16
        goroutines = 69
        max_procs = 16
        os = windows
        version = go1.8.3
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 191
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 5
        member_time = 7047
        members = 247
        query_queue = 0
        query_time = 16
```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = 2c77151
        version = 0.8.5
consul:
        bootstrap = false
        known_datacenters = 2
        leader = false
        leader_addr = 10.126.6.5:8300
        server = true
raft:
        applied_index = 590177577
        commit_index = 590177577
        fsm_pending = 0
        last_contact = 1.639504ms
        last_log_index = 590177578
        last_log_term = 688
        last_snapshot_index = 590177123
        last_snapshot_term = 688
        latest_configuration = [{Suffrage:Voter ID:10.126.6.4:8300 Address:10.126.6.4:8300} {Suffrage:Voter ID:10.126.6.6:8300 Address:10.126.6.6:8300} {Suffrage:Voter ID:10.126.
6.5:8300 Address:10.126.6.5:8300}]
        latest_configuration_index = 311871622
        num_peers = 2
        protocol_version = 2
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 688
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 2705
        max_procs = 2
        os = linux
        version = go1.8.3
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 191
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 5
        member_time = 7047
        members = 247
        query_queue = 0
        query_time = 16
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 45
        members = 6
        query_queue = 0
        query_time = 19
```

### Operating system and Environment details

- Servers and some Clients are Ubuntu 16.04: `Linux consul1 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- Some other clients are Windows Server 2016 Datacenter

### Description of the Issue (and unexpected/desired result)

I'm noticing that some times Consul 0.8.5 opens a bunch of connections over time. 
On one machine (Windows) it went from 2k to 15k over a 24 hour period. 
They all end up in FIN_WAIT2 state.

<img width="1312" alt="screen shot 2017-09-07 at 9 57 39 pm" src="https://user-images.githubusercontent.com/222027/30227405-9c474174-94a7-11e7-89f8-808ea27365ff.png">

Connections appear to be originating with consul.exe and are local connections over the LAN interface (10.x.x.x); Likely these are HTTP Health checks. Possibly forgetting to close connections?

I do see a lot of health check failures / connection refused messages in the log
The host on which this happened does not appear to have a disproportionate amount of them though, it appears pretty evenly distributed across our entire cluster

**Comment by slackpad** [comment]
Hi @justenwalker thanks for opening an issue. Is there any kind of `lsof` or `netstat` equivalent on Windows you can use to see which IIP:port combos those leaked connections involve? It would be interesting to see if they definitely tie to your application health checks and are outbound sockets opened by Consul or if they are from some inbound connection to Consul, such as something talking to Consul's HTTP interface on port 8500.

**Comment by justenwalker** [comment]
Hi @slackpad ; The host in question no longer has this problem since we destroyed / recreated it to recover. However, it eventually will resurface, and I'll try to get a netstat for that when it does.

**Comment by pearkes** [comment]
Given we haven't heard anything for this issue I'm going to close it out, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
