### ISSUE TITLE
May be feature request, direct/pipe the stdout output from watch script(s) to stdout from consul agent

### ISSUE THREAD

**Issue by vidhill** [hashicorp/consul#3464]
### `consul version` for both Client and Server
Client: 0.8.4
Server: 0.8.4

### Operating system and Environment details
Running within Docker Container on Kubernetes

### Description of the Issue (and unexpected/desired result)

Is it possible to direct/pipe the stdout output from watch scripts (configured in a config.json file) to the stdout that is output from consul agent, at the moment I am piping the content into a file.. but it would be preferable to get it out into stdout..

Example config fragment
```json
{
   "type": "nodes",
   "handler": "nodes-watch.js >> logs/node-watch-log.txt "
}
```

I know I may be able to achieve this by running `consul watch` processes separately for each of my watch scripts,  but as this is running within a docker container I would need to add in additional process management

**Comment by slackpad** [comment]
Hi @vidhill if you run Consul with debug log level it should output the watch output to the log, up to the first 4k of output - https://github.com/hashicorp/consul/blob/master/agent/watch_handler.go#L91. Hope that helps!
