### ISSUE TITLE
Consul prevents instances of services running if their host machine's hostnames are identical

### ISSUE THREAD

**Issue by lyptt** [hashicorp/consul#3468]
### `consul version` for both Client and Server
Client: `0.9.2`
Server: `0.9.2`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 1
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = 75ca2ca
        version = 0.9.2
consul:
        known_servers = 1
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 39
        max_procs = 2
        os = linux
        version = go1.8.3
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 33
        members = 3
        query_queue = 0
        query_time = 16
```

### Operating system and Environment details
Consul server runs on latest Centos 7
Consul agents run on Ubuntu Xenial 16.04

### Description of the Issue (and unexpected/desired result)
In my test environment, I have one Consul server, and three separate machines running Consul agents. Each agent is configured to auto-register with the server.

Each Consul agent machine has an identical hostname, as it's essentially left unconfigured from the defaults.

When booting, each machine replaces the previously registered machine as the only machine offering the service, even though the service definitions all have unique ids. What I would expect to happen is for Consul to respect the fact that the service definitions all contain unique ids and preserve each machine's registration.

### Log Fragments or Link to [gist](https://gist.github.com/)

Sep 12 18:32:28 ubuntu-xenial consul[21007]:     2017/09/12 18:32:28 [INFO] agent: Deregistered service 'zookeeper2'
Sep 12 18:32:28 ubuntu-xenial consul[21007]: agent: Deregistered service 'zookeeper2'
Sep 12 18:34:10 ubuntu-xenial consul[21007]:     2017/09/12 18:34:10 [INFO] agent: Deregistered service 'zookeeper2'
Sep 12 18:34:10 ubuntu-xenial consul[21007]: agent: Deregistered service 'zookeeper2'
Sep 12 18:34:10 ubuntu-xenial consul[21007]:     2017/09/12 18:34:10 [INFO] agent: Synced service 'zookeeper1'
Sep 12 18:34:10 ubuntu-xenial consul[21007]: agent: Synced service 'zookeeper1'
Sep 12 18:36:03 ubuntu-xenial consul[21007]:     2017/09/12 18:36:03 [INFO] agent: Deregistered service 'zookeeper3'
Sep 12 18:36:03 ubuntu-xenial consul[21007]: agent: Deregistered service 'zookeeper3'
Sep 12 18:36:03 ubuntu-xenial consul[21007]:     2017/09/12 18:36:03 [INFO] agent: Synced service 'zookeeper1'
Sep 12 18:36:03 ubuntu-xenial consul[21007]: agent: Synced service 'zookeeper1'

**Comment by slackpad** [comment]
Hi @lyptt Consul internally indexes the catalog by node name, and service IDs are only scoped for a given node name, so in a situation like this the agents will fight when running their anti-entropy process and remove services that they don't have locally. You'll need to configure each agent with a unique node name to fix this.

**Comment by lyptt** [comment]
Hi @slackpad, I figured this was the issue. Is this documented anywhere? I was completely unaware this was the case until I saw the results I was seeing. I know for certain it's not present in the service definition documentation.

I think ensuring this behaviour is described somewhere will help a lot for people who are unaware of how Consul's internal mechanisms work.

**Comment by i0rek** [comment]
It is documented here: https://www.consul.io/docs/agent/options.html#_node.
