### ISSUE TITLE
Dead nodes still being used in raft election

### ISSUE THREAD

**Issue by alkalinecoffee** [hashicorp/consul#3472]
### `consul version` for both Client and Server
Client: `0.9.3`
Server: `0.9.3`

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 112c060
	version = 0.9.3
consul:
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr =
	server = true
raft:
	applied_index = 318
	commit_index = 318
	fsm_pending = 0
	last_contact = 5m17.690705143s
	last_log_index = 319
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:244fe333-89d5-16cc-827f-72549ead6a1d Address:96.112.225.54:8300} {Suffrage:Voter ID:00e35c67-a4c7-f2bb-0834-15aa54ff1a9e Address:96.112.224.4:8300} {Suffrage:Voter ID:b72d18ba-3804-6eaf-07d7-dae9e68962d2 Address:96.112.224.84:8300} {Suffrage:Voter ID:a9b1e84f-0b07-a0bc-66c5-7379a9453423 Address:96.112.225.130:8300} {Suffrage:Nonvoter ID:4d840757-3f1b-8751-6998-b333daf31f2c Address:96.112.224.8:8300}]
	latest_configuration_index = 319
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Candidate
	term = 47
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 102
	max_procs = 1
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 3
	member_time = 10
	members = 6
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 3
	member_time = 96
	members = 9
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Amazon Linux in AWS

### Description of the Issue (and unexpected/desired result)
Consul loses the leader when running within an autoscaling group and the group is scaled in.  Consider the following:

1. Cluster created with ASG, initially 3 nodes.  Cluster bootstraps fine, health is good.
2. Cluster is scaled up to 6 nodes. Cluster health is good.
3. Cluster is scaled down to 3 nodes. The initial leader from the original 3 nodes is lost.
4. The cluster attempts an election, but logs show that raft still attempts to connect to some (or all) of the dead nodes. The election never succeeds.

Our configuration includes `leave_on_terminate = true`. We can see in the logs that when a node is terminated by the ASG, `consul` and `serf` appear to acknowledge the leave signal.  However, `raft` continues to try to connect to some of the dead nodes.

The `consul operator raft` commands do not work as no leader is elected, so I'm unable to manually remove these nodes from raft with the CLI.  To get the cluster working again, I need to manually create a `peers.json` and use that on all the nodes.

### Reproduction steps
1. Create cluster with ASG, `desired_capacity = 3`
2. Increase ASG size, `desired_capacity = 6`
3. Decrease ASG size, `desired_capacity = 3`

### Log Fragments or Link to [gist](https://gist.github.com/)

There are 3 original nodes that are now dead:

```
xxx.xxx.xxx.4
xxx.xxx.xxx.54
xxx.xxx.xxx.216
```

In my logs, `raft` won't bother connecting to xxx.216, but will keep trying to connect to the other two.

```
consul[2415]: serf: EventMemberLeave: ip-xxx-xxx-xxx-216.aws-dc1 xxx.xxx.xxx.216
consul[2415]: consul: Handled member-leave event for server "ip-xxx-xxx-xxx-216.aws-dc1" in area "wan"
consul[2415]: serf: EventMemberLeave: ip-xxx-xxx-xxx-216 xxx.xxx.xxx.216
consul[2415]: consul: Removing LAN server ip-xxx-xxx-xxx-216 (Addr: tcp/xxx.xxx.xxx.216:8300) (DC: aws-dc1)
consul[2415]: serf: EventMemberLeave: ip-xxx-xxx-xxx-54.aws-dc1 xxx.xxx.xxx.54
consul[2415]: consul: Handled member-leave event for server "ip-xxx-xxx-xxx-54.aws-dc1" in area "wan"
consul[2415]: serf: EventMemberLeave: ip-xxx-xxx-xxx-54 xxx.xxx.xxx.54
consul[2415]: consul: Removing LAN server ip-xxx-xxx-xxx-54 (Addr: tcp/xxx.xxx.xxx.54:8300) (DC: aws-dc1)
consul[2415]: serf: EventMemberLeave: ip-xxx-xxx-xxx-4.aws-dc1 xxx.xxx.xxx.4
consul[2415]: consul: Handled member-leave event for server "ip-xxx-xxx-xxx-4.aws-dc1" in area "wan"
consul[2415]: serf: EventMemberLeave: ip-xxx-xxx-xxx-4 xxx.xxx.xxx.4
consul[2415]: consul: Removing LAN server ip-xxx-xxx-xxx-4 (Addr: tcp/xxx.xxx.xxx.4:8300) (DC: aws-dc1)
consul[2415]: agent: failed to sync remote state: No cluster leader
... (below is repeated)
consul[2415]: raft: Heartbeat timeout from "xxx.xxx.xxx.216:8300" reached, starting election
consul[2415]: raft: Node at xxx.xxx.xxx.8:8300 [Candidate] entering Candidate state in term 3
consul[2415]: raft: Election timeout reached, restarting election
consul[2415]: raft: Node at xxx.xxx.xxx.8:8300 [Candidate] entering Candidate state in term 4
consul[2415]: raft: Node at xxx.xxx.xxx.8:8300 [Follower] entering Follower state (Leader: "")
consul[2415]: raft: Failed to make RequestVote RPC to {Voter 244fe333-89d5-16cc-827f-72549ead6a1d xxx.xxx.xxx.54:8300}: dial tcp xxx.xxx.xxx.8:0->xxx.xxx.xxx.54:8300: i/o timeout
consul[2415]: raft: Failed to make RequestVote RPC to {Voter 00e35c67-a4c7-f2bb-0834-15aa54ff1a9e xxx.xxx.xxx.4:8300}: dial tcp xxx.xxx.xxx.8:0->xxx.xxx.xxx.4:8300: i/o timeout
```

**Comment by alkalinecoffee** [comment]
So I got a little more information about this.  It may well be user error, but perhaps there are changes in Consul that could help prevent this so I'll leave this open for further discussion.

It appears that when the cluster is expanded, the new servers do not gain voting privileges (`bootstrap-expect=3` is set on all members).

When the cluster is abruptly scaled-in from 6 nodes to 3, the original nodes are destroyed, leaving the 3 new, non-voting servers.  As none have voting power, and no leader is elected, they remain in this condition, thus resulting in cluster failure.

I'm able to circumvent this by slowly scaling in one server at a time, checking to make sure at least 3 voters exist in the cluster before scaling in again.  This is a reasonable and safe approach, but I'm wondering if the remaining nodes should be able to figure out that the old cluster is effectively destroyed, and a new bootstrap process should begin.

**Comment by shilov** [comment]
Non-voting consul servers are an enterprise feature. All servers you add to the original cluster should become voting members, regardless of what your `bootstrap-expect` is set to.

Consul will automatically remove dead servers after 72 hrs. I suggest you ease the work consul has to do by running `consul leave` when taking down a machine.

In some cases, I've seen dead servers persist longer than expected, specifically when running v0.9.3. In case that happens, you can try removing them manually https://www.consul.io/docs/commands/operator/raft.html#remove-peer

**Comment by preetapan** [comment]
@shilov @alkalinecoffee When consul processes the join event from the three new servers that came with the increased ASG size, it does initially add them as [nonvoters]( https://github.com/hashicorp/consul/blob/4dab70cb937ee240bea8cf7287ffdc1af927748e/agent/consul/leader.go#L715), and then [autopilot](https://www.consul.io/docs/guides/autopilot.html) handles promoting them to voters. But the autopilot loop can only do that when there is a stable leader, because it needs that to make safe configuration changes. All of this is in the OSS version. The key difference with enterprise is that non voting servers can stay that way and never be promoted, to be used for scaling reads. 

As for what happened above, it was because of going from three to zero and coming back to adding three more new servers. Autopilot was not able to handle promoting those non voters because the cluster at that point lost all its voters. 

As for dead servers persisting longer than expected, that was a bug until Consul 0.9.3. https://github.com/hashicorp/consul/issues/3452 and fixed in Consul 1.0.

**Comment by shilov** [comment]
@preetapan thanks for clarifying. What constitutes a stable leader, is there other criteria aside from disagreement between servers over leader election?

If I'm not mistaken, @alkalinecoffee was scaling from 3 to 6 then back down to 3. The original 3 servers were still present when the additional 3 were added, but the new ones never got promoted to voters. I've seen some variation of this problem with 0.9.3, and solved it in a similar fashion by introducing new instances at a much slower rate.

I'm seeing much better reaping w/ 1.0.0, it's nice to see these issues being worked on, esp. since improvements like these often get less recognition in product announcements.

**Comment by preetapan** [comment]
I may have misunderstood what happened - I originally thought it went from 3 to 6 and back down to 3 immediately. The two main config values that affect autopilot promotion are : 
[ServerStabilizationTime](https://www.consul.io/docs/guides/autopilot.html#stable-server-introduction ) which is set to 10 seconds by default and controls how long before a server needs to be healthy before it can be promoted to voter. 
[AutopilotInterval](https://github.com/hashicorp/consul/blob/bb12368eaca74664a66e3d5fdaf0a7f8d2e50836/agent/consul/config.go#L425) which is hardcoded to 10 seconds, but given this is a background routine it is not guaranteed to run exactly at 10 seconds. 

In the worst case I can see how scaling back from 6 to 3 within 30 seconds or less can cause this to happen. 

It is also possible I could be missing something else and this is a different bug. Will discuss with others on the team internally to see if there's something else going on. In the meantime it would be helpful to know how long the time interval was between the scale up and scale down.

**Comment by slackpad** [comment]
This should have been made less tricky by https://github.com/hashicorp/consul/pull/3623 as well.
