### ISSUE TITLE
How should I use one ip to access the consul cluster.

### ISSUE THREAD

**Issue by Silence2012** [hashicorp/consul#3473]
How should I use one ip to access a consul cluster. For example there is 3 nodes consul cluster
consul node 1 : 10.10.10.2:8500  leader
consul node 2 : 10.10.10.3:8500  follow
consul node 3 : 10.10.10.4:8500  follow

How should I use one ip + port to access the consul cluster without inviting other software like nginx?

**Comment by jfgibbins** [comment]
Any type of load balancer, such as haproxy, nginx, f5, etc, or even just as simple as a VIP, setup with keepalived.  Consul UI is treated like any other web service for that purpose.

**Comment by magiconair** [comment]
You should not put consul behind a load balancer but instead install a local agent on all of your nodes and then connect to `localhost:8500`. The requests will be automatically forwarded to the current leader.

**Comment by jfgibbins** [comment]
@magiconair Yes, that would be true for applications that are using consul, but you certainly wouldn't install it on your local pc to access for management, so yes, there is reason to want to have it behind a cluster ip.  Unfortunately consul does not handle VIP on its own, so if you want to access it from a non-agent machine, the servers would need to be put behind a lb or vip.  I personally run it on top of docker swarm, which handles it using the ingress network, but that requires some adjustments, as consul's method of storing server IPs in raft, is rather crippling.

**Comment by Saliva520319** [comment]
@jfgibbins  Did you have some tricks about this?

**Comment by slackpad** [comment]
The best way to deal with the PC use case is probably via DNS (configure a DNS name with the Consul servers, for example) or some kind of LB or proxy, but for all other use cases we definitely recommend running the agent. Hope that helps!

**Comment by Jaware** [comment]
any LB or proxy suggestion?@slackpad

**Comment by ferrix** [comment]
One option is to use DNS forwarding in the local network. You can then point your browser at http(s)://consul.service.<dc>.consul/
