### ISSUE TITLE
v1/agent/metrics http endpoint returns nothing

### ISSUE THREAD

**Issue by cshabi** [hashicorp/consul#3484]
Server: 0.7.5

Server consul info:
agent:
       	check_monitors = 1
       	check_ttls = 0
       	checks = 1
       	services = 2
build:
       	prerelease =
       	revision = '21f2d5a
       	version = 0.7.5
consul:
       	bootstrap = false
       	known_datacenters = 4
       	leader = true
       	leader_addr = IP:8300
       	server = true
raft:
       	applied_index = 1295672656
       	commit_index = 1295672656
       	fsm_pending = 0
       	last_contact = 0
       	last_log_index = 1295672656
       	last_log_term = 242948
       	last_snapshot_index = 1295671400
       	last_snapshot_term = 242948
       	latest_configuration = [{Suffrage:Voter ID:IP:8300 Address:IP:8300} {Suffrage:Voter ID:IP:8300 Address:IP:8300} {Suffrage:Voter ID:IP:8300 Address:IP:8300}]
       	latest_configuration_index = 1279244436
       	num_peers = 2
       	protocol_version = 1
       	protocol_version_max = 3
       	protocol_version_min = 0
       	snapshot_version_max = 1
       	snapshot_version_min = 0
       	state = Leader
       	term = 242948
runtime:
       	arch = amd64
       	cpu_count = 24
       	goroutines = 21461
       	max_procs = 24
       	os = linux
       	version = go1.7.5
serf_lan:
       	encrypted = true
       	event_queue = 0
       	event_time = 52453
       	failed = 4
       	health_score = 0
       	intent_queue = 0
       	left = 1
       	member_time = 74294
       	members = 2735
       	query_queue = 0
       	query_time = 1120
serf_wan:
       	encrypted = true
       	event_queue = 0
       	event_time = 1
       	failed = 0
       	health_score = 0
       	intent_queue = 0
       	left = 0
       	member_time = 47
       	members = 10
       	query_queue = 0
       	query_time = 1

### Operating system and Environment details
ubuntu 12.04 

### Description of the Issue (and unexpected/desired result)
We stream our metrics to statsd and from there to graphit.
We are moving to prometheus and would like to not use the statsd exporter. 
Going over the documentation I saw theres a v1/agent/metrics end point that holds a son with the telemetry but I'm unable to bury my servers.
The endpoint seems to be empty, nothing is returned (not even an empty hash)

the command I'm running is:
curl http://localhost:8500/v1/agent/metrics

**Comment by slackpad** [comment]
Hi /v1/agent/metrics was added in Consul 0.9.1, so you'll need to upgrade Consul from 0.7.5 to get that.
