### ISSUE TITLE
Consul ACL tokens

### ISSUE THREAD

**Issue by hbmelachuru10** [hashicorp/consul#3486]
Consul server version v 0.8.4
1. Do we have any process to clean up unused ACL tokens? How do we know that client token is not in use?
2. Do we have any limit to create ACL client tokens ? Any maximum limit?
3. Can we provide any expiration on the acl tokens or is it long-lived?
Your response is appreciated. Thank you

@slackpad  @armon

**Comment by slackpad** [comment]
Hi @hbmelachuru10 Consul currently does not have any limits or automatic expiration, though if you use Vault it has a Consul secret back end that will manage token lifetime for you based on roles in Vault and secret leases - https://www.vaultproject.io/docs/secrets/consul/index.html.

**Comment by hbmelachuru10** [comment]
@slackpad : Is there any audit capability for consul acl tokens ?

**Comment by slackpad** [comment]
@hbmelachuru10 not yet - we have plans to create ACL accessor IDs (similar to Vault) which can be used to look up the tokens but don't grant any of the privileges. Once we have that in place we can log those along with actions. Don't have a time frame for that but it's on our radar.

**Comment by hbmelachuru10** [comment]
@slackpad Cool. Thank you so much for your quick response.

**Comment by slackpad** [comment]
NP - I'll close this one out!
