### ISSUE TITLE
Consul Nodes Going to Failed Instead of Dead

### ISSUE THREAD

**Issue by solasar** [hashicorp/consul#3487]
Issue:

In Consul 0.6.0, when an agent would be shutdown ungracefully, the node would correctly listed as dead.  In Consul 0.7.5, when an agent is shutdown ungracefully, the node goes to failed state and remains there until reaped.

Environment:
Consul 0.7.5 servers, Consul 0.7.5 Agents
Ubuntu in GCP

Steps to recreate:
The easiest way we've found to do this is to select an instance that has an agent running and run stop the consul service.  This should cause it to leave ungracefully, and persist in the members list as "failed" until reaped.

Expected Behavior:
These nodes should be eventually marked as dead after a period (preferably configurable) after falling into failed state.

Actual Behavior:
These nodes fall into failed state and remain that way until the reap period is reached and consul reaps it from the member list.

**Comment by slackpad** [comment]
Hi @solasar can you provide a little more details about where you saw "dead"? In Consul 0.6.0 you'd still see "failed" on an ungraceful leave:

```
$ docker run --net=host oldconsul members
Node    Address         Status  Type    Build  Protocol  DC
moby    127.0.0.1:8301  alive   server  0.6.0  2         dc1
yoyoyo  127.0.0.2:8301  failed  client  0.6.0  2         dc1
```

**Comment by solasar** [comment]
I apologize - by dead, I mean the Left state.  Our instances, when they did an ungraceful leave in 0.6.0, would go to the left state within the cluster.  Since our upgrade to 0.7.5, they go into a failed state rather then having left the cluster and will remain that way until the reap period, even if the IP is reused.  The instances should, after some time, go to the left state rather then staying within the failed state until reaping.

**Comment by slackpad** [comment]
Thanks @solasar this is likely a difference in the new default behavior of `leave_on_terminate` after Consul 0.7.0 - https://www.consul.io/docs/agent/options.html#leave_on_terminate:

> leave_on_terminate If enabled, when the agent receives a TERM signal, it will send a Leave message to the rest of the cluster and gracefully leave. The default behavior for this feature varies based on whether or not the agent is running as a client or a server (prior to Consul 0.7 the default value was unconditionally set to false). On agents in client-mode, this defaults to true and for agents in server-mode, this defaults to false.

You could set that to `true` for your servers to get back to the old behavior.

**Comment by solasar** [comment]
Thanks, that would help a lot!  I will test that out next time I do a consul cluster deployment.

**Comment by slackpad** [comment]
Sounds good - I'll close this out for now but please let us know if this doesn't work out.
