### ISSUE TITLE
How to get the total numbers of longpull

### ISSUE THREAD

**Issue by yuzd** [hashicorp/consul#3491]
the clients use following url to request a longpull from the consul server.

`http://127.0.0.1:8500/v1/catalog/service/serviceA?near=_agent&passing&index=11`

how to get the total numbers of longpull  from the consul server?

**Comment by slackpad** [comment]
Hi @yuzd there's not a distinction between blocking and non-blocking queries in Consul's telemetry, but the `consul.rpc.query` [telemetry](https://www.consul.io/docs/agent/telemetry.html) is a superset and includes both. Hope that helps!
