### ISSUE TITLE
Expect mode does not imply server mode

### ISSUE THREAD

**Issue by gmreburn** [hashicorp/consul#3510]
### `consul version` for both Client and Server
Client: `0.9.3`
Server: `0.9.3`

### Operating system and Environment details
Centos/7

### Description of the Issue (and unexpected/desired result)
[Consul Documentation](https://www.consul.io/docs/agent/options.html#_bootstrap_expect) states that `server` config flag is implied when using `bootstrap-expect` flag but this is not true. I receive `==> Expect mode cannot be enabled when server mode is not enabled`. I expected the server flag to be set to true as the documentation instructs.

### Reproduction steps
`# consul agent -bootstrap-expect=1 -data-dir=/var/consul`

### Log Fragments or Link to [gist](https://gist.github.com/)

`==> Expect mode cannot be enabled when server mode is not enabled`

**Comment by slackpad** [comment]
Hi @gmreburn that was badly worded so rephrased it to be more clear. You definitely need to also specify `-server`.
