### ISSUE TITLE
on windows, service won't register when ACL restricted

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/consul#3512]
### `consul version` for both Client and Server
Client: 0.9.3
Server: 0.9.3

### `consul info` for both Client and Server
Client:

Windows 2012 R2

Server:

Linux Ubuntu Xenial 17.04 LTS

### Operating system and Environment details

3-server raft, using ACL tokens.

Anonymous:
node "" {
  policy = "read"
}
service "" {
  policy = "read"
}
key "" {
  policy = "read"
}

Master:
(null)

Agent:
node "" {
  policy = "write"
}
service "" {
  policy = "write"
}
key "" {
  policy = "read"
}

### Description of the Issue (and unexpected/desired result)
Linux agents work fine.
Windows agents will register the node into consul, but when attempting to register a service added as a .json file, wll error:

[ERR] consul: RPC failed to server blah: rpc error: rpc error: Permission denied
[WARN] agent: Service 'server:service:port' registration blocked by ACLs

Should be noted that nodes update and remove fine.  Everything works as expected under Linux.  The error only exists for service registration with Windows.

**Comment by slackpad** [comment]
Hi @Justin-DynamicD that's pretty odd for a Windows-specific difference with ACLs. Can you provide a little more detail on how you are configuring your tokens? Are you configuring an agent token or putting the tokens into your JSON files along with the service?

**Comment by Justin-DynamicD** [comment]
for now putting tokens into the json file.  I'm planning on moving onto something more advanced once the intial security is tested/proved.

**Comment by Justin-DynamicD** [comment]
so for windows i have two jsons (done because for windows we use puppet to manage the files).  omiting the first one as it declares the token:

{"service":{"checks":[],"enableTagOverride":false,"id":"server:wmi-exporter:9182","name":"wmi-exporter","port":9182,"tags":["exporter"]}}

If you couldn't guess this registers an exporter for Prometheus.

**Comment by slackpad** [comment]
Ah ok so you aren't putting the token in the service JSON - are you configuring the agent with a token using https://www.consul.io/docs/agent/options.html#acl_token in its config JSON files?

**Comment by Justin-DynamicD** [comment]
So with a a little redaction, the _other_ file looks like this:

{"acl_agent_token":"redacted-but-i-put-my-acl-here","bind_addr":"10.10.12.51","datacenter":"redacted","encrypt":"redacted","encrypt_verify_incoming":true,"encrypt_verify_outgoing":true,"leave_on_terminate":true,"log_level":"INFO","retry_join":["my","three","servers"],"server":false}

**Comment by Justin-DynamicD** [comment]
I changed acl_agent_token to acl_token .... doesn't seem to make a difference, though it looks like I got that setting wrong.

**Comment by Justin-DynamicD** [comment]
OK so I guess it's a case of "RTFM".

Looking at your link more carefully:
```acl_datacenter - This designates the datacenter which is authoritative for ACL information. It must be provided to enable ACLs. All servers and datacenters must agree on the ACL datacenter. Setting it on the servers is all you need for cluster-level enforcement, but for the APIs to forward properly from the clients, it must be set on them too. In Consul 0.8 and later, this also enables agent-level enforcement of ACLs```

so setting acl-datacenter enabled the expected behavior

**Comment by Justin-DynamicD** [comment]
thank you so much for the guidance while I fumbled through this.

**Comment by slackpad** [comment]
No problem - glad you figured it out!
