### ISSUE TITLE
Terraform Module doesn't pull shared scripts

### ISSUE THREAD

**Issue by 2stacks** [hashicorp/consul#3518]
### Operating system and Environment details
Terraform v0.10.6 for Linux 64-bit

### Description of the Issue (and unexpected/desired result)
When using Consul module in Terraform shared scripts are not downloaded when executing 'terraform get'

### Reproduction steps

- add following to terraform config
```
module "consul" {
  source = "github.com/hashicorp/consul/terraform/aws"
  key_name = "KEY"
  key_path = "PATH"
  region   = "us-east-1"
  servers  = "3"
}
```

- Then execute
`terraform get`

- Verify shared scripts directory is missing
`ls -al ~/_INSTALL_PATH_/.terraform/modules/`

- Execute
`terraform apply`

>Error
>
>applying plan:
>
>1 error(s) occurred:
>
>* module.consul.aws_instance.server[0]: 1 error(s) occurred:
>
>* stat /Error applying plan:
>
>1 error(s) occurred:
>
>* module.consul.aws_instance.server[0]: 1 error(s) occurred:
>
>* stat >/_INSTALL_PATH_/modules/.terraform/modules/d830198f4c1a516c9c8db169096cddd5/../shared/scripts/debian_upstart.conf: no such file or directory
>
>Terraform does not automatically rollback in the face of errors.
>Instead, your Terraform state file has been partially updated with
>any resources that successfully completed. Please address the error
>above and apply again to incrementally change your infrastructure.

### Workaround

- Create Directories 
```
mkdir /_INSTALL_PATH_/.terraform/modules/shared
mkdir /_INSTALL_PATH_/.terraform/modules/shared/scripts
```

- Download missing scripts

```
cd /_INSTALL_PATH_/.terraform/modules/shared/scripts
wget https://raw.githubusercontent.com/hashicorp/consul/master/terraform/shared/scripts/install.sh
wget https://raw.githubusercontent.com/hashicorp/consul/master/terraform/shared/scripts/service.sh
wget https://raw.githubusercontent.com/hashicorp/consul/master/terraform/shared/scripts/ip_tables.sh
wget https://raw.githubusercontent.com/hashicorp/consul/master/terraform/shared/scripts/rhel_consul.service
wget https://raw.githubusercontent.com/hashicorp/consul/master/terraform/shared/scripts/rhel_upstart.conf
```

**Comment by kennethmyers** [comment]
Ran into the same issue. Made a pull request here: https://github.com/hashicorp/consul/pull/3527

**Comment by kennethmyers** [comment]
I was able to reproduce this issue.

Also, this issue breaks the module section of the Terraform tutorial which uses the Consul Terraform module provided in this repository as an example. See https://www.terraform.io/intro/getting-started/modules.html#using-modules

**Comment by pearkes** [comment]
I'm actually looking into migrating our modules in the repository to the [Terraform Module Registry](https://registry.terraform.io/) and then marking them as deprecated as we don't intend to continue maintaining them, but that would move them out of git and give a place for folks to migrate to if they are relying on them today.

**Comment by pearkes** [comment]
As noted above we've removed our modules from this repository. Did not end up migrating them, but the source is still available in Git.
