### ISSUE TITLE
Don't  deregister on critical service 

### ISSUE THREAD

**Issue by gabrielfsousa** [hashicorp/consul#3520]
Consul v0.9.3 - only server mode
docker - alpine

consul Don't  deregister a service on critical

**Comment by slackpad** [comment]
Hi @gabrielfsousa you have to configure that when you define the health check (see https://www.consul.io/docs/agent/checks.html):

> In Consul 0.7 and later, checks that are associated with a service may also contain an optional `deregister_critical_service_after field`, which is a timeout in the same Go time format as `interval` and `ttl`. If a check is in the critical state for more than this configured value, then its associated service (and all of its associated checks) will automatically be deregistered. The minimum timeout is 1 minute, and the process that reaps critical services runs every 30 seconds, so it may take slightly longer than the configured timeout to trigger the deregistration. This should generally be configured with a timeout that's much, much longer than any expected recoverable outage for the given service.

**Comment by gabrielfsousa** [comment]
thanks a lot, 
and when i'm using spring ?
what option is am yml file?

**Comment by slackpad** [comment]
Unfortunately I'm not sure about how Spring integrates with this, so you may want to check with that project directly.

**Comment by jiangxiaoqiang** [comment]
> Hi @gabrielfsousa you have to configure that when you define the health check (see https://www.consul.io/docs/agent/checks.html):
> 
> > In Consul 0.7 and later, checks that are associated with a service may also contain an optional `deregister_critical_service_after field`, which is a timeout in the same Go time format as `interval` and `ttl`. If a check is in the critical state for more than this configured value, then its associated service (and all of its associated checks) will automatically be deregistered. The minimum timeout is 1 minute, and the process that reaps critical services runs every 30 seconds, so it may take slightly longer than the configured timeout to trigger the deregistration. This should generally be configured with a timeout that's much, much longer than any expected recoverable outage for the given service.

how to use this config? I am doing like this but seems did not work as expect: https://stackoverflow.com/questions/69007497/how-to-deregister-the-service-in-consul-when-using-spring-could-consul
