### ISSUE TITLE
Make template renderer temp file configurable

### ISSUE THREAD

**Issue by maxenglander** [hashicorp/consul#3522]
Right now, when a template is rendered to disk, a temp file is first created in the parent directory of the "destination", before it is moved into place.

This is great, except when the `consul-template` process doesn't have permissions to create new files in the parent directory. Certainly, I could change the mode of the parent directory, but ideally I would like to be able to give the `consul-template` process only the permissions needed to write to the "destination".

I'd like to propose making the temporary directory where the template is rendered configurable, perhaps via a "template_directory" configuration variable, which defaults to the parent directory of the "destination" (current behavior), but can be overridden to simply write to "/tmp", in cases such as this one.

**Comment by slackpad** [comment]
Hi @maxenglander sorry for the late reply (there's a separate repo for consul-template). You should be able to use the `TMPDIR` environment variable to set this - https://golang.org/pkg/os/#TempDir.

**Comment by vvicaretti** [comment]
`TMPDIR` that doesn't seems to do the trick

**Comment by monitoring-aparavi** [comment]
Same for me, doesn't work
