### ISSUE TITLE
Consul don't elect leader after k8s resizing.

### ISSUE THREAD

**Issue by IgorGerasimov** [hashicorp/consul#3525]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `0.9.3 and 0.9.2`
Server: `0.9.3 and 0.9.2`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Operating system and Environment details
Kubernetes 1.7.3, Helm 2.6.0

### Description of the Issue (and unexpected/desired result)
After auto resizing cluster size from 2 to 3 nodes, consul could not elect leader.
Tried to reinstall it with https://github.com/kubernetes/charts/tree/master/stable/consul - but without result.
 

### Reproduction steps
Resize k8s cluster to 3 and back to 2 nodes - profit.

### Log Fragments or Link to [gist](https://gist.github.com/)
https://gist.github.com/IgorGerasimov/bc845f892be968c9774f915baf13a7f9

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by simisoz** [comment]
Check this maybe it will help.
http://www.devoperandi.com/cluster-consul-using-kubernetes-api/

**Comment by slackpad** [comment]
Hi @IgorGerasimov the link from @simisoz looks helpful. It looks like there was a problem doing the initial join, so that server wasn't able to be added to the existing cluster. The link has an example that passes in the pod IPs to join. There are a number of recent options for [retry-join](https://www.consul.io/docs/agent/options.html#retry-join) that can also help here. Hope that helps!
