### ISSUE TITLE
Stabilize the /v1/agent/self "Config" output

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3530]
The `Config` sub-key has always just been a dump of an internal structure, so it hasn't been stable. We need to look internally and externally (https://github.com/hashicorp/nomad/issues/3324) on places that depend on fields here and make a small, stable set of fields under `Config` that we document:

* `NodeName string`
* `Datacenter string`
* `Revision string`
* `Server bool`
* `Version string`

These are sourced from:

* https://github.com/hashicorp/nomad/blob/master/client/fingerprint/consul.go#L68-L72
* https://github.com/hashicorp/consul/blob/master/api/agent.go#L215
* https://github.com/hashicorp/consul/blob/master/command/exec.go#L193-L201
* https://github.com/hashicorp/consul/blob/master/command/rtt.go#L84

This test will be broken and needs an update - https://github.com/hashicorp/consul/blob/master/api/agent_test.go#L640-L647.

We should move the existing `Config` contents to `DebugConfig` and document that this is for debugging use only and is subject to change.

Once this is complete, we need to open a PR against https://github.com/terraform-providers/terraform-provider-consul/blob/master/consul/data_source_consul_agent_self.go that removes unsupported fields and notes that this data source will be deprecated in a future release of the provider.

**Comment by magiconair** [comment]
* https://github.com/hashicorp/nomad/blob/master/client/fingerprint/consul.go#L68-L72: `Datacenter`, `NodeName`, `Revision`, `Version`
* https://github.com/hashicorp/consul/blob/master/api/agent.go#L215: `NodeName`
* https://github.com/hashicorp/consul/blob/master/command/exec.go#L193-L201: `Datacenter`, `NodeName`
* https://github.com/hashicorp/consul/blob/master/command/rtt.go#L84: `Datacenter`, `NodeName`
