### ISSUE TITLE
Support specifying Consul gossip encryption key in agents via the environment

### ISSUE THREAD

**Issue by DavidHuie** [hashicorp/consul#3544]
Currently, Consul only supports specifying the gossip key in agents with the `-encrypt` CLI parameter. In certain environments, such as in Kubernetes, secret management is incompatible with CLI flags. However, secrets can be injected easily into application configs as either environment variables or files (specifying the encryption secret as a file is another option).

**Comment by slackpad** [comment]
Hi @DavidHuie thanks for opening an issue. Would you see any issue if we added an API-driven way to do this, similar to how we support setting ACL tokens (see https://www.consul.io/api/agent.html#update-acl-tokens)?

**Comment by DavidHuie** [comment]
@slackpad that's still not a perfect solution since we would have to create a mechanism to tie into the life-cycle of the Consul agent, which Kubernetes does not model perfectly.

**Comment by jsosulska** [comment]
Closing this issue as this is solved in a few different ways.
The [Consul-helm](https://www.consul.io/docs/k8s/helm) chart has support for passing in Gossip settings for servers and clients.
Consul also supports defining the encrypt option in the [configuration file](https://www.consul.io/docs/agent/options#encrypt-1).
Hope this helps!
