### ISSUE TITLE
Barrier write timeout can cause permanently degraded leader

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3545]
We encountered a user where the Consul leader ran into a network issue that lasted several minutes. Over the span of about 20 minutes there were errors queueing writes, with messages like `consul.coordinate: Batch update failed: timed out enqueuing operation`. Finally, one of these happened during a leader reconcile loop and we saw `consul: failed to wait for barrier: timed out enqueuing operation`.

Since the leader had been established for several days, this hit the `return` statement in the error handling logic here:

https://github.com/hashicorp/consul/blob/v1.0.0-beta2/agent/consul/leader.go#L97-L101

Which hit the `defer`-ed `revokeLeadership()` call here:

https://github.com/hashicorp/consul/blob/v1.0.0-beta2/agent/consul/leader.go#L111-L116

The result was that the leader loop exited and that the consistent read flag got reset, resulting in the application getting `Not ready to serve consistent reads`. Since the server never actually lost leadership it was stuck in this state. Restarting the leader fixed it. This was found in 0.9.2, but the code is the same in master today.

The change that added the `return` was #3230, which was working under the assumption that exiting the leader loop would cause the server to step down. In this unfortunate set of circumstances, the network errors were such that we hit the barrier write error, but we were able to service the Raft requirements to stay a leader. This is a bit of a manifestation of the separate path for pipelined Raft replication + a separate path for AE messages for maintaining leadership (I think), so that stems from our implementation.

In any case, the right thing to do here is to keep the timeout part of the deadlock fix from #3230, but do the old `goto WAIT` instead of the `return`. This would have let the leader make another attempt at the barrier later, and would have kept the leader tracking goroutine.

There's no good API now to ask Raft to step down, so later we might want to consider adding that, and if the leader tracking goroutine hasn't made progress then we could voluntarily step down, but the simple fix outlined above should be sufficient to defer to Raft's health checking. There are no other `return` statements of this type in `leaderLoop()`.

**Comment by cshabi** [comment]
HI Guys,

I would like to upgrade my 0.7.5 cluster to version 0.9.3.
Is it possible to create a separate package for that version with a fix for this bug?

**Comment by slackpad** [comment]
Hi @cshabi we don't have plans to backport this fix, so you'd need to cherry pick it into a local branch and build Consul.
