### ISSUE TITLE
Fix handling of long hostnames in the UI

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/consul#3556]
### `consul version`

`Consul v1.0.0-beta2`

Reproduced @ MacOS `10.12.6`:
 - Chrome Version `60.0.3112.113 (Official Build) (64-bit)`
 - Safari Version `11.0 (12604.1.38.1.7)`
 - Firefox Version `55.0.3 (64-bit)`

![screen shot 2017-10-09 at 14 50 53](https://user-images.githubusercontent.com/287584/31341424-5125deb8-ad01-11e7-83e7-f96b7958928d.png)

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
