### ISSUE TITLE
API for reading multiple keys at once

### ISSUE THREAD

**Issue by grosser** [hashicorp/consul#3558]
We are trying to read 10+ different KV-Store keys when our service starts ... atm that means 10 requests ... would be nice to have a read-multi api.

```
keys[]=foo&keys[]=bar
->
{
 "foo": {result},
  "bar": {result}
}
```

**Comment by slackpad** [comment]
Hi @grosser the transaction API can get 10 keys in one go - https://www.consul.io/api/txn.html.

**Comment by grosser** [comment]
that'll do, thx! :D 
some way to find that via the docs would be neat ... like linking under "Read Key" on https://www.consul.io/api/kv.html

**Comment by slackpad** [comment]
Added a note to the docs!
