### ISSUE TITLE
Add new /v1/health/nodes endpoint

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#356]
See #355. We should have a health endpoint that just lists all the nodes. Otherwise it is difficult to just watch for the "healthy" nodes. Integrate with nodes watch.

**Comment by doublerebel** [comment]
:+1:

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue. There hasn't been a lot of demand for this functionality, so we are going to close out this issue. We would still gladly review a PR for it though! Thanks and sorry!
