### ISSUE TITLE
Feature request: TTL for script based checks

### ISSUE THREAD

**Issue by nh2** [hashicorp/consul#3563]
Currently [script](https://www.consul.io/docs/agent/checks.html) based checks keep their status (e.g. passing) until the script is run the next time.

This creates two problems:

* When a check is passing and then consul reboots reboots, e.g. as part of the reboot of a whole cluster of machines, it reports the script checks as passing even though the thing they track might be down. In other words, consul reports a thing as up even though it might not have checked in a long time if that is the case. Eample: In my case, I'm tracking whether a GlusterFS volume is up by using `gluster volume status`, and when I reboot all machines including consul machines, the check and associated service is marked as passing, and other machines try to mount the volume even though it's down (because consul tells them that it's still up).
* When a check takes a long time to complete, e.g. is stuck due to some network hang (for up to 3600 seconds according to many OSs default TCP parameters), the service retains its current status (e.g. passing) for a long time.

It would be great if script checks could be given an optional TTL field, that would similar to the TTL check itself: If the TTL expires since the last script check completed, mark the service as failed.

**Comment by nh2** [comment]
I should also mention, you can already specify a `timeout` on script checks to prevent them running forever to solve most of the second point, but this is a harder constraint and it would actually terminate the check.
For example, if you run a check 60 seconds with a timeout of 30 seconds, and had a TTL feature for scripts set to 120 seconds, and your script would take 20 seconds, then you would have a downtime of only 5 seconds for the service (as the check succeeding 5 seconds after the TTL expires will set the service to passing and refresh the TTL).
If you set the timeout to 15 seconds instead, the script would be aborted, and you'd have to wait for the next check to come around a minute later, causing a downtime of > 45 seconds for the service.

**Comment by nh2** [comment]
Wait, does `timeout` actually kill the script?

I thought it did, but if I put a long running thing into the script, it seems to run just beyond its timeout and I have processes accumulating?

**Comment by slackpad** [comment]
> Wait, does `timeout` actually kill the script?

That was added in 1.0.

**Comment by david-yu** [comment]
Closing as this not planned. Script based checks are also somewhat problematic due to security issues that may arise from running scripts.
