### ISSUE TITLE
KV behavior inconsistent between keys/recurse/separator

### ISSUE THREAD

**Issue by benfleis** [hashicorp/consul#357]
I have a keyspace of `/foo/bar`, with `bar` having a value `baz`.  Like an `ls` command, I want to know the children of `foo`, but not necessarily the children's children.  A straight up `GET` doesn't work, while using  `?keys` does.  This is behaviourally inconsistent, as the docs for `keys` ambiguously state:

> It is possible to also only list keys without their values by using the "?keys" query parameter along with a GET request.

Which suggests to me (as would also be my intuition), that calling _without_ `keys` should return the "direct" key subset, and with `keys` is as explicitly promised.

I understand that I can also achieve this via `?recurse&separator=/`, but it feels strange to ask for, and then expressly limit, recursion, when a natural operation, with or without `&keys` feels right.

A simple curl log is pasted below to demonstrate.  (And edited to add visual whitespace.)  To be 100% clear, I would expect the 2nd query (/kv/foo/, without args) to return the same thing as the last.

``` bash
core@dev /opt/sbin $ curl -XPUT --url "http://localhost:8500/v1/kv/foo/bar" -d "baz"
true
core@dev /opt/sbin $ curl -XGET --url "http://localhost:8500/v1/kv/foo/bar"
[{"CreateIndex":53,"ModifyIndex":53,"LockIndex":0,"Key":"foo/bar","Flags":0,"Value":"YmF6"}]
core@dev /opt/sbin $ curl -XGET --url "http://localhost:8500/v1/kv/foo/"
core@dev /opt/sbin $ curl -XGET --url "http://localhost:8500/v1/kv/foo/?keys"
["foo/bar"]
core@dev /opt/sbin $ curl -XGET --url "http://localhost:8500/v1/kv/foo/?recurse"
[{"CreateIndex":53,"ModifyIndex":53,"LockIndex":0,"Key":"foo/bar","Flags":0,"Value":"YmF6"}]
core@dev /opt/sbin $ curl -XGET --url "http://localhost:8500/v1/kv/foo/?recurse&separator=/"
[{"CreateIndex":53,"ModifyIndex":53,"LockIndex":0,"Key":"foo/bar","Flags":0,"Value":"YmF6"}]
```

**Comment by jalaziz** [comment]
Any update on this? Seems odd that the `&key` supports `&separator` for limiting, but  `&recurse` doesn't.

**Comment by rocktavious** [comment]
+1 on adding `&separator` to `&recurse` - i would like to use this functionality too

**Comment by SH4DY** [comment]
Any news on this enhancement? Trying to GET only direct children. This would perform much better compared to retrieving all key-names of a node and then GET every node individually or as a txn.

**Comment by godefroi** [comment]
Late to the game, but as an inexperienced user, there are several behaviors here that feel strange:

- Recursion is on by default when specifying ?keys. This isn't the default in, for example, `ls`, and it feels unnatural here.
- When using ?keys, &recurse=false doesn't do anything. Given that recursion is on by default, this would be the most obvious way to turn it off.
- When using ?keys, recursion is turned off with &separator=/. This option isn't really clearly documented (what does it do, really?), and it's not obvious at all that this is how one would turn off recursion.

**Comment by nicolasgarnil** [comment]
@godefroi great explanation!
BTW, do you know if it is possible to select a subset of keys instead of an entire subtree?

**Comment by godefroi** [comment]
@nicolasgarnil I don't know, but I suspect not.

**Comment by i0rek** [comment]
Thank you for reporting! I understand that this behaviour is a a little confusing and the functionality is not fully fleshed out.
Right now our focus are on other areas of Consul and we don't have time to work on improving these APIs. I would be happy to review a PR if someone wants to provide one, that implements adds this. Having that said I am closing this issue now because for us there is no positive side in keeping it open.

Thanks.
