### ISSUE TITLE
InsecureSkipVerify

### ISSUE THREAD

**Issue by meekrab** [hashicorp/consul#3575]
Server: latest

How do I write a config file which sets "InsecureSkipVerify"?

There is nothing in the docs related to this simple item.

**Comment by preetapan** [comment]
Set TLSSkipVerify (can be lowercased as well) - https://www.consul.io/api/agent/check.html#tlsskipverify 

In the upcoming Consul 1.0 release, it will also accept tls_skip_verify.

**Comment by meekrab** [comment]
Thank you @preetapan. 
I see it's in the Agent Check Registration and not in the configuration of consul. 
It works as expected.
