### ISSUE TITLE
Docker script checks flappiness

### ISSUE THREAD

**Issue by preetapan** [hashicorp/consul#3576]
Discovered when regression testing the 1.0 release. Docker script healthchecks sometimes fail with a `connection reset by peer` error which causes it to flap unnecessarily. 

Reproduction steps:
Create a service with a docker script healthcheck. For my testing, I used a ubuntu container and configured the check to run `ls -l \` as the check. 

Agent logs:
```
 2017/10/13 15:49:38 [WARN] agent: Check 'service:bar' is now critical
    2017/10/13 15:49:38 [INFO] agent: Synced check 'service:bar'
    2017/10/13 15:49:58 [INFO] agent: Synced check 'service:bar'
    2017/10/13 15:50:37 [WARN] agent: Check 'service:foo' is now critical
    2017/10/13 15:50:37 [INFO] agent: Synced check 'service:foo'
    2017/10/13 15:50:57 [INFO] agent: Synced check 'service:foo'
    2017/10/13 15:51:37 [WARN] agent: Check 'service:foo' is now critical
```

Check output when it flaps to critical above: 
```
 "service:foo": {
    "Node": "preetha-work",
    "CheckID": "service:foo",
    "Name": "bar",
    "Status": "critical",
    "Notes": "",
    "Output": "start exec failed for container cefd3f7f5cd4: read unix @->/var/run/docker.sock: read: connection reset by peer",
    "ServiceID": "foo",
    "ServiceName": "foo",
    "ServiceTags": [],
    "CreateIndex": 0,
    "ModifyIndex": 0
  }
```

It seems to happen every few minutes and recover on its own, and then happen again. Needs further investigation.

**Comment by VMitov** [comment]
Any news on this? I experience the same issue?

**Comment by magiconair** [comment]
I can have a look at this one.

**Comment by magiconair** [comment]
Hmm, I cannot reproduce this. Here is what I did:

```
# pull ubuntu
docker pull ubuntu

# run ubuntu container
docker run -it ubuntu

# get docker container id
docker ps # get id of ubuntu container
# or run docker ps -f ancestor=ubuntu --format '{{.ID}}'

# run consul
~/consul-1.0.0/consul agent -dev -enable-script-checks

# register check
curl -v -XPUT -d '{"id":"foo", "name":"foo", "interval": "1s", "docker_container_id":"db9f738b1128", "script": "/bin/ls -l", "shell":"/bin/sh"}' localhost:8500/v1/agent/check/register

# watch output of consul for 'critical'
```

The test doesn't go critical.

**Comment by magiconair** [comment]
@preetapan is going to see whether she can still reproduce this and then provide me with the exact versions. I'm running docker on macOS so there may be a difference.

**Comment by magiconair** [comment]
I can reproduce this now on Linux with both Docker 17.03.1-ce and 17.09.1-ce and consul 1.0.0

**Comment by VMitov** [comment]
```
> docker version 
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:05:05 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:03:46 2017
 OS/Arch:      linux/amd64
 Experimental: false

> docker images | grep consul
consul                        latest              286d9c6a79b2        9 days ago          51.8MB
```

**Comment by magiconair** [comment]
I've pushed a PR which mitigates the problem although I don't fully understand it at this point. I don't see that behavior with docker on macOS for example.

**Comment by VMitov** [comment]
I'm testing this flappiness with my services and the issue indeed look fixed but I'm seeing something strange in the output of the check
`8Status: OK
`
Any idea what could be causing this?

**Comment by magiconair** [comment]
@VMitov First check if your server is sending that with a `tcpdump`. This could be a fall out from the closed connection. Does this happen every time?

**Comment by VMitov** [comment]
Yeah, it happens all the time - different artifact for different services but always the same for particular service.

**Comment by VMitov** [comment]
Also, it is not happening for 1.0.0.

**Comment by VMitov** [comment]
It's not cumming from my applications. It is something from the way docker exec works:
```
❯ curl --unix-socket /var/run/docker.sock -XPOST -d '{ "AttachStdin": false, "AttachStdout": true, "AttachStderr": false, "Cmd": ["sh", "-c", "ls"], "Tty": true }' -H "Content-Type: application/json" http:/v1.33/containers/2b504b972542/exec
{"Id":"8722ab518dba46d506c340a3d8bb909ef81e969535538cbb2849bf7867887cab"}
❯ curl --unix-socket /var/run/docker.sock -XPOST -d '{ "Detach": false, "Tty": false }' -H "Content-Type: application/json" http:/v1.33/exec/8722ab518dba46d506c340a3d8bb909ef81e969535538cbb2849bf7867887cab/start
zapp        endpoints  lib        proc       sbin       tmp
bin        etc        media      root       srv        usr
dev        home       mnt        run        sys        var
```

And this is happening because of this change https://github.com/hashicorp/consul/pull/3621/commits/94726ef105fc7feebced2f5e9fc0535046a05073. 

Any thoughts?

**Comment by VMitov** [comment]
Do you want me to open new issue for that?

**Comment by preetapan** [comment]
@VMitov I have set tty back to true again in master, that was an auxillary change for this issue anyway. Do you mind retesting your apps with master and see if those strange characters go away? TIA.

**Comment by VMitov** [comment]
Thanks @preetapan! I already tested it before raising the issue and it is OK. I wasn't sure why tty was false in the first place so I wasn't sure if changing it back is the proper solution. I'll retest once more tomorrow with the latest master just to be sire. Thanks again!

**Comment by VMitov** [comment]
I retested it and it's working as expected.
