### ISSUE TITLE
Agent-side ACL resolution will not use replicated ACL data

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3583]
Capturing an issue from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/icsiIyD8b0I/DMyMH-ctDAAJ.

When an agent is resolving ACL policies (such as in agent_endpoint.go), it always marks requests for the `acl_datacenter`, which means that if that's offline they will just fail. It won't try to get the results from the servers in its own datacenter, which might have replicated data.

We could probably do something up in the servers around the forwarding code for `ACL.GetPolicy` in order to fix this without requiring any changes to the agent side.

**Comment by chemicL** [comment]
Also, please consider the agents in the `acl_datacenter`, which could continue resolving policies via a non-local datacenter. This will reduce latency, however only for the time it takes to cache them locally, which still is more secure than switching `acl_down_policy` from `extend_cache` to `allow`.

**Comment by mkeeler** [comment]
Going to close this as all of the token resolution logic has been rewritten. There will be an internals doc to go over exactly hows its all done but in short, when running in the new ACL mode (non-legacy mode) and when resolving a token, client agents will always send requests to the servers in the local datacenter and those servers will forward the request if they cannot service them such as when token replication is not enabled.
