### ISSUE TITLE
Consul validate fails on the part of the configs

### ISSUE THREAD

**Issue by 123BLiN** [hashicorp/consul#3591]
### `consul version` for both Client and Server
Client: `1.0.0`
Server: `1.0.0`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 4
        check_ttls = 0
        checks = 4
        services = 2
build:
        prerelease =
        revision = 51ea240
        version = 1.0.0
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 9847
        max_procs = 4
        os = linux
        version = go1.9.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 619
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 3
        member_time = 1663
        members = 16
        query_queue = 0
        query_time = 1

```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 1
        checks = 1
        services = 1
build:
        prerelease =
        revision = 51ea240
        version = 1.0.0
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.11.51.88:8300
        server = true
raft:
        applied_index = 254138899
        commit_index = 254138899
        fsm_pending = 0
        last_contact = 23.805µs
        last_log_index = 254138900
        last_log_term = 47305
        last_snapshot_index = 254135347
        last_snapshot_term = 47305
        latest_configuration = [{Suffrage:Voter ID:12bad362-68b1-4e9e-8847-ce521c575448 Address:10.11.51.88:8300} {Suffrage:Voter ID:f01b52bb-4278-42b8-9a48-391e3f0c91f2 Address:10.11.44.50:8300} {Suffrage:Voter ID:fcc8842c-7061-4b67-897f-18abf0b0ea18 Address:10.11.51.201:8300}]
        latest_configuration_index = 252968109
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 47305
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 5263
        max_procs = 2
        os = linux
        version = go1.9.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 619
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 3
        member_time = 1663
        members = 16
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 32
        members = 3
        query_queue = 0
        query_time = 1

```

### Operating system and Environment details
Centos 7 and Windows 2012R2
### Description of the Issue (and unexpected/desired result)
New consul validate option fails for separate config file (health check) but works for config-dir 
### Reproduction steps
```
C:\Windows\system32>consul validate e:\ISApps\consul\config\service1.json
Config validation failed: data_dir cannot be empty
```
or
```
# consul validate /etc/consul/conf.d/
Config validation failed: Multiple private IPv4 addresses found. Please configure one
# consul validate /etc/consul/
Configuration is valid!
```
Possibly can be related to the https://github.com/hashicorp/consul/pull/3480

Thanks,
Roman

**Comment by slackpad** [comment]
Hi @123BLiN this is a bit of a weird one - with the config parsing changes `consul validate` is doing exactly what the agent would do, including a lot more of the dynamic stuff like IP address determination, and other validation like the data dir not being empty. Before it was more of a structural parse with a few checks. This is a problem if your config isn't complete, such as if you are passing some things along with CLI flags to the agent as well.

This might be a little more friendly to use if we supplied validate with a base config that had a few basic things set like a fake data-dir, bind address, and client address, but that might leave some things to be found later once the agent starts. @magiconair any thoughts on a good way forward with this one?

**Comment by magiconair** [comment]
This depends on what `consul validate` is supposed to do. If it is only doing syntactical or also semantical validation. Does it validate a configuration or fragments?

If the previous version was only doing syntactical checks then we need to stop after parsing.

**Comment by slackpad** [comment]
Looks like it was just syntax before, so we probably should just stop after parsing - https://github.com/hashicorp/consul/blob/v0.9.3/agent/config.go#L2174-L2246. It was never precisely defined in the description of this command.

**Comment by magiconair** [comment]
`ReadConfigPaths` calls `DecodeConfig` which does more than syntactical validation. It also verifies most (but not all) ip addresses, handles some (but not all) deprecations and evaluates the go-sockaddr templates:

https://github.com/hashicorp/consul/blob/v0.9.3/agent/config.go#L1139-L1494

We could add more pre-flight checks before the build step which `validate` could use but they would duplicate checks that are done later which can lead to other errors since we then need to ensure that they both test the same thing in the same way, e.g. `bind` being just an ip without a port.

What is the expectation on how this should work? @123BLiN maybe you can shed some light on this as well.

**Comment by 123BLiN** [comment]
Hi,

We use this feature to validate service deploy step, so we point consul validate to the concrete service/check config file to ensure that it was deployed properly, but our main consul agent configuration is placed in default.json configuration file.

I can not say that this isue is critical for us as we can call consul validate for the whole directory and it is pretty fast. 

Hope this helps,
Thanks!

**Comment by slackpad** [comment]
It sounds like the 1.0 strict behavior is the best thing then, and we
should just update the documentation.

I had always assumed that this could run on fragments of config but that's
more by accident than a planned feature it seems if the old command was
doing some subset of verifications. Now we can document that it runs
exactly the same checks that the agent does.

**Comment by 123BLiN** [comment]
I would say that if you may have parts of configuration that depends on another parts for example service id in the health check definition and so on, and you want to be sure that your whole configuration is valid and will not fail on the next reboot - you need to check it all, like for example "nginx -t" does. 

So maybe we were using it wrong.

**Comment by slackpad** [comment]
> The other question then is do we need an directory or filename as a parameter at all?

This is the one thing you also need to supply to the agent in order to locate the config files, so I think we need this at a minimum. Are you thinking it would look in the current working directory?

**Comment by zenina** [comment]
In Linux, I was able to workaround this issue by passing 

`--data-dir /path/to/datadir `
in my upstart script/startup options. I presume consul is not parsing the option out of the config file correctly. 

`consul agent -data-dir /var/consul -config-dir /etc/consul.d/client`

You might try passing the explicit -data-dir flag to your startup options in Windows.
