### ISSUE TITLE
Local path for `consul validate` requires a leading `./` to work

### ISSUE THREAD

**Issue by jayed** [hashicorp/consul#3592]
### `consul version` for both Client and Server
Client: `Consul v0.9.3`

### Operating system and Environment details
FreeBSD 11.1-RELENG

### Description of the Issue (and unexpected/desired result)
`consul validate` fails to recognize local paths without a leading "./"

### Reproduction steps
`consul valdiate saltstack/consul-server/files/config.json` produces a Usage message.
`consul validate ./saltstack/consul-server/files/config.json` produces `Configuration is valid!`

**Comment by slackpad** [comment]
Hi @jayed I can't reproduce this. What message do you see for the first case (is there some error that's maybe accompanying that usage message)?

**Comment by jayed** [comment]
And I just tried it again. I'm a big fat liar. I must have fumble-fingered the initial directory which has multiple matches. Sorry to waste your time!

**Comment by slackpad** [comment]
np thanks for the update!
