### ISSUE TITLE
Incorrect babysitting of processes for Healthcheck with script

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#3597]
Consul does not handle well terminaison of child processes in "script" of Healthchecks when child processes do timeout.

### `consul version` for both Client and Server
Client: `0.9.3`
Server: `0.9.3`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 1
	check_ttls = 0
	checks = 3
	services = 4
build:
	prerelease =
	revision = 112c060
	version = 0.9.3
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 42
	max_procs = 2
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3658
	failed = 4
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 701773
	members = 747
	query_queue = 0
	query_time = 1927
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 2
	services = 4
build:
	prerelease =
	revision = 112c060
	version = 0.9.3
consul:
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = 10.251.1.96:8300
	server = true
raft:
	applied_index = 150825412
	commit_index = 150825412
	fsm_pending = 0
	last_contact = 35.642492ms
	last_log_index = 150825412
	last_log_term = 2838
	last_snapshot_index = 150823059
	last_snapshot_term = 2838
	latest_configuration = [{Suffrage:Voter ID:10.251.1.97:8300 Address:10.251.1.97:8300} {Suffrage:Voter ID:10.251.1.98:8300 Address:10.251.1.98:8300} {Suffrage:Voter ID:10.251.1.96:8300 Address:10.251.1.96:8300}]
	latest_configuration_index = 31168778
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2838
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 3438
	max_procs = 23
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3658
	failed = 235
	health_score = 0
	intent_queue = 1
	left = 3
	member_time = 701787
	members = 982
	query_queue = 0
	query_time = 1927
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6265
	members = 6
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

On Centos 6, Consul is not launched by systemd, thus its child processes are not in a CGroup.

### Description of the Issue (and unexpected/desired result)

When Consul uses a script to perform a healthcheck, it does not properly kill the child process, thus, if the process hangs, it will accumulate stuck processes leading to Consul's death.

On our system, the check was the following:
```
nc -u 127.0.0.1 53 <<< ''
```

This script never ends, thus nc instances accumulates until consul dies.

The behaviour should be the following:

after the timeout of the command (or if not specified, when the next scheduling of command is launched, Consul should send a TERM signal to the child process and if the child process does not end, a SIGKILL.

### Reproduction steps

Create a healthcheck run every 10 seconds with blocking script, e.g:

```
{
  "script": "nc -u 127.0.0.1 53 <<< ''"
  "interval": "10s"
  [...]
}
```

This behavior is more dangerous on initv systems and less visible on systemd systems since systemd will kill the whole tree of processes -> thus when consul is killed, script childs will be destroyed and consul will be able to restart, but the bug exists on both systems.

**Comment by slackpad** [comment]
Hi @pierresouchay thanks for the report. This was fixed in Consul 1.0 under #2999, specifically #3509. We ended up not doing a term + wait + kill, but instead killing the whole process tree outright, since that was simpler and the timeout is already configurable.
