### ISSUE TITLE
/v1/status/peers does not return anything on 1.0.0 servers when mixed with 0.7.5

### ISSUE THREAD

**Issue by vchan2002** [hashicorp/consul#3608]
I have a set of consul servers set as 0.7.5.  I have bootstrapped two additional servers at 1.0.0, hoping to basically transition the new servers in and transition the old servers out.  The servers appeared to have bootstrapped properly.

For some reason, however, it seems that the /v1/status/peers endpoint returns nothing when I try it on 1.0.0, but it returns all five peers (0.7.5 and 1.0.0) when i'm on the 0.7.5 servers.

### `consul version` for both Client and Server
Server: 1.0.0

### Operating system and Environment details
Amazon Linux

### Reproduction steps
so... here's the output...
on 0.7.5 servers
curl http://10.0.254.157:8500/v1/status/peers
["10.0.254.157:8300","10.0.254.63:8300","10.0.254.104:8300","10.0.254.167:8300","10.0.254.80:8300"]
on 1.0.0 servers
curl http://10.0.254.167:8500/v1/status/peers
[]

### Log Fragments or Link to [gist](https://gist.github.com/)

Nothing of note.....

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @vchan2002 you need to configure the 1.0 servers in a special way in order to interoperate with servers running 0.7.5 - please see https://www.consul.io/docs/upgrade-specific.html#raft-protocol-now-defaults-to-3 for details.
