### ISSUE TITLE
Single node Consul cluster won't start after upgrade to 1.0.0

### ISSUE THREAD

**Issue by drabo** [hashicorp/consul#3614]
Hi,
I have a test cluster with one node that worked with Consul version 0.9.3 perfectly fine. It is used as backed for Vault that is running on the same machine.
The system configuration was tested as Centos 7 virtual machine in Virtualbox and also as RHEL 7 server in AWS.
After the upgrade to 1.0.0 it won't start as no leader can be elected.

Is there a way to force leadership without losing it in such single nod cluster?

The config file is following:
{
    "bind_addr": "192.168.56.130",
    "server": true,
    "bootstrap": true,
    "datacenter": "loco",
    "data_dir": "/opt/consul/data",
    "encrypt": "/W5SWUpXb1pw1CrOjJw/Fg==",
    "log_level": "TRACE",
    "enable_syslog": true,
    "enable_debug": true,
    "leave_on_terminate": false,
    "skip_leave_on_interrupt": true,
    "rejoin_after_leave": true,
    "retry_interval": "30s",
    "retry_join": [ "192.168.56.130" ],
    "disable_update_check": true,
    "ui": true
}

### `consul version` for both Client and Server
Client: `Consul v1.0.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
`
Server: `Consul v1.0.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 51ea240
	version = 1.0.0
consul:
	bootstrap = true
	known_datacenters = 1
	leader = false
	leader_addr = 
	server = true
raft:
	applied_index = 0
	commit_index = 0
	fsm_pending = 0
	last_contact = 195.740013ms
	last_log_index = 1286
	last_log_term = 207
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:192.168.56.130:8300 Address:192.168.56.130:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 207
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 72
	max_procs = 1
	os = linux
	version = go1.9.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 40
	event_time = 207
	failed = 0
	health_score = 0
	intent_queue = 1
	left = 0
	member_time = 24
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1

```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 51ea240
	version = 1.0.0
consul:
	bootstrap = true
	known_datacenters = 1
	leader = false
	leader_addr = 
	server = true
raft:
	applied_index = 0
	commit_index = 0
	fsm_pending = 0
	last_contact = 195.740013ms
	last_log_index = 1286
	last_log_term = 207
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:192.168.56.130:8300 Address:192.168.56.130:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 207
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 72
	max_procs = 1
	os = linux
	version = go1.9.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 40
	event_time = 207
	failed = 0
	health_score = 0
	intent_queue = 1
	left = 0
	member_time = 24
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
The system configuration was tested as Centos 7 virtual machine in Virtualbox and also as RHEL 7 server in AWS.

### Description of the Issue (and unexpected/desired result)
Test cluster with one node that worked with Consul version 0.9.3 perfectly fine. It is used as backed for Vault that is running on the same machine.
After the upgrade to 1.0.0 it won't start because is not able to elect the cluster leader.
In config file it was tested with both:
"bootstrap": true
and
"bootstrap_expect": 1

### Log Fragments or Link to [gist](https://gist.github.com/)

**The syslog before upgrade (ver 0.9.3), start consul:**
Oct 24 19:04:15 vault systemd: Starting Consul service...
Oct 24 19:04:16 vault consul: ==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
Oct 24 19:04:16 vault consul: ==> Starting Consul agent...
Oct 24 19:04:16 vault consul[14465]: raft: Initial configuration (index=1): [{Suffrage:Voter ID:192.168.56.130:8300 Address:192.168.56.130:8300}]
Oct 24 19:04:16 vault consul[14465]: raft: Node at 192.168.56.130:8300 [Follower] entering Follower state (Leader: "")
Oct 24 19:04:16 vault consul[14465]: serf: EventMemberJoin: vault.loco 192.168.56.130
Oct 24 19:04:16 vault consul[14465]: serf: EventMemberJoin: vault 192.168.56.130
Oct 24 19:04:16 vault consul[14465]: agent: Started DNS server 127.0.0.1:8600 (udp)
Oct 24 19:04:16 vault consul[14465]: consul: Adding LAN server vault (Addr: tcp/192.168.56.130:8300) (DC: loco)
Oct 24 19:04:16 vault consul: ==> Consul agent running!
Oct 24 19:04:16 vault consul: Version: 'v0.9.3'
Oct 24 19:04:16 vault consul: Node ID: 'c6543988-d654-0a08-efca-2e218f0fb04e'
Oct 24 19:04:16 vault consul: Node name: 'vault'
Oct 24 19:04:16 vault consul: Datacenter: 'loco' (Segment: '<all>')
Oct 24 19:04:16 vault consul: Server: true (Bootstrap: true)
Oct 24 19:04:16 vault consul: Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
Oct 24 19:04:16 vault consul: Cluster Addr: 192.168.56.130 (LAN: 8301, WAN: 8302)
Oct 24 19:04:16 vault consul: Encrypt: Gossip: true, TLS-Outgoing: false, TLS-Incoming: false
Oct 24 19:04:16 vault consul: ==> Log data will now stream in as it occurs:
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:192.168.56.130:8300 Address:192.168.56.130:8300}]
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] raft: Node at 192.168.56.130:8300 [Follower] entering Follower state (Leader: "")
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] serf: EventMemberJoin: vault.loco 192.168.56.130
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] serf: EventMemberJoin: vault 192.168.56.130
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] consul: Adding LAN server vault (Addr: tcp/192.168.56.130:8300) (DC: loco)
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] consul: Handled member-join event for server "vault.loco" in area "wan"
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] agent: Started HTTP server on 127.0.0.1:8500
Oct 24 19:04:16 vault consul[14465]: consul: Handled member-join event for server "vault.loco" in area "wan"
Oct 24 19:04:16 vault consul[14465]: agent: Started DNS server 127.0.0.1:8600 (tcp)
Oct 24 19:04:16 vault consul[14465]: agent: Started HTTP server on 127.0.0.1:8500
Oct 24 19:04:16 vault consul[14465]: agent: Retry join LAN is supported for: aws azure gce softlayer
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] agent: Retry join LAN is supported for: aws azure gce softlayer
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] agent: Joining LAN cluster...
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] agent: (LAN) joining: [192.168.56.130]
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] agent: (LAN) joined: 1 Err: <nil>
Oct 24 19:04:16 vault consul: 2017/10/24 19:04:16 [INFO] agent: Join LAN completed. Synced with 1 initial agents
Oct 24 19:04:16 vault consul[14465]: agent: Joining LAN cluster...
Oct 24 19:04:16 vault consul[14465]: agent: (LAN) joining: [192.168.56.130]
Oct 24 19:04:16 vault consul[14465]: agent: (LAN) joined: 1 Err: <nil>
Oct 24 19:04:16 vault consul[14465]: agent: Join LAN completed. Synced with 1 initial agents
Oct 24 19:04:23 vault consul[14465]: raft: Heartbeat timeout from "" reached, starting election
Oct 24 19:04:23 vault consul: 2017/10/24 19:04:23 [WARN] raft: Heartbeat timeout from "" reached, starting election
Oct 24 19:04:23 vault consul: 2017/10/24 19:04:23 [INFO] raft: Node at 192.168.56.130:8300 [Candidate] entering Candidate state in term 2
Oct 24 19:04:23 vault consul[14465]: raft: Node at 192.168.56.130:8300 [Candidate] entering Candidate state in term 2
Oct 24 19:04:23 vault consul[14465]: raft: Election won. Tally: 1
Oct 24 19:04:23 vault consul: 2017/10/24 19:04:23 [INFO] raft: Election won. Tally: 1
Oct 24 19:04:23 vault consul: 2017/10/24 19:04:23 [INFO] raft: Node at 192.168.56.130:8300 [Leader] entering Leader state
Oct 24 19:04:23 vault consul[14465]: raft: Node at 192.168.56.130:8300 [Leader] entering Leader state
Oct 24 19:04:23 vault consul[14465]: consul: cluster leadership acquired
Oct 24 19:04:23 vault consul: 2017/10/24 19:04:23 [INFO] consul: cluster leadership acquired
Oct 24 19:04:23 vault consul: 2017/10/24 19:04:23 [INFO] consul: New leader elected: vault
Oct 24 19:04:23 vault consul[14465]: consul: New leader elected: vault
Oct 24 19:04:23 vault consul[14465]: consul: member 'vault' joined, marking health alive
Oct 24 19:04:23 vault consul: 2017/10/24 19:04:23 [INFO] consul: member 'vault' joined, marking health alive
Oct 24 19:04:23 vault consul[14465]: agent: Synced node info
Oct 24 19:04:23 vault consul: 2017/10/24 19:04:23 [INFO] agent: Synced node info

**The syslog after upgrade (ver 1.0.0), start consul:**
Oct 25 16:45:08 vault consul[1242]: raft: Initial configuration (index=1): [{Suffrage:Voter ID:192.168.56.130:8300 Address:192.168.56.130:8300}]
Oct 25 16:45:08 vault consul[1242]: serf: EventMemberJoin: vault.loco 192.168.56.130
Oct 25 16:45:08 vault consul[1242]: serf: EventMemberJoin: vault 192.168.56.130
Oct 25 16:45:08 vault consul[1242]: agent: Started DNS server 127.0.0.1:8600 (udp)
Oct 25 16:45:08 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Follower] entering Follower state (Leader: "")
Oct 25 16:45:08 vault consul[1242]: serf: Failed to re-join any previously known node
Oct 25 16:45:08 vault consul[1242]: serf: Failed to re-join any previously known node
Oct 25 16:45:08 vault consul[1242]: consul: Adding LAN server vault (Addr: tcp/192.168.56.130:8300) (DC: loco)
Oct 25 16:45:08 vault consul[1242]: consul: Handled member-join event for server "vault.loco" in area "wan"
Oct 25 16:45:08 vault consul[1242]: agent: Started DNS server 127.0.0.1:8600 (tcp)
Oct 25 16:45:08 vault consul[1242]: agent: Started HTTP server on 127.0.0.1:8500 (tcp)
Oct 25 16:45:08 vault consul[1242]: agent: Retry join LAN is supported for: aws azure gce softlayer
Oct 25 16:45:08 vault consul[1242]: agent: Joining LAN cluster...
Oct 25 16:45:08 vault consul[1242]: agent: (LAN) joining: [192.168.56.130]
Oct 25 16:45:08 vault consul[1242]: memberlist: Initiating push/pull sync with: 192.168.56.130:8301
Oct 25 16:45:08 vault consul[1242]: memberlist: Stream connection from=192.168.56.130:57818
Oct 25 16:45:08 vault consul[1242]: agent: (LAN) joined: 1 Err: <nil>
Oct 25 16:45:08 vault consul[1242]: agent: systemd notify failed: No socket
Oct 25 16:45:08 vault consul[1242]: agent: Join LAN completed. Synced with 1 initial agents
Oct 25 16:45:15 vault consul[1242]: agent: failed to sync remote state: No cluster leader
Oct 25 16:45:16 vault consul[1242]: raft: Heartbeat timeout from "" reached, starting election
Oct 25 16:45:16 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Candidate] entering Candidate state in term 168
Oct 25 16:45:16 vault consul[1242]: raft: Votes needed: 1
Oct 25 16:45:16 vault consul[1242]: raft: Vote granted from 192.168.56.130:8300 in term 168. Tally: 1
Oct 25 16:45:16 vault consul[1242]: raft: Election won. Tally: 1
Oct 25 16:45:16 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Leader] entering Leader state
Oct 25 16:45:16 vault consul[1242]: raft: Added peer 192.168.56.130:8300, starting replication
Oct 25 16:45:16 vault consul[1242]: consul: cluster leadership acquired
Oct 25 16:45:16 vault consul[1242]: consul: New leader elected: vault
Oct 25 16:45:16 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Follower] entering Follower state (Leader: "")
Oct 25 16:45:16 vault consul[1242]: consul: failed to wait for barrier: node is not the leader
Oct 25 16:45:16 vault consul[1242]: consul: shutting down leader loop
Oct 25 16:45:16 vault consul[1242]: consul: cluster leadership lost
Oct 25 16:45:24 vault consul[1242]: agent: failed to sync remote state: No cluster leader
Oct 25 16:45:26 vault consul[1242]: raft: Heartbeat timeout from "" reached, starting election
Oct 25 16:45:26 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Candidate] entering Candidate state in term 169
Oct 25 16:45:26 vault consul[1242]: raft: Votes needed: 1
Oct 25 16:45:26 vault consul[1242]: raft: Vote granted from 192.168.56.130:8300 in term 169. Tally: 1
Oct 25 16:45:26 vault consul[1242]: raft: Election won. Tally: 1
Oct 25 16:45:26 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Leader] entering Leader state
Oct 25 16:45:26 vault consul[1242]: raft: Added peer 192.168.56.130:8300, starting replication
Oct 25 16:45:26 vault consul[1242]: consul: cluster leadership acquired
Oct 25 16:45:26 vault consul[1242]: consul: New leader elected: vault
Oct 25 16:45:26 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Follower] entering Follower state (Leader: "")
Oct 25 16:45:26 vault consul[1242]: consul: shutting down leader loop
Oct 25 16:45:26 vault consul[1242]: consul: failed to wait for barrier: leadership lost while committing log
Oct 25 16:45:26 vault consul[1242]: consul: cluster leadership lost

**---v This part is repeating forever. v---**
Oct 25 16:45:34 vault consul[1242]: raft: Heartbeat timeout from "" reached, starting election
Oct 25 16:45:34 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Candidate] entering Candidate state in term 170
Oct 25 16:45:34 vault consul[1242]: raft: Votes needed: 1
Oct 25 16:45:34 vault consul[1242]: raft: Vote granted from 192.168.56.130:8300 in term 170. Tally: 1
Oct 25 16:45:34 vault consul[1242]: raft: Election won. Tally: 1
Oct 25 16:45:34 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Leader] entering Leader state
Oct 25 16:45:34 vault consul[1242]: raft: Added peer 192.168.56.130:8300, starting replication
Oct 25 16:45:34 vault consul[1242]: consul: cluster leadership acquired
Oct 25 16:45:34 vault consul[1242]: consul: New leader elected: vault
Oct 25 16:45:34 vault consul[1242]: raft: Node at 192.168.56.130:8300 [Follower] entering Follower state (Leader: "")
Oct 25 16:45:34 vault consul[1242]: consul: shutting down leader loop
Oct 25 16:45:34 vault consul[1242]: consul: failed to wait for barrier: leadership lost while committing log
Oct 25 16:45:34 vault consul[1242]: consul: cluster leadership lost
**---^ This part is repeating forever. ^---**

Thanks

**Comment by slackpad** [comment]
Hi @drabo there's a note here about this - https://www.consul.io/docs/upgrade-specific.html#raft-protocol-now-defaults-to-3:

> If running a single Consul server, restarting it in-place will result in that server not being able to elect itself as a leader. To avoid this, either set the Raft protocol back to 2, or use [Manual Recovery](https://www.consul.io/docs/guides/outage.html#manual-recovery-using-peers-json) Using peers.json to map the server to its node ID in the Raft quorum configuration.
