### ISSUE TITLE
"Failed to parse watch" with docs example for watch event, "Invalid parameters: [args]"

### ISSUE THREAD

**Issue by mblakele** [hashicorp/consul#3619]
### `consul version` for both Client and Server
Client: `v0.8.3`
Server: `v0.8.3`

### `consul info` for both Client and Server

N/A

### Operating system and Environment details

Ubuntu 16.04

### Description of the Issue (and unexpected/desired result)

https://www.consul.io/docs/agent/watches.html#type-event has an example of json syntax for event watch:

```json
{
  "type": "event",
  "name": "web-deploy",
  "args": ["/usr/bin/my-service-handler.sh", "-web-deploy"]
}
```

However when this syntax is applied in consul.conf, startup fails with:

```bash
Failed to parse watch (map[string]interface {}{"args":[]interface {}{
"/usr/bin/my-service-handler.sh", "-web-deploy"
}}): Invalid parameters: [args]
```

I think it's supposed to be `handler` not `args`, and a string not `string[]`? With that change I can start consul.

```json
{
  "type": "event",
  "name": "web-deploy",
  "handler": "/usr/bin/my-service-handler.sh -web-deploy"
}
```

### Reproduction steps

Add the sample json to consul.conf under `watches`

### Log Fragments or Link to [gist](https://gist.github.com/)

N/A

**Comment by slackpad** [comment]
Hi @mblakele the `args` syntax was added in Consul 1.0, so for your version of Consul it's `handler`. There's a note up at the top of that page:

> Prior to Consul 1.0, watches used a single `handler` field to define the command to run, and would always run in a shell. In Consul 1.0, the `args` array was added so that handlers can be run without a shell. The `handler` field is deprecated, and you should include the shell in the `args` to run under a shell, eg. "args": ["sh", "-c", "..."].

**Comment by cclehui** [comment]
hi , @slackpad , my consul version is v1.0.6,  and my watchs config :

{
  "datacenter": "cclehui_test",
  "data_dir": "/home/cclehui/opensource/consul/data",
  "log_level": "INFO",
  "node_name": "agent_two",
  "server": true,
  "addresses": {
    "http": "0.0.0.0"
  },
  "ports": {
    "http": 8500
  },
  "ui": true,
  "watches": [
      {
          "type": "key",
          "key": "test/one",
          "handler_type": "script",
          "args": ["/bin/sh", "-c", "/home/cclehui/opensource/consul/watch/kv_test.sh"]
      }
  ]
}

but when i start the agent , i got a error:
**[ERR] agent: Failed to run watch handler '[/bin/sh -c /home/cclehui/opensource/consul/watch/kv_test.sh]': exit status 2**
