### ISSUE TITLE
Consul vault-KV value 

### ISSUE THREAD

**Issue by Hankhh** [hashicorp/consul#3629]
Hi Guys,

I am new to Hashicorp solutions. I recently implemented a pilot key management with vault. I am making use of AWS as secret backend and Consul as storage backend. I have an issue with reading Vault KV value from Consul-cli and HTTP API.
I successfully mounted AWS to the vault and generated a pair of access_key and secret_key which showed up on AWS IAM portal. But when I tried to get the value of the same key from consul cli using the following commands: I do know that " The storage backends used by Vault are also untrusted by design" but is there any way to read those key through Consul command line environment or not ?

consul kv get  vault/sys/expire/id/aws/creds/deploy/ce631c7b-1e0f-6475-3b6e-1a725a85c915

r▒Gt▒▒▒ʷ▒▒▒y▒v▒▒▒w:▒9▒▒▒V▒{▒▒▒wD):P▒▒▒@▒▒▒#▒j_>▒(▒▒.▒▒▒4G7▒֫{▒▒j▒▒▒▒w▒b▒Vp▒g▒▒4u9"▒▒$O▒▒G▒>▒f▒xp▒▒Б|▒▒Me[qb▒W▒▒▒

It just returns raw format.

consul kv export  vault/sys/expire/id/aws/creds/deploy/ce631c7b-1e0f-6475-3b6e-1a725a85c915

{
                "key": "vault/sys/expire/id/aws/creds/deploy/89f1c106-a334-3d80-9458-6b359c889751",
                "flags": 0,
                "value": "AAAAAQIqQhGN25cRHmoc24Gz28AANW1RH9hAV8Vo0MmOAbXPsTiRBwWcWYRCJ/+5W0IyvSbAO3t5ImZ+0LZMHNOTcoFet9Pnl++0v/Wu7QN5FuJqx/ztqN1Lt7FkvAXil/iKF2OAgaMRhdKB08NqiNxiPIx/gJo0I0cSenqGbCSuRJJriJcLayovoc4pT1htTtD+sdoAnJ4EfbpkjWgqYwoctotMbJ8KD1E5NR7qTzdZ0EZZxoAGr7xctxY29pgUItBOnoHFXFFX/E0zUESQoXukzS6nfqMpkKHfM3m6XQ3rul9fT1ZcFCvldAEY8P6WG0ER3KJMqeAKur+9pt6BPZmdGgZVNALojo+YUV06Q/97YgFqzTuo5p4R1BGa5d7eNJ/Li1tBulMVfoHznret2Dnr1g/pBNDDOfBb7E34OOA8iZoGSnh0Y/UcO1D7qe2OjHaYgo5x612SDKcz1I/Th

It returned the encrypted value of keys

- The Same problem through the consul web UI , it does not show anything on key value part.

I should mention that I have Consul and vault installed on the same server.
Here is my vault ACL in consul HTTP API 

{
  "key": {
    "vault/": {
      "policy": "write"
    }
  },
  "node": {
    "": {
      "policy": "write"
    }
  },
  "service": {
    "vault": {
      "policy": "write"
    }
  },
  "agent": {
    "": {
      "policy": "write"
    }

  },
  "session": {
    "": {
      "policy": "write"
    }
  }
}

Here is my vault config 

{
"listener" :[{
    "tcp": {
       "address" : "10.10.1.10:8200",
     "tls_cert_file" : "/etc/vault/ssl/consul.cer",
   "tls_key_file"  : "/etc/vault/ssl/consul.key"
   }
 }],

"storage" : {
   "consul" : {
  "address": "10.10.1.10:8600",
  "redirect_addr" : "https://10.10.1.10:8200",
   "path"   : "vault/",
  "scheme" : "https",
 "token" : "f4bb9cd3-8575-2755-702b-b1f8259ab9cc",
 "tls_ca_file" : "/etc/vault/ssl/mymm-root.cer",
  "tls_cert_file" : "/etc/vault/ssl/consul.cer",
 "tls_key_file" : "/etc/vault/ssl/consul.key"

Anonymous ACL 

event "" {
  policy = "read"
}
node "" {
  policy = "read"
}
service "" {
  policy = "read"
}
key "" {
  policy = "read"
}

Any idea what am I missing?
Thanks!

**Comment by bsodmike** [comment]
You had specified `"token" : "f4bb9cd3-8575-2755-702b-b1f8259ab9cc"` but you should set that up in Consul first -

```
[
  {
    "ID": "3bf874ad-c315-b37e-5fbc-dfd5d6184785",
    "Name": "vault",
    "Type": "management",
    "Rules": "agent \"\" { \n  policy = \"read\"\n}",
    "CreateIndex": 8746,
    "ModifyIndex": 8948
  }
]
```

This allows my unsealed vault to connect to Consul.  Also remember to restart your consul servers (or reload config) when ACLs are changed.  To protect leaking vaults data, I'm doing this too as an added safeguard.

```
[
  {
    "ID": "anonymous",
    "Name": "Anonymous Token",
    "Type": "client",
    "Rules": "key \"vault\" {\n  policy = \"deny\"\n}",
    "CreateIndex": 247,
    "ModifyIndex": 9109
  }
]
```

**Comment by slackpad** [comment]
Hi @Hankhh 

> It returned the encrypted value of keys

That's not encrypted, it's just Base64 encoded so that the key contents doesn't break the JSON format. The `consul kv get` outputs the raw key (which should still be encrypted). The visibility of the keys from the UI is governed by ACLs, so you'll need to use a suitable token for that.
