### ISSUE TITLE
Event sharing through Stateful protocol like WebSocket than HTTP long-pulling

### ISSUE THREAD

**Issue by s4kibs4mi** [hashicorp/consul#3639]
The problem is to get events using watch need to use long pulling. Is there any plan to do it through a stateful protocol like WebSocket or MQTT ? I don't want to do requests for unlimited time to look for update rather open a stateful connection and get event notification through this.

**Comment by slackpad** [comment]
Hi @s4kibs4mi we've thought about that but don't have any plans to add a websockets interface at this time.
