### ISSUE TITLE
BUG: If multiple recursors, DNS in Consul only checks first recursor

### ISSUE THREAD

**Issue by mnuic** [hashicorp/consul#3640]
When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `Consul v1.0.0`
Server: `Consul v1.0.0`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 7
	services = 13
build:
	prerelease =
	revision = 51ea240
	version = 1.0.0
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 72
	max_procs = 8
	os = linux
	version = go1.9.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 4632
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6988
	members = 12
	query_queue = 0
	query_time = 2
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 6
	services = 12
build:
	prerelease =
	revision = 51ea240
	version = 1.0.0
consul:
	bootstrap = false
	known_datacenters = 8
	leader = true
	leader_addr = a.b.c.d:8300
	server = true
raft:
	applied_index = 488778061
	commit_index = 488778061
	fsm_pending = 0
	last_contact = 0
	last_log_index = 488778061
	last_log_term = 23240
	last_snapshot_index = 488776684
	last_snapshot_term = 23240
	latest_configuration = [{Suffrage:Voter ID:9cc82777-f14f-454e-a1be-0c0284ebc0ab Address:a.b.c.d:8300} {Suffrage:Voter ID:d8766618-7ef5-473d-acd7-77a20dfd260e Address:a.b.c.d:8300} {Suffrage:Voter ID:6a9580b8-a8de-2761-659d-4fcb236616de Address:a.b.c.d:8300}]
	latest_configuration_index = 488672274
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 23240
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 996
	max_procs = 8
	os = linux
	version = go1.9.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 4632
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6988
	members = 12
	query_queue = 0
	query_time = 2
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 860
	members = 12
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Ubuntu 16.04.03 LTS, Docker v17.05.0-ce

### Description of the Issue (and unexpected/desired result)
If multiple recursors specifed in Consul config, when querying it Consul only check for the first one -> "recursors":["8.8.8.8","A.B.C.D"]
Example if I query service.my_company.com and I know that response should come from the second resursors. Consul checks first resursor and there is nothing, it should check the second one, but It doesn't

### Reproduction steps
Example is above, You can manipulate the query response with DNS ACL, or iptables denying the route.

### Log Fragments or Link to [gist](https://gist.github.com/)
There are no logs

**Comment by magiconair** [comment]
What do you get back when you query the first resolver? I've tested this with the first resolver not being available and then the second resolver works. If the first resolver returns an authoritative response for "does not exist" then I think it won't try the second resolver since it already got a valid response `not found`.

```
consul agent -dev -recursor 127.0.0.1 -recursor 8.8.8.8

$ dig @127.0.0.1 -p 8600 google.com. +short
172.217.6.78

2017/11/15 20:41:36 [ERR] dns: recurse failed: read udp 127.0.0.1:56565->127.0.0.1:53: read: connection refused
2017/11/15 20:41:36 [DEBUG] dns: recurse RTT for {google.com. 1 1} (14.549461ms)
2017/11/15 20:41:36 [DEBUG] dns: request for {google.com. 1 1} (udp) (15.075895ms) from client 127.0.0.1:54223 (udp)
```

**Comment by mnuic** [comment]
Hi @magiconair,

when querying the first resolver, inside the consul container:
```
# nslookup serviceA.company.com
nslookup: can't resolve '(null)': Name does not resolve

# nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve
Name:      google.com
Address 1: 172.217.18.14 fra02s19-in-f14.1e100.net
Address 2: 2a00:1450:4001:810::200e fra15s09-in-x0e.1e100.net
```

Logs:
```
2017/11/16 07:44:08 [ERR] dns: recurse failed: read udp A.B.C.D:20651->A.B.C.D:53: i/o timeout
2017/11/16 07:44:08 [ERR] dns: recurse failed: read udp A.B.C.D:47151->A.B.C.D:53: i/o timeout
2017/11/16 07:44:08 [ERR] dns: recurse failed: read udp A.B.C.D:22902->A.B.C.D:53: i/o timeout
2017/11/16 07:44:08 [ERR] dns: recurse failed: read udp A.B.C.D:47949->A.B.C.D:53: i/o timeout
``` 

First thing I thought that there are some network problems, but everything works. Can't figure out why the i/o timeout happen?!

For a workaround we left only one recursor that points to our internal DNS.

**Comment by dennisdupont** [comment]
I am seeing the same issue when using nslookup, but this is due to the nslookup timeout.  If the first recursor is not responding, the second is not attempted bu consul until after 2 seconds (verified with wireshark).  Since the default timeout with nslookup is 2 seconds, the error result is displayed. 

When I set the nslookup timeout to 5 seconds then it waits long enough for consul to try the second recursor.

Unfortunately the configuration item "recursor_timeout" does not appear to be accepted in the config file. I'd prefer to try with 1s.

**Comment by dennisdupont** [comment]
I was missing the fact that the "recursor_timeout" is a subkey of "dns_config".  It is working as expected now and does not timeout the nslookup.   More importantly I can expect better response time with the primary server unavailable.
