### ISSUE TITLE
server_name understanding and bug

### ISSUE THREAD

**Issue by discointheair** [hashicorp/consul#3641]
Hi

I am using consul 1.0.0 at centos with all configurations within config.json.
ATM I try to implement the using of “consul_tls_verify_server_hostname: true” with the same  wildcard certificate “*.consul.foo” for every servernode. (With “consul_tls_verify_server_hostname: false” everything works fine.)

My first try was only to set “consul_tls_verify_server_hostname: true”
At startup I get this exception:

`[ERR] consul: Failed to confirm peer status for consul1: rpc error getting client: failed to get conn: x509: certificate is valid for *.consul.foo, not server.dc1.consul. Retrying in 8s...`

After googling I found the option server_name and the explanation that this variable overwrite the pseudo default dns name “server.datacenter.consul” of the server node...

Here my understanding question:
Why is consul not using the real DNS to verify the CN of the certificate? I know from other Consul discussions there are assumptions that DNS is not reliable. But where is the more of security when a server can say by itself that his “hostname” matches to its certificate?

Bug:
Now I set server_name to “consul1.consul.foo” and the same error occurs:
`
[ERR] consul: Failed to confirm peer status for consul1: rpc error getting client: failed to get conn: x509: certificate is valid for *.consul.foo, not server.dc1.consul. Retrying in 8s...
`
The setting of server_name seems to have no effect.
If you want to have a detailed bug report I can give it to you. But I would happy about a discussion for the using of DNS to verify hostnames.

Thank you.

**Comment by xjsp** [comment]
Can confirm, I am seeing the same behavior: `failed to get conn: x509: certificate is valid for *.node.datacenter.dummy, not server.datacenter.dummy`. I would have expected the [node lookup format](https://www.consul.io/docs/agent/dns.html#node-lookups) `(<node>.node[.datacenter].<domain>)` to be valid in case of certificate validation as well. Can't override with `server_name` either.

Just to confirm that DNS returns formats as documented:

`$ dig consul.service.dummy SRV`

`;; ANSWER SECTION:`
`consul.service.dummy. 0 IN SRV    1 1 8300 lconex001625.node.datacenter.dummy.`
`consul.service.dummy. 0 IN SRV    1 1 8300 lconex001626.node.datacenter.dummy.`
`consul.service.dummy. 0 IN SRV    1 1 8300 lconex001627.node.datacenter.dummy.`

`;; ADDITIONAL SECTION:`
`lconex001625.node.datacenter.dummy. 0 IN A 10.116.2.129`
`lconex001626.node.datacenter.dummy. 0 IN A 10.116.2.198`
`lconex001627.node.datacenter.dummy. 0 IN A 10.116.2.199`

**Comment by discointheair** [comment]
Hi @xjsp 

Sorry. Dont saw your edited entry. 
>Using a certificate matching to server.datacenter.dummy, in your case server.dc1.consul resolves the ERR, would be interesting to know why :)

I think it do not solve the problem it only shows that if “server_name” (here the default pseudo DNS name) and the cert CN are equal the function clould work as expected. The real problem is that setting “server_name” has no effect and/or no real DNS server is queried.

**Comment by discointheair** [comment]
The bug seems only to appear when using consul as a server. If I using server_name within a client config it works correct.

@xjsp 
Can you confirm this?

**Comment by pearkes** [comment]
I'm not not totally sure I understand the question here:

>Why is consul not using the real DNS to verify the CN of the certificate? I know from other Consul discussions there are assumptions that DNS is not reliable. But where is the more of security when a server can say by itself that his “hostname” matches to its certificate?

Can you expand and explain the scenario you're in specifically?

**Comment by discointheair** [comment]
Hi @pearkes 
> Can you expand and explain the scenario you're in specifically?
Long time ago. Not complete any more.

>Why is consul not using the real DNS to verify the CN of the certificate?
To this topic:
[What is common name?](https://support.dnsimple.com/articles/what-is-common-name/)
As a client is makes no sense to ask the server what his CN is and compare it to the CN in the certificate he present you. 
As client you want to compare your request URL with the CN of the certificate the server presents you.

**Comment by i0rek** [comment]
@discointheair maybe I can clarify some things. The `server_name` configuration option has nothing to do with `verify_server_hostname`. 

`verify_server_hostname` is being used to enforce that only servers with a special certificate can join the other servers and participate in raft. If an agent presents a certificate that doesn't match the hostname `server.dc1.consul`, it cannot start as a server. Because the others running servers won't allow it! Not the agent itself decides if it can join, the others servers do. 

This issue is pretty old and it is not a bug as far as I understand. I will be happy to reopen in case you have more questions or thoughts around this.

**Comment by mikhail-yarosh** [comment]
@i0rek please, reopen the issue or clarify this:
`# Generate CA
consul tls ca create -domain=consul-server.test.int
# Generate Agents cert
consul tls cert create -client -domain=consul-server.consul-server.test.int
# Generate Server certs
consul tls cert create -server -domain=consul-server.consul-server.test.in
# Generate CLI cert
consul tls cert create -cli -domain=consul-server.consul-server.test.int`

also server starting with:
`consul agent -server -domain="consul-server.consul-server.test.int"`

and receive:

> 2019/05/24 10:30:24 [ERR] raft: Failed to make RequestVote RPC to {Voter 15783862-5551-936e-ce64-53e79fe317bb 10.56.15.90:8300}: x509: certificate is valid for server.dc1.consul-server.consul-vault1.svc.cluster.local, localhost, not server.dc1.consul

it shouldn't be a normal, or it doesn't matter which domain serving and generating certs.

**Comment by i0rek** [comment]
Hi @mikhail-yarosh,

I did the following:

```
$ consul tls ca create -domain=consul-server.test.int
$ consul tls cert create -domain=consul-server.test.int
$ cat server.json
{
	"ca_file": "./consul-server.test.int-agent-ca.pem",
	"cert_file": "./dc1-server-consul-server.test.int-0.pem",
	"key_file": "./dc1-server-consul-server.test.int-0-key.pem",
	"verify_outgoing": true,
	"verify_incoming": true,
	"verify_server_hostname": true
}
$ consul agent -server -bootstrap-expect 2 -data-dir dc1-s1 -bind 127.0.0.1 -node s1 -serf-lan-port 8301 -serf-wan-port 8701 -http-port 8500 -dns-port -1 -server-port 8101 -config-file server.json -datacenter dc1 -domain consul-server.test.int
$ consul agent -server -bootstrap-expect 2 -retry-join localhost:8301 -data-dir dc1-s2 -bind 127.0.0.1 -node s2 -serf-lan-port 20000 -serf-wan-port 40000 -http-port 30000 -dns-port 50000 -server-port 10000 -config-file server.json -datacenter dc1 -domain consul-server.test.int
```

And both servers can talk to each other just fine.

Your example is not complete and it has typos like `...test.int` vs `...test.in`. I think you enabled `verify_server_hostname` and started servers where cert and domain don't match. Your log line complains about that: `server.dc1.consul-server.test.in` vs `server.dc1.consul`.

> it shouldn't be a normal, or it doesn't matter which domain serving and generating certs.

Well it does for consul because this is an important piece in our security model, you can read about it here: https://www.consul.io/docs/agent/options.html#verify_server_hostname and https://www.consul.io/docs/internals/security.html. 

For these types of questions it would be great if you could use our mailing list next time. 👍
