### ISSUE TITLE
0.9.3 Autopilot does not remove dead nodes from remote WAN pool

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/consul#3644]
### `consul version` for both Client and Server
Server: 0.9.3

### `consul info` for both Client and Server
Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 112c060
	version = 0.9.3
consul:
	bootstrap = false
	known_datacenters = 2
	leader = true
	leader_addr = 172.18.92.73:8300
	server = true
raft:
	applied_index = 2835440
	commit_index = 2835440
	fsm_pending = 0
	last_contact = 0
	last_log_index = 2835440
	last_log_term = 135
	last_snapshot_index = 2833531
	last_snapshot_term = 135
	latest_configuration = [{Suffrage:Voter ID:8091983c-9e90-9156-ac17-8123b572ad1e Address:172.18.62.168:8300} {Suffrage:Voter ID:777f86b8-6f65-d3f1-a125-6d7b3686d005 Address:172.18.92.73:8300} {Suffrage:Voter ID:af016c7c-2680-d7c3-a640-369d6e31b61e Address:172.18.26.228:8300}]
	latest_configuration_index = 209941
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 135
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 218
	max_procs = 4
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 11
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 175
	members = 31
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 2
	member_time = 33
	members = 8
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
CoreOS running Consul Server in a Docker container.  Two 3-node Consul clusters WAN-joined.

```
# consul members -wan

ip-172-18-26-228.ec2.internal.dc-east               172.18.26.228:8302  alive   server  0.9.3  2         dc-east  <all>
ip-172-18-62-168.ec2.internal.dc-east               172.18.62.168:8302  alive   server  0.9.3  2         dc-east  <all>
ip-172-18-92-73.ec2.internal.dc-east                172.18.92.73:8302   alive   server  0.9.3  2         dc-east  <all>
ip-172-19-25-75.us-west-2.compute.internal.dc-west  172.19.25.75:8302   alive   server  0.9.3  2         dc-west  <all>
ip-172-19-59-3.us-west-2.compute.internal.dc-west   172.19.59.3:8302    alive   server  0.9.3  2         dc-west  <all>
ip-172-19-94-19.us-west-2.compute.internal.dc-west  172.19.94.19:8302   alive   server  0.9.3  2         dc-west  <all>
```

### Description of the Issue (and unexpected/desired result)
Ungracefully terminate a server node in dc-west.  The node will appear as 'failed' in dc-west and dc-east.  When a new server node connects and joins the cluster, autopilot will evict the failed node in dc-west.  dc-east will continue to show the node as failed until (I expect) the 72 hour timer expires and it is expunged.   When combined with #3463, this results in dc-east periodically returning `No path to datacenter` until another rebalance occurs.

### Reproduction steps
1. Create 2 WAN-joined 3 node Consul clusters
2. Ungracefully terminate a node.
3. Autopilot evicts the node when a replacement node provisions
4. Observe the 'far' datacenter remain unaware of the eviction and continue to try to reach the failed node.
4. Periodic No Path to Datacenter errors ensue.

A graceful `consul leave` is propagated properly.

**Comment by slackpad** [comment]
Hi @jhmartin autopilot has never operated on servers in the WAN pool (it just manages the Raft quorum based on the LAN pool). I think this really is just a manifestation of #3463, which if fixed should keep requests away from that failed server if there's a healthy one available.

**Comment by jhmartin** [comment]
@slackpad Thank you, I'll look forward to 1.0.1.
