### ISSUE TITLE
Watch trigger coalescing

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#365]
In some cases you want to watch multiple keys, services, health checks, etc, but invoke the same action on a change (restart service, etc). In this case, you don't want all those to fire and restart multiple times, instead you'd like to coalesce the triggers to fire once.

**Comment by tailhook** [comment]
Does this also mean that I will be able to set multiple watches in single HTTP request? Requirement to do tens or hundreds of connections looks weird.

**Comment by armon** [comment]
Not quite. This is a different issues. The HTTP watch merging is more of an API problem, since the API doesn't support that. This is about merging the firing of watches together.

**Comment by tailhook** [comment]
Yes. But it seems that http watch merging must be precursor to this issue, because I don't understand how to coalesce multiple watches when they are separate http requests.

Anyway should I create a separate issue for http watch merging?

**Comment by armon** [comment]
@tailhook Please do make a separate issue. It is something that is more likely to be part of a V2 API. For this issue, it's more of just a time-based de-duplication. E.g. Only fire the handler once per second for any of these watches. Useful when a single handler is triggered by multiple different watchers.

**Comment by nailgun** [comment]
+1

**Comment by tesseract2048** [comment]
Any idea where do I find the issue about merging HTTP watch requests? Thanks.

**Comment by slackpad** [comment]
Now that we have a generic trigger mechanism in the state store, we could extend /v1/txn to allow for blocking reads.

**Comment by slackpad** [comment]
This isn't on the roadmap at this time, we'd welcome a PR for it.
