### ISSUE TITLE
How to watch a key change/delete/add?

### ISSUE THREAD

**Issue by guotie** [hashicorp/consul#3653]
How to watch a key change/delete/add, like etcd watch

**Comment by slackpad** [comment]
Hi @guotie in Consul you use blocking queries to do that -
 https://www.consul.io/api/index.html#blocking-queries. The KV APIs like https://www.consul.io/api/kv.html#read-key support it. Hope that helps!

**Comment by guotie** [comment]
does there any sdk api in golang

**Comment by slackpad** [comment]
Yes - it's in the Consul repo itself - https://github.com/hashicorp/consul/tree/master/api. Here's an example of a blocking query on a key - https://github.com/hashicorp/consul/blob/master/api/lock.go#L358-L385.

**Comment by lwhile** [comment]
Does blocking query supports to watch a key was being deleted?

**Comment by slackpad** [comment]
> Does blocking query supports to watch a key was being deleted?

It will wake up if the key is deleted.
