### ISSUE TITLE
Client consul not able to join with server consul

### ISSUE THREAD

**Issue by naliniranjan82** [hashicorp/consul#3658]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

### `consul version` for both Client and Server
Client: `[client version here]` -0.7.1
Server: `[server version here]` -0.7.1

### `consul info` for both Client and Server
Client:

{
"ui": true,
"retry_join":["XXX.XXX.XXX.XX"],
"advertise_addr": "***.***.***.***",
"client_addr":"0.0.0.0",
"data_dir":"/home/consul_agent",
"datacenter":"central_eu"
}

[Client `consul info` here]
``` Failed to join XXX.XXX.XXX.XX: dial tcp XXX.XXX.XXX.XX:8301: getsockopt: connection refused
    2017/11/07 07:53:45 [WARN] agent: Join failed: <nil>, retrying in 30s
    2017/11/07 07:53:55 [WARN] manager: No servers available
    2017/11/07 07:53:55 [ERR] agent: failed to sync remote state: No known Consul servers
    2017/11/07 07:54:15 [INFO] agent: (LAN) joining: [XXX.XXX.XXX.XX]
    2017/11/07 07:54:15 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:

Server:
server_consul.json
{
"ui" : true,
"advertise_addr": "XXX.XXX.XXX.XX",
"data_dir" : "/home//consul_agent",
"client_addr" : "0.0.0.0",
"datacenter":"central_eu"
}
``
[Server `consul info` here]
```
$ ./consul agent -dev -config-file server_consul.json
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.1'
         Node name: 'nemuatapXXX
        Datacenter: 'central_eu'
            Server: true (bootstrap: false)
       Client Addr: XXX.XXX.XXX.XX (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: XXX.XXX.XXX.XX (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2017/11/07 07:22:36 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:XXX.XXX.XXX.XX:8300 Address:XXX.XXX.XXX.XX:8300}]
    2017/11/07 07:22:36 [WARN] memberlist: Binding to public address without encryption!
    2017/11/07 07:22:36 [INFO] raft: Node at XXX.XXX.XXX.XX:8300 [Follower] entering Follower state (Leader: "")
    2017/11/07 07:22:36 [INFO] serf: EventMemberJoin: nemuatapXXX XXX.XXX.XXX.XX
    2017/11/07 07:22:36 [INFO] consul: Adding LAN server nemuatapXXX (Addr: tcp/XXX.XXX.XXX.XX:8300) (DC: central_eu)
    2017/11/07 07:22:36 [WARN] memberlist: Binding to public address without encryption!
    2017/11/07 07:22:36 [INFO] serf: EventMemberJoin: nemuatapXXX.central_eu XXX.XXX.XXX.XX
    2017/11/07 07:22:36 [INFO] consul: Adding WAN server nemuatapXXX.central_eu (Addr: tcp/XXX.XXX.XXX.XX:8300) (DC: central_eu)
    2017/11/07 07:22:43 [ERR] agent: failed to sync remote state: No cluster leader
    2017/11/07 07:22:44 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2017/11/07 07:22:44 [INFO] raft: Node at XXX.XXX.XXX.XX:8300 [Candidate] entering Candidate state in term 2
    2017/11/07 07:22:44 [DEBUG] raft: Votes needed: 1
    2017/11/07 07:22:44 [DEBUG] raft: Vote granted from XXX.XXX.XXX.XX:8300 in term 2. Tally: 1
    2017/11/07 07:22:44 [INFO] raft: Election won. Tally: 1
    2017/11/07 07:22:44 [INFO] raft: Node at XXX.XXX.XXX.XX:8300 [Leader] entering Leader state
    2017/11/07 07:22:44 [INFO] consul: cluster leadership acquired
    2017/11/07 07:22:44 [DEBUG] consul: reset tombstone GC to index 3
    2017/11/07 07:22:44 [INFO] consul: New leader elected: nemuatapXXX
    2017/11/07 07:22:44 [INFO] consul: member 'nemuatapXXX' joined, marking health alive
### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @naliniranjan82 it looks like the log got cut off right after this line `2017/11/07 07:54:15 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:`, but the error message there should point to what happened. Hope that helps!

**Comment by chen-joe1015** [comment]
We also have this problem.plese help!

**Comment by banks** [comment]
@chen-joe1015 this is an old closed issue. 

Note the logs James pointed out that the original issue poster somehow cut off from their paste and see what you have in yours. If you still need help after looking at logs, please open a new issue with full details and your own logs etc. Thanks!
