### ISSUE TITLE
CIDR or wildcards support for auto-join

### ISSUE THREAD

**Issue by guestisp** [hashicorp/consul#3665]
Please add support for CIDR or wildcards (ie `192.168.*.*`) for `-auto-join` argument.

This would be great on local lan when you have a subnet hosting consul services that should be joined together

**Comment by magiconair** [comment]
Would this mean trying to join all 65535 (=256*256) possible addresses? I think this might be a feature for https://github.com/hashicorp/go-sockaddr if that isn't already supported.

**Comment by guestisp** [comment]
It depends on the user...
Currently I use something more useful like 192.168.0.0/28 and is working properly

**Comment by slackpad** [comment]
Agree with @magiconair on this one I think if we run the retry-join string through the go-sockaddr parser we can leverage that for this (not sure if we need a change there) - that would avoid a special case in Consul and would expose anything that go-sockaddr templates can do, which is quite a lot.

**Comment by slackpad** [comment]
Hi, this never made it on the roadmap, and it's not a very high priority for us. We would gladly review a PR for this functionality, but we are going to close this issue since it's not something we are going to implement ourselves (this would possibly need a PR against go-sockaddr and then a small update to Consul to run the retry-join address through the go-sockaddr template parser).

**Comment by guestisp** [comment]
Ok but as simple work around is still useful
Currently it's impossible to automatically join a set of nodes without using external services.

This PR will fix this. Obviously it can be made better, but is a simple temporary fix

**Comment by slackpad** [comment]
Hi @guestisp I definitely understand it's a simple code change but then we have to support it and transition to the new syntax for go-sockaddr later, update documentation, etc. In the long run it ends up being a lot of work for us. The go-sockaddr approach is more work to implement but has a flexible syntax for adding more features later and is a good logical fit for other types of address operations that folks will inevitably want.

**Comment by guestisp** [comment]
I've seen that a related PR was merged.
Is now possible to specify a CIDR range ? If yes, how ?

**Comment by guestisp** [comment]
Any help ?

**Comment by banks** [comment]
@guestisp this is a closed issue. We now support sockaddr templates for retry join which means any feature supported there can be used. You can read docks for go-sockaddr to see what is possible. If you need something extra consider a PR to go-sockaddr.
