### ISSUE TITLE
Tombstone GC bin sharing is broken by monotonic time

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3670]
Even after fiddling timing and reordering things to try to be more reliable in https://github.com/hashicorp/consul/commit/7b966e2d26833c64ec54a06ebdc027b2689a32ec, this test is failing unexpectedly:

```
[02:12:57][Step 1/1] --- FAIL: TestTombstoneGC (0.05s)
[02:12:57][Step 1/1] 	tombstone_gc_test.go:74: bad index: 120
```

Doing some debug tracing it looks like the time calculations are right, so it's not clear how the 120 and 125 are ending up in different buckets if they are written back-to-back. Need to dig into this.

**Comment by slackpad** [comment]
Added a skip in CI for now until we sort this out - it will still run the test locally, which seems to always be OK.

**Comment by slackpad** [comment]
Meh I got a few good runs but then it flaked again when I merged to master. Need to understand this more so reopening and reverting for now.

**Comment by flyinprogrammer** [comment]
i too can reproduce this flakiness:

```
--- FAIL: TestTombstoneGC (0.05s)
	tombstone_gc_test.go:79: bad index: 120
```

**Comment by slackpad** [comment]
Turns out that we weren't properly re-using bins because of equality issues with monotonic time. From https://golang.org/pkg/time/#Time:

> Note that the Go == operator compares not just the time instant but also the Location and the monotonic clock reading. Therefore, Time values should not be used as map or database keys without first guaranteeing that the identical Location has been set for all values, which can be achieved through use of the UTC or Local method, and that the monotonic clock reading has been stripped by setting t = t.Round(0). In general, prefer t.Equal(u) to t == u, since t.Equal uses the most accurate comparison available and correctly handles the case when only one of its arguments has a monotonic clock reading.
