### ISSUE TITLE
No alternative to deprecated checkIds when creating a session

### ISSUE THREAD

**Issue by pocman** [hashicorp/consul#3675]
Hi,

i'm trying to add some [checks](https://www.consul.io/api/session.html#checks) when creating a session. 
Documentation is unclear if I should provide a CheckId ou an Id (of the check object). In the code, it looks like only CheckIds are supported even if they are deprecated.

Do you plan on adding support for check.id params in the create session body ?

**Comment by slackpad** [comment]
Hi @pocman that is a list of check IDs, which aren't deprecated, so if you have a check `foo` on that node you'd have an entry like `["serfHealth", "foo"]` in the session definition. We can definitely improve the docs here a bit.
