### ISSUE TITLE
Wrong ACLs lead to desynchronization of Consul agent with Cluster

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#3676]
Hello

Consul Version: 0.9.3 (client & server)

We are using ACLs to register services and HealthCheck in a on-demand cluster, thus people might be able to use wrong tokens for the service they want to describe.

We found out that when several services have wrong ACLs, the state in the local Consul Agent is not the same as seen in the cluster.

While it seems legit for users having wrong token, however, sometimes, it seems that legit services cannot sync their state neither.

We are registering lots of services using the localhost:8500/v1/agent/service/register endpoint, and this is especially visible for health check statuses that are not properly updated. The case seems linked to having several services with wrong tokens (those services might include several heathchecks). Forbidding applications with wrong tokens seems to avoid this issue, but this is problematic since it desync the agent with its state reported by the cluster.

Example of messages as seen in the Consul Agent:
```
Nov 02 01:50:16 mesos-slave060-par consul[11906]: 2017/11/02 01:50:16 [ERR] consul: RPC failed to server 10.251.1.97:8300: rpc error: rpc error: Permission denied
Nov 02 01:50:16 mesos-slave060-par consul[11906]: 2017/11/02 01:50:16 [WARN] agent: Service 'mysuper-service-31519' registration blocked by ACLs
```

Here mysuper-service-31519 has clearly a wrong token and its registration fails.
But after a while, having several services doing similar thing completely break agent synchronization, so the state in the cluster is not updated anymore.

A restart of the agent solves the issue most of the time (while we had cases where we had to cleanup the repository of checks to solve the issue). It is especially strange that the service registered with his token is then properly updated (including its healthchecks) -> so I suspect that after a restart, Consul is loosing the token context and does not use the ACL anymore.

We are trying to create for now a clear reproduction of the bug, but it seems complicated (having several clients doing the same), and seems to happen after a while.

Do you have an idea where it could come from?

**Comment by wdauchy** [comment]
is there any progress regarding this issue?

**Comment by pierresouchay** [comment]
This one https://github.com/hashicorp/consul/pull/4405 would also help to diagnose those issues
