### ISSUE TITLE
Add option to log to stdout only if syslog logging fails

### ISSUE THREAD

**Issue by sgrimm-sg** [hashicorp/consul#3677]
### `consul version` for both Client and Server
Client: `0.7.5`
Server: `0.7.5`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease = 
	revision = '21f2d5a
	version = 0.7.5
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 39
	max_procs = 2
	os = linux
	version = go1.7.5
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 647
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 463
	members = 18
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease = 
	revision = '21f2d5a
	version = 0.7.5
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.0.5.27:8300
	server = true
raft:
	applied_index = 7650533
	commit_index = 7650533
	fsm_pending = 0
	last_contact = never
	last_log_index = 7650533
	last_log_term = 925
	last_snapshot_index = 7643039
	last_snapshot_term = 914
	latest_configuration = [{Suffrage:Voter ID:10.0.5.27:8300 Address:10.0.5.27:8300} {Suffrage:Voter ID:10.0.3.226:8300 Address:10.0.3.226:8300} {Suffrage:Voter ID:10.0.7.147:8300 Address:10.0.7.147:8300}]
	latest_configuration_index = 7650255
	num_peers = 2
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 925
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 127
	max_procs = 1
	os = linux
	version = go1.7.5
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 647
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 463
	members = 18
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Ubuntu 16.04 LTS on AWS EC2 instances

### Description of the Issue (and unexpected/desired result)

When the `enable_syslog` option is set, the Consul agent sends log messages to syslog as expected. However, it continues to also write the same log messages to stdout. If the agent is run as a system service and stdout/stderr are captured, this results in each message being logged twice.

One workaround is to redirect stdout/stderr to /dev/null, but that means losing any error messages the agent can't send to syslog (for example: errors about not being able to send messages to syslog!)

Ideally the agent would, if syslog logging was enabled, first try to log to syslog, and only if that failed, write the message to stdout.

### Reproduction steps

Run Consul agent as a systemd service and include `"enable_syslog": true` in the configuration JSON. Watch `/var/log/messages` and observe that each log message appears twice.

### Log Fragments or Link to [gist](https://gist.github.com/)

```
<30>Nov  9 22:37:28 consul-3 consul[8415]:     2017/11/09 22:37:28 [INFO] serf: EventMemberLeave: pgx-staging-2 10.0.3.188
<133>Nov  9 22:37:28 consul-3 consul[8415]: serf: EventMemberLeave: pgx-staging-2 10.0.3.188
```

**Comment by pearkes** [comment]
> One workaround is to redirect stdout/stderr to /dev/null, but that means losing any error messages the agent can't send to syslog (for example: errors about not being able to send messages to syslog!)

I think there are various ways to filter out important log messages in this use-case. Though I agree it is frustrating to duplicate, depending on your environment there are workarounds to avoid this while not dropping all messages.

**Comment by h0tw1r3** [comment]
The problem with nulling stdout and stderr is startup messages are lost (not all messages are sent to syslog).

**Comment by DrLex0** [comment]
I use this ugly workaround to preserve the startup messages and suppress stdout when syslog forwarding should be active:
```
ExecStart=/bin/bash -c 'exec 1> >(head -n 16); exec /usr/bin/consul agent -syslog -config-dir=/etc/consul.d'
```
This redirects stdout to a `head` process before replacing the shell with the consul process. After about 11 lines, consul starts sending to syslog. The first messages are logged as ‘bash’ which is ugly, but at least they are preserved.

It would make a lot more sense if consul would have an option to not print on stdout what is being sent to syslog.

**Comment by DrLex0** [comment]
The hack with `head` I mentioned above is not recommended. When the `head` process exits, stdout will be left dangling and this sometimes causes consul to exit with a SIGPIPE (I found no rhyme or reason when this happens and when not).
It is better to send stdout to a process that keeps running, like a grep that filters out the typical log lines also sent to syslog. It costs a tiny bit of extra resources but is more robust in many ways. Of course it's still a hack and I would prefer the duplicate lines not to be produced in the first place…
```
ExecStart=/bin/bash -c 'exec 1> >(grep --line-buffered -v "^    [0-9]"); exec /usr/bin/consul agent -syslog -config-dir=/etc/consul.d'
```
The `--line-buffered` is important, otherwise the messages will likely be stuck in a buffer forever.
