### ISSUE TITLE
DNS server cannot be used as stub resolver

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/consul#368]
Consul's DNS implementation appears not to work as a stub zone provider for  the .consul zone.  This causes DNS resolvers that forward queries to Consul for the zone to return `SERVFAIL` when Consul is configured as a stub resolver.  

(Unbound in particular suffers from this issue -- you can work around it by configuring Unbound to use `"consul."` as a  `forward-zone` instead of `stub-zone` but they are technically different and `stub-zone` would be the proper configuration.)

Example:

```
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52828
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;nginx.service.dc1.consul.	IN	A

;; ANSWER SECTION:
nginx.service.dc1.consul. 0	IN	A	10.0.2.15
```

**Comment by wunki** [comment]
@mfischer-zd were you able to configure unbound for consul? If so, could you share your forwarding configuration, can't get it to work myself. Thanks in advance.

**Comment by mfischer-zd** [comment]
Not yet -- we gave up and are using dnsmasq currently.

**Comment by nicwaller** [comment]
I had a similar problem setting up a stub zone with Unbound for Consul. I had to add this to the Unbound configuration file:

    server:
        do-not-query-localhost: no

By default, Unbound will prevent itself from sending queries to localhost (either stub or forward). After disabling this restriction, I found that Consul worked as a stub-zone, but still did not work as a forwarder.

**Comment by mfischer-zd** [comment]
@nicwaller, that was my subsequent finding as well (but had failed to mention it here).  Closing this issue.  Thanks for reminding me!

**Comment by joemiller** [comment]
FWIW, here is my working configuration. It took me several minutes to figure this out, so I'm posting here in case it helps others who stumble upon this link:

```
stub-zone:
  name: "consul"
  stub-addr: 127.0.0.1@8600
server:
  domain-insecure: "consul"
```

The key to getting it to work in our case was the `domain-insecure` so that Unbound would not try to do DNSSSEC validation which consul does not support. Otherwise you will see errors in the logs such as this (with `verbose: 2` or higher in unbound.conf):
```
May 22 17:14:18 graphite04b unbound[4158]: [4158:0] info: validation failure logstash_agent_tcp_4001.service.consul. ANY IN
May 22 17:14:18 graphite04b unbound[4158]: [4158:0] info: Could not establish a chain of trust to keys for consul. DNSKEY IN
May 22 17:14:18 graphite04b unbound[4158]: [4158:0] info: NSEC3s for the referral did not prove no DS.
```
