### ISSUE TITLE
Consul http output should support compression

### ISSUE THREAD

**Issue by kamaradclimber** [hashicorp/consul#3687]
### `consul version` for both Client and Server
Client: `0.9.3`
Server: `0.9.3`

### Description of the Issue (and unexpected/desired result)

Consul does not compress answers of the http api.

### Reproduction steps

Using `Accept-Encoding` header does not modify consul response.

`curl --compressed  -v 'consul.service.consul.prod.crto.in:8500/v1/health/service/web-rtb-eu?passing=true&stale='`

returns:
```
> GET /v1/health/service/web-rtb-eu?passing=true&stale= HTTP/1.1
> Host: consul.service.consul.prod.crto.in:8500
> User-Agent: curl/7.56.1
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 487052299
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 80
< Date: Mon, 13 Nov 2017 13:19:28 GMT
< Transfer-Encoding: chunked
```
response is 500K but could be compressed to ~30K

**Comment by mkeeler** [comment]
Going to close as I just merged support into master.
