### ISSUE TITLE
How should I use one ip to access the consul cluster?

### ISSUE THREAD

**Issue by songjianhua678** [hashicorp/consul#3689]
How should I use one ip to access a consul cluster. For example there is 3 nodes consul cluster
consul node 1 : 192.168.8.11
consul node 2 : 192.168.8.20
consul node 3 : 192.168.8.32

How should I use one ip + port to access the consul cluster ?

**Comment by discointheair** [comment]
Maybe you want to specify your problem.
If you want to join with another consul agent to the cluster, you need at least one IP to connect to.
If you only want to reach the KV Store/Consul API/GUI you can use a load balancer in front of the servers with the http port (default 8500) as target.

**Comment by slackpad** [comment]
Hi @songjianhua678 we always recommend running the Consul agent on each host and then just using 127.0.0.1:8500 to get to Consul's API. The agent will keep track of servers as they come and go, etc. so you don't need to worry about that. Hope that helps!
