### ISSUE TITLE
Web UI: Show left nodes

### ISSUE THREAD

**Issue by wkennington** [hashicorp/consul#369]
It would be nice to see nodes that have purposefully left, similar to the members rpc call.

**Comment by memelet** [comment]
Is there any workaround to this? My UI is getting pretty crowded with left members.

**Comment by ryanuber** [comment]
@memelet if the members have left, they should not show up in the UI. If they are killed abruptly, they should enter a "failed" state. In this state, Consul cannot determine if the node is expected to come back or not, so the member will not be reaped out for 72 hours. If you do not expect the nodes to return to the cluster, you can issue a leave event from the command line of any other member using the [force-leave command](https://consul.io/docs/commands/force-leave.html), or the [force-leave api](https://consul.io/docs/agent/http/agent.html#agent_force_leave).

**Comment by memelet** [comment]
Ah, that makes sense. Thanks ryanuber!

**Comment by slackpad** [comment]
@wkennington the cluster doesn't have a strong notion of nodes that have left - that's maintained by the gossip layer on each node. We don't plan on adding that info to the state store at this time, so we don't have a good way to show that in the UI.
