### ISSUE TITLE
Register services with public/floating ip address on consul

### ISSUE THREAD

**Issue by praveen12579** [hashicorp/consul#3690]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: no client
Server:  consul1.0.0

Server:
```
./consul agent -server -data-dir='/tmp/consul' -config-file='consul_config.json' -bootstrap-expect 1 -bind [private i/p] -client [private i/p] -ui &

### Operating system and Environment details
linux
### Description of the Issue (and unexpected/desired result)
how can I register services with public/floating ip address on consul

### Reproduction steps
steps:
1. Register services at remote machine.
with above consul they will be registered with private ip address
2. Register other services at same consul
In this step other services need to contact with already registered services.
As the previous services are registered with machines private i/p address, so those will be out of reach.

So Is there is any way to register services on cosul with public/floating ip address.
Or please suggest any other solution

**Comment by discointheair** [comment]
Hi see this for nodes:
https://www.consul.io/docs/agent/options.html#_advertise

For services you can register every IP you want as address.

**Comment by slackpad** [comment]
You can set the `address` field when you register a service to avoid getting the node's IP (see https://www.consul.io/docs/agent/services.html):

> The address field can be used to specify a service-specific IP address. By default, the IP address of the agent is used, and this does not need to be provided. The port field can be used as well to make a service-oriented architecture simpler to configure; this way, the address and port of a service can be discovered.

Depending on what you are doing, you may also want to make a node entry in the catalog manually, see https://www.consul.io/docs/guides/external.html for details on external services. Hope that helps!
