### ISSUE TITLE
Missing doc block about service register

### ISSUE THREAD

**Issue by WoZ** [hashicorp/consul#3691]
Hi!

I've found in current version of docs (https://www.consul.io/api/agent/service.html) that there is no info about `Port` parameter in `/agent/service/register` payload. 

I see that in https://github.com/hashicorp/consul/blob/df5e3fb18aa7f0103c23e1be6391185b7735d611/api/agent.go#L66 the field is present. But no info in docs.

Is it bug and PR is needed?

**Comment by preetapan** [comment]
@WoZ you are correct, there's no description of Port in the register service documentation, but it is mentioned in the sample payload in the [example](https://www.consul.io/api/agent/service.html#sample-payload), feel free to submit a PR
