### ISSUE TITLE
[QUESTION] Checks & services not synced over to new server added to cluster

### ISSUE THREAD

**Issue by cmacrae** [hashicorp/consul#3692]
Having a bit of trouble understanding an issue I'm having with a Consul cluster I've just increased the size of.

Here's a gist with details of the cluster (currently 2 servers, but will be increasing to 3 once I get past this issue): https://gist.github.com/cmacrae/e8de5b2f09b63e1a3710ce9b0e23ec25

So, up until now, I'd been running a single server. I just launched another instance into the cluster, it's joined, but it doesn't look like it's fully synced all info in the cluster.

That is to say: I have several services which are checking in with their healthcheck constantly. When their healthchecks get routed to the new node (servers are behind a loadbalancer), it results in the following in that node's log:
```
Nov 09 16:19:54 ip-172-31-48-67 consul[755]: 2017/11/09 16:19:54 [ERR] http: Request PUT /v1/agent/check/pass/service:cassandra-ip-172-31-48-183?note=ok, error: Unknown check "service:cassandra-ip-172-31-48-183" from=172.31.84.81:21981
Nov 09 16:19:54 ip-172-31-48-67 consul[755]: 2017/11/09 16:19:54 [ERR] http: Request PUT /v1/agent/check/pass/service:zookeeper-ip-172-31-53-124?note=ok, error: Unknown check "service:zookeeper-ip-172-31-53-124" from=172.31.76.159:42350
Nov 09 16:19:57 ip-172-31-48-67 consul[755]: 2017/11/09 16:19:57 [ERR] http: Request PUT /v1/agent/check/pass/service:cassandra-ip-172-31-57-186?note=ok, error: Unknown check "service:cassandra-ip-172-31-57-186" from=172.31.76.159:42350
Nov 09 16:19:57 ip-172-31-48-67 consul[755]: 2017/11/09 16:19:57 [ERR] http: Request PUT /v1/agent/check/pass/service:cassandra-ip-172-31-54-119?note=ok, error: Unknown check "service:cassandra-ip-172-31-54-119" from=172.31.84.81:21981
Nov 09 16:19:57 ip-172-31-48-67 consul[755]: 2017/11/09 16:19:57 [ERR] http: Request PUT /v1/agent/check/pass/service:elasticsearch-ip-172-31-53-95?note=ok, error: Unknown check "service:elasticsearch-ip-172-31-53-95" from=172.31.76.159:42350
Nov 09 16:19:59 ip-172-31-48-67 consul[755]: 2017/11/09 16:19:59 [ERR] http: Request PUT /v1/agent/check/pass/service:cassandra-ip-172-31-48-183?note=ok, error: Unknown check "service:cassandra-ip-172-31-48-183" from=172.31.84.81:21981
Nov 09 16:19:59 ip-172-31-48-67 consul[755]: 2017/11/09 16:19:59 [ERR] http: Request PUT /v1/agent/check/pass/service:zookeeper-ip-172-31-53-124?note=ok, error: Unknown check "service:zookeeper-ip-172-31-53-124" from=172.31.76.159:42350
Nov 09 16:20:02 ip-172-31-48-67 consul[755]: 2017/11/09 16:20:02 [ERR] http: Request PUT /v1/agent/check/pass/service:cassandra-ip-172-31-54-119?note=ok, error: Unknown check "service:cassandra-ip-172-31-54-119" from=172.31.84.81:21981
```

I've set up the ACL system, both node's in the cluster have their agent token set (with the necessary permissions - as shown in the ACL bootstrapping guide).

Looking at the indexes from `consul info` both servers do look like they're synced correctly... yet this new server doesn't know anything about the checks services are trying to check in on.

I'd expect the new server to join the cluster (which it has done so successfully), then sync all service and check info from the other server(s) in the cluster. Is this expectation incorrect?

Any ideas? I'd really appreciate some help understanding this!

**Comment by slackpad** [comment]
Hi @cmacrae the /v1/agent API is for working with services on a specific agent, so if you were running service X on node Y, you'd use the /v1/agent API on node Y to update a check for service X. All of the cluster-wide information for Consul is under the /v1/catalog and /v1/health APIs. The agent syncs its information up with the Consul servers to provide a global view, but /v1/agent should only be used by checks/services running on that agent. Does that make sense?

**Comment by cmacrae** [comment]
Hey @slackpad - thanks for the clarification. Yep, that makes sense 👍   
I'm using Joyent's Container Pilot for service orchestration, so I think I'll drop by there and see what they suggest for such a set-up.  
Thanks for your time; I'll close this off.
