### ISSUE TITLE
flaky tests

### ISSUE THREAD

**Issue by flyinprogrammer** [hashicorp/consul#3693]
Client: `1.0.1-rc1`
Server: `1.0.1-rc1`

### Operating system and Environment details

```
23:26 $ go version
go version go1.9.2 linux/amd64
```

```
23:27 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 17.10 (Artful Aardvark)
Release:	17.10
Codename:	artful
```

```
galago pro 2
3.5 GHz i7-7500U (2.7 up to 3.5 GHz – 4 MB Cache – 2 Cores – 4 Threads)
32 GB Dual Channel DDR4 at 2133MHz (2× 16 GB)
512 GB NVMe PCIe M.2 SSD
```

### Description of the Issue (and unexpected/desired result)
```
--- FAIL: TestAPI_CatalogNodes (1.58s)
	retry.go:116: values.go:22: verification for  at catalog_test.go:59:
```
```
--- FAIL: TestAPI_LockDestroy (1.80s)
	lock_test.go:215: err: failed to create session: Unexpected response code: 500 (Missing check 'serfHealth' registration)
```
```
--- FAIL: TestUiNodes (0.33s)
	ui_endpoint_test.go:97: bad: [0xc4200fd880 0xc4200fd8f0]
```
```
--- FAIL: TestStatsFetcher (0.49s)
	stats_fetcher_test.go:78: bad: map[string]*structs.ServerStats{"07c32b0d-21a3-885c-c062-c06ca9f8d119":(*structs.ServerStats)(0xc420bca8e0)}
```
```
--- FAIL: TestStatsFetcher (0.57s)
	stats_fetcher_test.go:78: bad: map[string]*structs.ServerStats{}
```
```
--- FAIL: TestPreparedQuery_Wrapper (0.73s)
	prepared_query_endpoint_test.go:2714: err: No path to datacenter
```
are all test failures I've gotten which don't seem to have ever been reported as issues in Github.

They did all eventually pass though:

```
23:39 $ make test
--> Checking for other consul instances
--> Building consul
mkdir -p pkg/linux_amd64/ bin/
go install -ldflags '-X github.com/hashicorp/consul/version.GitCommit=783a405d -X github.com/hashicorp/consul/version.GitDescribe=v1.0.1-rc1' -tags ''
cp /home/flyinprogrammer/Development/bin/consul bin/
cp /home/flyinprogrammer/Development/bin/consul pkg/linux_amd64
--> Running go vet
--> Running go test
go test -tags '' -i ./...
go test  -tags '' -timeout 5m -v ./... &>test.log ; echo $? > exit-code
PASS
```

so there's hope - let's make it great! 
I'm mostly opening this issue to gain clarity around:

1. Is this normal?
2. Are there better ways/environment to be running these tests?
3. How can I help?

### Reproduction steps
on an ubuntu box running 17.10 and go 1.9.2:

```
cd $GOPATH
mkdir -p $GOPATH/src/github.com/hashicorp
cd $GOPATH/src/github.com/hashicorp
git clone git@github.com:hashicorp/consul.git
cd consul
make test
```

**Comment by slackpad** [comment]
Hi @flyinprogrammer this is "normal" as we have some tests that depend on timing but definitely not ok :-) We can take a look and see what's up with these as your environment seems pretty reasonable. There are similar failures in Travis as well, so nailing these down by reworking them to be less timing sensitive (or using the testutil retry package if there's no good way to make them more deterministic) will help with our CI as well.

**Comment by edio** [comment]
@slackpad adding small delay to `TestAgent.Shutdown` before return workarounds flakiness for me

```
diff --git a/agent/testagent.go b/agent/testagent.go
index 2ce611fb..f8041f3c 100644
--- a/agent/testagent.go
+++ b/agent/testagent.go
@@ -230,8 +230,10 @@ func (a *TestAgent) Shutdown() error {
        }()*/
 
        // shutdown agent before endpoints
-       defer a.Agent.ShutdownEndpoints()
-       return a.Agent.ShutdownAgent()
+       err := a.Agent.ShutdownAgent()
+       a.Agent.ShutdownEndpoints()
+       time.Sleep(time.Millisecond * 20)
+       return err
 }
 
 func (a *TestAgent) DNSAddr() string {
```

Do you think it's something we could introduce to workaround the issue until properly fixed?
Almost every PR that is opened currently fails Travis CI. And I suspect, those which are not were run multiple times until CI passed.

**Comment by pearkes** [comment]
We've done a ton of work on test stability and CI is reliably green these days. Examples include #5376 and #5013, among many many others!
