### ISSUE TITLE
How to remove health check from consul

### ISSUE THREAD

**Issue by praveen12579** [hashicorp/consul#3694]
### `consul version` for both Client and Server
Client: No client
Server: consul1.0.0.
### `consul info` for both Client and Server

Server:
./consul agent -server -data-dir='/tmp/consul' -config-file='consul_config.json' -bootstrap-expect 1 -bind [private i/p] -client [private i/p] -ui &

### Operating system and Environment details
linux

### Description of the Issue (and unexpected/desired result)
How to remove health check from consul
I just want to register the services to consul and don't want to perform health check, so in order to do that what changes do I need to make?

**Comment by preetapan** [comment]
@praveen12579 Can you clarify what you mean by "health check" here? You can register a service without a healthcheck https://www.consul.io/api/agent/service.html though its not a recommended best practice.

**Comment by slackpad** [comment]
Closing since we never heard back.
