### ISSUE TITLE
deregister a service not work

### ISSUE THREAD

**Issue by pcleon** [hashicorp/consul#3703]
i want to deregister a service that no use anymore ,  but when i use deregister api, in the moment it works,
but in a while later it comes back again . 
is it a bug ?
how could i deregister or remove a service forever?

consul version is 1.0.0

````
[16:29:15 root@wo-sms ~]# curl -s localhost:8500/v1/catalog/services |jq
{
  "consul": [],
  "ngx": [
    "ngx"
  ],
  "squid": [
    "proxy"
  ]
}
[16:29:29 root@wo-sms ~]# curl -X PUT   http://localhost:8500/v1/catalog/deregister -d '{"node":"wo-sms","serviceid":"ngx"}'
true[16:29:33 root@wo-sms ~]# cus localhost:8500/v1/catalog/services |jqx"}'                                                    
{
  "consul": [],
  "squid": [
    "proxy"
  ]
}
[16:29:35 root@wo-sms ~]# curl -s localhost:8500/v1/catalog/services |jq
{
  "consul": [],
  "squid": [
    "proxy"
  ]
}
[16:29:38 root@wo-sms ~]# curl -s localhost:8500/v1/catalog/services |jq
{
  "consul": [],
  "ngx": [
    "ngx"
  ],
  "squid": [
    "proxy"
  ]
}
````

**Comment by slackpad** [comment]
Hi @pcleon if the agent is still running you will need to use the agent API on the agent where the service is registered - https://www.consul.io/api/agent/service.html#deregister-service. You can see https://www.consul.io/docs/internals/anti-entropy.html for more details about what's going on. Hope that helps!
