### ISSUE TITLE
Nodes can be marked failed when trying to leave

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3706]
We've seen reports from users with rapid node churn that sometimes even when a node does a graceful leave some of its peer nodes can mark it failed and some will mark it as left. This is difficult to reproduce but there are several factors that look like they contribute to this:

1. Consul agents in server mode have an unrelated-to-Serf delay after doing the leave and before shutting down via https://github.com/hashicorp/consul/blob/v1.0.1/agent/consul/server.go#L794-L800. This allows them more time for the leave to propagate via gossip while they still handle incoming probes from peers, preventing them from getting marked as failed. Consul agents in client mode don't have a corresponding mechanism. Internal to Serf there's a wait to make sure the leave is broadcast, but clients will exit right away so they may fail probes while the leave intent is propagating.

2. The Lamport time filtering can cause the leave event to be ignored if a node failed event already came in previously - https://github.com/hashicorp/consul/blob/v1.0.1/vendor/github.com/hashicorp/serf/serf/serf.go#L1035-L1038. This keeps the cluster from converging into the correct state eventually.

Addressing the first issue with a brief wait (~3 seconds) after the leave intent is broadcast should allow convergence even for massive 100k node clusters (https://www.serf.io/docs/internals/simulator.html) and is simple to implement.

To ensure the cluster arrives into a consistent state, even if the previous measure is insufficient, we should give priority to the leave intent event if we've gotten a previous node failed event. This will require a bit of special case logic but we can ensure that we apply the leave event even if we've gotten a failed event for the same Lamport time, no matter which order they come in.

**Comment by banks** [comment]
> To ensure the cluster arrives into a consistent state, even if the previous measure is insufficient, we should give priority to the leave intent event if we've gotten a previous node failed event.

@preetapan ISTR you looked into this or a related issue some time ago. The change in 6ad3147 is now in master but I'm not sure if there was anything done about the above point not linked here?

**Comment by jsosulska** [comment]
It's been almost 2 years with no response, and no users have reported or upvoted this. Going to close. If needed, please open a new issue, and reference this post.

Thank you.
