### ISSUE TITLE
Wrong in config document

### ISSUE THREAD

**Issue by jehunkim** [hashicorp/consul#3709]
Hello,

I found the wrong option in agent config page.

I tried to use 'serf_lan_bind' in this document https://www.consul.io/docs/agent/options.html#serf_wan_bind

But consul throw error 'Invalid config key'. 

So I'm looking it code in GitHub(https://github.com/hashicorp/consul/blob/master/agent/config/config.go), and I found It doesn't exist key in the code.

I think it have to change the document.

Thank you.

**Comment by yfouquet** [comment]
Hi @jehunkim,
It seems that the option still exist, but was renamed "serf_lan" (same goes for "serf_wan_bing" -> "serf_wan")
I have adjusted the documentation.

**Comment by slackpad** [comment]
Fixed in #3740.
