### ISSUE TITLE
TLS handshake timeout for HTTP checks

### ISSUE THREAD

**Issue by 123BLiN** [hashicorp/consul#3711]
Hello,

Not a bug just an information to think of, and maybe to add it somwhere in the consul playbook.
We have faced the issue on windows hosts when the CPU usage is above 95%.

Consul HTTP checks are failing with TLS handshake timeout error:
`"Get https://localhost: net/http: TLS handshake timeout"`
We were suspecting our applications endpoints but they were working pretty stable and fast, so it looks like consul process suffered from the lack of CPU time, so we've decided to increase consul agent process priority from "Normal" to "Above normal" - the issue was completely resolved. 

Hope this may help someone. 

Thanks,
Roman

**Comment by slackpad** [comment]
Thanks @123BLiN! I'm not sure where this would live in our docs, so I'll close this out, but Google will find it if folks run into a similar thing.
