### ISSUE TITLE
ACLs disabled

### ISSUE THREAD

**Issue by ArchontPnz** [hashicorp/consul#3713]
/etc/consul.d/config.json:
{
 "bind_addr": "***.***.***.240",
 "datacenter": "dc",
 "data_dir": "/var/consul",
 "encrypt": "***",
 "log_level": "INFO",
 "enable_script_checks": false,
 "enable_syslog": true,
 "enable_debug": true,
 "node_name": "ConsulClient",
 "acl_enforce_version_8": true,
 "server": true,
   "service": {"name": "Monit", "tags": ["monitoring"], "port": 8080},
 "rejoin_after_leave": true,
 "retry_join": [
    "***.***.***.240"
    ]
 }

ACL-config - /var/consul/master.json:
{
  "acl_datacenter":"dc",
  "acl_default_policy":"allow",
  "acl_down_policy":"allow",
  "acl_master_token":"********-****-****-****-************"
}

Run the following command: _consul agent -dev -bind ***.***.***.240 -config-dir /etc/consul.d -ui -client=***.***.***.240_

Log: https://gist.github.com/ArchontPnz/80b0581983412f6d5692ba074b140323

Why ACL disabled? What's my mistake?

**Comment by slackpad** [comment]
Hi @ArchontPnz the agent needs the `acl_datacenter` to be set as well, not just the servers. See https://www.consul.io/docs/guides/acl.html#bootstrapping-acls. Hope that helps!
