### ISSUE TITLE
Manual Script Auto Refresh on Consul

### ISSUE THREAD

**Issue by sundeepsid** [hashicorp/consul#3714]
Hello All,

Is there a way to auto refresh the consul ui. I just want to auto refresh nodes "health check" as the data changes frequently.

### `consul version` for both Client and Server
Client: `[10]`
Server: `[10]`

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!

**Comment by johncowen** [comment]
Hi @nwanjokuchikodi ,

To answer your question, 1.2.2 doesn't have autofreshing.

Our first objective was to reproduce the old Consul UI on a more modern codebase with an updated look and feel, whilst keeping new features to a minimum during this 'phase'.

I think we are now past that, so we are into a second 'phase'. Therefore you'll begin to see some of these new features make their way into the new UI over time. Features are likely to be added on a similar cadence to the main Consul binary releases so when I say 'over time' that might give you an idea of how regularly these new features are likely to be added.

There is upcoming work already done specifically related to your query, but I wouldn't want to comment quite yet on when it will be included in a release.

Overall I'm going to reopen this issue and I'll try to keep you updated here on this specific feature.

Thanks,

**Comment by johncowen** [comment]
Hi @sundeepsid and @nwanjokuchikodi 

Just to let you know there is work going on for this here:

https://github.com/hashicorp/consul/pull/5070

I'm collecting/linking issues related to autoupdating and UI blocking queries to that PR so that I can close them easily once we've merged it down, but if you want to give feedback or be updated when this lands that is the best place to follow progress for the moment.

Thanks,

John

**Comment by johncowen** [comment]
Hi @sundeepsi, @nwanjokuchikodi, @pdf and @sgrimm-sg

We've added live updates/auto update for the Catalog only (for the moment) in version 1.5. We are aware of some noisy clusters so we also made it off by default for the moment. You can enable it in the settings for the UI.

Future versions of the UI will move this to 'on by default' and also roll it out across the rest of the UI.

I'm going to close this issue as it specifically talks about heathchecks.

Thanks,

John
