### ISSUE TITLE
kv stored unexpected

### ISSUE THREAD

**Issue by wangping886** [hashicorp/consul#3715]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `0.7.5`
Server: `0.7.5`
### sorry , I can't recurrent what caused  kv stored like this and what know why results this. And what should I do to solve this phenomenon. The second picture present  when i click the first key ,
![image](https://user-images.githubusercontent.com/22444729/33306026-49189e76-d3d6-11e7-947b-7d74e85a715b.png)
![image](https://user-images.githubusercontent.com/22444729/33306746-616dc6f6-d3d9-11e7-9c95-f0a91b5e992b.png)

**Comment by discointheair** [comment]
Hi 
do you use consul-template somwhere?

**Comment by wangping886** [comment]
@discointheair  It seems  consul-template  has nothing to do with my question . but  I know  consul-template .

**Comment by discointheair** [comment]
May you coluld give some more information about the problem. 
The keys are as you expect them? 
Is your problem that if you click on the first key nothing happens? Because both pictures show the same keys. What says your browser address field about the current path? What happens if you use the KV API to get the keys?

**Comment by wangping886** [comment]
the first key in my first picture is empty string and when I click this key  the second picture show . maybe i put a  key `empty string`/foo/bar key caused this problem . but i never put that enough key under empty string

**Comment by discointheair** [comment]
OK. Now I understand. At which Level (URI) are you before/after clicking the first empty Key? How does it looks when you use the KV API instead of the GUI? Is the key also there, and what is its value?

**Comment by slackpad** [comment]
Closing since we never heard back. It looks like a key with a name like " " was created in this case, which is possible with Consul.
