### ISSUE TITLE
orbitz/consul-client

### ISSUE THREAD

**Issue by shekhar2709** [hashicorp/consul#3717]
I need an api help to store byte[] in kv, as we can do in zookeeper. I am using consul-client java api's. Please help

If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @shekhar2709 we don't support the orbitz/consul-client nor do we have a HashiCorp-supported Java API, you'll want to get help over on the project you are using. There are a few Java APIs listed on https://www.consul.io/downloads_tools.html as well. In general Consul doesn't care about the contents of keys, so any KV API should support putting binary data in there. Hope that helps!
