### ISSUE TITLE
Registering multiple containers on single host as Consul service

### ISSUE THREAD

**Issue by ccovarru** [hashicorp/consul#3718]
I apologize for the non-standard format of the issue, but it is more of a question that is unanswered elsewhere.

I have the following use case:

I have a Consul 1.0.0 cluster (3 nodes) running. I also have 3 hosts running Docker hosting multiple instances of app_a. For the sake of the example, I'll say I'm running three instances of the app on each host, running on ports 5001, 5002, and 5003 on each app. 

I'd like to register each one of the containers to a service in Consul. What is happening now is that every time the app tries to register itself as a service, it overwrites the previous data. Seems like Consul is only allowing a single instance of the service to be registered.

Is it possible to register multiple instances of a container running on one docker host as a service?

**Comment by skorhone** [comment]
I think that the answer that you are looking is in following fragment (copied from documentation)

A service definition must include a name and may optionally provide an id, tags, address, port, check, and enable_tag_override. **The id is set to the name if not provided**. It is required that all services have a unique ID per node, so if names might conflict then unique IDs should be provided.

You can register multiple instances on single host, if you assign a unique id on each instance of the service.

**Comment by slackpad** [comment]
Thanks @skorhone you are correct!
