### ISSUE TITLE
Consul client agent can't reconnect when server IPs change

### ISSUE THREAD

**Issue by surajrajpal** [hashicorp/consul#3722]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: 1.0.1
Server: 1.0.1

### `consul info` for both Client and Server
Client:
```
We use retry-join aws for the client 

```

Server:
```
3 server nodes constantly running which are autoscaled using amazon ecs to replace any/all failed nodes.
We use retry-join aws 
```

### Operating system and Environment details
AWS ECS - alpine linux v3.6
### Description of the Issue (and unexpected/desired result)

On failure of 3 consul server nodes (entire consul cluster) , the failed nodes are replaced by AWS ASG but the Consul client agents do not reconnect when the server ips are changed due to this. We have to restart the consul clients for it to work.  

### Reproduction steps
Stop/Terminate the consul servers. 
New consul server cluster is brought up by amazon ecs
The existing consul clients do not connect to the new consul servers. 

### Log Fragments or Link to [gist](https://gist.github.com/)

Server Logs: 

[gist] https://gist.github.com/surajrajpal/ac4ae3945b3aca89acabc5522e6dc8a0

Client Logs 
`2017/12/01 09:07:59 [WARN] manager: No servers available
    2017/12/01 09:07:59 [WARN] agent: Syncing service "ip-0.0.0.:ecs-service:81" failed. No known Consul servers
    2017/12/01 09:07:59 [ERR] agent: failed to sync changes: No known Consul servers
    2017/12/01 09:07:59 [WARN] manager: No servers available
`
`2017/12/01 09:19:07 [WARN] agent: Syncing service "ip-0.0.0.0:ecs-service:81" failed. No known Consul servers
    2017/12/01 09:19:07 [ERR] agent: failed to sync changes: No known Consul servers
    2017/12/01 09:19:07 [WARN] manager: No servers available`

Please contact for any further details.

**Comment by slackpad** [comment]
Hi @surajrajpal in this case it looks like you are tagging only the server instances so the new servers join each other but don't join up with any of the clients. If you tag some client agents as well, then the servers will learn about the rest of the cluster when they come up and the clients will start using the new servers right away.

**Comment by surajrajpal** [comment]
Thanks @slackpad . It works fine now after tagging the clients.
