### ISSUE TITLE
Notification Alerts on Health Check Warning or Critical Status

### ISSUE THREAD

**Issue by bhagathk** [hashicorp/consul#3724]
Is there any functionality in Consul to generate Notifications when there is any warning and critical status from the Health Checks?

### `consul version` for both Client and Server
Client: `[10]`
Server: `[10]`

**Comment by JeeveshN** [comment]
You should look into concept of watchers https://www.consul.io/docs/agent/watches.html.
These can fire up a script that would generate the notification for you.

**Comment by slackpad** [comment]
Consul doesn't have anything like this built in, but you could use watchers as @JeeveshN suggested, or one of the projects like https://github.com/AcalephStorage/consul-alerts or https://github.com/kyhavlov/consul-alerting. Hope that helps!
