### ISSUE TITLE
help: why register node address only 127.0.0.1 ?

### ISSUE THREAD

**Issue by ngxlua** [hashicorp/consul#3725]
### `consul version` for both Client and Server

Client/Server: `current master / dev mode`

### Operating system and Environment details

```
Ubuntu 16.04 X64
```

### Description of the Issue (and unexpected/desired result)

i register for the service like this `/v1/agent/service/register`

```
curl -X PUT \
  http://127.0.0.1:8500/v1/agent/service/register \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
    "ID": "test:80:220.181.57.217",
    "Name": "test",
    "Address": "220.181.57.217",
    "Port": 80
}'
```

but, `node.Address` only `127.0.0.1` in health api response, i thought it would be `220.181.57.217`:

```
[
    {
        "Node": {
            "ID": "c6954f4f-452c-7d72-590e-89e99aeb0ddb",
            "Node": "test.local",
            "Address": "127.0.0.1",
            "Datacenter": "dc1",
            "TaggedAddresses": {
                "lan": "127.0.0.1",
                "wan": "127.0.0.1"
            },
            "Meta": {
                "consul-network-segment": ""
            },
            "CreateIndex": 5,
            "ModifyIndex": 6
        },
        "Service": {
            "ID": "test:80:220.181.57.217",
            "Service": "test",
            "Tags": [],
            "Address": "220.181.57.217",
            "Port": 80,
            "EnableTagOverride": false,
            "CreateIndex": 7,
            "ModifyIndex": 7
        },
       ...
]
```

**Comment by discointheair** [comment]
Hi
The "Node" is the address of the consul node. The Service Address is the address which returns the/a backend of your service. Where do register the service? At a consul client or server?
If its registered at a server the 127.0.0.1 make sense.  If its registered at a client there should be set the consul client agent IP.

**Comment by slackpad** [comment]
That's correct - this should be the node's address, which comes from the [`-bind`](https://www.consul.io/docs/agent/options.html#_bind) configuration usually, and there's also an [`-advertise'](https://www.consul.io/docs/agent/options.html#_advertise) configuration for special situations. Hope that helps!
