### ISSUE TITLE
Autopilot's cleanup_dead_servers configuration not working

### ISSUE THREAD

**Issue by sbasyal** [hashicorp/consul#3730]
`consul version`: `1.0.0`

While trying to use the Autopilot's [cleanup_dead_servers](https://www.consul.io/docs/agent/options.html#cleanup_dead_servers) Configuration, it is not working.

I tried the following configuration before bootstrapping the cluster:

```
    "autopilot": { 
        "cleanup_dead_servers": false,
        "last_contact_threshold": "500ms"
    },
```
And I can see that `last_contact_threshold` is set, but the `cleanup_dead_servers` is still false, which I can verify with the `consul operator autopilot get-config` command:

```
$ consul operator autopilot get-config
CleanupDeadServers = true
LastContactThreshold = 500ms
MaxTrailingLogs = 250
ServerStabilizationTime = 10s
RedundancyZoneTag = ""
DisableUpgradeMigration = false
UpgradeVersionTag = ""
```

**Note** that the only catch to using Autopilot Configuration is that it has to be in the leader's config when the cluster is bootstrapped for the first time. Also, if we just try to add that config to an *existing* cluster it won't do anything. But `CleanupDeadServers` seems always true unless we run `consul operator autopilot set-config -cleanup-dead-servers=false`.

**Comment by slackpad** [comment]
@kyhavlov can you take a look at this one? Might need to update Nomad as well.
