### ISSUE TITLE
Serf health fails after agent failure but health check passes

### ISSUE THREAD

**Issue by gamefundas** [hashicorp/consul#3734]
Consul Server/Client version 0.6.4

#2740, #1790 talks about this but I am not sure if the original issue was reported for a specific version and fixed in a release. I am getting a lot of these in 0.6.4.

The health check API (/v1/health/checks/service.name) also returns the bad node as passing/healthy. My spring cloud application uses the java ConsulClient API, it returned the bad node as healthy. Hoping upgrading Consul would fix this. Can someone (@mikezh15, @slackpad) confirm.

Thanks
Andy

**Comment by slackpad** [comment]
Hi @gamefundas when a node is unhealthy its health checks will stay in their last state, but the `serfHealth` check will move to the failed state. The `serfHealth` status is maintained by the cluster itself and the Consul servers, and the rest of the health checks are updated by the agent which might not be available. Consul internally ANDs all the node and servce-level health checks statuses to determine overall health, so the `serfHealth` check moving to failed takes out failed nodes.

This has always been Consul's behavior so #2740 and #1790 were just clarifying this. Hope that helps!
