### ISSUE TITLE
query a set of services by tags

### ISSUE THREAD

**Issue by Lfengjie** [hashicorp/consul#3739]
### `consul version` for both Client and Server
Client: `[v1.0.0]`
Server: `[v1.0.0]`

I can not get a list of Services by tags, I can not find API about this.

**Comment by yfouquet** [comment]
Hi @Lfengjie,
Does it concern Go or Http Api?
Regarding HTTP, you can do .../v1/catalog/services/<my-service>?tag=<my-tag> (see https://www.consul.io/api/catalog.html#list-nodes-for-service)
Regarding Go, you can just specify the tag (see https://godoc.org/github.com/hashicorp/consul/api#Catalog.Service).
Did i understand well you question, or you are looking for something different?

**Comment by slackpad** [comment]
Closing since we didn't hear back, and @yfouquet provided some good pointers.

**Comment by shane-axiom** [comment]
To clarify, this issue asked about getting _all services by tag_. The suggested answers relate to filtering nodes for a specific service by tag. It doesn't appear that it's currently possible to [lisdt services](https://www.consul.io/api-docs/catalog#list-services) and filter by tag.

**Comment by blake** [comment]
Hi @shane-axiom, PR #11742 will add support for filtering services by tag from the list services API.
