### ISSUE TITLE
delete acl with slashes

### ISSUE THREAD

**Issue by discointheair** [hashicorp/consul#3741]
`consul version` for both Client and Server
1.0.0

Hi

With a script bug I created a ACL ID with a slash:

   "ID": "/tmp/out.txt",
    "Name": "shortname",
    "Type": "client",

Now I am not able to delete the ACL with GUI or API.
For services it seems to be possible with upload json data:
[service with slash](https://github.com/hashicorp/consul/issues/1096)

But with /v1/acl/destroy I was not able to use it. 

Any ideas?

Thank you

**Comment by slackpad** [comment]
Hi @discointheair there's currently no way to delete that given how the Go HTTP router works. This will be fixed once https://github.com/hashicorp/consul/issues/2027 is in place, since all ACLs will have a GUID that can be used for CRUD operations.
