### ISSUE TITLE
ACL API: Accept token Rules values as JSON objects

### ISSUE THREAD

**Issue by duncanhall** [hashicorp/consul#3748]
**Consul version**: `1.0.1` 

When making `PUT` requests to the [ACL API](https://www.consul.io/api/acl.html) we are able to declare token rules as string encoded HCL or JSON. Eg:

**Encoded HCL**
```json
{
  "Name": "Example Token",
  "Type": "client",
  "Rules": "key \"\" { policy = \"read\" } service \"\" { policy = \"write\"} node \"\" { policy = \"write\"}"
}
```
**Encoded JSON**
```
{
  "Name": "Example Token",
  "Type": "client",
  "Rules": "\"key\": { \"\": { \"policy\": \"read\" } },  \"service\": { \"\": { \"policy\": \"write\" } }, \"agent\": { \"\": { \"policy\": \"write\" } }"
}
```
While in theory it's nice to have both HCL and JSON supported, in practice the required escape sequences make it feel like writing neither HCL nor JSON, even for simple examples like above. Trying to update and test new token rules becomes overly complicated.

As the rest of the token is already provided as JSON, it would be much easier to interact with the API if Rules could simply be provided as JSON objects:

```json
{  
  "Name":"Example Token",
  "Type":"client",
  "Rules":{  
    "key":{  
      "":{  
        "policy":"read"
      }
    },
    "service":{  
      "":{  
        "policy":"write"
      }
    },
    "agent":{  
      "":{  
        "policy":"write"
      }
    }
  }
}
```

**Comment by slackpad** [comment]
This will be mitigated somewhat by #3208 but it's still worth considering since the escaping is tricky.

**Comment by abohne** [comment]
This really tripped me up.  It's really not intuitive that would need to specify the rules the as an escaped JSON string, when you're already submitting a JSON payload.

**Comment by ChipV223** [comment]
Closing this since with the release of v1.4.0 which include a revamp of the ACL System, creating policies for ACL tokens has become more intuitive. 

But do reach out if you have any additional questions or concerns!
