### ISSUE TITLE
Cannot read config file when referenced through nested symbolic links 

### ISSUE THREAD

**Issue by HCanber** [hashicorp/consul#3753]
Version: __1.0.1__, __1.0.2__

### Description of the Issue (and unexpected/desired result)

Consul does not start as it's unable to read config files for the specific structure below. It works in 1.0.0. 

I have a structure with symbolic links that looks like this:

```
/
+-- consul
    +-- config
        +-- dir
        |   +-- server.json
        +-- link_dir -> dir
        +-- server.json -> link_dir/server.json
```

This kind of structure is created by Kuberenetes when mounting volumes, see https://github.com/kelseyhightower/consul-on-kubernetes/issues/23
The structure above is exactly the same as in the linked issue, except I've simplified the names.

### Reproduction steps

1. Create a file named `Dockerfile` with the content

    ``` dockerfile
    FROM consul:1.0.1
    RUN mkdir -p /consul/config/dir && \
      echo '{"node_name":"foobar"}' > /consul/config/dir/server.json && \
      ln -s dir /consul/config/link_dir && \
      ln -s link_dir/server.json /consul/config/server.json
    ```

1. Build image:

    ``` sh
    docker build -t consul-test .
    ```

1. See content of `/consul/config`

    ``` sh
    docker run -t --name=dev-consul --entrypoint ls consul-test -al /consul/config/  &&\
    docker rm dev-consul >/dev/null
    ```

    ```
    total 12
    drwxr-xr-x    1 consul   consul        4096 Dec 15 15:40 .
    drwxr-xr-x    1 consul   consul        4096 Dec  1 19:14 ..
    drwxr-xr-x    2 root     root          4096 Dec 15 15:40 dir
    lrwxrwxrwx    1 root     root             3 Dec 15 15:40 link_dir -> dir
    lrwxrwxrwx    1 root     root            20 Dec 15 15:40 server.json -> link_dir/server.json
    ```

1. See the content of `server.json`

    ``` sh
    docker run -t --name=dev-consul --entrypoint cat consul-test  /consul/config/server.json  &&\
    docker rm dev-consul >/dev/null
    ```

    ``` json
    {"node_name":"foobar"}
    ```

1. Start consul with `server.json` as config file

    ``` sh
    docker run --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 consul-test agent -dev -client 0.0.0.0 -config-file=/consul/config/server.json -log-level=TRACE ;\
    docker rm dev-consul >/dev/null
    ```

    It fails with:

    ```
    ==> Found address '172.17.0.2' for interface 'eth0', setting bind option...
    ==> config: ReadFile failed on /consul/config/link_dir: read /consul/config/link_dir: is a directory
    ```

1. To prove that it works in version 1.0.0, modify the content of `Dockerfile` to use image `consul:1.0.0`. Build the image and start Consul:

    ``` sh
    docker build -t consul-test .
    docker run --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 consul-test agent -dev -client 0.0.0.0 -config-file=/consul/config/server.json -log-level=TRACE ;\
    docker rm dev-consul >/dev/null
    ```

   Consul will start correctly. Press `Ctrl+C` to exit

1. To cleanup execute

    ``` sh
    docker rmi consul-test
    ```

I have verified that it does not work in version 1.0.2 either. I used 1.0.1 in this example as 1.0.2 hasn't been released to Docker Hub.

**Comment by fastest963** [comment]
The problem is that the consul DockerFile by default (without a way to prevent it) looks for config files in `/consul/config` (see: https://github.com/hashicorp/docker-consul/blob/master/0.X/docker-entrypoint.sh#L45). Since you have non files in there, it fails. I'm working on a PR.
