### ISSUE TITLE
Feature Request: On Demand Health Check

### ISSUE THREAD

**Issue by madhugilla** [hashicorp/consul#3773]
Hello,

It would be great if Consul API/Agent provide facility to do an OnDemand health check rather than waiting for Consul to check at the configured health check Interval.

Thanks -Madhu

**Comment by slackpad** [comment]
Hi @madhugilla can you expand a little more on your use case? Are you thinking of an API that tells Consul to immediately run one of its existing registered health checks?

**Comment by madhugilla** [comment]
@slackpad  exactly, and also maybe a button on the UI when clicked will do the same.

**Comment by kyhavlov** [comment]
@madhugilla Can you explain why you would want to trigger it this way instead of relying on the built-in intervals in Consul?

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.

**Comment by madhugilla** [comment]
i can verify the status of a service on an ondemand basis, rather than wait for consul to tell me.

**Comment by eugeniyk** [comment]
@kyhavlov / @pearkes current use case - deployments / traffic move

I'd like to verify "deep health check" of my server by calling endpoint and underlying services to verify that my connectivity is still work, classes are loaded, etc

It's not a lightweight check so I can't run it periodically - instead I'd like to run them on demand
Would be very nice if you can expose such API
