### ISSUE TITLE
"Catalog.Register" RPC failed to server. rpc error making call: rpc error making call: ACL not found

### ISSUE THREAD

**Issue by tahaiqbalkhan9** [hashicorp/consul#3779]
### `consul version` for both Client and Server
I have 3 consul, running in server mode
6 consul running in client mode in which two of them are 0.6.4 and 4 of them are at version 1.0.1.
 
2 x Client: `0.6.4`
4 x Client: `1.0.1`
Server: `1.0.1`

### `consul info` for both Client and Server
Client:
`Node        Address             Status  Type    Build  Protocol  DC   Segment
qmapsvs100  172.61.53.32:8301   alive   server  1.0.1  2         dc1  <all>
qmapsvs98   172.61.53.30:8301   alive   server  1.0.1  2         dc1  <all>
qmapsvs99   172.61.53.31:8301   alive   server  1.0.1  2         dc1  <all>
QMWBSVS51   172.61.53.51:8301   alive   client  0.6.4  2         dc1  <default>
QMWBSVS52   172.61.53.52:8301   alive   client  0.6.4  2         dc1  <default>
qmapsvs101  172.61.51.114:8301  alive   client  1.0.1  2         dc1  <default>
qmapsvs102  172.61.51.115:8301  alive   client  1.0.1  2         dc1  <default>
qmapsvs103  172.61.51.116:8301  alive   client  1.0.1  2         dc1  <default>
qmapsvs104  172.61.53.66:8301   alive   client  1.0.1  2         dc1  <default>
``
### Operating system and Environment details
CentOS 7.3

I have been getting these error in log files of consul. I am trying to register a service in consul using json file:

`Jan  3 13:46:01 pmapsvs101 consul: 2018/01/03 13:46:01 [WARN] agent: Syncing service "idmoccurrences" failed. rpc error making call: rpc error making call: ACL not found

Jan  3 13:46:01 pmapsvs101 consul: 2018/01/03 13:46:01 [ERR] agent: failed to sync remote state: rpc error making call: rpc error making call: ACL not found

Jan  3 13:46:01 pmapsvs101 consul[13409]: agent: Syncing service "idmoccurrences" failed. rpc error making call: rpc error making call: ACL not found

Jan  3 13:46:01 pmapsvs101 consul[13409]: agent: failed to sync remote state: rpc error making call: rpc error making call: ACL not found

Jan  3 13:46:05 pmapsvs101 consul[13409]: http: Request GET /v1/agent/self, error: Permission denied from=127.0.0.1:64357
`

**Comment by slackpad** [comment]
Hi @tahaiqbalkhan9 it looks like you have ACLs enabled but you aren't passing a valid token. For services you can supply a `token` field in the JSON file to be used, or else the agent's configured [`acl_token`](https://www.consul.io/docs/agent/options.html#acl_token) will be used. Similar for the /v1/agent/self call - you need to pass a token with node read permissions. Please take a look at the ACL guide which has details on using Consul's ACL system. Hope that helps!

**Comment by tahaiqbalkhan9** [comment]
In my server and client, configuration I am using **acl_agent_token** and that doesn't seem to take effect for json service files. 
Below is Agent token ACL:
`node "" { policy = "write" }
service "" { policy = "write" }
agent "" { policy = "write" } `

And my service file:
`{
  "service": {
    "token": "708df16c-ada4-56e8-aw8e-c41c60e6e84",
    "id": "serviceid",
    "name": "servicename",
    "address" : "abc.co.nz",
    "port": 8180,
    "check": {
      "http": "http://abc.co.nz:8180/service/health",
      "interval": "10s",
      "timeout": "6s"
    }
  }
}`

And Service Token ACL:
`service "idmoccurrences" {
  policy = "write"
}
`
But I am able to register services using the same **acl_agent_token** using API.

Not sure why the agent is not acknowledging the **acl_agent_token**?

**Comment by slackpad** [comment]
The `acl_agent_token` is only used for the agent's own registration of its node record in the catalog, it doesn't apply to any of the user-supplied service registrations. The `acl_token` is used for those. Please see https://www.consul.io/docs/guides/acl.html#acl-agent-token for some more details.
