### ISSUE TITLE
Web UI memory leak

### ISSUE THREAD

**Issue by vasily-kirichenko** [hashicorp/consul#3784]
I had this page opened in Firefox 57 for about a day:

![image](https://user-images.githubusercontent.com/873919/34609276-2003359e-f22d-11e7-8201-265028bb9ef7.png)

After that firefox.exe consumes ~6GB of memory, after refreshing (F5) the Consul UI page it dropped to 2GB.

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full rewrite, so we'll make sure this is included then!
