### ISSUE TITLE
Zero RTT measurement errors on Windows

### ISSUE THREAD

**Issue by slackpad** [hashicorp/consul#3789]
This captures the forward work from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/consul-tool/mXjkW9vGLws/xKiLcbUjEQAJ, where a user running Consul 1.0.2 reported seeing:

```
2018/01/02 22:07:16 [ERR] serf: Rejected coordinate from host1: round trip time not in valid range, duration 0s is not a positive value less than 10s
2018/01/02 22:07:17 [ERR] serf: Rejected coordinate from host2: round trip time not in valid range, duration 0s is not a positive value less than 10s
2018/01/02 22:07:18 [ERR] serf: Rejected coordinate from host3: round trip time not in valid range, duration 0s is not a positive value less than 10s
```

This should have been fixed by #3704, though this user is on Windows. Maybe the monotonic time granularity is too high?

We should see if we can figure out the root cause, and reduce that ERR level to DEBUG (or even TRACE) since it's not ERR-worthy.

**Comment by calinah** [comment]
Hi is there a fix for this in the meantime? right now I am getting flooded with this messages - I'm running consul on k8s on gke so it's just windows related error.
