### ISSUE TITLE
Provide binaries for FreeBSD

### ISSUE THREAD

**Issue by tbartelmess** [hashicorp/consul#380]

**Comment by ryanuber** [comment]
This will be made much easier once Consul does not rely on cgo. We should then be able to cross-compile to any given platform. This is on our roadmap, and we are targeting 0.6.

**Comment by sean-** [comment]
Speaking of, has consul/hashicorp thought about how it is going to manage its dependencies? Something like nut is appealing and being used internally to manage vendor dependencies for binaries. ? -sc

https://github.com/jingweno/nut

-- 
Sean Chittenden

**Comment by tarrant** [comment]
As long as we are bike shedding over dependency management I'll say that Godeps has been solid and has worked extremely well for us. In fact my scripts to build consul currently use Godeps to vendor consul.

**Comment by sean-** [comment]
It's actually less bike shedding vs concern over the official freebsd port and the lax way go manages the versioning of its dependencies, and the security complications that stem from that reality. 

-- 
Sean Chittenden

**Comment by armon** [comment]
Closing this for now, but when we go pure-Go (0.6) this will be easy!
