### ISSUE TITLE
Consul federation doesn't route traffic to remote datacenter on client node failing

### ISSUE THREAD

**Issue by deepm718** [hashicorp/consul#3800]
**Expectation is when client service or client nodes failed in any datacenter then the incoming traffic 
  should be route to remote datacenter.**

**I've 2 datacenters [dc1, dc2], both have been joined using join -wan(consul join -wan server1 server2 serverN)**

**Using Fabio for load balancing.**  

**Consul Federation(Basic) For remote datacenter query forwarding.**

**consul geo failover**
  Consul geo working for DNS QUERY but not routing to remote dc for web traffic.

**Consul Geo prepared query:**
             curl \
               --request POST \
              --data \
              '{
              "Name": "api",
             "Service": {
             "Service": "httpserver",
             "Tags": ["urlprefix-/"],
             "Failover": {
             "Datacenters": ["dc1", "dc2"]
            }
          }
      }' http://127.0.0.1:8500/v1/query

**My Infra:** 
3 Consul servers each datacenters.
2 web servers in back-end with registered their services and health checks on consul 
   servers in each datacenter.
In each datacenter services registered with same name & different ServiceID
**Server Version:** Consul v1.0.2
**Client Version:**  Consul v1.0.2 

**Client service and health checks:**  httpserver.json
     {
  "service": {
                   "id": "SERVICE-HTTP-WEB1",
                  "name": "httpserver",
                  "tags": ["urlprefix-/"],
                  "port": 8000,
                  "check": {
                  "id": "server_check",
                  "name": "CHeck_Nginx",
                  "http": "http://localhost:8000",
                  "interval": "5s",
                  "timeout": "1s"
                  }
            }
}

**In each datacenter incoming web traffic routed to back-end nginx servers by fabio load balancer.**

The issue is When all of client Nginx web servers failed or all client nodes get down in any datacenter, The traffic should be forwarded to remote datacenter. instead there in logs i see:
**logs:   [WARN] No route for localhost:9999/**

**Is there i'm missing anything??**

**When query consul members -wan:**
## Consul start:
    /consul agent \
    -advertise=10.139.80.88 \
    -bind=0.0.0.0 \
    -advertise-wan=139.59.68.32 \
    -bootstrap-expect=3 \
    -client=0.0.0.0 \
    -data-dir=/var/lib/consul \
    -config-dir=/etc/consul.d/server \
    -server \
    -ui

**config file: config.json**
  {
    "server": true,
    "datacenter": "dc2",
    "data_dir": "/var/lib/consul",
    "log_level": "INFO",
    "enable_syslog": true,
    "translate_wan_addrs": true,     # **(It doesn't affect whether apply or not  )**
    "retry_join": ["10.139.80.89", "10.139.80.87"]      # **(registered proper using private/public as well)**
   }

**consul members -wan [correct info]**

  Node              Address               Status  Type    Build  Protocol  DC   Segment
  dc1-server-0.dc1  10.139.80.88:8302  alive   server  1.0.2  2         dc1  <all>
  dc1-server-1.dc1  10.139.80.89:8302   alive   server  1.0.2  2         dc1  <all>
  dc1-server-2.dc1  10.139.80.87:8302    alive   server  1.0.2  2         dc1  <all>
  dc2-server-0.dc2  10.130.71.114:8302     alive   server  1.0.2  2         dc2  <all>
  dc2-server-1.dc2  10.130.71.113:8302     alive   server  1.0.2  2         dc2  <all>
  dc2-server-2.dc2  10.130.71.115:8302    alive   server  1.0.2  2         dc2  <all> 
  
**[ Registered with both private and public ip as well.. No issue with server registration as lan as well in wan]**

**_When i query for remote datacenter or vice-versa result is correct._**
dig @localhost -p 8600 httpserver.service.dc2.consul

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @localhost -p 8600 httpserver.service.dc2.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47869
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;httpserver.service.dc2.consul.	IN	A

;; ANSWER SECTION:
httpserver.service.dc2.consul. 0 IN	A	10.139.240.239      **[NGINX RUNNING ]**
httpserver.service.dc2.consul. 0 IN	A	10.139.48.49          **[NGINX RUNNING ]**

;; Query time: 43 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Sun Jan 14 14:10:31 UTC 2018
;; MSG SIZE  rcvd: 90

**Comment by slackpad** [comment]
Hi @deepm718 Consul supports failover via prepared queries via DNS or the prepared query API, but I think Fabio would need to implement similar functionality or be enhanced to understand the results of a prepared query. This is something that would need to be done on the Fabio side. I'll cc @magiconair on here for thoughts.

**Comment by deepm718** [comment]
Hi James,Thank you so much for looking into, you are right, The prepared query helped me in same.   25.01.2018, 06:24, "James Phillips" <notifications@github.com>:Hi @deepm718 Consul supports failover via prepared queries via DNS or the prepared query API, but I think Fabio would need to implement similar functionality or be enhanced to understand the results of a prepared query. This is something that would need to be done on the Fabio side. I'll cc @magiconair on here for thoughts.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
