### ISSUE TITLE
Replacement of HTTP checks, TTL check, failed

### ISSUE THREAD

**Issue by firerain-fd** [hashicorp/consul#3803]
Hello.
There is a "Test" service.
The "Test" service has an HTTP check.
If I want to register a TTL check for the "Test" service instead of HTTP, without deleting the service in the directory, nothing happens.
The service remains with HTTP verification.
If I do a turnover, when the service has a TTL check and I register an HTTP check, without the service being removed from the directory, everything goes well, the TTL check is replaced by an HTTP check.

Registration with the following parameters:
notes = "Check TTL";
TTL = "2s";
Name = "Service 'Test' TTL check";
DeregisterCriticalServiceAfter = "168h";

**Comment by slackpad** [comment]
Hi @firerain-fd if you are using configuration files you can update the config file with the new check definition and then to a `consul reload` to pick up the changes. If you are using the API like https://www.consul.io/api/agent/check.html you can remove the check and add a new one. Hope that helps!
