### ISSUE TITLE
Error starting userland proxy

### ISSUE THREAD

**Issue by eddamalique01** [hashicorp/consul#3809]
- [ ] root@edwin-Vostro-3900:/home/admin# sudo docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h agent-one progrium/consul -server -bootstrap
docker: Error response from daemon: driver failed programming external connectivity on endpoint zen_hypatia (cd6020c7bbff040f20ae1ab5e5a24225a71915266e20e45ad30647788179c779): Error starting userland proxy: listen udp 0.0.0.0:8600: bind: address already in use.
ERRO[0000] error waiting for container: context canceled 
root@edwin-Vostro-3900:/home/admin# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
2d5f56ac4f96        progrium/consul     "/bin/start -serve..."   6 seconds ago       Created                                 zen_hypatia
root@edwin-Vostro-3900:/home/admin# sudo docker run -p 8400:8400 -p 8500:8500 -p 8800:53/udp -h agent-one progrium/consul -server -bootstrap
docker: Error response from daemon: driver failed programming external connectivity on endpoint peaceful_banach (6a026c76af5201532f4efb140b31cb25114ff7e991f1950c9283748c3839df67): Error starting userland proxy: listen tcp 0.0.0.0:8500: bind: address already in use.
ERRO[0000] error waiting for container: context canceled 
root@edwin-Vostro-3900:/home/admin# sudo docker run -p 8400:8400 -p 8500:8500 -p 8800:53/udp -h agent-one progrium/consul -server -bootstrap
docker: Error response from daemon: driver failed programming external connectivity on endpoint eloquent_torvalds (f61407a3f0070d01fcb8e22c4f6e51a5b7b38872d35c6bcb6c65b7bc84e8528f): Error starting userland proxy: listen tcp 0.0.0.0:8500: bind: address already in use.
ERRO[0001] error waiting for container: context canceled 
root@edwin-Vostro-3900:/home/admin# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
766c5e7d27a8        progrium/consul     "/bin/start -serve..."   6 seconds ago        Created                                 eloquent_torvalds
f3fd604fe5f9        progrium/consul     "/bin/start -serve..."   35 seconds ago       Created                                 peaceful_banach
2d5f56ac4f96        progrium/consul     "/bin/start -serve..."   About a minute ago   Created                                 zen_hypatia
root@edwin-Vostro-3900:/home/admin# netstat -nap|grep 8500
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN      31508/consul    
unix  2      [ ACC ]     STREAM     LISTENING     1141941  7941/unity-scope-lo @admin-com.canonical.Unity.Scope.applications.T16622732985002
unix  3      [ ]         STREAM     CONNECTED     1141943  7941/unity-scope-lo @admin-com.canonical.Unity.Scope.applications.T16622732985002
root@edwin-Vostro-3900:/home/admin# netstat -nap|grep 8600
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      31508/consul    
udp        0      0 127.0.0.1:8600          0.0.0.0:*                           31508/consul    
If

 you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by eddamalique01** [comment]
Do any one has an idea on how I can get rid of the above error.

**Comment by Cardds** [comment]
`listen udp 0.0.0.0:8600: bind: address already in use.`

Rebind the ports of the new container to ports that are not in use. Or, stop what service is using those ports, which, from your netstat command, appears to be a conflicting consul service, PID 31508.

**Comment by slackpad** [comment]
Agree with @Cardds on this one - hope that helps!
