### ISSUE TITLE
DNS: SSHFP record support for nodes

### ISSUE THREAD

**Issue by ajf** [hashicorp/consul#381]
Would it be possible and reasonable to add SSHFP record support when querying nodes?

Consul agent could configure some external handler for retrieving the SSH fingerprint which would generally look something like this:

```
# ssh-keygen -r [Host Key]
/etc/ssh/ssh_host_rsa_key.pub IN SSHFP 1 1 99a1f1d0f418ded803a9f62f0a511a381a605
/etc/ssh/ssh_host_rsa_key.pub IN SSHFP 2 1 e8bb1f02f0e9e8e7eaecb0489eda02baf11ca2a2
```

Each node could then publish their own SSHFP records which clients could use to validate the identity of the host when SSHing.

Good idea/Bad idea?

**Comment by slackpad** [comment]
Closing this out since we haven't had other requests for it, and Vault now offers some SSH support so it would be unlikely we'd add this to Consul.
