### ISSUE TITLE
Telemetry documentation is outdated

### ISSUE THREAD

**Issue by zoltan-toth-mw** [hashicorp/consul#3810]
### Description of the Issue (and unexpected/desired result)
Some documented metrics are no longer available (i.e.: consul.raft.state.leader) while new metrics are not documented (i.e.: consul.memberlist.probeNode)  on https://www.consul.io/docs/agent/telemetry.html

### `consul version` for both Client and Server
Server: Consul v1.0.2

**Comment by whit537** [comment]
Thanks, @zoltan-toth-mw. Up for making a PR? :)

**Comment by zoltan-toth-mw** [comment]
Nah, I'm busy with our own systems  :)

**Comment by whit537** [comment]
Fair enough. :)

**Comment by pearkes** [comment]
I believe these missing metrics were filled in with https://github.com/hashicorp/consul/pull/4335. Thanks!
