### ISSUE TITLE
[Feature Request] Add a Annotations filed in Consul Service Definition

### ISSUE THREAD

**Issue by weiwei04** [hashicorp/consul#3811]
Current service definition is like 
```json
{
  "redis": {
    "ID": "redis",
    "Service": "redis",
    "Tags": [],
    "Address": "",
    "Port": 8000
  }
}
```

How about add a Annotations filed, so user can store some metadata in service definition, and consul needn't to interpret.

```json
{
  "redis": {
    "ID": "redis",
    "Service": "redis",
    "Tags": [],
    "Annotations": {
        "weights": "1"
    },
    "Address": "",
    "Port": 8000
  }
}
```

In our use case, we use nginx + lua_module to get service instances from consul. We'd like to store the instance's weight into `Annotations` when register service, so that, the nginx + lua_module can set instance's weight by interpret the `Annotations` filed.

**Comment by slackpad** [comment]
Hi @weiwei04 thanks for opening an issue - I'm going to close this in favor of https://github.com/hashicorp/consul/issues/1107, which we can hopefully address pretty soon. We are planning on adding a limited KV field for services, like we did for nodes via https://www.consul.io/docs/agent/options.html#node_meta, which should hit your use case as well.
