### ISSUE TITLE
Cluster logs show: agent: Coordinate update error: No cluster leader

### ISSUE THREAD

**Issue by dpgaspar** [hashicorp/consul#3812]
We have a 3 node cluster that is showing on the logs the following error messages:

"agent: Coordinate update error: No cluster leader"
"consul.acl: Failed to get policy from ACL datacenter: No cluster leader"

No problems or impact found, we are using consul-template. These logs entries appeared and disappeared.

### `consul version` for both Client and Server
Client: 1.0.0
Server: 0.9.3

Server:
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 112c060
	version = 0.9.3
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.25.138.57:8300
	server = true
raft:
	applied_index = 2876209
	commit_index = 2876209
	fsm_pending = 0
	last_contact = 17.911658ms
	last_log_index = 2876209
	last_log_term = 521
	last_snapshot_index = 2874639
	last_snapshot_term = 521
	latest_configuration = [{Suffrage:Voter ID:10.25.138.57:8300 Address:10.25.138.57:8300} {Suffrage:Voter ID:10.25.136.179:8300 Address:10.25.136.179:8300} {Suffrage:Voter ID:10.25.140.68:8300 Address:10.25.140.68:8300}]
	latest_configuration_index = 2844431
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 521
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 676
	max_procs = 2
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 42
	failed = 16
	health_score = 7
	intent_queue = 0
	left = 1
	member_time = 1097
	members = 55
	query_queue = 0
	query_time = 106
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 2
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 203
	members = 5
	query_queue = 0
	query_time = 1

### Operating system and Environment details
Amazon Linux 2017-09

**Comment by dpgaspar** [comment]
ok, found a failed member on the cluster:

prod-consul-cluster-A                   DD.DD.DD.DD:8301   alive   server  0.9.3  2         us-west-2  <all>
prod-consul-cluster-B                   DD.DD.DD.DD:8301  alive   server  0.9.3  2         us-west-2  <all>
prod-consul-cluster-C                   DD.DD.DD.DD:8301  failed    server  0.9.3  2         us-west-2  <all>
prod-consul-cluster-D                   DD.DD.DD.DD:8301   alive   server  0.9.3  2         us-west-2  <all>

**Comment by dpgaspar** [comment]
After evicting the failed node with force-leave, the cluster still presents errors, these last 1-2 min.

I have some of these on the logs from random members:
memberlist: Marking prod-consul-cluster-XXX as failed, suspect timeout reached (0 peer confirmations)

**Comment by dpgaspar** [comment]
This issue continues, still seeing:
memberlist: Marking prod-consul-cluster-XXX as failed, suspect timeout reached (0 peer confirmations)

on the logs and ocasional:
consul.acl: Failed to get policy from ACL datacenter: No cluster leader

One a day. The cluster recovers automatically, and no elections take place.

**Comment by slackpad** [comment]
Hi @dpgaspar does it ever elect a leader? If there are dead servers in your Raft configuration you may need to run https://www.consul.io/docs/guides/outage.html#manual-recovery-using-peers-json in order to get the proper set of alive servers in there to get a quorum again.

**Comment by dpgaspar** [comment]
Thanks for the reply @slackpad, they did elect a leader, this problem is gone since I let all the agents gossip with each other.

**Comment by cm99521** [comment]
Hi consul maintainers, same error for me. is there a solution please just tell!!!
