### ISSUE TITLE
ACLs are disabled in this Consul cluster. This is the default behavior, as you have to explicitly enable them

### ISSUE THREAD

**Issue by eddamalique01** [hashicorp/consul#3816]
1. I don't really understand this step:
Step 1: enable ACL’s

This was the most risky thing - it involved changing crucial configuration and restarting all Consul servers. This has proven to be a hazard in the past, so I proceeded with great care. My screwing up the quality cluster was entirely my own fault, by the way. I was really not careful here. I learned my lesson again :-)
Easiest way to turn on ACL’s turned out to be: add a new json file in Consul’s data dir. We have the datadir in /usr/share/consul/, so I let Puppet add a file /usr/share/consul/master.json:

Does anyone knows a simple way on how I can configure the acl because I don't understand the above step.

If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @eddamalique01 it looks like you are looking at http://jovandeginste.github.io/2016/05/04/turning-on-acl-s-in-our-consul-cluster.html. Since that blog was written we re-worked the ACL Guide to walk through everything that's required to set up ACLs for the first time - https://www.consul.io/docs/guides/acl.html. Hope that helps!
