### ISSUE TITLE
github.com/hashicorp/go-msgpack is a really old unmaintained fork

### ISSUE THREAD

**Issue by nim-nim** [hashicorp/consul#3826]
Hi,

Now that https://github.com/ugorji/go/ made its first stable and supported release, maybe it's time to use it directly instead of vendoring github.com/hashicorp/go-msgpack which is an old unmaintained fork from 2015 which his lagging hundreds of commits behind?

**Comment by onlyjob** [comment]
Good dependency hygiene is important. Simply replacing "github.com/hashicorp/go-msgpack" with "github.com/ugorji/go" in all imports appears to work without breaking the build or tests.

Please consider switching to "github.com/ugorji/go".

**Comment by onlyjob** [comment]
@stale bot wishes this issue was never reported...

**Comment by david-yu** [comment]
Closing as hashicorp/go-msgpack is still maintained.
