### ISSUE TITLE
Server Configuration.

### ISSUE THREAD

**Issue by eddamalique01** [hashicorp/consul#3829]
Following this documentation link: https://imaginea.gitbooks.io/consul-devops-handbook/content/server_configuration.html

Can someone help me understand the write came up with server1 aserver2 and server3 in the Server Configuration step. Please.

 you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by slackpad** [comment]
Hi @eddamalique01 I'm not sure I fully understand your question (and that's not a guide we created), but we have some documentation at https://www.consul.io/intro/getting-started/install.html that helps walk you through starting with Consul. Hope that helps!
