### ISSUE TITLE
Support of DNS-Based Service Discovery (RFC6763)

### ISSUE THREAD

**Issue by oliora** [hashicorp/consul#383]
It would be great if Consul supports DNS-Based Service Discovery [RFC6763](http://tools.ietf.org/html/rfc6763).

The implementation can reuse existing service info, something like RFC-2782 style lookup does.
For example, service name can be used as service type. Tag can be used as protocol (`tcp` is the default which need not to be added as tag) and service id is used as service instance name. So lookup for PTR records for `_logstash._udp.service.consul.` will retrieve records for all services with name `logstash` and tag `udp`, something like:

```
_logstash._udp.service.consul.       10      IN      PTR     mylogstash1._logstash._udp.service.consul.
_logstash._udp.service.consul.       10      IN      PTR     mylogstash2._logstash._udp.service.consul.
... (SRV and A records, see RFC for details)
```

**Comment by sethvargo** [comment]
Hey there,

Thank you for opening an issue. This sounds cool, but it has not been a widely-requested feature. We would gladly review a PR for this, but we do not have plans to implement this ourselves.

**Comment by tugberkugurlu** [comment]
@sethvargo what type of spec does Consul use for DNS based service discovery? Is that a custom one or a defined one such as RFC6763?

**Comment by banks** [comment]
@tugberkugurlu DNS interface docs are here: https://www.consul.io/docs/agent/dns.html
