### ISSUE TITLE
[Feature Request] Logging of Config files as they are read

### ISSUE THREAD

**Issue by jshoffstall** [hashicorp/consul#3836]
At TRACE-level output, please print the list of configuration files as they are read. It would also be helpful to have CLI-level or API-level read-only access to the current, complete, effective configuration.

**Comment by slackpad** [comment]
Hi @jshoffstall the full effective configuration can be found in the `DebugConfig` section of https://www.consul.io/api/agent.html#read-configuration.

**Comment by pearkes** [comment]
I'm going to close this out given it isn't an immediate goal and that the API exists to make this possible as a workaround.
