### ISSUE TITLE
All services have same CreateIndex and ModifyIndex

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#3838]
version: 0.8.4

Couple days ago, we registered a bunch of services in consul via go api. and the days after that we overwrote them (using the same register api) once in a while. Yesterday when we check out the data from the consul and found all the services have the same CreateIndex and ModifyIndex!!!
How that could happen? bugs?

`{"Node":{"ID":"","Node":"default-all","Address":"127.0.0.1","Datacenter":"dc1","TaggedAddresses":null,"Meta":{"external":"true","internal":"true","ns":"default"},"CreateIndex":586142,"ModifyIndex":586395},"Services":{"_fia_172.20.128.28_8999":{"ID":"_fia_172.20.128.28_8999","Service":"fia","Tags":[],"Address":"172.20.128.28","Port":8999,"EnableTagOverride":false,"CreateIndex":586142,"ModifyIndex":586142},"_keybox_172.20.128.28_9399":{"ID":"_keybox_172.20.128.28_9399","Service":"keybox","Tags":[],"Address":"172.20.128.28","Port":9399,"EnableTagOverride":false,"CreateIndex":586142,"ModifyIndex":586142},"_keybox_172.20.128.29_9399":{"ID":"_keybox_172.20.128.29_9399","Service":"keybox","Tags":[],"Address":"172.20.128.29","Port":9399,"EnableTagOverride":false,"CreateIndex":586142,"ModifyIndex":586142},"_keybox_172.20.128.30_9399":{"ID":"_keybox_172.20.128.30_9399","Service":"keybox","Tags":[],"Address":"172.20.128.30","Port":9399,"EnableTagOverride":false,"CreateIndex":586142,"ModifyIndex":586142},"_pm_mgt_172.20.128.28_10093":{"ID":"_pm_mgt_172.20.128.28_10093","Service":"pm_mgt","Tags":[],"Address":"172.20.128.28","Port":10093,"EnableTagOverride":false,"CreateIndex":586142,"ModifyIndex":586142},"_pm_mgt_172.20.128.29_10093":{"ID":"_pm_mgt_172.20.128.29_10093","Service":"pm_mgt","Tags":[],"Address":"172.20.128.29","Port":10093,"EnableTagOverride":false,"CreateIndex":586142,"ModifyIndex":586142},"_pm_mgt_172.20.128.30_10093":{"ID":"_pm_mgt_172.20.128.30_10093","Service":"pm_mgt","Tags":[],"Address":"172.20.128.30","Port":10093,"EnableTagOverride":false,"CreateIndex":586142,"ModifyIndex":586142}}}`

**Comment by slackpad** [comment]
Hi @hehailong5 the way that the catalog is implemented internally this can happen after a snapshot restore has occurred. Here's the bit of code where this comes from:

https://github.com/hashicorp/consul/blob/v1.0.3/agent/consul/state/catalog.go#L234-L242

That will create a whole set of records all with the same index (`idx`).

**Comment by hehailong5** [comment]
Hi
When snapshot restore usually happens?

**Comment by hehailong5** [comment]
Does restart cluster with peers.json (new ips) always trigger this?

**Comment by slackpad** [comment]
> Does restart cluster with peers.json (new ips) always trigger this?

That would totally cause this because that process creates a snapshot and then restores it as part of the its operation. That'll move all the indexes up to the same value.
