### ISSUE TITLE
node_ttl wildcards (feature request)

### ISSUE THREAD

**Issue by maxadamo** [hashicorp/consul#3842]
### Description of the Issue (and unexpected/desired result)

Have a wildcard, to define node TTL based on domains

### `consul version` for both Client and Server
Client: `1.0.2`
Server: `1.0.2`

### `consul info` for both Client and Server
Client:
```
*not relevant*
```

Server:
```
*not relevant*
```

### Operating system and Environment details

Linux, CentOS 7, Ubuntu 16.04

### Log Fragments or Link to [gist](https://gist.github.com/)

Since I'm using a recursor, I'd avoid using a TTL 0 for the recursed zone (where a low TTL doesn't even make much sense). In order to do that I was imagining something like the following:

```
"dns_config": {
    "allow_stale": true,
    "node_ttl": (
        ".consul": "5s",
        "*": "1200s"
    }
},
```

**Comment by slackpad** [comment]
Hi @maxadamo it looks from the recurse code  that it should be propagating whatever TTL is on the records from the recursor. Are you seeing a case where the recursor returns a non-zero TTL and then Consul's changing it?

**Comment by maxadamo** [comment]
@slackpad thanks for your reply. Yes, I think this feature that I've requested doesn't make any sense :) 
TTL come from the DNS. Now I'm using unbound DNS to route requests either to Consul or to the other DNSs, but even the recursor that I had setup with Consul worked pretty well. 
I believe you can close this issue.
