### ISSUE TITLE
consul agent with -retry-join and provider=gce fails to handle changing set of instances

### ISSUE THREAD

**Issue by jrw972** [hashicorp/consul#3846]
### Description of the Issue (and unexpected/desired result)

Consul fails to elect a leader when the set of instances on Google Compute Engine changes.

### Reproduction steps

1. Create a Google Compute instance group of size 3 tagged with `consul-service`.
2. Run consul via

`/usr/local/sbin/consul agent -data-dir /var/run/consul -server -client 0.0.0.0 -dns-port 53 -domain ${project_id} -recursor 169.254.169.254 -retry-join "provider=gce tag_value=consul-service" -bootstrap-expect 3`

3. Observe that a leader is elected.

4. Replace the instances specifying a maximum unavailable of zero and an appropriate non-zero maximum surge.  (This will create new instances before deleting the old instances.) 

5. Observe that a leader is not elected.  The newly created instances will query GCP and get a list of instances that include both the new instances that are being created and the old instances that will be removed.  Consul will continue to attempt connections to the deleted instances and fail to elect a cluster leader.

### `consul version` for both Client and Server
Client: NA
Server: v1.0.3

### `consul info` for both Client and Server
Client: NA

Server: (after hanging a long time)
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease = 
        revision = 48f3dd56
        version = 1.0.3
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 
        server = true
raft:
        applied_index = 67
        commit_index = 67
        fsm_pending = 0
        last_contact = 5m0.544659696s
        last_log_index = 68
        last_log_term = 4
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:bbaf7a08-cae2-442e-c856-63aa86e5718f Address:10.128.0.14:8300} {Suffrage:Voter ID:c316d363-ae04-b797-77c7-9dcaee309be7 Address:10.128.0.15:8300} {Suffrage:Nonvoter 
ID:7084986b-7e1c-5cf1-4688-f7371d1830f6 Address:10.128.0.16:8300} {Suffrage:Nonvoter ID:f102fc76-0dc4-b1be-0fa3-776089f736c7 Address:10.128.0.12:8300} {Suffrage:Nonvoter ID:a7807d30-5612-863a-73ad-f5c214b09b4e Addre
ss:10.128.0.11:8300}]
        latest_configuration_index = 68
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Candidate
        term = 43
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 66
        max_procs = 1
        os = linux
        version = go1.9.2
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 3
        failed = 1
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 10
        members = 5
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 2
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 20
        members = 6
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

f1-micro (1 vCPU, 0.6 GB memory)

debian-9-stretch-v20171018

### Log Fragments or Link to [gist](https://gist.github.com/)

https://gist.github.com/jrw972/34457b8892737a6f52e7de0e53b2d348

**Comment by slackpad** [comment]
Hi @jrw972 do you know when your automated process will terminate the old servers?

> Replace the instances specifying a maximum unavailable of zero and an appropriate non-zero maximum surge. (This will create new instances before deleting the old instances.)

It looks from the `consul info` output above that the there are newly-added servers that have not yet been promoted to voters by autopilot:

```
[{Suffrage:Voter ID:bbaf7a08-cae2-442e-c856-63aa86e5718f Address:10.128.0.14:8300}
{Suffrage:Voter ID:c316d363-ae04-b797-77c7-9dcaee309be7 Address:10.128.0.15:8300}
{Suffrage:Nonvoter ID:7084986b-7e1c-5cf1-4688-f7371d1830f6 Address:10.128.0.16:8300}
{Suffrage:Nonvoter ID:f102fc76-0dc4-b1be-0fa3-776089f736c7 Address:10.128.0.12:8300}
{Suffrage:Nonvoter ID:a7807d30-5612-863a-73ad-f5c214b09b4e Address:10.128.0.11:8300}]
```

This could happen if it started terminating servers before the new ones are promoted. Also, old servers would need to be terminated one at a time and removed from the cluster before terminating another. The autopilot API has some tools that can help determine when it's safe to terminate an existing server - https://www.consul.io/docs/guides/autopilot.html#server-health-checking.

**Comment by jrw972** [comment]
The "when" is up to GCP's replacement policy.  In this case, it will start terminating them once the new ones return 200 on port 8500.  Thus, it is possible (as you have observed) for GCP to delete the old servers before the new ones have been promoted.  I will look into increasing the time to allow the new servers to become voters.  There seem to be two issues then.

1.  When will consul give up on trying to contact a peer that is no longer available?
2.  Will the cluster reform if all of the voters terminate leaving only non-voters?  I feel like it should.

I should also note that I'm not interested in persistence.  I can repopulate all of the records when the instances are replaced.

**Comment by slackpad** [comment]
> When will consul give up on trying to contact a peer that is no longer available?

Autopilot will remove them as long as the cluster still has a quorum and a leader.

> Will the cluster reform if all of the voters terminate leaving only non-voters? I feel like it should.

Unfortunately Consul can't make a change to voter/nonvoter status without a leader, since those changes need to be coordinated and go through Raft as well.

> The "when" is up to GCP's replacement policy. In this case, it will start terminating them once the new ones return 200 on port 8500. 

You might be able to point GCP at https://www.consul.io/api/operator/autopilot.html#read-health. That'll return 200 only if the cluster is healthy, otherwise it gets a 429, so that would likely wait out the required period.

> I should also note that I'm not interested in persistence. I can repopulate all of the records when the instances are replaced.

If that's the case you might want to terminate the old servers first and just fire up a new cluster and populate it; that would avoid all the tricky coordination which results in trying to hand off the quorum to the new servers and remove the old servers safely.

**Comment by jrw972** [comment]
Got it.  GCP has a setting for lengthening the time before an instance is considered healthy.  When set to 60 seconds, the cluster was able to reform without a problem.  Thanks for your help.
