### ISSUE TITLE
Lock Semantics Unclear in Documentation or Bug in Lock Behavior

### ISSUE THREAD

**Issue by nugend** [hashicorp/consul#3847]
It's not explicitly laid out in the KV documentation that locking is co-operative and does not interact with normal update semantics *or* CAS semantics.

If this is expected, it's really not a problem as any issue should be mitigated by ACLs. It should probably be clearly called out though.

If this is not intended, then that's a pretty bad bug, I think:

```
$ consul version
Consul v1.0.3
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
$ consul agent -dev
```

Terminal 1:
```
$ SESSION=`curl -X PUT localhost:8500/v1/session/create | jq -r .ID`
$ curl -X PUT http://localhost:8500/v1/kv/my-key?acquire=$SESSION
```

Terminal 2:
```
$ curl localhost:8500/v1/kv/my-key
[
    {
        "LockIndex": 1,
        "Key": "my-key",
        "Flags": 0,
        "Value": null,
        "Session": "7b382038-cae5-d89e-f18d-27c32aef26a7",
        "CreateIndex": 8,
        "ModifyIndex": 8
    }
]
$ curl -X PUT localhost:8500/v1/kv/my-key?cas=8 -d "not what i expected"
$ curl localhost:8500/v1/kv/my-key
not what I expected
$ curl -X PUT localhost:8500/v1/kv/my-key -d "also this"
$ curl localhost:8500/v1/kv/my-key
also this
```

Anyway, *pretty* sure that's a documentation bug.

**Comment by preetapan** [comment]
@nugend Yes, lock acquisition when updating a KV prefix is optional. If the acquire param is not set you can still update the key.

If you want to coordinate updates to that key across multiple processes or nodes, you would create another session and use [accquire and [](release](https://www.consul.io/api/kv.html#release)) to manage access between different lock holders.

Hope this helps. We can try to make this more explicit in the documentation.

**Comment by nugend** [comment]
Yeah, I figured it was a docs issue, it's just a touch surprising since I don't *think* there's any mention of it in any of the documentation. I think adding a sentence at the end of https://www.consul.io/api/kv.html#acquire saying, "An update that does not include the acquire parameter will proceed normally even if another session has locked the key."

And *maybe* a Note or Warning callout in the https://www.consul.io/docs/guides/leader-election.html page would be good ("Consul's lock acquisition is co-operative. Be sure to use only one update strategy for a given key." or something like that)

**Comment by nugend** [comment]
@preetapan Should I open a separate issue for documentation or something?

**Comment by slackpad** [comment]
We can keep this one open to close the loop on updating the docs.

**Comment by preetapan** [comment]
fixed in https://github.com/hashicorp/consul/pull/3853
