### ISSUE TITLE
Error starting agent: agent: timeout starting DNS servers

### ISSUE THREAD

**Issue by fandaye** [hashicorp/consul#3848]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### Description of the Issue (and unexpected/desired result)
I created a user'consul', which I want to run with the user,Result
    
    localhost consul: ==> Error starting agent: agent: timeout starting DNS servers

### Reproduction steps
config：

   {
     "datacenter": "dc01",
     "retry_interval":"5s",
     "client_addr":"0.0.0.0",
     "recursors": ["114.114.114.114","115.115.115.115"],
     "data_dir": "/data/consul/data",
     "log_level": "INFO",
     "rejoin_after_leave": true,
     "bootstrap_expect": 2,
     "server": true,
     "node_name": "docker01",
     "advertise_addr":"172.16.50.112",
     "ui": true,
     "ports": {
       "dns": 53
     }
   }

'root'users run normal

    # /usr/local/bin/consul agent -config-file /etc/consul/consul.json

'consul'users run

    $ /usr/local/bin/consul agent -config-file /etc/consul/consul.json
    ==> Starting Consul agent...
    ==> Error starting agent: agent: timeout starting DNS servers

### `consul version` for both Client and Server
Client: `1.0.3`
Server: `1.0.3`

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
[Server `consul info` here]
```

### Operating system and Environment details
centos 7.4 X86
### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by preetapan** [comment]
@fandaye you have port 53 as the DNS port in the config mentioned above. By default, only the root user can listen on privileged ports ( below 1024). There's more information online on how to bind to privileged ports as a non root user (either port forwarding or setcap)
