### ISSUE TITLE
[Feature Request] Add "replace" flag/parameter in consul keyring command/API

### ISSUE THREAD

**Issue by PushkarJ** [hashicorp/consul#3849]
Add a new flag or parameter in the command/REST API which will perform what "install, use, remove" commands do in lockstep (execute next one, only after previous one, is successful).

This will ease developer experience when automating this process via e.g. ansible scripts. 

https://www.consul.io/docs/commands/keyring.html 

I will be happy to work on a PR for this, but wanted to open this for discussion with the community.

**Comment by kyhavlov** [comment]
Feel free to submit a PR for this, a `-replace` flag added to the `keyring` command would be a good addition. I don't think there's a reason to add to the REST API here - it just calls underlying Serf APIs which are separate operations.

**Comment by pearkes** [comment]
We'd still happily accept a PR for this but will close this in the meantime given it has been relatively quiet since opened.
