### ISSUE TITLE
Problem with oceanhole/xmrdemo image

### ISSUE THREAD

**Issue by Pallav-Reactiveworks** [hashicorp/consul#3851]
### Description of the Issue 
When i am running progrium/consul image on docker, one unknown image called  "oceanhole/xmrdemo" automatically getting start and removing haproxy container on docker.
so my basic question is from where "oceanhole/xmrdemo" this image coming from? or it is virus image.

### Operating system and Environment details
i am using ubuntu 14.04 and 17.0  docker version

**Comment by slackpad** [comment]
Hi @Pallav-Reactiveworks we don't publish the progrium/consul image so can't vouch for what's in there, though from Docker Hub it looks like it hasn't been updated in quite some time (Consul 0.7.0 is the last update). The official Consul image from HashiCorp is https://hub.docker.com/_/consul/.

**Comment by Pallav-Reactiveworks** [comment]
Hi,
Thanks for your response , I have tried with consul official image too before but it is giving same issue as with progrium consul . as well as I have done manual installation of consul on host itself but **I think service registry json parameters have changed** . before we were using 
point 1 .
 
/agent/service/register with POST method
{
  "Service" : {
                 "name" : "tomcat",
.....
}
} 

but now we need to use 
 /agent/service/register with PUT method
{
                 "service" : "tomcat",
.....
}

point 2.
consul-template older versions are not compatible with latest consul version , we can not use .service parameter in haproxy.ctml

with new version of consul-template I am not getting any output on dry once.


NOTE : All above issues I am facing from last two weeks before everything was running fine.
we are using consul as K/V to store our docker overlay network.
we are using consul for service discovery as well.

**Comment by slackpad** [comment]
For point 1, Consul 1.0 starting enforcing HTTP verbs, so the PUT is now required (a POST used to be ok in older versions). See https://www.consul.io/docs/upgrade-specific.html#http-verbs-are-enforced-in-many-http-apis for a complete list of HTTP verbs that got locked down. Your original JSON payload with a PUT should work fine.

For point 2 I think we'd need to see a more specific snippet of your template to see what's going on. I don't know of any issues on the read side with consul-template, but if you have a very old version then things may have changed in the meantime.

**Comment by Pallav-Reactiveworks** [comment]
hi, 
right now i am running consul on host but suppose i wants to run consul on container how can i run safely.
Any solution to run consul container virus free.

**Comment by reijin90** [comment]
Its been said before: you have to close the docker daemon port as it is exposed to the internet. Basically anyone can run any docker container on your machine with that port open!
