### ISSUE TITLE
warn: go-bindata repo was recreated

### ISSUE THREAD

**Issue by gobwas** [hashicorp/consul#3868]
Hi!

Use of `go-bindata` could be dangerous according to [this tweet](https://twitter.com/francesc/status/961249107020001280):
>go-bindata creator deleted their @github account and someone else created a new account with the same name. There's no guarantees that the new user has good intentions, so if you're using the repository make sure you verify it first!

At least in listed in `GOTOOLS` variable and built with `tools` target in `GNUMakefile`.

Cheers.

**Comment by slackpad** [comment]
Thanks for the heads up @gobwas!

**Comment by commitay** [comment]
@slackpad  Running `go get` for `hashicorp/go-bindata` fetches `jteeuwen/go-bindata`

[hashicorp/go-bindata/blob/master/go-bindata/main.go](https://github.com/hashicorp/go-bindata/blob/a0ff2567cfb70903282db057e799fd826784d41d/go-bindata/main.go#L15)

```
go get -u -v github.com/hashicorp/go-bindata/...
github.com/hashicorp/go-bindata (download)
github.com/jteeuwen/go-bindata (download)
github.com/jteeuwen/go-bindata
github.com/hashicorp/go-bindata/go-bindata
```

**Comment by slackpad** [comment]
Good catch @commitay, thank you! I updated the import path via https://github.com/hashicorp/go-bindata/commit/bf7910af899725e4938903fb32048c7c0b15f12e which fixes this:

```
$ go get -u -v github.com/hashicorp/go-bindata/...
github.com/hashicorp/go-bindata (download)
```

**Comment by commitay** [comment]
Thanks for the quick fix!
