### ISSUE TITLE
Inconsistent catalog replies for non-existent nodes and services

### ISSUE THREAD

**Issue by robn** [hashicorp/consul#387]
When querying a non-existent service, you get a successful response with an empty array:

```
$ curl -i http://localhost:8500/v1/catalog/service/foo
HTTP/1.1 200 OK
Content-Type: application/json
X-Consul-Index: 3
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Tue, 07 Oct 2014 11:20:38 GMT
Content-Length: 2

[]
```

(One could argue a 404 makes more sense, but this will do).

When querying a non-existent node however, you get a successful response with null:

```
$ curl -i http://localhost:8500/v1/catalog/node/foo
HTTP/1.1 200 OK
Content-Type: application/json
X-Consul-Index: 3
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Tue, 07 Oct 2014 11:20:43 GMT
Content-Length: 4

null
```

Which isn't considered "valid" JSON by some parsers out of the box (and the spec isn't totally clear).

I haven't dug further through the API to see where else there might be problems like this.

Consistency would be good here!

**Comment by sethvargo** [comment]
These should all be 404s and should be pre-1.0 so we can break the API. It'll need a big callout in the changelog, but worth making consistent.

**Comment by slackpad** [comment]
This didn't make it into 1.0, unfortunately, so we have to keep them as-is. A future /v2 version of these can be made more consistent.
