### ISSUE TITLE
Consul Kerberos authentication 

### ISSUE THREAD

**Issue by dhiren051** [hashicorp/consul#3880]
Consul is showing ‘401 Unautorized’ status where if I directly hit http health endpoint it shows ‘HEALTHY’. Does anybody know how to set Kerberos authentication for http calls ?

**Comment by slackpad** [comment]
This was cross-posted to https://groups.google.com/forum/#!msg/consul-tool/O0bC5DJlQJ8/O9N2nOuwBwAJ, so answered there.
