### ISSUE TITLE
Consul container not using localhost for health checks

### ISSUE THREAD

**Issue by rnmalone** [hashicorp/consul#3883]
Hi there.

We're running Consul in a docker container through `docker run consul,` and running it off its default settings. We can register services successfully, but registering a health endpoint on the local machine is a struggle as the container doesn't use the host's ip.

I've tried starting a consul container using the `-net=host ` flag but this seems to cause more issues than before, as the container refuses to expose it's ports to my machine, even configuring the normal ports in the command and kinematic. 

The goal is for consul to poll ports on the host machine for a health status but it's just going wrong.

I glady accept this not an issue with consul and a result of incorrect setup, but any help will be highly appreciated.

Thanks!

**Comment by kyhavlov** [comment]
The correct solution here is pretty dependent on how you've set up your networking with docker; exposing ports to the host with the `-p 8080:80` syntax should work though (maybe check the address/port combination that gets bound on the host). 

You may also want to look into their networks feature for this: https://docs.docker.com/engine/tutorials/networkingcontainers/

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
