### ISSUE TITLE
retry-join cannot build a cluster

### ISSUE THREAD

**Issue by Milad-Irani** [hashicorp/consul#3895]
Hi,

I am trying to use -retry-join option to firm a cluster in a OpenStack cloud provider using 3 Consul nodes. According to the documentation (https://www.consul.io/docs/agent/options.html#openstack) I use the below configuration for all 3 nodes (tags are already generated for every Consul instance) :

`> consul version`
Consul v1.0.2
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

`> sudo consul agent  -data-dir=/opt/consul/data -server -bootstrap-expect=3 -retry-join 'provider=os tag_key=Consul tag_value=production'`

bootstrap_expect > 0: expecting 3 servers
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.0.2'
           Node ID: '3c62686d-9b91-d5bb-232d-7521a1b6'
         Node name: 'consul-00'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 10.180.1.14 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: true, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2018/02/19 10:14:20 [INFO] raft: Initial configuration (index=0): []
    2018/02/19 10:14:21 [INFO] raft: Node at 10.180.1.14:8300 [Follower] entering Follower state (Leader: "")
    2018/02/19 10:14:21 [INFO] serf: EventMemberJoin: consul-00.dc1 10.180.1.14
    2018/02/19 10:14:21 [WARN] serf: Failed to re-join any previously known node
    2018/02/19 10:14:21 [INFO] serf: EventMemberJoin: consul-00 10.180.1.14
    2018/02/19 10:14:21 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
    2018/02/19 10:14:21 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
    2018/02/19 10:14:21 [INFO] agent: Started HTTP server on 127.0.0.1:8500 (tcp)
    2018/02/19 10:14:21 [INFO] agent: started state syncer
    2018/02/19 10:14:21 [INFO] agent: Retry join LAN is supported for: aliyun aws azure digitalocean gce os scaleway softlayer
    2018/02/19 10:14:21 [INFO] agent: Joining LAN cluster...
    2018/02/19 10:14:21 [INFO] discover-os: ProjectID not provided. Looking up in metadata...
    2018/02/19 10:14:21 [WARN] serf: Failed to re-join any previously known node
    2018/02/19 10:14:21 [INFO] consul: Adding LAN server consul-00 (Addr: tcp/10.180.1.14:8300) (DC: dc1)
    2018/02/19 10:14:21 [INFO] consul: Handled member-join event for server "consul-00.dc1" in area "wan"
    2018/02/19 10:14:21 [INFO] discover-os: ProjectID is a1f5b576b6b04c4897cad491e69b29e4
    2018/02/19 10:14:21 [ERR] agent: Join LAN: discover-os: Auth url must be provided
2018/02/19 10:12:28 [WARN] agent: Join LAN failed: No servers to join, retrying in 30s
    2018/02/19 10:12:31 [ERR] agent: Coordinate update error: No cluster leader

So as it is shown:

1. It complains about the Auth_url, though, it is an optional input.
2. It cannot form a cluster and select the leader, even though 3 servers are already there.
3. Nodes are not able to discover each other.

`> consul members`
Node       Address           Status  Type    Build  Protocol  DC   Segment
consul-00  10.180.1.14:8301  alive   server  1.0.2  2         dc1  <all>

**Comment by banks** [comment]
> It complains about the Auth_url, though, it is an optional input.

It's "optional" in the docs because you may alternatively provide it via `OS_AUTH_URL` 

https://github.com/hashicorp/go-discover/blob/8f2af0ac44208783caab4dd65462ffb965229c60/provider/os/os_discover.go#L114

If you have done neither, there is a good chance that is the problem although I've never used OpenStack myself so there may be another issue I'm missing from these symptoms.

Can you confirm that the auth URL is provided to Consul via ENV?

**Comment by Milad-Irani** [comment]
You are right, it was my mistake. I did not provide the auth_url as an env var.
