### ISSUE TITLE
Consul no longer builds with Go 1.10 - go:cgo_export_static main only allowed in cgo-generated code

### ISSUE THREAD

**Issue by FireBurn** [hashicorp/consul#3896]
Cloning into 'consul'...
+ cd consul
+ export GOPATH=/apps/was/jenkins/workspace/Compile_Consul
+ GOPATH=/apps/was/jenkins/workspace/Compile_Consul
+ CONSUL_DEV=1
+ make
go get -u -v github.com/elazarl/go-bindata-assetfs/... github.com/hashicorp/go-bindata/... github.com/magiconair/vendorfmt/cmd/vendorfmt github.com/mitchellh/gox golang.org/x/tools/cmd/cover golang.org/x/tools/cmd/stringer github.com/axw/gocov/gocov gopkg.in/matm/v1/gocov-html
github.com/elazarl/go-bindata-assetfs (download)
github.com/hashicorp/go-bindata (download)
github.com/magiconair/vendorfmt (download)
github.com/mitchellh/gox (download)
Fetching https://golang.org/x/tools/cmd/cover?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/cover?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/cover": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/cover?go-get=1
get "golang.org/x/tools/cmd/cover": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/cover?go-get=1
Parsing meta tags from https://golang.org/x/tools/cover?go-get=1 (status code 200)
get "golang.org/x/tools/cover": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cover?go-get=1
get "golang.org/x/tools/cover": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/cmd/stringer?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/stringer?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/stringer": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/stringer?go-get=1
get "golang.org/x/tools/cmd/stringer": verifying non-authoritative meta tag
github.com/axw/gocov (download)
Fetching https://gopkg.in/matm/v1/gocov-html?go-get=1
Parsing meta tags from https://gopkg.in/matm/v1/gocov-html?go-get=1 (status code 200)
get "gopkg.in/matm/v1/gocov-html": found meta tag main.metaImport{Prefix:"gopkg.in/matm/v1/gocov-html", VCS:"git", RepoRoot:"https://gopkg.in/matm/v1/gocov-html"} at https://gopkg.in/matm/v1/gocov-html?go-get=1
gopkg.in/matm/v1/gocov-html (download)
github.com/matm/gocov-html (download)
runtime/internal/sys
runtime/internal/atomic
runtime
# runtime
../../../../go/src/runtime/cgo.go:9:3: //go:cgo_export_static main only allowed in cgo-generated code
make: *** [tools] Error 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by banks** [comment]
@FireBurn thanks for the report, what platform is this on?

I can't reproduce with `master` on Darwin:
```
$ go version
go version go1.10 darwin/amd64
$ env CONSUL_DEV=1 make
... [worked] ...
$ consul version
Consul v1.0.6-14-g4c90fbfd-dev (4c90fbfd)
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```
Where `4c90fbfd` is current master.

**Comment by FireBurn** [comment]
It's go version go1.10 linux/amd64 on RHEL7, self compiled/bootstrapped 

I have the same issue with Elasticsearch Beats but Gitlab worked fine with 1.10.

Here's the complete output:

[EnvInject] - Loading node environment variables.
Building remotely on Build node in workspace /apps/was/jenkins/workspace/Compile_Consul
[Compile_Consul] $ /bin/sh -xe /tmp/hudson1781177980150736039.sh
+ rm -rf '*'
++ pwd
+ JENKINS_DIR=/apps/was/jenkins/workspace/Compile_Consul
+ cd /apps/was/jenkins/workspace/Compile_Consul
+ wget https://storage.googleapis.com/golang/go1.10.src.tar.gz
--2018-02-19 09:58:52--  https://storage.googleapis.com/golang/go1.10.src.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.23.48, 2a00:1450:4009:80a::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.23.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18300467 (17M) [application/octet-stream]
Saving to: ���go1.10.src.tar.gz���


2018-02-19 09:58:52 (59.8 MB/s) - ���go1.10.src.tar.gz��� saved [18300467/18300467]

+ tar xf go1.10.src.tar.gz
+ cd go/src
+ GOROOT_BOOTSTRAP=/usr/lib/golang
+ GOOS=linux
+ GOARCH=amd64
+ ./bootstrap.bash
#### Copying to ../../go-linux-amd64-bootstrap

#### Cleaning ../../go-linux-amd64-bootstrap

#### Building ../../go-linux-amd64-bootstrap

Building Go cmd/dist using /usr/lib/golang.
Building Go toolchain1 using /usr/lib/golang.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
----
Bootstrap toolchain for linux/amd64 installed in /apps/was/jenkins/workspace/Compile_Consul/go-linux-amd64-bootstrap.
Building tbz.
-rw-r--r--. 1 wasadm was 69687702 Feb 19 10:00 /apps/was/jenkins/workspace/Compile_Consul/go-linux-amd64-bootstrap.tbz
+ export GOROOT=/apps/was/jenkins/workspace/Compile_Consul/go
+ GOROOT=/apps/was/jenkins/workspace/Compile_Consul/go
+ export PATH=/apps/was/jenkins/workspace/Compile_Consul/bin:/usr/local/bin:/usr/bin
+ PATH=/apps/was/jenkins/workspace/Compile_Consul/bin:/usr/local/bin:/usr/bin
+ GOROOT_BOOTSTRAP=/apps/was/jenkins/workspace/Compile_Consul/go-linux-amd64-bootstrap
+ GOOS=linux
+ GOARCH=amd64
+ ./make.bash
Building Go cmd/dist using /apps/was/jenkins/workspace/Compile_Consul/go-linux-amd64-bootstrap.
Building Go toolchain1 using /apps/was/jenkins/workspace/Compile_Consul/go-linux-amd64-bootstrap.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
---
Installed Go for linux/amd64 in /apps/was/jenkins/workspace/Compile_Consul/go
Installed commands in /apps/was/jenkins/workspace/Compile_Consul/go/bin
+ cd /apps/was/jenkins/workspace/Compile_Consul
+ mkdir -p /apps/was/jenkins/workspace/Compile_Consul/src/github.com/hashicorp/
+ cd /apps/was/jenkins/workspace/Compile_Consul/src/github.com/hashicorp/
+ git clone https://github.com/hashicorp/consul.git
Cloning into 'consul'...
+ cd consul
+ export GOPATH=/apps/was/jenkins/workspace/Compile_Consul
+ GOPATH=/apps/was/jenkins/workspace/Compile_Consul
+ CONSUL_DEV=1
+ make
go get -u -v github.com/elazarl/go-bindata-assetfs/... github.com/hashicorp/go-bindata/... github.com/magiconair/vendorfmt/cmd/vendorfmt github.com/mitchellh/gox golang.org/x/tools/cmd/cover golang.org/x/tools/cmd/stringer github.com/axw/gocov/gocov gopkg.in/matm/v1/gocov-html
github.com/elazarl/go-bindata-assetfs (download)
github.com/hashicorp/go-bindata (download)
github.com/magiconair/vendorfmt (download)
github.com/mitchellh/gox (download)
Fetching https://golang.org/x/tools/cmd/cover?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/cover?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/cover": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/cover?go-get=1
get "golang.org/x/tools/cmd/cover": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/cover?go-get=1
Parsing meta tags from https://golang.org/x/tools/cover?go-get=1 (status code 200)
get "golang.org/x/tools/cover": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cover?go-get=1
get "golang.org/x/tools/cover": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/cmd/stringer?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/stringer?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/stringer": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/stringer?go-get=1
get "golang.org/x/tools/cmd/stringer": verifying non-authoritative meta tag
github.com/axw/gocov (download)
Fetching https://gopkg.in/matm/v1/gocov-html?go-get=1
Parsing meta tags from https://gopkg.in/matm/v1/gocov-html?go-get=1 (status code 200)
get "gopkg.in/matm/v1/gocov-html": found meta tag main.metaImport{Prefix:"gopkg.in/matm/v1/gocov-html", VCS:"git", RepoRoot:"https://gopkg.in/matm/v1/gocov-html"} at https://gopkg.in/matm/v1/gocov-html?go-get=1
gopkg.in/matm/v1/gocov-html (download)
github.com/matm/gocov-html (download)
runtime/internal/sys
runtime/internal/atomic
runtime
# runtime
../../../../go/src/runtime/cgo.go:9:3: //go:cgo_export_static main only allowed in cgo-generated code
make: *** [tools] Error 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by banks** [comment]
Thanks,

We'll be upgrading to 1.10 soon no doubt and will fix this if it affects us. 

I don't have a linux box with build chain on handy to test cross-compile right this minute but a quick search brings up https://groups.google.com/forum/#!topic/golang-nuts/52ZHzgo6u1k which is old but in which this exact error is caused due to GOROOTs being mangled by `gb` build tool.

> I have the same issue with Elasticsearch Beats

🤔 Hmmmm

As a sanity check can you confirm that the exact same build env/script works with go 1.9?

**Comment by FireBurn** [comment]
It does, I built it with 1.9.4 as soon as my build failed with 1.10

**Comment by katykk193** [comment]
I got the error of "//go:cgo_export_static main only allowed in cgo-generated code" with go1.10.1.linux-amd64.tar.gz, when I execute "go get github.com/tendermint/tendermint/cmd/tendermint".

**Comment by Tachone** [comment]
"I got the error of "//go:cgo_export_static main only allowed in cgo-generated code" with go1.10.1.linux-amd64.tar.gz, when I execute "go get github.com/tendermint/tendermint/cmd/tendermint"."


How to fix this problem?

**Comment by FireBurn** [comment]
So it seems something has changed between 1.9 & 1.10, adding the GO bin directory to my PATH fixes the issues I'm seeing - this wasn't required before

**Comment by stdupp** [comment]
May be you should check the go command is $GOROOT/bin/go .
