### ISSUE TITLE
Consul server is not clearing the old snapshots

### ISSUE THREAD

**Issue by hbmelachuru10** [hashicorp/consul#3913]
Hi,
Consul version: 0.8.4
We have 5 consul servers but one of the consul server is not clearing the old snapshots and it is creating as .tmp extension, which i dont see it in other consul servers. As the snapshots and raft.db is piling up, the /data folder size is at its max.

`sh-4.2$ cd /data/raft/snapshots/                                                                                                                                              
sh-4.2$ ls                                                                                                                                                                    
254567-7291011-1510286201297.tmp  254737-8909400-1510749370111.tmp   257218-22711993-1518363719958      257218-22867149-1518418506577.tmp  257394-26297283-1519414730624.tmp  
254567-7381365-1510308048576.tmp  254753-9246080-1510867645751.tmp   257218-22744840-1518375004897      257218-22867169-1518418518725.tmp  257394-26297283-1519414741973.tmp  
254615-7801146-1510415098697.tmp  254753-9254551-1510870714530.tmp   257218-22777700-1518386593456      257394-26297283-1519414656785.tmp  257394-26297283-1519414752595.tmp  
254701-8522589-1510614408528.tmp  254806-9974738-1511433413449.tmp   257218-22802360-1518395405996      257394-26297283-1519414669107.tmp  257394-26297283-1519414763589.tmp  
254701-8572405-1510631309618.tmp  254831-10086375-1511517895777.tmp  257218-22835184-1518407021582      257394-26297283-1519414681451.tmp  257394-26297283-1519414774231.tmp  
254717-8728626-1510684371816.tmp  257218-22637984-1518337442820      257218-22846395-1518410917080      257394-26297283-1519414693373.tmp  257394-26297283-1519414881304.tmp  
254724-8745062-1510690467795.tmp  257218-22662657-1518346288189      257218-22854601-1518413880611      257394-26297283-1519414707843.tmp  257394-26297283-1519414902677.tmp  
254734-8786179-1510705074823.tmp  257218-22687337-1518355053363      257218-22867116-1518418496578.tmp  257394-26297283-1519414718892.tmp  257394-26297283-1519414914430.tmp

sh-4.2$ cd 254567-7291011-1510286201297.tmp                                                                                                                                   
sh-4.2$ ls                                                                                                                                                                    
meta.json  state.bin                                                                                                                                                          
sh-4.2$ ls -al                                                                                                                                                                
total 71780                                                                                                                                                                   
drwxr-xr-x.  2 1000750000 root     4096 Nov 10 03:56 .                                                                                                                        
drwxr-xr-x. 42 1000750000 root     4096 Feb 23 19:41 ..                                                                                                                       
-rw-r--r--.  1 1000750000 root      720 Nov 10 03:56 meta.json                                                                                                                
-rw-r--r--.  1 1000750000 root 73195520 Nov 10 03:56 state.bin`

1. How often the snapshots are cleared ? And how many snapshots were available in the last state?
2. What does the .tmp extension mean in snapshots? I dont see that in other servers.
3. How can i manually check the consul server cluster state?
4. And also, does this issue impact the service discovery? Because the consul-pet-2 is having old IPs for the other app services.
5. Why is consul server(consul-pet-2) is using old IPs for the service?

Thank you for your response.

**Comment by preetapan** [comment]
Hi @hbmelachuru10 , I'll try to address the questions that I understand 

1 ) Two snapshots are retained, this comes from a value that Consul sets up [here](https://github.com/hashicorp/consul/blob/17805e463401ef9fd3b4688d426f29d4f9e398cd/agent/consul/server.go#L59)
2) The .tmp file is intermediate state while the snapshot is being built. After that intermediate step is done it should be renaming it to something like `254567-7291011-1510286201297`

Your server appears to be in an errored state, based on what you are describing it hasn't been able to successfully write snapshots, and make raft commits. 

Please share logs from your consul server (consul-pet-2) and after that we can try to diagnose the root cause.

**Comment by hbmelachuru10** [comment]
Thank you so much for your response. For now, i have cleared the old snapshots and restarted the consul server. I have zipped the logs for debugging purpose. we further debugging the logs.

**Comment by rai-deepankar** [comment]
Hello,
Is there a way to limit the size of the these snapshot files, along with the number of files?
Right now, in my setup, there are 3 snapshots, one being a .tmp, each with size of ~600MB; however raft.db is 41MB.
