### ISSUE TITLE
Join wan operation requires known IPs which are... unknown in advance

### ISSUE THREAD

**Issue by roman-cnd** [hashicorp/consul#3915]
Hi,

Sorry in advance about asking a clarification question here on github, I've checked gitter and it didn't yeild much information.

I'm looking to find a way to make wan join operation for clusters in different datacenters self-serving and easy. E.g. when consul server instance starts, it should know which cluster to join over WAN based on local metadata, tags etc. 

The networking part of the equation is solved already, agents can talk to each other directly. 

This is kinda is what retry_join does with `provider = abc`. But this seems like a challenging task because `retry_join_wan` only accepts lists of WAN IPs (or an address that must resolve to those IPs).

And having static, hardcoded IPs in the config file seem pretty gross.

Is there another discovery method to have consul cluster joined over WAN without the need to know IPs on the other side? Right now I'm experimenting with consul clusters behind ELB (IPs are always known and fresh) however, the agent needs a direct connection so that's probably a dead end.

Thanks!
Roman

**Comment by jhmartin** [comment]
I believe using an ELB will work. I used an ELB for local LAN joining -- the clients were configured with the ELB DNS name, with the servers behind that. The behavior I observed was the client would use the ELB for the initial discovery, then fetch all of the individual node IPs from gossip and not use the ELB again. I suspect something similar will work for WAN joining.

**Comment by roman-cnd** [comment]
The client is thinking that ELB's IPs are the ones to join, it can't get though them.

```
    2018/02/26 14:34:47 [INFO] agent: (WAN) joined: 0 Err: 3 error(s) occurred:

* Failed to join xxx.xxx.xxx.xxx: EOF
* Failed to join xxx.xxx.xxx.xxx: EOF
* Failed to join xxx.xxx.xxx.xxx: EOF
    2018/02/26 14:34:47 [WARN] agent: Join WAN failed: <nil>, retrying in 30s
```

**Comment by kyhavlov** [comment]
It sounds like you've used the [Cloud auto-join](https://www.consul.io/docs/agent/options.html#cloud-auto-joining) feature for the LAN retry-join, are you aware it can be used for the retry-join-wan config as well?

**Comment by roman-cnd** [comment]
I've tried `retry-join-wan` with cloud join feature, but it failed since there was no metadata service for X on provider Y. The creds were configured locally for X.

**Comment by kyhavlov** [comment]
Connecting to a different provider should still work even when you can't use the metadata from the local provider, can you not also specify the creds for Y locally?

**Comment by roman-cnd** [comment]
Oh, I see now - it should totally work with cloud discovery. 
https://github.com/hashicorp/go-discover/blob/master/provider/aws/aws_discover.go#L19-L33

**Comment by roman-cnd** [comment]
Ok, some progress...

"retry_join_wan": ["provider=aws region=us-east-1 tag_key=tag tag_value=value" ]

```
    2018/02/27 22:07:11 [ERR] agent: Join WAN: discover-aws: DescribeInstancesInput failed: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

aws ec2 describe-instances has no problems running

**Comment by 123BLiN** [comment]
> aws ec2 describe-instances
I think this may be not enough, I doubt you will also need describe tags, and describe network interfaces, but documentation says that this should be enough - strange.

**Comment by roman-cnd** [comment]
Ok, the case is finally closed. The last one was "user error".

Specifically, supervisord config for consul didn't have env variable `HOME` configured. Thus aws sdk couldn't find file with permissions in its usual place (~/.aws)

`retry_join_wan` behaves now 😄Thanks to Kyle for pointing out it can be used for service discovery in multi-cloud setups.

**Comment by shantanugadgil** [comment]
Just as a recommendation, you should do the permissions with a specific IAM role rather than keys.
Easier and less housekeeping.

**Comment by roman-cnd** [comment]
That's right, cluster in aws uses iam by default.
However, for this specific problem of making other consul clusters join over WAN to one in aws, the iam keys must be available on the non-aws servers. With the IAM role is restricted to describing instances only, everything is nicely 🔐
