### ISSUE TITLE
Unclear docs 

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/consul#3921]
Related: https://github.com/hashicorp/nomad/issues/304

I think the documentation on networking traffic (what component initiates traffic, over which protocol and to what component) is a bit unclear on: https://www.consul.io/docs/agent/options.html#ports - when I say component in this context it means server, agent, or server on the remote side of a wan.

Having certainty around the communication patterns is a prerequisite in order to be able to plan a deployment and firewall openings.

As far as I understand the docs, if not operating over wan (lan only), and having several network zones for the agents (with firewalls between the zones), and all servers in one network zone (again with firewalls in front of them) the only required opening is from the agents, towards the servers 8300/tcp?

**Comment by shantanugadgil** [comment]
How about a picture with servers and clients to show who talks to whom over which port and protocol.

**Comment by davidkarlsen** [comment]
That would be super awesome!

**Comment by kyhavlov** [comment]
The [architecture page](https://www.consul.io/docs/internals/architecture.html#10-000-foot-view) in the docs has a good diagram for what you're describing. Is this picture/doc page similar to what you were thinking of or is there some other aspect that's not clear there?

**Comment by davidkarlsen** [comment]
That seems to be spon on! Thanks!
