### ISSUE TITLE
Suggestion to use github.com/kevinburke/go-bindata

### ISSUE THREAD

**Issue by ilovezfs** [hashicorp/consul#3930]
I've just added a [formula for go-bindata in Homebrew](https://github.com/Homebrew/homebrew-core/pull/24801) based on [Kevin Burke's fork](https://github.com/kevinburke/go-bindata)

Instead of https://github.com/hashicorp/go-bindata, would you consider using https://github.com/kevinburke/go-bindata ? He's making release tags https://github.com/kevinburke/go-bindata/releases and others are having good luck with compatibility. See https://github.com/Dr-Terrible/go-overlay/issues/76#issuecomment-360482724

>That fork is API compatible with the original package and the author doesn't wish to diverge from it, or add new incompatible features

**Comment by ilovezfs** [comment]
It looks like the main alternative to https://github.com/kevinburke/go-bindata right now is https://github.com/shuLhan/go-bindata. I'm not sure if you have a preference between the two.

**Comment by preetapan** [comment]
@ilovezfs we will consider porting any useful patches over but prefer to maintain our own fork until we can fix Consul's build scripts to not pull HEAD of these third party tools, thus bringing in unintended changes.

**Comment by ilovezfs** [comment]
OK. Thanks for the reply. https://github.com/Dr-Terrible/go-overlay/issues/76#issuecomment-370777900 made a nice chart showing a sampling of current compatibility for those forks in case it's at all useful to you.
