### ISSUE TITLE
Protect webui for consul using ACL

### ISSUE THREAD

**Issue by Manayaan** [hashicorp/consul#3931]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### Description of the Issue (and unexpected/desired result)
My requirement is to to protect the Web-UI for Consul using ACL ,

I already using master -token only but Consul agent start giving Permission denied as soon as I start using master-token. my WebUI is protected after this but getting permission errors in agent servers

After that I tried to to use acl_token , After using this token Permission denied error gone from both Agents and Master Server , but my webui is still not protected and is open for everyone
### `consul version` for both Client and Server
Client: `[client version here]`
Server: `[server version here]`

### `consul info` for both Client and Server
Client:
```
cat config.json
{
"bind_addr": "10.80.32.39",
"client_addr": "0.0.0.0",
"pid_file": "/apps/consul/consul.pid",
"datacenter": "DOA",
"data_dir": "/apps/consul/data",
"log_level": "INFO",
"node_name": "Consul-ca",
"server": false,
"acl_token": "1ef3f529-d1ff-fibb-923b-7f90-0d80769a2e7b",
"rejoin_after_leave": true,
"retry_join": [
    "10.80.32.40:8301",
    ]
}


[Client `consul info` here]
```

Server:
```
{
  "acl_master_token": "xbig###abc",
  "acl_datacenter": "DOA",
  "acl_default_policy": "deny",
  "acl_token": "1ef3f529-d1ff-fibb-923b-7f90-0d80769a2e7b"
}


[Server `consul info` here]
```

### Operating system and Environment details

Linux

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by pearkes** [comment]
Prior to any work on ACLs I definitely recommend reviewing the [ACL Bootstrapping Guide](https://www.consul.io/docs/guides/acl.html#bootstrapping-acls). Seems like you're farther along here but it is worth taking a look at as it explains some of the concepts and potential challenges you're hitting.

It seems like you need to create 2 tokens and modify the anonymous token. Step 3 is the important one for you, I believe.

1. Create an agent token that has write permissions that your agents can utilize. This is something like:
```
curl \
    --request PUT \
    --header "X-Consul-Token: <token>" \
    --data \
'{
  "Name": "Agent Token",
  "Type": "client",
  "Rules": "node \"\" { policy = \"write\" } service \"\" { policy = \"read\" }"
}' http://127.0.0.1:8500/v1/acl/create
```
2. Modify the anonymous token so DNS queries etc work:

```
$ curl \
    --request PUT \
    --header "X-Consul-Token: <token> " \
    --data \
'{
  "ID": "anonymous",
  "Type": "client",
  "Rules": "node \"\" { policy = \"read\" }"
}' http://127.0.0.1:8500/v1/acl/update
```
3. Create a UI token. You can then use this in the UI by going to the settings page and inputting it there. That looks something like this:

```
curl \
    --request PUT \
    --header "X-Consul-Token: <bootstrap_token>" \
    --data \
'{
  "Name": "UI Token",
  "Type": "client",
  "Rules": "key \"\" { policy = \"write\" } node \"\" { policy = \"read\" } service \"\" { policy = \"read\" }"
}' http://127.0.0.1:8500/v1/acl/create
```

Hope that helps!
