### ISSUE TITLE
GRPC Check flag name "grpc_use_tls" should be "grpcusetls"

### ISSUE THREAD

**Issue by kefahi** [hashicorp/consul#3932]
The documentation of grpc check (https://www.consul.io/docs/agent/checks.html) clearly mentions the grpc check flag grpc_use_tls. However that flag has no effect; instead "grpcusetls" is honoured.

To reproduce the problem, setup a Grpc Health checking service with TLS  (https://github.com/grpc/grpc/blob/master/doc/health-checking.md); then create a service with checks (using the /v1/agent/service/register  api) if you use the documented flag you will get the error message below; if you change that flag to grpcusetls it will succeed.

Using the grcpc_use_tls (set to true) for Consul GRPC check against the TLS enabled Health service always fails with the following message in the logs:
 [DEBUG] Check "service:grpcrootid" failed: rpc error: code = Unavailable desc = transport is closing

consul version: 1.0.6

Querying the check data indicates that when using "grpc_use_tls"  then GRPCUseTLS is always false (i.e. the setting is ignored). It would only reflect value when grpcusetls is used.

It looks like the struct tag is not properly set for Check GRPCUseTLS. Looking at the code 
agent/agent_endpoint.go : func AgentRegisterService
I noticed that args structs.ServiceDefinition is used to call agent/http.go decodeBody
which uses mapstructure.Decode to parse the json passed to the api. The issue is that CheckType referenced in structs.ServiceDefinition does not have mapstructure tags. (agent/structs/check_type.go).

I also noticed duplications in Check type/definition. on of them that is not used by the api above has the correct mapstructure tag (agent/config/config.go). So another way to solve this issue is to refer the api code to use the ServiceDefinition/CheckDefinition in that config.go file instead.

**Comment by preetapan** [comment]
@kefahi We do use the right mapstructure label [here](https://github.com/hashicorp/consul/blob/5f31c8d8d3f3f90ab5f4c29ed6e29122dc7ec5a6/agent/config/config.go#L345) for agent check definitions, described in the documentation page you mentioned above https://www.consul.io/docs/agent/checks.html. There's unit tests that verify this as well. This is used in parsing service definition files that can be specified in the agent's config directory.

However, if you are using the /agent/service/register endpoint, then see the HTTP API documentation described here https://www.consul.io/api/agent/check.html#grpcusetls. There we correctly mention that the param in the json should be `GRPCUseTLS`. 

I can see how this is a source of confusion, sorry for that. We will consider making new features more uniform in the future
