### ISSUE TITLE
feature request: TCP+SSL health check

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/consul#3936]
### Description of the Issue (and unexpected/desired result)
Would it be possible to add functionality for a **TCP+SSL** health check with optional **SNI** field?

Equivalent of the following OpenSSL command client command:
```# openssl s_client -servername foo.example.com -connect zoo.example.com:443```

The SSL server I am using doesn't like the **connect-disconnect** caused by the TCP health check, and prints error log messages. ☹️ 

For now, I am making do with a script based health check which is a wrapper over openssl commandline.

### Reproduction steps
The SSL enabled server prints error log messages when the simple TCP health check occurs.

### `consul version` for both Client and Server
Client: `[Consul v1.0.6]`
Server: `[Consul v1.0.6]`

### Operating system and Environment details
CentOS 7.4+, Ubuntu 14.04, Ubuntu 16.04

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Hi,

Is this a fair ask? Or am I asking something inherently something wrong?

Thanks and Regards,
Shantanu

**Comment by mkeeler** [comment]
@shantanugadgil Thanks for the idea. It certainly seems like a reasonable request. If you or another community member had the time and motivation to implement this then we would be happy to review a PR for the feature. Alternatively, if others would also like to see this implemented add a :+1: upvote reaction to the original issue here as that is one factor we use to prioritize work.

**Comment by shantanugadgil** [comment]
bump, poke .. 🐛  👉 
😄

**Comment by shantanugadgil** [comment]
Some code I have **cobbled** together:
https://github.com/shantanugadgil/sslchecker

This serves my purpose as a standalone Go (static) based binary instead of having to include openssl inside the Docker container. Hopefully Consul would get this facility "builtin".

*** Last I checked, the Consul documentation doesn't **highlight** anywhere that `script` health checks attached to a Docker will execute **_inside_** the Docker.
(my job launcher being Nomad)

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
@mkeeler any thoughts on the TCP+SSL checker from my repo?

**Comment by shantanugadgil** [comment]
any eyeballs 👀 on this (https://github.com/shantanugadgil/sslchecker) to integrate the idea into Consul?

@pearkes @johncowen @kyhavlov @i0rek 

Thanks,
Shantanu

**Comment by jsosulska** [comment]
This is still a valid ask. Currently, TCP checks don't use SSL, so this would be adding functionality as well as adding the SNI optional field.

**Comment by pgporada** [comment]
@banks and @mkeeler I've put up PR #18381 that should complete this issue.
