### ISSUE TITLE
AgentServiceCheck struct: Args []string `json:"ScriptArgs,omitempty"`

### ISSUE THREAD

**Issue by domelz** [hashicorp/consul#3939]
### Description of the Issue (and unexpected/desired result)

https://github.com/hashicorp/consul/blob/v1.0.6/api/agent.go uses `json:"ScriptArgs,omitempty"` for the "Args" field of the AgentServiceCheck struct. 

Should `json:"ScriptArgs,omitempty"` be changed to `json:"Args,omitempty"`?

// AgentServiceCheck is used to define a node or service level check
type AgentServiceCheck struct {
	CheckID           string              `json:",omitempty"`
	Name              string              `json:",omitempty"`
	Args              []string            `json:"ScriptArgs,omitempty"`
	Script            string              `json:",omitempty"` // Deprecated, use Args.
	DockerContainerID string              `json:",omitempty"`
	Shell             string              `json:",omitempty"` // Only supported for Docker.
	Interval          string              `json:",omitempty"`
	Timeout           string              `json:",omitempty"`
	TTL               string              `json:",omitempty"`
	HTTP              string              `json:",omitempty"`
	Header            map[string][]string `json:",omitempty"`
	Method            string              `json:",omitempty"`
	TCP               string              `json:",omitempty"`
	Status            string              `json:",omitempty"`
	Notes             string              `json:",omitempty"`
	TLSSkipVerify     bool                `json:",omitempty"`

	// In Consul 0.7 and later, checks that are associated with a service
	// may also contain this optional DeregisterCriticalServiceAfter field,
	// which is a timeout in the same Go time format as Interval and TTL. If
	// a check is in the critical state for more than this configured value,
	// then its associated service (and all of its associated checks) will
	// automatically be deregistered.
	DeregisterCriticalServiceAfter string `json:",omitempty"`
}

### `consul version` for both Client and Server
Client: `1.0.6`
Server: `1.0.6`

### `consul info` for both Client and Server
Client:
```

```

Server:
```

```

**Comment by preetapan** [comment]
@domelz Thanks for reporting. This is a known issue (https://github.com/hashicorp/consul/issues/3587) 
and is called out in the documentation here - https://www.consul.io/api/agent/check.html#parameters. We accept both forms for backwards compatibility with Consul 1.0 and will deprecate ScriptArgs in a future relase.
