### ISSUE TITLE
Intermittent Service Discovery issue with consul servers

### ISSUE THREAD

**Issue by hbmelachuru10** [hashicorp/consul#3943]
We are using consul version 0.8.4. We have 5 consul servers and is mainly used for service discovery and consul kvs.
1. Sometimes consul server is resolving the old IPs(probably the pods got killed), why is the old IPs were not de-registered as soon as the client pod gets killed?  If so, how long we have to wait to deregister them. Before the pod gets killed, we are doing consul leave, so that it will leave gracefully and should de register the service.

2. I see some errors in the logs,    "2018/02/27 02:43:23 [ERR] memberlist: Failed to send ack: write tcp 10.0.28.95:8301->10.0.36.141:55040: i/o timeout from=10.0.36.141:55040". What does this mean?

3. We have enabled only tcp ports. Is it mandatory to include udp ports too? In architecture design, decided that we would be using only tcp ports. But the server logs shows that it is trying to connect udp too. How can i disable udp and make sure the consul uses only tcp. Is there any flags to use only tcp, instead of both udp and tcp.

4. Sometimes when the servers are resolving the DNS, it is throwing an error as "Name or service not known" intermittently. How can i check the cluster health at that particular defined time?

Thank you

**Comment by shilov** [comment]
Removing a service if the client leaves would be misleading. The service might still be running. Adding a health check would remedy this issue. 

Consul relies on UDP for the serf protocol and DNS. There's no way around it.

**Comment by hbmelachuru10** [comment]
Hi @shilov , Yes, we have added health checks, but problem still exists. Any suggestions?

**Comment by pearkes** [comment]
1. Once a node is deregistered it should stop resolving for services on that node.
2. Could be a number of things, typically we see this in network or CPU constrained environments. I'd verify the health of both of those things.
3. As @shilov mentioned, TCP is available for fallback in various UDP-first features of Consul, but we do not recommend relying on this for standard operation.
4. The DNS lookup is doing a healthcheck, it sounds like you may have no services at that address at that time.
