### ISSUE TITLE
Client/agent unable to communicate with Consul cluster over wan

### ISSUE THREAD

**Issue by hfarooqui** [hashicorp/consul#3947]
Experts,

I have a global cluster with 3 nodes in AWS.
DC1 does not have any additional server and idea is to register client with global cluster.
Is this even possible or do we have to have consul server per datacenter (as per consul architecture)?

I am unable to find any doumentation which talks about client/agent configuration for wan.

Any help in this regards will be highly appretiated.

**Comment by shilov** [comment]
You'll need servers in each datacenter, but those servers can communicate with other DCs.

**Comment by hfarooqui** [comment]
thanks @shilov 

Looks like I cannot have agents in DC talking directly to global consul cluster as cannot communicate over wan.

I created a consul server in my datacenter. When I try to join this server to global consul cluster I get the following error:
```
export CONSUL_HTTP_SSL=true
consul join --http-addr hfconsul.aries.mobileiron.net 10.10.10.204:8302 -wan
Error joining address '10.10.10.204:8302': Unexpected response code: 500 (1 error(s) occurred:

* Failed to join 10.10.10.204: remote error: Encryption is configured but remote state is not encrypted)
Error joining address '-wan': Unexpected response code: 500 (1 error(s) occurred:

* Failed to resolve -wan: lookup -wan: no such host)
Failed to join any nodes
```

Both the servers share the same encryption keys.

Any thoughts?

**Comment by shilov** [comment]
I believe you need to specify `-wan` followed by the address of the server you're trying to join

**Comment by hfarooqui** [comment]
```consul join --http-addr consul.examples.net  -wan 10.10.10.204:8302```
throws the same error :(

Yes, it will be a three node cluster in new dc.
Also I have come to realise that have a global consul cluster does not make much sense as each dc will have their own clusters and if they wish to share data they can do it over wan.

**Comment by hbmelachuru10** [comment]
hi @hfarooqui, 
I think you are trying to join with ports. But according to documentation, you dont have to include -wan ports. I have tried to join without mentioning ports.

sh-4.2$ consul join -http-addr=10.0.40.120:8500 -wan 173.34.56.121                                                                                                             
Successfully joined cluster by contacting 1 nodes.         
                                                                                                                   
sh-4.2$ consul join -http-addr=10.0.40.120:8500 -wan 173.34.56.121:8300                                                                                                        
Error joining address '173.34.56.121:8300': Unexpected response code: 500 (1 error(s) occurred:                                                                                
                                                                                                                                                                              
* Failed to join 64.101.7.121: read tcp 10.0.40.120:45230->173.34.56.121:8300: read: connection reset by peer)                                                                 
Failed to join any nodes.

**Comment by pearkes** [comment]
Given we haven't heard anything based on the suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
