### ISSUE TITLE
allow to register service only with specified name

### ISSUE THREAD

**Issue by DanielCharczynski** [hashicorp/consul#3949]
We would like to allow to register service **ONLY** with specified name eg:  "admin"

at the moment there is no such possibility.
If we create such ACL where will be possibility to register services like "admi1", "admin-abc" - everything that starts with "admin" prefix

This is critical security issue because there is possibility to register unlimited number of services.

Is there any possibility to fix this issue?

**Comment by preetapan** [comment]
@DanielCharczynski thanks for the report. This is a known limitation. We have some plans to better integrate [sentinel](https://www.hashicorp.com/sentinel) to enterprise Consul for more fine grained control like this.

**Comment by mkeeler** [comment]
@DanielCharczynski With the new ACL system in 1.4.0-rc1 Consul now supports exact matching on a resources segment and prefix matching requires opting in.

So for your policy you would write

```
service "admin" {
   policy = "write"
}
```

This will only allow registering the "admin" service and nothing else. For the sake of documenting it here, the corresponding prefix matching rule is:

```
service_prefix "admin" {
   policy = "write"
}
```
