### ISSUE TITLE
Add a CLI command to verify agent readiness

### ISSUE THREAD

**Issue by mstewa34** [hashicorp/consul#3953]
When bringing up a Consul agent I want to verify that it's ready for use before giving up control to other applications.  This is particularly important for larger clusters where it's possible that joining the cluster fully can take more time.

At the moment there's no nice way to verify this with the consul CLI. We could hit `consul info` but that doesn't provide any guarantees other than checking that the agent is listening for incoming requests.  Today we hit [/v1/status/leader](https://www.consul.io/api/status.html#get-raft-leader) which at minimum guarantees that the agent has joined the cluster successfully but requires tools outside of the consul CLI to send the request.

It doesn't seem like it would be too difficult to add a new command (or flag/parseable output to `info`) to verify that the agent was ready.  If it functions similarly to [/v1/status/leader](https://www.consul.io/api/status.html#get-raft-leader) then it would be susceptible to server leadership issues but that also might be useful to know of.

**Comment by domgoodwin** [comment]
I've made a PR which implements the -leader flag into info

**Comment by freddygv** [comment]
Hi @mstewa34, PR #4763 implemented a `consul operator ready` command that queries the `v1/status/leader` endpoint and returns the address of the leader. It's acting as a wrapper for the HTTP endpoint. Is that the kind of command that you were looking for?

Additionally, you mentioned that this endpoint is susceptible to server leadership issues. If there is no cluster leader, would you be OK with allowing applications to contact that agent? Many of the operations won't be available. 

It would be helpful if you could clarify what kind of state you expect. Do you want confirmation that the cluster has been bootstrapped and the client agent can communicate with servers? Even if the leader is unavailable the client can still take certain actions locally like registering services.

**Comment by i0rek** [comment]
@mstewa34 and @domgoodwin thank you for reporting and providing a PR!
@mkcp and I decided to close this issue and the corresponding PR because the requirements are not clear and the PR only adds a command that shows information which is available in `consul info` already.
