### ISSUE TITLE
ACLs ability to restrict per Datacenter

### ISSUE THREAD

**Issue by aroca** [hashicorp/consul#3955]
### Description of the Issue (and unexpected/desired result)

I am thinking it would be nice to be able to restrict tokens/policies to datacenters access.
Like having the policy for a token to allow reads but only from dc=[DC1] or dc=[DC1,DC2]

This is because there are sometimes that the KV prefixes are not that easy to manage, and sometimes you dont want for some agents in one DC to be able to access other DCs. Also would be great for services queries and registrations of course.

DOnt know if i was clear or if there is a way of currently doing something similar. SO here it goes the issue.

**Comment by mkeeler** [comment]
@aroca With the new ACL system in the 1.4.0-rc1 build (and currently in master), policies can be assigned a list of datacenters that policy is valid within. So now you can limit access to the KV (or any resource) to a particular set of datacenters.

You can check out the RC or wait for the 1.4.0-rc1 build, and I am going to close this as it has been implemented.
