### ISSUE TITLE
Fetch Events by LTime 

### ISSUE THREAD

**Issue by RcRonco** [hashicorp/consul#3968]
Hi, There is a way to fetch list of events by specific LTime or even to clean the events in node?
Right now Im using Consul to pass events between nodes, after a while each request to list events is big and there is no known way (at least to me) to filter the data by Index or LTime.

**Comment by banks** [comment]
As the docs mention you can filter by name, and we implicitly filter by ACL token (which is based on event name too). No such filtering exists for LTime, and the index is really just (based on) the event id with no ordering guarantees as noted in the Caveat in the docs. https://www.consul.io/api/event.html#list-events

What is your specific use-case for events? 

Events use gossip so they are not strongly ordered or reliable which makes any filter based on LTime or index have potentially surprising behaviour - limiting to only ones after X doesn't necessarily do what you want and might cause you to miss all new events after some sequence of restarts or failures.

The agent stores the last 256 events it's seen in a ring buffer and that is what this endpoint returns. So there is a fixed upper limit on how many are stored/returned: https://github.com/hashicorp/consul-connect/blob/acfc60523fd7cd13aa8d8377a037d3090a395ab7/agent/agent.go#L221.

It's hard to see how filtering can help given the semantics of events - perhaps it points to them being inappropriate for you use-case hence the question for what you need to achieve. Hopefully we can help figure out it it's the right tool for you and if so then how we can support your usage better :)

**Comment by RcRonco** [comment]
I have an application that use consul for multiple use cases like:
* coordinate operations based on the lock key feature.
* KV for central configuration
* Service Discovery
Because of the wide range of uses of Consul in the project, I tried to check if there is any way to use events. 

I need to find solution to a problem of update the internal state of the instances of the application, which require kind of PubSub solution for 518 Bytes Messages, I know that Consul event is not builded for that.

**Comment by banks** [comment]
Yeah I don't recommend Consul events as a generic transport/PubSub system for your apps as you guessed. Even if you only ever need low throughput, the lack of visibility into the distribution (unless you build that into your app which is at least as hard as using an external message queue or similar) and lack of guarantees about delivery or timing probably make it unnecessarily hard to reason about.

I'd recommend looking into a proper PubSub/queue service or building messaging into your app directly.
