### ISSUE TITLE
Suggestion: Allow -bind=eth0 / -advertise=eth0

### ISSUE THREAD

**Issue by mrusme** [hashicorp/consul#3969]
### Description of the Issue (and unexpected/desired result)

Rather than forcing the process that launches a consul agent/server to perform bash-acrobatics and (e.g. `export CONSUL_AGENT_BIND_ADDR=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)`), why not simply allow specifying the device-name on `-bind` and `-advertise`?

### Operating system and Environment details

Could be implemented for any OS consul runs on.

**Comment by rhyas** [comment]
There's support for something similar already in consul: https://godoc.org/github.com/hashicorp/go-sockaddr/template  It's not quite as simple as "eth0", but then,  eth0" isn't as simple as that on all OS's either. (:

**Comment by mrusme** [comment]
@rhyas that wouldn't work as a value to either of the parameters (`bind` / `advertise`), would it?

**Comment by takeda** [comment]
I have same issue, but I think there is a better way to solve this than -bind=eth0.

One of my issues is that on my development machine I have multiple interfaces and depending on situation (whether I'm connected to VPN or not, or whether I'm using WiFi or Ethernet) the interface to bind is different.

I made following script to solve it:

```
first_consul_server () {
	python -c 'import json, sys; print(json.load(sys.stdin)["start_join"][0])' < ${CONSUL_CONF}
}

outside_if () {
	if which ip > /dev/null; then
		ip route get $1 | awk '/dev/ {print $5; exit}'
	else
		route get $1 | awk '/interface/ {print $2; exit}'
	fi
}

my_ip () {
	outside_if $1 | xargs ifconfig | awk '/inet / {print $2; exit}'
}
```

Then use `-bind $(my_ip $(first_consul_server))`

What would be great is that Consul would assume that the right IP is attached to the interface that will be used to connect with Consul servers and this way we would not need to specify `-bind` explicitly unless automatic method would fail.

**Comment by takeda** [comment]
I see, so looks like perhaps my request should be listed as a separate issue from yours. It looks like both of these features won't conflict with each other.

**Comment by kyhavlov** [comment]
@mrusme It's valid to use the go-sockaddr syntax [linked above](https://godoc.org/github.com/hashicorp/go-sockaddr/template) to pass something like `consul agent -bind '{{ GetInterfaceIP "eth0" }}'` anywhere that you could use an address, such as `-bind`, `-advertise`, `-client` or for more specific things like the Serf LAN advertise address.

For @takeda's case it should be possible to use either `GetPrivateInterfaces` or `GetAllInterfaces` and then pick the interface to prioritize based on what you want. There are a lot of detailed examples on the godoc page. Hope that helps!

**Comment by pearkes** [comment]
I'm going to close this in favor of #4090, our go-sockaddr documentation is lacking and I think resolving that will help considerably with these types of questions.
