### ISSUE TITLE
Consul ACL error with Vault 0.9.5

### ISSUE THREAD

**Issue by kronjob** [hashicorp/consul#3972]
Description  :- Consul client throws ACL not found error with Vault 0.9.5. Same consul-access-token and same ACL policy works with Vault 0.7.

Reproduction steps :-
Running Vault 0.9.5 and Consul client in one kubernetes pod and consul server on another pod
storage "consul" {
                  address = "localhost:8500"
                  disable_registration = "true"
                  token = "$VAULT_CONSUL_KEY"
                }
                listener "tcp" {
                  address = "0.0.0.0:8200"
                  tls_disable = 1
                }
                listener "tcp" {
                  address = "0.0.0.0:9000"
                  tls_disable = 1
                }
                disable_mlock = true

Consul version :-
Client 1.0.6
Server 1.0.6

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 9a494b5f
	version = 1.0.6
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 40
	max_procs = 1
	os = linux
	version = go1.9.3
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 25
	members = 5
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 9a494b5f
	version = 1.0.6
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.244.2.11:8300
	server = true
raft:
	applied_index = 742
	commit_index = 742
	fsm_pending = 0
	last_contact = 25.602µs
	last_log_index = 742
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:bddb8ded-00bc-a865-b090-3f1c8304bbf1 Address:10.244.2.11:8300} {Suffrage:Voter ID:f1316e8a-0ba4-02ec-6c17-d09ae5ed8274 Address:10.244.1.25:8300} {Suffrage:Voter ID:16261898-9135-803f-c989-26a34eae74c8 Address:10.244.0.62:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 77
	max_procs = 1
	os = linux
	version = go1.9.3
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 25
	members = 5
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 3
	query_queue = 0
	query_time = 1

```

### Operating system and Environment details
Kubernetes cluster

### Log Fragments or Link to [gist](https://gist.github.com/)
Vault error -
Error checking seal status: Error making API request.

URL: GET http://localhost:8200/v1/sys/seal-status
Code: 500. Errors:

* failed to check seal configuration: Unexpected response code: 403

Error initializing: Error making API request.

URL: PUT http://localhost:8200/v1/sys/init
Code: 400. Errors:

* failed to check for initialization: Unexpected response code: 403

Consul client :
  2018/03/19 17:48:23 [ERR] consul: "KVS.Get" RPC failed to server 10.244.1.25:8300: rpc error making call: rpc error making call: ACL not found
    2018/03/19 17:48:23 [DEBUG] manager: cycled away from server "consul-1"
    2018/03/19 17:48:23 [ERR] http: Request GET /v1/kv/vault/core/seal-config, error: rpc error making call: rpc error making call: ACL not found from=127.0.0.1:32848
    2018/03/19 17:48:23 [DEBUG] http: Request GET /v1/kv/vault/core/seal-config (2.740423ms) from=127.0.0.1:32848
 2018/03/19 17:50:12 [ERR] consul: "KVS.ListKeys" RPC failed to server 10.244.0.62:8300: rpc error making call: rpc error making call: ACL not found
    2018/03/19 17:50:12 [DEBUG] manager: cycled away from server "consul-0"
    2018/03/19 17:50:12 [ERR] http: Request GET /v1/kv/vault/core/?keys=&separator=%2F, error: rpc error making call: rpc error making call: ACL not found from=127.0.0.1:33114
    2018/03/19 17:50:12 [DEBUG] http: Request GET /v1/kv/vault/core/?keys=&separator=%2F (2.44601ms) from=127.0.0.1:33114

**Comment by kronjob** [comment]
Hi,  
I am new to Vault/Consul so might have done something wrong here. Kindly help.
ACL policy for vault -
{
  "ID": "3ee7669e-2b97-11e8-aaa5-e37db31138b6",
  "Name": "Vault Token",
  "Type": "client",
  "Rules": "key \"vault/\" { policy = \"write\" } key \"\" { policy = \"read\" } service \"vault\" { policy = \"write\" } session \"\" { policy = \"write\" }"
}

**Comment by sureshchoudhary** [comment]
@kronjob Try adding **node "" { policy = "write" }** to the ACL policy rules.

**Comment by kronjob** [comment]
Thanks for your suggestion...I will try this out
