### ISSUE TITLE
consul snapshot fails 

### ISSUE THREAD

**Issue by bru2code** [hashicorp/consul#3997]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### Description of the Issue (and unexpected/desired result)

Issues with consul snapshots. This is running inside kubernetes pod with containers inside it.  Where /tmp is a read only file system for containers ofcourse. Is there a way we can explicitly state to consul snapshot command so that it doesn't use /tmp to get the snapshot or use working directory where we run this command, so that we can get away from filesystem permissions errors! Or any other ideas to get the backup of consul working perhaps! /consul/data is a persistent volume! 

Consul snapshot fails with below error. This is running on kubernetes/openshift containers. 

consul snapshot save backup-vault-1-mc8vb.snap
Error saving snapshot: Unexpected response code: 500 (failed to create snapshot file: open /tmp/snapshot521157298: read-only file system)

### `consul version` for both Client and Server
consul version
Consul v1.0.6
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:
```
consul info
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 9a494b5f
        version = 1.0.6
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 10.217.15.18:8300
        server = true
raft:
        applied_index = 579995
        commit_index = 579995
        fsm_pending = 0
        last_contact = 0
        last_log_index = 579995
        last_log_term = 494
        last_snapshot_index = 579925
        last_snapshot_term = 494
        latest_configuration = [{Suffrage:Voter ID:cee6a1c7-d98e-4130-3fa3-7eb54d964de0 Address:10.217.11.216:8300} {Suffrage:Voter ID:4362d7af-acdb-7eee-5e1e-be323f107d27 Address:10.217.14.223:8300} {Suffrage:Voter ID:d9703ff5-cb25-6d35-60ba-485664dd70cf Address:10.217.15.18:8300}]
        latest_configuration_index = 454779
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 494
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 114
        max_procs = 4
        os = linux
        version = go1.9.3
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 51
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 64
        members = 5
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 23
        members = 3
        query_queue = 0
        query_time = 1

```

### Operating system and Environment details
kubernetes v1.7.6+a08f5eeb62 
### Log Fragments or Link to [gist](https://gist.github.com/)
```
    2018/03/28 15:48:14 [INFO] consul.fsm: snapshot created in 30.27µs
    2018/03/28 15:48:14 [INFO] raft: Starting snapshot up to 579925
    2018/03/28 15:48:14 [INFO] snapshot: Creating new snapshot at /consul/data/raft/snapshots/494-579925-1522252094395.tmp
    2018/03/28 15:48:14 [INFO] snapshot: reaping snapshot /consul/data/raft/snapshots/494-578779-1522245003735
    2018/03/28 15:48:14 [INFO] raft: Compacting logs from 569572 to 569685
    2018/03/28 15:48:14 [INFO] raft: Snapshot to 579925 complete
    2018/03/28 15:48:14 [ERR] http: Request GET /v1/snapshot, error: failed to create snapshot file: open /tmp/snapshot521157298: read-only file system from=127.0.0.1:37648

```

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by leprechau** [comment]
Linking information discussed on gitter ...

The code here ...
https://github.com/hashicorp/consul/blob/master/snapshot/snapshot.go#L50-L53
uses ioutil.TempFIle to create that intermediate file.

The standard go conventions can be used to set the path …
https://golang.org/pkg/os/#TempDir

You should just need to set a `TMPDIR` environment variable in the Consul execution scope.

**Comment by bru2code** [comment]
Just to add to this, updating TMPDIR to a folder where I can write didn't work or make any difference either! 
```
sh-4.2# consul snapshot save backup-vault-1-mc8vb.snap
Error saving snapshot: Unexpected response code: 500 (failed to create snapshot file: open /tmp/snapshot885281385: read-only file system)
sh-4.2# env | grep TMP
TMPDIR=/consul/data/tmpdir/
sh-4.2# pwd
/consul/data/tmpdir
sh-4.2# touch file2
sh-4.2# ls
file1  file2  vault.json  vault1.json
sh-4.2# echo ' test file ' > file2
sh-4.2# cat file2
 test file
sh-4.2# consul snapshot save backup-vault-1-mc8vb.snap
Error saving snapshot: Unexpected response code: 500 (failed to create snapshot file: open /tmp/snapshot631285428: read-only file system)
sh-4.2#

```

**Comment by leprechau** [comment]
@bru2code so that's setting the `TMPDIR` on your shell.  That will need to be set in the consul agent (server) execution scope.

**Comment by leprechau** [comment]
Example ...

terminal 1
```
$ TMPDIR=/nonexistent consul agent -dev
```

terminal 2
```
$ consul snapshot save foo
Error saving snapshot: Unexpected response code: 500 (failed to create snapshot file: open /nonexistent/snapshot144063415: no such file or directory)
```

**Comment by preetapan** [comment]
Thanks for answering @leprechau, yes that's the right way to do it, you will have to override TMPDIR when starting the agent.

**Comment by bru2code** [comment]
Hi -  We Just realised that it still fails, didn't get to try this afterwards 
 consul snapshot save backup-vault-1-mc8vb.snap
Error creating snapshot file: open backup-vault-1-mc8vb.snap: read-only file system

Any further clues here ! 

Thnx, Raju

**Comment by leprechau** [comment]
What's the complete path?  That error message doesn't look complete.

**Comment by bru2code** [comment]
2018/04/02 13:58:43 [INFO] consul.fsm: snapshot created in 31.48µs
    2018/04/02 13:58:43 [INFO] raft: Starting snapshot up to 277191
    2018/04/02 13:58:43 [INFO] snapshot: Creating new snapshot at /consul/data/raft/snapshots/57-277191-1522677523977.tmp
    2018/04/02 13:58:43 [INFO] snapshot: reaping snapshot /consul/data/raft/snapshots/57-268931-1522625877979
    2018/04/02 13:58:43 [INFO] raft: Compacting logs from 266395 to 266951
    2018/04/02 13:58:44 [INFO] raft: Snapshot to 277191 complete
    2018/04/02 14:07:54 [INFO] consul.fsm: snapshot created in 35.882µs
    2018/04/02 14:07:54 [INFO] raft: Starting snapshot up to 277285
    2018/04/02 14:07:54 [INFO] snapshot: Creating new snapshot at /consul/data/raft/snapshots/57-277285-1522678074476.tmp
    2018/04/02 14:07:54 [INFO] snapshot: reaping snapshot /consul/data/raft/snapshots/57-276634-1522674027771
    2018/04/02 14:07:54 [INFO] raft: Compacting logs from 266952 to 267045
    2018/04/02 14:07:54 [INFO] raft: Snapshot to 277285 complete

**Comment by bru2code** [comment]
That's all I have in the logs!

**Comment by leprechau** [comment]
@bru2code so it looks like the server agent successfully created and reaped the snapshot in the data path.  Is it possible it's on the client side that it cannot write the snapshot?

You might also get more information if you look at `consul monitor -log-level=DEBUG` when creating the snapshot.

**Comment by preetapan** [comment]
> consul snapshot save backup-vault-1-mc8vb.snap
Error creating snapshot file: open backup-vault-1-mc8vb.snap: read-only file syste

If that's the command you ran, what directory did you run it from? It will save that file `backup-vault-1-mc8vb.snap` to the current directory. The user you are running it has probably does not have write permissions. Either give it a full path to a file in a directory with write permissions, or make the current directory writeable.

**Comment by bru2code** [comment]
Yes @preetapan  that did the trick. Cheers
