### ISSUE TITLE
Consul registers Vault service on port 80 instead of 8200

### ISSUE THREAD

**Issue by bis-sb** [hashicorp/consul#3999]
I'm experimenting with Consul, Nomad, and Vault and am having issues with how Consul registers the Vault service. I'm running those three applications as containers on three nodes, i.e. each node will have Vault, Consul, and Nomad running on it. Setup was simple and the discovery magic seemed to work right out of the box, however I notice that the vault service isn't registering correctly in Consul, i.e. I look in the UI and see this:
![server3](https://user-images.githubusercontent.com/22668001/38095675-02d07d30-333f-11e8-84ce-0785662f7d13.PNG)
![server2](https://user-images.githubusercontent.com/22668001/38095681-0575ffba-333f-11e8-88c5-473baf7f4108.PNG)
![server1](https://user-images.githubusercontent.com/22668001/38095686-07d02b32-333f-11e8-8fd9-c4e5d7e81931.PNG)

Two of those Vault instances are communicating on port 8200, the third is communicating on port 9200 (because of an existing Vault instance on that server), yet Consul registers all these Vault instances as running on port 80, why?

This is causing me issues because I want to use consul-template to generate an nginx conf file. That nginx.conf file has an upstream for Vault which will only contain an entry for the active Vault server; consul-template is able to successfully determine which Vault instance is the "active" one, the issue is that the template writes the upstream entry as {{.Address}}:{{.Port}} and Consul has the port registered as 80, thus trying to reach the endpoint fails. However, if I manually change that 80 to 8200 (or 9200, depending on which one is active) then it works as expected.

I have all the Vault instances configured nearly identically, for example a server with IP address 128.1.2.3 that's running Vault on port 8200 is configured as such:
```
listener "tcp" {
        address = "0.0.0.0:8200"
        tls_disable = "true"
}

storage "consul" {
        address = "128.1.2.3:8500"
        path = "vault"
        service_tags = "vault"
}

cluster_name = "vault.service.consul"
cluster_addr = "http://128.1.2.3:8200" (the address of Vault on that node)
api_addr = "http://1.1.1.1/vault" (the Nginx endpoint for Vault)

default_lease_ttl = "168h"
max_lease_ttl = "720h"
disable_mlock = "true" (True because I can't get mlock to work when Vault's running in a container)
```
I even tried setting "service_address" in the "consul" storage backend, but it seemed to have no effect as the service still gets registered as `vault::80` instead of `vault:<ip>:<correct port>`

**Comment by bis-sb** [comment]
After more experimenting it seems that Consul is deriving the Vault address from the `api_addr` field. In my case it's port 80, hence why Consul thinks Vault is running on port 80. 

Reading the [Vault HA documentation](https://www.vaultproject.io/docs/concepts/ha.html#client-redirection) again led me to try a different approach: set the `api_addr` to the address of Vault on one of the other servers: since I have 3 servers, I have each Vault instance setting the `api_addr` in a circular fashion, i.e. Vault 1's api_addr points to Vault 2, Vault 2's points to Vault 3, and Vault 3's points to Vault 1.

This now has the effect of registering the Vault service on the `api_addr` that was set in the Vault configuration, i.e. Consul registers Vault 1 with Vault 2's address, Vault 2 with Vault 3's address, and Vault 3 with Vault 1's address.

Is there really no way to configure Vault for HA mode, while having Consul correctly register the Vault service?

**Comment by preetapan** [comment]
@bis-sb Consul does not register Vault, its the other way around - Vault registers itself in Consul. You are likely missing some configuration 

https://www.vaultproject.io/docs/configuration/storage/consul.html should tell you how to override the service registration address if you don't want default behavior. I suggest asking this question in the Vault google group as well.

**Comment by bis-sb** [comment]
OK thanks for clearing that up about which app does the registering. 
The odd thing is that the only setting that controls the address Vault registers as is the `service_address`, but what I'm observing is that Vault always uses the `api_addr` setting (service_address seems to be ignored or at least not used in the way it's documented).
It's possible I'm missing another setting but the documentation makes no mention of using another setting in conjunction with service_address.
