### ISSUE TITLE
Consul allows stale reads during start-up

### ISSUE THREAD

**Issue by manjotkhangura** [hashicorp/consul#4008]
### Description of the Issue (and unexpected/desired result)
I am using Consul 1.0.6 and happened to see the similar behavior as "Consul allows stale reads during start-up #2644". This bug #2644  was fixed last year. More details below..

Originally, I saw the issue on 1.0.3 and then upgraded to 1.0.6 to see if the upgrade fixes it. But it did not. 

### Setup
* Linux box running microservices in a docker containers. 
* One of the microservice on startup reads a consul KV entry. I will call this service as 'foo'. 
* Consul too is running in a docker container on its own. It is the public consul container. 
* In docker-compose 'foo' is setup as depends-on 'consul. 

### Reproduction steps
* Power cycle the Linux box.
* 'foo' starts and reads consul KV entry
* Most of the time, on first KV data read it gets stale data that was written to it a while back. But after a while consul starts reading the correct value. 
* I observed that if foo reads the same KV pair value a couple of times on startup, the second value seems to be read back correctly for the few times I have tried it. 

### `consul version` for both Client and Server
Client: HTTP API call (Golang Client 1.0.6)
Server: 1.0.6

### `consul info` for both Client and Server
Client:
```
[Client `consul info` here]
```

Server:

```
gent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 2
build:
	prerelease = 
	revision = 48f3dd56
	version = 1.0.3
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 172.18.0.3:8300
	server = true
raft:
	applied_index = 185069
	commit_index = 185069
	fsm_pending = 0
	last_contact = 0
	last_log_index = 185069
	last_log_term = 12
	last_snapshot_index = 180825
	last_snapshot_term = 12
	latest_configuration = [{Suffrage:Voter ID:4c6807b1-0a29-a542-edbd-a06540509314 Address:172.18.0.3:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 12
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 84
	max_procs = 4
	os = linux
	version = go1.9.2
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 1
	event_time = 12
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1

```

### Operating system and Environment details
CentOS (Atomic) Linux with foo and consul running in their own docker containers 

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

**Comment by manjotkhangura** [comment]
Apparently I was not using persistent mode in my get HTTP API query for kv pair. I have changed it to persistent mode and it seems be returning consistent results so far.

**Comment by mkeeler** [comment]
@manjotkhangura It sounds like you figured out the problem so I am going to close this issue. If the issue reappears after your fix then please reopen the issue and we can look into it.
