### ISSUE TITLE
[Enhancement] Consul KV default to get

### ISSUE THREAD

**Issue by alkalinecoffee** [hashicorp/consul#4009]
Minor suggestion.  It would be nice to cut down a little bit of duplication by omitting `get` from simple read operations by adjusting the CLI KV subcommand to always default to `get`, ie

```
consul kv /mykey
# equivalent to
consul kv get /mykey
```

**Comment by pearkes** [comment]
Given other commands such as `consul snapshot` and `consul catalog` that have subcommands and are used as namespaces, similar to KV, do not have these defaults I think it would risk some amount of confusion. Basically, this type of shortcut isn't a current pattern and would be hard to apply more broadly.

Generally, I would argue the explicit subcommand is a good thing for users. Given that, I'm going to close this but do feel free to re-open if you feel it is a natural and obvious fit for the broader Consul UX.

**Comment by alkalinecoffee** [comment]
Fair enough. Thanks for the explanation.
