### ISSUE TITLE
"consul members" command hangs on the agents

### ISSUE THREAD

**Issue by neerajb** [hashicorp/consul#4011]
We have a 5000 node consul cluster - 5 servers and rest of them clients. After running them for about 48 hours the number of "failed" nodes reported by "consul members" command is increasing gradually (1000 so far). 
On the failed nodes these are the observations:
1) "Consul members" command and "agent/self" api is hanging and non-responsive. 
2) The RSS size for the consul agent process is between 1 GB - 2.5 GB compared to ~40 MB on the responsive nodes.

Version of client and server - 1.0.2

[Output](https://www.dropbox.com/s/s7dyj4qblhqpqnt/monitor.txt?dl=0) of consul monitor --log-level=DEBUG
 [Heap dump](https://www.dropbox.com/s/wnwa55e4kjg1ayn/pprof.consul.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz?dl=0) taken on 1 server when RSS size was around 275 MB

**Comment by mkeeler** [comment]
@neerajb What platform was this on? I am looking to pull the right binary from https://releases.hashicorp.com/consul/1.0.2/ to match the heap dump you gathered

**Comment by neerajb** [comment]
@mkeeler The binary is amd64 arch running on debian 8

**Comment by neerajb** [comment]
1) Overall cpu utilization is very low. Here is a sar sample
[sar.txt](https://github.com/hashicorp/consul/files/1888587/sar.txt)

2) Packet loss also seems to be improbable. Here is a ping sample between 2 nodes:
[ping.txt](https://github.com/hashicorp/consul/files/1888592/ping.txt)


Also I can see > 9900 goroutines inside consul agent process stuck in 
"/goroot/src/runtime/sema.go:56 sync.runtime_Semacquire (0x43ee19)"

**Comment by mkeeler** [comment]
@neerajb Thanks for the update. 9900+ goroutines hanging out waiting for the lock could certainly cause this behavior too. I am going to dig into the code a bit more to audit the locking a bit and will get back with you.

**Comment by neerajb** [comment]
@mkeeler Seem to have found the issue. There is a deadlock scenario that is being triggered.
serf.go Stats() api is taking a Rlock on memberLock and waiting for TransmitLimitedQueue q.Lock inside NumQueued() in memberlist.
While getBroadcasts() in memberlist has taken the q.Lock and is waiting for memberLock Rlock.

The Stats() API was hit via /agent/Self HTTP API which was triggered by our healthcheck script.
Disabling this script has fixed the issue for us for the time being.
I think if we release the memerlock Lock inside Stats() API before trying to acquire TransmitLimitedQueue lock it should fix the issue. I will be happy to submit a PR for the same.

**Comment by mkeeler** [comment]
@neerajb Thanks a ton. If you had a branch ready for PR we would be glad to take it.

**Comment by mkeeler** [comment]
After the 1.0.7 release I am going to update the vendoring for serf to pull in these changes.

**Comment by neerajb** [comment]
Thanks @mkeeler

**Comment by pearkes** [comment]
Should be fixed by #4088.
