### ISSUE TITLE
Make limits a reloadable configuration

### ISSUE THREAD

**Issue by guidoiaquinti** [hashicorp/consul#4012]
### Description of the Issue (and unexpected/desired result)
Right now it's not possible to apply [limit](https://www.consul.io/docs/agent/options.html#limits) changes without a restart. It could be nice make them a reloadable configuration.
 
### Reproduction steps
- edit `limits` in the config
- send a `SIGHUP` to consul
- `limits` are not refreshed at runtime

**Comment by jwasinger** [comment]
If it's alright, I'd like to make an attempt at this issue.  It's been awhile since I made contributions to Consul and it would be nice to get some more :)
