### ISSUE TITLE
Adding support for Prometheus endpoint in Consul Agents

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#4014]
Hello,

It seems that https://github.com/armon/go-metrics did add support for Prometheus

Would you agree to add support for it in Consul to Consul stats could be easily scrapped by Prometheus?

Some fixes have been applied on Nov 16, 2017 to the lib, so basically upgrading a bit the lib, and I am OK to do a PR adding support for it.

Would you consider such inclusion ?

Kind Regards

**Comment by guidoiaquinti** [comment]
+1 🎉

**Comment by pierresouchay** [comment]
The PR adds supports for Prometheus endpoint.

* Endpoint can be reached with `/v1/agent/metrics?format=prometheus` with the same semantics as Nomad implementation
* to test the feature, you can use for instance: the flags in command line: ```consul agent -hcl 'telemetry{ prometheus_retention_time="24h"}' -hcl 'telemetry{disable_hostname=true}'```

I added in the documentation that disable_hostname=true is recommended

**Comment by pierresouchay** [comment]
This PR: https://github.com/hashicorp/consul/pull/4042 has to be considered as well to use the multi-dimensional features of Prometheus

**Comment by pearkes** [comment]
I hope you don't mind @pierresouchay but I'm going to call this closed given your work was included in 1.1.0 of Consul. As we know https://github.com/hashicorp/consul/pull/4042 is still open, but I think that is suitable to track the addition of labels (and has the relevant context).
