### ISSUE TITLE
Unable to remove node from cluster

### ISSUE THREAD

**Issue by makeacode** [hashicorp/consul#4027]
https://github.com/hashicorp/consul/blob/ac09b30d3304a6c90de1c59f23caed2215c3ede0/agent/consul/state/session.go#L389

Somehow one of my node's session has gotten into a bad state and i'm unable to delete it from the cluster.  It's throwing an error on the line referenced above because the session has no behavior.

Output of api call on session:

[
  {
    "ID": "1840ec6c-e963-e002-693c-1b8d7bcfdbc9",
    "Name": "Vault Lock",
    "Node": "vault01",
    "Checks": [
      "serfHealth"
    ],
    "LockDelay": 15000000000,
    "Behavior": "",
    "TTL": "",
    "CreateIndex": 89696,
    "ModifyIndex": 0
  }
]

Output from consul server when trying to deregister node:

Apr 12 12:29:48 consul01 consul[1286]: consul.fsm: DeleteNode failed: failed deleting session: unknown session behavior ""
Apr 12 12:29:48 consul01 consul[1286]: 2018/04/12 12:29:48 [WARN] consul.fsm: DeleteNode failed: failed deleting session: unknown session behavior ""

Snapshot of how it looks in consul UI:
![capture](https://user-images.githubusercontent.com/12228368/38691691-96240244-3e4f-11e8-96d0-6f477d5129c8.PNG)

**Comment by shantanugadgil** [comment]
how about the following:
* stop the consul agent on the node
* delete the data-dir on the node
* do a force-leave of the node (from the server)
* start Consul agent again on the node.

**Comment by makeacode** [comment]
@shantanugadgil sorry for the delay...the node in question has already been deleted so I cannot perform the steps listed above.  the problem seems to be in the data the consul servers are maintaining about the node's sessions.  because the session has no behavior defined (for unknown reason) it hits the path in the code where it just pops an exception and no deletion happens

**Comment by pearkes** [comment]
Thanks for the bug report. I think we'll need a reproduction to help understand what is going on here. I'm going to close this bug encourage a new issue with those steps if appropriate.
