### ISSUE TITLE
Document service metadata in services documentation

### ISSUE THREAD

**Issue by pearkes** [hashicorp/consul#4032]
#3811 added support for service metadata and documented the API endpoints, but we should also add  some examples to the [service definition](https://www.consul.io/docs/agent/services.html) documentation.

**Comment by joelcollin** [comment]
@pearkes, this seems to have been addressed in #4047 by @pierresouchay (https://github.com/hashicorp/consul/pull/4047/files/303997ff552d4c70ebf66e0e1346bfe6f4e2a95d).

**Comment by pearkes** [comment]
Yes it was, thanks @joelcollin!
