### ISSUE TITLE
DNS query returns NXDOMAIN sporadically

### ISSUE THREAD

**Issue by pheitman** [hashicorp/consul#4034]
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:

### Description of the Issue (and unexpected/desired result)

I am using consul as a DNS server, querying for the services registered with consul. Occasionally (within a thousand queries but usually at the worst possible time), a query will return NXDOMAIN instead of the IP address of the service. If I use the following test, it will fail within a minute and a half:

while [ -n "$(getent hosts postgres-primary.service.primehome)" ]; do
    sleep 0.1
done
echo "getent postgres-primary.service.primehome FAILED!"

I have done a similar test, with 

curl -sf http://localhost:8500/v1/health/service/postgres-primary?passing

and it doesn't fail, which implies to me that the problem is not that the service is unhealthy

I expect (and require) that as long as the service is registered and is healthy that the dns query reply with the service's IP address. 

### Reproduction steps

Configure consul with the dns port as 53 and the domain as 'primehome'. Register a service with consul (with the domain primehome). Run the test shown above to query DNS for the <service>.service.primehome. Do this until it fails to return the ip address of the service.

### `consul version` for both Client and Server
Client: 0.7.5
Server: 0.7.5

### `consul info` for both Client and Server
Client:
```
I am running the test against the server. See the section below
```

Server:
```
 agent:
	check_monitors = 0
	check_ttls = 1
	checks = 2
	services = 3
build:
	prerelease = 
	revision = '21f2d5a
	version = 0.7.5
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 172.18.0.2:8300
	server = true
raft:
	applied_index = 508531
	commit_index = 508531
	fsm_pending = 0
	last_contact = never
	last_log_index = 508531
	last_log_term = 8
	last_snapshot_index = 508071
	last_snapshot_term = 8
	latest_configuration = [{Suffrage:Voter ID:172.18.0.2:8300 Address:172.18.0.2:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 8
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 69
	max_procs = 4
	os = linux
	version = go1.7.5
serf_lan:
	encrypted = false
	event_queue = 0
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 6
	members = 2
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

running in a docker container (docker 1.13.1). Running the dns lookup test from a bash shell within the consul server container. The postgres server is running in a separate container. It has its own local consul agent

### Log Fragments or Link to [gist](https://gist.github.com/)

Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 28 1} (368.774µs) from client 127.0.0.1:53561 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 1 1} (261.771µs) from client 127.0.0.1:54122 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 28 1} (354.277µs) from client 127.0.0.1:44728 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 1 1} (216.88µs) from client 127.0.0.1:51954 (udp)
2018/04/16 20:57:40 [DEBUG] http: Request PUT /v1/session/renew/f302c190-5684-75a3-c7b5-6a6d15cd49e9 (118.821µs) from=127.0.0.1:37600
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 28 1} (364.201µs) from client 127.0.0.1:50341 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 1 1} (309.239µs) from client 127.0.0.1:59403 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 28 1} (374.285µs) from client 127.0.0.1:48859 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 1 1} (273.332µs) from client 127.0.0.1:58175 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 28 1} (349.584µs) from client 127.0.0.1:49441 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 1 1} (283.964µs) from client 127.0.0.1:34944 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 28 1} (329.92µs) from client 127.0.0.1:33419 (udp)
2018/04/16 20:57:40 [DEBUG] dns: request for {postgres-primary.service.primehome. 1 1} (376.901µs) from client 127.0.0.1:34866 (udp)

This was recorded from 'consul monitor -log-level=trace'. There was nothing to indicate why NXDOMAIN was returned after the last dns: entry

**Comment by pearkes** [comment]
Thanks for the report. This is worrying but this version of Consul is rather old.

Did you disable [allow_stale](https://www.consul.io/docs/agent/options.html#allow_stale) or are you using the default?

**Comment by pheitman** [comment]
Thank you for your comment. I thought the same thing (that this version of Consul is rather old). I've upgraded to 1.0.7 and retried the test. Using getent hosts still fails rather quickly (a minute or so at 10 queries per second). However, 'host -t A' seems to be working well - I have been running for 2.5 hours without a problem. With 0.7.5, even 'host -t A' would fail within a couple of minutes. I'm hopeful that this problem is not a problem in the latest version and can consider this closed
