### ISSUE TITLE
Consul binding to wrong address / ignoring bind_address

### ISSUE THREAD

**Issue by iceman91176** [hashicorp/consul#4039]
Hello,

### Issue
we are experiencing a strange issue with our consul cluster (new installation). All consul-agents are configured to talk to each other by IPv6 (parameter bind_addr). And all except one use IPv6. This one starts up and uses one of the (private) IPv4-Adresses it can find as serf/cluster-ip address. Of course this host cannot reach the other consul membersby their IPv6-Address , and they cannot reach the IPv4-Host, although in the member-list the node is listed as alive on all nodes.

We deployed all consul clients in this Dc with ansible, so the configuration (exceptt bind_addr) is identical.

### Reproduction steps
It ony happened one this one host, but on this one happens all the time.  So after removing all data from consul-data dir on the client and starting from scratch we have the same issue.

### `consul version` for both Client and Server
Client: `1.0.7`
Server: `1.0.7`

### `consul info` for both Client and Server
Client:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = fb848fc4
        version = 1.0.7
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 36
        max_procs = 8
        os = linux
        version = go1.10
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 4
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 69
        members = 25
        query_queue = 0
        query_time = 1
```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = fb848fc4
        version = 1.0.7
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = [2a00:1f08:900:3::2]:8300
        server = true
raft:
        applied_index = 1846
        commit_index = 1846
        fsm_pending = 0
        last_contact = 34.039386ms
        last_log_index = 1846
        last_log_term = 4
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:b04ca821-8cde-181a-edef-7b439b2ca48e Address:[2a00:1f08:900:3::1]:8300} {Suffrage:Voter ID:34aafb72-c099-dc94-d328-a4af26b80260 Address:[2a00:1f08:900:3::2]:8300} {Suffrage:Voter ID:adebc4e5-c6b8-5db0-d560-d8d41c959efb Address:[2a00:1f08:900:1::6]:8300}]
        latest_configuration_index = 1
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 4
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 137
        max_procs = 8
        os = linux
        version = go1.10
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 4
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 69
        members = 25
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 4
        members = 3
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details
CentOS Linux release 7.3.1611 (Core)

### Log Fragments or Link to [gist](https://gist.github.com/)
Client logs

Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: serf: EventMemberJoin: ceph-dc-1-01-mon-03 10.60.0.26
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: agent: Started DNS server 0.0.0.0:8600 (tcp)
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: agent: Started DNS server 0.0.0.0:8600 (udp)
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: agent: Started HTTP server on [::]:8500 (tcp)
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: ==> Consul agent running!
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: Version: 'v1.0.7'
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: Node ID: 'f80dd96c-312c-a3a6-3dfb-686b809deb8e'
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: Node name: 'ceph-dc-1-01-mon-03'
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: Datacenter: 'dc-witcom-cloud' (Segment: '')
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: Server: false (Bootstrap: false)
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, DNS: 8600)
Apr 17 11:50:39 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[160228]: Cluster Addr: 10.60.0.26 (LAN: 8301, WAN: 8302)

Errors on this host are (repeating)
Apr 17 13:19:18 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[171141]: agent: Coordinate update error: rpc error getting client: failed to get conn: dial tcp: address 10.60.0.26:0: no suitable address found
Apr 17 13:19:21 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[171141]: memberlist: Initiating push/pull sync with: [2a00:1f08:900:3::2]:8301
Apr 17 13:19:21 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[171141]: 2018/04/17 13:19:21 [DEBUG] memberlist: Initiating push/pull sync with: [2a00:1f08:900:3::2]:8301
Apr 17 13:19:45 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[171141]: consul: "Catalog.NodeServices" RPC failed to server [2a00:1f08:900:3::1]:8300: rpc error getting client: failed to get conn: dial tcp: address 10.60.0.26:0: no suitable
Apr 17 13:19:45 ceph-dc-1-01-mon-03.mgmt.witcom.net consul[171141]: 2018/04/17 13:19:45 [ERR] consul: "Catalog.NodeServices" RPC failed to server [2a00:1f08:900:3::1]:8300: rpc error getting client: failed to get conn: dial tcp: address

On server(s)
Apr 17 13:20:15 object-storage-gw-02.mgmt.witcom.net consul[35505]: memberlist: Failed to send ping: write udp [2a00:1f08:900:3::2]:8301->10.60.0.26:8301: sendto: network is unreachable
Apr 17 13:20:15 object-storage-gw-02.mgmt.witcom.net consul[35505]: 2018/04/17 13:20:15 [ERR] memberlist: Failed to send ping: write udp [2a00:1f08:900:3::2]:8301->10.60.0.26:8301: sendto: network is unreachable

Thanks
Carsten

**Comment by mkeeler** [comment]
@iceman91176 What is the command being used to run the consul client that fails. Is it used a sock addr template for the bind addr or are you specifying it manually?

**Comment by iceman91176** [comment]
We are starting consul like this

consul agent -config-dir=/etc/consul.d

Bind-Addr is configured manually/hardcoded in the config-file. The config-files are generated with ansible
It works on dozens of different hosts without problems

{
    "addresses": {
        "dns": "0.0.0.0",
        "http": "0.0.0.0",
        "https": "0.0.0.0"
    },
    "bind_addr": "2a00:1f08:900:1::7",
    "data_dir": "/var/consul",
    "datacenter": "...",
    "domain": "...",
    "enable_syslog": true,
    "encrypt": "...",
    "log_level": "INFO",
    "node_name": "ceph-dc-1-01-mon-02",
    "retry_join": [
        "[2a00:1f08:0900:3:0:0:0:1]",
        "[2a00:1f08:0900:3:0:0:0:2]",
        "[2a00:1f08:900:1::6]"
    ],
    "server": false
}
