### ISSUE TITLE
Upgraded consul cluster fails to elect leader, continuously attempts to

### ISSUE THREAD

**Issue by dpedu2** [hashicorp/consul#4046]
### Description of the Issue (and unexpected/desired result)

I have a 3 node consul 0.6.4 cluster that I wanted to upgrade to the latest version, 1.0.7. These nodes serve only as the backend for a vault server.

I upgraded by moving the new binary into place on the leader first as mentioned in the docs and restarting the service, which looked OK - one of the older nodes became the leader, I believe. However, after performing the same steps on the remaining two nodes, some oddness started.

It seemed like the cluster was trapped in a cycle of electing a new leader at which time the elected leader would log the following. See below.

As a workaround, I tried 0.9.3 instead which instantaneously worked. 

### Reproduction steps

- Create consul cluster on an older version, we used 0.6.4
- Upgrade to 1.0.7
- Chaos

### `consul version` for both Client and Server
Client: n/a
Server: `v1.0.7`

### `consul info` for both Client and Server
Client:
```
n/a not using client
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 1
	services = 1
build:
	prerelease =
	revision = 112c060
	version = 0.9.3
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.1.60.240:8300
	server = true
raft:
	applied_index = 7241327
	commit_index = 7241327
	fsm_pending = 0
	last_contact = 37.083134ms
	last_log_index = 7241327
	last_log_term = 8583
	last_snapshot_index = 7235419
	last_snapshot_term = 8328
	latest_configuration = [{Suffrage:Voter ID:10.1.60.240:8300 Address:10.1.60.240:8300} {Suffrage:Voter ID:10.1.59.89:8300 Address:10.1.59.89:8300} {Suffrage:Voter ID:10.1.62.96:8300 Address:10.1.62.96:8300}]
	latest_configuration_index = 7240855
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 8583
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 82
	max_procs = 1
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 300
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 134
	members = 3
	query_queue = 0
	query_time = 5
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 48
	members = 3
	query_queue = 0
	query_time = 4
```

### Operating system and Environment details

Ubuntu 14.04.4 x64
Kernel 3.16.0-69-generic
Running in VMware VMs

### Log Fragments 

```
2018/04/18 12:16:26 [WARN] raft: Rejecting vote request from 10.1.60.240:8300 since our last term is greater (8553, 8551)
    2018/04/18 12:16:27 [ERR] agent: failed to sync remote state: No cluster leader
    2018/04/18 12:16:29 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2018/04/18 12:16:29 [INFO] raft: Node at 10.1.59.89:8300 [Candidate] entering Candidate state in term 8555
2018/04/18 12:16:29 [WARN] Unable to get address for server id 10.1.62.96:8300, using fallback address 10.1.62.96:8300: Could not find address for server id 10.1.62.96:8300
2018/04/18 12:16:29 [WARN] Unable to get address for server id 10.1.60.240:8300, using fallback address 10.1.60.240:8300: Could not find address for server id 10.1.60.240:8300
2018/04/18 12:16:29 [WARN] Unable to get address for server id 10.1.59.89:8300, using fallback address 10.1.59.89:8300: Could not find address for server id 10.1.59.89:8300
    2018/04/18 12:16:29 [INFO] raft: Election won. Tally: 2
    2018/04/18 12:16:29 [INFO] raft: Node at 10.1.59.89:8300 [Leader] entering Leader state
    2018/04/18 12:16:29 [INFO] raft: Added peer 10.1.60.240:8300, starting replication
    2018/04/18 12:16:29 [INFO] raft: Added peer 10.1.59.89:8300, starting replication
    2018/04/18 12:16:29 [INFO] raft: Added peer 10.1.62.96:8300, starting replication
2018/04/18 12:16:29 [WARN] Unable to get address for server id 10.1.62.96:8300, using fallback address 10.1.62.96:8300: Could not find address for server id 10.1.62.96:8300
    2018/04/18 12:16:29 [INFO] consul: cluster leadership acquired
2018/04/18 12:16:29 [WARN] Unable to get address for server id 10.1.60.240:8300, using fallback address 10.1.60.240:8300: Could not find address for server id 10.1.60.240:8300
2018/04/18 12:16:29 [WARN] Unable to get address for server id 10.1.59.89:8300, using fallback address 10.1.59.89:8300: Could not find address for server id 10.1.59.89:8300
    2018/04/18 12:16:29 [INFO] consul: New leader elected: vault3.site.com
    2018/04/18 12:16:29 [INFO] raft: Node at 10.1.59.89:8300 [Follower] entering Follower state (Leader: "")
    2018/04/18 12:16:29 [ERR] consul: failed to wait for barrier: leadership lost while committing log
    2018/04/18 12:16:29 [INFO] consul: cluster leadership lost
    2018/04/18 12:16:29 [WARN] raft: AppendEntries to {Voter 10.1.60.240:8300 10.1.60.240:8300} rejected, sending older logs (next: 7241058)
    2018/04/18 12:16:29 [WARN] raft: AppendEntries to {Voter 10.1.62.96:8300 10.1.62.96:8300} rejected, sending older logs (next: 7241056)
    2018/04/18 12:16:29 [ERR] agent: Coordinate update error: No cluster leader
```

**Comment by jhmartin** [comment]
Thats quite a jump in versions. After you stabilized on 0.9.3 have you tried upgrading again?

**Comment by dpedu2** [comment]
I did not try upgrading further after 0.9.3 was deployed. I'm planning on trying the upgrade again but it will take some time to coordinate.

**Comment by pearkes** [comment]
Agreeing with @jhmartin here -- given the jump (that is a huge delta in Consul's versioning) I would expect things to go wrong. We recommend reading the [upgrade notes](https://www.consul.io/docs/upgrading.html) and upgrading in smaller increments in this type of scenario. Once you try 0.9.3 -> 1.0.7 can you let us know how it goes?

**Comment by dpedu2** [comment]
If jumping across versions isn't supported I would expect to see something on that page suggesting so. It specifically mentions that backwards incompatible changes have "not been an issue yet." Perhaps this line should be removed?

Additionally supporting this is the linked [protocol compatibility](https://www.consul.io/docs/compatibility.html) page that shows both my original version and 1.0.7 speak the same protocol versions and agree on the "latest" protocol version. Likewise, the [version specific](https://www.consul.io/docs/upgrade-specific.html) upgrade guide shares the same sentiment in that it lacks constraints. I agree that a large jump is inherently riskier but if this is something Consul doesn't support it should be documented.

**Comment by kyhavlov** [comment]
@dpedu2 This section in the version specific upgrade guide talks about a raft protocol change in v1.0, and how it's relevant when upgrading from a version pre 0.8.0 to 1.0 (which seems to be the issue that your servers had): 
https://www.consul.io/docs/upgrade-specific.html#raft-protocol-now-defaults-to-3

**Comment by pearkes** [comment]
Given we discussed the versioning expectations above, I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

We will definitely continue focusing on how to be sure that our compatibility promise is clearer as we write further upgrade guides.
