### ISSUE TITLE
Enhancement: ability to purge raft of old peers

### ISSUE THREAD

**Issue by jefferai** [hashicorp/consul#405]
I have an issue where one of my servers has an IP that occasionally changes upon reboot. As I have now learned, this causes the cluster to lose sync because eventually, after a few reboots, the cluster thinks it has lost a majority of its nodes. E.g. it starts out with 3 nodes; then has "3/4" nodes, then has "3/5" nodes; then after a reboot it drops to "2/5" (losing quorum) and after the machine starts back up it's "3/6" (still no quorum).

Can a way to purge Raft of nodes you know to be invalid be implemented? It'd be nicer if you can tell Consul that particular peers are no longer valid, rather than having to go through a bootstrap.

**Comment by slackpad** [comment]
This is now supported in Consul 0.7 via the `consul operator` command and API, the outage guide has been updated with details - https://www.consul.io/docs/guides/outage.html.
