### ISSUE TITLE
grpc check returning NOT_SERVING should be treated as warning and not critical

### ISSUE THREAD

**Issue by gorset** [hashicorp/consul#4054]
We want to use the GRPC health check with DeregisterCriticalServiceAfter, but NOT_SERVING is treated as critical which means we risk the service being automatically deregistered.

We have been using DeregisterCriticalServiceAfter with the HTTP check so that processes with a unclean shutdown (linux OOM killer, kill -9, etc) is removed automatically. The HTTP checks will treat 429 as a warning, which means we can can disable a server temporary without problem (this could be due to overload, maintenance, vacuum, etc) and still have a short timeout like 1 minute for DeregisterCriticalServiceAfter. This has worked very well for us and this has been a sufficient solution to avoid getting orphaned service registrations.

If NOT_SERVING is treated as a warning (similar to 429 for HTTP health check) all our problems would go away and we could use DeregisterCriticalServiceAfter again with a low timeout, making the system less brittle.

**Comment by PhilipGough** [comment]
Would it be a good idea to make the status for GRPC configurable in the check definition? As in warning or critical, while defaulting to critical? If yes then I can take a look at adding this.

**Comment by pearkes** [comment]
We'd happily accept a PR for this. Otherwise, we likely won't be extending the GRPC beyond their current capabilities in the near future, so will close this.
