### ISSUE TITLE
One of Datacenter Dead and removed from Wan pool but still issues.

### ISSUE THREAD

**Issue by ansham22** [hashicorp/consul#4055]
Hi Team,

Suddenly I started seeing an issue where i removed one of the DCs from my wan pool few days back and everything was perfectly fine. But what I can see today one of my consul agent is trying to contact to that DC and i can see this query fired from consul-agent to consul servers. 

    DNS-Slave.39316 > 172.21.25.26.8300: Flags [P.], cksum 0x545f (incorrect -> 0x835f), seq 40828:41041, ack 101806, win 1444, options [nop,nop,TS val 2504551729 ecr 502070149], length 213
E..	..@.@.Q........... l.7}.]..L....T_.....
ServiceMethod.Health.ServiceNodes..AllowStale..Datacenter.biznet.MaxQueryTime..MinQueryIndex..NodeMetaFilters..RequireConsistent..ServiceName.consul.ServiceTag..Source..Datacenter..Node..TagFilter..Token

Can you please help me with the same because I am getting these errors in my consul agent logs although my prod isn't effected.

    2018/04/24 13:05:11 [ERR] consul: RPC failed to server 172.21.25.28:8300: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] dns: rpc error: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] consul: RPC failed to server 172.21.25.84:8300: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] dns: rpc error: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] consul: RPC failed to server 172.21.25.84:8300: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] dns: rpc error: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] consul: RPC failed to server 172.21.25.26:8300: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] dns: rpc error: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] consul: RPC failed to server 172.21.25.27:8300: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] dns: rpc error: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] consul: RPC failed to server 172.21.25.83:8300: rpc error: No path to datacenter
    2018/04/24 13:05:11 [ERR] dns: rpc error: rpc error: No path to datacenter

**Comment by memelet** [comment]
I am seeing the same behavior. What was the resolution that closed this issue?
