### ISSUE TITLE
can't set consul.serf_lan.memberlist in config file

### ISSUE THREAD

**Issue by weiwei04** [hashicorp/consul#4058]
### Description of the Issue (and unexpected/desired result)

below is my consul client config.json

```json
{
  "bootstrap": false,
  "datacenter": "dc1",
  "data_dir": "/data0/consul",
  "log_level": "INFO",
  "enable_syslog": true,
  "retry_join": [
"consul0", "consul1", "consul2"
  ],
  "consul": {
    "serf_lan": {
      "memberlist": {
        "probe_timeout": "600ms",
        "probe_interval": "2s"
      }
    }
  }
}
```

curl -v "http://127.0.0.1:8500/v1/agent/self" got

```json
...
    "ConsulSerfLANProbeInterval": "1s",
    "ConsulSerfLANProbeTimeout": "500ms",
...
```

seems the default config defined in

https://github.com/hashicorp/consul/blob/master/agent/config/default.go#L183

override the config.json

According to the comments in https://github.com/hashicorp/consul/blob/master/agent/config/builder.go#L35
```golang
// The sources are merged in the following order:
//
//  * default configuration
//  * config files in alphabetical order
//  * command line arguments```
```

seems the current NewBuilder impl was not correct, 
https://github.com/hashicorp/consul/blob/master/agent/config/builder.go#L112
```golang
	b.Head = append(b.Head, newSource("flags.slices", slices))
```

https://github.com/hashicorp/consul/blob/master/agent/config/builder.go#L128
```golang
       b.Tail = append(b.Tail, NonUserSource(), DefaultConsulSource(), DefaultEnterpriseSource(), DefaultVersionSource())
```

the b.Tail(DefaultConsulSource()) overrides the b.Sources(which was parsed from config file)

**Comment by pearkes** [comment]
This currently isn't possible at the user configuration layer. We are adding similar configuration values in an upcoming release, so it is possible these could be as well. I'm going to tag that here so we see it. However, if it isn't possible to simply plumb these through we'll likely close this as we don't believe this low-level configuration should be necessary in most networks.

cc/ @mkeeler

**Comment by mkeeler** [comment]
@weiwei04 The new configuration exists at the top level now like: (hcl syntax)

```
gossip_lan {
   probe_timeout = ...
   probe_interval = ...
}
gossip_wan {
   probe_timeout = ...
   probe_interval = ...
}
```
