### ISSUE TITLE
Consul Cluster issue

### ISSUE THREAD

**Issue by karthikrajakandasamy** [hashicorp/consul#4063]
I run the consul in my local machine. Using the comment 

consul agent -dev -bind=MyIpaddress1

Another machine also running consul, let say whose ip address is MyIpAddress2

I joined this two using the below comment from my machine

consul join "MyIpAddress2"

it is successfully registered. From UI am able to see, under Node two machine host name are there.  If i register any microservice from code in first machine consul, it is showing under the first machine Node whereas  it is not registering in second machine consul. I need to register in second machine also, which means if i register service in any machine consul,  that should be registered in both machine consul. Can anyone help me to resolve this? Thanks in advance.

**Comment by pearkes** [comment]
@karthikrajakandasamy services are registered per node, but should be available in the catalog for the whole Consul cluster. If you register the service against both nodes with the same ID you'll still just have one service. 

Try:

```consul catalog services```

And you'll see what I mean, I think! A good way to think about is that service registration is about declaring the availability of service on the node it is registered on.

**Comment by karthikrajakandasamy** [comment]
@pearkes Thanks for your answer. My question is, I have two consul server both are connected together using join command. 
Now i am registering Micro service "A"  with 1st consul server. micro service "A" details shown under  1st consul server in UI.
Whereas  micro service "A" details not shown under the 2nd consul server in the UI. 
So Replica is not happening in the Consul Cluster. Is any configuration need to setup for replica ?

**Comment by jhmartin** [comment]
@karthikrajakandasamy Can you show how you are registering the service, and the command you are using to query the service on both nodes?
