### ISSUE TITLE
Cannot delete ACL ID that contains "\n"

### ISSUE THREAD

**Issue by stevenscg** [hashicorp/consul#4069]
### Description of the Issue (and unexpected/desired result)

Follow-on to the Google group [discussion](https://groups.google.com/forum/#!topic/consul-tool/W769k0GHyV0).

We ended up with some ACL IDs (UUIDs) with a trailing newline character ("\n").

These ACLs cannot be deleted via the API.

We have tried the literal, escaping the slash, and urlencoding the ID.

Examples:
```
curl -v --header "X-Consul-Token: $CONSUL_HTTP_TOKEN" --request PUT http://$CONSUL_HTTP_ADDR/v1/acl/destroy/fd...487\n
curl -v --header "X-Consul-Token: $CONSUL_HTTP_TOKEN" --request PUT http://$CONSUL_HTTP_ADDR/v1/acl/destroy/fd...487%0A
```

The first returns HTTP 200, but does not actually remove the entry.

The second returns HTTP 400 and does not remove the entry.

### `consul version` for both Client and Server
Client: `Consul v1.0.7`
Server: `Consul v1.0.7`

**Comment by mkeeler** [comment]
@stevenscg Newlines in URIs are not allowed by default. If you add this to your server configurations it should allow you to delete them:

```
disable_http_unprintable_char_filter = true
```
