### ISSUE TITLE
Multiple Consul clusters can merge and overwrite each other's data

### ISSUE THREAD

**Issue by umairmufti** [hashicorp/consul#4074]
### Description of the Issue (and unexpected/desired result)
There appears to be a bug whereby multiple Consul clusters can merge into a larger cluster. After a leader election, some servers will have their KVDBs effectively wiped. 

This can occur even when the `acl_default_policy` is set to `deny` for each cluster and each cluster utilizes a unique `acl_master_token`.

### Reproduction steps
1. Start a cluster with 3 servers. Include the following configurations:
```
{
 "datacenter":"dc1",
 "acl_datacenter":"dc1",
 "acl_master_token":"cluster1",
 "acl_agent_token":"cluster1",
 "acl_default_policy":"deny"
}
```
2. Start a second cluster with 3 servers. Include the following configurations:
```
{
 "datacenter":"dc1",
 "acl_datacenter":"dc1",
 "acl_master_token":"cluster2",
 "acl_agent_token":"cluster2",
 "acl_default_policy":"deny"
}
```
3. Start an agent that connects to `cluster1`. No need to provide an ACL.
4. Restart the same agent, this time connecting to `cluster2`. No need to provide an ACL.
5. Gossip will allow all 6 server agents to discover each other to create a single, larger cluster. This can result in data loss.

### `consul version` for both Client and Server
Client: `1.0.1`
Server: `1.0.1`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 9564c29
	version = 1.0.1
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 43
	max_procs = 24
	os = linux
	version = go1.9.2
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 4
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 9564c29
	version = 1.0.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.172.75.40:8300
	server = true
raft:
	applied_index = 17
	commit_index = 17
	fsm_pending = 0
	last_contact = 0
	last_log_index = 17
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:595614dd-64a9-d710-c259-617153a7bcef Address:10.172.75.40:8300} {Suffrage:Voter ID:7637e75b-b7ff-07d0-3d88-c46877d57e4d Address:10.172.76.40:8300} {Suffrage:Voter ID:4cf6fce1-499f-80fc-0295-268aafd0bb98 Address:10.172.77.40:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 96
	max_procs = 24
	os = linux
	version = go1.9.2
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
RHEL7.4
Docker v1.13.1

**Comment by jhmartin** [comment]
This is expected behavior -- the two clusters are identified as being the same, so when the servers eventually become aware of each other they treat it as a split-brain recovery scenario and normalize, with one 'half' losing out. 

You can prevent this by configuring a gossip encryption key or using a different datacenter name for each cluster.

**Comment by umairmufti** [comment]
Thanks for the response. However, I'm not sure I understand why this is expected behavior. How are the two clusters identified as being the same? Whey would a rogue agent be able to cause data loss in a cluster without providing a token? That seems like a vulnerability, at the least.
 
Regarding the datacenter, that seems like a kludge. I prefer to use my datacenter names to reflect the actual datacenter of the cluster. In any case, wouldn't they just be joined as different datacenters within the same cluster, anyway?
 
Will take a look at the gossip encryption. Thanks for pointing that out.

**Comment by shantanugadgil** [comment]
I think if you have an encryption key set, which is different for separate clusters, then such cross pollination should get prevented.

The only way to join an existing cluster would be to know the encryption key.

**Comment by pearkes** [comment]
@shantanugadgil is correct here. If multiple clusters exist and are reachable in the same network, they will potentially join each other (using authentication other than ACLs, which is confusing). As concluded enabling encryption with unique keys will avoid this issue.
