### ISSUE TITLE
JSON case-sensitivity/specification

### ISSUE THREAD

**Issue by deviant-logic** [hashicorp/consul#408]
Best I can tell, the JSON values produced by the HTTP API are specified by example in this doc: http://www.consul.io/docs/agent/http.html.  It would be helpful to have a more precise schema for these messages.  In particular, it would be helpful to explicitly declare the case-(in)sensitivity of the keys in these messages.

**Comment by sethvargo** [comment]
Hi there,

The new HTTP API docs have example requests and responses now. The fields correspond directly to the fields in the configurations (which are also documented in the new http api docs).
