### ISSUE TITLE
Docs: add examples for common go-sockaddr configs when "Multiple private IPv4 addresses found"

### ISSUE THREAD

**Issue by OPSTime** [hashicorp/consul#4090]
**c1 configuration:**

> {
>   "datacenter": "dc1",
>   "data_dir": "/data/consul",
>   "log_level": "DEBUG",
>   "node_name": "c1",
>   "server": true,
>   "bind_addr": "0.0.0.0",
>   "client_addr": "0.0.0.0",
>   "bootstrap_expect":2,
>   "retry_join": [ "192.168.1.11","192.168.1.12","192.168.1.13" ],
>   "rejoin_after_leave": true,
>   "retry_interval": "5s",
>   "enable_debug": false,
>   "enable_syslog": true,
>   "syslog_facility": "local5",
> 
>   "ui":false,
>   "telemetry": {
>      "statsite_address": "127.0.0.1:2180"
>   },
> 
>   "disable_remote_exec": true,
>   "encrypt": "we7GdJPNHgpBVYS61QYVPg==",
>   "encrypt_verify_incoming": true,
>   "encrypt_verify_outgoing": true,
> 
>   "acl_datacenter": "dc1",
>   "acl_master_token": "d30f6835-535c-40ab-bce9-e14e8f4a8098",
>   "acl_down_policy": "extend-cache",
>   "acl_default_policy": "deny",
> 
>   "acl_agent_token": "42b5137b-c22f-d7a3-f94c-ef59524e6670"
> }

**c2 configuration:**
> {
>   "datacenter": "dc1",
>   "data_dir": "/data/consul",
>   "log_level": "DEBUG",
>   "node_name": "c2",
>   "server": true,
>   "bind_addr": "0.0.0.0",
>   "client_addr": "0.0.0.0",
>   "bootstrap_expect":2,
>   "retry_join": [ "192.168.1.11","192.168.1.12","192.168.1.13" ],
>   "rejoin_after_leave": true,
>   "retry_interval": "5s",
>   "enable_debug": false,
>   "enable_syslog": true,
>   "syslog_facility": "local5",
> 
>   "ui":false,
>   "telemetry": {
>      "statsite_address": "127.0.0.1:2180"
>   },
> 
>   "disable_remote_exec": true,
>   "encrypt": "we7GdJPNHgpBVYS61QYVPg==",
>   "encrypt_verify_incoming": true,
>   "encrypt_verify_outgoing": true,
> 
>   "acl_datacenter": "dc1",
>   "acl_master_token": "d30f6835-535c-40ab-bce9-e14e8f4a8098",
>   "acl_down_policy": "extend-cache",
>   "acl_default_policy": "deny",
> 
>   "acl_agent_token": "42b5137b-c22f-d7a3-f94c-ef59524e6670"
> }

**c3 configuration:**
> {
>   "datacenter": "dc1",
>   "data_dir": "/data/consul",
>   "log_level": "DEBUG",
>   "node_name": "c3",
>   "server": true,
>   "bind_addr": "0.0.0.0",
>   "client_addr": "0.0.0.0",
>   "bootstrap_expect":2,
>   "retry_join": [ "192.168.1.11","192.168.1.12","192.168.1.13" ],
>   "rejoin_after_leave": true,
>   "retry_interval": "5s",
>   "enable_debug": false,
>   "enable_syslog": true,
>   "syslog_facility": "local5",
> 
>   "ui":false,
>   "telemetry": {
>      "statsite_address": "127.0.0.1:2180"
>   },
> 
>   "disable_remote_exec": true,
>   "encrypt": "we7GdJPNHgpBVYS61QYVPg==",
>   "encrypt_verify_incoming": true,
>   "encrypt_verify_outgoing": true,
> 
>   "acl_datacenter": "dc1",
>   "acl_master_token": "d30f6835-535c-40ab-bce9-e14e8f4a8098",
>   "acl_down_policy": "extend-cache",
>   "acl_default_policy": "deny",
> 
>   "acl_agent_token": "42b5137b-c22f-d7a3-f94c-ef59524e6670"
> }
> 

**start node：**

> start c1: success
> start c2: success
> start c3: failed

**c3 log:**

> -- Logs begin at Tue 2018-03-27 02:40:01 CST, end at Mon 2018-05-07 21:06:26 CST. --
> May 07 21:04:54 c3 systemd[1]: Starting Consul service discovery agent...
> May 07 21:04:54 c3 systemd[1]: consul.service: control process exited, code=exited status=1
> May 07 21:04:54 c3 systemd[1]: Failed to start Consul service discovery agent.
> May 07 21:04:54 c3 systemd[1]: Unit consul.service entered failed state.
> May 07 21:04:54 c3 systemd[1]: consul.service failed.
> May 07 21:04:54 c3 systemd[1]: consul.service holdoff time over, scheduling restart.
> May 07 21:04:54 c3 systemd[1]: Starting Consul service discovery agent...
> May 07 21:04:54 c3 consul[1191]: Config validation failed: Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'.
> May 07 21:04:54 c3 systemd[1]: consul.service: control process exited, code=exited status=1
> May 07 21:04:54 c3 systemd[1]: Failed to start Consul service discovery agent.
> May 07 21:04:54 c3 systemd[1]: Unit consul.service entered failed state.
> May 07 21:04:54 c3 systemd[1]: consul.service failed.
> May 07 21:04:54 c3 systemd[1]: consul.service holdoff time over, scheduling restart.
> May 07 21:04:54 c3 systemd[1]: Starting Consul service discovery agent...
> May 07 21:04:54 c3 systemd[1]: consul.service: control process exited, code=exited status=1
> May 07 21:04:54 c3 systemd[1]: Failed to start Consul service discovery agent.
> May 07 21:04:54 c3 systemd[1]: Unit consul.service entered failed state.
> May 07 21:04:54 c3 systemd[1]: consul.service failed.
> May 07 21:04:54 c3 systemd[1]: consul.service holdoff time over, scheduling restart.
> May 07 21:04:54 c3 systemd[1]: Starting Consul service discovery agent...
> May 07 21:04:54 c3 systemd[1]: consul.service: control process exited, code=exited status=1
> May 07 21:04:54 c3 systemd[1]: Failed to start Consul service discovery agent.
> May 07 21:04:54 c3 systemd[1]: Unit consul.service entered failed state.
> May 07 21:04:54 c3 systemd[1]: consul.service failed.
> May 07 21:04:54 c3 systemd[1]: consul.service holdoff time over, scheduling restart.

**Comment by pearkes** [comment]
If you have multiple addresses, you'll need to choose a specific one for Consul to bind and advertise on. You can use go-sockaddr support to do this dynamically when you don't want to write the actual IP into the configuration file.

In your case I'd recommend this:

```
"bind_addr": "{{ GetInterfaceIP \"eth0\" }}"",
```

Where `eth0` is the interface you wish to bind to. This isn't clearly an option in our docs that I can see ([this section](https://www.consul.io/docs/agent/options.html#_bind)) so I definitely think that could be improved. Going to tag this issue as such.

I also noticed you are binding the client to `0.0.0.0` -- this is typically on loopback, the most common scenario, so you may want to review [those docs](https://www.consul.io/docs/agent/options.html#_client).

**Comment by sean-** [comment]
Or `{{ GetPrivateIP }}` to use an internal heuristic that likely picks the correct address (no guarantees).  You can test this out in advance using the CLI:

1. `go get -u github.com/hashicorp/go-sockaddr/cmd/sockaddr`
2. `sockaddr eval GetPrivateIP`

https://github.com/hashicorp/go-sockaddr/blob/acd314c5781ea706c710d9ea70069fd2e110d61d/README.md#sockaddr-library

Writing docs for this would be an ace contribution.

**Comment by patrick-nw** [comment]
Seeing this error during validation attempts in my Consul class. Just wanted to add a +1 to the issue...

**Comment by banks** [comment]
@patrick-nw thanks for the feedback. In general 👍 responses on the original issue are more useful than comments to point out it affects you to as it disrupts the flow of conversation less and make sit easier for us to see a count of people impacted. Of course if you have additional relevant info a comment is always welcome!

Also wanted to check that you are aware that this is not a _bug_ this is working as it's meant to so your validation error is expected and will not be "fixed" by any change here. The only reason this is still open is to potentially consider if we can document the common patterns posted by Jack and Sean above.

**Comment by orarnon** [comment]
Hi @sean- , I'm unable to install:
`# github.com/posener/complete/cmd/install
go/src/github.com/posener/complete/cmd/install/install.go:102: undefined: os.Executable
# github.com/hashicorp/go-sockaddr
go/src/github.com/hashicorp/go-sockaddr/ifaddrs.go:140: undefined: strings.Compare
go/src/github.com/hashicorp/go-sockaddr/ifaddrs.go:181: undefined: strings.Compare
go/src/github.com/hashicorp/go-sockaddr/ifaddrs.go:728: signRE.Copy undefined (type *regexp.Regexp has no field or method Copy)
go/src/github.com/hashicorp/go-sockaddr/ifaddrs.go:1201: whitespaceRE.Copy undefined (type *regexp.Regexp has no field or method Copy)
go/src/github.com/hashicorp/go-sockaddr/ifaddrs.go:1244: whitespaceRE.Copy undefined (type *regexp.Regexp has no field or method Copy)
go/src/github.com/hashicorp/go-sockaddr/ifaddrs.go:1264: ifNameRE.Copy undefined (type *regexp.Regexp has no field or method Copy)
go/src/github.com/hashicorp/go-sockaddr/ifaddrs.go:1265: ipAddrRE.Copy undefined (type *regexp.Regexp has no field or method Copy)
go/src/github.com/hashicorp/go-sockaddr/route_info_solaris.go:12: routeInfo redeclared in this block
	previous declaration at go/src/github.com/hashicorp/go-sockaddr/route_info_linux.go:8
go/src/github.com/hashicorp/go-sockaddr/route_info_solaris.go:18: NewRouteInfo redeclared in this block
	previous declaration at go/src/github.com/hashicorp/go-sockaddr/route_info_linux.go:14
go/src/github.com/hashicorp/go-sockaddr/route_info_solaris.go:26: routeInfo.GetDefaultInterfaceName redeclared in this block
	previous declaration at go/src/github.com/hashicorp/go-sockaddr/route_info_linux.go:29
go/src/github.com/hashicorp/go-sockaddr/ifaddrs.go:1265: too many errors`

**Comment by pearkes** [comment]
I think we're still leaving this open to improve the examples for go-sockaddr in our docs. Removing the question label.

**Comment by bflad** [comment]
Submitted pull request 😄 #5701
