### ISSUE TITLE
watches was loaded many times

### ISSUE THREAD

**Issue by lyddragon** [hashicorp/consul#4093]
**watches configuration：**

>   "watches": [
>     {
>       "type": "key",
>       "key": "bench",
>       "token": "d30f6835-535c-40ab-bce9-e14e8f4a8077",
>       "handler_type": "script",
>       "args": ["/data/shell/t.sh"]
>     }
>   ]

**/data/shell/t.sh**

> #!/bin/bash
> echo 1 >>/tmp/out.log

**consul.service**

> [Unit]
> Description=Consul service discovery agent
> Requires=network-online.target
> After=network-online.target
> 
> [Service]
> Type=simple
> User=consul
> Group=consul
> Restart=on-failure
> Environment=GOMAXPROCS=8
> ExecStartPre=/usr/local/consul/bin/consul validate -quiet /usr/local/consul/etc/
> ExecStart=/usr/local/consul/bin/consul agent -config-dir=/usr/local/consul/etc/
> ExecReload=/bin/kill -HUP $MAINPID
> KillSignal=SIGTERM
> TimeoutStopSec=5
> 
> [Install]
> WantedBy=multi-user.target

**run command**

> systemctl reload consul
> systemctl reload consul

**change key:  bench value**

**cat /tmp/out.log**

> 1
> 1

**Comment by pearkes** [comment]
I believe you are asking about the behavior of watches during reload -- are seeing the issue described here: #571?

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again. I still believe this is a duplicate of #571.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
