### ISSUE TITLE
add keyprefix watch option to return only changed keys

### ISSUE THREAD

**Issue by piavlo** [hashicorp/consul#410]
currently keyprefix watch returns all keys under a keyprefix then one of the keys changes
returning only the changed keys.
Afaiu first it needs to be implemented at http kv blocking ?recurse GET method level returning only modified keys. Is this doable?

tnx

**Comment by ctheune** [comment]
I'd like to ask for a small favor (happy to make a pull request).

Can we clarify this in the docs a bit more? I had to dig around the code to find out whether this was intentional or accidental. And I think https://www.consul.io/docs/agent/watches.html could be more explicit about this.

**Comment by armon** [comment]
@ctheune Please send a PR! Happy to review and merge

**Comment by ctheune** [comment]
Alright. Sorry this took so long (I got distracted and needed some quiet time to get the docs going - luckily Github shows a rendered version, I was fighting against bundler with Ruby 2.2 to get the docs to compile locally) ...
