### ISSUE TITLE
Question - when a consul member is non gracefully shutdown

### ISSUE THREAD

**Issue by jamesmcminn96** [hashicorp/consul#4101]
When a machine running the consul agent is shutdown (hardware failure, operator error, etc) and it doesn't have the option to gracefully leave the cluster with a `consul leave`. How would the cluster ever become aware that all services running on that node are now unhealthy? As the application healthchecks run locally, the agent would never get the opportunity to report failure of a service.

What are some recommended steps to dealing with this kind of outage? As far as I'm aware application level TTL healthchecks are only monitored by the local agent.

Thanks in advance!

**Comment by jhmartin** [comment]
Consul agents all healthcheck each other, hence the requirement to open several udp and tcp ports between all nodes.  A remote agent will detect that Consul is gone shortly after it goes offline and gossip this observation to the other nodes. The services on the node will be marked offline at this point.

**Comment by jamesmcminn96** [comment]
Thanks @jhmartin - is there any indication of how long on average it would take for a failure of this nature to be detected? And is that time taken dependent on the number of members?

**Comment by seafoodbuffet** [comment]
In my experience, this has been a few seconds max in my environment (3 servers and 60ish client agents)

**Comment by jamesmcminn96** [comment]
Thanks @seafoodbuffet & @jhmartin
