### ISSUE TITLE
Consul 1.1.0 UI doesnt Load

### ISSUE THREAD

**Issue by Nivedan3112** [hashicorp/consul#4112]
HEllo Folks ,

We already have consul setup in our organization . I observerd there has been a new ui update for consul and we wanted to check the new ui. To start of i downloaded consul for windows in my local (1.1.0) and did a consul agent -dev the ui doesnt load ?? Any info

**Comment by pearkes** [comment]
@Nivedan3112 I can't reproduce this on other platforms, so it may be a windows issue. Can you run `consul info` and post the output of that while Consul is running?

If you're trying to use the new UI, you have to opt-in like this:

```
$ CONSUL_UI_BETA=1 consul agent -dev
...
$ curl http://localhost:8500
<a href="/ui/">Moved Permanently</a>.
```

If that variable is not set, it should load the old UI.

**Comment by pearkes** [comment]
@Nivedan3112 After setting a system variable I'm able to load both the old and new UIs in Windows with 1.1.0. If you're not seeing the new one, I'd be sure the variable is set correctly.

![pasted image at 2018_05_11 03_23 pm](https://user-images.githubusercontent.com/846194/39949419-90181290-552f-11e8-9de1-6a158f589672.png)
![image 6](https://user-images.githubusercontent.com/846194/39949450-b771ea1e-552f-11e8-8d6b-79ffc012def1.png)

**Comment by Nivedan3112** [comment]
Hello , can you also share me what system variable you have set , and also how did you start the consul in windows

**Comment by Nivedan3112** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/30735786/39973019-08f7e82c-56d7-11e8-8f0a-20b11e8baf96.png">

**Comment by ChipV223** [comment]
Hi @Nivedan3112!

You would need to set the `CONSUL_UI_BETA` environmental variable in the Windows Environment Variables section to either the value true or 1. Once you done that and start a new cmd prompt window to create a new Consul agent, you should be able to access the beta Consul UI

**Comment by wzlee** [comment]
@ChipV223 But how to run consul with brew services start consol with this params?
Ps: Consul installed by brew.

**Comment by ChipV223** [comment]
@wzlee: I'm not too familiar with brew since I'm a primary Windows user, but the first step of this is to set the `CONSUL_UI_BETA` env variable on your Mach machine to either `true` or `1`. From there, you would just need to start up Consul with the `-ui` flag to enable the Consul Beta UI
