### ISSUE TITLE
ACL token dropdown buttons are hidden near footer

### ISSUE THREAD

**Issue by scalp42** [hashicorp/consul#4125]
Hi folks,

Using the new UI, some dropdown buttons (at least the `delete` one) are hidden by the footer.

Chrome `v65.0.3325.181`, see screenshot:

<img width="1225" alt="screen shot 2018-05-14 at 2 24 01 pm" src="https://user-images.githubusercontent.com/1475276/40024322-c4286454-5782-11e8-87a1-e0e8e24dc483.png">

Appears to be more difficult on Safari `v11.1` to scroll the page for the tokens (struggling to get to the bottom of the list):

<img width="1223" alt="screen shot 2018-05-14 at 2 27 58 pm" src="https://user-images.githubusercontent.com/1475276/40024420-11daa446-5783-11e8-8cdc-5e6135fc2b08.png">

Thanks ✌️

**Comment by johncowen** [comment]
HI @scalp42 ,

Just checking in with you to see if you've been able to try out the updated UI in 1.2.0. We added a fix for your above issue, so the above should be resolved now. If so feel free to close this issue, or I'll close it in a few days if I don't hear anything back from you.

If its not resolved, please let me know and we can re-look.

Thanks 👍

**Comment by scalp42** [comment]
I haven't had a chance to roll out an update to 1.2.0 yet. Feel free to close if the issue is fixed, I'm hoping I can upgrade tomorrow.
