### ISSUE TITLE
Setup Consul Cluster on a single Server

### ISSUE THREAD

**Issue by Heurazio** [hashicorp/consul#4128]
Sorry if this is the wrong place to ask this question but I didn't find anything related to my problem.

I like to set up a Cluster (3 Servers and 1 Agent - for the Web UI) on a single physical server (Windows Server 2016).

The first Consul Server is starting as expected but when I start the second server I get a:

`Error starting agent: Failed to start Consul server: Failed to start RPC layer: listen tcp 0.0.0.0:8300: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.`

This is my `config.json` that I use for the server startup.

```
{
    "bootstrap_expect": 3,
    "server": true,
    "datacenter": "dc1",
    "data_dir": "D:\\Consul\\consul\\data",
    "encrypt": "DummyKey==",
    "log_level": "INFO",
    "retry_join": ["127.0.0.1"]
}
```

I'm not sure how to configure the second (and third) server to use "other ports" and how to link the three servers together. 

What's the correct configuration for three `Consul Server Agents` on one single physical server (with only one IP-Address)? What are the correct port mappings and `retry_join` settings for this use case? How do I link the additional WebUI Agent to the cluster?

**Comment by Heurazio** [comment]
Thanks for your answer.

The main reason why I want to setup clustering is, that it's advised to have 3-5 Servers running. But if this is not necessary for a single physical server I can just "skip" this till more servers are in the network.

**Comment by seafoodbuffet** [comment]
So yes, very much so. I wouldn't bother running more than one server unless:
a) redundancy and failure tolerance is an immediate requirement
b) you need lots of servers to deal with a large network of agents
