### ISSUE TITLE
some characters now URL encoded in WebUi

### ISSUE THREAD

**Issue by jamessoubry** [hashicorp/consul#4132]
#### Overview of the Issue

When using the webui characters are now being url encoded in current versions (v1.0.7). this doesn't affect the workings of consul but its ugly and can be confusing to users.

This was not an issue in older versions (specifically v0.8.2).

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create folder called "test-folder,dev" via the webui, cli or api
1. inspect the folder in webui. it will be called "test-folder%2Cdev" the browser url will have "%2C" in it too.
1. manually change the browser url to ",".  left pane will display "%2C", right pane will display ","
1. the same happens for keys

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = fb848fc4
	version = 1.0.7
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.10.102.57:8300
	server = true
raft:
	applied_index = 824925
	commit_index = 824925
	fsm_pending = 0
	last_contact = 34.013832ms
	last_log_index = 824925
	last_log_term = 32
	last_snapshot_index = 819407
	last_snapshot_term = 32
	latest_configuration = [{Suffrage:Voter ID:1d3bb1b9-f04e-532d-f453-da7eb26b548c Address:10.10.102.57:8300} {Suffrage:Voter ID:1c585c4c-ece2-8b3c-af43-460b7c54a4da Address:10.10.100.49:8300} {Suffrage:Voter ID:39058208-6fa7-d91f-2550-0a63ea13979c Address:10.10.101.235:8300}]
	latest_configuration_index = 751060
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 32
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 124
	max_procs = 1
	os = linux
	version = go1.10
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 21
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 79
	members = 6
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 29
	members = 3
	query_queue = 0
	query_time = 1

</details>

<details>
  <summary>Server info</summary>

{"Config":{"Datacenter":"eu-west-1","NodeName":"ip-10-10-100-49","NodeID":"1c585c4c-ece2-8b3c-af43-460b7c54a4da","Revision":"fb848fc48","Server":true,"Version":"1.0.7"},"DebugConfig":{"ACLAgentMasterToken":"hidden","ACLAgentToken":"hidden","ACLDatacenter":"eu-west-1","ACLDefaultPolicy":"deny","ACLDisabledTTL":"2m0s","ACLDownPolicy":"extend-cache","ACLEnableKeyListPolicy":false,"ACLEnforceVersion8":true,"ACLMasterToken":"hidden","ACLReplicationToken":"hidden","ACLTTL":"30s","ACLToken":"hidden","AEInterval":"1m0s","AdvertiseAddrLAN":"10.10.100.49","AdvertiseAddrWAN":"10.10.100.49","AutopilotCleanupDeadServers":true,"AutopilotDisableUpgradeMigration":false,"AutopilotLastContactThreshold":"200ms","AutopilotMaxTrailingLogs":250,"AutopilotRedundancyZoneTag":"","AutopilotServerStabilizationTime":"10s","AutopilotUpgradeVersionTag":"","BindAddr":"10.10.100.49","Bootstrap":false,"BootstrapExpect":3,"CAFile":"","CAPath":"","CertFile":"","CheckDeregisterIntervalMin":"1m0s","CheckReapInterval":"30s","CheckUpdateInterval":"5m0s","Checks":[],"ClientAddrs":["10.10.100.49"],"ConsulCoordinateUpdateBatchSize":128,"ConsulCoordinateUpdateMaxBatches":5,"ConsulCoordinateUpdatePeriod":"5s","ConsulRaftElectionTimeout":"1s","ConsulRaftHeartbeatTimeout":"1s","ConsulRaftLeaderLeaseTimeout":"500ms","ConsulSerfLANGossipInterval":"200ms","ConsulSerfLANProbeInterval":"1s","ConsulSerfLANProbeTimeout":"500ms","ConsulSerfLANSuspicionMult":4,"ConsulSerfWANGossipInterval":"500ms","ConsulSerfWANProbeInterval":"5s","ConsulSerfWANProbeTimeout":"3s","ConsulSerfWANSuspicionMult":6,"ConsulServerHealthInterval":"2s","DNSARecordLimit":0,"DNSAddrs":["tcp://10.10.100.49:8600","udp://10.10.100.49:8600"],"DNSAllowStale":true,"DNSDisableCompression":false,"DNSDomain":"consul.","DNSEnableTruncate":false,"DNSMaxStale":"87600h0m0s","DNSNodeTTL":"0s","DNSOnlyPassing":false,"DNSPort":8600,"DNSRecursorTimeout":"2s","DNSRecursors":[],"DNSServiceTTL":{},"DNSUDPAnswerLimit":3,"DataDir":"/consul/data","Datacenter":"eu-west-1","DevMode":false,"DisableAnonymousSignature":false,"DisableCoordinates":false,"DisableHostNodeID":true,"DisableKeyringFile":false,"DisableRemoteExec":true,"DisableUpdateCheck":false,"DiscardCheckOutput":true,"DiscoveryMaxStale":"0s","EnableACLReplication":false,"EnableAgentTLSForChecks":false,"EnableDebug":false,"EnableScriptChecks":false,"EnableSyslog":false,"EnableUI":true,"EncryptKey":"hidden","EncryptVerifyIncoming":true,"EncryptVerifyOutgoing":true,"HTTPAddrs":["tcp://10.10.100.49:8500"],"HTTPBlockEndpoints":[],"HTTPPort":8500,"HTTPResponseHeaders":{},"HTTPSAddrs":[],"HTTPSPort":-1,"KeyFile":"hidden","LeaveDrainTime":"5s","LeaveOnTerm":true,"LogLevel":"INFO","NodeID":"1c585c4c-ece2-8b3c-af43-460b7c54a4da","NodeMeta":{},"NodeName":"ip-10-10-100-49","NonVotingServer":false,"PidFile":"","RPCAdvertiseAddr":"tcp://10.10.100.49:8300","RPCBindAddr":"tcp://10.10.100.49:8300","RPCHoldTimeout":"7s","RPCMaxBurst":1000,"RPCProtocol":2,"RPCRateLimit":-1,"RaftProtocol":0,"ReconnectTimeoutLAN":"0s","ReconnectTimeoutWAN":"0s","RejoinAfterLeave":false,"RetryJoinIntervalLAN":"30s","RetryJoinIntervalWAN":"30s","RetryJoinLAN":["provider=aws tag_key=hidden tag_value=ecosystems-mgmt-EcsAutoScalingGroup-D3F4PLJ905UG"],"RetryJoinMaxAttemptsLAN":0,"RetryJoinMaxAttemptsWAN":0,"RetryJoinWAN":[],"Revision":"fb848fc48","SegmentLimit":64,"SegmentName":"","SegmentNameLimit":64,"Segments":[],"SerfAdvertiseAddrLAN":"tcp://10.10.100.49:8301","SerfAdvertiseAddrWAN":"tcp://10.10.100.49:8302","SerfBindAddrLAN":"tcp://10.10.100.49:8301","SerfBindAddrWAN":"tcp://10.10.100.49:8302","SerfPortLAN":8301,"SerfPortWAN":8302,"ServerMode":true,"ServerName":"","ServerPort":8300,"Services":[],"SessionTTLMin":"0s","SkipLeaveOnInt":true,"StartJoinAddrsLAN":[],"StartJoinAddrsWAN":[],"SyncCoordinateIntervalMin":"15s","SyncCoordinateRateTarget":64,"SyslogFacility":"LOCAL0","TLSCipherSuites":[],"TLSMinVersion":"tls10","TLSPreferServerCipherSuites":false,"TaggedAddresses":{"lan":"10.10.100.49","wan":"10.10.100.49"},"TelemetryAllowedPrefixes":[],"TelemetryBlockedPrefixes":["consul.consul"],"TelemetryCirconusAPIApp":"","TelemetryCirconusAPIToken":"hidden","TelemetryCirconusAPIURL":"","TelemetryCirconusBrokerID":"","TelemetryCirconusBrokerSelectTag":"","TelemetryCirconusCheckDisplayName":"","TelemetryCirconusCheckForceMetricActivation":"","TelemetryCirconusCheckID":"","TelemetryCirconusCheckInstanceID":"","TelemetryCirconusCheckSearchTag":"","TelemetryCirconusCheckTags":"","TelemetryCirconusSubmissionInterval":"","TelemetryCirconusSubmissionURL":"","TelemetryDisableHostname":false,"TelemetryDogstatsdAddr":"","TelemetryDogstatsdTags":[],"TelemetryFilterDefault":true,"TelemetryMetricsPrefix":"consul","TelemetryStatsdAddr":"","TelemetryStatsiteAddr":"","TranslateWANAddrs":false,"UIDir":"","UnixSocketGroup":"","UnixSocketMode":"","UnixSocketUser":"","VerifyIncoming":false,"VerifyIncomingHTTPS":false,"VerifyIncomingRPC":false,"VerifyOutgoing":false,"VerifyServerHostname":false,"Version":"1.0.7","VersionPrerelease":"","Watches":[]},"Coord":{"Vec":[-0.003555229454099929,-0.026253169367918213,-0.0036845706397469844,0.013877259150364897,0.013190613162439123,-0.002207940541885754,-0.0038779471604471634,-0.02248585219169883],"Error":0.04483211850502736,"Adjustment":0.0002584626059010799,"Height":0.00012894300271877547},"Member":{"Name":"ip-10-10-100-49","Addr":"10.10.100.49","Port":8301,"Tags":{"build":"1.0.7:fb848fc4","dc":"eu-west-1","expect":"3","id":"1c585c4c-ece2-8b3c-af43-460b7c54a4da","port":"8300","raft_vsn":"3","role":"consul","segment":"","vsn":"2","vsn_max":"3","vsn_min":"2","wan_join_port":"8302"},"Status":1,"ProtocolMin":1,"ProtocolMax":5,"ProtocolCur":2,"DelegateMin":2,"DelegateMax":5,"DelegateCur":4},"Stats":{"agent":{"check_monitors":"0","check_ttls":"0","checks":"0","services":"0"},"build":{"prerelease":"","revision":"fb848fc4","version":"1.0.7"},"consul":{"bootstrap":"false","known_datacenters":"1","leader":"false","leader_addr":"10.10.102.57:8300","server":"true"},"raft":{"applied_index":"824967","commit_index":"824967","fsm_pending":"0","last_contact":"2.26838ms","last_log_index":"824967","last_log_term":"32","last_snapshot_index":"819405","last_snapshot_term":"32","latest_configuration":"[{Suffrage:Voter ID:1d3bb1b9-f04e-532d-f453-da7eb26b548c Address:10.10.102.57:8300} {Suffrage:Voter ID:1c585c4c-ece2-8b3c-af43-460b7c54a4da Address:10.10.100.49:8300} {Suffrage:Voter ID:39058208-6fa7-d91f-2550-0a63ea13979c Address:10.10.101.235:8300}]","latest_configuration_index":"751060","num_peers":"2","protocol_version":"3","protocol_version_max":"3","protocol_version_min":"0","snapshot_version_max":"1","snapshot_version_min":"0","state":"Follower","term":"32"},"runtime":{"arch":"amd64","cpu_count":"1","goroutines":"131","max_procs":"1","os":"linux","version":"go1.10"},"serf_lan":{"coordinate_resets":"0","encrypted":"false","event_queue":"0","event_time":"21","failed":"0","health_score":"0","intent_queue":"0","left":"0","member_time":"79","members":"6","query_queue":"0","query_time":"1"},"serf_wan":{"coordinate_resets":"0","encrypted":"false","event_queue":"0","event_time":"1","failed":"0","health_score":"0","intent_queue":"0","left":"0","member_time":"29","members":"3","query_queue":"0","query_time":"1"}},"Meta":{"consul-network-segment":""}}

</details>

### Operating system and Environment details

same on different infrastructures:

docker ECS AMI Linux 

marathon mesos ubuntu

### Log Fragments

not sure you need this

**Comment by johncowen** [comment]
HI @jamessoubry , thanks for helping us out with this!

I'm not sure if you are aware, but we are currently working on a new UI for consul, it's currently in beta but we are asking people if they would be willing to give it a try in non-production environments. There are instructions on how to try it out here:

https://www.consul.io/intro/getting-started/ui.html

Could you let me know if the new beta UI solves your issue. If not we can certainly look at this further.

Thanks

**Comment by johncowen** [comment]
Hi @jamessoubry , I'm going to close this issue for the moment, please let me know if you would like us to look at anything else regarding this and we can reopen.

Thanks
