### ISSUE TITLE
Multi line values are not supported by the new web-ui

### ISSUE THREAD

**Issue by dbro86** [hashicorp/consul#4138]
With the **old** web-ui there is it possible to fill a key with a multi line value.
But with the **new** web-ui there is it not possible to enter a line feed (return) into the value field.

Furthermore the new web-ui shows an existing multi line value as an oneliner.
All line feeds aren't visible anymore.

Kind regards

**Comment by johncowen** [comment]
Hi @dbro86 

We added a fix for this in the 1.2.0 version of the UI. Let me know if this has resolved your issue, and if so feel free to close, or I'll close over the next few days.

If its not resolved, please let me know and we can re-look.

Thanks,
