### ISSUE TITLE
Auditing + ACL entries

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#414]
Enable some form of auditing with ACLs

**Comment by blewa** [comment]
+1.  This is a very compelling feature for many larger shops.

**Comment by njsaunders** [comment]
+1

**Comment by houtmanj** [comment]
Just including identifying information in an event would already be an huge step that would allow watches to act on the information.

**Comment by TMaster** [comment]
+1

**Comment by fromonesrc** [comment]
@armon has consul auditing been put on the roadmap? We have a requirement for this and looking into options.

**Comment by sethvargo** [comment]
Hi all,

This is something that's on our internal roadmap. We have some really good ideas about it, but we will open an issue for discussion once we've flushed it out internally a bit more. Thanks!

**Comment by redmoses** [comment]
@sethvargo is there any update about this feature request? Did you guys open any other issue for this?

**Comment by redmoses** [comment]
Thanks for responding though. I’ll create a new one. Cheers!

**Comment by blake** [comment]
We just announced the beta release of Consul 1.8 which includes support for Audit Logging in Consul Enterprise.

See the announcement blog for more details (https://www.hashicorp.com/blog/announcing-hashicorp-consul-1-8/).
