### ISSUE TITLE
Enable the `pprof` endpoints by default

### ISSUE THREAD

**Issue by guidoiaquinti** [hashicorp/consul#4147]
#### Feature Description
Enable the `pprof` endpoints by default

Right now we need to run the agent with the `enable_debug` set to true to have them registered:

https://github.com/hashicorp/consul/blob/863ac12811c4673d6b4930b03b31344655e5abf7/agent/http.go#L143-L148

My proposal is to move them out of the `if` and keep the `enable_debug` flag for future functionalities. 

#### Use Case(s)
I think there's value to enable the endpoints by default, especially as there isn't any noticeable performance overhead till they are actively used.

**Comment by eugenepaniot** [comment]
Enabling debug by default may have unexpected security impact, as it allow to dump memory heap.

**Comment by guidoiaquinti** [comment]
Fair point, thank you for your feedback @eugenepaniot and @banks 🙇
