### ISSUE TITLE
Allow the http check to post a specified body

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/consul#4148]
#### Feature Description

As far as I can tell currently there is no way to send a payload via the http check. You can specify `headers` but not `body`.

#### Use Case(s)

Some JSON-RPC interfaces require posting JSON to the endpoint to call a method.

**Comment by mkeeler** [comment]
@jakubgs You may want to check out the discussion on [this PR](https://github.com/hashicorp/consul/pull/3992) as I think that is basically what you are asking for. 

With that in mind could you elaborate on your use case a little more and in particular speak a little to the last comment @preetapan left with regards to why a GET request wouldn't be suitable and to whether you are trying to modify application state with the health check.
