### ISSUE TITLE
SSL on Consul in windows machine not working

### ISSUE THREAD

**Issue by karthikrajakandasamy** [hashicorp/consul#4149]
In my windows machine i have to use consul SSL, which means the consul UI Should run with https. For that i followed the below steps, but it is not working perfectly. Can any one suggest me the solution

1. Created the key using below command
**openssl genrsa -out consul.key 4096**

2. Created certificate consul_ca.crt using below command
**openssl req -new -x509 -days 365 -key consul.key -subj '/C=US/ST=Somestate/L=sometown/O=somecompany/OU=someorg/CN=someguy' -out consul_ca.crt**

3. Created CSR using below command
**openssl req -new -key consul.key -out consul.csr -subj '/C=US/ST=Somestate/L=sometown/O=somecompany/OU=someorg/CN=*'**

4. Created consul.crt file using the below command
**openssl x509 -extfile openssl.conf -extensions ssl_client -req -days 365 -in consul.csr -CA consul_ca.crt -CAkey consul.key -out consul.crt -set_serial 01**

5. After i created the above certificates, i used the below Configuration in my config file

"verify_incoming": true,
"verify_outgoing": true,
"cert_file": "/opt/consul/conf.d/consul.crt",
"key_file": "/opt/consul/conf.d/consul.key"
"ca_file": "Certificate/consul_ca.crt",

Then i started my Consul with the above configuration.
My consul started and running but when i tried to access the consul UI using https the page is not loading.
Could any please provide me any solution for this issue?

**Comment by pierresouchay** [comment]
Hello,

I am surprised you are still using Consul 0.4.1... and furthermore, the path are likely examples, meaning that this kind of path is unlikely to work on Windows (not c: or d: within paths):

/opt/consul_0.4.1/conf.d/consul.crt

So, I just might misunderstand and Consul is not running Windows, and only is your http client, or your might just have copied some doc from somewhere.

I would recommend to:

* Read carefully the doc
* Give full output of commands
* Try to give information about consul version and logs

I am not from hashicorp, but the bug report looks quite incomplete to me

Regards

**Comment by jdelic** [comment]
I don't understand the reference to consul 0.4.1, I assume that @karthikrajakandasamy edited his original question and removed that.

However

> "verify_incoming": true,

means [the following](https://www.consul.io/docs/agent/options.html#verify_incoming):

> `verify_incoming`: If set to true, Consul requires that all incoming connections make use of TLS and that the client provides a certificate signed by a Certificate Authority from the ca_file or ca_path. This applies to both server RPC and to the HTTPS API. By default, this is false, and Consul will not enforce the use of TLS or verify a client's authenticity.

Please note the reference to **SSL Client Certificates**. You configured consul to require the clients to provide a client certificate and presumably you do not when trying to access the UI. Set `verify_incoming` to `false` and try again maybe? Aside from that, I recommend that you follow @pierresouchay's advice and try to find some log output from consul and perhaps post it to gitter.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
