### ISSUE TITLE
consul issue on kubernetes

### ISSUE THREAD

**Issue by nik786** [hashicorp/consul#4151]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

2018/05/24 05:13:36 [ERR] agent: failed to sync remote state: No known Consul servers
    2018/05/24 05:13:58 [ERR] agent: failed to sync remote state: No known Consul servers
    2018/05/24 05:14:16 [ERR] agent: failed to sync remote state: No known Consul servers
    2018/05/24 05:14:34 [ERR] agent: failed to sync remote state: No known Consul servers
    2018/05/24 05:14:52 [ERR] agent: failed to sync remote state: No known Consul servers
    2018/05/24 05:15:14 [ERR] agent: failed to sync remote state: No known Consul servers

cat deployments/consul-1.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul
  namespace: kube-system
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
        member: consul-1
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: consul
          image: "progrium/consul:latest"
          args:
            - "agent"
            - "-bind=0.0.0.0"
            - "-ui"
            - "-node=consul-1"
            - "-server"
            - "-bootstrap-expect=3"
            - "-advertise=$(CONSUL_1_SERVICE_HOST)"
            - "-rejoin"
            - "-retry-join=consul-1.consul.kubernetes.default.svc.cluster.local"
            - "-retry-join=consul-2.consul.kubernetes.default.svc.cluster.local"
            - "-retry-join=consul-3.consul.kubernetes.default.svc.cluster.local"
            - "-client=0.0.0.0"
            - "-data-dir=/var/lib/consul"
            - "-config-dir=/etc/consul"
            - "-domain=cluster.local" 
            - "-disable-host-node-id"
          ports:
            - containerPort: 8300
              name: server
            - containerPort: 8301
              name: serflan-tcp
              protocol: "TCP"
            - containerPort: 8301
              name: serflan-udp
              protocol: "UDP"
            - containerPort: 8302
              name: serfwan-tcp
              protocol: "TCP"
            - containerPort: 8302
              name: serfwan-udp
              protocol: "UDP"
            - containerPort: 8400
              name: rpc-port
            - containerPort: 8500
              name: api-port
            - containerPort: 8600
              name: consuldns-tcp
              protocol: "TCP"
            - containerPort: 8600
              name: consuldns-udp
              protocol: "UDP"
          volumeMounts:
            - name: "consulconfig"
              mountPath: /etc/consul
      volumes:
        - name: "consulconfig"
          "secret": {
            "secretName": "consul-config"
          }

can any tell me how to resolve this issue??

2018/05/24 05:13:36 [ERR] agent: failed to sync remote state: No known Consul servers
 2018/05/24 05:13:58 [ERR] agent: failed to sync remote state: No known Consul servers
 2018/05/24 05:14:16 [ERR] agent: failed to sync remote state: No known Consul servers

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
