### ISSUE TITLE
Consul 1.1.0 windows virus?

### ISSUE THREAD

**Issue by yakcamnevets** [hashicorp/consul#4157]
Hello, I submitted Consul to my company for approval for use on our systems and they returned the following virus scan results reporting that Consul 1.1.0 windows 386 contains Win32.Trojan.WisdomEyes. Could this be a false positive? Please advise.
[https://imgur.com/a/urcFac9](https://imgur.com/a/urcFac9)

**Comment by mkeeler** [comment]
@yakcamnevets This better be a false positive. We at HashiCorp certainly aren't embedding trojans in the software we produce. I will have to do a little more digging to be 100% sure though.

**Comment by mkeeler** [comment]
I have submitted our binary to Baidu for confirmation that it is a false positive. Unfortunately I have found no similar way to submit a binary for false-positive confirmation from Cylance.

Given that only 2 out of 65 checked flagged I am inclined to call this a false-positive. I doubled checked some of the others and many of them also look for the WisdomEyes trojan and did not find it. I will update this issue if/when I get a response back from Baidu.

**Comment by mkeeler** [comment]
@yakcamnevets We still have no reply from Baidu and a colleague of mine found a way to contact Cylance too (no reply from them either).

I am going to close this out as I am fairly certain there is no trojan within the binary. If we ever get something back from the AV vendors I will still update this issue but I am not holding my breath.
