### ISSUE TITLE
Support Multiple DNS domains for service requests

### ISSUE THREAD

**Issue by clly** [hashicorp/consul#4165]
This is similar to https://github.com/hashicorp/consul/issues/2920 and https://github.com/hashicorp/consul/issues/290 but I don't know if it would work for their use cases.

I've got a branch that seems to work. I've still got to create tests for my changes but I wanted to file this to see if it's something that would be accepted. I've added some examples at the bottom

#### Feature Description

Allow a service to do a DNS request against consul with a different domain and receive Service and Node responses for that domain. I'm not sure if SOA and NS requests are required but based on what I saw in the consul code it would be more complicated.

#### Use Case(s)

We're going to want to do a DNS migration and when we change the domain for consul we would need to be able to figure out a migration path. We don't have a way to rewrite DNS requests in our environment now (that I'm aware of) and any that I've been able to find would require implementing new DNS technologies. Configuring consul to respond to multiple domains would allow us to make that change without needing to coordinate that change with the applications using Consul DNS.

```
./consul agent -dev -domain consul.clly.me -extra-domain "clly.me"
```

```
[ raphael connor@7 11:55: ~/go/src/github.com/hashicorp/consul ] $
 (connor.r.kelly@gmail.com connor/multiple-dns-domains) --> nslookup -port=8600 consul.service.consul.clly.me localhost
Server:		localhost
Address:	127.0.0.1#8600

Name:	consul.service.consul.clly.me
Address: 127.0.0.1

[ raphael connor@7 11:56: ~/go/src/github.com/hashicorp/consul ] $
 (connor.r.kelly@gmail.com connor/multiple-dns-domains) --> nslookup -port=8600 consul.service.clly.me localhost
Server:		localhost
Address:	127.0.0.1#8600

Name:	consul.service.clly.me
Address: 127.0.0.1

[ raphael connor@7 11:56: ~/go/src/github.com/hashicorp/consul ] $
 (connor.r.kelly@gmail.com connor/multiple-dns-domains) --> 
```

SRV records still return the original domain as do SOA and NS requests 
```
[ raphael connor@7 11:57: ~/go/src/github.com/hashicorp/consul ] $
 (connor.r.kelly@gmail.com connor/multiple-dns-domains) --> nslookup -query=SRV -port=8600 consul.service.clly.me localhost
Server:		localhost
Address:	127.0.0.1#8600

consul.service.clly.me	service = 1 1 8300 raphael.node.dc1.consul.clly.me.

[ raphael connor@7 11:57: ~/go/src/github.com/hashicorp/consul ] $
 (connor.r.kelly@gmail.com connor/multiple-dns-domains) --> 
```

**Comment by mnuic** [comment]
Hi,

That is exactly what we need. We would like to have ability to have multiple DNS domains registered in consul. One domain for internal use, let’s say for services to communicate internally, and one domain for client requests.

Let’s say domain ‘example.internal.com’ for services to be able to reslov each other, and second domain ‘example.external.com’ for external clients to resolv requests on http or https.

Is it possible to have this added in next release?

**Comment by freddygv** [comment]
Hi @clly this is functionality that we would like to add before the 1.6 release. 

Are you interested in completing the work from your branch? If so we can get it reviewed, but if not we can implement it.

**Comment by freddygv** [comment]
@clly we will be reviewing #4526 since we just heard back from that contributor. Would be great if you could take a look at it as well.

**Comment by clly** [comment]
I am very excited. I'm sorry I never finished the work on my branch. life kind of happened :(

**Comment by i0rek** [comment]
Will close this issue since the PR has been merged!
