### ISSUE TITLE
Consul SSL Issue with service register

### ISSUE THREAD

**Issue by karthikrajakandasamy** [hashicorp/consul#4171]
Am Using consul with SSL. I created consul UI to access with secured way by calling the below URL
**https://127.0.0.1:8500/ui/**. I created SSL certificate to achieve this.

Now am trying to register one external service in this Consul UI, but i could not achieve this. Am facing some certificate issue. Am using consul.net Dll where i dont have an option to achieve httphandler from my clinet. Can anyone suggest me to register service in my consul server using dot net. Thanks in advance. Below is my code for HTTP client.

              **HttpHandler = new HttpClientHandler();
                HttpHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
                HttpHandler.SslProtocols =System.Security.Authentication.SslProtocols.Tls12;
                HttpHandler.ClientCertificates.Add(new X509Certificate2(@"\Certificate\consul.crt"));
                HttpClient = new HttpClient(HttpHandler);**

**Comment by mkeeler** [comment]
@karthikrajakandasamy This question would probably be better asked in the [Consul google group](https://groups.google.com/forum/#!forum/consul-tool). General questions should be asked there as you are more likely to get replies from other users and not just the Consul developers (which monitor the forum too). If you do encounter a bug or would like to submit a feature request then please enter a new issue for it.

As an aside, the Consul team doesn't directly support any dot net API client. You may want to find the developers of the client libraries you are using if they are not working with Consul utilizing TLS and submit a bug/feature request to them.

Also if you have all the SSL/TLS issues worked out with using a HTTP client directly (not via some API intermediary) then you may find the [API docs](https://www.consul.io/api/agent/service.html) useful.
