### ISSUE TITLE
Unable to start a Consul cluster on OpenShift

### ISSUE THREAD

**Issue by Riduidel** [hashicorp/consul#4172]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

It's impossible to start a Consul Cluster in a kubernetes environment with Consul 1.1.0

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Have a Kubernetes cluster at hand (I use an OpenShift one, but I don't think this has a signifiant impact)
1. Prepare Consul deployment using [Kelsey Hightower tutorial](https://github.com/kelseyhightower/consul-on-kubernetes/blob/master/README.md). 
1. In the Stateful Set security constraints, add a `runAsUser: 100` to use Consul user, and replace consul version for image by the latest one
1. Optionnally you can remove the security declarations
1. Try to start your Consul cluster by deploying the stateful set

It will fail with `su-exec: setgroups(1000): Operation not permitted`

To my mind, this is linked to su-exec being unable to "pass-thourgh" when the user is already "the good none". In my case, I'm already consul:consul, so su-exec should just run the command.

### Operating system and Environment details

Reproduced on an OpenShift cluster

**Comment by m3744** [comment]
I have similar issue, only tcp 8300 port service alive, other service not work.

**Comment by Riduidel** [comment]
I modified the Consul docker image according to the procedure described on StackOverflow question [Run Consul Docker image as non root in Kubernetes](https://stackoverflow.com/a/50354067/15619) and it works now as expected.

**Comment by m3744** [comment]
Hi Riduidel:

    I describe my problem,I accounding  Kelsey Hightower tutorial setup consul cluster environment, installed after I launch server bootstrap mode, service seem not work, service only listen tcp 8300 port. below is my k8s setting and some log

CENTOS 7.1
kubernetes version 1.8.8


consul stateful pods print  log

WARNING: LAN keyring exists but -encrypt given, using keyring
WARNING: WAN keyring exists but -encrypt given, using keyring
bootstrap_expect &gt; 0: expecting 3 servers
==&gt; Starting Consul agent...

consul stateful pods netstat log
/ $ netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 :::8300                 :::*                    LISTEN      
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path

**Comment by pearkes** [comment]
Looks like you've sorted this out @Riduidel, so going to close this.

**Comment by AlexisLessard** [comment]
A PR to integrate this fix to the consul docker image has been created: [Allow Consul to run as non-root user #113](https://github.com/hashicorp/docker-consul/pull/113). Could someone from Hashicorp look into it?
