### ISSUE TITLE
Local config doesn't work!

### ISSUE THREAD

**Issue by shang7053** [hashicorp/consul#4174]
i used spring-cloud-starter-consul-all:1.3.2.RELEASE .
in dev-env, I wish I could specify a server by property like *.ribbon.listOfServers=127.0.0.1:9700，but，it doesn't work, unless set spring.cloud.consul.enabled to false or code like that `@FeignClient(name = "baseapi", url = "http://127.0.0.1:9700/", fallback = PartnerRpcFallback.class)`
the global config in consul-config like this ,`spring.cloud.config.override-system-properties=true
spring.cloud.config.allow-override=true
spring.cloud.config.override-none=false`
Shouldn't local configuration files cover remote configuration files?

**Comment by kyhavlov** [comment]
This doesn't sound like an issue with Consul itself - you probably want to get help from the [spring consul repo](https://github.com/spring-cloud/spring-cloud-consul).
