### ISSUE TITLE
Address of service missing in new UI if it differs from the node

### ISSUE THREAD

**Issue by dacameron** [hashicorp/consul#4175]
Nice work on the new UI, it looks great!

In the old consul UI the address of the service was visible if it differed from the node's address. In the new UI on v1.1.0 I only see the port of the service not the address.

While not common, we sometimes register a service with a different address to the node through the agent API. This info is hidden in the new UI.

**Comment by johncowen** [comment]
Hi @dacameron good spot! Thanks for trying things out for us, will check in with the rest of the team and come back to you on this. If you notice anything else in the meantime, please let us know.

**Comment by leprechau** [comment]
We just noticed the same thing after updating to 1.1.0 on our docker hosts.  We routinely run one consul agent per docker host but like to see the internal addresses of each service (container) in the UI when troubleshooting.

**Comment by johncowen** [comment]
Hi @leprechau thanks for the +1 on this. It's on our radar, but definitely good to know others are noticing it also 👍 , also good to hear your use case.

As soon as we have any concrete news on this we'll update this issue, it should be fairly soon.

Thanks, and keep any other things you notice coming!

Ah, just as a final note, remember if this is getting in the way of your workflow, you can also start up 1.1.0 **without** the CONSUL_UI_BETA variable and you can continue to use the old UI as normal.

**Comment by leprechau** [comment]
@johncowen Thank you and yes understood on the _beta_ status.  I've placed the `CONSUL_UI_BETA` into the sysconfig environment variable file in our RPM setup.

**Comment by kotuk81** [comment]
+1 on this. 
Missing this info on that

**Comment by johncowen** [comment]
Apologies for the wait on this folks!
