### ISSUE TITLE
De-Couple Consul Cluster WAN

### ISSUE THREAD

**Issue by smitjainsj** [hashicorp/consul#4182]
#### Overview of the Issue

While I am performing upgrade on our Multi DC Consul Cluster , in order to move ahead. I planned to decouple all the clusters  first and then upgrade one by one. However, I have tried all possible IPTABLES combination to block traffic within Consul Clusters but the WAN output doesn't show them as **failed**.

The current setup runs on a 5 DC  arch (with individual cluster running in each DC) and I am trying to decouple all of them in order to upgrade the cluster. I started with decoupling with 1 DC, lets say DC01 from the rest of the group. Therefore, I did implement iptables to block all INPUT and OUTPUT traffic to the DC01 Nodes IP address and vice versa on the DC01 Cluster nodes. 
However, even after the iptables , the output for the command  from DC0{2,3,4,5} ``` $ consul members -wan ``` still shows the servers of DC01 in **failed** state which is **CORRECT** .
But if I execute the command from DC01  ``` $ consul members -wan ```  its show all nodes as **alive** state.

Currently I am trying to upgrade from **Consul 0.6.4 to 1.0.7**

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 1
build:
	prerelease =
	revision = 26a0ef8c
	version = 0.6.4
consul:
	bootstrap = false
	known_datacenters = 5
	leader = false
	server = true
raft:
	applied_index = 13157448
	commit_index = 13157448
	fsm_pending = 0
	last_contact = 7.805017ms
	last_log_index = 13157448
	last_log_term = 255
	last_snapshot_index = 13150987
	last_snapshot_term = 250
	num_peers = 2
	state = Follower
	term = 255
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 107
	max_procs = 24
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 14
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 396
	members = 132
	query_queue = 0
	query_time = 1
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 91
	members = 15
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Client info</summary>

```
$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 26a0ef8c
	version = 0.6.4
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 40
	goroutines = 36
	max_procs = 40
	os = linux
	version = go1.6
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 14
	failed = 0
	intent_queue = 0
	left = 0
	member_time = 396
	members = 132
	query_queue = 0
	query_time = 1
```

</details>

### Consul Server OS Information
```
$ cat /etc/*release
Oracle Linux Server release 6.5
Red Hat Enterprise Linux Server release 6.5 (Santiago)
Oracle Linux Server release 6.5
```

### Iptables rules
The below iptables are implemented on the DC0{2,3,4,5} cluster nodes and vice versa on the DC01 cluster nodes.

```
sudo iptables -A OUTPUT  -d dc01-node1 -j DROP
sudo iptables -A OUTPUT  -d dc01-node2 -j DROP
sudo iptables -A OUTPUT  -d dc01-node3 -j DROP
sudo iptables -A INPUT  -s dc01-node1  -j DROP
sudo iptables -A INPUT  -s dc01-node2 -j DROP
sudo iptables -A INPUT  -s dc01-node3  -j DROP
sudo iptables -L INPUT && sudo iptables -L OUTPUT

```

### Log Fragments
While checking logs on the all the consul cluster nodes, I can see that the cluster is not able to talk to each other but the command ``` $ consul members -wan ```  still shows alive.

```
@400000005b0fbc0e3187d51c     2018/05/31 09:10:28 [DEBUG] memberlist: Initiating push/pull sync with: x.x.x.x:8301
@400000005b0fbc162004ffa4     2018/05/31 09:10:36 [ERR] memberlist: Failed to send ping: write udp [::]:8302->x.x.x.x:8302: sendto: operation not permitted
@400000005b0fbc1b2006249c     2018/05/31 09:10:41 [ERR] memberlist: Failed to send ping: write udp [::]:8302->x.x.x.x:8302: sendto: operation not permitted
@400000005b0fbc2020060d2c     2018/05/31 09:10:46 [ERR] memberlist: Failed to send ping: write udp [::]:8302->x.x.x.x:8302: sendto: operation not permitted
@400000005b0fbc222461d5cc     2018/05/31 09:10:48 [INFO] agent.rpc: Accepted client: 127.0.0.1:51518
@400000005b0fbc252005bf0c     2018/05/31 09:10:51 [ERR] memberlist: Failed to send ping: write udp [::]:8302->x.x.x.x:8302: sendto: operation not permitted
```

**Comment by pearkes** [comment]
What ports are you blocking with iptables? My assumption without too much understanding is that you may be allowing wan gossip (serf) traffic. However, I would like to understand what you're trying to accomplish by doing this in the first place? 

Here's a list of [ports in use by Consul](https://www.consul.io/docs/agent/options.html#ports-used).

**Comment by pearkes** [comment]
Sorry, I didn't read this properly the first time and it looks like you're blocking all input and output traffic, so ports are irrelevant? I think I'd go back to my question of what you're trying to accomplish, with that being said.

**Comment by smitjainsj** [comment]
I want to decouple each DC in the cluster, ideally as per the documentation
it says the consul would remove the server which is in failed state in 72
hours but this happened. Since I cannot stop the current  cluster in each
DC and I also want to decouple it . So, I was trying to use IPtables to
block communication within the consul server nodes. However, this doesn't
work in the 0.6 version.


Thanks & Regards,
------------------------------------------------
Smit Jain
Contact no.-9582921008
Email: smitjain.sj@gmail.com

**Comment by pearkes** [comment]
If the nodes are already joined, stopping traffic between them will not decouple or disconnect them in the catalog. Consul will treat it as a recoverable failure for some amount of time depending on your configuration. I'd recommend not joining or not utilizing cross-wan features of Consul during this time.
