### ISSUE TITLE
Standardization of weights for load-balancing

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#4198]
#### Feature Description

When using Consul to discover backends for reverse proxies, there is now way to guess the weight of a given backends.

Since backends are running on different nodes, I would be nice to standardize in Consul how much calls are redirected to a given instance, thus all proxies and libraries might be using the same rules. Historically, some proxies / libraries are using tags, some other start using Meta in instances, but all of this is a mess.

Some proxies are using DNS SRV (eg: HaProxy), some other HTTP APIs, it would be nice to have the same data for both.

I propose the following:

1. Add metadata in Services with specific semantics regarding Load-Balancing
2. Return the data in HTTP and SRV DNS interfaces
3. Allow using the warning status in DNS response to modify the weight dynamically (thus it would allow services to heavily loaded to receive less traffic, for instance when they receive too many requests and return warning state)

#### Implementation proposal

When defining a service, use the following optional service Meta:

```
{
  "Meta": {
    "_dns_passing_prio": "1",          # default value = 1
    "_dns_passing_weight": "10",   # default value = 1
    "_dns_warning_prio": "1".         # default value = 1
    "_dns_warning_weight": "1"     # default value = 0
  }
}
```

When DNS return SRV requests, for each SRV record, apply the corresponding `_dns_<state>_weight` and `_dns_<state>_prio` to fill DNS SRV records

This could be very easily implemented and would simplify a lot interoperability of Load balancing systems.

Optionally, we might also use similar meta data at node level (defined in the agent) in order to multiply those weights based on node characteristics (thus services would not have to know on what kind of large/tiny instance they are running) - but it could be a improvement for another PR.

What do you think?

I am ready to implement this if Hashicorp considers including it.

**Comment by iksaif** [comment]
cc: @wdauchy
