### ISSUE TITLE
Feature Request: Webui Filter services by tags

### ISSUE THREAD

**Issue by mgmonteleone** [hashicorp/consul#420]
Would be quite usefull for admins to be able to filter the services list by tag.

For example we tag services by customer name/instance, utilityService, microService, etc...

> As a system admin i would be able to filter the service list by tags so that I can quickly identify which service types are running on which host to be able to plan and maintain the environment.

**Comment by sethvargo** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
