### ISSUE TITLE
Suspicious log messages after upgrading to Consul v0.8.5

### ISSUE THREAD

**Issue by piniv** [hashicorp/consul#4200]
Hello!

We have recently upgraded our server cluster from version **v0.7.5** to **v0.8.5** in a rolling manner (launch/terminate) and shortly after that started to roll out **v0.8.5** to the clients (currently ~80% upgraded).
After the upgrade, we noticed some concerning DEBUG messaged on the leader:

### 1. Rebalanced X servers -> Number is incorrect
> manager: Rebalanced 7 servers, next active server is i-04a311c462b14ef27.us-east (Addr: tcp/172.30.145.167:8300) (DC: us-east)

Our cluster is containing only 5 working servers.
Found this bug https://github.com/hashicorp/consul/issues/3463 but not sure it applies to our case since I do not see any servers in "failed" state when running `consul members` nor when listing raft peers `consul operator raft --list-peers`

### 2. Pinging 2 dead servers
This one is probably connected to the first issue - manager keeps trying to ping old/dead servers.

> 2018/06/06 14:17:54 [DEBUG] manager: pinging server "i-0ae3fd2cb938b8ac4.us-east (Addr: tcp/172.30.148.207:8300) (DC: us-east)" failed: rpc error: failed to get conn: dial tcp <nil>->172.30.148.207:8300: getsockopt: no route to host

>2018/06/06 14:24:45 [DEBUG] manager: pinging server "i-0fd8076a727c42e12.us-east (Addr: tcp/172.30.179.93:8300) (DC: us-east)" failed: rpc error: failed to get conn: dial tcp <nil>->172.30.179.93:8300: i/o timeout

As mentioned, those servers are not shown in any of the members/peers lists. I also tried to `force-leave` them out of the cluster but the message keeps showing up.

### 3. forgoing reconnect for random throttling
> [DEBUG] serf: forgoing reconnect for random throttling

Not sure what this means, but it repeats every minute (exactly!) - Any mentioning I have found about this message was associated to K/V lock which we don't use.

Please let me know if I can provide with any other useful info. Thanks!

**Comment by pearkes** [comment]
Unfortunately there seem to be some related issues with upgrades of these versions. I'm going to close this in favor of #4135 which will be referenced.

**Comment by phamtai97** [comment]
Hi all.
@pearkes  I have this issue. I deploy the Consul server cluster includes 3 nodes. I check log and see: 

```sh
manager: Rebalanced 3 servers, next active server is consul3_645.6 (Addr: tcp/x.x.x.x:8300) (DC: xxx-consul-dev-cluster
```
I use version v1.6.3.
