### ISSUE TITLE
Shown tags are not consistent (seem to pick an instance to display from)

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/consul#4203]
Consul 1.1.0 Beta UI

**Describe the problem you're having**
One the Services page tag "active" is shown, on the Service page tag "standby" is shown.
![screen shot 2018-06-06 at 16 03 03](https://user-images.githubusercontent.com/90741/41065175-61ab0268-69a3-11e8-8ceb-fc56574b8483.png)
![screen shot 2018-06-06 at 16 03 08](https://user-images.githubusercontent.com/90741/41065176-6388372c-69a3-11e8-8157-09c4d4f64014.png)

**Describe the solution you'd like**
Tags should be consistently displayed. I'm open to ideas, but definitely need to have a consistent view of tags. Perhaps have all tags shown on overview view, and on the service view have all tags displayed as across top like [here](https://github.com/hashicorp/consul/issues/4119#issuecomment-388979307) but as clickable node filters. Additionally show corresponding tags on each node?

**Share inspiration**
How have you seen this problem solved well in other UIs?

**Comment by johncowen** [comment]
Hi @dekimsey ,

Thanks for the feedback, and for trying things out for us!

I'm unable to replicate this right now. Would you be able to paste me the JSON responses you are getting for these 2 pages? Or at least a truncated version of it if the entire response isn't possible. If you are using Chrome you should be able to get them from the Web Inspector in the Network > [XHR] > [Response] tab.

I'm specifically after the responses to:

`GET /v1/internal/ui/services`

and

`GET /v1/health/service/vault`

Thanks,

**Comment by dekimsey** [comment]
@johncowen well that's odd. It happens to all services, not just vault. We've recently restructured the services so they no longer have tags. At least in our services we were holding it wrong anyway. 

Here's the output from those API calls.

### `GET /v1/internal/ui/services`

```
...
  {
    "Name": "vault",
    "Tags": [
      "standby"
    ],
    "Nodes": [
      "devchi-inf-001",
      "devchi-inf-002",
      "devchi-inf-003"
    ],
    "ChecksPassing": 6,
    "ChecksWarning": 0,
    "ChecksCritical": 0
  },
...
```

### `GET /v1/health/service/vault`
```
[
  {
    "Node": {
      "ID": "4f34087c-506b-ea61-62c2-f3cbabdfb790",
      "Node": "devchi-inf-001",
      "Address": "10.70.255.191",
      "Datacenter": "devchi",
      "TaggedAddresses": {
        "lan": "10.70.255.191",
        "wan": "10.70.255.191"
      },
      "Meta": {
        "consul-network-segment": ""
      },
      "CreateIndex": 3774185,
      "ModifyIndex": 3778538
    },
    "Service": {
      "ID": "vault:10.70.255.191:8200",
      "Service": "vault",
      "Tags": [
        "active"
      ],
      "Address": "10.70.255.191",
      "Meta": null,
      "Port": 8200,
      "EnableTagOverride": false,
      "CreateIndex": 3832001,
      "ModifyIndex": 3832096
    },
    "Checks": [
      {
        "Node": "devchi-inf-001",
        "CheckID": "serfHealth",
        "Name": "Serf Health Status",
        "Status": "passing",
        "Notes": "",
        "Output": "Agent alive and reachable",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Definition": {},
        "CreateIndex": 3774185,
        "ModifyIndex": 3774185
      },
      {
        "Node": "devchi-inf-001",
        "CheckID": "vault:10.70.255.191:8200:vault-sealed-check",
        "Name": "Vault Sealed Status",
        "Status": "passing",
        "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
        "Output": "Vault Unsealed",
        "ServiceID": "vault:10.70.255.191:8200",
        "ServiceName": "vault",
        "ServiceTags": [
          "active"
        ],
        "Definition": {},
        "CreateIndex": 3832002,
        "ModifyIndex": 3832097
      }
    ]
  },
  {
    "Node": {
      "ID": "4555d830-c164-2326-a9a6-670ce975461e",
      "Node": "devchi-inf-002",
      "Address": "10.70.255.200",
      "Datacenter": "devchi",
      "TaggedAddresses": {
        "lan": "10.70.255.200",
        "wan": "10.70.255.200"
      },
      "Meta": {
        "consul-network-segment": ""
      },
      "CreateIndex": 3774185,
      "ModifyIndex": 3778535
    },
    "Service": {
      "ID": "vault:10.70.255.200:8200",
      "Service": "vault",
      "Tags": [
        "standby"
      ],
      "Address": "10.70.255.200",
      "Meta": null,
      "Port": 8200,
      "EnableTagOverride": false,
      "CreateIndex": 3832006,
      "ModifyIndex": 3832006
    },
    "Checks": [
      {
        "Node": "devchi-inf-002",
        "CheckID": "serfHealth",
        "Name": "Serf Health Status",
        "Status": "passing",
        "Notes": "",
        "Output": "Agent alive and reachable",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Definition": {},
        "CreateIndex": 3774185,
        "ModifyIndex": 3774185
      },
      {
        "Node": "devchi-inf-002",
        "CheckID": "vault:10.70.255.200:8200:vault-sealed-check",
        "Name": "Vault Sealed Status",
        "Status": "passing",
        "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
        "Output": "Vault Unsealed",
        "ServiceID": "vault:10.70.255.200:8200",
        "ServiceName": "vault",
        "ServiceTags": [
          "standby"
        ],
        "Definition": {},
        "CreateIndex": 3832007,
        "ModifyIndex": 4133033
      }
    ]
  },
  {
    "Node": {
      "ID": "4325030d-273d-3387-1e32-494d48af8522",
      "Node": "devchi-inf-003",
      "Address": "10.70.255.185",
      "Datacenter": "devchi",
      "TaggedAddresses": {
        "lan": "10.70.255.185",
        "wan": "10.70.255.185"
      },
      "Meta": {
        "consul-network-segment": ""
      },
      "CreateIndex": 3774185,
      "ModifyIndex": 3778536
    },
    "Service": {
      "ID": "vault:10.70.255.185:8200",
      "Service": "vault",
      "Tags": [
        "standby"
      ],
      "Address": "10.70.255.185",
      "Meta": null,
      "Port": 8200,
      "EnableTagOverride": false,
      "CreateIndex": 3832011,
      "ModifyIndex": 3832011
    },
    "Checks": [
      {
        "Node": "devchi-inf-003",
        "CheckID": "serfHealth",
        "Name": "Serf Health Status",
        "Status": "passing",
        "Notes": "",
        "Output": "Agent alive and reachable",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Definition": {},
        "CreateIndex": 3774185,
        "ModifyIndex": 3774185
      },
      {
        "Node": "devchi-inf-003",
        "CheckID": "vault:10.70.255.185:8200:vault-sealed-check",
        "Name": "Vault Sealed Status",
        "Status": "passing",
        "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
        "Output": "Vault Unsealed",
        "ServiceID": "vault:10.70.255.185:8200",
        "ServiceName": "vault",
        "ServiceTags": [
          "standby"
        ],
        "Definition": {},
        "CreateIndex": 3832012,
        "ModifyIndex": 4057771
      }
    ]
  }
]

```

**Comment by burdandrei** [comment]
same here,  if I got service with 3 different tags, on Services screen only  one random tag is displayed

**Comment by johncowen** [comment]
Hey @dekimsey , @burdandrei again thanks for the help here. Looking at the response JSON you passed over (thankyou!), I actually think this has surfaced 2 separate, but related, issues. 

I'll be catching up with the team later today to discuss.

**Comment by johncowen** [comment]
Hi @dekimsey and @burdandrei ,

These does indeed seem to be 2 issues, I've split them into a new issue here #4222 to track the rendering of tags on the 'services listing page', and I will keep tracking the rendering of tags on the 'service detail page' here. One is vaguely backend related but both issues affect the UI.

Thanks again for your help with this one!

**Comment by johncowen** [comment]
Hi @dekimsey and @burdandrei ,

I'm just checking back in with you to see if the 1.2.0 release containing part of the fix for this has solved your issue? Be aware that the fix included was for the tags on the 'service detail page' only. We are tracking the tags on the 'services listing page' in #4222 (see above)

Hopefully things look better now, but please let me know if not.

Thanks

**Comment by burdandrei** [comment]
Hi @johncowen  sorry for the delay.
1.2.0 and in services overview I still see not all the tags of the services

**Comment by johncowen** [comment]
Hey @burdandrei 

No problem! Sorry yeah, I think what you call the 'services overview' page, is what I refer to as the 'services listing' page. If so, please keep an eye on #4222 once that is closed, the UI will reflect the fix.

Thanks!
