### ISSUE TITLE
consul_http_GET_v1_kv___count sums up values instead of displaying current in prometheus

### ISSUE THREAD

**Issue by vankosa** [hashicorp/consul#4205]
Hello everybody

I do not know whether to consider it a bug or a feature, but I get this behavior from myself.

When the:
```
$ curl -s http://dc.consul:8500/v1/agent/metrics | jq '.Samples | .[] | select(.Name == 
 consul.http.GET.v1.kv._") | .Count?'
$ 9
```
I get as a result one value (as I understand - the current number of requests)

If you run:
```
$ curl -s http://dc.consul:8500/v1/agent/metrics?format=prometheus | grep kv | grep count
$ consul_http_GET_v1_kv___count 398249
```

I get a completely different result, which, in my opinion, is the sum of the number of requests for some (not defined by me) time interval

In this case, the "PUT" queries show the current value in both the JSON and the Prometheus

Thanks in advance for the answer.

**Comment by pearkes** [comment]
Would be great to get input from @pierresouchay on this as I'm not totally sure what the intended output is for Prometheus.

**Comment by pearkes** [comment]
I hoped that helped answer your question @vankosa, I'm going to close this issue now.
