### ISSUE TITLE
Disable anti-entropy for an agent ?

### ISSUE THREAD

**Issue by skurtzemann** [hashicorp/consul#4207]
Hi,

Is there a way to disable anti-entropy for a agent (like `EnableTagOverride` does for a service) in order to avoid the log message `agent: Synced node info` ?

My usage is the following :
- I start an agent with some `node-meta` informations 
- An external process add a new `node-meta` (for example `node-status:busy`) in order to use it later to find easily the node using `/v1/catalog/service/<service>?node-meta=<my-new-node-meta>`
  - But when the agent sync his status the added node-meta is removed...

Thanks
Sébastien

**Comment by pearkes** [comment]
So there is good background on `EnableTagOverride` here: https://github.com/hashicorp/consul/issues/1102. I think I understand your use case, in that you want to update the catalog with new or additional node meta and not have the agent node meta be overridden by the sync.

As a workaround, `node-meta` is [reloadable](https://www.consul.io/docs/agent/options.html#reloadable-configuration), meaning you can HUP the agents with updated node metadata and without much churn can get what I believe is your desired affect. This is I assume less convenient then using the catalog APIs directly, though.

I'll tag this as a feature request, but I'm not 100% sure that is doable. Hopefully that workaround is appropriate for your use-case for now.

**Comment by pearkes** [comment]
Follow-up question...why does this have to be node metadata specifically, and can't be tied to a service via tags that allow this behavior (or service meta, which isn't able to be filtered in the same way, and doesn't have the override behavior)? Would appreciate understanding your use-case a bit more here and why you didn't take an approach focused on the services.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.

**Comment by BarthV** [comment]
Hi @pearkes !

This feature may be interesting for https://github.com/hashicorp/consul-k8s/issues/40 .
Currently anti-entropy mecanisms drop `hostNetwork: true` services pushed by consul-k8s in a Kubernetes cluster where worker nodes (kubelets) are also running a consul agent using the same name & the same IP
