### ISSUE TITLE
Support Unix domain socket for client HTTP interface

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#421]
Would you consider providing a Unix domain socket interface alongside the existing TCP interface?  I like the idea of being able to share the socket with Docker containers, which would otherwise require me to (a) have the client listen on all interfaces or (b) extend Consul to listen on some-but-not-all interfaces.  (a) also allows for finer-grained access control for local clients.

**Comment by sethvargo** [comment]
@ryanuber this is done now, correct?

**Comment by ryanuber** [comment]
This functionality is now in master.

**Comment by blalor** [comment]
Is it possible to listen on localhost:8500 *in addition to* the domain socket?  That was functionality I was hoping would be there.

**Comment by ryanuber** [comment]
@blalor not currently, no. We basically just support setting the address of the HTTP server to `unix://x/y/z` to listen on a domain socket rather than TCP. Could you elaborate on your use case a bit?

**Comment by blalor** [comment]
I never want to open port 8500 beyond the local machine.  I want to be able to make the consul agent available to docker containers without exposing the agent to the LAN (or worse), which is easy with the domain socket.  I also don’t want to have to fiddle with iptables to restrict TCP access to the agent.  curl only recently added unix domain socket support, and that’s not in most distributions, yet; I use curl frequently to query the agent.

So, ideally I’d be able to specify a list of ports to listen on.

**Comment by ryanuber** [comment]
Ok, that makes sense, re-opening. For the time being, you might be able to get away with using an HTTPS server and a UNIX domain socket.

**Comment by blalor** [comment]
Thanks!  I’ve had a workaround for a while, using socat:

socat -d -d -lu -lf/var/log/docker-consul-proxy.log tcp-listen:8500,bind=172.17.42.1,fork tcp:127.0.0.1:8500,nodelay

I’m actually just exposing the agent to the docker0 interface in this case, which was slightly simpler than dealing with the domain socket.  If the list of listen-able interfaces could include multiple IPs and ports I think that would be ideal.

**Comment by slackpad** [comment]
I'm going to close this out in favor of https://github.com/hashicorp/consul/issues/473 which captures the "bind to multiple" loose end here.
