### ISSUE TITLE
ACLs page could use a sorted listing

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/consul#4210]
1.1.0 Beta UI

**Describe the problem you're having**
The ACL display page doesn't sort by anything obvious. It might be sorted by uuid.

**Describe the solution you'd like**
I'd like to see the ACLs sorted. Maybe management > client, then alphabetically thereafter? It need not have sortable tables (I don't really see that as super valuable here), but the view should definitely be sorted by some obvious metric.

**Share inspiration**
A common UX design is that anything displayed to the user should always be sorted and it should be sorted by something the user can see (not an internal identifier). I could be making this up. Or maybe it was in Don't Make Me Think. Anyway, it's a pretty sane rule to follow 😄 . Thanks!

**Comment by opihana** [comment]
@dekimsey The API currently sorts by token id, as you suspected. By hiding the token in the UI, this sorting is unintuitive. And although we _will_ be updating the UI to show the token (at least partially), we still think it'll be best to sort ACLs by name. We'll let you know when this has been updated.
