### ISSUE TITLE
Window Key not resizable with new UI

### ISSUE THREAD

**Issue by maxadamo** [hashicorp/consul#4218]
**New UI**
I am testing the NEW UI.

**window not resizable in JSON mode**
I store long keys in Consul, and wen I click "json" it shows a pretty nice window, but unfortunately the user experience is just bad. In order to work with my key I always need to scroll up and down. 

**it should be resizable**
The same as in the old UI. 

**Share inspiration**
Keep the good old work: in the old UI it was resizable.

**Comment by johncowen** [comment]
Hey @maxadamo , good spot that one!

Thanks for trying the new beta out for us, if you spot anything else please let us know. In the meantime we'll update you here once we've addressed your issue.

Thanks!

**Comment by johncowen** [comment]
Hi @maxadamo ,

I'm not sure if you managed to try out the UI in the 1.2.0 release, but it contained a fix to address this issue.

If you could let me know, and I can look to close this issue (or feel free to close it yourself)

Thanks,

**Comment by maxadamo** [comment]
@johncowen yes, it's resizable and it looks very nice.
