### ISSUE TITLE
prepared query using dc parameter doesn't work in version 0.7.5

### ISSUE THREAD

**Issue by cshabi** [hashicorp/consul#4224]
#### Overview of the Issue
For prometheus federation queries, we want to have a prepared query that is built using a service name resolved from a different consul DC.

We followed the documentation and came up with this command:
`curl -v -X POST -H "Content-Type: application/json" -d'{"Name":"prometheus","Service":{"Service":"<service_name>"}}' http://localhost:8500/v1/query?dc=<DC_name>`

The command ran successfully and returned an ID:
`* About to connect() to localhost port 8500 (#0)`
`*   Trying 127.0.0.1... connected`
`> POST /v1/query?dc=sadc1 HTTP/1.1`
`> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3`
`> Host: localhost:8500`
`> Accept: */*`
`> Content-Type: application/json`
`> Content-Length: 80`
`>`
`* upload completely sent off: 80out of 80 bytes`
`< HTTP/1.1 200 OK`
`< Content-Type: application/json`
`< Date: Thu, 14 Jun 2018 13:28:43 GMT`
`< Content-Length: 45`
`<`
`* Connection #0 to host localhost left intact`
`* Closing connection #0`
`{"ID":"59607176-e96b-726b-6ed8-42b7c5654d7d"}`

When querying the ID we get:
`curl http://localhost:8500/v1/query/59607176-e96b-726b-6ed8-42b7c5654d7d
Query not found`

Trying to execute it returns the same output

### Consul info for Server
agent:
	check_monitors = 1
	check_ttls = 0
	checks = 2
	services = 3
build:
	prerelease =
	revision = '21f2d5a
	version = 0.7.5
consul:
	bootstrap = false
	known_datacenters = 4
	leader = true
	leader_addr = IP:8300
	server = true
raft:
	applied_index = 1376209986
	commit_index = 1376209986
	fsm_pending = 0
	last_contact = 0
	last_log_index = 1376209986
	last_log_term = 354988
	last_snapshot_index = 1376208113
	last_snapshot_term = 354988
	latest_configuration = [{Suffrage:Voter ID:IP:8300 Address:IP:8300} {Suffrage:Voter ID:IP:8300 Address:IP:8300} {Suffrage:Voter ID:IP:8300 Address:IP:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 1
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 354988
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 27957
	max_procs = 24
	os = linux
	version = go1.7.5
serf_lan:
	encrypted = true
	event_queue = 0
	event_time = 154339
	failed = 2
	health_score = 0
	intent_queue = 0
	left = 3
	member_time = 144882
	members = 1982
	query_queue = 0
	query_time = 1175
serf_wan:
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 147
	members = 10
	query_queue = 0
	query_time = 1

### Operating system and Environment details
ubuntu12.04 baremetal servers

**Comment by pearkes** [comment]
Are you creating the prepared query in the same datacenter as you're reading it from? Your GET request will default the dc to the local agent, whereas you're passing `<dcname>` explicitly when creating it. I'd try to be explicit on create/get there and you should be able to retrieve the prepared query.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
