### ISSUE TITLE
Failed to start Raft: mmap too large

### ISSUE THREAD

**Issue by SurferL** [hashicorp/consul#4240]
#### Overview of the Issue

Following on from a question in the [community mails](https://groups.google.com/forum/#!topic/consul-tool/grZZV_v7odo) about an issue I'm having with servers reconnecting after a powercut, one of the error messages has me perplexed on what to do next on a mac-mini:
```
bootstrap_expect > 0: expecting 3 servers
==> Error starting agent: Failed to start Consul server: Failed to start Raft: mmap too large
```

Furthermore, looking at `/var/consul/raft/raft.db`, it think's the file is `562.95 TB` large, but getting more info says it only takes `34.4 MB on disk`.

Also, Mac Server 2 has an error message which I don't know how to decipher...

Any more information on how I should proceed while retaining information (and not wiping /var/consul), would be very much appreciated as I have some data from Vault stored there as well!

#### Reproduction Steps

Rough steps to reproduce this issue, from my scenario:

1. Create a cluster with n client nodes n and 3 server nodes (server nodes being a ubuntu VM, and two mac-mini's).
2. Interrupt the power supply to the mac-mini's and have them restart.
3. See how the servers cannot reconnect together.

### Operating system and Environment details

Mac Server 1: OSX 10.13.3, Consul version 1.0.6
Mac Server 2: OSX 10.13.3, Consul version 1.0.6
Ubuntu server: Ubuntu 16.04 LTS, Consul version 1.0.6

### Log Fragments

Mac Server 1:
```
bootstrap_expect > 0: expecting 3 servers
==> Error starting agent: Failed to start Consul server: Failed to start Raft: mmap too large
```

Mac Server 2:

```
goroutine 1 [running]:
github.com/hashicorp/consul/vendor/github.com/boltdb/bolt.(*node).spill(0xc4201d81c0, 0x10, 0x10)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/vendor/github.com/boltdb/bolt/node.go:375 +0x715
github.com/hashicorp/consul/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc42003a0f8, 0x19c88fe, 0x2b272e0)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/vendor/github.com/boltdb/bolt/bucket.go:570 +0x4d3
github.com/hashicorp/consul/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc42003a0e0, 0x29ba09c, 0x4)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/vendor/github.com/boltdb/bolt/tx.go:163 +0x129
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft-boltdb.(*BoltStore).initialize(0xc42050d760, 0x0, 0x0)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft-boltdb/bolt_store.go:75 +0x134
github.com/hashicorp/consul/vendor/github.com/hashicorp/raft-boltdb.NewBoltStore(0xc420504240, 0x18, 0x2, 0xc420504240, 0x18)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/vendor/github.com/hashicorp/raft-boltdb/bolt_store.go:51 +0xc4
github.com/hashicorp/consul/agent/consul.(*Server).setupRaft(0xc4203c2f00, 0x0, 0x0)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/agent/consul/server.go:488 +0xaa5
github.com/hashicorp/consul/agent/consul.NewServerLogger(0xc42008b180, 0xc420461860, 0xc4203aaf60, 0x0, 0xc420461860, 0xc4203b2c00)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/agent/consul/server.go:333 +0xcb9
github.com/hashicorp/consul/agent.(*Agent).Start(0xc420342a80, 0xc420342a80, 0x0)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/agent/agent.go:292 +0x2ed
github.com/hashicorp/consul/command/agent.(*cmd).run(0xc4202ab000, 0xc42000e1a0, 0x2, 0x2, 0x0)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/command/agent/agent.go:337 +0x414
github.com/hashicorp/consul/command/agent.(*cmd).Run(0xc4202ab000, 0xc42000e1a0, 0x2, 0x2, 0xc4202adee0)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/command/agent/agent.go:77 +0x50
github.com/hashicorp/consul/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4201c8ea0, 0xc4201c8ea0, 0x40, 0xc4202b6340)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/vendor/github.com/mitchellh/cli/cli.go:242 +0x1eb
main.realMain(0x1c48687)
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/main.go:52 +0x416
main.main()
/private/tmp/consul-20180209-96398-sbh1rs/src/github.com/hashicorp/consul/main.go:19 +0x22
bootstrap_expect > 0: expecting 3 servers
panic: pgid (206158430208) above high water mark (8390)
```

Ubuntu server:

```
consul[1375]:     2018/06/14 14:00:08 [ERR] agent: failed to sync changes: No cluster leader
consul[1375]:     2018/06/14 14:00:09 [ERR] http: Request GET /v1/kv/vault/core/lock, error: No cluster leader from=127.0.0.1:45572
consul[1375]:     2018/06/14 14:00:14 [INFO] serf: attempting reconnect to <MachineName> <IP-ADDRESS>:8302
consul[1375]:     2018/06/14 14:00:14 [WARN] raft: Election timeout reached, restarting election
consul[1375]:     2018/06/14 14:00:14 [INFO] raft: Node at <IP-ADDRESS>:8300 [Candidate] entering Candidate state in term 24259
consul[1375]: 2018/06/14 14:00:14 [WARN] Unable to get address for server id 39677f93-a2e8-8281-2fcb-2323c113037d, using fallback address <IP-ADDRESS>:8300: Could not find address for server id 39677f93-a2e8-8281-2fcb-2323c113037d
consul[1375]: 2018/06/14 14:00:14 [WARN] Unable to get address for server id 74054daa-8408-4479-4082-b5ead4f8f5ed, using fallback address <IP-ADDRESS>:8300: Could not find address for server id 74054daa-8408-4479-4082-b5ead4f8f5ed
consul[1375]:     2018/06/14 14:00:14 [ERR] raft: Failed to make RequestVote RPC to {Voter 39677f93-a2e8-8281-2fcb-2323c113037d <IP-ADDRESS>:8300}: dial tcp <IP-ADDRESS>:0-><IP-ADDRESS>:8300: getsockopt: connection refused
consul[1375]:     2018/06/14 14:00:14 [ERR] raft: Failed to make RequestVote RPC to {Voter 74054daa-8408-4479-4082-b5ead4f8f5ed <IP-ADDRESS>:8300}: dial tcp <IP-ADDRESS>:0-><IP-ADDRESS>:8300: getsockopt: connection refused
consul[1375]:     2018/06/14 14:00:14 [ERR] http: Request GET /v1/kv/vault/core/lock, error: No cluster leader from=127.0.0.1:45586
consul[1375]:     2018/06/14 14:00:15 [ERR] http: Request PUT /v1/session/create, error: No cluster leader from=127.0.0.1:45514
consul[1375]:     2018/06/14 14:00:15 [WARN] agent: Check "vault:<IP-ADDRESS>:8200:vault-sealed-check" missed TTL, is now critical
consul[1375]:     2018/06/14 14:00:17 [WARN] agent: Syncing check "cpuUsage" failed. No cluster leader
consul[1375]:     2018/06/14 14:00:17 [ERR] agent: failed to sync changes: No cluster leader
consul[1375]:     2018/06/14 14:00:18 [ERR] agent: failed to sync remote state: No cluster leader
```

**Comment by banks** [comment]
> Furthermore, looking at /var/consul/raft/raft.db, it think's the file is 562.95 TB large

Yikes! When you say "looking at" can be you be more specific which tool reports that? The OS finder? 

It would _seem_ like your filesystem is corrupt if so - that information doesn't even come from the file itself. Is it possible to attempt to copy that file onto another volume/FS and see what the result is?

> panic: pgid (206158430208) above high water mark (8390)

Hmm this sounds a lot like an unresolved BoltDB issue we've seen before in other tools (https://github.com/hashicorp/nomad/issues/3977). The root cause though is likely the underlying filesystem being corrupt which is corroborated by your first issue which doesn't seem like it can possible be a bug in BoltDB if the FS metadata is that wrong.

If your ubuntu node is not complaining about it's DB, it should be possible to take a snapshot of that one and restore it on the other nodes. https://www.consul.io/docs/commands/snapshot.html

Hope that helps. I don't think there is much we can do if the underlying FS is corrupt sadly.

**Comment by SurferL** [comment]
Hi @banks - thanks for the detailed response! 

I was just using the macOS finder to grab the details for `raft.db`. I don't _believe_ the system is corrupt, as disk utility (first aid) reports that everything is okay, although I could be wrong here.

I'm afraid I've already just gone ahead and wiped `/var/consul` to restart the system from scratch, so can't do the test of copying that file to another volume/FS.

**Comment by banks** [comment]
Thanks for the update. Hopefully you'll never see that issue again but of
course if you do let us know and we'll hopefully get a chance to look a
little sooner!

**Comment by hehailong5** [comment]
We see same here in Ubuntu server:

/opt/application/consul/../consul-works/custom-config-dir/ports.json is:
{"ports":{"http":1102,"server":1099,"serf_lan":1100,"serf_wan":1101}}
@C_CMD@ /opt/application/consul/consul agent -server -bootstrap-expect 3 -data-dir /opt/application/consul/../consul-works/data-dir -config-dir /opt/application/consul/../consul-works/config-dir -config-dir /opt/application/consul/../consul-works/custom-config-dir -node=server-192_168_10_2 -domain=openpalette -disable-host-node-id -dns-port=53 -bind=192.168.10.2 -client=192.168.10.2 -retry-join=192.168.10.1 -retry-join=192.168.10.3 -retry-interval=5s
==> WARNING: Expect Mode enabled, expecting 3 servers
==> Starting Consul agent...
==> Error starting agent: Failed to start Consul server: Failed to start Raft: mmap too large

/opt/application/consul # ./consul info --http-addr=http://192.168.10.2:1102
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = f436077
        version = 0.8.4
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 192.168.10.1:1099
        server = true
raft:
        applied_index = 1818866
        commit_index = 1818866
        fsm_pending = 0
        last_contact = 63.817033ms
        last_log_index = 1818866
        last_log_term = 28
        last_snapshot_index = 1812722
        last_snapshot_term = 28
        latest_configuration = [{Suffrage:Voter ID:192.168.10.1:1099 Address:192.168.10.1:1099} {Suffrage:Voter ID:192.168.10.3:1099 Address:192.168.10.3:1099} {Suffrage:Voter ID:192.168.10.2:1099 Address:192.168.10.2:1099}]
        latest_configuration_index = 1818760
        num_peers = 2
        protocol_version = 2
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 28
runtime:
        arch = amd64
        cpu_count = 24
        goroutines = 98
        max_procs = 24
        os = linux
        version = go1.8.3
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 11
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 18
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 9
        members = 3
        query_queue = 0
        query_time = 1
