### ISSUE TITLE
UI may have issues with "Dark Mode"

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/consul#4248]
1.1.0 Beta UI

**Describe the problem you're having**
Teams has a dark mode, when enabled the view is unreadable. In normal view it's got a light Teams-beige going on. Some of the Vampires that work here have reported the issue to me though.

**Describe the solution you'd like**
Readable screen. Looks like the body is transparent. This may be more of an issue with Team's implementation of "dark mode" in their embedded iframe thing. But maybe making less transparent objects would suffice.

**Share inspiration**

<img width="982" alt="light" src="https://user-images.githubusercontent.com/90741/41612516-c8fe85d8-73b8-11e8-9ff6-25101999728b.png">
<img width="982" alt="dark" src="https://user-images.githubusercontent.com/90741/41612515-c8ee7990-73b8-11e8-8e3f-2418d8f51ec1.png">

**Comment by johncowen** [comment]
Hi @dekimsey ,

This commit should fix that one 👍 

https://github.com/hashicorp/consul/pull/4228/commits/3c02e17fa74c441d3175c5bfadb46c0eaf8a74b5

Thanks tho!

**Comment by johncowen** [comment]
HI @dekimsey ,

I'm just checking in to see if you've been able to try 1.2.0 which includes the commit that should solve the above issue. We tried this out in the upcoming Safari/DarkMode and the issue wasn't visible, but we noticed that it wasn't visible in our previous release either, so it would be good to know if it's fixed for your case.

Let me know if not.

Thanks,
