### ISSUE TITLE
New UI doesn't JSON slider is not persistent 

### ISSUE THREAD

**Issue by giladsh1** [hashicorp/consul#4255]
**Old UI or New UI**
New UI

**Describe the problem you're having**
The JSON slider doesn't "remember" the user's choice when setting it to on.
the user us required to select it every time.

**Describe the solution you'd like**
The UI should "remember" the user's choice.

**Comment by johncowen** [comment]
Hi @giladsh1 

I've just noticed this is still open, we added a persistent toggle to the UI, as well as making 'CODE' the default (so code editing mode is on by default)

I'm going to close this for the moment, but please feel free to reopen if it's not resolved sufficiently for you.

Thanks,
