### ISSUE TITLE
New UI doesn't validate JSON format

### ISSUE THREAD

**Issue by giladsh1** [hashicorp/consul#4256]
**Old UI or New UI**
New UI

**Describe the problem you're having**
The old UI used to show a green / red color when  checking the "validate JSON" box.
The new UI doesn't show when a JSON is valid / invalid.

**Describe the solution you'd like**
the user should be able to detect whether the input JSON is valid or not when setting the JSON slider to on.

**Comment by johncowen** [comment]
Hi @giladsh1 ,

We've recently released an RC which includes JSON validation/linting to the code editor, therefore I'm going to close this issue. Please feel free to reopen if it doesn't address your issue.

Thanks,

John
