### ISSUE TITLE
Support YAML validation in new UI

### ISSUE THREAD

**Issue by giladsh1** [hashicorp/consul#4258]
**Old UI or New UI**
New UI

**Describe the problem you're having**
Please support YAML syntax in the new UI.

**Describe the solution you'd like**
I would like to have a YAML validator in Consul KV with rich text editing, much like the JSON validator.

**Comment by johncowen** [comment]
Hi @giladsh1 

Firstly thanks for trying the new UI out for us and filing these issues, definitely appreciated!

Better JSON/YAML and other syntax validation is something that is on our radar, but good to hear that you'd like to see this also.

We'll try to keep you up to date here when we have more news on this.

Thanks,

**Comment by johncowen** [comment]
Hi @giladsh1 ,

We've recently released an RC which includes YAML validation/linting to the code editor, therefore I'm going to close this issue. Please feel free to reopen if it doesn't address your issue.

Thanks,

John
