### ISSUE TITLE
Allow filter of failed / left nodes in the UI

### ISSUE THREAD

**Issue by giladsh1** [hashicorp/consul#4260]
**Old UI or New UI**
New UI

**Describe the problem you're having**
We're using Terraform and Consul to create dev environments with many micro-services deployed to each environment.
more often than not, it's easier to apply changes using destroy / apply an entire environment with the same environment name.
However, since consul still shows failed/left nodes in UI, it's hard to distinguish the previous environment from the newly created one.

**Describe the solution you'd like**
add an option to filter only alive / failed / left nodes in the services tab + nodes tab based on serf health status.

IMHO filtering out of nodes should be the default UI view.
In most cases, when I open the the UI in the services tab, I see services listed as failed, only to eventually see  that the failed node is failing or left.

**Comment by opihana** [comment]
Hi @giladsh1,

Thank you for sharing this issue. We are working on fixing this for the next release. Specifically, we'll be updating the filters to be a bit more intuitive for the 3 different filtering scenarios people would typically want, and I believe it would cover your issue as that third filter would be only Nodes with 100% passing. See the screenshot below:

![screen shot 2018-07-02 at 10 10 29 am](https://user-images.githubusercontent.com/6323933/42171915-2e895122-7de0-11e8-9cc4-ad7b68ef4ae4.png)

Let me know if you think that covers it!

**Comment by giladsh1** [comment]
Hi @opihana 
Thanks for reaching out.
IMHO, this is not the best solution for this issue, since it will mask real issues.

When using auto-scaling features or AWS's spot instances, one should except a LOT of nodes replacements (can be hundreds a day).
unfortunately, these nodes does not always leave the cluster gracefully with "consul leave". 
They appear as bad nodes in the UI, even though there is no real issue, since they no longer exist...

For that reason, I'm not interested in filtering out bad nodes by error count, since it's not very helpful. instead I would like to get the option to filter out nodes where Serf is no longer responsive (marked as "failed" when running consul members). 
It's a very different scenario if Serf or my app is not responding, and using your suggested solution, I won't be able to distinguish these two cases.

Thanks and best regards

**Comment by opihana** [comment]
Thanks for clarification @giladsh1. It sounds like there could be a long term back end solution to this, but we don't currently have plans for working on that. For the short term, you're right: we can improve our filtering functionality. For an upcoming release, we are working on redesigning our search capabilities in the UI (for example, adding support for regex as referenced in #4201). I will definitely consider this use case--filtering out Serf failures--when I go about that comprehensive search design. We'll update you when we have news to share on it. 

When I have designs ready for this, I may be in need of user testers. Would you be interested in helping us test out this feature? These tests usually take 30 minutes and are done remotely over video call with screen share. If so, may I reach out to you (when the time comes) via the email listed on your Github account?

**Comment by giladsh1** [comment]
sure, I'd be happy to help.
