### ISSUE TITLE
Add HTTP Response to notes in HTTP Checks

### ISSUE THREAD

**Issue by ChaosCA** [hashicorp/consul#4262]
#### Feature Description

From the docs I see that the last check will include a `notes` field. According to the docs this is set to whatever the running script returned. This request extends the same functionality to HTTP Checks.

If I had an HTTP Check to a `mydomain/api/health` the `notes` field would store the last response if it ended in a 200 status code.

#### Use Case(s)

- The API Health page could return useful application specific details on it’s health that another application that asks Consul for a status could use.
- For example, the web page could return a JSON Response that includes the number of users currently logged in, allowing another application that asks Consul about the health of a service to know that information and take action accordingly for that node.
- Pretty much all the same use cases as the feature already exists for Scripts

#### Workaround

If I’m understanding currently a work around for this missing functionality would be to add a `curl mydomain/api/heath` to a script as that would output the JSON response and would get picked up by consul? 
Apologies if this feature exists already in some form, perhaps a documentation update should just occur then.

**Comment by ChaosCA** [comment]
It seems like this exists in the `Output` key. I don't see it documented anywhere but it seems like the body of the response is placed into a string containing the HTTP Status Code.

```
curl http://localhost:8500/v1/agent/checks
{"service:test":{"Node":"848f45e98c7a","CheckID":"service:test","Name":"/api/health","Status":"passing","Notes":"","Output":"HTTP GET http://localhost:5000/api/health: 200 OK Output: {\"hi\":123}\n","ServiceID":"test","ServiceName":"test API","ServiceTags":[],"Definition":{},"CreateIndex":0,"ModifyIndex":0}}
```

Specifically the Output key contains:
```
HTTP GET http://localhost:5000/api/health: 200 OK Output: {\"hi\":123}\n
```

As a string. So you'd have to parse that string looking for the beginning and end of your JSON object. 

It would be more useful if the body of the page is (at least partially) placed into the `notes` key.

**Comment by ChaosCA** [comment]
As well it doesn't seem like `Output:` updates unless the `Status` changes.

**Comment by kamaradclimber** [comment]
> As well it doesn't seem like Output: updates unless the Status changes

if you look at the /catalog api, this behavior is an optimization to avoid updating the servers everytime healthcheckoutput changed, which can happen quite often when you query any http endpoint for instance (some people start to put a healthcheck on a /metric endpoint for instance).

Looking at /agent/checks endpoint will show you the latest Output

**Comment by ChaosCA** [comment]
I was using the `/health/checks/service` for getting the Output, I suppose that uses the catalog API?

Thank you though, that makes sense.

I would still be interested in having the `notes` field be what HTTP responses `Output` like it does with scripts and TTL checks. Let me know what you think.

**Comment by pearkes** [comment]
For HTTP checks, the output key will show the HTTP response. You may not see this right away for the reasons @kamaradclimber mentioned. I believe this is already a use-case covered by that and so I'm going to close this.
