### ISSUE TITLE
New UI unusable when datacenter is down

### ISSUE THREAD

**Issue by fastest963** [hashicorp/consul#4265]
#### Overview of the Issue

The old UI would still let you see alive datacenters despite a single datacenter being down but the new UI immediately fails when the services call for a particular datacenter fails. You can't even change datacenters since the list doesn't load. When you load the UI you get:
```
500 (The backend responded with an error)
```

Because the JS is trying to load `/v1/internal/ui/services?dc=vagrant-james` and it's returning a 500 error.

It looks like the localStorage `dc` key is set to the down datacenter and since the dropdown doesn't load to let you select a different DC, it just fails on load. I think a good short-term fix is just still showing the DC selector at the top.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create multiple clusters
2. Goto `/ui`
3. Shutdown all servers in one cluster.
4. Reload `/ui`

### Log Fragments

Related log:
```
http: Request GET /v1/internal/ui/services?dc=vagrant-james, error: rpc error getting client: failed to get conn: dial tcp <nil>->10.42.0.5:8300: connect: connection refused from=130.211.2.84:56091
```

**Comment by johncowen** [comment]
Hi @fastest963 ,

Thanks for submitting the issue and for trying things out for us!

Just so I can try and replicate your problem as closely as possible, could I ask you - when the UI is requesting `/v1/internal/ui/services?dc=vagrant-james` and you are getting a 500, if you perform a request to `/v1/catalog/datacenters` (using `curl` or something), does `vagrant-james` exist in the response?

Lastly, just incase, hopefully you are aware that you can just revert to the old UI for the moment if this gets in the way of your workflow by not using the CONSUL_UI_BETA environment variable.

Thanks

**Comment by johncowen** [comment]
Hey no problem, the least I can do!

Ok, sounds like a strange one to me, let me check with the team, I would have assumed that if the datacenter is 'down' it should be in that list, or alternatively, if its classed as 'up' just with no services then that `/v1/internal/ui/services?dc=vagrant-james` should respond with an empty list, or a 404.

As a 500 is an internal server error, this would indicate to me a possible problem in the backend with our internal API endpoint.

That being said, if I can work around this scenario in the frontend, then I can certainly try.

I'm not sure if you are aware, but in the old UI there is a landing page with a list of datancenters and nothing else (as opposed to an immediate redirect to the services page), so I did put in some extra work to try to make sure this wouldn't cause any issue, but I was testing this for when a DC was removed and therefore ceased to exist in the `/v1/catalog/datacenters` response (and therefore I get a 404 when I go to `/v1/internal/ui/services?dc=vagrant-james`.

Thanks for the extra info though, I'll dig into it a bit further tomorrow.

👋

**Comment by fastest963** [comment]
Yup, I did notice that the landing page in the new UI was changed to just default to the last DC. I think that's a good change overall if we can just figure out this issue, then it'll be perfect!

**Comment by fastest963** [comment]
@johncowen Hey sorry, things have been hectic since I'm about to leave on vacation. Loading the UI at another DC's URL worked. I didn't realize you could do that. My issue was just happenstance that it was the first DC in the list but as long as I can select it via the UI or change the URL either work for now.

Thanks a lot!

**Comment by johncowen** [comment]
Hey @fastest963,

Cool, no problem - it sounds like I replicated your case, pretty sure I checked against the same situation from what you'd said. There's a PR gone in ^ to hedge against this a little more, hopefully it will prevent your issue from happening. Please do come back and reopen or re submit another issue if you continue to have problems post release the above PR. I'll try and check back once it's gone into a release.

Have good vacation!

**Comment by johncowen** [comment]
Hi @fastest963 ,

Just a quick note to ask if you've been able to try out the UI in the new 1.2.0 release? I was just triple checking with you to see if the UI in the new release solves your above issue?

Thanks,
