### ISSUE TITLE
Consul should report an error if it is not able to restore kv values from a backup snap

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/consul#4270]
#### Feature Description
Consul should report an error if it is not able to restore kv values from a backup snap.

#### Use Case(s)

https://github.com/hashicorp/consul/issues/3002

**Comment by banks** [comment]
In what cases is Consul unable to restore KV from a backup?

The linked issue seems to be only that vault cached stale stuff but was closed once that was established.

Can you provide some context for _why_ and how you are seeing KVs not being restored?

Thanks

**Comment by drewmullen** [comment]
It was indeed when there are cached values. Seems like an opportunity to throw a error rather than "success"

**Comment by banks** [comment]
Maybe I'm still missing something...

In the issue linked the cached values were in _Vault_. Consul has no idea what it's clients might have cached or not, how could we improve the error message there?

**Comment by drewmullen** [comment]
Sounds more like I was missing something lol I didn't catch the nuance of the data being cached by vault (and not consul). I often think of the tools as one.
