### ISSUE TITLE
Documentation Clarification: discovery_max_stale 

### ISSUE THREAD

**Issue by carlislk** [hashicorp/consul#4273]
#### Overview of the Issue

The documentation for discovery_max_stale seems to be listed incorrectly. It list listed under https://www.consul.io/docs/agent/options.html#discard_check_output. 

From a comment on gitter, the follow test case uses:
https://github.com/hashicorp/consul/blob/0d4e8676d1f75a2376a716677773edad22349682/agent/config/runtime_test.go#L2365
`"discovery_max_stale": "5s",
			"domain": "7W1xXSqd",
			"dns_config": {
				"allow_stale": true,
				"a_record_limit": 29907,`
#### Reproduction Steps
https://www.consul.io/docs/agent/options.html#discovery_max_stale

**Comment by mkeeler** [comment]
@carlislk Good catch. I updated it with that PR and it should show up on the website once that is merged and the website is deployed again.
