### ISSUE TITLE
Consul 1.2.0 states 1.1.0 in the  ui

### ISSUE THREAD

**Issue by roidelapluie** [hashicorp/consul#4276]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

Consul version in the ui is not correct

#### Reproduction Steps

Get consul 1.2.0

Run ./consul agent -dev

Open 127.0.0.1:8500

Version in the bottom is Consul v1.1.0-766-g681

### Consul info for both Client and Server

fresh consul 1.2.0

### Operating system and Environment details

Linux x64

**Comment by mkeeler** [comment]
This is a minor bug in the release/build process that will be fixed for the next release.
