### ISSUE TITLE
Intentions web ui does not know about the "clients"

### ISSUE THREAD

**Issue by roidelapluie** [hashicorp/consul#4281]
#### Overview of the Issue

When using a proxy to connect to a Consul Connect service, the service name of the proxy is not known in the intentions page of the UI.

#### Reproduction Steps

1. Start a consul 1.2.0 cluster
1. Register a service in the consul with proxy connect enabled
1. Connect to the service with a proxy: `./consul connect proxy -service myself -upstream prometheus:9091`
1. Go to the UI to create intention
1. The "myself" service is not in the autocomplete list and the message is confusing

We should maybe change the text to "future services or client services" ? And also the client is currently connected so it is strange not to have it in the autocomplete list.

![ms](https://user-images.githubusercontent.com/291750/41903957-879e781c-7937-11e8-9560-4b504452aed1.png)
![ms2](https://user-images.githubusercontent.com/291750/41903959-87ba1ac2-7937-11e8-9ba5-60e8754ae656.png)

### Consul info for both Client and Server

```
agent:                                                                                                                                    
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 2
build:
        prerelease = 
        revision = 28141971
        version = 1.2.0
consul:
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 127.0.0.1:8300
        server = true
raft:
        applied_index = 206
        commit_index = 206
        fsm_pending = 0
        last_contact = 0
        last_log_index = 206
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:a4d2c177-35cd-dcb2-1ca1-469d54b085e7 Address:127.0.0.1:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 106
        max_procs = 8
        os = linux
        version = go1.10.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

Linux

**Comment by opihana** [comment]
Hi @roidelapluie, thanks for checking out Connect right when it launched. Apologies for the slow response on this issue.

>When using a proxy to connect to a Consul Connect service, the service name of the proxy is not known in the intentions page of the UI.

We actually consider this a feature of setting Intentions, not a bug. We built it this way. When setting intentions for connecting to a proxy service, there would be nothing to enforce it, so we disallow it. Let us know if you have any further questions about this. Otherwise, we'll close the issue.

**Comment by roidelapluie** [comment]
thanks
