### ISSUE TITLE
lost metadata of node after updating from v1.1.0 to v1.2.0

### ISSUE THREAD

**Issue by sgavrylenko** [hashicorp/consul#4284]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

Lost meta data info of service after updating 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 3 server nodes (consul v1.1.0)
2. Register service
3. Update consul to v1.2.0
4. Check meta info about service

### Operating system and Environment details

Linux amd64

**Comment by banks** [comment]
Thanks for the report. 

I’ve not been able to confirm yet but it’s possible this got squashed during the large merge of the new connect feature.

We’ll double check what changed and why the tests didn’t catch it.

**Comment by mkeeler** [comment]
@sgavrylenko What data is missing? Are you unable to get this info via the HTTP API, DNS or both? If you could give the command/query you are using that is missing the data that would help in narrowing this down a bit.

**Comment by pearkes** [comment]
I'm having trouble reproducing this registering services via the HTTP API, see below.

```
$ curl --silent localhost:8500/v1/agent/self | jq '.Config.Version'
"1.1.0"
$ curl --silent -X PUT -d '{"Datacenter": "dc1", "Node": "example", "Address": "www.example.com", "Service": {"Service": "example-service", "Port": 80, "Meta": {"foo": "bar"}}}' http://localhost:8500/v1/catalog/register
true
$ curl --silent localhost:8500/v1/catalog/service/example-service | jq '.[0].ServiceMeta'
{
  "foo": "bar"
}

## Replace binary, but retain data-dir

consul-provider-scratch $ curl --silent localhost:8500/v1/agent/self | jq '.Config.Version'
"1.2.0"
consul-provider-scratch $ curl --silent localhost:8500/v1/catalog/service/example-service | jq '.[0].ServiceMeta'
{
  "foo": "bar"
}
```

**Comment by sgavrylenko** [comment]
@mkeeler during registration of service (via API)  we add some info (e.g. role, env, project etc). Then use this meta info for scraping metrics in prometheus

After updating consul to last version, prometheus couldn't find any meta info
So for fix this, we re-added all meta info

**Comment by mkeeler** [comment]
@sgavrylenko What does the output of a command like this `curl --silent <consul network addr>/v1/catalog/node/<node name>` look like.

**Comment by sgavrylenko** [comment]
@mkeeler With meta info it looks like this 
`{
  "Node": {
    "ID": "",
    "Node": "host.name.com",
    "Address": "123.123.123.123",
    "Datacenter": "dc-release",
    "TaggedAddresses": null,
    "Meta": {
      "env": "release",
      "project": "project",
      "role": "backend"
    },
    "CreateIndex": 1987280,
    "ModifyIndex": 1987280
  },
  "Services": {
    "node-exporter": {
      "ID": "node-exporter",
      "Service": "node-exporter",
      "Tags": [
        "monitoring",
        "project_project",
        "env_release",
        "role_backend"
      ],
      "Address": "",
      "Meta": null,
      "Port": 9100,
      "EnableTagOverride": false,
      "ProxyDestination": "",
      "Connect": {
        "Native": false,
        "Proxy": null
      },
      "CreateIndex": 1987280,
      "ModifyIndex": 1987280
    }
  }
}`

but after update it was
`{
  "Node": {
    "ID": "",
    "Node": "host.name.com",
    "Address": "123.123.123.123",
    "Datacenter": "dc-release",
    "TaggedAddresses": null,
    "Meta": {
    },
    "CreateIndex": 1987280,
    "ModifyIndex": 1987280
  },
  "Services": {
    "node-exporter": {
      "ID": "node-exporter",
      "Service": "node-exporter",
      "Tags": [
        "monitoring",
        "project_project",
        "env_release",
        "role_backend"
      ],
      "Address": "",
      "Meta": null,
      "Port": 9100,
      "EnableTagOverride": false,
      "ProxyDestination": "",
      "Connect": {
        "Native": false,
        "Proxy": null
      },
      "CreateIndex": 1987280,
      "ModifyIndex": 1987280
    }
  }
}`

**Comment by mkeeler** [comment]
@sgavrylenko I am also unable to reproduce this. I tried various combinations of service and node metadata, connect enabled/disabled, different meta values (including those ripped exactly out of your last post). I just ctrl+c out of my 1.1 Consul and start 1.2.

How are you upgrading the nodes in the cluster?
Can you provide some of your configuration so I can try to mirror your exact scenario with my testing?

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
