### ISSUE TITLE
List of nodes messed up / stacked

### ISSUE THREAD

**Issue by phoerious** [hashicorp/consul#4305]
**Old UI or New UI**
New UI

**Describe the problem you're having**
When I click on nodes, I see them all stacked on top of each other, except two: one which is directly below and one which is at the very bottom right when I scroll down.

This does not happen when I go to Services and then list the nodes from there.

![consul](https://user-images.githubusercontent.com/911270/42041909-35823d44-7af3-11e8-95dc-310059b27587.png)

You can see the much darker box shadow, which is because all nodes but two are stacked (without the blacking you'd actually see the node names being on top of each other). The second non-stacked node is not visible, because it's hidden beyond the scroll fold.

I'm using Consul version 1.2.0 (which still stays 1.1.0-766-g6813a990 in the footer BTW) and Google Chrome.

**Comment by mkeeler** [comment]
@phoerious The version discrepancy is a [known issue](https://github.com/hashicorp/consul/issues/4276) with the build system not updating the version. You are using the 1.2.0 UI.

@johncowen This looks to be your domain.

**Comment by phoerious** [comment]
Yes, I also checked the STDOUT dump for the version number. :-)

**Comment by mkeeler** [comment]
@phoerious If you `curl <consul addr>/v1/catalog/nodes` do you have entries with empty ID fields? There was a bug with regards to services registered without IDs not having them auto-generated that was causing some odd behavior in the  UI.

**Comment by phoerious** [comment]
Yes, indeed. It seems that all stacked nodes have empty IDs, while the other three have an autogenerated UUID.

**Comment by phoerious** [comment]
Great. Thanks!
