### ISSUE TITLE
bind_addr documentation not up to date with the code

### ISSUE THREAD

**Issue by Lasering** [hashicorp/consul#4306]
#### Overview of the Issue

The documentation about the `bind_addr`/`-bind` config says:
>The address that should be bound to for internal cluster communications. This is an IP address that should be reachable by all other nodes in the cluster. By default, this is "0.0.0.0", meaning Consul will bind to all addresses on the local machine and will advertise the first available private IPv4 address to the rest of the cluster. If there are multiple private IPv4 addresses available, Consul will exit with an error at startup. If you specify "[::]", Consul will advertise the first available public IPv6 address. If there are multiple public IPv6 addresses available, Consul will exit with an error at startup. Consul uses both TCP and UDP and the same port for both. If you have any firewalls, be sure to allow both protocols. **In Consul 1.0 and later this can be set to a space-separated list of addresses to bind to, or a go-sockaddr template that can potentially resolve to multiple addresses.**

#### Reproduction Steps
Steps to reproduce this issue, eg:

1. Try to launch a consul server with multiple bind addresses:
`consul agent -config-file=/etc/consul/consul.json -bind ":: 0.0.0.0"`
or
`consul agent -config-file=/etc/consul/consul.json` where the `consul.json` sets:
`"bind_addr": ":: 0.0.0.0"`

`consul.json` is setting server to true among other settings.

2. Get greeted with:
`==> bind_addr cannot contain multiple addresses. Use 'addresses.{dns,http,https}' instead.`
https://github.com/hashicorp/consul/blob/v1.2.0/agent/config/builder.go#L365

The `addresses` does not configure the Cluster Addr (WAN and LAN) so I cannot use that instead.

#### Notes
Setting:
`"client_addr": "127.0.0.1 ::1"` does exactly as stated in the documentation.

**Comment by mkeeler** [comment]
@Lasering In this case the documentation doesn't reflect the behavior. The documentation will be updated to reflect the current behavior. Also I don't believe that it ever worked but somehow made it into the documentation.

**Comment by Lasering** [comment]
The funny part is if I set bind_addr to be `::` or to be `0.0.0.0` consul will still listen in both IPv4 and IPv6. At least in CentOS 7.

**Comment by mkeeler** [comment]
@Lasering just to make sure I am understanding: binding to 0.0.0.0 allows ipv6 connections?

I would expect binding to :: to allow both ipv4 and ipv6 (unless you have your kernel/sysctl params configured otherwise). I didn't think there was anything in the kernel to do the same for ipv4

**Comment by Lasering** [comment]
Yes, that exactly right.

Just showing the important configs:
```
# cat /etc/consul/consul.json
{
  "client_addr": "::1",
  "bind_addr": "0.0.0.0",
  "server": true,
}
```

```
# systemctl status consul
● consul.service - consul
   Loaded: loaded (/etc/systemd/system/consul.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-06-29 13:25:18 UTC; 2min 50s ago
  Process: 11638 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 11729 (consul)
   CGroup: /system.slice/consul.service
           └─11729 /opt/consul/1.2.0/consul agent -config-file=/etc/consul/consul.json -config-dir=/etc/consul/conf.d

Jun 29 13:25:18 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:18 [INFO] agent: Started DNS server [::1]:8600 (tcp)
Jun 29 13:25:18 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:18 [INFO] agent: Started HTTP server on [::1]:8500 (tcp)
Jun 29 13:25:18 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:18 [INFO] agent: started state syncer
Jun 29 13:25:25 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:25 [WARN] raft: Heartbeat timeout from "" reached, starting election
Jun 29 13:25:25 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:25 [INFO] raft: Node at 100.68.7.175:8300 [Candidate] entering Candidate state in term 3
Jun 29 13:25:25 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:25 [INFO] raft: Election won. Tally: 1
Jun 29 13:25:25 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:25 [INFO] raft: Node at 100.68.7.175:8300 [Leader] entering Leader state
Jun 29 13:25:25 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:25 [INFO] consul: cluster leadership acquired
Jun 29 13:25:25 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:25 [INFO] consul: New leader elected: consul-to-test-vault.novalocal
Jun 29 13:25:25 consul-to-test-vault.novalocal consul[11729]: 2018/06/29 13:25:25 [INFO] agent: Synced node info
```

```
# netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd           
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1172/sshd           
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      973/master          
tcp6       0      0 :::8300                 :::*                    LISTEN      11729/consul        
tcp6       0      0 :::8301                 :::*                    LISTEN      11729/consul        
tcp6       0      0 :::8302                 :::*                    LISTEN      11729/consul        
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd           
tcp6       0      0 ::1:8500                :::*                    LISTEN      11729/consul        
tcp6       0      0 :::22                   :::*                    LISTEN      1172/sshd           
tcp6       0      0 ::1:8600                :::*                    LISTEN      11729/consul        
tcp6       0      0 ::1:25                  :::*                    LISTEN      973/master          
tcp6       0      0 :::443                  :::*                    LISTEN      11565/nginx: master 
```

```
# telnet 100.68.7.175 8301
Trying 100.68.7.175...
Connected to 100.68.7.175.
Escape character is '^]'.
```

I "masked" the IPv6.

```
# telnet abcd:1234:abcd:2035:f816:3eff:fe10:195d 8301
Trying abcd:1234:abcd:2035:f816:3eff:fe10:195d...
Connected to abcd:1234:abcd:2035:f816:3eff:fe10:195d.
Escape character is '^]'.
```

```
# systemctl stop consul
[root@consul-to-test-vault centos]# telnet abcd:1234:abcd:2035:f816:3eff:fe10:195d 8301
Trying abcd:1234:abcd:2035:f816:3eff:fe10:195d...
telnet: connect to address abcd:1234:abcd:2035:f816:3eff:fe10:195d: Connection refused
```

I can show you the sysctl params if that is helpful.

**Comment by mkeeler** [comment]
@Lasering So I just learned that Go when asked to bind to `0.0.0.0` instead chooses to bind to an dual-stack ipv6 socket. So `::` and `0.0.0.0` will effectively be the same thing

**Comment by mkeeler** [comment]
@Lasering That makes sense. Regarding the actual OS socket created and used for listening `::` and `0.0.0.0` will be no different. Consul itself will do other protocol checks in other parts of the code.
