### ISSUE TITLE
Consul auto deregistering the vault checks and services.

### ISSUE THREAD

**Issue by smartaquarius10** [hashicorp/consul#4311]
Our consul and vault cluster is working from so many days on windows machines. Whenever, vault is sealed or totally closed, we used to get its health checks  with the help of this url 

**curl https://xxxxxxx:8500/v1/health/state/any**

like this

{
        "Node": "xxxxxxxx",
        "CheckID": "vault:xxxxxxx:8200:vault-sealed-check",
        "Name": "Vault Sealed Status",
        "Status": "critical",
        "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
        "Output": "Vault Sealed",
        "ServiceID": "vault:xxxxxxxx:8200",
        "ServiceName": "vault",
        "ServiceTags": [
            "active"
        ],
        "Definition": {},
        "CreateIndex": 607885,
        "ModifyIndex": 607951
    },

For some testing purpose we have kept our vault server totally closed(on one machine) for few days and hit the health check url again. This is the result I have received:

{
        "Node": "xxxxxxxx",
        "CheckID": "vault:xxxxxxx:8200:vault-sealed-check",
        "Name": "Vault Sealed Status",
        "Status": "critical",
        "Notes": "Vault service is healthy when Vault is in an unsealed status and can become an active Vault server",
        "Output": "TTL expired",
        "ServiceID": "vault:xxxxxxxx:8200",
        "ServiceName": "vault",
        "ServiceTags": [
            "active"
        ],
        "Definition": {},
        "CreateIndex": 607885,
        "ModifyIndex": 607951
    },

Now I have opened the window machine(where it is hosted) and ran the vault server. And, checked the health using the url defined above. In the result I have received this value as different where as others are same.

**"Output": ""**

I thought there is some error so I closed the vault server and at that very moment, first time I have seen this log in consul client window:

**Deregistered service "vault:xxxxxxx:8200"
[ERR] consul:  "Catalog.Deregister" RPC failed to server "vault:xxxxxxx:8200:vaul-sealed-check"
Deregisterd check "vault:xxxxxxx:8200:vault-sealed-check"**

Due to this its details are stopped coming in health check url which never happened before in passed 6 months. I used to close vault many times but never seen this log and always received some output in health checks using consul.

I thought may be due to TTL expiration I am getting issue so I have updated this TTL for vault service check using this url

curl https://<consul ur>/agent/check/pass/"vault:xxxxxxx:8200:vault-sealed-check"

After this, I re-ran the vault and rather than getting Output attribute blank I use to get values like this

        "Output": "Vault Sealed",
Or if unsealed,
        "Output": "Vault Unsealed",

But the moment I have closed the vault again, consul deregistered the vault details. And, after re running the vault I received the output value as blank again like this 

**"Output": ""**

Here my query is why my consul client is dregistering the vault server. Is there any way I can stop this auto deregisteration of vault checks and service. It is my humble request please let me know if its a bug or not. Because due to this issue the we are facing very serious challenge in the organization. We have made some window services for autonomous health monitoring of cluster but due to this issue our whole code is throwing exceptions in production environment. Any help will be much appreciated.

**Comment by smartaquarius10** [comment]
Typo in the query asked. For TTL Pass I have used this url

curl https:/myconsul:8500/agent/check/pass/"vault:xxxxxxx:8200:vault-sealed-check"

And I also got status as 200 OK

**Comment by pearkes** [comment]
> Here my query is why my consul client is dregistering the vault server. Is there any way I can stop this auto deregisteration of vault checks and service. It is my humble request please let me know if its a bug or not. Because due to this issue the we are facing very serious challenge in the organization. We have made some window services for autonomous health monitoring of cluster but due to this issue our whole code is throwing exceptions in production environment. Any help will be much appreciated.

I think if I understand you correctly you want to disable part of the Vault integration with Consul. That is achievable. See [here](https://www.vaultproject.io/docs/configuration/storage/consul.html#disable_registration) for more.
