### ISSUE TITLE
Strange split view look for the Code Editor in the UI

### ISSUE THREAD

**Issue by johncowen** [hashicorp/consul#4330]
Creating new issue by @giladsh1 from #4257 :

**Old UI or New UI**
New UI

**Describe the problem you're having**

Code View in the UI has a strange 'split' look, seem to be platform/browser specific

> This issue is always visible when using the "code view" - in the first blank line...

![42218932-dbef5224-7ed2-11e8-812c-e87e4fbc4074](https://user-images.githubusercontent.com/554604/42219277-55982764-7ec3-11e8-843c-3174272874b3.png)

> consul is running on CentOS Linux release 7.4.1708.
> I'm using Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by johncowen** [comment]
Hi @giladsh1

(just 'split' this out into a new issue so its more visible)

I don't suppose you noticed whether this has appeared since upgrading from 1.1.0 to 1.2.0, ie. do you know if this issue was apparent in the 1.1.0 UI?

Thanks

**Comment by giladsh1** [comment]
Hi @johncowen 
this issue was not visible in 1.1.0
FYI
