### ISSUE TITLE
Persist acl_agent_token etc. when set using the API

### ISSUE THREAD

**Issue by ac-astuartkregor** [hashicorp/consul#4333]
#### Feature Description

Currently the agent APIs that let you set the acl_agent_token and others ([these ones](https://www.consul.io/api/agent.html#update-acl-tokens)) do not cause the agent token to be persisted, and therefore the token must be set every time the agent restarts:
> Tokens are not persisted, so will need to be updated again if the agent is restarted.

It would be very useful if the token was persisted, in line with the [master ACL bootstrap API](https://www.consul.io/docs/guides/acl.html#bootstrapping-acls).

#### Use Case(s)

* Using the APIs for automation of consul provisioning and ACL bootstrapping.
* Prevents mangling of config files and easier automation.
* Consistency with existing APIs for ACLs.

**Comment by arctiqtim** [comment]
Seeing this behaviour as well.  To add to the use cases:
 * Kubernetes/Docker based deployments - wanting to bootstrap for automation and pods/containers can't be restarted.

**Comment by joewilliams** [comment]
Has there been any movement or updates on this issue?

**Comment by joewilliams** [comment]
Seems like `enable_token_persistence = true` was added in 1.4.3 which I think fixes this issue.

**Comment by mkeeler** [comment]
@joewilliams Yep, going to close this as that was implemented in 1.4.3.
