### ISSUE TITLE
Can't save empty kv pairs in new UI

### ISSUE THREAD

**Issue by adamkdean** [hashicorp/consul#4336]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

If you edit an empty key-value pair in the new UI, you are unable to save it. There are no buttons visible. Empty key-value pairs can be created in the UI initially, and through the API, but not through the UI if you remove all the content from a non-empty key-value pair.

**Comment by johncowen** [comment]
Hi @adamkdean 

Thanks for submitting this, it was a doozy! Sorry if it's been getting in your way!

I've submitted a PR ^ so a fix for this should be in our next release. If this is getting in the way of your workflow in the meantime, be aware you can use the CONSUL_UI_LEGACY env var if need be.

If you spot anything else, please keep the issues coming 👍 

Thanks,

**Comment by adamkdean** [comment]
No problem and thanks for the quick response. Just helping to improve the interface by testing it. It's great by the way, good improvement. Good job to the entire team. 👏

**Comment by chenger** [comment]
@adamkdean 
Ver 1.20
You can create key with empty value if you had not even point on value field and press save.
