### ISSUE TITLE
Consul mutual TLS setup guide/example for kubernetes

### ISSUE THREAD

**Issue by yacut** [hashicorp/consul#4338]
Without any guide it is hard to understand how Consul with mutual TLS works on kubernetes, so I would like to see an example for it, like here for Istio https://istio.io/docs/guides/bookinfo/. 
Some information about Consul and Istio is [here](https://www.consul.io/intro/vs/istio.html) but I think it is not enough.
Beautiful guide "Running HashiCorp's Consul on Kubernetes" from @kelseyhightower is [here](https://github.com/kelseyhightower/consul-on-kubernetes) but it is without mutual TLS services.

#### Feature Description

Add guides or examples for the following points:
- How to configure and use consul on kubernetes with mutual TLS?
- How works communication between services with mutual TLS?
- How to use consul with kubernetes ingress with mutual TLS?
- How works consul service discovery on kubernetes with mutual TLS?

#### Use Case(s)

- Guide for developers how wants to start Consul mutual TLS on kubernetes
- Practical example that helps to test consul features on kubernetes
- Compare mutual TLS setup with Istio

**Comment by pearkes** [comment]
Thanks for this @yacut. There is some work planned and being done now to better document and support Consul integrating with Kubernetes in a number of ways, some of which you mention.

**Comment by i0rek** [comment]
mutual TLS supported arrived in consul-helm: https://github.com/hashicorp/consul-helm.
