### ISSUE TITLE
make: *** [tools] Error 1

### ISSUE THREAD

**Issue by wayilau** [hashicorp/consul#4339]
I want build consul from source, but i met a problem like below:

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. create a project named go-oss
2. git clone git@github.com:hashicorp/consul.git to folder :"~/workspc/go-oss/src/github.com/hashicorp/consul"
3. set GOPATH=~/workspc/go-oss,  set the environment variable CONSUL_DEV=1
4. the cd ~/workspc/go-oss/src/github.com/hashicorp/consul type : make
5. when i use command : "make dev", it works fine.
### Consul info for both Client and Server

<details>
  <summary>Client info</summary>
 
```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.
os: Mac OS High Sierra 10.13.5 (17F77)
go version: 1.10.3
### Log Fragments

go get -u -v github.com/elazarl/go-bindata-assetfs/... github.com/hashicorp/go-bindata/... github.com/magiconair/vendorfmt/cmd/vendorfmt github
.com/mitchellh/gox golang.org/x/tools/cmd/cover golang.org/x/tools/cmd/stringer github.com/axw/gocov/gocov gopkg.in/matm/v1/gocov-html
github.com/elazarl/go-bindata-assetfs (download)
github.com/hashicorp/go-bindata (download)
github.com/magiconair/vendorfmt (download)
github.com/mitchellh/gox (download)
Fetching https://golang.org/x/tools/cmd/cover?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/cover?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/cover": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com
/tools"} at https://golang.org/x/tools/cmd/cover?go-get=1
get "golang.org/x/tools/cmd/cover": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
package golang.org/x/tools/cmd/cover: golang.org/x/tools is a custom import path for https://go.googlesource.com/tools, but /Users/francis/work
spc/go-oss/src/golang.org/x/tools is checked out from https://github.com/golang/tools.git
Fetching https://golang.org/x/tools/cmd/stringer?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/stringer?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/stringer": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/stringer?go-get=1
get "golang.org/x/tools/cmd/stringer": verifying non-authoritative meta tag
package golang.org/x/tools/cmd/stringer: golang.org/x/tools is a custom import path for https://go.googlesource.com/tools, but /Users/francis/workspc/go-oss/src/golang.org/x/tools is checked out from https://github.com/golang/tools.git
github.com/axw/gocov (download)
Fetching https://golang.org/x/tools/cover?go-get=1
Parsing meta tags from https://golang.org/x/tools/cover?go-get=1 (status code 200)
get "golang.org/x/tools/cover": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cover?go-get=1
get "golang.org/x/tools/cover": verifying non-authoritative meta tag
package golang.org/x/tools/cover: golang.org/x/tools is a custom import path for https://go.googlesource.com/tools, but /Users/francis/workspc/go-oss/src/golang.org/x/tools is checked out from https://github.com/golang/tools.git
Fetching https://gopkg.in/matm/v1/gocov-html?go-get=1
Parsing meta tags from https://gopkg.in/matm/v1/gocov-html?go-get=1 (status code 200)
get "gopkg.in/matm/v1/gocov-html": found meta tag get.metaImport{Prefix:"gopkg.in/matm/v1/gocov-html", VCS:"git", RepoRoot:"https://gopkg.in/matm/v1/gocov-html"} at https://gopkg.in/matm/v1/gocov-html?go-get=1
gopkg.in/matm/v1/gocov-html (download)
github.com/matm/gocov-html (download)
make: *** [tools] Error 1

**Comment by MagnumOpus21** [comment]
```
Sivas-MacBook-Pro:~ siva$ mkdir -p ~/workspc/go-oss
Sivas-MacBook-Pro:~ siva$ export GOPATH=~/workspc/go-oss
Sivas-MacBook-Pro:~ siva$ cd workspc/go-oss/
Sivas-MacBook-Pro:go-oss siva$ mkdir -p src/github.com/hashicorp
Sivas-MacBook-Pro:go-oss siva$ cd src/github.com/hashicorp/
Sivas-MacBook-Pro:hashicorp siva$ git clone git@github.com:hashicorp/consul.git
Sivas-MacBook-Pro:consul siva$ export CONSUL_DEV=1
Sivas-MacBook-Pro:consul siva$ make
==> Building Consul - OSes: darwin, Architectures: amd64
Building sequentially with go install
--->   darwin/amd64
```
Hi @wayilau , I followed the exact same steps as you did, but I got to build the Consul binary.

**Comment by MagnumOpus21** [comment]
I'm closing this. Should you come across another bug, please go ahead and open a new issue.

**Comment by wayilau** [comment]
can you tell my you go version is ?

**Comment by wayilau** [comment]
could you tell my your go version is ?

**Comment by MagnumOpus21** [comment]
Same version as yours, 1.10.3

**Comment by wayilau** [comment]
thanks， i think i missed a step: make tools. i followed this url: https://www.consul.io/docs/install/index.html#compiling-from-source, first 'make tools',then type 'make' or 'make dev'， it works fine.

**Comment by MagnumOpus21** [comment]
Glad you could figure it out :)
