### ISSUE TITLE
Single-node bootstrapped server demotes only leader to follower on startup

### ISSUE THREAD

**Issue by vito** [hashicorp/consul#434]
This is new behavior with 0.4.1, which seems to be introduced by hashicorp/raft@21328757b36df08d0d2093c26191f66d27e829aa.

Logs: https://gist.github.com/vito/6df780384b077d6e7dd6

Context: This was after upgrading that VM, which involves detaching the disk containing Consul's state, reattaching it to a fresh VM, and starting Consul up on the new VM. Maybe some state that Consul uses to identify itself was lost when rolling the VM?

My use case: I'm using Consul for drop-in DNS-based service discovery, and this is a very small deployment. A single Consul server is colocated with another process, and the rest of the cluster is told to join it in client mode. When the VM is being rolled it's expected that there will be no leaders for a period of time, and everything will be unavailable, but that when it's back up things will recover.

The deploy and update flow is heavily automated, and currently I unconditionally configure `bootstrap` or `bootstrap_expect` on the server. Even without that set, though, it just fails to join anyone on start, so my deploy seems hosed.

**Comment by re5et** [comment]
Has there been any progress on this one? Being bitten by it atm.

**Comment by osiloke** [comment]
I think this happens when the raft folder is not deleted on close i.e when the system does not cleanly power done. I saw something similar while using weed-fs which also uses raft.

**Comment by wwalker** [comment]
I am having the same problem, on 0.4.1; and ,like osiloke, removing the raft directory before restarting the server resolves the problem.

**Comment by dcoxall** [comment]
I am having this issue. Was using vagrant and bootstrap_expect 1and I see in the logs the leader is correctly selected and then demoted. Also 0.4.1. It happens even if I completely rebuild the VM

**Comment by vito** [comment]
Awesome!
