### ISSUE TITLE
CONSUL_HTTP_ADDR by default should be http://localhost:8500

### ISSUE THREAD

**Issue by Lasering** [hashicorp/consul#4344]
#### Feature Description

The default value of CONSUL_HTTP_ADDR should be `http://localhost:8500`.

#### Use Case(s)

This way Consul installations on IPv6 only or IPv4 only would work out of the box. More precisely executing consul commands would work out of the box.

**Comment by burdandrei** [comment]
https://github.com/hashicorp/consul/pull/4382 this should do it

**Comment by pearkes** [comment]
We ended up deciding against this. You can read the reasoning here:

https://github.com/hashicorp/consul/pull/4382#issuecomment-413975818
