### ISSUE TITLE
Consul v1.2.0 UI shows v1.1.0-xx in footer

### ISSUE THREAD

**Issue by scalp42** [hashicorp/consul#4355]
I'm not sure if the UI is on a different release train.

On a Consul v1.2.0 node:

<img width="481" alt="screen shot 2018-07-06 at 11 35 05 pm" src="https://user-images.githubusercontent.com/1475276/42407657-3ced3790-8175-11e8-9387-b5b7337d30f5.png">

Thanks in advance!

**Comment by mitchellh** [comment]
Thanks, this is fixed in master and will be fixed in 1.2.1. :)
