### ISSUE TITLE
Can't edit empty K/V in new ui

### ISSUE THREAD

**Issue by chenger** [hashicorp/consul#4360]
![b2](https://user-images.githubusercontent.com/2116107/42448520-13627b2a-8386-11e8-9921-14cb3573f553.png)
I'v uploaded keys with consul kv put. Empty keys, I'v imported could not be edited. There is no buttons in the form.
I still can delete them from the list.

**Comment by johncowen** [comment]
Hi @chenger ,

Pretty sure this is a dupe of #4336 which is now fixed in master and will be available in the next release.

Thanks,

**Comment by chenger** [comment]
@johncowen
Yes, thanks, i didnt read full text.
