### ISSUE TITLE
hope UI will support oauth verify.

### ISSUE THREAD

**Issue by Anricx** [hashicorp/consul#4367]
current ui do not have access control, will consul ui add support oauth verify(like github orginization oauth)?

#### Feature Description

configure ui support oauth access control like chronograf:
![image](https://user-images.githubusercontent.com/4424338/42486263-acba20fa-842d-11e8-863e-86cacb4fe6f1.png)

**Comment by johncowen** [comment]
Hi @Anricx 

The UI is only a thin client over the Consul HTTP API, so currently it will only support what the HTTP API of Consul itself supports.

I'm not sure if you are aware but Consul supports Access Control Lists:

https://www.consul.io/docs/guides/acl.html

Which may suit your needs?

Thanks,

**Comment by Anricx** [comment]
will there be a much powerful ui to manage consul services ? or already have some other tool to do such as:
* manually register/deregister service
* and so on

**Comment by johncowen** [comment]
Hi @Anricx 

We'll be adding more and more features to the UI as we move forwards. Some things may come sooner than others.

👍

**Comment by johncowen** [comment]
Hi @Anricx,

I'm going to close this, please feel free to re-open in the future if necessary.

Thanks

**Comment by Anricx** [comment]
it's ok.
