### ISSUE TITLE
List of healthy nodes not wrapped vertical

### ISSUE THREAD

**Issue by chenger** [hashicorp/consul#4368]
On vertical-align monitors, when all nodes are healthy and there is more than 20 nodes scroll apear on the right and field with nodes don't wrap down. See screenshot.

Also this concept of tile is good for users and extreamly unusable for administrating. The concept of lines with details is preferably.
![ui-bug3](https://user-images.githubusercontent.com/2116107/42498617-4f7fee3a-8435-11e8-8175-d96f4de7fb69.png)

**Comment by opihana** [comment]
@chenger Thank you for submitting this bug and adding the helpful screenshot. We'll be working on a fix. When we have an update, we'll let you know!
