### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by lyddragon** [hashicorp/consul#4370]
**OS:**
CentOS Linux release 7.0.1406 (Core)
Linux iZ2ze626b3aa33i4di6vq8Z 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**consul Version:**
Consul v1.2.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

**Test command：**
$  ./hey -m PUT -d '111111' -n 500000 -c 3000 -H "X-Consul-Token: d97f793d-1dd9-4678-b6e5-2457dcfc80ads"  http://172.16.1.246:8500/v1/kv/bench  

**Top info：**
Tasks: 135 total,   1 running, 134 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  16266416 total,  7928720 used,  8337696 free,   366368 buffers
KiB Swap:        0 total,        0 used,        0 free.   957964 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                             
**17348 consul    20   0 5359548 4.907g 201724 S   0.6 31.6  10:41.46 /usr/local/consul/bin/consul agent -config-dir=/usr/local/consul/etc/**

**Comment by banks** [comment]
Hi @lyddragon, thanks for the report.

Can you share why you think the memory is leaking? It's using quite a lot but from a single snapshot it's impossible to know if that's a leak or just normal usage. Can you provide graphs that show memory consumption over time?

Memory leaks are hard to track down at the best of times so it would help to have a lot more information - is this cluster under load, how long has it taken to get to 4GB RAM? How much does it "normally" use? How many KVs are you storing? How many services, nodes etc?

Is it just a plain server with no other activity other than your benchmark? What does your benchmark program do? Did the same behaviour happen with older versions of Consul?

**Comment by lyddragon** [comment]
![image](https://user-images.githubusercontent.com/5848331/42517437-4a84fad0-8492-11e8-88bf-51a4794f1643.png)

**Comment by lyddragon** [comment]
20:25 restart consul

**Comment by banks** [comment]
Hey,

That graph just shows that consul is using a lot of memory until it got restarted then it starting using lots of memory again. If your `hey` program is just writing millions of KV records then that's exactly what we'd expect to see. A memory leak tends to manifest in small growth creeping up over hours/days even when load on the cluster and keys in KV store are remaining constant.

Please provide more information about what that program is doing and all the other things I mentioned in last post otherwise we can't even tell if there is a problem at all much less help track down where! :D

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
