### ISSUE TITLE
Consul ACLs - Keyring Policy

### ISSUE THREAD

**Issue by codyja** [hashicorp/consul#4378]
#### Overview of the Issue

I’m enabling consul ACLs and have an anonymous policy defined. I wanted to restrict access to kv vault/ path (to prevent accidental deletes), prevent keyring commands, and operator commands, without authenticating first (and being an admin). All seems working, except for the keyring policy. If I set the keyring policy to deny or read, I can still run commands like `consul keyring -install=new_key_here` as anonymous, also same with the `-remove` flag. I tested with 1.0.7 consul originally, but also just tested with 1.2.0. Also, I have a default allow policy `"acl_default_policy": "allow",`

#### Reproduction Steps
anonymous.json payload file:

```
{
  "ID": "anonymous",
  "Type": "client",
  "Rules": "key \"vault/\" { policy = \"deny\" } keyring = \"deny\" operator = \"deny\""
}
```

Install anonymous policy into consul:
`curl --request PUT --header "X-Consul-Token: secret_mgmt_token" --data @anonymous.json http://consul_server:8500/v1/acl/create`

#### What I see happen
Validate no token set, so using anonymous policy, install new key, removed an older key works.
```
$ consul keyring -list
==> Gathering installed encryption keys...
error: Unexpected response code: 500 (Reading keyring denied by ACLs)
$ consul keygen
R8or7dfK0MhZlrsuD6oMpQ==
$ consul keyring -install=R8or7dfK0MhZlrsuD6oMpQ==
==> Installing new gossip encryption key...
$ consul keyring -remove=R8or7dfK0MhZlrsuD6oMpQ==
==> Removing gossip encryption key...
$ consul keyring -list
==> Gathering installed encryption keys...
error: Unexpected response code: 500 (Reading keyring denied by ACLs)
```

### Consul info for both Client and Server

```
Node                                              Address            Status  Type    Build      Protocol  DC              Segment
consul-server-dc1-i-07a7d9fb093d2c7f4.site1.local  10.10.11.254:8301  alive   server  1.2.0+ent  2         site1-staging  <all>
consul-server-dc1-i-08015392c2ce5e734.site1.local  10.10.11.147:8301  alive   server  1.2.0+ent  2         site1-staging  <all>
consul-server-dc1-i-0c8f44a8d20ee6d5f.site1.local  10.10.11.105:8301  alive   server  1.2.0+ent  2         site1-staging  <all>
```

**Comment by pearkes** [comment]
Thanks for the report. We've reproduced this and we'll fix it in part of our next release. This is a security issue but due to it not affecting clusters with the default policy set to deny (as we do recommend for most cases) we're not treating as a critical severity.
