### ISSUE TITLE
New UI doesn't show correct list of the nodes

### ISSUE THREAD

**Issue by rudziankou** [hashicorp/consul#4389]
Some of the items are overlapped with each other. And I also see empty slots in the grid. Could you please check this. Thank you!

![bug](https://user-images.githubusercontent.com/1725954/42666826-5a9aeb76-85fc-11e8-8864-24f676e283f0.png)

**Comment by johncowen** [comment]
Hi @rudziankou 

Thanks for the report! We've had this reported a couple of times also (#4249, #4305), the recent 1.2.1 release has a fix in the UI to watch for this and fix the visual problem.

But do let us know if you spot anything else after updating to 1.2.1 (and feel free to reopen if 1.2.1 doesn't fix it for you)

Thanks,
