### ISSUE TITLE
Pretty-print JSON health check responses in UI

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/consul#4390]
I'm using the new UI.

**Describe the problem you're having**
Currently when the JSON response from a health check is a bit big it gets cut off in the UI.
It would be nice if it was pretty-printed with indentation so it's readable.

![consul_json_big](https://user-images.githubusercontent.com/2212681/42691484-83f1ed10-86a8-11e8-89b2-1d2e3e472e02.png)

**Comment by opihana** [comment]
@jakubgs Thank you for submitting this idea. It definitely would be a great feature. We've added it to our backlog, but haven't prioritized it. If and when we have an update, we'll let you know!

**Comment by jakubgs** [comment]
Damn you you wretched machine.

**Comment by johncowen** [comment]
Hey @jakubgs !

(Humans to the rescue! 😄 )

We improved the rendering of the healthchecks and their outputs lately (take a look here https://demo.consul.io/ui/dc1/services/uuid/consul-client-3/_nomad-task-bcq6oxc7uh2nyxczmpzjhfuffzkq7lxv) we were just wondering if this solves your issue?

![Screenshot 2019-11-25 at 16 37 46](https://user-images.githubusercontent.com/554604/69559483-ee46f380-0fa1-11ea-9ee9-faa0ee7f0701.png)

Thanks!

**Comment by jakubgs** [comment]
That's exactly what I was hoping for, thanks @johncowen !

**Comment by johncowen** [comment]
Oh great! I'll close the issue now then, thanks @jakubgs !
