### ISSUE TITLE
Missing button

### ISSUE THREAD

**Issue by Flybro** [hashicorp/consul#4391]
#### Overview of the Issue
After creating an empty key, you can not edit it.

#### Reproduction Steps
1. Create an empty key with no value.
2. You are not allowed to edit this key, even with master token, as Save, Cancel changes and Delete buttons are missing. Although you can still delete it from the key's list.
![image](https://user-images.githubusercontent.com/10743439/42695043-763cb3a6-86b4-11e8-97a5-2da04d0b57b6.png)

**Comment by johncowen** [comment]
Hi @Flybro 

Thanks for the report! Pretty sure this is the same as #4336 and #4360 which has been fixed in 1.2.1.

I'm closing this as a dupe, but please feel free to reopen if 1.2.1 doesn't address this for you.

Please keep anything else coming.

Thanks,

**Comment by johncowen** [comment]
He says...

Looking into this now @Flybro 

👍 definitely thanks for the report!

Thanks,

**Comment by johncowen** [comment]
Hi @Flybro 

Sorry for the confusion, could you confirm for me what version of of the UI you are running on?

Thanks,

**Comment by Flybro** [comment]
Hi John,
Sorry my bad, I forgot to mention version, 1.2.0, and indeed in 1.2.1 the
bug disappeared

Cheers


W dniu pt., 13.07.2018 o 16:16 John Cowen <notifications@github.com>
napisał(a):
