### ISSUE TITLE
Usability in smaller screens is low

### ISSUE THREAD

**Issue by milanaleksic** [hashicorp/consul#4395]
**Old UI or New UI**
new UI, version 1.2.0

**Describe the problem you're having**
In the list of services, not enough space is left for the list so it's (almost) impossible to scroll. I am using iPhone SE so I wouldn't really say screen is small, maybe that it's a smaller one than some others but on other web sites I have no issues like this so I believe there is place for improvement...

**Describe the solution you'd like**
I would append extra empty space (like on the Nodes page) so that scrolling and visibility is possible

![img_1627](https://user-images.githubusercontent.com/50055/42735132-41232bb8-884f-11e8-95dc-edc43f97de38.jpg)

P.S. the version is also marked with a pencil but I understand that is issue that was already reported and handled via #4276 so please ignore it

**Comment by opihana** [comment]
Hi @milanaleksic, thank you for submitting this issue. We'll be working on a fix!

**Comment by opihana** [comment]
We're definitely going to continue improving the mobile-friendliness of Consul, but the specific issues brought up here have been resolved by the PRs above.
