### ISSUE TITLE
Display gossip encryption state in info

### ISSUE THREAD

**Issue by lra** [hashicorp/consul#440]
Small feature request, if it's not already there: I'd like to know if encryption is enabled or not in `consul info`.

I'm in the process of enabling encryption on our unencrypted cluster, and as a HUP is not enough, I need to restart all cluster instances. Would help to have a place to check if the running consul have encryption on or off, to know which are the ones I'm missing.

If there is already a place to check the runtime encrypt parameter, my bad.

**Comment by armon** [comment]
Done in #245

**Comment by lra** [comment]
Any way to know if ACL are enabled? I don't see anything in `consul info` of 0.5.1

**Comment by armon** [comment]
@lra There is no way to tell from `consul info`, but you can check the `ACLDatacenter` in /v1/agent/self
