### ISSUE TITLE
Make/Depoly UI Centos 7

### ISSUE THREAD

**Issue by TimRiley348** [hashicorp/consul#4402]
New to Consul and attempting to set up a sandbox environment.  I would like to demonstrate the sandbox environment.  The UI-V2 is good vehicle to display the results to others.  I can make and deploy the old ui (there are errors but it sort of works).  I can't get by even the basic make for ui-v2 on Centos 7.5.

Is the place where I can ask for assistance? 

Thanks,

**Comment by mkeeler** [comment]
@TimRiley348 Normally these sorts of questions would be better asked in one of the community forums as we use GitHub for bugs and feature requests.

Some links to those resources are here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [consul mailing list](https://www.consul.io/community.html)

With that being said, for building ui-v2 I would recommend running `make ui-docker`. This will build a docker container with all the required dependencies and put the resulting artifacts in pkg/web_ui/v2. 

If there are any further questions please post to the mailing list/google group and we can answer questions there.
