### ISSUE TITLE
the new web-ui kv page ignores the URL path, and restarts navigation at the root

### ISSUE THREAD

**Issue by pieterbreed** [hashicorp/consul#4409]
**New UI**
v1.2.1

**Describe the problem you're having**
When I browse through the KV db the URL changes as a navigate through folders, example: `http://consul-ui.internal/ui/dc1/kv/config/global/`. If I hit refresh, I expect that the same page will be shown after the re-render. Instead, browsing _restarts_ from the root of the KV store (and the URL changes to reflect this) `http://consul-ui.internal/ui/dc1/kv`.

**Describe the solution you'd like**
I'd like for the UI to honor the URI path and show me the same page I was on before I browser-reloaded. This was the behaviour in the old UI.

**Comment by johncowen** [comment]
Hi @pieterbreed 

Thanks for submitting the report!

I have a sneaky feeling this is a duplicate of #4324 basically an issue with the redirects within the UI 'server' (the server redirects anything with a trailing slash to a URL without the trailing slash).

I added a workaround in https://github.com/hashicorp/consul/pull/4373 which is in master but unfortunately did make it into the 1.2.1 release.

Pretty sure this will fix your issue, but I'll check back in once we push another release.

Thanks,

**Comment by johncowen** [comment]
Hi @pieterbreed ,

This fix made it into the 1.2.2 release (which we released early this week). I think it should solve your issue. If you can have a try and let me know either way that would be great.

Thanks,

**Comment by pieterbreed** [comment]
whoop whoop! it works, thank you very much :)

**Comment by johncowen** [comment]
Best Response Ever. 👍 

😄
