### ISSUE TITLE
Create ACL with a pre-defined token ID

### ISSUE THREAD

**Issue by gabrielfsousa** [hashicorp/consul#4416]
Is it possible to create ACL with a known ID that i generate?

**Comment by gabrielfsousa** [comment]
manage to found how

curl --request PUT --header "X-Consul-Token: acl_mast-er_t-oken-acl_-master_token" --data '{ "ID": "acl_agen-t_to-kena-cl_a-gent_tokenac" , "Name": "Agent Token", "Type": "client", "Rules": "node \"\" { policy = \"write\" }

**Comment by banks** [comment]
You got it!
