### ISSUE TITLE
New labels to help new contributors

### ISSUE THREAD

**Issue by soteras** [hashicorp/consul#4423]
#### Feature Description

I am new in golang and i want to help in this project, but i dont know if the issue is simple or hard. My suggestion is add new labels to help new contributors.

#### Use Case(s)

level-starter
level-intermediate
level-advanced

**Comment by soteras** [comment]
Yes i know it is a little hard but i'll help you a lot. Thanks

**Comment by mkeeler** [comment]
@soteras Going to close this as I think @banks answered the question. For the time being we are going to attempt to be better at labeling issues and in particular that `good-first-issue` one would be a good place for anyone new to the code base.
