### ISSUE TITLE
Multiple recursors return SERVFAIL

### ISSUE THREAD

**Issue by dfredell** [hashicorp/consul#4426]
#### Overview of the Issue

I'm running a local consul agent and specifying two recursor DNS servers. I want the ability to DNS query all 3 DNS servers in this order: consul, my internal data center DNS, and google's dns 8.8.8.8. My internal datacenter DNS returns SERVFAIL when querying `www.google.com` I then expect consul to query 8.8.8.8 but instead consul returns SERVFAIL. 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Setup a DNS server that doesn't forward requests to a public DNS, mine is at `10.2.3.28`, I'm using [Triton CNS](https://github.com/joyent/triton-cns) for my DNS server.
2. Start consul locally (with one node `-dev`) and point to an internal (10.2.3.28) and external (8.8.8.8 google's) dns recursor
* `consul agent -dev -server -ui -recursor 10.2.3.28 -recursor 8.8.8.8`
3. Verify that querying the consul service DNS endpoint works. This is a valid response, see how the `ANSWER SECTION:` has an ip address
```
~> dig @127.0.0.1 -p 8600 consul.service.consul 
; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> @127.0.0.1 -p 8600 consul.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 877
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;consul.service.consul.		IN	A

;; ANSWER SECTION:
consul.service.consul.	0	IN	A	127.0.0.1

;; ADDITIONAL SECTION:
consul.service.consul.	0	IN	TXT	"consul-network-segment="

;; Query time: 2 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Fri Jul 20 10:29:44 CDT 2018
;; MSG SIZE  rcvd: 102
```
4. Next try and query via consul for an address that is in your internal DNS, notice how that works successfully
`dig @127.0.0.1 -p 8600 lb.svc.80d12....`
5. Finally try and query via consul for `www.google.com` and notice how it fails
``` 
~> dig @127.0.0.1 -p 8600 www.google.com
; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> @127.0.0.1 -p 8600 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 23010
;; flags: qr rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1470
;; QUESTION SECTION:
;www.google.com.			IN	A

;; Query time: 32 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Fri Jul 20 10:35:37 CDT 2018
;; MSG SIZE  rcvd: 43
```
6. This is the same result I get when querying my internal DNS directly for www.google.com
```
~> dig @10.2.3.28 www.google.com           
; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> @10.2.3.28 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 51448
;; flags: qr rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1470
;; QUESTION SECTION:
;www.google.com.			IN	A

;; Query time: 31 msec
;; SERVER: 10.2.3.28#53(10.2.3.28)
;; WHEN: Fri Jul 20 10:36:23 CDT 2018
;; MSG SIZE  rcvd: 43
```
7. I would expect consul's DNS endpoint to look for `www.google.com` on 10.2.3.28, not find it, then go onto the next recursor which is 8.8.8.8 and 8.8.8.8 would be able to answer `www.google.com`

### Consul info for both Client and Server

<details>
  <summary>Consul info</summary>

```
~> consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 39f93f01
	version = 1.2.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 10
	commit_index = 10
	fsm_pending = 0
	last_contact = 0
	last_log_index = 10
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:b262bd1a-d445-5196-f9ab-0a04d794df7a Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 75
	max_procs = 8
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

```
~> uname -a
Linux bender 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments

```
    2018/07/20 10:29:03 [DEBUG] dns: recurse RTT for {www.google.com. 1 1} (31.716944ms)
    2018/07/20 10:29:03 [DEBUG] dns: request for {www.google.com. 1 1} (udp) (31.838467ms) from client 127.0.0.1:34702 (udp)
```

**Comment by MagnumOpus21** [comment]
Hey @dfredell , I wasn't able to replicate this issue across three different machines, running Consul with the same options that you provided. Note that the log fragment is in [DEBUG], this happens only if the DNS is _returned_ by a recursor. If it doesn't get a DNS response, the Consul logs it as an [ERROR].  I also looked into the codebase and modified it to get the recursor queried for the DNS query. 
```
2018/07/23 17:19:08 [ERR] dns: recurse failed: read udp 192.168.1.13:52993->10.2.3.28:53: i/o timeout
    2018/07/23 17:19:08 [DEBUG] dns: recurse RTT for {www.google.com. 1 1} (15.536815ms) Recursor answered: 8.8.8.8:53
    2018/07/23 17:19:08 [DEBUG] dns: request for {www.google.com. 1 1} (udp) (2.021407992s) from client 127.0.0.1:50641 (udp)
```

**Comment by MagnumOpus21** [comment]
But if I were to use a docker container with dnsmasq, it gives a **REFUSED** status, not **SERVFAIL**. So there is a bug here. Ty for bringing this into light. 👍

**Comment by dfredell** [comment]
Hey hey, nice I'm glad you could get a docker test case going. I was trying to get a test case going for the past 30min with a bind9 docker and it was only returning **REFUSED**

**Comment by dfredell** [comment]
Hello @MagnumOpus21, 
Do you know what release version this will be released in? I see it was merged into master on Aug 2nd but it isn't in the https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#unreleased notes

**Comment by MagnumOpus21** [comment]
Hey @dfredell , it should be out in the next release. And thank you for reminding us to add it to the changelogs. 😁
