### ISSUE TITLE
Managed Proxies sometimes not restarted

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#4455]
#### Overview of the Issue

I had a test cluster with 3 servers and 1 client. The client was setup with a single server with a managed proxy. All of this was done in docker. When I `docker restart` the client container it sometimes starts back up but doesn't start the managed proxy.

I think there is a race condition somewhere because this usually happens when I do

`docker restart consul-srv1 consul-srv2 consul-srv3 consul-client3`

but not when I run

`docker restart consul-client3`

The big difference here is that they are all on the same physical hardware so for that moment in time the system is under more load when restarting 4 containers vs 1.

#### Reproduction Steps

Its not 100% reproducible but with my 4 node cluster on a single docker node. The only step is to restart all of the nodes simultaneously.

**Comment by mkeeler** [comment]
In my testing I just have 4 containers without any persistent storage. However the containers are never destroyed so the writes to the main container filesystem are persisted between restarts of the container (stop/start not destroy/create).

Additionally the snapshot.json file contains the proxy that it thinks should be running. It just fails to start it when Consul starts.

As for the logs, the next time I run into the issue I will grab the logs.

**Comment by mkeeler** [comment]
In my most recent reproduction the proxy is started but non-functional.

The proxy logs look like this:

```
==> Consul Connect proxy starting...
    Configuration mode: Agent API
              Proxy ID: web-proxy

==> Log data will now stream in as it occurs:

    2018/07/30 13:29:31 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 5s
    2018/07/30 13:29:36 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 20s
    2018/07/30 13:29:56 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 45s
    2018/07/30 13:30:41 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 1m20s
    2018/07/30 13:32:01 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 2m5s
    2018/07/30 13:34:06 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 3m0s
    2018/07/30 13:37:06 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 3m0s
    2018/07/30 13:40:06 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 3m0s
    2018/07/30 13:43:06 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 3m0s
    2018/07/30 13:46:06 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 3m0s
    2018/07/30 13:49:06 [ERR] consul.watch: Watch (type: connect_leaf) errored: Unexpected response code: 500 (cluster has no CA bootstrapped yet), retry in 3m0s
```

These messages keep coming out. The proxy process will not bind to the local port yet and thus is unavailable. 

Then I curl the roots endpoint: `curl localhost:8500/v1/agent/connect/ca/roots` and then the proxy starts listening and connect generally starts working. It seems as if somehow the error status is being cached locally as the CA was "bootstrapped" (restored from a raft snapshot) when the cluster came up (about 13:30 in the logs). Then for 20 minutes I was seeing those error logs about it not being bootstrapped.

**Comment by mkeeler** [comment]
So I reproduced the proxy process not being started. The logs look like:

```
==> Found address '172.18.0.7' for interface 'eth0', setting bind option...
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.2.2-5-ge5b5995ad-dev (e5b5995ad+CHANGES)'
           Node ID: 'd4dfe5aa-0fb1-aab6-c0af-7462cd9a1b2d'
         Node name: 'consul-client3'
        Datacenter: 'dc1' (Segment: '')
            Server: false (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 172.18.0.7 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2018/07/30 18:17:19 [INFO] serf: EventMemberJoin: consul-client3 172.18.0.7
    2018/07/30 18:17:19 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)```

I added a few extra trace messages and those logs (interspersed with other logs) are:

```
2018/07/30 18:17:19 [INFO] serf: EventMemberJoin: consul-client3 172.18.0.7
2018/07/30 18:17:19 [DEBUG] agent: restored service definition "web-proxy" from "/consul/data/services/5c6e75c35549b0153623e105f7364d64"
2018/07/30 18:17:19 [DEBUG] agent: check "service:web-proxy" exists, not restoring from "/consul/data/checks/d260f5c06af1440218d8c46c39a262e5"
2018/07/30 18:17:19 [DEBUG] agent/proxy: managed Connect proxy manager started
2018/07/30 18:17:19 [TRACE] agent/proxy: reconciling proxy "web-proxy" with the state
2018/07/30 18:17:19 [TRACE] agent/proxy: proxy "web-proxy" exists in the local state
2018/07/30 18:17:19 [TRACE] agent/proxy: proxy "web-proxy" is consistent with the local state
2018/07/30 18:17:19 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
```

**Comment by mkeeler** [comment]
I think I got to the bottom of it.

https://github.com/hashicorp/consul/blob/master/agent/proxy/daemon.go#L430-L435

So we call findProcess which finds the process and checks if its alive.

https://github.com/hashicorp/consul/blob/master/agent/proxy/process_unix.go#L22-L28

So the check is to send signal 0 and make sure we don't error in sending the signal.

So what happens when you send signal 0 to a thread on linux. Answer: exactly the same as if you had sent it to the parent process. So in my case (consul in a container) what is happening is that when the container starts and consul comes up there are some number of threads the go runtime launches behind the scenes. Sometimes those threads have a pid that is the same as the previous proxy instance's pid so Consul thinks the process has started and wont start it again.

How do we fix this? The answer is its hard and platform specific. On linux we would need to read the command line arguments out of proc to ensure not only is the process alive but its running the correct program. On macos/freebsd there are other sysctl functions (this is with a C api) that can be used to query this information. On Windows its also entirely different. Solaris/OpenBSD who knows?

**Comment by banks** [comment]
Good catch Matt. 

We never really designed managed proxies to be run inside a container like this. While it's still possible this could happen on a non-containerised system, the fact that a full system boot typically starts orders of magnitudes more processes is likely to make it much less rare if it's even possible at all there.

That said, it's clearly not ideal - my assumption was that the process could be different but if it was running as a different users we'd likely not be allowed to send signal anyway which would protect somewhat from picking another process arbitrarily. I hadn't considered another thread in the agent's runtime could "steal" that pid though with the same user obviously.

We did consider other "safety" mechanisms for this - sending a signal like USR1 and requiring that proxies respond in a certain way with their ID say, but that would limit the use of managed proxies with third party binaries etc.

In general it seems our assumption that the process ID space is large and random enough to be a reasonable thing to do here is especially problematic in containers so we could look at an alternative.

Having a platform-agnostic way to fetch the actual process command information like you suggest may be the best option. We should consider this.

FWIW it's a somewhat known issue that this code won't work right on Windows already so we need to solve for cross-platform in general anyway.

**Comment by banks** [comment]
> One other potential alternative is to use file locking on the pid file.

It also only works for our own built-in proxy. Not being able to run any third party proxy as managed is not really going to work.

We _could_ build a execute wrapper that is directly started and then execs the actual proxy binary configured. We went back and forth on that during design - it has other benefits like standardisinng output logging more potentially if "our" code is on the proxy process side too even for external proxies but it's also a whole extra moving part to consider.

Given the unpleasant nature of this issue though, it might end up being the cleanest solution as we can then implement arbitrary IPC protocols and still be able to support any external proxy binary>

🤔

**Comment by banks** [comment]
We deprecated managed proxies in 1.3.0. See the [full rationale here](https://www.consul.io/docs/connect/proxies/managed-deprecated.html) but tl;dr is issues like this make them hugely complex for something we still don't think is wise to use in production.
