### ISSUE TITLE
ACL bootstrap not initialized

### ISSUE THREAD

**Issue by rudziankou** [hashicorp/consul#4467]
Hi folks,

I have 3 nodes Consul cluster running on the VM's as a service. I'm doing an application upgrade from 0.7.1 to 1.2.1. I moved Consul to Docker engine. When an upgrade is completed I'm trying to bootstrap ACL (ACL was disabled before). I'm executing the following command: 

`curl --request PUT 127.0.0.1:9500/v1/acl/bootstrap`

I'm expecting to receive a master token, but I received an error:

`rpc error making call: ACL bootstrap not initialized, need to force a leader election and ensure all Consul servers support this feature`

Existing Consul configuration:
> {
    "server": true,
    "datacenter": "dc01",
    "data_dir": "/opt/consul/data",
    "log_level": "INFO",
    "encrypt": "cg8StVXbQJ0gPvMd9o7yrg==",
    "enable_syslog": true,
    "ports": {
        "http": 9500,
        "dns": 9501,
        "serf_lan": 9502,
        "serf_wan": 9503
    },
    "client_addr": "0.0.0.0",
    "ui": false,
    "disable_update_check": true
}

New Consul configuration:
> {
    "bootstrap_expect": 3,
    "server": true,
    "disable_update_check": true,
    "ui": false,
    "datacenter": "dc01",
    "data_dir": "/opt/consul/data",
    "log_level": "INFO",
    "encrypt": "cg8StVXbQJ0gPvMd9o7yrg==",
    "ports": {
        "http": 9500,
        "dns": 9501,
        "serf_lan": 9502,
        "serf_wan": 9503
    },
    "client_addr": "0.0.0.0",
    "raft_protocol": 2,
    "performance": {
        "raft_multiplier": 1,
        "leave_drain_time": "20s",
        "rpc_hold_timeout": "20s"
    },
    "node_name": "consul01.somedomain.com",
    "advertise_addr": "10.44.70.125",
    "acl_datacenter": "dc01",
    "acl_default_policy":"allow",
    "retry_join": ["consul01", "consul02", "consul03"]
}

Could you please help me fix this issue?
Thanks!

**Comment by mkeeler** [comment]
@rudziankou What does the output of `consul operator raft list-peers` look like. You should see a one of the servers showing a state of "leader" and the other 2 having the state of "follower".

The error message you saw would indicate that your cluster hasn't chosen a leader yet and until that happens many things that use data stored in raft wont work (including ACL bootstrapping).

**Comment by rudziankou** [comment]
Before:
```
consul operator raft -list-peers -http-addr=127.0.0.1:9500

Node                 ID                 Address            State     Voter
consul01.domain.com  10.44.70.125:8300  10.44.70.125:8300  leader    true
consul02.domain.com  10.44.70.126:8300  10.44.70.126:8300  follower  true
consul03.domain.com  10.44.70.127:8300  10.44.70.127:8300  follower  true
```

After:
```
docker exec -it consul consul operator raft list-peers -http-addr=127.0.0.1:9500

Node                 ID                 Address            State     Voter  RaftProtocol
consul01.domain.com  10.44.70.125:8300  10.44.70.125:8300  follower  true   2
consul02.domain.com  10.44.70.126:8300  10.44.70.126:8300  leader    true   2
consul03.domain.com  10.44.70.127:8300  10.44.70.127:8300  follower  true   2
```

```

Exactly the same issue (I executed this command on each host):
curl --request PUT localhost:9500/v1/acl/bootstrap
rpc error making call: ACL bootstrap not initialized, need to force a leader election and ensure all Consul servers support this feature
```

**Comment by slackpad** [comment]
@rudziankou if during your upgrade one of the newer servers became leader before the 0.7.1 servers had left the cluster, then you would have seen [this message](https://github.com/hashicorp/consul/blob/master/agent/consul/leader.go#L352) in your logs, indicating that it couldn't set up ACL bootstrap yet.

Now that you've upgraded all the servers, if you restart your leader node to force an election it should be able to initialize ACL bootstrap. Consul does this check because the older servers won't understand the Raft command to set up ACL bootstrap, and will panic if they see it.

**Comment by rudziankou** [comment]
Thanks, @slackpad . Closing ticket.
