### ISSUE TITLE
cli: add command to restart all managed proxy processes

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#4481]
Currently managed Connect proxies are intentionally left running when the client agent exits to prevent service traffic being interrupted by agent upgrades or crashes.

In production, the expected way to stop a proxy is to deregister it's service and have the agent manage it for you.

It is sometimes required to force proxy's to upgrade however and manually finding their process ID and killing them to allow agent to restart is not a great UX to have to explain to people.

I propose something like:

```
$ consul connect restart-proxies
==> This will restart 3 managed proxies for "web", "db", and "cache" services. Clients of these services will see connections closed and they will be unavailable for a few seconds while they are restarted. Are you sure you want to proceed? (y/N)
==> Restarting pids 1234, 1235, 1236
==> Done, new pids: 2345, 2346, 2347
```

**Comment by pearkes** [comment]
We no longer manage proxies (deprecated) and will be removing that functionality in the future so going to close this.
