### ISSUE TITLE
Support "Authorization: Bearer <token>"

### ISSUE THREAD

**Issue by splashx** [hashicorp/consul#4483]
#### Feature Description

It would be great if consul could support `Authorization: Bearer <token>`. 

#### Use Case(s)

There are some tools which won't support custom headers (see https://github.com/prometheus/prometheus/issues/2346 and https://github.com/prometheus/prometheus/issues/1724).  

One should not expect the world would interface with Consul using a non-standard `X-Consul-Token` header. 

`Authorization: Bearer <token>` and `X-Consul-Token: <token>` could be interchangeable for long-lasting backwards compatibility.

**Comment by mkeeler** [comment]
@splashx This seems like a reasonable request. The Authorization header with the Bearer auth scheme seems to be an exact match for how the tokens are used. I am not sure when the team could get around to implementing it but we would be open to a PR for this.

**Comment by mbag** [comment]
@mkeeler :  @splashx and I worked on this. I've created PR #4502 with code we have prepareed. If there are some changes to be made, please let me know.

**Comment by shubheksha** [comment]
I'd be happy to take this up! Can y'all can give me some pointers regarding the implementation since I'm very new to the code base? 😄
