### ISSUE TITLE
Vsphere/Vmware and Consul cluster auto join

### ISSUE THREAD

**Issue by kereza** [hashicorp/consul#4486]
Hello,

I have already implemented Consul cluster in AWS with AutoJoin and EC2 tagging.

https://www.consul.io/docs/agent/cloud-auto-join.html

Now I am trying to do the same on a VMware/Vsphere environment. I have done everything as the tutorial describes, but the issue there is the TAGS. Seems that those tags which are generated from the UI are not the actual tags which Consul see. As far as I understood there are different tags which can only be applied via the REST API.

Has someone managed to make a consul cluster in Vsphere with auto-join function ? I have searched all over the internet for some user stories on this topic, but there is none.

Thank you in advance

**Comment by pearkes** [comment]
Hey @kereza! This is a new feature (added here: https://github.com/hashicorp/go-discover/pull/43) so I'm not sure there's much information about it online yet. It sounds like your guess is right and it may be a different type of tags.

We have end-to-end tests for go-discover that run successfully for vSphere. The cluster is created via Terraform, see here:

https://github.com/hashicorp/go-discover/blob/87161d12f3b7f7ebf17aedcbd493fefd2e419ea1/test/tf/vsphere/main.tf#L75-L87

This is configuration for the [`vsphere_tag`](https://www.terraform.io/docs/providers/vsphere/r/tag.html) resource in Terraform, which then references this vSphere documentation:

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.vcenterhost.doc/GUID-E8E854DD-AA97-4E0C-8419-CE84F93C4058.html

So maybe if you take a look there it'll point you in the right direction.

**Comment by kereza** [comment]
Thank you. The issue was on my side.  Too complicated password and it was not rendered correctly . Also the user which I have used did not have privileges to read the tags etc.
