### ISSUE TITLE
consul hangs when ran from a dev server and resumed on a new ip

### ISSUE THREAD

**Issue by eedwards-sk** [hashicorp/consul#4494]
#### Overview of the Issue

When starting up a consul service on a local dev machine after putting the machine to sleep and then waking it up on a new network IP, it never properly recovers.

Log gets spammed with 'error getting server health':

<details>
  <summary>log spam</summary>

    2018/08/06 17:06:53 [WARN] consul: error getting server health from "mac": rpc error getting client: failed to get conn: dial tcp <nil>->10.0.1.93:8300: i/o timeout
    2018/08/06 17:06:56 [WARN] consul: error getting server health from "mac": context deadline exceeded
    2018/08/06 17:06:57 [WARN] consul: error getting server health from "mac": last request still outstanding
    2018/08/06 17:06:59 [WARN] consul: error getting server health from "mac": last request still outstanding
    2018/08/06 17:07:01 [WARN] consul: error getting server health from "mac": last request still outstanding

</details>

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. create 1 local single node cluster (see plist)

<details>
  <summary>service plist</summary>

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>local.consul.agent.local</string>
    <key>ProgramArguments</key>
    <array>
        <string>/opt/consul/local/bin/consul</string>
        <string>agent</string>
        <string>-dev</string>
        <string>-bind</string>
        <string>0.0.0.0</string>
        <string>-client</string>
        <string>0.0.0.0</string>
        <string>-node</string>
        <string>mac</string>
        <string>-node-id</string>
        <string>c69d9705-76d9-4804-a2ed-d30b452b769d</string>
        <string>-datacenter</string>
        <string>local</string>
        <string>-dns-port</string>
        <string>8600</string>
        <string>-http-port</string>
        <string>8500</string>
        <string>-serf-lan-port</string>
        <string>8301</string>
        <string>-serf-wan-port</string>
        <string>8302</string>
        <string>-server-port</string>
        <string>8300</string>
    </array>
    <key>StandardOutPath</key>
    <string>/tmp/consul.agent.local.stdout</string>
    <key>StandardErrorPath</key>
    <string>/tmp/consul.agent.local.stderr</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>ThrottleInterval</key>
    <integer>30</integer>
</dict>
</plist>
```

</details>

2. put machine to sleep
3. wake machine up on another network
4. attempt to go to any hostname it should be serving

### Consul info for Client/Server

<details>
  <summary>Client/Server info</summary>

```
→ /opt/consul/local/bin/consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 3
build:
	prerelease =
	revision = e716d1b5
	version = 1.2.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.0.1.93:8300
	server = true
raft:
	applied_index = 1115
	commit_index = 1115
	fsm_pending = 0
	last_contact = 0
	last_log_index = 1115
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:c69d9705-76d9-4804-a2ed-d30b452b769d Address:10.0.1.93:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 72
	max_procs = 8
	os = darwin
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

OS X 10.13.6

### Log Fragments

See description

### Workaround

Stop and Start the Service

**Comment by pearkes** [comment]
This is surprising given you're running dev mode, which shouldn't persist anything.

However:

- You're setting a node ID, so perhaps it is persisting that and there isn't a graceful leave happening. I would remove the node ID if you don't need to set it for another reason.
- Often times this can happen on clients without leave_on_terminate set. https://www.consul.io/docs/agent/options.html#leave_on_terminate. This should make the client gracefully leave when shutting down. However, given it seems you're running a single node in dev mode this may not help.
- Finally, a question -- is there any reason you're running in `-dev` mode?

See also #1580.

**Comment by eedwards-sk** [comment]
@pearkes thanks for the response

Today I noticed from a `consul info` that even though supposedly the default for version `1.0.0` and up was `raft_protocol=3`, mine was running `2`, so I changed that in the args.

I'm also going to remove the explicit node id as per your instructions.

As per your question, this is in dev mode because it's part of a local ephemeral dev CI stack. I have an orchestration script which stands up consul and then registers host entries for the CI stack. It's idempotent, so it's designed to handle the consul server going away and coming back (thus in memory is fine so far).

**Comment by pearkes** [comment]
@eedwards-sk Got it. Let me know if those changes resolve your issue.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.

**Comment by eedwards-sk** [comment]
Hey @pearkes  sorry for the lack of updates. I did switch to raft protocol 3 and removed the node ID. I'm still experiencing the issue (just did right now, in fact). Seems to reproduce by putting the machine to sleep on one network and then waking it up on another (switching wifi, e.g. I went from 10.x network to a 192.168.x network).

```
    2018/08/21 21:32:29 [WARN] consul: error getting server health from "mac": last request still outstanding
    2018/08/21 21:32:32 [WARN] consul: error getting server health from "mac": context deadline exceeded
    2018/08/21 21:32:33 [WARN] consul: error getting server health from "mac": last request still outstanding
    2018/08/21 21:32:35 [WARN] consul: error getting server health from "mac": last request still outstanding
```

**Comment by ChipV223** [comment]
Hi @eedwards-sk !

Just wanted to check to see if this is still an issue? I've been playing around with this myself using a Windows 10 laptop(starting a dev server, putting the computer to sleep in my house wifi, and starting to the computer on a different wifi) and I've not been able to see the behavior

**Comment by eedwards-sk** [comment]
I haven't been using consul on different networks in a while, so I haven't had a chance to exercise a repro.

I'll close this for now and re-open if I manage to repro.
