### ISSUE TITLE
New UI - Tags under the nodes tab gets truncated

### ISSUE THREAD

**Issue by bhn26** [hashicorp/consul#4500]
**Old UI or New UI**
New UI

**Describe the problem you're having**
Tags aren't fully displayed in the new UI. If there are too many tags or the tags are too long, it'll get truncated at a point.

**Describe the solution you'd like**
Here's a picture of the current UI in a test cluster I spun up:

![screen shot 2018-08-07 at 4 37 09 pm](https://user-images.githubusercontent.com/14156744/43808113-45f51642-9a60-11e8-95c4-8d0d1482b703.png)

The truncated tag should be a full "asdfasdfasdf" like the previous three that are fully shown. However, it can't be seen or displayed.

I was hoping a solution to this could be that and tags that are to be truncated would simply be placed on a new line increasing the height of each row when needed to accommodate for the lack of space.

**Comment by johncowen** [comment]
Hi @bhn26 !

Thanks for the feedback! This is something the team has been discussing, so it's good to hear you'd like this to be improved (one of the options we've been looking at is exactly what you propose here 😄 )

In my mind, we need to ensure that if you use lots of tags, that your screen doesn't actually contain more tags than services (some people may end up with 3 or 4 lines of tags, meaning you might only be able to show say 5 services without having to scroll).

We have also been talking about an improved UI search experience using tags and other Consul features more, which could help here. Our initial release of the UI was aimed at replicating the old UI with a modern look and feel and providing a better 'base' to move forwards with, and we are at a stage now where we can really drill into making certain areas of the UI work better for our users, so hopefully you'll begin to see the result of this work soon.

One last thought, I know it's not ideally what you are after, but you can see all the tags for a service if you click into it from the Service Listing view. This currently takes you to a new/separate page, but there are more discussions ongoing about looking at making this easier so you don't have to click in and out and in and out to be able to see further details for a service/services. I think this would almost completely solve your request here (as well as solving it for people who uses lots and lots of tags).

Thanks again for your feedback, if you spot anything else which would help with your workflow, please keep an other ideas coming! I'll try and come back here and update you on further progress on this.

Thanks,
