### ISSUE TITLE
behavior of -config-file flag does not match usage statement

### ISSUE THREAD

**Issue by drawks** [hashicorp/consul#4506]
#### Overview of the Issue

The description of the `-config-file` flag in the consul command usage statement says:

>   -config-file=<value>
>    Path to a JSON file to read configuration from. Can be specified
>    multiple times.

However when providing the path to a valid json config file as the argument to the flag it will not be parsed as JSON unless the file has a `.json` extension.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a valid json config file named `consul.conf` such as
```{
  "datacenter": "east-aws",
  "data_dir": "/tmp/consul",
  "log_level": "INFO",
  "node_name": "foobar",
  "server": true,
  "bootstrap": true,
  "bootstrap_expect": 1,
  "advertise_addr": "{{ GetAllInterfaces | sort \"default\" | limit 1 | join \"address\" \" \" }}",
  "bind_addr": "0.0.0.0"
}
```
1. Run `consul agent -config-file=./consul.conf`
1. View error
```==> Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'.```
1. Rename config file to `consul.conf.json`
1. Run `consul agent -config-file=./consul.conf.json`
1. Consul parses the config and starts running

### Consul info for both Client and Server
```$ ./consul version
Consul v1.2.2
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

**Comment by drawks** [comment]
It seems like there are a few solutions here
1. Correct the usage statement to reflect that config file extension must match its format
2. Make `-config-format` default to json such that the behavior of the `config-file` flag matches the existing usage statement
3. Make the behavior ambiguous by detecting the file type at parse time and update the usage statement to reflect the same
4. Make the `-config-format` flag mandatory and don't bother with doing anything magical with the file extension

I think the first option is probably the most sane since it doesn't change the behavior of the tool.

**Comment by drawks** [comment]
`-config-dir` usage statement is similarly broken, if your config dir has `.hcl` files in it they are parsed and loaded even though the usage statement says that only `.json` files will be read:
``` -config-dir=<value>
     Path to a directory to read configuration files from. This
     will read every file ending in '.json' as configuration in this
     directory in alphabetical order. Can be specified multiple times.
```

**Comment by pearkes** [comment]
Thanks for the detailed notes on this @drawks. We came to similar conclusions in https://github.com/hashicorp/consul/issues/4477 starting from a different issue, but I just updated that to reference this as well and I'll close this as a duplicate to consolidate.
