### ISSUE TITLE
two servers connect together after two clients swapped serf lan ports used before restart

### ISSUE THREAD

**Issue by ao-song** [hashicorp/consul#4514]
#### Overview of the Issue

We have met a problem when doing something with Consul which seems still trying to connect the left node, as a consequence, two servers connect together after two clients swapped serf lan port used before restart.

Following please find the reproduction procedure.

#### Reproduction Steps

Consul version: 1.1.0

1. Start four Consul processes, two servers and two clients, **client A** connect **server A** with serf_lan set to *32035*, **client B** connect **server B** with serf_lan set to *32036*, **client A** and **client B** are on the same machine, they share the same IP;
2. Kill the two clients, make them left by using force-leave on servers;
3. Start one **new client A** connect **server A** with serf_lan set to *32036*, one **new client B** connect **server B** with serf_lan set to *32035*;
3. All four Consul processes connect together.

### Log Fragments
Please check the Consul member log below:

#### Server A:
**after force leave the client:**
Node                            Address                           Status  Type    Build  Protocol  DC    Segment
server-2008:e6f9:8210:9c40::2d  [2008:e6f9:8210:9c40::2d]:22501   alive   server  1.1.0  2         test<all>
client_9233_2961  [2008:e6f9:8292:72::72:63]:32035  left    client  0.8.5  2         test<default>

**after client port swapped:**
Node                             Address                           Status  Type    Build  Protocol  DC    Segment
server-2008:e6f9:8210:9c40::13   [2008:e6f9:8210:9c40::13]:22501   alive   server  1.1.0  2         test <all>
server-2008:e6f9:8210:9c40::2d   [2008:e6f9:8210:9c40::2d]:22501   alive   server  1.1.0  2         test <all>
client_14067_7908  [2008:e6f9:8292:72::72:63]:32036  alive   client  0.8.5  2         test <default>
client_9233_2961   [2008:e6f9:8292:72::72:63]:32035  left    client  0.8.5  2         test <default>
client_13842_2941  [2008:e6f9:8292:72::72:63]:32035  alive   client  0.8.5  2         test <default>

#### Server B:
**after force leave the client:**
Node                             Address                           Status  Type    Build  Protocol  DC    Segment
server-2008:e6f9:8210:9c40::13   [2008:e6f9:8210:9c40::13]:22501   alive   server  1.1.0  2         test <all>
client_9667_2182   [2008:e6f9:8292:72::72:63]:32036  left    client  0.8.5  2         test <default>

**after client port swapped:**
Node                             Address                           Status  Type    Build  Protocol  DC    Segment
server-2008:e6f9:8210:9c40::13   [2008:e6f9:8210:9c40::13]:22501   alive   server  1.1.0  2         test <all>
server-2008:e6f9:8210:9c40::2d   [2008:e6f9:8210:9c40::2d]:22501   alive   server  1.1.0  2         test <all>
client_14067_7908  [2008:e6f9:8292:72::72:63]:32036  alive   client  0.8.5  2         test <default>
client_13842_2941  [2008:e6f9:8292:72::72:63]:32035  alive   client  0.8.5  2         test <default>
client_9667_2182   [2008:e6f9:8292:72::72:63]:32036  left    client  0.8.5  2         test <default>

### Operating system and Environment details
Linux

**Comment by ao-song** [comment]
After some more tests, we have some new found which I think I need update here.

It seems the data-dir is reused when clients are restarted(**start consul with the same data-dir**). As there is some serf info stored there, I don't know if that will somehow make the new clients remember the previous connections and keep trying to re-connect the previous servers?

**Comment by pearkes** [comment]
Sorry I'm not totally clear on the issue here. It would help if you could let us know the expected behavior you wish to see here is.

**Comment by ao-song** [comment]
close issue as not valid anymore
