### ISSUE TITLE
Blocking query does not return an update

### ISSUE THREAD

**Issue by sangleganesh** [hashicorp/consul#4519]
the issue:
we use consul KV to store data and watch for updates to this data using blocking query (List).
in the following scenario the List does not return an update for the key that is updated

lets say the following code does update and delete
```
// update and then delete the key
client.KV().Put(key, ...)
pair, .. := consulApi.Get(key) // Assume pair.ModifyIndex=100 
client.KV().Delete(key, nil)
```

another go routine has a blocking List() call

```
for {
        // Make a blocking List query
        kvPairs, meta, err := client.List(prefix, opts)
        ...
}
```

From what we have seen, the List unblocks sometimes returning the key-value pair with ModifyIndex 100 and sometimes it does not show up at all.

As far as I understand, consul does not guarantee individual updates, so does this mean that because the key is deleted there is always a possibility that the last update to the key may not show up in List() ?

**Comment by kyhavlov** [comment]
There's no guarantee that you'll get any intermediate updates returned by the blocking query, no. You can only count on the query returning the most recent state whenever there's an update - if multiple updates happen while the query is returning then they can be missed.

**Comment by pearkes** [comment]
This was addressed in @kyhavlov's response above.
