### ISSUE TITLE
Can't set advertise port either in command line or config file

### ISSUE THREAD

**Issue by applee** [hashicorp/consul#4534]
#### Overview of the Issue

I'm running a consul agent with old version **0.9.3** in a docker container, for I‘m not the owner of host machine and can't run consul agent on it. It goes well with the config below.
```
    "advertise_addrs": {
       "serf_lan": "10.16.136.186:31234",
       "serf_wan": "10.16.136.186:31235"
    },
    ...
```
The IP 10.16.136.186 is the host machine IP address, and 31234/31235 are ports on host machine mapping to container 8301/8302. Everything goes well with version 0.9.3 for some mouths until I plan to upgrade consul version to **1.2.x**. Now I found some config changed, I can only set advertise address without port. consul members as below:

` 10.16.136.186:8301   failed   client  1.2.2`

We can see it using the default serf lan port 8301, then it can't go well.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease = 
        revision = e716d1b5
        version = 1.2.2
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

**Comment by banks** [comment]
Hi,

`advertise_addrs` was removed entirely in 1.0 along with a few other well-documented breaking changes: https://www.consul.io/docs/upgrade-specific.html#advertise_addrs-removed

Now ports are configured separately from listen addresses. See docs for `addresses` config:

> For TCP addresses, the variable values should be an IP address with the port. For example: 10.0.0.1:8500 and not 10.0.0.1. However, ports are set separately in the ports structure when defining them in a configuration file. 
https://www.consul.io/docs/agent/options.html#addresses

I think the valid configuration would be:

```
"advertise_addr": "10.16.136.186",
"ports": {
  "serf_lan": 31234,
  "serf_wan": 31235
}
```

Hope this helps!

**Comment by applee** [comment]
@banks Thanks a lot, btw I also need set `retry_join` or `start_join` with explicit port 8301, otherwise the consul agent connect the server with the `ports` above and failed to start.
