### ISSUE TITLE
Why are configuration file checks not supported?

### ISSUE THREAD

**Issue by klj890** [hashicorp/consul#4544]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Hi，We need a command to check for configuration file errors.
Every time I perform reload, the error messages are too crude.
I have to find out where I made a mistake, maybe just missing an "s".

**Comment by pierresouchay** [comment]
You mean like `consul validate` ?

Can you give an example of the current error message and what you would like to see?

**Comment by klj890** [comment]
Yes,this is i need!
thank you @pierresouchay
