### ISSUE TITLE
Multiple Connectivity Issue Between Consul Servers

### ISSUE THREAD

**Issue by orarnon** [hashicorp/consul#4545]
#### Overview of the Issue

Connectivity issues between Consul servers.

### Consul info for both Client and Server
<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 3
	checks = 3
	services = 4
build:
	prerelease =
	revision = 39f93f01
	version = 1.2.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.200.4.70:8300
	server = true
raft:
	applied_index = 386883295
	commit_index = 386883295
	fsm_pending = 0
	last_contact = 0
	last_log_index = 386883295
	last_log_term = 68372
	last_snapshot_index = 386876788
	last_snapshot_term = 68372
	latest_configuration = [{Suffrage:Voter ID:673e0ff3-815a-4c56-0b5b-1ccf17d7a7d1 Address:10.200.1.154:8300} {Suffrage:Voter ID:082aa7eb-3692-0d7b-b4fe-7efd1ab5b42e Address:10.200.4.70:8300} {Suffrage:Voter ID:1b0d7168-4d6c-0b73-b8e9-c805223a6428 Address:10.200.10.157:8300}]
	latest_configuration_index = 386838514
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 68372
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 15751
	max_procs = 4
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 4204
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 19
	member_time = 1549445
	members = 1116
	query_queue = 0
	query_time = 245
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3408
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Ubuntu 14.04.5 LTS
AWS server of c5d.2xlarge type.

<details>
  <summary>Consul Config</summary>

```
{
  "performance": {
    "raft_multiplier": 1,
    "leave_drain_time":"15s",
    "rpc_hold_timeout":"20s"
  },
  "addresses": {
    "dns": "127.0.0.1",
    "http": "0.0.0.0"
  },
  "dns_config": {
    "node_ttl": "1s",
    "service_ttl": {
      "*": "1s"
    },
    "allow_stale": true,
    "max_stale": "5s"
  },
  "discovery_max_stale": "30s",
  "telemetry": {
    "dogstatsd_addr": "127.0.0.1:8125",
    "dogstatsd_tags": [ "datacenter:us-east-1" ]
  },
  "rejoin_after_leave": true,
  "domain": "consul.",
  "log_level": "warn",
  "enable_syslog": false,
  "syslog_facility": "LOCAL3",
  "leave_on_terminate": true,
  "skip_leave_on_interrupt": false,
  "disable_remote_exec": false,
  "check_update_interval": "5m",
  "enable_debug": false,
  "data_dir": "/var/lib/consul",
  "server": true,
  "bootstrap_expect": 3,
  "retry_join": [
    "consul1.sonic-us.us-east-1",
    "consul2.sonic-us.us-east-1",
    "consul3.sonic-us.us-east-1"
  ],
  "ui": true,
  "client_addr": "127.0.0.1",
  "bind_addr": "{{ GetInterfaceIP \"eth0\" }}",
  "datacenter": "sonic-us_us-east-1",
  "node_name": "consul2.sonic-us.us-east-1",
  "ports": {
    "dns": 8600,
    "http": 8500,
    "serf_lan": 8301,
    "serf_wan": 8302,
    "server": 8300
  },
}
```

</details>
### Log Fragments

2018/08/20 13:27:23 [DEBUG] manager: pinging server "consul3.sonic-us.us-east-1.sonic-us_us-east-1 (Addr: tcp/35.172.200.121:8300) (DC: sonic-us_us-east-1)" failed: rpc error getting client: failed to get conn: dial tcp 10.200.4.70:0-><**PUBLIC_IP**>:8300: i/o timeout
2018/08/20 13:27:23 [DEBUG] manager: No healthy servers during rebalance, aborting
2018/08/20 13:27:29 [ERR] memberlist: Push/Pull with consul3.sonic-us.us-east-1.sonic-us_us-east-1 failed: dial tcp <**PUBLIC_IP**>:8302: i/o

**Comment by orarnon** [comment]
Might be related to: 
https://github.com/hashicorp/consul/issues/4066

Essentially, we use: "bind_addr": "0.0.0.0" which suppose to bind to the first private IP (which it does). However, it seems that wan_serf communication is occurring on the public IP which is inaccessible.

**Comment by pearkes** [comment]
> However, it seems that wan_serf communication is occurring on the public IP which is inaccessible.

This is expected behavior. If you join multiple clusters over WAN the servers need to be able to communicate over the `serf_wan` port. If you ensure there is connectivity between those hosts at that port you shouldn't see these messages! Hope that helps.

**Comment by orarnon** [comment]
Hi @pearkes , 
We seem to be miscommunicating. 
I have a 3 node cluster in the same datacenter which communicates of LAN and CANNOT communicate over public IP. Following Consul's documentation and other issues, I've configured the cluster to bind to eth0 (my internal IP in AWS) with no other configurations. Which means, that serf_wan should have been bound to the same interface on which the serf_wan port is open.

**Comment by ne0guille** [comment]
Hi @orarnon ,  @pearkes  any recommendation on how to solve this?
ive got the same message but with 8301 port, ive enabled consul connect
```ERROR] agent.client.memberlist.lan: memberlist: Push/Pull with node_name failed: dial tcp public_ip:8301: connect: no route to host```
