### ISSUE TITLE
Logging to file on Windows

### ISSUE THREAD

**Issue by Gianlu** [hashicorp/consul#4555]
#### Feature Description

Logging to file on Windows

#### Use Case(s)

Hi,
in latest release, consul can be installed as Windows service and this is a very nice feature. But when I ran consul via nssm, I could redirect console output to a file in order to have a log file.
Could you introduce a log file directive (if you prefer, only for windows) like `--syslog` for *nix systems?
Something like `--logfile "C:\hashicorp\consul\logs\log.log"` (or `--logfile "C:\hashicorp\consul\logs\log-{date}.log"`)

Thank you!

**Comment by MagnumOpus21** [comment]
Hello, @Gianlu . Can you try this as a temporary solution? 
`consul monitor -log-level=trace > path-to-logfile` from the command line or powershell, after you have launched Consul as a Windows service.
