### ISSUE TITLE
Can I disable agent api?

### ISSUE THREAD

**Issue by myokoo** [hashicorp/consul#4557]
Hi there.

at v1.0.1. 
By writing the following setting to default.json. Consul agent can disabled agent api. 

```json
"ports": {
    "http": -1
}
```

but v1.2.1. 
Consul agent can't disable agent api.

```bash
$ /usr/local/bin/consul agent -config-dir=/etc/consul.d
WARNING: LAN keyring exists but -encrypt given, using keyring
==> Starting Consul agent...
==> Error starting agent: No suitable client address can be found
```

It seems that https://github.com/hashicorp/consul/commit/3b6eef8ec698a4a249bb5d02196e6d49b299e63d is affected.

Do I have to run the API?
if agent api can disable. please tel me.

Thanks!

**Comment by mkeeler** [comment]
@myokoo thanks for the report. This is a regression and will get fixed soon. You will be able to disable the http api but not if enabling connect.

**Comment by myokoo** [comment]
Thank you for your teachings.
I am looking forward to updating the version.
