### ISSUE TITLE
Feature Request: always-on "code toggle"

### ISSUE THREAD

**Issue by adamkdean** [hashicorp/consul#4558]
#### Feature Description

It would be great if the UI "code toggle" could be always-on by default. Alternatively, this could be a sticky setting per KV pair. 

#### Use Case(s)

I often find myself making changes, then re-opening a KV pair and re-toggling on the code view.

Associated (UX improvements): https://github.com/hashicorp/consul/issues/4559
Associated (UX improvements): https://github.com/hashicorp/consul/issues/4560

**Comment by johncowen** [comment]
Hi @adamkdean ,

Good to know you'd prefer this. This is actually on our roadmap, and should hopefully be coming soon.

Will try to update you here when it lands.

Thanks
