### ISSUE TITLE
Feature Request: light theme code view

### ISSUE THREAD

**Issue by adamkdean** [hashicorp/consul#4559]
#### Feature Description

It would be great if the UI code view matched the rest of the theme. The current dark code feels at odds with the beautiful new UI.

#### Use Case(s)

I often find myself looking at the black code view, and then having JSON imprinted in my vision, which disturbs me on a spiritual and emotional level.

Associated (UX improvements): https://github.com/hashicorp/consul/issues/4558
Associated (UX improvements): https://github.com/hashicorp/consul/issues/4560

**Comment by johncowen** [comment]
Hi @adamkdean ,

This is something we've also been chatting about 😀 

Again, I'll try to keep you updated here once this lands.

Thanks,

**Comment by opihana** [comment]
Hi @adamkdean, thanks for sharing your use case. I thoroughly appreciate the description. 😄  I'd love to share some new styles we're playing with. We're hoping to be able to offer a user setting for dark or light code editors in the future, with the light as the default.

![screen shot 2018-08-27 at 3 47 33 pm](https://user-images.githubusercontent.com/6323933/44685208-8907f980-aa10-11e8-8f6e-0f6083ba485c.png)

Specifically, I'd love to hear your feedback on text colors. What would you expect to see? The ones shown here would be for Terraform, hence the purple from Terraform's brand colors.
