### ISSUE TITLE
Feature Request: save and continue editting

### ISSUE THREAD

**Issue by adamkdean** [hashicorp/consul#4560]
#### Feature Description

It would be great if the UI allowed you to save a KV pair and continue editing.

#### Use Case(s)

I often find myself making changes and having to re-open KV pairs. Over the past month I've probably done this close to 140,000 times, give or take 10,000.

Associated (UX improvements): https://github.com/hashicorp/consul/issues/4558
Associated (UX improvements): https://github.com/hashicorp/consul/issues/4559

**Comment by johncowen** [comment]
Hey @adamkdean ,

Definitely a good suggestion! This is something we haven't specifically spoken about, but we do have something larger on the roadmap that should solve this for you. Will keep you updated here.

BTW, just to try to give you further info, all of these issues you submitted today should be on a 'near term' roadmap.

Thanks,

**Comment by adamkdean** [comment]
That's great. I knew if I went for a bunch of recommendations I'd hit at least one thing you probably haven't already got on your list. I look forward to the big reveal and all the pending improvements.

Keep up the good work.

💯
