### ISSUE TITLE
ui-v2: TextEncoder undefined

### ISSUE THREAD

**Issue by tobiaskohlbau** [hashicorp/consul#4570]
#### Overview of the Issue

When using Microsoft Edge (latest version) no textboxes are rendered with values. The log shows `SCRIPT5009: 'TextDecoder' is not defined`. Looks like the polyfill which is used [here](https://github.com/hashicorp/consul/blob/a00a2dc1480bff44ae77e4e2d2000b7b8f40e593/ui-v2/app/utils/atob.js#L7) does not work properly.
```
return new (TextDecoder || TextEncoderLite)(encoding).decode(bytes);
```

Edit:
Maybe I should express that with textboxes I mean boxes for changing the values (of a key). 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Deploy consul service
2. Browse Key within KV.
3. Present value is not rendered

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
Web-UI
```

</details>

<details>
  <summary>Server info</summary>

```

agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = e716d1b5
        version = 1.2.2
consul:
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 192.168.12.200:8300
        server = true
raft:
        applied_index = 378021
        commit_index = 378021
        fsm_pending = 0
        last_contact = 0
        last_log_index = 378021
        last_log_term = 10
        last_snapshot_index = 376895
        last_snapshot_term = 10
        latest_configuration = [{Suffrage:Voter ID:27b5a34f-cd40-4bbd-7f46-4926a538309b Address:192.168.12.200:8300} {Suffrage:Voter ID:b0bbdf58-caeb-0232-2c65-8bf2538d1672 Address:192.168.12.220:8300} {Suffrage:Voter ID:d1a3b415-71ff-037d-c655-721f9ebf3a1e Address:192.168.12.210:8300}]
        latest_configuration_index = 174
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 10
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 105
        max_procs = 2
        os = linux
        version = go1.10.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 7
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 3
        members = 3
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 6
        members = 3
        query_queue = 0
        query_time = 1

```

</details>

### Operating system and Environment details

Linux(Server), Windows 10 Edge (Client)
Default environment.

### Log Fragments

```
SCRIPT5009: 'TextDecoder' is not defined
```

**Comment by johncowen** [comment]
Hi @tobiaskohlbau ,

Apologies for the delay in coming back to you! Firstly thanks for submitting the bug report! Secondly I've added a fix that addresses this in Edge, and therefore it should be in our next release once the above PR is merged.

Thanks again!

John

**Comment by tobiaskohlbau** [comment]
Hi @johncowen ,

thanks for the reply and the bugfix. Looking forward to the next release :-)
