### ISSUE TITLE
Is it still possible to tell other agent to connect me with a different port?

### ISSUE THREAD

**Issue by EMayej** [hashicorp/consul#4571]
Hi guys
Does anyone know how to write my configuration to tell other agent to reach me at port 1234 while I actually binds my port on 8301? 

Some of my agents need to be run inside docker containers, but docker assigns dynamic host port to me. For instance, my agent uses port 8301 inside the container but the host port docker gives me is 1234, so external machines should visit 1234 to reach this agent.

However, my agent told other agent that it is running on port 8301, but that port is hidden by docker, other agent couldn't see it.

The `.ports.serf_lan` doesn't help here. If I set that to 1234, other agents know they should send message to host port 1234 but docker still forwards traffic from host port 1234 to container port 8301. My agent binds it self on 1234(container port) thus it won't receive any message.

I can't create a host port upfront because my environment only assign a dynamic host port when creating my container.

**Is it still possible(like in 0.9) to tell other agent that they should reach me at port 1234(host port) while I bind my port on 8301(inside docker container)?**

**Comment by pearkes** [comment]
Hey @EMayej, I think this should be answered in our [Consul with Containers](https://www.consul.io/docs/guides/consul-containers.html#networking) guide in the networking section.
