### ISSUE TITLE
Key action buttons are not present in the web UI when the key value is empty

### ISSUE THREAD

**Issue by giladsh1** [hashicorp/consul#4589]
#### Overview of the Issue

When creating an empty key in the UI, the "Save", "Cancel changes" and "Delete"  do not appear in the UI.

#### Reproduction Steps

Steps to reproduce this issue:
1. create an empty key
2. in UI, click the key name in order to view it's value - the buttons do not show.

valid state (the key has " " as value) - 

![image](https://user-images.githubusercontent.com/11939618/44643247-7d004580-a9d8-11e8-877c-8751a068bf29.png)

invalid state (the key is empty) - 
![image](https://user-images.githubusercontent.com/11939618/44643265-90abac00-a9d8-11e8-808d-63d839583f12.png)

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 4
	services = 0
build:
	prerelease = 
	revision = 28141971
	version = 1.2.0
consul:
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = 10.224.9.55:8300
	server = true
raft:
	applied_index = 1009977
	commit_index = 1009977
	fsm_pending = 0
	last_contact = 54.427859ms
	last_log_index = 1009977
	last_log_term = 4
	last_snapshot_index = 1001143
	last_snapshot_term = 4
	latest_configuration = [{Suffrage:Voter ID:229cbf97-30ba-1e53-e02c-ccb3eeb46f28 Address:10.224.9.55:8300} {Suffrage:Voter ID:94cb10fb-3d55-f62a-3881-4743cdc4f300 Address:10.225.20.171:8300} {Suffrage:Voter ID:1822c202-23e1-b611-c72e-ff117ad70613 Address:10.226.20.21:8300}]
	latest_configuration_index = 766726
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 4
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 6672
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 256
	member_time = 4183
	members = 464
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2172
	members = 6
	query_queue = 0
	query_time = 1

```

</details>

#### Operating system and Environment details

server running on CentOS Linux release 7.4.1708 (Core)

**Comment by johncowen** [comment]
Hi @giladsh1 !

I have a sneaky feeling this is the same as https://github.com/hashicorp/consul/issues/4336 which is now fixed in the latest version. It looks like you are running 1.2.0, are you able to upgrade to 1.2.2? If so could you try and confirm for me whether this has solved your issue?

Thanks,

**Comment by giladsh1** [comment]
indeed - version 1.2.2 fixes this issue
