### ISSUE TITLE
Cannot able to access the key value tab in the consul ui

### ISSUE THREAD

**Issue by malsimi** [hashicorp/consul#4607]

**Comment by johncowen** [comment]
Hi @malsimi 

Thanks for submitting an issue! Do you have any more information such as what version of the Consul UI you are running. Could you provide a screengrab of what you are seeing when you try to access the Key Value tab?

Thanks,

John

**Comment by johncowen** [comment]
Hi @malsimi ,

We aren't quite sure what you are referring to here, so we are going to close this issue for the moment. Please feel free to open with more information if you continue to see the issue.

Thanks,
