### ISSUE TITLE
HTTP Generic metrics using labels

### ISSUE THREAD

**Issue by uepoch** [hashicorp/consul#4611]
#### Feature Description

Use better labeling for http generic metrics
Method and endpoint should be in a specific label
This will avoid weirdly named metrics like `consul_http_PUT_v1_kv___`

#### Use Case(s)

Some metrics sink already support labeling (prometheus, dogstatsd(not sure, for this one),..) and anybody using aggregations/alerting based on theses metrics would have an easier time treating this data with a generic querying function instead of having to template lots of configuration to handle all endpoints

Personal point: I also believe suffixing '_' to identify an endpoint containing a pattern is counter-intuitive

I understand that this will break naming contract already used by clients

My colleague Pierre made #4042 to enhance another set of labels, and I was thinking about using a similar, if not the same enabling config-flag

What do you think ?

**Comment by mkcp** [comment]
This will be solved by #8271

**Comment by mkcp** [comment]
This will be resolved in 1.9
