### ISSUE TITLE
separator query parameter is ignored by kv api

### ISSUE THREAD

**Issue by edio** [hashicorp/consul#4634]
#### Overview of the Issue

KV api documentation 

#### Reproduction Steps

1. start new agent in dev mode
2. store value in KV
```
$ curl -X PUT localhost:8500/v1/kv/foo/bar -d "1"
true
```
3. read value without `separator` parameter
```
$ curl localhost:8500/v1/kv/foo/bar
[
    {
        "LockIndex": 0,
        "Key": "foo/bar",
        "Flags": 0,
        "Value": "MQ==",
        "CreateIndex": 8,
        "ModifyIndex": 8
    }
]
```
**4. read value with `separator` parameter**
```
$ curl -i localhost:8500/v1/kv/fooXXXbar\?separator=XXX
HTTP/1.1 404 Not Found
X-Consul-Index: 8
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Wed, 05 Sep 2018 18:41:03 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```
**5. read recursively with `separator` parameter**
```
$ curl localhost:8500/v1/kv/foo\?separator=XXX\&recurse=true
[
    {
        "LockIndex": 0,
        "Key": "foo/bar",
        "Flags": 0,
        "Value": "MQ==",
        "CreateIndex": 8,
        "ModifyIndex": 8
    }
]
```

I expected at least one of the following
* 4th step succeeds and returns value of key `foo/bar`
* 5th step returns `"Key": "fooXXXbar"`

**Comment by pearkes** [comment]
Given you're creating a key with a separator `/`, you can't then read it with a separator `XXX`. I believe if you change step one to write the key `fooXXXbar` the rest of the steps should work. Does that make sense?

**Comment by pearkes** [comment]
> what is the role of separator query parameter?

It basically just "splits" the key on that string. There's not a notion of hierarchy in how the data is stored.

> would foo still be a parent of bar? Would fooXXXbar be returned if I make a call foo?recurse&separator=XXX?

Yeah if you call foo with recurse, it will recurse through each matching part of the key separated by the provided string.

Hope that helps and sorry for the late response!
