### ISSUE TITLE
500 (The backend responded with an error)

### ISSUE THREAD

**Issue by vTNT** [hashicorp/consul#4641]
#### Overview of the Issue

when i run this command: consul join -wan xx.xx.xx.xx, it show that this ip can join successful. but when i want switch to this node,  i can see some error from consul ui;
500 (The backend responded with an error)
Consul returned an error. You may have visited a URL that is loading an unknown resource, so you can try going back to the root. If your ACL token was not found you can reset it, and then you will be redirected to the settings page to enter a new ACL token. Try looking in our documentation

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl ...`
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

VERSION: consul 2.2

**Comment by csayler** [comment]
what was fix?

**Comment by ravi-mrk** [comment]
Any fix or workaround for this? I see the same issue.

**Comment by mkeeler** [comment]
What is meant by "when I want switch to this node, I can see some error from consul ui".

Specifically do you mean that in the Consul UI your are switching datacenters to look at the datacenter of the node you just wan joined?

What versions of Consul are running across all the nodes. The servers are *all* going to need to be at least the version of whatever node is running the UI.

**Comment by lhalcyon** [comment]
fix? I see the same issue . when I use rancher to deploy consul

**Comment by brandonAIQ** [comment]
Also seeing this issue. Version (1.5.2) on all clients and servers.

> Specifically do you mean that in the Consul UI your are switching datacenters to look at the datacenter of the node you just wan joined?

Yes, that's when the issue comes up for me! Would like at least more info as to where to look to see what's going wrong. Might it have to do with ACLs or security groups?

**Comment by mkeeler** [comment]
If it were ACL related you would be seeing a 403. 

To troubleshoot I would recommend running `consul monitor -log-level debug` on the node running the consul ui. Those 500 response stem from some RPC error and the logs should provide more info.

**Comment by brandonAIQ** [comment]
Was indeed security groups! Needed to make sure all-traffic ingress was allowed from the new server node into the old one, then restarted with `consul reload`.

FYI to anyone else who finds themselves in this thread, good place to check ☝️
