### ISSUE TITLE
consul lock does not propagate the SIGTERM to the child process. 

### ISSUE THREAD

**Issue by skyrocknroll** [hashicorp/consul#4643]
#### Overview of the Issue

`consul lock` is not propagating the `SIGTERM` to the child process. 
#### Reproduction Steps

Steps to reproduce this issue, eg:

1. start a process with consul lock 
2.  find the consul PID and send SIGTERM
3. Consul does not send the SIGTERM signal to the child process.  

#### Version
consul : v 1.2.2
os : ubuntu
os version : 16.04
architecture: 64 bit

**Comment by freddygv** [comment]
@skyrocknroll I'm having trouble reproducing this in 1.2.2 and ubuntu 16.04

Here are the steps I am taking:
1. Run Consul agent: `consul agent -dev`
2. Start long sleep process with Consul lock: `consul lock service/sleep sleep 10m`
3. Send SIGTERM to PID for CMD: `consul agent -dev`

Consul agent then shuts down, and the sleep process exits shortly thereafter with:
`Error running handler: signal: terminated`

The SIGTERM signal does appear to be propagated to the child process.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.

**Comment by rboyer** [comment]
For the record this was fixed by: https://github.com/hashicorp/consul/pull/4737
