### ISSUE TITLE
Not able to grab consul 0.5.2 from links

### ISSUE THREAD

**Issue by brianpham** [hashicorp/consul#4654]
#### Overview of the Issue

Not able to wget the following files anymore

https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
https://dl.bintray.com/mitchellh/consul/0.5.2_web_ui.zip

#### Reproduction Steps

wget https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
wget https://dl.bintray.com/mitchellh/consul/0.5.2_web_ui.zip

**Comment by pearkes** [comment]
@brianpham Sadly since moving off of it we can't guarantee access to bintray access anymore. We recommend using releases.hashicorp.com. All versions are mirrored there.

https://releases.hashicorp.com/consul/0.5.2/

If you're seeing us link to bintray somewhere let us know and we'll correct that!
