### ISSUE TITLE
Add Metric with Version Information

### ISSUE THREAD

**Issue by jdfalk** [hashicorp/consul#4659]
#### Feature Description

Add a metric that dumps the current status of the `consul version` command. Even better would be the data from `consul info`.

#### Use Case(s)

This would allow us to quickly query this information in Prometheus/Grafana to ensure that we are running the latest versions of the consul agent. If we aren't it means that our system configuration software is having issues and so it's an easy check against both.

**Comment by pearkes** [comment]
Thanks for the suggestion! How do you envision the format of a value for a metric like this? We don't have much precedent for something like it.

One workaround would be to consume the HTTP API [`/v1/agent/self`](https://www.consul.io/api/agent.html#read-configuration) endpoint that can provide the version per agent and you can then format / output it as you see fit.

**Comment by jdfalk** [comment]
If you look at the mysql exporter they support version info by setting a few labels with the data on the metric mysql_version_info.

```
innodb_version="5.7.21-21"
version="5.7.21-21", 
version_comment="Percona Server (GPL), Release 21, Revision 2a37e4e"
```
