### ISSUE TITLE
KV and catalog are not available on the part of clients when one of the consul server crashes

### ISSUE THREAD

**Issue by jack-walters** [hashicorp/consul#4664]
#### Overview of the Issue

KV and catalog are not available on the part of clients when one of the consul server crashes (power failure, system panic, etc)

#### Reproduction Steps
On some of client hosts (service-1.priv for example), which running consul in NO server mode run command that write data to KV:
` while :; do curl  -X PUT -d 'some data'  http://localhost:8500/v1/kv/test/key1 ; sleep 1; echo -e "\n$(date)"; done`

Then check with which consul server service-1.priv has  RPC connect:
`netstat -tpan | grep ESTABLISHED | grep :8300 `
_tcp        0      0 service-1.priv:42824        consul-server-2.priv:8300 ESTABLISHED 817/consul_ 

In my case it's  consul-server-2.priv.
Than kill host consul-server-2 by power or block traffic by firewall to reproduce server crash.
We will see next situation with writing data to KV on the service-1.priv host - 20 seconds we can't write data:
` while :; do curl  -X PUT -d 'some data'  http://localhost:8500/v1/kv/test/key1 ; sleep 1; echo -e "\n$(date)"; done`
....
_true
Wed Sep 12 21:20:30 UTC 2018
true
rpc error making call: EOF
Wed Sep 12 21:20:51 UTC 2018
true
Wed Sep 12 21:20:52 UTC 2018
..._

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease = 
	revision = 5174058f
	version = 1.1.0
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 75
	max_procs = 1
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 97
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 680
	members = 25
	query_queue = 0
	query_time = 7

```

</details>

<details>
  <summary>Server info</summary>

```
[root@vss-rel-consul-3.am /]# consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 5174058f
	version = 1.1.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.2.1.244:8300
	server = true
raft:
	applied_index = 279861908
	commit_index = 279861908
	fsm_pending = 0
	last_contact = 38.791456ms
	last_log_index = 279861908
	last_log_term = 254887
	last_snapshot_index = 279849854
	last_snapshot_term = 254887
	latest_configuration = [{Suffrage:Voter ID:021a3503-35d1-888f-0ecd-f77ee59172d9 Address:10.2.1.244:8300} {Suffrage:Voter ID:8b66e573-823d-a6d5-4284-ebb24d4673da Address:10.2.1.245:8300} {Suffrage:Voter ID:939d7067-814b-4f46-c7ab-655921d8488c Address:10.2.1.243:8300}]
	latest_configuration_index = 279283538
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 254887
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 176
	max_procs = 1
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 97
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 680
	members = 25
	query_queue = 0
	query_time = 7
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 116
	members = 3
	query_queue = 0
	query_time = 1

```

</details>

### Operating system and Environment details
CentOS Linux release 7.4.1708 x86_64

**Comment by pearkes** [comment]
@jack-walters this is expected behavior (though the timing does feel off -- I believe this should happen faster than it did in your example based on the timeouts configured by default). The leader election will cause consistent reads (default) to fail until a new leader is elected.

You could optionally add the [stale parameter](https://www.consul.io/api/index.html#stale) to read from any Consul server available, which is a trade-off but may fit your use-case.
