### ISSUE TITLE
Check script do not pass any host environment variable to subprocess.

### ISSUE THREAD

**Issue by Xeite** [hashicorp/consul#4667]
#### Overview of the Issue

Check script (CheckMonitor in code) do not pass any host environment variable to subprocess. It make locale issue when using python3 script with click library.

At a glance, I thought it's related to library that I used. But after I investigate consul checks.go, it seems root cause is that Consul check does not pass any os.environ to subcommand.

I could not assure it's intentional because watch script do pass default os.environ to subcommand. Anyway, it make abnormal behavior that user could not understand and I think It's better to fix following watch command behavior to reduce API inconsistency.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Make check script like 'python3 script.py'
2. script.py has python click library
3. click library could not be executed since internally it depends on locale environment(LC_ALL, LANG).

**Comment by pearkes** [comment]
Unless I misunderstand you should be able to prefix environment variables in the arguments of the [check definition](https://www.consul.io/docs/agent/checks.html#check-definition). Hope that helps!
