### ISSUE TITLE
Embedded use of the Agent

### ISSUE THREAD

**Issue by xla** [hashicorp/consul#467]
This issue wants to explore the viability of the Agent functionalities used as a library in a new binary by using it as a golang pkg. For some context we (SoundCloud) are currently rebuilding our Service Discovery and have already well established dimensions in our SD schemas. In order to keep those stable we have to wrap consul in one way or another. As we are convinced that the general consul architecture is the way to go forward we like to want to deploy an agent per host. Our own Agent would have an HTTP as well as a DNS interface enforcing our dimensions and translate those into Consul services with appropriate set of tags.

The idea being instead of having our agent and the Consul agent running side-by-side on each host we want to wrap the Agent codebase to let our agent act as a participant in the gossiping, forward requests, etc. How viable is such approach in terms of:
- readiness of the Agent code to be used as library
- security implications
- other showstoppers

Happy to discuss and/or contribute in order to make this possible.

---

/cc @grobie @peterbourgon

**Comment by sdeoras** [comment]
Hi folks, I arrived at this thread trying to understand how best to integrate our code at [Portworx](https://portworx.com/)  with consul client for managing consul server failover scenario. I read earlier in this post that the recommended way is to use consul binary running as a client. We will certainly look into managing another process but prefer not to have such a dependency. We are wondering about benefits of using consul client as opposed to working with server end points directly. Most ideal for us would be to use consul client as a library, however, if that is not possible, what would we be missing by trying to work with server end points directly?
cc: @sangleganesh
