### ISSUE TITLE
VALIDATE JSON option removed while creating key/value store in consul UI

### ISSUE THREAD

**Issue by sushovan23** [hashicorp/consul#4671]
I notice that in the latest version of Consul UI while creating the key-value store the validate JSON option is removed. Will it come back and also how to use the code button?

**Comment by johncowen** [comment]
Hi @sushovan23 ,

Thanks for the +1 on this!

Yes, it will be back. We've been discussing providing more validation options aswell as JSON hence the delay on this. See #4258, #4256 and https://github.com/hashicorp/consul/pull/4160#discussion_r192360114 for more background.

For now the code button simply turns off/on a syntax highlighting 'code editor' view. We recently changed this to be on by default as we think most people want this view by default (#4558).

Thanks,

John
