### ISSUE TITLE
Consul downgrade from 1.2.2 to 0.7.1

### ISSUE THREAD

**Issue by rudziankou** [hashicorp/consul#4674]
Hi folks,
Is it possible to downgrade Consul without data loss? I have pretty big KV storage there. 

Consul version: 1.2.2
Target version: 0.7.1

PS. I'm preparing update from 0.7.1 to 12.2. Everything looks good. I just looking for for a backup plan in case of emergency.

Thanks!

**Comment by kyhavlov** [comment]
Hey @rudziankou, downgrading that way *could* work, but it's not supported and you'll probably run into an issue around a Raft log entry being written by the newer Consul version that the older one doesn't understand. 0.7.1 does have the `snapshot` command though, so you should be able to use that to back up all of the data in case you need to revert to the old version and restore for some reason: https://www.consul.io/docs/commands/snapshot.html

Hope that helps!

**Comment by rudziankou** [comment]
Thanks, @kyhavlov.
