### ISSUE TITLE
how many client should I deply?

### ISSUE THREAD

**Issue by yasenagat** [hashicorp/consul#4689]
Hi,

* i write a http service 
* i want regist my service to consul using consul http api  when my service start ,runtime over http api.
* i have 4 agent ,3 server , 1 client
```shell
[root@localhost ~]# ./consul members
Node                      Address              Status  Type    Build  Protocol  DC   Segment
sddev-1                   192.168.3.125:8301   alive   server  1.2.2  2         dc1  <all>
sddev-2                   192.168.10.208:8301  alive   server  1.2.2  2         dc1  <all>
sddev-3                   192.168.10.210:8301  alive   server  1.2.2  2         dc1  <all>
sddev-4                   192.168.10.37:8301   alive   client  1.2.2  2         dc1  <default>

[root@localhost ~]# ./consul operator raft list-peers
Node     ID                                    Address              State     Voter  RaftProtocol
sddev-2  919217c9-6aaf-b946-7c40-e9e88656afde  192.168.10.208:8300  follower  true   3
sddev-1  1859cc71-a849-be09-f101-a6cd9f9743e0  192.168.3.125:8300   leader    true   3
sddev-3  b8bd89bd-23b0-f290-e035-78d48c9dcee4  192.168.10.210:8300  follower  true   3
```

* should I regitst my service to [agent client],is it right?
or Can I regist my service to [agent server]?

* what is the best practise for running agent client?

* how many client do i need? rule?

**Comment by banks** [comment]
Hey @yasenagat 

Questions like around best-practice and usage are better suited to the [mailing list](https://groups.google.com/group/consul-tool/) where other folks who use Consul can help out. Issues are generally used only for requesting new features.

Also, take a look at the [architecture documentation](https://www.consul.io/docs/internals/architecture.html):

It's expected that you run client on every node in your datacenter. Services register and query their local client so there is no need to "discover" Consul and consul can be used to discover anything else in the DC. Any other model breaks a lot of the assumptions in Consul like the failure detector built into each client is assumed to be a good proxy for the services registered on the client.

In some rare cases [consul-esm](https://github.com/hashicorp/consul-esm) can be used to monitor external services or those running on hardware that can't support a client agent for some reason (e.g. mainframes). You almost certainly don't need that though!
