### ISSUE TITLE
Rolling over consul multiple times in a short time frame leaves a cluster that cannot elect a leader

### ISSUE THREAD

**Issue by neitzj** [hashicorp/consul#4692]
#### Overview of the Issue

I'm trying to setup rolling deploys using terraform with mix of cloudformation. I'm performing rolling deploys with essentially this snippet of cloudformation configuration in an aws_cloudformation_stack.

"UpdatePolicy": {
       "AutoScalingRollingUpdate": {
         "MinInstancesInService": 2,
         "MaxBatchSize": "1",
      "SuspendProcesses" : [ "HealthCheck", "ReplaceUnhealthy", "AZRebalance", "AlarmNotification", "ScheduledActions"],
         "PauseTime": "PT15M",
         "WaitOnResourceSignals" : true
       }
     }

This is configured on an autoscaling group resource in the cloudformation template.

I then use a script on startup to determine if we have joined the cluster and then signal cloudformation
with cfn-signal.

The script is below.

#! /bin/bash

IP=$(ip addr show dev eth0 | awk '/net /{print $2}' | cut -d/ -f1)
echo "Found IP $IP -- waiting for consul to join the cluster"
while ! curl -s http://localhost:9010/v1/status/peers | grep -q $IP:; do echo Waiting for Consul; sleep 1; done
/opt/aws/bin/cfn-signal --region "${region}" --stack "${stack}" --resource AutoScalingGroup
echo "Successfully joined the `cluster!"`

This works fine for the first rolling deploy I do. However usually on the second attempt within 10 minutes. The second rolling deploy leaves the cluster in a state where no leader can be elected.
I'm trying to be careful to only bring up one server at a time as stated in the documentation. But it seems something has gone wrong in the process. Is there a way to get this process to work or if there are simply to many failed servers in a short period of time does that lead to cluster failure or is this behaviour some kind of bug? In short what are best practices to getting consul to work in an autoscaling group with rollover?

My consul version 1.0.6
My consul cluster size is 3.

Agent configuration:

{
   "telemetry" : {"statsd_address": "127.0.0.1:8125"},
   "performance": {
       "raft_multiplier": 1
       },
   "leave_on_terminate": true,
   "encrypt": "****",
   "ports" : { "http": 9010, "dns": 9020, "serf_lan" : 9030, "serf_wan" : 9040, "server" : 9050 }
}

When the cluster gets into the bad state I noticed the following

curl -s http://localhost:9010/v1/status/peers

Gives me this
["10.6.103.136:9050","10.6.39.1:9050","10.6.172.47:9050","10.6.170.31:9050","10.6.37.104:9050","10.6.36.51:9050","10.6.109.112:9050","10.6.107.180:9050"]

However doing
/opt/pureweb.io/services/consul operator raft list-peers -http-addr=127.0.0.1:9010

Gives me this
Error getting peers: Failed to retrieve raft configuration: Unexpected response code: 500 (No cluster leader)

```
output from client 'consul info' command here
```
agent:
       check_monitors = 0
       check_ttls = 0
       checks = 0
       services = 0
build:
       prerelease =
       revision = 9a494b5f
       version = 1.0.6
consul:
       bootstrap = false
       known_datacenters = 1
       leader = false
       leader_addr =
       server = true
raft:
       applied_index = 297
       commit_index = 297
       fsm_pending = 0
       last_contact = 1.975697067s
       last_log_index = 298
       last_log_term = 10
       last_snapshot_index = 0
       last_snapshot_term = 0
       latest_configuration = [{Suffrage:Voter ID:4eb767fc-b0ba-e68a-8f94-9647722a3d2d Address:10.6.103.136:9050} {Suffrage:Nonvoter ID:2354e3c7-caa1-8c89-b202-1aee6bd9a926 Address:10.6.39.1:9050} {Suffrage:Nonvoter ID:54f4079f-4b1b-3ded-d71e-a25a117c1383 Address:10.6.172.47:9050} {Suffrage:Voter ID:4f56e095-c0a0-d499-a650-98db54ec4b70 Address:10.6.170.31:9050} {Suffrage:Nonvoter ID:1fc35b7d-d2ad-6a0e-18ed-5c072ad0d63e Address:10.6.37.104:9050} {Suffrage:Voter ID:61283c85-47c7-42bc-0a59-59283c02978a Address:10.6.36.51:9050} {Suffrage:Voter ID:bfc44df4-77f6-d237-8e5a-389b66204ff7 Address:10.6.109.112:9050} {Suffrage:Nonvoter ID:b58c44c6-1c54-c67e-f6fa-f06550edc4ac Address:10.6.107.180:9050}]
       latest_configuration_index = 295
       num_peers = 3
       protocol_version = 3
       protocol_version_max = 3
       protocol_version_min = 0
       snapshot_version_max = 1
       snapshot_version_min = 0
       state = Candidate
       term = 140
runtime:
       arch = amd64
       cpu_count = 2
       goroutines = 117
       max_procs = 2
       os = linux
       version = go1.9.3
serf_lan:
       coordinate_resets = 0
       encrypted = true
       event_queue = 0
       event_time = 6
       failed = 2
       health_score = 0
       intent_queue = 0
       left = 1
       member_time = 16
       members = 9
       query_queue = 0
       query_time = 1
serf_wan:
       coordinate_resets = 0
       encrypted = true
       event_queue = 0
       event_time = 1
       failed = 0
       health_score = 0
       intent_queue = 0
       left = 2
       member_time = 19
       members = 5
       query_queue = 0
       query_time = 1

### Operating system and Environment details

Linux (amazon linux) running on AWS

### Log Fragments

I see the following over and over again in the logs

Sep 18 21:19:57 ip-10-6-36-51 consul[2817]: raft: Failed to make RequestVote RPC to {Voter 4eb767fc-b0ba-e68a-8f94-9647722a3d2d 10.6.103.136:9050}: dial tcp <nil>->10.6.103.136:9050: i/o timeout
Sep 18 21:19:57 ip-10-6-36-51 consul[2817]: raft: Failed to make RequestVote RPC to {Voter 4f56e095-c0a0-d499-a650-98db54ec4b70 10.6.170.31:9050}: dial tcp <nil>->10.6.170.31:9050: i/o timeout
Sep 18 21:19:58 ip-10-6-36-51 consul[2817]: raft: Election timeout reached, restarting election
Sep 18 21:19:58 ip-10-6-36-51 consul[2817]: raft: Node at 10.6.36.51:9050 [Candidate] entering Candidate state in term 165
Sep 18 21:19:59 ip-10-6-36-51 consul[2817]: raft: Failed to make RequestVote RPC to {Voter 4eb767fc-b0ba-e68a-8f94-9647722a3d2d 10.6.103.136:9050}: dial tcp <nil>->10.6.103.136:9050: i/o timeout
Sep 18 21:19:59 ip-10-6-36-51 consul[2817]: raft: Failed to make RequestVote RPC to {Voter 4f56e095-c0a0-d499-a650-98db54ec4b70 10.6.170.31:9050}: dial tcp <nil>->10.6.170.31:9050: i/o timeout
Sep 18 21:20:00 ip-10-6-36-51 consul[2817]: raft: Node at 10.6.36.51:9050 [Follower] entering Follower state (Leader: "")
Sep 18 21:20:01 ip-10-6-36-51 consul[2817]: raft: Heartbeat timeout from "" reached, starting election
Sep 18 21:20:01 ip-10-6-36-51 consul[2817]: raft: Node at 10.6.36.51:9050 [Candidate] entering Candidate state in term 167

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
