### ISSUE TITLE
Consul kv command no longer present on Ubuntu

### ISSUE THREAD

**Issue by George3d6** [hashicorp/consul#4693]
Hello,

I've installed consul on Ubuntu via `apt install consul`.

Previously, using the package on Ubuntu, Arch and the binary install there was a "kv" command which allowed me to interact with the ky-value store.

The latest docs seems to indicate is still exists: https://www.consul.io/intro/getting-started/kv.html

However, running `consul kv get --recurse blah`

returns an error/help message that indicates the command doesn't exist:

```
usage: consul [--version] [--help] <command> [<args>]

Available commands are:
    agent          Runs a Consul agent
    configtest     Validate config file
    event          Fire a new event
    exec           Executes a command on Consul nodes
    force-leave    Forces a member of the cluster to enter the "left" state
    info           Provides debugging information for operators
    join           Tell Consul agent to join cluster
    keygen         Generates a new encryption key
    keyring        Manages gossip layer encryption keys
    leave          Gracefully leaves the Consul cluster and shuts down
    lock           Execute a command holding a lock
    maint          Controls node or service maintenance mode
    members        Lists the members of a Consul cluster
    monitor        Stream logs from a Consul agent
    reload         Triggers the agent to reload configuration files
    rtt            Estimates network round trip time between nodes
    version        Prints the Consul version
    watch          Watch for changes in Consul
```

**Comment by pearkes** [comment]
The `kv` command was introduced in [Consul 0.7.1](https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#071-november-10-2016). I'm guessing the version you have installed via apt is from earlier than that. You will need to install a newer version from releases.hashicorp.com, sorry about that!
