### ISSUE TITLE
New -log-file parameter may require additional configuration 

### ISSUE THREAD

**Issue by pdroz** [hashicorp/consul#4696]
#### Overview of the Issue
When using the -log-file flag, if Consul is not running as a user with enough permissions to write logs to /var/log (typically owned by root) then Consul will not create the log files, no error messages of any kind are presented back to to the user. 

Running consul as user:root group:root solves this issue. But if someone wants to run Consul as a different user, say as user:consul group:consul.. then additional steps need to be taken.

If trying to write to a sub-directory like /var/log/consul - this will work if you grant ownership to the user/group Consul is running as. 

This may be better suited as a feature request to generate a log message if Consul does not have sufficient permissions to write it's log files and maybe some additional clarification/reminders in the documentation. 

#### Reproduction Steps

On an agent node I'm passing the flag '-log-file /var/log/consul.log' 

I pass the flag using the systemd unit file:

cat /etc/systemd/system/consul.service
[Unit]
Description=Consul Agent
After=network.target

[Service]
User=consul
Group=consul
ExecStart=/usr/local/bin/consul agent -config-dir /etc/consul -log-file /var/log/consul.log 
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
LimitNOFILE=131072

[Install]
WantedBy=multi-user.target

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 48d287ef
	version = 1.2.3
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 49
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1466
	members = 55
	query_queue = 0
	query_time = 133
```

</details>

<details>
  <summary>Server info</summary>

```
/usr/local/bin/consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 39f93f01
	version = 1.2.1
consul:
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = 10.174.164.215:8300
	server = true
raft:
	applied_index = 4912474
	commit_index = 4912474
	fsm_pending = 0
	last_contact = 5.597379ms
	last_log_index = 4912474
	last_log_term = 478
	last_snapshot_index = 4899765
	last_snapshot_term = 478
	latest_configuration = [{Suffrage:Voter ID:ae3e23d7-58b1-408e-258a-a7a42d70341a Address:10.174.164.215:8300} {Suffrage:Voter ID:10b49945-ce73-24ae-4c29-95eff2675c8b Address:10.174.164.199:8300} {Suffrage:Voter ID:6c972b98-ebf2-d110-fc60-f51ead0fa5a0 Address:10.174.164.209:8300}]
	latest_configuration_index = 4692215
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 478
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 230
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1466
	members = 55
	query_queue = 0
	query_time = 133
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 113
	members = 6
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

CentOS Linux release 7.5.1804 (Core)

### Log Fragments
The log file does not even appear in /var/log

**Comment by pdroz** [comment]
Ok, so I found that if I change my service to run as user=root and group=root then the logs get created. On the flip side, if i create a directory /var/log/consul and grant ownership to consul:consul then the log file is created successfully. 

However no matter what log file name I pass it still always just create files named consul-timestamp.log

example:

/usr/local/bin/consul agent -config-dir /etc/consul -log-file='/var/log/consul/consul.log'

generates:

/var/log/consul# ls
consul-1537395014138763084.log

Shouldn't it be creating logs named 'consul.log' since thats what I specify?

Another issue i Noticed.. if i try to pass the flag '-log-rotate-rotation '  I always get a message of:

flag error parsing flags: flag provided but not defined: -log-rotate-rotation

**Comment by pearkes** [comment]
I believe it will be expected that the path must be writeable, so going to close this, but agree it would be far better to raise an error message back to the user.
