### ISSUE TITLE
-log-rotate-rotation' flag I always get the "flag provided but not defined" 

### ISSUE THREAD

**Issue by pdroz** [hashicorp/consul#4698]
I noticed if i try to pass the '-log-rotate-rotation' flag I always get the "flag provided but not defined" message. 

Since this is a very new feature I'm opening this bug to verify if it was documented but somehow not implemented.

**Comment by MagnumOpus21** [comment]
Hey @pdroz  thanks for testing the log rotate functionality. -log-rotate-duration is the flag for rotating the files based on the timelimits. -log-rotate-rotation is not a flag at all. My apologies if the documentation caused any issues.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
