### ISSUE TITLE
Running consul agents in Kubernetes and connect to external Consul server possible?

### ISSUE THREAD

**Issue by peterwi** [hashicorp/consul#4702]
Hi
I can't seem to work out correct entries in values.yaml to only set up consul agents on kubernetes to connect to external consul server
Is this possible?
Many thanks in advance

**Comment by pearkes** [comment]
Hey @peterwi, do you mind opening this issue on [consul-k8s](https://github.com/hashicorp/consul-k8s) or asking via the [Consul mailing list](https://www.consul.io/community.html)?
