### ISSUE TITLE
[Security] Allow to disable scripts registration in HTTP APIs in a agent

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#4711]
Consul allow to activate healthcheck scripts using the `enable-script-checks` directive.

There are cases however were we would like to enable script for an agent, but protect any malicious usage of it from the HTTP API.

I propose to add the following change:

 * Introduction of `enable-local-script-checks` and `enable-remote-script-checks`. The former enabling script checks ONLY for checks defined in Consul configuration file, while the second would also enable script registration from HTTP API on the agent
 * Keep `enable-script-checks` which is the equivalent for enabling both `enable-local-script-checks`and `enable-remote-script-checks`

This would allow to use `enable-local-script-checks` on all our machines and thus keeping our healthchecks while enforcing security and keeping HTTP API.

A colleague of mine will provide soon a PR to implement this.

**Comment by pearkes** [comment]
I believe we can close this based on #4715 🎉.
