### ISSUE TITLE
[Feature] Auto backup & restore functionality 

### ISSUE THREAD

**Issue by realfresh** [hashicorp/consul#4716]
#### Feature Description / Use case

Consul KV snapshot feature is very helpful for taking and restoring backups. It would be even more awesome if:

1. Consul could periodically upload a snapshot of its KV store to something like an S3 bucket. 
2. Consul could be bootstrapped directly off a snapshot stored in an S3 bucket

This would completely remove the need to externally create any kind of backup/restore functionality for safety reasons when running in production.

**Comment by vaLski** [comment]
What about:

* dropping a simple consul **check** (https://www.consul.io/docs/agent/checks.html)
* on all of your consul servers
* and this check will take care of backup the KV
* and sending it to S3?
* check definition
```
{
	"check": {
		"id": "consul_backup",
		"name": "consul_backup",
		"args": ["/usr/local/bin/consul_backup.sh"],
		"interval": "60m",
		"timeout": "120s"
	}
}
```
* script definition
```
set -e
umask 077
# TODO
# exercise for the reader
# Should I run only on the current raft leader and not on all consul servers?
consul snapshot save /path/to/consul.snapshot.$(date +'%a-%H:00').gz
s3cmd put FILE [FILE...] s3://BUCKET[/PREFIX]
```
* In this way you have backups on the selected interval
* monitoring for your backups inside consul by looking into the the checks status should the .sh exit with code different than 0.

**Comment by pearkes** [comment]
Please see the [`consul snapshot`](https://www.consul.io/docs/commands/snapshot.html) command and the [`consul snapshot agent`](https://www.consul.io/docs/commands/snapshot/agent.html) service (the latter being in the enterprise version of Consul only) for ways to solve 1.

For 2, restores are still manually performed but could be automated using the existing tooling depending on your scenario.
