### ISSUE TITLE
v1/health/state returns wrong status if node goes down itself

### ISSUE THREAD

**Issue by EugenMayer** [hashicorp/consul#4721]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

If a node is stopped, the service-check status is a) not removed from `v1/health/state` and b) neither the state becomes "critical". It stays on passed even though the serfHealth check of the node is already critical.

It should be expected that at least a) happens, since that service can no longer be online it should either be gone ( since the node is gone ) or b) it should be failed ( as the node is failing ).

The problem maybe comes from the root, that the check is done on the node foo, and that node has been stopped. Now that check is no longer happening and the state is not recieving any updates.

We should propagate a state:critical state to all services defined on a node or we should remove any check status from `v1/health/state` which has not recieved an update after interval x ..since this means we have no information about the status ( because the check is no longer running ) - it should by no meaning be "passed"

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. have a consul server up and running
2. add a new node 'foo' which registers one service 'whatever' and one service check 'bar'
3. now stop the node 'foo'

### Consul info for both Client and Server

Server: Consul v1.2.2
Cliean: Consul v1.2.2

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease = 
        revision = e716d1b5
        version = 1.2.2
consul:
        known_servers = 1
        server = false
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 53
        max_procs = 4
        os = linux
        version = go1.10.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 3
        failed = 1
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 6
        members = 10
        query_queue = 0
        query_time = 1

```

### Operating system and Environment details

Official consul docker image

**Comment by pearkes** [comment]
> We should propagate a state:critical state to all services defined on a node or we should remove any check status from v1/health/state which has not recieved an update after interval x ..since this means we have no information about the status ( because the check is no longer running ) - it should by no meaning be "passed"

This is intentional. When querying for an instance of that service via the health APIs (eg the DNS interface) you'd retrieve only services that are passing and on a node that has a passing serfHealth check. With failing checks, that node is failing, and won't be routed or returned.
