### ISSUE TITLE
lock to remote data center fails if remote data center loses a server

### ISSUE THREAD

**Issue by alex-seth-jones** [hashicorp/consul#4724]
#### Overview of the Issue

"consul lock" to a remote data center stops working if a consul server in that remote data center goes down. It appears that the client is still trying to talk to the downed server in the other cluster. See the log message at the bottom.

#### Reproduction Steps
1. create two consul clusters in separate data centers with 3 servers each, and federate them together
2. do 'consul lock -datacenter=< remote dc > ...' (this succeeds)
3. take down one consul server in that remote data center
4. lock breaks and cannot be regained

### Consul info for both Client and Server
[centos@consul-server-1 ~]$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 48d287ef
	version = 1.2.3
consul:
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = 80.0.0.6:8300
	server = true
raft:
	applied_index = 10039
	commit_index = 10039
	fsm_pending = 0
	last_contact = 92.819397ms
	last_log_index = 10039
	last_log_term = 89
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:185f17a5-15da-5565-44ac-a33d80d689ac Address:80.0.0.8:8300} {Suffrage:Voter ID:7b3fa9bf-ca1f-ad76-954f-836410a99fa6 Address:80.0.0.6:8300} {Suffrage:Voter ID:eb637dfa-40b9-78d5-61c1-f62fcc068249 Address:80.0.0.9:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 89
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 102
	max_procs = 1
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 8
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 27
	members = 6
	query_queue = 0
	query_time = 1
[centos@consul-server-1 ~]$ 

### Operating system and Environment details

CentOS 7

### Log Fragments

(This IP address is the address of the server which was brought down.)
Lock acquisition failed: failed to create session: Unexpected response code: 500 (rpc error getting client: failed to get conn: dial tcp 80.0.0.12:0->172.23.245.99:8300: connect: connection refused)

**Comment by pearkes** [comment]
I'm guessing you took down the leader (`172.23.245.99`). Is that correct? It likely was returning 500 as a leader election was in progress.

**Comment by alex-seth-jones** [comment]
Yes, but, even after the leader election completed it still was failing.

**Comment by pearkes** [comment]
@alex-seth-jones strange that should only be temporary. Did you try another wan join ([`-wan`](https://www.consul.io/docs/commands/join.html#wan)?
