### ISSUE TITLE
TTL service health checks are flapping causes service to be critical

### ISSUE THREAD

**Issue by daledude** [hashicorp/consul#4742]
#### Overview of the Issue

Service TTL health checks are going critical because the heartbeat doesn't seem to be "seen" until after the TTL. This happens Intermittently but it happens almost at the exact same time on 2 servers running Consul agents that run containers using Containerpilot to report health.  Currently TTL for flapping services is set to 3 seconds. Containerpilot is the app reporting heartbeats and the packets (via tcpdump) from Containerpilot are getting to Consul before the TTL expire. Using "consul monitor" debug shows times in the seconds and I'm trying to figure what Consul would be doing to cause the PUT to take seconds instead of us/ms. Can someone please help me to understand so I can better diagnose?

I have 2 geographically distributed Consul clusters that are federated. Only one datacenter is currently used.
```
agent: Check "service:myservice" missed TTL, is now critical
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 16
	checks = 17
	services = 17
build:
	prerelease =
	revision = 48d287ef
	version = 1.2.3
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 40
	goroutines = 77
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 128268
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3240
	members = 11
	query_queue = 0
	query_time = 2

```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 3
	services = 3
build:
	prerelease =
	revision = 48d287ef
	version = 1.2.3
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.0.73.40:8300
	server = true
raft:
	applied_index = 7437669
	commit_index = 7437669
	fsm_pending = 0
	last_contact = 14.021586ms
	last_log_index = 7437669
	last_log_term = 320
	last_snapshot_index = 7423109
	last_snapshot_term = 320
	latest_configuration = [{Suffrage:Voter ID:f93dbced-b149-5539-192d-2d30a2dfcdbb Address:10.0.73.43:8300} {Suffrage:Voter ID:231d973b-d435-a781-f5bb-a17ab0ecc7c4 Address:10.0.73.40:8300} {Suffrage:Voter ID:33b96a8a-b22f-d058-40a4-c2a5eaaee157 Address:10.0.73.28:8300}]
	latest_configuration_index = 3358110
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 320
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 104
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 128268
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3240
	members = 10
	query_queue = 0
	query_time = 2
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 905
	members = 3
	query_queue = 0
	query_time = 2

```

</details>

### Operating system and Environment details

Ubuntu Xenial with kernel 4.13.0-36-generic.
Client has 8 core (40cpu) with 141GB memory. Shared containers.
Server has 4cpu with 4GB memory. KVM.

### Log Fragments

From "consul monitor"
```
Request PUT /v1/agent/check/update/service:myservice (4.080230008s) from=10.0.48.11:25712
Request PUT /v1/agent/check/update/service:myservice(4.081487095s) from=10.0.48.11:25710
Request PUT /v1/agent/check/update/service:myotherservice (3.96971888s) from=@
Request PUT /v1/agent/check/update/service:myotherservice (3.82907243s) from=@
Request PUT /v1/agent/check/update/service:myotherservice (3.823959718s) from=@
```

**Comment by alitvak69** [comment]
It sounds like #3852 and #3738.  I hate to say me too.  Can developers please chime in?

**Comment by pearkes** [comment]
This does seem like #3852 so will close in favor of that. If you can please post debug logs.

**Comment by pearkes** [comment]
@alitvak69 apologies I meant to centralize on https://github.com/hashicorp/consul/issues/3738 instead which is still open and we are considering an issue that needs to be reproduced and fixed.

It may well be a separate root cause but that can be determined when we look more deeply into the issue.
