### ISSUE TITLE
Updating Consul service using api

### ISSUE THREAD

**Issue by revengel** [hashicorp/consul#4743]
There are exist two methods: register and deregister. How I can update the consul service (e.x. Change name, tags, checks or other information)? It is must be atomic operation.

**Comment by pearkes** [comment]
@revengel updates can be made by re-registering. However, there may be numerous side-effects to this -- in not all cases does the registration get updated in place. Depending on your use case you may be able to simply call the registration API again though (such as tag or meta updates).
