### ISSUE TITLE
Long host names are displayed incorrectly in consul Web Ui Nodes page

### ISSUE THREAD

**Issue by fc572** [hashicorp/consul#4748]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

The page cannot correctly display long machine names

#### Reproduction Steps

Steps to reproduce this issue, eg:
In your own consul demo project 
https://demo.consul.io/ui/dc1/nodes
change the name of the node "consul-client-5" to "consul-client-5-with-a-lot-more-chars-to-make-this-string-long-and-hard-to-display-ok-maybe-now-it-is-enough-thanks-guys" 

It has to be consul-client-5 because in your example this machine has a failing test
Restart the service so that the new name can be picked up. You should see something similar to the image in the screen shot attached 1842.png
![1842](https://user-images.githubusercontent.com/5091969/46468734-379a1980-c7c9-11e8-92ca-a0a151f2e624.png)

### Operating system and Environment details

CentOS Linux 7 (Core)
Kernel 3.10.0-693.el7.x86_64 on an x86_64

### Log Fragments

N/A

**Comment by fc572** [comment]
Hi John,

Yes it is the address of the node.
Sorry for the confusion.

Thank you,
Francesco.

**Comment by johncowen** [comment]
Hey Francesco!

No problem, I think the above PRs will 'improve' matters.

I was just checking I'd got the right field, the bug makes it confusing even for me to be sure its that field! 😄 

Thanks!

John
