### ISSUE TITLE
Doc online have some error

### ISSUE THREAD

**Issue by seifeHu** [hashicorp/consul#4779]
on line document is the '-log-rotate-rotation  '

but in the cmd help it show 
`
  -log-rotate-duration value  	Time after which log rotation needs to be performed
`

**Comment by i0rek** [comment]
Thanks for reporting. This is alreday fixed on master https://github.com/hashicorp/consul/commit/b95a6d16db01c5961d9df4346b64d99e4fff898e and will be rolled out soon.
