### ISSUE TITLE
Consul and the Loopback Interface

### ISSUE THREAD

**Issue by rudziankou** [hashicorp/consul#4798]
Hi folks,

I have question about Loopback Interface. I have setup requirements like this:

1. Consul agent should listen on HTTP and HTTPS ports only for localhost. They should not be accessible from outside. 
2. With number 1 in place and if there are containers running on that host, they should still be able to access consul agent via its HTTP and HTTPS APIs.

I found an answer for the number one question: "client_addr": "127.0.0.1"

For the question number two I found Dummy Interface Solution: https://medium.com/zendesk-engineering/making-docker-and-consul-get-along-5fceda1d52b9. In this case config will look like this: "client_addr": "169.254.1.1". Based on this https://www.consul.io/docs/agent/options.html#_client it can be set to a space-separated list of addresses. I tried this: "client_addr": "127.0.0.1 169.254.1.1".  Consul did not start. What I did wrong?

Do I have any other options?

Thanks!

**Comment by i0rek** [comment]
Thanks for reporting! Could you provide more information like which consul version you are using, what the output is from consul and what system you are running consul on?

**Comment by rudziankou** [comment]
Hi @i0rek,

Server:
3 nodes cluster
Consul 1.2.2
Centos7
`{
    "bootstrap_expect": 3,
    "server": true,
    "disable_update_check": true,
    "ui": true,
    "datacenter": "dc01",
    "data_dir": "/var/lib/consul",
    "log_level": "INFO",
    "encrypt": "ntOAJwEazHKgTL8NwH7lk==",
    "ports": {
        "http": 60200,
        "dns": 60201,
        "serf_lan": 60202,
        "serf_wan": 60203
    },
    "client_addr": "0.0.0.0",
    "raft_protocol": 2,
    "performance": {
        "raft_multiplier": 1,
        "leave_drain_time": "20s",
        "rpc_hold_timeout": "20s"
    },
    "node_name": "consul01.company.com",
    "advertise_addr": "192.168.0.10",
    "acl_datacenter": "dc01",
    "acl_default_policy":"allow",
    "retry_join": ["consul01", "consul02", "consul03"]
}`

Client:
Many nodes
Consul 0.7
Centos7
`{
    "datacenter": "dc01",
    "log_level": "INFO",
    "data_dir": "/var/lib/consul",
    "advertise_addr": "192.168.0.11",
    "client_addr": "127.0.0.1",
    "disable_update_check": true,
    "ports": {
        "http": 60200,
        "dns": 60201,
        "serf_lan": 60202,
        "serf_wan": 60203
    },
    "encrypt": "ntOAJwEazHKgTL8NwH7lk==",
    "retry_join": ["consul01", "consul02", "consul03"]
}`

So Consul client is available from the localhost only but is not available inside the docker containers. I'm looking for a solution to this. I found one with dummy interface. Do I have any other options?

Thanks!

**Comment by pearkes** [comment]
I recommend the [Consul with Containers](https://www.consul.io/docs/guides/consul-containers.html) guide for guidance around running Consul in Docker.

I'd also suggest the [Consul mailing list](https://www.consul.io/community.html) for any additional questions, as GitHub is intended primarily for bug reports or feature requests.
