### ISSUE TITLE
How to listen service change?

### ISSUE THREAD

**Issue by looake** [hashicorp/consul#4802]
when i use go api

**Comment by banks** [comment]
Hi, please see the documentation on [blocking queries](https://www.consul.io/api/index.html#blocking-queries) and catalog/health API endpoints.

In general questions like this are better suited to the [mailing list](https://groups.google.com/group/consul-tool/) which has more people actively responding.

**Comment by looake** [comment]
> Hi, please see the documentation on [blocking queries](https://www.consul.io/api/index.html#blocking-queries) and catalog/health API endpoints.
> 
> In general questions like this are better suited to the [mailing list](https://groups.google.com/group/consul-tool/) which has more people actively responding.

thanks to you
