### ISSUE TITLE
Check output not being picked up

### ISSUE THREAD

**Issue by bencyoung** [hashicorp/consul#4803]
#### Overview of the Issue

I have a service with an http check which returns a string status. This isn't being shown in the health check status

#### Reproduction Steps

Register a check with status "passing". Service is reported as healthy but the health check doesn't record the output:

```
[
    {
        "Node": "...",
        "CheckID": "service:47c71e1e-089a-4a63-8460-1d3814b13e4e",
        "Name": "Service 'Gateway' check",
        "Status": "passing",
        "Notes": "",
        "Output": "",
        "ServiceID": "47c71e1e-089a-4a63-8460-1d3814b13e4e",
        "ServiceName": "Gateway",
        "ServiceTags": [
        ],
        "Definition": {},
        "CreateIndex": 28,
        "ModifyIndex": 28
    }
```

This is with the latest version of Consul

**Comment by pierresouchay** [comment]
To avoid having too much noise in the cluster, there is an optimization to force output to be sync when state change, otherwise, IIRC it is synced on anti-entropy syncs only (depends on the size of cluster, but every few minutes)

**Comment by bencyoung** [comment]
Ah ok, that's likely it then
