### ISSUE TITLE
Syslog setup error: Unix syslog delivery error

### ISSUE THREAD

**Issue by vamsi248** [hashicorp/consul#4807]
Syslog bug on consul version 1.3.0

**Comment by i0rek** [comment]
Thanks for reporting! We have a template with useful information and we actually need that in order to be able to help you! If you could provide more information like steps to reproduce, OS you are running on, and consul output we can look into this issue. Thanks!

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
