### ISSUE TITLE
Is it possible to disable gossip between agents?

### ISSUE THREAD

**Issue by Mariius** [hashicorp/consul#4813]
I is possible to disable gossip between agents and configure Consul in such a way so that Agents only communicate to servers, but not with other agents?
As far as I see it is not possible and gossip is a must-have, am I correct?

**Comment by i0rek** [comment]
Yes thats correct. Gossip is essential for running Consul reliably.

**Comment by shantanugadgil** [comment]
Recently I faced a similar issue in a multi datacenter setup in AWS.
Once VPC peering landed for all regions, doing a full mesh network was just a matter of scripting (using Terraform for the peering as well as route tables)

Now the problem is not there, where all vpcs can talk to each other.
