### ISSUE TITLE
Documentation clarification - Sidecar Service

### ISSUE THREAD

**Issue by djenriquez** [hashicorp/consul#4829]
I was reading through the docs for [sidecar-service](https://www.consul.io/docs/connect/proxies/sidecar-service.html) merged in #4752 and its not apparently clear to me how `"connect": { "sidecar_service": {} }` expands to a registered sidecar service with a proxy defined as:
```
  "proxy": {
    "destination_service_name": "db",
    "destination_service_id": "db",
    "local_service_address": "127.0.0.1",
    "local_service_port": 9090,
  }
```

Does this mean all default `sidecar_services` will automatically have a `proxy` named `"db"` that has a `local_service_port` registered to `9090`? If not, can we please update the documentation to clarify that this part is _NOT_ implicitly defined?

Secondly, further down, its reported that:
```
proxy.destination_service_name - Defaults to the parent service name.
proxy.local_service_port - Defaults to the parent service port.
```

If this was really the case, wouldn't it be more correct if the above were defined as:
```
  "proxy": {
    "destination_service_name": "web",
    "destination_service_id": "web",
    "local_service_address": "127.0.0.1",
    "local_service_port": 8080,
  }
```
since `"web"` is the parent service and `"web"`'s port is `8080`?

If there are some assumptions made to set the proxy to `db` /w service port `9090`, that clarification would be greatly appreciated.

Many thanks!

**Comment by djenriquez** [comment]
Actually, reading through more of the docs, it appears this should be the proxy that defines ingress traffic to the parent service, in which case, the doc is just incorrect? Or am I just super confused now and this is supposed to be an upstream definition to service `db`. 🤔

**Comment by pearkes** [comment]
@djenriquez `sidecar_service` is meant to represent the proxy in both the source and destination function. The configuration is different for each. I think some confusion is occurring because we don't make this super clear on the outset, will note to improve the docs there.

**Comment by jarrettj** [comment]
Hi,

Good day.

Thanks man, I'm just as lost. Maybe through in a complete example as well? :-D

Regards.
JJ
