### ISSUE TITLE
Consul Services CLI API.

### ISSUE THREAD

**Issue by alexshv** [hashicorp/consul#4830]
Documentation says there's 'consul services' CLI API. But Im running dockerized agent locally and there's no such command. 
Consul Version - v0.9.0.

<img width="709" alt="screen shot 2018-10-23 at 14 58 03" src="https://user-images.githubusercontent.com/8845709/47359077-70485700-d6d4-11e8-97d7-aec7f15be9ba.png">

**Comment by ChipV223** [comment]
Hi @alexshv !

The services CLI API was released with Consul 1.4.0, which explains why you don't see the listing in version 0.9.0. In order to use the API, you would need to upgrade your Consul instance.

Let me know if you have any other questions!

**Comment by alexshv** [comment]
@ChipV223 Thanks! :)
