### ISSUE TITLE
Write an ACL upgrade Guide

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#4835]
The guide needs to cover how to transition from a legacy ACL system to using the new system.

Basically it should go over how to upgrade your systems and then how to transition rules in tokens to policies.

**Comment by pearkes** [comment]
- Primary Datacenter can come first or second. It needs to be upgraded for anything else to use new ACLs or to use local tokens
- Standard rolling upgrade procedure
- Configuration is backwards compatible but there are additional new options that will eventually be required. `acls {}`, `PrimacyDatacenter`

**Comment by banks** [comment]
#4880
