### ISSUE TITLE
v1.3.0 Bootstraping ACL - "invalid config key primary_datacenter"

### ISSUE THREAD

**Issue by edmundkwok** [hashicorp/consul#4843]
Hi there,

I'm deploying a fresh Consul cluster on 1.3.0 with ACL using the following config:

```javascript
{
  "primary_datacenter": "dc1",
  "acl_default_policy": "deny",
  "acl_down_policy": "extend-cache"
}
```

On startup, the logs shows the following error:

```
invalid config key primary_datacenter
```

I was looking through the code to see where this comes up, and it looks like this revert - https://github.com/hashicorp/consul/commit/8bcfbaffb6588b024cd1a3cf0952e6bfa7d9e900#diff-82751e0f6acee8ce7c2f62cfe46735ad - also removed `primary_datacenter` in 1.3.0? 🙁

**Comment by mkeeler** [comment]
@edmundkwok The `primary_datacenter` config entry is only valid in 1.4.0-rc1 at this point.

In v1.3.0 you must use the `acl_datacenter` config entry which is deprecated in 1.4.0-rc1. The revert commit is there because we didn't intend for that code to go into 1.3.0 but we merged it prior to the 1.3.0 release.

Also note that the ACL systems in 1.3.0 and 1.4.0-rc1 are vastly different.

**Comment by mkeeler** [comment]
I guess we are in a bit of a tricky situation. The docs on the website are really valid for 1.4.0-rc1 but there is no place where you can see whats valid for 1.3.0.

We need both of course but we currently don't have a website capable of versioning docs.

**Comment by edmundkwok** [comment]
This is the legacy docs though (https://www.consul.io/docs/guides/acl-legacy.html vs https://www.consul.io/docs/guides/acl.html), with the notice at the top:

```
1.3.0 and earlier: This guide only applies in Consul versions 1.3.0 and before. If you are using the 1.4.0 RC please use the updated guide here
```

I presume this is separate file altogether? But I'll leave it to you guys to decide what's best since 1.4.0 may be released soon (I hope!). Just cautious about others who may stumble upon the same issue and not find a resolution.
