### ISSUE TITLE
Local installation of consul : Your bundle is locked to i18n (0.9.5)

### ISSUE THREAD

**Issue by kiwis2** [hashicorp/consul#4863]
Hello

I just landed and discovered consul, and decided to discover the app as I'm PhD student working on Participatory Governance. 
The issue that blocked me from even locally exploring consul came after i ran out the command bundle install.

> $ bundle install
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Resolving dependencies......
> Your bundle is locked to i18n (0.9.5), but that version could not be found in
> any of the sources listed in your Gemfile. If you haven't changed sources, that
> means the author of i18n (0.9.5) has removed it. You'll need to update your
> bundle to a version other than i18n (0.9.5) that hasn't been removed in order to
> install.
> 

**also when i try bundle update i get :** 

> $ bundle update
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Could not find gem 'rails (= 4.2.10)' in any of the gem sources listed in your
> Gemfile.

I was following the steps from the documentation for installing consul locally. 

could anyone please help out?

Thanks

Screen shot
![s_s](https://user-images.githubusercontent.com/44402753/47622938-5ad79080-db0b-11e8-9701-adc888cc3299.jpg)

**Comment by i0rek** [comment]
You must be looking at the wrong github repository, because Consul doesn't have a Gemfile in its root directory.

**Comment by kiwis2** [comment]
How's it even possible not to have a gemfile??
I followed the installation instructions from the documentation.
And copied the clone command as it's!

**Comment by i0rek** [comment]
Because consul is written in Golang. The packaged manager `Bundler` is for ruby.

**Comment by kiwis2** [comment]
So what's your advise in this case i used gitbash for windows i started
with clone command and it loaded all the files available on github source
code including gemfile.
Could you please advise?

**Comment by i0rek** [comment]
My advise is to check if this github repo: https://github.com/hashicorp/consul is the correct place to report your issue because we don't have a gemfile!
