### ISSUE TITLE
Got a bug ,  regsiter service can not push to cluster,    Is cmd consul leave different from pkill -2 consul ? 

### ISSUE THREAD

**Issue by seifeHu** [hashicorp/consul#4865]
#### Overview of the Issue

I build a consul cluster , 3 servers , and  10+ client . consul version is .1.2.3

I find register  service to  client  , It is ok In client . But the service not push to cluster .

I find log have some err.

` "Catalog.Register" RPC failed to server 10.56.63.15:8300: rpc error making call: failed inserting node: Error while renaming Node ID: "f53fa71f-be08-9ed7-b9b2-5e792fbeb32e": Node name node-10_56_63_235 is reserved by node 8db2c9cc-864c-384e-0bf4-90651a712486 with name node-10_56_63_235
`

I fixed  the problem In next steps
1、consul leave 
2、restart consul 
3、join the cluter again

First step , I used to  pkill -2 consul . But It is not work~
It this a Bug ?

**Comment by pierresouchay** [comment]
It says the node name is already being used by another agent. For the cluster, it means that 2 nodes try using the same name. Is it bare metal or VMs? Do you reuse the same node names several times?

**Comment by pierresouchay** [comment]
Probably similar to https://github.com/hashicorp/consul/issues/4741

**Comment by seifeHu** [comment]
> Probably similar to #4741

tks .  First I build a cluster .They were not vote a leader. Then In this time client agent join the cluster。

I found there were not a leader . I restart server with  -bootstrap-expect=3 and the cluster have a leader

I kill consul client agent (not use kill -SIGINT ) and restart consul client 。So meet the problem  。

**Comment by pearkes** [comment]
Agree we can close this in favor of #4741.
