### ISSUE TITLE
Running the UI in a 1.4 client against a 1.3 cluster gives 500 error at the ACLs pages

### ISSUE THREAD

**Issue by johncowen** [hashicorp/consul#4871]
When running a 1.4 UI client against a 1.3 cluster of servers, the new ACL API endpoints give 500 errors, therefore the UI shows a 500 error page when navigating to the ACLs area

Also see:

https://github.com/hashicorp/consul/issues/4839#issuecomment-433541999

@rboyer

**Comment by rboyer** [comment]
Note in case it's not covered with the above: This also is triggered when a NEW client is forwarding requests to an OLD server in a completely different datacenter
