### ISSUE TITLE
Add option to make services not return self

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#488]
I'd like to request a feature where a DNS and/or HTTP query for a service should have the option to not return the querying server or return the querying server last. For example, if I have the topology like this:

server1 10.0.0.5
server2 10.0.0.6
server3 10.0.0.7

And all 3 have the service "someservice" on them, then I can do "dig someservice.mydomain.consul" from server3 with the proposed "exclude self" option set on the service config file, and I would get back a random reply (as per current behavior) of the IP addresses excluding the machine that queried - that is, I'd get back 10.0.0.5 and 10.0.0.6 shuffled, but never get back 10.0.0.7 when querying from 10.0.0.7.

"self last" is the same as current behavior except the reply is sorted out so that 10.0.0.7 would ALWAYS come last so it's there no matter what if the service is a singleton or has no other healthy nodes.

The reason I want this feature is because I have services that operate on themselves but then restart their own daemon and thus lose connection to themselves - the exact use case is I have a pair of Salt master servers, and I'm using Salt to manage itself and Consul for DNS (and also to find a Salt Master to talk to) so I don't want the Salt master trying to use itself for the config source, restarting the salt-master service, then losing connectivity because the service just restarted out from under it. This is actually happening and there doesn't seem to be a way to say "Don't talk to myself", hence this feature request. The other use case I have for it is setting up Raft clusters for various other services like InfluxDB - during install, I want to loop until there is at least a second node up, then join to it. I could use the K/V store for that, but I can't really for the first use case I listed with the Salt masters.

Alternatively, I can try implementing this myself - it looks pretty easy and I found the function to change, but I'd like to get your thoughts on whether this is a feature you'd accept a pull request on or if there's a more canonical way to do it before I start work.

**Comment by a86c6f7964** [comment]
I requested something like this in the email group, and thought that adding something like "ExcludeAgent" to the prepared queries sounded like a good option to try and make this work.

**Comment by slackpad** [comment]
Prepared queries would definitely be the right way to express something like this. We haven't seen a ton of other interest in this, so we don't have plans to implement this at this time, but we'd welcome a PR for it.
