### ISSUE TITLE
Create lock in different datacenter

### ISSUE THREAD

**Issue by sevagh** [hashicorp/consul#4886]
#### Feature Description

Allow `consul lock` against a datacenter that the local agent is not a part of.

#### Use Case(s)

I want a "global" lock - I want to use `consul lock` to lock a deployment that can happen from a host in "dc1" and a host in "dc2". I want to use a neutral "dc3" for this lock. Turns out that locking against a datacenter that the local agent not a member of is not supported.

My test setup is a local 2-datacenter consul cluster:

```
shanssian:consul $ CONSUL_HTTP_ADDR="http://localhost:9500" consul members -wan
Node           Address         Status  Type    Build     Protocol  DC   Segment
agent-one      127.0.0.1:8301  alive   server  1.4.0rc1  2         foo  <all>
agent-two.bar  127.0.0.1:9302  alive   server  1.4.0rc1  2         bar  <all>
```

When I try to lock against the wrong datacenter (i.e. the one that my agent isn't a member of), it's unsupported:

```
shanssian:consul $ consul lock -datacenter=foo fake-lock echo hello
Lock acquisition failed: failed to create session: Unexpected response code: 500 (rpc error making call: Missing node registration)
```

I've been trying to implement this PR myself - here's a relevant Google Groups discussion: https://groups.google.com/forum/#!msg/consul-tool/wEkG7Ztm68Q/8mpjlo-bAQAJ;context-place=searchin/consul-tool/node$20registration%7Csort:date

In that discussion, @slackpad says that if a Session has a TTL and no checks associated, it should be OK to register.

It looks like the session is automatically created with `Node: $localagent, Checks: [serfHealth]` from the `consul lock` command:

```
 &{
    ID:3bd4752b-9fa1-8a6a-ccd6-412be65ec41f
    Name:Consul lock for 'echo hello' at 'fake-lock'
    Node:agent-two
    Checks:[serfHealth]
    LockDelay:15s
    Behavior:release
    TTL:15
    RaftIndex:{CreateIndex:252 ModifyIndex:252}
}
```

I'm looking at the code here: https://github.com/hashicorp/consul/blob/master/agent/session_endpoint.go#L65

This is the call where this Session body is sent to the different datacenter. I'm uncertain how to best tackle this. The default check `[serfHealth]` seems to correspond to the Node in the existing datacenter, not the other one, which the current datacenter agent sends to the other datacenter via RPC.

Finally, when the other datacenter agent receives the request, even if I modify the Session code ([here](https://github.com/hashicorp/consul/blob/master/agent/consul/state/session.go#L187)) to allow a non-existent Node to continue if the TTL is defined, I still get an error since the default `[serfCheck]` in the Session request body refers to the `[serfCheck]` on the agent in the first datacenter:

```
2018/11/01 16:00:52 [ERR] http: Request PUT /v1/session/create?dc=foo, error: rpc error making call: Missing check 'serfHealth' registration from=127.0.0.1:59570
```

I'm wondering what the strategy should be here:

1. If sending the New Session request to an agent in a different datacenter, clear the Node and Checks[] array
2. ???

#### Any relevant use-cases that you see.

Again, to describe my original usecase, I have 3 DCs, one of which I want to use for "global locks" to lock across any consul DC. Problem is that `consul lock -datacenter=<not-my-datacenter>` doesn't work without the modifications above.

I hope this is clear - I'm happy to expand more on my request.

**Comment by sevagh** [comment]
Also note, the foo/bar testcases I pasted above were contrived but we do have some real Consul clusters in production where this would be useful (and tested before creating a PR).

**Comment by pearkes** [comment]
@sevagh Sorry we don't have tons of bandwidth to help you ahead of a PR but from James' original suggestion on the linked mailing list post I would suggest some sort of conditional to determine if the datacenter was non-local and removing the node and checks state as you've mentioned in order for the receiving DC to process the request properly.

I think you'd need to modify the existing validations to allow for nil nodes as long as the TTL was greater than 0 in the links you suggested there.

I'm not sure of the use-case you're looking at specifically but we may not be able to quickly get this change upstreamed so want to set expectations there. I hope I've answered all of your questions -- I'm going to close this but please do reply back with further questions or open the PR you've been working on!
