### ISSUE TITLE
Enhance the consul connect proxy CLI command with -local-bind-address argument

### ISSUE THREAD

**Issue by rberlind** [hashicorp/consul#4893]
#### Feature Description
Currently, there are two ways to create Consul Connect upstream proxies:
1. With [Consul configuration files](https://www.consul.io/docs/connect/proxies.html#upstream-configuration-reference)
2. With the `consul connect proxy` CLI command including the [-upstream argument](https://www.consul.io/docs/commands/connect/proxy.html#upstream).

The former has local_bind_address and local_bind_port arguments that can be used to specify the IP and port which the upstream proxy should listen on for requests from the Consul service talking to the upstream proxy. So, an application talking to an upstream proxy can bind to the IP specified by local_bind_address which defaults to 127.0.0.1 but could be set to the private IP or even a public IP of the host the upstream proxy runs on.

However, the `consul proxy connect` CLI command only allows you to set the -upstream argument in the form name:port where name is the name of the Consul service the upstream proxy will connect to and port is the port that the local Consul service will talk to.  Note that the upstream proxy will only bind to 127.0.0.1 on the specified port.

This makes it impossible for an application inside a Docker container to connect to an upstream proxy created with the `consul connect proxy` command unless the container runs on the Docker host network in which case the app can send requests to the host's 127.0.0.1 IP.  If the Docker container is running on a bridge or overlay network, any request sent by the app to "127.0.0.1" will actually talk to 127.0.0.1 inside the container which is NOT mapped to 127.0.0.1 on the host for these docker network choices.

Since it is very common to run Docker containers on bridge and overlay networks, it would be good to enhance the `consul connect proxy` CLI command with a new -local-bind-address argument that would cause an upstream proxy created with this command to bind to the IP provided.

While this issue focuses narrowly on the need to add a -local-bind-address argument to the `consul connect proxy` command, ideally that command would support all options for proxies that can be set in Consul configuration files.

#### Use Case(s)

Improving the `consul connect proxy` CLI command as suggested would be especially useful for customers running Nomad and Consul Connect together since they might want to use Nomad to schedule the proxies with the `consul connect proxy` command as suggested in this [doc](https://www.consul.io/docs/connect/platform/nomad.html). This allows Nomad to schedule the proxies together with the apps that Nomad might already be running without requiring a user to define the proxies in Consul configuration files.

**Comment by wathiede** [comment]
According to the flag parser for -upstream: https://sourcegraph.com/github.com/hashicorp/consul@53f3962/-/blob/command/connect/proxy/flag_upstreams.go#L18

You can specify -upstream=<service>:<bind ip>:<bind port> in addition to the documented -upstream=<service>:<bind port>

Does that meet your need?

**Comment by rberlind** [comment]
It very well might.  I will try to do some tests this week.  It sounds like it would allow me to specific `-upstream=name:address:port`.  It would be nice if the doc for the flag (and the comment in the code) mentioned that.

**Comment by rberlind** [comment]
I did try using the flag with both address and port, but did not yet have success.  I will revisit this later this week or next week.
