### ISSUE TITLE
ui: edit token page doesn't detect HCL vs JSON rules (v 1.4+)

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#4894]
1. Create either a Legacy Token or a New Token using HCL to define the Rules section.
2. Go to new UI and open the Edit Token page for that token.
3. The large rule editing window defaults to JSON with no apparent sniffing, so the first thing you see is a red `(X)` saying "Parse error on line 1" because it's trying to parse HCL as JSON.

If you manually flip to HCL then it's ok, and apparently remembers the HCL flag, which only causes the reverse problem to happen when you visit a Token that has its rules formatted in JSON.

**Comment by johncowen** [comment]
Hey @rboyer 

😮 thanks for this.

This should have gone in here but somehow didn't, thanks for spotting!

https://github.com/hashicorp/consul/pull/4866/files#diff-40ad7beb521f309157a5d021388c3581

Basically, rule editing should be HCL only (although see comment below), so it shouldn't show you that little syntax dropdown on the editor.

Bit more info here:

> The large rule editing window defaults to JSON with no apparent sniffing

We made the decision not to do any sniffing, for the moment at least. There is always a chance it might get annoying. We might revisit this decision later down the line.

> If you manually flip to HCL then it's ok, and apparently remembers the HCL flag, which only causes the reverse problem to happen when you visit a Token that has its rules formatted in JSON.

A while back with the Code Editor ON/OFF switch we made the decision to make that a global switch following user feedback, so if you set it 'on' whilst editing one KV it will also be 'on' in another KV. This 'syntax setting' follows the same approach.

I have just realized though, you bring up a good point as Token/Policy rules themselves are not necessarily always in HCL format? They could be in JSON format also? Is that right?

I think for the moment I'm going to PR that change to restrict to HCL only. The HCL 'mode' doesn't have any linting, only colorizing, and colorizing JSON using HCL mode doesn't look 'too bad'. Plus I would hazard a guess that HCL is going to be the most common.

I'll add you as approver on that PR.

Thanks again!

**Comment by johncowen** [comment]
Closing this, I've verified this myself again during development, and with a full binary build and verify in both 1.4 talking to 1.3 and 1.4 talking to 1.4. All looks good.

Pretty sure we got to the bottom of what was happening here with @banks
