### ISSUE TITLE
4xx HTTP response for catalog API query with non-existent dc query param

### ISSUE THREAD

**Issue by dadjeibaah** [hashicorp/consul#4901]
#### Feature Description

Consul's catalog API allows you to query for services associated with a particular datacenter using a query parameter in the API request. e.g.

```bash
➜  ~ curl -v http://localhost:8500/v1/catalog/service/cat?dc=dc1
...
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Accept-Encoding
< X-Consul-Effective-Consistency: leader
< X-Consul-Index: 18
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Mon, 05 Nov 2018 22:17:17 GMT
< Content-Length: 861
<
...
```

When querying that same request to a datacenter that does not exist, I would expect Consul to respond to the request with a 4xx but it responds with a 5xx

```bash
➜  ~ curl -v http://localhost:8500/v1/catalog/service/cat?dc=dc2
...
< HTTP/1.1 500 Internal Server Error
< Vary: Accept-Encoding
< X-Consul-Index: 1
< X-Consul-Knownleader: false
< X-Consul-Lastcontact: 0
< Date: Mon, 05 Nov 2018 22:19:57 GMT
< Content-Length: 21
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
No path to datacenter%
```

In Linkerd, we use consul to provide service discovery for apps and we, in part, use the http status code to determine if the query encountered a consul failure or if service discovery information returns empty results. In the case of sending an non-existent dc, it seems that kind of query should be treated as "Not Found" instead of an "Internal Server Error".

**Comment by pearkes** [comment]
Unfortunately I don't see us fixing this soon as it'd be a breaking API change. I'd recommend either reading the body in the response to determine the cause of the error in the case of 5xx. We don't disagree the HTTP status code could be more accurate here but unfortunately that type of change causes a substantial blast radius that I don't think is justified for this scenario.

We do hope eventually to work on a new version of our API that holistically solves some of these inconsistencies (within the APIs or with standards) but for now I'd recommend the above workaround. Thanks for opening an issue!
