### ISSUE TITLE
Locks behavior after falling consul cluster

### ISSUE THREAD

**Issue by lukashes** [hashicorp/consul#4902]
I tried to implement locks at my backed same way:

```
...
for {
  select {
  case <-time.After(time.Second):
  }

  select {
    case <-lockCh:
      lockCh, err = consul.Lock(ctx.Done())
      if err != nil {
        fmt.Println(err)
        continue
      }
  }
  
...
}
```

If `lockChan` closed - I am trying to acquire new lock. But if connection to the consul service is broken (after consul termination) I see error: `Lock already held`. Expected behavior (for me) if `lockCh` was closed I lost my lock and I can try new one. But I can't because `Lock.isHeld` field is still `true`. 

Could you explain is it good behavior or error inside locks API?

**Comment by banks** [comment]
Hi,

Did you get a change to read through https://www.consul.io/docs/internals/sessions.html which explains the high level design of lock sessions?

Locks need to be attached with sessions. Sessions need to be associated with a health check and locks have an expiry time, both of these are used to trade of safety vs liveness.

I guess what you are seeing is that the lock is not timed out yet. See https://www.consul.io/api/session.html#lockdelay.

If that doesn't help, I suggest you ask on the https://groups.google.com/forum/#!forum/consul-tool as we prefer to keep github issues for bug reports or feature requests.

**Comment by banks** [comment]
@lukashes also see #4935 it seems there is a bug here that might be affecting your usage.

**Comment by lukashes** [comment]
Yes, it was my case. Thank you for mentioning.
