### ISSUE TITLE
Loop of death when DNS queries a service that was registered wrong

### ISSUE THREAD

**Issue by sielaq** [hashicorp/consul#4907]
#### Overview of the Issue

Consul gets out of memory and dies or machine hangs  
due to the loop of DNS resolve  
when buggy service has been registered  
and one DNS query was asked

#### Reproduction Steps

0. `dnsmasq` (or unbound) with config like:
```
server=/service/127.0.0.1#8600
server=/service.domain.com/127.0.0.1#8600
```

1. register service that points to itself via giving as `Address`  
not an IP, but hostname from domain that is gonna be resolve again via consul
```
{
  "Node": "foo",
  "Address": "foo.service.domain.com",
  "Service": {
    "Service": "foo",
    "Port": 8500
  }
}
```
2. query it
```
dig @localhost -p 8600 foo.service.domain.com
```

(of course  the simple `.domain.com` can be `.consul`  
or even no domain need at all, if you register services like `foo.service`   
but having 1st entry in `dnsmasq`)

### affected versions 

all version of consul > 0.7

### Operating system and Environment details

Reproducible on Linux (amd64)

### Log Fragments

 `-log-level=TRACE` is not giving anything special

### Expected behavior

consul is not dying

**Comment by pierresouchay** [comment]
@sielaq Should be fixed with https://github.com/hashicorp/consul/pull/4918
