### ISSUE TITLE
Allow tags in upstreams

### ISSUE THREAD

**Issue by matthoey-okta** [hashicorp/consul#4927]
#### Feature Description

It would be cool if you could create upstreams and then filter based on tags. Let's say 2 nodes for Service B have two separate tags, it would be nice if in the connect setup for Service A you could have two upstreams with two different local_bind_ports that filter on the two tags for Service B.

I realize this could also be achieved with separate services, but tags seem to already be supported for services so I think the same functionality could be pushed down to the upstreams as well.

#### Use Case(s)

Just as you might run separate DNS queries for tags within a service, you can also use separate upstreams on the same service but with different tags.

**Comment by pearkes** [comment]
Have you looked at [prepared queries](https://www.consul.io/docs/guides/acl.html#prepared-query-rules) at all? They are supported as an upstream for the built-in proxy and #4969 will add support for them in Envoy.

It isn't tag filtering but I believe it may give you what you're looking for based on the description.

**Comment by pearkes** [comment]
I'm glad, yeah agree #1956 or something like it would improve the experience with prepared queries. One thing I'll suggest for that (going to actually go over there and point it out as well) is that the Consul Terraform Provider supports a [prepared_query](https://www.terraform.io/docs/providers/consul/r/prepared_query.html) resource that can potentially provide you with a nice workflow to bootstrap and manage prepared queries.

I'm going to close this for now but feel free to comment back or open a new issue if prepared queries are helping with your use-case.
