### ISSUE TITLE
Consul script check reporting missing file but file exists

### ISSUE THREAD

**Issue by joshk132** [hashicorp/consul#4943]
#### Overview of the Issue

I am trying to set up some basic checks using consul but have ran into an issue where consul reports my script check as critical due to a missing file. I am setting this up using a custom chef cookbook and I know that the value for the check/file path is the exact same as what I am creating with chef because it is the exact same variable. 

#### Reproduction Steps

Steps to reproduce this issue, eg:

Create a consul single node server using the command `/work-disk/consul/consul agent -server -data-dir=/work-disk/consul/data -node=consul-test-node-1 -config-dir=/work-disk/consul -enable-script-checks -bootstrap`

Create the script check script file

```
memchecksh = "/work-disk/consul/data/mem-check.sh"

cookbook_file memchecksh do
  source 'mem-check.sh'
  owner consul_user
  group consul_user
  mode '0755'
  action :create
end
```

Register a check using the following chef resource

```
mem_check = {
  "ID" => "mem_check_api", 
  "Name" => "mem check api", 
  "args" => ["#{memchecksh}"], 
  "interval" => "10s", 
  "timeout" => "1s"
}

json = JSON.dump mem_check

http_request 'register_mem_check' do
  url 'http://127.0.0.1:8500/v1/agent/check/register'
  message {json}
  action :put
end
```

### Consul info for both Client and Server

```
josh@JK-SRV-HOSTNAME:~$ /work-disk/consul/consul info
agent:
        check_monitors = 2
        check_ttls = 0
        checks = 2
        services = 1
build:
        prerelease =
        revision = e8757838
        version = 1.3.0
consul:
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 192.168.0.34:8300
        server = true
raft:
        applied_index = 195
        commit_index = 195
        fsm_pending = 0
        last_contact = 0
        last_log_index = 195
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:aa114be3-132f-fd69-5768-77b0355f5887 Address:192.168.0.34:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 82
        max_procs = 2
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1

```

### Operating system and Environment details

Ubuntu 16.04.3 LTS

**Comment by pierresouchay** [comment]
Hard to tell, you are providing chef cookbook, but not Consul messages nor the shell script.
What I can tell you is that is works for us. 
Do your script starts with line #!/bin/bash or similar (this is a fork, so Linux needs this line to find the interpreter)?

**Comment by joshk132** [comment]
@pierresouchay  What consul message should I be including? The shell script is a simple memory check script, what it contains should not have an impact weather consul can find a file or not?? 

Script starts with `#!/bin/sh` not the line you mentioned.

Here you can see where I am finding/saying it can't find the file

```
curl http://127.0.0.1:8500/v1/health/state/critical | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   292  100   292    0     0   219k      0 --:--:-- --:--:-- --:--:--  285k
[
    {
        "CheckID": "mem_check_api",
        "CreateIndex": 7,
        "Definition": {},
        "ModifyIndex": 7,
        "Name": "mem check api",
        "Node": "JK-SRV-CHEF-TEST-2",
        "Notes": "",
        "Output": "fork/exec /work-disk/consul/data/mem-check.sh: no such file or directory",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Status": "critical"
    }
]
```

Main line out of that being ` "Output": "fork/exec /work-disk/consul/data/mem-check.sh: no such file or directory",`

**Comment by pierresouchay** [comment]
Check the script does exists and that /bin/sh does exists as well.

Also check with the user Consul is running with that the script can be read

**Comment by pierresouchay** [comment]
Try with /bin/true as script to see if it works, but looks like a path issue still

**Comment by pierresouchay** [comment]
So, you mean you don't have the same value in health than in /v1/agents/checks?

If that's the case, that's probably an ACL issue: your agent and it's token has not the right to publish its result because it has not the rights on Memory*

Check your agent logs

**Comment by joshk132** [comment]
@pierresouchay No the output is not the same in both, I assumed that was because the health just didn't report that info. 

I have no ACL setup currently and am registering this check via the API. I have a service check that checks Nginx I defined through a config file and that seems to have worked fine.

**Comment by joshk132** [comment]
I am working on a consul upgrade at work as well as the project that I opened this issue for and I am getting the same output as I got for the above. The checks were known to be working in 0.7.1 and now they don't work in 1.3.0 . I did change the `script` too `args` before registering the checks.

**Comment by jkwysdom** [comment]
I am having the exact same issue as you, hopefully it gets solved soon. Will be keeping an eye on this ticket hopefully @pierresouchay  or someone else knows the solution.

**Comment by banks** [comment]
The big change in 1.0.0 was not just a string replaced with array in the check syntax but we switched from blindly passing the string through to your shell.

So when using `args` we exec the binary that is the first argument directly instead of passing it through to `bash =c '<script>'`. This is better for security as well as much less pain trying to escape things correctly.

> `"shell" => "/bin/bash",`

That is only supported for Docker checks. If you want to try running in a shell to mimic the old behaviour, try:

```
"args": ["sh", "-c", "/work-disk/consul/data/mem-check.sh"]
```

Does that work? If so we at least know it's something to do with the shell.

If not then things get strange. For example a super unintuitive reason that exec can return `no such file or directory` is if the binary you are executing (or something it forks/execs in turn) is dynamically linked against something that is not found or linked against the wrong libc or similar. This can often happen if you move binaries between OSes or build in one container and run in another etc.

Can you sanity check for me that if you `su` to the consul user and try to actually execute the script you don't see the same thing? (I think you said you verified consul user can see it there).

**Comment by pierresouchay** [comment]
@jkwysdom sh is not a path, neither is ruby, you have to use absolute paths.

To test what is wrong, do the following:

"args": ["/bin/ls", "/tmp"]

if it work, create a shell script called `"/tmp/myscript.sh"` and `chmod a+x /tmp/myscript.sh`:
```shell
#!/bin/bash
ls /tmp/
```
and execute it: `"args": ["/bin/bash", "/tmp/myscript.sh"]`

if it works, try with `"args": ["/tmp/myscript.sh"]`

if all of this is working, something is wrong in your script :-)

Beware, in fork, there are no $PATH environment variables, so executable must have absolute paths.

You can skip the shell, but in that case, ensure the 'x' permission on the file, and please ensure that the first line of script is `#!/bin/bash` or whatever your scripting language is for the kernel (which is launching your executable) to recognize which interpreter to launch (kernel does not know anything about extensions as Windows does.
