### ISSUE TITLE
Multiple health checks not registering right or failing after upgrade

### ISSUE THREAD

**Issue by jkwysdom** [hashicorp/consul#4962]
#### Overview of the Issue

I have downloaded and set up a consul 1.3.0 single node server and so far I can register checks but I can't seem to get them working. I am upgrading from 0.7.1 so I know a few things need to change like `script` is now `args` . I have a few different check types that seem to be failing after the upgrade. I have included a few different checks that fail below, I have many similar ones but these should give me an idea of how to fix the rest.

I found this recent ticket that seems to be similar to mine though it hasn't be resolved yet and only includes script checks.

https://github.com/hashicorp/consul/issues/4943

#### Reproduction Steps

1. Install consul 1.3.0
2. Start consul using the below command
`/wd/consul/consul agent -server -bootstrap-expect 1 -data-dir /wd/consul_data -bind 10.0.0.38 -enable-script-checks=true`
3. Register script health check using the below JSON
```
{
  "ID": "cpu",
  "Name": "CPU health check",
  "Args": [ "/wd/scripts/check_linux_procstat.pl", "-w 85", "-c", "95" ],
  "Interval":  "30s"
}
```
4. Run the below command to see that status of each check
curl http://127.0.0.1:8500/v1/agent/checks | python -m json.tool
5. Result from previous command
```
"cpu": {
        "CheckID": "cpu",
        "CreateIndex": 0,
        "Definition": {},
        "ModifyIndex": 0,
        "Name": "CPU health check",
        "Node": "consul-testing-node-1",
        "Notes": "",
        "Output": "fork/exec /work-disk/scripts/check_linux_procstat.pl -w 85 -c 95: no such file or directory",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Status": "critical"
    }
```

Same steps as above except  step 3 is the below json and step 5 is the below output
**JSON**
```
{
      "ID": "portal",
      "Name": "Portal Health Check",
      "HTTP": "http://consul-testing-node-1:8080/configurableHealthCheck",
      "Interval": "30s"
    }
```
**Output**
```
{
        "CheckID": "portal",
        "CreateIndex": 43,
        "Definition": {},
        "ModifyIndex": 85,
        "Name": "Portal Health Check",
        "Node": "consul-testing-node-1",
        "Notes": "",
        "Output": "Get http://consul-testing-node-1:8080/configurableHealthCheck: dial tcp 10.7.1.5:8080: connect: connection refused",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Status": "critical"
    }
```

Similar to above but step is the below json and step 5 is the below output
**JSON**
```
{
	"Name": "Postgres check",
	"Args": ["/disk/check_postgres//check_postgres.pl", "-u", "consul", "-db", "consul", "--action connection"],
	"Interval": "20s"
}
```

**Output**
```
{
        "CheckID": "service:postgresql",
        "CreateIndex": 27,
        "Definition": {},
        "ModifyIndex": 80,
        "Name": "Postgres check",
        "Node": "consul-testing-node-1",
        "Notes": "",
        "Output": "Invalid arguments:\n  --action connection\n\nUsage: check_postgres.pl <options>\n Try \"check_postgres.pl --help\" for a complete list of options\n Try \"check_postgres.pl --man\" for the full manual\n",
        "ServiceID": "postgresql",
        "ServiceName": "postgresql",
        "ServiceTags": [
            "master"
        ],
        "Status": "critical"
    }

Manually run this script works fine so it is not the script causing the issue, script also gives the right exit codes as it is the same as the old version I was using (0.7.1)
```
### Consul info for both Client and Server

```
/work-disk/consul/consul info
agent:
	check_monitors = 4
	check_ttls = 0
	checks = 13
	services = 10
build:
	prerelease = 
	revision = e8757838
	version = 1.3.0
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 10.7.1.5:8300
	server = true
raft:
	applied_index = 223
	commit_index = 223
	fsm_pending = 0
	last_contact = 0
	last_log_index = 223
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:3c18a838-8258-9545-dd02-a46186f6af2c Address:10.7.1.5:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 93
	max_procs = 8
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

OS: Ubuntu 16.04.5 LTS
Consul: 1.3.0
Config management: Chef

**Comment by pierresouchay** [comment]
-w 85 should probably be in 2 separate args, check that your pl script starts with #!/usr/bin/perl and is executable

**Comment by banks** [comment]
Thanks for the report!

The change was back in 1.0.0 IIRC - we no longer pass the string through to a shell to execute blindly. So you correctly changed the `script` string to an args array but as @pierresouchay mentions those need to be each separate token the shell would render otherwise they are treated as a singe argument possibly containing spaces.

Do pierre's tips help?

**Comment by jkwysdom** [comment]
@pierresouchay Putting -w 85 in different tags didn't change anything, I realized that just after posting and changed it then. 

Script starts with `#!/usr/bin/env perl` which should be fine considering the script ran before without issues and that it also can run fine manually. 

As for the others where the files are 'missing' any ideas on that? All files are owned by the consul user, have the correct permission (0755) I have also tried with wide open permissions that would remove that possible issue. 

@banks No his suggestion didn't help. See my above ^

**Comment by jkwysdom** [comment]
For the service check, any ideas on why that might be not working right?

**Comment by banks** [comment]
@jkwysdom I'd like to help find a minimal reproduction for this.

Can you try the simplest possible script check and see it it works? Maybe something like `args: ["echo", "OK"]`?

Can you tell us about your environment - is consul running on bare metal/vm/container? Is /work-disk/ a physical device? chroot? network disk? etc. How is consul agent being run/supervised (I assume systemd)? 

As mentioned on the other ticket file not found from exec can be caused by some unexpected cases like any binary being forked from your script linking a library that isn't found or similar. Can you verify the following please:

 - If you su to the consul user you can still exec the script
 - If yes, can you dump `env` locally (don't paste it without redacting anything sensitive of course!)
 - Can you run `args: ["env"]` as a check and observe it's output?
 - If yes, are there significant differences in the PATH or LD_PRELOAD or anything else suspicious?

**Comment by jkwysdom** [comment]
@banks  Thanks for the help so far

I added a new check with the args like you suggested and the result was a passing check. 

My ENV is a Azure VM with DNS pointing directly to it. Work disk is just a directory I created to use a a central place to store things and make life easier for me as a lot of stuff gets stored there. My consul user has proper permissions to access everything in the /work-disk/consul directory and /work-disk is open to everyone (777). Consul is being started via a ruby script (from when we used 0.7.1) that worked well for us so far and I would like to avoid changes to it since it is in a language that I barely understand, ruby.

This is the command after I replace the variables with their default values except I didn't fill in the `-bind` value

/work-disk/consul/consul agent -server -bootstrap-expect 1 -data-dir /work-disk/consul/data -bind " + @@local_host + " -enable-script-checks=true


1. I can run all script I am having issues with as the consul user without using sudo 
2. I think this is what you were asking for

```
XDG_SESSION_ID=2583
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=<IP> 61696 22
SSH_TTY=/dev/pts/0
USER=john
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/john
PATH=/home/john/bin:/home/john/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/john
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/john
LOGNAME=john
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
SSH_CONNECTION=<IP> 61696 10.7.1.5 22
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/1000
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
```

3.  Output of test health check with the `env` arg
```
"test": {
        "CheckID": "test",
        "CreateIndex": 0,
        "Definition": {},
        "ModifyIndex": 0,
        "Name": "test",
        "Node": "consul-testing-node-1",
        "Notes": "",
        "Output": "SUDO_GID=1000\nMAIL=/var/mail/root\nUSER=root\nLANGUAGE=C.UTF-8\nSHLVL=1\nHOME=/home/john\nSUDO_UID=1000\nLOGNAME=root\n_=/work-disk/consul/manage_consul.rb\nTERM=xterm-256color\nUSERNAME=root\nPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin\nLANG=C.UTF-8\nLS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:\nSUDO_COMMAND=/usr/bin/chef-client\nSHELL=/bin/bash\nSUDO_USER=john\nLC_ALL=C.UTF-8\nPWD=/\n",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "Status": "passing"
    }
```

4. I don't see LD_PRELOAD

**Comment by jkwysdom** [comment]
I managed to resolve the missing file errors I was getting (I will comment on that other ticket to inform that OP). I had to add `"/usr/bin/perl",` to the start of my args for perl scripts and a similar one for ruby scrips too, I assume the same for bash scripts. 

Still not sure about the service checks, they are still failing.

**Comment by banks** [comment]
> Consul is being started via a ruby script

What runs/supervises the ruby script? Systemd?

Couple of things:

 - your check on the consul server is running as `root` (`USER=root`) vs `john`. Please don't run Consul as root!
 - the `PATH` is different: `/home/john/bin:/home/john/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin` vs `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin`. If any of the ruby gems or dependencies your scipt needs were installed as `john` they likely are the reason you are not able to see the same.

> I can run all script I am having issues with as the consul user without using sudo

I'm not sure I quite understand - from the ENV it looks like Consul is running under `sudo` (`SUDO_USER=john` which means it's in a `root` shell but sudo was somewhere in the path.

So can you try running the script outside Consul with `sudo /wd/scripts/check_linux_procstat.pl` and see if you get the same?

**Comment by jkwysdom** [comment]
> What runs/supervises the ruby script? Systemd?

I'm not exactly sure, it is just a script we run that starts consul. We run this script almost always through chef.

Consul is not running under root, it is started using the user `consul`. I know enough to not run it as root. 

I did solve the ruby script issue as well as the perl and bash one. 

Any and all scripts that were the issue can be run by the consul user. See my last comment, I resolved the missing file issue. My issue with the service checks failing still persists.

**Comment by banks** [comment]
> Consul is not running under root, it is started using the user consul. I know enough to not run it as root.

Hmm the consul agent directly execs the binary you pass it which in this case was just `env` so it runs as _the same user consul is running as_. If `env` showed `USER=root` then I'm pretty sure your consul is running as root somehow. Did you just start a consul instance manually with `sudo` in this case to test or was that the real chef-provisioned Consul agent?

> We run this script almost always through chef.

Chef has to run as root (usually via sudo) to make changes it needs to your system. If it is just running the script directly then the script presumably runs as root. This is not a great way to run Consul even without the root thing, what happens if the ruby script crashes or gets killed by OOM killer? Really sorry if this is all basic stuff for you, I'm just trying to figure out exactly what is going on based on the results you posted and your responses and it's always hard to gauge how much understanding is being assumed!

If your chef cookbook is installing it as a service then it is probably using systemd under the hood but I'd really double check on the user it's running on as it seems from what you posted that the script Consul ran as was root under sudo! If you can share you chef cookbook or script I can maybe help more.

> I did solve the ruby script issue as well as the perl and bash one.

Great!

> Any and all scripts that were the issue can be run by the consul user

Can you be specific, is the Consul user `john` here? since your pasted results from both user `john` and the actual Consul check ENV seemes to show `root` via `john` running sudo.

**Comment by banks** [comment]
> My issue with the service checks failing still persists.

Can you post specifics. Everything I see in this thread so far seems to be about the file not found issue - if you could post logs and check output etc. for the now failing check that would help. Thanks!

**Comment by jkwysdom** [comment]
> Did you just start a consul instance manually with sudo in this case to test or was that the real chef-provisioned Consul agent?

Consul is being started by our script which runs as the consul user and does not have sudo anywhere in the script.

> Really sorry if this is all basic stuff for you, 

No worries, if it gets the result I am looking for I'd rather it be a simple issue and we find it than it actually be a complex one or a consul issue. So far just been my wrong config

>This is not a great way to run Consul even without the root thing

The decision to run it via chef bash block with the user as consul was made a while before I got this job and I was told make as little modifications as possible though I will look into who owns the consul process.

> Can you be specific, is the Consul user john here? since your pasted results from both user john and the actual Consul check ENV seemes to show root via john running sudo.

I messed up when I posted that because it should have been ran when I was the consul user but instead I was using a dummy user we have for testing things. 

I attached at the bottom of this comment what it should have been

> Can you post specifics.

See my OP that was the only place it got touched on. There is an example there for what I am talking about.


```
SHELL=/bin/bash
TERM=xterm-256color
USER=consul
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MAIL=/var/mail/consul
PATH=/home/consul/bin:/home/consul/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
PWD=/home/consul
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/consul
LOGNAME=consul
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
LESSOPEN=| /usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
```

**Comment by banks** [comment]
Can you just sanity check for me - i'm trying to understand how the `env` check printed `USER=root` and `SUDO_USER=john` if it was executed by Consul running as `consul`.. Consul has no way to elevate it's privs and it should't alter the ENV either.

Can you try `ps aux | grep consul` and find out for sure what user it's running as?

> There is an example there for what I am talking about.

The other two script errors I see are:

> Invalid arguments:\n  --action connection\n\nUsage: check_postgres.pl <options>\n Try \"check_postgres.pl --help\" for a complete list of options\n Try \"check_postgres.pl --man\" for the full manual\n

and

> Get http://consul-testing-node-1:8080/configurableHealthCheck: dial tcp 10.7.1.5:8080: connect: connection refused

Are these what you are still seeing?

The first seems to be because of `"--action connection"` but I think you said you sorted that.

The seconds seems to be a network connectivity issue - not sure that can be related to Consul? Can you crul that endpoint from the host outside of Consul?

**Comment by jkwysdom** [comment]
Closed, got a fresh set of eyes from a co-worker and they noticed that we currently don't have that service check working in prod for an unknown reason but it is not important. Though it seems that consul 1.3.0 now reports critical services in the health check API calls. Going to have to look into how to disable that so our pager duty doesn't go off non stop
