### ISSUE TITLE
Versioned Documentation

### ISSUE THREAD

**Issue by alex-driedger-hs** [hashicorp/consul#4964]
#### Feature Description

On the documentation page, be able to select the version of the docs you want to view. This could be a dropdown that defaults to the most recent

For example, [React Native has versioned docs](https://facebook.github.io/react-native/versions).

#### Use Case(s)

Our team is running an older version of consul (0.7) and it would be very useful to see the documentation for that version, instead of having to guess what features have been added/removed since then.

**Comment by joewilliams** [comment]
Another +1 for this, we are running into this quite a bit since we don't run the latest consul.

**Comment by elee** [comment]
This would be helpful as building the docs from source is non-trivial.

**Comment by anthony-coder** [comment]
Versioned Documentation would be useful since we're leveraging older versions of consul

**Comment by i0rek** [comment]
We absolutely agree and this is something we are working on. Closing this issue since there is no point in keeping it open.

**Comment by blake** [comment]
Hi folks, PR #11327 finally introduced versioned documentation to the Consul website. The website now has docs for the most recent end-of-support version (1.8.x) and the current supported releases (1.9.x, 1.10,x and 1.11.x).
