### ISSUE TITLE
Website: redirects are incorrect

### ISSUE THREAD

**Issue by Pxlatn** [hashicorp/consul#4973]
#### Overview of the Issue

Website redirects are not being correctly processed.

Requests to https://www.consul.io/intro/getting-started/install.html get 301 redirected to https://www.consul.iohttps://learn.hashicorp.com/consul/getting-started/install.html

#### Reproduction Steps

1. Follow link to https://www.consul.io/intro/getting-started/install.html
2. Observe incorrect redirect.

### Consul info for both Client and Server

N/A

### Operating system and Environment details

Firefox 63.0.1

### Log Fragments

```
> GET /intro/getting-started/install.html HTTP/1.1
> User-Agent: curl/7.38.0
> Host: www.consul.io
> Accept: */*
> 
< HTTP/1.1 301 https://www.consul.iohttps://learn.hashicorp.com/consul/getting-started/install.html
< Retry-After: 0
< Content-Length: 0
< location: https://www.consul.iohttps://learn.hashicorp.com/consul/getting-started/install.html
```

**Comment by banks** [comment]
@Pxlatn thanks for the heads-up.

This was due to a change we made to add a different redirect just now. Turns out the old ones were added via a different mechanism. Will be fixed shortly.

**Comment by Pxlatn** [comment]
Hi, this issue is actually still present.
Following the link in the issue still redirects as reported.

**Comment by banks** [comment]
Thanks @Pxlatn! It _was_ fixed on Friday but due to a miscommunication was undone by subsequent website update 😄. CDN cache behaviour added an extra element of misdirection into the mix too.

This should be fixed for good now.

**Comment by banks** [comment]
(If you still see the bad redirect, your browser could be caching the old one - try in a private browsing window etc.)
