### ISSUE TITLE
(code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by satheeshCharles** [hashicorp/consul#4976]
Team,
Consul not starting with basic configuration 

#### Overview of the Issue

As described in the https://learn.hashicorp.com/vault/operations/ops-vault-ha-consul.html have configured my system. However when I try to start the service getting the below error. I have verified all the files/permissions. 

#### Reproduction Steps

Steps to reproduce this issue:
> vi /usr/local/etc/consul/client_agent.json
```
{
  "server": true,
  "node_name": "consul_s1",
  "datacenter": "dc1",
  "data_dir": "/var/consul/data",
  "bind_addr": "0.0.0.0",
  "client_addr": "0.0.0.0",
  "advertise_addr": "10.1.42.101",
  "bootstrap_expect": 3,
  "retry_join": ["10.1.42.101", "10.1.42.102", "10.1.42.103"],
  "ui": true,
  "log_level": "DEBUG",
  "enable_syslog": true,
  "acl_enforce_version_8": false
}



```
/etc/systemd/system/consul.service
```

[Unit]
Description=Consul server agent
Requires=network-online.target
After=network-online.target

[Service]
User=consul
Group=consul
PIDFile=/var/run/consul/consul.pid
PermissionsStartOnly=true
ExecStartPre=-/bin/mkdir -p /var/run/consul
ExecStartPre=/bin/chown -R consul:consul /var/run/consul
ExecStart=/usr/local/bin/consul agent \
    -config-file=/usr/local/etc/consul/server_agent.json \
    -pid-file=/var/run/consul/consul.pid
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
KillSignal=SIGTERM
Restart=on-failure
RestartSec=42s

[Install]
WantedBy=multi-user.target
```
OS : CentOS Linux release 7.5.1804 (Core)

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = f2b13f30
        version = 1.3.1
consul:
        known_servers = 0
        server = false
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 41
        max_procs = 4
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 2
        members = 1
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

CentOS Linux release 7.5.1804 (Core)

### Log Fragments

$ sudo systemctl start consul
$ sudo systemctl status consul

`● consul.service - Consul server agent
   Loaded: loaded (/etc/systemd/system/consul.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2018-11-19 11:25:53 HKT; 8s ago
  Process: 30717 ExecStart=/usr/local/bin/consul agent -config-file=/usr/local/etc/consul/server_agent.json -pid-file=/var/run/consul/consul.pid (code=exited, status=1/FAILURE)
  Process: 30714 ExecStartPre=/bin/chown -R consul:consul /var/run/consul (code=exited, status=0/SUCCESS)
  Process: 30712 ExecStartPre=/bin/mkdir -p /var/run/consul (code=exited, status=0/SUCCESS)
 Main PID: 30717 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/consul.service

Nov 19 11:25:53 devops-node-01.novalocal systemd[1]: consul.service: main process exited, code=exited, status=1/FAILURE
Nov 19 11:25:53 devops-node-01.novalocal systemd[1]: Unit consul.service entered failed state.
Nov 19 11:25:53 devops-node-01.novalocal systemd[1]: consul.service failed.
`

**Comment by banks** [comment]
Hi, the log doesn't actually show any Consul output that would help figure out why it's not starting.

Can you try to run `consul validate /usr/local/etc/consul/client_agent.json` to see if it's a config error? (Mostly likely reason for immediate termination). If that doesn't help, can you paste the output from `journald` to see what Consul is actually erroring with?

**Comment by satheeshCharles** [comment]
Hi, @banks  Thanks for the assistance. Consul has back online with the cluster. Thanks.

**Comment by banks** [comment]
@satheeshCharles glad to hear you are up and running. 

If you get a chance to describe the error you saw it might help future searchers who come across this!

**Comment by venkatatmecs** [comment]
consul validate /etc/consul.d/ui.json
Config validation failed: data_dir cannot be empty

**Comment by venkatatmecs** [comment]
root@ubuntu:~# systemctl status consul
● consul.service - Consul
   Loaded: loaded (/etc/systemd/system/consul.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-06-01 02:41:04 PDT; 10min ago
     Docs: https://www.consul.io/
  Process: 97481 ExecStart=/usr/bin/consul agent -server -ui -data-dir=/tmp/consul -bootstrap-expect=1 -node-vault -
 Main PID: 97481 (code=exited, status=1/FAILURE)

Jun 01 02:41:04 ubuntu consul[97481]:             Sets the server port to listen on.
Jun 01 02:41:04 ubuntu consul[97481]:   -syslog
Jun 01 02:41:04 ubuntu consul[97481]:             Enables logging to syslog.
Jun 01 02:41:04 ubuntu consul[97481]:   -ui
Jun 01 02:41:04 ubuntu consul[97481]:             Enables the built-in static web UI server.
Jun 01 02:41:04 ubuntu consul[97481]:   -ui-dir value
Jun 01 02:41:04 ubuntu consul[97481]:             Path to directory containing the web UI resources.
Jun 01 02:41:04 ubuntu consul[97481]: ==> error parsing flags: flag provided but not defined: -node-vault
Jun 01 02:41:04 ubuntu systemd[1]: consul.service: Main process exited, code=exited, status=1/FAILURE
Jun 01 02:41:04 ubuntu systemd[1]: consul.service: Failed with result 'exit-code'.
lines 1-17/17 (END)



How to resolve it?

**Comment by mkeeler** [comment]
@venkatatmecs I think your issue is that you need `-node=vault` instead of `-node-vault` in your cli arguments to start Consul.

**Comment by sarath998** [comment]
● consul.service - "HashiCorp Consul - A service mesh solution"
     Loaded: loaded (/lib/systemd/system/consul.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-08-04 11:39:34 IST; 26min ago
       Docs: https://www.consul.io/
   Main PID: 53068 (code=exited, status=203/EXEC)

Aug 04 11:39:34 sarath systemd[1]: consul.service: Scheduled restart job, restart counter is at 5.
Aug 04 11:39:34 sarath systemd[1]: Stopped "HashiCorp Consul - A service mesh solution".
Aug 04 11:39:34 sarath systemd[1]: consul.service: Start request repeated too quickly.
Aug 04 11:39:34 sarath systemd[1]: consul.service: Failed with result 'exit-code'.
Aug 04 11:39:34 sarath systemd[1]: Failed to start "HashiCorp Consul - A service mesh solution".


i don't know how to solve this plz anyone can help me...

**Comment by blake** [comment]
Hi @sarath998, can I recommend opening a thread in the Consul section of [HashiCorp's discuss forum](https://discuss.hashicorp.com/)? That would be a better place to discuss and troubleshoot this issue. Thanks.
