### ISSUE TITLE
KV Import Not Working

### ISSUE THREAD

**Issue by Emmo213** [hashicorp/consul#4981]
#### Issue Description
Unable to import KV pairs from file

#### Reproduction Steps

1) Add a new KV pair:  `consul kv put redis/config/connections 5`
2) Export to a file: `consul kv export > kv.json`
This creates the following file:

`[
        {
                "key": "redis/config/connections",
                "flags": 0,
                "value": "NQ=="
        }
]`

3) Import the file:  `consul kv import kv.json`
Receiving error message of: Cannot unmarshal data: invalid character 'k' looking for beginning of value

I also tried clearing out the KV pair before doing an import in case there was an issue with overwriting an existing value - it didn't make a different, I'm still receiving the same error. 

### Consul info 
<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 0bddfa2+
	version = 1.4.0
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 182
	commit_index = 182
	fsm_pending = 0
	last_contact = 0
	last_log_index = 182
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:a8521226-e200-456c-d889-44f62a81799f Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 81
	max_procs = 8
	os = darwin
	version = go1.11.2
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1

```

</details>

### Operating system and Environment details

Just installed Consul v1.4.0 through Brew on OSX 10.13.6.

**Comment by rboyer** [comment]
The syntax of `consul kv import` for reading from a file is:
```
consul kv import @filename.json
```

If you prefix your filename with '@' it should work.

**Comment by Emmo213** [comment]
Thank you, I got it. 

In case anybody else runs across this in the future, the file name does NOT have the '@' symbol but when you're importing the file it needs to have the '@' symbol. 

``<machine_name>:<user_name>$ ls kv.json``
``kv.json``
``<machine_name>:<user_name>$ consul kv import \@kv.json``
``Imported: redis/config/connections``

**Comment by chris-aeviator** [comment]
running into this with `@` even

```
/tmp # cat kv-prod.json
[
	{
		"key": "config-prod/service/drupal",
		"flags": 0,
		"value":
...

		"value": "ewogICAgY29va2llX2h0dHBvbmx5OiB0cnVlCiAgfQ=="
	},
]
```

```
/tmp # consul kv import @kv-prod.json
Cannot unmarshal data: invalid character ']' looking for beginning of value
```
