### ISSUE TITLE
GET /connect/intentions endpoint doesn't respond with a X-Consul-Index header

### ISSUE THREAD

**Issue by johncowen** [hashicorp/consul#4989]
#### Overview of the Issue

The `GET /connect/intentions` endpoint doesn't respond with a `X-Consul-Index` header

This means HTTP blocking queries for intention listing is not currently possible.

**Comment by johncowen** [comment]
Bit more info here:

`curl -i http://localhost:8500/v1/connect/intentions`

I've noticed that other headers 'could' be missing here also:

```
Content-Type: application/json
Vary: Accept-Encoding
Date: Thu, 29 Nov 2018 09:51:37 GMT
Content-Length: 2
```

There are no `X-Consul-*` headers, not sure if this should also have `X-Consul-Knownleader` etc also?

**Comment by kainoaseto** [comment]
Hi @johncowen I have been seeing this same issue and believe to have fixed it in this PR #5355

Feel free to give it a try and see if it helps, I'm hoping we can get this merged in after getting some more eyes on it in case more work needs to be done.

**Comment by johncowen** [comment]
Hey @kainoaseto 

Thanks so much for this!

I'm sure the core team will take a look, but I'll give them a nudge also.

Thanks,

John

**Comment by kainoaseto** [comment]
No problem! Hopefully the fix is just this one change.

Awesome that sounds great, looking forward to the feedback from the core team.

**Comment by banks** [comment]
Thanks @kainoaseto for this fix!
