### ISSUE TITLE
Urgent-Unable to get checks based on checkid /v1/agent/check/:checkid

### ISSUE THREAD

**Issue by gouthamkunduru90** [hashicorp/consul#4995]
#### Overview of the Issue

I am trying to to get check details using check id but it is not working getting 404
tried endpoint GET /v1/agent/check/:checkid
#### Reproduction Steps

Steps to reproduce this issue, eg:

$ curl -X GET http://localhost:8500/v1/agent/check/39b0c205-ca1e-4f9e-5d31-98c2-1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**Comment by banks** [comment]
`39b0c205-ca1e-4f9e-5d31-98c2-1` is not a valid UUID. Our check IDs are not necessarily UUIDs but are whatever you gave it, but it's close enough to be suspicious.

Can you provide more information about how you registered the check?

On what basis is this issue "Urgent"?

**Comment by gouthamkunduru90** [comment]
@banks I writing a spring boot starter it registers service metadata to consul service registry. while deploying to PCF. I gave the checkid as pivotal cloud foundry service instance id-ttl. I am intentionally registering checkid as serviceid-ttl 
Below is my check object
{
    "39b0c205-ca1e-4f9e-5d31-98c2-1-ttl": {
        "Node": "master-1",
        "CheckID": "39b0c205-ca1e-4f9e-5d31-98c2-1-ttl",
        "Name": "person-service-1-ttl",
        "Status": "passing",
        "Notes": "",
        "Output": "",
        "ServiceID": "39b0c205-ca1e-4f9e-5d31-98c2-1",
        "ServiceName": "person-service",
        "ServiceTags": [
            "v1"
        ],
        "Definition": {},
        "CreateIndex": 0,
        "ModifyIndex": 0
    }

**Comment by gouthamkunduru90** [comment]
Looks like there is no Api endpoint with /v1/agent/check/<checkid> exists to invoke.. could you please confirm this... so that i can change the logic in my spring boot starter

**Comment by pierresouchay** [comment]
@gouthamkundur `/v1/agent/checks` give you the list of checks on your local agent

**Comment by gouthamkunduru90** [comment]
@pierresouchay Thanks for the response. I found that endpoint but my goal is to get a only one check object using checkid. I also found /v1/health/checks/<servicename> which returns all the checks for that particular service. Problem here is i have 10 instances of same service and each service instance is having a check associated with it[ for example i have a service with name person-service which is running in cloud foundry. i have scaled that service to 10. so now i have 10 service instances for person-service. Each service instance is having a check object]. so i am not finding a way to get a only one check object using its unique check object.

**Comment by pierresouchay** [comment]
.ServiceID will give you the instance

**Comment by gouthamkunduru90** [comment]
i can get the service instance using /v1/agent/service/:serviceID but i am unable to fetch the associated check using /v1/agent/check/:checkID

**Comment by pierresouchay** [comment]
Yes, but /v1/agent/services will give you the full list, filter all checks having the ServiceID you want

**Comment by gouthamkunduru90** [comment]
/v1/agent/services is not returning the checks  associated with the services

{
    "39b0c205-ca1e-4f9e-5d31-98c2-1": {
        "ID": "39b0c205-ca1e-4f9e-5d31-98c2-1",
        "Service": "person-service",
        "Tags": [
            "v1"
        ],
        "Meta": {
            "Region": "HDC",
          },
        "Port": 61***,
        "Address": "192.*.***.***",
        "Weights": {
            "Passing": 1,
            "Warning": 1
        },
        "EnableTagOverride": false
    },
    "43a5b50c-0ec3-4761-663d-fa68-0": {
        "ID": "43a5b50c-0ec3-4761-663d-fa68-0",
        "Service": "person-service",
        "Tags": [
            "v1"
        ],
        "Meta": {
            "Region": "HDC",
           },
        "Port": 61***,
        "Address": "192.1.***.***",
        "Weights": {
            "Passing": 1,
            "Warning": 1
        },
        "EnableTagOverride": false
    }

**Comment by gouthamkunduru90** [comment]
got it i can do that. 
my code actually look for the existence of the particular check every 10 mins. assume i have total 100 check objects to filter my check i need iterate a loop which is a expensive :(.. do you have any plan of implementing an endpoint like /v1/agent/checks/:checkID in the API.

**Comment by pierresouchay** [comment]
@gouthamkunduru90 how expensive? This does not seems like something very hard to compute.

Unless you are publishing thousands of services on a single node, performance is unlikely to be an issue.

I don't really get what you are trying to achieve. Furthermore, looking on the agent is a bit weird, since what you probably is to check against the catalog (for instance /v1/health/service/:service )

Here is a simple shell script you might look at to get inspiration that I am using daily to check consistency between an agent and its catalog, this script basically checks that all the checks of an agent are published well in the Consul Cluster by comparing the local checks and the content of the catalog:

```shell
#!/bin/bash

function usage {
  echo "USAGE: $0 [-l verbose|info|warn] NODE_TO_CHECK"
  exit 254
}

if test $# -lt 1
then
  usage
  exit 254
fi

verbose=info
while getopts "l:m:h" option
do
  case $option in
    l)
      verbose=$OPTARG
      ;;
    m)
      echo "-m OPTION is deprecated"
      ;;
    h)
      usage
      ;;
  esac
done
shift $((OPTIND-1))
AGENT_ADDRESS=$1

tmp_file=$(mktemp)
curl --retry-connrefused --retry 1 --connect-timeout 9 -fs $AGENT_ADDRESS:8500/v1/agent/checks?pretty -o "$tmp_file"
if [ $? -ne 0 ]
then
  nname=$(dig -x $AGENT_ADDRESS +short| grep -v -e '^$'||echo 'Cannot resolve Reverse')
  ping -c 1 -t 7 $AGENT_ADDRESS >/dev/null
  if [ $? -eq 0 ]
  then
    port_is_open=$(nc $AGENT_ADDRESS 8500 2>&1 || echo "Port 8500 is down")
    echo "[ERROR] Consul Agent $AGENT_ADDRESS seems down on $AGENT_ADDRESS:8500, but can ping it, FQDN: ${nname}, port status=$port_is_open"
    exit 250
  else
    echo "[ERROR] Machine $AGENT_ADDRESS is not reachable; FQDN: ${nname}"
    exit 251
  fi
fi
local_checks=$(jq -r '.[]|(.CheckID + ";"+ .Status)' "$tmp_file")


curl -fs $AGENT_ADDRESS:8500/v1/health/node/${AGENT_ADDRESS}?pretty -o "$tmp_file"||echo '[]' > "$tmp_file"
if test '[]' = $(head -n1 "$tmp_file")
then
  curl --retry-connrefused --retry 3 -fsS $AGENT_ADDRESS:8500/v1/agent/self -o "$tmp_file" || { echo "[ERROR] Cannot guess node name for $AGENT_ADDRESS"; exit 252; }
  node_name=$(jq -r ".Member.Name" "$tmp_file")
  if test $verbose = "verbose"
  then
    echo "[ INFO ] found node name=${node_name} from $AGENT_ADDRESS:8500/v1/agent/self"
  fi
  curl --retry-connrefused --retry 3 -fs $AGENT_ADDRESS:8500/v1/health/node/${node_name}?pretty -o "$tmp_file" || { echo "[ERROR] Cannot find node ${node_name} in $AGENT_ADDRESS:8500/v1/health/node/${node_name}"; exit 253; }
fi

cluster_checks=$(jq -r '.[]|(.CheckID + ";"+ .Status)' "$tmp_file")
errors=0
errors_list=""
num_checks=$(echo $local_checks | wc -w | tr -d ' ')
if [ $num_checks -gt 600 ]
then
  echo "[ WARN ] there are $num_checks checks to validate for $AGENT_ADDRESS, script $0 might timeout"
fi
for check_s in $local_checks
do
  check_id=$(echo $check_s|cut -d \; -f1)
  found=0
  for k in $cluster_checks
  do
    if [[ "$k" =~ "$check_id" ]]
    then
       found=1
       if [[ "$k" = "$check_s" ]]
       then
         if [[ "$verbose" = "verbose" ]]
         then
           echo "[  OK  ] for $check_id: LOCAL:$check_s VS $k"
         fi
       else
         if [[ "$verbose" != "warn" ]]
         then
           echo "[FAILED] for $check_id: LOCAL:$check_s VS $k"
         fi
         errors_list="$errors_list $check_id"
         errors=$((errors + 1))
       fi
       break
    fi
  done
  if [[ $found -eq 0 ]]
  then
    if [[ $verbose != "warn" ]]
    then
      echo "[FAILED] SERVICE $check_id MISSING in Cluster"
    fi
    errors_list="$errors_list $check_id"
    errors=$((errors + 1))
  fi
done
if test $verbose = "info"
then
  echo "[ INFO ] Services on agent $AGENT_ADDRESS: "$(echo $local_checks|tr ';' '\n'|wc -l)
  echo "[ INFO ] Services in cluster $AGENT_ADDRESS: "$(echo $cluster_checks|tr ';' '\n'|wc -l)
fi
if test $verbose = "verbose"
then
  echo "[ INFO ] Services on agent $AGENT_ADDRESS: $local_checks"
  echo "[ INFO ] Services in cluster $AGENT_ADDRESS: $cluster_checks"
fi
if test $errors = 0
then
  if test "$verbose" != "warn"
  then
    echo "[  OK  ] $AGENT_ADDRESS has No ERROR"
  fi
else
  echo "[FAILED] $AGENT_ADDRESS has $errors errors: $errors_list"
fi
exit $errors
```

**Comment by pearkes** [comment]
Given there hasn't been further discussion based on the suggestions/questions above I'm going to close this issue. It doesn't appear this is a bug, either. Thanks for the tips @pierresouchay!

**Comment by gouthamkunduru90** [comment]
Tips from @pierresouchay really helped to solve my problem. Thankyou so much
