### ISSUE TITLE
no cluster leader, three server pods running with normal state, but one cannot communicate with the other two

### ISSUE THREAD

**Issue by zmaxyan** [hashicorp/consul#5006]
There are 1 client and 3 servers.
The 3 server pod seems running with normal state.
The ser-1 cannot receive any information from ser-0 and ser-2
"[DEBUG] memberlist: Stream connection from=192.168.78.33:34780" there is only stream connection information of itself not others, so "[DEBUG] manager: Rebalanced 1 servers" 
but ser-0 and ser-2 can receive the stream connection information with each other
As the "bootstrap_expect" is set to 3, so  we get "No cluster leader" error

There is some warning at the start time "WARN] memberlist: Failed to resolve ...... no such host"

Can you help to solve this problem?

**Comment by pierresouchay** [comment]
You can try using IP address when doing the join command on servers OR, if it does not work, the the peers.json method (see in `data_dir/raft/peers.info`)

**Comment by pearkes** [comment]
Thanks for opening an issue! I think this is likely better suited for the  [Consul mailing list](https://www.consul.io/community.html). I'd also suggest providing configuration examples and other information to help folks on the mailing list help out. 

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.

**Comment by zmaxyan** [comment]
@pearkes I do not agree to close this issue.  The problem is still existed.
from the pod ser-1, using consul command:
consul members
Node               Address              Status  Type    Build  Protocol  DC   Segment
xxxx-dc1-ser-1  192.168.228.xxx:8301  alive   server  1.1.0  2         dc1  <all>
consul operator raft list-peers
Error getting peers: Failed to retrieve raft configuration: Unexpected response code: 500 (No cluster leader)

from the other pod(ser-0,ser-2,cli-0), using consul command:
consul members
Node           Address               Status  Type    Build  Protocol  DC   Segment
xxxx-dc1-ser-0       192.168.188.xx:8301  alive   server  1.1.0  2         dc1  <all>
xxxx-dc1-ser-2       192.168.101.xx:8301  alive   server  1.1.0  2         dc1  <all>
xxxx-dc1-cli-0        192.168.188.xx:8301  alive   client  1.1.0  2         dc1  <default>
consul operator raft list-peers
Error getting peers: Failed to retrieve raft configuration: Unexpected response code: 500 (No cluster leader)

**Comment by ssboopathi** [comment]
I also got the same issue.

**Comment by DUWENINK** [comment]
I got the same issue. Kindly give the solution.

**i use the fllow scripts in my vms**

`sc create consul binpath= "c:\Consul\consul.exe agent --data-dir c:\Consul\data --ui --server --bind=192.168.1.118 --client 0.0.0.0" start= auto`
`sc create consul binpath= "c:\Consul\consul.exe agent --data-dir c:\Consul\data --ui --server --bind=192.168.1.119 --join=192.168.1.118 --client 0.0.0.0" start= auto`
`sc create consul binpath= "c:\Consul\consul.exe agent --data-dir c:\Consul\data --ui --server --bind=192.168.1.120 --join=192.168.1.118 --client 0.0.0.0" start= auto`
but now it shows
`C:\Consul>consul members
Node       Address             Status  Type    Build  Protocol  DC   Segment
DWK-Node1  192.168.1.118:8301  alive   server  1.5.2  2         dc1  <all>
DWK-Node2  192.168.1.119:8301  alive   server  1.5.2  2         dc1  <all>
DWK-Node3  192.168.1.120:8301  alive   server  1.5.2  2         dc1  <all>`

C:\Consul>consul.exe operator raft list-peers
**Error getting peers: Failed to retrieve raft configuration: Unexpected response code: 500 (No cluster leader)**
**TheUI**:
![image](https://user-images.githubusercontent.com/16337239/61533118-75b5b080-aa5e-11e9-93aa-3312e3f31292.png)

**Comment by maggosourabh** [comment]
Do we have any solution on this. As we are also facing the same issue where all our consul nodes went in follower state.

**Comment by like-inspur** [comment]
I use consul-helm to install three nodes consul cluster on kubernetes and encounter that when one node down other two node all become follower, so there is no leader in the current two node cluster

**Comment by zhoub** [comment]
Same issue
