### ISSUE TITLE
Consul service name include '@' , Consul agent can't resolve right record by DNS Query.

### ISSUE THREAD

**Issue by xinyu7git** [hashicorp/consul#5007]
My Service Name: cn-bj2@mysql@usre-service-admin-public , because of some reasons , I cannot modify service name. 

dig @127.0.0.1 -p 8600 cn-bj2@mysql@usre-service-admin-public.service.consul  

but the command is invaild.

**Comment by i0rek** [comment]
Thanks for reporting. Your service name contains characters that are not allowed in DNS. Documented here: https://www.consul.io/docs/agent/services.html#service-and-tag-names-with-dns. I think you servicename is valid without the `@`.
