### ISSUE TITLE
consul watch and handler only work with a stdin in external script

### ISSUE THREAD

**Issue by ghost** [hashicorp/consul#501]
consul 0.4.1

3 consul server
2 consul agent

config watch on consul agent 1 . 

agent 1:

cat /etc/consul.d/watch.json
{
  "watches": [
   {
     "type": "keyprefix",
     "prefix": "web/",
     "handler": "/root/test.sh"
   }
  ]
}

handler script :

cat /root/test.sh
#!/bin/bash

date >> /root/watch.log

start consul agent as below:

/root/gocode/bin/consul agent -data-dir /tmp/consul -config-dir /etc/consul.d/ -client 192.168.2.62 -join 192.168.2.73

And Error as below:
2014/11/26 10:05:08 [INFO] consul: adding server consul-server2 (Addr: 192.168.2.72:8300) (DC: dc1)
    2014/11/26 10:05:08 [INFO] consul: adding server consul-server3 (Addr: 192.168.2.73:8300) (DC: dc1)
    2014/11/26 10:05:08 [INFO] consul: adding server consul-server1 (Addr: 192.168.2.71:8300) (DC: dc1)
    2014/11/26 10:05:08 [ERR] agent: Failed to invoke watch handler '/root/test.sh': write |1: broken pipe

then we change the handler script and it works 
cat /root/test.sh
#!/bin/bash
**read a**
date >> /root/watch.log

We have tested update the kv and the watch and handler  works without problem.

The question is why handler script need such an input ? even it don't need one?

The consul docs about watch (http://www.consul.io/docs/agent/watches.html) and said : 

**A handler should read it's input from stdin, and expect to read JSON formatted data. The format of the data depends on the type of the watch. Each watch type documents the format type, and because they map directly to an HTTP API, handlers should expect the input to match the format of the API.**

What is the correct way to make a handler to meet the above requirement?

**Comment by slackpad** [comment]
Closing this per the workaround in https://github.com/hashicorp/consul/issues/501#issuecomment-64699620.

**Comment by ArKam** [comment]
Hi everyone, I'm affraid I'll have to re-open this bug as I'm facing the exact same issue with python handlers (Python 3.4) even if I manage the stdin/json load.

Using the command line tool is almost working but wait for a stdin EOF which never come and so fill the handler with an infinite stdin data.
If we keyboard interrupt the signal the command success and the data (just a testing string) is repeating itself countlessly on the destination file of the handler.

Using the external script is failing immediately with the error: `agent: Failed to invoke watch handler`

**Comment by ArKam** [comment]
@slackpad ok, so, I've found out what's going on exactly with the `agent: Failed to invoke` error, indeed, you may end up with this kind of error if your unix user do not have available terminal or if the user do not have home directory.

Using the standard input is really handy, but indeed that introduce a bunch of other pitfalls.

**Comment by taharah** [comment]
I ran into the same issue with some Ruby scripts that I was using as watch handlers since I run Consul as a system user with no home directory or shell. I ended up writing a small bash wrapper script that sets up the necessary PATH and shell variables for the scripts to execute properly.

**Comment by kedare** [comment]
Any equivalent fix for a Powershell handler ?

I tried to use this without success:

`Read-Host | Out-Nul`

**Comment by dilipmevada** [comment]
Hi,
How can we i get updated values in my handler file.? 
What will be the code of lines for Handler file (.sh) file.?
