### ISSUE TITLE
Consul not able to joing cluster after system crash in kubernetes cluster

### ISSUE THREAD

**Issue by Baitanik** [hashicorp/consul#5028]
I have consul running in kubernetes cluster environment with quorum 3 ( (4/2)+1 = 3)
I have total 4 servers , so consul should support 1 node failure . 
 
Node      Address             State     Voter  RaftProtocol
consul-0  xxx.xx.xxx.22:8300  follower  true   3
consul-2  xxx.xx.xxx.21:8300  leader    true   3
consul-3  xxx.xx.xxx.6:8300   follower  true   3
consul-1  xxx.xx.xxx.14:8300  follower  true   3

Testing done : 1. 4 nodes consul cluster running .(consul-0 ,consul-1 , consul-2 , consul-3)
                        2. Simulate system failure for **consul-1**, disconnect one node from network (plug out network cable)
                        3. After some time join the plug (system start)
                        4. Now this consul -1 is not able to join back in the cluster . 

this is the log from consul -2 - leader : 
  2018/11/15 16:24:03 [INFO] serf: EventMemberJoin: consul-1.dc1 xxx.xx.xxx.14
    2018/11/15 16:24:03 [INFO] consul: Handled member-join event for server "consul-1.dc1" in area "wan"
    2018/11/15 16:24:03 [INFO] serf: EventMemberJoin: consul-1 xxx.xx.xxx.14
    2018/11/15 16:24:03 [INFO] consul: Adding LAN server consul-1 (Addr: tcp/xxx.xx.xxx.14:8300) (DC: dc1)
    2018/11/15 16:24:08 [WARN] raft: Heartbeat timeout from "xxx.xx.xxx.22:8300" reached, starting election
    2018/11/15 16:24:08 [INFO] raft: Node at xxx.xx.xxx.21:8300 [Candidate] entering Candidate state in term 67093
    2018/11/15 16:24:08 [INFO] raft: Election won. Tally: 2
    2018/11/15 16:24:08 [INFO] raft: Node at xxx.xx.xxx.21:8300 [Leader] entering Leader state
    2018/11/15 16:24:08 [INFO] raft: Added peer d45a6b9c-3fc7-37cb-b335-aac1ce7a1966, starting replication
    2018/11/15 16:24:08 [INFO] raft: Added peer 06e1cfad-9d83-0715-62df-b5cd7fbdb15e, starting replication
    2018/11/15 16:24:08 [INFO] raft: Added peer baff136e-0e88-43d4-5e2c-48803c3bfbdb, starting replication
    2018/11/15 16:24:08 [INFO] consul: cluster leadership acquired
    2018/11/15 16:24:08 [INFO] consul: New leader elected: consul-2
    2018/11/15 16:24:08 [INFO] raft: pipelining replication to peer {Voter d45a6b9c-3fc7-37cb-b335-aac1ce7a1966 xxx.xx.xxx.22:8300}
    2018/11/15 16:24:08 [INFO] raft: pipelining replication to peer {Voter 06e1cfad-9d83-0715-62df-b5cd7fbdb15e xxx.xx.xxx:8300}
    2018/11/15 16:24:08 [ERR] raft: peer {Nonvoter baff136e-0e88-43d4-5e2c-48803c3bfbdb xxx.xx.xxx.14:8300} has newer term, stopping replication
    2018/11/15 16:24:08 [INFO] raft: Node at xxx.xx.xxx.21:8300 [Follower] entering Follower state (Leader: "")
    2018/11/15 16:24:08 [ERR] consul: failed to wait for barrier: leadership lost while committing log
    2018/11/15 16:24:08 [INFO] consul: cluster leadership lost
    2018/11/15 16:24:08 [INFO] raft: aborting pipeline replication to peer {Voter d45a6b9c-3fc7-37cb-b335-aac1ce7a1966 xxx.xx.xxx.22:8300}
    2018/11/15 16:24:08 [INFO] raft: aborting pipeline replication to peer {Voter 06e1cfad-9d83-0715-62df-b5cd7fbdb15e xxx.xx.xxx:8300}

and in from client we were getting "no-cluster-leader" while connecting to consul ..

According to consul guide with 4 servers and quorum 3 , it should support 1 system crash and should automatically join in server starts . can you please help me with this one.

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
