### ISSUE TITLE
Azure azure-discovry not work on Azure China

### ISSUE THREAD

**Issue by xukai286** [hashicorp/consul#5040]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Azure azure-discovry not work on Azure China. The discovery call failed due to different REST endpoint between Azure and Azure China

#### Reproduction Steps

Steps to reproduce this issue, eg:

use terraform to deploy  azure single region  consul cluster on Azure China .
the consule could install successfully but join cluster faild.

the "consul monitor" shows:
2018/12/02 09:34:12 [ERR] agent: Join LAN: discover-azure: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/083f3fc7-4620-42f6-abfe-4080fa8bae8e/providers/Microsoft.Network/networkInterfaces?api-version=2015-06-15: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 3f48b5b2-2a99-4503-b2b3-c89c6ef2aab4 not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: ec5183be-502f-4dad-95e9-bdf3d9d70600\r\nCorrelation ID: f7615eab-2352-48e1-9216-5692d7e005c8\r\nTimestamp: 2018-12-02 09:34:12Z","error_codes":[90002],"timestamp":"2018-12-02 09:34:12Z","trace_id":"ec5183be-502f-4dad-95e9-bdf3d9d70600","correlation_id":"f7615eab-2352-48e1-9216-5692d7e005c8"}

there're some differences between Azure and Azure China.
they have the different REST endpoint
https://docs.azure.cn/zh-cn/articles/guidance/developerdifferences

eg:
for ARM:
global Azure: https://management.azure.com
China Azure: https://management.chinacloudapi.cn

Could we give  some config file to make the endpoint is configurable?

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by pearkes** [comment]
Thanks for opening this issue! I'm going to close it in favor of https://github.com/hashicorp/go-discover/issues/67 as that is the right place to track this.
