### ISSUE TITLE
hashicorp vault as backend storage

### ISSUE THREAD

**Issue by mkyc** [hashicorp/consul#5043]
#### Feature Description

allow to store consul data in Hashicorp vault. 

#### Use Case(s)

I'd love to store terraform state in consul, but it makes sense only if data is stored at rest. Using vault as storage for consul would solve this puzzle. I didn't find clear information that consul can store data encrypted.

**Comment by pearkes** [comment]
> I didn't find clear information that consul can store data encrypted.

This is certainly true and something we do want to solve but isn't easy by any means. Utilizing Vault for this could make sense but Vault commonly uses the [Vault storage backend](https://www.vaultproject.io/docs/configuration/storage/consul.html) to store data in Consul in an HA fashion. Using Vault to store Consul data (or even just keys to access it) would create quite the chicken-and-egg problem for that use-case.

> I'd love to store terraform state in consul

I'd actually recommend using a different remote state backend that solves these concerns out of the box then. There are many that provide lots of value beyond Consul's integration and solve the data-at-rest issue specifically.

Thanks for the suggestion!
