### ISSUE TITLE
Consul 1.3.0 not registering any checks or services

### ISSUE THREAD

**Issue by jkwysdom** [hashicorp/consul#5045]
#### Overview of the Issue

I am running consul 1.3.0 and it will not register any checks or services. As you can imagine this sucks. This is part of an upgrade and I have tested before and checks and services did register so I highly doubt that the code for registering is the cause. I am not going to include it since it is company specific and not a regularly formatted API call using curl and is a bit of a mess to follow.

#### Reproduction Steps

Download and put consul binary at /work-disk/consul/consul

Run this command to start the first server 
`/work-disk/consul/consul agent -server -bootstrap-expect 1 -data-dir /work-disk/consul_data -config-file /work-disk/consul/conf.json -bind 10.7.1.5 -enable-script-checks=true`

I should add that consul will not start if I do `-enable-script-checks true` compared to what I have now.

**conf.json**

```
{
  "acl_datacenter": "consul-testing",
  "acl_default_policy":"deny",
  "acl_down_policy": "deny",
  "acl_master_token": "<token>",
  "encrypt": "<enc key>==",
  "datacenter": "consul-testing"
}
```

### Consul info for both Client and Server

```
agent:
	check_monitors = 8
	check_ttls = 0
	checks = 16
	services = 8
build:
	prerelease = 
	revision = e8757838
	version = 1.3.0
consul:
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 10.7.1.5:8300
	server = true
raft:
	applied_index = 1117
	commit_index = 1117
	fsm_pending = 0
	last_contact = 0
	last_log_index = 1117
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:966ce68e-307d-8f0b-5f1c-25d064906690 Address:10.7.1.5:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 104
	max_procs = 8
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2
	members = 2
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3
	members = 2
	query_queue = 0
	query_time = 1
```
### Operating system and Environment details

Ubuntu 16.04 LTS provisioned using chef,has many cookbooks with different checks as well as some basic checks.

**Comment by pierresouchay** [comment]
@jkwysdom hard to tell, but do you use ACLs at registration time and are those ACLs correct?

You should at least provide logs on the agent to move on

**Comment by pierresouchay** [comment]
The logs are available with the 'consul monitor' command.

It is probably an ACL issue, you might have a look to /v1/agent/checks to see if you register properly. 

Giving the payload of registration would definitely help as well

**Comment by jkwysdom** [comment]
@pierresouchay Thanks, as for the checks registering properly to that route, if I use curl on loacalhost:8500/v1/agent/checks I get back just an empty json object. 

Just tried with the token when doing the check and they show up. Maybe that is something to change in a new release. Change it so that if you do an API call to a ACL protected route with no token that instead of returning empty it would return a 403 like other routes do.

One other question semi related, is there a doc page that goes over which API routes will return a blank either JSON object or an array?
