### ISSUE TITLE
Consul servers are not in sync version 0.8.4

### ISSUE THREAD

**Issue by hbmelachuru** [hashicorp/consul#5046]
We have 5 consul servers (0.8.4) and all the services are registered in the consul. But only one service that is, elasticsearch which is also 5 replicas has some issues in the consul. 
When i check the health of the service in consul for all the 5 elasticsearch replicas:

1. Consul server 1 has only 3 elasticsearch IPs that has been registered and is in passing state. I couldnot find the other 2. Not even in critical or warning state.
2. Consul server 2 has only 2 elasticsearch IPS that has been registered and is in passing state. We couldnot see the other 3 pods. 
3. Consul server 3 has only 4 elasticsearch IPS that has been registered and is in passing state.

So all the consul servers has different elasticsearch and the data is not in sync. This is happening only for elasticsearch and not for any other service.

I have restarted the consul servers one by one, and it started working fine and were able to see all the 5 pods in the consul server and the data is consistent in consul servers.
What could be the issue with consul servers?

Appreciate your quick response. Thank you in advance.

**Comment by ChipV223** [comment]
@hbmelachuru : Is it possible for you to share debug logging(preferably with the TRACE log level) from the server agents showing the issue? You can grab the logging by going to the Consul instances and run `consul monitor -log-level=TRACE`

**Comment by hbmelachuru** [comment]
Hi @ChipV223 ,
Thanks for your response,
I dont see any errror messages in the logs in all five servers. I have pasted the logs in the snippet.
`2018-12-03 20:13:08,169 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {sql.service.dc-env.consul. 28 1} (661.443µs) from client 10.0.36.1:10666 (udp)

2018-12-03 20:13:08,224 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {log.service.dc-env.consul. 1 1} (524.573µs) from client 10.0.68.1:18001 (udp)

2018-12-03 20:13:08,279 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {sql.service.dc-env.consul. 1 1} (516.738µs) from client 10.0.36.1:33537 (udp)

2018-12-03 20:13:08,290 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {log.service.dc-env.consul. 33 1} (408.049µs) from client 10.0.38.1:48587 (udp)

2018-12-03 20:13:08,293 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {v1.service.service.dc-env.consul. 1 1} (424.078µs) from client 10.0.68.1:17331 (udp)

2018-12-03 20:13:08,326 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {sql.service.dc-env.consul. 1 1} (321.904µs) from client 10.0.36.1:23521 (udp)

2018-12-03 20:13:08,417 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {auth.node.dc-env.consul. 1 1} (457.676µs) from client 10.0.28.1:39286 (udp)

2018-12-03 20:13:08,419 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {sql.service.dc-env.consul. 1 1} (476.419µs) from client 10.0.36.1:39615 (udp)

2018-12-03 20:13:08,428 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {ram.node.dc-env.consul. 28 1} (392.164µs) from client 10.0.28.1:7547 (udp)

2018-12-03 20:13:08,440 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {ram.node.dc-env.consul. 1 1} (515.111µs) from client 10.0.28.1:51319 (udp)

2018-12-03 20:13:08,464 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {ram.node.dc-env.consul. 1 1} (355.88µs) from client 10.0.28.1:38305 (udp)

2018-12-03 20:13:08,478 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {ram.node.dc-env.consul. 1 1} (366.596µs) from client 10.0.28.1:48087 (udp)

2018-12-03 20:13:08,491 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {ame.node.dc-env.consul. 1 1} (372.393µs) from client 10.0.28.1:1369 (udp)

2018-12-03 20:13:08,496 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {ram.node.dc-env.consul. 1 1} (466.31µs) from client 10.0.28.1:6074 (udp)

2018-12-03 20:13:08,498 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {log.service.dc-env.consul. 1 1} (275.179µs) from client 10.0.68.1:1727 (udp)

2018-12-03 20:13:08,514 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {log.service.dc-env.consul. 1 1} (446.261µs) from client 10.0.68.1:38638 (udp)

2018-12-03 20:13:08,536 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {log.service.dc-env.consul. 1 1} (613.5µs) from client 10.0.68.1:16234 (udp)

2018-12-03 20:13:08,694 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {log.service.dc-env.consul. 1 1} (539.243µs) from client 10.0.68.1:41753 (udp)

2018-12-03 20:13:08,780 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {ame.node.dc-env.consul. 1 1} (423.442µs) from client 10.0.38.1:15602 (udp)

2018-12-03 20:13:09,000 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:08 [DEBUG] dns: request for {v1.service.service.dc-env.consul. 1 1} (573.699µs) from client 10.0.68.1:10668 (udp)

2018-12-03 20:13:09,451 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:09 [DEBUG] dns: request for {zipkin.service.dc-env.consul. 28 1} (637.656µs) from client 10.0.25.1:52665 (udp)

2018-12-03 20:13:09,952 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:09 [DEBUG] dns: request for {sql.service.dc-env.consul. 28 1} (815.786µs) from client 10.0.38.1:19611 (udp)

2018-12-03 20:13:10,037 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:10 [DEBUG] dns: request for {zipkin.service.dc-env.consul. 1 1} (542.5µs) from client 10.0.26.1:64832 (udp)

2018-12-03 20:13:10,045 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:10 [DEBUG] http: Request GET /v1/health/state/any (7.218075ms) from=10.0.37.162:60940

2018-12-03 20:13:10,101 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:10 [DEBUG] dns: request for {zipkin.service.dc-env.consul. 28 1} (571.366µs) from client 10.0.36.1:21746 (udp)

2018-12-03 20:13:10,559 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:10 [DEBUG] dns: request for {log.service.dc-env.consul. 1 1} (480.593µs) from client 10.0.68.1:46854 (udp)

2018-12-03 20:13:11,370 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:11 [DEBUG] dns: request for {zipkin.service.dc-env.consul. 1 1} (609.288µs) from client 10.0.28.1:39132 (udp)

2018-12-03 20:13:11,728 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:11 [DEBUG] memberlist: Initiating push/pull sync with: 173.36.77.6:8302

2018-12-03 20:13:12,038 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:12 [DEBUG] dns: request for {graylog-pet-1.node.dc-env.consul. 1 1} (488.224µs) from client 10.0.38.1:43004 (udp)

2018-12-03 20:13:12,401 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:12 [DEBUG] dns: request for {v1.node.dc-env.consul. 1 1} (598.321µs) from client 10.0.36.1:29892 (udp)

2018-12-03 20:13:12,404 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:12 [DEBUG] dns: request for {v1.node.dc-env.consul. 28 1} (457.174µs) from client 10.0.36.1:45593 (udp)

2018-12-03 20:13:12,427 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:12 [DEBUG] dns: request for {v1.node.dc-env.consul. 1 1} (402.379µs) from client 10.0.36.1:46094 (udp)

2018-12-03 20:13:12,429 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:12 [DEBUG] dns: request for {v1.node.dc-env.consul. 28 1} (388.44µs) from client 10.0.36.1:55300 (udp)

2018-12-03 20:13:12,709 DEBG 'start_consul' stdout output:
    2018/12/03 20:13:12 [DEBUG] dns: request for {directory-authn-serviceer-v4-1.node.dc-env.consul. 28 1} (393.273µs) from client 10.0.36.1:38285 (udp)
`

**Comment by ChipV223** [comment]
Thank you for the info, @hbmelachuru 

Not sure if you saw the last part of my earlier comment, but can you provide some information about said services when registering them through Consul as it would helpful to know:

- How you are querying the services(DNS or HTTP)
- What does the catalog vs health checks say?
- Are the service checks flapping?

**Comment by hbmelachuru** [comment]
Hi @ChipV223 
Sorry, i missed the second part of your question.
1. I am querying DNS service for elasticsearch. ex: graylog-es.service.dc-env.consul
2. Health check shows as it is passing for the registered service. the command used for the health check query is curl http://localhost:8500/v1/catalog/service/graylog-es.
3. Yes, elasticsearch service check is flapping.

**Comment by pierresouchay** [comment]
@hbmelachuru To ensure what you are seing, you might try to launch this script at the same time on all servers:
[consul_check_services_changes.sh](https://raw.githubusercontent.com/pierresouchay/consul-ops-tools/master/bin/consul_check_services_changes.sh) http://<consul_server>:8500/v1/health/service/graylog-es

Do this for all your 5 servers at the same time in 5 terminals, and check whether the output changes at the same time. in theory it should!

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
