### ISSUE TITLE
Leader doesn't step down when establishLeadership fails

### ISSUE THREAD

**Issue by kyhavlov** [hashicorp/consul#5047]
Currently the leaderLoop method will periodically retry the establishLeadership operations until successful, instead of stepping down immediately after a failure. This could theoretically cause problems because it's still able to do other normal leader operations like reconciling nodes from Serf or KV read/writes while it's waiting to retry, which violates the assumption that establishLeadership has to succeed before we can handle requests as the leader.

We should look into this and see if there's any negative consequences to immediately stepping down as leader when the establishLeadership method returns an error.

**Comment by i0rek** [comment]
It seems to me that we do not retry `establishLeadership` periodically. The `leaderLoop` reconciles periodically: https://github.com/hashicorp/consul/blob/master/agent/consul/leader.go#L215-L216 but `establishLeadership` is not being called from the loop, only once after acquiring leadership: https://github.com/hashicorp/consul/blob/master/agent/consul/leader.go#L169.

`establishLeadership` is however called by `reassert` after restoring a snapshot: https://github.com/hashicorp/consul/blob/master/agent/consul/leader.go#L221-L222. `reassert` revokes leadership before it tries to establish it again.

That being said, I think we are doing everything correctly and there is no need to change anything.

**Comment by banks** [comment]
The bug I think @i0rek is that `establishLeadership` does a bunch of work that _must succeed_ for the leader to be in a healthy state. If it fails then the leader is not actually behaving like a leader and many of our invariants break for things like Connect CA, cleaning up state, replication etc.

So I don't think the leader loop should _retry_ `establishLeader` so much as it should fail hard and exit the leader loop and step down as leader when it fails.

The fact it doesn't is what can leave some specific errors that impact `establishLeader` to cause the leader to be in a broken state where it is only running with part of it's state and goroutines that we expect it to run so some features work and others get into "impossible" states like being nil when we assume established leader must have X setup etc.

In general an error from `establishLeader` means that the leader is not able to get into a healthy state where one or more of its expected sub processes are not initialised properly so I don't think it's ever right to continue trying to be leader in that state.

**Comment by i0rek** [comment]
There is some progress. I implemented leadership transition in raft and as soon that is merged and revendored in consul, we can finally step down if establishleadership fails. https://github.com/hashicorp/raft/pull/306.
