### ISSUE TITLE
[windows10 msys2 fish] consul -autocomplete-install

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5054]
Consul 1.4.1-dev

➜ consul -autocomplete-install
Error executing CLI: Did not found any shells to install

If you can point me to the source code that is responsible for the autocomplete-install part I can maybe take a look. Dont think this will make it on somebodies favorite list of things today XD Maybe include a option to just save the files manually like for example consul -autocomplete-install fish

Anyway just reporting

**Comment by pearkes** [comment]
We use the https://github.com/mitchellh/cli library, I'm sure that support for fish would be accepted there!
