### ISSUE TITLE
Doc noise reduction

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5055]
Learning Consul takes time and allot of space in your head. The problem is I dont have allot of space. So for me to learn something I need to compress information to make it fit in my head. My brain works simple. Find color and bold things and save it in a 4 bit neuron pointer. This fails when encountering

https://www.consul.io/docs/guides/leader-election.html

The last thing I want to store is how json is formatted :)

![image](https://user-images.githubusercontent.com/863731/49490637-25803a00-f851-11e8-8731-dd3723d902c9.png)

This is to minimal https://godoc.org/github.com/hashicorp/consul and this to verbose https://www.consul.io/docs good documentation is like husband and wife between developers and documentation writers. Developers sometimes need to do the dishes too and sometimes document writers have to watch a football match instead of a soapserie

**Comment by gertcuykens** [comment]
Example 2

![image](https://user-images.githubusercontent.com/863731/49535082-8d6f6880-f8c3-11e8-84cb-3d5c785565dd.png)

Let me explain why the above `Advanced Topic!` is misleading go to

https://www.consul.io/docs/commands/kv.html

Only developers who wrote consul know that if you want to create a kv session lock you need to use 

https://www.consul.io/docs/commands/kv/put.html#acquire

If you don't read the internal session document you have no idea what the session is for

**Comment by gertcuykens** [comment]
Example 3

![image](https://user-images.githubusercontent.com/863731/49535689-01f6d700-f8c5-11e8-9595-d90e8549c100.png)

Now what is wrong here, the red highlight is fine, and the hole documentation it's not that bad. Just a bit off feedback.

Imagine you want to learn me or grandpa the kv put command. First you tell me to do this 

consul kv put -base64 foo/encoded aGVsbG8gd29ybGQK

So I type it in with one finger and when I finally type it in and push on enter you then tell me, Nooo you deleted the data! :) Also I think you ment not the example above but the example that actually overwrites with a empty value which is one more above.

Also `If the -base64 flag is set, the data will be` -->decoded<-- `before writing:` confusing if you name the key  `foo/encoded` `consul kv put -base64 foo/encoded aGVsbG8gd29ybGQK`

**Comment by topfunky** [comment]
It sounds like you're trying to learn about several different Consul concepts. Is there a specific problem you're trying to solve or a task you want to achieve?

We currently have several kinds of documentation and learning resources including

- API documentation
- Reference architecture and implementation guides
- Step by step task guides
- High level theory

We're also building https://learn.hashicorp.com/consul/ where we will create sequences of topics that can help you work through a feature (such as using the KV store) or a role (such as an operator who is building a Consul cluster from scratch).

**Comment by gertcuykens** [comment]
I believe your doing a tremendous good job to try to make good documentation for consul. The 3 examples are just details on where it could be improved for me personally when i went through them.

So in summary 
- don't highlight stuff that isn't important like example 1 json formatting
- example 2 is personal preference. I believe that specific session part is mandatory to understand before you can use sessions. So you can't skip this as a advanced topic
- example 3, the warning should come first before the actually command
- be consistent in example 3 like the decode / encode naming

Also personal preference put https://godoc.org/github.com/hashicorp/consul as the higest priority before writing any other guides. A document writer should be constantly monitoring developers and tell them if there intention wasn't clear. When a document writer understand the godoc it will result in optimal guides and futuher documentation

**Comment by pearkes** [comment]
I think the highlight of https://godoc.org/github.com/hashicorp/consul being unhelpful is a good call-out and will impede folks trying to implement directly with Consul and perhaps should be its own issue.

The rest of your feedback is great but I don't feel is appropriate to track as a single issue so I am going to close it. I think we can collectively listen to it though and do our best to improve those areas as we continue to write more docs and evolve the formatting.
