### ISSUE TITLE
Can I get first level child keys of a specific parent key?

### ISSUE THREAD

**Issue by pain400** [hashicorp/consul#5057]
## command
I want to get child keys of app, so I exec command like this:
```
consul kv get -keys app/
```
And get result as follows:
```
app/cps
app/dab
app/sad
...
```
How can I get result as follows:
```
cps
dab
sad
...
```

## HTTP
I found consul also provide api to get child keys like privious command, I do a get request like this:
```
curl http://127.0.0.1:8500/v1/kv/app
```
But I get all keys that with 'app' prefix as following:
```
app/cps/datasource
app/cps/port
app/cps/domain
...
```
How can I get result like this:
```
cps
dab
sad
...
```

**Comment by pearkes** [comment]
There's not a way to do this via CLI/API now but I'd recommend just using something like `sed` or `jq`.

```
$ KEY=app
$ consul kv get -keys $KEY/
app/bar
app/foo
$ consul kv get -keys $KEY/ | sed -e "s/$KEY\///g"
foo
bar
```

Hope that helps!

**Comment by DanielYWoo** [comment]
I have a key with 300 child keys, and each key has 10000 child keys, that's 300x10000=3M keys. I have to load 3M keys to find the 3K keys. That's too bad.
