### ISSUE TITLE
KV: ConsulIndex 

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5063]
https://www.consul.io/api/kv.html

`ModifyIndex is the last index that modified this key. This index corresponds to the X-Consul-Index header value`

It would make way more sense to me to call it ConsulIndex instead to be consistent

```
[
  {
    "CreateIndex": 100,
    "ConsulIndex": 200,
    "LockIndex": 200,
    "Key": "zip",
    "Flags": 0,
    "Value": "dGVzdA==",
    "Session": "adf4238a-882b-9ddc-4a9d-5b6758e4159e"
  }
]
```
Can this issue be labeled v2 please, so when it is v2 time this get mentioned :)

**Comment by pierresouchay** [comment]
I tend to disagree here: it is the same value as X-Consul-Index at the exact moment where the value is modified, but it will be different of the current X-Consul-Index returned by Consul on each request eventually. At creation time, it will therefore be the same as CreateIndex, but to me this renaming is confusing. 

Thus for any key in the KV:

CreateIndex <= ModifiedIndex <= Current_X_Consul_Index

**Comment by gertcuykens** [comment]
Hmm you got a point there. Closing until I or somebody else can come up with a counter argument. PS Adding your explanation to the docs wouldn't hurt :)

**Comment by pierresouchay** [comment]
@gertcuykens Fell free to create a PR improving the doc :-)
