### ISSUE TITLE
Use go modules

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5068]
I know the vendor map has most things covert but still I believe go modules is the way to go and will be benefisial for the time there going to be a V2 

PS the ui-v2 map has my alarm bels going a bit because even if it's the gui, I think there is a more go modules way of doing it. (ui/v2)

**Comment by pearkes** [comment]
@gertcuykens We're definitely going to be moving to Go modules, and some of the libraries we use (such as [go-discover](https://github.com/hashicorp/go-discover) already are setup that way. Not quite sure when we will for sure but it is likely going to be aligned to the Go 1.12 release.

**Comment by maksim77** [comment]
Any news on this? Only Consul and Vaiult prevent us from switching to modules.

**Comment by pearkes** [comment]
@maksim77 we do use go modules now. #5517 among a few other PRs moved us there.
