### ISSUE TITLE
UI: agent type (server or leaf) and highlight leader

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5073]
http://127.0.0.1:8500/ui/dc/nodes

I think there is plenty of room and colors left to indicate which nodes are real servers and who is leader :)

Also there doesn't seem to be a API way to show the `node type` like `consul members` does?

![image](https://user-images.githubusercontent.com/863731/49684488-df3b0d00-fad4-11e8-8de5-dc1ce760e58d.png)

**Comment by pierresouchay** [comment]
I think the consul service is what you are looking for, however leader information is not available AFAIK in catalog

**Comment by gertcuykens** [comment]
![image](https://user-images.githubusercontent.com/863731/49689400-f43d8d80-fb20-11e8-9ef7-7ac85b24acb4.png)

Ok your right http://127.0.0.1:8500/ui/dc0/services/consul does show the servers, but it's a bit on the edge of knowing what to look for. Don't think it's far fetched to show consul information on the Nodes tab. We can introduce for example color borders. Black border is a leaf node. Magenta border consol server. And party parrot the leader :D

**Comment by johncowen** [comment]
Hey folks 👋 

I was actually looking at something related to this the other day. It sounds like what you might be asking for is a mix of what we already have plus possibly:

https://www.consul.io/api/status.html#get-raft-leader
https://www.consul.io/api/status.html#list-raft-peers
https://www.consul.io/api/agent.html#list-members

?

Does that sound right?

Thanks,

John

**Comment by gertcuykens** [comment]
Yes in summary differentiate
- leader
- client
- server

in the node tab with css for example border color

**Comment by dfredell** [comment]
I agree it would be nice to know from the UI which consul node is the leader. Currently I just hit the `/v1/status/leader` url.
I think a good way to represent leader would with an icon, maybe next to the green heath check. Just using a color wouldn't work for someone color blind, or using a screen reader.

**Comment by opihana** [comment]
@gertcuykens, we've got a PR in (see open PR link above) for part of this request, the leader UI. 

![image](https://user-images.githubusercontent.com/6323933/62475155-1cda5d80-b76a-11e9-8580-4e7a8906e5da.png)

Curious to hear more about your interest in seeing server and client information as well. What sort of tasks or use cases would that extra information help you achieve faster or easier? What decisions would that help you make?

**Comment by dfredell** [comment]
For me, I like knowing which node is the leader when I'm doing a rolling update. I will scale up to 6 consul servers. Stop the two old non leaders, then the old leader do a `consul leave` then stop the old leader. That way an old non leader don't become a leader for a minute. Probably not necessary but makes me happy.

**Comment by gertcuykens** [comment]
@opihana 

From consul doc
> Within each datacenter, we have a mixture of clients and servers. It is expected that there be between three to five servers. This strikes a balance between availability in the case of failure and performance, as consensus gets progressively slower as more machines are added. However, there is no limit to the number of clients, and they can easily scale into the thousands or tens of thousands.

So basically you want a small number of servers and allot of clients, so it matters allot if it's a server or a client. If you spin up servers by accident instead of clients, you would have a false impression everything is ok

**Comment by opihana** [comment]
@dfredell and @gertcuykens Great feedback, thank you. Your point, Gert, is more about making sure you understand the ratio of servers to clients easily. I'll keep that in mind when designing client/server indications on this page.
