### ISSUE TITLE
Docs: Grpc API docs missing?

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5075]
After enabling the grpc port I did 

`grpcurl -cacert ca.pem localhost:8502 -list`

Failed to construct request parser and formatter for "json": error creating message resolver: server does not support the reflection API

But that's not the problem :) The problem is I am missing proto files and at least a basic example how to use the grpc API

What I did find is the grpc check 

https://www.consul.io/docs/agent/checks.html

```
{
  "check": {
    "id": "mem-util",
    "name": "Service health status",
    "grpc": "127.0.0.1:12345",
    "grpc_use_tls": true,
    "interval": "10s"
  }
}
```

Which is nice although it doesn't mention anything about what tls certificates are being used are there the same as the consul cli ones or separate ones? And if separate where do you define them?

I expected that every http API call can be translated to a grpc call but can't find examples or at least proto files to play around with using grpcurl ?

**Comment by gertcuykens** [comment]
For the second question I found `Currently gRPC is only used to expose Envoy xDS API to Envoy proxies.`  See now that is something that should be highlighted in a box and defenatly a reference to a example guide :)

**Comment by pearkes** [comment]
By default it will not use provided TLS certificates in the check. This functions the same as the HTTP(s) check. You might be looking for https://www.consul.io/docs/agent/options.html#enable_agent_tls_for_checks which lets you use the agent certificates. 

I've opened https://github.com/hashicorp/consul/pull/5086 to help clarify this. Thanks!

**Comment by gertcuykens** [comment]
Perfect :) One more thing it's correct that specifying a complete separate tls certificate only for a specific https / grpc check is not possible right? So it must be either a valid or the same as the agent one?

Maybe mention that too in the doc that its currebtly not supported to specify separate https / grpc certificate? 

https://www.consul.io/docs/agent/checks.html
