### ISSUE TITLE
After restarting Consul client, services not advertised to Consul server

### ISSUE THREAD

**Issue by zonnie** [hashicorp/consul#5084]
#### Overview of the Issue

I'm having a very weird issue...I have 1 Consul server and 2 clients. One machine hosts both 1 server and 1 client and another hosts a client only.
While the server sees the client the catalog doesn't have the records for the remote Consul client (172.16.200.1). The members shows all nodes though.
This happened after I reset the remote client...Any idea ?
```
root@ubuntuServer:~# consul members
Node                    Address            Status  Type    Build  Protocol  DC  Segment
consul-server-85956785  172.16.99.1:8301   alive   server  1.4.0  2         gc  <all>
consul-client-15139172  172.16.200.1:8302  failed  client  1.4.0  2         gc  <default>
consul-client-50867366  172.16.99.1:8302   alive   client  1.4.0  2         gc  <default>
consul-client-83726090  172.16.200.1:8302  alive   client  1.4.0  2         gc  <default>
This reproduces easily by resetting 172.16.200.1...
The only workaround is to reset the Consul server (@ 172.16.99.1)
```
#### Reproduction Steps

Steps to reproduce this issue, eg:

1. 2 hosts - the first running both Consul server & client (different instances) + a host running only a Consul client. The first host has a Nomad server & client as well while the 2nd host has a Nomad client only.
1. Run `consul catalog services` - see all services
2. Restart the Consul client on the 2nd host
3. Run `consul catalog services` - see **ONLY** the services that run on the 1st host

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 5
build:
        prerelease =
        revision = 0bddfa23
        version = 1.4.0
consul:
        acl = disabled
        known_servers = 1
        server = false
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 57
        max_procs = 8
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 4
        failed = 1
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5
        members = 4
        query_queue = 0
        query_time = 1

```
</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 3
        services = 3
build:
        prerelease =
        revision = 0bddfa23
        version = 1.4.0
consul:
        acl = disabled
        bootstrap = true
        known_datacenters = 0
        leader = true
        leader_addr = 172.16.99.1:8300
        server = true
raft:
        applied_index = 614446
        commit_index = 614446
        fsm_pending = 0
        last_contact = 0
        last_log_index = 614446
        last_log_term = 4
        last_snapshot_index = 607410
        last_snapshot_term = 4
        latest_configuration = [{Suffrage:Voter ID:8d907f86-fc90-dfb2-cbaa-449e00118097 Address:172.16.99.1:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 4
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 126
        max_procs = 8
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 4
        failed = 1
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5
        members = 4
        query_queue = 0
        query_time = 1

```
</details>

### Operating system and Environment details

Linux Ubuntu 14.04, using the official Consul Docker container (1.4.0)

### Log Fragments

Not sure which logs to attach here...

**Comment by ChipV223** [comment]
Hi @zonnie , would it be possible for you to supply the trace-level debug logs of your server and client agents as well as any other logging showing the output of `consul catalog services` only displaying the services running on the 1st host? You can retrieve the debug logs by running `consul monitor -log-level=TRACE` on the machines running the agents

**Comment by zonnie** [comment]
The `consul catalog services` in case I see only the server located client:
```
root@ubuntuServer:~# gc-consul catalog services
consul
nginx
nomad
nomad-client
telegraf
telegraf-relay
zookeeper
root@ubuntuServer:~#
```
Attached the logs - I hope these is what you meant 
[client.txt](https://github.com/hashicorp/consul/files/2672720/client.txt)
[server.txt](https://github.com/hashicorp/consul/files/2672723/server.txt)

**Comment by zonnie** [comment]
Closing the issue - the problem was:
```
consul-client-15139172  172.16.200.1:8302  failed  client  1.4.0  2         gc  <default>
consul-client-83726090  172.16.200.1:8302  alive   client  1.4.0  2         gc  <default>
```
These two confused the Consul server - I was giving random names to nodes thinking it's only for display - the name change messed up Consul's server to think these are 2 different agents.
