### ISSUE TITLE
Consul not electing leader after upgrade 0.7.1 -> 1.3.1

### ISSUE THREAD

**Issue by jkwysdom** [hashicorp/consul#5092]
#### Overview of the Issue

I am upgrading from consul 0.7.1 to consul 1.3.1 and when I try the upgrade I can not get consul to elect a leader with the new versions. Logs show that it is electing a leader but the API call to `http://127.0.0.1:8500/v1/status/leader ` shows that no leader is elected on either node. 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster of 2 nodes using consul 0.7.1
2. Get consul 1.3.1 and unzip/rename
wget https://releases.hashicorp.com/consul/1.3.1/consul_1.3.1_linux_amd64.zip
unzip consul_1.3.1_linux_amd64.zip # rename to consul_1.3.1 when prompt'd
rm consul_1.3.1_linux_amd64.zip

3.Do this on all nodes
./consul leave

4. Then rename everything
mv consul consul_0.7.1
mv consul_1.3.1 consul
5. Finally re-run chef-client which in turn runs a ruby script that checks for existing nodes and if found will create a new regular server and but if no nodes exist it will use the -bootstrap flag to bootstrap the server.

Conf.json file

{
"client_addr": "0.0.0.0",
"datacenter": "consul-testing",
"acl_datacenter": "consul-testing",
"acl_default_policy":"deny",
"acl_down_policy": "deny",
"acl_master_token": "<master acl token>",
"acl_agent_token": "<agent acl token>",
"data_dir": "/work-disk/consul_data",
"domain": "consul",
"enable_script_checks": true,
"dns_config": {
"enable_truncate": true,
"only_passing": true
},
"enable_syslog": true,
"encrypt": "<enc key>==",
"leave_on_terminate": true,
"log_level": "INFO",
"rejoin_after_leave": true,
"server": true,
"start_join": ["10.7.1.5", "10.7.1.6"]
}

Commands used
/work-disk/consul/consul agent -bootstrap -data-dir /work-disk/consul_data -config-file /work-disk/consul/conf.json -bind 10.7.1.5
/work-disk/consul/consul agent -data-dir /work-disk/consul_data -config-file /work-disk/consul/conf.json -bind 10.7.1.5

### Operating system and Environment details

Ubuntu 16.04 LTS consul 1.3.1 is target version

### Log Fragments

2018/12/13 14:57:15 [INFO] consul: New leader elected: consul-testing-node-2
2018/12/13 14:57:16 [ERR] agent: Coordinate update error: No cluster leader
2018/12/13 14:57:17 [WARN] raft: Election timeout reached, restarting election
2018/12/13 14:57:17 [INFO] raft: Node at 10.7.1.5:8300 [Candidate] entering Candidate state in term 175
2018/12/13 14:57:17 [WARN] raft: Unable to get address for server id 10.7.1.6:8300, using fallback address 10.7.1.6:8300: Could not find address for server id 10.7.1.6:8300
2018/12/13 14:57:17 [ERR] agent: failed to sync remote state: No cluster leader

**Comment by ChipV223** [comment]
Hi @jkwysdom ! Looking at your config, I don't see anything that resembles `bootstrap_expect` which will tell Consul how many server agents need to be active in order to achieve quorum and elect a leader of the cluster. Can you try adding that field and restarting your agents to see if there are any improvements?

**Comment by jkwysdom** [comment]
@ChipV223 I had tried `bootstrap_expect` before when I was trying to set up a new cluster with 1.3.1 and it caused a ton off issues like chef-client failing  and no cluster leader there. I took that out and added `-boostrap` instead since I can only bootstrap one server. My ruby script looks for how many nodes and then if 0 nodes uses the bootstrap command otherwise it just runs the command without -bootstrap

**Comment by ChipV223** [comment]
Interesting. Is it possible for you to try starting the cluster w/o the use of chef(i.e. manually) and having `bootstrap_expect` set to the number of servers nodes that the cluster will have? Based on your earlier report about the issues when setting `bootstrap_expect`, I'm wondering if this could be an issues with the chef script you are using to create the cluster

**Comment by jkwysdom** [comment]
@ChipV223 Just gave that a try and, in the logs it said that it elected a new leader but when I use the api to check /status/leader endpoint I get back just `""` so doesn't seem to be selecting the leader.

**Comment by ChipV223** [comment]
Is it possible to see both the logs and the output of the `check /status/leader` endpoint, so we can take a look? Also how many server and client agents are you running on this environment so I can try to repro this on my end(I tested 1.3.1 previously with a 3-server-node test cluster where it was able to elect a leader, but that was a few weeks ago)

**Comment by jkwysdom** [comment]
@ChipV223 I am rebuilding my ENV as I think I may have a solution, if you look [here](https://www.consul.io/docs/upgrade-specific.html#raft-protocol-now-defaults-to-3) you notice that 1.3.1 would default to version 3, but [here](https://www.consul.io/docs/upgrade-specific.html#raft-protocol-version-compatibility) says that you can't jump more than one version which would be happening when I am going from 0.7.1 to 1.3.1 if I read that right. 

Okay finished setting it up before I commented, turns out the raft protocol was the issue. Would be nice if that was put on the upgrade page, that it is a known issue. Maybe an upgrade FAQ would be nice as I know I have had a hard time with the upgrade process and I have seen a lot of issues on here about the upgrade process too. A FAQ might cut down the number of issues reported.

**Comment by ChipV223** [comment]
@jkwysdom Glad to hear that you able to the cluster working after updating the protocol to version 3. We actually have [this section](https://www.consul.io/docs/upgrade-specific.html) in our Upgrade Consul guide that talks about the actions that needed to be taken when you leap from an older version such as 0.7.1 to 1.3.1, so please take a look at that when you have the opportunity!
