### ISSUE TITLE
add agent port number in log entry (8300)

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5100]
The only thing missing in the first log entry is the gossip agent port (8300) it self, can this be added for completeness please?
```
==> Consul agent running!
           Version: '1.4.1-dev'
           Node ID: 'eed4d3a8-44ee-ad14-f574-293e2e9fd92a'
         Node name: 'home'
        Datacenter: 'dc0' (Segment: '')
            Server: false (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: 8501, gRPC: 8502, DNS: 8600)
      Cluster Addr: ... (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: true, TLS-Outgoing: true, TLS-Incoming: true
```

Something like `Cluster Addr: …:8300 (LAN: 8301, WAN: 8302)`

**Comment by pearkes** [comment]
`8300` is the [server RPC port](https://www.consul.io/docs/agent/options.html#server_rpc_port) and doesn't deal with gossip. I don't think we need to output this in the startup log but we'd look at a potential PR for doing so. Not clear where it would go as it doesn't fit under cluster or client really.
