### ISSUE TITLE
consul restore from snapshot

### ISSUE THREAD

**Issue by viveksaiaws** [hashicorp/consul#5103]
**Background**
we use consul for vault storage backed hosted on Kubernetes environment  

**issue**
while restoring consul throwing error that `413 Request Entity Too Large`

**command**
`curl -k --request PUT --data-binary @/tmp/snapshot.tgz -H "@@@@" 
https://xxx.xxx.xxx/v1/snapshot`

**sanpshot size**
`7762322(7.4 MiB) snapshot.tgz`

**Error**
```
        "<html>", 
        "<head><title>413 Request Entity Too Large</title></head>", 
        "<body bgcolor=\"white\">", 
        "<center><h1>413 Request Entity Too Large</h1></center>", 
        "<hr><center>nginx</center>", 
        "</body>", 
        "</html>"
```

**Comment by pearkes** [comment]
Hey @viveksaiaws, looks like you have nginx proxying to Consul and perhaps have a configured nginx in such a way to limit the size of request bodies. I _believe_ you're looking for [`client_max_body_size`](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size).

I'm going to close this as I do not think it is an issue with Consul, but hope that helps.
