### ISSUE TITLE
Coredns consul plugin

### ISSUE THREAD

**Issue by gertcuykens** [hashicorp/consul#5108]
Kubernetes 1.13 will have coredns as default, maybe comsider making a coredns consul plugin?

a) Think it will reduce complexity if consul can offload all dns problems to coredns
b) Predicting coredns is going to be to motherload of all cloud dns servers

https://coredns.io/explugins/
https://coredns.io/plugins/

**Comment by mkeeler** [comment]
@gertcuykens DNS is a core feature of Consul and is not something we want to move out of Consul in favor of plugin integration with a third-party DNS server. For our many users that are using Consul’s DNS we do not want to have to ask them to install CoreDNS or any third-party software to make it work. Therefore it needs to remain a builtin part of Consul.

CoreDNS can already integrate with Consul so there is really no need for a plugin. The proxy plugin in CoreDNS can proxy DNS queries to Consul’s DNS server which will then do all the service discovery or prepared query execution.

Even with all of that, there is nothing to prevent someone in the community from writing a CoreDNS plugin that utilizes Consul’s API. Its just not something we want to pursue and maintain at this point in time.

**Comment by spdowling** [comment]
For anybody else looking for potential existing solutions, [segment produced a plugin previously](https://github.com/segmentio/coredns-plugins).
