### ISSUE TITLE
How do I enable acl functionality

### ISSUE THREAD

**Issue by stevenlee87** [hashicorp/consul#5109]
hello!

consul version:1.4.0
linux: CentOS Linux release 7.2.1511 (Core) 
docker run -d --net=host -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' --name=node1 consul agent -server -bind=10.100.68.142  -bootstrap-expect=3 -node=node1
docker run -d --net=host -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' --name=node2 consul agent -server -bind=10.100.67.81  -join=10.100.68.142 -node-id=$(uuidgen | awk '{print tolower($0)}')  -node=node2
docker run -d --net=host -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' --name=node3 consul agent -server -bind=10.100.64.75 -join=10.100.68.142 -node-id=$(uuidgen | awk '{print tolower($0)}') -ui -node=node3 -client=10.100.64.75
docker run -d --net=host -e 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' --name=node4 consul agent -bind=10.100.73.71 -retry-join=10.100.68.142 -node-id=$(uuidgen | awk '{print tolower($0)}') -node=node4

I read this documentation:
https://www.consul.io/docs/guides/acl.html

Bootstrapping ACLs
Bootstrapping ACLs on a new cluster requires a few steps, outlined in the examples in this section.

» Enable ACLs on the Consul Servers
The first step for bootstrapping ACLs is to enable ACLs on the Consul servers in the primary datacenter. In this example, we are configuring the following:

1.A primary datacenter of "dc1", which is where these servers are.
2.An ACL master token of "b1gs33cr3t"; see below for an alternative using the /v1/acl/bootstrap API
3.A default policy of "deny" which means we are in whitelist mode
4.A down policy of "extend-cache" which means that we will ignore token TTLs during an outage
Here's the corresponding JSON configuration file:

{
  "primary_datacenter": "dc1",
  "acl" : {
    "enabled": true,
    "default_policy": "deny",
    "down_policy": "extend-cache",
    "tokens" : {
      "master" : "b1gs33cr3t"
    }
  }
}

I execute the following command：
curl \
>     --request PUT \
>     http://127.0.0.1:8500/v1/acl/bootstrap
prompt：ACL support disabled

How do I get master tokens before I enable acl ?

**Comment by rboyer** [comment]
Hi,

There are two ways to bootstrap the ACL system:

1. By providing the `acl.tokens.master` field in the json configuration file with a value that you generate yourself (in the example above that is `b1gs33cr3t`).
2. By using the `/v1/acl/bootstrap` endpoint.

The first time the elected Consul Server Leader is restarted with the pre-seeded master token (1) it triggers an internal bootstrap operation using that value. After this bootstrap is completed the `acl.tokens.master` value in the configuration file is ignored.

If you did not provide a pre-seed value in the configuration file then you can use the HTTP API endpoint of `/v1/acl/bootstrap` exactly once (2), and internally it will generate a random value to use for the master token, persist it, and return it back to you for your records and future use.

You cannot use both at the same time. Here's what happens if you try to do both:

```
$ cat > config.json <<EOF
{
  "primary_datacenter": "dc1",
  "acl": {
    "enabled": true,
    "default_policy": "deny",
    "down_policy": "extend-cache",
    "tokens": {
      "master": "b1gs33cr3t"
    }
  }
}
EOF
$ consul agent -data-dir ./data  -bind 127.0.0.1  -server -bootstrap-expect 1 -config-file ./config.json 
BootstrapExpect is set to 1; this is the same as Bootstrap mode.
bootstrap = true: do not enable unless necessary
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.4.0'
           Node ID: 'f6d29d55-761e-7889-43ce-1abdfa8a37b8'
         Node name: 'laptop'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2018/12/18 10:20:21 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:f6d29d55-761e-7889-43ce-1abdfa8a37b8 Address:127.0.0.1:8300}]
    2018/12/18 10:20:21 [INFO] raft: Node at 127.0.0.1:8300 [Follower] entering Follower state (Leader: "")
    2018/12/18 10:20:21 [INFO] serf: EventMemberJoin: laptop.dc1 127.0.0.1
    2018/12/18 10:20:21 [INFO] serf: EventMemberJoin: laptop 127.0.0.1
    2018/12/18 10:20:21 [INFO] consul: Adding LAN server laptop (Addr: tcp/127.0.0.1:8300) (DC: dc1)
    2018/12/18 10:20:21 [INFO] consul: Handled member-join event for server "laptop.dc1" in area "wan"
    2018/12/18 10:20:21 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
    2018/12/18 10:20:21 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
    2018/12/18 10:20:21 [INFO] agent: Started HTTP server on 127.0.0.1:8500 (tcp)
    2018/12/18 10:20:21 [INFO] agent: started state syncer
    2018/12/18 10:20:28 [ERR] agent: failed to sync remote state: No cluster leader
    2018/12/18 10:20:30 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2018/12/18 10:20:30 [INFO] raft: Node at 127.0.0.1:8300 [Candidate] entering Candidate state in term 2
    2018/12/18 10:20:30 [INFO] raft: Election won. Tally: 1
    2018/12/18 10:20:30 [INFO] raft: Node at 127.0.0.1:8300 [Leader] entering Leader state
    2018/12/18 10:20:30 [INFO] consul: cluster leadership acquired
    2018/12/18 10:20:30 [INFO] consul: New leader elected: laptop

...now this is the relevant part showing the bootstrap-from-config-file happening...

    2018/12/18 10:20:30 [INFO] acl: initializing acls
    2018/12/18 10:20:30 [INFO] consul: Created ACL 'global-management' policy
    2018/12/18 10:20:30 [WARN] consul: Configuring a non-UUID master token is deprecated
    2018/12/18 10:20:30 [INFO] consul: Bootstrapped ACL master token from configuration
    2018/12/18 10:20:30 [INFO] consul: Created ACL anonymous token from configuration

...(remainder omitted)...
```

If you attempt to use the bootstrap HTTP endpoint now, this happens:
```
$ curl -sL 'http://localhost:8500/v1/acl/bootstrap' -XPUT
Permission denied: ACL bootstrap no longer allowed (reset index: 5)
```

If you wanted to exclusively use the HTTP API to bootstrap, this is what you'd do:
```
$ cat > config.json <<EOF
{
  "primary_datacenter": "dc1",
  "acl": {
    "enabled": true,
    "default_policy": "deny",
    "down_policy": "extend-cache"
  }
}
EOF
$ consul agent -data-dir ./data  -bind 127.0.0.1  -server -bootstrap-expect 1 -config-file ./config.json
BootstrapExpect is set to 1; this is the same as Bootstrap mode.
bootstrap = true: do not enable unless necessary
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.4.0'
           Node ID: '1b30bf36-05f2-e820-d5eb-561b7a0945f2'
         Node name: 'laptop'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2018/12/18 10:27:38 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:1b30bf36-05f2-e820-d5eb-561b7a0945f2 Address:127.0.0.1:8300}]
    2018/12/18 10:27:38 [INFO] raft: Node at 127.0.0.1:8300 [Follower] entering Follower state (Leader: "")
    2018/12/18 10:27:38 [INFO] serf: EventMemberJoin: laptop.dc1 127.0.0.1
    2018/12/18 10:27:39 [INFO] serf: EventMemberJoin: laptop 127.0.0.1
    2018/12/18 10:27:39 [INFO] consul: Adding LAN server laptop (Addr: tcp/127.0.0.1:8300) (DC: dc1)
    2018/12/18 10:27:39 [INFO] consul: Handled member-join event for server "laptop.dc1" in area "wan"
    2018/12/18 10:27:39 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
    2018/12/18 10:27:39 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
    2018/12/18 10:27:39 [INFO] agent: Started HTTP server on 127.0.0.1:8500 (tcp)
    2018/12/18 10:27:39 [INFO] agent: started state syncer
    2018/12/18 10:27:46 [ERR] agent: failed to sync remote state: No cluster leader
    2018/12/18 10:27:48 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2018/12/18 10:27:48 [INFO] raft: Node at 127.0.0.1:8300 [Candidate] entering Candidate state in term 2
    2018/12/18 10:27:48 [INFO] raft: Election won. Tally: 1
    2018/12/18 10:27:48 [INFO] raft: Node at 127.0.0.1:8300 [Leader] entering Leader state
    2018/12/18 10:27:48 [INFO] consul: cluster leadership acquired
    2018/12/18 10:27:48 [INFO] consul: New leader elected: laptop
    2018/12/18 10:27:48 [INFO] acl: initializing acls
    2018/12/18 10:27:48 [INFO] consul: Created ACL 'global-management' policy
    2018/12/18 10:27:48 [INFO] consul: Created ACL anonymous token from configuration
    2018/12/18 10:27:48 [INFO] serf: EventMemberUpdate: laptop
    2018/12/18 10:27:48 [INFO] serf: EventMemberUpdate: laptop.dc1
    2018/12/18 10:27:48 [INFO] consul: member 'laptop' joined, marking health alive
    2018/12/18 10:27:50 [WARN] agent: Node info update blocked by ACLs

...now the system is waiting for the HTTP request to come in...
```

If you attempt to use the bootstrap HTTP endpoint now, it will work:
```
$ curl -sL 'http://localhost:8500/v1/acl/bootstrap' -XPUT | jq .
{
  "ID": "6b74a43a-7311-c64e-084e-df08a1ea8f3e",
  "AccessorID": "dcb68a88-3112-8104-3f73-a5f5da3b04f4",
  "SecretID": "6b74a43a-7311-c64e-084e-df08a1ea8f3e",
  "Description": "Bootstrap Token (Global Management)",
  "Policies": [
    {
      "ID": "00000000-0000-0000-0000-000000000001",
      "Name": "global-management"
    }
  ],
  "Local": false,
  "CreateTime": "2018-12-18T10:29:21.774142507-06:00",
  "Hash": "oyrov6+GFLjo/KZAfqgxF/X4J/3LX0435DOBy9V22I0=",
  "CreateIndex": 9,
  "ModifyIndex": 9
}
```

And the server logs show it completed:
```
    2018/12/18 10:29:21 [WARN] acl.bootstrap: failed to remove bootstrap file: remove data/acl-bootstrap-reset: no such file or directory
    2018/12/18 10:29:21 [INFO] consul.acl: ACL bootstrap completed
```

**Comment by stevenlee87** [comment]
> $ consul agent -data-dir ./data -bind 127.0.0.1 -server -

docker run --net=host -e 'CONSUL_LOCAL_CONFIG={"primary_datacenter": "dc1","acl": {"enabled": true,"default_policy": "deny","down_policy": "extend-cache"}}' --name=node1 consul agent -server -bind=10.100.68.142  -bootstrap-expect=1 -node=node1

I execute the following command：
curl -sL 'http://localhost:8500/v1/acl/bootstrap' -XPUT
prompt:
The ACL system is currently in legacy mode

**Comment by stevenlee87** [comment]
curl \
    --header "X-Consul-Token: 461b1743-a669-9325-a187-9b9d893df8f8" \
    --request PUT \
    --data '{"Token": "bb53b1b4-27ee-33a7-dc24-ea9241fa1891"}' \
http://127.0.0.1:8500/v1/agent/token/acl_token
