### ISSUE TITLE
Node ACL suffix rules

### ISSUE THREAD

**Issue by Lasering** [hashicorp/consul#5110]
#### Feature Description
Node ACL should support suffix rules.

#### Use Case(s)
My node names are the FQDN of the machine. In my infrastructure I have many services, each service has a DNS subdomain for it, eg, *.mysql.example.com, *.mongo.example.com. And each machine of a service has a name under that subdomain, eg, server1.production.mysql.example.com, server2.production.mysql.example.com, server1.staging.mysql.example.com, server1.production.mongo.example.com.

Currently (v1.4.0) there is no way to create a Token/Policy per service that would allow access just to the nodes of that service. Node prefix will catch to many nodes in one go. And exact rules entail changing the policy every time a new machine is added/removed.

So the only solution I have is to create a policy which grants write access to all the nodes with an empty node prefix.

#### Solution(s)

- Use globs like in Vault thus allowing something like:
```
node "*.mongo.example.com" {
  policy "write"
}
```
- Support suffixes directly:
```
node_suffix ".mongo.example.com" {
  policy "write"
}
```

**Comment by pearkes** [comment]
We're going to leave this open to understand how common the need is but are definitely leaning towards not implementing this given the naming convention can be flexible and work with prefixes.

**Comment by Lasering** [comment]
It is flexible to work with prefixes but not with suffixes.

**Comment by pearkes** [comment]
See my note here: https://github.com/hashicorp/consul/issues/5221#issuecomment-454577841 going to centralize discussion of this on that issue. Thanks!
