### ISSUE TITLE
serfHealth fails time to time

### ISSUE THREAD

**Issue by worksandun** [hashicorp/consul#5113]
I am using consul v0.7.3 and there is an issue that the surfHealth fails time to time in different nodes. But those nodes are reachable from other hosts at that time. The servers are EC2 in aws.

### System Log
Dec 19 12:09:12 reg1 consul-alerts: time="2018-12-19T12:09:12+05:30" level=info msg="Getting profile for node:  bo1.micro.stg.achotels.use1.aws  service:    check:  serfHealth"
Dec 19 12:09:12 reg1 consul-alerts: time="2018-12-19T12:09:12+05:30" level=info msg="Getting profile for node:  master1.db.stg.achotels.use1.aws  service:    check:  serfHealth"
Dec 19 12:09:12 reg1 consul-alerts: time="2018-12-19T12:09:12+05:30" level=info msg="Getting profile for node:  web1.bo.stg.srilankan.use1.aws  service:    check:  serfHealth"
Dec 19 12:10:18 reg1 consul: 2018/12/19 12:10:18 [INFO] serf: EventMemberJoin: master1.db.stg.achotels.use1.aws 10.66.11.6
Dec 19 12:10:18 reg1 consul[784]: serf: EventMemberJoin: master1.db.stg.achotels.use1.aws 10.66.11.6
Dec 19 12:10:29 reg1 consul-alerts: time="2018-12-19T12:10:29+05:30" level=info msg="Updating reminder data for consul-alerts/reminders/master1.db.stg.achotels.use1.aws/serfHealth"
Dec 19 12:10:31 reg1 consul-alerts: time="2018-12-19T12:10:31+05:30" level=info msg="Getting profile for node:  web1.bo.stg.achotels.use1.aws  service:    check:  serfHealth"
Dec 19 12:10:36 reg1 consul: 2018/12/19 12:10:36 [INFO] serf: EventMemberFailed: master1.db.stg.achotels.use1.aws 10.66.11.6
Dec 19 12:10:36 reg1 consul[784]: serf: EventMemberFailed: master1.db.stg.achotels.use1.aws 10.66.11.6
Dec 19 12:10:43 reg1 consul-alerts: time="2018-12-19T12:10:43+05:30" level=info msg="Updating reminder data for consul-alerts/reminders/master1.db.stg.achotels.use1.aws/serfHealth"
Dec 19 12:12:27 reg1 consul: 2018/12/19 12:12:27 [INFO] serf: EventMemberFailed: bo1.micro.stg.achotels.use1.aws 10.66.11.215
Dec 19 12:12:27 reg1 consul[784]: serf: EventMemberFailed: bo1.micro.stg.achotels.use1.aws 10.66.11.215
Dec 19 12:12:33 reg1 consul: 2018/12/19 12:12:33 [INFO] serf: EventMemberFailed: web1.bo.stg.abans.use1.aws 10.46.11.79
Dec 19 12:12:33 reg1 consul[784]: serf: EventMemberFailed: web1.bo.stg.abans.use1.aws 10.46.11.79

### consul members sample
web1.bo.stg.abans.use1.aws                          10.46.11.79:8301   alive   client  0.7.3  2         use1
web1.bo.stg.achotels.use1.aws                       10.66.11.148:8301  failed  client  0.7.3  2         use1
web1.bo.stg.rezdemo.use1.aws                        10.18.0.10:8301    alive   client  0.7.3  2         use1
web1.bo.stg.srilankan.use1.aws                      10.64.11.72:8301   alive   client  0.7.3  2         use1

**Comment by pearkes** [comment]
@worksandun we made substantial improvements to this mechanism in Consul 0.9 and I'd recommend 
upgrading to that version or newer. This was aimed at this "flappiness" that you describe.

More information can be found here: https://www.hashicorp.com/blog/making-gossip-more-robust-with-lifeguard/. That post details the improvements to the system available in 0.9+.
