### ISSUE TITLE
consul:1.2.4 is missing on docker hub

### ISSUE THREAD

**Issue by EugenMayer** [hashicorp/consul#5116]
1.2.4 seems to have been never released to docker-hub https://hub.docker.com/_/consul?tab=tags

**Comment by pearkes** [comment]
It looks like we missed adding all the versions we backported due the [script check security issue](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/consul-tool/kmGKTj3YxUg). Our release process for that was a little non-standard so we missed it.

We'll get those added thanks for pointing that out.

**Comment by EugenMayer** [comment]
thanks!

**Comment by pearkes** [comment]
This is fixed in https://github.com/docker-library/official-images/pull/5210.

See https://hub.docker.com/_/consul?tab=tags.

Thanks again for bringing this to our attention @EugenMayer.

**Comment by EugenMayer** [comment]
That was quick, great and thanks!
