### ISSUE TITLE
Serf Health check is failing with remote consul server 

### ISSUE THREAD

**Issue by venkat-koppisetti** [hashicorp/consul#5122]
Actually we are running Consul agent server on node1 and consul client is running in a docker container on another node2.
Consul client is registered with consul agent server but SerfHealth check is changed back and forth between critical and passing every few seconds (5 or so).
i ran tcpdump command and got to know that consul agent server is using consul client container ip to send gossip messages to check weather client is alive or not but node1 does not know about client docker ip address thats why serf health check is failing.
But if i run Consul agent server on node2 where the consul client container is running, everything seems to be working.
How to run consul agent server and consul client on different nodes to work properly?
**consul agent config:**
{
        "server": true,
    "node_name": "consulAgent",
        "bootstrap": true,
    "data_dir": "/var/consul",
        "client_addr": "0.0.0.0",
        "bind_addr": "192.168.8.173",
        "ui": true
}
**Command to run consul agent server:**
consul agent -dev -ui -data-dir /var/consul -config-dir /etc/consul.d/

**consul client config:**
{
    "server": false,
    "node_name": "reachwvA10.244.2.29.dev.mr.tv3cloud.net",
    "data_dir": "/var/consul",
    "log_level": "INFO",
    "enable_syslog": true,
    "enable_debug": true,
    "enable_script_checks": true,
    "start_join": [
        "192.168.8.173"
    ],
    "datacenter": "dc1"
}
**Command to run consul client:**
consul agent -config-dir /etc/consul.d/

**Node datails:**
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**docker info**
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-20-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.853GiB
Name: k8s-worker1
ID: WXH3:XKAF:A7OZ:MYP5:G6DI:5CBA:ALXM:XJ3F:JC7P:AIDQ:ECND:G7SY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
