### ISSUE TITLE
encryption key has to be 24 o 32 bytes long, 16 bytes does not work

### ISSUE THREAD

**Issue by frafra** [hashicorp/consul#5129]
encryption key has to be 24 o 32 bytes long, 16 bytes does not work, even if the documentation and the CLI message says otherwise.

Consul version 1.4.0.

**Comment by pearkes** [comment]
Can you write more about the issue you're running into? Not sure we have enough information to investigate. I'll actually close this but feel free to re-open with more, there's a bunch of suggested information to include in the bug report template.
