### ISSUE TITLE
consul snapshot restore backup.snap

### ISSUE THREAD

**Issue by xiongmaodada** [hashicorp/consul#5131]
when I use consul   for  restore backup.snap on windows environment: `consul snapshot restore backup.snap`, services  can be found by  web ui(`http://localhost:8500/ui/dc1/services`). but  services are  deregistered  after a few minutes. Some information as follows:
```
2018/12/25 14:06:03 [INFO] snapshot: Creating new snapshot at log\raft\snapshots\8-578282-1545717963902.tmp
2018/12/25 14:06:04 [INFO] snapshot: reaping snapshot log\raft\snapshots\6-578179-1545716716587
2018/12/25 14:06:04 [INFO] raft: Copied 24290 bytes to local snapshot
2018/12/25 14:06:04 [INFO] raft: Restored user snapshot (index 578282)
2018/12/25 14:07:12 [INFO] agent: Deregistered service "test_proxy_test_test/10.234.128.36/8090"
2018/12/25 14:07:12 [INFO] agent: Deregistered service "http://10.234.128.36:21001/api"
2018/12/25 14:07:12 [INFO] agent: Deregistered service "common-service-demo_P1/10.234.128.36/21001"
2018/12/25 14:07:13 [INFO] agent: Deregistered service "/test-test-2008"
2018/12/25 14:07:13 [INFO] agent: Synced node info
```

And then,  there are not services in web ui(`http://localhost:8500/ui/dc1/services`).

consul version: `Consul v1.3.0`

**Comment by pearkes** [comment]
It sounds like you restored the backup to a cluster that did not have those services registered on the nodes and was overwritten by [anti-entropy](https://www.consul.io/docs/internals/anti-entropy.html). Refer to that document for the behavior there. If those services were externally registered you may be registering them against a real node which could be causing this.
