### ISSUE TITLE
Include jq in Consul docker releases

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/consul#5134]
#### Feature Description

It would really empower JSON based checks if the docker image included the [`jq`](https://github.com/stedolan/jq) utility.

#### Use Case

For example, lets say I want to not only check that a an [ElasticSearch](https://github.com/elastic/elasticsearch) cluster is up but also `green`:
RIght now I can only check if there's a response like this:
```bash
$ curl -sk 'localhost:9200/_cluster/health?pretty'
```
```json
{
  "cluster_name" : "status-logs-search",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 4,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 412,
  "active_shards" : 1223,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```
But with `jq` I could:
```bash
$ curl -sk 'localhost:9200/_cluster/health?pretty' | jq --exit-status '.status == "green"'
true
$ echo $?
0
$ curl -sk 'localhost:9200/_cluster/health?pretty' | jq --exit-status '.status == "red"'
false
$ echo $?
1
```
#### Details
I checked the docker image size increase with `apk --no-cache add jq` on top of `consul:1.4.0` image and the size changed from `105MB` to `106MB`. Or to be exact `106470637 bytes` - `105284115 bytes` = `1186522 KB`(`1.186522 Mb`).

**Comment by pearkes** [comment]
Definitely concern on bloating the image but given the precendent here I think we'd accept a PR for this as `jq` is such a widely used utility.

Example here for `curl`: https://github.com/hashicorp/docker-consul/pull/30

**Comment by jakubgs** [comment]
Right. The alternative to that is try to implement some kind of JSON parsing functionality into Consul checks themselves, but that sounds like a real waste of effort considering tool like `jq` are available.

**Comment by pearkes** [comment]
Thanks for the PR @jakubgs. This should be available in the next released version of the Docker image.
