### ISSUE TITLE
docker run consul not able to get consul UI

### ISSUE THREAD

**Issue by saytik** [hashicorp/consul#5138]
hi.

I make a clean run of consul agent -server with docker:

> PN=consul-new
> docker stop $PN && docker rm -f  $PN
> docker run -d \
>    --name $PN \
>    -p 8500:8500 \
>    -v /data/consul_data:/consul/data \
>    consul:1.4.0 agent -server  -bootstrap-expect=1

> # docker logs consul-new
> BootstrapExpect is set to 1; this is the same as Bootstrap mode.
> bootstrap = true: do not enable unless necessary
> ==> Starting Consul agent...
> ==> Consul agent running!
>            Version: 'v1.4.0'
>            Node ID: 'c64ac7ef-4601-a8e3-f21b-bf547716f157'
>          Node name: '06f91a63a4a5'
>         Datacenter: 'dc1' (Segment: '<all>')
>             Server: true (Bootstrap: true)
>        Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
>       Cluster Addr: 172.17.0.5 (LAN: 8301, WAN: 8302)
>            Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false
> 
> ==> Log data will now stream in as it occurs:
> 
>     2018/12/27 10:32:45 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:c64ac7ef-4601-a8e3-f21b-bf547716f157 Address:172.17.0.5:8300}]
>     2018/12/27 10:32:45 [INFO] raft: Node at 172.17.0.5:8300 [Follower] entering Follower state (Leader: "")
>     2018/12/27 10:32:45 [INFO] serf: EventMemberJoin: 06f91a63a4a5.dc1 172.17.0.5
>     2018/12/27 10:32:45 [INFO] serf: EventMemberJoin: 06f91a63a4a5 172.17.0.5
>     2018/12/27 10:32:45 [INFO] consul: Handled member-join event for server "06f91a63a4a5.dc1" in area "wan"
>     2018/12/27 10:32:45 [INFO] consul: Adding LAN server 06f91a63a4a5 (Addr: tcp/172.17.0.5:8300) (DC: dc1)
>     2018/12/27 10:32:45 [INFO] agent: Started DNS server 127.0.0.1:8600 (tcp)
>     2018/12/27 10:32:45 [INFO] agent: Started DNS server 127.0.0.1:8600 (udp)
>     2018/12/27 10:32:45 [INFO] agent: Started HTTP server on 127.0.0.1:8500 (tcp)
>     2018/12/27 10:32:45 [INFO] agent: started state syncer
>     2018/12/27 10:32:53 [ERR] agent: failed to sync remote state: No cluster leader
>     2018/12/27 10:32:54 [WARN] raft: Heartbeat timeout from "" reached, starting election
>     2018/12/27 10:32:54 [INFO] raft: Node at 172.17.0.5:8300 [Candidate] entering Candidate state in term 2
>     2018/12/27 10:32:54 [INFO] raft: Election won. Tally: 1
>     2018/12/27 10:32:54 [INFO] raft: Node at 172.17.0.5:8300 [Leader] entering Leader state
>     2018/12/27 10:32:54 [INFO] consul: cluster leadership acquired
>     2018/12/27 10:32:54 [INFO] consul: New leader elected: 06f91a63a4a5
>     2018/12/27 10:32:54 [INFO] consul: member '06f91a63a4a5' joined, marking health alive
>     2018/12/27 10:32:57 [INFO] agent: Synced node info

**On UI i see consul error:**

> HTTP error code from Consul: 0 error
> This is an error page for the Consul web UI. You may have visited a URL that is loading an unknown resource, so you can try going back to the root.
 
Also, UI works  from container inside

**Comment by saytik** [comment]
fixed by adding to consul start:
--net=host 
to_start_command:  -bind=193.106.94.245 -client 0.0.0.0

**Comment by pearkes** [comment]
I think this is working as intended and your fix is right. See the [networking section of the container guide](https://www.consul.io/docs/guides/consul-containers.html#networking) for more detailed information.
