### ISSUE TITLE
Consul master token does not have permissions for checks api after upgrading from 0.9 to 1.4

### ISSUE THREAD

**Issue by nitsh** [hashicorp/consul#5139]
#### Overview of the Issue

After upgrading from 0.9 to 1.4, I couldn't use the master token to list/register/deregister a check on a node.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 3 server nodes with consul version 0.9 and master token
2. Upgrade to 1.4 without changing the master token
3. Try registering a check with master token on one of the servers and it says permission denied
4. A different token with `node:write,service:write` permissions can do list/register/deregister of the checks.

**Comment by nitsh** [comment]
@mkeeler  I think I might have missed some important information.
The following are the updated steps to reproduce : 
1. Create 2 wan joined clusters(dc: local1, local2) of consul v0.9 with 3 nodes each.
2. local1 is the "acl_datacenter" for both DCs
The acl config now is as follows in all the nodes of both DCs
```
{
  "acl_datacenter": "local1",
  "acl_default_policy": "deny",
  "acl_down_policy": "allow",
  "acl_master_token": "token-x",
  "acl_agent_token": "token-x"
}
```
3. Upgrade all the servers in local1 and local2 DCs to 1.4.0 with following ACL config 
```
{
  "primary_datacenter": "local1",
  "acl": {
    "enabled": true,
    "default_policy": "deny",
    "down_policy": "allow",
    "tokens": {
      "master": "token-x",
      "agent": "token-x",
      "agent_master": "token-x"
    }
  }
}
```
4. Now I try to register a new check using `http://{{url}}:8500/v1/agent/check/register` on the first server of local2 cluster with `X-Consul-Token:token-x` and I get `Permission denied`. 
5. Then I create a new token with `node:write, service:write` permissions on local2 DC. Using this token, I am able to register and get checks.

I couldn't find any "acl: intializing legacy acls" log messages and all the servers were upgraded to 1.4.0.

**Comment by nitsh** [comment]
I've also tried the following config 
```
{
  "primary_datacenter": "local1",
  "acl": {
    "enabled": true,
    "default_policy": "deny",
    "down_policy": "allow",
    "tokens": {
      "master": "token-x",
      "agent": "token-x",
      "agent_master": "token-x",
      "replication": "token-x"

    }
  }
}
```

**Comment by mkeeler** [comment]
@nitsh I will try and reproduce this locally and see what I can find. 

Also just to verify, the permission denied is coming back through the API during check registration and not something ONLY being emitted in the logs? There are two places where the acl token would get validated one is completely within the HTTP API layer and if it fails there it would produce the permission denied error through the API.

**Comment by mkeeler** [comment]
@nitsh Actually, I think the problem is that you have set `acl.tokens.agent_master` to your master token.

The agent master token should be used to allow access to the agent APIs when other ACL tokens would be unresolvable due to network connectivity or other issues.

When resolving the token if it matches the agent master token in the configuration it will use a separate but more limited policy that allows agent and node read for any node and agent write only for that single agents name. This check happens prior to normal token resolution so its injecting the more limited policy for your master token due to the configuration.

**Comment by nitsh** [comment]
@mkeeler The issue is resolved by removing `acl.tokens.agent_master` from the configuration. Thanks.

**Comment by mkeeler** [comment]
@nitsh Yeah, normally the `acl.tokens.agent_master` token is set to some special value that is not a real token. Otherwise for agent operations it can mask/override the other real token.

I am glad it worked out.
