### ISSUE TITLE
Compare Consul to mDNS

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#517]
Some confusion around this, would be good to clarify.

**Comment by KushalP** [comment]
Can you be specific about the confusion here?

One is an external service (consul) whereas the other can be baked into an application's code (mDNS).

**Note:** worth saying that I've assumed you're referring to [node_mdns](https://github.com/agnat/node_mdns).

**Comment by armon** [comment]
I've been asked about the difference between using Consul and using mDNS. Like most things on the comparison page, they are typically apples and oranges but its useful to clarify.

**Comment by armon** [comment]
I don't know if these are confused often enough to be warranted. mDNS does not work in any cloud or multi-tenant network environment.
