### ISSUE TITLE
Consul >= 1.3.0 doesn't filter services by tags / returns an empty array

### ISSUE THREAD

**Issue by sofarsog00d** [hashicorp/consul#5179]
#### Overview of the Issue
Consul >= 1.3.0 doesn't filter services by tags / returns an empty array

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Run `curl -X GET 'http://localhost:8500/v1/health/service/service_name?tag=env1'`
2. Output:
`[]`
It works with consul **1.2.4**, but doesn't with **1.3.0** or higher.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 2
	check_ttls = 0
	checks = 70
	services = 70
build:
	prerelease =
	revision = 0bddfa23
	version = 1.4.0
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 233
	max_procs = 8
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1322
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 24072
	members = 32
	query_queue = 0
	query_time = 53
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 2
	check_ttls = 0
	checks = 70
	services = 70
build:
	prerelease =
	revision = 0bddfa23
	version = 1.4.0
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 233
	max_procs = 8
	os = linux
	version = go1.11.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1322
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 24072
	members = 32
	query_queue = 0
	query_time = 53
```
</details>

**Comment by sofarsog00d** [comment]
Any help?)

**Comment by Aestek** [comment]
@sofarsog00d could you provide your service definition ?

**Comment by pearkes** [comment]
@sofarsog00d can you post the results of the query without the tag parameter? Could be related to https://github.com/hashicorp/consul/pull/4717.

**Comment by sofarsog00d** [comment]
@pearkes 

consul 1.2.4
```shell
root@node1:~# curl -X GET 'http://localhost:8500/v1/catalog/service/service?tag=env1'
[{"ID":"7h4973f4h-3233-f37h-5555-666683625f46","Node":"node1",
"Address":"11.11.11.111","Datacenter":"dc-1","TaggedAddresses":{"lan":"11.11.11.111",
"wan":"11.11.11.111"},"NodeMeta":{"consul-network-segment":""},
"ServiceKind":"","ServiceID":"env1-service","ServiceName":"service",
"ServiceTags":["env1","5.8.1"],"ServiceAddress":"11.11.11.111",
"ServiceWeights":{"Passing":0,"Warning":0},"ServiceMeta":null,"ServicePort":11222,
"ServiceEnableTagOverride":false,"ServiceProxyDestination":"",
"ServiceConnect":{"Native":false,"Proxy":null},"CreateIndex":163932811,"ModifyIndex":273911893}]
```

consul 1.4
```shell
root@node1:~# curl -X GET 'http://localhost:8500/v1/catalog/service/auth?tag=unstable1'
[]
```

**Comment by pearkes** [comment]
@sofarsog00d can you post without the `?tag=env1` against 1.4?

**Comment by sofarsog00d** [comment]
@pearkes yes, it works without `?tag=env`, but output will be with _service_ from all environments, e.g. service-env1, service-env2, service-env3, where envX - different servers. So I need to filter _service_ by environment.

**Comment by pearkes** [comment]
@sofarsog00d right, I understand -- just trying to gather more information to aid in debugging and I think that would be useful.

**Comment by sofarsog00d** [comment]
@pearkes any updates?

**Comment by sofarsog00d** [comment]
any news?

**Comment by mkeeler** [comment]
@sofarsog00d I just tried reproducing and so far tag filtering is working as expected. Could you please submit the curl output of the request without passing the `?tag=env1` filter. Seeing the raw information would be helpful in tracking this down.

**Comment by Elufimov** [comment]
I am facing this problem too. We are in a process of updating our consul cluster to the lates version from 0.7.0. I have stable reproduction with agent (1.4.0) connected to out old cluster (0.7.0) and in new test cluster (1.4.0). Lets us see test cluster for example: 
3 master node with simple config:
```
{
    "bootstrap_expect": 3,
    "server": true,
    "datacenter": "caravan",
    "data_dir": "/var/lib/consul",
    "encrypt": "some key",
    "log_level": "ERR",
    "ui": true,
    "recursors":[
      "172.18.1.2",
      "172.18.1.3",
      "172.18.1.4"
    ],
    "start_join": [
      "${local.consul1_ip}",
      "${local.consul2_ip}",
      "${local.consul3_ip}"
    ]
}
```

Service:
```
curl -X "PUT" "http://first_master:8500/v1/agent/service/register?dc=caravan" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "ID": "Elastic localhost PROD",
  "Address": "localhost",
  "Name": "Elastic",
  "Tags": [
    "PROD"
  ]
}'
```
```
curl -X "GET" "http://first_master:8500/v1/health/service/Elastic" 
[
    {
        "Node": {
            "ID": "",
            "Node": "first_master",
            "Address": "some_address"
            "Datacenter": "",
            "TaggedAddresses": {
                "lan": "some_address",
                "wan": "some_address"
            },
            "Meta": null,
            "CreateIndex": 5,
            "ModifyIndex": 80927
        },
        "Service": {
            "ID": "Elastic localhost PROD",
            "Service": "Elastic",
            "Tags": [
                "PROD"
            ],
            "Address": "localhost",
            "Meta": null,
            "Port": 0,
            "Weights": null,
            "EnableTagOverride": false,
            "ProxyDestination": "",
            "Proxy": {},
            "Connect": {},
            "CreateIndex": 80916,
            "ModifyIndex": 80916
        },
        "Checks": [
            {
                "Node": "first_master",
                "CheckID": "serfHealth",
                "Name": "Serf Health Status",
                "Status": "passing",
                "Notes": "",
                "Output": "Agent alive and reachable",
                "ServiceID": "",
                "ServiceName": "",
                "ServiceTags": [],
                "Definition": {},
                "CreateIndex": 5,
                "ModifyIndex": 5
            }
        ]
    }
]
```
```
curl -X "GET" "http://first_master:8500/v1/health/service/Elastic?tag=PROD" 
[]
```

**Comment by mkeeler** [comment]
@Elufimov Can you execute the secondary query with `curl -v`. I tried reproducing with your exact service and a 3 server node consul cluster (both versions 1.3.0 and 1.4.0) and am unable to. What I am hoping to determine is whether you are getting stale or cached data, the headers curl will output should indicate if either of these two scenarios are happening.

**Comment by mkeeler** [comment]
Well that theory is definitely gone. Not stale or cached and the leader is serving the request.

**Comment by Elufimov** [comment]
It is very strange that we have different results. Can I provide additional data?

**Comment by mkeeler** [comment]
Maybe but I will need to do some more digging to see what I should ask you to gather.

**Comment by Elufimov** [comment]
I will be glad to help. This is definitely blocker for us.

**Comment by Elufimov** [comment]
I tried connect agents to our prod cluster (0.7.0):
1.2.4 worked fine 
1.3.0 returned empty array
1.4.0 returned empty array
1.4.1 returned empty array

**Comment by jippi** [comment]
Might be https://github.com/hashicorp/consul/pull/4944 ? was 1.3.1 to fix an issue in 1.3.0 - maybe not a full fix?

**Comment by Elufimov** [comment]
I managed to reproduce the issue after I created 0.7.0 test cluster and joined 1.4.0 agent to it. It hope this will help with reproduction.

**Comment by mkeeler** [comment]
@Elufimov That scenario is definitely unusual but I think it should work. Does the problem always present itself with 1.3.0+ agents in a cluster with agents < 1.3.0?

I think I could see how that might cause an issue.

**Comment by Elufimov** [comment]
> Does the problem always present itself with 1.3.0+ agents in a cluster with agents < 1.3.0?
It was in my dev env. If you need I could reproduce issue on needed versions of agent and cluster. However right now I am focused of upgrading our cluster to the latest version. And so far I have no problems with this process.

**Comment by mkeeler** [comment]
I am going to try to repro with some servers on v1.2.4 and a client on 1.4.0. I think I might know why this is happening.

**Comment by mkeeler** [comment]
The general recommendation is that servers in your cluster be upgraded first. Some features in the client agent's require the server-side updates to work properly and multi-tag filtering (introduced in 1.3.0) was one of them. The client sends somewhat different filters to the servers in 1.3.0 that pre-1.3.0 servers do not recognize.

Sometimes new clients may happen to work with older servers but its not something we explicitly support and its not something that should be relied upon.

**Comment by Elufimov** [comment]
Thx for your quick help with this issue. Your versions policy is reasonable.

**Comment by sofarsog00d** [comment]
Thanks!
