### ISSUE TITLE
Consul won't actually sync the services to the other nodes ?

### ISSUE THREAD

**Issue by stevenlee87** [hashicorp/consul#5180]
hello!

consul version:1.4.0
linux: CentOS Linux release 7.2.1511 (Core)

My consul cluster has five servers（consul1-consul5）,including 3 servers that serve as both server and client at the same time.

I registered a service: testservice1 on the server consul3(It's also a client)

But, When I shutdown the service of consul3, I can't see testservice in the other nodes.

1.Consul won't actually sync the services to the other nodes ?
2.What if a server's hard drive breaks down or goes down?
3.Can my services registered on the client be synchronized to the entire cluster?

**Comment by stevenlee87** [comment]
A similar issue: https://github.com/hashicorp/consul/issues/4030

**Comment by pearkes** [comment]
@viralpoetry posted a good link that is worth looking into. Consul will make any registered services available in the catalog, if there is a node failure it will mark those services as failing, and you can perform cross-dc lookups in the catalog using the dc parameters.

**Comment by 475132489** [comment]
@stevenlee87 me too, How did you solve this problem？
