### ISSUE TITLE
Connect: Broken links to Vault and PKI extend documents

### ISSUE THREAD

**Issue by santisaez** [hashicorp/consul#5182]
The references to Vault and how to extended the PKI system in the Connect document are broken:

```markdown
To generate and distribute certificates, Consul has a built-in CA that requires no other dependencies, and also ships with built-in support for [Vault](#). The PKI system is pluggable and can be [extended](#) to support any system.
```

https://github.com/hashicorp/consul/blame/v1.4.0/website/source/docs/connect/index.html.md#L59-L62

**Comment by pearkes** [comment]
Good catch thanks! https://github.com/hashicorp/consul/pull/5185
