### ISSUE TITLE
Documentation Bug for catalog/service. call is wrong.

### ISSUE THREAD

**Issue by rhyas** [hashicorp/consul#5183]
#### Overview of the Issue
The documentation on https://www.consul.io/api/catalog.html#list-nodes-for-service is wrong. It states you can filter on multiple tags, but this isn't currently implemented/possible with this API endpoint, as noted in this issue: https://github.com/hashicorp/consul/issues/1841

**Comment by pearkes** [comment]
This was added in 1.3.0 by https://github.com/hashicorp/consul/pull/4717. I'm guessing you may be using an earlier version? #4964 points out the issues with not versioning our docs such as these.
