### ISSUE TITLE
Documentation missing example configuration and watch command for Type: checks

### ISSUE THREAD

**Issue by richnusgeeks** [hashicorp/consul#5188]
#### Overview of the Issue

Current Watches documentation page is providing config example and watch command for all kinds except checks.

#### Reproduction Steps

Info missing on https://www.consul.io/docs/agent/watches.html

### Consul info for both Client and Server

Current release

**Comment by pearkes** [comment]
To add a bit more it looks like the checks type of watches is missing example output, eg.

![image](https://user-images.githubusercontent.com/846194/50702297-606abe80-1005-11e9-95b9-42615f12977e.png)

This can be fixed by adding that to the checks type example. Would appreciate a PR for this!

**Comment by richnusgeeks** [comment]
> To add a bit more it looks like the checks type of watches is missing example output, eg.
> 
> ![image](https://user-images.githubusercontent.com/846194/50702297-606abe80-1005-11e9-95b9-42615f12977e.png)
> 
> This can be fixed by adding that to the checks type example. Would appreciate a PR for this!

Sure, I'll create a PR when explore more. Just to clarify, as per https://www.consul.io/docs/agent/watches.html , only output is shown but both example and watch command are missing:
![consul_watch_checks_doc](https://user-images.githubusercontent.com/226598/50705498-df64f480-100f-11e9-94e5-40ec311bf6c5.png)
