### ISSUE TITLE
Serf MemberUpdate does not update Raft peerset

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#519]
If a Consul server node fails, and restarts with a new IP (but same name), the Serf layer will properly handle updating the node-to-IP mapping, however this does not update the Raft peer set. This causes 2 peers, one at old and one at new IP. Over time, this can cause a quorum loss when repeated. The MemberUpdate should properly cycle the RemotePeer and AddPeer to avoid this.

**Comment by slackpad** [comment]
Closing as a dup of #457.
