### ISSUE TITLE
 How to configure multiple configuration names？

### ISSUE THREAD

**Issue by MCeDo** [hashicorp/consul#5192]
how to configurate multiple config names so that I'm abled to use multiple keys from consul config to start my project? like this:
`spring.cloud.consul.config.name=mysql,rabbitmq,zipkin,${spring.application.name}
`
then, I can read multiple key's value to configurate my project?

Official introduction is 
`config/testApp,dev/
config/testApp/
config/application,dev/
config/application/`

**Comment by i0rek** [comment]
Hello @MCeDo, this sounds more like a good question for [spring cloud consul](https://github.com/spring-cloud/spring-cloud-consul).
