### ISSUE TITLE
Destroying a session doesn't release locks

### ISSUE THREAD

**Issue by markpapadakis** [hashicorp/consul#5205]
This is probably a bug, but it may be consistent with Consul underlying semantics, in which case, I would appreciate if it was confirmed as this being the case.

We are working on a Kafka like service that relies on Consul for leader election, clusters metadata management, etc. Everything's working fine, except for a lingering issue specific to sessions.

For example, for every "cluster" there is a single elected leader. Leader election works by creating a session using the sessions API, and then creating a special key("/clusters/<cluster_name>/leaders/CLUSTER") using `?acquire=<session id>` (where the session id is the id of the session acquired earlier by the node). This works great.

All other nodes actively monitor "/clusters/<cluster_name>/leaders/" using `?recurse=true` and an appropriate `&index=`. 

When a cluster leader node terminates, it destroys the session it has created using "/v1/session/destroy/<session id>". All other nodes that have been long-polling for updates to /leaders are not provided with an HTTP response because the keyspace "/leaders" is recursively monitored.

Here lies the problem:
```json
[  
   {  
      "LockIndex":0,
      "Key":"TANK/clusters/phaistos/leaders/",
      "Flags":0,
      "Value":null,
      "CreateIndex":3322637,
      "ModifyIndex":3322637
   },
   {  
      "LockIndex":172,
      "Key":"TANK/clusters/phaistos/leaders/CLUSTER",
      "Flags":0,
      "Value":"Mg==",
      "CreateIndex":3322649,
      "ModifyIndex":4007316
   }
]
```
As you can see, the "CLUSTER" key is (no longer) associated with a `Session`, which means there is no exclusive lock held for that key by any other nodes, because the cluster leader destroyed that session and as expected that session is no longer associated with "CLUSTER".

However, when nodes rush to attempt to acquire ownership of that "CLUSTER" key (because there is no leader and thus this requires a leader election), this fails with a response code 200 and content "false". This is irrespective of the number of nodes that attempt to acquire ownership; fails even if there is a single node remaining the cluster that tries to do so. If however we retry that on failure, after about 4 or 5 seconds, it succeeds.

The only way to solve it is for the cluster leader to explicitly release the lock on "CLUSTER" by using `?release=<session id>` before destroying the session (on tear down).

Shouldn't destroying the session suffice? If not, then why does the response to the long-polling recursive request for /leaders return with "CLUSTER" not being associated with a Session (as expected)?

As of Consul v1.4.0 this issue hasn't been resolved.
Please advice.

**Comment by burdandrei** [comment]
Hi @markpapadakis,
this is expected behavior.  Locks got their own TTLs, and are released when session was not updated during TTL

**Comment by markpapadakis** [comment]
@burdandrei Thank you. I appreciate the response. 
However, why does the response to `GET /1/kv/TANK/clusters/phaistos/leaders/?recurse=true` return no `Session` for "CLUSTER" when the session is destroyed - even if the lock itself is not released? It's somewhat misleading because if "Session" is missing then presumably the key is not locked.
