### ISSUE TITLE
[ACL] Ghost service instance after agent wipe 

### ISSUE THREAD

**Issue by Aestek** [hashicorp/consul#5209]
#### Overview of the Issue

With ACLs enabled and default policy deny, if an agent looses its state files (eg `services/7469af256ad396e876ed20bb3ca87649`) and is restarted it cannot deregister the services previously registered on this agent because it no longer has a token with `policy: write` for the services.

On startup the agent tries to deregister `test-service` using `acl_token`. If the `acl_token` does not have write permission on `test-service` the deregistration fails and the service stays in the catalog while not registered on the agent.
The Serf Health Status is passing because the agent is up again, the service heath checks are no longer updated because they are not running on the agent anymore so the service is still "passing" in `/v1/health`, becoming effectively a **passing** ghost service instance.

This can happen during hardware maintenance for example. A dead hard drive makes the node crash. The node is reinstalled and keeps the same hostname / node-id.

#### Steps to reproduce the problem

* Register a service `test-service` on an agent
* Stop the agent without a leave
* Remove its state service files (`/services/*`)
* Start the agent again 
* The agent outputs ACL error logs, and `test-service` is still present in the catalog whereas not registered on the agent anymore

##### Give write access on the service to the `acl_token`

This is not ideal because many different services can run on the same node, this would require to give write access to all services, which defeats the ACLs.
We could also prefix each service id by the node-name for example and give write access on this prefix to the `acl_token`. This would require a complete migration of our services and ACLs which is not doable for us. Furthermore this makes the service id rule much more complex, from "service ids need to be unique per agent" to "services ids need to be unique per agent and begin with a prefix shared by the agent ACL token so the agent can deregister services in all cases".

##### Allow service deletion if the token has write permission on the agent

A token with `agent: write` policy can leave an agent, effectively deregistering its service. We propose to extend this capability to service deregistration on agent the token has `agent` permission on.
This provides a much simpler way to deal with this edge case, while maintaining the same semantics and level of security defined today by ACls.
This simpler approach is also easier to setup, the rule being: `acl_token`s need `agent: write` policy on the node they are deployed to.

**Comment by rboyer** [comment]
> Allow service deletion if the token has write permission on the agent

Amusingly while working through some edge cases for something else I ran across this situation as well and just hadn't gotten around to documenting it on an issue.

I'd settled on probably making catalog register and catalog deregister require asymmetric ACLs. Register would require `service:write` + `node:write`, and deregister would merely require `node:write` for the reasons you described above.

**Comment by pierresouchay** [comment]
@rboyer except having node:write for registration would break lots of existing ACLs. We thought a lot with @Aestek on how fixing this and it sounds me like the less worse compromise as it does not weaken security and allow agent to re-init properly with the same result as a leave/join would do.
