### ISSUE TITLE
when consul is cluster,how a spring boot h register to the consule cluster?the host only be one ip

### ISSUE THREAD

**Issue by zjypp** [hashicorp/consul#5253]
consul:
      host: #only one ip

**Comment by i0rek** [comment]
Hello @zjypp, this sounds more like a question for [spring cloud consul](https://github.com/spring-cloud/spring-cloud-consul). Plus I think it would be great if you could rephrase your question to be more clear about what your problem is exactly.

**Comment by i0rek** [comment]
This is the consul core repo and you want to go to the spring cloud consul repo because we cannot help you with your spring configuration: https://github.com/spring-cloud/spring-cloud-consul.
