### ISSUE TITLE
Website Typo: typo in code for compiling from source docs/install/index.html

### ISSUE THREAD

**Issue by matthoey-okta** [hashicorp/consul#5254]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I believe in the following line the exclamation point and dollar sign need reversed:

```
$ mkdir -p $GOPATH/src/github.com/hashicorp && cd $!
```

**Comment by i0rek** [comment]
@matthoey-okta good catch! Would you like to send a PR?

**Comment by i0rek** [comment]
Thank you!
