### ISSUE TITLE
Support different advertise address for WAN gossip

### ISSUE THREAD

**Issue by brycekahle** [hashicorp/consul#527]
I would like the ability to use a node's public ip address for WAN gossip protocol, but retain use of the private ip for LAN gossip. This would negate the need to run a VPN tunnel between two datacenters.

**Comment by x0e-foobar** [comment]
+1

**Comment by dave-tucker** [comment]
:+1:

**Comment by mavenugo** [comment]
:+1:

**Comment by arenstar** [comment]
+1

**Comment by bmonkman** [comment]
:+1: Really need this.

**Comment by blalor** [comment]
Looking into joining clusters across disparate cloud providers and data centers. In some cases creating a vpn between these networks may not be advisable or possible, such as for regulatory reasons. Having separate advertise addresses for lan and wan pools is a must.

**Comment by fabx** [comment]
+1

**Comment by pepov** [comment]
+1 is there any progress on this already?

**Comment by pepov** [comment]
As far as I can see the rpc advertise address should be separated too. I've managed to make the WAN gossip use a different address with this patch: https://github.com/pepov/consul/commit/9c3ef28756f571cee33d69ff90033f419a5c2ac1

I suppose `RPCAdvertise` should be separated too for wan and lan. Is this a right way to go?

**Comment by pepov** [comment]
Ok, I think I just overcomplicated this and there is no need to separate the rpc advertise address because it's only for the raft protocol. (Except when you want to config the raft layer different from what advertise_addr is set to)

**Comment by armon** [comment]
Fixed in #816
