### ISSUE TITLE
Consul 1.4.1 breaks compatibility with older versions of the API client.

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#5270]
After releasing Consul 1.4.1 we discovered that there were problems with Nomad's integration with Consul. After further digging we discovered a couple problems.

The symptom of the problem first manifest themselves with the [`api.Agent.Checks`](https://godoc.org/github.com/hashicorp/consul/api#Agent.Checks) function of previous versions of the API client being unable to decode the JSON responses coming back from Consul. The root cause of this was that in 1.4.1 Consul was now sending back some empty strings for the `time.Duration` fields in the [`HealthCheckDefinition`](https://godoc.org/github.com/hashicorp/consul/api#HealthCheckDefinition) struct. Previously if the fields were empty they were not omitted. On the client side, the empty strings were unable to be decoded into the `time.Duration` values.

The fix for the first problem will be to omit those empty string fields just as we did before.

As we looked into this issue we found a secondary issue which was that the types of the fields in the 1.4.1 API client had been changed from an `api.ReadableDuration` to a raw `time.Duration`. As this could cause issues with consumers of the API client, the change will be reverted to maintain compatibility with older versions.

**Comment by memelet** [comment]
I was coming up from 1.2.0. I've already downgraded one cluster to 1.4.0. Doing the second now. The production cluster can remain at 1.2.0 until next week. Thanks!!

**Comment by pearkes** [comment]
This is fixed in https://github.com/hashicorp/consul/pull/5276 and is part of 1.4.2, which has been released.

**Comment by robloxrob** [comment]
This fix worked for me. Thank you for the rapid turn around!
