### ISSUE TITLE
Consul Exec should terminate new processes, -detach as option

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#528]
Currently consul exec will fork/exec the process. The agents can detect that a exec has been canceled and they stop streaming output, but the child process is not killed. The default behavior should be to kill the process, unless a -detach flag is provided which lets it keep running for long running jobs.

**Comment by slackpad** [comment]
We should refactor `consul exec` to use the child package as well as #2053.

**Comment by slackpad** [comment]
Closing this against https://github.com/hashicorp/consul/issues/2999. I don't think we should do "detach" so I'm not carrying that forward - that seems super hard to reason about, and we don't really want to be kicking off long running jobs with `consul exec`.
