### ISSUE TITLE
Lookup configuration values from environment

### ISSUE THREAD

**Issue by foosinn** [hashicorp/consul#5286]
#### Feature Description

Load a configuration setting from custom environment variable. 

Example:

```
{
  "datacenter": "east-aws",
  "data_dir": "/opt/consul",
  "log_level": "INFO",
  "node_name": "fancyhost",
  "server": true,
  "addresses": {
    "https": "0.0.0.0"
  },
  "ports": {
    "https": 8501
  },
  "key_file": "$KEY_FILE",
  "cert_file": "$CERT_FILE",
  "ca_file": "$CA_FILE"
}
```

In the example the certificate configs would be loaded from environment variables. Those would be easy to provide by Systemd's `EnvironmentFile` or Docker. Another option would be the use of go templates.

#### Use Case(s)

Not all configuration options are currently accessable via environment variable. Users could limit some specific config options to be set by environment variable.

**Comment by i0rek** [comment]
@foosinn thanks for your report. There are some values that are read from the environment already: https://www.consul.io/docs/commands/index.html#environment-variables but not everything is supported. Your example is though!

**Comment by i0rek** [comment]
Closing now, but happy to reopen if there is still a problem.
