### ISSUE TITLE
Feature: Intentions Match API. Return all intentions for a service without filtering by source/destination

### ISSUE THREAD

**Issue by johncowen** [hashicorp/consul#5296]
#### Feature Description

I would like to be able to retrieve all intentions for a service in one API request, returning all intentions for a single service whether being the source or destination.

Currently I'm using https://www.consul.io/api/connect/intentions.html#list-matching-intentions in a UI which has a required `by` query parameter like so:

`/connect/intentions/match?by=source&name=service`

Suggestions/options:

1. `by` could be optional, returning all intentions for a service if not specified
2. `by` could be specified multiple times (I think this is currently possible with the `name` parameter)
3. `by` could be a comma separated value
4. `by` could use `either` (or another keyword) as a value

Personally I'd prefer 1, if not then 2 (it follows the usage for something we already have - `name`)

#### Use Case(s)

Being able to show all intentions per service as simply as possible, therefore showing what this service can talk to. Right now you can make 2 API requests and `concat` them, but if you then want to include live updating blocking queries in here, doing that will get more complicated.

**Comment by pearkes** [comment]
I believe this would be resolved with more generic endpoint filtering, correct?

**Comment by johncowen** [comment]
Hey! Yeah a filtering endpoint here would be perfect!
