### ISSUE TITLE
docs: Update Connect Proxy Integration Guide

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#5298]
https://www.consul.io/docs/connect/proxies/integrate.html

Is all still accurate but fairly minimal. We should add more detail around:

 - AuthZ per connection not per request
 - Periodic re-auth for persistent connections
 - Reading "opaque" proxy config from the config endpoint
 - Authenticating with the agent using an ACL token

**Comment by blake** [comment]
This was addressed by #8869 which included the initial draft of updates to this doc from 3406d923e48b8cb707114515e755dbe8e796c6fc.
