### ISSUE TITLE
UI paperwork very confusing.

### ISSUE THREAD

**Issue by subrays** [hashicorp/consul#5299]
I have three consul servers set up, and four services(each registered exactly one health check).

![image](https://user-images.githubusercontent.com/1000942/52026736-e0703f80-2543-11e9-8614-fc877378b0aa.png)
on this page, node details are correct but node number is actually node number + service number, I suppose.

![image](https://user-images.githubusercontent.com/1000942/52026792-14e3fb80-2544-11e9-8b65-a82c27acf0d3.png)
on this page, each service has two health checks where I only registered one. (The other one seems to be "Serf Health Status" which I don't care and don't know how to turn off).

![image](https://user-images.githubusercontent.com/1000942/52026877-655b5900-2544-11e9-9ce5-f9a2ce9ceda0.png)
On this page, service detail is good, but still, the number(2) is confusing. I believe the number means health checks but again, I have only one instance of the service, and only one health check related to this service, the other one (the Serf Health Status) is not related to my service, but related to the node.

All the API returns are good, only UI is confusing. What people expect, I guess, is when they see "Nodes: All(7)", they expect 7 nodes, not 7 health checks. Can you fix that?

**Comment by subrays** [comment]
Oho I am using consul 1.4.1 through your official docker image:)

**Comment by johncowen** [comment]
Hi @subrays 

There's an issue which deals with this, and also work detailed there that is upcoming to mostly address this here:

https://github.com/hashicorp/consul/issues/4158

There is also work slightly related to this here:

https://github.com/hashicorp/consul/pull/5326

You'll notice that the upcoming 'Service Instance' listing does split the HealthChecks into Node and Service healthchecks.

I think these 2 address at least most of your issue. But let me know, and we can possibly close this issue on release of the above. If there is anything left over we can maybe create an issue to deal with whatever is left.

Thanks,

John

**Comment by subrays** [comment]
Thanks @johncowen , looks like this issue can be closed:)
