### ISSUE TITLE
Agent does not use configured token for remote exec handling

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#530]
The agent should use the locally configured token when responding to a remote exec. Currently, the anonymous token (e.g. no token) is used, causing permission failures.

**Comment by ronpanto** [comment]
Any news on that?

**Comment by ryanuber** [comment]
@ronpanto a fix is now in the master branch! See #655 for details.

**Comment by ronpanto** [comment]
any idea when the next consul version is scheduled for?

**Comment by ryanuber** [comment]
@ronpanto within the next few weeks (sorry I don't have a solid date)
