### ISSUE TITLE
Whitespace prefixes and suffixes in keys is not apparent in web UI

### ISSUE THREAD

**Issue by afprusin** [hashicorp/consul#5305]
If a key in Consul's KV store begins with or ends with whitespace, the whitespace is not clearly reflected in the web UI; I suspect the string is being trimmed before being displayed.  This can cause headaches with troubleshooting keys with spacebar-typos.

Steps to reproduce this issue, eg:
Create a key and value using the web frontend with a key of

>"  someKey  "

(Quotes used only to show whitespace).
Observe the appearance in the web frontend after creation.

**Comment by johncowen** [comment]
Hi @afprusin 

Thanks so much for reporting this issue! I've had a quick look at reproducing this and from what I can see the KV is saved/retrieved correctly. But when the UI displays the value any surrounding spaces aren't displayed properly. The surrounding spaces are even in the actual HTML.

<img width="222" alt="screenshot 2019-02-04 at 09 27 46" src="https://user-images.githubusercontent.com/554604/52199853-2c322a00-285f-11e9-90dd-570596ab09be.png">

I'm aware that there was a problem with URL encoding in versions previous to 1.4.2. So if you could confirm the version you experienced this issue with, and even possibly confirm that the spaces are in the HTML (by right clicking on the text and choose 'Inspect Element'), that would be great.

Thanks,

John

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
