### ISSUE TITLE
Question: Ever-increasing raft commit times

### ISSUE THREAD

**Issue by danveloper** [hashicorp/consul#5309]
I'm trying to get to the bottom of a situation we're seeing in one of our environments where Consul has an ever-increasing raft commit time.

![image](https://user-images.githubusercontent.com/1418180/52220146-d744e280-2863-11e9-8694-92d3ecc18df6.png)

(These metrics are `consul.raft.commitTime`, `consul.kvs.apply`, and `consul.leader.barrier` respectively.)

Here's some background information on the environment:

We have a shared network space between two respective Consul environments (dev and prod). IP addresses from one environment are able to be allocated in the other, and over the last month we've found this causes really bad problems to the Serf gossip mesh at our measure of scale (~11,000 instances between the two environments). With the rate of churn between the two environments, we've noticed the gossip mesh in both becomes "poisoned" after some period of time (where the Consul agents for the instances in the dev environment will overload their handoff queue trying to -- unsuccessfully -- talk instances that used to be in dev but now its IP address is allocated to an instance in prod, and vice-versa). During the poisoning, Consul agents are not able to process all the membership change events and nodes that have long gone away are reported as alive, and so forth. Ultimately, nodes in the gossip mesh appear to "flap" in and out of alive/failed/left states. 

To remediate this problem, we enabled gossip encryption for the agents in the dev environment, which allowed its gossip mesh to recover. What we did not anticipate, however, was that Consul agents in the prod environment would attempt to process the encrypted gossip messages from the dev environment, and thus backed up their handoff queue resulting in a corollary poisoning event. 

We were able to trace back that the increased gossip activity was causing the service catalog to be updated with every leader loop, resulting in very high raft activity, and ultimately service unavailability at the cluster servers. To remediate this, we abandoned the Consul agent sidecars that were coscheduled with workloads, and we monitor instance membership through a separate, external system. 

After removing Serf from the environment, the prod Consul cluster was able to recover itself and has consistent times for raft commit time, kv writes, and leader loop. However the dev cluster exhibited significantly different behavior, where its raft commit times were in the 10s of seconds and the leader loop was taking up to 15s to complete. Checking on the cluster servers, none of them agreed on the size of `raft.db` (181mb, 78mb, and 92mb across three servers). I'm not sure if this is related, but after removing the `raft` and `serf` directories and performing a rolling reboot, the three servers became semi-consistent on the size of that file, and raft commit times dropped to ~50ms. The leader loop was still taking up to 10s to complete, compared to 100ms in the prod cluster. The raft commit times for the dev cluster have steadily increased over 24hrs from 50ms to ~1s with indications it will continue to grow.

We use Vault to manage Consul ACLs for consumers -- not sure if this is noteworthy, but figured it's worth including for completeness.

**Things we've done to get here:**
 * Started with Consul 1.0.6 as agent and servers
 * Upgraded all nodes to Consul 1.3.1
 * Upgraded all nodes to Consul 1.4.2
 * Removed agent nodes from the infrastructure (only server nodes exist in the Serf mesh at this point)
 * Forced all consumers of service catalog and k/v to perform stale reads to alleviate pressure on the leader
 * Forked Consul at https://github.com/hashicorp/consul/commit/6e83f68637a719fbbbac69a5ddfcf21eda09ad79 and added some logging to try to figure out what's going on (this is what we're currently running at)

My question is this: is there any possibility the raft database has somehow become corrupted, resulting in the ever-increasing raft transaction times? And if so, is there some way I can diagnose this or otherwise see what Consul is spending its time on?

Thank you for all the work you've done on Consul, it's been incredibly valuable. Any help is greatly appreciated.

**Comment by johnrengelman** [comment]
We also see this for `consul.raft.replication.appendEntries.rpc`
![image](https://user-images.githubusercontent.com/1012772/52222469-30fbdb80-2869-11e9-8019-0d29aa1371f5.png)

**Comment by banks** [comment]
Hey, thanks for the detailed feedback. I have a couple of initial observations/questions that may or may not help diagnose:

 1. It looks like the actual number of raft writes is steadily increasing, not just the time so I suspect the time is just a symptom of increasing load. Can you show CPU spent in iowait over that time frame - raft commit latency tends to be dominated by disk throughput.
 2. The other factor that can be related is if the KV store or catalog is growing - then the state grows and takes longer and longer to write snapshots, which takes more disk IO, which makes raft log appends slower. Do you have a way to see what snapshot file size has done over time on these hosts?
 3. Can you describe what you workload looks like? You mentioned 11k agents I think but are those in containers, on separate VMs etc? Are they doing DNS queries/HTTP discovery/Blocking queries/KV reads/writes etc? Roughly how many per writes per second do you _expect_ to happen? HOw many distinct services, instances per service etc. A rough idea here is super useful.
 4. Has your Dev cluster been upgraded to 1.4.2 as well? There was a known issue in 1.3.0 IIRC which caused agents to sync their services more often than necessary, but that should now be fixed.
 5. Finally. 1.4.0 introduces [`consul debug` command](https://www.consul.io/docs/commands/debug.html) which among other things will automate making heap profiles and capturing config and metrics. If possible (and **please read the security notices in the docs** there) could you upload a debug trace - ideally two some hours apart after load has increased some so we can see what is going on?

Thanks, hopefully we can help diagnose this issue!

**Comment by johnrengelman** [comment]
Hi @banks data coming:
1)
CPU I/O Wait
![image](https://user-images.githubusercontent.com/1012772/52224268-31967100-286d-11e9-8da9-04b860b365c7.png)

Disk I/O
![image](https://user-images.githubusercontent.com/1012772/52224245-26434580-286d-11e9-8936-eefe2183826e.png)

2) We don't have the snapshot size data over time. Are are current sizes:
  raft:
  `raft.db`: 238948352
  `state.bin`: 140916509
  serf:
  `local.snapshot`: 73111
  `remote.snapshot`: 1065

3) Combination of containers and VMs, but the Consul agent is always running in a container. No Consul DNS, some service/node discovery over HTTP, consistent K/V reads (~ every 2 secs per workload doing a stale read). Writes should be very low, only when a developer modifies an application configuration. Services and Nodes are 1-to-1

4) The servers are on 1.4.2, the remaining agents now at 1.4.2 and 1.3.1. We are working to eliminate those as well.

5) Working on getting the debug now.

**Comment by danveloper** [comment]
Hey @banks thanks for the reply.

![image](https://user-images.githubusercontent.com/1418180/52224073-b9c84680-286c-11e9-9f66-32a5c3261164.png)

Here's the 24hr view of the raft commit time and kv write times. The green bars are counts and the yellow line is the time spent (`count` and `mean` off the `consul.kvs.apply` respectively).

![image](https://user-images.githubusercontent.com/1418180/52224284-3b1fd900-286d-11e9-873d-e5b672c53703.png)

Here's the CPU iowait time for the affected cluster.

![image](https://user-images.githubusercontent.com/1418180/52224325-55f24d80-286d-11e9-84a8-6aa8a895a7ee.png)

Here's the disk i/o for the affected cluster.

>It looks like the actual number of raft writes is steadily increasing, not just the time so I suspect the time is just a symptom of increasing load.

Reads are heavy in our environment, but writes are really infrequent. Clients store application configuration in the consul k/v but don't use the k/v as an intermediate datastore. Disk throughput looks nominal and doesn't appear to have a corollary increase to the raft commit times.

>The other factor that can be related is if the KV store or catalog is growing - then the state grows and takes longer and longer to write snapshots, which takes more disk IO, which makes raft log appends slower. Do you have a way to see what snapshot file size has done over time on these hosts?

This has been pretty consistent over the last 24hrs. Over 48hrs the snapshot size has grown ~2MB in size, which is reflected accurately across the three server nodes.

>Can you describe what you workload looks like? You mentioned 11k agents I think but are those in containers, on separate VMs etc? Are they doing DNS queries/HTTP discovery/Blocking queries/KV reads/writes etc? Roughly how many per writes per second do you expect to happen? HOw many distinct services, instances per service etc. A rough idea here is super useful.

They are container workloads where we deploy (previously) a Consul agent sidecar alongside the app. Almost every workload is an HTTP app and distinct deployments ("server groups" in Spinnaker terms) get a service in the service catalog. Every deployment only has an individual corresponding service, and we use Fabio to load balance to them. A very low number of workloads use HTTP service discovery (mostly just platform components). Nobody from what I can tell from the `monitor` logs uses blocking queries. KV reads are very high, but writes are very infrequent. We expect to see between 20 and 40 KV writes per minute.

>Has your Dev cluster been upgraded to 1.4.2 as well?

Yeah, the dev cluster is the one we're running off of master. We reverted back to 1.4.2 release this morning and it didn't help (we're monitoring to see if it made it worse -- the spikes in the graph above at approx 1100 are when we went back from 1.4.2-dev to 1.4.2 proper).

>If possible (and please read the security notices in the docs there) could you upload a debug trace

I'll do my best.

Thanks a lot for the reply.

**Comment by danveloper** [comment]
Additional nodes on infrastructure:
 * These servers are provisioned to a controlled VMware cluster with 16 CPU cores and 24GB ram
 * The underlying storage is a Netapp A300 filer with SSDs. The LUNs are provisioned via NFS.
 * The servers are Dell M630 blades
 * The VMware infrastructure is dedicated and is not co-tenant with application workloads.

Thanks

**Comment by danveloper** [comment]
Through the course of troubleshooting yesterday, we observed that offloading HTTP k/v reads from one particular server in the three-node cluster caused the raft commit times to drop to normal levels and they are no longer increasing. I can't seem to find anything in the code that would indicate why read operations (on a non-leader node especially) would affect commit times.

Troubleshooting steps:
 * Migrated server VMs to various different hypervisors _(no effect)_
 * Performing a rolling reboot of all the servers _(no effect)_
 * Offloaded k/v reads over HTTP endpoint from consul1 server to consul2 server using nginx proxy-pass _(cluster stabilized)_

The cluster is stable at this point, but I don't have a good answer why. We're going to continue to capture pprof data to see if it will lead us to some conclusion, but if there are any ideas I'm open to them.

(Side note: thank you very much for putting the debug capability into Consul -- we're working to figure out how much of the data we can share.)

**Comment by johnrengelman** [comment]
Wanted to update this ticket with some more details.

We exported the Consul state using `consul snapshot save`, then rebuilt the cluster into a clean state and restored using `consul snapshot restore`. This returned all the metrics to a normal state. However after 36 hours running in this mode, we can see an upward trend in the replication times to the 2 follower servers. I've included a screenshot of the trend below.

![image](https://user-images.githubusercontent.com/1012772/52537934-fcd55e80-2d31-11e9-898e-40125419aa42.png)

Some additional details:
1. There are only 11 nodes that are joined via Serf to this cluster. All 11 are static IPs on permanent VMs.
2. There are approximately 5,000 nodes and services (1 to 1 node to service) registered via the Consul HTTP API. We only update these registrations on edge transitions for the health checks associated with them.

Other notes:
1. When restoring the Consul cluster, we re-built our existing servers, so they had the same IP and hostname. This appeared to cause some issues when restoring the snapshot as the `node-id`s were different. We were receiving a number of warnings in the logs about it being unable to ensure the node registration because of the mismatch in the `node-id`. We recovered this by re-doing the restore and using the same `node-id`s from the previous servers.

**Comment by johnrengelman** [comment]
@banks How can we send the debug data to you?

**Comment by pearkes** [comment]
@johnrengelman you'll need to ensure `enable_debug` is set on the target agent to get the profiling from `consul debug` which is important to us in this scenario. As Paul said definitely read the security notices in those docs! You can send a link or the files themselves if small enough to consul-oss-debug@hashicorp.com.

**Comment by johnrengelman** [comment]
Thanks @pearkes. Will get them to you today.

**Comment by johnrengelman** [comment]
Hi @pearkes the debug files will come Monday (had to get a place to put them for you).
However, I did some more digging and I found a couple of odd issues on the cluster that is experiencing this problem. 
It seems as though the leader is making a RPC connection to itself (this follows the leader to a different node if I force an election).

```
$ lsof -i -aP -p $(pgrep consul) | grep 8300
consul  82212 consul 1524u  IPv6 581273983      0t0  TCP consul1:8300->consul1:39750 (ESTABLISHED)
consul  82212 consul 1519u  IPv4 581277735      0t0  TCP consul1:39750->consul1:8300 (ESTABLISHED)
```

I also see an elevated number of `accept4` syscall errors on this cluster:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 73.47   10.518938         799     13170       803 futex
 10.87    1.556930          11    141240           setsockopt
  3.46    0.494713          14     35889       489 accept4
  3.45    0.494399          13     36686           epoll_ctl
  2.72    0.389173          11     35345           getsockname
  2.22    0.317893          51      6291           nanosleep
  1.97    0.282218          20     14252           write
  0.77    0.109770          14      8027           epoll_pwait
  0.64    0.092074          14      6733      2602 read
  0.18    0.026130          14      1816           getpid
  0.14    0.019886          15      1294           close
  0.06    0.009098          12       755           getrandom
  0.05    0.007049          26       268           sched_yield
  0.00    0.000000           0         6           pwrite64
  0.00    0.000000           0         1         1 recvfrom
  0.00    0.000000           0         1         1 recvmsg
  0.00    0.000000           0         2           fdatasync
------ ----------- ----------- --------- --------- ----------------
100.00   14.318271                301776      3896 total
```

Compared to a working cluster:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 73.86   10.550993         193     54772      1686 futex
 22.27    3.180768          11    299629           write
  1.51    0.215489          24      9020           sched_yield
  1.12    0.160116          15     10930      5240 read
  0.63    0.089888          58      1559           nanosleep
  0.57    0.081126          12      6730           epoll_pwait
  0.04    0.005754         959         6           fdatasync
  0.00    0.000249          12        20           pwrite64
  0.00    0.000063          13         5           setsockopt
  0.00    0.000056          14         4         2 accept4
  0.00    0.000054           6         9           sendto
  0.00    0.000039          20         2         1 recvfrom
  0.00    0.000022          11         2           epoll_ctl
  0.00    0.000021          11         2           getsockname
  0.00    0.000000           0         3           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00   14.284638                382693      6929 total
```

The error all all `EAGAIN`: `accept4(18, 0xc00a6fab00, 0xc00a6faae4, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)`
which is the code for a non-blocking io read where there was no data. 

The descriptor `18` is the `http` port for the `consul` process (which i realize isn't the RPC port, but is still odd).

It's been very difficult to figure out what is a symptom and what is a cause in this problem, but the crux is that a single write to the Raft database is taking taking a significant amount of time (1 - 2s, sometimes more).

![image](https://user-images.githubusercontent.com/1012772/52904256-17567e80-31ef-11e9-89c5-54017fbb7d53.png)

Which leads me back to the leader making RPC calls to itself, which seems like a very odd thing to be doing, and would explain a lot if the RPC call which stuck in some odd loop.

**Comment by johnrengelman** [comment]
Seems like the self connection is the autopilot health check on the server. Funny that I don't see this connection hanging open on any other cluster.

**Comment by johnrengelman** [comment]
An update to this issue. We recently modified the config of another cluster to use the DatadogStatsd telemetry configuration and it immediately starting exhibiting these problems with high commit times and high replication times. We reverted the telemetry settings back to the standard statsd configuration and the cluster returned to normal metrics.

So apparently there is an issue in that library related to publishing metrics.

**Comment by LeoCavaille** [comment]
Thanks for the details @johnrengelman we are looking at your issue.
The sink used is provided by [go-metrics](https://github.com/armon/go-metrics/tree/master/datadog) which wraps the Datadog statsd client, it seems like there are some tunables that could be changed in go-metrics to make the sink more performant.
In the meantime, would you have any metrics from the agent where you enabled the sink especially looking at `system.udp.*` and `datadog.agent.dogstatsd.*` (if you use Agent 6)?
