### ISSUE TITLE
Case sensitive issue on snapshot restore

### ISSUE THREAD

**Issue by jasonmcintosh** [hashicorp/consul#5316]
#### Overview of the Issue
Snapshots start failing if someone register catalog node in different case.  We're seeing snapshot restore failure messages after rebooting servers, causing the clusters to fail.

https://github.com/hashicorp/consul/blob/5bdf130767edd4f435753b803828647bb2e0faee/agent/consul/state/catalog.go#L274
seems to be case sensitive (this is a guess).  Specific error message:

Feb  5 13:16:39 SERVER consul: 2019/02/05 13:16:39 [ERR] raft: Failed to restore snapshot: failed to restore snapshot 1234123412341234: check node "nodename" does not match node "UPPERNODENAME"

#### Reproduction Steps
Right now, this SEEMS like the steps - working on reproducing the issue to confirm:

Consul agent starts with standard node name registration
Process register with consul using catalog, which seems to replace the initial node registration
Seems to trigger snapshot failures afterewards.

**Comment by pierresouchay** [comment]
Which version of Consul?
We had similar issue in the past but if I am not mistaken, it has fixed in
https://github.com/hashicorp/consul/pull/4415 available from version 1.2.3+

**Comment by i0rek** [comment]
Closing now, but happy to reopen if there is still a problem.
