### ISSUE TITLE
 Question: determine client name/id from consul monitor logs

### ISSUE THREAD

**Issue by Nmishin** [hashicorp/consul#5319]
After update from Consul version 0.8.4 to version 1.3.1 we have errors in the consul monitor logs:
`[DEBUG] consul: dropping service "service" from result due to ACLs`
How can I determine which Consul client try to get this service and why this doesn't allow?

**Comment by pearkes** [comment]
This is kind of a duplicate of #4706, or at least very similar. I'm going to go comment on that issue with this use case.
