### ISSUE TITLE
[question] consul exec  production security policy

### ISSUE THREAD

**Issue by wuub** [hashicorp/consul#532]
We would like to leave consul exec enabled on most, if not all, of our nodes but:
 a) limit the number of people (and systems!) authorized to use it
 b) secure our cluster from being completely open, when a single node is compromised

KV ACL was our first attempt, but since nodes must be allowed to write an ack during exec, and since consul exec accepts kv --prefix, it doesn't seem to help much with point b)

Are some kind of exec ACLs on the roadmap?
Maybe exec RPC can piggyback on top of verify_incoming and a whitelisted set of authorized key fingerprints?

**Comment by jhmartin** [comment]
As an interim step perhaps the security could be delegated?  Sort of like the SSH 'ForceCommand' such that the requested command would be passed to some other command?  In this way I could validate that the command is either on a known whitelist, or verify that the command is signed in some manner by an authorized user.

Otherwise it is a very ugly security story.

**Comment by armon** [comment]
@jhmartin The interim solution is to disable exec support until the ACL framework covers it

**Comment by armon** [comment]
Question is answered, closing

**Comment by kaelumania** [comment]
I would also like to see feature, where we can decide which commands are whitelisted, e.g. block `rm -rf /`. The proposed interim step by @jhmartin sounds reasonable good to me. That way we can decide, if the command gets really executed or is being blocked by the node. A similar way would be to add a configuration option to the agent, which describes which command should be used to execute the command given by the exec request, e.g. `{ "exec_engine" : "/usr/local/bin/secure_bash" }` and maybe the exec carries only the parameters to this command.
