### ISSUE TITLE
[Enhancement] consul kv get/put -base64 option changed behavior

### ISSUE THREAD

**Issue by Nmishin** [hashicorp/consul#5341]
Hi, we upgraded Consul from 0.8.4 version to the 1.3.1 and see new undocumented in the changelog behavior of consul kv get/put  command with -base64 option:

**In the 0.8.4 version:**
`cat test_file`
`this is a test file`

`cat test_file | base64 | consul kv put -token=$CONSUL_HTTP_TOKEN "service/dc/test/base64" -`
`Success! Data written to: service/dc/test/base64`

`cat test_file | consul kv put -token=$CONSUL_HTTP_TOKEN "service/dc/test/plain" -`
`Success! Data written to: service/dc/test/plain`

`consul kv get -token=$CONSUL_HTTP_TOKEN "service/dc/test/plain"`
`this is a test file`

`consul kv get -token=$CONSUL_HTTP_TOKEN "service/dc/test/base64"`
`dGhpcyBpcyBhIHRlc3QgZmlsZQo=`

`consul kv get -base64 -token=$CONSUL_HTTP_TOKEN "service/dc/test/plain"`
`this is a test file`

`consul kv get -base64 -token=$CONSUL_HTTP_TOKEN "service/dc/test/base64"`
`dGhpcyBpcyBhIHRlc3QgZmlsZQo=`

**In the 1.3.1 version:**
`cat test_file `
`this is a test file`

`cat test_file | base64 | consul kv put -token=$CONSUL_HTTP_TOKEN "service/dc/test/base64" -`
`Success! Data written to: service/dc/test/base64`

`cat test_file | consul kv put -token=$CONSUL_HTTP_TOKEN "service/dc/test/plain" -`
`Success! Data written to: service/dc/test/plain`

`consul kv get -token=$CONSUL_HTTP_TOKEN "service/dc/test/plain"`
`this is a test file`

`consul kv get -token=$CONSUL_HTTP_TOKEN "service/dc/test/base64"`
`dGhpcyBpcyBhIHRlc3QgZmlsZQo=`

`consul kv get -base64 -token=$CONSUL_HTTP_TOKEN "service/dc/test/plain"`
`dGhpcyBpcyBhIHRlc3QgZmlsZQo=`

`consul kv get -base64 -token=$CONSUL_HTTP_TOKEN "service/dc/test/base64"`
`ZEdocGN5QnBjeUJoSUhSbGMzUWdabWxzWlFvPQo=`

As I understand in the version 0.8.4 if Consul was bug with `kv get -base64` - this command wasn't return base64, and on the 1.3.1. version this bug was fixed.

My concern - why this wasn't added to the changelog, because this is was unexpected change for us.

**Comment by mkeeler** [comment]
I believe this was the PR which fixed the issue: https://github.com/hashicorp/consul/issues/3736

The reason you don't see it mentioned in the 1.3.1 changelog is that it was released in v1.0.2 and included in that part of the changelog.
