### ISSUE TITLE
Logfile is write only in V1.4

### ISSUE THREAD

**Issue by varnson** [hashicorp/consul#5346]
logfile is write only in Redhat Linux

OS: Redhat Enterprise Linux Server release 6.9 (Santiago)
Consul: Ver1.4

#### Reproduction Steps
Steps to reproduce this issue, eg:

1. Create a cluster with 1 client nodes and 3 server nodes.
2. use -log-file=log/server.log in server command line.

then you can find that all log files are write only. (0200)

Reason:
In file consul/logger/logfile.go, Line57:
    os.OpenFile(newfilePath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 640)
I find that the last number is 640.
But in golang doc, the sample is 0640.
So I think that it should be fixed.
Golang doc: https://golang.org/pkg/os/#OpenFile

**Comment by toretto460** [comment]
Just opened a PR to fix that https://github.com/hashicorp/consul/pull/5354

**Comment by mkeeler** [comment]
@toretto460 Thanks again for the PR.
