### ISSUE TITLE
envoy 1.10 deprecated --v2-config-only

### ISSUE THREAD

**Issue by rafaelpirolla** [hashicorp/consul#5363]
#### Feature Description

To support envoy 1.10 we need to stop enforcing the --v2-config-only argument.

#### Use Case(s)

Some features of current envoy version could be needed and there is no way to run it with consul at this time.

**Comment by pearkes** [comment]
I'm going to close this as a duplicate of https://github.com/hashicorp/consul/issues/5323.

**Comment by sl1pm4t** [comment]
Hi @pearkes, you closed this issue in favor of #5323 but it has now closed and did not end up fixing this issue. Could this issue be re-opened?
