### ISSUE TITLE
Consul 1.4 for Linux kernel 2.6.32,Runtime error

### ISSUE THREAD

**Issue by wbt225** [hashicorp/consul#5364]
Consul for Linux kernel 2.6.32,Runtime error.
The error message:
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x1508dc1, 0x17)
	/goroot/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x1ee7c912044800, 0xc400000000)
	/goroot/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
	/goroot/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
	/goroot/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
	/goroot/src/runtime/proc.go:1193 +0x76

goroutine 1 [runnable, locked to thread]:
fmt.init()
	<autogenerated>:1 +0x112

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/goroot/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/goroot/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/goroot/src/os/signal/signal_unix.go:28 +0x41

**Comment by mkeeler** [comment]
@wbt225 Are you sure you are running on a 2.6.32 kernel? Error 38 is `ENOSYS` which means that the `epoll_pwait` system call is not implemented for your kernel.

**Comment by wbt225** [comment]
Sorry ,  2.6.18-308.el5  kernel.

**Comment by 42wim** [comment]
Go (and therefore also consul) doesn't support kernels that old. 

See https://github.com/golang/go/wiki/MinimumRequirements
