### ISSUE TITLE
Consul is becoming unresponsive in kubernetes

### ISSUE THREAD

**Issue by bikkinamahesh369** [hashicorp/consul#5375]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here if you have a question.

- Frequently asked questions: https://www.consul.io/docs/faq.html
- Consul Guides: https://www.consul.io/docs/guides/index.html

Any other questions can be sent to the Consul mailing list: https://www.consul.io/community.html

Hi All, I am running consul in kubernetes envirnoment . when trying to access consul service from other microservice. Sometimes i am getting this error... Consul not Reachable Get http://consul:8500/v1/kv/mahesh/valid_ip : dial tcp: lookup consul on 10.3.0.10:53: no such host\n" / # consul version
Consul v1.0.1
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

/ # consul members
Node Address Status Type Build Protocol DC Segment
consul.default 10.2.0.2:8301 alive server 1.0.1 2 dc1 <all>

/ # consul info
agent:
check_monitors = 0
check_ttls = 0
checks = 0
services = 0
build:
prerelease =
revision = 9564c29
version = 1.0.1
consul:
bootstrap = true
known_datacenters = 1
leader = true
leader_addr = 10.2.0.2:8300
server = true
raft:
applied_index = 9950196
commit_index = 9950196
fsm_pending = 0
last_contact = 0
last_log_index = 9950196
last_log_term = 4
last_snapshot_index = 9942597
last_snapshot_term = 4
latest_configuration = [{Suffrage:Voter ID:ceb0b3d6-6557-395d-3242-4266dc6d0c4f Address:10.2.0.8:8300}]
latest_configuration_index = 1
num_peers = 0
protocol_version = 3
protocol_version_max = 3
protocol_version_min = 0
snapshot_version_max = 1
snapshot_version_min = 0
state = Leader
term = 4
runtime:
arch = amd64
cpu_count = 8
goroutines = 139
max_procs = 8
os = linux
version = go1.9.2
serf_lan:
coordinate_resets = 0
encrypted = false
event_queue = 1
event_time = 2
failed = 0
health_score = 0
intent_queue = 0
left = 0
member_time = 2
members = 1
query_queue = 0
query_time = 1
serf_wan:
coordinate_resets = 0
encrypted = false
event_queue = 0
event_time = 1
failed = 0
health_score = 0
intent_queue = 0
left = 0
member_time = 2
members = 1
query_queue = 0
query_time = 1
Lot connection are opened from consul client api... Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address Foreign Address State
tcp 0 0 consul-0.consul.default.svc.cluster.local:47404 consul-0.consul.default.svc.cluster.local:8300 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.3:39094 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.49:50162 TIME_WAIT
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:43370 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:43826 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:43366 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:42946 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.49:49918 TIME_WAIT
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:43814 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:42950 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.48:51752 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:43362 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.49:49960 TIME_WAIT
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.49:49958 TIME_WAIT
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:43818 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.49:50144 TIME_WAIT
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:42952 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.3:39088 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.15:43820 ESTABLISHED
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.49:49920 TIME_WAIT
tcp 0 0 consul-0.consul.default.svc.cluster.local:8500 ::ffff:10.2.0.3:39098 ESTABLISHED . Lot of connectiones open... Is this is problem , consul is becoming unresposive or any other root cause?... please can anyone help me??

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
