### ISSUE TITLE
token anonymous is not used when no token with API

### ISSUE THREAD

**Issue by varnson** [hashicorp/consul#5380]
Consul Ver1.4.0
OS: renhat enterprise linux 7.4

When I call  /v1/catalog/services with no token, it returns [].
When I call  /v1/catalog/services?token=anonymous , it returns services list as wished.

My config file:
"acl":{
"default_policy":"deny"
}
and I had added read policy to anonymous.

docs(https://www.consul.io/docs/agent/acl-system.html) had said that "The anonymous token is used when a request is made to Consul without specifying a bearer token".

But why it is different in my Consul System?

**Comment by mkeeler** [comment]
@varnson Do you have a default token set on your servers by any chance? This would be the `acl.tokens.default` or `acl_token` configuration entries. Alternatively it could have been set through the API with the `v1/agent/token/acl_token` endpoint.

The default token can act as a per-agent anonymous token. If not could you describe your setup a little more. Are you querying a server directly or going through a client agent?

**Comment by varnson** [comment]
Thank you for your reply，I have a default token and now I see  it's the problem. I will close this issue.
