### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by Scorpiion** [hashicorp/consul#539]
Hi,

We are currently considering to deploy Consul on our servers. It's a mix of FreeBSD and Linux servers. Our PaaS system is also written in Go, and we cross compile Go code to both Linux and FreeBSD more or less on a daily basis. First I thought FreeBSD was support by Consul, by it seems to be missing here:
https://www.consul.io/downloads.html

I just wanted to ask what the "official" stand on FreeBSD support is, is it something that Hashicorp want to support but have lacked time and resource to do so far, or is it intentionally not supported?

_Ps. Congrats on the new funding round. Ds._

Regards, Robert

**Comment by theonewolf** [comment]
This is useful for FreeNAS users (that want FreeNAS devices to appear in a cluster).  Just chiming in with my 2 cents.  About to checkout Consul in a FreeNAS jail.

**Comment by tobiastom** [comment]
Is there a reason why the port [is outdated](http://www.freshports.org/sysutils/consul/)?
