### ISSUE TITLE
UI: Serve UI with external web server

### ISSUE THREAD

**Issue by Scorpiion** [hashicorp/consul#540]
Hi,

Not sure if this is a bug or feature request. It is supposed to work to serve the UI with Nginx (for example) or is that explicitly prohibited?

The [docs](http://www.consul.io/intro/getting-started/ui.html) states:
_"You don't need a separate web server to run the web UI. The Consul agent itself can be configured to serve the UI."_

Sounds like it should work to use a separate web server as well, but I have found that it does not works since the UI depend on an internal REST interface that does not exist if the "-web-ui" parameter is not passed to the client during startup.

Not working:
`consul agent -bind=10.0.0.14 -join=10.0.0.11 -data-dir=/tmp/consul`

Working:
`consul agent -bind=10.0.0.14 -join=10.0.0.11 -data-dir=/tmp/consul -ui-dir /usr/share/nginx/html`

The missing REST API is "/v1/internal/ui", example:
`curl -v 127.0.0.1:8500/v1/internal/ui/nodes`

To reproduce the setup on a fresh Ubuntu install (with consul install), run these commands to install the files:

```
sudo apt-get install nginx -y
wget https://dl.bintray.com/mitchellh/consul/0.4.1_web_ui.zip
unzip 0.4.1_web_ui.zip
sudo mv /usr/share/nginx/html /usr/share/nginx/html_old
sudo mkdir -p /usr/share/nginx/html 
sudo cp -r dist/* /usr/share/nginx/html/
sudo rm /etc/nginx/sites-enabled/default
```

Nginx conf for Consul Web UI (/etc/nginx/sites-enabled/consul):

```
server {
  listen 80 default_server;

  root /usr/share/nginx/html;
  index index.html index.htm;

  server_name localhost;

  location /ui {
    try_files $uri $uri/ =404;
  }

  # Forward consul API requests
  location /v1 {
    proxy_pass http://127.0.0.1:8500;    
  }
}
```

I have not digged into the code at this moment, but I assume the "-ui-dir" parameter activates the REST resource "/v1/internal/ui". Maybe there should be a separate parameter than enables the "/v1/internal/ui" resource without enabling the static files serving?

I guest this sort of work as a workaround, but it feels wrong:
`consul agent -bind=10.0.0.14 -join=10.0.0.11 -data-dir=/tmp/consul -ui-dir null`

**Comment by anroots** [comment]
> Do you not want to set the actual ui-dir for a particular reason? Are the files not available?

See #1076. I want to protect the UI with HTTP Basic Auth via Nginx. Currently, I've set Consul to serve the web UI, but the port is not published. I then link to it from a Nginx (container) and only allow queries to upstream Consul if the user is authenticated.

It would be cleaner and more secure if I could remove the web UI from the Consul container and host it entirely in Nginx.

**Comment by romarioschneider** [comment]
My works config:

```
server {

    listen 80;
    server_name my.consul.com;
    rewrite     ^   https://$server_name$request_uri? permanent;
    access_log /var/log/nginx/my.consul.com_80_access.log;
    error_log /var/log/nginx/my.consul.com_80_error.log warn;
}

server {

    listen 443;
    server_name my.consul.com;

    access_log /var/log/nginx/my.consul.com_443_access.log;
    error_log /var/log/nginx/my.consul.com_443_error.log warn;

    ssl on;
    ssl_certificate /etc/nginx/ssl/my.consul.com.crt;
    ssl_certificate_key /etc/nginx/ssl//my.consul.com.key;

    location / {

        auth_basic "Need Auth";
        auth_basic_user_file /etc/nginx/passwd;

        root /usr/share/nginx/omnic;
        index index.html;

        }

    location /consul/ui/ {

        proxy_pass http://172.22.2.10:8500/ui/;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    }

    location /v1/ {

        proxy_pass http://172.22.2.10:8500/v1/;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}
```

**Comment by boomshadow** [comment]
I, also, didn't need to do the `-ui-dir` option. Here is my working config for HTTP. If you want to do HTTPS with Nginx, that also works. I tested it out.

    server {
        listen         80;
        server_name    consul.mydomain.com;
        location / {
            proxy_pass        http://127.0.0.1:8500;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_redirect off;
        }
        access_log /var/log/nginx/consul.mydomain.com.log;
    }
