### ISSUE TITLE
-node on CLI, but node_name in config

### ISSUE THREAD

**Issue by danbst** [hashicorp/consul#5413]
#### Feature Description

I've tried to override node name in consul config (using JSON syntax):
```
{
   "node": "nomad_01",
   ....
}
```
However got an error:
```
Mar 02 09:43:40 consul consul[286]: ==> Error parsing /etc/consul.json: 1 error(s) occurred:
Mar 02 09:43:40 consul consul[286]: * invalid config key node
```
I was very surprised, because documentation says it is a valid CLI option (https://www.consul.io/docs/agent/options.html#_node).

Maybe add some notice to docs that this option is called `"node_name"` in configuration file? Wonder if there are any other such misleading options.

#### Use Case(s)

In my case I wanted to change id of agent without using CLI or changing hostname.

**Comment by danbst** [comment]
Also, minor, equivalent config key in `nomad` is called `name`, not `node`. Another little confusion

**Comment by i0rek** [comment]
`node_name` is in the docs as well (and has a reference back to `-node`): https://www.consul.io/docs/agent/options.html#node_name. But I totally see your point. We definitely accept a PR for a reference in `-node`. 

It would be great if our options would be more consistent across CLI and config file as well as across products, but this is means quite some work and won't be done in short term.

**Comment by danbst** [comment]
strange, how didn't I notice that? Good then.
