### ISSUE TITLE
Documentation for ACL in Consul 1.4 is insufficient

### ISSUE THREAD

**Issue by rancid-racer** [hashicorp/consul#5415]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Followed the documentation for v 1.4 for ACL and configuring the policy_ttl and token_ttl settings.  The documentation on https://www.consul.io/docs/agent/options.html#acl indicates that this is in seconds for the TTL Value.  When attempting to set the value to [int] 300 and restart consul an error is thrown that a string is being expected in the field.  I quoted the numerical value and received another start error indicating that a unit must be provided.

I was able to resolve this issue by using "300s" in the field. These values are indicated nowhere!!

Configuration documentation for ALL of the Hashicorp products are awful and at no point do they clearly indicate what valid values are or the expected type.  Configuration of any products has been a quest of trial and error and anyone publishing documentation should be embarrassed.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl ...`
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by Salgat** [comment]
Agreed, this confused the hell out of me. Ironically your issue here is answering my question of what units I use for that value.

**Comment by bbaassssiiee** [comment]
## Too many options
Configuration options listings like [this](https://www.consul.io/docs/agent/options.html) might be exhaustive, they also exhaust the readers.

### Improve like this:
- Set up a Consul cluster with agents and have a default deny ACL policy using [Ansible role](https://github.com/brianshumate/ansible-consul). 
- Document adding a service with health checks using minimal policies and token.
- Document how to query for that service with a read-only policy.
### Create blog post please...
