### ISSUE TITLE
Consul server and the command 'consul members'

### ISSUE THREAD

**Issue by SweeXordious** [hashicorp/consul#5425]
Hello,

I have a simple question considering consul services.
When i create a service and host it using a consul server, i notice that the members addresses dont show up when i use the commad 'consul members', i get nothing. 
My question is : Is it possible to make the server behave like a client and subscribe to the service so that i can see its address using the 'consul members' command along with the other clients addresses ?

Thank you so much for any help.

**Comment by tradel** [comment]
@SweeXordious, the `consul members` command lists the servers and agents that Consul knows about. If you want to see a list of services, use the command `consul catalog services`.

Servers are able to host services just like clients are. In fact, the servers register a "consul" service, which you will see in the output from the above command.

**Comment by SweeXordious** [comment]
> @SweeXordious, the `consul members` command lists the servers and agents that Consul knows about. If you want to see a list of services, use the command `consul catalog services`.
> 
> Servers are able to host services just like clients are. In fact, the servers register a "consul" service, which you will see in the output from the above command.

Thank you for your reply, but t tried that, but i guess the 'catalog' option is not available for me 


`vagrant@host-1:~$ consul catalog services
usage: consul [--version] [--help] <command> [<args>]

Available commands are:
    agent          Runs a Consul agent
    event          Fire a new event
    exec           Executes a command on Consul nodes
    force-leave    Forces a member of the cluster to enter the "left" state
    info           Provides debugging information for operators.
    join           Tell Consul agent to join cluster
    keygen         Generates a new encryption key
    keyring        Manages gossip layer encryption keys
....
`

**Comment by mkeeler** [comment]
@SweeXordious You must be running an older version of Consul. The `catalog` subcommand was added in version 0.9.0.

**Comment by SweeXordious** [comment]
> @SweeXordious You must be running an older version of Consul. The `catalog` subcommand was added in version 0.9.0.

Seems to be the case :D Thank you.
