### ISSUE TITLE
 "Catalog.Register" RPC failed to server 10.52.23.32:8300: rpc error making call: rpc error making call: Invalid service address

### ISSUE THREAD

**Issue by JamesJoe-C** [hashicorp/consul#5426]
### Log Fragments or Link to gist
Client:
<pre>
Mar 05 15:50:44 consul-agent1 consul[99571]: 2019/03/05 15:50:44 [ERR] consul: "Catalog.Register" RPC failed to server 10.52.23.32:8300: rpc error making call: rpc error making call: Invalid service address
Mar 05 15:50:44 consul-agent1 consul[99571]: 2019/03/05 15:50:44 [WARN] agent: Syncing service "dingding-proxy" failed. rpc error making call: rpc error making call: Invalid service address
Mar 05 15:50:44 consul-agent1 consul[99571]: 2019/03/05 15:50:44 [ERR] agent: failed to sync remote state: rpc error making call: rpc error making call: Invalid service address
Mar 05 15:50:47 consul-agent1 consul[99571]: 2019/03/05 15:50:47 [ERR] consul: "Catalog.Register" RPC failed to server 10.52.23.4:8300: rpc error making call: rpc error making call: Invalid service address
Mar 05 15:50:47 consul-agent1 consul[99571]: 2019/03/05 15:50:47 [WARN] agent: Syncing service "dingding-proxy" failed. rpc error making call: rpc error making call: Invalid service address
Mar 05 15:50:47 consul-agent1 consul[99571]: 2019/03/05 15:50:47 [ERR] agent: failed to sync remote state: rpc error making call: rpc error making call: Invalid service address

</pre>

### consul version for both Client and Server

<pre>
# consul version
Consul v1.4.2
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
</pre>

### consul info for both Client and Server
Client:
<pre>
# consul info

agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 2
build:
	prerelease =
	revision = c97c712e
	version = 1.4.2
consul:
	acl = disabled
	known_servers = 2
	server = false
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 68
	max_procs = 2
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 13
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 52
	members = 3
	query_queue = 0
	query_time = 1

]
</pre>
Server:
<pre>
# consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = c97c712e
	version = 1.4.2
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.52.23.31:8300
	server = true
raft:
	applied_index = 11504
	commit_index = 11504
	fsm_pending = 0
	last_contact = 0
	last_log_index = 11504
	last_log_term = 13
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:352ecf6e-a40d-5a44-b03a-8c796421b8a6 Address:10.52.23.4:8300} {Suffrage:Voter ID:06544c79-19fa-4ea0-435d-35779c61da62 Address:10.52.23.32:8300} {Suffrage:Voter ID:0f6f42db-400c-e2b6-fd00-8a0e2ad2fcdb Address:10.52.23.31:8300}]
	latest_configuration_index = 285
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 13
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 114
	max_procs = 1
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 13
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 52
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 11
	members = 3
	query_queue = 0
	query_time = 1
</pre>
### Operating system and Environment details
Centos 7

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.

**Comment by bbaassssiiee** [comment]
Please update this page for this error: https://www.consul.io/docs/common-errors.html
