### ISSUE TITLE
Connect proxy registration via HTTP API

### ISSUE THREAD

**Issue by andye2004** [hashicorp/consul#5438]
I am registering a proxy via the HTTP API following the example [here](https://github.com/hashicorp/nomad-guides/tree/master/application-deployment/consul-connect-with-nomad), the proxies are being registered but there are no automatic health checks being generated.

I need to explicitly add in a check for the TCP proxy to get it to appear. Is this by design?

**Comment by pearkes** [comment]
If you're manually registering proxies in the case of Nomad (currently, while a full integration is planned), you do need to manually register health checks as well. The [sidecar_service helper](https://www.consul.io/docs/connect/proxies/sidecar-service.html) talks more about how this is simplified in certain scenarios. Hope that helps.

**Comment by andye2004** [comment]
@pearkes Thanks Jack.
