### ISSUE TITLE
HTTP health check not set as critical when request is cancelled

### ISSUE THREAD

**Issue by maximepiton** [hashicorp/consul#5440]
Hello there,

Multiple times, we had the case of a service being declared as healthy in consul, whereas not responding to health check requests. As seen in the logs, the health check requests were continuously failing, likely because of a faulty service :

`2019/03/07 08:38:04 [WARN] agent: Check "7d044b1b74fe56f986febac56a51459bbbd20863" error while reading body: net/http: request canceled (Client.Timeout exceeded while reading body)`

Looking to the code of the http health check logic, it does appear to me that when the request is cancelled during the `resp.Body` stream being read, the warning message seen above is logged, but the status of the health check is not updated :
https://github.com/hashicorp/consul/blob/master/agent/checks/check.go#L418

=> Shouldn't the health check be updated to a critical state in that case?

Thanks for your answers

**Comment by pierresouchay** [comment]
@maximepiton to me, the status is properly updated a few lines below:
```
} else {
		// CRITICAL
		c.Logger.Printf("[WARN] agent: Check %q is now critical", c.CheckID)
		c.Notify.UpdateCheck(c.CheckID, api.HealthCritical, result)
	}
```

**Comment by alinoeabrassart** [comment]
@pierresouchay In this case, the statusCode is 200 and is read properly but if, when reading the body, the request is cancelled, the status remains 200 but the body read never finishes hence the warning. This is where the confusion comes from I guess, seeing the 200 we would expect the request to end properly but in this case it never finishes not because health checks are too close together (cancellation) but because the service is not healthy and cannot answer properly (never finishes the body write).

Reading Consul documentation we can see that only the status code is considered when doing the healthcheck but maybe a proper body should be expected too ?

**Comment by pierresouchay** [comment]
Having cannot guess the meaning of text, so, the app should be modified to return http 500 or 502 when it occurs

Another way (if you cannot modify the app for instance) would be to use a script that would parse the result, return 200, except when text contains the string you mentioned

**Comment by alinoeabrassart** [comment]
Sorry maybe I was not very clear. There is no string returned, the fact is that the write of the response body on the server part is never finished and that causes the error (net/http error) to be raised. Maybe this is the expected result and we will try to modify the app accordingly. It could worth mentioning in the documentation that a full http response with a proper body is not expected, an http response with an incomplete body and a status code set at 200 will be considered healthy too.

**Comment by pearkes** [comment]
If an HTTP service returns HTTP 200 Consul will not mark it critical. Any subtle change to that "contract" that is well documented could have unintended side-effects for other users who may have the reverse problem, so we're unlikely to change it for this reason (which I would say is not ordinary). 

I liked @pierresouchay's suggestions for a workaround: wrap the HTTP check in a script that handles your specific use-case, or update the application rendering the response to not return 200 in that scenario.
