### ISSUE TITLE
Incorrect documentation for Service Leaf Certificate API

### ISSUE THREAD

**Issue by andye2004** [hashicorp/consul#5447]
Consul version: v1.4.3

I have, for the last 3 hours been trying to work out how to generate a certificate for a native application to use Consul Connect based on the documentation [here](https://www.consul.io/api/agent/connect.html#service-leaf-certificate), where it describes the `Service Leaf Certificate` endpoint as:-

`/agent/connect/ca/leaf/:service`

and then gives an example as:-

`curl http://127.0.0.1:8500/v1/connect/ca/leaf/web` 

The problem is, neither of these are correct, I realised this after re-reading the section on [`Accepting Inbound Connections`](https://www.consul.io/docs/connect/proxies/integrate.html#accepting-inbound-connections) where it has a link to the HTTP API but has the link text as:-

`/v1/agent/connect/ca/leaf/`

Note that this is actually a combination of both the API method definition and ALSO the example and the actual endpoint is:-

`http://127.0.0.1:8500/v1/agent/connect/ca/leaf/web`

which does work!

Incidentally, it looks like the .../ca/roots documentation in the HTTP API page is also wrong as it is also documented similar to the leaf API endpoint but amusingly works for both and contributes towards confusion as to why the leaf endpoint returns a 404.

`curl -iv http://127.0.0.1:8500/v1/connect/ca/roots`

and

`curl -iv http://127.0.0.1:8500/v1/agent/connect/ca/roots`

**Comment by pearkes** [comment]
Thanks for pointing this out, there are definitely some inconsistencies there. Would love to see a PR for this, the documentation is located in the `website/` directory.

**Comment by andye2004** [comment]
@banks Apologies Paul, I had actually made the necessary changes but simply forgot to commit / push them and to raise a PR for them. I've done this now although I know it has been closed, primarily because it is a more comprehensive update.
