### ISSUE TITLE
In cluster mode, the registration service is sent to the Client side (the same is true for Server).

### ISSUE THREAD

**Issue by philiahe** [hashicorp/consul#5448]
#### Reproduction Steps

1. Create a cluster with 1 client node and 3 server nodes
![image](https://user-images.githubusercontent.com/8486693/54018571-01bbef80-41c4-11e9-8056-90c1be96eb0b.png)
![image](https://user-images.githubusercontent.com/8486693/54018695-55c6d400-41c4-11e9-8cae-523c623c7136.png)

2. The service is registered on the client side and can be seen on the client page, but not on the Server side
![image](https://user-images.githubusercontent.com/8486693/54019006-0fbe4000-41c5-11e9-8f56-c2a04eb6bd60.png)

![image](https://user-images.githubusercontent.com/8486693/54018902-cc63d180-41c4-11e9-8c20-511948b0021a.png)

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 567e41ff
	version = 1.4.3
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 192.168.35.160:8300
	server = true
raft:
	applied_index = 2769
	commit_index = 2769
	fsm_pending = 0
	last_contact = 64.916153ms
	last_log_index = 2769
	last_log_term = 13
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:b33a08ca-177e-93c4-1727-1a35eaf7a9f0 Address:192.168.35.160:8300} {Suffrage:Voter ID:7619ace2-47f0-6049-47cf-3cbb480595da Address:192.168.35.161:8300} {Suffrage:Voter ID:22f3292e-913f-09a0-c0ad-72e53ce9a3ac Address:192.168.35.163:8300}]
	latest_configuration_index = 1159
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 13
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 79
	max_procs = 2
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 20
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 11
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 567e41ff
	version = 1.4.3
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 192.168.35.160:8300
	server = true
raft:
	applied_index = 2762
	commit_index = 2762
	fsm_pending = 0
	last_contact = 0
	last_log_index = 2762
	last_log_term = 13
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:b33a08ca-177e-93c4-1727-1a35eaf7a9f0 Address:192.168.35.160:8300} {Suffrage:Voter ID:7619ace2-47f0-6049-47cf-3cbb480595da Address:192.168.35.161:8300} {Suffrage:Voter ID:22f3292e-913f-09a0-c0ad-72e53ce9a3ac Address:192.168.35.163:8300}]
	latest_configuration_index = 1159
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 13
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 105
	max_procs = 2
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 5
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 20
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 11
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details
centos7

**Comment by philiahe** [comment]
Even if the cluster is in three Server modes, the service information will only exist on which machine the service is registered.If the registered Server fails, other servers will not provide service information.

**Comment by pierresouchay** [comment]
@philiahe This is usually an ACL issue.

Ensure that the token you are using to register the checks/service have rights in the cluster

You might verify this with https://github.com/pierresouchay/consul-ops-tools/blob/master/bin/check_consul_consistency.sh

**Comment by philiahe** [comment]
> @philiahe This is usually an ACL issue.
> 
> Ensure that the token you are using to register the checks/service have rights in the cluster
> 
> You might verify this with https://github.com/pierresouchay/consul-ops-tools/blob/master/bin/check_consul_consistency.sh
> 
> Looking at the logs of agent also might give you some hints about what is going on


Thank you for your reply~ 

The following is the error prompted by the script：
```
[root@centos-3 ~]# ./check_consul_consistency.sh -l info
curl: option --retry-connrefused: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
             [-l preload] [-m mark] [-M pmtudisc_option]
             [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
             [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
             [-W timeout] destination
[ERROR] Machine  is not reachable; FQDN: ; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> -x +short
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 64585
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: Message has 11 extra bytes at end
;; QUESTION SECTION:
;+short.in-addr.arpa.		IN	PTR
;; Query time: 2164 msec
;; SERVER: 192.168.35.2#53(192.168.35.2)
;; WHEN: Sun Mar 10 12:00:27 CST 2019
;; MSG SIZE  rcvd: 48

```

**Comment by philiahe** [comment]
I started the cluster without using the ACL.

Here is the script for one of the nodes:
`consul agent-server-data -dir=/opt/module/consul -node=centos-4 -bind=192.168.35.163 -client=0.0.0.0 -bootstrap-expect 2 - ui-datacenter =apigateway-1 &`

**Comment by shineyjg** [comment]
i got the same problem. Did you solve the problem? Is it a ACL issue? Someone give some tips? thank u.

**Comment by philiahe** [comment]
> i got the same problem. Did you solve the problem? Is it a ACL issue? Someone give some tips? thank u.

集群模式应该是没问题，Consul的生命周期是正常退出就会触发leave事件，突然宕机或者断网是不会触发leave的，服务在其他节点可以找到。

如果你是用Ocelot会遇到另一个问题，就是Ocelot无法查找failed状态下Consul节点的信息。我已经跟Ocelot提了PR了。

https://github.com/ThreeMammals/Ocelot/pull/810

**Comment by shineyjg** [comment]
注册在client上的service为什么没有持久化存储到server？client一退出，整个server集群都没有这个service的信息了！设计应该不是这样的吧。怎么避免？

**Comment by philiahe** [comment]
1，Client是单点，**异常**退出后信息依然在Service集群上，所以设计上是没问题的。
2，可以通过Vip的方式做负载，目前我们的部署方式是每台服务器都会有Client，因为Client本身是很轻量级的，服务信息是保存在Server的各个节点中的。

**Comment by shineyjg** [comment]
你提的这个issue不就是在client端注册了服务无法广播到其它server端吗？我这里场景一样：
起3个server和2个client
在其中一个client上注册服务。这时候整个集群确实能看到该服务在其中的一个client node上。（为什么不在所有node上？）
接下来退出这个client。按理通过另一个client或其它server都还应该有该服务的信息。但实际上是服务不见了。 
如果重启那个故意退出的client，服务又回来了。

注：
我启动时固定了node name和id。
查看日志都正常。

我的问题是：
1. 为什么注册服务到其中一个client的时候，只能看到该服务在那个client上，无法广播到其它server和client？按理client是无状态的，注册的服务信息不是应该保存到server节点上吗？为什么注册时用的那个client退出，整个集群就丢失了该服务？
2. 你提的这个issue到底解决了吗？怎么解决的？

**Comment by philiahe** [comment]
1、Client上的注册好的服务是会同步到Server端的；
我一直在强调“异常”退出的情况，直接Ctrl+C或者重启都是“正常”退出。看下Consul的日志就明白，Leave表示节点要退出集群，同时把节点中的服务都注销掉。

2、这是Consul独有的机制，算不上Issue。Consul和Zookeeper，Etcd这类注册中心设计时就不一样。

**Comment by shineyjg** [comment]
感谢！我这里还有两个问题：
1. 如果正常退出，服务就注销掉。如果注册时用的client所在机器维护需要重启，在重启期间岂不是服务不可用。
2. 如果异常退出，异常退出注册服务时用的client，集群中确实还有服务，但服务状态是不健康的。见下图
![consul](https://user-images.githubusercontent.com/1079398/54405756-776b1280-4712-11e9-8fba-6912fc4bb25f.png)
这时候服务还是不可用（感觉服务健康检查也必须通过当初注册时的client来完成）

这样的设计怎么能保证服务持续可用呢？

**Comment by philiahe** [comment]
1，重启很快；

2，根据业务场景不同服务会注册到多个Client，Client高可用可以引入其他负载组件（HAProxy/Keepalive）；

**Comment by shineyjg** [comment]
> 建议把不同服务注册到多个Client，Client高可用还可以引入其他负载组件（HAProxy/Keepalive）；

负载组件不是问题。 关键现在client是有状态的，崩溃了一台client，通过这一台client注册的服务就不见了或健康检测不通过，负载均衡无法解决这个问题。

总感觉这是用的姿势有问题，希望有人解答这个疑问。因为从文档上看client是轻量的，应该只是转发请求到server，但实际测试结果，就是只有这台client的/consul/data/services目录下有持久化服务信息文件，其它client和server上都没有！ 从高可用设计角度出发也不应该是这样的。 

我准备查下源码来搞清楚这个问题。

**Comment by philiahe** [comment]
节点宕机了，节点本身是不健康的。你可以访问别的Client或者直接访问Server都是可以获取到服务，只要服务是健康的就行。

**Comment by shineyjg** [comment]
> 节点宕机了，节点本身是不健康的。你可以试试访问别的Client或直接走Server都可以获取到服务，只要服务是健康的就行。

一台client宕机（当然这台就无法访问了），就是访问了别的client或server获取不到服务，或者获取到服务，但显示服务不在健康状态

**Comment by philiahe** [comment]
后台服务可以访问的。

**Comment by philiahe** [comment]
curl -s 127.0.0.1:8500/v1/catalog/service/{你的服务名} | python -m json.tool

**Comment by crazy-pizza** [comment]
@shineyjg 你的问题解决了吗，我现在跟你有同样的疑惑
