### ISSUE TITLE
Automatically tagging services with agent specific tags

### ISSUE THREAD

**Issue by janitha** [hashicorp/consul#545]
It would be useful to be able to configure a set of default_tags in the agent that are automatically applied to any service registered with that agent. 

Example Usecase: A situation where machines in a network are grouped together (eg. group-foo, group-bar). At the moment, when a service is registered from a machine from "group-foo", each service's service definition needs to explicitly specify the tag "group-foo". With this proposed feature, the user only needs to specify the default_tags=["group_foo"] for consul agent, and any service registering through the agent would automatically get the "group-foo" tag. 

An alternate method would be to able to allow tagging the consul agents (instead of adding tags to the service), and during querying, one could restrict results only to certain agent tags.

**Comment by armon** [comment]
I understand. I think for now this doesn't seem broadly useful to me, and is probably better solved in the tools that are generating the service definitions rather than in Consul itself.

**Comment by slackpad** [comment]
The https://www.consul.io/docs/agent/options.html#node_meta feature should meet this need, and you can search the catalog by this for nodes and services.
