### ISSUE TITLE
Health check removed when deregister not-linked service

### ISSUE THREAD

**Issue by vfrz** [hashicorp/consul#5456]
#### Overview of the Issue

I have two service registered with one health check per service, when I deregister the first service, the health check of the second get deregistered but continue to check.

** Fix proposal PR: #5457 **

#### Reproduction Steps

1. Create Service 1 with params:
```
ID = "service1"
Name = "Service 1"
```
2. Create Service 2 with params:
```
ID = "service2"
Name = "Service 2"
```
3. Create Check 1 with params:
```
ID = "check1"
Name = "Check 1"
ServiceID = "service1"
```
4. Create Check 2 with params:
```
ID = "check2"
Name = "Check 2"
ServiceID = "service2"
```
5. Deregister Service 1
6. List checks using `/agent/checks` endpoint
7. Check 2 has been deregistered but still running (see it in the console / log)

(8. After restarting Consul, Check 2 is appearing again)

### Consul and environment info
Using Consul v1.4.3 on Windows 10 x64

Can't reproduce using v1.4.2, the bug was surely introduced with this commit: https://github.com/hashicorp/consul/commit/2aac4d5168cc761ca58f2500e65ec1874cb9f168

I'll update the issue alongside my research.

**Comment by pschultz** [comment]
Script for easy reproducing (run `consul agent -dev -node=localhost` first):

```sh
# Register two service instances
for port in 31508 31226; do
    jq --arg port $port -n '{
        "Address": "127.0.0.1",
        "Port": $port|tonumber,
        "Check": {
            "Interval": "5s",
            "HTTP": ("http://localhost:"+$port+"/health-check")
        },
        "Name": "my-service",
        "ID": ("my-service-"+$port)
    }' | curl -XPUT localhost:8500/v1/agent/service/register -d@-
done

# Verify two checks exist (plus Consul's usual serfHealth check)
curl localhost:8500/v1/health/node/localhost

# Deregister *one* instance
consul services deregister -id my-service-31508

# Only Consul's serfHealth check remains
curl localhost:8500/v1/health/node/localhost
```
