### ISSUE TITLE
Feature Request: Open Source Network Segmentation

### ISSUE THREAD

**Issue by RcRonco** [hashicorp/consul#5459]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description
Open sourcing Network Segments feature from Consul EE.

#### Use Case(s)
In segmented environment consul can't be in "mesh" with other consul clients, which causing to consul become unstable.
This use case makes Consul unusable in segmented networks which  I think need to be a basic feature of Consul to be adopted in more organizations.

**Comment by pearkes** [comment]
Thanks for the feedback, @RcRonco. 

I wanted to link to some prior discussion about another HashiCorp project from @mitchellh to try and set some context here.

https://github.com/hashicorp/vault/issues/132#issuecomment-320880698

We try to be very careful in selecting features for the proprietary version of our product that best align with what we believe larger scale organizations need, in an effort to ensure we can build a sustainable business and support the open source functionality in the long term. This is a tough balance, and the needs of all sizes of organizations differ, but we do our best to work through the details for each feature and make our decision carefully. Ultimately, we believe network segments as a feature is in this category. We recognize the criticality of standing behind liberally licensed OSS philosophically but make trade-offs to ensure the success of the project.

Thank you for opening this issue and bringing this up. We are definitely open to questions and are happy to explain our reasoning for the decision.

**Comment by FilipK-CZ** [comment]
Still the same decision?
