### ISSUE TITLE
how to join multi address when deploy by docker

### ISSUE THREAD

**Issue by ryzencool** [hashicorp/consul#5466]
when deploy without docker, 
`
consul join --http-addr 192.168.2.211:8500 192.168.2.210
`
worked, but  with docker, how to use commandLine parameter `-join` to config multi address, in other words, what is the format with multi address

**Comment by mkeeler** [comment]
@ryzencool The command will take multiple addresses as positional args and will iterate through all of them attempting to join all of them.

In general you can issue the command like:

`consul join -http-addr <agent address> <join addr 1> [<join addr 2> ... <join addr N>]`
