### ISSUE TITLE
Consul agent pods cannot find acl

### ISSUE THREAD

**Issue by farrukh90** [hashicorp/consul#5472]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
On kubernetes we have 3 master 3 client nodes. Once it is deployed for some reason following message appears in logs

`

> 2019/03/11 17:23:43 [ERR] agent: failed to sync remote state: rpc error making call: ACL not found
> 2019/03/11 17:23:44 [ERR] agent: Coordinate update error: rpc error making call: ACL not found
> 2019/03/11 17:24:00 [ERR] agent: failed to sync remote state: rpc error making call: ACL not found
> 2019/03/11 17:24:10 [ERR] agent: Coordinate update error: rpc error making call: ACL not found
> 2019/03/11 17:24:19 [ERR] agent: failed to sync remote state: rpc error making call: ACL not found

`

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps
Our consul is deployed using helm 

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl ...`
1. View error

### Consul info for both Client and Server
Consul server 1.4.3
<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details
Kubernetes cluster Debain
OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by mkeeler** [comment]
@farrukh90 You will get those errors if you have enabled ACLs but not assigned an ACL token to the agents.

For information on how to setup ACLs you can refer to the guide: https://learn.hashicorp.com/consul/advanced/day-1-operations/acl-guide

**Comment by danlsgiga** [comment]
I believe this is a real bug... I'm having the same issue... the cluster comes up fine, we add the ACL token via API or via `consul acl set-agent-token default ...` and after a couple minutes the errors start to show up.

Running a simple `curl -s http://127.0.0.1:8500/v1/acl/token/self | jq -r .SecretID` returns the ACL token correctly but the logs are filling up with...

```bash
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: rpc error making call: ACL not found
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [WARN] agent: Service "_nomad-task-4yqpba2cji5tndurs6p5x5ncat6xahce" registration blocked by ACLs
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: ACL not found
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [WARN] agent: Service "_nomad-client-o4liis4qjul7fqdwkp57gkefcc53ku22" registration blocked by ACLs
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: rpc error making call: ACL not found
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [WARN] agent: Service "_nomad-task-xlgpzvtlqepe7at5uxrgpvrtqab5gijn" registration blocked by ACLs
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: rpc error making call: ACL not found
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [WARN] agent: Service "_nomad-task-xgcth3a6pdtpgrtsqbd2ic4zvddq23ni" registration blocked by ACLs
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: ACL not found
Mar 23 01:21:30 xx consul[20990]: 2019/03/23 01:21:30 [WARN] agent: Check "021c7b9cf5014a1de76327f91a8329b1a47769c1" registration blocked by ACLs
Mar 23 01:22:34 xx consul[20990]: 2019/03/23 01:22:34 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: ACL not found
Mar 23 01:22:34 xx consul[20990]: 2019/03/23 01:22:34 [WARN] agent: Service "_nomad-task-xlgpzvtlqepe7at5uxrgpvrtqab5gijn" registration blocked by ACLs
Mar 23 01:22:34 xx consul[20990]: 2019/03/23 01:22:34 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: rpc error making call: ACL not found
Mar 23 01:22:34 xx consul[20990]: 2019/03/23 01:22:34 [WARN] agent: Service "_nomad-task-xgcth3a6pdtpgrtsqbd2ic4zvddq23ni" registration blocked by ACLs
Mar 23 01:22:34 xx consul[20990]: 2019/03/23 01:22:34 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: rpc error making call: ACL not found
Mar 23 01:22:34 xx consul[20990]: 2019/03/23 01:22:34 [WARN] agent: Service "_nomad-task-4yqpba2cji5tndurs6p5x5ncat6xahce" registration blocked by ACLs
Mar 23 01:22:34 xx consul[20990]: 2019/03/23 01:22:34 [ERR] consul: "Catalog.Register" RPC failed to server xx:8300: rpc error making call: ACL not found
Mar 23 01:22:34 xx consul[20990]: 2019/03/23 01:22:34 [WARN] agent: Service "_nomad-client-o4liis4qjul7fqdwkp57gkefcc53ku22" registration blocked by ACLs
```

The annoying part is... even with `default_policy` set to "allow" this is happening!

Note: I've redacted IPs and hostnames from the log.

**Comment by pearkes** [comment]
Given we haven't heard anything based on our suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.
