### ISSUE TITLE
Consul discovers non-existent IP addresses of nomad services

### ISSUE THREAD

**Issue by lememta** [hashicorp/consul#5476]
#### Overview of the Issue

We have a consul cluster with 3 consul servers and multitude consul agents (consul ver 1.4.3). Additionally in each consul server we have a nomad service running. Originally, the 3 nomad service were running on address: 10.32.0.1, 10.32.0.2, 10.32.0.3 respectively. However, when we changed the ip address on those machines to 10.32.0.4, 10.32.0.5, 10.32.0.6, consul still discovers the old ip address + the new ones. These results in nomad to non-determistically be routed to the old ip addresses. For example if we do: `nomad status` sometimes I get
```
Error querying jobs: Get https://nomad:4646/v1/jobs: dial tcp 10.32.0.3:4646: i/o timeout
```

Moreover if we do `dig nomad.service` we see the following:
```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> nomad.service
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23207
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 22, AUTHORITY: 0, ADDITIONAL: 23

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nomad.service.groq.            IN      A

;; ANSWER SECTION:
nomad.service.     0       IN      A       10.32.0.1
nomad.service.     0       IN      A       10.32.0.2
nomad.service.     0       IN      A       10.32.0.3
nomad.service.     0       IN      A       10.32.0.4
nomad.service.     0       IN      A       10.32.0.5
nomad.service.     0       IN      A       10.32.0.6
```

 It looks like consul is still maintaining the old ip address.

Things we have tried to solve this issue with no positive result:

1. Manual Recovery Using `peers.json`
2. We tried using `consul services deregister <blah>` where `<blah>` is a json document like the following:
```
{
  "Datacenter": "dc1",
    "Node": "consul-0",
 "ServiceID": "_nomad-server-xc3voyalhntpwxbpwowm7gj3gwbntjwd
}
```

3. Manually removing the json files located in `data-dir/consul/consul/services`. Which resulted in the following warning:
```
...
 2019/03/11 20:40:07 [WARN] agent: Service "_nomad-server-xm52c2enjoly5qeciljqubwrqcie7usd" deregistration blocked by ACL
....
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 1
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = 48d287ef
        version = 1.2.3
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 55
        max_procs = 2
        os = linux
        version = go1.10.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1257
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 6763
        members = 90
        query_queue = 0
        query_time = 1
```

</details>

**Comment by shantanugadgil** [comment]
A couple of things here:

Q: By Nomad "service" I assume you mean Nomad and Consul servers are on the same set of machines (seems quite normal, I too have configuarations like this)
Could you post output of `consul members` and `nomad server members` (need to reconfirm the cmd for nomad servers, AFK right now)?

Q: How did you "change" the IPs, did you add new machines and then shutdown/remove the older?

Q: The old data will remain until GCed.

Q: could you post the Consul server and Nomad server configs? (without the sensitive things, of course)

**Comment by lememta** [comment]
> A couple of things here:
> 
> Q: By Nomad "service" I assume you mean Nomad and Consul servers are on the same set of machines (seems quite normal, I too have configuarations like this)

Yes both Nomad and Consul are running on the same machine.

> Could you post output of `consul members` and `nomad server members` (need to reconfirm the cmd for nomad servers, AFK right now)?
`consul members`

```
Node                 Address             Status  Type    Build  Protocol  DC     Segment
consul-0             10.32.0.4:8301     alive   server  1.4.3  2         dc1  <all>
consul-1             10.32.0.5:8301     alive   server  1.4.3  2         dc1  <all>
consul-2             10.32.0.6:8301     alive   server  1.4.3  2         dc1  <all>
c1             <ip-address>:8301  alive   client  1.2.3  2         dc1  <default>
c2             <ip-address>:8301  alive   client  1.2.3  2         dc1  <default>
....
```

`nomad server members`

```
Name            Address     Port  Status  Leader  Protocol  Build  Datacenter  Region
consul-0.dc1  10.32.0.4  4648  alive   false   2         0.8.7  dc1       dc1
consul-1.dc1  10.32.0.5  4648  alive   false   2         0.8.7  dc1       dc1
consul-2.dc1  10.32.0.6  4648  alive   false   2         0.8.7  dc1      dc1
```

Note that  I had to run multiple times `nomad server members` to get the above output. This is due to the fact it will hit the inexistent ip address:

```
* Region "dc1": Get https://nomad.service.nomad:4646/v1/status/leader?region=dc1: dial tcp 10.32.0.1:4646: i/o timeout
```
> Q: How did you "change" the IPs, did you add new machines and then shutdown/remove the older?

I shutdown the old machines and brought up a new machine.

> Q: The old data will remain until GCed.
What do you mean, can you clarify this item?

> Q: could you post the Consul server and Nomad server configs? (without the sensitive things, of course)
Nomad server config:
```
data_dir   = "/opt/nomad"
datacenter = "dc1"
region     = "dc1"

acl {
  enabled = true
}

tls {
  ca_file = "CA_FILE"
  rpc = true
  verify_server_hostname = true
}

vault {
  enabled = true
  ca_file = "CA_FILE"
}

server {
  enabled = true
  bootstrap_expect = 3
  authoritative_region = "dc1"
}

consul {
  address   = "IP_ADDRESS:PORT"
  cert_file = "CERT_PATH"
  ssl       = true
}

tls {
  cert_file              = "PATH"
  key_file               = "PATH"
  http                   = true
  rpc                    = true
}

vault {
  address = "IP_ADDRESS:PORT"
  create_from_role = "nomad-cluster"
}
```

**Comment by lememta** [comment]
@shantanugadgil any idea?

**Comment by shantanugadgil** [comment]
@lememta  nothing seems to pop out from the config.
though I assume you would tried to "force leave" the older Consul servers.

usually invasive things like `peers.json` should not be needed, you _should_ theoretically be able to "cleanup and reset" things from the cmd line.

FWIW, My Nomad server section has an expanded "server" section
```hcl
server {
  encrypt           = "<secret_key_here>"
  node_gc_threshold = "1h"
  job_gc_threshold  = "1h"
  eval_gc_threshold = "1h"
  enabled           = true

  bootstrap_expect   = 3
  rejoin_after_leave = true

  server_join {
    retry_join     = ["serverip1", "serverip2", "serverip3"]
    retry_max      = 0
    retry_interval = "30s"
  }
}
```
Of course, the `retry_join` uses cloud autojoin if deployed on a supported public cloud.

**Comment by pearkes** [comment]
Nomad maintains the lifecycle of service registration for itself in Consul via the integration -- including the address of the service/Nomad. This seems like a potential issue in Nomad and not Consul specifically. Consul will return results from the catalog as they exist in the catalog, but that needs to match what is registered and there isn't any sort of reconciliation process for that other than waiting for the thing that registered it in the first place to re-register it with a new address. Hope that helps answer your question at a high level. There could be improvements that could be made to Nomad, though.
