### ISSUE TITLE
The Param “Check Definition” of consul api "/v1/txn" did not changed ，when I use this api

### ISSUE THREAD

**Issue by novice-dgh** [hashicorp/consul#5477]
**[@banks: edited to make JSON formatting more readable]**

**Before I use consul api "v1/txn",my node health like this:**
```json
[
    {
        "Node":"exporter",
        "CheckID":"service:exporter",
        "Name":"codis-exporter web http check",
        "Status":"critical",
        "Notes":"Http based health check",
        "Output":"",
        "ServiceID":"exporter",
        "ServiceName":"exporter",
        "ServiceTags":[
            "codis_exporter"
        ],
        "Definition":{
            "Interval":"6s",
            "Timeout":"6s",
            "DeregisterCriticalServiceAfter":"6s",
            "HTTP":"http://0.0.0.0:9599",
            "TLSSkipVerify":true
        },
        "CreateIndex":11,
        "ModifyIndex":11
    }]
```

**when I use consul api "v1/txn" with param :**
```json
[
	{
		"KV": null,
		"Node": null,
		"Service": null,
		"Check": {
			"Verb": "cas",
			"Check": {
				"Node": "exporter",
				"CheckID": "service:exporter",
				"Name": "codis-exporter web http check",
				"Status": "passing",
				"Notes": "Http based health check",
				"Output": "HTTP GET http://0.0.0.0:9599: 200 OK Output: \u003chtml\u003e\n             \u003chead\u003e\u003ctitle\u003eCodis Exporter\u003c/title\u003e\u003c/head\u003e\n             \u003cbody\u003e\n             \u003ch1\u003eCodis Exporter\u003c/h1\u003e\n             \u003cp\u003e\u003ca href='/metrics'\u003eMetrics\u003c/a\u003e\u003c/p\u003e\n             \u003c/body\u003e\n             \u003c/html\u003e",
				"ServiceID": "exporter",
				"ServiceName": "exporter",
				"ServiceTags": [
					"codis_exporter"
				],
				"Definition": {
					"Interval": "6s",
					"Timeout": "6s",
					"DeregisterCriticalServiceAfter": "6s",
					"HTTP": "http://0.0.0.0:9599",
					"Header": null,
					"Method": "",
					"TLSSkipVerify": true,
					"TCP": ""
				},
				"CreateIndex": 11,
				"ModifyIndex": 11
			}
		}
	}
]
```

**Then , the Node state has changed and the "Interval" and "Timeout" in Check Definition was not changed , the datas what I commit has covered。like this：**
![image](https://user-images.githubusercontent.com/21008755/54181003-13f5a080-44d8-11e9-85e1-162bcd19bd34.png)

@evanphx @topfunky @hornbeck @dylanegan

**Comment by novice-dgh** [comment]
before use like this：
![image](https://user-images.githubusercontent.com/21008755/54174178-249a1c80-44c0-11e9-9698-85a52c6b35da.png)

**Comment by evanphx** [comment]
Do not tag random people.

**Comment by myuen4** [comment]
I think this bug is caused by a change in JSON syntax

https://github.com/hashicorp/consul/blob/v1.4.3/agent/txn_endpoint.go#L242

The txn endpoint linked above expects to use `"IntervalDuration"`, `"TimeoutDuration"` and `"DeregisterCriticalServiceAfterDuration"` instead of the older `"Interval"`, `"Timeout"` and `"DeregisterCriticalServiceAfter"` properties

It looks like the Consul Go API also needs to be updated to support the change in JSON format for the txn endpoint, it only ever sends the versions with out "Duration".

https://github.com/hashicorp/consul/blob/v1.4.3/api/health.go#L54
