### ISSUE TITLE
WebUI check count is inaccurate

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/consul#548]
![screen_shot_2014-12-18_at_11_20_47_am](https://cloud.githubusercontent.com/assets/408570/5491557/105831ce-86a8-11e4-81e2-6a8bddd299a6.png)

In this example, you can see there are three failing checks (for three unique services), but the bar says "2 checks failing"

**Comment by ryanuber** [comment]
@sethvargo have you seen this since you reported it? I haven't noticed it thus far and not sure how to reproduce it.

**Comment by sethvargo** [comment]
Not really. And no one else has reported it. I blame safari or something.
