### ISSUE TITLE
Nessus scan consul v0.8.4 -- “Web Server HTTP Header Memory Exhaustion DoS  for 8500”

### ISSUE THREAD

**Issue by chymy** [hashicorp/consul#5481]
Nessus scan consul v0.8.4, the result is that Web Server HTTP Header Memory Exhaustion DoS  for 8500.
Which version solves this problem please?

**Comment by pierresouchay** [comment]
We did scan our Consul agents recently with Nessus and Consul version. 1.2.3+, 1.3.1+ and 1.4.2+ without finding any vulnerability, so I think those versions are Ok

**Comment by pearkes** [comment]
We didn't resolve this specific vulnerability in Consul to my knowledge, but it may have been by libraries or the language we use. I would try against more modern versions of Consul built with newer versions of Go.
