### ISSUE TITLE
Unable to get Consul metrics in telegraf after upgrading to 1.3.0

### ISSUE THREAD

**Issue by harika224121** [hashicorp/consul#5490]
Hi,

We are using Telegraf as metrics collector. In order to collect Consul metrics we are using StatsD. 
Recently we have upgraded our consul server version from 0.8.4 to 1.3.0 since then we are not able to get the metrics in telegraf can anyone please help us with this issue. 

This is the configuration for statsd plugin in telegraf.conf file:-

[[inputs.statsd]]

   service_address = ":8125"

    templates = [
     "consul.consul.* measurement.field*"
     ]
#

**Comment by danielingd** [comment]
In our solution Consul in all versions wokrs greate. In consul conf:
 ```
},
      "telemetry":{
        "statsd_address":"localhost:514"
  },
```

And full telegraf conf:


>[global_tags]
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 100
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  #precision = "0s"
  #debug = false
  quiet = false
  logfile = "/logs/telegraf.log"
 [[outputs.socket_writer]]
 address = "udp://localhost:515"
 data_format = "graphite"
   [[inputs.statsd]]
    protocol = "udp"
    max_tcp_connections = 250
    tcp_keep_alive = false
    service_address = "localhost:514"
    delete_gauges = true
   delete_counters = true
   delete_sets = true
   delete_timings = true
   percentiles = [90]
   metric_separator = "."
   parse_data_dog_tags = false
   allowed_pending_messages = 10000
   percentile_limit = 1000

**Comment by pearkes** [comment]
Thanks @danielingd! Given we haven't heard anything based on the suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
