### ISSUE TITLE
Agent doesn't rejoin the cluster after network outage

### ISSUE THREAD

**Issue by nosammai** [hashicorp/consul#5494]
### Overview of the Issue

After a network outage where all nodes had issues connecting with each other, we had a few nodes in our cluster that didn't rejoin properly. I had to kill the consul agent process on those nodes. After being restarted, they properly rejoined the cluster.

#### Client info

Running `consul info` on the broken client hangs indefinitely

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = f2b13f30
        version = 1.3.1
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.0.71.68:8300
        server = true
raft:
        applied_index = 87538244
        commit_index = 87538244
        fsm_pending = 0
        last_contact = 31.715476ms
        last_log_index = 87538245
        last_log_term = 371
        last_snapshot_index = 87534647
        last_snapshot_term = 371
        latest_configuration = [{Suffrage:Voter ID:2379d5df-16a0-008d-7ee2-9f928500c1a2 Address:10.0.71.68:8300} {Suffrage:Voter ID:ff7d8f4d-6d2e-ce57-b32b-e6d4c783a039 Address:10.0.71.72:8300} {Suffrage:Voter ID:358fc0ed-fe8d-fa41-2866-29dd9916ee54 Address:10.0.71.80:8300} {Suffrage:Voter ID:ab636eef-359f-be0a-bf39-adee748642f8 Address:10.0.71.97:8300} {Suffrage:Voter ID:9e1e71f2-59f6-498e-ff71-bd34b8e1fb48 Address:10.0.71.60:8300}]
        latest_configuration_index = 82809372
        num_peers = 4
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 371
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 5350
        max_procs = 2
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 101
        failed = 6
        health_score = 0
        intent_queue = 0
        left = 277
        member_time = 266170
        members = 1299
        query_queue = 0
        query_time = 372
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 260
        members = 5
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

VMs running CentOS 7.5, running consul 1.3.1
5 Server nodes and ~1,700 client nodes in the cluster

### Log Fragments
The broken clients were repeating this over and over:
```
2019/03/14 03:29:04 [DEBUG] manager: Rebalanced 5 servers, next active server is dev-consul-server-05 (Addr: tcp/10.0.71.80:8300) (DC: dev)
2019/03/14 03:29:21 [DEBUG] serf: forgoing reconnect for random throttling
2019/03/14 03:29:28 [DEBUG] memberlist: Stream connection from=10.0.81.18:44658
2019/03/14 03:29:32 [DEBUG] memberlist: Initiating push/pull sync with: 10.1.28.72:8301
2019/03/14 03:29:51 [DEBUG] serf: forgoing reconnect for random throttling
2019/03/14 03:30:21 [DEBUG] serf: forgoing reconnect for random throttling
2019/03/14 03:30:51 [DEBUG] serf: forgoing reconnect for random throttling
2019/03/14 03:31:21 [DEBUG] serf: forgoing reconnect for random throttling
2019/03/14 03:31:51 [DEBUG] serf: forgoing reconnect for random throttling
2019/03/14 03:32:01 [DEBUG] manager: Rebalanced 5 servers, next active server is dev-consul-server-01 (Addr: tcp/10.0.71.60:8300) (DC: dev)
2019/03/14 03:32:21 [DEBUG] serf: forgoing reconnect for random throttling
```

The other nodes think that the client is alive:
```
[msedlik@dev-consul-server-01 ~]$ consul members | grep dev-consul-client01
dev-consul-client01                                    10.0.82.176:8301  alive   client  1.3.1  2         dev 
```

I can successfully get newly created KV data from the client, and I can see the request in the trace logs.
```
2019/03/14 21:35:34 [DEBUG] http: Request GET /v1/kv/test (1.81049ms) from=127.0.0.1:57278
```

When I attempt to create a consul session my HTTP request times out, and I never see a log for the request.

**Comment by pearkes** [comment]
There's some strange behavior in here. Full debug logs would help for the affected clients. What is notably strange about it is that...

> I can successfully get newly created KV data from the client, and I can see the request in the trace logs.

If I understand you correctly, this is performing a non-stale RPC request to a real Consul server, which means you shouldn't have reachability problems.

> When I attempt to create a consul session my HTTP request times out, and I never see a log for the request.

You definitely should! Hard to know why you'd see this behavior while not having issues with KV reads.

Either way, I think we'd need more debug logs for the client and potentially one of the servers to dig deeper, as well as potential profiling of client binary. I'm going to pro-actively close this issue but maybe if you do have that data you can open a new issue and reference this one?

Hopefully you understand without detailed data it can be really challenging to narrow down the cause of these types of issues. Thanks for reporting!

**Comment by voiprodrigo** [comment]
This just happened to me. With latest version. 4 days cluster split due to network isolation,  5 node cluster spllit into 3+2. After network recovery, the two isolated nodes had to be restarted.
