### ISSUE TITLE
Advertise Ports

### ISSUE THREAD

**Issue by i0rek** [hashicorp/consul#550]
I want to suggest another configuration option and I am curious what you think. Similiar to `AdvertiseAddr` I want to introduce `AdvertisePorts`. It would be very similiar to the existing `Ports` configuration option. `AdvertisePorts` would allow to specify the ports a consul client is reachable on. 

Use case: I want to run consul client in a container. I have multiple containers per host and multipe hosts. There is a seperate host running consul server. My problem is that I can use `AdvertiseAddr` to communicate the container host ip, but I cannot configure different ports. Without it I can only run one consul per host because the ports are claimed then.

**Comment by i0rek** [comment]
@armon @ryanuber do you have any thoughts about that?

**Comment by ryanuber** [comment]
It makes sense that the node is able to join, since the join operation is being performed from the new node and is an outbound UDP message. Sounds like the problem starts once the new node's address is gossiped, and other nodes in the cluster begin pinging it for health status.

What `advertise` option are you using in the config file? Consul in its current code base should actually error if you specify `ip:port`. The option *should* be `advertise_addr`, and not `advertise` or `AdvertiseAddr`. I believe that Serf allows `ip:port` so this might just be oversight on our part. I'll take a look at this today.

**Comment by armon** [comment]
Sorry about the delay, just getting back from holidays. I agree this makes sense, but I think the only port that you can really advertise is the RPC port. The other ports are not gossiped around and generally do not need to be accessible over the network. Since the RPC port is included in the gossip messages this shouldn't be too hard. Not sure why advertise address is causing the node to suspect itself. Must be a bug.

**Comment by armon** [comment]
@i0rek Take a look at consul/server.go setupSerf(). Basically the "port" value we gossip out is the RPC port, which currently is setup to the real port. I guess there could be a new AdvertisePorts configuration that would allow a different port value to be gossiped out which would be set there.

**Comment by rotatingJazz** [comment]
An `AdvertisePorts` configuration option sounds like the cleanest solution. :+1:

**Comment by armon** [comment]
@i0rek with respect to the self-suspect, a dump of "consul members" and "consul members -detailed" would be useful. Looking through the memberlist code, not sure how this is possible.

**Comment by i0rek** [comment]
@armon this is what I see when I start consul in the container: 

```
hans@ip-10-74-2-162:~$ consul members| grep ip-10-77-16-60-1
ip-10-77-16-60-1       172.17.0.37:8301     alive   client  0.4.1  2
hans@ip-10-74-2-162:~$ consul members -detailed| grep ip-10-77-16-60-1
ip-10-77-16-60-1       172.17.0.37:8301     alive   vsn=2,vsn_min=1,vsn_max=2,build=0.4.1:3b3f0822,role=node,dc=dc1
```

and after a minute or so:

```
hans@ip-10-74-2-162:~$ consul members| grep ip-10-77-16-60-1
ip-10-77-16-60-1       172.17.0.37:8301     failed  client  0.4.1  2
hans@ip-10-74-2-162:~$ consul members -detailed| grep ip-10-77-16-60-1
ip-10-77-16-60-1       172.17.0.37:8301     failed  dc=dc1,vsn=2,vsn_min=1,vsn_max=2,build=0.4.1:3b3f0822,role=node
```

**Comment by i0rek** [comment]
this is what happens on the cluster leader:

```
hans@ip-10-77-1-23:~$ consul monitor --log-level=trace | grep ip-10-77-16-60-1
2015/01/05 22:41:57 [INFO] serf: EventMemberJoin: ip-10-77-16-60-1 172.17.0.37
2015/01/05 22:41:57 [INFO] consul: member 'ip-10-77-16-60-1' joined, marking health alive
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:58 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:41:59 [DEBUG] serf: messageJoinType: ip-10-77-16-60-1
2015/01/05 22:42:23 [INFO] serf: EventMemberFailed: ip-10-77-16-60-1 172.17.0.37
2015/01/05 22:42:23 [INFO] consul: member 'ip-10-77-16-60-1' failed, marking health critical
2015/01/05 22:42:24 [INFO] serf: EventMemberJoin: ip-10-77-16-60-1 172.17.0.37
2015/01/05 22:42:24 [INFO] consul: member 'ip-10-77-16-60-1' joined, marking health alive
2015/01/05 22:43:12 [INFO] serf: EventMemberFailed: ip-10-77-16-60-1 172.17.0.37
2015/01/05 22:43:12 [INFO] consul: member 'ip-10-77-16-60-1' failed, marking health critical
2015/01/05 22:43:13 [INFO] serf: EventMemberJoin: ip-10-77-16-60-1 172.17.0.37
2015/01/05 22:43:13 [INFO] consul: member 'ip-10-77-16-60-1' joined, marking health alive
2015/01/05 22:43:32 [INFO] serf: EventMemberFailed: ip-10-77-16-60-1 172.17.0.37
2015/01/05 22:43:32 [INFO] consul: member 'ip-10-77-16-60-1' failed, marking health critical
2015/01/05 22:45:10 [INFO] serf: EventMemberJoin: ip-10-77-16-60-1 172.17.0.37
2015/01/05 22:45:10 [INFO] consul: member 'ip-10-77-16-60-1' joined, marking health alive
2015/01/05 22:45:33 [INFO] serf: EventMemberFailed: ip-10-77-16-60-1 172.17.0.37
2015/01/05 22:45:33 [INFO] consul: member 'ip-10-77-16-60-1' failed, marking health critical
```

**Comment by i0rek** [comment]
@ryanuber you were right and I was wrong. I got the configuration option wrong. Consul doesn't start anymore now that I am using the right one.

```
root@5c335b6c39f9:~# start-consul
==> Starting Consul agent...
==> Error starting agent: Failed to parse advertise address: 10.77.16.60:8304
root@5c335b6c39f9:~# cat /opt/consul.d/container.json
{
  "advertise_addr": "10.77.16.60:8304",
  "node_name": "ip-10-77-16-60-1"
}
```

**Comment by i0rek** [comment]
I would vote for accepting the port in `advertise_addr` like serf does.

**Comment by ryanuber** [comment]
@i0rek I pushed #576 yesterday which should help us avoid this confusion in the future. As for `advertise_addr`, I don't think we can just accept the port number on the end of the address in `ip:port` format, since we use it to set up two separate gossip agents and the RPC advertise address. I think as @armon said the way to go would be to have some new config option, maybe like:

```
"advertise_addrs": {
    "serf_lan": "1.2.3.4:8301",
    "serf_wan": "1.2.3.4:8302",
    "rpc": "1.2.3.4:8400"
}
```

**Comment by ryanuber** [comment]
Alternatively, you might want to try tweaking the `ports` config, specifically `serf_lan` and/or `serf_wan`. That combined with the `advertise_addr` might get you past this.

**Comment by rotatingJazz** [comment]
@ryanuber I've tried that, it only works when all the nodes have the same ports.

**Comment by i0rek** [comment]
@ryanuber thanks for #576!
Re `ports`: thats not enough as @rotatingJazz said. 
Re `advertise_addrs`: I will give it a shot and let you know once I have something to look at.
