### ISSUE TITLE
consul restart docker No cluster leader

### ISSUE THREAD

**Issue by An0nymous0** [hashicorp/consul#5500]
1.

```
version: '3.6'

x-consul: &consul
    image: consul:1.4.3
    volumes:
      - consul:/consul

volumes:
  consul:

networks:
  springcloud-overlay:
    external: true

services:
  client:
    <<: *consul
    command: "agent -retry-join server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    depends_on:
      - server-bootstrap
    deploy:
      replicas: 2

  server:
    <<: *consul
    ports:
      - "8500:8500"
    depends_on:
      - server-bootstrap
    environment:
        - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true,"leave_on_terminate":false}'
    command: "agent -server -retry-join server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}' -ui"
    deploy:
      replicas: 2
      placement:
        constraints: [node.hostname == node-2]

  server-bootstrap:
    image: consul:1.4.3
    environment:
        - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true,"leave_on_terminate":false}'
    command: "agent -server -bootstrap-expect 3 -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      placement:
        constraints: [node.hostname == node-5]
```

2. ssh node-5

3.  systemctl restart docker(master node-id and IP change)

```
bootstrap_expect > 0: expecting 3 servers
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v1.4.3'
           Node ID: '2b9d4092-ab1b-ad74-3d59-0925537dc1bc'
         Node name: '744fdbc3bd99'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 10.0.2.70 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2019/03/16 02:47:03 [INFO] raft: Initial configuration (index=0): []
    2019/03/16 02:47:03 [INFO] raft: Node at 10.0.2.70:8300 [Follower] entering Follower state (Leader: "")
    2019/03/16 02:47:03 [INFO] serf: EventMemberJoin: 744fdbc3bd99.dc1 10.0.2.70
    2019/03/16 02:47:03 [INFO] serf: EventMemberJoin: 744fdbc3bd99 10.0.2.70
    2019/03/16 02:47:03 [INFO] consul: Handled member-join event for server "744fdbc3bd99.dc1" in area "wan"
    2019/03/16 02:47:03 [INFO] consul: Adding LAN server 744fdbc3bd99 (Addr: tcp/10.0.2.70:8300) (DC: dc1)
    2019/03/16 02:47:03 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)
    2019/03/16 02:47:03 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
    2019/03/16 02:47:03 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
    2019/03/16 02:47:03 [INFO] agent: started state syncer
    2019/03/16 02:47:10 [WARN] raft: no known peers, aborting election
    2019/03/16 02:47:10 [ERR] agent: failed to sync remote state: No cluster leader
    2019/03/16 02:47:35 [ERR] agent: Coordinate update error: No cluster leader
    2019/03/16 02:47:35 [ERR] agent: failed to sync remote state: No cluster leader
    2019/03/16 02:48:05 [ERR] agent: failed to sync remote state: No cluster leader
    2019/03/16 02:48:12 [ERR] agent: Coordinate update error: No cluster leader
    2019/03/16 02:48:36 [ERR] agent: failed to sync remote state: No cluster leader
    2019/03/16 02:48:45 [ERR] agent: Coordinate update error: No cluster leader
    2019/03/16 02:49:01 [ERR] agent: failed to sync remote state: No cluster leader
    2019/03/16 02:49:12 [ERR] agent: Coordinate update error: No cluster leader
    2019/03/16 02:49:25 [ERR] agent: failed to sync remote state: No cluster leader
    2019/03/16 02:49:44 [ERR] agent: Coordinate update error: No cluster leader
    2019/03/16 02:50:02 [ERR] agent: failed to sync remote state: No cluster leader
    2019/03/16 02:50:18 [ERR] agent: Coordinate update error: No cluster leader
```

**Comment by kasuri** [comment]
I have exactly the same issue in Azure with a VMSS.  The specific error that I get is: Failed to join 10.2.138.17: dial tcp 10.2.138.17**:8301: connect: no route to host**

If I check Consul Info, it shows each server has one member (itself) and port 8301 is live:

2d5d9439-947c-4ce6-aa53-9ff1f4e37fda  **10.2.138.16:8301  alive**   server  1.4.2  2 

If I use NMAP, I do not see port 8301 listed:

**sudo nmap -sS localhost**
Starting Nmap 6.40 ( http://nmap.org ) at 2019-03-22 17:59 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000010s latency).
Other addresses for localhost (not scanned): 127.0.0.1
Not shown: 995 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
53/tcp   open  domain
111/tcp  open  rpcbind
8500/tcp open  fmtp
8600/tcp open  asterix

Here is log output.  
Mar 22 17:01:22 consul000005 consul[5250]: ==> Starting Consul agent...
Mar 22 17:01:22 consul000005 consul[5250]: ==> Consul agent running!
Mar 22 17:01:22 consul000005 consul[5250]: Version: 'v1.4.2'
Mar 22 17:01:22 consul000005 consul[5250]: Node ID: 'dd50f0b2-60c5-a111-c979-c94199c25a76'
Mar 22 17:01:22 consul000005 consul[5250]: Node name: '220de264-c32b-48c7-9270-7f079cdfe25f'
Mar 22 17:01:22 consul000005 consul[5250]: Datacenter: 'centralus' (Segment: '<all>')
Mar 22 17:01:22 consul000005 consul[5250]: Server: true (Bootstrap: false)
Mar 22 17:01:22 consul000005 consul[5250]: Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
Mar 22 17:01:22 consul000005 consul[5250]: Cluster Addr: 10.2.138.18 (LAN: 8301, WAN: 8302)
Mar 22 17:01:22 consul000005 consul[5250]: Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false
Mar 22 17:01:22 consul000005 consul[5250]: ==> Log data will now stream in as it occurs:
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] raft: Initial configuration (index=0): []
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] raft: Node at 10.2.138.18:8300 [Follower] entering Follower state (Leader: "")
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] serf: EventMemberJoin: 220de264-c32b-48c7-9270-7f079cdfe25f.centralus 10.2.138.18
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] serf: EventMemberJoin: 220de264-c32b-48c7-9270-7f079cdfe25f 10.2.138.18
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] consul: Adding LAN server 220de264-c32b-48c7-9270-7f079cdfe25f (Addr: tcp/10.2.138.18:8300) (DC: centralus)
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] consul: Handled member-join event for server "220de264-c32b-48c7-9270-7f079cdfe25f.centralus" in area "wan"
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] agent: started state syncer
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] agent: Retry join LAN is supported for: aliyun aws azure digitalocean gce k8s os packet scaleway softlayer trit
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] agent: Joining LAN cluster...
Mar 22 17:01:22 consul000005 consul[5250]: 2019/03/22 17:01:22 [INFO] agent: (LAN) joining: [10.2.138.16 10.2.138.17]

Please help!

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the [Consul mailing list](https://www.consul.io/community.html)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
