### ISSUE TITLE
sequential KVs

### ISSUE THREAD

**Issue by tcolgate** [hashicorp/consul#553]
It would be nice if consul supported zk/etcd style sequential keys. This appears to be the only feature from etcd to make consul KVs usable as a more general consensus service, making it useful for building more general distributed mechanism on top of (e.g. two phase commit and read/write locks).

**Comment by armon** [comment]
This can be simulated pretty easily using just CAS which the API already supports. I'm not sure sequential keys are useful enough to warrant making the API more complex.

**Comment by derekelkins** [comment]
What would be really nice, but I don't know if there is any reasonable way of doing this without embedding an interpreter into Consul (I haven't thought about it that much though), would be to atomically perform *arbitrary* (deterministic) functions of the value in updates.  The obvious example is a counter: it would be nice not to do two round trips one with what can be a stale read and a (consistent) write, possibly needing to retry again when we could do one consistent write and never need to retry (and dramatically simplify the API usage in this case).  A possible middle-ground is to allow *compile-time* plugins to be added that would add additional endpoints to the kv path or have just a dedicated perform_op endpoint.  In database terms this would be akin to "support stored procedures".

It's probably desirable to not make this *too* easy, as bad things will happen if the operation takes a long time.

**Comment by armon** [comment]
I think this is an extremely dangerous route to go down, and not something we plan to support. Unless there is an exceptionally good reason, this starts to go down the RDMBS triggers and PL/SQL path which is something I'd rather avoid.

**Comment by tcolgate** [comment]
After checking out the go api client, it already has a nice lock and
semaphore api.
I do think a 'sequentail' option, maybe just using the raft index, would be
handy (you can build up nice queues of tasks, avoiding thundering hurds),
but I can definitely do without.
  The client lib is fantastic, thanks so much for all your work on consul!

**Comment by derekelkins** [comment]
@armon I made a separate issue as it is confusing to discuss this here. #667

**Comment by ryanuber** [comment]
As of now we still haven't found a compelling reason to add support for this. I'm going to close this out for now.
