### ISSUE TITLE
consul disk io average utiliztion exceed 50%?

### ISSUE THREAD

**Issue by chymy** [hashicorp/consul#5536]
Hi.
we are using consul 0.8.4 and on random one server (we have 3 servers), we find  disk average utiliztion exceed 50% once a day. Is there any way to deal with it? And are there any tasks that consume disk io?

**Comment by pearkes** [comment]
Depending on the write load to Consul, disk can definitely bottleneck performance of Consul servers. See the [server performance](https://www.consul.io/docs/guides/performance.html) section of the documentation for more information.
