### ISSUE TITLE
HealthCheck: "grpc  connect: no route to host"  consul is always try reconnecting...

### ISSUE THREAD

**Issue by GStones** [hashicorp/consul#5555]
2019/03/26 17:07:37 [INFO] ccResolverWrapper: sending new addresses to cc: [{10.56.3.56:43961 0  <nil>}]
    2019/03/26 17:07:37 [INFO] ccResolverWrapper: sending new addresses to cc: [{10.56.3.56:46436 0  <nil>}]
    2019/03/26 17:07:40 [WARN] grpc: addrConn.createTransport failed to connect to {10.56.3.56:43961 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.56.3.56:43961: connect: no route to host". Reconnecting...
    2019/03/26 17:07:40 [WARN] grpc: addrConn.createTransport failed to connect to {10.56.3.56:46436 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.56.3.56:46436: connect: no route to host". Reconnecting...
    2019/03/26 17:07:50 [INFO] ccResolverWrapper: sending new addresses to cc: [{10.56.3.56:43961 0  <nil>}]
    2019/03/26 17:07:50 [INFO] ccResolverWrapper: sending new addresses to cc: [{10.56.3.56:46436 0  <nil>}]
    2019/03/26 17:07:53 [WARN] grpc: addrConn.createTransport failed to connect to {10.56.3.56:43961 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.56.3.56:43961: connect: no route to host". Reconnecting...
    2019/03/26 17:07:53 [WARN] grpc: addrConn.createTransport failed to connect to {10.56.3.56:46436 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.56.3.56:46436: connect: no route to host". Reconnecting...
    2019/03/26 17:08:03 [INFO] ccResolverWrapper: sending new addresses to cc: [{10.56.3.56:43961 0  <nil>}]
    2019/03/26 17:08:03 [INFO] ccResolverWrapper: sending new addresses to cc: [{10.56.3.56:46436 0  <nil>}]
    2019/03/26 17:08:06 [WARN] grpc: addrConn.createTransport failed to connect to {10.56.3.56:43961 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.56.3.56:43961: connect: no route to host". Reconnecting...
    2019/03/26 17:08:06 [WARN] grpc: addrConn.createTransport failed to connect to {10.56.3.56:46436 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.56.3.56:46436: connect: no route to host". Reconnecting...
    2019/03/26 17:08:16 [INFO] ccResolverWrapper: sending new addresses to cc: [{10.56.3.56:43961 0  <nil>}]
    2019/03/26 17:08:16 [INFO] ccResolverWrapper: sending new addresses to cc: [{10.56.3.56:46436 0  <nil>}]
    2019/03/26 17:08:19 [WARN] grpc: addrConn.createTransport failed to connect to {10.56.3.56:43961 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.56.3.56:43961: connect: no route to host". Reconnecting...
    2019/03/26 17:08:19 [WARN] grpc: addrConn.createTransport failed to connect to {10.56.3.56:46436 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.56.3.56:46436: connect: no route to host". Reconnecting...

**Comment by GStones** [comment]
it can not remove this service

**Comment by pearkes** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here for initial debugging.

Maybe this is better suited for the [Consul mailing list](https://www.consul.io/community.html) until we can determine a specific problem.

If you feel this is a bug and can provide additional information, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md).
