### ISSUE TITLE
Consul log file rotation => Delete log archives

### ISSUE THREAD

**Issue by javicrespo** [hashicorp/consul#5556]
#### Feature Description

The logfile configuration allows for log rotation (by size/date), but there is no way to specify how many archives to be kept (the same way logrotate allows to specify that with the _rotate_ setting).
So in the scope of this feature, a new config setting _-log-rotate-max-archives_ would be added. At rotation time, old log files would be deleted.

#### Use Case(s)

Windows machines where there is no logrotate service

I'd be happy to submit a PR if you guys deem this feature useful.

**Comment by pearkes** [comment]
Sure, this seems sensible as an option for log rotation!

**Comment by javicrespo** [comment]
Thx, I've implemented it here => #5577

**Comment by javicrespo** [comment]
@pearkes, I've recreated a PR for this #5831 (I've integrated the log level recent changes).
Could you take a look at it please?

**Comment by freddygv** [comment]
Fixed by: #5831
