### ISSUE TITLE
Is it possible to disable IPv6 or configure it specifically?

### ISSUE THREAD

**Issue by joewilliams** [hashicorp/consul#5562]
Is it possible configure `consul agent` (running in client mode) to not listen or do anything for IPv6 interfaces? I [thought](https://github.com/hashicorp/consul/blob/v0.7.5-rel/website/source/docs/agent/options.html.markdown#_bind) by specifying the address specifically in the config it would avoid this but it doesn't seem like it. Looking at [this](https://github.com/hashicorp/consul/blob/v0.7.5-rel/consul/util.go) it's not obvious to me what might be happening. Any advice?

```
# cat /etc/consul/config.json | jq .bind_addr
"172.16.2.3"
```
```
# netstat -peanut | grep consul
tcp        0      0 172.16.2.3:8301       0.0.0.0:*               LISTEN      998        3225767786  31017/consul
tcp6       0      0 :::8500                 :::*                    LISTEN      998        3225767789  31017/consul
tcp6       0      0 :::8600                 :::*                    LISTEN      998        3225754173  31017/consul
tcp6       0      0 :::8400                 :::*                    LISTEN      998        3225767788  31017/consul
udp        0      0 172.16.2.3:8301       0.0.0.0:*                           998        3225767787  31017/consul
udp6       0      0 :::8600
```

We are running a very old version of consul for reasons :tm:
```
# consul version
Consul v0.7.5
```

**Comment by mkeeler** [comment]
@joewilliams The bind addr is used just for internal cluster communications. Other client facing aspects are using other addresses:

[::]:8500 - Is the HTTP server
[::]:8600 - DNS server
[::]:8400 - RPC server (this is usually 8300 but there is some terraform code out there that sets this to 8400 so I assume thats what it is for you)

Each address can be set individually using the `addresses` configuration stanza: https://www.consul.io/docs/agent/options.html#addresses

Or you can set the `client_addr` configuration to default all of these: https://www.consul.io/docs/agent/options.html#client_addr

**Comment by joewilliams** [comment]
FWIW *seems* like golang will listen on IPv6 and IPv4 by default. https://golang.org/src/net/dial.go?s=20989:21043

**Comment by joewilliams** [comment]
Thanks @mkeeler!

**Comment by mkeeler** [comment]
You are correct. We actually bind to 0.0.0.0 by default but golang will use a dual stack socket and listen on [::] instead.

**Comment by vijaypatnana** [comment]
Is there a way to disable the ipv6 completely? My consul version - v1.8.1.

**Comment by tfrijsewijk** [comment]
I'm deploying an application using Nomad. I register the application using the `service` stanza. I'm using fabio which in turn forwards my traffic for `my-url.localhost` to `[::]:MY_PORT`. For demo purposes I'm running everything on the same machine.

Is it possible that it forwards to `0.0.0.0` or even `localhost`/`127.0.0.1` ? The application that I'm deploying does not support IPv6.

I've looked into advertise addresses and binding addresses but whatever combination I try, it keeps using `[::]`.

Any suggestions?
