### ISSUE TITLE
The package is vendoring it self

### ISSUE THREAD

**Issue by h8liu** [hashicorp/consul#5570]
#### Overview of the Issue

It has itself in the vendor directory:
https://github.com/hashicorp/consul/tree/master/vendor/github.com/hashicorp/consul/internal

#### Reproduction Steps

Visit here:
https://github.com/hashicorp/consul/tree/28c8484/vendor/github.com/hashicorp/consul/internal

It is really weird.. wonder how the vendor is generated.

**Comment by h8liu** [comment]
btw, it won't build with the world without go modules, due to the vendored `internal`.

**Comment by pearkes** [comment]
This should be fixed by https://github.com/hashicorp/consul/pull/5568. Let us know if not.
