### ISSUE TITLE
Manual Service Registering Address GetInterfaceIP

### ISSUE THREAD

**Issue by marcotuna** [hashicorp/consul#5580]
#### Feature Description

https://www.consul.io/docs/commands/services/register.html#address

When manually registering a service if we want a different ip address assigned to it (different from the consul agent) the flag "address" must be added, however it only allows to manually specify the ip address. It should be possible to add inside the "address" shortcuts like `GetInterfaceIP`

#### Use Case(s)

/etc/consul.d/service-name.json
```
{
   "service":{
      "address": "192.168.10.12",
      "name":"service-name",
      "port":8080
   }
}
```
It should be possible to replace the address with GetInterfaceIP from [go-sockaddr](https://github.com/hashicorp/go-sockaddr) which is already implemented in consul.

/etc/consul.d/service-name.json
```
{
   "service":{
      "address": "{{ GetInterfaceIP `eth0` }}",
      "name":"service-name",
      "port":8080
   }
}
```

**Comment by pearkes** [comment]
Though I see the reasoning for operators who don't know the IP ahead of laying down service configuration files, realistically I don't see us implementing this soon. I think there are some questionable lifecycle issues if we start interpolating dynamic values into these files, currently they are entirely static.

In practice people typically use tools like `jq` and similar to template these things out when triggered from some dynamic operation. I hope that helps and sorry we don't have a better answer for you on this. 

You may also want to take a look at [`consul services register`](https://www.consul.io/docs/commands/services/register.html) which we hope to continue improving parameters for.
