### ISSUE TITLE
rpc to watch

### ISSUE THREAD

**Issue by pmenglund** [hashicorp/consul#559]
I'd like to see support for using rpc to add watches and get notified when a watch fires.

**Comment by armon** [comment]
Unfortunately, this would require us to duplicate a significant amount of logic to make this work over RPC as well as HTTP. IMO this is unnecessary complexity, and the HTTP interface should be preferred. I don't see how RPC avoids the firewall issue?

**Comment by pmenglund** [comment]
If it is done over RPC, I only need to open an unidirectional port in the FW, while the HTTP interface require another port to be open which allows traffic back to the RPC server. This is generally much harder to get through a security review.

**Comment by armon** [comment]
Typically you only connect to the RPC (CLI) and the HTTP ports over loopback, so a firewall shouldn't affect things. The RPC port on the servers (8300) is different, and does need to allow for inbounds.

**Comment by pmenglund** [comment]
I am connecting to the rpc port bound to the main IP on one of the consul
servers, from a server residing in a different security zone (higher
classification, different network, very restricted FW between).

The issue is opening the FW for HTTP traffic initiated from the lower
security zone to the higher.

Being able to setup the watch to publish the info over the rpc channel
would greatly simplify that.

**Comment by armon** [comment]
Unfortunately it's just not something we can support in the short term. It requires a substantial amount of work to work around a policy and not a technical issue.

**Comment by pmenglund** [comment]
But in the long term? :)

**Comment by armon** [comment]
Potentially, but not something I'd commit to.
