### ISSUE TITLE
Encryption is configured but remote state is not encrypted

### ISSUE THREAD

**Issue by viveksair** [hashicorp/consul#5590]
```
    2019/04/01 17:57:00 [ERR] memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=172.30.112.93:32860
    2019/04/01 17:57:15 [ERR] memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=172.30.112.93:33390
    2019/04/01 17:57:30 [ERR] memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=172.30.112.93:34052
    2019/04/01 17:57:45 [ERR] memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=172.30.112.93:34716
    2019/04/01 17:58:00 [ERR] memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=172.30.112.93:35222
    2019/04/01 17:58:15 [ERR] memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=172.30.112.93:36066
    2019/04/01 17:58:30 [ERR] memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=172.30.112.93:36766
```

I am getting above errors from consul cluster(3 node cluster)

**Background**
we use consul for vault storage backed hosted on Kubernetes environment

**Version** : 1.2.2

**Comment by pearkes** [comment]
It looks like the agent at 172.30.112.93 is not configured for gossip encryption. This is the agent you're viewing logs of rejecting that message due to it seeing an unencrypted message with a setting to verify incoming messages.

Here's the relevant source of the error in memberlist:

https://github.com/hashicorp/memberlist/blob/2e1a43a4eac88545b8c77a5f6916e496e5525c89/net.go#L946-L964

I'd double-check your encryption configuration on both sides!

**Comment by tannh** [comment]
How fixed many thanks. The documentation not clear.

**Comment by abhsinh2** [comment]
I am seeing the same error:
memberlist: failed to receive: Encryption is configured but remote state is not encrypted from

Why is this error thrown and how can I resolve?

**Comment by xiangjiansheng** [comment]
I am seeing the error:
    2019/12/19 16:12:35 [ERR] memberlist: Push/Pull with n2.dc1 failed: Encrypti
on is configured but remote state is not encrypted
Why is this error thrown and how can I resolve?
