### ISSUE TITLE
Inconsistent data in cluster

### ISSUE THREAD

**Issue by telmich** [hashicorp/consul#560]
When connecting two datacenters, the information about the 2nd datacenter is not available on all nodes:

root@consul01:~# consul members -wan
Node                         Address              Status  Type    Build  Protocol
consul01.ungleich-init7      77.109.150.152:8302  alive   server  0.4.1  2
backup-hetzner.hetzner-rz16  136.243.3.230:8302   alive   server  0.4.1  2
root@consul01:~# consul members 
Node      Address              Status  Type    Build  Protocol
consul01  77.109.150.152:8301  alive   server  0.4.1  2
consul03  77.109.150.154:8301  alive   server  0.4.1  2
consul02  77.109.150.153:8301  alive   server  0.4.1  2

root@consul03:~# curl http://consul01.ungleich.ch:8500/v1/catalog/datacenters; echo ""
["hetzner-rz16","ungleich-init7"]
root@consul03:~# curl http://consul02.ungleich.ch:8500/v1/catalog/datacenters; echo ""
["ungleich-init7"]
root@consul03:~# curl http://consul03.ungleich.ch:8500/v1/catalog/datacenters; echo ""
["ungleich-init7"]
root@consul03:~#

**Comment by armon** [comment]
@telmich Did all the servers join the WAN gossip ring? It looks like only consul01 joined. The WAN join is done separately from the normal cluster join.

**Comment by telmich** [comment]
@armon I have just joined -wan one server of the ungleich-init7 dc from hetzner-rz16.

I assumed (seems incorrectly) that all servers are informed about the other datacenter via gossip in the local datacenter?

If it is necessary to join -wan to every other server in the datacenter, I would have to repeat the step for every server in the other datacenter every time the node reboots?

I.e. having 3 servers in ungleich-init7, 3 servers in hetzner-rz16 and 3 servers in our upcoming dc, every server would have to join 6 other servers?

I think what makes me mostly puzzled is that I assumed that the information (view) of the cluster should be eventually consistent -  did I assume wrong here?

**Comment by ryanuber** [comment]
@telmich currently consul utilizes two separate gossip pools; a LAN gossip ring and a WAN gossip ring. Each server node must join at least one other server node in the WAN gossip ring in order to see the remote datacenters. It is not necessary to join every node in the WAN pool.

Also, you should not need to perform the join manually on each reboot. The peer set should be persisted and re-joined on subsequent start-ups.

Hope this helps!

**Comment by telmich** [comment]
I understand - I will close this issue here & move on to google groups for some questions about the design of consul - thanks for clarification!
