### ISSUE TITLE
Return explanatory header when HTTP 404 on /v1/kv/

### ISSUE THREAD

**Issue by kanzure** [hashicorp/consul#561]
Here is an idea.

From [docs](http://www.consul.io/intro/getting-started/kv.html):

> Since there are no keys, we get a 404 response back. Now, we can put a few example keys

How about returning an HTTP header that explains this is an empty set, and that the key value store is probably functioning? Something like `X-CONSUL-EMPTY`.

**Comment by armon** [comment]
I agree this is a legacy wart. It can't be changed safely now, but for v2 hopefully we can button down the consistency issues in the API!

**Comment by sean-** [comment]
If this does get revisited, my $0.02:

If the key was found but there is an empty set, a "204 No Content" response seems like the best result, whereas a 404 implies the key was not found.

**Comment by armon** [comment]
Yeah 204 probably makes the most sense, but I also like the idea of an empty list.

**Comment by ryanuber** [comment]
My thinking was that 204 is more to indicate success and nothing else. The empty list would prevent the client from having to handle it specially.

**Comment by armon** [comment]
I think we can return empty list + 204, since any 2XX is a success.

**Comment by armon** [comment]
I guess that answers that haha.

**Comment by slackpad** [comment]
Since we don't want to break the /v1 API and we'd do a deeper redesign for a /v2 API, I don't think this is worth keeping open at this time.
