### ISSUE TITLE
Ability to define more than one health check per service

### ISSUE THREAD

**Issue by petemounce** [hashicorp/consul#562]
I'd love to be able to do this. We run in AWS, with ELBs, and so each of our components will have at least one endpoint for the ELB-based health-check. This is a "I'm present" check.

Some of our more sophisticated components are starting to have more health checks, so we can assert that things are healthy in production. For example, pinging http dependencies, select'ing from a database, etc. It would be great if consul can ping these individually, so we can see this level of granularity via it.

Some of these checks indicate "cannot function"; some of them indicate "can function but degraded" - I think consul's 0=good, 1=warning, 2=critical has us covered here (thanks!).

(I've only tried against 0.4.1 - #367 alludes to something like this being possible already...?)

**Comment by armon** [comment]
I think we have an open ticket for this already! This is a goal for 0.5. The core supports it already (internal catalog / APIs), but we need to expose it out.

**Comment by petemounce** [comment]
@armon that's great; looking forward to it landing!

**Comment by ryanuber** [comment]
@petemounce there is a PR open for this on #591, and an existing issue on #230. Closing this out to track in those issues, thanks!

**Comment by petemounce** [comment]
Brilliant!

--
