### ISSUE TITLE
When running Consul as Windows Service it is not working

### ISSUE THREAD

**Issue by kvskranthikumar** [hashicorp/consul#5623]
When running Consul as Windows Service using "sc" it is not working. It is working perfectly with NSSM.

Consul Version used 1.4.3 version

Command used to run Consul as Windows Service -
sc create "Consul" binPath= "C:\Program Files (x86)\Consul\consul.exe agent -config-file ServerSettings.json" start= auto

Output -
[SC] CreateService SUCCESS

ServerSettings.json -

{
	"datacenter": "CatManConfigMgnt",
	"client_addr": "127.0.0.1",
	"bind_addr": "127.0.0.1",
	"ui": true,
	"data_dir": "C:/Program Files (x86)/Consul/Data",
	"log_level": "INFO",
	"node_name": "CatManConfigService",
	"bootstrap": true,
	"server": true,
	"watches": [{
			"type": "checks",
			"handler": "/usr/bin/health-check-handler.sh"
		}
	],
	"telemetry": {
		"statsite_address": "127.0.0.1:2180"
	},
	"http_config": {
		"response_headers": {
			"Access-Control-Allow-Origin": "*"
		}
	}
}

OS Details -
Windows 10 Enterprise 
Version - 1709
OS  Build - 16299.967

When starting the Service I get below issue -
![Starting Service Error](https://user-images.githubusercontent.com/12032164/55811444-c4ba8400-5b06-11e9-901c-5296e49591c6.JPG)

Event Viewer under System -
The Consul service terminated unexpectedly.  It has done this 2 time(s).

**Comment by ChipV223** [comment]
Hi @kvskranthikumar!

As a test, I tried creating a new Windows service using the v1.4.4 binary in Windows 10 and I was able to start the service with any of the issues that you described

```
chipv@CV-HASHI C:\Users\chipv
$ sc create "Consul_Service" binPath="C:\Consul_Service\consul.exe agent -config-dir=C:\Consul_Service\consul_configA.json" start=auto
[SC] CreateService SUCCESS

chipv@CV-HASHI C:\Users\chipv
$ sc query Consul_Service

SERVICE_NAME: Consul_Service
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

chipv@CV-HASHI C:\Users\chipv
$ sc start Consul_Service

SERVICE_NAME: Consul_Service
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 12596
        FLAGS              :

chipv@CV-HASHI C:\Users\chipv
$ sc query Consul_Service

SERVICE_NAME: Consul_Service
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

chipv@CV-HASHI C:\Users\chipv
$ sc query Consul_Service

SERVICE_NAME: Consul_Service
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

Config file used in test:

```
{
    "bootstrap_expect": 1,
    "bind_addr": "0.0.0.0",
	"advertise_addr": "192.168.1.178",
	"data_dir": "/tmp/consul_test",
    "node_name": "ServerA",
    "server": true,
    "log_level": "INFO",
    "client_addr": "0.0.0.0"
}
```

OS Details:

```
Windows 10
Version: 1803
OS Build: 17134.648
```

Out of curiosity, does your issue occur everytime you trying creating a Windows service for Consul?

**Comment by kvskranthikumar** [comment]
Hi Vaughn,

I was able to figure out this issue-
1. User permission issue with "C:\Program Files (x86)", when placed Consul under this directory.
2. Changed "-config-file" parameter with "-config-dir"

Thank you for the sample, it helped!

**Comment by xBentu** [comment]
I am having the same issue.  The Consul service stops working right after I start it. 

![image](https://user-images.githubusercontent.com/56086690/67125625-43356400-f1c3-11e9-8b8e-4f4eca243a2e.png)

Windows 10 Enterprise
![image](https://user-images.githubusercontent.com/56086690/67125779-868fd280-f1c3-11e9-8c65-2783eccb3125.png)
