### ISSUE TITLE
list acl tokens from Consul using curl with external hostname (consul server) doesnot work.

### ISSUE THREAD

**Issue by vijayalp** [hashicorp/consul#5624]
Quorum of Consul agents server and client is installed.
$ consul --version
Consul v0.7.2
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

We get to see connection refused error when from Consul client machine  curl command run to get list of available acltokens  using external hostname/ipaddress of consul server in URL.
That is, lets say machine m1=invpbg071 have consul-server, m2=invpbg078 have consul client installed
To list all the acl tokens present in the consul quorum run below curl command  from m2 with url having external hostname of consul server.
[consul_configfiles.zip](https://github.com/hashicorp/consul/files/3060112/consul_configfiles.zip)

[invpbg078] $ curl  http://invpbg071:31500/v1/acl/list?token=test-token
curl: (7) Failed connect to invpbg071:31500; Connection refused

Works when url have localhost or 127.0.0.1 .

curl http://localhost:16500/v1/acl/list?token=test-token
curl http://127.0.0.1:16500/v1/acl/list?token=test-token
[{"ID":"4ca37d16-61b4-0b2c-b5bc-57dc377af6a2","Name":"read-token","Type":"client","Rules":"{\"key\":{\"TestConfiguration/ACD_PBG/\":{\"policy\":\"read\"}}}","CreateIndex":51449,"ModifyIndex":51449},{"ID":"56d4814e-cd75-d843-3939-00aeac0442ae","Name":"read-token","Type":"client","Rules":"{\"key\":{\"TestConfiguration/ACD_PBG/\":{\"policy\":\"read\"}}}","CreateIndex":51448,"ModifyIndex":51448},{"ID":"anonymous","Name":"Anonymous Token","Type":"client","Rules":"","CreateIndex":4,"ModifyIndex":4},{"ID":"test-token","Name":"Master Token","Type":"management","Rules":"","CreateIndex":5,"ModifyIndex":5}]

**Comment by pearkes** [comment]
> curl: (7) Failed connect to invpbg071:31500; Connection refused

This would lead me to believe that no APIs work, not just the ACL list API. I'd double-check that your configuration has Consul listening on the right interfaces.

Would also highly recommend using a newer version of Consul, 0.7.2 is quite old! Hope that helps.

**Comment by vijayalp** [comment]
Using consul 1.4.2, still we get to see same issue
API command "consul acl token list -http-addr=**invpbg071**:16500 -token=test-token"  results to 
connection refused.

However,
consul acl token list -http-addr=**127.0.0.1**:16500 -token=test-token
lists all the tokens in consul.

Are there any more configuration to made at machine/network level to work with hostname or external ip address?
