### ISSUE TITLE
Snapshot

### ISSUE THREAD

**Issue by 475cheng** [hashicorp/consul#5629]
1. How to set a timed snapshot

2. The specified profile snapshot was not generated

3. If it is generated, where will it be generated?

Start command: consul agent -dev -config-file=/data/consul/test.json -data-dir /tmp/consul-node=s1 -bind=172.20.4.98 -ui -client 0.0.0.0

Configuration file: test. json
{
   "snapshot_agent": {
      "http_addr": "172.20.4.98:8500",
      "token": "",
      "datacenter": "",
      "ca_file": "",
      "ca_path": "",
      "cert_file": "",
      "key_file": "",
      "tls_server_name": "",
      "log": {
        "level": "INFO",
        "enable_syslog": false,
        "syslog_facility": "LOCAL0"
      },
      "snapshot": {
        "interval": "1m",
        "retain": 30,
        "stale": false,
        "service": "consul-snapshot",
        "deregister_after": "72h",
        "lock_key": "consul-snapshot/lock",
        "max_failures": 3
      },
      "local_storage": {
        "path": "."
      },
      "aws_storage": {
        "access_key_id": "",
        "secret_access_key": "",
        "s3_region": "",
        "s3_bucket": "",
        "s3_key_prefix": "consul-snapshot",
        "s3_server_side_encryption":false,
        "s3_static_snapshot_name":""
      }
    }
}

**Comment by pearkes** [comment]
Hi @475cheng, the snapshot agent is a [Consul Enterprise feature](https://www.consul.io/docs/commands/snapshot/agent.html). If you're running Consul Enterprise, you're entitled to support (https://www.hashicorp.com/support.html), so you can get help with usage questions from there. Hope that helps.
