### ISSUE TITLE
add a delay time for first health check

### ISSUE THREAD

**Issue by varnson** [hashicorp/consul#5632]
#### Feature Description
Would you please add a fixed delay time for first health check after service registration?

#### Use Case(s)
For some reasons, we do not want a service to be active immediately after service registration.
For example, after we deployed a service, we need to test it for some simple cases to ensure it works well. So it must not be active in Consul.
Now we had called the agent/service/maintenance API after service registration API.
And I know Consul will wait for a random time  before the first health check in agent/checks/check.go. Because it is a random time, I am not sure the service will not be active before my calling of  agent/service/maintenance.

So, would you please add a fixed delay time for the first health check?
I had made an example at https://github.com/varnson/consul/commit/de02367c564db99329d6a060a3f09fcfc9ab74a7.
It's too simple and the time is fixed by 2s.
Maybe it's better if  this time  was added in config file. 
It is also an alternative way to add a parameter in service registration API to set maintenance mode when service registration. 

Thank you very much.

**Comment by pierresouchay** [comment]
We are doing it this way for the few services saying passing too early:
Add another health check with status critical by default. Run it every 5 min (or whatever you delay is)

**Comment by pearkes** [comment]
I think that is an appropriate workaround from @pierresouchay, I'm going to close this. I think adding a delay as described may be somewhat confusing for users who I could see getting tripped up on this behavior as it adds some variability to the the health check workflow.

Thank you for the suggestion!

**Comment by nosretep** [comment]
Can someone explain why the workaround works, and/or show a snippet of json config of what is being suggested?
