### ISSUE TITLE
No Watch API?

### ISSUE THREAD

**Issue by wi-cuckoo** [hashicorp/consul#5636]
Sorry to bother, In [Godoc](https://godoc.org/github.com/hashicorp/consul/api), I didn't see the WATCH api. Does it not naming watch. And In Etcd, I found it easily.

If I programming with Golang, How to use the watch feature, It's very important

**Comment by pearkes** [comment]
If you're trying to watch for changes in the Consul API you're really just using [blocking queries](https://www.consul.io/api/index.html#blocking-queries). In the Go API you specify options related to that with [query options](https://godoc.org/github.com/hashicorp/consul/api#QueryOptions).

Hope that helps!
