### ISSUE TITLE
Unable to pass -log-file during consul binary run nor able to pass in to config.json file

### ISSUE THREAD

**Issue by ashwinkupatkar** [hashicorp/consul#5646]
#### Overview of the Issue

I am running consul inside a docker container.

I am using following command in my entry script to start dockerised consul server

/opt/consul/bin/consul agent -config-dir /opt/consul/conf

But when I put /opt/consul/bin/consul agent -config-dir /opt/consul/conf -log-file /opt/consul/consul.log

IT throws following error:

==> error parsing flags: flag provided but not defined: -log-file

######################

When I place the param in config.json , it throws below error

 ==> Error parsing /opt/consul/conf/consul.json: 1 error(s) occurred:
Apr 11 02:06:05 <somehostname> consul[12094]:
Apr 11 02:06:05 <somehostname> consul[12094]: * invalid config key log-file
 

### Consul info for both Client and Server
consul version 1.2.2
consul client 0.7.0
</details>

### Operating system and Environment details
Centos7

### Log Fragments

==> error parsing flags: flag provided but not defined: -log-file

 ==> Error parsing /opt/consul/conf/consul.json: 1 error(s) occurred:
Apr 11 02:06:05 <somehostname> consul[12094]:
Apr 11 02:06:05 <somehostname> consul[12094]: * invalid config key log-file

**Comment by pearkes** [comment]
The log-file option was added in 1.2.3 and you're using 1.2.2, upgrading should fix the issue!

https://github.com/hashicorp/consul/commit/ca35d04472a79cfbde76fa0ecf27caa3ef387a33

Would recommend upgrading to 1.2.4.

**Comment by ashwinkupatkar** [comment]
Thanks pearkes
