### ISSUE TITLE
Read the configuration file from SVN to k/v

### ISSUE THREAD

**Issue by a420648511** [hashicorp/consul#5647]
Using consul as the configuration center, how to read an configuration file(.yml) from SVN to import to its key/value when setting up key/value

**Comment by pearkes** [comment]
You should take a look at https://github.com/Cimpress-MCP/go-git2consul or https://github.com/breser/git2consul which help manage KV via git, which is similar and shows a possible approach to the problem you're trying to solve.

Please note issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend questions be sent to the [Consul mailing list](https://www.consul.io/community.html).
