### ISSUE TITLE
how can i get service register info (health check path) with consul rest api?

### ISSUE THREAD

**Issue by charles1503** [hashicorp/consul#5648]
how can i get service register info (health check path) use consul RestAPI? we use consul for spring cloud service discovery ,but someone service appear shake In a short period of time,so i hope get service health check path for custom monitoring

**Comment by pearkes** [comment]
I think you want to query the checks API for a list of checks for a specific service:

https://www.consul.io/api/health.html#list-checks-for-service

Hope that helps!
