### ISSUE TITLE
HTTP API to support reading ACL policy by name

### ISSUE THREAD

**Issue by eeroniemi** [hashicorp/consul#5649]
#### Feature Description

Add fetching ACL policy by name to HTTP API.

CLI supports this, for example:

`consul acl policy read -name=foo`

#### Use Case(s)

I have fixed names for certain ACL policies. I want to check if policy exists before trying to create it. Now only way to do this is to get list of all policies and iterate this list.

**Comment by mkeeler** [comment]
The cli supports it by doing exactly what you mention. List the policies and find the name.

However this does seem like a reasonable request and one that shouldn't be particularly hard to implement.

I am thinking we would add an `/acl/policy/name/:name` endpoint to retrieve a policy by name.

**Comment by jkirschner-hashicorp** [comment]
The `/acl/policy/name/:name` endpoint was added in https://github.com/hashicorp/consul/pull/6615.

What remains is to connect a command to that endpoint.

Marking as a "good first issue".

**Comment by bisakhmondal** [comment]
Hey guys, I have opened a PR with the required updates. Please take a look when you are free.
Thanks.

/assign

Ping @jkirschner-hashicorp

**Comment by jkirschner-hashicorp** [comment]
Thanks @bisakhmondal! We'll take our first look at this next week during our weekly community PR review meeting.

**Comment by bisakhmondal** [comment]
Awesome. Thanks : )
