### ISSUE TITLE
Consul should update watches on ACL policy changes

### ISSUE THREAD

**Issue by jdelic** [hashicorp/consul#5651]
This ticket was tested against consul-template v0.20.0 and consul v1.4.4.
I believe that this is a consul bug, as consul-template shows normal behavior in the debug log.

We have a two phase setup for consul because of #4977. This means that the following things happen in sequence during node setup:

* [dynamicsecrets](https://github.com/jdelic/dynamicsecrets) creates consul ACL tokens for the node's agent and it's consul-template job via the consul API on its local consul server
* the ACL tokens' secret ids get delivered to the node via [Salt](https://github.com/saltstack/salt)
* Salt writes a consul-template configuration with an ACL token and a consul configuration file with the agent token to disk
* Salt reloads consul-template and consul
* In parallel the Salt minion triggers an event on the Salt master server to provision the tokens with the correct ACLs
* consul-template renders a haproxy instance for my version of a servicemesh [consul-smartstack](https://github.com/jdelic/consul-smartstack), specifically [servicerenderer.ctmpl.py](https://github.com/jdelic/consul-smartstack/blob/b9386cbd0ea204be27978ca0f5db876d0f86f16a/servicerenderer.ctmpl.py#L55) which watches the whole services catalog.

### Expected behavior

The consul agent reads local service definitions and receives cluster-wide service catalog data and repeatedly tries to register its services. When the master attaches the correct policies to the ACL token the agent uses, the agent succeeds with its requests.

Meanwhile consul-template polls the service catalog, but doesn't get any service, because its ACL token is a valid token without any policies. When ACL policies get attached to its ACL token, it gets an update with the new services that it can now see.

### Actual behavior

consul-template runs as a daemon and renders the template with the empty service catalog, then it doesn't pick up the actual service catalog when it's ACL token becomes valid.

I can see consul dropping the services in its response to consul-template in it's log output

```
{"@timestamp":"2019-04-11T16:20:13.412383+00:00",  "msg": "consul: dropping serv
ice \"authserver-int\" from result due to ACLs" }
{"@timestamp":"2019-04-11T16:20:13.424693+00:00",  "msg": "consul: dropping serv
ice \"consul\" from result due to ACLs" }
{"@timestamp":"2019-04-11T16:20:13.428518+00:00",  "msg": "consul: dropping serv
ice \"postgresql\" from result due to ACLs" }
{"@timestamp":"2019-04-11T16:20:13.428800+00:00",  "msg": "consul: dropping serv
ice \"redis-cache\" from result due to ACLs" }
{"@timestamp":"2019-04-11T16:20:13.429052+00:00",  "msg": "consul: dropping serv
ice \"vault\" from result due to ACLs" }
{"@timestamp":"2019-04-11T16:20:13.429932+00:00",  "msg": "consul: dropping serv
ice \"vault-ui\" from result due to ACLs" }
```

I guess that watches in consul don't get reevaluated when their ACLs gain or lose policies.

**Comment by pearkes** [comment]
Thanks for the detailed report. From my understanding I think we need a clear repro (eg. with curl and Consul running in dev mode (`consul agent -dev`) that does the following:

1. Create a service `foobar`
1. Watch the service index with an ACL token that does not have the a policy that is capable of reading the `foobar` service
1. Attach an updated policy that does have this capability
1. The watch should return
