### ISSUE TITLE
Provide the expected behavior for -retry-max

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#5653]
Hi,

the consul agent is booting with old data with the following command line:

consul agent -server -bootstrap-expect 3 -data-dir /opt/application/consul/../consul-works/data-dir -config-dir /opt/application/consul/../consul-works/config-dir -config-dir /opt/application/consul/../consul-works/custom-config-dir -node=server-20_20_20_107 -domain=openpalette -disable-host-node-id -dns-port=53  -recursor=10.41.132.9  -bind=20.20.20.107 -client=20.20.20.107 -retry-join=20.20.20.106 -retry-join=20.20.20.108 -retry-interval=5s -retry-max=5

the situation now is that the node 20.20.20.108 is not available and will be never online, I was expecting that consul cluster will be eventually setup with two members: 20.20.20.106 and 20.20.20.107, but the fact is that the consul cluster cannot finish the leader election with  retrying the 20.20.20.108 endlessly.

so the questions goes here:
1. why the -retry-max didn't take effect?
2. I would never know which nodes are not available, so I need to just put them all in the retry join list, and wish the consul would exclude the unavailable one(s) automatically if the retry maximum exceeds and proceed with the booting with the remaining ones. 
does Consul support this requirement?

Thanks,
Allen

**Comment by pearkes** [comment]
> but the fact is that the consul cluster cannot finish the leader election with retrying the 20.20.20.108 endlessly

This is strange. Can you include logs from the server that is failing to join?

**Comment by hehailong5** [comment]
Hello,
there was no consul instance running on 20.20.20.108 at all, this was made on purpose just to verify the -retry-max.
and for the 20.20.20.106 and 20.20.20.107, it just prints the following error every 5 seconds:

    2019/04/11 20:43:55 [ERR] raft: Failed to make RequestVote RPC to {Voter 20.20.20.108:1104 20.20.20.108:1104}: dial tcp 20.20.20.106:0->20.20.20.108:1104: getsockopt: connection refused
