### ISSUE TITLE
Unable to get all service lists via HTTP interface

### ISSUE THREAD

**Issue by xiaoxing598** [hashicorp/consul#5657]
1. When I asked Consul's HTTP interface to get a list of services, I got a null data, but there were a lot of services, at least on the WEBUI.
```
curl http://10.x.x.x:8500/v1/agent/services
{}
```
2. You can see the trace of the request in the consular log
```
[DEBUG] http: Request GET /v1/agent/services (37.378µs) from=10.x.x.x:50048
```

**Comment by pierresouchay** [comment]
@xiaoxing598 It returns only services on the agent you are querying.
To query services in the cluster, use `/v1/catalog/services` instead

**Comment by xiaoxing598** [comment]
@pierresouchay I have previously successfully requested  `/v1/agent /services`  and returned the result, it can return the details of each service, I am curious to request this interface now but did not respond to the correct content. In addition, I tried to request the interface address you gave to see the response successfully, which means that the consular service was installed correctly.

```
{
    "consul": [],
    "java-aggservice-test": [
        "version=1.0.0",
        "secure=false"
    ],
    ...
}
```

**Comment by pierresouchay** [comment]
Look at docs first: https://www.consul.io/api/agent/service.html

v1/agent/* will show local agent data
V1/catalog/* or v1/health/* will show services of whole cluster

**Comment by xiaoxing598** [comment]
ok，thanks!
