### ISSUE TITLE
Quorum member failure spams log messages

### ISSUE THREAD

**Issue by jcmcken** [hashicorp/consul#566]
Currently, if a quorum member fails for some reason, the current cluster leader will spam messages like ``Failed to contact <ipaddr>:8300 in <amount>s`` every 0.5 seconds (on ``INFO``). This leads to a hugely verbose log. On my test machines, each line is about 100 bytes, which means about 700KB of logs per hour per failed server just for this "Failed to contact" message.

Could we consider some sort of exponential decay for this message (.5s,1s,3s, etc.), or some way to summarize it so that it isn't printed every 1/2 second?

**Comment by armon** [comment]
It does do an exponential back off currently (from 10msec to 500msec), but I guess we can raise the limit to 5 seconds instead. I agree it can be very noisy!

**Comment by armon** [comment]
Fixed by https://github.com/hashicorp/raft/commit/16b50a19d1a1b0c85ebf20294d2838b3c1814943
