### ISSUE TITLE
Option to make "-reason" flag for maintenance mode mandatory

### ISSUE THREAD

**Issue by antonsoroko** [hashicorp/consul#5676]
#### Feature Description
Config file option to make "-reason" flag for maintenance mode mandatory, e.g. only for production environment. Also this way it would be backward compatible.
A written overview of the feature.

#### Use Case(s)

Could be very useful when you run consul in production with a lot of agents and you want to keep your cluster in consistent state. Sometimes people take node for troubleshooting (`maint -enable`) without specifying a `reason` and then they forget to disable maintenance mode. So after some time you end up with a bunch of nodes in undefined state.
We really could use such a feature.

If you think that this idea is viable then I can try to make a PR.

Thank you in advance!

**Comment by pearkes** [comment]
Hey @antonsoroko! Thanks for the suggestion, and for thinking about backwards compatibility.

I'm leaning towards closing this and saying we shouldn't do it. You're right that if we made a configuration item we could make this backwards compatible, but we'd then be adding yet another boolean for what I would characterize as a semi-obscure requirement.

How I could see a lot of organizations solving this problem of requiring the `-reason` flag are:

- Writing a wrapper script of some kind and storing it wherever people typically run this command that validate presence of an argument for a reason. This could be extended to validate format of the reason, length of the reason, really anything!
- Depending on how your systems work, you might be able to even automate the maintenance enablement via the Consul HTTP API so you can add further validation or automation (hooks into other services for example)

Does that make sense? That reasoning leads me to thinking closing this is the best approach.

**Comment by antonsoroko** [comment]
Hi @pearkes 
Thank you for the detailed explanation of possible solutions.
We thought about wrapper - is it simple solution, but drawback is that this is one more level of abstraction (small one, though). But still it reminds me https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering :-)

Please do not close this issue yet, maybe i will come out with new reasons :-)
If not - i will close the ticket.

Thank you again!
