### ISSUE TITLE
token field missing from example

### ISSUE THREAD

**Issue by toupet** [hashicorp/consul#5684]
This docuement states "This example shows all possible fields, but note that only a few are required." and then provides an example which does not include the 'token' field and should.  Later on, the document states, "Services may also contain a token field to provide an ACL token."  Which contradicts the fact that the example does not contain the 'token' field.  This should be added to the example so that it is clear on how the field should appear when it is used.

I ran into this becuase my service was failing to register and could not figure out what was going on until I found an example of using the token and realized that was my problem.

**Comment by pearkes** [comment]
Which page are you talking about in particular?

**Comment by mkeeler** [comment]
This was the page: https://www.consul.io/docs/agent/services.html
