### ISSUE TITLE
Make ports information consistent in documents

### ISSUE THREAD

**Issue by grove-mountain** [hashicorp/consul#5690]
# Overview of the Issue

Information on ports needed for firewall configurations is confusing.   Need to highlight TCP and UDP port usage in all places listed.

Searching for "Consul Ports" on Google yields HashiCorp pages of:
https://www.consul.io/docs/install/ports.html
https://www.consul.io/docs/agent/options.html
https://learn.hashicorp.com/consul/advanced/day-1-operations/reference-architecture

The first two don't explicitly call our UDP ports early on, but you can find the information at the bottom of the options page.
https://www.consul.io/docs/agent/options.html#ports-used

The ports config should definitely call out UDP:
https://www.consul.io/docs/agent/options.html#ports

As well as https://www.consul.io/docs/install/ports.html as this is the first result (currently) for Google searches.  DuckDuckGo has different ordering.

**Comment by judithpatudith** [comment]
Hey, @kaitlincarter-hc assigning you in case this ties into the ports work you're already doing. Thanks for the specific feedback @grove-mountain :)

**Comment by kaitlincarter-hc** [comment]
@grove-mountain I've created a PR that will hopefully reduce confusion https://github.com/hashicorp/consul/pull/5693

**Comment by jsosulska** [comment]
Closing as the relevant PR was merged.
