### ISSUE TITLE
How to get the bootstrap token in all the nodes in the consul cluster via http end point? (v1.2.2)

### ISSUE THREAD

**Issue by ashwinkupatkar** [hashicorp/consul#5691]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here if you have a question.

- Frequently asked questions: https://www.consul.io/docs/faq.html
- Consul Guides: https://www.consul.io/docs/guides/index.html

Any other questions can be sent to the Consul mailing list: https://www.consul.io/community.html

**Comment by pearkes** [comment]
Given the content in the body of the issue this may have been opened accidentally, I'm going to close it.
