### ISSUE TITLE
health service check problem

### ISSUE THREAD

**Issue by Moriadry** [hashicorp/consul#5697]
if we use agent service to register some certain service， but port = null， we will not get this health service (What's more , we can still get HealthCheckService and agent services). 

I believe this is a obvious bug.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

just as my description.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by pierresouchay** [comment]
@Moriadry can you paste the exact definition of your service here?

**Comment by pearkes** [comment]
Given we haven't heard anything based on the suggestions/questions above I'm going to close this issue, but I encourage you to comment and we can re-open it if you want to pick this up again.

Alternatively, if things have changed dramatically, feel free to create a new issue or PR.
