### ISSUE TITLE
consul members not joining in kubernetes cluster

### ISSUE THREAD

**Issue by AATHITH** [hashicorp/consul#5702]
### Overview of the Issue:
I tried to run a consul-vault cluster in kubernetes.
I used this link https://testdriven.io/blog/running-vault-and-consul-on-kubernetes/ to create the cluster.
The first time it worked fine 3 consul servers where there, 2 vault-consul clients where joined automatically.
But when I recreate it again I'm not able to create the cluster like before, Consul members were not able to join the cluster(can't join the cluster even if I try to join manually).

### Steps to reproduce this issue:
1. use this link to create the consul-vault cluster[ https://testdriven.io/blog/running-vault-and-consul-on-kubernetes/]
2. **consul members** command will show only one consul server(eg: if you used 'kubectl port-forward consul-0 8500:8500' only that consul-0 will be visible in "consul members")

### Consul info for both Client and Server
the output from server 'consul info' command here
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 0bddfa23
        version = 1.4.0
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr =
        server = true
raft:
        applied_index = 0
        commit_index = 0
        fsm_pending = 0
        last_contact = never
        last_log_index = 0
        last_log_term = 0
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = []
        latest_configuration_index = 0
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 0
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 80
        max_procs = 2
        os = linux
        version = go1.11.1
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 1
        left = 0
        member_time = 2
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1

### Operating system and Environment details

OS:Ubuntu 16,
k8s:1.14(1 master, 1 worker)

### Log Fragments
log for consul-0
https://files.gitter.im/hashicorp-consul/Lobby/yYtI/thumb/image.png

**Comment by pearkes** [comment]
Hey @AATHITH unfortunately we can't really help debug the configuration in the linked post as it could be many different things. We do officially support running Consul on or with Kubernetes and provide configuration (via Helm) and services to make that easier. I'd recommend starting there if you're having trouble!

https://www.consul.io/docs/platform/k8s/index.html
