### ISSUE TITLE
Is the registered service case-sensitive in Consul？

### ISSUE THREAD

**Issue by chymy** [hashicorp/consul#5707]
Is the registered service case-sensitive in Consul please？

**Comment by pierresouchay** [comment]
Yes and no.

If you register those 2 services on an agent:

redis1.json
```
{
      "ID": "redis1",
      "Name": "redis",
      "Port": 8000
}
```
`curl --request PUT http://127.0.0.1:8500/v1/agent/service/register -d @redis.json`

redis2.json
```
{
      "ID": "redis2",
      "Name": "Redis",
      "Port": 8000
}
```
`curl --request PUT http://127.0.0.1:8500/v1/agent/service/register -d @redis2.json`

You will end up with this in `curl localhost:8500/v1/catalog/services`:
```
{
    "Redis": [],
    "consul": [],
    "redis": []
}
```

But if you query both:
`curl localhost:8500/v1/catalog/service/Redis`
and
`curl localhost:8500/v1/catalog/service/redis`

you will end with the same result (same for DNS or `/v1/health/service/redis` VS `/v1/health/service/Redis`)... so basically, the catalog list of service is case sensitive, but not the other endpoints.

This is reasonable as DNS is not case-sensitive neither, maybe `/v1/catalog/services` might not return both (but it might break some code relying on that)

Still you can remark that the case will be preserved in their ServiceName value in each endpoint as well (so Redis for one, redis for the other)

**Comment by pearkes** [comment]
Thanks for the great and thorough answer here @pierresouchay!

**Comment by ikimi** [comment]
After 5 years, met the same problem 😂
