### ISSUE TITLE
Consul TLS Cert Create Option not working

### ISSUE THREAD

**Issue by lijumc** [hashicorp/consul#5710]
The option "-additional-ipaddress" comes with Consul TLS Cert Create is not working.

Steps to reproduce this issue, eg:

1. Install consul v1.4.4 binary 
2. Run `consul tls ca create` to generate a CA certificate
3. Run ` consul tls cert create -server -additional-ipaddress=172.17.0.1` to generate server certificate
4. Step #3 fails and throwing below error message,

`flag provided but not defined: -additional-ipaddress`

Refer 1: https://www.consul.io/docs/commands/tls/cert.html
Refer 2:  https://learn.hashicorp.com/consul/advanced/day-1-operations/certificates

**Comment by pearkes** [comment]
Hey @lijumc looks like this was added in https://github.com/hashicorp/consul/pull/5602 but somehow the documentation deployed. This will be in our next release which is relatively soon and is on master now. Sorry for that confusion!
