### ISSUE TITLE
UI HTTP Headers

### ISSUE THREAD

**Issue by johncowen** [hashicorp/consul#5712]
#### Feature Description

Add relevant HTTP headers when serving the index file of the UI. Potentially provide a configuration option to disable these headers, although there is a chance that folks who want to disable these could strip them via a proxy.

See prior art in Vault UI

**Comment by pearkes** [comment]
I went to open a new issue and then realized it was not necessary as this exists!

Here are some notes:

Currently, the configurable [API response headers](https://www.consul.io/docs/agent/options.html#response_headers) do not apply to the /ui endpoint, where we serve the UI from.

This makes [CSP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), and possibly others, non-configurable when using the built-in UI serving mechanism.

For reference, this is possible in Nomad [here](https://github.com/hashicorp/nomad/blob/master/command/agent/http.go#L262) and Vault [here](https://www.vaultproject.io/api/system/config-ui.html#configure-ui-headers).

This can help protect against various attacks in-browser against the Consul UI.
