### ISSUE TITLE
Consul vendoring itself is causing panics on type assertions

### ISSUE THREAD

**Issue by tom-hadlaw-hs** [hashicorp/consul#5713]
#### Overview of the Issue

I have a module that uses the `consul/watch` module, `watch` in turn imports `consul/api`; however this import appears to use the vendored files under `consul/vendor/github.com/hashicorp/consul/api`. Later I attempt to do a type assertion on an `interface{}` such as:

```
i.(api.KVPairs)
``` 

which causes a runtime panic:

`panic: interface conversion: interface {} is api.KVPairs, not api.KVPairs (types from different packages)`

Before the panic occurs I added a println which prints out the `reflect.TypeOf(i).PkgPath()` that shows that the pkgpath of the interface{} is `github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api`

whereas the command:

`fmt.Println("Local Path =", reflect.TypeOf(api.KVPair{}).PkgPath())`

yields 

`github.com/hashicorp/consul/api`

It appears as though Go will give first priority to vendored code, even if the library itself being vendored: https://github.com/golang/go/blob/a16dcc00526dbb5ff411004c987a4182a8d68e7c/src/cmd/go/internal/load/pkg.go#L845

#### Reproduction Steps

Start a local consul "cluster"

Create the following module `test0`
```
package test0

import "github.com/hashicorp/consul/watch"

type Handler func(data interface{})

func TestWatch(h Handler) {
	params := map[string]interface{}{
		"type":   "keyprefix",
		"token":  "sometoken",
		"prefix": "foo/",
	}

	wp, err := watch.Parse(params)
	if err != nil {
		panic(err)
	}

	wp.Handler = func(idx uint64, data interface{}) {
		h(data)
	}

	wp.Run("localhost:8500")
}
```

The run 
```
package main

import (
	"fmt"

	"github.com/hashicorp/consul/api"
	"github.com/pod/test0"
)

func main() {
	test0.TestWatch(test0.Handler(func(i interface{}) {
		a := i.(api.KVPairs)
		fmt.Println(a)
	}))
}
```

### Operating system and Environment details
GO Version: 1.11.5
OS: Darwin and Linux
Architecture: amd64

**Comment by mkeeler** [comment]
@tom-hadlaw-hs Sorry for the problems here. We are working through the best way to fix this while enabling go module support. I have a PR open which does fix the issue as it removes vendoring of our own nested api and sdk modules (would be great if that was the default behavior of `go mod vendor`). Also it moves the watch package into the api package/modules to allow the same thing to not cause issues with go 1.12.X
