### ISSUE TITLE
Extensions support

### ISSUE THREAD

**Issue by indesil** [hashicorp/consul#5717]
#### Feature Description
Hello,
I wanted to ask about possibility of adding extensions (plugins) to consul.
Currently in our project we are using consul's KV where data is taken from git repos.
I'm aware that there is something like git2consul or gonsul but that requires us to install and maintaining another third part library.  My question is can you provide some plugin like extensions to consul allowing us to add some extra features embedded withing consul installation like git synchronization?
That could give us a chance to have complex feature rich instillation without need of any standalone extensions that are only used for consul and nothing else.

#### Use Case(s)
User wants to add git synchronization extension allowing to fetch KV values from git repos. By adding proper plugin it could be done automatically. Allowing to configure such plugins via consul UI would be a nice feature too.

**Comment by pearkes** [comment]
Some of the integrations in Consul are pluggable but I'm not sure we plan to specifically embed (via plugins) features like you describe. I think the model we will continue is providing an HTTP API to communicate with Consul over the network (or the same host).

Some of our projects such as https://github.com/hashicorp/consul-template work in that way and I believe that is the model will will continue following.
