### ISSUE TITLE
How do you automagically replace nodes in the catalog?

### ISSUE THREAD

**Issue by sspreitzer** [hashicorp/consul#5726]
Hi there

So here is what I do:
* Using terraform to spin up nodes, the nodes join my local consul server (dev mode).
* The node agent runs in a container
* I destroy and recreate the nodes frequently, the nodes' consul does not unregister
* I use that to expose the consul catalog to traefik for edge Loadbalancing

What does not work:
* Consul does not accept a node once i destroyed the old one. It states that there is already a node with that hostname registered under a different node-id

My questions:
* How can I get this to fly?
* What am I missing?
* Why does consul not accept to overwrite the exisiting hostname+node-id combination? Sounds broken to me?

Thanks a lot and kind regards
Sascha

**Comment by sspreitzer** [comment]
Ah yes, and `-disable-host-node-id` does not work in that case.

**Comment by sspreitzer** [comment]
As a workaround I added `consul force-leave <nodename>` in the terraform destroy part.

**Comment by pearkes** [comment]
See also #4741 which has rich set of context on this specific issue that I think will describe the nuance to this type of situation. There was just a fix landed there that will hopefully help address your specific use-case!
