### ISSUE TITLE
Question with the CAP

### ISSUE THREAD

**Issue by doucheng** [hashicorp/consul#5728]
hi guys，consul is a great project, I has a question by the docs :

https://www.consul.io/intro/vs/serf.html

>Consul is opinionated in its usage while Serf is a more flexible and general purpose tool. In CAP terms,Consul uses a CP architecture, favoring consistency over availability. Serf is an AP system and sacrifices consistency for availability.This means `Consul cannot operate` if the central servers cannot form a quorum while Serf will continue to function under almost all circumstances.

what mean of the `Consul cannot operate`, read or write ?

**Comment by ChipV223** [comment]
@doucheng : To answer your question, Consul is unusable if the server nodes are not able to create a quorum & elect a leader, given that it uses a consensus protocol based on Raft.

For more information on the Consul architecture, I recommend checking out the [following section](https://www.consul.io/docs/internals/architecture.html) from the Consul documentation!
