### ISSUE TITLE
Failed restoring services when service file is a directory

### ISSUE THREAD

**Issue by kdlan** [hashicorp/consul#573]
#497 add a feature that consul can restore the services locally registered

When register a service with name like 'example/test-service', the local file will be store as `$DATA_DIR/services/example/test-service`, restart the consul agent and it fails. 

```
==> Starting Consul agent...
==> Error starting agent: Failed restoring services: read /tmp/services/example: is a directory
```

**Comment by armon** [comment]
Good catch! @ryanuber maybe we can canonicalize somehow? I think windows has some characters it doesn't like either. Simplest may be to just MD5(ServiceID) or something.

**Comment by ryanuber** [comment]
Ah, tricky! @armon makes sense, will adjust this.

**Comment by ryanuber** [comment]
@kdlan This should now be fixed in master! Let us know if you have further issues. Thanks for reporting this.

**Comment by kdlan** [comment]
I pull the master with commit `a24f6e3d4ded207e28ce639459fd88bf102da8d5` , But I can't build consul now.

```
> make
--> Installing build dependencies
--> Running go fmt
--> Installing dependencies to speed up builds...
# github.com/hashicorp/consul/consul
consul/client.go:142: conf.Merge undefined (type *serf.Config has no field or method Merge)
consul/server.go:306: conf.Merge undefined (type *serf.Config has no field or method Merge)
consul/server.go:308: conf.Merge undefined (type *serf.Config has no field or method Merge)
make: *** [all] Error 2
```

**Comment by kdlan** [comment]
I update the Serf Repository and it can build and it works now.  Great thanks!
