### ISSUE TITLE
/v1/config/ endpoint always returns 200 and empty list 

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#5741]
```
curl -i localhost:8500/v1/config/list
HTTP/1.1 200 OK
Content-Type: application/json
Vary: Accept-Encoding
Date: Tue, 30 Apr 2019 11:24:10 GMT
Content-Length: 3

[]
```

```
curl -i localhost:8500/v1/config/
HTTP/1.1 200 OK
Content-Type: application/json
Vary: Accept-Encoding
Date: Tue, 30 Apr 2019 11:24:24 GMT
Content-Length: 3

[]
```

We should 404 anything that's not a valid endpoint

**Comment by banks** [comment]
Actually this seems to be valid. The issue is that the config is not actually being bootstrapped as expected it seems.

**Comment by mkeeler** [comment]
Returning an empty list with /v1/config seems OK. How we handle something like /v1/config/list where the kind in the URL is invalid I am not sure. I think I might lean towards a 500 instead although.
