### ISSUE TITLE
Service with HTTP check, validate Get API result

### ISSUE THREAD

**Issue by Mathavana** [hashicorp/consul#5765]
Hi,
this is my service definition.
![image](https://user-images.githubusercontent.com/5356325/57065722-ef11f280-6cfc-11e9-8be8-2715ec9f6beb.png)

I need to validate the above mention end point returning the following out put, instead of 200 status code.
![image](https://user-images.githubusercontent.com/5356325/57065812-22548180-6cfd-11e9-916b-7dcf51f6ac6a.png)

**Comment by pierresouchay** [comment]
Use a script (args) to validate then...
