### ISSUE TITLE
Consuls marks all services as failed when it cannot perform health check of the 1 service

### ISSUE THREAD

**Issue by terancet** [hashicorp/consul#5787]
I am using Consul v1.4.4  as the "Service Discovery" service. 

I launch Consul locally in the following way

`./consul agent -dev -config-dir=./consul-service-registration-configurations/`

where the `./consul-service-registration-configurations/` contains two service definitions in json format

```
{
  "service": {
    "name": "serviceF",
    "tags": [
      "serviceF"
    ],
    "port": 5001
  },
  "check": {
    "id": "serviceF",
    "name": "Check the status of the serviceF by making get request on 5001 port",
    "http": "http://localhost:5001/serviceF/status",
    "method": "GET",
    "interval": "10s",
    "timeout": "1s"
  }
}
```

```
{
  "service": {
    "name": "serviceH",
    "tags": [
      "serviceH"
    ],
    "port": 5000
  },
  "check": {
    "id": "serviceH",
    "name": "Check the status of the serviceH by making get request on 5000 port",
    "http": "http://localhost:5000/serviceH/status",
    "method": "GET",
    "interval": "10s",
    "timeout": "1s"
  }
}
```
I simulate the following scenario: I make the service `serviceF` to fail but `serviceH` remains to be healthy. In this case, Consul marks all services as failed in UI

![image](https://user-images.githubusercontent.com/2099309/57194390-24158380-6f4f-11e9-89ba-c67c1976a040.png)

and I am not being able to query the healthy service `serviceH`. 

But when I remove the health check in `serviceF`, then I can easily query the healthy service `serviceH` and I can see from Consul UI that all services have the green status

![image](https://user-images.githubusercontent.com/2099309/57194405-4909f680-6f4f-11e9-92fb-b1e69d7a603a.png)

Questions are the following:
1. Is this a bug or did I launch Consul in the inproper way?
2. How can I deregister the unhealthy service immidiatly after the health check has failed?

**Comment by mkeeler** [comment]
@terancet I believe the problem is that you are registering a node level check and not a health check bound to a service.

The details are [here](https://www.consul.io/docs/agent/checks.html#service-bound-checks) but in short you should add a `service_id` field in the check definition to bind that health check to the service instead of the whole node. Node level health checks will propagate to all services for that node which is why the failing health check ends up making it look like all the services are unhealthy.

**Comment by terancet** [comment]
@mkeeler really appreciate your answer! Your answer solved my problem =)
