### ISSUE TITLE
API: The TTL check resources do not update the note if the state does not change.

### ISSUE THREAD

**Issue by OzWolf** [hashicorp/consul#579]
**Scenario**
- Service check is currently in a critical state.  We use the `?note={note}` query parameter to report the failing healthcheck(s) so as support staff can track the issue quickly.
- Service pings the TTL check resource at `/v1/agent/check/{state}/{checkId}` but the state is still critical though the note we wish to show has changed.

**Result**

The Output/Note does not update appropriately if the state has not changed and will continue to show the output from the initial instance the state went critical.

**Current Work Around**

We currently toggle the state of the service check to ensure the `?note={note}` value is flushed correctly.

**Desired Output**

Be able to re-iterate a current check state but accept the new note/output property.

**Comment by armon** [comment]
This is actually a "feature". See here: https://consul.io/docs/agent/options.html#check_update_interval
Basically the `check_update_interval` controls how often the output / notes are synced given that the state does not change. This is an important optimization as some checks like uptime may run every second with slightly different output, causing an enormous amount of useless write load.

There are some options here. If it works for you guys, just modify that value to be lower than 5 minutes. We can also consider some type of flag or endpoint to "force flush" the current state, ignoring the time delay.

**Comment by OzWolf** [comment]
Ah, missed that little nugget in the configuration. Thanks. 

Happy for this issue to be closed based on the explanation.

**Comment by oliora** [comment]
This would be great to have a "force flush" flag added to `/v1/agent/check/xxx`.

**Comment by armon** [comment]
@oliora Good idea! Tagging for enhancement.

**Comment by slackpad** [comment]
Tagging this for https://github.com/hashicorp/consul/issues/1982 instead, which should automatically get updates propagated after a state change. This seems like a better solution since we don't want people wiring force-flush into their checks.
