### ISSUE TITLE
FR: Centralized Consul servers w/o direct IPv4 connectivity

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/consul#5815]
#### Feature Description

Consul server mode where the servers are remote from the agent cluster, and the agents have an inherent namespace in all registrations.

#### Use Case(s)

I'm considering a scenario where I have several hundred AWS VPCs with overlapping IPv4 spaces.  Managing separate Consul clusters in each of these is a maintenance and cost nightmare. Running a single Consul server cluster that is used by all of these VPCs would be much simpler. Since the users are not from a single administrative entity I'd want each client group to include a namespace similar to how Vault handles multi-tenancy, so that no naming decision used by group A impacts group B.

I can think of two ways to achieve the requisite connectivity:
1. AWS VPC Privatelink, but presently UDP is not supported.  In this scenario the Consul servers would _not_ be able to initiate connectivity to the agents at all, and agents could not speak UDP to the servers.
2. IPv6.  I could allow IPv6 connectivity between the agents and servers. This starts to look like the Network Segments feature, except that each 'segment' in this scenario would be opaque to each other to prevent clobber of services. I wouldn't want to reuse the datacenter functionality for this since datacenters would still be useful within a namespace (think east vs west AWS regions).  The client application do not necessarily support IPv6 so although Consul would use IPv6 for inter-consul connectivity I'd want an option for all service queries to return the IPv4 address.

**Comment by pearkes** [comment]
I think there is a bit more to your scenario but I think this kind of ties into #766 and it might be worth chiming in with the specifics of your use-case there. Hope that makes sense and thank you for the detailed feedback!

**Comment by burdandrei** [comment]
if you can do IPv6 this can solve a lot of problems - I ran a couple of cluster with ipv6 only - worked really good
