### ISSUE TITLE
return configured domain in reverse PTR instead of .consul.

### ISSUE THREAD

**Issue by dankennedy** [hashicorp/consul#582]
I'm using the reverse lookup function added very recently and while it returns the correct result it always returns the node name as machine1.node.dc.consul even though we have a domain configured in server.json of blah, so I would expect the answer to be machine1.node.dc.blah

Firstly is my assumption correct? If so, I'll create a PR to update it.

Thanks

Finally just wanted to express my thanks/appreciation for consul as a whole. Great work.

**Comment by armon** [comment]
Definitely a bug! Marking as a bug so we can fix, but would love a PR as well :)
