### ISSUE TITLE
consul service tags do not resolve when forwarding DNS

### ISSUE THREAD

**Issue by vvitayau** [hashicorp/consul#5822]
#### Overview of the Issue

https://learn.hashicorp.com/consul/security-networking/forwarding
https://medium.com/zendesk-engineering/making-docker-and-consul-get-along-5fceda1d52b9 does not behaving correctly after setup detailed below.

I have multiple foobar.service.consul, each service is uniquely tagged to denote its environment.

I am able to resolve foobar.service.consul 
but unable to resolve the tagged production.foobar.service.consul
through the combination of the dummy interface 169.254.1.1 and dnsmasq

What is interesting is this is not an issue if I instead simply include the consul server in
/etc/resolv.conf to avoid using dnsmasq and dummy interface 169.254.1.1
```
$ echo "nameserver <my consul server ip> | sudo tee -a /etc/resolv.conf

$  mysql -h production.foobar.service.consul -u root -p MyDatabase -e 'show tables;'
+-------------------+
| Tables_in_MyDatabase |
+-------------------+
...
+-------------------+
```

#### Reproduction Steps 

1. `sudo ip link add dummy0 type dummy`
2. `sudo ip addr add 169.254.1.1/32 dev dummy0`
3. `sudo ip link set dev dummy0 up`
4. `sudo yum install -y dnsmasq`
5. `sudo mkdir -p /etc/dnsmasq.d`
6. `echo -e 'server=/consul/169.254.1.1#8600\nlisten-address=127.0.0.1\nlisten-address=169.254.1.1' | sudo tee /etc/dnsmasq.d/consul.conf`
7. `sudo systemctl enable dnsmasq`
8. `sudo systemctl start dnsmasq`
9. `sudo sed -i 1's/$/\nnameserver 169.254.1.1 &/' /etc/resolv.conf`
10. `echo CONSUL_HTTP_ADDR=169.254.1.1:8500 | sudo tee /etc/environment`
11.  WORKS - `mysql -h foobar.service.consul -u root -p MyDatabase -e 'show tables;'
12.  FAILS - `mysql -h production.foobar.service.consul -u root -p MyDatabase -e 'show tables;'

SAME error as
```
docker run --network=host --dns=169.254.1.1 -it mysql /bin/bash

#  mysql -h foobar.service.consul -u root -p MyDatabase -e 'show tables;'
ERROR 2005 (HY000): Unknown MySQL server host 'production.foobar.service.consul' (0)

#  mysql -h foobar.service.consul -u root -p MyDatabase -e 'show tables;'
+-------------------+
| Tables_in_MyDatabase |
+-------------------+
...
+-------------------+
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 3
build:
        prerelease =
        revision = ea5210a3
        version = 1.4.4
consul:
        acl = disabled
        known_servers = 14
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 49
        max_procs = 2
        os = linux
        version = go1.11.4
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 88
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 6
        member_time = 5615
        members = 41
        query_queue = 0
        query_time = 541
```
</details>

### Operating system and Environment details

```Red Hat Enterprise Linux Server release 7.6 (Maipo)``` on AWS

**Comment by pierresouchay** [comment]
Can you output the result of dig on the machine for both resolutions (with and without tag)?
