### ISSUE TITLE
[Enhancement] Display Node Count in "Nodes" and "Services" tab along with HealthCheck count

### ISSUE THREAD

**Issue by kamaltherocky** [hashicorp/consul#5828]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Currently, when we go to the "Nodes" tab, the count which is shown there is the healthCheck count which passing or warning or critical. It would be useful to display the Number of nodes.
The same applies to the "Services" tab, we display the healthCheck count , so please include the number of Nodes along side of each service

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by opihana** [comment]
Hi @kamaltherocky, thanks for submitting this issue. We've updated this in Consul 1.5, which you can explore using https://demo.consul.io/ui/dc1/nodes.
