### ISSUE TITLE
[question] website: add link to learn.hashicorp.com/consul

### ISSUE THREAD

**Issue by jweissig** [hashicorp/consul#5829]
On the current version of the website https://www.consul.io/ there is no link in the header back to https://learn.hashicorp.com/consul/ like on other hashicorp products (vault, terraform, etc). This is a missed opportunity as learning site has some good labs, a UI demo, etc.

Is this a good idea? Should I submit a PR for it?

**Comment by pearkes** [comment]
There is currently some work being done to the nav/headers so I'd hold off submitting a PR for such a change but I do have one clarifying question – how were you aware of learn.hashicorp.com when on the product site? Did you initially navigate there and then to the product site and wanted to get back, or similar?

**Comment by jweissig** [comment]
Makes senes. I knew about the learn.hashicorp.com site already after checking out Vault. It was a nice addition to the Vault site too, the site since the learn pages are packed with useful walkthroughs. I'd definitely suggest adding it for Consul too.
