### ISSUE TITLE
API Client does not respect HTTP_PROXY env variable

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#583]
See: 
https://github.com/armon/consul-api/issues/15
https://github.com/hashicorp/consul-template/issues/132#issuecomment-67775902

**Comment by marcellodesales** [comment]
I have the same problem... My HTTP_PROXY env variable is set... I get those ones in the logs:

```
==> Failed to check for updates: Get https://checkpoint-api.hashicorp.com/v1/check/consul?arch=amd64&os=linux&signature=03650230-84fe-9b2b-40e1-a6743de9e67d&version=0.4.1: dial tcp 54.83.40.233:443: i/o timeout
```

This should be downloaded automatically, correct?

**Comment by cskksc** [comment]
I think this issue can be closed now.
https://golang.org/src/net/http/transport_test.go?#L1913
Is a similar test required in consul or cleanhttp ?

**Comment by ryanuber** [comment]
I've verified that this works in the API client as expected, and subsequently all Consul commands such as `consul lock`, `consul agent`, etc. Please re-open or comment if you are still seeing this.

**Comment by marcellodesales** [comment]
@cskksc  @ryanuber thanks!
