### ISSUE TITLE
rpc: can't find method Internal.ServiceDump from xxxx

### ISSUE THREAD

**Issue by varnson** [hashicorp/consul#5833]
OS: RHEL7.4

We have a cluster of 3 nodes with consulV1.4.4.
When I add a new server node with consul 1.5 to it, the new node cannot display the ui correctly.
In the UI, nodes list looks well, But services list cannot be display correctly. 
API "/v1/internal/ui/services?dc=xxxxx"  returns "500 internal server error".
And the log also show a message of “rpc: can't find method Internal.ServiceDump from xxxx”.
#### Reproduction Steps

Steps to reproduce this issue:

1. a cluster with 3 nodes of consul V1.4.4 (with -ui enabled).
2. we have about 20 java services registered in the cluster.
3. add a new node with consul V1.5 with -ui enabled.
4, open the ui of V1.5 and check the services list.(it displays  "500(The backend responded with an error)")
5, the UI of v1.4.4 still work well.

**Comment by mustafayildirim** [comment]
I've same issue but I run on Docker instance.

**Comment by tradel** [comment]
Hey @varnson. v1.5.0 added some new RPC's which were not present in previous versions. What's happening when you try to bring up the UI on the 1.5 node is that it's making RPC calls to the leader, which is still running 1.4, and the calls fail because the RPC method doesn't exist. 

Generally you shouldn't mix different Consul versions in a cluster, except temporarily during an upgrade. If you're in the middle of upgrading your cluster to 1.5, go ahead and finish, and then everything should work as expected.

**Comment by varnson** [comment]
@tradel OK, I see, thank you very much! I will close this issue.

**Comment by mustafayildirim** [comment]
It worked. Thanks

> Hey @varnson. v1.5.0 added some new RPC's which were not present in previous versions. What's happening when you try to bring up the UI on the 1.5 node is that it's making RPC calls to the leader, which is still running 1.4, and the calls fail because the RPC method doesn't exist.
> 
> Generally you shouldn't mix different Consul server versions in a cluster, except temporarily during an upgrade. If you're in the middle of upgrading your cluster to 1.5, go ahead and finish, and then everything should work as expected.
> 
> (Note that this applies specifically to Consul _servers_. It's fine for your Consul clients to be on an older version than the servers. In fact, it's recommended practice to upgrade the servers first, and then the clients.)

It worked. Thanks

**Comment by gamefundas** [comment]
In my case this is happening when the other datacenter is running a older consul cluster. Until 1.3 (didnt test 1.4) we didn't have any issue as both datacenters were able to see each and talk to each other using the WAN configuration. However it appears the most recent version of Consul server breaks this.

**Comment by mkeeler** [comment]
If you are using the UI on a Consul agent running 1.5.0 then all your servers that the UI needs to communicate with must be running v1.5.0 as well.

@gamefundas the simplest solution for you if you cannot upgrade the rest of the servers in your other dcs to 1.5.0 would be to run a client agent with the UI enabled using the 1.4.4 version and not enable the UI on your 1.5.0 instances. It will then perform the old behavior and not use the new RPC.
