### ISSUE TITLE
Long timeouts unintuitive behaviour

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#5834]
#### Overview of the Issue

Handling of timeouts in checks is counter-intuitive in Consul.

Consider this example:

```
Checks: [
 {
   "http": "http://localhost:80/healthz",
   "interval": "30s",
   "timeout": "30s"
  }
]
```
=> Will create a HTTP check with timeout of 10s

While:
```
Checks: [
 {
   "http": "http://localhost:80/healthz",
   "interval": "30s",
   "timeout": "29s"
  }
]
```
=> Will create a HTTP check with timeout of 29s

While I see the point of setting the timeout to interval at maximum, in that case, it should behave as an upper boudary.

I thus propose the following:

if timeout ≥ Interval => use Interval and display a Warning at registration time

**Comment by adams-sarah** [comment]
Closing this. Fix (https://github.com/hashicorp/consul/pull/6094) is in 1.6 release branch and will go out with the 1.6 release.
