### ISSUE TITLE
[ui] wrong node when clicking on service

### ISSUE THREAD

**Issue by scalp42** [hashicorp/consul#5853]
When clicking on a service, it always redirect to the same node.

I'm not sure if it's intended.

![consul](https://user-images.githubusercontent.com/1475276/57833047-fb229900-776d-11e9-9f11-d57ef5ee6f9d.gif)

**Comment by johncowen** [comment]
Thanks for the report @scalp42 (definitely not intended 😄 ), as always much appreciated! 

There's a fix coming for this (see above), and it also led to us spotting another similar bug elsewhere.

Thanks!

John
