### ISSUE TITLE
Best Practices to run in Production

### ISSUE THREAD

**Issue by leosabbir** [hashicorp/consul#5868]
Right now I am test phase. And I am running single instance of Consul as server to register services and then discover them.

Will only one instance be sufficient in production (probably not)? What are the practices to run multiple instances? Any reference to documentation?

**Comment by pearkes** [comment]
There are guides available here:

https://learn.hashicorp.com/consul/?track=datacenter-deploy#datacenter-deploy

This will walk you through all aspects of a production deployment of Consul.

**Comment by leosabbir** [comment]
Could provide little bit of explanation on necessity of multiple servers and separate clients?
