### ISSUE TITLE
Consul Server and Clients

### ISSUE THREAD

**Issue by leosabbir** [hashicorp/consul#5869]
The tutorials at https://learn.hashicorp.com/consul/?track=getting-started#getting-started

explains how to create cluster of consul servers and clients.

But does not explain why do we need them? Could someone explain the necessity of multi nodes servers and clients?

Why do we need separate servers and clients?

Also somewhere in the tutorial says "we have to run consul agent on every member of the cluster". Does it mean I have to run consul agent on every VM where my services are running?

**Comment by judithpatudith** [comment]
Hi @leosabbir, you can learn more about Consul's architecture by reading the [architecture documentation](https://www.consul.io/docs/internals/architecture.html). Judging by the last question you might also be interested in learning about our [consensus protocol](https://www.consul.io/docs/internals/consensus.html), Raft. That doc explains why you will want more than one server in production 🙂 

We usually use GitHub issues to report bugs and have a separate [mailing list for questions](https://groups.google.com/forum/#!forum/consul-tool). If you have any lingering questions after reading through the docs please feel free to ask them there. Hope this helps!
