### ISSUE TITLE
Improve unit test reliability

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/consul#588]
Audit tests for reliability.

* Use `testutil`'s wait methods to improve probably of time-sensitive tests passing.
* Fix any leader wait functions to ensure the `LastIndex` is > 0 before proceeding.

**Comment by tiwilliam** [comment]
:+1:

`TestHTTPAgentRegisterService` seem to be an reliability issue.

**Comment by ryanuber** [comment]
Thanks, @tiwilliam. I'll take a look at that.
Another note to self: This one has come up on occasion:

```
--- FAIL: TestAgentAntiEntropy_Check_DeferSync (0.49s)
	local_test.go:444: no update: &{Node 104 web web passing    }
```

**Comment by ryanuber** [comment]
TestHTTPAgentRegisterService should now be fixed, as well as TestAgentAntiEntropy and a few other various tests which were problematic.

One test I'm unsure of how to solve yet is this one:
```
--- FAIL: TestLeader_LeftServer-5 (11.11s)
	leader_test.go:327: should have 2 peers: [127.0.0.1:15370 127.0.0.1:15362 127.0.0.1:15366]
```

It rarely fails, but when it does, its failing for a solid 11s due to continued errors like:
```
2015/01/09 18:32:07 [DEBUG] raft: Failed to contact 127.0.0.1:15362 in 10.823062378s
```

**Comment by ryanuber** [comment]
I "fixed" this by wrapping a WaitForResult in a WaitForResult...

```
ok  	github.com/hashicorp/consul/consul	0.831s
ok  	github.com/hashicorp/consul/consul	0.621s
ok  	github.com/hashicorp/consul/consul	0.734s
ok  	github.com/hashicorp/consul/consul	0.624s
ok  	github.com/hashicorp/consul/consul	0.625s
ok  	github.com/hashicorp/consul/consul	22.444s
ok  	github.com/hashicorp/consul/consul	0.625s
```

You can definitely tell when it doesn't pass the first time, because it has to `WaitForResult` then `WaitForResult`, both failing, then the second time the outer `WaitForResult` finishes, it succeeds.

![](http://cdn.meme.am/instances/500x/57929148.jpg)

**Comment by ryanuber** [comment]
Actually, I moved the waitforresult out further to retry a broader set of checks in 2c9bb57. This passed reliably in much less time for the failure scenarios.

**Comment by ryanuber** [comment]
Test stability should be improved quite a bit now. One new (and rare) failure:

```
--- FAIL: TestACL_NonAuthority_Management (10.66s)
	acl_test.go:379: unexpected failed read
```

**Comment by ryanuber** [comment]
Recently, our success rate has suffered a bit. I am seeing logs like the following from Travis-CI and on my local machine. Seems related to #616.

```
$ make deps
--> Installing build dependencies
github.com/hashicorp/consul (download)
# cd /home/travis/gopath/src/github.com/hashicorp/consul; git symbolic-ref HEAD
fatal: ref HEAD is not a symbolic ref
/home/travis/gopath/src/github.com/hashicorp/consul on detached head; repairing
# cd /home/travis/gopath/src/github.com/hashicorp/consul; git checkout master
error: pathspec 'master' did not match any file(s) known to git.
package github.com/hashicorp/consul: exit status 1
github.com/armon/go-radix (download)
github.com/hashicorp/golang-lru (download)
github.com/hashicorp/hcl (download)
github.com/hashicorp/go-multierror (download)
github.com/armon/circbuf (download)
github.com/armon/go-metrics (download)
github.com/armon/gomdb (download)
github.com/hashicorp/go-msgpack (download)
github.com/hashicorp/memberlist (download)
github.com/hashicorp/raft (download)
github.com/hashicorp/raft-mdb (download)
github.com/hashicorp/serf (download)
github.com/laher/goxc (download)
github.com/hashicorp/yamux (download)
github.com/inconshreveable/muxado (download)
github.com/hashicorp/go-checkpoint (download)
github.com/hashicorp/go-syslog (download)
github.com/hashicorp/logutils (download)
github.com/miekg/dns (download)
github.com/mitchellh/cli (download)
github.com/mitchellh/mapstructure (download)
github.com/ryanuber/columnize (download)
make: *** [deps] Error 1
The command "make deps" failed and exited with 2 during .
Your build has been stopped.
```

**Comment by armon** [comment]
I've also had issues after #616. I wonder if we roll that back?

**Comment by ryanuber** [comment]
@armon I think so. I looked into Terraform to see what we were doing for tests and updating deps, and we aren't taking the same approach there. I t seems fair to get test errors if you try running the tests with outdated deps.

**Comment by armon** [comment]
Yeah it also makes it really slow to run the tests...

**Comment by ryanuber** [comment]
Just saw this failure on travis-ci. Haven't seen it anywhere else yet:
```
--- FAIL: TestDNS_ServiceLookup_CNAME (0.13s)
	dns_test.go:1224: Bad: &dns.Msg{MsgHdr:dns.MsgHdr{Id:0xd894, Response:true, Opcode:0, Authoritative:true, Truncated:false, RecursionDesired:true, RecursionAvailable:true, Zero:false, AuthenticatedData:false, CheckingDisabled:false, Rcode:0}, Compress:false, Question:[]dns.Question{dns.Question{Name:"search.service.consul.", Qtype:0xff, Qclass:0x1}}, Answer:[]dns.RR{(*dns.CNAME)(0xc208f5a4e0), (*dns.A)(0xc2082182c0)}, Ns:[]dns.RR{}, Extra:[]dns.RR{}}
```

**Comment by armon** [comment]
I think this has come a LONG way. Closing for now, we will fix the new ones one by one.
