### ISSUE TITLE
The consul connect envoy command with -grpc-addr has wrong documentation for default value

### ISSUE THREAD

**Issue by nitsh** [hashicorp/consul#5884]
#### Overview of the Issue

The documentation for `consul connect envoy` : https://www.consul.io/docs/commands/connect/envoy.html#grpc-addr-lt-addr-gt-

command with `-grpc-addr` says its default is `http://127.0.0.1:8502` but it fails with error saying grpc address has too many colons. 
It should be `127.0.0.1:8502` instead.

**Comment by i0rek** [comment]
Thanks for reporting @nitsh, would you like to submit a PR for that?

**Comment by nitsh** [comment]
@i0rek This is my first PR. Let me know if I missed something.

**Comment by pearkes** [comment]
Fixed in https://github.com/hashicorp/consul/pull/5886, thanks @nitsh!
