### ISSUE TITLE
ACL policy syntax validation error

### ISSUE THREAD

**Issue by nathanl79** [hashicorp/consul#5887]
#### Overview of the Issue

In consul v1.5.0, if an ACL token has the following policy attached to it with `acl = "write"` implemented using .hcl format, when using the `consul validate` command, it showed the error: `* 'acl' expected a map, got 'string'`. I verified that the syntax was indeed valid.  I also tried this in a few different environments with no luck.

If you ignore the consul validation error, update the policy with `acl= "write"` enabled, restart the agent, then run `consul snapshot agent`, it runs successfully without error.

An example of a management token based on the following policy should have valid syntax by adding the `acl = "write"`, for example:

```
acl = "write"

key_prefix "" {
   policy = "write"
}
service_prefix "" {
   policy = "write"
}
session_prefix "" {
   policy = "write"
}
node_prefix "" {
   policy = "write"
}
```

#### Reproduction Steps

1. Add acl= "write" parameter for snapshot-agent policy in .hcl format.
2. Run the `consul validate snapshot-agent-policy.hcl` command
3. Output of `consul validate` showed this error: `* 'acl' expected a map, got 'string'`.
4. Checked .hcl syntax for validation which passed. 
5. If you ignore the consul validation error, update the policy with `acl= "write"` enabled, restart the agent, then run `consul snapshot agent`, it runs successfully without error.

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 1d130f17
	version = 1.5.0+ent
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
license:
	customer = temporary
	expiration_time = 2019-05-22 17:58:33.393325917 +0000 UTC
	features = Automated Backups, Automated Upgrades, Enhanced Read Scalability, Network Segments, Redundancy Zone, Advanced Network Federation
	id = temporary
	install_id = *
	issue_time = 2019-05-22 17:28:33.393325917 +0000 UTC
	package = premium
	product = consul
	start_time = 2019-05-22 17:23:33.393325917 +0000 UTC
raft:
	applied_index = 17
	commit_index = 17
	fsm_pending = 0
	last_contact = 0
	last_log_index = 17
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:02260c72-87fa-663c-1039-990ea9bd13c5 Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 87
	max_procs = 2
	os = linux
	version = go1.12.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1``
```
</details>

### Operating system and Environment details

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch.

### Log Fragments

```
Config validation failed: Error parsing snapshot-agent-policy.hcl: 1 error(s) decoding:

* 'acl' expected a map, got 'string'
```

**Comment by mkeeler** [comment]
@nathanl79 The `consul validate` command is used to validate Consul's configuration files and not ACL policies. They are both HCL but the config file validation is expecting something like:

```
acl {
  enabled = true
  tokens {
      master = "af4dfd2e-1952-4c27-9ab9-1ad2aa24ef0a"
  }
}
```

Maybe it would be useful for us to add a new subcommand under `consul acl` to validate the rules syntax?

**Comment by nathanl79** [comment]
Thank you for clarifying this @mkeeler! I think it would be useful to add a new subcommand under `consul acl` to validate the rules syntax.

I'll got ahead and close out this issue.
