### ISSUE TITLE
C++ client contribution

### ISSUE THREAD

**Issue by NickYang1988** [hashicorp/consul#5902]
Hi,

Thanks for the awesome consul works first.

I use consul as a service discovery center recently, but I cannot find a simple and easy C++ client. So I write a new one with a single header file and test file.

Could I contribute this project as the official C++ SDK?

Here is the URL: https://github.com/ArkNX/consulpp

If the official stuff has any questions, please contact me.

Forward your reply.

**Comment by pearkes** [comment]
Please do contribute a PR for this! The page is here:

https://github.com/hashicorp/consul/blob/master/website/source/downloads_tools.html.erb
