### ISSUE TITLE
invalid config key acl.enable_key_list (v1.5.1)

### ISSUE THREAD

**Issue by phosphre** [hashicorp/consul#5906]
#### Overview of the Issue

At the time of this writing (where v1.5.1 is the latest Consul version), [the docs say](https://www.consul.io/docs/agent/options.html#acl_enable_key_list):

enable_key_list - Either "enabled" or "disabled", **defaults to "disabled"**. When enabled, the list permission will be required on the prefix being recursively read from the KV store. Regardless of being enabled, the full set of KV entries under the prefix will be filtered to remove any entries that the request's ACL token does not grant at least read permissions. This option is only available in Consul 1.0 and newer.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. I added this line to the consul.hcl server config file:

```
acl = {
  enable_key_list           = "disabled",
...
```

1. I run 

`/usr/local/bin/consul agent -config-dir=/etc/consul.d/ -log-level=TRACE`

as root, I get:

```
==> Error parsing /etc/consul.d/consul.hcl: 1 error occurred:
	* invalid config key acl.enable_key_list
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
NA: Server agents tested only
```

</details>

<details>
  <summary>Server info</summary>

```
Agent doesn't start.
```

</details>

### Operating system and Environment details

This is on a packer-built, stripped-down macOS virtualbox vagrant-supplied centos7 3.10.0-957.12.2.el7.x86_64 kernel.

### Log Fragments

See above.

**Comment by mkeeler** [comment]
It appears that the documentation isn't quite right. The correct config is `enable_key_list_policy`.

I am going to leave this issue open to track an update to the docs.
