### ISSUE TITLE
Consul Connect: Proxy to route by name?

### ISSUE THREAD

**Issue by aclowkey** [hashicorp/consul#5915]
Let's say for example, I have 2 services: API, ElasticSearch. The way to connect them is to: install client on each node, and a proxy. Then, when API wants to talk to ElasticSearch, it will connect to localhost:9200, which will reach the proxy, then routed to ElasticSearch.

Now let's say I don't want to know port numbers, I just want to access elasticsearch.service.consul, but through the proxy, is this possible?

What is the best approach to this? If my API has 10,000 upstream microservices, does it need to remember 10,000 different ports?

Also, do I have to define upstream for each service? This becomes a problem if I have many many ,and they're constantly changing. Doesn't it beat the service discovery purpose?

**Comment by jonathanbeber** [comment]
That's a good issue. I had the same feeling when starting with connect. 

On the [roadmap preview](https://www.hashicorp.com/blog/roadmap-preview-what-s-next-for-consul-service-mesh) blog post, they said that:

> the data plane exposes upstream services to your application via local ports. A new feature of Consul introduces the ability for advanced layer 7 routing; traffic can be routed to different upstream services based on Path or HTTP header.

and more:

> While a 1-1 relationship between a local port and upstream service is fine for many purposes, the capability for HTTP routing makes it easy to build aggregated services such as API gateways or to replace centralized load balancers with a smarter decentralized approach.

I really believe that's on the roadmap.

Maybe this issue is good to discuss the fact Connect has a lot of expectations on it and I didn't find an easy way to have access to its design document. Include on the documentation, a design document for the product would help to address this kind of questions.

**Comment by vilva42** [comment]
I like the approach of Traefik/Fabio in regards to this. I just hit localhost:9200/<service> and they route traffic to consul services. I do not know the reasoning behind why multiple ports are needed for each upstream connection but from an operations standpoint, it is too much config to be maintained.

**Comment by wbertelsen** [comment]
+1 to this. In our self-configured envoy mesh, we use the [cluster_header](https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/api/v2/route/route.proto.html?highlight=cluster_header#envoy-api-field-route-routeaction-cluster-header) routing rule supported by envoy to route dynamically based on a header. It would be nice if connect also supported this


```yaml
virtual_hosts:
  - name: cloud_service
    domains: ["*"]
    routes:
    - match: { prefix: "/" }
      route: { cluster_header: service-name } # This routes to remote clusters named by the svc-name header
```

**Comment by chrisboulton** [comment]
You should be able to do this today, assuming I understand -- it's similar to a use case that we have for Connect.

When you configure your proxy sidecar, configure it with a single upstream, say `http-out`:

```
"connect": {
  "sidecar_service": {
    "proxy": {
      "upstreams": [
        {
          "destination_name": "http-out",
          "local_bind_port": 4140
        }
      ]
    }
  }
}
```

Create a service-defaults for `http-out`:

```
kind = "service-defaults"
name = "http-out"
protocol = "http"
```

Create a service-resolver that maps to concrete services: (this example uses `:authority`/`Host` headers):

```
kind = "service-router"
name = "http-out"
routes = [
  {
    match {
      http {
        header = [
          {
            name = ":authority"
            exact = "backend-service-1"
          }
        ]
      }
    }

    destination {
      service = "backend-service-1"
    }
  },
  {
    match {
      http {
        header = [
          {
            name = ":authority"
            exact = "backend-service-2"
          }
        ]
      }
    }

    destination {
      service = "backend-service-2"
    }
  },
]
```

Update the `service-router` when you add new services. (it would be nice to be able to capture groups or values and use them, but that doesn't seem to be supported today)

**Comment by uc-dang-tiki** [comment]
I encounter this problem when I try to use consul connect. Hope Consul team could fix it soon.

**Comment by blake** [comment]
Consul 1.10 introduced support for transparent proxy on Kubernetes (support for additional runtimes will be added in the future). This allows downstream applications to utilize the KubeDNS hostname when connecting to upstream services through the proxy, and eliminates the need to manually declare upstreams in the local proxy config. See https://www.consul.io/docs/connect/transparent-proxy for more details.
