### ISSUE TITLE
Vendor directory causes type mismatch

### ISSUE THREAD

**Issue by asim** [hashicorp/consul#5937]
The recent commit of the vendor directoy causes a type mismatch in our use of the consul api.

```
go-micro/registry/consul/watcher.go:48:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
go-micro/registry/consul/watcher.go:213:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
```

Is it possible to correct the referencing for this?

**Comment by mkeeler** [comment]
Definitely. I am not at my laptop at the moment to PR this but it should only require running `make update-vendor` as that will remove consul from the vendor dir

**Comment by Rochfort** [comment]
Can I ask you to commit with `make update-vendor` command because it breaks all the builds in CI?

**Comment by mkeeler** [comment]
It will be done hopefully in the next half hour or so
