### ISSUE TITLE
How could I create cluster on one machine? How to config?

### ISSUE THREAD

**Issue by laball** [hashicorp/consul#5938]
Is Consul support create cluster on one machine ? How should I config?
Is it possible?
I know you don't do that in a production environment.
It is for study or development environment.
So what should I do?

**Comment by dineshba** [comment]
For development purpose, we can use `consul agent -dev` which will create a single node consul cluster. 
Hope this helps!

**Comment by kaitlincarter-hc** [comment]
Hi @laball, 
Using `consul agent -dev` is great for quick testing! However, if you really need a small cluster you could use [Vagrant](https://learn.hashicorp.com/consul/getting-started/join) or [Docker](https://hub.docker.com/_/consul) to create small local clusters. 
-Kait

**Comment by laball** [comment]
@dineshba @kaitlincarter-hc Thinks.
