### ISSUE TITLE
Misleading clipboard copy success message

### ISSUE THREAD

**Issue by leoj3n** [hashicorp/consul#5953]
<img width="1372" alt="Screen Shot 2019-06-11 at 9 09 27 PM" src="https://user-images.githubusercontent.com/990216/59319432-3f7f5700-8c90-11e9-8828-c86c6a17a8fa.png">

**Comment by johncowen** [comment]
Fixed in 1.5.2 by https://github.com/hashicorp/consul/pull/5958
