### ISSUE TITLE
consul agent node meta can be override by catalog api

### ISSUE THREAD

**Issue by lf1029698952** [hashicorp/consul#5955]
#### Feature Description

consul agent node meta can be override by catalog api, 
https://www.consul.io/api/catalog.html#register-entity

When I set SkipNodeUpdate=false, but will be agent Synced node info return to the original.
#### Use Case(s)

We use consul cluster for kubernetes pods service discovery, consul agent as a sidecar to pods, As shown in the following figure.
![image](https://user-images.githubusercontent.com/11751263/59835660-ac73aa80-937c-11e9-92d0-dd898df9e3ba.png)

We define many nginx attribute in consul node meta:
```
"NodeMeta": {
    "check_domain": "www.xxx.com",
    "check_fall": "2",
    "check_interval": "10000",
    "check_mode": "http",
    "check_rise": "3",
    "check_timeout": "1500",
    "check_url": "/healthcheck",
    "env": "test",
    "load_balancer": "round_robin",
    "upstream": "projectname_region_env",
    "status": "up",
    "weight": "10"
  },
```

I want to modify node meta attribute by consul catalog api, 
to reload nginx upstream conf and not modify pod consul agent.

We try to use enable_tag_override to modify tag by catalog api, but service tag can't support map k-v struct.

Feature:
* node meta support to  be override by catalog api
* or service tag support map k-v struct.

I wonder if my usage is correct. Please correct me.
Thanks！

**Comment by IYism** [comment]
I also encountered a similar problem.

**Comment by lf1029698952** [comment]
anyone have the same situation as us, could you give me some suggestions? Thanks.

**Comment by haoflynet** [comment]
+1

**Comment by zhouyuanyuana** [comment]
We have faced this issue, wish the feature can be support asap,tks!
