### ISSUE TITLE
ETA for 0.5 release?

### ISSUE THREAD

**Issue by pikeas** [hashicorp/consul#596]
It's been almost 3 months since the last release. Is master stable and safe enough to run directly? If not, is there a timeline for the next release?

**Comment by ryanuber** [comment]
Hi @pikeas, 0.5 is only a short way out! We plan to have a release within the month, barring any major issues. The master branch should be pretty stable at this point, but there are a few additional features in the coming weeks which should be getting merged in. Consul 0.5 is going to be a fairly large release, and will bring lots of new functionality, so bear with us while we make sure the release is ready. Hang in there!

**Comment by pikeas** [comment]
Thanks for the reply, Ryan! Any chance the CHANGELOG could see an update prior to release? Some (all?) of the docs on Github have already been updated, but it's hard to determine what's new/fixed/better without combing through commits.

**Comment by ryanuber** [comment]
@pikeas it's a safe bet that the CHANGELOG will get some lovin' pretty shortly. We typically bulk-update it as part of release preparation for Consul.
