### ISSUE TITLE
http service health check marked failing erroneously

### ISSUE THREAD

**Issue by southwel** [hashicorp/consul#5963]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A service and (http)health check registered via REST API `v1/agent/service/register` is marked failing / critical(red), but tcpdump check of network traffic shows that the service endpoint returns 200 to consul server agent initiated health check http request.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 4 server nodes and https load balancer providing access to port 8500 on server nodes to expose the http api.  I don't think the number of server nodes really matters, it just needs to be a functional server cluster that can be accessed via an https load balancer.  I used consul 1.5.1 release.  I'm using GCP to host the server instances and also for the https load balancer.

I've used tcpdump and verified the traffic is flowing between servers and that the service is returning 200 to health check request from consul.

I've noticed that sometimes when I register this same service it works as expected, but ~75% of the time it does not.  In both cases I see no difference between the check as seen in /opt/consul/checks.

2. Register a service as such:

/usr/local/bin/curl -v -H 'X-Consul-Token: aaaaaa-aaaa-aaaa-aaaa-aaaaaaa' -H 'Content-Type: application/json' --request PUT -d '{
  "ID": "83302490-3414-4bfa-8930-eb8e88832501",
  "Name": "test_service",
  "Tags": [
    "test_service"
  ],
  "Address": "ec2-1.1.1.1.compute-1.amazonaws.com",
  "Port": 9191,
  "EnableTagOverride": false,
  "Check": {
    "DeregisterCriticalServiceAfter": "60s",
    "HTTP": "http:\/\/ec1.1.1.1.compute-1.amazonaws.com:9911\/metrics",
    "Interval": "2s"
  },
  "Weights": {
    "Passing": 10,
    "Warning": 1
  }
}' https://my.consulserver.com/v1/agent/service/register

3. View error

### Consul info for both Client and Server

client is curl (newest version, or older versions, I've tried both)
server is 1.5.1

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 40cec984
	version = 1.5.1
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.128.5.241:8300
	server = true
raft:
	applied_index = 83722
	commit_index = 83722
	fsm_pending = 0
	last_contact = 12.643412ms
	last_log_index = 83722
	last_log_term = 123
	last_snapshot_index = 81928
	last_snapshot_term = 110
	latest_configuration = [{Suffrage:Voter ID:280b468a-9fdf-0ea6-f0d8-f04418a9f8e2 Address:10.128.5.241:8300} {Suffrage:Voter ID:81de271f-fbd1-f5cb-f91f-1bd6156a4fe4 Address:10.128.5.174:8300} {Suffrage:Voter ID:a87778d6-a9b8-adfe-87f1-1edaffd98078 Address:10.128.5.245:8300} {Suffrage:Voter ID:b1fe31c1-ebf7-cf10-dd51-45cc2bd63424 Address:10.128.4.182:8300}]
	latest_configuration_index = 82863
	num_peers = 3
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 123
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 110
	max_procs = 2
	os = linux
	version = go1.12.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 41
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 487
	members = 8
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 150
	members = 5
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Linux consul-server-aaa 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by pierresouchay** [comment]
In theory, before being scheduled, the service check is supposed to be critical by default unless you specify its state. Which means, at least during 2s, it should be critical. Could it be what you observe? Does the check flaps sometimes?
