### ISSUE TITLE
Consul DNS: HAProxy `server-template` not considering all service IPs

### ISSUE THREAD

**Issue by Gurpartap** [hashicorp/consul#5968]
#### Overview of the Issue

A [recent Hashicorp webinar](https://www.hashicorp.com/resources/load-balancing-strategies-with-nginx-haproxy-and-consul) by @cpu601 included [example usage of HAProxy (`server-template`)](https://github.com/cpu601/consul-lb-templates/blob/master/haproxy-native-integration/haproxy.cfg) for specifying backend servers using consul DNS.

When I run, say, **5 dynamic-port instances of myrpcapp service on 4 client nodes** (whereby 2 of these myrpcapp instances would be on the same machine with the same ip address but different ports), HAProxy appears to only be picking up 4 of the client ip addresses from consul's DNS response (corresponding to the set of unique ip addresses returned by dns).

Best practices aside, do all the services need to be running on unique client nodes (or ip addresses) for them to be returned in whatever DNS query haproxy uses? If so, this would hamper canary deployments, which won't be receiving traffic from this load balancing strategy, unless we're running an equal number of surplus set of client nodes just for this purpose.

None of this would be a problem when using consul template for backend propagation, as we'll be able to repeat the ip addresses, each with a different port. However, this method incurs a lot of undesirable config reload churn during deployments.

#### Reproduction Steps

1. The `server-template` directive in [webinar's haproxy example](https://github.com/cpu601/consul-lb-templates/blob/master/haproxy-native-integration/haproxy.cfg) requires an expected servers count to be set
1. As in the webinar example, I set this to *expect up to 10 servers max* for my backend:
```
server-template myrpcapp_srv 10 _myrpcapp._tcp.service.consul resolvers consul resolve-prefer ipv4 check
```
1. My test cluster has *4 client nodes* (consul+nomad).
1. I used nomad to deploy *5 service instances* of myrpcapp, each with its own dynamic port.
1. HAProxy seems to only be considering up to 4 instances of this service, rather than 5. In haproxy's stats dashboard, 4 of them show as UP and 6 as DOWN.
1. From what I read on https://www.haproxy.com/blog/dns-service-discovery-haproxy/ and https://www.haproxy.com/blog/haproxy-and-consul-with-dns-for-service-discovery/ , HAProxy is able to handle 100s of servers using this method, as long as they fit in 8K of DNS response.

My haproxy is configured to handle this:
```
resolvers consul
  nameserver consul 127.0.0.1:8600
  accepted_payload_size 8192
  hold valid 1s
```
So is consul:
```
"dns_config": {
  "enable_truncate": true,
  "udp_answer_limit": "100 <- seems to have no effect"
}
```

#### Other findings
* As expected, `dig +short SRV myrpcapp.service.consul` gives 5 consul nodes (2 of them being repeated and with different ports).
* However, `dig +short myrpcapp.service.consul` gives 4 distinct ip addresses.

HAProxy probably should be querying for [SRV records](https://www.haproxy.com/blog/dns-service-discovery-haproxy/), but perhaps it doesn't (?). How can I determine if this is or isn't a consul caused behaviour.

#### Consul client config:
```json
{
    "advertise_addr": "10.120.101.8",
    "autopilot": {
        "cleanup_dead_servers": true,
        "disable_upgrade_migration": false,
        "last_contact_threshold": "200ms",
        "max_trailing_logs": 250,
        "redundancy_zone_tag": "az",
        "server_stabilization_time": "10s",
        "upgrade_version_tag": ""
    },
    "bind_addr": "10.120.101.8",
    "client_addr": "0.0.0.0",
    "data_dir": "/opt/consul/data",
    "datacenter": "dc1",
    "disable_remote_exec": true,
    "dns_config": {
        "enable_truncate": true
    },
    "domain": "consul",
    "enable_script_checks": false,
    "encrypt": "<key>",
    "encrypt_verify_incoming": true,
    "encrypt_verify_outgoing": true,
    "log_level": "INFO",
    "node_name": "pool1-node4",
    "recursors": [
        "8.8.8.8",
        "8.8.4.4"
    ],
    "retry_join": [
        "10.120.101.21",
        "10.120.101.22",
        "10.120.101.23"
    ]
}
```

#### HAProxy config (deployed as nomad system job)
```conf
global
  log stdout local0
  spread-checks 5


defaults
  log global
  maxconn 3333
  timeout check 5s
  option abortonclose
  option httplog
  option logasap


resolvers consul
  nameserver consul 127.0.0.1:8600
  accepted_payload_size 8192
  hold valid 1s


listen stats
  bind {{env "NOMAD_ADDR_stats"}}
  mode http
  stats enable
  stats uri /haproxy/stats
  stats refresh 5s


frontend myrpcapp_frontend
  bind {{env "NOMAD_ADDR_myrpcapp"}} ssl  crt /usr/local/etc/haproxy/myrpcapp.pem  alpn h2
  mode tcp
  option tcplog

  tcp-request inspect-delay 5s
  tcp-request content accept if { req.ssl_hello_type 1 }

  default_backend myrpcapp_backend


backend myrpcapp_backend
  mode tcp
  balance roundrobin

  server-template myrpcapp_srv 10 _myrpcapp._tcp.service.consul resolvers consul resolve-prefer ipv4 check
```

**Comment by pierresouchay** [comment]
`dig +short SRV myrpcapp.service.consul +bufsize=8192`

if you want more than your MTU, you might also use +tcp

**Comment by Gurpartap** [comment]
> `dig +short SRV myrpcapp.service.consul +bufsize=8192`

I suppose the `accepted_payload_size 8192` in config would make haproxy do something like that. Regardless, it's only 4 or 5 servers we're playing with… so perhaps we don't even need this adjustment.

**Comment by pierresouchay** [comment]
You can put bufsize up to 65535, but in this case, due to mtu limitations (most probably) you'll need tcp.
According to my tests, that's around  4-500 servers (depends on compression) see https://github.com/hashicorp/consul/issues/4071#issuecomment-389764834 and relevant PRs for more information

**Comment by Gurpartap** [comment]
In my case, either consul or haproxy, with its [server-template feature](http://cbonte.github.io/haproxy-dconv/1.9/configuration.html#4.2-server-template), is running some kind of distinct() filter on the returned ip addresses.

Either that, or perhaps haproxy is running the wrong dns query command. I don't think I'm constrained by response size here. Am I?

This `server-template` integration was mentioned in detail in a recent Hashicorp webinar by @cpu601. However, it would not be of much practical use if it cannot support multiple instances of a service listening on the same IP address.

**Comment by Gurpartap** [comment]
ok. it was, apparently, haproxy which was skipping on duplicate ip addresses coming in from its consul dns resolving, and it has an option to not do that!

[`resolve-opts allow-dup-ip`](http://cbonte.github.io/haproxy-dconv/1.9/configuration.html#5.2-resolve-opts)

here's how I used it in my haproxy config:
```
server-template myrpcapp_srv 10 _myrpcapp._tcp.service.consul  resolvers consul  resolve-opts allow-dup-ip  resolve-prefer ipv4  check
```

this might be a useful addition to the webinar example repo, since it's a fairly common use case to have multiple instances of a service listening on the same ip.

**Comment by pierresouchay** [comment]
As a side note, you might try consul-templaterb as well (my own promo) : https://github.com/criteo/consul-templaterb/blob/master/samples/haproxy_dns.cfg.erb

**Comment by cpu601** [comment]
Hey @Gurpartap ,

thanks for following up, highlighting this and pointing to the resolution!

> ok. it was, [apparently](https://github.com/haproxy/haproxy/blob/86eded6c69516f579427533c6dcca07c38dc87ac/src/server.c#L4009-L4011), haproxy which was skipping on duplicate ip addresses coming in from its consul dns resolving, and it has an option to not do that!
> 
> [`resolve-opts allow-dup-ip`](http://cbonte.github.io/haproxy-dconv/1.9/configuration.html#5.2-resolve-opts)
> 
> here's how I used it in my haproxy config:
> 
> ```
> server-template myrpcapp_srv 10 _myrpcapp._tcp.service.consul  resolvers consul  resolve-opts allow-dup-ip  resolve-prefer ipv4  check
> ```
> 
> this might be a useful addition to the webinar example repo, since it's a fairly common use case to have multiple instances of a service listening on the same ip.
> 

While preparing for the mentioned webinar, I did not test this case and therefore did not run into this issue...

I will definitely mention this in the example repo and follow-ups!

As this issue is resolved and more related to HAProxy, than Consul itself, I would suggest closing it.

Happy to follow up offline with you @Gurpartap and @pierresouchay !

**Comment by Gurpartap** [comment]
@cpu601: Thank you for the video, and merging the example suggestion! Couldn't have found haproxy server-template without your contribution.

If it interests anyone, the community could use more suggestions/resources/stories around various load balancers, their specialities, limitations, consul config integrations, etc.
