### ISSUE TITLE
 [ERR] dns: recurse failed: read udp 192.168.137.128:42529->192.168.137.128:53: i/o timeout

### ISSUE THREAD

**Issue by yiwenshuo** [hashicorp/consul#5983]
The consul server parameter file is :
----------------------------------

{
    "addresses": {
        "http": "0.0.0.0",
        "dns": "0.0.0.0"
    },
    "bind_addr": "0.0.0.0",
    "advertise_addr": "192.168.137.128",
    "bootstrap_expect": 1,
    "datacenter": "yn",
    "data_dir": "/server/consul/data",
    "dns_config": {
        "allow_stale": false,
        "max_stale": "87600h",
        "node_ttl": "0s",
        "service_ttl": {
            "*": "0s"
        }
    },
    "domain": "yws",
    "enable_syslog": false,
    "leave_on_terminate": false,
    "log_level": "info",
    "node_name": "ywsconsulserver2",
    "node_meta": {
        "location": "B1 in test"
    },
    "performance": {
        "raft_multiplier": 1
    },
    "ports": {
        "http": 8500,
        "dns": 53
    },
    "reconnect_timeout": "72h",
    "recursors": [
    "192.168.137.128"
    ],
    "retry_join": [
    "192.168.137.128"
    ],
    "retry_interval": "10s",
    "server": true,
    "skip_leave_on_interrupt": true,
    "ui": true
}
----------------------------------

When I start the consul after minutes later, I got so many errors in the consul.log,the content is ：

----------------------------------
 2019/06/18 17:08:03 [ERR] dns: recurse failed: read udp 192.168.137.128:42529->192.168.137.128:53: i/o timeout
    2019/06/18 17:08:03 [ERR] dns: all resolvers failed for {pool.ntp.org. 1 1} from client 192.168.137.128:35645 (udp)
    2019/06/18 17:08:03 [ERR] dns: recurse failed: read udp 192.168.137.128:58414->192.168.137.128:53: i/o timeout
    2019/06/18 17:08:03 [ERR] dns: all resolvers failed for {pool.ntp.org. 28 1} from client 192.168.137.130:36721 (udp)
    2019/06/18 17:08:03 [ERR] dns: recurse failed: read udp 192.168.137.128:52679->192.168.137.128:53: i/o timeout
    2019/06/18 17:08:03 [ERR] dns: all resolvers failed for {pool.ntp.org. 1 1} from client 192.168.137.130:36721 (udp)
    2019/06/18 17:08:03 [ERR] dns: recurse failed: read udp 192.168.137.128:35371->192.168.137.128:53: i/o timeout
    2019/06/18 17:08:03 [ERR] dns: all resolvers failed for {pool.ntp.org. 1 1} from client 192.168.137.128:52679 (udp)
    2019/06/18 17:08:03 [ERR] dns: recurse failed: read udp 192.168.137.128:40012->192.168.137.128:53: i/o timeout
    2019/06/18 17:08:03 [ERR] dns: all resolvers failed for {pool.ntp.org. 28 1} from client 192.168.137.128:58414 (udp)

----------------------------------

But I can telnet by : telnet 192.168.137.128  53, the result return ok.

**Comment by pearkes** [comment]
This error message and an approach to resolving it is described here: https://www.consul.io/docs/common-errors.html

Hopefully that helps!
