### ISSUE TITLE
Internal UI Services endpoint does not unblock when it should

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#5988]
#### Overview of the Issue

curling the internal/ui/services endpoint with a specific index does not unblock when new services get added.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Start a consul agent: `consul agent -dev`
1. Run `curl localhost:8500/v1/internal/ui/services`
1. Rerun with the index: `curl localhost:8500/v1/internal/ui/services?index=9`
1. While the previous command is blocking run: `consul services register -name foo -port 80`

It doesn't unblock the internal/ui/services request.

**Comment by rboyer** [comment]
@mkeeler I can reproduce against `1.5.x`, but not against `1.6.x` or `master`. I guess this got fixed in 1.6.0.
