### ISSUE TITLE
Docs: Node Coordinates Unclear / has Typo

### ISSUE THREAD

**Issue by cwillhelm** [hashicorp/consul#6014]
#### Feature Description
There is a minor typo in the `godoc` under this section:

```
func (*Coordinate) Node

func (c *Coordinate) Node(node string, q *QueryOptions) ([]*CoordinateEntry, *QueryMeta, error)

Node is used to return the coordinates of a single in the LAN pool.
```

I think it's supposed to be:

Node is used to return the coordinates of a single _**NODE**_ in the LAN pool.

While this may seem like a minor issue, I think it's always worth improving upon documentation wherever possible, plus I feel like it adds a bit of clarity because if you're reading that for the first time, you'll question yourself.... "return the coordinates of a single what?"

#### Use Case(s)

Improve user experience and documentation readability.

**Comment by pearkes** [comment]
Thanks your suggestion looks right. If you want to PR feel free, otherwise someone will get to this!
