### ISSUE TITLE
Some TTL checks will be Missed randomly and response from consul will be slow when the number of "TTL checks" is above 800 for a client node

### ISSUE THREAD

**Issue by w281015308** [hashicorp/consul#6016]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I found that some TTL checks will be Missed randomly and response from consul will be slow when the number of "TTL checks" is above 800 for a client node

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. start above 800 service instance and update their check state to consul via http 
2. when the number of TTL checks just beyond 800 and then some instances will missed TTL and
register a new service instance will be slow via http

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details
Environment : linux docker  8G , 4core
3 server nodes
2 client nodes
800+  service instances

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by w281015308** [comment]
![6E8896F7-2F6C-4dd9-81CF-545774324E59](https://user-images.githubusercontent.com/11220995/60155154-f563ad00-981b-11e9-9107-b45384b807fa.png)
 below is information from client node console windows

**Comment by pierresouchay** [comment]
TTL requires a round trip with a write on server each time AFAIK, so your server might be too loaded.

From our experience, agent start having issues with sync with more than 500+ checks per agent...

The 800+ services instances are for different service(s) (I mean do you have 800 different services) or a just a few services ? (And in that case, how many instances do you have max per service?)

**Comment by w281015308** [comment]
> TTL requires a round trip with a write on server each time AFAIK, so your server might be too loaded.
> 
> From our experience, agent start having issues with sync with more than 500+ checks per agent...
> 
> The 800+ services instances are for different service(s) (I mean do you have 800 different services) or a just a few services ? (And in that case, how many instances do you have max per service?)

hi Pierres, we have 800 different service instances and around 40+ instances for each service and we don't use service mesh mode. I want to know why having issues for check TLL with more than 800 checks per agent . 800 is fine.  The issue agent can not resume after restart . i guess consul have max threads limit or other reasons?   Could you explain why encounter this for me?
