### ISSUE TITLE
Provider recursor as CLI flag

### ISSUE THREAD

**Issue by NoumanSaleem** [hashicorp/consul#602]
http://www.consul.io/docs/agent/options.html#recursor
Would be great if this was available as a cli flag for running with docker

**Comment by armon** [comment]
Tagged for enhacement

**Comment by florentvaldelievre** [comment]
Could you please advise if it has been released within <a href="https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip">0.5.0</a> ? 
I can only see it within the master branch

Thank you

**Comment by ryanuber** [comment]
@florentvaldelievre unfortunately this barely missed the 0.5.0 release. There will be a 0.5.1 release in the next couple of weeks which will include this fix.
