### ISSUE TITLE
Add script/command information to the healthcheck API endpoint

### ISSUE THREAD

**Issue by johncowen** [hashicorp/consul#6039]
#### Feature Description

Add more information to the healthcheck API endpoint, such as the command being called, the URL being used etc.

Put this behind an service:write ACL (not service:read) or similar.

#### Use Case(s)

Make it easier for consul operators to debug why a healthcheck could be failing either via the UI or other means.

**Comment by crhino** [comment]
Closing this in favor of #1680, it has the most 👍 's.
