### ISSUE TITLE
How to automatically replace a server that fails, no manual intervention

### ISSUE THREAD

**Issue by petemounce** [hashicorp/consul#605]
I have a 3 server cluster in AWS, managed by a 3/3/3 ASG.

I start the servers with `-bootstrap-expect 3` via an upstart job. How should I handle the case where an instance dies unexpectedly? As in, without manual intervention?

Should I have logic in the upstart job that only adds the -bootstrap-expect flag if the instance is a replacement for a failed instance? I guess I could detect that by querying the launch-time of the instances in the cluster, and if the existing instances are older by, say, an hour or more, assume the current instance is a new one and it shouldn't be bootstrapping?

Or, should I start the servers _without_ `-bootstrap-expect`, and instead issue `consul info` queries to other servers to peek to see whether there's a bootstrapped cluster?

I found [auto-consul](https://github.com/ethanrowe/auto-consul) but have not yet done more than glance at it. (cc @ethanrowe for interest).

One upstart job to run consul like 
```
description "Consul agent"

start on runlevel [2345]
stop on runlevel [!2345]

respawn

script
  # Make sure to use all our CPUs, because Consul can block a scheduler thread
  export GOMAXPROCS=`nproc`

  # Get the public IP
  BIND=`ifconfig eth0 | grep "inet addr" | awk '{ print substr($2,6) }'`

  export CLUSTER_SIZE=$(aws autoscaling describe-auto-scaling-groups | jq -c -M -r '.AutoScalingGroups[] | {name: .AutoScalingGroupName, desired_capacity: .DesiredCapacity}' | grep je-consul-qa13-all.*ConsulCluster | jq -c -M -r '.desired_capacity' | tr -d "\n")
  exec /usr/local/bin/consul agent \
    -bootstrap-expect $CLUSTER_SIZE \
    -config-dir="/etc/consul.d" \
    -bind=$BIND \
    >>/var/log/consul.log 2>&1
end script
```

and one upstart job to join the other servers in the cluster:

```
description "Join the consul cluster"

start on started consul
stop on stopped consul

task

script
  # Keep trying to join until it succeeds
  set +e
  while :; do
    export CONSUL_JOIN=$(aws ec2 describe-instances --query 'Reservations[].Instances[].{PrivateIpAddress:PrivateIpAddress}' --filters 'Name=tag:Name,Values=qa13 - consul - all' 'Name=instance-state-name,Values=running' --output text | tr "\n" " ")
    logger -t "consul-join" "Attempting join: ${CONSUL_JOIN}"
    /usr/local/bin/consul join \
      ${CONSUL_JOIN} \
      >>/var/log/consul-join.log 2>&1
    [ $? -eq 0 ] && break
    sleep 5
  done

  logger -t "consul-join" "Join success!"
end script
```

and a consul.json like:

```
{
  "server": true,
  "rejoin_after_leave": true,
  "enable_syslog": true,
  "syslog_facility": "local5",
  "data_dir": "/var/consul/data",
  "ui_dir": "/var/consul/ui",
  "addresses": {
    "http": "<some address>"
  },
  "datacenter": "eu-west-1",
  "statsd_addr": "<some address>",
  "recursor": "<some address>"
}
```

I also have an upstart job to set an EC2 tag on the server instances once the output of `consul info` locally shows `bootstrap = false`. I hope that's the best thing to use to indicate that a cluster has been bootstrapped...?

**Comment by petemounce** [comment]
I should have included some sample logs (IPs obfuscated):
```
2015/01/15 11:08:46 [WARN] raft: Election timeout reached, restarting election
2015/01/15 11:08:46 [INFO] raft: Node at 10.432.1.89:8300 [Candidate] entering Candidate state
2015/01/15 11:08:47 [INFO] raft: Node at 10.432.1.89:8300 [Follower] entering Follower state
2015/01/15 11:08:47 [ERR] raft: Failed to make RequestVote RPC to 10.432.0.22:8300: dial tcp 10.432.0.22:8300: i/o timeout
2015/01/15 11:08:48 [ERR] raft: Failed to make RequestVote RPC to 10.432.0.22:8300: dial tcp 10.432.0.22:8300: i/o timeout
2015/01/15 11:08:48 [WARN] raft: Heartbeat timeout reached, starting election
2015/01/15 11:08:48 [INFO] raft: Node at 10.432.1.89:8300 [Candidate] entering Candidate state
2015/01/15 11:08:49 [INFO] raft: Duplicate RequestVote for same term: 41225
2015/01/15 11:08:49 [ERR] raft: Failed to make RequestVote RPC to 10.432.1.201:8300: dial tcp 10.432.1.201:8300: no route to host
2015/01/15 11:08:49 [ERR] raft: Failed to make RequestVote RPC to 10.432.1.201:8300: dial tcp 10.432.1.201:8300: no route to host
2015/01/15 11:08:50 [WARN] raft: Election timeout reached, restarting election
2015/01/15 11:08:50 [INFO] raft: Node at 10.432.1.89:8300 [Candidate] entering Candidate state
2015/01/15 11:08:50 [ERR] memberlist: Failed to receive remote state: EOF
2015/01/15 11:08:50 [ERR] raft: Failed to make RequestVote RPC to 10.432.0.22:8300: dial tcp 10.432.0.22:8300: i/o timeout
2015/01/15 11:08:50 [ERR] memberlist: Failed to receive remote state: EOF
2015/01/15 11:08:50 [INFO] raft: Duplicate RequestVote for same term: 41226
2015/01/15 11:08:50 [ERR] memberlist: Failed to receive remote state: EOF
2015/01/15 11:08:50 [INFO] raft: Node at 10.432.1.89:8300 [Follower] entering Follower state
2015/01/15 11:08:51 [INFO] raft: Duplicate RequestVote for same term: 41227
2015/01/15 11:08:51 [WARN] raft: Heartbeat timeout reached, starting election
2015/01/15 11:08:51 [INFO] raft: Node at 10.432.1.89:8300 [Candidate] entering Candidate state
2015/01/15 11:08:52 [ERR] raft: Failed to make RequestVote RPC to 10.432.1.201:8300: dial tcp 10.432.1.201:8300: no route to host
2015/01/15 11:08:52 [ERR] raft: Failed to make RequestVote RPC to 10.432.1.201:8300: dial tcp 10.432.1.201:8300: no route to host
2015/01/15 11:08:52 [ERR] raft: Failed to make RequestVote RPC to 10.432.0.22:8300: dial tcp 10.432.0.22:8300: i/o timeout
2015/01/15 11:08:53 [WARN] raft: Election timeout reached, restarting election
2015/01/15 11:08:53 [INFO] raft: Node at 10.432.1.89:8300 [Candidate] entering Candidate state
2015/01/15 11:08:53 [ERR] raft: Failed to make RequestVote RPC to 10.432.0.22:8300: dial tcp 10.432.0.22:8300: i/o timeout
2015/01/15 11:08:53 [INFO] raft: Node at 10.432.1.89:8300 [Follower] entering Follower state
```

**Comment by armon** [comment]
You can provide `-bootstrap-expect` on all the nodes safely. It only operates if the cluster is not yet bootstrapped. The problem with automatic server replacement is that Consul cannot know when its possible to do safely. Is the failure temporary? Just a network issue? Will the node come back? 

If you have more knowledge about the environment than Consul, you can automatically issue a `force-leave` against the failed node, and then add a new node. This can be done by querying the EC2 APIs to determine if the node is still alive. This cannot be done by Consul since it requires a deeper knowledge of the operating environment that we'd like to have at this point.

**Comment by petemounce** [comment]
That sounds fine - I can subscribe an SQS to our AutoScaling SNS, listen for ConsulCluster termination notes, correlate the instance ID to the consul node-name (or something), and issue a force-leave for that server.

Then, when ASG brings up the replacement, it will slot in automatically...?

I think that covers the node-failure case.

What about the scale-up / scale-down case...?

**Comment by armon** [comment]
@petemounce You can do `force-leave` idempotent, so not an issue. As long as the ASG group brings up a node that joins the existing cluster, it should get added in automatically. Both scale-up and scale-down should be fine as long as quorum is not lost!

**Comment by petemounce** [comment]
"as long as quorum is not lost" - so, if I lose a node out of a 3 node cluster, there's an even number. Does that mean quorum is lost until the node is replaced? Or, how does that work? If this is in the docs, please link me and I'll devour those.

**Comment by ryanuber** [comment]
@petemounce the consensus protocol is covered in detail [here](https://consul.io/docs/internals/consensus.html), but I think the most relevant part to your question is the following:

> Quorum - A quorum is a majority of members from a peer set, or (n/2)+1. For example, if there are 5 members in the peer set, we would need 3 nodes to form a quorum. If a quorum of nodes is unavailable for any reason, then the cluster becomes unavailable, and no new logs can be committed.

If there are 3 servers, the quorum size is 2, so you should still remain operational while the lost node is fixed or replaced. You might also be interested in reading the [outage guide](https://consul.io/docs/guides/outage.html) for more details on how to recover if quorum is lost.

**Comment by phobologic** [comment]
@petemounce  What we're looking at for this is to allow the consul autoscaling group to be able to query the AWS API to list instance info.  When a new host in the autoscaling group comes up it gets the other instances in the consul server cluster from that API and automatically joins.

We don't currently force leave the old server, assuming that it will safely disappear after the timeout (I think the default is 72 hours) but perhaps that is misguided.

We're still in the process of testing it out, but so far it seems promising.

**Comment by ryanuber** [comment]
I'm going to close this as it seems the question was answered. Thanks!

**Comment by cleung2010** [comment]
@phobologic @ryanuber When you use ASG to maintain the desired number of servers, do the new servers increase the quorum? Let's say you start with 5 servers, so the quorum is 3. If two servers are lost and two new ones are brought back up by ASG, does the number of known servers (at least for the first 72 hours) become 7 and the quorum becomes (7/2)+1? If the quorum is not static, and you got trough two more iterations within 72 hours the quorum will be (11/2)+1=6 but the number of servers will be 5 so it will be in an unhealthy state. In other words, I would like to know if new server nodes joining would increase the quorum.

**Comment by highlyunavailable** [comment]
@cleung2010 Yes, if you do not `leave` or `force-leave` old server nodes while quorum is maintained.

Take the following scenario:

You have an ASG with the following servers (the raft topology matches this):
i-012345 (alive)
i-6789ab (alive)
i-cdef01 (alive)

Your quorum is 2, because the total server count is 3.

If you lose `i-6789ab` and `i-234567` is created to replace it, then you will have the following raft topology:

i-012345 (alive)
i-6789ab (failed)
i-cdef01 (alive)
i-234567 (alive)

If `i-cdef01` then fails and `i-89abcd` is created to replace it, the raft topology will now be:

i-012345 (alive)
i-6789ab (failed)
i-cdef01 (failed)
i-234567 (alive)
i-89abcd (alive)

So, to answer your question, yes, adding new servers does increase the quorum.

**Comment by cleung2010** [comment]
@highlyunavailable Thanks for the prompt reply! So there is a chance that ASG (if no `leave` or `force-leave` is issued) will cause an outage in the case where it spins up servers to the point that the quorum is above the desired/max amount set on ASG. I guess I will do something similar to what @petemounce mentioned and use SQS + AutoScaling SNS to signal a `force-leave` on the old instances.

**Comment by cleung2010** [comment]
I guess the quorum can be deduced from `num_peers` provided by `consul info`.

**Comment by nadirollo** [comment]
This thread has just made my day :+1: 
I was researching on how to get an ASG for the Consul Server Cluster and this shed the light I was looking for. Thanks!
