### ISSUE TITLE
Broken link to step-by-step guide for enabling TLS on existing cluster

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#6067]
#### Overview of the Issue

The link to the step-by-step guide for [configuring TLS on an existing cluster](https://github.com/hashicorp/consul/blob/a58d8e91ac258c04174afca3818cbdae23aa8d3f/website/source/docs/agent/encryption.html.md) is broken.

It appears [this](https://learn.hashicorp.com/consul/security-networking/certificates) is the intended target page, but the step-by-step guide is missing.

The pre-Learn docs exist at [`027025c`](https://github.com/hashicorp/consul/blob/027025c2e1e016abf04e98d6d1edf9d97ba67bf2/website/source/docs/agent/encryption.html.markdown#configuring-tls-on-an-existing-cluster).

#### Reproduction Steps

1. visit https://www.consul.io/docs/agent/encryption.html
2. click "guide" link in last sentence: "Review this step-by-step [guide](https://learn.hashicorp.com/consul/security-networking/agent-encryption#enable-tls-existing-cluster) to learn how."
3. note that destination is not the intended one

**Comment by ChipV223** [comment]
Thanks for the head's up @blalor. We just pushed #6071 that should fix this issue.

I'll go ahead and close this up, but do reach out if you have any other questions!
