### ISSUE TITLE
Does consul api support golang 1.11?

### ISSUE THREAD

**Issue by gaoxinge** [hashicorp/consul#6069]
When I use `go get github.com/hashicorp/consul/api`, it will raise `go build github.com/hashicorp/consul/api: module requires Go 1.12`. I use golang 1.11.

**Comment by mkeeler** [comment]
@gaoxinge If go modules are in use, then we require 1.12. You can use go 1.11 but it will have to be with modules disabled.

**Comment by gaoxinge** [comment]
@mkeeler  So consul api only supports go mod with golang 1.12?

**Comment by mkeeler** [comment]
For now yes. We created the module with go 1.12 and it put a version tag into the mod file. I would have to check and see what the ramifications of removing that would be.

**Comment by gaoxinge** [comment]
@mkeeler Oh, thanks.
