### ISSUE TITLE
New configuration item to change the default value for the MaxHeaderBytes attribute of HTTP server

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#6074]
#### Feature Description
To prevent from Web Server HTTP Header Memory Exhaustion DoS attack, a new configuration item should be provided to change the default value for the MaxHeaderBytes attribute of HTTP server.

#### Use Case(s)
Web Server HTTP Header Memory Exhaustion DoS attack

**Comment by hehailong5** [comment]
any feedback on this one? thanks!

**Comment by mkeeler** [comment]
This sounds totally reasonable to me.
