### ISSUE TITLE
Use Rancher to Deploy consul & Java service , health check error

### ISSUE THREAD

**Issue by lhalcyon** [hashicorp/consul#6078]
![image](https://user-images.githubusercontent.com/21357951/60713620-fc8d6800-9f4b-11e9-82eb-f5497796faf7.png)

**Comment by lhalcyon** [comment]
test-app-xxx is the container name.

**Comment by pierresouchay** [comment]
Your check cannot be reached from your consul agent as the container name is not resolved

**Comment by lhalcyon** [comment]
@pierresouchay  I meet the problem that container ping another container timeout . 
host private ip is 172.16.xx.xx  
container ip is like 10.42.0.9  , 10.42.0.10 ...
But when I exec in a container and ping another container , the ip shows 10.42.n.245 which I never set before .

**Comment by lhalcyon** [comment]
problem solved!
