### ISSUE TITLE
Cannot load UI on MS Edge with IE11 mode enabled

### ISSUE THREAD

**Issue by lssilva** [hashicorp/consul#6089]
Migrated to the latest version Consul 1.5.2 and the UI cannot be loaded on MS Edge (version 41.16299.1004.0)
on Google Chrome it works fine.

Error:
Consul returned an error. You may have visited a URL that is loading an unknown resource

From Console windows it prints 

SCRIPT5: SCRIPT5: Access is denied.

vendor-061947b514883cb4c3c6919dbd867f5a.js (3541,43)

**Comment by johncowen** [comment]
Hi @lssilva 

I've tried MSEdge on the current demo site (Consul UI 1.5.2)

![Screenshot 2019-07-12 at 12 23 50](https://user-images.githubusercontent.com/554604/61124900-1f65d200-a4a0-11e9-8056-2073395d8f5d.png)

Everything seems to work fine. Although it is a slightly later version than the one you are using.

(MSEdge does show a warning in the developer console about unclosed tags, but that seems to be related to correctly closed SVG elements and the warning doesn't seem to effect anything and doesn't show in other browsers)

Could you let me know if you get the same error you are seeing when visiting the demo site at https://demo.consul.io?

Also out of interest (and related to something we are discussing within the team). You mention you are able to use the UI fine in Google Chrome. I'm not sure if you can give us this information or not, but are you restricted in any way as to which browser you use within your working environment, or is this issue just something you've noticed?

Thanks,

John

**Comment by ChipV223** [comment]
HI @lssilva !

Just wanted to reach out and see if you've been able to check if there's anything restrictive in your working environment that may be causing the Consul UI to not load when using MS Edge. I just tried launching the UI using v1.6.0+beta Windows binary and it loaded without any issues

**Comment by lssilva** [comment]
@ChipV223
Yes I do believe it is a Javascript download restriction. The same issue was present on the demo.consul.io 
I tried to debug but the minified payload not as easy but it could be that some js is not being embedded but downloaded from a different source.

**Comment by ChipV223** [comment]
Thank you for the update @lssilva !

In addition to seeing you are able get your firewall to be less restrictive on the JS scripts, another idea that comes to mind is the version of Microsoft Edge that you are using(v41.16299.1004.0). Are you able to update Windows so that the version of Edge is at least v44.17763.1.0(the version I used in the repro)

**Comment by lssilva** [comment]
Hi @ChipV223 
I had a look again and it seems to be an issue with ember.js but due to the minified version I cannot see exactly the route or what causes the issue. I also checked the networking tab and no requests or downloads were blocked. 
  
I rolled it back to version 1.4.2, version 1.4.2 works without a problem.

Regarding update, unfortunately it is not an option. After a few years we just upgraded to this version. But as I mentioned I rolled back and it is working.

**Comment by johncowen** [comment]
Hi @lssilva ,

Thanks for helping us get to the bottom of this. Would it be possible for you to post a screengrab similar to the one I posted above? Importantly showing the entire browser window (including the location bar), plus the error that you are seeing showing in console. There may be a little clue to help us somewhere in that screengrab if you could do that for us.

Thanks,

**Comment by lssilva** [comment]
Error happens on the initial page and the console is:

 `
HTML1300: Navigation occurred.
ui (1,1)

3 HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
ui (57,105)

 jQuery.Deferred exception: Unable to get property 'indexOf' of undefined or null reference TypeError: Unable to get property 'indexOf' of undefined or null reference
   at init (https://demo.consul.io/ui/assets/consul-ui-82bbb5cfe1bfa824eeaee7e24ddf6139.js:663:21)
   at r (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3810:1)
   at o (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3716:1)
   at i.create (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3727:1)
   at e.prototype.create (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:2183:1)
   at Anonymous function (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:2169:56)
   at a (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:2166:5)
   at e.prototype.lookup (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:2154:231)
   at lookup (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3603:137)
   at Ut (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3136:1) undefined
vendor-061947b514883cb4c3c6919dbd867f5a.js (1014,40)

 Error while processing route: index Unable to get property 'indexOf' of undefined or null reference TypeError: Unable to get property 'indexOf' of undefined or null reference
   at init (https://demo.consul.io/ui/assets/consul-ui-82bbb5cfe1bfa824eeaee7e24ddf6139.js:663:21)
   at r (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3810:1)
   at o (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3716:1)
   at i.create (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3727:1)
   at e.prototype.create (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:2183:1)
   at Anonymous function (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:2169:56)
   at a (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:2166:5)
   at e.prototype.lookup (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:2154:231)
   at lookup (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3603:137)
   at Ut (https://demo.consul.io/ui/assets/vendor-061947b514883cb4c3c6919dbd867f5a.js:3136:1)
vendor-061947b514883cb4c3c6919dbd867f5a.js (3409,1)

2 SCRIPT5007: Unable to get property 'indexOf' of undefined or null reference
vendor-061947b514883cb4c3c6919dbd867f5a.js (1013,205)
`

**Comment by johncowen** [comment]
Hi @lssilva ,

Thanks so much for this! I've noticed this is the same error I get when using the UI in IE11. I'm just wondering it you are using Edge in IE11 compatibility mode?

Thanks,

**Comment by lssilva** [comment]
Yes, I believe so.

**Comment by johncowen** [comment]
Hi @lssilva 

Thanks for the info. Are you able to use Edge without the IE11 compatibility mode enabled? You also mention above that you are able to view and use the UI in Google Chrome, is this something you can do day to day?

I'd like to understand if this is something that is blocking you from working or whether it's just that you've noticed the UI doesn't work whilst using Edge in IE11 compatibility mode.

> I rolled it back to version 1.4.2, version 1.4.2 works without a problem.

I tried loading up 1.4.2 in IE11 (not Edge in IE11 compatibility mode) to double check this, and whilst it 'works', it's visually very broken (something we are aware of).

Lastly could you confirm which version of Windows you are running? I 'believe' IE11 compatibility mode in Edge is only available in Windows 8.1, but it would be good to confirm which version of Windows you are running.

Thanks,

John

**Comment by lssilva** [comment]
@johncowen 

Windows 10 Enterprise
Version 1709
OS Build 16299.1217

Microsoft Edge 41.16299.1004.0
Microsoft EdgeHTML 16.16299

Unfortunately there is not much I can do regarding versions or compatibility mode.

For development we can use Chrome but most users have Edge. On long term we are building our own UI on top of Consul and we will be able to upgrade without the need of Consul UI but for now we are also using the Consul UI

**Comment by johncowen** [comment]
Hi @lssilva 

From what I've understood here, the UI doesn't work in IE11 mode in MS Edge (or IE11 itself). We've verified that the UI does run correctly when run in MS Edge without it being in IE11 mode. Would that be correct? If so I'd like to update the title of this issue to something like 'Cannot load UI on IE11'. Does that sound ok?

**Comment by lssilva** [comment]
No reason to close issue that is innactive, I belive issues should be closed if fixed or rejected if you have bots that automatically closes issues why should I invest my time reporting them in the first place?

**Comment by ChipV223** [comment]
Closing as MS no longer support IE 11 and Consul UI is designed to work will with all actively supported browsers(i.e. Chrome, Firefox, MS Edge, etc)
