### ISSUE TITLE
Consul UI lock session warning displayed when no lock is set

### ISSUE THREAD

**Issue by matesik1995** [hashicorp/consul#6097]
#### Overview of the Issue

While traversing through consul kv via UI, when I open a key, which has session lock set, there is warning displayed. After that was shown once, warning is displayed in each key, even if the lock is not set there. Warning disappears after clearing cache  

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create consul session
2. Acquire a lock on any key
3. View this key in UI
4. Go to any other key
5. Warning is still displaying
![untitled](https://user-images.githubusercontent.com/9439125/60896458-ab8cb500-a266-11e9-9274-dd2af417f835.png)

### Consul info for server
consul server version 1.5.2 (from dockerhub)
### Operating system and Environment details

Fedora 29
Google Chrome 73.0.3683.103

**Comment by johncowen** [comment]
Hi @matesik1995 ,

Just to let you know we included a fix for this in the latest Consul 1.6.1 release. I'm going to close this issue, but please feel free to reopen if you continue to have issues.

Thanks!
