### ISSUE TITLE
AutoEncrypt missing port in address

### ISSUE THREAD

**Issue by hooksie1** [hashicorp/consul#6098]
Getting a missing port error for autoencrypt.

A paragraph or two about the issue you're experiencing.

We have a cluster of 5 servers running with TLS enabled. But when we try to use TLS on the clients, we get this error:

    agent: AutoEncrypt resolveAddr failed: address <server-ip>: missing port in address

### Consul info for both Client and Server

Here's our client ssl config:
```
{
  "verify_incoming": false,
  "ca_file": "/etc/consul/ssl/consul-agent-ca.pem",
  "auto_encrypt": {
    "tls": true
  },
  "ports": {
    "http": -1,
    "https": 8501
  }
}
```

Not sure what other information would be helpful.

**Comment by tgerdes** [comment]
Just ran into this as well.  As a workaround I updated my client's join configuration from:
```
retry_join = ["consul-server01"]
```
to 
```
retry_join = ["consul-server01:8301"]
```
https://www.consul.io/docs/agent/options.html#retry-join says the port only needs to be specified if using a different Serf LAN port than the default 8301;  The auto_encrypt option should probably support omitting the port for the join addrs.

**Comment by draoncc** [comment]
I'm running into this as well, but have Cloud Auto-Joining set up for AWS. I've been unable to locate any configuration that would allow me to set the port on which to connect to on discovered IP addresses.

**Comment by hooksie1** [comment]
> 
> 
> Just ran into this as well. As a workaround I updated my client's join configuration from:
> 
> ```
> retry_join = ["consul-server01"]
> ```
> 
> to
> 
> ```
> retry_join = ["consul-server01:8301"]
> ```
> 
> https://www.consul.io/docs/agent/options.html#retry-join says the port only needs to be specified if using a different Serf LAN port than the default 8301; The auto_encrypt option should probably support omitting the port for the join addrs.

That seems to have done it. Thanks!
