### ISSUE TITLE
Feature request: Debian package + repository

### ISSUE THREAD

**Issue by sammcj** [hashicorp/consul#61]
I want to start by saying I really appreciate the excellent work hashicorp are doing.

It would be great if you could consider hosting a Debian package repo for Consul, this makes it much easier to manage updates and automated deployment.

Personally I find reprepo a very quick-and-easy tool for managing repositories - quick howto here: http://anonscm.debian.org/gitweb/?p=mirrorer/reprepro.git;a=blob_plain;hb=HEAD;f=docs/short-howto

**Comment by allen13** [comment]
The influxdb project makes good use of [fpm](https://github.com/jordansissel/fpm) for simultaneously building rpms, debs, and tars at the same time. https://github.com/influxdb/influxdb/blob/master/package.sh

It removes all details of maintaining the differences.

**Comment by geekq** [comment]
consul is a single binary, for easy (re-)distribution and handling.
Packaging as .deb is just a three-liner with fpm:

```
wget -N https://releases.hashicorp.com/consul/0.6.0/consul_0.6.0_linux_amd64.zip
unzip -o consul_0.6.0_linux_amd64.zip
fpm --force --verbose -s dir -t deb -n consul -v 0.6 --url=http://consul.io --vendor=HashiCorp  --description "A distributed service discovery tool" ./consul=/usr/local/bin/consul
```

**Comment by haf** [comment]
@geekq This assumes you have your own build infrastructure, can trigger it on updates to some public URI address and don't want to parametise anything like the version. Or are you really suggesting someone would type those commands out every time one wants to upgrade consul?
