### ISSUE TITLE
Memory leak when "[ERR] agent: failed to sync remote state: rpc error"

### ISSUE THREAD

**Issue by sgirones** [hashicorp/consul#611]
Consul agent stats
```
19047 root      20  0 41.1g 547m 6700 S  13  0.2  0:03.85 consul
[...]
19047 root      20  0 44.5g 3.9g 6828 S    4  1.5  0:43.20 consul
```

Consul logs: 
```
[ERR] agent: failed to sync remote state: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error: rpc error [...]
```

Still we haven't had time to reproduce it, but maybe someone looking at the code can identify it. Deducing from the log, the problem can come from here: https://github.com/hashicorp/consul/blob/3d3c48bd504defd585dbaefa1336ea3c359ad04a/command/agent/local.go#L249

**Comment by ryanuber** [comment]
I've seen this once before as well, but wasn't able to reproduce it. Tagging as a bug, thanks!

**Comment by sgirones** [comment]
I can say it was solved once the consul data was cleaned. It had non-reachable IPs.

If I have time these days I will try to reproduce, but can't promise.

**Comment by armon** [comment]
Fixed by https://github.com/hashicorp/raft/commit/a88bfa8385bc52c1f25d0fc02d1b55a2708d04ab
