### ISSUE TITLE
A Go-micro web microservice logs error related to Consul

### ISSUE THREAD

**Issue by BruceWangNo1** [hashicorp/consul#6118]
#### Overview of the Issue

I am writing microservices using Go-micro and Consul as the registry. And the web service is logging errors possibly related to Consul. I have tried update packages and tried earlier and latest versions of consul binaries. The following is the error message.  

```
[ERR] consul.watch: Watch (type: service) errored: Get http://127.0.0.1:8500/v1/health/service/go.micro.tea.srv.wiki?index=16: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retry in 5s
```
I don't think I ever wrote this error message inside the web service. Consul log showed that it received the requests. Nothing wrong with http_proxy and https_proxy env variable. They are all empty.
I found that issue #3031 is reporting a similar problem. However, that issue does not help me with a fix. 
I found that HTTP Get http://127.0.0.1:8500/v1/health/service/go.micro.tea.srv.wiki?index=16 is experiencing the same problem in Postman. However, after I stripped "?=index=#" at the end, a normal response is received. Also, # is changing almost every time I restart the web service.

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = a82e6a7f
	version = 1.5.2
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 10
	commit_index = 10
	fsm_pending = 0
	last_contact = 0
	last_log_index = 10
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:9f5b93df-1813-0d66-21ea-b89e3b325e17 Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 77
	max_procs = 8
	os = darwin
	version = go1.12.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Log Fragments

2019/07/12 11:29:49 [ERR] consul.watch: Watch (type: service) errored: Get http://127.0.0.1:8500/v1/health/service/go.micro.tea.srv.wiki?index=16: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retry in 5s
2019/07/12 11:29:49 [ERR] consul.watch: Watch (type: services) errored: Get http://127.0.0.1:8500/v1/catalog/services?index=17: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retry in 5s

**Comment by BruceWangNo1** [comment]
I found the underlying cause for these errors. There is something wrong with the web srv as you have suggested. There is a Timeout field in struct registry.Options in "github.com/micro/go-micro/registry" which is wrongly set to time.Second * 5 in the web srv. After I commented it out, the error logs were gone.

**Comment by wubo0067** [comment]
哥们这个问题怎么解决的？

**Comment by BruceWangNo1** [comment]
@wubo0067 registry.Options不要设置Timeout
