### ISSUE TITLE
100% CPU after upgrade to consul 1.5.2

### ISSUE THREAD

**Issue by 42wim** [hashicorp/consul#6120]
After upgrading to 1.5.2 our consul agents where taking all available CPU.

I traced the issue to PR #5468

We specify our IPv6 recursor on startup with the flag `-recursor [2001:db8:85a3:8d3:1319:8a2e:370:7348]` but without a port (which should use the default port 53)

This PR introduced a tight loop on that port 53 check in: https://github.com/hashicorp/consul/blob/a82e6a7fd33a0d05b9b871bcaf1d7595c9b8dedc/agent/dns.go#L271-L275 which results in an every increasing bracket adding `[[[2001:db8:85a3:8d3:1319:8a2e:370:7348]]:53]:53` etc and taking all the CPU

According to https://github.com/golang/go/issues/20470 the "[]" are only allowed when specifying a port with an ipv6 address.

But the `-recursor 2001:db8:85a3:8d3:1319:8a2e:370:7348` fails with `too many colons in address`

So a possible fix would be to check for that error as below:

```
START:
	_, _, err := net.SplitHostPort(recursor)
	if ae, ok := err.(*net.AddrError); ok && (ae.Err == "missing port in address" ||  ae.Err == "too many colons in address") {
		recursor = ipaddr.FormatAddressPort(recursor, 53)
		goto START
```

ping @pierresouchay 

Simple workaround for this bug is specifying the port `-recursor [2001:db8:85a3:8d3:1319:8a2e:370:7348]:53`

**Comment by banks** [comment]
Thanks @42wim for the great debugging tips too.

You're proposed fix sounds like a good one to me. If you'd like to contribute it as a PR with a test that would be much appreciated. But if not we will take a look.

**Comment by 42wim** [comment]
Made PR for this in #6128
