### ISSUE TITLE
Support ACL template policy for Nodes

### ISSUE THREAD

**Issue by vasilij-icabbi** [hashicorp/consul#6123]
#### Feature Description
Automatically populate `segment` in `node` resource in ACL. Probably something like "ACL Service Identities" can be reused, or same approach taken. For instance:

```
node "<node name>" {
    policy = "write"
}
```

Where \<node name\> is automatically replaced with actual node name (e.g. consul-1)

#### Use Case(s)
Consul Server cluster that runs using AWS ASG and least permissive tokens is a requirement. To achieve that, currently need to create custom scripts and handlers.

Discussed [here](https://discuss.hashicorp.com/t/consul-exclusive-acl-policy-for-nodes-service-in-asg/1654)

**Comment by blake** [comment]
@vasilij-icabbi, Consul 1.8.1 added support for [Node Identities](https://www.consul.io/docs/security/acl/acl-system#acl-node-identities) in PR #7970, which works similarly to ACL Service Identities.

You can create an agent token with `consul acl token create -node-identity=<nodename>:<DC>`. The pre-configured ACL policy template listed in the docs will be assigned to the token.
