### ISSUE TITLE
documentation: auto encrypt on an existing Consul datacenter not possible?

### ISSUE THREAD

**Issue by 42wim** [hashicorp/consul#6127]
I've upgraded to v1.5.2 and wanted to migrate to auto encrypt. According to the documentation on https://learn.hashicorp.com/consul/security-networking/certificates this should be possible

> If you are configuring RPC encryption on an existing Consul datacenter, verify_incoming and verify_outgoing must be set to false to allow existing communication to continue uninterrupted. 

But, with auto encrypt it's not possible to set `verify_incoming` to `false`.

Consul bails with `==> if auto_encrypt.allow_tls is turned on, TLS must be configured in order to work properly.`

https://github.com/hashicorp/consul/blob/97ecc0517ccda9ae3254c1f64b6ee3c9b9fe9a99/agent/config/builder.go#L1113-L1117

**Comment by rollerd** [comment]
This also seems to contradict the documentation in the [Learn Consul guide](https://learn.hashicorp.com/consul/security-networking/certificates#configuring-the-consul-ui-for-https):
` There is a combination of options however that allows us to keep using verify_incoming for RPC, but not for HTTPS:
{
  "verify_incoming": false,
  "verify_incoming_rpc": true
}
`

**Comment by isaac-mj** [comment]
I'm having the same issues here. Is this being looked after?

**Comment by i0rek** [comment]
Thanks for reporting @42wim, @rollerd and @isaac-mj. The documentation is not correct and will be fixed.

Setting up `auto_encrypt` in an existing datacenter should be possible. You need to enable it on every server first and then you can let clients use it. Servers needs to have TLS enabled, which is the code sample you provided. 

Let me know if it works for you or if you need more guidance.

**Comment by TheVanitas** [comment]
I'm having a similar issue. I'm currently setting up a new single-node cluster (for now) on 1.5.3 and I'm following the guide to securing RPC communication with TLS encryption. I'm trying to configure the UI for HTTPS which requires setting `verify_incoming` to false and `verify_incoming_rpc` to true. However, as soon as I do that and restart the server, I'm also getting `if auto_encrypt.allow_tls is turned on, TLS must be configured in order to work properly.`

**Comment by 42wim** [comment]
@i0rek for an existing it's not possible to use `auto_encrypt` with `verify_incoming` disabled, as such you can't update your servers/clients without outage.

Also on a new setup you can't use the UI anymore like @TheVanitas reports

**Comment by nickespinosa** [comment]
@42wim I was able to get the UI working with auto_encrypt by configuring 1 node out of a 3 node cluster without the auto_encrypt settings, and connecting directly to it.

Hope this helps.

**Comment by i0rek** [comment]
I created an issue for this #6338. I think you should be able to serve the UI from a client in the meanwhile. Sorry for the troubles.

**Comment by 42wim** [comment]
@i0rek i've upgraded to 1.6.1, it's still not possible to enable auto encrypt on an existing datacenter though. 

I'm trying to configure first of the 3 servers.

I can now set `verify_incoming` to `true` and `verify_incoming_rpc` to `false` or `verify_incoming_rpc` to true and `verify_incoming` to `false` but the result is the same.

```
Oct 09 16:11:29 consul-3 consul[25692]: 2019/10/09 16:11:29 [WARN] consul.rpc: Non-TLS connection attempted with VerifyIncoming set from=[x.x.x.x]:44313
```

Full config
```
{
  "verify_incoming": true,
  "verify_incoming_rpc": false,
  "verify_outgoing": false,
  "verify_server_hostname": false,
  "auto_encrypt": {
    "allow_tls": true
  },
  "ca_file": "/usr/share/consul/consul-agent-ca.pem",
  "cert_file": "/usr/share/consul/server-consul.pem",
  "key_file": "/usr/share/consul/server-consul-key.pem"
}
```

**Comment by i0rek** [comment]
@TheManyula your issues should be fixed, that true?
@42wim thanks for your update. Could you describe the steps you are going through in detail? I am wondering if you are starting with a non-TLS cluster and want to upgrade to auto_encrypt?

Thanks!

**Comment by 42wim** [comment]
@i0rek Yes I'm trying to upgrade a non-TLS cluster to auto_encrypt and following the procedure on https://learn.hashicorp.com/consul/security-networking/certificates

I'm doing basically step 1 and then changing the verify_incoming and verify_outgoing to false like in the documentation

> If you are configuring TLS encryption on an existing Consul deployment, verify_incoming and verify_outgoing must be set to false to allow existing communication to continue uninterrupted. This will require a rolling restart on all the servers. Once the clients are configured, you can then enable verify_incoming and verify_outgoing on the servers.

**Comment by i0rek** [comment]
@42wim I think you need to 

1) Setup servers with TLS and `auto_encrypt` with the caveat of disabling `verify_incoming` and `verify_outgoing` like you said.
1) Enable auto_encrypt on the clients
1) Enable `verify_incoming` and `verify_outgoing` on the servers

The logs you posted indicate that a client tries to communicate via TLS without having a certificate.

**Comment by 42wim** [comment]
@i0rek well the main issue is that it's not possible to disable `verify_incoming` and `verify_outgoing` on the servers. Consul doesn't want to start up.

```Nov 18 15:27:22 icts-q-consul-3 consul[41542]: ==> if auto_encrypt.allow_tls is turned on, either verify_incoming or verify_incoming_rpc must be enabled```

**Comment by i0rek** [comment]
@42wim thanks for pointing that out! I am relaxing that requirement in https://github.com/hashicorp/consul/pull/6811 to enable migrations.

And I would like to ask everyone to explain your use case of `verify_incoming` on consul clients in that PR.

**Comment by 42wim** [comment]
@i0rek I'm running a `release/1.6.x` build with your PR in it, and now it works perfectly (as per documentation)
Thanks again!

**Comment by i0rek** [comment]
Thank you for confirming @42wim!
