### ISSUE TITLE
CAS and Acquire in same request doesn't fail with curl

### ISSUE THREAD

**Issue by hmurraydavis** [hashicorp/consul#6135]
Per #985, a PUT request with both cas and acquire should fail with a Conflicting flags error. When testing in the command line with curl, this does not fail and updates the key in the store. 

``` 
curl -X PUT -d barasdf http://localhost:8500/v1/kv/foo?cas=822&acquire=0a793542-55c6-f6a7-98d8-0cb0e9be1d3a
[1] 2568
$ true 
```

This error was correctly generated when the request was sent through http4s and Scala with the same request body (copied and pasted the http string). 

It would be good if the behavior was consistent.

**Comment by DhashS** [comment]
This doesn't happen for me in testing with pure cURL - though I'm sitting next to @hmurraydavis and can confirm that it's doing that.

``` 
dhash@opal ~  $ curl -X PUT -d '{"Name": "lockname"}' http://127.0.0.1:8500/v1/session/create
{
    "ID": "04596b06-e1e6-b639-e7aa-4ddf94255b37"
}
 dhash@opal ~  $ curl -X PUT -d bar "http://localhost:8500/v1/kv/foo?acquire=04596b06-e1e6-b639-e7aa-4ddf94255b37"
true
 dhash@opal ~  $ curl -X PUT -d bar "http://localhost:8500/v1/kv/foo?acquir^C
 dhash@opal ~  $ curl -X GET http://localhost:8500/v1/kv/foo
[
    {
        "LockIndex": 1,
        "Key": "foo",
        "Flags": 0,
        "Value": "YmFy",
        "Session": "04596b06-e1e6-b639-e7aa-4ddf94255b37",
        "CreateIndex": 18,
        "ModifyIndex": 18
    }
]
 dhash@opal ~  $ curl -X GET http://localhost:8500/v1/kv/foo^C
 dhash@opal ~  $ curl -X PUT -d bar2 "http://localhost:8500/v1/kv/foo?acquire=04596b06-e1e6-b639-e7aa-4ddf94255b37&cas=18"
Conflicting flags: acquire=04596b06-e1e6-b639-e7aa-4ddf94255b37&cas=18⏎ 
```

**Comment by i0rek** [comment]
@hmurraydavis thanks for reporting.

I started an agent: `consul agent -dev` and did what @DhashS described. And I am also getting the same error like @DhashS. Which makes me think your application is doing something else.

**Comment by DhashS** [comment]
Yes our application was wrong, fixed now.
that cURL command still shouldn't ever return 200.
I'd call this a bug

**Comment by i0rek** [comment]
@DhashS thanks for confirming. I am closing this bug, feel free to open a separate issue for the `200` http status code though!
