### ISSUE TITLE
Failed to build consul locally

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#6140]
Version: 1.4.0
Go version: 1.9.7 linux/amd64

root@nfvo1-E9000:~/hhl/git/consul/build-support/scripts# ./build-local.sh -o linux -a x86_64
+ ./build-local.sh -o linux -a x86_64
==> Building Consul - OSes: linux, Architectures: x86_64
Building sequentially with go install
--->   linux/x86_64
../../go/src/github.com/envoyproxy/go-control-plane/envoy/type/http_status.pb.go:11:2: code in directory /root/hhl/go/src/github.com/envoyproxy/protoc-gen-validate/validate expects import "github.com/lyft/protoc-gen-validate/validate"
../../go/src/github.com/gogo/protobuf/gogoproto/gogo.pb.go:9:2: found packages descriptor (descriptor.go) and google_protobuf (gostring.go) in /root/hhl/go/src/github.com/gogo/protobuf/protoc-gen-gogo/descriptor
ERROR: Failed to build Consul for linux/x86_64

What's going wrong here and how to fix it?

**Comment by pearkes** [comment]
Hey @hehailong5, looks like you need a newer version of Go (> 1.12). That should fix it for you. Thanks for opening an issue.
