### ISSUE TITLE
Remove Trust Domain from Envoy Names

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#6142]
Envoy has a 60 character limit for things like cluster names. Currently we are using the SNI for naming of clusters and we just are happening not to run into the limit (although we have been close)

Right now the SNI is structured like:

`<service subset>.<service name>.<namespace>.<datacenter>.<internal/external>.<cluster id>.consul`

The trust domain is the `<cluster id>.consul` part and accounts for 40 bytes.

We should probably change things to have cluster names like:

`<service subset>.<service name>.<namespace>.<datacenter>`

This would make it less likely we run into the 60 character limit.

**Comment by rboyer** [comment]
Do we need this if we do https://github.com/hashicorp/consul/pull/6202 ?

**Comment by mkeeler** [comment]
I actually needed to close this issue. We cannot do this because the SNI has to be the cluster name (at least for gateways) in order for the sni_cluster network filter to work.
