### ISSUE TITLE
Improve performance of mapstructure in HTTP API

### ISSUE THREAD

**Issue by pearkes** [hashicorp/consul#6147]
We should cache mapstructure conversion results in the API (see below) or we could do the conversion before any field processing happens and just use those results everywhere. The decodeBody function is used by more than just the TXN API but it is most noticeable there given the types of requests typically made.

Quoting @mkeeler:

> Every time DecodeHookExec is called it first runs typedDecodeHook on the ComposeDecodeHookFunc. Then after conversion etc. it will execute the composed function which recursively invokes DecodeHookExec on each of those two functions. That in turn does the same thing with calling typedDecodeHook. So for every field we call typedDecodeHook 3 times. As you can see in the flamegraph calling that function accounts for most of the time spent in DecodeHookExec and overall is accounting for a very large portion of the overall CPU time.
>
> So what does typedDecodeHook do? Very little in fact. In essence its just checking if the passed in value is convertible to one of two interfaces, converts it and returns the converted value. This “conversion” is just checking that a provided function pointer has the right signature and “converts” it to the named function type. 
>
> The answer here is that the reflection base checking if the fn pointers are convertible and then converting them is not cheap and we are doing it way more often than we need to. For every field in every request being decoded by the HTTP API we will rerun the exact same conversion routines repeatedly. They will always produce the same result, yet we keep rerunning them. In some cases a Txn request could contain many operations to be performed. Each one of those operations will have at least 4 fields internally. So we will do the 3 conversion 
>
> 5X + 1 times where X is the number of operations in the txn (so we are calling typedDecodeHook at least 16 times for every Txn op). While the HTTP API enforces a max of 64 ops in a Txn request, that is enforced AFTER decoding so it could be possible to send huge requests that have no chance of actually being applied but they can easily consume very large amounts of CPU.

**Comment by adams-sarah** [comment]
I'm going to try to paste some of the context I gain on this issue as it comes to me, in case I drop off or someone else has ideas they can chime in.

Wrote a more strenuous benchmark for `mapstructure`, which decodes a semi-complex, 75KB json blob into a Go struct. Thought the new benchmark alone, especially compared to the output of existing benchmarks, was note worthy (**new more strenuous benchmark at the bottom**) 🏒  :

```
Sarahs-MacBook-Pro:mapstructure sadams$ go test -bench=. -benchmem -memprofile memprofile.out -cpuprofile cpuprofile.out
goos: darwin
goarch: amd64
pkg: github.com/mitchellh/mapstructure
Benchmark_Decode-8                   	  300000	      4342 ns/op	    1993 B/op	      51 allocs/op
Benchmark_DecodeViaJSON-8            	  500000	      3998 ns/op	    1232 B/op	      34 allocs/op
Benchmark_JSONUnmarshal-8            	 1000000	      1881 ns/op	     288 B/op	      13 allocs/op
Benchmark_DecodeBasic-8              	  200000	      9671 ns/op	    6327 B/op	      76 allocs/op
Benchmark_DecodeEmbedded-8           	  200000	      6396 ns/op	    5827 B/op	      75 allocs/op
Benchmark_DecodeTypeConversion-8     	   50000	     31449 ns/op	   16402 B/op	     240 allocs/op
Benchmark_DecodeMap-8                	  500000	      3057 ns/op	    1208 B/op	      34 allocs/op
Benchmark_DecodeMapOfStruct-8        	  100000	     12206 ns/op	   11031 B/op	     139 allocs/op
Benchmark_DecodeSlice-8              	 1000000	      2333 ns/op	     944 B/op	      29 allocs/op
Benchmark_DecodeSliceOfStruct-8      	  200000	     11264 ns/op	   10430 B/op	     128 allocs/op
Benchmark_DecodeWeaklyTypedInput-8   	  500000	      2728 ns/op	    1464 B/op	      28 allocs/op
Benchmark_DecodeMetadata-8           	  500000	      2762 ns/op	    1707 B/op	      26 allocs/op
Benchmark_DecodeMetadataEmbedded-8   	  300000	      6242 ns/op	    5276 B/op	      62 allocs/op
Benchmark_DecodeTagged-8             	 1000000	      1601 ns/op	     840 B/op	      18 allocs/op
Benchmark_DecodeLargeJson-8          	     500	   2893028 ns/op	 1373138 B/op	   33971 allocs/op
```
(gist of the benchmark is here just in case: https://gist.github.com/adams-sarah/44cb61871a1057da8fde05b059c0478a)

**Comment by adams-sarah** [comment]
Alright I've got some more benchmarks and some charts. I decided to compare the growth of these benchmarks against similar benchmarks that I wrote for `encoding/json`.

(RED = mitchellh/mapstructure

This pretty much what I expected given that `mapstructure` uses `reflect`, and uses it recursively. Using reflect recursively does not scale well, especially in terms of memory usage.

But here are the benchmarks and such:

```
pkg  | Bench name | iterations | ns/op | B/op | allocs/op
encoding/json | Benchmark_Sarah_Decode-8 | 1000000 | 2213 | 320 | 14
encoding/json | Benchmark_Sarah_DecodeViaJSON-8 | 1000000 | 1781 | 656 | 5
encoding/json | Benchmark_Sarah_DecodeBasic-8 | 500000 | 3259 | 368 | 13
encoding/json | Benchmark_Sarah_DecodeMapOfStruct-8 | 1000000 | 2111 | 648 | 16
encoding/json | Benchmark_Sarah_DecodeSlice-8 | 1000000 | 1122 | 232 | 8
encoding/json | Benchmark_Sarah_DecodeSliceOfStruct-8 | 1000000 | 1388 | 288 | 8
encoding/json | Benchmark_Sarah_DecodeTagged-8 | 3000000 | 471 | 184 | 2
encoding/json | Benchmark_Sarah_DecodeLargeJson75kb-8 | 2000 | 1026076 | 104284 | 7335
encoding/json | Benchmark_Sarah_DecodeLargeJson1mb-8 | 100 | 14790997 | 2039177 | 135597
  |   |   |   |   |  
  |   |   |   |   |  
mitchellh/mapstructure | Benchmark_Decode-8 | 300000 | 4670 | 1993 | 51
mitchellh/mapstructure | Benchmark_DecodeViaJSON-8 | 300000 | 4222 | 1232 | 34
mitchellh/mapstructure | Benchmark_DecodeBasic-8 | 200000 | 10160 | 6327 | 76
mitchellh/mapstructure | Benchmark_DecodeMapOfStruct-8 | 100000 | 12954 | 11031 | 139
mitchellh/mapstructure | Benchmark_DecodeSlice-8 | 500000 | 2432 | 944 | 29
mitchellh/mapstructure | Benchmark_DecodeSliceOfStruct-8 | 100000 | 12137 | 10431 | 128
mitchellh/mapstructure | Benchmark_DecodeTagged-8 | 1000000 | 1655 | 840 | 18
mitchellh/mapstructure | Benchmark_DecodeLargeJson75kb-8 | 500 | 2983173 | 1373150 | 33971
mitchellh/mapstructure | Benchmark_DecodeLargeJson1mb-8 | 100 | 37533688 | 19567845 | 460321

**Comment by adams-sarah** [comment]
(^ whoops hit send too soon)

**Comment by adams-sarah** [comment]
Attaching a screenshot of the cpu flame graph mentioned in the issue description. Or, rather, an instance of one. 
<img width="1286" alt="Screen Shot 2019-08-23 at 1 58 04 PM" src="https://user-images.githubusercontent.com/2741356/63623601-d597fd80-c5ae-11e9-9231-96c3dbf3a091.png">

@mkeeler
