### ISSUE TITLE
Legacy ACLs after upgrade to consul 1.4.5 do not functionally identically

### ISSUE THREAD

**Issue by perzizzle** [hashicorp/consul#6153]
#### Overview of the Issue
Legacy ACLs working with consul 1.0.0 do not work on consul 1.4.5

#### Reproduction Steps
1. Create a cluster with 3 server nodes and 1 client node running consul 1.0.0
3. Bootstrap acl's and create new token with the following ACL definition.
key "" { policy = "read" } 
3. Put a value into the kv
consul kv put -token=master_token foo bar
4. Recursively pull it
consul kv get -recurse -token=acl_defined_above foo
5. Next upgrade the cluster 1 node at a time to consul 1.4.5. Tokens are NOT migrated. See the following gist for the server config [https://gist.github.com/perzizzle/aa2831a60bfa5d008d4bb1432f49454e](url)
6. Attempt to recursively get key
Error querying Consul agent: Unexpected response code: 403

My reading of https://www.consul.io/docs/acl/acl-migrate-tokens.html is that legacy tokens should behave identically after the upgrade (Existing tokens will continue to work in the same way for at least two "major" releases).

I'm struggling with the order of operations to accomplish this upgrade without causing any downtime. My initial plan was to do the binary upgrade, then migrate the tokens to the new syntax  but our apps fail to get the kv values while the consul 1.4.5 binary is rolling out across all of the nodes.

### Operating system and Environment details
All servers are:
Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Comment by mkeeler** [comment]
@perzizzle Did you previously have `acl_enable_key_list_policy` set to true for your 1.0.0 config?

Because a "read" policy does not allow listing once you have that enabled. It allows reading any of the individual entries though.

**Comment by perzizzle** [comment]
You are correct. That is a new config parameter added to our system that I missed the downstream effects of.
