### ISSUE TITLE
avoid sending the compiled discovery chain over RPC

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#6182]
The compiled discovery chain is currently being sent over RPC, but it's a tricky AST-like structure that may change a lot over time (making backwards compatibility hard).

We should shift to only sending collections of related config entries over the wire and executing the compiler on the other side so we are freer to significantly change the AST structure over time.

**Comment by mkeeler** [comment]
### Food For Thought

I think there are reasons why its not an exact match for the usage but this does sound similar to the Txn API.

We could potentially request the service defaults, routes, splits and resolver for a service with one Txn request. The main issue is that how would we know ahead of time what other related config entries we will also need. We could just have the request for each entry and any "related" entries. Doing this in the Txn API would eliminate the need for a specialized RPC and instead push it into a new Txn Op type.

**Comment by rboyer** [comment]
This may be obviated by #6213

**Comment by rboyer** [comment]
Closing in favor of  #6213
