### ISSUE TITLE
/v1/agent endpoints hang

### ISSUE THREAD

**Issue by jwalton** [hashicorp/consul#6184]
### Overview of the Issue

GETs to localhost:8500/v1/agent/self (and seemingly any /agent endpoint) are hanging forever.

I've seen this on both Consul 1.0.0 and 1.4.4 (at first I thought perhaps this was #4011 and 1.4.4 was the highest consul version any node in my cluster was running, so it seemed like a safe one to upgrade to).

Once the agent is in this state, I have to `kill -9` it to kill it.

For me, this problem is particularly irksome, as at some point someone did something "clever" and made it so we poll this endpoint in our .bashrc to check if this is a development node or a production node, and print a nice "This is a production node, please be careful" message.  The upshot of this is, I can't SSH into any of these nodes (this is EC2, so I can disassociate their IAM Role, reboot them, and then SSH in - when consul isn't connected to the cluster this endpoint works.  But as soon as I restore the IAM Role, consul finds the rest of the cluster, and this problem starts happening.

#### Reproduction Steps

I don't know.  These nodes have happily been running consul v1.0.0 literally for years (some are on v0.9.1), and then all of a sudden three days ago, this suddenly started happening on many (but, strangely, not all) nodes in my cluster.  About 24 nodes are affected of about 50 total.  Restarting consul or rebooting to node seems to always end up back in this state.  I haven't tried restarting consul on any of the "good" nodes.  :P

### Consul info for both Client and Server

`consul info` hangs on the client.

<details>
  <summary>Server info</summary>

```
[root@ip-192-168-2-194:~]# consul info
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 2
	services = 1
build:
	prerelease =
	revision =
	version = 1.1.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 192.168.2.175:8300
	server = true
raft:
	applied_index = 856816090
	commit_index = 856816090
	fsm_pending = 0
	last_contact = 915.978545ms
	last_log_index = 856816090
	last_log_term = 31276
	last_snapshot_index = 842116082
	last_snapshot_term = 31276
	latest_configuration = [{Suffrage:Voter ID:bf3e2800-862d-0043-7751-bebc95ef8340 Address:192.168.2.175:8300} {Suffrage:Voter ID:518e2c37-b20c-93ef-6a18-a2001b60bd89 Address:192.168.2.194:8300} {Suffrage:Voter ID:812abc71-a930-fb66-a719-20a2e3ebc4b2 Address:192.168.1.163:8300}]
	latest_configuration_index = 675916175
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 31278
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 313
	max_procs = 1
	os = linux
	version = go1.9.5
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1081
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 13115
	members = 38
	query_queue = 0
	query_time = 717
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 717
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Ubuntu 16.04.6 LTS (not sure if all nodes are running this version - there's a lot of nodes in our cluster, and some are pretty old, but the one I'm SSHed into right now is on this version).

### Log Fragments

[Client agent log](https://gist.github.com/jwalton/eba7053b76eb8ebb0872d818c60d5821).  There's a post-SIGTERM log at the bottom - consul is still running at this point until I `kill -9` it.

**Comment by jwalton** [comment]
Aha!  This is possibly related to https://github.com/hashicorp/consul/issues/866.  Two of my consul servers are out of disk space because raft.db is 25G+.

**Comment by mkeeler** [comment]
@jwalton That is a very large raft.db. How large are the raft snapshots?

**Comment by jwalton** [comment]
On the leader, raft.db is 62M and each of the snapshot folders in /var/lib/consul/raft/snapshots is 1.1M.

On the other two nodes, the snapshot folders are the same size, but raft.db is huge:

```
[root@ip-192-168-1-163:/var/lib/consul/raft]# du -h .
1.1M	./snapshots/31276-842104782-1562044467146
1.1M	./snapshots/31276-842087827-1562043276663
2.2M	./snapshots
24G	.
```

**Comment by mkeeler** [comment]
Well the snapshots look the correct size on both and the leader looks correct.

Normally as part of the snapshotting process the raft log gets truncated. Its supposed to only contain up to the 10K most recent raft logs as the snapshot contains a point in time representation of what should be in memory. So a snapshot combined with all the newer logs is sufficient to recreate the full state.

The raft.db is also a grow-only file so once it gets to that size it will remain there (although various parts of it will get rewritten). It seems unlikely though that it got to 24G in size with only 10K log entries as each one would need to be 2.5+ MB in size.

On those two non-leader servers do you see logs like: 

"Compacting logs from %d to %d" or "log compaction failed"

**Comment by jwalton** [comment]
`journalctl -u consul | grep -i compacting` shows that logs were being compacted up until Jul 2:

```
Jul 02 03:55:24 ip-192-168-1-163.shared.vpc consul[1307]:     2019/07/02 03:55:24 [INFO] raft: Compacting logs from 842010646 to 842027153
Jul 02 04:15:01 ip-192-168-1-163.shared.vpc consul[1307]:     2019/07/02 04:15:01 [INFO] raft: Compacting logs from 842027154 to 842043807
Jul 02 04:35:10 ip-192-168-1-163.shared.vpc consul[1307]:     2019/07/02 04:35:10 [INFO] raft: Compacting logs from 842043808 to 842060784
Jul 02 04:54:36 ip-192-168-1-163.shared.vpc consul[1307]:     2019/07/02 04:54:36 [INFO] raft: Compacting logs from 842060785 to 842077587
Jul 02 05:14:27 ip-192-168-1-163.shared.vpc consul[1307]:     2019/07/02 05:14:27 [INFO] raft: Compacting logs from 842077588 to 842094542
```

But there were no more lines that matched the grep after that point in time.

**Comment by mkeeler** [comment]
That would do it. Although now the question is how this could happen which will require some more looking into.

**Comment by jwalton** [comment]
Also interesting, this node has 100% inode usage:

```
[root@ip-192-168-1-163:/var/lib/consul/raft]# df -i .
Filesystem                Inodes   IUsed IFree IUse% Mounted on
/dev/disk/by-label/nixos 3276800 3276800     0  100% /
```

I tried to delete raft.db and restart consul to get this node back up, but it couldn't recreate raft.db.  -_-

**Comment by jwalton** [comment]
And my leader stop compacting logs on Jul 14th (although it has lots of inodes free).  :(

**Comment by mkeeler** [comment]
Is there anything else with the raft db open on the followers that might prevent relinquishing the indodes?

**Comment by mkeeler** [comment]
Actually, with no free inodes, this would prevent raft from snapshotting and then compacting the logs properly.

Do you have something generating log files and not reaping them after some time (or something similar that has created tons of files but not removed them)?

**Comment by jwalton** [comment]
Yeah, although there are lots of inodes free on the leader, and it stopped on the 14th.

Logs on the 14th from the leader say:

```
Jul 14 12:26:10 ip-192-168-2-175.shared.vpc consul[25958]: 2019/07/14 12:26:10 [DEBUG] raft-net: 192.168.2.175:8300 accepted connection from: 192.168.1.163:36880
Jul 14 12:26:10 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:10 [INFO] consul: New leader elected: ip-192-168-1-163.shared.vpc
Jul 14 12:26:14 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:14 [WARN] memberlist: Was able to connect to ip-192-168-1-163.shared.vpc.us-east-1 but other probes failed, network may be misconfigured
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [WARN] raft: Heartbeat timeout from "192.168.1.163:8300" reached, starting election
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] raft: Node at 192.168.2.175:8300 [Candidate] entering Candidate state in term 31278
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] raft: Election won. Tally: 2
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] raft: Node at 192.168.2.175:8300 [Leader] entering Leader state
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] raft: Added peer 518e2c37-b20c-93ef-6a18-a2001b60bd89, starting replication
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] raft: Added peer 812abc71-a930-fb66-a719-20a2e3ebc4b2, starting replication
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] consul: cluster leadership acquired
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] consul: New leader elected: ip-192-168-2-175.shared.vpc
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] raft: pipelining replication to peer {Voter 812abc71-a930-fb66-a719-20a2e3ebc4b2 192.168.1.163:8300}
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [WARN] raft: AppendEntries to {Voter 518e2c37-b20c-93ef-6a18-a2001b60bd89 192.168.2.194:8300} rejected, sending older logs (next: 856816091)
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to get log at index 856816090: log not found
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [INFO] raft: aborting pipeline replication to peer {Voter 812abc71-a930-fb66-a719-20a2e3ebc4b2 192.168.1.163:8300}
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to install snapshot 31276-856854390-1563106811373: failed to create snapshot: mkdir /var/lib/consul/raft/snapshots/31276-856854390-1563107178387.tmp: no space left on dev
ice
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to send snapshot to {Voter 518e2c37-b20c-93ef-6a18-a2001b60bd89 192.168.2.194:8300}: failed to create snapshot: mkdir /var/lib/consul/raft/snapshots/31276-856854390-15631
07178387.tmp: no space left on device
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to get log at index 856816090: log not found
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to install snapshot 31276-856854390-1563106811373: failed to create snapshot: mkdir /var/lib/consul/raft/snapshots/31276-856854390-1563107178412.tmp: no space left on dev
ice
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to send snapshot to {Voter 518e2c37-b20c-93ef-6a18-a2001b60bd89 192.168.2.194:8300}: failed to create snapshot: mkdir /var/lib/consul/raft/snapshots/31276-856854390-15631
07178412.tmp: no space left on device
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [WARN] raft: AppendEntries to {Voter 812abc71-a930-fb66-a719-20a2e3ebc4b2 192.168.1.163:8300} rejected, sending older logs (next: 856859318)
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to get log at index 856816090: log not found
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [WARN] raft: AppendEntries to {Voter 812abc71-a930-fb66-a719-20a2e3ebc4b2 192.168.1.163:8300} rejected, sending older logs (next: 856859317)
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to install snapshot 31276-856854390-1563106811373: failed to create snapshot: mkdir /var/lib/consul/raft/snapshots/31276-856854390-1563107178441.tmp: no space left on dev
ice
Jul 14 12:26:18 ip-192-168-2-175.shared.vpc consul[25958]:     2019/07/14 12:26:18 [ERR] raft: Failed to send snapshot to {Voter 518e2c37-b20c-93ef-6a18-a2001b60bd89 192.168.2.194:8300}: failed to create snapshot: mkdir /var/lib/consul/raft/snapshots/31276-856854390-1563107178441.tmp: no space left on device
```

On the third node, we have:

```
Jul 02 05:08:24 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/02 05:08:24 [INFO] raft: Compacting logs from 842072855 to 842089350
Jul 02 05:27:31 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/02 05:27:31 [INFO] raft: Compacting logs from 842089351 to 842105842
Jul 22 13:44:58 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 13:44:58 [INFO] serf: Attempting compaction to recover from error...
Jul 22 13:44:58 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 13:44:58 [ERR] serf: Compaction failed, will reattempt after 30s: failed to open new snapshot: open /var/lib/consul/serf/local.snapshot.compact: no space left on device
Jul 22 13:48:06 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 13:48:06 [INFO] serf: Attempting compaction to recover from error...
Jul 22 13:48:06 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 13:48:06 [ERR] serf: Compaction failed, will reattempt after 30s: failed to open new snapshot: open /var/lib/consul/serf/local.snapshot.compact: no space left on device
Jul 22 14:33:46 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 14:33:46 [INFO] serf: Attempting compaction to recover from error...
Jul 22 14:33:46 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 14:33:46 [ERR] serf: Compaction failed, will reattempt after 30s: failed to open new snapshot: open /var/lib/consul/serf/local.snapshot.compact: no space left on device
```

So it tried to start compacting logs again today, I'm guessing when I murdered it's friend.

I'm trying to figure out where all these inodes have gone.  We're a small company, and our dev-ops guy left for another company recently, so I've kind of inherited these nodes...

**Comment by banks** [comment]
Running out of inodes often happens because some process is regularly creating zero-length or very small temp files and they are not being cleaned up. Because they are very small the disk doesn't seem to be full but each one consumes an inode. It's pretty common so there may well be good trouble shooting steps to take on the web that I forget off-hand but I'd check `/tmp` `/var/log` and the other usual suspects.

**Comment by mkeeler** [comment]
@jwalton That compaction today is trying to compact the Serf snapshot and is unrelated to raft. Although its one more symptom of the problem.

**Comment by jwalton** [comment]
@banks Thanks.  I'm running `for i in /*; do echo $i; find $i |wc -l; done`.  It's getting stuck somewhere in /nix/store, so I'm digging around in there.  If you're not familiar with nix, this is where nix stores... everything.  It's like the node_modules of the nix world.

**Comment by jwalton** [comment]
`rm /tmp/consul-notications.log && nix-collect-garbage -d` is deleting rather a lot of files.  I'm up to 1M free inodes and counting.  I'm going to let this run for a bit, then try to resync raft.db, and then we'll see what state the world is in.

**Comment by jwalton** [comment]
OK, so let's give these servers some names to make this easier:

"consul1" was leader, with the sensible raft.db size of 62MB.
"consul2" and "consul3" had full disks, no inodes, 25GB raft.db, and consul2 stopped compacting on Jul 2nd.

I just ran `nix-collect-garbage -d` on all three nodes.  On "consul2" and "consul3" it freed up on the order of 12.5Gs and millions of inodes.  On consul2 I had already deleted raft.db - when I restarted consul it came up and synced and raft.db was about 25M (it's since grown to 40M).  consul3 still has a 25GB raft.db, but my consul cluster is now behaving sanely, so I'll let this sit for a little bit and see if it starts compacting again now that all three nodes are in more sensible states.

**Comment by jwalton** [comment]
Ok, all three nodes are now printing messages claiming they are compacting... but consul3 still has a 25GB raft.db file.  :P  Logs from it from today are:

```
Jul 22 13:44:58 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 13:44:58 [INFO] serf: Attempting compaction to recover from error...
Jul 22 13:44:58 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 13:44:58 [ERR] serf: Compaction failed, will reattempt after 30s: failed to open new snapshot: open /var/lib/consul/serf/local.snapshot.compact: no space left on device
Jul 22 13:48:06 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 13:48:06 [INFO] serf: Attempting compaction to recover from error...
Jul 22 13:48:06 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 13:48:06 [ERR] serf: Compaction failed, will reattempt after 30s: failed to open new snapshot: open /var/lib/consul/serf/local.snapshot.compact: no space left on device
Jul 22 14:33:46 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 14:33:46 [INFO] serf: Attempting compaction to recover from error...
Jul 22 14:33:46 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 14:33:46 [ERR] serf: Compaction failed, will reattempt after 30s: failed to open new snapshot: open /var/lib/consul/serf/local.snapshot.compact: no space left on device
Jul 22 15:42:20 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 15:42:20 [INFO] raft: Compacting logs from 842105843 to 856805850
Jul 22 15:42:21 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 15:42:21 [INFO] raft: Compacting logs from 842105843 to 856805850
Jul 22 15:57:01 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 15:57:01 [INFO] serf: Attempting compaction to recover from error...
Jul 22 15:57:01 ip-192-168-2-194.shared.vpc consul[1256]:     2019/07/22 15:57:01 [INFO] serf: Finished compaction, successfully recovered from error state
Jul 22 16:47:22 ip-192-168-2-194.shared.vpc consul[16879]:     2019/07/22 16:47:22 [INFO] raft: Compacting logs from 842105843 to 856805850
```

I'm going to delete raft.db and restart this node to get this back to something sensible, unless anyone has something they want me to look at?

**Comment by jwalton** [comment]
(Does raft.db the file ever actually shrink?  Or does compacting just stop it from growing uncontrollably?)

**Comment by mkeeler** [comment]
It will never shrink. Space within the file will be reclaimed but if you want to shrink it you will have to remove that raft data and let it get streamed from the leader fresh.

**Comment by banks** [comment]
> so I'll let this sit for a little bit and see if it starts compacting again now that all three nodes are in more sensible states.

Sounds like you found the fix! FWIW the third server still won't shrink its raft.db on its own. Even when compacting starts (which it should have already - check logs) the file won't get smaller even though there is only going to be ~40MB of actual data stored in it due to the design of BoltDB. Currently the only way to shrink it is to do what you did on consul2 (only when 1 and 2 are both healthy of course!).

**Comment by jwalton** [comment]
Yup, everything is compacting, my nodes are happy.  Somehow when I was debugging this and rebooting nodes, one of my reboots trashed mongodb, but it's just staging, so nothing important lost.

Thanks all for the help diagnosing this!  :D
