### ISSUE TITLE
Probes on Openshift

### ISSUE THREAD

**Issue by kobuti** [hashicorp/consul#6188]
Hi,

I am deploying a consul as a cluster on Openshift in my work. Sometimes, the pods lose connection with each other, and I restart them to rejoin a cluster. Otherwise, the whole cluster will be problematic with the error No Cluster Leader on all of them.

The problem is, I want to automate these processes, and the way we have to do this is doing a liveness probe.  So I have 2 kinds of ways to do this

HTTP GET on a specific path and will return OK to openshift if this response contains a HTTP status between 200 and 399. (In this case, not very helpful because all queries exposed in HTTP API return 200 with error response on body, and openshift reads HTTP STATUS, and do not have any way to read response body)

Container command will consider OK if commands return code 0. (Still looking for a command that ends with other response code  than 0 if no cluster leader is available)

I have been searching for a while on how to do this, but so far, I only managed to perform a curl on server bootstrap, but sometimes this fails which makes me think this is not the best approach.

Have any one solved this problem?

Thanks in advance

**Comment by i0rek** [comment]
@kobuti thanks for reporting. How many consul servers do you have in your setup?

**Comment by kobuti** [comment]
Hi @i0rek, my setup is 

2 servers
1 bootstrap 
3 agents

Best regards

**Comment by i0rek** [comment]
You mentioned that your probes are loosing connection with each other - that is a problem for consul servers. In order for it to work properly the network must be somewhat stable. Consul is designed around failure, but if consul servers are constantly loosing connection it won't work.

We are also no experts in Openshift, please reach out to our mailing list which is in our main readme, maybe someone else can help you.
