### ISSUE TITLE
Better distributed testing of network partition and errors

### ISSUE THREAD

**Issue by h2non** [hashicorp/consul#620]
I've seen you are currently using Jepsen. I think it's a good solution, but the stack setup it's a bit rudimentary, depends on a large stack (including JVM) and it's hard to configure and the programmatically control over testing

I'm want to propose another solution which I've used some months ago which could be really more simple and satisfies essentially the same goals.
I'm talking about [blockade](https://github.com/dcm-oss/blockade), and it was in fact inspired in Jepsen.

It's a Python utility which creates Dockers and uses tc/iptables to infer network latencies, failures and isolation in the containers VLAN 

In fact, I've created a repo to test a Consul cluster and see if it behaves properly in multiple failover and isolation scenarios, however this is still a work in progress. Just take a look:
https://github.com/innotech/consul-cluster-test

**Comment by armon** [comment]
This looks great! Keep us up-to-date on your progress of setting up a blockade environment. I would love to get more testing in place with more advanced failure cases

**Comment by darron** [comment]
I also did this with Vagrant and some Rake commands - it worked pretty well to partition nodes and kill network connections etc.

I will see if I'm able to release it.

**Comment by slackpad** [comment]
Marking this to look at this (or something newer) for an integrated CI solution.

**Comment by slackpad** [comment]
There hasn't been much movement on this so I don't think it adds much to keep it open. We are working on improving our CI and also plan to re-run Jepsen in the near future.
