### ISSUE TITLE
error getting server health from <server> context deadline exceeded

### ISSUE THREAD

**Issue by orarnon** [hashicorp/consul#6208]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Consul master node gets warning messages:
[WARN] consul: error getting server health from <server>: context deadline exceeded
We all see spikes in latency for DNS queries as well as raft transaction time.
CPU is low.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 2
	services = 1
build:
	prerelease =
	revision = ea5210a3
	version = 1.4.4
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 36
	goroutines = 190
	max_procs = 36
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 16735
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 629
	member_time = 4683446
	members = 2625
	query_queue = 0
	query_time = 356
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 5
	checks = 5
	services = 6
build:
	prerelease =
	revision = ea5210a3
	version = 1.4.4
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 0
	leader = true
	leader_addr = 10.200.1.154:8300
	server = true
raft:
	applied_index = 595827285
	commit_index = 595827285
	fsm_pending = 0
	last_contact = 0
	last_log_index = 595827285
	last_log_term = 83859
	last_snapshot_index = 595815855
	last_snapshot_term = 83859
	latest_configuration = [{Suffrage:Voter ID:673e0ff3-815a-4c56-0b5b-1ccf17d7a7d1 Address:10.200.1.154:8300} {Suffrage:Voter ID:36660a37-bc45-8acf-d294-e5693bfe19fa Address:10.200.2.72:8300} {Suffrage:Voter ID:c07d93ea-8d79-bdd3-4564-fbbd5a35ca97 Address:10.200.3.166:8300}]
	latest_configuration_index = 595815683
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 83859
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 88194
	max_procs = 4
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 16735
	failed = 0
	health_score = 0
	intent_queue = 1
	left = 8
	member_time = 4683438
	members = 2004
	query_queue = 0
	query_time = 356
```

</details>

### Operating system and Environment details

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty

Instance type:
c5d.2xlarge

All servers are in the same availability zone (AWS).

### Log Fragments

We get these:
2019/07/24 11:49:57 [WARN] consul: error getting server health from "server": context deadline exceeded

These come in bursts from the master node to its peers - nothing else related in terms of log.

**Comment by pearkes** [comment]
Hey @orarnon unfortunately there is never one cause for these messages. We've documented common issues here associated with it:

https://www.consul.io/docs/common-errors.html#deadline-exceeded

The best thing I can recommend is monitoring the hosts and network Consul is running on and potentially increasing capacity based on what that shows. There is no single answer, sadly.

**Comment by orarnon** [comment]
Hi

Well, I agree there but maybe you can provide some guidance.
When our services begin to flap, we experience a register\de-register "storm" which kills Consul. This is our theory but we're not sure.
That's an example of what happens during such a storm:
**Register time skyrocketing**
![image](https://user-images.githubusercontent.com/3972988/63415465-76978480-c406-11e9-9f99-e7ba00961d04.png)

**RPC Queries**
![image](https://user-images.githubusercontent.com/3972988/63415551-96c74380-c406-11e9-9e14-de39d1f60961.png)

**Raft**
![image](https://user-images.githubusercontent.com/3972988/63415609-acd50400-c406-11e9-8318-a7f496539b18.png)
![image](https://user-images.githubusercontent.com/3972988/63415628-b3fc1200-c406-11e9-944b-84ae9d341971.png)

**KV Store Apply time**
![image](https://user-images.githubusercontent.com/3972988/63415668-c1190100-c406-11e9-974f-b22834663833.png)

**Consul Health Service Query**
![image](https://user-images.githubusercontent.com/3972988/63415743-d68e2b00-c406-11e9-9da0-b72d6efce510.png)

We don't want to leave Consul for the moment but these issues are bringing our production down.
The only thing that helps with this storm, is killing consul-template on a lot of servers.

**Comment by orarnon** [comment]
When there's no outage, we still see these errors a lot, so I ran strace, maybe it can help:
https://gist.github.com/orarnon/fbdae850ec877bdd30560df1dd697be2
