### ISSUE TITLE
Docs: Clarify 'bind', 'dnsmasq' and 'unbound' do not work on systemd

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#6217]
I've been struggling to get consul running on ubuntu 18.04 for several days. 
The learn page shows several methods for forwarding dns including:

- Bind
- Dnsmasq
- Unbound
- systemd-resolvd
- iptables

I've tried the first 3 options with no luck. 
If you are running systemd, are `bind` `dnsmasq` and `unbound` solutions not an option? This issue seems to indicate that is the case.  https://github.com/hashicorp/consul/issues/4155 

Please clarify that `bind`, `dnsmasq`, and `unbound` setup options are not an option for systems running systemd.

**Comment by i0rek** [comment]
@spuder thanks for reporting! I will forward that to our education team!

**Comment by Justdoit2** [comment]
test

**Comment by blake** [comment]
Thanks for the report, @spuder. The learn guide was just updated to include instructions on how to disable systemd-resolved so that you can use these other resolvers to forward DNS to Consul.

https://learn.hashicorp.com/tutorials/consul/dns-forwarding
