### ISSUE TITLE
acl: Token API should return TTL

### ISSUE THREAD

**Issue by msbit01** [hashicorp/consul#6218]
Consul 1.5.0 added optional acl token expiration TTLs, which is awesome, but now I'm not seeing a way to check what the TTL is on a token. The "read" API does not include that information: https://www.consul.io/api/acl/tokens.html#read-a-token

Is there a way to check when a token will expire? If not, would it be reasonable to add something to the API for this?

**Comment by rboyer** [comment]
Setting an expiration time on an ACL token using a TTL is a convenience feature. It is converted into an explicit expiration time before being persisted to the underlying database.

If you read a token that has has an expiration time it will come back in a field named [`ExpirationTime`](https://www.consul.io/api/acl/tokens.html#expirationtime)

**Comment by msbit01** [comment]
Ah, my mistake, I hadn't noticed the ExpirationTime. Thank you!
