### ISSUE TITLE
How to use environment variables is unnecessarily difficult to figure out

### ISSUE THREAD

**Issue by trondhindenes** [hashicorp/consul#6228]
#### Overview of the Issue
It's next to impossible to figure out how to configure Consul using environment variables based on the documentation

#### Reproduction Steps
For instance, I'm trying to figure out how to set the `--node` parameter for the agent using envvars (this is just an example)

Reading https://www.consul.io/docs/agent/options.html, it looks like I can use a config file, regular command params or environment variables to configure. There's no other mention of environment variables or any info such as:
- how envvars map to command-line flags
- is any prefixing/upper-casing required
- etc

in my opinion the whole config section could use a good ol' rewrite, but at least provide some information. I'm seing hints of upper-casing and prefixing with `CONSUL_` to get the right env var name to use, but there's actually no documentation of this anywhere.

We're really happy with Consul, but its documentation is very painful to use.

**Comment by tristan-weil** [comment]
There is a list of envvars here https://www.consul.io/docs/commands/index.html (but you probably found it).
I don't think there's an automatic mapping for all options.

**Comment by trondhindenes** [comment]
yeah, it's quirky for sure. Why not "flatten" the documentation so that each setting documents its cli-arg, config file attr and envvar in a structured way?

**Comment by i0rek** [comment]
@trondhindenes thanks for reporting, I will forward that to our education team.

**Comment by lkysow** [comment]
I don't think you can actually set any config values via environment variable for clients or servers.
The env vars are only used when running consul cli commands against running clients and servers.

`CONSUL_HTTP_ADDR` isn't used:
```
$ consul agent -data-dir=/tmp/consul | grep "Client Addr"
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)

$ CONSUL_HTTP_ADDR=192.168.0.1 consul agent -data-dir=/tmp/consul | grep "Client Addr"
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
```

`CONSUL_CACERT` isn't used:
```
$ consul agent -data-dir=/tmp/consul -server -hcl='verify_outgoing=true'
==> Starting Consul agent...
...
    2019/12/09 17:11:49 [WARN] agent: Node name "lkysow.local" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
==> Error starting agent: VerifyOutgoing set, and no CA certificate provided!
    2019/12/09 17:11:49 [INFO] agent: Exit code: 1


$ CONSUL_CACERT=$(pwd)/consul-agent-ca.pem consul agent -data-dir=/tmp/consul -server -hcl='verify_outgoing=true'
==> Starting Consul agent...
...
==> Log data will now stream in as it occurs:

    2019/12/09 17:25:39 [WARN] agent: Node name "lkysow.local" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
==> Error starting agent: VerifyOutgoing set, and no CA certificate provided!
    2019/12/09 17:25:39 [INFO] agent: Exit code: 1
```
