### ISSUE TITLE
Create API endpoint to return a check's script, interval, HTTP, TTL

### ISSUE THREAD

**Issue by pete0emerson** [hashicorp/consul#623]
I'd like an API call to return a check's script, interval, HTTP, and TTL. Ideally this would be exposed in the UI as well, but I'll create a separate ticket for it.

My use case:

I'm planning on using consul as a Nagios replacement. When I am debugging an issue, the first thing I want to do is replicate the check by hand and see how the check is failing. This is also useful when adding new checks, sometimes the author of a new check doesn't get the check right the first time around.

I would think this could be returned via v1/agent/checks as it would just add four fields, but Armon thinks this would cause backwards incompatibility. See https://groups.google.com/forum/?hl=en#!topic/consul-tool/QsvHza81HFo for discussion.

**Comment by micahhausler** [comment]
+1

**Comment by andrewhlin** [comment]
+1

**Comment by blalor** [comment]
I'll add another +1 to this.  The check config is persisted in the agent's data directory, but that's really peeking behind the curtain.

**Comment by wingsofovnia** [comment]
+1 too. Im writing a Service Discovery Consul wrapper and need to retrieve info about http check interval and it's type, but /v1/agent/checks doesn't report such info...

**Comment by Blatwurst** [comment]
+1 - good just for debugging misbehaving checks, like checking that the supplied command line (script) or url (http) is correct.

**Comment by cirocosta** [comment]
I'm not sure if it helps but on my side, I've been just encoding the check definitions as JSON and persisting that in 'notes'  such that it can be retrieved later. Not the super best option as it's not "first-class"  but it's been doing the job so far. Maybe it fits your needs :grin:

**Comment by psyhomb** [comment]
@cirocosta that sounds like a good workaround, thx

**Comment by aburmeis** [comment]
There seem to be some endpoints capable of doing so but the implementations is either incomplete or buggy:
* `/v1/health/service/:name` contains an always empty `Definition` for each check
* `/v1/agent/health/service/name/:name` contains a filled `Definition` but it seems to be broken as al values are defaults not reflecting the real state (like `Interval`: `0s`)
Would it be more usefull to fix the existing endpoints instead of creating even more?!

**Comment by crhino** [comment]
Closing this in favor of #1680, it has the most 👍 's.
