### ISSUE TITLE
Doc: 'Learn.hashicorp' encryption page runs step 3 and step 4 together

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#6232]
The rendering is messed up on the agent-encryption page of the learn guide. 

https://learn.hashicorp.com/consul/security-networking/agent-encryption

The markdown appears fine in github preview. 

Notice how step 3 and 4 code blocks run together? 

<img width="1182" alt="Screenshot 2019-07-28 20 49 54" src="https://user-images.githubusercontent.com/242382/62018806-7abee200-b179-11e9-99d7-cf6ae8ea86c7.png">

This is the page where the bug is
https://github.com/hashicorp/consul/edit/master/website/source/docs/guides/agent-encryption.html.md

There must be some escape character missing.

**Comment by kaitlincarter-hc** [comment]
Hi @spuder, thanks for creating this issue. We fixed the code snippet causing this misconfiguration.
