### ISSUE TITLE
Expose check configuration in UI

### ISSUE THREAD

**Issue by pete0emerson** [hashicorp/consul#624]
If [#623](https://github.com/hashicorp/consul/issues/623) is accepted, then exposing check configuration (script, HTTP, Interval, TTL) in the UI is the next logical step.

Use case: I'm planning on replacing Nagios with Consul, and when checks fail I want to be able to trace them back to the source and run the checks manually.

**Comment by Blatwurst** [comment]
+1 - would be great for debugging misbehaving checks

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then (and if #623 is accepted).
