### ISSUE TITLE
Request better documentation

### ISSUE THREAD

**Issue by dibyajyotiron** [hashicorp/consul#6240]
Is it possible to write a better documentation? The documentation is utter right garbage, examples are not there, even deprecated things are not removed from the docs ! Worst documentation for an incredible product! Please improve it.

**Comment by i0rek** [comment]
Thank you for letting us know. We are constantly working on making it better, but there surely are areas that need improvement! If you have something more specific in mind it would be great if you could tell us.

Please be more polite in future as per our [community guidelines](https://www.hashicorp.com/community-guidelines). Saying the documentation is garbage is inappropriate.

**Comment by judithpatudith** [comment]
Hi, @dibyajyotiron I'm on our technical writing team, and I just wanted to reach out to make sure that you know about [learn.hashicorp.com](https://learn.hashicorp.com/consul). All our tutorials and examples live there, and I hope you'll find them helpful. 

The documentation itself is also open-source (it lives [here](https://github.com/hashicorp/consul/tree/master/website/source/docs)) so if you find specific thing's you'd like to improve we'd love contributions, or if you'd rather open issues for docs bugs, they are welcome as well. 

We're a pretty small (and new) team and Consul is a fast-moving project. I hope you'll understand that we're doing our best to improve the docs as fast as we can, and we'd love to see you get more involved in the effort! Thanks for caring enough to flag it. All the best.
