### ISSUE TITLE
Increase size of documented gossip encryption key size

### ISSUE THREAD

**Issue by freddygv** [hashicorp/consul#6244]
Currently Consul's docs state that gossip encryption keys must be 16 bytes long. However, the underlying `memberlist` library, allows for 16, 24, and 32 byte keys (supporting AES 128, 192, and 256).

Consul should move the default key size to 32 bytes so that gossiped messages are encrypted with AES 256. This would be an improvements for users who expect or require AES 256 to encrypt their data.

Currently AES 256 is supported for gossip encryption, but it's not documented. This proposal is to change the default in the key generator as well as the related documentation and tests.

Lastly, Consul would continue to allow 16-byte gossip encryption keys. These would no longer be generated by the `keygen` command.

**Comment by freddygv** [comment]
Will be in upcoming release, closing.

**Comment by kmcquade** [comment]
@freddygv - There is no referenced PR here. Where was this added?

**Comment by freddygv** [comment]
@kmcquade I'm having trouble finding the PR, but here's the commit:
https://github.com/hashicorp/consul/commit/1a14b94441dbd715fcb83d78c99fe87de9ad01ea

**Comment by blake** [comment]
I was able to locate this in https://github.com/hashicorp/consul/pull/6388. That commit SHA doesn't seem to be present in any PRs other than this one.

**Comment by kmcquade** [comment]
Thanks everyone. I really appreciate it. I’m sure this will help others who are wondering the same thing in the future.
