### ISSUE TITLE
HTTP2 ping health check

### ISSUE THREAD

**Issue by edio** [hashicorp/consul#6260]
### Feature Description

Consul offers _HTTP + Interval_ and _gRPC + Interval_ checks already.

As HTTP2 is getting more widespread it would be nice to have health-checks for HTTP2 services and gRPC services that do not implement gRPC health-checking protocol.

HTTP2 offers a special `PING` frame _for measuring a minimal round-trip time from the sender, as well as determining whether an idle connection is still functional_
https://http2.github.io/http2-spec/#PING

The check should also have configurable timeout, so slow apps could be considered unhealthy

#### Use Case(s)

Convenient native health checks for
* HTTP2 applications
* gRPC applications without support for gRPC health-checking protocol

---
I'd be willing to submit a PR if there's interest in this feature

**Comment by pearkes** [comment]
> I'd be willing to submit a PR if there's interest in this feature

Definitely! As you describe it sounds interesting, but there may be more detailed feedback in PR discussion.
