### ISSUE TITLE
Gossip Storm Causing Leader Elections and Slowness

### ISSUE THREAD

**Issue by pauloconnor** [hashicorp/consul#6289]
#### Overview of the Issue

We're currently expecting an issue where one of our consul clusters is experiencing a constant leader election, due to what we believe is a gossip storm. Our cluster had ~500 more nodes added to it - each of these nodes was doing a single KV watch. This additional load caused multiple leader elections, and degraded performance.

We are not seeing any resource exhaustion on any of the cluster servers. Over a number of seconds, we observed cluster servers leaving and rejoining

<img width="1575" alt="consul_memberlist_msg_suspect" src="https://user-images.githubusercontent.com/465717/62631710-10503380-b929-11e9-9577-e71f05c93199.png">

<img width="1656" alt="leader transactions per minute" src="https://user-images.githubusercontent.com/465717/62631711-10503380-b929-11e9-871d-ef574e3b5de5.png">

<img width="1651" alt="leader_last contact" src="https://user-images.githubusercontent.com/465717/62631713-10e8ca00-b929-11e9-8a0e-73ba0034b147.png">

<img width="1652" alt="lan failed" src="https://user-images.githubusercontent.com/465717/62631714-10e8ca00-b929-11e9-8b90-41b4989703fd.png">

<img width="1647" alt="catalog register timings" src="https://user-images.githubusercontent.com/465717/62631715-10e8ca00-b929-11e9-85de-a11798f47aed.png">

<img width="1652" alt="apply timings" src="https://user-images.githubusercontent.com/465717/62631717-10e8ca00-b929-11e9-8643-8e1aed5df668.png">

```
$ consul members | grep server | head -5
consul-server-asg-iad-default-d9y9                 10.0.229.222:8301   left    server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-gqu5                 10.0.133.148:8301   failed  server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-lc2r                 10.0.50.29:8301     alive   server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-vesd                 10.0.244.83:8301    left    server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-vw67                 10.0.95.219:8301    alive   server  1.2.3  2         prod-us-east-1  <all>
```

```
$ consul members | grep server | head -5
consul-server-asg-iad-default-d9y9                 10.0.229.222:8301   left    server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-gqu5                 10.0.133.148:8301   left    server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-lc2r                 10.0.50.29:8301     alive   server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-vesd                 10.0.244.83:8301    alive   server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-vw67                 10.0.95.219:8301    alive   server  1.2.3  2         prod-us-east-1  <all>
```

```
$ consul members | grep server | head -5
consul-server-asg-iad-default-d9y9                 10.0.229.222:8301   left    server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-gqu5                 10.0.133.148:8301   left    server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-lc2r                 10.0.50.29:8301     alive   server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-vesd                 10.0.244.83:8301    alive   server  1.2.3  2         prod-us-east-1  <all>
consul-server-asg-iad-default-vw67                 10.0.95.219:8301    alive   server  1.2.3  2         prod-us-east-1  <all>
```

We also observed consul.memberlist.msg.suspect climbing drastically at the same time.

#### Reproduction Steps

We haven't made any changes to this cluster in many months, and cannot reproduce this easily, as it's a production system.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 1
	check_ttls = 0
	checks = 2
	services = 3
build:
	prerelease =
	revision = 48d287ef
	version = 1.2.3
consul:
	known_servers = 5
	server = false
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 78
	max_procs = 8
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3012
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 282
	member_time = 301891
	members = 3341
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 2
	services = 3
build:
	prerelease =
	revision = 48d287ef
	version = 1.2.3
consul:
	bootstrap = false
	known_datacenters = 36
	leader = true
	leader_addr = 10.0.95.219:8300
	server = true
raft:
	applied_index = 5973652107
	commit_index = 5973652234
	fsm_pending = 128
	last_contact = 0
	last_log_index = 5973652234
	last_log_term = 6355
	last_snapshot_index = 5973637418
	last_snapshot_term = 6341
	latest_configuration = [{Suffrage:Voter ID:41c4d076-fe6c-5c18-180b-cd4ab09b26aa Address:10.0.95.219:8300} {Suffrage:Voter ID:8c37560f-d160-c327-fcc1-54da4a3c5a56 Address:10.0.142.77:8300} {Suffrage:Voter ID:acf53dfa-b07f-10c5-cb04-86829dc6c3b3 Address:10.0.133.148:8300} {Suffrage:Voter ID:7523067c-e736-3057-3993-39180b31979c Address:10.0.244.83:8300}]
	latest_configuration_index = 5973648616
	num_peers = 3
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 6355
runtime:
	arch = amd64
	cpu_count = 16
	goroutines = 91656
	max_procs = 16
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 3011
	failed = 4
	health_score = 4
	intent_queue = 1
	left = 642
	member_time = 301880
	members = 3700
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 191720
	members = 181
	query_queue = 0
	query_time = 1```

</details>

### Operating system and Environment details

All hosts running Xenial on AWS

### Log Fragments

```
    2019/08/07 07:05:26 [ERR] raft: Failed to pipeline AppendEntries to {Voter acf53dfa-b07f-10c5-cb04-86829dc6c3b3 10.0.133.148:8300}: write tcp 10.0.95.219:33264->10.0.133.148:8300: i/o timeout
```

```
    2019/08/07 07:05:25 [ERR] consul.session: Apply failed: timed out enqueuing operation
    2019/08/07 07:05:26 [ERR] consul.session: Invalidation failed: timed out enqueuing operation
```

```
    2019/08/07 06:28:04 [DEBUG] http: Request GET /v1/status/leader (33.542µs) from=10.128.77.47:7328
    2019/08/07 06:28:04 [DEBUG] http: Request GET /v1/status/leader (34.286µs) from=10.128.207.63:52987
    2019/08/07 06:28:04 [DEBUG] http: Request GET /v1/status/leader (34.765µs) from=10.128.144.88:2327
    2019/08/07 06:28:04 [DEBUG] http: Request GET /v1/status/leader (31.212µs) from=10.128.225.254:12904
```

```
   2019/08/07 06:28:08 [DEBUG] memberlist: Stream connection from=10.0.115.4:29991
   2019/08/07 06:28:09 [INFO] serf: EventMemberFailed: consul-server-asg-iad-default-vw67 10.0.95.219
   2019/08/07 06:28:09 [INFO] consul: Removing LAN server consul-server-asg-iad-default-vw67 (Addr: tcp/10.0.95.219:8300) (DC: prod-us-east-1)
```

More logs https://gist.github.com/pauloconnor/6fa9199b7fc6b77be2e63d6747517639

**Comment by pierresouchay** [comment]
Can you try using KV watches with ?stale parameter (to avoid hammering the consul leader)? Does it changes something?

**Comment by pauloconnor** [comment]
I believe we allow stale results. Our working theory atm is that the amount of gossip traffic is over loading the cluster.

**Comment by pierresouchay** [comment]
Probably fixed by https://github.com/hashicorp/consul/pull/8343
