### ISSUE TITLE
config_dir giving an error with 0.5rc1

### ISSUE THREAD

**Issue by darron** [hashicorp/consul#629]
`Sourcing config file.
==> Error decoding '/etc/consul/config.json': Config has invalid keys: config_dir`

Easy fix on my end - but not expected and didn't see that change in the CHANGELOG.

It does work on the command line as `-config-dir` - was it just an accident it didn't error out before?

```
Consul v0.5.0rc1-2-g1908701.rc1 (190870179a39b7d4ac3a74e80374dbe9a5ed159c)
Consul Protocol: 2 (Understands back to: 1)
```

**Comment by ryanuber** [comment]
@darron was this working before? I do not see where a config_dir was supported in the code. Previously consul would have silently ignored this, but in 0.5.0 we are adding a more strict config checker which catches unknown config keys.

**Comment by ryanuber** [comment]
@darron related: #71

**Comment by ryanuber** [comment]
I'm going to close this out since it sounds like you figured it out, and it was just a mistake on our end that this didn't error before. Thanks!

**Comment by darron** [comment]
Yes - it just looks like it didn't error before - thanks for checking into it!
