### ISSUE TITLE
seeing weird issue with ServiceID after registering with local agent. ServiceID is duplicated starting with lowercase alphabet

### ISSUE THREAD

**Issue by sushovan23** [hashicorp/consul#6292]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
We are registering many telegraf agents to consul using the ServiceID and serviceName as Telegraf via python script interacting with consul rest apis.

After a few days when we add more telegraf agents using same ServiceID and serviceName as Telegraf

It starts to register them with Telegraf and telegraf.

Its showing both Telegraf and telegraf as services in UI and all nodes are duplicated. Inturn causes prometheus to show duplicate timeseries metrics as serviceName is a label and its case sensitive.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a single agent consul. 
2. Add nodes running telegraf and use catalog service register api to register the nodes with serviceID/serviceName of Telegraf
3. After a few days add few more 100 nodes with same serviceID/serviceName. 
4. You will see telegraf and Telegraf appear in UI with all nodes duplicated in both serviceIDs.

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 34eff659
        version = 1.5.0
consul:
        acl = disabled
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 127.0.0.1:8300
        server = true
raft:
        applied_index = 88198
        commit_index = 88198
        fsm_pending = 0
        last_contact = 0
        last_log_index = 88198
        last_log_term = 6
        last_snapshot_index = 87985
        last_snapshot_term = 6
        latest_configuration = [{Suffrage:Voter ID:67e0d355-4936-1643-ccff-9e36844785e0 Address:127.0.0.1:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 6
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 1861
        max_procs = 2
        os = linux
        version = go1.12.1
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 6
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1

```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.
3.10.0-862.14.4.el7.x86_64 Linux
### Log Fragments

```
/opt/consul/bin/consul catalog services
CouchbaseExporter
Telegraf
consul
telegraf

/opt/consul/bin/consul services deregister -id=telegraf
Deregistered service: telegraf

2019/08/07 18:32:53 [WARN] agent: Failed to deregister service "telegraf": Service "telegraf" does not exist
```

**Comment by pierresouchay** [comment]
I think the ID of your service is not telegraph, try de registering by name instead, can you dump the result of `curl localhost:8500/v1/health/service/telegraph` ?

**Comment by sushovan23** [comment]
if you see the catalog services command output 
its showing Telegraf and telegraf

**Comment by sushovan23** [comment]
showing two of the items from the output of the command. its more than 3000 nodes:
```
{
	"Node": {
		"ID": "",
		"Node": "xyz",
		"Address": "xyz",
		"Datacenter": "",
		"TaggedAddresses": null,
		"Meta": {
			"prom_instance": "Linux-InfraStructure-Prometheus-6",
			"proxy": "True"
		},
		"CreateIndex": 87095,
		"ModifyIndex": 87095
	},
	"Service": {
		"ID": "Telegraf",
		"Service": "Telegraf",
		"Tags": [],
		"Address": "",
		"Meta": null,
		"Port": 9126,
		"Weights": {
			"Passing": 1,
			"Warning": 1
		},
		"EnableTagOverride": false,
		"ProxyDestination": "",
		"Proxy": {},
		"Connect": {},
		"CreateIndex": 87095,
		"ModifyIndex": 87095
	},
	"Checks": []
},
"Node": {
	"ID": "",
	"Node": "abc",
	"Address": "abc",
	"Datacenter": "",
	"TaggedAddresses": null,
	"Meta": {
		"prom_instance": "Linux-InfraStructure-Prometheus-5",
		"proxy": "True"
	},
	"CreateIndex": 87095,
	"ModifyIndex": 87095
},
"Service": {
	"ID": "telegraf",
	"Service": "telegraf",
	"Tags": [],
	"Address": "",
	"Meta": null,
	"Port": 9126,
	"Weights": {
		"Passing": 1,
		"Warning": 1
	},
	"EnableTagOverride": false,
	"ProxyDestination": "",
	"Proxy": {},
	"Connect": {},
	"CreateIndex": 87095,
	"ModifyIndex": 87095
},
"Checks": []
}
```

**Comment by pierresouchay** [comment]
It is not clear to me with your sample whether this is a problem (nodes are different, why is case different... Several stuffs registering differently?)
have a look to https://github.com/hashicorp/consul/issues/5707

But I don't really get the issue with your data for now

**Comment by sushovan23** [comment]
I see the issue you mentioned, But what I'm seeing is slightly different. We only registered with  Telegraf but automatically we also see telegraf being listed in services. We never registered with telegraf (lower case) but still its showing in UI and consul data. 
we have prometheus using consul for service discovery so it sees same node with two services Telegraf and telegraf.

**Comment by sushovan23** [comment]
@pierresouchay Thanks for pointing to correct direction. Definitely we see that some registrations were done with telegraf causing all registrations to be duplicated as not all consul apis are case sensitive which is pointed in the other post

**Comment by pierresouchay** [comment]
What is indeed weird is that both have the same index

**Comment by pierresouchay** [comment]
@sushovan23 did you find the reason?

**Comment by sushovan23** [comment]
@pierresouchay Yes there were a few registrations with `telegraf` instead of `Telegraf` 
it was causing list of nodes to be duplicated for both of them.
this can be closed.
