### ISSUE TITLE
dns all dcs

### ISSUE THREAD

**Issue by gistao** [hashicorp/consul#6295]
I have three data centers. I want to get an instance after global load balancing(3 dcs) through by dns, but I can't find a way. What should I do?

**Comment by tristan-weil** [comment]
Hello,

I am not sure if I understand correctly, but you should look at Connect (https://learn.hashicorp.com/consul/getting-started/connect) and Prepared Queries (https://learn.hashicorp.com/consul/developer-discovery/geo-failover).

I hope this will help you

**Comment by gistao** [comment]
sorry，let me repeat that.

I have a service A, deployed 3 instances in dc1, and 2 instances in dc2, and 5 instances in dc3.

I want to use consul dns to achieve global load balancing.

but now, only one dc or failover. 

What should I do? thx

**Comment by i0rek** [comment]
@gistao thanks for reaching out. Please use our mailing list for questions - you can find it in our main readme.
