### ISSUE TITLE
Securing RPC communication with TLS and auto_encrypt doesn't work

### ISSUE THREAD

**Issue by TheManyula** [hashicorp/consul#6297]
I've started setting up single-node cluster on version `1.5.3` and I'm currently following the guide to [securing RPC communication with TLS](https://learn.hashicorp.com/consul/security-networking/certificates#configuring-agents). Note, that I have enabled `auto_encrypt´ with `allow_tls = true`. I started up a fresh instance in bootstrap mode with `verify_incoming = true` and `verify outgoing = true`. So far, so good.

Now, in step 2, I need to change the settings to `verify_incoming = false` and add `verify_incoming_rpc = true` so I can access the UI. Once I do that and restart the instance, I'm getting `==> if auto_encrypt.allow_tls is turned on, TLS must be configured in order to work properly.`

What else can I do to make this work?

**Comment by i0rek** [comment]
@TheVanitas you are correct, thats an issue right now (https://github.com/hashicorp/consul/issues/6338). You can use a consul client to serve the UI until it is fixed.

**Comment by i0rek** [comment]
This should work now, which is why I am closing this issues.
