### ISSUE TITLE
Is it safe to use filepath.Glob to find old log files?

### ISSUE THREAD

**Issue by varnson** [hashicorp/consul#6307]
In file logfile.go, a method called pruneFiles() was added to remove old log files.
It use filepath.Glob() to find log files and delete some files from the top of the list.
Source was listed below:
// Prune if there are more files stored than the configured max
	stale := len(matches) - l.MaxFiles
	for i := 0; i < stale; i++ {
		if err := os.Remove(matches[i]); err != nil {
			return err
		}
	}
But if matches[0] contains the newer log files, it will be deleted and the older one will be kept. And I cannot find any docs which said the filepath.Glob() function would store the oldest file in  matches[0].
So I think it may be a problem.

**Comment by i0rek** [comment]
@varnson thanks for reporting!

> // glob searches for files matching pattern in the directory dir
> // and appends them to matches. If the directory cannot be
> // opened, it returns the existing matches. New matches are
> // added in lexicographical order.

from https://golang.org/src/path/filepath/match.go. This is why it is safe to do that.
