### ISSUE TITLE
central service config resolution can be disregarded in restart and failure conditions

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#6323]
There are several ways a service can end up registered locally on an agent:

1. Registered via HTTP API.
2. Registered via Config File HCL/JSON snippet.
3. Agent cold restart that reloads from persisted copy of (1).
4. Agent hot reload that reloads from (2) and a persisted copy of (1).

Of these, (1) and (4) happen when the agent is fully operational and (2) and (3) happen while the agent is still wiring itself up. Notably config file and persistent reloads _must_ happen before the Agent API is available and anti-entropy starts happening. If that is violated then there may be catalog registration flaps or local uses of the API that see things vanish and come back into existence.

If central service config is enabled any attempt by the agent to register a service locally is diverted through the ServiceManager. This applies equally to (1), (2), (3), and (4). The point of central service config is to only ever surface the _merged config_ in the Agent API and sent to the catalog. The original user-provided (incomplete) service registration should never be seen outside of the agent process. It would be easy to have ServiceManager hard-wait for the necessary RPCs to complete to flatten `proxy-defaults` and `service-defaults` down for use, and that would totally be ok for (1) and (4) but it is impossible for (2) and (3).

Both of those happen while the agent is still wiring itself up and it may not even be able to execute RPCs yet, so the service manager today assumes that errors during the _first_ central service config fetch are acceptable and it just leaks the incomplete registration out into the world. Very quickly after the rest of startup completes the actual central config comes back and the state is corrected.

If anything polls the Agent API during this window of time they'll see the wrong config. This definitely can happen with `consul connect envoy` during bootstrap generation. If you quickly sequence:

1. `consul agent` start
2. `consul services register`
3. `consul agent` restart
4. `consul services (re-)register`
5. `consul connect envoy`

The resulting envoy config randomly will omit things like observability settings from central config. And because the consul binary exec'd away nothing will fix that lack in the envoy without a restart.

**Comment by rboyer** [comment]
Also worth noting that the agent registration that is persisted to disk incorrectly is the _merged_ config in the case of central config being used, instead of the original config.

That incorrect behavior actually masks most occurrences of THIS bug in practice. In my reproduction sequence above it _needs_ that second `register` in order to trigger this bug because the merged config is present in the persisted snapshot.

We can't just fix the incorrect persistence bug without making this bug more obvious.

**Comment by mkeeler** [comment]
> Also worth noting that the agent registration that is persisted to disk incorrectly is the _merged_ config in the case of central config being used, instead of the original config.

This is definitely a bug.

The rest of it though is just how the system needs to work I think. You have the exact same scenario of leaking a partial config if you update some central config value and immediately go and try to pull the latest update. Its racey. I would say the fully resolved service config is eventually consistent and thats about the best we can do without a lot more synchronization. One place this seems problematic is if a gateway is started with the `-register` flag. It will race to 
update the service config with the proxy defaults before the envoy cli command will try to pull the config. Maybe we could add a header to the APIs response to indicate whether full resolution has ever finished. Obviously this wouldn't handle the case where central conf is modified at nearly the same time as we get the config but it could be a way to fix most cases.

Maybe we should persist the relevant config entries associated with the persisted services. When an agent comes back up we can prepopulate the agent cache with those entries. It is a grander idea but couldn't we potentially persist the whole agent cache between restarts.

**Comment by mkeeler** [comment]
I have also thought about making the envoy CLI command manage an Envoy subprocess instead of just exec'ing it. Then our CLI process could continue running and update the envoy config/hot restart as necessary.

**Comment by rboyer** [comment]
My current in-flight solution was to persist the most recently used config entry data alongside of the original service definition and reload it. Also to change the system to persist registration data for Config and API alike (with a flag for which source it came from so that reloads can treat them differently as they already are today).

That would basically switch it so that a consul agent restart picks right up where it left off with regards to things previously registered.

Assuming that was in place, then I think the only other change that would help would be to _require_ that interactive API driven registrations block until the RPC completes successfully once.

There will still be edges, but short of having some sort of (selective) persistent agent cache I'm not sure how to fully remove the edges.

**Comment by rboyer** [comment]
This may become increasingly more relevant as we shift more stuff to be primarily homed in central service config.

**Comment by mkeeler** [comment]
I think your in-flight solution sounds spot on. One question I have is whether API registrations should have to opt-in to the blocking behavior or maybe we should prevent the behavior all together for services that are not:

* typical kind service with a sidecar service definition
* kind connect-proxy
* kind mesh-gateway

Or rather should we default to not blocking the registration for typical services without a sidecar definition.

**Comment by banks** [comment]
> Or rather should we default to not blocking the registration for typical services without a sidecar definition.

One tricky part here is that the near-term goal is to have a central config for enabling sidecars too... That implies every typical service reg _may_ be a sidecar registration as well depending on what central config says. I know when we tried to build this for 1.5.0 there were a lot of edge cases though and needed some re-thinking so it's possible the actual service can still not block but asynchronously have the config checked and if necessary a sidecar added. I think that still prevents this race since it's about proxy config on the sidecar/gateway only.

**Comment by mkeeler** [comment]
That is a good point and another reason it might be good to make the behavior either opt-in or have the capability to opt-out because we have no way of determining if the behavior is wanted. We could potentially allow up to a couple hundred ms and if you want to wait longer you need to specify the max wait time. Regardless of what you are registering and whats in central conf you may or may not want to wait for the fully resolved config (although it should be a very short time unless your DC has no path to the primary yet)

I could also be overthinking things a lot. These RPCs should complete very quickly so having an unconditional blocking for a predefined amount of time is probably fine too.
