### ISSUE TITLE
Connect Secondary CA Intermediate Cert is missing a Subject

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#6330]
The intermediate certificate generated by our leader initialization routines in secondary datacenters is missing a Subject.

According to the [spec](https://tools.ietf.org/html/rfc5280#section-4.1.2.6), if the certificate has the basic constraint with CA=true then the Subject must not be empty.  Therefore we should put a valid subject in there.

**Comment by banks** [comment]
This is no longer true as of 1.7.0 changes now in master.
