### ISSUE TITLE
Docs: Example shows TTL and Interval; results in "Invalid check" error

### ISSUE THREAD

**Issue by huttj** [hashicorp/consul#6343]
#### Overview of the Issue

[The Sample Payload](https://www.consul.io/api/agent/service.html#register-serice) for registering a service via HTTP includes a JSON body with both `Interval` and `TTL`. When using both of these, the API responds with `Invalid check: Interval and TTL cannot both be specified`.

#### Reproduction Steps

1. Run `consul agent -dev`
2. Run `curl http://localhost:8500/v1/agent/service/register -X PUT -d '{"Id":"123456","Name":"test-service","Port":5000,"Check":{"HTTP":"http://localhost:5000/health","Interval":"10s","TTL":"15s”}}’`

### Consul info for both Client and Server

Configuration is default

### Operating system and Environment details

n/a

### Log Fragments

```
2019/08/16 14:34:36 [DEBUG] http: Request PUT /v1/agent/service/register (132.336µs) from=127.0.0.1:60983
2019/08/16 14:34:37 [DEBUG] manager: Rebalanced 1 servers, next active server is joshuahutt-mac.dc1 (Addr: tcp/127.0.0.1:8300) (DC: dc1)
2019/08/16 14:34:40 [DEBUG] consul: Skipping self join check for "joshuahutt-mac" since the cluster is too small
2019/08/16 14:35:19 [DEBUG] agent: Skipping remote check "serfHealth" since it is managed automatically
2019/08/16 14:35:19 [DEBUG] agent: Node info in sync
2019/08/16 14:35:40 [DEBUG] consul: Skipping self join check for "joshuahutt-mac" since the cluster is too small
```

**Comment by kkbatta** [comment]
We are seeing the same issue. Could someone explain why these two have to be mutually exclusive?
I do not want the call back to execute until the check fails 3 times consecutively. I am trying to achieve this by giving interval as 10s and ttl as 31s .  I am sure I am reading something wrong. 
Any pointers towards how this can be achieved will be greatly appreciated.

**Comment by blake** [comment]
> I do not want the call back to execute until the check fails 3 times consecutively.

@kkbatta, if I am understanding correctly, it sounds like you may asking for functionality which was introduced in https://github.com/hashicorp/consul/pull/5739. Does this look like it would satisfy your requirement?
