### ISSUE TITLE
Mesh page on Consul.io spelling error

### ISSUE THREAD

**Issue by Cingulara** [hashicorp/consul#6345]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A spelling mistake on the mesh page that I cannot seem to find in this repo. Its "edit" link on the page goes to a 404. Very minor thing but was bugging me. 😄 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Go to https://www.consul.io/mesh.html
2. see error on "service" misspelled below:

"Service mesh is a new approach to secure the service itself rather than relying on the network. Consul uses centrally managed service policies and configuration to enable dynamic routing and security based on *sevice* identity. These policies scale across datacenters and large fleets without IP-based rules or networking middleware."

### Operating system and Environment details

Any OS, but I am using MacOS with Chrome.

### Log Fragments
None.

**Comment by mkeeler** [comment]
The misspelling is here: https://github.com/hashicorp/consul/blob/6012343e6b9dd7011765067384483cde82f26ee9/website/source/mesh.html.erb#L56

Our website is currently not represented on the master branch.
