### ISSUE TITLE
How to monitor that a key/value has changed

### ISSUE THREAD

**Issue by 727909266** [hashicorp/consul#6353]
How to monitor that a key/value has changed
does there any sdk api in golang

**Comment by slackpad** [comment]
https://www.consul.io/api/features/blocking.html

https://github.com/hashicorp/consul/blob/master/api/kv.go#L60

https://github.com/hashicorp/consul/blob/master/api/api.go#L112-L114

**Comment by 727909266** [comment]
thanks
