### ISSUE TITLE
Connect: Terminating (External Service) Gateways

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#6357]
**Scope:**
 - Needs RFC and UX/design work
 - Maybe ~2 weeks implementation assuming no scope creep

---

In our original Connect launch last year we explained how Connect could be used even to control access to your existing managed services or services that can't be run with an agent and sidecar proxy such as mainframes and legacy infrastructure.

While it's sort of possible to achieve this now by running a proxy in a sidecar mode on a host with a consul client agent and then securing the "private" network between the proxy and the external service such that the only way for other applications to talk to that service is via the Connect "side-car".

But there are a number of limitations that make this not very practical:
 1. Sidecars can only represent a single service right now which makes it impractical to deploy separate "terminating proxy" for many external services. This is already a feature request for regular side-cars in pods where multiple service ports are exposed and so needs to be fixed in general: https://github.com/hashicorp/consul/issues/5388
 2. We currently assume that sidecars speak plain TCP to the "local application". Although we always allowed overriding the IP to point to somewhere explicit, we don't allow for example establishing a TLS connection to a managed service such as a cloud-managed database instance. At the very least here we'd need to make it work with TLS based services and likely need to make things like client certs for the external service configurable etc.
 3. We need dedicated tooling probably in the CLI to make it easy to register and run one of these proxies.
 4. We should probably consider how to manage pools of them so each pool of proxies provides redundancy and throughput scaling to a set of services, but so that multiple distinct pools can be setup for cases where it's important to limit exposure. For example if you have 10 external services all accessible to a set of 3 terminating proxy nodes, they become a very high value target for compromise as they have access to all of those systems. One proxy per external system is inconvenient per 1. but we also shouldn't assume only one set of terminating proxies per DC all with access to everything external.

See internal PRD for more detail.

**Comment by bsakweson** [comment]
Has this been realized? A typical example for this use case is nats-streaming docker image. There are three ports expose for the client, server and monitoring that is ports [4222, 6222, 8222].

**Comment by banks** [comment]
@bsakweson the broader issue here is a work in progress on the Consul team!
We expect to have terminating gateways ready in the next few months which
will _likely_ include the same machinery needed to support multiple service
ports in one sidecar but design isn't finalized yet. If it doesn't we'll
break that into a separate issue again.

**Comment by blake** [comment]
Consul 1.8 is now generally available. In addition to the guide @jsosulska shared, documentation for terminating gateways can also be found at https://www.consul.io/docs/connect/terminating-gateway.

Please reach out on [discuss.hashicorp.com](https://discuss.hashicorp.com/) if you have any questions regarding configuring or using terminating gateways.
