### ISSUE TITLE
more builders

### ISSUE THREAD

**Issue by ceh** [hashicorp/consul#639]
As mentioned in #636, Consul failed to build on Windows when `syscall.Kill` was introduced in f2f980f5bc5baf7187a63edfb9f6248770a38c71.

All supported platforms should have a builder to catch failures as early as possible.

Travis CI does currently not support Windows. See travis-ci/travis-ci#216

Alternatives? https://build.golang.org and http://build.camlistore.org comes to mind.
(Of course, the downside of setting up something custom is that it requires work and infrastructure.)

**Comment by ryanuber** [comment]
@ceh I agree that this would be really nice to have. I think we also want artifact generation for various platforms while using cgo to make our releases less manual, its just not something we've been able to invest in yet.

**Comment by slackpad** [comment]
Closing this out - now that we have no CGO dependencies, our CI build loop builds all the platforms from Linux using `gox`.
