### ISSUE TITLE
consul returned an error

### ISSUE THREAD

**Issue by ptlive1001** [hashicorp/consul#6400]
consul returned an error ,you may have visited a url that is loading an unknow resoure,so you can try going back to the root or try re-submitting you acl token/secretid by going back to acls

**Comment by i0rek** [comment]
@ptlive1001 thanks for reporting! Please provide more information, ideally a way to reproduce your issue so that we can help you.

**Comment by s-christoff** [comment]
Re-opening and allowing stale bot to take its course. Apologies about this :)

**Comment by s-christoff** [comment]
Howdy -
I am going to go ahead and close this issue. If you think it should remain open, please comment back and let us know why!

Thanks!
