### ISSUE TITLE
Auto join using multicast

### ISSUE THREAD

**Issue by Matts966** [hashicorp/consul#6402]
#### Feature Description

Is a feature to join the cluster using multicast like this [code](https://github.com/schollz/peerdiscovery) allowed or planned to be implemented?

I read [this](https://github.com/hashicorp/consul/blob/master/website/source/docs/faq.html.md#q-does-consul-rely-on-udp-broadcast-or-multicast) so I will close this issue if it is not desireble.

#### Use Case(s)

If this feature enabled and there is already an agent in the local network which supports multicast, we can add new node to the cluster without detailed configuration.

**Comment by s-christoff** [comment]
Hey @Matts966 , thank you for bringing this up. As you indicated with the FAQ:
> Consul uses the Serf gossip protocol which relies on TCP and UDP unicast. Broadcast and Multicast are rarely available in a multi-tenant or cloud network environment. For that reason, Consul and Serf were both designed to avoid any dependence on those capabilities.

We do not intend to support multicast or plan to implement it!

**Comment by s-christoff** [comment]
Howdy - after discussing this internally we decided this is something we would like to add, and opened a new issue with more context for us to track.
That issue is here: #6666
