### ISSUE TITLE
Use certificates generated by auto_encrypt for HTTPS API and not only RPC

### ISSUE THREAD

**Issue by timarenz** [hashicorp/consul#6403]
#### Feature Description

As per conversation with @i0rek auto_encrypt today only provisions certificates for RPC. It would be very useful if the same certificates could also be used for TLS access to the HTTP API.

#### Use Case(s)

Users use auto_encrypt to automatically distribute certificates to the Consul client agents. Many enterprise users need to talk to the local HTTP API of the Consul agent using TLS. As auto_encrypt only provisions certificates for RPC and not HTTPS, users today need to deploy additional TLS certificates on the Consul client agent to secure the HTTP API using TLS. Using the same certificates that are provisioned for RPC for local TLS access would be very helpful.

**Comment by i0rek** [comment]
I am trying to think about how the cert should be created. 

* make sure to clearly mark it is client cert so that our TLS code doesn't confuse it with a service or agent cert
* in the beginning it would share the same expiration time like the rest of connect which defaults to 72h. It would be affected by [leaf_cert_ttl](https://www.consul.io/docs/agent/options.html#ca_leaf_cert_ttl) in the beginning
* which ACL privileges are required for this one
* provide CLI and HTTP API access to create client certs
* ironically we want to make sure to use HTTPS because we are transferring private keys. That means that the first cert would have to be fetched from the server. Afterwards that client cert can be used to fetch more even from clients.

**Comment by i0rek** [comment]
@timarenz thoughts? also it would be great if you could explain the use case a little.

**Comment by timarenz** [comment]
Most enterprise users are required to use encrypted communication. This is true for a) RPC and b) TLS for HTTP API. Our best practice is that all communication to the HTTP API is done using the local HTTP API of the Consul agent via localhost. 

This local HTTP API is something that is used in almost any Consul environment via native integration from within an application or using tools like consul-template.

Even though this is local communication it needs to be secured using TLS. This is especially true when Consul is used in Kubernetes and many different services talk to the same Consul agent on the corresponding Kubernetes node.

Without auto_encrypt a user would need to (manually) provision certificates for each Consul agent to secure RPC and HTTP API access. This is really cumbersome and you need additional systems like Vault to automate such a process.

With auto_encrypt today we only automatically provision certificates for RPC. However, as stated before, most customers need TLS encrypted access to the HTTP API as well. This requires them, even though certificates to secure RCP are deployed automatically, to deploy additional certificates to set up TLS access to the HTTP API. This contradicts the usefulness of auto_encrypt for that particular use case as the certificates that are (manually) provisioned by the user can also be used for RPC. 

So, if a user needs to use TLS for the HTTP API there is no benefit in using auto_encrypt. Which is a common setup.

However, if we would also automatically provision certificates that could be used for TLS access to the HTTP API this would greatly improve the user experience as no additional certificates / process would be needed to properly set up a secured Consul agent.

The TLS certificate should include localhost, 127.0.0.1, <node>.node[.datacenter].<domain> as subject alternate names. Also, it might be a good idea to add a configuration parameter in the agent config that allows to specify additional SANs, or at least the FQDN of the system that the Consul agent is running on, to include them as SAN as well. 

One a side note, enabling auto_encrypt and also enabling HTTPs today doesn't result in an error instead the Consul agent starts up without any error but there are handshake errors when you try to connect to the local HTTP API via TLS.

**Comment by i0rek** [comment]
This PR is a step into this direction: https://github.com/hashicorp/consul/pull/6489. If present, the HTTPS listener will be set up with the auto encrypt cert. With `verify_incoming = false` on the client, the HTTPS endpoints can now be used.
