### ISSUE TITLE
Method Not Allowed returned when registering

### ISSUE THREAD

**Issue by kennethkryger** [hashicorp/consul#6412]
If you add a slash "/" at the end for the path "/v1/agent/service/register" when registering a service you get a response with status code 405 "Method Not Allowed".

This seems to me as a bug?

### Operating system and Environment details

I've tried it on Windows 10 running the Consul agent with the "-dev" command line argument.

**Comment by s-christoff** [comment]
Hey, thanks for reporting this! 
This can be a little surprising however this is typically a cosmetic feature that we do not support.
Hope this clarifies things! :)
