### ISSUE TITLE
Go Get Command Failing

### ISSUE THREAD

**Issue by ss25sand** [hashicorp/consul#6414]
#### Overview of the Issue and Error Logs

When I run `go get -u github.com/hashicorp/consul/api`, I get the following message:
```
go: finding github.com/sean-/seed latest
go: finding golang.org/x/sys latest
go: finding github.com/armon/go-metrics latest
go: finding golang.org/x/net latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/sync latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/prometheus/client_model latest
go: finding github.com/armon/circbuf latest
go: finding github.com/tv42/httpunix latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding golang.org/x/tools latest
go: finding github.com/kr/logfmt latest
go: finding github.com/modern-go/concurrent latest
go: finding github.com/alecthomas/template latest
go: finding github.com/alecthomas/units latest
go: finding golang.org/x/xerrors latest
package github.com/hashicorp/consul/api: unknown import path "github.com/hashicorp/consul/api": ambiguous import: found github.com/hashicorp/consul/api in multiple modules:
	github.com/hashicorp/consul v1.4.2 (/Users/ssandhu/Documents/GoFiles/pkg/mod/github.com/hashicorp/consul@v1.4.2/api)
	github.com/hashicorp/consul/api v1.2.0 (/Users/ssandhu/Documents/GoFiles/pkg/mod/github.com/hashicorp/consul/api@v1.2.0)
```
#### Reproduction Steps

1. RUN `go get -u github.com/hashicorp/consul/api`

### Operating system and Environment details

Mac OS, go version go1.12.7 darwin/amd64

**Comment by sev3ryn** [comment]
same issue appears for me. 
Looks like Hashicorp approach to have multiple go.mod files per one repo adds a lot of troubles.

Also same issue goes for vault
```
go: downloading github.com/hashicorp/vault/api v1.0.4
go: extracting github.com/hashicorp/vault/api v1.0.4
go get github.com/hashicorp/vault/api: ambiguous import: found github.com/hashicorp/vault/api in multiple modules:
        github.com/hashicorp/vault v1.1.5 (/Users/sev3ryn/prj/go/pkg/mod/github.com/hashicorp/vault@v1.1.5/api)
        github.com/hashicorp/vault/api v1.0.4 (/Users/sev3ryn/prj/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.4)
```

**Comment by leighmcculloch** [comment]
In `consul` `v1.4.2` there was no `go.mod` file in the `api` subpackage so it can't be used with any version of the `api` subpackage that has its own `go.mod`, otherwise Go will see the import path available from two modules and not know what to do.

Do you have a separate dependency on the `consul` repository at `v1.4.2`? If so, I think you'll need to bump it to at least `consul` `v1.5.0` if you want a newer version of the `api` package, that's the first version of `consul` I see where the `api` directory is it's own module.

**Comment by leighmcculloch** [comment]
I think this issue is relevant: golang/go#29736.

**Comment by leighmcculloch** [comment]
This is one way that the `consul` project could prevent this from happening for folks: ugorji/go#279.

**Comment by mantzas** [comment]
Same issue for me.

**Comment by sev3ryn** [comment]
@mitchellh @rboyer @mkeeler  
It is already month without response - and it is major issue - everyone who depends on consul in there projects can't run `go mod tidy` because of this issue.

**Comment by mantzas** [comment]
@sev3ryn I did actually go with the latest version which fixed my problem.

**Comment by sev3ryn** [comment]
@mantzas thanks,  after few `go get` `go mod tidy` iterations, works for me too,

@everyne  mentioned in my comment above - sorry for bothering!

**Comment by s-christoff** [comment]
Hey, it seems like this is resolved. But if you're still having issues go ahead and comment on this thread. If it is resolved in 30 days the bot will go ahead and automatically close this.

Thank you!

**Comment by bradbl** [comment]
I'm seeing this when getting the latest tagged Vault.

```
$ go get github.com/hashicorp/vault@v1.2.3
Setting GOPROXY to ***
Setting GO111MODULE to on
Using go version go1.12.9 darwin/amd64...
Running command "go get github.com/hashicorp/vault@v1.2.3"...
build github.com/hashicorp/vault: cannot load github.com/hashicorp/consul/api: ambiguous import: found github.com/hashicorp/consul/api in multiple modules:
	github.com/hashicorp/consul v1.4.0 (/Users/bradb/go-code/pkg/mod/github.com/hashicorp/consul@v1.4.0/api)
	github.com/hashicorp/consul/api v1.0.1 (/Users/bradb/go-code/pkg/mod/github.com/hashicorp/consul/api@v1.0.1)
```

**Comment by bradbl** [comment]
FWIW, I believe this is due to improperly carving out the submodules.  See https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository.  Here is a commit from another project which ran into this issue and fixed it: https://github.com/Azure/go-autorest/commit/5bd9621f41a06b08038be5c0522971a35316d5ef.

**Comment by crhino** [comment]
Hi there @bradbl, took a look at the link and commit you referenced. Unfortunately the whole reason we have split `api` and `sdk` out into their separate modules is to not pull in the whole of consul as a transitive dependency in the `go.{mod,sum}`.

Given that, and the fact that updating the required dependency version with a `go mod tidy` should solve the issue, I am going to close this issue out.
