### ISSUE TITLE
example in doc not work.

### ISSUE THREAD

**Issue by schmel** [hashicorp/consul#6438]
Consul v1.5.3

Hi, this example - https://learn.hashicorp.com/consul/developer-discovery/external
not work in clean consul instance. 

```
{
  "Node": "hashicorp",
  "Address": "learn.hashicorp.com",
  "NodeMeta": {
    "external-node": "true",
    "external-probe": "true"
  },
  "Service": {
    "ID": "learn1",
    "Service": "learn",
    "Port": 80
  },
  "Checks": [
    {
      "Name": "http-check",
      "status": "passing",
      "Definition": {
        "http": "https://learn.hashicorp.com/consul/",
        "interval": "30s"
      }
    }
  ]
}
```

consul validate /etc/consul.d
Config validation failed: Error parsing /etc/consul.d/external.json: 1 error(s) decoding:
* 'checks': source data must be an array or slice, got map

Json validate - is OK.

**Comment by dineshba** [comment]
I was able to post the external.json successfully.
```bash
curl --request PUT --data @external.json localhost:8500/v1/catalog/register
```
I am not 100% sure whether service register post json and config json is interchangeable.

**Comment by daledude** [comment]
Using the HTTP API allows snake_case **and** CamelCase. The **config files must** be snake_case only.

[https://www.consul.io/docs/agent/services.html#service-definition-parameter-case](url)

**Comment by schmel** [comment]
ok, i convert example from doc to hcl over https://www.hcl2json.com/

```
"Address" = "learn.hashicorp.com"

"Checks" = {
  "Definition" = {
    "http" = "https://learn.hashicorp.com/consul/"
    "interval" = "30s"
  }

  "Name" = "http-check"
  "status" = "passing"
}

"Node" = "hashicorp"

"NodeMeta" = {
  "external-node" = "true"
  "external-probe" = "true"
}

"Service" = {
  "ID" = "learn1"
  "Port" = 80
  "Service" = "learn"
}
```

this it work, thanks
