### ISSUE TITLE
Flag to ignore/skip bad service check files so consul agent keeps running with other good checks

### ISSUE THREAD

**Issue by varunturlapati** [hashicorp/consul#6444]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

**Problem Context**
Consul agents failing on bad service checks

**Detail**
On a Consul agent one can specify service healthchecks through json files written under /etc/consul/conf/
It is not unusual for each machine (deploying an agent) to have multiple such checks for each service that is running on it. Let’s say there are 100 services each specifying their corresponding healthchecks as svc1.json through svc100.json. Consider:

If any of the json files are invalid, not only does the check not register but also Consul agent goes down (upon restart).
If all the jsons are valid but a/few parameter/s, incompatible with the version of Consul agent is/are present in the check file, the Consul agent goes down (upon restart). For ex, passing a local script healthcheck in a version like 0.9.0 causes Consul agent to fail.

In case 1), it is reasonable to expect validation/linting of json but in case 2) in a heterogeneous setup (mixed versions) clusters are brought down because of an incorrect check param. In large deployments, there are many services that rely on Consul for service discovery. As such, failing the entire service discovery on that node/cluster for one bad param in one bad service check file defeats the purpose of service discovery.

**Alternative solutions**
Treat each json separately and blacklist/ignore/skip the bad files. That way, services 1 to 99 which have correct healthchecks don’t suffer from a bad one newly written.
If changing the default behavior of Consul is not ideal then there should at least be an option to specify the behavior if incorrect values are encountered. For ex, in /etc/consul/consul.conf there could be a parameter “ignore_file_on_error”: true means that if bad files are encountered Consul skips those and continues with the rest.

This gives the developer a chance to fix the check without bringing down the entire node/agent.

#### Use Case(s)

In any combination of the following:

- large deployments
- heterogeneous versions of Consul
- multiple contributors adding service checks

it is hard to predict if a new check will succeed on all clusters. If bad checks are introduced, it is important to let consul agent run with the successful checks instead of failing early.

#### Approach
Introduced a flag `IgnoreBadCheckFiles` which is a boolean. It tells consul agent if it could continue with other checks or it should stop at the first bad check. By default it is false to ensure compatibility with existing consul defaults.
This helps in cases like:

1. Introducing local script checks but the agent config disallows it
2. Typos or bad values like 'interval = -1s'

This doesn't help in cases like:

1. Bad JSON/HCL format (consul validate or Linters could be used)
2. Bad keys like 'htto' or 'intervak'

**Comment by varunturlapati** [comment]
https://github.com/hashicorp/consul/pull/6445

**Comment by tradel** [comment]
See also #6041.

**Comment by varunturlapati** [comment]
Hello! I was wondering if I could get feedback on the outcome of the discussion. I'd love to take up review comments or feedback if available.

**Comment by dnephin** [comment]
hello @varunturlapati , I'd like to make sure I understand the issue correctly. In the description you mention restarting the agent is what causes the problem. Are you stopping the agent, then starting it again? Or are you using [reload](https://www.consul.io/docs/commands/reload) (`consul reload`, or sending SIGHUP) to the agent to have it pick up the new configuration.

If you are using reload, I think #6041 might be the correct solution (as was mentioned above).

If you are stopping the agent then starting the agent, one option might be to first run `consul validate` on the new config. That should catch most of the problems. To handle the different versions you could run `consul validate` with each version that exists in the cluster, so that all versions can confirm that the configuration is correct before stopping any agent. For that approach #7560 might be necessary to ensure that all the services and checks are correct.

**Comment by jsosulska** [comment]
Closing this and https://github.com/hashicorp/consul/pull/6445. See [this comment](https://github.com/hashicorp/consul/pull/6445#issuecomment-685935450) for more information.
