### ISSUE TITLE
Building from release

### ISSUE THREAD

**Issue by hoffoo** [hashicorp/consul#645]
Is it possible to use the releases from here to build consul: https://github.com/hashicorp/consul/releases

It doesn't seem like it since they don't include .git,:

```
package github.com/hashicorp/consul: directory "/home/dev/go/src/github.com/hashicorp/consul" is not using a known version control system
```

**Comment by ryanuber** [comment]
@hoffoo probably not with the Makefile, since we ensure from there that all of the deps are available. You might be able to build using plain old `go build` in the consul directory, but YMMV.
