### ISSUE TITLE
Envoy: support validating root certificates and serial/hash during AuthZ

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#6455]
This is mostly a placeholder ticket for an issue we need to create against Envoy when we have a concrete proposal.

This one is pretty simple and we've informally discussed it with Envoy authors before: add additional context to `ext_authz` requests when operating at network level (can add to HTTP  too but we don't need that in Connect).

Specifically we would like:
 - the serial number or sha256 hash of the client's _leaf_ certificate that was validated. This will allow building revocation black lists for Connect that can be checked at AuthZ time rather than rely on CRLs.
 - the serial number or hash or `authorityKeyIdentifier` of the root certificate that the client's cert was signed by. 
 - the URL SAN or CN of the validating root.

The root information allows us to enforce tighter security boundaries when federating trust between external PKI identities e.g. enforce that an identity was issued by a root that's actually allowed to issue them and not another that has gone rogue. This can to some extent be insured externally through x509 name constraints however many PKI solutions don't make it easy to set those or don't have strong enough conventions around identity to enforce them leaving systems that do vulnerable to having it's identities spoofed if the other trusted PKI system is compromised.

None of this will change the current Connect implementation as we do not have any revocation and root checking only matters when federating multiple trust domains which is also not yet a feature. But both are necessary for planned future work and should be integrated with our AuthZ once they exist before this issue is closed.

**Comment by mkeeler** [comment]
As of Envoy 1.13 both the source and destination TLS certificates should be included in the `Check` request. We will still have to pull out the serial/fingerprint but it is now possible.

https://www.envoyproxy.io/docs/envoy/v1.13.0/api-v3/service/auth/v3/attribute_context.proto.html?highlight=principal

**Comment by mkeeler** [comment]
The xDS server should parse the source certificate and set the `ClientCertSerial` in the `ConnectAuthorizeRequest`

**Comment by banks** [comment]
We don't do An Authz callback since 1.9.0 so this is invalid now.
