### ISSUE TITLE
Package does not build without modules.

### ISSUE THREAD

**Issue by h8liu** [hashicorp/consul#6458]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Does not build without modules.

#### Reproduction Steps

Use go 1.13, setup a `GOPATH`, then:

```
$ GO111MODULE="off" go get github.com/hashicorp/consul
src/github.com/hashicorp/consul/vendor/github.com/envoyproxy/go-control-plane/envoy/type/http_status.pb.go:11:2: code in directory /Users/h8liu/gowork/src/github.com/hashicorp/consul/vendor/github.com/envoyproxy/protoc-gen-validate/validate expects import "github.com/lyft/protoc-gen-validate/validate"
```
### Consul info for both Client and Server

Irrelevant.

### Operating system and Environment details

Irrelevant. Tested on OSX, but should be reproducible on all platforms.

### Log Fragments

N/A

**Comment by mkeeler** [comment]
@h8liu There are a few Go 1.13 compatibility issues and I would recommend using Go 1.12 instead until those are worked out. The same command you showed works fine with Go 1.12.8

**Comment by mkeeler** [comment]
Additionally the main Consul binary itself is only intended to be compiled with modules enabled. Therefore I am going to close the issue.

**Comment by h8liu** [comment]
if it is only intended to be compiled with modules enabled, why not remove a vendor directory?

**Comment by mkeeler** [comment]
@h8liu Now that there are module proxies/caches we may. Right now the vendor directory is unused but in a pinch we could add a replace directive to resolve a module from that dir rather than an upstream repo if for some reason the repo disappeared.
