### ISSUE TITLE
Consul agent node name expression no match

### ISSUE THREAD

**Issue by peaaceChoi** [hashicorp/consul#6467]
#### Overview of the Issue
I run a new dev mode server for registering. 
When the node name has hyphen(-) character, catalog api return a expression evaluator Error.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Run dev mode  Server node with node name flag (-node=host-name)
```
 consul agent -dev -node=host-name
```
2. Register Sample Service
3. Call the Catalog api
```
curl-G http://127.0.0.1:8500/v1/catalog/service/{service-name} --data-urlencode 'filter=Node==host-name'
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
no client configuration
```

</details>

<details>
  <summary>Server info</summary>

```
no server configuration
```

</details>

### Operating system and Environment details

mac os mojava(10.14.5), consul version 1.5.3-dev

### Log Fragments

Failed to create boolean expression evaluator: 1:14 (13): no match found, expected: ".", "[", [ \t\r\n], [a-zA-Z0-9_] or EOF

### opinion
if developer using default node name, it will be use host name. And mostly  host name has a hyphen(-)character. So I think this bug is critical. 

I am curious about your opinion.
thanks.

**Comment by johncowen** [comment]
Hi @peaaceChoi 

I'm pretty sure you'll need to quote the string, take a look here:

https://www.consul.io/api/features/filtering.html#values

Let me know if that helps

Thanks

**Comment by peaaceChoi** [comment]
hi, @johncowen 
That's working find. And this issue can be closed.
Thanks your comments.

**Comment by fsiler** [comment]
How does one quote the key value?  For example, jobs registered in Nomad automatically register the meta `"external-source": "nomad"`.  I am having trouble using filtering along these lines; eg. `curl --get http://consul-server:8500/v1/catalog/services --data-urlencode 'filter=ServiceMeta.external-source == "nomad"'` returns all services; eg, the filter doesn't work.  If you try to filter a specific service, you get `Failed to create boolean expression evaluator: 1:21 (20): no match found, expected: "!=", ".", "==", "[", [ \t\r\n] or [a-zA-Z0-9_]% `

**Comment by jkirschner-hashicorp** [comment]
@fsiler : You mentioned that when you call `curl --get http://consul-server:8500/v1/catalog/services --data-urlencode 'filter=ServiceMeta.external-source == "nomad"'`, you get all services. What call do you use that generates the error message `Failed to create boolean expression evaluator`?

**Comment by fsiler** [comment]
instead of `/v1/catalog/services/`, I used `/v1/catalog/service/**servicename**`.

**Comment by aannkkiit** [comment]
how did you solve that hyphen issue? I'm also getting the same error  
`curl --get http://localhost:8500/v1/catalog/nodes --data-urlencode 'filter=Meta.patch-set == "2022Q4"'`
rpc error making call: Failed to create boolean expression evaluator: 1:11 (10): no match found, expected: "!=", ".", "==", "[", [ \t\r\n] or [a-zA-Z0-9_]

**Comment by jkirschner-hashicorp** [comment]
@aannkkiit : I'm wondering whether the filter expression lacks support for a Meta key name that contains a hyphen (like `patch-set`). If that's the case, I recommend we open a separate issue for that.

It seems like quotes only help if the _value_ contains a hyphen (like `host-name` in the original post).
