### ISSUE TITLE
"Merge Canceled" when trying to connect to 0.5.0rc1 server from 0.5.0rc1 client. 

### ISSUE THREAD

**Issue by byllc** [hashicorp/consul#647]
I am getting "Merge Canceled" with no further output when trying to connect to 0.5.0rc1 server from 0.5.0rc1 client.  Swapping out for the 0.4 release fixes the issue. Our configuration is pretty standard 

```json
{ "datacenter": "dc1",
  "data_dir": "/var/consul",
  "start_join": [ "192.168.157.70" ]
}

{"service": {"name": "director-1",
  "check": {"script": "check_service", "interval": "10s"}}}
```
and the agent is started with `consul agent -config-dir /etc/consul.d'`

**Comment by ryanuber** [comment]
Hi @byllc,

Sounds like this is related to the new cluster mixing guard we are introducing in 0.5. Is the client in a different datacenter than the server? Consul could be guarding against mixing multiple datacenters into a single gossip pool.

**Comment by byllc** [comment]
@ryanuber  Thanks, that seems to have been the problem, the server had a different datacenter name specified than the config for the agent.
