### ISSUE TITLE
Update curl's filename used in the restore example of the API snapshot page

### ISSUE THREAD

**Issue by etc-crontab** [hashicorp/consul#6476]
On the page https://www.consul.io/api/snapshot.html, the first "curl" uses "snapshot.tgz" as the destination filename to store the snapshot.

And few lines below, the "curl" used to restore the snapshot uses the filename "snapshot" (without extension). It should probably be "snapshot.tgz" to be consistent with the first "curl".

**Comment by blake** [comment]
Thanks for bringing this to our attention. I've fixed this in the docs, and it'll be published with the next website update.
