### ISSUE TITLE
api: replace-existing-checks param needs api package support

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#6496]
As noted in @fastest963 https://github.com/hashicorp/consul/pull/4905 we merged a feature for 1.6.0 that has an inconsistent API doc and is missing the new field being added as an option in the `api` package.

> It looks like the docs say `?replace-existing-checks=1` but the code has:
>
> ```
> query.Get("replace-existing-checks") == "" || query.Get("replace-existing-checks") == "true"
> ```
> Should the docs be updated to say that the value should be =true or should =1 be allowed?

I suggest we at least update the docs I don't think we use "1" anywhere else to happy to just fix docs.

**[Edit]: ** Docs are fixed, this issue is now to add the param to the `api`.

We should also make this usable from `api` too.

**Comment by Aestek** [comment]
Fixed in https://github.com/hashicorp/consul/pull/6497

**Comment by banks** [comment]
Doc fix was made in #6497. I'm leaving this open until we've added `api` package support for that new option.

**Comment by Aestek** [comment]
Woops, yes, read that a bit fast.
It _is_ fixed in https://github.com/hashicorp/consul/pull/6541

**Comment by i0rek** [comment]
Fixed here https://github.com/hashicorp/consul/pull/7136.

**Comment by mikemorris** [comment]
Closing as it looks like this was resolved in ^ and released in `hashicorp/consul/api v1.4.0` https://github.com/hashicorp/consul/commit/ef6399928d1584944180b8f0ac6621e550ca8c07
