### ISSUE TITLE
advertise address != bind address

### ISSUE THREAD

**Issue by ChristianKniep** [hashicorp/consul#650]
Hey there,

I used etcd/skydns and loosely couple check scripts before and I love consul just for making my live easier!
Currently I am consolidating our AWS infrastructure and I got a docker server instance which runs the consul server.
![screen shot 2015-01-28 at 13 50 28](https://cloud.githubusercontent.com/assets/1420201/5937823/a6c1d702-a6f4-11e4-8ba5-8fe8070c8f24.png)
Ontop of that a handfull of containers provide the services I desire (influxdb, nginx, elasticsearch, ...).

If I expose the service using consul the advertised adress is equal to the bind address, which is not accessable from other instances.
I decided to use the DOCKER_HOST adress to advertise the services, but unfortunately if I do so the clients fighting for this IP address to check their serfHealth as well.
```
    "bind_addr": "DOCKER_CONTAINER",
    "advertise_addr": "DOCKER_HOST",
```
Is it possible to overcome this issue? I learned that each agent is eager to talk to all other agents.
So maybe it's not that easy to hide containers behind a common IP address. Maybe I have to use weaver to get real IPs for all of them. :(

Or could it be solved by using multiple data centers? One global and one per docker server domain?

Any clues on how to architect this in a smart way?

**Comment by sielaq** [comment]
Why do You need consul in every container on one same DOCKER_HOST ?
What you need is one consul per docker host - much easier and comfortable.

**Comment by ChristianKniep** [comment]
Ahh... I thing I gotcha. On second thought I was thinking about such a construct.
![screen shot 2015-01-28 at 14 57 34](https://cloud.githubusercontent.com/assets/1420201/5938827/e2f762d2-a6fe-11e4-9bb9-4cac7d0fc8f4.png)

But on third thought you are saying I should kick out the consul agents on each docker container, but only use one consul agent on the bare-metal that deals with all containers as well, correct?

![screen shot 2015-01-28 at 15 20 01](https://cloud.githubusercontent.com/assets/1420201/5939100/261383be-a701-11e4-98e4-0fa7966e4778.png)
con_srv01 will advertise and check all services that are provided by 'his' docker container friends?

**Comment by sielaq** [comment]
correct, even better now you can use registrator (https://github.com/progrium/registrator) so all services gonna be register in consul automaticaly (just if you need this funtionallity)

**Comment by ChristianKniep** [comment]
Dude, you are kidding me! :) I love this stuff. What exiting time we are living in...
I have to digest it over night, but it looks like gold.

**Comment by sielaq** [comment]
actually to be honest -  I'm using consul also in a container, but only one per docker host.
So docker host doen't have ANY additional services which are NOT running in containers - I don't need to use puppet for that anymore.

**Comment by ChristianKniep** [comment]
yeah... that's my goal as well. Provisioning is reduce to setup the docker host and start the essential containers (registry, consul, registrator) and off you go.
http://qnib.org/2014/12/19/Docker-and-ConfigMgmt/

**Comment by sielaq** [comment]
so you can try this one:
https://github.com/eBayClassifiedsGroup/paas-in-a-box/
you have all pieces integrated together already :)

**Comment by ChristianKniep** [comment]
Uhi, please keep posting comments. :+1: 
You are located in Berlin? I work at locafox.de (Kreuzberg); we should grab a drink some day...
Over and out.

**Comment by rotatingJazz** [comment]
@sielaq "Why do You need consul in every container on one same DOCKER_HOST ?" -> multi-tenancy is one reason.

**Comment by rotatingJazz** [comment]
@sielaq I suppose you assume everyone runs docker hosts on elastic cloud and not on dedis. On dedis the illogical thing is to under-use your hardware, not the opposite because of software limitations. 

Besides, having multiple consul instances will be trivially possible once https://github.com/hashicorp/consul/issues/550 lands.
