### ISSUE TITLE
Autopilot: reset settings time-to-time

### ISSUE THREAD

**Issue by Nmishin** [hashicorp/consul#6505]
#### Overview of the Issue

When we perform Consul cluster update one node by one, new nodes recreated and signet to the cluster with "Voter": false. After investigating the problem, we found that consul autopilot settings were reset to the wrong values:
```
 CleanupDeadServers = false
 LastContactThreshold = 0s
 MaxTrailingLogs = 0
 ServerStabilizationTime = 0s
 RedundancyZoneTag = ""
 DisableUpgradeMigration = false
 UpgradeVersionTag = ""
```

Because of LastContactThreshold was value 0s all new servers mark as unhealthy and have non-voter status.

#### Reproduction Steps

This issue occurred three times in different environments, but we can't reproduce it.

### Consul info for both Client and Server

</details>

<details>
  <summary>Server info</summary>

```
root@consul-0-shrz ~ > consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = e716d1b5
	version = 1.2.2
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.208.11.18:8300
	server = true
raft:
	applied_index = 162561479
	commit_index = 162561479
	fsm_pending = 0
	last_contact = 0
	last_log_index = 162561479
	last_log_term = 25
	last_snapshot_index = 162558814
	last_snapshot_term = 25
	latest_configuration = [{Suffrage:Voter ID:679e7af4-0f18-4fa8-963d-cba5448c8c2f Address:10.208.11.18:8300} {Suffrage:Voter ID:b527516c-9a82-bdc0-d4dd-f5a96974a7f6 Address:10.208.11.13:8300} {Suffrage:Voter ID:6a3326cd-8c3c-0cf9-05f3-21b1640f1c62 Address:10.208.11.32:8300}]
	latest_configuration_index = 162281628
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 25
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 773
	max_procs = 2
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 19
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 18
	member_time = 44871
	members = 124
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 7
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

We recreate consul nodes with preserve node-id and node name.
We don't configure consul autopilot at all.
We use this configuration a long time with Consul version 0.8.4, and seems it issue happens only with consul version 1.2.2

**Comment by s-christoff** [comment]
Issues on GitHub for Consul are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [FAQ (Frequently asked questions)](https://www.consul.io/docs/faq.html)
- [Consul Guides](https://www.consul.io/docs/guides/index.html)
- Any other questions can be sent to the Consul section of the [HashiCorp forum]: (https://discuss.hashicorp.com/c/consul)

If you feel this is a bug, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.
