### ISSUE TITLE
Configurable CheckHTTP timeout

### ISSUE THREAD

**Issue by arnaudbriche** [hashicorp/consul#651]
Hi,

I'm using the master branch and I see you added CheckHTTP, which is awesome, however, from the code I can see that you set a default timeout of 10s on the HttpClient, and than the timeout can be no less than 1s (with 1s interval between checks).

I think it would be preferable to allow the client to specify a timeout explicitely for the request, preferably in milliseconds, to allow use-cases where one wants services taking to much time to respond be marked as unhealthy.

**Comment by armon** [comment]
Good idea!

**Comment by armon** [comment]
Fixed in master
