### ISSUE TITLE
Session Creation without Chuncked encoding and with Chunked encoding has issues

### ISSUE THREAD

**Issue by bkannadassan** [hashicorp/consul#6515]
#### Overview of the Issue
When we create session with the payload in chunked mode we see that the name, check, ttl none of them getting parsed and session created with NULL name..

#### Reproduction Steps
1) Payload...
```
       [root@bkannadassan-centos-aiohng-3 ~]# cat ~/payloads.json
    {
      "LockDelay": "15s",
      "Name": "my-service-lock",
      "Node": "consul-server4",
      "Checks": ["service:balaji1"],
      "Behavior": "release"
    }
```
2)  **curl     --request PUT     --data @payloads.json     http://127.0.0.1:8500/v1/session/create**
```
 {
    "ID": "d0789a83-b2a2-470b-bb57-2cc308bfe55b",
    "Name": "my-service-lock",
    "Node": "consul-server4",
    "Checks": [
      "service:balaji1"
    ],
    "LockDelay": 15000000000,
    "Behavior": "release",
    "TTL": "",
    "CreateIndex": 254364,
    "ModifyIndex": 254364
  }
```
_Issue not seen_

3) **curl  -H "transfer-encoding:chunked"   --request PUT     --data @payloads.json     http://127.0.0.1:8500/v1/session/create**
```
  {
    "ID": "c7b9c6e4-615a-3885-72b1-c499544d433b",
    "Name": "",
    "Node": "consul-server4",
    "Checks": [
      "serfHealth"
    ],
    "LockDelay": 15000000000,
    "Behavior": "release",
    "TTL": "",
    "CreateIndex": 254382,
    "ModifyIndex": 254382
  }
```
We can see above Checks is taking default health check and Name is null..

### Consul info for both Client and Server

<details>
> agent:
>         check_monitors = 0
>         check_ttls = 0
>         checks = 3
>         services = 3
> build:
>         prerelease =
>         revision = a42ded47
>         version = 1.5.3
> consul:
>         acl = disabled
>         known_servers = 3
>         server = false
> runtime:
>         arch = amd64
>         cpu_count = 6
>         goroutines = 54
>         max_procs = 6
>         os = linux
>         version = go1.12.1
> serf_lan:
>         coordinate_resets = 0
>         encrypted = true
>         event_queue = 0
>         event_time = 32
>         failed = 0
>         health_score = 0
>         intent_queue = 0
>         left = 0
>         member_time = 94
>         members = 4
>         query_queue = 0
>         query_time = 1

</details>

### Operating system and Environment details

We are running in Centos7,  and using consul version 1.5.3

We are blocked with the same, we are dependent on this for leader election. Any help on the same much appreciated..

rgds
Balaji Kamal Kannadassan

**Comment by bkannadassan** [comment]
```
func (s *HTTPServer) SessionCreate(resp http.ResponseWriter, req *http.Request) (interface{}, error) {
        // Default the session to our node + serf check + release session
        // invalidate behavior.
        args := structs.SessionRequest{
                Op: structs.SessionCreate,
                Session: structs.Session{
                        Node:      s.agent.config.NodeName,
                        Checks:    []types.CheckID{structs.SerfCheckID},
                        LockDelay: 15 * time.Second,
                        Behavior:  structs.SessionKeysRelease,
                        TTL:       "",
                },
        }
        s.parseDC(req, &args.Datacenter)
        s.parseToken(req, &args.Token)

        s.agent.logger.Printf("[1Balaji-DEBUG] http: Session Creating Buddy %s\n ", args.Session.TTL)
        // Handle optional request body
        if req.ContentLength > 0 {
                fixup := func(raw interface{}) error {
                        if err := FixupLockDelay(raw); err != nil {
                                return err
                        }
                        if err := FixupChecks(raw, &args.Session); err != nil {
                                return err
                        }
                        return nil
                }
                s.agent.logger.Printf("[2Balaji-DEBUG] http: Session Creating Buddy %s\n ", args.Session.TTL)
                if err := decodeBody(req, &args.Session, fixup); err != nil {
                        resp.WriteHeader(http.StatusBadRequest)
                        fmt.Fprintf(resp, "Request decode failed: %v", err)
                        return nil, nil
                }
        }
        s.agent.logger.Printf("[3Balaji-DEBUG] http: Session Creating Buddy %s\n ", args.Session.TTL)
```
On further debugging source code of consul, following is what I could see..

        if req.ContentLength > 0 { ==> this is zero hence its not going to debug the body..

**Comment by bkannadassan** [comment]
```
        // Handle optional request body
-       if req.ContentLength > 0 {
+        {


```To add I tried removing ContentLenght Check, Since ContentLength isn't supposed to be valid in chunked mode and I see now its creating fine. But I still think this isn't correct fix and there should be a better fix for the same..

rgds
Balaji Kamal Kannadassan

**Comment by bkannadassan** [comment]
[https://stackoverflow.com/questions/3304126/chunked-encoding-and-content-length-header](url)

Hence looks like if its chunked encoding then we shouldn't be checking content length. Please let me know if this can be fixed similar way ?.

rgds
Balaji Kamal Kannadassan

**Comment by bkannadassan** [comment]
Hi All,

  Any pointers on the same would be helpful..

rgds
Balaji Kamal Kannadassan

**Comment by s-christoff** [comment]
Hey @bkannadassan ,
At this time Consul does not explicitly support chunked encoding.
Apologies about the confusion!
