### ISSUE TITLE
ARMv7 Support

### ISSUE THREAD

**Issue by abrucker235** [hashicorp/consul#6519]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description
Downloads supporting latest ARM versions.

#### Use Case(s) 
Homelab Raspberry PI4 Clusters or A Series machines on Amazon.
 
I got a simple working version compiling myself: GOOS=linux GOARM=7 GOARCH=arm go build

**Comment by jwalzer** [comment]
Is this still unsolved?

https://github.com/hashicorp/docker-consul currently breaks, when building the container on a RasperryPi because no build for armv7 is available.

**Comment by mikemorris** [comment]
This should be resolved in the upcoming 1.11.0 release with the merge of https://github.com/hashicorp/consul/pull/11417, as well as upcoming patch releases for [1.10.x](https://github.com/hashicorp/consul/pull/11454), [1.9.x](https://github.com/hashicorp/consul/pull/11452), [1.8.x](https://github.com/hashicorp/consul/pull/11455) once the corresponding PRs have been merged and we switch over to the new release process.

This new process will build `GOARCH=arm GOARM=5` 32-bit binaries (intended for broad compatibility) and `GOARCH=arm64` (ARMv8) 64-bit binaries, per the matrix at https://github.com/golang/go/wiki/GoArm

**Comment by proffalken** [comment]
@mikemorris is there any more news on this?

Arch and Ubuntu are showing 1.11.1, whereas the Arm repos for rasbian etc. are only showing 1.10.x

Just wanted to make sure I'd not missed an updated release URI or similar?

**Comment by blake** [comment]
Hi @proffalken,

> Arch and Ubuntu are showing 1.11.1, whereas the Arm repos for rasbian etc. are only showing 1.10.x

These repositories are not managed by HashiCorp. [HashiCorp's Linux repository](https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository) currently only provides packages for x86_64/amd64 systems.

Binaries for 32-bit ARM can be found at <https://releases.hashicorp.com/consul/1.11.1/>.

**Comment by proffalken** [comment]
Ok thanks @blake

**Comment by blake** [comment]
Hi @proffalken,

> HashiCorp's Linux repository currently only provides packages for x86_64/amd64 systems.

I realized my previous comment is no longer accurate. Both 32-bit and 64-bit ARM packages have been available in the Linux package repo since about late Nov / early Dec 2021. This support was added with PR #11417.

Use the following command to add the repo to your APT sources for Ubuntu/Debian.

```shell-session
$ sudo apt-add-repository "deb [arch=armhf] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
```
