### ISSUE TITLE
Consul CLI should have a command to view service details

### ISSUE THREAD

**Issue by ishustava** [hashicorp/consul#6528]
#### Feature Description

Currently there is no way to view service details through the CLI which would return more or less information returned by the `GET /v1/catalog/service/:service` API call.

A command could look something like this:
```
consul catalog services -service <my-service>
```
or 
```
consul catalog services <my-service>
```

#### Use Case(s)

I would like to use the CLI to see service registration details such as the service address and service port. Consul UI already supports it and I'd expect the UX be similar for the CLI.

**Comment by jewertow** [comment]
@ishustava could you look at my pull request?

**Comment by jewertow** [comment]
@ishustava could you review my pull request?

**Comment by kyhavlov** [comment]
This would make more sense as a new catalog subcommand like `consul catalog service`, for listing instances of a specific service.

**Comment by david-yu** [comment]
Closing as we now have a way to do this in v2 Catalog: https://developer.hashicorp.com/consul/docs/k8s/multiport/reference/resource-command#example-usage-2

```
$ consul resource list catalog.v2beta1.Service
```
