### ISSUE TITLE
Create ACL with a pre-defined token ID

### ISSUE THREAD

**Issue by igormoochnick** [hashicorp/consul#656]
Is it possible to create ACL with a known ID?

We need this use case for our Test environments, when the applications may rely on a specific token to be present and that can survive the Consul cluster restarts.

Thanks a lot

**Comment by armon** [comment]
Currently the only way to do that is with the `acl_master_token`. That is the only one that can be specified ahead of time.

**Comment by armon** [comment]
Closing since `acl_master_token` is the best route. Please re-open if you have an issue.
