### ISSUE TITLE
Accept datacenter as a param for force-leave from WAN pool

### ISSUE THREAD

**Issue by freddygv** [hashicorp/consul#6582]
Currently `consul force-leave` can only force remove servers in the current datacenter from the WAN pool.

This is because the name of the current DC is appended to the node name before calling `RemoveFailedNode` from the WAN pool.

If a user in dc1 wants to force-remove a server in `dc2` (`s2.dc2`), and calls `consul force-leave s2.dc2`, the server will naively append its current DC name to the end of the node name when attempting the WAN pool removal. Since `s2.dc2.dc1` doesn't exist, the removal will fail.
 
To allow for users to remove nodes in other DCs we should allow users to specify a datacenter explicitly. 

This could look something like: `consul force-leave -datacenter=dc2 s2`

If the datacenter is excluded we could continue to do the DC append if the DC is not already a suffix of the node name.

**Comment by freddygv** [comment]
If an external contributor would like to submit this, I can provide more context as well guidance during the process.

**Comment by dedifferentiator** [comment]
@freddygv new at contributing to consul, but I suppose I can resolve this, what should I look at?

**Comment by freddygv** [comment]
Thank you for volunteering to help out @dedifferentiator !

To begin you should read the internals docs, these provide an overview for how the code is organized: https://github.com/hashicorp/consul/blob/master/INTERNALS.md

I would also recommend looking through this PR, since it made a change that touches a lot of the same functions: https://github.com/hashicorp/consul/pull/6571

To add a flag to the CLI there are several steps:
1. The new flag needs to be added in [the appropriate file](https://github.com/hashicorp/consul/blob/master/command/forceleave/forceleave.go) inside of the `command/` package.
2. [The Go API function](https://github.com/hashicorp/consul/blob/master/api/agent.go#L723) that the CLI command calls needs to be updated to accept the new parameter. However, the Go API is public facing, and we don’t believe this change should require a breaking change to the existing function signature of `ForceLeave`. [ForceLeavePrune](https://github.com/hashicorp/consul/blob/master/api/agent.go#L735) is currently unreleased, so I propose replacing it with a function called `ForceLeaveWithOpts` that accepts a node name as well as a pointer to QueryOptions, similar to how [ConnectCALeaf](https://github.com/hashicorp/consul/blob/master/api/agent.go#L786) does. The QueryOptions would contain the Datacenter and Prune flags. [Here](https://github.com/hashicorp/consul/pull/6551) is an example of how to expand what is in the `QueryOptions` struct, and [here](https://github.com/hashicorp/consul/blob/master/command/keyring/keyring.go#L112) is an example for how a pointer to `QueryOptions` can be passed into an API function call.
3. The [HTTP endpoint handler](https://github.com/hashicorp/consul/blob/master/agent/agent_endpoint.go) needs to parse the new param as done [here](https://github.com/hashicorp/consul/blob/master/agent/agent_endpoint.go#L1078).
4. The [function](https://github.com/hashicorp/consul/blob/master/agent/agent.go#L1782) called by the HTTP handler needs to accept the new DC flag.
5. The [Server implementation](https://github.com/hashicorp/consul/blob/master/agent/consul/server.go#L1011) of `RemoveFailedNode` will also need to be updated, as per the issue description above. Note that this function is implemented in two other places to satisfy the [delegate interface](https://github.com/hashicorp/consul/blob/master/agent/agent.go#L128), so when the signature changes for the Server implementation, the interface and other implementations also need an update.

Let me know if you have any questions.

**Comment by freddygv** [comment]
Closing for reasons described [here](https://github.com/hashicorp/consul/pull/6609#issuecomment-573843734).

**Comment by jsosulska** [comment]
Reopening issue and reinvestigating.

**Comment by jsosulska** [comment]
Similar to #6548 & https://github.com/hashicorp/consul/issues/3757

**Comment by blake** [comment]
As of Consul 1.11.0 `force-leave` again supports leaving members from the WAN pool that exist in remote DCs (fixed by #11722). The syntax is the same as is documented on the [`consul force-leave` CLI documentation](https://www.consul.io/commands/force-leave#examples).
