### ISSUE TITLE
Allow subscribing to consul event stream.

### ISSUE THREAD

**Issue by sigil66** [hashicorp/consul#661]
I am debating a migration from serf to consul. Currently I am able to create external integrations via the event stream with:

https://github.com/hashicorp/serf/blob/master/client/rpc_client.go#L495

I haven't found any obvious way to easily consume to the consul event stream externally with out executing a separate process based event handler for every event. Am I missing something?

**Comment by armon** [comment]
@sigil66 Take a look at the event APIs: https://consul.io/docs/agent/http.html#event. Those are mapping down to Serf user events under the hood. Other types of events (Join/Fail/Leave) map to state in the catalog which can be queried.

**Comment by sigil66** [comment]
Thank you!
