### ISSUE TITLE
Register check documentation is misleading

### ISSUE THREAD

**Issue by CogitoGroupDevTeam** [hashicorp/consul#6635]
Running: Consul v1.6.1

In the documentation for registering a health check https://www.consul.io/api/agent/check.html#register-check

The 'ID' field is documented as follows. Specifies a unique ID for this check on the node. This defaults to the "Name" parameter, but it may be necessary to provide an ID for uniqueness.

However when I register a service using the ID parameter it does not register with that ID. Instead it works if CheckID is used when registering the check. I believe this should just be a small documentation update that might have someone a bit of time troubleshooting the issue.

Thanks for your time on this.

**Comment by pierresouchay** [comment]
@CogitoGroupDevTeam It actually depends, but I think you are incorrect.

The documentation is correct regarding https://www.consul.io/api/agent/check.html#register-check

While the response uses CheckID, I agree that's messy, but that's probably to delay with ascending compatibility:

With CheckID:
```
{
  "CheckID": "mem2",
  "Name": "Memory utilization",
  "Notes": "Ensure we don't oversubscribe memory",
  "DeregisterCriticalServiceAfter": "90m",
  "HTTP": "https://example.com",
  "Method": "POST",
  "Header": {"x-foo":["bar", "baz"]},
  "TCP": "example.com:22",
  "Interval": "10s",
  "TLSSkipVerify": true
}
```
`curl --request PUT -d @testcheck.json    http://127.0.0.1:8500/v1/agent/check/register` => will register:
```
    "Memory utilization": {
        "CheckID": "Memory utilization",
        "Name": "Memory utilization",
        "Status": "passing",
```
So, bascially, CheckID is ignored and Name is used instead...

While using ID:
```
{
  "ID": "mem",
  "Name": "Memory utilization",
  "Notes": "Ensure we don't oversubscribe memory",
  "DeregisterCriticalServiceAfter": "90m",
  "HTTP": "https://example.com",
  "Method": "POST",
  "Header": {"x-foo":["bar", "baz"]},
  "TCP": "example.com:22",
  "Interval": "10s",
  "TLSSkipVerify": true
}
```

will give the correct result:
```
"mem": {
        "CheckID": "mem",
        "Name": "Memory utilization",
        "Status": "passing"
        
}
```

So, you probably did a mistake, but the documentation is correct (it is not the case if check is embedded into a service however.

But I agree with you the usage of both CheckID and ID is very misleading (but would be hard to change for compatibility reasons)

**Comment by shaqq** [comment]
@pierresouchay @s-christoff 

Would it be sufficient to update the docs from:

```
- `ID` `(string: "")` - Specifies a unique ID for this check on the node.
  This defaults to the `"Name"` parameter, but it may be necessary to provide an
  ID for uniqueness.
```

to:

```
- `ID` `(string: "")` - Specifies a unique ID for this check on the node.
  This defaults to the `"Name"` parameter, but it may be necessary to provide an
  ID for uniqueness. This value will return in the response as `"CheckId"`
```
Another thought would be to add `CheckId` as a parameter for the register check endpoint, and then mark `Id` as deprecated. I briefly looked into it, and it appears possible to accept both parameters but give priority to `CheckId` to allow people to migrate. Though.... to be fair, this is a fairly small thing to change the API over....
