### ISSUE TITLE
detect missed updates using watch API

### ISSUE THREAD

**Issue by sangleganesh** [hashicorp/consul#6643]
Hello,
We have a following scenario:

1. We use consul as a key-value store for get/put/delete and use its watch mechanism to detect changes in the key-value store (https://github.com/portworx/kvdb/tree/master/consul)

2. The question is relates to watch API:
   - we use the watch prefix API with waitIndex - lets say X (largest modify index for any key with that prefix)
   - when the watch returns is it possible to get which index was the one on which the modification was done ? 
For example, if a key was /abc/pwx - LastIndex: 100
and then it was updated, that watch return LastIndex: 110, but if we had it return PreviousIndex: 100 we could determine nothing changed in-between ?

**Comment by s-christoff** [comment]
Hey @sangleganesh, 
Thank you so much for bringing this up. Please feel [read this documentation ](https://www.consul.io/api/features/blocking.html)that touches on why we are unable to return which index was the one modification was done on. 
We are reworking parts of the mechanism which will make this less of an issue in the future.
