### ISSUE TITLE
Lifeguard

### ISSUE THREAD

**Issue by dzyand** [hashicorp/consul#6647]
Do you have the source code of Lifeguard?

**Comment by bosconi** [comment]
Hi @dzyand. Thanks for your interest in Lifeguard. Lifeguard is a set of extensions to the SWIM protocol. It was developed by modifying HashiCorp's implementation of SWIM, called memberlist (https://github.com/hashicorp/memberlist). So our implementation of Lifeguard is embedded within memberlist. 

https://github.com/hashicorp/serf has a dependency on memberlist, and Consul in turn has a dependency on Serf. Consul therefore uses memberlist indirectly, via Serf APIs.

In case you didn't see it, our paper on Lifeguard is available here: https://arxiv.org/abs/1707.00788 There are actually two versions of the paper - see the v1 and v2 links in the Submission History section at the bottom of the page. V1 discusses the Lifeguard features in terms of Self-Awareness, Dogpile and Buddy System, which we the names given to these features internally during development. But not all the terms are used in the source code. Awareness is mentioned, and https://github.com/hashicorp/memberlist/blob/master/awareness.go is the core of the implementation of that functionality. Dogpile on the other hand was added without using that term: https://github.com/hashicorp/memberlist/commit/973dec8d2e609864e0ceaf94aa6eb88b8efa23ff#diff-77750e76abdbc2ddd5dc682094d028ad The Buddy System code only mentions the term in a test: https://github.com/hashicorp/memberlist/commit/bfc0d6b0c617e499f96969805c601de49cd805c2

V2 of the paper was concerned with digging deeper into why each of these features makes the contribution that it does, and verifying that the various tunable parameters have good default settings. During that work we realized that what we previously referred to as Self-Awareness and Dogpile are both really heuristics for the health of the local node (the node this instance of the memberlist/the Consul agent is running on. Hence the naming differences between the two versions of the paper. Self-Awareness became Local Health Aware Probe, and Dogpile became Local Health Aware Suspicion. However the code was not changed to reflect these changes in thinking, so you will still have to refer to V1 of the paper to understand how things map onto the code.

If you (or anyone else) have questions about any this, please email me. I am one of the authors of the paper, and my email address is on the first page of both versions.

Jon.

**Comment by dzyand** [comment]
@bosconi  It's a great honor to hear from you！

**Comment by dzyand** [comment]
@bosconi How to deploy 128 Consul agents （the Lifeguard paper）are in a single Linux VM？
In other words,How to make Lifeguard experiment with consul？Start an agent in a terminal，Using different ports to manually start 128 agents in 128 terminals？（Maybe you were too busy to see my email, so I asked you through GitHub，I'm very sorry to disturb you！）
Thank you for you reply！

**Comment by dzyand** [comment]
@bosconi I'm sorry for disturbing you again！After using docker to pull Consul, how can I modify the source code to test Lifeguard，I have deployed multiple nodes with docker compose.
