### ISSUE TITLE
Question: How to configure to support upload a file with size 2M

### ISSUE THREAD

**Issue by NextZeus** [hashicorp/consul#6660]
When i upload a file with size of 2M, it return a message

"413 Request Entity Too Large"

please give me an example ,how to configure limit of upload file size. 

Thanks

**Comment by pierresouchay** [comment]
Max size is 512k: https://www.consul.io/docs/faq.html#q-what-is-the-per-key-value-size-limitation-for-consul-39-s-key-value-store-

**Comment by pierresouchay** [comment]
No

**Comment by NextZeus** [comment]
> No

ok, thank you.
