### ISSUE TITLE
Still uses github.com/hashicorp/net-rpc-msgpackrpc

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/consul#6664]
See https://github.com/hashicorp/net-rpc-msgpackrpc/issues/1#issuecomment-24591071 for details.

Wouldn't it be better to use [github.com/ugorji/go](https://github.com/ugorji/go) instead?

**Comment by mkeeler** [comment]
Unfortunately it’s not so simple as a drop in replacement. Our fork was done from that library at a point in time where the upstream broke backwards compatibility.  A few months ago I attempted to swap in ugorji/go for our fork but it broke compatibility with several of our messages that get used and thus is a blocker on us pulling it in. There are others at HashiCorp investigating what it would take to get rid of our fork as we want it gone as much as anyone else. However it may or may not ever happen. 

Another data point is that we are going to be moving away from msgpack all together as we start using protobufs which has already begun. For a while we will have to support both simultaneously  but eventually the library can probably be removed in whole without replacement. 

Going to close this for now.
