### ISSUE TITLE
Allow compile-time plugins to add operations to the key-value store

### ISSUE THREAD

**Issue by derekelkins** [hashicorp/consul#667]
This began from a comment in #553.

Right now, despite Raft providing support to atomically do an arbitrary deterministic function of the state, it's only possible with Consul to atomically read a single key, or atomically write a single key.  If you want to read-modify-write a single key, e.g. increment, this can only be accomplished inefficiently with CAS or with locks.  If you want to manipulate multiple keys atomically, locks are the only reasonable solution and that exposes you to either inconsistency or deadlock.  Since the locks are advisory, any lock-based solution is not atomic.  It's only atomic to operations that participate in the lock-based protocol.

There are two significant concerns I see.  The first is that it is difficult to enforce determinism, though it's not difficult to guarantee as an author of a plugin.  To mitigate this, which plugins are used, if any, would be a very deliberate choice.  In this case, by requiring them to be compiled in.  The second issue is if the operation consistently take a long time (i.e. more than a leader election timeout) it will definitely cause (false) failure suspicion of the leader and possibly cause the whole cluster to become unavailable.  Again, this is mitigated by the use of a plugin being a deliberate choice.  Also, I believe this situation can happen today.  If I write a gigabyte of data to a key, this will probably cause problems.

The alternative is to use locks which seems more dangerous to me.

A concern Armon brought up was that this would lead to "RDMBS triggers and PL/SQL".  This provides no support for triggers.  I do agree and have said that this is basically a stored procedure, however stored procedures and triggers are orthogonal.  (As an example, VoltDB is a relational database whose *only* interface is stored procedures, yet it does not support triggers.)

**Comment by armon** [comment]
Closing, as this is not something we plan on supporting at this point.
