### ISSUE TITLE
consul may continue running without a working HTTP server

### ISSUE THREAD

**Issue by lmb** [hashicorp/consul#6677]
#### Overview of the Issue

We configure consul to run the HTTP API on port 8500. However, we found that sometimes we had a running consul process that wasn't listening on that port anymore.

After digging through logs we found the following:

```
2019/10/14 12:43:38 accept tcp 127.0.0.1:8500: accept4: too many open files in system
```

This corresponds to ENFILE (not EMFILE). The server had run out of file descriptors, and this aborted the HTTP accept loop:

https://github.com/hashicorp/consul/blob/60f6ec0/agent/agent.go#L935-L937

However the consul process kept running. Should the process abort instead under these circumstances?

I've filed https://github.com/golang/go/issues/35131 with Go to maybe treat ENFILE as a temporary error as well.

#### Reproduction Steps

1. Exhaust files available to the OS
2. Try to connect to the consul RPC port

### Operating system and Environment details

Linux

**Comment by i0rek** [comment]
It has been changed in golang and is part of golang 1.14: https://github.com/golang/go/commit/17190de08570d36dda9b2904609271354cc3c64a. We are on 1.13 but we will move to 1.14 soon and by then this issue will be fixed.
Do you think it would be ok to close this issue now @lmb? Thanks for reporting and getting it fixed!

**Comment by lmb** [comment]
Have you considered crashing consul if one of its interfaces shuts down for good?

**Comment by i0rek** [comment]
It is certainly something that we should be thinking about, it doesn't happen that often which is why we don't have an answer for that question right away. It is something we would need to careful with for sure.
What you like consul to do in these cases?

**Comment by lmb** [comment]
In our case we only narrowly avoided a production incident, and it took some head scratching to figure out what was going on. I'd probably prefer crashing.

**Comment by dnephin** [comment]
Consul 1.8.0 was released which uses go1.14, and includes the fix.

But I think the underlying issue remains. If one of the goroutines that is serving the HTTP API exits, the agent should shut down. https://godoc.org/golang.org/x/sync/errgroup is designed to handle exactly this problem.
