### ISSUE TITLE
Consul agent is flappy or missing "serf health status" check after IP change

### ISSUE THREAD

**Issue by cshabi** [hashicorp/consul#6704]
#### Overview of the Issue

We have 3 physical consul clusters, smaller is roughly 900 nodes, largest is roughly 2500 nodes. We have an automated process that changes a node's IP on the cluster (not consul server) and reboots the node.
The process goes as followed:
- change interfaces files on a machine
- reboot the machine
- run chef to update consul config with new IP
- restart consul agent (done during chef run)

To validate the process we run ```curl``` from another agent in the cluster to this endpoint: ```/v1/health/node/<node_fqdn>```.

After reboot the agent is alive and appears as healthy in the cluster with the old IP. The health endpoint check returns the services registered on the node as well as the 'Serf health status' both passing. Once the agent's config is updated with the new IP (using chef) and is restarted, the agent enters the 'left' state and the 'Serf health status'  is critical.

At this point we added another restart to the agent which introduced an unstable agent status:
The  'Serf health status' is missing from the curl's output, and the agent appears in 'left' state in consul members with the old IP address. In several occasions, the service registered on the node will also disappear and the ```curl``` will return an empty answer.

### Output of curl after the second consul agent restart (as seen by one of the consul servers in the cluster). Serf health status is missing

```Every 1.0s: curl http://localhost:8500/v1/health/node/<fqdn_of_node_with_new_ip>?pretty                                                   Tue Oct 28 09:20:50 2019

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100  1006  100  1006    0     0   187k      0 --:--:-- --:--:-- --:--:--  196k
[
    {
        "Node": "fqdn_of_node_with_new_ip",
        "CheckID": "generic-80",
        "Name": "generic Health Status",
        "Status": "critical",
        "Notes": "",
        "Output": "",
        "ServiceID": "generic-ops-80",
        "ServiceName": "generic-ops",
        "ServiceTags": [
            "hostType-metal",
            "servicetype-generic"
        ],
        "Definition": {},
        "CreateIndex": 147106319,
        "ModifyIndex": 147106378
    }
]
```

#### Reproduction Steps
When we reproduced the issue on the smallest(900~ nodes) cluster it took about 9:30 mins until the  'Serf health status' was returned in the output as 'passing'. On our largest cluster(2500~ nodes) it took about 30 mins until the  'Serf health status' was returned in the output as 'passing
'

We were unable to reproduce this issue in a smaller vagrant environment with 3 servers and 4 agents. 

### Consul info for both Client and Server
 
<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 1
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = 39f93f01
	version = 1.2.1
consul:
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 43
	max_procs = 24
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 106217
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 151080
	members = 929
	query_queue = 0
	query_time = 1168
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 2
	check_ttls = 0
	checks = 2
	services = 2
build:
	prerelease =
	revision = 39f93f01
	version = 1.2.1
consul:
	bootstrap = false
	known_datacenters = 4
	leader = false
	leader_addr = <leader_ip>:8300
	server = true
raft:
	applied_index = 147108187
	commit_index = 147108187
	fsm_pending = 0
	last_contact = 37.559104ms
	last_log_index = 147108187
	last_log_term = 3284
	last_snapshot_index = 147092358
	last_snapshot_term = 3284
	latest_configuration = [{Suffrage:Voter ID:65d9e50f-4ca6-173a-aa14-40d623abe4b8 Address:<follower_ip>:8300} {Suffrage:Voter ID:dac1062f-e054-8cda-9a22-eb57bcb90387 Address:<follower_ip>:8300} {Suffrage:Voter ID:f750be1e-f3ab-4e34-84c1-c1194c30e83c Address:<leader_ip>:8300}]
	latest_configuration_index = 84118976
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 3284
runtime:
	arch = amd64
	cpu_count = 24
	goroutines = 24424
	max_procs = 24
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 106217
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 151082
	members = 929
	query_queue = 0
	query_time = 1168
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 879
	members = 10
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

3 physical consul datacenters. in each datacenter we have 3 consul servers running Ubuntu16.04

**Comment by cshabi** [comment]
Hi guys,

Just a quick update, we were able to over come this issue by:

- change interfaces files on a machine
- stop + force-leave consul agent
- change consul's default.json advertise_addr to the new ip
- delete the content of consul's data dir (including the node-id file,  checks,proxy,serf and services directories)
- reboot the node

Do you know why deleting the data solved the issue?

**Comment by ChipV223** [comment]
Hi @cshabi !

The reason why the deleting the data worked because it's possible that the previous data got corrupted with the IP change somehow. Given that you were not able to repro this in your smaller environment, it appears that this was a one-off

Since you mentioned you were able to resolve this, I'll go ahead and close. But should it occur again, feel free to reopen this and provide logs(preferably debug) so that we can review them on our end!
