### ISSUE TITLE
Add documentation for KV Max Value Size Limit

### ISSUE THREAD

**Issue by clly** [hashicorp/consul#6707]
#### Feature Description

As part of https://github.com/hashicorp/vault/issues/5597 there was a change in consul to allow modification of the maximum value in the consul raft database which increases how big of an entry you can store in the KV store. This was merged into consul in this issue: https://github.com/hashicorp/consul/pull/6172 but it's still undocumented. 

Some documentation could be added.

**Comment by ChipV223** [comment]
Fixed with https://github.com/hashicorp/consul/pull/7405 and https://github.com/hashicorp/consul/pull/7388
