### ISSUE TITLE
Learn hashicorp Consul ACL documentation with HCL is wrong

### ISSUE THREAD

**Issue by aparedero** [hashicorp/consul#6737]
#### Overview of the Issue

The official docs at learn.hashicorp.com regarding ACLs seems to be outdated (either HCL syntax is not correct). If try to use the configuration showned, it shows error.

#### Reproduction Steps

1. Create a .hcl file with the syntax on the webpage:
https://learn.hashicorp.com/consul/security-networking/production-acls

```
# agent.hcl
{
  acl = {
    enabled = true,
    default_policy = "deny",
    enable_token_persistence = true
  }
}
```

2. Run `consul agent -dev -node test1 -config-file ~/consul-config.hcl`
3. View error
```==> Error parsing /home/user/consul-config.hcl: At 2:1: expected: IDENT | STRING got: LBRACE```

### Consul info for both Client and Server

```
==> Starting Consul agent...
           Version: 'v1.6.1'
           Node ID: '83092843-6757-abd9-1793-4c556e239550'
         Node name: 'test1'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false
```

Using JSON it works:

```
{
  "acl": {
    "enabled": true,
    "default_policy": "deny",
    "enable_token_persistence": true,
    "down_policy": "extend-cache"
  }
}
```

**Comment by rboyer** [comment]
Thanks for pointing out the example text was incorrect. I've fixed it and the learn site should redeploy shortly.
