### ISSUE TITLE
Is there a way to set up policies in consul config.json?

### ISSUE THREAD

**Issue by ppodbielski** [hashicorp/consul#6743]
Hi,
my configuration:
consul in docker v1.4
I'm using config.json file while starting up with basic configuration. 
Is there a way to set up policies in consul config.json and assign them to an anonymous token?
I would like to have a config.json that I can use with consul docker with default policies. I don't want to use API to create tokens and policies.

**Comment by s-christoff** [comment]
Howdy,

Thank you for bringing this to our attention. This seems to be similar to this issue [here](https://github.com/hashicorp/consul/issues/6706). I'm going to go ahead and close this as a duplicate for now, but if you feel they are different please comment and we can discuss!
