### ISSUE TITLE
Unable to run make test on latest master

### ISSUE THREAD

**Issue by varunturlapati** [hashicorp/consul#6762]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

In order to get the latest changes from master (rebasing my branch), I first wanted to ensure I could run `make test` on master in the first place. I see the following issue:
`
$ make test

--> Checking for other consul instances
==> Building Consul - OSes: darwin, Architectures: amd64
Building sequentially with go install
--->   darwin/amd64
go: finding k8s.io/api latest
go: downloading k8s.io/api v0.0.0-20191108065827-59e77acf588f
go: extracting k8s.io/api v0.0.0-20191108065827-59e77acf588f
go: downloading k8s.io/apimachinery v0.0.0-20191108065633-c18f71bf2947
go: extracting k8s.io/apimachinery v0.0.0-20191108065633-c18f71bf2947
go: finding k8s.io/apimachinery v0.0.0-20191108065633-c18f71bf2947
build github.com/hashicorp/consul: cannot load k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest (v0.0.0-20191108065827-59e77acf588f) found, but does not contain package k8s.io/api/admissionregistration/v1alpha1
ERROR: Failed to build Consul for darwin/amd64
make: *** [dev-build] Error 1
`

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. git clone master (as of 8th Nov 2019)
1. make test
1. (or) make dev

### Operating system and Environment details

MacOSX Catalina
Go version go1.13.1 darwin/amd64

### Log Fragments
build github.com/hashicorp/consul: cannot load k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest (v0.0.0-20191108065827-59e77acf588f) found, but does not contain 

I tried to clone it in a separate path just to see if something got messed up in my CWD but that throws the same error.

Context: I am trying to work on tests for the PR comments here: https://github.com/hashicorp/consul/pull/6445

**Comment by rboyer** [comment]
Hm. I tried to reproduce by trying a fresh `go mod download` and `make dev` in a new environment (fresh $GOPATH) and it worked on both go `1.12.13` and `1.13.4`. I know occasionally I've seen some libraries fail to download via git but those usually were fleeting. Did you wait and try again a bit later to see if there was some general networking hiccup involved?

I should note however that the version of Go we currently test/build/release with is the `1.12` series and there are some structural changes we need to make so that everything works with the `1.13` series.

**Comment by varunturlapati** [comment]
I tried it first yesterday and then today - at home, at my office. So diff places and times and so I don't think it was a network glitch. I'll try to downgrade my Go to 1.12.13 and update the thread.

**Comment by varunturlapati** [comment]
I tried 1.12.13 and it looks like it fails on something else. ☹️ 
`$ make test
--> Checking for other consul instances
==> Building Consul - OSes: darwin, Architectures: amd64
Building sequentially with go install
--->   darwin/amd64
go: finding k8s.io/api latest
build github.com/hashicorp/consul: cannot load crypto/ed25519: malformed module path "crypto/ed25519": missing dot in first path element
ERROR: Failed to build Consul for darwin/amd64
make: *** [dev-build] Error 1
sm-vturlapati:consul vturlapati$ echo $GOROOT
/usr/local/opt/go@1.12/libexec
`
Is there a reference doc for how I could establish/assert a correct dev env?

**Comment by crhino** [comment]
I tried this locally as well, on version `1.12.13`. `make dev` was able to correctly build the a `darwin/amd64` binary.

We have the [CONTRIBUTING.md](https://github.com/hashicorp/consul/blob/master/.github/CONTRIBUTING.md) doc, but that probably is not helpful in this circumstance.

You might try cloning Consul outside of any `$GOPATH`, making sure `$GOPATH` is not set, and trying it that way. With Go modules, GOPATH should no longer be required. Other than that, you might try starting with a fresh `$GOPATH` to get rid of any cached/corrupted data.

**Comment by varunturlapati** [comment]
Ok, so here is what I did to get this to work:

1. Completely uninstall Go, remove directories that have Go binaries
1. Unset GOPATH, GOROOT
1. Create and export a new GOPATH
1. Install Go 1.12.13 from the Go downloads page (not brew install)
1. Clone project in a completely different path but maintaining the project structure `src/github.com/hashicorp/consul` within the new GOPATH

As such, we could mark this as resolved/closed, or whichever the appropriate status is. Separately I have a diff issue getting tests to pass on master but that would be a new issue, right?

**Comment by crhino** [comment]
@varunturlapati Glad to hear that you got this working, although unfortunate that such drastic actions had to be taken!

Sorry to hear about having trouble getting tests passing on master though, I agree we can close this ticket out and you can open a new one for any test problems.

Thank you for continuing to struggle forward, we very much appreciate your contributions. On that note, if you have any suggestions for improving documentation around contributing and such, we are always looking to improve them.

**Comment by varunturlapati** [comment]
Thanks @crhino! I am okay with the struggles because it is not trivial to document every issue and every environment. That said I was wondering if the scoping of tests to be run for a given PR could be done.

Or perhaps recognizing that the failed tests are not in the related area. This may already be done but if so could that be formally noted? Otherwise if tests fail upon a fresh clone it may break the momentum of the intended PR.
