### ISSUE TITLE
Sometimes service health check exception (net/http: request canceled (Client.Timeout exceeded while awaiting headers))

### ISSUE THREAD

**Issue by dirkmurphy** [hashicorp/consul#6781]
Hi Team

I use consul as registrition center with spring cloud (consul).

And sometimes there are some exceptions occurred when consul healthcheck. health checkout output as below: 
**Get http://192.168.206.4:29000/ds-billing-service/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)**

When consul health check failed, then it will be changed to "passing" soon.
And I use "curl" to request health check api from consul client machine. all times I will get a quick response in 300ms with http code 200.

So I write a crontab to check all services health check url directly every 3 seconds. But there are no exception found in my crontab, and all healthcheck url return with http code 200 all the time.

I found this problem in Consul v1.5.2 and Consul v1.6.1.

Can you provide some help?
Thank you

**Comment by dirkmurphy** [comment]
I have tried to modify consul health check timeout to 30s. but it takes no effect.
spring:
  cloud:
    consul:
      # consul client
      host: 192.168.206.4
      port: 8500
      discovery:
        service-name: ds-billing-service
        ip-address: 192.168.206.4
#        health-check-url: http://192.168.206.4:29000/ds-billing-service/actuator/health
        health-check-path: /ds-billing-service/actuator/health
        health-check-interval: 30s
        health-check-timeout: 30s

**Comment by dirkmurphy** [comment]
I have tried to modify consul health check timeout to 30s. but it takes no effect.
spring:
  cloud:
    consul:
      # consul client
      host: 192.168.206.4
      port: 8500
      discovery:
        service-name: ds-billing-service
        ip-address: 192.168.206.4
        health-check-path: /ds-billing-service/actuator/health
        health-check-interval: 30s
        health-check-timeout: 30s

**Comment by crhino** [comment]
Hi there, to triage this effectively we would need you to reproduce this issue without using the spring-cloud integration, e.g. using either the `consul` CLI or the API endpoints. This helps rule out any intermediate code causing an issue or obscuring information.

If you are able to reproduce this, please open a [new issue](https://github.com/hashicorp/consul/issues/new?template=bug_report.md) with the appropriate information.

**Comment by dirkmurphy** [comment]
I have solved it.
The reason is my database connection sometimes not stable. It will lead to health check timeout
