### ISSUE TITLE
Add support for Tencent Cloud to auto-join

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#6812]
Tencent cloud has contributed go-discover support in https://github.com/hashicorp/go-discover/pull/125.

We should update our vendored version of go-discover and the auto-join docs to allow use in Consul.

**Comment by likexian** [comment]
Hello,
I have update the tests and docs, PR: https://github.com/hashicorp/consul/pull/6818
Hope to help.

**Comment by i0rek** [comment]
Closing since #6818 has been merged. Thanks for your help @likexian!
