### ISSUE TITLE
Where is "configurable" reap time for client nodes?

### ISSUE THREAD

**Issue by casper-gh** [hashicorp/consul#6814]
Per FAQs, reap time can be configured, but I have tried both `reconnect_timeout` and AutoPilot `cleanupDeadServer` but nothing works, dead hosts still linger for days before it would be reaped (not 72 hours as promised). These settings seem to be intended for the "servers" only, not clients. Someone please help confirm this?

Background: I'm using spot EC2s and they get replaced very often, this results in a lot of dead hosts (in failed or left state).

So, where is this setting for client nodes that would tell the "servers" to remove the hosts from cluster (equivalent with `consul force-leave`).

**Comment by Amier3** [comment]
Leaving this comment mainly for clarification as it's been a few years,

`reconnect_timeout` does work for servers and clients. What possibly could've happened here is the `reconnect_timeout` worked and the client was pruned from gossip, but the catalog removal failed causing the client to still be listed. 

I'm closing this out for now, if this is still an issue in the latest consul versions feel free to open this back up :) .
