### ISSUE TITLE
Unnecessary error log on startup "failed to sync remote state: No known Consul servers"

### ISSUE THREAD

**Issue by fastest963** [hashicorp/consul#6815]
#### Overview of the Issue

When starting up consul prints out:
```
2019/11/19 20:12:14 [ERR] agent: failed to sync remote state: No known Consul servers
```

Which is unnecessary and just caused by a race with starting the state syncer.

#### Reproduction Steps

1. Start consul agent:
```
/usr/bin/consul \
  agent \
  -bind=0.0.0.0 \
  -client=0.0.0.0 \
  -retry-join=x.x.x.x \
  -retry-join=x.x.x.x \
  -retry-join=x.x.x.x \
  -config-file=/etc/consul/agent.json \
  -datacenter=gce-us-east1 \
  -data-dir=/var/lib/consul/data \
  -encrypt=x
```

### Operating system and Environment details

CentOS 7 running in GCE

### Log Fragments

<details>
  <summary>Logs</summary>

==> Starting Consul agent...
Version: 'buildDate=Thu Nov 14 20:33:39 UTC 2019 commit=1200f25eabc75368484a78698e75f1e61b6ed010 runtime=go version go1.13.4 linux/amd64'
Node ID: 'da5761d0-3843-038f-ef05-e9699741f7e4'
Node name: 'b4c9f3ff'
Datacenter: 'gce-us-east1' (Segment: '')
Server: false (Bootstrap: false)
Client Addr: [x.x.x.x] (HTTP: 8500, HTTPS: 8501, gRPC: -1, DNS: 8600)
Cluster Addr: x.x.x.x (LAN: 8301, WAN: 8302)
Encrypt: Gossip: true, TLS-Outgoing: true, TLS-Incoming: false, Auto-Encrypt-TLS: false
==> Log data will now stream in as it occurs:
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: b4c9f3ff x.x.x.x
2019/11/19 20:12:14 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)
2019/11/19 20:12:14 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
2019/11/19 20:12:14 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
2019/11/19 20:12:14 [INFO] agent: Started HTTPS server on [::]:8501 (tcp)
2019/11/19 20:12:14 [INFO] agent: Retry join LAN is supported for: aliyun aws azure digitalocean gce k8s mdns os packet scaleway softlayer triton vsphere
2019/11/19 20:12:14 [INFO] agent: Joining LAN cluster...
2019/11/19 20:12:14 [INFO] agent: (LAN) joining: [x.x.x.x x.x.x.x x.x.x.x]
2019/11/19 20:12:14 [INFO] agent: started state syncer
==> Consul agent running!
2019/11/19 20:12:14 [WARN] manager: No servers available
2019/11/19 20:12:14 [ERR] agent: failed to sync remote state: No known Consul servers
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: a39403f9 x.x.x.x
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: jamie x.x.x.x
2019/11/19 20:12:14 [INFO] consul: adding server mixer (Addr: tcp/x.x.x.x:8300) (DC: gce-us-east1)
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: umar x.x.x.x
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: richard x.x.x.x
2019/11/19 20:12:14 [INFO] consul: adding server naptha (Addr: tcp/x.x.x.x:8300) (DC: gce-us-east1)
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: 22371646 x.x.x.x
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: bd6a3d05 x.x.x.x
2019/11/19 20:12:14 [INFO] consul: adding server oreo (Addr: tcp/x.x.x.x:8300) (DC: gce-us-east1)
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: gunter x.x.x.x
...
2019/11/19 20:12:14 [INFO] serf: EventMemberJoin: stella x.x.x.x
2019/11/19 20:12:14 [INFO] agent: (LAN) joined: 3
2019/11/19 20:12:14 [INFO] agent: Join LAN completed. Synced with 3 initial agents
2019/11/19 20:12:14 [INFO] agent: Synced node info

</details>

**Comment by i0rek** [comment]
@fastest963 thanks for reporting! Why do you think it is unnecessary?

**Comment by fastest963** [comment]
@i0rek thanks for the quick reply! It happens every single time we start up consul and we currently have a policy of alerting on errors from critical infrastructure. We get an alert every time a new node is spun up or whenever consul is restarted (after an update for instance). Additionally, it immediately retries the full sync on this error. Maybe instead it can be a warning if we cannot fix the race with calling it too early before we have any servers.
