### ISSUE TITLE
Consul watches fail when using agent configuration

### ISSUE THREAD

**Issue by jeanluclariviere** [hashicorp/consul#6824]
#### Overview of the Issue

Hello,
I'm trying to implement watches via the agent's configuration but this fails. If i use the CLI to run `./consul watch -token=xxxxxxxxxxxxxxxxxxxxxx -type=checks -state=passing /app/consul/checks/test-fire.sh` and kill one of my services, my test-fire.sh script executes, and I'm alerted via email. However, I've gone and configured the agent configuration with this same settings and it fails:

```
{
    "bootstrap_expect": 3,
    "client_addr": "127.0.0.1",
    "datacenter": "DEV-DC",
    "data_dir": "/app/consul",
    "domain": "consul",
    "enable_script_checks": true,
    "dns_config": {
        "enable_truncate": true,
        "only_passing": true
    },
    "enable_syslog": true,
    "encrypt": "f422H2+WrMjtl2VbNTNYsg==",
    "leave_on_terminate": true,
    "log_level": "INFO",
    "bind_addr": "10.10.10.1",
    "rejoin_after_leave": true,
    "server": true,
    "start_join": [
        "10.10.10.1",
        "10.10.10.2",
        "10.10.10.3"
    ],
    "ui": true,
    "watches": [
        {
            "type": "checks",
            "state": "passing",
            "args": ["/app/consul/checks/test-fire.sh"]
        }
    ]
}
```
The only thing appears to do is trigger the test-fire.sh script if i restart the consul service via systemctl. I'm hoping i'm just missed a step somewhere...

#### Consul info
Version 1.2.3

**Comment by jeanluclariviere** [comment]
Still having issues configuring this, any help would be appreciated.

**Comment by ChipV223** [comment]
Hi @jeanluclariviere !

I'm curious if you are still running into this issue in any of the later Consul releases? If you can attach the `test-fire.sh`, I would love to try to repro this behavior on my end.

**Comment by jeanluclariviere** [comment]
Hey @ChipV223,
I'd honestly forgotten about this issue. At the time, test fire was a super simple `echo "Subject: Firing" | sendmail example@email.com`. I'm not sure if we're using a different version of consul now, but we've since gotten this working. I looked over our config and it looks identical, aside from the script which now takes in an email like this: `sendmail example@email.com < /path/to/email.txt`, so I'm not really sure what to make of this. Since this is so outdated, I'm going to be closing this issue, but I appreciate you reaching out after all this time.
