### ISSUE TITLE
Snapshot verifying failed in 1.6.2

### ISSUE THREAD

**Issue by rvojcik** [hashicorp/consul#6826]
#### Overview of the Issue

Hi guys.  We're using consu cluster (3 nodes) as storage backend for Vault.
After upgrade on 1.6.2 we start to experience snapshot create problems.

#### Reproduction Steps
It's hard to reproduced, it happend time to time.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

When snapshot is creating time to time it fail with

```
# consul snapshot save test.snap
Error verifying snapshot file: failed to read snapshot file: failed to read or write snapshot data: unexpected EOF
```
</details>

<details>
  <summary>Server info</summary>

I found in logs:
```
Nov 21 04:00:05 consul1 consul[16915]:     2019/11/21 04:00:05 [ERR] http: Request GET /v1/snapshot, error: failed to stream snapshot: read tcp 192.168.1.100:48098->192.168.1.128:8300: read: connection reset by peer from=192.168.2.7:44364
```
Maybe problem on our side somewhere in the network ?
</details>

### Operating system and Environment details

Debian Stretch, amd64, kernel 4.4.174

### Log Fragments
I'll try to capture traces from periodic backups

**Comment by crhino** [comment]
Hi, thanks for submitting an issue. This certainly could be transient network issues, but if you able to reproduce this frequently more logs would definitely be helpful!

**Comment by Nagarajuwas** [comment]
I recently upgraded my environment consul servers 1.6.2 version. But I have not seen this behaviour. I think it could be a network issue from your environment.

**Comment by rvojcik** [comment]
I had no luck with reproducing this.
It didn't happen for o few days so I think is something in our infrastructure which cause this problem in some cases. I'm closing this issue.
