### ISSUE TITLE
metrics: Add a gauge for the number of active blocking queries

### ISSUE THREAD

**Issue by banks** [hashicorp/consul#6846]
We currently have a metric for blocking queries but it's almost useless since it's a counter that increments whenever a blocking query begins:

https://github.com/hashicorp/consul/blob/973341a5926679c548ff99809eb6d6ee62c2c1c6/agent/consul/rpc.go#L495

What operators (and consul developer 😉 ) really want to know about is how many blocking queries _are actually open/being handled right now_.

This should be easy:
 - add an uint64 to the server that is accessed atomically (watch struct alignment - probably needs to be at the top of the struct)
 - atomically increment it right on the line linked above when a blocking query starts
 - defer an atomic decrement for when the query returns
 - after each operation emit a gauge metric with the current value

Note that we shouldn't replace or rename the current metric since that is a breaking change for users monitoring stacks, this should be a new gauge, I suggest we call it `consul.rpc.queries_blocking` or something (that bikeshed needs painting).

**Comment by mkcp** [comment]
Looking to pick this up later this week
