### ISSUE TITLE
Possible deadlock situation when leader is flapping

### ISSUE THREAD

**Issue by i0rek** [hashicorp/consul#6852]
#### Overview of the Issue

When running some load testing, we saw two of the servers having more goroutines than we expected. And even after our load testing was done, the number keept going up. The logs showed that the leader was flapping and one important bit is that the same server lost and acquired leadership in the same second. 

Dumping the goroutines helped us understand what was going on:

* `monitorLeadership` is starting `leaderLoop` and adds to a waitgroup: https://github.com/hashicorp/consul/blob/fd3c56ff68829821da4be139185c0a96938e1929/agent/consul/leader.go#L74-L78
* when raft signals that leadership is lost,`monitorLeadership` is waiting on that waitgroup before it can finally shutdown. it is done that way to make sure consul only ever runs a single `leaderLoop`: https://github.com/hashicorp/consul/blob/fd3c56ff68829821da4be139185c0a96938e1929/agent/consul/leader.go#L88-L90
* the channel that is used to signal raft leadership has only 1 capacity: https://github.com/hashicorp/consul/blob/66d138f35e2cc5548412a55362a7bcedbe198888/agent/consul/server.go#L725
* if raft leadership is flapping fast, consul is waiting for the above waitgroup and in the meanwhile raft is blocked because at this time it wrote `true` to the channel to indicate that leadership was acquired and now it wants to write `false`, but it can't because it is blocked. Now the raft leaderloop is blocked: https://github.com/hashicorp/consul/blob/fd3c56ff68829821da4be139185c0a96938e1929/vendor/github.com/hashicorp/raft/raft.go#L426-L434 
* when autopilot started `PromoteNonVoters` while it was still leader, but is still running, it now blocks on getting the raft configuration because raft doesn't run the loop anymore since it is waiting to write to the notify channel: https://github.com/hashicorp/consul/blob/fd3c56ff68829821da4be139185c0a96938e1929/agent/consul/autopilot.go#L67-L68

#### Fixes

* [x] buffer channel more, the docs are even recommending that: https://github.com/hashicorp/consul/blob/fd3c56ff68829821da4be139185c0a96938e1929/vendor/github.com/hashicorp/raft/config.go#L186-L189
* [x] restructure consul to decouple aggressive reading from channel from leader loop

#### Related

* https://github.com/hashicorp/raft/issues/356

#### Raw goroutine dump of deadlocked server

https://gist.github.com/banks/e6d14f2f94a49bbba48d52023b643008

**Comment by banks** [comment]
For posterity, I tried to re-follow this chain and there are a couple of links missing in the description I had to figure out again.

 * https://github.com/hashicorp/consul/blob/fd3c56ff68829821da4be139185c0a96938e1929/agent/consul/leader.go#L88-L90
  The chan close terminates `leaderLoop` which setup a `defer s.revokeLeadership()` here: https://github.com/hashicorp/consul/blob/fd3c56ff68829821da4be139185c0a96938e1929/agent/consul/leader.go#L192
* `revokeLeadership` stops stuff, including autopilot: https://github.com/hashicorp/consul/blob/fd3c56ff68829821da4be139185c0a96938e1929/agent/consul/leader.go#L361
* `autopilot.Stop` closes things and then waits on it's internal wait group for all of it's background health checking to stop (to be sure that the server is not doing any "leaderish" things any more: https://github.com/hashicorp/consul/blob/3de783cc252ab9eca19e1e4eb28d7526bdabf79a/agent/consul/autopilot/autopilot.go#L95-L97
* as explained above, if autopilot has just triggered a promotion (which needs to read raft status) while still leader, that could get blocked on the raft leader loop which is waiting to deliver the next notification about leadership lost.


This is still pretty hard to hold in your head! But a possible sequence of events here between the 3+ goroutines involved in the deadlock cycle could be:

| Seq | Raft | Consul MonitorLeadership | Consul leaderLoop | Autopilot |
| --- |---|---|---|---|
| 1 | Leadership lost | | | | | |
| 2 | `notifyCh <- false` | unblocks | | | | |
| 3 | starts candidate Loop | | | |
| 4 |  |  | | interval times out, trigger `promoteServers` |
| 5 |  | close `weAreLeader` and wait for `leaderLoop` to return | | |
| 6 |  | `revokeLeadership` waits for autopilot to stop | | |
| 7 | wins election |  | | |
| 8 | start new leaderLoop, send `notifyCh <- true` filling chan buffer |  | | |
| 9 |  |  | | `PromoteNonVoters` requests raft status (blocked waiting for raft loop to service) |
| 10 | Leadership lost again | | | | |
| 11 |  `notifyCh <- false` blocks | blocked waiting for `leaderLoop` to return | blocked waiting for `autopilot.Stop()` | blocked waiting for `raft.Status()` to be serviced by raft |

**Comment by banks** [comment]
Bear in mind that this is on a heavily loaded server so some of these operations that should take microseconds are likely struggling to get CPU time and raft is flappy because not being serviced in a timely way. So if this seems implausible/hard to replicate it would be in a controlled way, but once server is overloaded chances of hitting something like this are much higher.
