### ISSUE TITLE
1.5.2: TestHTTPServer_H2 fails on mipsel

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/consul#6858]
~~~~
--- FAIL: TestHTTPServer_H2 (10.75s)
    http_test.go:182: err: Get https://127.0.0.1:18157/echo: net/http: TLS handshake timeout
~~~~

_mipsel_ is a slow architecture so it might be that the test is failing because timing is too strict...

**Comment by i0rek** [comment]
Thanks for reporting. The timeout is set to 10secs and that sounds like a sane amount of time to me. Are you suggesting we should increase that even more?

**Comment by onlyjob** [comment]
Yes I thing increasing timeout might be reasonable because test _somitemes_ passes (non-deterministically).

**Comment by i0rek** [comment]
Thanks for your reply! I opted for increasing the timeout only for tests. That should fix your issue without changing production behavior.

**Comment by onlyjob** [comment]
Thanks. :)
