### ISSUE TITLE
A feature to exclude particular key prefixes from being replicated accross DCs.

### ISSUE THREAD

**Issue by chowmean** [hashicorp/consul#6869]
#### Feature Description
Consul can exclude the replication of certain key prefixes. A configuration like don't replicate data from `/key/path`

#### Use Case(s)
I am trying to use consul as a queue and using KV store. I have to run it in multiple DCs. I will be running a worker in each DC. I don't want the worker from one DC to pick the task from the other DC. Writes and read to a particular KV prefix should be local in DC and not being replicated to others so that the other workers cannot read task of others DC. Is it possible to do it in the current consul? I want to do this using consul to avoid adding extra components. 

Need suggestions on what is the best way to achieve this. One way is I can have the queue name different for each DC and the workers in that DC so data will be replicated but the workers will use their local queue names.

**Comment by banks** [comment]
@chowmean Consul doesn't replicate KVs between DCs at all. Did you actually encounter an issue with this? Can you describe your configuration if so as there is some confusion here.

See the docs here: https://www.consul.io/docs/internals/architecture.html#10-000-foot-view

Especially:

> In general, data is not replicated between different Consul datacenters. When a request is made for a resource in another datacenter, the local Consul servers forward an RPC request to the remote Consul servers for that resource and return the results. If the remote datacenter is not available, then those resources will also not be available, but that won't otherwise affect the local datacenter. There are some special situations where a limited subset of data can be replicated, such as with Consul's built-in ACL replication capability, or external tools like consul-replicate.

I'd also suggest that Consul KV is not a good fit for a work queue in general. If you really need strong consistency and very low thoughput registration of tasks (more like static-ish role/task/shard assignments) it could be a good fit, but it is not designed to be a high-throughput database or queue and many better tools exist for that.

**Comment by chowmean** [comment]
Thanks for the info and suggestions.
