### ISSUE TITLE
The ARM64 version of Consul currently on the website (1.6.2) is postfixed with `-dev`

### ISSUE THREAD

**Issue by benumbed** [hashicorp/consul#6875]
#### Overview of the Issue
See a reproduction below:

root@vault-01:~# consul version
Consul 1.6.2-dev
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

#### Reproduction Steps

`consul version`

**Comment by alvin-huang** [comment]
Hey @benumbed thanks for writing in this issue! This is known on our side and will be fixed in the next version. The binary still contains the changes in the 1.6.2 changelog but had the wrong version flag passed in.

**Comment by benumbed** [comment]
I had a feeling that's what happened :).  I'll close the issue since it doesn't really affect anything.
