### ISSUE TITLE
Consul client 1.0.2 consumingtoo much memory

### ISSUE THREAD

**Issue by edgdelgado** [hashicorp/consul#6880]
My client is using too much memory, it keep growing util use all of it.

Could it be something with this version?

 1397 consul    20   0 6382124 6.064g   7232 S   1.4 10.3   9792:47 consul

version: 1.0.2

**Comment by ChipV223** [comment]
Hi @edgdelgado !

Have you tried restarting the agent node to see if that alleviates the RAM usage. In cases that I've seen, especially if Consul is being served as a backend for Vault(especially when secrets and leases are being removed in Vault), sometimes the memory usage never settles and a restart is needed. In addition, I would also recommend upgrading your Consul nodes given that the version you are using is over 2 years old,
