### ISSUE TITLE
ui issue on homepage

### ISSUE THREAD

**Issue by adkatrit** [hashicorp/consul#690]
Recently got a rotatable monitor, allowing for portrait mode web browsing.  
On https://consul.io/ (though not on any other consul.io page) there is a 150px high semi-transparent white bar covering your logo/download/github links.

Let me know if you need more repro data or a screencap.  I'm on a 900 X 1400 portrait mode.  I know i'm among a small % of internet users with portrait monitors, however i'd venture to guess that if you change that demographic from "internet users" to "developers who would like to use consul"  that % is likely to be quite a bit higher.   Thanks!

**Comment by pearkes** [comment]
Thanks, fixed!
