### ISSUE TITLE
stop consul agent graceful

### ISSUE THREAD

**Issue by tmanninger** [hashicorp/consul#6935]
I am using consul 1.6.2

In the documentation you can read:
```An agent can be stopped in two ways: gracefully or forcefully. To gracefully halt an agent, send the process an interrupt signal (usually Ctrl-C from a terminal or running kill -INT consul_pid ). When gracefully exiting, the agent first notifies the cluster it intends to leave the cluster. This way, other cluster members notify the cluster that the node has left.```

If i kill the main process with "kill -INT id", the process stops immediately and does not leave the cluster.
The other consul nodes get the following error:
``` [ERR] consul: "KVS.Get" RPC failed to server 10.31.73.17:8300: rpc error making call: EOF
[ERR] http: Request GET /v1/kv/vault/core/lock?index=134153889&wait=15000ms, error: rpc error making call: EOF from=172.17.0.2:52636
[ERROR] core: failed to acquire lock: error="failed to read lock: Unexpected response code: 500"
[ERR] consul: "Session.Apply" RPC failed to server 10.31.73.16:8300: rpc error making call: rpc error getting client: failed to get c
onn: dial tcp 10.31.73.16:0->10.31.73.17:8300: connect: connection refused
[ERR] http: Request PUT /v1/session/destroy/a6f1508d-fac5-0b24-fa8f-dab621e7dedf, error: rpc error making call: rpc error getting cli
ent: failed to get conn: dial tcp 10.31.73.16:0->10.31.73.17:8300: connect: connection refused from=172.17.0.2:52640
```

If i use "consul leave", the nodes leaves the cluster as expected.

Is this behavior intended?

**Comment by crhino** [comment]
Hi @tmanninger. Are you attempting to remove a client agent or a server agent? The behavior is different depending.

In general, this is intended functionality, see the descriptions for [`skip_leave_on_interrupt`](https://www.consul.io/docs/agent/options.html#skip_leave_on_interrupt) and [`leave_on_terminate`](https://www.consul.io/docs/agent/options.html#leave_on_terminate) for more up-to-date descriptions of the behavior.

We can update the [stopping an agent](https://www.consul.io/docs/agent/basics.html#stopping-an-agent) section to be correct.

**Comment by tmanninger** [comment]
Hi @crhino,



> We can update the [stopping an agent](https://www.consul.io/docs/agent/basics.html#stopping-an-agent) section to be correct.
Yes, it's a good idea ;-)..

Thanks for help
