### ISSUE TITLE
service_id contains "//" It can be registered and added, but cannot be deleted.

### ISSUE THREAD

**Issue by starsliao** [hashicorp/consul#6961]
curl --request PUT http://192.168.200.111:8500/v1/agent/service/deregister/A//B

curl --request PUT http://192.168.200.111:8500/v1/agent/service/deregister/A%2F%2FB

The commands above can not be deleted。

**Comment by EmilyBjartskular** [comment]
This is not a bug with consul but rather a bug with golangs net/http package. There is a pull request under review that should fix this in a future release of golang.

The pull request in question:
https://github.com/golang/go/pull/39171
