### ISSUE TITLE
Test Vault Connect CA Provider against N versions of Vault

### ISSUE THREAD

**Issue by mkcp** [hashicorp/consul#6963]
Per @rboyer's comments in #6535 and its implementation #6949, decoupling the Vault CA Provider tests from other go test jobs gives us room to abstract and test against [multiple vault binary versions](https://github.com/hashicorp/consul/blob/master/.circleci/config.yml#L566-L570). Both local development and CI contexts are worth considering as we dev this out, so the [envoy integration tests](https://github.com/hashicorp/consul/blob/master/test/integration/connect/envoy/run-tests.sh) provide a solid abstraction for integration testing against many versions of an external dependency.

**Comment by alvin-huang** [comment]
The easiest way to accomplish this is using YAML anchors around the Vault test job and passing in the `VAULT_BINARY_VERSION` as an environment variable when building out separate jobs. An example of this for Envoy is here: https://github.com/hashicorp/consul/blob/0d61369fcd66d6120cbc2741a1b5e6c315797b64/.circleci/config.yml#L511-L557

**Comment by jkirschner-hashicorp** [comment]
Marking closed by https://github.com/hashicorp/consul/pull/15661
> adds support to run the existing suite of vault related integration tests against the last 4 versions of vault (1.9, 1.10, 1.11, 1.12)

Note that the above PR hard-codes the last 4 versions of Vault rather than discovering them dynamically, so there's a small opportunity for improvement in the future.
