### ISSUE TITLE
will consul 1.7 support envoy 1.12+?

### ISSUE THREAD

**Issue by cbarbara-okta** [hashicorp/consul#6967]
I don't see envoy 1.12+ support listed in https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#170-beta1-december-10-2019, will they work together?

There are many important envoy bug fixes, features and security fixes only being placed in 1.12, can we get official support for 1.12?

**Comment by banks** [comment]
Hey @cbarbara-okta yes it will.

I thought we had an issue tracking this already but apparently we don't so I'll use this one.

I've already run our integration suite against 1.12 so it works as it is. We need to update docs, CI and a few other things (like default version Nomad and consul-k8s use) which is the thing that we are waiting for here but I'll use this issue to make sure that is done before the GA 1.7.0 - consider it safe to use 1.12 with current 1.7.0 betas too.

**Comment by cbarbara-okta** [comment]
that's great news, thanks @banks
