### ISSUE TITLE
Any plan to support setting service metadata via registrator?

### ISSUE THREAD

**Issue by tayzlor** [hashicorp/consul#697]
I had a search but could not find anything around this in consul and/or registrator. 
See https://github.com/progrium/registrator/issues/52 for some background.
Are there are plans to support registering metadata with the service in consul like this?

**Comment by armon** [comment]
@tayzlor Yes, there is another open ticket to support adding metadata to services which could then be used downstream by registrator.

**Comment by pccowboy** [comment]
@armon Can you post that other ticket's ID?  I am interested in following that effort, and seeing if I can contribute to it.

**Comment by armon** [comment]
@pccowboy It's not a specific issue I guess, but a collection:
* https://github.com/hashicorp/consul/issues/367
* https://github.com/hashicorp/consul/issues/154

Basically, it's to support K/V tags on Nodes / Checks / Services. My guess is this will require a v2 API that allows us to rethink things a bit.

**Comment by slackpad** [comment]
Since this is covered in other issues, closing as a duplicate.
