### ISSUE TITLE
Consul ACL endpoints allow for ?dc= parameter to override

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#698]
The ACL endpoints should always route to the `ACLDatacenter`, but currently their use of `parse` in certain cases allows the ?dc= query parameter to override that value which results in errors.

**Comment by armon** [comment]
On further review, it looks like we handle this already. It's not possible for a client to override the DC.

**Comment by armon** [comment]
Original report:
```
I understand that "In any Consul cluster, only a single datacenter is authoritative for ACLs, so all requests are automatically routed to that datacenter regardless of the agent that the request is made to."

But if I query an ACL API endpoint with ?dc=authoritative_dc, I get the error "rcp error: ACL not found". If I omit the dc param, I am able to successfully query the endpoint.

As far as I have seen, all other endpoints take in the dc parameter and this is the only one that does not.  It seems unintuitive when I make an ACL endpoint call and it fails even when I pass in the correct dc. 

For design consistency, shouldn't this endpoint allow the use of dc=authoritative_dc?
```

**Comment by ryanuber** [comment]
I've been looking at this as well, and I don't see where we actually use the `?dc=` query parameter for anything on the ACL endpoints. Passing in the correct datacenter as a query param should work as expected, since it really won't be used anyways. The agent will always use the configured `ACLDatacenter`.
