### ISSUE TITLE
Do we realy need communication configs in config or properties file in service mesh environment.

### ISSUE THREAD

**Issue by masifpak** [hashicorp/consul#6986]
Hi Geeks,

Lets say we have 3 microservices m1, m2 and m3. All have config files. If mi need to communicate with m2, do we need any parameter in config of mi to communicate with m2 on host name or IP? 
or just need to mention in control plane of service mesh?

Thanks

**Comment by jsosulska** [comment]
Hi @masifpak ,

Thank you for your question! I recommend you ask it on our [Discuss Forums](https://discuss.hashicorp.com/c/consul/29), as our community is very helpful. It may be helpful to specify what configs you are discussing, like the application or Consul configs, and what those services require for communication.

Thanks, and looking forward to seeing you on the forums.
