### ISSUE TITLE
Confused about doc in 'Service Definition' part

### ISSUE THREAD

**Issue by jejt123** [hashicorp/consul#6989]
I'm reading the doc of consul .The doc gives a [configuration](https://www.consul.io/docs/agent/services.html#service-definition) file for the service, parts of it are as follows:
```
    "tagged_addresses": {
      "lan": {
        "address": "192.168.0.55",
        "port": 8000,
      },
      "wan": {
        "address": "198.18.0.23",
        "port": 80
      }
    },
    "port": 8000
```
So why the ports in tagged_addresses are different, does this mean that the wan address uses a proxy. Or the tagged_addresses configuration item have any other meaning?

**Comment by blake** [comment]
Hi @jejt123, apologies for the late response. We just published documentation on [tagged addresses](https://www.consul.io/docs/discovery/services#tagged-addresses). Hopefully this helps to clarify the purpose of the different address types.
