### ISSUE TITLE
Vault Deployment Guide documentation errors

### ISSUE THREAD

**Issue by billq** [hashicorp/consul#6992]
#### Overview of the Issue

Following the Vault Deployment Guide is difficult due to numerous errors in the document.  It is impossible to create a working Vault deployment following this document verbatim.

#### Reproduction Steps

Steps to reproduce this issue:

1. Create some bare servers.
2. Follow the Deployment Guide to try to create a working Vault/Consul deployment.
3. Give up in frustration.

### Details
In the section »Set up ACL for Vault access to Consul >= 1.4.x
1. The numeric sequence is not correct for the steps to be taken (numbering restarts at 1. frequently)
2. The URL for CONSUL_ADDR is specified using https, which will not work.  http needs to be used (export CONSUL_ADDR="https://127.0.0.1:8500")
3. The CONSUL API Management Token returned by the curl statement is embeded in a JSON statement, and it is not apparent from the document to which component CONSUL_TOKEN needs to be set, i.e.
`{
  "ID":"b6fffff3e-c13e-f3f2-d1d4-2dcfff1636ee",
  "AccessorID":"9e87ffff-cccc-4fa0-fdd6-19ffff7bdc23",
  "SecretID":"b64f6fff-c13e-f3f2-d1ff-2dcff91636ee",
  "Description":"Bootstrap Token (Global Management)",
  "Policies":[{
    "ID":"00000000-0000-0000-0000-000000000001",
    "Name":"global-management"
  }],
  "Local":false,
  "CreateTime":"2020-01-03T08:55:49.80825667206:00",
   "Hash":"oyrov6+GFLjo/KffffffF/X4J/3LX0fffDOBy9V22I0=",
   "CreateIndex":2760,
   "ModifyIndex":2760
}`
4. Regardless of what CONSUL_TOKEN is set to, the curl statement that is supposed to generate the Consul ACL agent token fails, with:
` curl  --request PUT  --header "X-Consul-Token: ${CONSUL_TOKEN}"       --data '{"Name": "Agent Token", \
         "Type": "client", \
         "Rules": \
            "node \"\" { policy = \"write\" \} \
            service \"\" { policy = \"read\" }"
        }'         ${CONSUL_ADDR}/v1/acl/create
Request decode failed: invalid character '\\' looking for beginning of object key string

It is obvious this document has never been used to do an actual deployment.  If you are writing an installation guide, please test it before publication.

**Comment by roooms** [comment]
Thanks for sharing this feedback @billq , we will take a look at this and provide an update.

**Comment by roooms** [comment]
@billq while we look into this further, please could you share which versions of Vault, Consul and Linux you were using? I'm testing combinations already, but your specific versions would be helpful. Thanks very much.

**Comment by roooms** [comment]
We're making a number of updates to the Vault deployment guide documentation to better support use with Consul ACLs. ETA for completion is the end of this week.

**Comment by billq** [comment]
Hi Dan,

Thanks very much.  I'm very anxious to get moving with vault & consul.
Hopefully your updates will help me out!  Your attention is greatly
appreciated!

Bill

**Comment by roooms** [comment]
Hi Bill,

We have been working on updates to this deployment guide and are close to having a new version for publication. I just wanted to share a little more background on why this is still being worked on and isn't yet finished.

In considering your feedback along with the multiple permutations of Consul and Vault versions, and the OSS vs Enterprise differences, we've concluded that now is the time to split this deployment guide into specific OSS and Enterprise versions. This has increased the level of effort to improve the guides beyond the issues you raised, but will result in a better experience long-term.

We may publish the fixes you require in the current guide format, but have started work on the larger piece of work as well.

Again, thanks very much for your feedback.

-Dan

**Comment by billq** [comment]
Dan,

Thanks for your attention to this critical document.  Vault/Consul is
clearly the only product to consider in this space, and having clear and
concise documentation is crucial.

Regards,
Bill Quayle

**Comment by roooms** [comment]
Bill,

We've finished updating this guide, keeping it to the same scope as before. It's in a private repo at the moment but will soon be published in the Learn repo. The updates address the Consul ACL setup sections. I've just verified the guidance works for Vault 1.3.1 and Consul 1.6.2 on Ubuntu 16.04 with systemd. If you have further trouble, please let me know which versions you're using.

As mentioned above, we will be releasing a more thorough guide for setting up Vault that includes all the Consul steps, rather than expecting you to jump to the Consul deployment guide and then back to make the necessary ACL changes.

Thanks,
Dan
