### ISSUE TITLE
[ERR] memberlist: failed to receive: Remote state is encrypted and encryption is not configured from=

### ISSUE THREAD

**Issue by yanivx** [hashicorp/consul#6994]
I am on consul version 1.2.2 and I am getting this error from Dec 30th after some auto update any idea what could be the reason for below failure. Config files are the same no changes have been made in config file.  

The agent is configured for gossip encryption. We are using a static keyring that doesn't change.

Regards,
Vinay

**Comment by ChipV223** [comment]
@yanivx: Based on the error message, it sounds like the node in question is not configured for gossip encryption.

Here's the relevant source of the error in memberlist:

https://github.com/hashicorp/memberlist/blob/2e1a43a4eac88545b8c77a5f6916e496e5525c89/net.go#L946-L964

I'd double-check your encryption configuration on both sides!
