### ISSUE TITLE
Add Azure MSI for cloud auto-join instructions to the documentation

### ISSUE THREAD

**Issue by devops-rob** [hashicorp/consul#6999]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

With support for using Azure managed Service Identities to authenticate against azure for cloud auto-join being added in this release and tested successfully by myself, We need to add these details to the documentation.

#### Use Case(s)

For anyone who would like to use cloud auto-join with Azure, it's important we make them aware of the MSI possibility as it's a more secure way to auth against azure

**Comment by jsosulska** [comment]
This is resolved in #7000
