### ISSUE TITLE
Service doesn't show up in UI after registration

### ISSUE THREAD

**Issue by pete0emerson** [hashicorp/consul#701]
I am POSTing the following JSON to the /v1/agent/service/register endpoint:

```
{
  "ID": "web1",
  "Name": "web",
  "Port": 8000,
  "Check": {
    "Script": "curl -s localhost:8000",
    "Interval": "10s"
  }
}
```

Under 0.4.1 I see the service when I curl /v1/agent/services:

```
{
   "consul" : {
      "ID" : "consul",
      "Port" : 8300,
      "Tags" : [],
      "Service" : "consul"
   },
   "web1" : {
      "ID" : "web1",
      "Port" : 8000,
      "Tags" : null,
      "Service" : "web"
   }
}
```
 
and also in the UI.

Under 0.5.0 (v0.5.0rc1-120-g907bbfa.rc1 (907bbfa8c9fdd51e7e6d97fb5b3c4464eb14bd7d) to be precise) I also see the service (but note that "Address" is an empty string):

```
{
   "consul" : {
      "ID" : "consul",
      "Address" : "",
      "Port" : 8300,
      "Tags" : [],
      "Service" : "consul"
   },
   "web1" : {
      "ID" : "web1",
      "Address" : "",
      "Port" : 8000,
      "Tags" : null,
      "Service" : "web"
   }
}
```

However, it is NOT showing up in the UI.

The other clue which may lead to an answer (either a bug or a PEBKAC on my part) is that on the agent, I do see this:

```2015/02/13 14:45:00 [ERR] agent: failed to sync changes: ACL not found```

**Comment by pearkes** [comment]
Can you open up your dev console on your browser and see if there are any errors coming from the JavaScript?

**Comment by pearkes** [comment]
Thanks for reporting this!

**Comment by ryanuber** [comment]
This sounds like an anti-entropy problem, meaning the service definition can't be synced from the agent to the server. That would explain why you can see it in the agent's API, but not in the UI since it can't be synced to the catalog. Do you have an ACL token configured? Is it currently valid on the server?

Any further details will help us figure out what's going on.
Thanks!

**Comment by pete0emerson** [comment]
Well, nuts, I'm unable to replicate this. I just did a fresh test with a fresh data dir, and it's showing up in the UI. No clue what was happening before. I'll re-open if I can reliably reproduce.
