### ISSUE TITLE
Can consul support batch operation?

### ISSUE THREAD

**Issue by xdhuxc** [hashicorp/consul#7015]
Hello，It seems that consul does not support batch operation, I think it will be a wonderful feature.

#### Consul can support batch operation
I hope consul can support batch operation. in the case, we can create (delete or update) many kvs in a single request and consul will only trigger once. It is a useful function,  in many cases, we want this.

#### Use Case(s)
I am using confd to pull data from consul and using the watch feature of consul. Because consul does not support batch operation, every kv I insert to consul will trigger confd, this will cause seriously performance issues. I think it would be better if consul support batch support.

**Comment by i0rek** [comment]
Yes, consul supports batch operations through the transaction api: https://www.consul.io/api/txn.html.
