### ISSUE TITLE
Agent does not start without -bind on EC2 VPC instance

### ISSUE THREAD

**Issue by dgarstang** [hashicorp/consul#703]
Consul will not start as an agent on a EC2 VPC instance unless the -bind options is given. Otherwise, it fails with the error "Error starting agent: Failed to get advertise address: No private IP address found".

**Comment by armon** [comment]
Can you provide more information? We run all of our nodes in VPC without bind and have no issues.

**Comment by cetex** [comment]
I guess this is the same issue as https://github.com/hashicorp/consul/issues/725

By default, consul won't bind to any ip that isn't in the ranges:
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
The source is here https://github.com/hashicorp/consul/blob/master/consul/util.go

A VPC can be setup with any ip range, so if the vpc that @dgarstang has is using anything else than these ip's consul will refuse to start.

**Comment by armon** [comment]
@dgarstang Can you confirm if that is the case? @cetex is correct, Consul will not bind to a non-private address by default, but that behavior can be overridden with `-bind`.

**Comment by armon** [comment]
Closing for now, please re-open with more information.
