### ISSUE TITLE
node elected, but not - I cannot make sense of the logs

### ISSUE THREAD

**Issue by seropian** [hashicorp/consul#704]
Hi,

I have a 3-node cluster. It run 2 nodes, then I stopped master, and started it back on.
Here is an excerpt of the restarted master:
    2015/02/16 09:21:53 [INFO] consul: New leader elected: node1
    2015/02/16 09:21:53 [ERR] agent: failed to sync remote state: No cluster leader
    2015/02/16 09:21:53 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
    2015/02/16 09:22:12 [ERR] agent: failed to sync remote state: No cluster leader
    2015/02/16 09:22:41 [ERR] agent: failed to sync remote state: No cluster leader
    2015/02/16 09:22:50 [ERR] http: Request /v1/health/service/consul?dc=dc1&token=, error: No cluster leader

As you can see, the 2 nodes vote node1 back on, election is ok for node1, than the ERRs with no cluster leader keep going forever. I would expect a WARN/ERR saying why the election decision was reverted. 
Also I can see the node2 sees node1 as alive.

Please let me know what info can I provide,
node1 runs in docker 1.5.0 in virtualbox in mac, with ports forwarded (however ui reports node1 exporting only consul service)
node2 runs in docker 1.5.0 in linux (ui reports all services on node2, except now, when it appears as 500)

Thanks,
Nicu

**Comment by armon** [comment]
@seropian It's hard to tell without the logs from all the machines what is happening. There is clearly some issue preventing the leader election, but this is too limited of information to tell.

**Comment by nmarasoiu** [comment]
Thanks, I will close, the cluster works ok now..
