### ISSUE TITLE
Consul TRACE logs not available

### ISSUE THREAD

**Issue by fewknow** [hashicorp/consul#7041]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Attempting to try to look at trace logs of consul for debugging issue.  I am using `consul monitor -log-level trace` .   This just does [DEBUG] logs.  I am able to use this method with all the other levels ; debug,info,err and it seems to be working.

I expect their to be [TRACE] logs available and not just [DEBUG]

#### Reproduction Steps

Steps to reproduce this issue, eg:

Log onto server and navigate to /consul directory. 
set ENV variables
export CONSUL_HTTP_SSL=true
export CONSUL_HTTP_ADDR=localhost:8500
export CONSUL_CACERT=/consul/1.6.1/ssl/ca.crt
export CONSUL_CLIENT_CERT=/consul/1.6.1/ssl/server.crt

Run command `./consul monitor -log-leve trace.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
No Client for this issue
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
check_monitors = 0
check_ttls = 0
checks = 0
services = 0
build:
prerelease =
revision = 9be6dfc3
version = 1.6.1
consul:
acl = enabled
bootstrap = false
known_datacenters = 1
leader = false
leader_addr = 10.103.7.0:8300
server = true
raft:
applied_index = 524966
commit_index = 524966
fsm_pending = 0
last_contact = 40.203072ms
last_log_index = 524967
last_log_term = 2
last_snapshot_index = 524383
last_snapshot_term = 2
latest_configuration = [{Suffrage:Voter ID:02295c9e-ea02-189e-235e-4b65e51ff0b8 Address:10.103.6.222:8300} {Suffrage:Voter ID:cf2bb2fe-6b49-b127-e05d-c6ecc9e70b14 Address:10.103.6.250:8300} {Suffrage:Voter ID:4f982bff-6931-74ac-0dd1-1782d3776cad Address:10.103.7.0:8300}]
latest_configuration_index = 508418
num_peers = 2
protocol_version = 3
protocol_version_max = 3
protocol_version_min = 0
snapshot_version_max = 1
snapshot_version_min = 0
state = Follower
term = 2
runtime:
arch = amd64
cpu_count = 2
goroutines = 94
max_procs = 2
os = linux
version = go1.12.1
serf_lan:
coordinate_resets = 0
encrypted = true
event_queue = 0
event_time = 2
failed = 0
health_score = 0
intent_queue = 0
left = 0
member_time = 24
members = 5
query_queue = 0
query_time = 3
serf_wan:
coordinate_resets = 0
encrypted = true
event_queue = 0
event_time = 1
failed = 0
health_score = 0
intent_queue = 0
left = 0
member_time = 8
members = 3
query_queue = 0
query_time = 3

```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

vault@U01VDAALAPP0427:/consul> ./consul monitor -log-level=TRACE
2020/01/15 12:58:38 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:38 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:38 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:38 [DEBUG] http: Request GET /v1/snapshot (21.464515ms) from=10.103.7.145:43832
2020/01/15 12:58:39 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:39 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:39 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:39 [ERR] http: Request GET /v1/snapshot, error: failed to stream snapshot: read tcp 10.103.6.222:49799->10.103.7.0:8300: read: connection reset by peer from=10.103.7.145:43834
2020/01/15 12:58:39 [DEBUG] http: Request GET /v1/snapshot (18.859541ms) from=10.103.7.145:43834
2020/01/15 12:58:39 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:39 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:39 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:39 [DEBUG] http: Request GET /v1/snapshot (23.193626ms) from=10.103.7.145:43836
2020/01/15 12:58:40 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:40 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:40 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:40 [DEBUG] http: Request GET /v1/snapshot (25.825064ms) from=10.103.7.145:43838
2020/01/15 12:58:41 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:41 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:41 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:41 [DEBUG] http: Request GET /v1/snapshot (22.748418ms) from=10.103.7.145:43840
2020/01/15 12:58:42 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:42 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:42 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:42 [DEBUG] http: Request GET /v1/snapshot (22.448492ms) from=10.103.7.145:43842
2020/01/15 12:58:43 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:43 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:43 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:43 [DEBUG] http: Request GET /v1/snapshot (26.98096ms) from=10.103.7.145:43848
2020/01/15 12:58:44 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:44 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:44 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:44 [DEBUG] http: Request GET /v1/snapshot (21.291337ms) from=10.103.7.145:43850
2020/01/15 12:58:44 [DEBUG] memberlist: Stream connection from=10.103.7.0:50250
2020/01/15 12:58:45 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:45 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:45 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:45 [DEBUG] http: Request GET /v1/snapshot (21.500831ms) from=10.103.7.145:43852
2020/01/15 12:58:46 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:46 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:46 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:46 [DEBUG] http: Request GET /v1/snapshot (25.384664ms) from=10.103.7.145:43856
2020/01/15 12:58:47 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:47 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:47 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:47 [DEBUG] http: Request GET /v1/snapshot (22.146857ms) from=10.103.7.145:43858
2020/01/15 12:58:48 [DEBUG] memberlist: Initiating push/pull sync with: 10.103.7.145:8301
2020/01/15 12:58:48 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1
2020/01/15 12:58:49 [DEBUG] tlsutil: OutgoingRPCWrapper with version 1
2020/01/15 12:58:49 [DEBUG] tlsutil: OutgoingRPCConfig with version 1
2020/01/15 12:58:49 [DEBUG] http: Request GET /v1/snapshot (21.804411ms) from=10.103.7.145:43860
2020/01/15 12:58:50 [DEBUG] tlsutil: IncomingHTTPSConfig with version 1

**Comment by s-christoff** [comment]
Howdy @fewknow, 
It seems like there are only about 10~ trace level outputs in Consul. Some of them output when a script check is enabled, so I went ahead and set up a local script check file and was able to get one of the trace log lines to output:
```
consul monitor -log-level=TRACE
2020/01/16 20:57:29 [TRACE] agent: Check "mem-util" output: /bin/sh: /usr/bin/free: No such file or directory
2020/01/16 20:57:29 [DEBUG] agent: Check "mem-util" is "passing"
```

I think because there are so few trace outputs is why you are not seeing them. I am going to close this issue for now, but if you have any other concerns please feel free to reply and we can discuss them.
