### ISSUE TITLE
cache_max_age set to `0s` results in max_age being disabled

### ISSUE THREAD

**Issue by aglover-zendesk** [hashicorp/consul#7073]
#### Overview of the Issue

We have recently enabled Consul agent caching. Our main use case is to allow agents to continue functioning in case of a Consul Server outage, not to cache stale results for long periods (our topology changes too frequently).

For the majority of node/service/catalog queries, everything is using [Background Refresh Caching](https://www.consul.io/api/features/caching.html#background-refresh-caching). We can assume that we are serving non-stale results, unless the agent can't reach the servers. This gives us resilience against Consul server issues, without adding any staleness. This works great.

However, prepared queries are using [Simple Caching](https://www.consul.io/api/features/caching.html#simple-caching) and the only way to limit their staleness is with the `cache_max_age` configuration value, which corresponds to the `Cache-Control: max-age` API header. Because of this, we set `cache_max_age` to `0s` in our agent configuration. AFAICT, this combination of configuration values is the only way to enable agent caching for DNS, while ensuring prepared queries aren't stale.

But this doesn't work as expected. When querying prepared queries via DNS with `cache_max_age` set to `0s`, I would assume every query would result in a cache miss and fetching fresh results. Instead, the agent seems to be caching results forever. I believe this issue ultimately comes from [this line](https://github.com/hashicorp/consul/blob/34e6e23d43b55712486659ade4bab0f5fab05179/api/api.go#L695-L696)

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a trimmed down configuration file with the necessary bits for DNS caching, like this:
    ```
    {
      "dns_config": {
        "allow_stale": true,
        "enable_truncate": true,
        "only_passing": true,
        "use_cache": true,
        "cache_max_age": "0s"
      },
      "recursors": [
        "127.0.0.1"
      ]
    }
    ```
1. Run Consul agent in dev mode, specifying the config file: `consul agent -dev -config-file consul.conf.json`
1. Register a new entity in the catalog.
    ```
    $ cat catalog-entry.json
    {
      "Datacenter": "dc1",
      "Node": "foobar",
      "Address": "192.168.10.10",
      "Service": {
        "ID": "redis1",
        "Service": "redis",
        "Address": "192.168.10.10",
        "Port": 8000
      }
    }
    $ curl -X PUT --data @catalog-entry.json http://127.0.0.1:8500/v1/catalog/register
    ```
1. Create a prepared query.
    ```
    $ cat prepared-query.json
    {
      "Name": "my-query",
      "Service": {
        "Service": "redis",
        "OnlyPassing": false
      },
      "DNS": {
        "TTL": "10s"
      }
    }
    $ curl -X POST --data @prepared-query.json http://127.0.0.1:8500/v1/query
    {
        "ID": "bbe85f98-82bd-abb5-dd4d-a16e448e9365"
    }
    ```
1. Query the prepared query. Note the IP address returned
    ```
    $ dig my-query.query.consul @127.0.0.1 -p8600 +short
    192.168.10.10
    ```
1. Add another catalog entity, simulating a change in topology.
    ```
    $ cat new-catalog-entry.json
    {
      "Datacenter": "dc1",
      "Node": "foobar2",
      "Address": "1.2.3.4",
      "Service": {
        "ID": "redis1",
        "Service": "redis",
        "Address": "1.2.3.4",
        "Port": 8000
      }
    }
    $ curl -X PUT --data @new-catalog-entry.json http://127.0.0.1:8500/v1/catalog/register
    ```
1. Query the prepared query again. Note that the new node is not present in the results.
    ```
    $ dig my-query.query.consul @127.0.0.1 -p8600 +short
    192.168.10.10
    ```

If you set `cache_max_age` to any non-zero value, everything works as expected.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

Client and server are the same in this instance, since the issue can be reproduced with Consul agent in `-dev` mode.

</details>

<details>
  <summary>Server info</summary>

```
$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 1200f25+
	version = 1.6.2
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 37
	commit_index = 37
	fsm_pending = 0
	last_contact = 0
	last_log_index = 37
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:6ead0162-36fe-ae71-89f0-cc4ff4cb2121 Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 76
	max_procs = 8
	os = darwin
	version = go1.12.13
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Ubuntu 16.04 and 18.04 hosts, mix of Consul 1.6.1 and Consul 1.6.2 agents. 

### Log Fragments

No relevant log fragments, because no error or warning is emitted. Consul believes everything is fine :)

**Comment by dnephin** [comment]
Hello @aglover-zendesk, thank you for opening this issue! Sorry it has taken us a little while to reply.

You are correct about how this works. The `dns_config` applies to all the caches in the DNS server (the blocking refresh ones used by the catalog, as well as the simple caching used by prepared queries). Enabling the cache for the catalog queries also enables it for prepared queries. One option might be to allow different config for each of the caches used by the DNS server. That would unfortunate grow our config size quite a bit.

I believe it is expected that a zero value for a field indicates "no value". So `0s` for max_age is equivalent to not setting a max_age, which results in results being cached until the TTL expires. We probably need to document this better in a few places. I'll look for somewhere appropriate to document it. 

I think there may be a way to work around this problem without any code changes. If you set `max_age` to something very short, like `1ns` (1 nanosecond), it should behave the way you want. Anything supported by https://golang.org/pkg/time/#ParseDuration should be valid in this config field. You could also use a short value like `100ms` if you wanted some small amount of caching.

The `max_age` field is ignored by the blocking cache, so it won't change the behaviour of the other caches used by the DNS server.

**Comment by dnephin** [comment]
I see now that the [docs you linked](https://www.consul.io/api/features/caching.html#simple-caching) mention that the `max-age` HTTP header works differently for a zero value. I suspect that is to comply with [the specification for Cache-Control](https://tools.ietf.org/html/rfc7234#section-5.2.1.1).

It is unfortunate that the config and http headers work differently, but I do not think  we can change that now. I'll attempt to call that out as well in the docs change.

**Comment by aglover-zendesk** [comment]
> If you set max_age to something very short, like 1ns (1 nanosecond), it should behave the way you want. Anything supported by https://golang.org/pkg/time/#ParseDuration should be valid in this config field.

That's helpful, thanks @dnephin . 

Re: the absence of a fix - what I don't understand is that `0s` is a valid value for `Cache-Control: max-age` - you get a cache miss, the agent queries the server, a result is returned. The only reason it doesn't work for prepared queries over DNS is because you conditionally apply the header if `MaxAge` is greater than 0. I think the fix is literally a one-line PR - remove [this line](https://github.com/hashicorp/consul/blob/34e6e23d43b55712486659ade4bab0f5fab05179/api/api.go#L695) and _always_ append the `max-age` header, even if it's `0`.

I'd be happy to open a PR as long as Hashicorp is open to this type of fix.

**Comment by dnephin** [comment]
The DNS server does not use the HTTP API. The line you linked is in the client library for the HTTP API. The change you propose may be correct, but I don't think it will fix this issue. There is [special handling in the HTTP API](https://github.com/hashicorp/consul/blob/34e6e23d43b55712486659ade4bab0f5fab05179/agent/http.go#L793-L803) for the 0 value. In all other cases that I'm aware of a 0 value means "not set".

The DNS server passes [MaxAge as QueryOptions](https://github.com/hashicorp/consul/blob/34e6e23d43b55712486659ade4bab0f5fab05179/agent/dns.go#L1062-L1066), which is [used by the cache](https://github.com/hashicorp/consul/blob/v1.8.0/agent/cache/cache.go#L274-L278) to determine if the cached entry can be returned, or not.

We could change this behaviour, but as far as I know most places in Consul use 0 to mean unset. That is how `Index` fields work, and I imagine there are a bunch of others that work this way. I believe the HTTP `max-age` header is the special case .

**Comment by aglover-zendesk** [comment]
Got it, thanks for clarifying 👍
