### ISSUE TITLE
Dump acl configuration created via ui

### ISSUE THREAD

**Issue by FishmasterHM** [hashicorp/consul#7088]
HI, Im wondering, is there any way that i can dump my acl configurations that originally done via ui ?

**Comment by blake** [comment]
Hi @FishmasterHM,

There is not a single API / CLI call which would allow you to dump all policies. You would need to iterate over & read all of the policies manually.

Here are two example of how you could do that using the API and CLI. I will be using [curl](https://curl.haxx.se/) and/or [jq](https://stedolan.github.io/jq/) for the examples.

First, set the [CONSUL_HTTP_ADDR](https://www.consul.io/docs/commands/index.html#consul_http_addr) and [CONSUL_HTTP_TOKEN](https://www.consul.io/docs/commands/index.html#consul_http_token) in your environment.

```shell
export CONSUL_HTTP_ADDR=http://192.0.2.10:8500
export CONSUL_HTTP_TOKEN=6bf03bb8-b74c-4e38-abcd-640dbc250ee0
```

### API

List all policies in Consul by performing an HTTP GET on the [/acl/policies](https://www.consul.io/api/acl/policies.html#list-policies) endpoint. As you can see in [List Policies: sample output](https://www.consul.io/api/acl/policies.html#sample-response-4), the output does not contain the details of each policy. You need to issue a separate HTTP GET to [/acl/policy/:id](https://www.consul.io/api/acl/policies.html#read-a-policy) for each policy to obtain its details. 

Pipe the output of list policies to jq to create a new array containing just the policy IDs. Then use a `for` loop to iterate over the list of policy IDs and GET the details for each policy (see [sample request](https://www.consul.io/api/acl/policies.html#sample-response-1)).

```bash
for policy_id in $(curl -s -H "X-Consul-Token: $CONSUL_HTTP_TOKEN" $CONSUL_HTTP_ADDR/v1/acl/policies | jq -r 'map(.ID)[]'); do
  curl -s -H "X-Consul-Token: $CONSUL_HTTP_TOKEN" $CONSUL_HTTP_ADDR/v1/acl/policy/$policy_id\?pretty
done
```

### CLI

You could achieve the same using the CLI, however the output won't be as structured as is the case with JSON.

```bash
for policy_id in $(consul acl policy list | awk '/ID/ { print $2 }'); do
  consul acl policy read -id $policy_id
  # Add a line break between the next policy
  echo "\n"
done
```

These examples are relatively basic, but I hope they provide what you're looking for. I would recommend using one of Consul's many [SDKs](https://www.consul.io/api/libraries-and-sdks.html) if you are looking to automate this, and perform the policy dump at regular intervals.
