### ISSUE TITLE
Consul getting deregistered after certain time in AWS environment

### ISSUE THREAD

**Issue by hashim-mohammed** [hashicorp/consul#7089]
#### Overview of the Issue

We have found that the services that are registered in consul are getting deregistered after a time interval of 25 days. We have around 15-20 services registered in consul. What could be the reason for this occurrence?

 Consul Info
                                                                                                                                                                 agent:                                                                                                                                                                                                 check_monitors = 0                                                                                                                                                                             check_ttls = 16                                                                                                                                                                                checks = 16                                                                                                                                                                                    services = 16                                                                                                                                                                          build:                                                                                                                                                                                                 prerelease =                                                                                                                                                                                   revision = 9be6dfc3                                                                                                                                                                            version = 1.6.1                                                                                                                                                                        consul:                                                                                                                                                                                                acl = disabled                                                                                                                                                                                 bootstrap = true                                                                                                                                                                               known_datacenters = 1                                                                                                                                                                          leader = true                                                                                                                                                                                  leader_addr = 15.0.0.122:8300                                                                                                                                                                  server = true                                                                                                                                                                          raft:                                                                                                                                                                                                  applied_index = 1276248                                                                                                                                                                        commit_index = 1276248                                                                                                                                                                         fsm_pending = 0                                                                                                                                                                                last_contact = 0                                                                                                                                                                               last_log_index = 1276248                                                                                                                                                                       last_log_term = 5                                                                                                                                                                              last_snapshot_index = 1269706                                                                                                                                                                  last_snapshot_term = 5                                                                                                                                                                         latest_configuration = [{Suffrage:Voter ID:8f146041-94d3-ba3d-dade-706d1277f430 Address:15.0.0.122:8300}]                                                                                      latest_configuration_index = 1                                                                                                                                                                 num_peers = 0                                                                                                                                                                                  protocol_version = 3                                                                                                                                                                           protocol_version_max = 3                                                                                                                                                                       protocol_version_min = 0                                                                                                                                                                       snapshot_version_max = 1                                                                                                                                                                       snapshot_version_min = 0                                                                                                                                                                       state = Leader                                                                                                                                                                                 term = 5                                                                                                                                                                               runtime:                                                                                                                                                                                               arch = amd64                                                                                                                                                                                   cpu_count = 8                                                                                                                                                                                  goroutines = 189                                                                                                                                                                               max_procs = 8                                                                                                                                                                                  os = linux                                                                                                                                                                                     version = go1.12.1                                                                                                                                                                     serf_lan:                                                                                                                                                                                              coordinate_resets = 0                                                                                                                                                                          encrypted = false                                                                                                                                                                              event_queue = 1                                                                                                                                                                                event_time = 5                                                                                                                                                                                 failed = 0                                                                                                                                                                                     health_score = 0                                                                                                                                                                               intent_queue = 0                                                                                                                                                                               left = 0                                                                                                                                                                                       member_time = 1                                                                                                                                                                                members = 1                                                                                                                                                                                    query_queue = 0                                                                                                                                                                                query_time = 1                                                                                                                                                                         serf_wan:                                                                                                                                                                                              coordinate_resets = 0                                                                                                                                                                          encrypted = false                                                                                                                                                                              event_queue = 0                                                                                                                                                                                event_time = 1                                                                                                                                                                                 failed = 0                                                                                                                                                                                     health_score = 0                                                                                                                                                                               intent_queue = 0                                                                                                                                                                               left = 0                                                                                                                                                                                       member_time = 1                                                                                                                                                                                members = 1                                                                                                                                                                                    query_queue = 0                                                                                                                                                                                query_time = 1

### Operating system and Environment details

AWS-AMI 
Node.js - v10.16.3

### Log Fragments

Jan 03 05:24:37 ip-xx-x-x-xx.ec2.internal consul[10876]: agent: Check "service:default-codesmart-xx.x.x.xx-3026-464cb8eb-8e83-4f90-b9a4-dbab94bc4331" for service "default-codesmart-xx.x.x.xx-3026-464cb8eb-8e83-4f90-b9a4-dbab94bc4331" has been critical for too long; deregistered service
Jan 03 05:24:37 ip-x-x-x-xx.ec2.internal consul[10876]: agent: Check "service:default-workflowmanager-xx.x.x.xx-3040-5ca4abd1-1916-454d-9c46-49d15f33e1c9" for service "default-workflowmanager-xx.x.x.xx-3040-5ca4abd1-1916-454d-9c46-49d15f33e1c9" has been critical for too long; deregistered service

Jan 03 05:24:38 ip-xx-x-x-xx.ec2.internal consul[10876]: 2020/01/03 05:24:38 [INFO] agent: Deregistered check 'service:default-datastreammanager-xx.x.x.xx-3011-537b8124-20c0-4ae8-8428-222d3bf1aa7e'
Jan 03 05:24:38 ip-xx-x-x-xx.ec2.internal consul[10876]: agent: Deregistered check 'service:default-datastreammanager-xx.x.x.xx-3011-537b8124-20c0-4ae8-8428-222d3bf1aa7e'

**Comment by ChipV223** [comment]
@hashim-mohammed : Looking at the logs, it looks like the services are being deregistered due to failing health checks:

```
Jan 03 05:24:37 ip-x-x-x-xx.ec2.internal consul[10876]: agent: Check "service:default-workflowmanager-xx.x.x.xx-3040-5ca4abd1-1916-454d-9c46-49d15f33e1c9" for service "default-workflowmanager-xx.x.x.xx-3040-5ca4abd1-1916-454d-9c46-49d15f33e1c9" has been critical for too long; deregistered service
Jan 03 05:24:38 ip-xx-x-x-xx.ec2.internal consul[10876]: 2020/01/03 05:24:38 [INFO] agent: Deregistered check 'service:default-datastreammanager-xx.x.x.xx-3011-537b8124-20c0-4ae8-8428-222d3bf1aa7e'
Jan 03 05:24:38 ip-xx-x-x-xx.ec2.internal consul[10876]: agent: Deregistered check 'service:default-datastreammanager-xx.x.x.xx-3011-537b8124-20c0-4ae8-8428-222d3bf1aa7e'
```

Since you are running Consul on AWS, can you confirm if the firewall is configured correctly as all the required Consul ports are open?
