### ISSUE TITLE
Support Zone Transfers

### ISSUE THREAD

**Issue by awheeler** [hashicorp/consul#709]
It would be nice if the Consul servers would support slave DNS servers via Zone xfer.
There have been brief instances where all consul servers were down during an upgrade (no leader was being elected via the auto bootstrap, I ended up having to force an election), and during that time, all services were unavailable.
So, it would be great if dedicated DNS servers could cover that gap.

**Comment by armon** [comment]
We've thought about going down this path, but instead prefer to use something like consul-template to generate a valid BIND configuration and use that for zone xfer. It's just too much complexity to include in the core.

**Comment by nathanisaac-s** [comment]
I've looked into doing something similar with the Consul API (both from vanilla curl calls and via python-consul) and I'm finding that the steps needed to generate a DNS zone for xfer seem a little convoluted--is there a simple path that I'm missing that I could easily pass into consul-template?

**Comment by armon** [comment]
@nathanisaac-s We haven't actually attempted to generate a zone transfer, so I'm not sure. It's not a recommended pattern. Better to use DNS delegation or forwarding.

**Comment by alexinthesky** [comment]
Hi,
on the same subject, I am wondering how would you increment the serial of a zone file generated with consul-template?

thanks
Alex

**Comment by highlyunavailable** [comment]
@alexinthesky Use the datetime as the serial number? If you use `{{timestamp "unix"}}` then it'll return the unix time in seconds. Otherwise, check out the "timestamp" directive in the consul-template readme and it has alternative ways to format the time.

**Comment by blalor** [comment]
How about the Consul index from the watch?

**Comment by highlyunavailable** [comment]
@blalor if you can get that data, that would be a better serial, yes. I didn't see anything that let you access the consul index for consul-template.

**Comment by blalor** [comment]
Ah, right.  That’s an implementation detail for consul-template.  *sigh* Carry on.

**Comment by nathanisaac-s** [comment]
@highlyunavailable using the UNIX timestamp does generate a legal zonefile that will meet the DNS requirements for a higher serial number, but it's not strictly speaking a `+=1` increment which seems to be the original intent... In any case the unix timestamp has been my goto solution for the same issue as well so I'm not alone.

Would storing the DNS zone into a consul KV pair be one possibility?

**Comment by alexinthesky** [comment]
Thanks for your answers, i started storing the date in the format I liked in the kV store, but I'll use the timstamp instead, it totally fits my needs.

**Comment by awheeler** [comment]
The template I came up with for generating the zone file is pretty simple:
```
{{range services}}{{range service .Name}}
{{.Name}}       0      IN      A       {{.Address}}{{end}}{{end}}
```
But, I have a lot of services, and a lot of servers, and get this in the consul-template logs:
`watching 198 dependencies - watching this many dependencies could DDoS your consul cluster`
Is there a more efficient way to generate the zones that doesn't run the risk of DDoS'ing the servers?
Obviously using consul as a DNS doesn't have this problem, but as indicated in the OP, I've had some issues where I had no leaders, and suddenly all services were down.
Replicating this to a full DNS server handles that situation now w/o issue.

**Comment by alexinthesky** [comment]
@awheeler this fails if you have dots in the service names..... I ended up using the ID field, like that 

{{range services}}{{range service .Name "any"}}
{{.ID}} 60 A  {{.Address}}{{end}}{{end}}

but maybe there is a more elegant solution to introduce dots (I have no choice but to do this ) ?
