### ISSUE TITLE
Failed to retrieve the token list: Unexpected response code: 403

### ISSUE THREAD

**Issue by pkelleratwork** [hashicorp/consul#7095]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

- installed consul:1.6.2 via helm
- 3 consul servers created
- kubectl exec into server pod
- run `consul acl token list`
- get error `Failed to retrieve the token list: Unexpected response code: 403 (rpc error making call: Permission denied)`

OS, Architecture, and any other information you can provide about the environment.
kuberbetes deployment on aws

**Comment by HDYLOVEYL** [comment]
请问这个问题怎么解决的？
