### ISSUE TITLE
Add doc comments to exported functions in agent/agent.go

### ISSUE THREAD

**Issue by mkcp** [hashicorp/consul#7101]
There's a bunch of exported functions in https://github.com/hashicorp/consul/blob/master/agent/agent.go without doc comments. Adding some descriptions in would reduce linter warnings, and provide better access to the codebase for those who use doc-based tooling to explore and learn.

**Comment by vikkyomkar** [comment]
@mkcp i would like to contribute to this issue

**Comment by mkcp** [comment]
Awesome @vikkyomkar, looking forward to seeing your PR. Do you have any questions before you get started? Let us know if any come up during the writing process.

**Comment by shaqq** [comment]
@mkcp I ended up throwing up a PR, take a look when you can!
