### ISSUE TITLE
SIGSEGV when attempting to remove both a service and associated check in anti-entropy

### ISSUE THREAD

**Issue by crhino** [hashicorp/consul#7107]
#### Overview of the Issue

Found the issue through a test flake. May or may not be easily reproducible in the wild.

Running `make test-flake FLAKE_PKG=command/connect/proxy FLAKE_TEST=TestRegisterMonitor FLAKE_N=100 FLAKE_CPUS=0.05` results in:

```
2020-01-22 17:40:48 - (1/100)
2020-01-22 17:40:58 - (2/100)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x17672bc]

goroutine 101 [running]:
github.com/hashicorp/consul/agent/local.(*State).deleteService(0xc0002ba0e0, 0xc0004c12c0, 0x9, 0x300010002, 0x1000200000003, 0xc0000bc720)
	/Users/chrispiraino/workspace/consul/agent/local/state.go:1100 +0x3ec
github.com/hashicorp/consul/agent/local.(*State).SyncChanges(0xc0002ba0e0, 0x0, 0x0)
	/Users/chrispiraino/workspace/consul/agent/local/state.go:1037 +0x202
github.com/hashicorp/consul/agent/local.(*State).SyncFull(0xc0002ba0e0, 0x0, 0x308981f)
	/Users/chrispiraino/workspace/consul/agent/local/state.go:1018 +0x5c
github.com/hashicorp/consul/agent/ae.(*StateSyncer).nextFSMState(0xc00004cf80, 0x307e532, 0x8, 0x307e532, 0x8)
make: *** [test-flake] Error 1
```

Investigating further, the seg fault appears to happen because of attempting to delete/prune a after a `SyncFull` call, which ends up re-adding the `CheckID` to the `checks` map [here](https://github.com/hashicorp/consul/blob/b71630b752539068e48f44367e1179ad55685864/agent/local/state.go#L962), That is then referenced [here](https://github.com/hashicorp/consul/blob/b71630b752539068e48f44367e1179ad55685864/agent/local/state.go#L1096), catching a `nil` value of `c.Check` and seg faulting.

Wrote up a better test reproduction and will add it as a unit test in the fix.

**Comment by mkcp** [comment]
Nice one! Going to mark this related to #7042
