### ISSUE TITLE
Option to not leave cluster automatically on quit

### ISSUE THREAD

**Issue by hoffoo** [hashicorp/consul#714]
In my use case I would like a node to not leave the cluster automatically when it shuts down. As it stands when consul quits it leaves the cluster and its services are unregistered; this makes it difficult to be absolutely certain about all the services and nodes that are currently available (ie. consul was shut down and now its services disappear instead of getting marked as failing). What I really want is a service to be considered failing if consul isn't running.

This is somewhat related to #244 because in this case we wouldn't want the node to be reaped either. 

This would be really great as a configuration option, something like "leave_on_quit" which defaults to true.

**Comment by highlyunavailable** [comment]
Check out http://www.consul.io/docs/agent/options.html#skip_leave_on_interrupt and http://www.consul.io/docs/agent/options.html#leave_on_terminate . Is this what you're looking for?

I think skip_leave_on_interrupt set to true and leave_on_terminate set to false is what you'd want.

**Comment by hoffoo** [comment]
@highlyunavailable this is exactly what i needed, thanks a lot!
