### ISSUE TITLE
Add `-format=json` flag to the ACL CLI commands

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#7141]
#### Feature Description

After reviewing some of the upcoming guide updates for ACLs it seemed like allowing these CLI commands to output the JSON response instead of the normal formatting might be better in some cases. This would be particularly useful if we want to post-process the result with `jq` or some other tool to grab a token secret or policy id.

This request is to add a `-format` option that defaults to `pretty` (our default format) but has the option to be specified as `json` and in that case we will just output the JSON response.

**Comment by mullakhmetov** [comment]
@mkeeler could you please review my attempt? #7198
