### ISSUE TITLE
Securing Consul Web UI

### ISSUE THREAD

**Issue by yakhyadabo** [hashicorp/consul#7150]
I come from [this thread](https://github.com/hashicorp/consul/issues/1720).

My main concern is to know what's the proper way to secure the consul ui. 
I've read the documentation and it's not mentioned anywhere.

**Comment by ashleyprimo** [comment]
You can enable mTLS on the web interface of Consul; see https://www.consul.io/docs/internals/security.html

**Comment by johncowen** [comment]
Hi @yakhyadabo 

Thanks for the answer there @ashleyprimo !

Related to that, from looking at that thread you linked to, did you want to add a password to the Consul UI?

If so, we currently recommend running the UI behind a proxy with some sort of authentication on the proxy (so using nginx or similar). We have spoken amongst the team about potentially adding some sort of OAuth or similar to the UI itself (also see https://github.com/hashicorp/consul/issues/4367), but there is nothing super definite on that as yet. I'll update you here when I know more.

Thanks,

**Comment by yakhyadabo** [comment]
Ok @johncowen, 

I will be relying on ACLs so secure the UI. 

Regards,

**Comment by johncowen** [comment]
Hey @yakhyadabo 

If your UI installation will be available publicly please be aware that there is some information that cannot be restricted by ACLs, i.e. the names of your datacenters, the Consul version you are running.

If you are exposing the Consul API/UI publicly and you do not want that information exposed, we'd recommend putting an authentication proxy in front of it.

**Comment by yakhyadabo** [comment]
The cluster is not publicly exposed.
