### ISSUE TITLE
Allow providing token in service definition

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#716]
There is currently no way to provide a token along with a service registration such that the token has higher priority than the `ACLToken`. This is an issue since the agent may have reduce or no privileges, but an application may wish to register with its own elevated permissions.

**Comment by anthonybishopric** [comment]
:+1: for this, we are currently in that situation now where we allow read access on services but our privileged agent may write them using its token.

**Comment by armon** [comment]
Fixed by #891
