### ISSUE TITLE
consul connect envoy hangs when $CONSUL_CACERT references many certificates

### ISSUE THREAD

**Issue by hamann** [hashicorp/consul#7168]
## Overview of the Issue

With newest 1.7.0-beta3 we painfully realized that `consul connect envoy` hangs when $CONSUL_CACERT is set to something like `/etc/ssl/certs/ca-certificates.crt` or a file which includes many certificates - we added our certificates with `update-ca-certificates` so that most programs will work without further configuration.
The reason for this issue is that since https://github.com/hashicorp/consul/pull/6822 certificates now will be inlined into the bootstrap json and with a json >= 65536 bytes (default pipe buffer size on linux) https://github.com/hashicorp/consul/blob/cc9a6f79934a6da58b7aec63c057681d82aded5a/command/connect/envoy/exec_unix.go#L96
will block until something reads from the pipe.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. export `CONSUL_CACERT=/etc/ssl/certs/ca-certificates.crt`
2. consul connect envoy -sidecar-for service-id
3. process blocks without any logs

**Comment by jsosulska** [comment]
Hi @hamann 

Thanks for reporting this issue, and apologies for the delay in reply. Have you tried the [`ca-path`](vhttps://www.consul.io/docs/commands/connect/envoy.html#ca-path-lt-value-gt-)/`CONSUL_CAPATH` value instead of CACERT?

Please let me know if you are still running into this issue, or if there was an alternative resolution.

Happy Coding,

**Comment by hamann** [comment]
@jsosulska We pointed CONSUL_CACERT to a file containing only the important cert, that fixed it for us

**Comment by jsosulska** [comment]
Thank you for the response! I hope this helps others as well :)
Please 👍 if this issue can be closed, otherwise it will be closed on Friday.
