### ISSUE TITLE
Static ACL definitions

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#717]
Similar to checks and services, we should support some way to provide static ACL definitions that are loaded by the agent. Not clear how this is done given that the IDs are uniquely generated.

**Comment by colinrymer** [comment]
What if this used a similar mechanism to the `acl_master_token` generation? You provide the `id` and consul generates the policy:

```json
{
  ...
  "acl_policy": {
    "id": "this_is_a_uuid",
    "name": "my policy",
    "type": "client",
    "rules": {
      "key": {
        "foo/private": {
          "policy": "deny"
        }
      },
      "service": {
        "": {
          "policy": "write"
        },
        "secure": {
          "policy": "read"
        }
      }
    }
  }
}
```

The big concern with this approach would be id collisions - not sure how best to handle that scenario.

**Comment by sheldonh** [comment]
Pretty please! This would make it SOOO much easier to provision Vault+Consul with Terraform.

For static policies, the ID is pretty much a non-issue. Most of the time, I'll just include the ID in the policy, because it's an ID I already produced with uuidgen and intend to distribute to clients (like Vault).

If I don't give you an ID, I'm either being very clever or I'm being an idiot. Either way, give me what I deserve (with a randomly generated ID that I have to go find for myself somehow).

**Comment by sheldonh** [comment]
In fact, I'd go so far as to say that, if it makes implementation easier, static ACLs should *require* an ID.

**Comment by colinrymer** [comment]
@armon any thoughts on this? I'd really love to get our ACL definitions in source control!

**Comment by armon** [comment]
@colinrymer It's now possible with some of the changes in Consul 0.5.2, but wasn't previously. It's on our roadmap, but no definitive timeline yet. It should be pretty easy to whip up a script using our API currently to scan files in a dir and hit the API.

**Comment by slackpad** [comment]
I'm thinking a nice way to do this might be to configure servers with a static https://www.consul.io/api/txn.html body to run right after bootstrapping. If we add ACLs to transactions (it's designed to be open), then you can do whatever transactions can do when your cluster bootstraps, like set up some KV, make some ACLs, etc.

**Comment by pearkes** [comment]
Wanted to note that once https://github.com/terraform-providers/terraform-provider-consul/pull/60 is merged you will be able to manage ACLs via Terraform.
