### ISSUE TITLE
Confusing error when configuring encryption

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#718]
I started the agent and server with `-encrypt`.  Then I added installed and enabled a new key.  Finally I deleted the old key (the one initially used with `-encrypt`).  Upon restarting the agent, I see:

    ==> WARNING: LAN keyring exists but -encrypt given, ignoring

Obviously the LAN keyring is taking precedence over the one given with `-encrypt`, but the warning message is misleading.

**Comment by ryanuber** [comment]
@blalor ah, re-reading the message now it does sound a little ambiguous (**what** is it ignoring?). I'll clarify.

**Comment by ryanuber** [comment]
@blalor the message should now read:
```
WARNING: LAN keyring exists but -encrypt given, using keyring
```

Thanks for the report!

**Comment by blalor** [comment]
:+1:
