### ISSUE TITLE
Add "version added" in the documentation

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/consul#720]
Hello.

When we browse the documentation, we don't know if the feature is available only in XX version, or if it's available in version YY.

I come from PHP/Symfony world, and we have (I think) a very good UX. As you can see in the [documentation](http://symfony.com/doc/current/components/process.html#usage) we have hint:

>  2.5: The mustRun() method was introduced in Symfony 2.5.

and on the right top of the page, we have a version selector.

**Comment by ryanbreen** [comment]
That looks really slick!  Even barring a UI like that, we should definitely add detail as to when a feature was added.  That's provided for a small number of options / features, but it's a good idea to do an audit and specifically denote things added in 0.4 and 0.5 (I'm assuming no one is using anything earlier than 0.3, but I'm not sure how fair that is).

**Comment by ryanuber** [comment]
So far we have punted this onto our [changelog](https://github.com/hashicorp/consul/blob/master/CHANGELOG.md). We are looking into ways to make the API documentation better, which maybe could include hints like this. If we introduce hints for commands, flags, guides, and all other documentation, I think we need to find a way to make it non-intrusive on the overall look. It could make things start looking messy if we just have `Available since x.y.z` everywhere.

Thanks for the suggestion! Let's keep this open for more design-minded people to comment.

**Comment by armon** [comment]
I agree, this is a great idea. It's done sporadically in places, but it would be nice to have more uniformly.

**Comment by sethvargo** [comment]
@armon @ryanuber this is something that has come up in almost all of our projects at least once. I think we could build something into middleman-hashicorp in the frontmatter or some type of common annotation that we use.

**Comment by pearkes** [comment]
Yea, I think @sethvargo has a good point in that we can just build this into middleman-hashicorp. 

Design wise, a subtle `> v0.5` underneath the doc title or w/e would be a good approach and not clutter things too much IMO.

**Comment by pearkes** [comment]
But yea, I also agree with @ryanuber that if we do it inline full width across the text it could get tiresome/distracting. Need something a little quieter.

**Comment by dpkp** [comment]
another approach might be to have versioned documentation, something like `consul.io/docs/latest/index.html` w/ a small footer or sidebar link to switch from `latest` to a prior version.  That's how I've seen projects on readthedocs manage this.

**Comment by slackpad** [comment]
We've been adding "version added" as we go for now, and there are some internal projects working on more general versioning for documentation. I'm going to close this out since it's tracked elsewhere internally and will be done across all the projects.
