### ISSUE TITLE
consul clients not discovering consul server

### ISSUE THREAD

**Issue by KRISHS68** [hashicorp/consul#7208]
#### Overview of the Issue

due to outage we encountered consul no leader issue , we deleted the old cluster and recreated new consul server cluster and joined the same to TCP and UDP LB , however after this our consul clients running in DB are not able to discover the new consul server IP's and join cluster.

we have 'retry_join' parameter in client json to auto join using consul network tag.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. remove consul cluster which has no leader issue
2. create new consul cluster and join it to loadbalancer
3. consul client wouldnt join new consul cluster ,even 'retry_join' is configured , and keeps trying with old cluster ip's

### Operating system and Environment details

Centos7 VM in GCP 

### Log Fragments

Jan 22 06:58:53 sskafkacontrolcenterdev-dev531-v000-r416 consul-template[21034]: 2020/01/22 06:58:53.494266 [WARN] (view) kv.block(kafka/ss-kafka-control-center-dev/BROKERS): Unexpected res
Jan 22 06:58:53 sskafkacontrolcenterdev-dev531-v000-r416 consul-template[21034]: 2020/01/22 06:58:53.983868 [WARN] (view) health.service(ss-zk-carbon-dev|passing): Unexpected response code:
Jan 22 06:59:47 sskafkacontrolcenterdev-dev531-v000-r416 consul-template[21034]: 2020/01/22 06:59:47.215667 [ERR] (view) health.service(ss-kafka-npe-dev|passing): Unexpected response code:
Jan 22 06:59:47 sskafkacontrolcenterdev-dev531-v000-r416 consul-template[21034]: 2020/01/22 06:59:47.215693 [ERR] (runner) watcher reported error: health.service(ss-kafka-npe-dev|passing):
Jan 22 06:59:47 sskafkacontrolcenterdev-dev531-v000-r416 consul-template[21034]: 2020/01/22 06:59:47.215747 [ERR] (cli) health.service(ss-kafka-npe-dev|passing): Unexpected response code: 5
Jan 22 06:59:47 sskafkacontrolcenterdev-dev531-v000-r416 systemd[1]: consul-template.service: main process exited, code=exited, status=14/n/a
Jan 22 06:59:47 sskafkacontrolcenterdev-dev531-v000-r416 systemd[1]: Unit consul-template.service entered failed state.
Jan 22 06:59:47 sskafkacontrolcenterdev-dev531-v000-r416 systemd[1]: consul-template.service failed.
Jan 22 09:06:48 sskafkacontrolcenterdev-dev531-v000-r416 systemd[1]: Starting Consul-Template Daemon…

2020/01/22 06:55:26 [INFO] serf: attempting reconnect to consulserver-npe-v003-01hh 10.148.1.225:8301
Jan 22 06:55:28 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: 2020/01/22 06:55:28 [WARN] manager: No servers available
Jan 22 06:55:28 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: manager: No servers available
Jan 22 06:55:28 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: 2020/01/22 06:55:28 [ERR] agent: Coordinate update error: No known Consul servers
Jan 22 06:55:28 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: agent: Coordinate update error: No known Consul servers
Jan 22 06:55:42 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: 2020/01/22 06:55:42 [WARN] manager: No servers available
Jan 22 06:55:42 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: manager: No servers available
Jan 22 06:55:42 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: 2020/01/22 06:55:42 [ERR] dns: rpc error: No known Consul servers
Jan 22 06:55:42 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: 2020/01/22 06:55:42 [WARN] manager: No servers available
Jan 22 06:55:42 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: 2020/01/22 06:55:42 [ERR] dns: rpc error: No known Consul servers
Jan 22 06:55:42 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: dns: rpc error: No known Consul servers
Jan 22 06:55:42 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: manager: No servers available
Jan 22 06:55:42 sskafkacontrolcenterdev-dev531-v000-r416 consul[16777]: dns: rpc error: No known Consul servers

**Comment by blake** [comment]
Hi @KRISHS68,

Sounds like you're running into the same issue as described in #6672. I just replied to your thread on Discuss (https://discuss.hashicorp.com/t/consul-client-not-joining-server-after-outage/5427)  clarifying the behavior of the `retry_join` option.

Would it be okay if we continue this conversation on that thread?

**Comment by KRISHS68** [comment]
Thanks blake , yeah i would udpate for any questions in the thread
