### ISSUE TITLE
No leader on single-node cluster after 0.4.1 → 0.5.0 upgrade

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul#721]
As @ryanuber and I were discussing in #consul, after upgrading from 0.4.1 to 0.5.0 my single-node cluster (operating necessarily in bootstrap mode) has no leader.  It does self-elect but then steps down.  Starting up a *new* single node cluster with an empty data-dir does not exhibit this problem.

config:
```json
{
    "node_name": "consul-001.us-east-1.aws.dev.example.com",
    "datacenter": "wpd_us-east-1_aws_dev",
    "server": true,
    "rejoin_after_leave": true,
    "bootstrap": true,
    "data_dir": "/var/lib/consul",
    "ui_dir": "/usr/share/consul/ui",
    "enable_syslog": true
}
``` 

log:
```
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'consul-001.us-east-1.aws.dev.example.com'
        Datacenter: 'wpd_us-east-1_aws_dev'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 10.132.254.166 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2015/02/20 18:38:34 [INFO] raft: Restored from snapshot 3-663909-1424334937771
    2015/02/20 18:38:34 [INFO] raft: Node at 10.132.254.166:8300 [Follower] entering Follower state
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: EventMemberJoin: consul-001.us-east-1.aws.dev.example.com 10.132.254.166
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: Ignoring previous leave in snapshot
    2015/02/20 18:38:34 [INFO] serf: EventMemberJoin: consul-001.us-east-1.aws.dev.example.com.wpd_us-east-1_aws_dev 10.132.254.166
    2015/02/20 18:38:34 [INFO] serf: Attempting re-join to previously known node: web-wpdsvc-002.dev.example.com: 10.132.4.60:8301
    2015/02/20 18:38:34 [INFO] consul: adding server consul-001.us-east-1.aws.dev.example.com (Addr: 10.132.254.166:8300) (DC: wpd_us-east-1_aws_dev)
    2015/02/20 18:38:34 [WARN] serf: Failed to re-join any previously known node
    2015/02/20 18:38:34 [INFO] consul: adding server consul-001.us-east-1.aws.dev.example.com.wpd_us-east-1_aws_dev (Addr: 10.132.254.166:8300) (DC: wpd_us-east-1_aws_dev)
    2015/02/20 18:38:34 [ERR] agent: failed to sync remote state: No cluster leader
    2015/02/20 18:38:36 [WARN] raft: Heartbeat timeout reached, starting election
    2015/02/20 18:38:36 [INFO] raft: Node at 10.132.254.166:8300 [Candidate] entering Candidate state
    2015/02/20 18:38:36 [INFO] raft: Election won. Tally: 1
    2015/02/20 18:38:36 [INFO] raft: Node at 10.132.254.166:8300 [Leader] entering Leader state
    2015/02/20 18:38:36 [INFO] consul: cluster leadership acquired
    2015/02/20 18:38:36 [INFO] consul: New leader elected: consul-001.us-east-1.aws.dev.example.com
    2015/02/20 18:38:36 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2015/02/20 18:38:37 [INFO] raft: Removed ourself, transitioning to follower
    2015/02/20 18:38:37 [INFO] raft: Node at 10.132.254.166:8300 [Follower] entering Follower state
    2015/02/20 18:38:37 [INFO] consul: cluster leadership lost
    2015/02/20 18:38:37 [INFO] consul: member 'sandbox-jsteadman.dev.example.com' reaped, deregistering
    2015/02/20 18:38:37 [ERR] consul: failed to reconcile: No cluster leader
    2015/02/20 18:38:38 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
    2015/02/20 18:38:38 [ERR] agent: failed to sync remote state: No cluster leader
    2015/02/20 18:38:44 [INFO] serf: Attempting re-join to previously known node: ip-10-129-1-206: 10.132.254.166:8301
    2015/02/20 18:38:44 [INFO] serf: Re-joined to previously known node: ip-10-129-1-206: 10.132.254.166:8301
```

**Comment by ryanuber** [comment]
@blalor shared some debug logs with me, which included this raft log:
```
    2015/02/20 19:32:34 [DEBUG] raft: Node 10.129.1.145:8300 updated peer set (3): []
```

Looking at the raft code, it's obvious why this log causes this problem. Need to look into how we get into this state to begin with. Perhaps a graceful leave on a single-node cluster is how we get here(?).

**Comment by blalor** [comment]
Bumping this.  Should I wait for a fix or just blow away the raft directory on my single-node clusters so I can get them back up and running?

**Comment by ryanuber** [comment]
@blalor I haven't been able to get a repro case on this. I tried starting up a 0.4.1 single-server cluster with 1 client and then upgrading it to 0.5, but things worked normally, so the upgrade by itself doesn't seem to be the problem. Are there any steps you've been able to reproduce this with?

**Comment by blalor** [comment]
I’ve got two single-node clusters that still won’t start; does that count as reproducible? :-)  Otherwise, no.  I can share the raft dir with you if that’ll help.

**Comment by armon** [comment]
@blalor The simplest fix is to just blow away the data dir. There was a regression in 0.4.1 that changes how single node clusters worked, which is why the 0.4.0 -> 0.4.1 and the 0.4.1 -> 0.5.0 transitions have been problematic.

**Comment by blalor** [comment]
Gah, I think this problem is also impacting my ability to enable encryption in the cluster.  I previously had no encryption enabled at all.  Now that I’m trying to roll through my servers to turn it on, I’ve got a cluster with no leaders and I can’t restart one of them with bootstrap: true because it keeps stepping down.

**Comment by armon** [comment]
@blalor What may be possible is to actually start another server (no bootstrap), then edit the peers file to have both of the servers.

**Comment by armon** [comment]
Single server mode is a bit of a special snowflake, where the multi-server case may just fix this

**Comment by blalor** [comment]
Ok, I'm declaring bankruptcy and nuking the raft dir.  This just isn't working.  modifying peers sort of worked, but now I'm getting this error:
```
    2015/02/23 19:02:41 [WARN] raft: Election timeout reached, restarting election
    2015/02/23 19:02:41 [INFO] raft: Node at 10.130.2.135:8300 [Candidate] entering Candidate state
    2015/02/23 19:02:41 [DEBUG] memberlist: Responding to push/pull sync with: 10.130.2.135:44138
    2015/02/23 19:02:41 [ERR] memberlist: Failed to receive remote state: Encryption is configured but remote state is not encrypted
    2015/02/23 19:02:41 [ERR] raft: Failed to make RequestVote RPC to 10.130.2.135:8301: EOF
    2015/02/23 19:02:41 [ERR] raft: Failed to make RequestVote RPC to 10.130.0.248:8301: EOF
    2015/02/23 19:02:41 [ERR] raft: Failed to make RequestVote RPC to 10.130.1.77:8301: EOF
```

Looks like enabling encrypting on an existing cluster has some issues.

**Comment by armon** [comment]
@blalor You cannot have a cluster with partial encryption, it's sort of all-or-nothing.

**Comment by blalor** [comment]
I can definitely reproduce the original issue here by changing the `advertise_addr` setting.  If I start server without the option, add the option, then restart the server, it immediately drops itself as a leader after election.

**Comment by MrMMorris** [comment]
I ran into something similar to this when trying to enable encryption. Wiping the `raft/` directory forced an election :grinning:. Thanks for the tip!

**Comment by blalor** [comment]
Still having this problem with 0.5.2.  I had two servers, removed one, set `bootstrap` to `true` on the remaining one, and now the sole server demotes itself again and refuses to remain a leader.

**Comment by slackpad** [comment]
Sorry for the late reply on this one - having two servers and then taking one down and running bootstrap per https://github.com/hashicorp/consul/issues/721#issuecomment-109061739 will result in a split brain. We've updated the outage guide with more details https://www.consul.io/docs/guides/outage.html and we've done lots of work on Raft peer management in Consul 0.7 so closing this out.
