### ISSUE TITLE
Consul connect configure envoy circuit breakers

### ISSUE THREAD

**Issue by rrondeau** [hashicorp/consul#7211]
Hi

I'm using consul connect in ours k8s clusters to interconnect services.
We are using envoy proxy and want to customize circuit_breakers values for some services.

I try to use service-defaults or service-router central configs but we did not find anything we wanted.
We tried to use the new limits block on proxy upstream definition but this only set circuit breaker limits for upstream clusters and not for the local_app envoy proxy.

For now we are overriding the consul connect dynamic cluster configs with `envoy_cluster_json` and also overriding `envoy_local_cluster_json` for the public listener cluster limits.

This is pretty complex and i would like to know if there is a better/simpler solution for this ?

Do you have any plans to support this type of configs in the consul central configs ?

**Comment by jsosulska** [comment]
Hi @rrondeau ,

Thanks for requesting this, and apologies for the delayed response. I will dig into this and see if I can find more information. You may find other peoples' recommendations to this question on our [forums](discuss.hashicorp.com) as well. 

Thanks for your patience!

**Comment by dnephin** [comment]
@rrondeau if possible could you share your `envoy_cluster_json` and `envoy_local_cluster_json` config? That would be very helpful. Thank you!

**Comment by jsosulska** [comment]
Hi @rrondeau ,

Please let us know if this is still an issue. As @dnephin mentioned, it would be really helpful to see your configs.

An additional question - How are you deploying Consul to K8s? Is it through the Consul-helm chart?

Best,
Jono

**Comment by rrondeau** [comment]
Hi
We are using consul-helm chart and consul-k8s injector.
I forked and re-build the consul-k8s injector with a custom service template.

The local cluster part :
```
      envoy_local_cluster_json = <<EOL
        {
          "@type": "type.googleapis.com/envoy.api.v2.Cluster",
          "name": "local_app",
          "type": "STATIC",
          "connect_timeout": "30s",
          "circuit_breakers": {
            "thresholds": [
              {
                "priority": "DEFAULT",
                "max_connections": 100000,
                "max_pending_requests": 100000,
                "max_requests": 100000,
                "max_retries": 3
              },
              {
                "priority": "HIGH",
                "max_connections": 100000,
                "max_pending_requests": 100000,
                "max_requests": 100000,
                "max_retries": 3
              }
            ]
          },
          "load_assignment": {
            "cluster_name": "local_app",
            "endpoints": [
              {
                "lb_endpoints": [
                  {
                    "endpoint": {
                      "address": {
                        "socket_address": {
                          "address": "127.0.0.1",
                          "port_value": {{ .ServicePort }}
                        }
                      }
                    }
                  }
                ]
              }
            ]
          }
        }
      EOL
```
And the upstream cluster part :
```
        envoy_cluster_json = <<EOL
          {
            "@type": "type.googleapis.com/envoy.api.v2.Cluster",
            "name": "{{ .Name }}",
            "type": "EDS",
            "eds_cluster_config": {
              "eds_config": {
                "ads": {}
              }
            },
            "connect_timeout": "5s",
            "circuit_breakers": {
              "thresholds": [
                {
                  "priority": "DEFAULT",
                  "max_connections": 100000,
                  "max_pending_requests": 100000,
                  "max_requests": 100000,
                  "max_retries": 3
                },
                {
                  "priority": "HIGH",
                  "max_connections": 100000,
                  "max_pending_requests": 100000,
                  "max_requests": 100000,
                  "max_retries": 3
                }
              ]
            },
            "alt_stat_name": "{{ .Name }}"
          }
        EOL
```

**Comment by devilmind81** [comment]
How can I override the limits of a specific envoy related to a specific service running on my k8s cluster?

I'm using consul 1.9.1 on k8s with autoinjection enabled by default.

Thank you in advance.

**Comment by blake** [comment]
@rrondeau @devilmind81 Consul 1.10 (currently in beta) supports configuring circuit breakers via the service-defaults config entry.  An example configuration can be found at https://www.consul.io/docs/connect/config-entries/service-defaults#upstream-configuration-beta.

You can test this on Kubernetes, and configure the limits using CRDs, by deploying version [0.32.0-beta2](https://github.com/hashicorp/consul-helm/releases/tag/v0.32.0-beta2) of the Helm chart.

Please take a look and let me know whether this satisfies your requirements.

**Comment by rrondeau** [comment]
Thanks for the heads up @blake !
I will be happy to test this when the 1.10 will be released :-)

**Comment by hamishforbes** [comment]
Has anyone managed to get this to work in Consul 1.10?
I've finally gotten around to upgrading my cluster and now everything is running on 1.10.3 (using the 0.36.0 Helm chart)

But no matter what combination of `service-default` config entries i create I cannot get `MaxConnections` to pass through to my Envoy sidecars?

I am testing with 2 services `api-gateway` and `scala-api`.
I've set defaults and service specific overrides in both service defaults (with different values so i can identify them if they get used), but the /config_dump endpoint on Envoy still shows an empty circuit breakers config.

I am using prepared queries in my upstream annotations, could this be causing a problem?

**Comment by hamishforbes** [comment]
> I am using prepared queries in my upstream annotations, could this be causing a problem?

Would appear to be the problem!  
In case anyone else stumbles across this issue I've filed a separate bug for here:
https://github.com/hashicorp/consul/issues/11613
