### ISSUE TITLE
ui: 1.7.0-beta4+ent - chosen namespace not rendered correctly

### ISSUE THREAD

**Issue by fredrikhgrelland** [hashicorp/consul#7229]
#### Overview of the Issue
The ui does not render the "check-mark" next to the currently chosen namespace, but rather in the middle of the area.

![image](https://user-images.githubusercontent.com/40291976/73891229-15f4ea80-4874-11ea-8f61-fec509408d20.png)

Left chrome, right firefox in ubuntu 16.04

#### Reproduction Steps
create 2 additional namespaces and observe.

### Consul info for both Client and Server

1.7.0-beta4+ent linux 64

**Comment by johncowen** [comment]
Just a quick thanks for the spot @fredrikhgrelland 🙌. We hit a strange problem with our CSS compiler/minifier. We've merged a fix for this so I'm going to close this now.
