### ISSUE TITLE
Not possible to use gossip encryption without a warning in the logs

### ISSUE THREAD

**Issue by mikehardenize** [hashicorp/consul#7231]
#### Overview of the Issue

First time I start consul with a blank slate, I have `encrypt = "key"` in my config file and I get `Encrypt: Gossip: true` in the output. If I restart consul, it warns me that I supplied "encrypt" again, but there is a keyring and it's going to use that instead. So I remove the "encrypt" option from my config, to get rid of the warning, assuming it will just use the keyring. Instead after restarting, I just get `Encrypt: Gossip: false` - It seems like the only option is to leave "encrypt" in the config and ignore the warning. It's like you can't have encrypted gossip without also having this warning.

#### Reproduction Steps

Steps to reproduce this issue:

Do as I described in the overview

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 7f3b5f34
	version = 1.6.3
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.150.0.13:8300
	server = true
raft:
	applied_index = 45
	commit_index = 45
	fsm_pending = 0
	last_contact = 0
	last_log_index = 45
	last_log_term = 3
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:4cb7c3a4-097d-2ece-a4b0-7efba281f21d Address:10.150.0.13:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 3
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 84
	max_procs = 1
	os = linux
	version = go1.12.13
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 1
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
</details>

### Operating system and Environment details

CentOS 7

**Comment by i0rek** [comment]
Thank you for reporting @mikehardenize! I can see how thats confusing, despite it being only a warning. What do you think is the right way to deal with it?

**Comment by mikehardenize** [comment]
How about: If there is an encryption key in the keyring, and it matches what is in the config file, then don't warn about it?

Alternatively, a new config option `encrypt_gossip = true`, which will cause consul to fail unless an encryption key is supplied either as a command line argument, or from the config file, or from the keyring. So when I first start up, I can set `encrypt = "thekey"`, and on the second run I can just set `encrypt_gossip = true` and remove `encrypt` from the config file, as it's in the keyring.

I suppose a third alternative would be to just not store the encryption key in the keyring if it's in the config.

I'm happy with any of these solutions

**Comment by i0rek** [comment]
Thank you for your suggestions! I like the first one:

> If there is an encryption key in the keyring, and it matches what is in the config file, then don't warn about it?

Would you like to submit a PR for that?

**Comment by mikehardenize** [comment]
I'm not familiar enough with golang to write a patch for this.
