### ISSUE TITLE
Consul UI cannot work ( consul v1.6.3 with ARMEL )

### ISSUE THREAD

**Issue by meanshe** [hashicorp/consul#7258]
When I use 'consul v1.6.3 armel' 

[root]# **./consul -server -ui -bind=172.16.42.50 -client 0.0.0.0 -data-dir=./**

UI can not work as I got a error message:

![image](https://user-images.githubusercontent.com/652203/74225895-87aab980-4cf6-11ea-87d7-9b9a1b8798a7.png)

**Comment by johncowen** [comment]
Hi @meanshe ,

Would it be possible to take a look in the Network Panel of the Web Inspector in your browser to see what errors are appearing there? It looks to me that there is a problem with the Consul API rather than the UI itself, possibly due to some sort of configuration problem. If you could let me know what errors you are getting in Web Inspector we can try to get to the bottom of it.

Thanks,

**Comment by meanshe** [comment]
Hi @johncowen ,

The browser is  'Chrome 59.0.3071.115'.

**Network Panel** 
![image](https://user-images.githubusercontent.com/652203/74234271-6a321b80-4d07-11ea-8d27-a3bacb2e93bd.png)

**Console Panel**
![image](https://user-images.githubusercontent.com/652203/74234368-a06f9b00-4d07-11ea-9531-f35f15dbf3a7.png)

**Consul Log** 
![image](https://user-images.githubusercontent.com/652203/74234163-335c0580-4d07-11ea-88c8-917864831f67.png)

**Comment by meanshe** [comment]
Hi @johncowen ,

The browser is  'Chrome 59.0.3071.115'.

**Network Panel** 
![image](https://user-images.githubusercontent.com/652203/74234608-3277a380-4d08-11ea-9d90-42c231879faf.png)

**Console Panel**
![image](https://user-images.githubusercontent.com/652203/74234583-20960080-4d08-11ea-8008-db16c719b872.png)

**Consul Log** 
![image](https://user-images.githubusercontent.com/652203/74234630-415e5600-4d08-11ea-988c-36a04b572cb3.png)

**Comment by johncowen** [comment]
hi @meanshe 

Thanks for the quick response. I'm guessing the fact that you are Chrome 59 information is actually the root of the error. Are you able to update/upgrade your browser?

Thanks,

**Comment by meanshe** [comment]
hi @johncowen 
The newest version(80.0.3987.87) of chrome work well !
Thanks,

**Comment by johncowen** [comment]
Thanks for the conformation @meanshe!
