### ISSUE TITLE
Better error message when datacenter is not configured correctly

### ISSUE THREAD

**Issue by eranchetz** [hashicorp/consul#727]
If you try to connect to a cluster with the wrong consul datacenter name you get the following error message:
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Joining cluster...
==> Merge canceled

I suggest adding the line below to clarify:
==> Merge canceled (Check datacenter name configuration)

**Comment by armon** [comment]
Thanks! Definitely not the best message currently.

**Comment by outrunthewolf** [comment]
Just to clarify. If my Consul server cluster is set to "-dc eu-west-1" and a server from "-dc us-west-1" tries to connect to it, it will be rejected?

How do I have servers from all over the world connect to a consul cluster in a single region then? Not specify the dc in the server config?

**Comment by ryanbreen** [comment]
If by connect you mean join, you shouldn't do that across the world. A consul cluster should map to a DC, and joining from elsewhere will lead to that remote need frequently appearing unavailable due to latency.

**Comment by outrunthewolf** [comment]
So... each DC should really have an individual server cluster? Is that purely because of latency?

I feel like a centralised approach would be easier to manage?

**Comment by ryanbreen** [comment]
Each DC should have its own cluster for resiliency. A central cluster is implicitly a single point of failure, so I find Consul's approach much better than impairing the functionality of remote DCs if they lose connectivity to the central cluster.

**Comment by ryanbreen** [comment]
For more detail, see this doc: http://www.consul.io/docs/guides/datacenters.html

**Comment by outrunthewolf** [comment]
Thanks. I appreciate you taking the tie to answer these questions.
