### ISSUE TITLE
Service deregistered unexpectedly

### ISSUE THREAD

**Issue by senkadir** [hashicorp/consul#7271]
Hi,

We have few services on consul. The services automatically registers themselves to consul. 
While everything fine something happining and one or more services deregistered from consul services. When we check logs some one call Consul api to deregister service.
The log line here:

`2020/02/12 14:41:26 [DEBUG] http: Request PUT /v1/agent/service/deregister/identity (3.9751ms) from=172.22.5.32:51528`

Who is making this call and why ? 

Consul runs on: 172.22.5.32

**Comment by i0rek** [comment]
Hello @senkadir,

thanks for reporting. This is an issue we cannot help you with. It seems like something on your side is deregistering the service. You should check your automation around consul to figure out what is deregistering it and why. Good luck!

**Comment by kkarim1983** [comment]
I am currently utilizing Consul version 1.10.3 in conjunction with various microservices built on .NET Core. Occasionally, I encounter an issue where a service deregisters abruptly and then re-registers itself. During these instances of service deregistration, I execute connectivity and probe health check commands between the microservices and Consul, and they appear to be functioning correctly. Is there a configuration setting within the config.json file that dictates the duration of service deregistration?

**Comment by kkarim1983** [comment]
@hanshasselberg needs your advise and support in this regards.
