### ISSUE TITLE
gRPC Healthcheck unable to parse scheme

### ISSUE THREAD

**Issue by poolski** [hashicorp/consul#7274]
#### Overview of the Issue

Since the introduction of support for healthchecking gRPC services natively without needing to use a third-party tool like [grpc_health_probe](https://github.com/grpc-ecosystem/grpc-health-probe), we've been looking to use Consul's own healthchecks. 

Given a configuration like this: 
```
{
  "service": {
    "id": "thanos-sidecar",
    "name": "thanos-sidecar",
    "port": 19090,
    "tags": [
      "server"
    ],
    "checks": [
      {
        "id": "thanos-sidecar-grpc",
        "name": "Thanos sidecar gRPC healthcheck",
        "grpc": "127.0.0.1:19090",
        "tls_skip_verify": true,
        "interval": "10s"
      }
    ]
  }
}
```
we've found a constant stream of 
```
2020/02/12 13:48:12 [INFO] ClientConn switching balancer to "pick_first"
2020/02/12 13:48:22 [INFO] parsed scheme: ""
2020/02/12 13:48:22 [INFO] scheme "" not registered, fallback to default scheme
2020/02/12 13:48:22 [INFO] ccResolverWrapper: sending update to cc: {[{127.0.0.1:19090 0  <nil>}] <nil>}
```
in the output of `consul monitor`

Digging a bit deeper, this issue seems to come from the `grpc-go` library's `clientConn.resolverBuilder` function: 
```
resolverBuilder := cc.getResolver(cc.parsedTarget.Scheme)
if resolverBuilder == nil {
  // If resolver builder is still nil, the parsed target's scheme is
  // not registered. Fallback to default resolver and set Endpoint to
  // the original target.
  grpclog.Infof("scheme %q not registered, fallback to default scheme", cc.parsedTarget.Scheme)
  cc.parsedTarget = resolver.Target{
    Scheme:   resolver.GetDefaultScheme(),
    Endpoint: target,
  }
  resolverBuilder = cc.getResolver(cc.parsedTarget.Scheme)
  if resolverBuilder == nil {
    return nil, fmt.Errorf("could not get resolver for default scheme: %q", cc.parsedTarget.Scheme)
  }
}
```
https://github.com/grpc/grpc-go/blob/eb53a9e8ba93d766afe9b14fcc6cb6dd8b19371b/clientconn.go#L251

Because the service address is defined as an IP address or hostname, there is no support for the protocol/scheme being used, which this function tries to work out.

When trying to set an address including the scheme, like `"grpc": "grpc://127.0.0.1:19090"`, Consul throws an error because it tries to resolve `grpc` rather than treating it as the scheme: 
```
2020/02/12 14:01:23 [WARN] grpc: addrConn.createTransport failed to connect to {grpc: 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup grpc on 127.0.0.1:53: no such host". Reconnecting...
```

The issue affects Consul 1.5.2 at the least - I've tried to upgrade to the latest version, but the issue is still there. 

In addition, although the docs say that you can use `"grpc_use_tls": true,` to skip TLS verification, in testing we've found that `"tls_skip_verify": true` also works...

I realise that the messages are all `INFO` messages, but there doesn't seem to be any way to silence them in Consul, so the output of `consul monitor` gets polluted with all of this info messaging which makes other messages get lost in the noise.

**Comment by guidao** [comment]
Try  "grpc":  "passthrough:///127.0.0.1:1909"

https://github.com/grpc/grpc-go/blob/eb53a9e8ba93d766afe9b14fcc6cb6dd8b19371b/internal/resolver/passthrough/passthrough.go#L25

**Comment by poolski** [comment]
I'll give that a try and report back, thanks, @guidao
