### ISSUE TITLE
Link to configuration option anchors refs

### ISSUE THREAD

**Issue by ryanbreen** [hashicorp/consul#730]
There are numerous places in the documentation where we refer to configuration options by name but only link to the configuration option page.  We should update these links to take the reader directly to the relevant option based on its anchor.  That feels like a much better user experience as the options doc is pretty huge.

This is enabled by the recent fixes to middleman-hashicorp to make support for anchors in list items more robust.

**Comment by sethvargo** [comment]
Along these lines, I think it might makes sense to split the API doc pages (especially the HTTP docs) into smaller pages. It makes searching and linking easier than a really long, single page doc.

**Comment by ryanbreen** [comment]
Seth, totally agreed about the need for more granularity, but @ryanuber already cracked the HTTP API monolith prior to 0.5: https://consul.io/docs/agent/http.html.  Does that cover the specific example you cited?

**Comment by ryanbreen** [comment]
According to `grep`, there are no longer any references to options.html that lack anchor refs (well, there are two, but both of those are intentional).

**Comment by armon** [comment]
Awesome! I'm redeploying the Consul site now with all the updates. Thanks!
