### ISSUE TITLE
Not able to register a service with a header based health check

### ISSUE THREAD

**Issue by ashharishpatel** [hashicorp/consul#7301]
Consul Version is 1.0.7
While we are trying to register a service according to the provided documentation, 
https://www.consul.io/api/agent/service.html#register-service and
https://www.consul.io/api/agent/check.html
we are facing issues while trying to register a service with a header as part of the health check.

We get the below error when we try to register the service:-
*** 'check.header[Content-Type]': source data must be an array or slice, got string**
Tried both the methods of registering -- HTTP API and the service definition.

Has anyone faced similiar issues?

**Comment by ashharishpatel** [comment]
Sample Service Definition similiar to what we are trying to register:
============================
{
  "service": {
    "id": "sample-app-id",
    "name": "sample-app",
    "address": "192.168.0.51",
    "port": 11580,
    "check": {
		"Header": {
			"x-tenant-Id": "12345"
		},
		"Interval": "30s",
		"HTTP": "http://192.168.0.51:11580/api/v1/health.do"
	},
    "token": "002d2440-5eb5-7b57-a667-ef1388440b4d"
  }
}

**Comment by remilapeyre** [comment]
Hi @ashharishpatel, the value of the `Header` field must be an array since each header can have multiple values (https://www.consul.io/api/agent/check.html#header):
```sh
$ curl \
    --request PUT \
    --data '{
    "id": "sample-app-id",
    "name": "sample-app",
    "address": "192.168.0.51",
    "port": 11580,
    "check": {
        "Header": {
            "x-tenant-Id": ["12345"]
        },
        "Interval": "30s",
        "HTTP": "http://192.168.0.51:11580/api/v1/health.do"
    },
    "token": "002d2440-5eb5-7b57-a667-ef1388440b4d"
}' http://127.0.0.1:8500/v1/agent/service/register
```
