### ISSUE TITLE
wan federation via mesh gateways re-bootstrapping

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#7339]
There's a recovery-type situation for wanfed via gateways that we probably need to have a story around:

1. user initializes with the `-primary-gateway` args
2. system uses fallback addresses from (1) to do the initial wan join
3. after wan join completes and the rest of the secondary bootstrapping happens we can replicate federation states
4. now we can exclusively use the primary's federation state list of gateways instead of the fallback.

But...what if there was some non-graceful rotation of the primary gateways that didn't give the secondaries time to replicate at least one of the new mesh-gateway addresses? Then the secondary replicated federation state information is useless AND since having _any_ primary federation state trumps the flag/config fallback data it will try to use gateways that don't exist "forever".

Probably need some sort of active process in the GatewayLocator that does some simple light RPC (status check?) to the wildcard primary server address through each mesh-gateway listed in the state store for the primary periodically. Need to heuristically determine if the state machine gateways are still usable, and if not goes back to using the fallback ones until the state machines ones work again (presumably after we can hook up federation state replication streams to the primary again).

**Comment by oleksiyp** [comment]
A great feature to have. Is there any ETA for associated PR to be merged and released?
