### ISSUE TITLE
Leader Last Contact Fluctuations impacting Cluster Health

### ISSUE THREAD

**Issue by nosammai** [hashicorp/consul#7348]
#### Overview of the Issue

After a couple days of running in production, our Consul clusters started having issues with Autopilot health reporting unhealthy due to `consul.raft.leader.lastContact` being above the threshold (raft multiplier is 1). Looking at our graphs of this data, the average value for this metric is still low around ~30ms, but the max starts to fluctuate wildly, getting worse over time, and eventually starting to cause periodic leader elections. CPU usage on the servers is around 5% on average. After the issue starts, network traffic seems to increase by a decent amount (screenshot below). Number of RPC requests to the servers doesn't seem to increase. This happened on 3/4 of the consul clusters in our Federation simultaneously. Performing a full rolling restart of the server nodes in a cluster seems to bring the max for that cluster down to normal levels until it gets triggered again.

I removed the cluster I assumed was problematic (highest wan network latency) from the federation, and after a few days I observed the same bad behavior in that cluster while the others remained stable. I am guessing that this might be caused by some network event that disrupts connectivity for a short period of time, causing some lasting effects to the original cluster and others in the federation until the clusters are restarted.

I would like some help figuring out:

- Why does Consul get stuck in a state where the last contact time fluctuates until a rolling restart is performed?
- Why does this bad state seem to propagate over Federation links, requiring restarts of those clusters as well?

Sorry if this isn't very much information, I'm happy to provide any additional debug info/details.

#### Reproduction Steps

1. Run Consul in our production network
2. Wait a day or two for max leader last contact stat to fluctuate wildly

(sorry these are not very helpful.. )

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = 1200f25e
        version = 1.6.2
consul:
        acl = disabled
        known_servers = 5
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 88
        max_procs = 2
        os = linux
        version = go1.12.13
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 71
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1486
        members = 1023
        query_queue = 0
        query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

Problematic cluster that was removed from federation:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 1200f25e
        version = 1.6.2
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.61.167.62:8300
        server = true
raft:
        applied_index = 2756784
        commit_index = 2756784
        fsm_pending = 0
        last_contact = 11.127528ms
        last_log_index = 2756784
        last_log_term = 262
        last_snapshot_index = 2747711
        last_snapshot_term = 262
        latest_configuration = [{Suffrage:Voter ID:21612dd4-89a5-3ca4-633b-bf5e99e44804 Address:10.61.166.46:8300} {Suffrage:Voter ID:b8fc95e9-3483-d828-3a30-4803a57355a6 Address:10.61.167.62:8300} {Suffrage:Voter ID:d10d8340-b3c6-2fac-1f21-d37818ac7182 Address:10.61.167.38:8300} {Suffrage:Voter ID:2dffdedd-3665-94e1-6efa-c812bd1bb0f6 Address:10.61.229.138:8300} {Suffrage:Voter ID:ce3e4fbb-1cf8-7f98-fe74-16d1072680b8 Address:10.61.229.45:8300}]
        latest_configuration_index = 2389112
        num_peers = 4
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 262
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 7404
        max_procs = 8
        os = linux
        version = go1.12.13
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 71
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1486
        members = 1023
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 233
        members = 5
        query_queue = 0
        query_time = 1
```
One of the other clusters still in federation:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = 1200f25e
        version = 1.6.2
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 3
        leader = true
        leader_addr = 10.74.172.113:8300
        server = true
raft:
        applied_index = 4288611
        commit_index = 4288611
        fsm_pending = 0
        last_contact = 0
        last_log_index = 4288611
        last_log_term = 149
        last_snapshot_index = 4284213
        last_snapshot_term = 149
        latest_configuration = [{Suffrage:Voter ID:2f88bac1-90e1-b583-8b27-3ebd040355f7 Address:10.74.172.113:8300} {Suffrage:Voter ID:04abd3f3-5074-ef11-d700-1fb91ed867f1 Address:10.74.175.153:8300} {Suffrage:Voter ID:d518d329-0e32-e5c9-5a13-4b490a22ce2a Address:10.74.236.86:8300} {Suffrage:Voter ID:ef6e919e-50a1-e268-8db4-f78db8f6a838 Address:10.74.237.40:8300} {Suffrage:Voter ID:a9bb0c66-a240-6250-8161-d3063568244a Address:10.74.175.131:8300}]
        latest_configuration_index = 3864668
        num_peers = 4
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 149
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 7898
        max_procs = 8
        os = linux
        version = go1.12.13
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 21
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5111
        members = 1136
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 317
        members = 15
        query_queue = 0
        query_time = 1
```
</details>

### Operating system and Environment details

Servers are CentOS 7 VMs with 8 CPUs, 24G RAM. Servers and Clients are running docker-ce-19.03.2-3, and the consul docker container version 1.6.2 in host networking mode. 700 - 1200 clients and 5 servers in each production cluster.

### Log Fragments

The only server logs I see on the misbehaving cluster other than the normal snapshot logs are these. The graph (attached below) starts showing the fluctuating max at 21:30
```
2020/02/24 14:42:39 [WARN] yamux: failed to send ping reply: session shutdown
2020/02/24 18:48:07 [WARN] yamux: failed to send ping reply: session shutdown
2020/02/24 21:47:39 [ERR] yamux: Failed to write header: tls: use of closed connection
2020/02/24 21:50:43 [ERR] yamux: Failed to write header: tls: use of closed connection
2020/02/24 22:22:31 [WARN] yamux: failed to send ping reply: session shutdown
2020/02/24 22:22:31 [ERR] yamux: Failed to write header: tls: use of closed connection
2020/02/24 22:52:25 [WARN] yamux: failed to send ping reply: session shutdown
```

![image](https://user-images.githubusercontent.com/2600910/75305553-50aacc80-57fb-11ea-90fc-001653ca819e.png)

![image](https://user-images.githubusercontent.com/2600910/75305995-9025e880-57fc-11ea-83c0-8d59826796be.png)

**Comment by pierresouchay** [comment]
@nosammai based on my experience, using `raft multiplier = 1` causes some issues with Wan or as soon your cluster becomes large, on our side, our tests went better with 3.

Concerning federation over WAN, if you are using ACLs, I would strongly advice to use `async-cache` for `acl_down_policy` which improves quite a lot the performance over wan when connectivty is still here but degraded.

I am currently working an article about our settings (WAN of 9 DCs in prod, with around 40 agents), you might find some interresting items: https://medium.com/criteo-labs/configure-consul-for-performance-at-scale-f6a089706377

**Comment by nosammai** [comment]
Thanks for the info @pierresouchay! We have ACLs disabled in our clusters currently. From the docs my understanding of the raft_multiplier value was that it just increases the thresholds before leader elections will occur, but doesn't actually change the behavior of the cluster? I'm just curious why consul seems to get stuck in this state until the servers are restarted, and that it's still happening to one of our clusters even after it's totally removed from the WAN.

**Comment by nosammai** [comment]
After doing more digging I am fairly certain this is related to https://github.com/hashicorp/consul/issues/4984 since we have hundreds of services with multiple watches on service health for services with >1k members.

I am going to try upgrading to 1.7.x with the limit increase from https://github.com/hashicorp/consul/pull/7200 and see if that helps smooth things out.

**Comment by pierresouchay** [comment]
@nosammai yes,very likely. You might have a look to our articles seems you seem to have the very same kind of setup as ours:
https://medium.com/criteo-labs/anatomy-of-a-bug-when-consul-has-too-much-to-deliver-for-the-big-day-4904d19a46a4
and
https://medium.com/criteo-labs/configure-consul-for-performance-at-scale-f6a089706377

We are still using our shared blocking queries patch in our version (and 8192+ limit and a patch with Grpc), but the 8192 limit should already quite improve your situation

**Comment by nosammai** [comment]
I wasn't able to upgrade to 1.7.x yet since we have some services out there that are incompatible, but I made some other changes to reduce the number of watches significantly and this doesn't seem to be an issue anymore. I think it's safe to say this is a dupe of #4984

**Comment by pierresouchay** [comment]
@nosammai Out of curiosity, what is the incompatible change you met with 1.7.x?

**Comment by nosammai** [comment]
Some of our services are sending 'id' instead of 'checkid' in their health check/service registration, and it looks like 1.7 started rejecting invalid field names. We patched this easily but haven't been able to roll out the latest version everywhere yet.

**Comment by pierresouchay** [comment]
Huh... Interesting, thank you!
