### ISSUE TITLE
Typo on `Getting Started` `Connect Services` page

### ISSUE THREAD

**Issue by cainejette** [hashicorp/consul#7367]
Under the [`Control Communication With Intentions`](https://learn.hashicorp.com/consul/getting-started/connect#control-communication-with-intentions) anchor, there's a word misspelled: `therefor`.

I tried finding this in the source, but they don't seem to line up: https://github.com/hashicorp/consul/blob/master/website/source/intro/getting-started/connect.html.md#controlling-access-with-intentions ??

**Comment by preetapan** [comment]
@cainejette Thanks for letting us know. The learn guides currently live in an internal repo, I've let the relevant folks know. Will close this issue but post an update once the typo's fixed.
