### ISSUE TITLE
how do you change consul ui port from 8500 to something like 8080

### ISSUE THREAD

**Issue by amitmawkin** [hashicorp/consul#739]

**Comment by ryanuber** [comment]
Hi @amitmawkin,

The port the UI runs on is currently always the same as the HTTP API.  You can change this by specifying the `ports` key in consul's configuration, like so:
```
{
    "ports": {
        "http": 8080
    }
}
```

You can read more about the configurable ports in the [agent configuration documentation](https://consul.io/docs/agent/options.html).

If you need to run the UI on a different port than the HTTP API, you will need to serve the UI files from a different web server, such as Apache or nginx.

**Comment by cfrelet** [comment]
another simple way is to specify the port in the start command line:
`consul agent -dev -http-port=8080`

All options here: https://www.consul.io/docs/agent/options.html
