### ISSUE TITLE
Support for linux on ARM

### ISSUE THREAD

**Issue by wolfeidau** [hashicorp/consul#74]
Just interested to hear if anyone has tried this on an ARM device?

Was there any reasons why it wasn't cross compiled for ARM?

Thanks

**Comment by jaromil** [comment]
Hi there. Regarding cross-compiling using qemu-static, please note there are bugs with it and pthreads running on multi-core machines. We have fixed those developing pinthread in Devuan https://git.devuan.org/packages-base/pinthread/blob/master/README.md

I'm just wondering if this may be useful also to streamline ARM builds of consul anywhere around here

**Comment by wolfeidau** [comment]
You can do the builds of this on a cloud service now like https://www.scaleway.com/.

Fast cheap ARM based VPS on demand.

That is what I am using for builds using the distributions built by @davecheney.

**Comment by davecheney** [comment]
With Go 1.5, cross compilation requires no preparation of the local tool
chain, you can build for every architecture from any 1.5 install.

Hope this helps

Dave

**Comment by alexellis** [comment]
Is there any chance of an updated version for ARM? Or working build instructions? I'm trying to build in docker with armhf/ubuntu, build-essential and Dave Chenny's Go 1.5.x.

**Comment by highlyunavailable** [comment]
@alexellis The whole underlying storage mechanism changed in Consul 0.6.0 (there's no more cgo, it's all memdb and written in Go now AFAIK) - you might want to open a new issue with the exact errors you are getting for further assistance.

**Comment by StefanScherer** [comment]
@alexellis Have you seen the download page https://www.consul.io/downloads.html with consul 0.6.3 for ARM as well.
For the old version 0.5.2 the Hypriot team once did a drone build on a Scaleway machine https://github.com/hypriot/rpi-consul/blob/drone-0.4.0/.drone.yml, but this seems outdated for 0.6.x

**Comment by alexellis** [comment]
@highlyunavailable  @StefanScherer Hi again Stefan, after finding this thread and spending ages trying to build on ARM docker.. the binary works equally well and is much simpler to use. We really need some official ARM images for things like Consul.

I'm trying to set up a multi-host docker 1.9.1 ARM cluster with swarm, so the documentation calls for Consul. Anyway this is what I've put together:

```
FROM armhf/ubuntu
RUN apt-get update && apt-get -qy install \
 wget unzip
WORKDIR /root/
RUN wget \
 https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_arm.zip
RUN mkdir /data
RUN mkdir /ui
RUN unzip consul*.zip -d /usr/local/bin/

RUN consul version

EXPOSE 8300 8301 8301/udp 8302 8302/udp 8400 8500 53/udp

VOLUME ["/data"]
ADD ./config /config/

ENV DNS_RESOLVES consul
ENV DNS_PORT 8600

ENTRYPOINT ["/usr/local/bin/consul", "agent", "-config-dir=/config"]
```

agent.config

```
{
	"client_addr": "0.0.0.0",
	"bootstrap": true,
	"server": true,
	"data_dir": "/data",
	"leave_on_terminate": true,
	"dns_config": {
		"allow_stale": true,
		"max_stale": "1s"
	}
}
```

**Comment by slackpad** [comment]
Sorry for any confusion. Just in case someone comes across this later, building Consul for ARM 0.6.0 and later should be a matter of following the build instructions in the readme. We cross-compile using `gox` so you can build this binary on a non-ARM host.
