### ISSUE TITLE
Provide a way to configure Zone aware routing using Envoy Proxy

### ISSUE THREAD

**Issue by vilva42** [hashicorp/consul#7401]
#### Feature Description

Envoy allows you to configure [zone aware routing](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/zone_aware_routing) for which you need to set `cluster_type` as EDS and [locality information](https://www.envoyproxy.io/docs/envoy/v1.11.0/api-v2/api/v2/core/base.proto#core-locality). It would be nice if there's a way to configure it through bootstrap options or provide guidance on how to accomplish this through Connect's L7 configs. 

#### Use Case(s)

We would like to limit cross-AZ traffic.

**Comment by vilva42** [comment]
**Update:**

Had a discussion with @blake and found that this can be accomplished by creating service subsets. For example, you can place all your service instances under a default subset, lets say `us-east-1` and a AZ subset `us-east-1b`. You can then use the AZ info from instance metadata with [service-router's](https://www.consul.io/docs/agent/config-entries/service-router.html) http header or query parameter to route to the same AZ subset. If no instances are found in the same AZ, requests are routed to default subset. This way you don't run into the [M:N Zone aware routing issue](https://github.com/envoyproxy/envoy/issues/6333) that envoy currently has. The downside of this approach is that it doesn't support subzone routing and requires minor code/config changes. 

I plan to test it this week and update my comment.

**Comment by jsosulska** [comment]
https://github.com/hashicorp/consul/issues/6417 is linked to this.

**Comment by dschaaff** [comment]
I'm interested in using service subsets to accomplish this today. @vilva42 were you able to get this working?

**Comment by vilva42** [comment]
@dschaaff I haven't. We decided to move on from service mesh as we were on ECS and the integration was complex.

**Comment by Shaiou** [comment]
Hello, any issues about this issue ?

**Comment by aryaKetan** [comment]
Any update on this. Not sure if this issue is resolved but the issue remains open.

**Comment by david-yu** [comment]
This feature is available in Consul Enterprise 1.17 and HCP Consul, as described in https://developer.hashicorp.com/consul/docs/v1.17.x/connect/manage-traffic/route-to-local-upstreams. As this is the official, supported solution from HashiCorp, we consider this issue to be resolved. Thanks so much for your interest and feedback!

**Comment by arj22** [comment]
> This feature is available in Consul Enterprise 1.17 and HCP Consul, as described in https://developer.hashicorp.com/consul/docs/v1.17.x/connect/manage-traffic/route-to-local-upstreams. As this is the official, supported solution from HashiCorp, we consider this issue to be resolved. Thanks so much for your interest and feedback!

So it is not available in the open source version for now?
