### ISSUE TITLE
Allow selecting Serf profile at startup

### ISSUE THREAD

**Issue by jefferai** [hashicorp/consul#741]
Consul is designed to run in a datacenter environment, but this means that Serf timings can be unsuitable for use in development environments, where the agents connecting to the Consul servers may be running on virtual machines, behind MASQ in Docker, or other latency-inducing platforms.

In testing, building custom Consul that uses WAN Serf timings fixes this issue, but it doesn't seem to me like this is an unreasonable use-case, and it would be nice to see it supported upstream if you guys agree via some kind of toggle-able flag.

**Comment by armon** [comment]
Hmm this seems interesting. I guess it's a very advanced feature, but something we could support.

**Comment by ryanuber** [comment]
Sounds reasonable to me as well. The config options might look a little different, since we actually have two different gossip pools to control the timing values for. I’m not sure what exactly the config would look like, since assigning values like "local", "lan", or "wan" would be pretty odd-looking. Any thoughts?

**Comment by armon** [comment]
This is also somewhat related: https://github.com/hashicorp/consul/issues/242. I think ultimately I'd like to support an "advanced" configuration block that allows low-level parameters to be tuned. It should be very clear to users that they must know what they are doing and that there will be unintended consequences if they mess it up.

**Comment by jefferai** [comment]
Unless you want something super fine-grained for all timings, I would imagine that using Serf terminology is the right way to go. Even if it looks odd. Documentation could point to relevant Serf documentation as to the meanings  :-)

So it could be something like:

"gossip_timing_overrides": {
  "lan": "wan"
}

Potentially instead of "lan" it could be "consul_lan": "serf_wan" or some such thing to eliminate confusion. Also "consul_wan".

**Comment by jefferai** [comment]
Ack. Crossed comments. Individually adjusting timings would of course also work, although it's nice to be able to select from known profiles.

**Comment by armon** [comment]
My fear is that only supporting profiles is not flexible enough (something we learned from Serf), so it may be easier to just expose all the controls and then document various profiles on the site.

**Comment by jefferai** [comment]
That makes sense. :+1:

**Comment by 42wim** [comment]
Also would like to have this feature.

Giving access to ProbeTimeout in DefaultLANConfig() would probably solve a lot of the issues here with flapping nodes (EventMemberFailed/EventMemberJoin). The default of 500ms is just not high enough for (some) virtualized (vmware only maybe?) servers.

I increased this to two seconds on our build (got even issues on 1 sec) and it's now running smoothly.
(maybe something to add to the FAQ?)

**Comment by slackpad** [comment]
We've done a ton of work on the https://www.consul.io/docs/internals/gossip.html, especially via Lifeguard, and I don't think there's a need for manual tuning anymore.
