### ISSUE TITLE
Output log error if provided log dir is not present or is not writable

### ISSUE THREAD

**Issue by djmgit** [hashicorp/consul#7468]
#### Feature Description
Presently if the log directory provided by user is not present or is not writable due to permission issues, consul does not throw any error. Consul should throw error in such cases for easy debugging.

#### Use Case(s)

This will help in fast debugging.

**Comment by jsosulska** [comment]
Added feature request + bug, to track ease of debugging.

**Comment by dnephin** [comment]
Related to #7447 I believe
