### ISSUE TITLE
Document the `acl_master_token` install

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#747]
See this thread: https://groups.google.com/forum/#!topic/consul-tool/paXNKstLrGw

We should document when the `acl_master_token` is installed as there is insufficient documentation around that.

**Comment by ryanbreen** [comment]
I can take a cut at this.

**Comment by armon** [comment]
@ryanbreen Thanks!

**Comment by ryanbreen** [comment]
Armon, let me know if the merged PR doesn't look adequate. We can re-open if so.

**Comment by armon** [comment]
@ryanbreen Thanks!
