### ISSUE TITLE
Allow modifying outgoing HTTP requests

### ISSUE THREAD

**Issue by raghur** [hashicorp/consul#7475]
#### Feature Description
Envoy has Lua integration for http request/response inspection & manipulation - however, these don't seem to be surfaced via Consul. 
Allowing the outgoing request to be modified (data/headers) via consul would be a great feature to have.

#### Use Case(s)
1. Service X has consumers A, B.... E
1. Service X is now split into X and Y.
2. L7 routing rules can direct traffic to Y based on request path.
3. However, services A & B are ready but C, D & E aren't yet ready to deal with teh slightly different response that Y now provides.
4. Trying to coordinate with owners of svc A -- E is a non starter.
5. Even for A & B, having to ask them to include a special header to help with routing seems dirty.

With the ability to inspect and modify outgoing requests
1. Trivially attach additional header at the proxy based on destination service.
2. Current routing rules are sufficient to have a setup where A & B are served by Y but B, C and D are served by X till they're ready to cut over.

**Comment by joec4i** [comment]
Hi @blake Is there any plan to add support for custom envoy filters? It'll open up a lot of opportunities for users to custom consul connect / envoy for various use cases.
