### ISSUE TITLE
Special support for docker - Unit files ala fleet style using docker as init system

### ISSUE THREAD

**Issue by criloz** [hashicorp/consul#748]
I would like to know about what do you thing about this idea?

add a special support for docker (due to its great popularity), and use it as init system (it can work great with any microOS like rancherOS(https://github.com/rancherio/os))

This is a unit file for fleet  (https://coreos.com/docs/launching-containers/launching/fleet-unit-files/)

Consul could  use unit files like this

```
[Unit]
Description=Some Monitoring Service

[Service]
DockerImage=hashicorp/monitoring

[X-Fleet]
datacenter=chicago
node=node1
Conflicts=monitor*
```
 And use files like this for start automatically services and register them 

I think that could be possible use this feature in Consul, instead of using systemd as init system (like fleet) we can use docker,  and the already existing `consul watch` and `consul event`

**Comment by ericson-cepeda** [comment]
+1 for unit files.

**Comment by armon** [comment]
At this time, we do not plan on Consul supporting being a supervisor of that nature, and would like to limit its scope of responsibilities. For that reason, I'm closing this ticket.
