### ISSUE TITLE
Lease And Benchmarks Support

### ISSUE THREAD

**Issue by vinglogn** [hashicorp/consul#7487]
#### Feature Description
1、Consul is support Key/Value Storage，but kv storage performance is very low, and there not exist any  benchmarks or test tools.
2、KV pair can not bind a lease just like Etcd, I think the lease feature is very import for me.

Do you have a plan to support the above two features?

**Comment by dnephin** [comment]
Thank you for your interest in Consul!

I am not all that familiar with etcd, but from looking at the docs I believe etcd leases may be similar to Consul sessions. The reference docs for sessions are here: https://www.consul.io/api/session.html.

**Comment by vinglogn** [comment]
tks！
