### ISSUE TITLE
Support Swagger for HTTP APIs

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#7493]
It would be very cool to support Swagger for Consul APIs.

While the API documentation is pretty cool, supporting Swagger would quite improve predictability and would allow to create automatic stubs for several languages.

Would you consider this ?

**Comment by pierresouchay** [comment]
Hello @jsosulska,

I implemented support for it (just 1 method documented for now) with the Pull-Request https://github.com/hashicorp/consul/pull/7522. With this PR, it would also be trivial to add nice UI in Consul UI to perform all Consul operations with open documentation.

On the long term, it might even supersede / complement / be the source of https://www.consul.io/api/index.html

I'll wait until having feedback on it, but I really think it would improve the usage of Consul APIs.

**Comment by pierresouchay** [comment]
Examples of rendering of APIs with Redoc and Swagger UI (which allows to run the endpoints with fancy UI, support for auth, and might be included and tuned in Consul-UI later):

# Rendering with Redoc (of course, it did not take time to customize it)
<img width="1449" alt="Result endered by Redooc" src="https://user-images.githubusercontent.com/8089033/77740542-bf09c700-7013-11ea-8824-cef244b2246f.png">

# Rendering with Swagger UI (you can call the endpoints with UI - with support for auth if needed if ACLs are enabled)
<img width="1496" alt="Result renderd by Swagger UI" src="https://user-images.githubusercontent.com/8089033/77740588-ce891000-7013-11ea-9f3e-0ef56e428c44.png">

**Comment by jsosulska** [comment]
@pierresouchay - Thanks for running this down! I will take it back to the larger team and we'll look at this more and respond soon.

**Comment by pierresouchay** [comment]
@jsosulska Could anyone have a look at https://github.com/hashicorp/consul/pull/7522 and tell me whether it could be considered?

**Comment by jsosulska** [comment]
Hi @pierresouchay ,

After speaking to the team, the consensus is that Swaggar will not be included in Consul at this time. One of the major concerns are that the level of effort to align the codebase with Swagger is incredibly non-trivial, and there are are other priorities the team would like to focus on. 

In the future, if we make any substantial changes to the API, we should consider improving support for generating documentation from the code, which would make supporting Swagger, or a similar technology, a possibility.

The Consul team's intention is that they have designed API endpoints that are relatively easy to use from a generic http client. If there are endpoints which are not easy to use, the team feels comfortable addressing issues as they come. If you do find usability issues, please open a new issue, as it would be very much appreciated.

Thanks for requesting this, I'll go ahead and close.

**Comment by shweshi** [comment]
@jsosulska Hey.. any new updates on this, can this be taken up. Also are you guys open for contributions? If you guys start community can help on this.
