### ISSUE TITLE
[Feature proposal] Reverse proxy

### ISSUE THREAD

**Issue by hden** [hashicorp/consul#75]
### Why?

DNS is susceptible to caching and disabling DNSSEC is slightly out of the comfort zone of ordinary deployment engineers. An interesting approach by [airbnb/synapse](https://github.com/airbnb/synapse) is to use a reverse proxy.

![design diagram](https://cloud.githubusercontent.com/assets/1910549/2786275/4f7576a2-cb71-11e3-8468-d724df1720fc.png)
### Benefits?
- Common load-balancing strategy e.g. round-robin
- Automatic redispatch when error

**Comment by tj** [comment]
We're shopping for nicer solutions to this as well. @mitchellh I just watched your recent dockercon presentation and you mentioned it's on the roadmap for Consul, do you think that's a near-future feature? Cutting out that extra layer for our small team would be awesome!

**Comment by armon** [comment]
@tj Take a look at (consul-template)[https://github.com/hashicorp/consul-template]. It is now our defacto standard way to do this. You can use it to configure HAProxy / Varnish / nginx / Apache as a reverse proxy as you need.
