### ISSUE TITLE
Consul clients do not automatically rejoin to the cluster after consul server restart

### ISSUE THREAD

**Issue by 59861795qqcom** [hashicorp/consul#7511]
hi, I am occured the problem ,  when I restart instance which running the consul client . 
then the consul members set it as left , after the instance starting , the client can not join again , 
it keep said 
"2020-03-26T11:32:21.180Z [WARN]  agent: Join cluster failed, will retry: cluster=LAN retry_interval=30s error=<nil>
2020-03-26T11:32:39.683Z [WARN]  agent.client.manager: No servers available
2020-03-26T11:32:39.683Z [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"

I checked #3938 ,but it seems no solution ,  

consul version 1.7.2

**Comment by 59861795qqcom** [comment]
when the client instance restart , the  status become  left , and cannot rejoin the cluster .

**Comment by jsosulska** [comment]
Hi @59861795qqcom 

Thanks for the update, and for tracking down that previous issue! 
Would you mind providing me with some additional information? 
- Can you please provide the Agent and Server configs?

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

- Can you post how you are restarting the Consul process? Is it through systemd, a command, or some other way?
- Is this happening on all members, or only specific hosts?

Looking forward to hearing back from you!
Best,
Jono

**Comment by 59861795qqcom** [comment]
Hi @ jsosulska , 
the problem have resolved ,  the client side ,do with a wrong flag,   I am add the flag: rejoin_after_leave = true
 it will recovery the before status . 
I think you can close the ticket .  thanks for the reply for my question .

**Comment by jsosulska** [comment]
Hi @59861795qqcom 

Thanks for letting me know :)
