### ISSUE TITLE
`ConnectCALeafRequest` should factor in `DNSSAN` and `IPSAN` into its cache key

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#7514]
https://github.com/hashicorp/consul/blob/e5d6273a48c15d6bab91584bd15c11e031195ec1/agent/cache-types/connect_ca_leaf.go#L640-L672

When computing the cache key for this type it should also be including the `IPSAN` and `DNSSAN` fields in the hash.

Currently there is no way for user provided input to set these fields and they are only used for auto-encrypt. Therefore this shouldn't be affecting anyone today. If we were to allow for setting these via an API or configuration then it could be problematic.

Regardless the "correct" behavior for this cache type should be to include those two slices in the hash structure call.

**Comment by sashaaKr** [comment]
@mkeeler Hey,
I would like to give a try to take this one.

So if I'm understand the scope of this change in `func (r *ConnectCALeafRequest) Key() string` function, am I right?

**Comment by mkeeler** [comment]
@sashaaKr Yes that is correct. There is a `hashstructure` call in that method that should probably include both of those other two fields. Besides that method we would need to add a new test (probably in agent/cache-types/connect_ca_leaf_test.go) to verify that a leaf request for the same service with different SANs outputs different values for the cache key.

One other thing to note here is that the cache key doesn't take the token or datacenter into account as that is information that the cache implementation always pulls out itself.

**Comment by sashaaKr** [comment]
@mkeeler great, I think I can handle

**Comment by sashaaKr** [comment]
@mkeeler hope this is ok:
https://github.com/hashicorp/consul/pull/7597

**Comment by crhino** [comment]
Fixed by #7597
