### ISSUE TITLE
Document how to use envoy

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#7538]
In the documentation for using consul-connect, the documentation states

>We are using the Consul Connect's built-in proxy for this guide. In a production deployment, we recommend using Envoy instead.

Many other instances have documentation on how to setup a production ready cluster, but when it comes to consul+connect with envoy, the reader is expected to just figure it out. 

Please add some documentation around envoy proxies so users can setup production ready clusters without guessing. 

https://learn.hashicorp.com/consul/developer-mesh/connect-services

**Comment by blake** [comment]
Hello,

The guide you linked also contains examples of using Envoy as a sidecar. The following guide in the series, https://learn.hashicorp.com/consul/developer-mesh/connect-envoy, walks through using Envoy with Connect.

It sounds like this information isn’t as easy to find as info on the built-in proxy. Would you be willing to share a bit more info on how you feel we could improve these guides, or make the Envoy-related information more discoverable?

**Comment by spuder** [comment]
Thanks, I did eventually find the information once I read further.

I think a single sentence could be added to the guide that will make this much clearer.

Change this: 
> We are using the Consul Connect's built-in proxy for this guide. In a production deployment, we recommend using Envoy instead.

To this:
> We are using the Consul Connect's built-in proxy for this guide. In a production deployment, we recommend using Envoy instead. Setting up Envoy is covered later in this guide.

**Comment by blake** [comment]
@spuder Thanks for the suggestion. I've added that statement to the Learn guide.
