### ISSUE TITLE
About ACL issue, modify the consul profile acl_default_policy, then reload the configuration, acl_default_policy not take effect

### ISSUE THREAD

**Issue by lindane** [hashicorp/consul#754]
consul version 0.5.0

Clustered environment for three server, two agent.
     server address: 192.168.2.71,192.168.2.72,192.168.2.73
     agent address: 192.168.2.61,192.168.2.62

1.consul configuration file as follows
{
  "server": true,
  "datacenter": "dc1",
  "data_dir": "/tmp/consul",
  "node_name": "consul-server1",
  "addresses": {
    "http": "192.168.2.71",
    "rpc": "192.168.2.71"
  },
  "acl_datacenter": "dc1",
  "acl_default_policy": "deny",
  "acl_master_token": "master_token_test",
  "acl_down_policy":"deny",
  "acl_token": "anonymous"
}

2.Start consul server

**Comment by lindane** [comment]
consul version 0.5.0

Clustered environment for three server, two agent.
server address: 192.168.2.71,192.168.2.72,192.168.2.73
agent address: 192.168.2.61,192.168.2.62

1.consul configuration file as follows
{
"server": true,
"datacenter": "dc1",
"data_dir": "/tmp/consul",
"node_name": "consul-server1",
"addresses": {
"http": "192.168.2.71",
"rpc": "192.168.2.71"
},
"acl_datacenter": "dc1",
"acl_default_policy": "deny",
"acl_master_token": "master_token_test",
"acl_down_policy":"deny",
"acl_token": "anonymous"
}

2.Start consul server
  consul agent -bootstrap-expect 3 -config-dir /etc/consul.d/ -atlas lindaneye/lindan -atlas-join

3.Start consul agent
  gocode/bin/consul agent -config-dir /etc/consul.d/ -atlas lindaneye/lindan -atlas-join

4.Began testing,The following test procedures and results with the same problem
  https://groups.google.com/forum/#!topic/consul-tool/8GWVT7W9zcY

issue 1:
  The parameter acl_default_policy has been set to deny and set the "service(here is mysql)" policy=write. When trying to register in the service/catalog endpoint,  the registration action failed. Is this a bug or misconfigure  And will it be resolved in the ver 0.5.1 ?

5.The consul's config file has  acl_default_policy changed to allow, and then reload the configuration again, the latest configuration file is shown below:
  {
  "server": true,
  "datacenter": "dc1",
  "data_dir": "/tmp/consul",
  "node_name": "consul-server1",
  "addresses": {
    "http": "192.168.2.71",
    "rpc": "192.168.2.71"
  },
  "acl_datacenter": "dc1",
  "acl_default_policy": "allow",
  "acl_master_token": "master_token_test",
  "acl_down_policy":"deny",
  "acl_token": "anonymous"
}
Now look at the server logs. There are some warnings:
     2015/03/04 04:54:22 [WARN] agent: Service 'mysql-1' registration blocked by ACLs
     2015/03/04 04:54:29 [WARN] agent: Check 'service:mysql-1' registration blocked by ACLs

issue 2:Modify acl_default_policy configured to allow and use / v1 / agent / service/register to register a service . Failed to register the service into endpoint after the reload the configuration. It is a bug or misconfigure?

**Comment by armon** [comment]
@lindane Unfortunately the `acl_default_policy` cannot be updated via a reload, it requires a restart of the servers to take affect. My guess is that the updated policy had not taken place.

With respect to the initial test of value "deny", based on your configuration here, it seems that is the correct behavior. The agent is configured with `acl_token` of "anonymous" and the default behavior is being set to "deny", so registration _should_ be blocked unless I'm missing something.

**Comment by lindane** [comment]
issue 1:In my environment, I do not want to restart the server through to make the new policy to take effect. there are other ways to make the new policy to take effect?

Default behavior is being set to "deny",but I set a new acl rules via postman,as follows:
1.api          http://192.168.2.61:8500/v1/acl/create?token=master_token_test
value      {"Name":"test_token","Type":"client","Rules":" service \"mysql/\" { policy = \"write\" } "}
Returns the id of an acl 

2.Use /v1/agent/service/register endpoint registration services,now look at the server logs. There are some warnings:
2015/03/04 04:54:22 [WARN] agent: Service 'mysql' registration blocked by ACLs
2015/03/04 04:54:29 [WARN] agent: Check 'service:mysql' registration blocked by ACLs

issue 2:I set a new acl rules,policy mysql service is set to write，so mysql service is to register /v1/catalog/services endpoints ,but / v1 / catalog / register endpoints and no mysql service.I acl newly created rule is wrong?

**Comment by ryanuber** [comment]
@lindane Currently there is no way to change the default policy without a restart. You will have to reload the servers in order for this to take effect.

Regarding the policy for the mysql service, you might want to make sure that the policy text is correct. It looks like there is a trailing slash '/' character in the service name, which might explain why you are being denied.

**Comment by lindane** [comment]
Thanks!

‘/’Is an extra character.I try to '/' characters removed as follows:
1.api http://192.168.2.61:8500/v1/acl/create?token=master_token_test
value {"Name":"test_token","Type":"client","Rules":" service \"mysql\" { policy = \"write\" } "}
Returns the id of an acl
2./v1/acl/list as follows:
{
"CreateIndex": 2774,
"ModifyIndex": 2774,
"ID": "e94af8d4-a21c-7edd-32db-834539bbebe5",
"Name": "test_token",
"Type": "client",
"Rules": " service \"mysql\" { policy = \"write\" } "
},
3.Use /v1/agent/service/register endpoint registration services,now look at the server logs. There are some warnings:
2015/03/06 02:56:44 [WARN] agent: Service 'mysql' registration blocked by ACLs
2015/03/06 02:56:52 [WARN] agent: Check 'service:mysql' registration blocked by ACLs

issue 1: Can not be register into the /v/catalog/services endpoints,acl rules created wrong?

**Comment by armon** [comment]
@lindane It sounds like you are hitting this same issue: https://github.com/hashicorp/consul/issues/734
Currently, the `acl_token` of the agent is used to register the service, so if that ACL does not have the proper permissions the registration is denied. The token passed in via the `/v1/agent/service/register` API is being ignored which is a bug.

**Comment by lindane** [comment]
Thanks!
