### ISSUE TITLE
Local token slider in New Token UI is confusing

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#7564]
![image](https://user-images.githubusercontent.com/1034429/78093928-22835400-7388-11ea-8a1f-3adff15b63c7.png)

Is this going to create a local or global token?

It's kinda confusing at first glance. By turning "No" to "Yes" then the token is "Not restricted". There's a bunch of double negatives in there that tripped me up.

Maybe if the slider changed from local to global it would make more sense.

**Comment by johncowen** [comment]
Closing see https://github.com/hashicorp/consul/pull/7830
