### ISSUE TITLE
difference in prometheus metrics vs normal metrics endpoint

### ISSUE THREAD

**Issue by 42wim** [hashicorp/consul#7584]
#### Overview of the Issue

Difference between the `consul_kvs_apply_count` from prometheus vs non-prometheus metrics.
The prometheus one are way higher and increasing much faster then the normal metrics.

7328 vs 152 (which seems to be the correct one)
(a few seconds later it shows 9679 vs 154)

```
# HELP consul_kvs_apply consul_kvs_apply
# TYPE consul_kvs_apply summary
consul_kvs_apply{quantile="0.5"} 4.07623815536499
consul_kvs_apply{quantile="0.9"} 5.345826148986816
consul_kvs_apply{quantile="0.99"} 11.635574340820312
consul_kvs_apply_sum 31233.52734351158
consul_kvs_apply_count 7328
```

```
   {
      "Name": "consul.kvs.apply",
      "Count": 152,
      "Rate": 64.95448677539825,
      "Sum": 649.5448677539825,
      "Min": 3.1917779445648193,
      "Max": 12.864093780517578,
      "Mean": 4.273321498381464,
      "Stddev": 1.0830046538542744,
      "Labels": {}
    },
```

I'm running consul v1.6.4 on linux/64bit

telemetry config is

```
{
 "telemetry": {
   "prometheus_retention_time": "24h",
   "disable_hostname": true
 }
}
```

**Comment by pierresouchay** [comment]
consul_kvs_apply_count 7328
=> 7328 in 24h ~5/min seems Ok

**Comment by pierresouchay** [comment]
`"prometheus_retention_time": "24h" `
Means that count will be reset to 0 every 24 hours (while it is done every minute for JSON default implementation)

**Comment by 42wim** [comment]
@pierresouchay thanks, makes sense now!
