### ISSUE TITLE
When should I go to deregister a node

### ISSUE THREAD

**Issue by Mstch** [hashicorp/consul#7590]
I manually unregister the node before the node restarts and re-register node after startup, is this correct and reasonable?

**Comment by jsosulska** [comment]
Hey @Mstch 

Thanks for posting!  For questions like this, we recommend posting them on the [Consul Discuss Forum](https://discuss.hashicorp.com/c/consul/29). That way, other people looking for answers can find them more quickly.

The short answer is - no, you shouldn't need to deregister the node. Consul can handle nodes [leaving](https://www.consul.io/docs/commands/leave.html) quite well. There may be times where [force leave](https://www.consul.io/docs/commands/force-leave.html) is what you want. In the force leave docs, there are even specific call outs for what `force-leave` is used for.

> Consul periodically tries to reconnect to "failed" nodes in case failure was due to a network partition. After some configured amount of time (by default 72 hours), Consul will reap "failed" nodes and stop trying to reconnect. The force-leave command can be used to transition the "failed" nodes to a "left" state more quickly, as reported by consul members.

If you are performing maintenance, or doing rolling restarts, a "leave" command before is perfectly fine. When the node is starting back up, you can set up the Consul agent to start on boot. We provide the [`-join`](https://www.consul.io/docs/agent/options.html#_join) and [`-retry-join`](https://www.consul.io/docs/agent/options.html#retry-join) options to help configure this in a file or via command line.

I hope this helps :) Please fee free to open a discussion post, and we can continue it there. I will leave this up until Friday, close this issue, and repost it on the Discuss forums then so it can be found easily.

Thank you!

**Comment by Mstch** [comment]
Thank you for your  reply @jsosulska 
I also want to ask another question, what status does ```leave``` here mean

> -rejoin - When provided, Consul will ignore a previous leave and attempt to rejoin the cluster when starting. By default, Consul treats leave as a permanent intent and does not attempt to join the cluster again when starting. This flag allows the previous state to be used to rejoin the cluster.

My understanding is that terminating the consul agent process through ```consul leave``` is leave
In fact, I didn't quite understand what this rejoin does. . . could you please tell me  something more about the ```rejoin```

**Comment by Mstch** [comment]
Oh, I seem to know the meaning of ```-rejoin```
He will only act on agents that do not use``` -join ```or ```-retry -join```at startup, and then automatically join the last joined cluster. Is this the case?

**Comment by jsosulska** [comment]
Hi @Mstch - Just wanted to circle back here. 

`join` is a **single** attempt of the consul agent to connect to any other agent.
[`rejoin`](https://www.consul.io/docs/agent/options.html#_rejoin) is used to rejoin in the event that the node has "left".
`-retry-join` will continue to attempt to retrying a join until it is successful. It's recommended to set [`-retry-max`](https://www.consul.io/docs/agent/options.html#_retry_max) when setting `-retry-join`.

For most cases, `-retry-join` and `retry-max` should work in your configurations.
Thanks!
