### ISSUE TITLE
Improve docs for secondary datacenter requirements of the Primary Datacenter (dc) Certificate SAN

### ISSUE THREAD

**Issue by punkrokk** [hashicorp/consul#7607]
#### Overview of the Issue

Lack of clarity to the certificate SAN requirements to have multiple datacenters.

When trying to add a secondary datacenter with TLS, there is a lack of clarity around how a requirement 
of any additional datacenters is to have the secondary datacenter's DNS name (servers.datacenter.consul.) in the certificate SAN. I think this is a common enough use case to include in the docs. I can see other things around secondary datacenter use cases that would be good to codify in the future, but starting here. 

#### Reproduction Steps

1. Create two datacenters
2. Enable TLS on Primary
3. Try to enable TLS on secondary
4. TLS errors due to the secondary datacenter SAN not present on primary datacenter certs (in SAN)
5. brick wall

### Consul info for both Client and Server

On consul server in secondary dc: 
<details>
  <summary>Server info</summary>

```
2020-04-07T03:45:01.792Z [ERROR] agent.server.raft: failed to heartbeat to: peer=10.20.3.193:8300 error="x509: certificate is valid for server.dc1.consul, localhost, not server.dc2.consul"
```

</details>

### Operating system and Environment details

Amazon Linux2, Ubuntu, CentOS7

### Challenges
It's not evident at all that in order to have TLS enabled in primary and secondary CA (I was doing client auto-join, and verify incoming) that one needs to create the primary dc certs like so: 

```
consul tls cert create -server -dc=dc1 -additional-dnsname=my_datacenterName
```

I definitely wasted a ton of time on this, and I think it's an important enough concept that it should either be in the `agent -> encryption` docs or in the `Datacenter Federation with WAN Gossip` Hashicorp Learn page. 

Please let me know if I just happened to miss the one page where this is better explained.

**Comment by eddie-rowe** [comment]
Thank you @punkrokk for your great feedback here! Based on your feedback, we've just finished updating our Learn guides here with more details regarding TLS in federated Consul datacenters:
https://learn.hashicorp.com/tutorials/consul/deployment-guide
https://learn.hashicorp.com/tutorials/consul/tls-encryption-secure

**Comment by punkrokk** [comment]
Thanks!
