### ISSUE TITLE
how is the deps folder being used? 

### ISSUE THREAD

**Issue by aminjam** [hashicorp/consul#762]
I am trying to build an older release from master branch using the `deps` folder, but I don't see any way to pull in the dependencies from previous versions. Consul doesn't seem to be using `godep` in a traditional way. With vendoring, the older version of dependencies are usually included. Is there a `make` command that will honor the `Rev` tag of the packages for an older release e.g. v4.0?

**Comment by armon** [comment]
@aminjam It is currently being used just to tag the versions at the time of the release. You can always move that file into the root as the `Godep` file, and then use the tool to reset and vendor the dependencies.
