### ISSUE TITLE
Consul http api does not preserve datacenter capitalization

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/consul#7630]
#### Overview of the Issue

If a datacenter has been created with a name MyDataCenter and  http://127.0.0.1:8500/v1/agent/members is called the name for dc is returned as "mydatacenter"

#### Reproduction Steps
1.   Create Consul Datacenter with a name with capitals
2.  Call http://127.0.0.1:8500/v1/agent/members

Consul version 1.6.2

**Comment by idrennanvmware** [comment]
Closing - user error on our part.

**Comment by pierresouchay** [comment]
Consul tend to be case insensitive since it also have a DNS compatibility layer which is case insensitive : see https://github.com/hashicorp/consul/issues/5707 for the reasons for

**Comment by pierresouchay** [comment]
Sorry, I misread, could you please provide a full test case?

**Comment by jsosulska** [comment]
Thanks @pierresouchay ! As you pointed out, Consul uses a [DNS interface](https://www.consul.io/docs/agent/dns.html) for a lot of its service discovery features. 

@idrennanvmware , if you have additional questions, please feel free to reach out on [our forums](discuss.hashicorp.com).

Thanks for the question!
