### ISSUE TITLE
Not being able to launch the Consul UI in internet explorer : TypeError: Unable to get property 'indexOf' of undefined or null reference

### ISSUE THREAD

**Issue by RajatRokade** [hashicorp/consul#7645]
I have a requirement where i need to be able to access the consul UI in IE browser. I am not being able to get the UI up and running the IE browser. It gives the following error `Consul returned an error.You may have visited a URL that is loading an unknown resource, so you can try going back to the root or try re-submitting your ACL Token/SecretID by going back to ACLs.
Try looking in our documentation `

Error Produced on the IE Console :` index Unable to get property 'indexOf' of undefined or null reference TypeError: Unable to get property 'indexOf' of undefined or null reference`

I am able to access the UI in other browsers. Is there a way in which i can get it running with the IE browser?

![Consul IE](https://user-images.githubusercontent.com/32566657/79224912-87a37300-7e79-11ea-812f-c7a08a6bf793.JPG)

![Consul IE](https://user-images.githubusercontent.com/32566657/79303435-85d6bf80-7f0c-11ea-9952-af23ba82510b.JPG)

**Comment by johncowen** [comment]
Closing as MS no longer supports IE 11 and Consul UI is designed to work with all actively supported browsers(i.e. Chrome, Firefox, MS Edge, etc)

See also https://www.consul.io/docs/troubleshoot/faq#q-what-browsers-are-supported-by-the-consul-ui
