### ISSUE TITLE
Can client and server be deployed on the same machine?

### ISSUE THREAD

**Issue by rickyma** [hashicorp/consul#7657]
If we only have 3 nodes in our production environment, we put consul server on each node to make a distributed consul server cluster.
Can we also put consul clients on these nodes? Because according to the architecture of consul, a service should communicate to the client(on the same machine) not a server directly.
Or it is not necessary to deploy server and client on the same machine. Because a server can do all the jobs that a client can do? e.g. health check?

**Comment by rickyma** [comment]
Anyone?

**Comment by clly** [comment]
A consul server _can_ act as a client. You can register services with them, do KV reads and writes and create session. My understanding is that it's not a recommended deployment and that services that use consul should use a consul agent to proxy to a consul server.

Some of those reasons are likely to make it easier pointing to the address of a service and make sure that a consul agent doesn't necessarily need to go off box to check a services healthcheck. Another reason is likely to ensure that there aren't any actions that a consul agent is doing that would prevent the consul server from fulfilling it's leadership duties.

**Comment by rickyma** [comment]
@clly I don't know if I got it wrong. Does this mean a Consul Server can do all the jobs that a Consul Client can. So I only need to deploy a Consul Server, that'll be enough? So the conclusion is: There is no need to deploy both Client and Server on the same node. Only Server will do.

**Comment by chuckyz** [comment]
That is correct.  You can even split ACLs between server/client access path on the exact same node if you wish to take it that far (e.g.: server <=> server communication uses a different ACL than app <=> client communication, even though it's the same server).

Consul server and client are the same binary and everything. :)

**Comment by jsosulska** [comment]
Hi folks, thanks everyone for the replies.

@rickyma - Please take a look at our [architecture documentation](https://www.consul.io/docs/internals/architecture.html).  

To answer your question; If you have other services also running on the Consul _Servers_, you do not need to add any additional clients. A design note, however - this can cause issues if the other services are resource intensive workloads. If a service located on your Consul _Server_ deployment takes down your Consul cluster, that outage will spread to all clients external from those services.

To take this one step further - once you have a dedicated deployment of Consul _Servers_, when new machines are added to host other services, these additional machines should have _clients_ installed on them, not more servers.

I hope this clarifies your questions. Please feel free to reach out to our [forums](discuss.hashicorp.com) where our community can provide more active support!

**Comment by rickyma** [comment]
Thanks for your reply @jsosulska .
Before I posted this question, I had read about the [architecture documentation](https://www.consul.io/docs/internals/architecture.html). But I didn't find anything useful to my question.

As you can see on this [consul/getting-started/agent](https://learn.hashicorp.com/consul/getting-started/agent). It says: "A client must be running on every node in the Consul datacenter that runs services, since clients are the source of truth about service health." So I don't know how to follow this rule in my scenario.

Due to some complicated reasons, I have to place a "particular service" on Consul Server nodes instead of Consul Client nodes. That's why I was asking if Consul Client is necessary in my scenario. If Consul Client is necessary for every service, that means I have to find a way to deploy a client and a server on the "particular service" node at the same time. If Consul Client is not necessary, that means a consul server will be enough(it can do all the work that a client can). I don't need to deploy extra clients on the consul server nodes which deployed my "particular services".

I don't know if I make myself clear. So I uploaded a picture of a simplified version of my deployment architecture.
![image](https://user-images.githubusercontent.com/13834479/81092647-8246bf00-8f33-11ea-9eb1-20ffe5e7de0a.png)
