### ISSUE TITLE
Consul client not listening to localhost randomly

### ISSUE THREAD

**Issue by urjitbhatia** [hashicorp/consul#7668]
Our consul client agent randomly stops listening on localhost causing KV get failures. There are no logs in Consul's log but even running `consul info` fails.

Our config is: 
```consul agent -config-dir=/etc/consul.d -bind=<privateip> -client "127.0.0.1 <privateip>```

It seems to start off fine but at some point it stops listening on localhost without any errors in the logs.

but nothing interesting in Consul logs.

### Consul info for both Client and Server

```
consul info
Error querying agent: Get http://127.0.0.1:8500/v1/agent/self: EOF
```
```
consul version
Consul v1.6.5
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```
### Operating system and Environment details

```
4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments

Nomad logs:
```
 2020/04/17 23:57:31.429824 [WARN] (view) kv.get(config/api/mysql/graph/pool.min): Get "http://127.0.0.1:8500/v1/kv/config/api/mysql/graph/pool.min?stale=&wait=60000ms": EOF (retry attempt 1 after "250ms")
    2020/04/17 23:57:31.429834 [WARN] (view) kv.get(config/api/mysql/graph-ro/pool.max): Get "http://127.0.0.1:8500/v1/kv/config/api/mysql/graph-ro/pool.max?stale=&wait=60000ms": read tcp 127.0.0.1:56686->127.0.0.1:8500: read: connection reset by peer (retry attempt 1 after "250ms")
    2020/04/17 23:57:31.429841 [WARN] (view) kv.get(config/api/mysql/awards/pool.min): Get "http://127.0.0.1:8500/v1/kv/config/api/mysql/awards/pool.min?stale=&wait=60000ms": read tcp 127.0.0.1:56684->127.0.0.1:8500: read: connection reset by peer (retry attempt 1 after "250ms")
```

**Comment by pierresouchay** [comment]
Hello @urjitbhatia,

Did you, by chance forget to specify [http_max_conns_per_client](https://www.consul.io/docs/agent/options.html#http_max_conns_per_client) ? (So, you might be limited to 100 connections).

When reaching this limit, the agent abruptly close the connection, vote for https://github.com/hashicorp/consul/issues/7527 if this is your problem :-)

**Comment by jsosulska** [comment]
Hi @urjitbhatia ,

As Pierre mentioned, there are some configurations you can adjust to make this more flexible. Please let us know what the result was.

If this does not solve your issue, please also include a snippet or gist with your consul server + client configuration files.

Happy Coding!

**Comment by urjitbhatia** [comment]
Hi @pierresouchay that was it! Thanks for the pointer - we went down a frustrating search for why it was behaving badly and this saved us. Looks like a foot-gun waiting in the config changes.

@jsosulska - thanks for the nudge, that did solve our problem. I wonder if there is a way to make the default either yell louder when this is happening (there were no logs indicating we were exhausting connections and silently dropping requests) or to make the change configurable via consul server UI perhaps for easier remediation once a cluster is up but not behaving properly in this case.

**Comment by pierresouchay** [comment]
@urjitbhatia Vote for #7527 and also for https://github.com/hashicorp/go-connlimit/pull/6 :-)
=> the clients will have a clear message with the error (and might be able to rate limit for instance)
