### ISSUE TITLE
etcd vs consul

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/consul#768]
Hi. I'm try to choose cluster manager for object storage engine.
So i read about etcd and consul.
I need: easy to boostrap cluster  (ideally i don't want to know about all members, i have 2-3 nodes with persistent addresses, and 100 nodes that need to join to cluster and can vote for leader election (so in consul terminology it servers). Ideally C api/binding to simplify curl/dns dances. Able to detect current leader from external application. Automatic node adding and removing when node start/stop.

What is the main benefits in my cases of consul vs etcd?

**Comment by armon** [comment]
@vtolstov I highly recommend reading this page first:
https://consul.io/intro/vs/zookeeper.html

With respect to your questions:
* Bootstrapping Consul is very simple, and the address of all nodes do not need to be known. The gossip protocol is used to automatically manage that.
* You cannot use 100 nodes as a server. Technically you can try, but the system will suffer and not perform as you expect. There should be 3 or 5 servers, potentially 7, and the rest are clients.
* There is no official C API, but you can use libcurl easily enough, as it's just a REST HTTP/JSON API.
* The `/v1/status/leader` endpoint can be used to find the leader.
* Nodes are automatically added/removed using the gossip protocol

If you are trying to do client-side leader elect (e.g. elect a leader in your own application, not Consul), then take a look here:
* https://consul.io/docs/guides/leader-election.html
* https://consul.io/docs/commands/lock.html

Hope that helps!

**Comment by vtolstov** [comment]
> You cannot use 100 nodes as a server. Technically you can try, but the system will suffer and not perform as you expect. There should be 3 or 5 servers, potentially 7, and the rest are clients.

In case of etcd i read somewhere.. that etcd use only needed servers (7 or 9) and all other acts as followers and when the one of server that in leader election dies, follower node joins leader election...
Does it possible to do this in consul?

**Comment by armon** [comment]
@vtolstov Unfortunately Consul does not support hot-standby servers. Nodes must be active servers or clients. This is something we are interested in looking into eventually, but no short term plans.

**Comment by iamthemuffinman** [comment]
@armon So if you have 3-5 active servers and 100 clients, if one of the active servers kicks the bucket, a client won't step up to take the place of an active server?

**Comment by ryanbreen** [comment]
That is correct.  Consul agents are either servers or clients.  There's not
currently a facility for a client to become a server automatically.

**Comment by iamthemuffinman** [comment]
@ryanbreen Is there a branch to add this feature?

**Comment by ryanbreen** [comment]
I don't believe so.  It may be something the team is considering, but to my
knowledge it's not an immediate roadmap item.

**Comment by armon** [comment]
I think @ryanbreen perfect answered this. There is no plans to support that feature in the short term, so you must dedicate server nodes in advance. I'm going to close this as I think the question is answered.
