### ISSUE TITLE
Serf events available in consul

### ISSUE THREAD

**Issue by felka** [hashicorp/consul#770]
It will be great having serf events like member-join. member-leave and etc in consul events.
Thanks

**Comment by blalor** [comment]
+1

**Comment by slackpad** [comment]
Hi after thinking about this a bit I think I'm going to close this out. These events are best effort and low level details of Consul's implementation. Consul provides better tools such as https://www.consul.io/api/index.html#blocking-queries if you want to see these as they happen. Keeping these as internal details to Consul will help keep us free to make changes later.
