### ISSUE TITLE
consul snapshot size reduced from 1GB to 17 MB 

### ISSUE THREAD

**Issue by sgoogal** [hashicorp/consul#7709]
consul snapshot size reduced a lot recently from 1GB to 17 MB over the period of one month, not sure why, is it because of compaction? if so when will be compaction triggered?

**Comment by jsosulska** [comment]
This is currently being discussed on our [Forum](https://discuss.hashicorp.com/t/consul-snapshot-compaction/8445). Closing in favor of the thread.
