### ISSUE TITLE
KV store does not maintain object content types

### ISSUE THREAD

**Issue by mpalmer** [hashicorp/consul#772]
If I PUT a resource, sending a `Content-Type` request header of some arbitrary type, I expect that a request to retrieve that resource (with `?raw`) to send back the same `Content-Type` in the response headers.  Instead, I just get back `text/plain` all the time.

**Comment by armon** [comment]
Unfortunately, there is no `Content-Type` storage for objects internally. They are just opaque binary blobs. I don't anticipate us supporting this in the near future.

**Comment by armon** [comment]
Closing, as we have no immediate plans to support this.
