### ISSUE TITLE
ID vs CheckID for Healthcheck in consul version 1.7.2

### ISSUE THREAD

**Issue by abguptms** [hashicorp/consul#7733]
What is the right property to use for consul health check registration between ID and CheckID?

The [doc ](https://www.consul.io/api/agent/check.html#register-check) seems to be pointing to "ID" usage but when its actually used in the code, consul returns Serialization error mentioning "ID" property is unknown.

On the contrary, if CheckID is used for registration(which is expected to be deprecated), it goes through.

**Comment by jsosulska** [comment]
Hi @abguptms ,

Thanks for posting about this. Can you please provide some additional information?
1. A copy of your check config/payload
2. What command(s) are you using to register this check?
3. Can you provide any log snippets, in a gist if they are more than 20 lines?

Happy Coding!

**Comment by dnephin** [comment]
I believe we have an umbrella issue for this problem: #7566

**Comment by jsosulska** [comment]
Hey @abguptms ,

Since there has not been a response in 30 days, closing.
If you would like to continue the conversation, please continue on #7566 . We will track and collect information there. You can copy paste my questions and the response on that thread.

Happy Coding!
