### ISSUE TITLE
Consul services register silently does nothing when given file with unsupported file extension

### ISSUE THREAD

**Issue by greenrd** [hashicorp/consul#7748]
#### Overview of the Issue

I tried to register a service but nothing happened. The problem turned out to be because the file extension was incorrect, but the need for the file extension to be from a supported list was not mentioned on the documentation page for the `consul services register` subcommand. Also, I believe at least one error or warning should have been printed: either a message about an ignored file, a message that no services were registered, or both.

#### Reproduction Steps

1. Create a service description file, calling it foo.service
1. Type `consul services register foo.service`

### Consul info for both Client and Server

<details>
  <summary>Client and server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 5
        services = 8
build:
        prerelease = 
        revision = 1200f25e
        version = 1.6.2
consul:
        acl = disabled
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 10.42.4.108:8300
        server = true
raft:
        applied_index = 49678
        commit_index = 49678
        fsm_pending = 0
        last_contact = 0
        last_log_index = 49678
        last_log_term = 2
        last_snapshot_index = 49177
        last_snapshot_term = 2
        latest_configuration = [{Suffrage:Voter ID:b6705d1a-a960-0c91-dba5-5e684c63face Address:10.42.4.108:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 16
        goroutines = 91
        max_procs = 16
        os = linux
        version = go1.12.13
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

Alpine Linux 3.9 in Docker container

### Log Fragments

There are no relevant log fragments, because the API is never called.

**Comment by jsosulska** [comment]
Hello @greenrd ,

Thanks for reporting this. The information regarding what filetypes are supported for services is discussed in the [service documentation](https://www.consul.io/docs/agent/services.html#service-definition), rather than the documentation for a specific endpoint.

I do agree that a silent fail is not the best feedback experience though. I'm going to tag this as an enhancement, and we'll take a look at improving this.

**Comment by dnephin** [comment]
#7762 should fix this problem, and a couple other places that we were not printing warnings
