### ISSUE TITLE
How do I turn a web page into a Chinese page

### ISSUE THREAD

**Issue by gengxinyu0** [hashicorp/consul#7749]
I hope to be able to Chinese web pages but there is no good way, I hope to get your help

**Comment by jsosulska** [comment]
Hi @gengxinyu0 

Are you looking to have the Consul web UI in Chinese, or our Consul.io website in Chinese?

**Comment by gengxinyu0** [comment]
Because I don't see the consul Chinese interface, I want the Web UI in English but I can't compile page file, can you help me? Thank you very much

**Comment by gengxinyu0** [comment]
Because I don't see the consul Chinese interface, I want to amend the Web UI in English to Chinese but I can't compile the page file, can you help me? Thank you very much

**Comment by gengxinyu0** [comment]
I want to use the Chinese Consul Web UI
