### ISSUE TITLE
Misleading error message from agent when cluster not bootstrapped

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/consul#775]
Scenario:
- Agent is joined to server
- Cluster not bootstrapped (servers not joined to each other such that `bootstrap_expect` is reached)
- Running `consul members` on agent shows existence of servers

Error when running `curl localhost:8500/v1/catalog/services`: `No known Consul servers`

**Comment by n2taylor** [comment]
I have also seen this one. Could it at least return valid JSON?

**Comment by slackpad** [comment]
Hi, this never made it on the roadmap, and it's not a very high priority for us. We would gladly review a PR for this functionality, but we are going to close this issue since it's not something we are going to implement ourselves.
