### ISSUE TITLE
http_max_conns_per_client default value has changed

### ISSUE THREAD

**Issue by lockp111** [hashicorp/consul#7766]
http_max_conns_per_client default value is 200.
but docs show the value is 100.

**Comment by jsosulska** [comment]
Hi @lockp111 

Thanks for reporting this! The code base has actually been updated to reflect this change, as this was fixed in PR#7289. We're in the process of revamping our website, so this will be updated in the next two weeks to reflect this change.

Closing as a duplicate for now.
