### ISSUE TITLE
Add API endpoint for restoring ACL tokens

### ISSUE THREAD

**Issue by dblessing** [hashicorp/consul#777]
We would feel much more comfortable having a backup of ACL tokens. We can do that now, but we can't restore those tokens. We would have to generate new tokens and then apply the rules. Then we would have to give those new tokens to all of our applications/clients. If we had an API endpoint to restore ACL tokens that would help.

**Comment by armon** [comment]
I agree, this seems to be a broader issue for customers. Tagging as enhancement.

**Comment by stevendborrelli** [comment]
+1 this. Would love to be able to specify our own UUID when generating a policy.

**Comment by keithchambers** [comment]
+1

**Comment by ryanbreen** [comment]
+1.  This would be huge for disaster recovery.  Reissuing new tokens to a community of clients isn't really an option, at least not in an acceptable timeframe.
