### ISSUE TITLE
Consul server/agent with unix socket http breaks 'consul watch'

### ISSUE THREAD

**Issue by fujin** [hashicorp/consul#778]
Our system uses unix sockets for RPC and HTTP instead of the usual TCP, this is so I don't have to protect the network layer from user code (long story)

I have everything working OK, and I've used the consul/api package to talk over the unix socket in a minimal k/v client, but some of the built in commands are not functioning, all of those that seem to use HTTP, like watch, exec, etc.

This is where the error is coming from: https://github.com/hashicorp/consul/blob/58806bc7bb0330edf953f7798fa4cd8f555e8c0d/command/watch.go#L140-L144

```
[aj@aj-onebox-zero ~]$ /opt/consul/consul members -detailed                                                                                                                                                                              
Node                            Address              Status  Tags
aj-onebox-zero.onebox.panth.io  10.223.145.110:8301  alive   role=consul,dc=onebox,vsn=2,vsn_min=1,vsn_max=2,build=0.5.0:0c7ca91c,port=8300,bootstrap=1
[aj@aj-onebox-zero ~]$ echo $CONSUL_RPC_ADDR 
/opt/consul/rpc.sock
[aj@aj-onebox-zero ~]$ echo $CONSUL_HTTP_ADDR 
/opt/consul/http.sock
[aj@aj-onebox-zero ~]$ sudo cat /etc/consul.d/config.json 
{
  "addresses": {
    "rpc": "unix:///opt/consul/rpc.sock",
    "http": "unix:///opt/consul/http.sock"
  },
  "unix_sockets": {
    "group": "1031",
    "mode": "770"
  },
<trimmed>
}
[aj@aj-onebox-zero ~]$ ls -lah /opt/consul/http.sock 
srwxrwx--- 1 consul pantheon 0 Mar 12 02:09 /opt/consul/http.sock
(reverse-i-search)`l': ls -lah /opt/consu^Chttp.sock 
[aj@aj-onebox-zero ~]$ /opt/consul/consul watch -http-addr=/opt/consul/http.sock -type key -key foo
Error querying Consul agent: Get http:///opt/consul/http.sock/v1/agent/self: dial tcp: lookup /opt/consul/http.sock: no such host
```

What is weird I suppose is that I am using this consul/api package in our internal kv client, which works fine against the socket:

```
[aj@aj-onebox-zero ~]$ ./consulapi kv get 404                                                                                                                                                                                                  
2015/03/12 20:56:23 payload is nil
[aj@aj-onebox-zero ~]$ ./consulapi kv get foo
2015/03/12 20:56:25 data: bar
2015/03/12 20:56:25 sha256: fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9
[aj@aj-onebox-zero ~]$ ./consulapi kv delete foo
2015/03/12 20:56:34 OK
```

Thoughts? Does the consul agent need the CONSUL_*_ADDR's in the systemd unit file as environment variables as well?

**Comment by fujin** [comment]
`http:///opt/consul/http.sock/v1/agent/self` looks to be the source of the issue. It's taking the socket url and turning it into http instead of treating it as unix:// or similar.

**Comment by fujin** [comment]
Same without specifying -http-addr (using the CONSUL_HTTP_ADDR, I presume)

```
[aj@aj-onebox-zero ~]$ echo $CONSUL_HTTP_ADDR 
/opt/consul/http.sock
[aj@aj-onebox-zero ~]$ /opt/consul/consul watch -type key -key foo
Error querying Consul agent: Get http:///opt/consul/http.sock/v1/agent/self: dial tcp: lookup /opt/consul/http.sock: no such host
```

**Comment by ryanuber** [comment]
Hey @fujin, if you prefix the socket path with `unix://` that should work. Basically the client keys off of this prefix to replace the default HTTP client with a custom one which speaks over UNIX sockets.

Can you give that a try and let us know if it works? It should be the same for consul/api too. Thanks!

**Comment by fujin** [comment]
```
[aj@aj-onebox-zero ~]$ export CONSUL_HTTP_ADDR=unix:///opt/consul/http.sock
[aj@aj-onebox-zero ~]$ /opt/consul/consul watch -type key -key foo
null
[aj@aj-onebox-zero ~]$ /opt/consul/consul exec ls
==> aj-onebox-zero.onebox.panth.io: finished with exit code 1
1 / 1 node(s) completed / acknowledged
```

Well I'll be a monkeys uncle :8ball:  I don't know what my custom consulapi kv client is doing (how it is working) but I'll modify our environment variables. Please consider resolved!

**Comment by ryanuber** [comment]
Glad to hear it!
