### ISSUE TITLE
Add consul lock -try

### ISSUE THREAD

**Issue by iconara** [hashicorp/consul#780]
I'm really excited about `consul lock` and have already found many uses for it, it's a great feature. There's one thing that would make it even greater: a way to try the lock and not run if it can't be aqcuired immediately.

As I understand it the way it works now is that all invocations of `consul lock …` will run eventually, but sometimes you only want one of them to run.

One example that I have previously implemented using locking through the HTTP API is listening for service changes and updating a DNS record. All nodes have a watch that is run when the service health changes, but only one of them should update the DNS record. With `consul lock` only one would update the record _at a time_, but all would eventually run, which may not be catastrofic in this case as they would make the same update, but it would be unnecessary. In my implementation the watch attempts to take the lock but when unsuccessful it just exists without doing anything.

It would be great if `consul lock` would have something like a `-try` flag that would behave similarily (and return a non-zero exit code when it failed). Alternatively a `-timeout N` flag could be used to wait N seconds to acquire the lock before failing, with `-timeout 0` working more or less like `-try`.

Apologies if this is already planned or has been suggested elswhere.

**Comment by armon** [comment]
This is a great idea! Thanks!

**Comment by marceldegraaf** [comment]
@armon are there plans to implement this in the foreseeable future, or would you accept a pull request for this? In the latter case: can you give me an indication of how hard it is to implement this in Consul?

@iconara did you find a workaround for the missing `-try`/`-timeout` flags in your setup? If so, can you share that?

**Comment by iconara** [comment]
@marceldegraaf I haven't got any good workarount for this, no. I have one application that does something like it through the HTTP interface, but it would be so much better to use `consul lock -try`. I'd be very greatful if this was implemented.

**Comment by slackpad** [comment]
I'll see about getting this into our near term roadmap after we ship 0.6.

**Comment by marceldegraaf** [comment]
Thanks @slackpad. If you're open to a PR for this, and can point me to how that would work in the Consul code base, I'd be glad to submit one.

**Comment by daveadams** [comment]
I would love to have `-try` but especially `-timeout N`. It would solve a lot of problems, and it was immediately what came to mind when I read about the `lock` command. I can think of workarounds using HTTP API as mentioned, but command line lock would be amaze.

**Comment by skippy** [comment]
https://github.com/EvanKrall/cronsul/blob/master/cronsul is an interesting approach.  It isn't as elegant as `consul lock -try` would be, and it leaves garbage behind, but for what he had to work with it is nicely done!

**Comment by insanejudge** [comment]
I hate just doing a +1, but this functionality is something I've ended up hacking together in a similar manner to cronsul a few times over, and combined with the existing lock/semaphore would provide a powerful set of tools to simply assemble some pretty complex systems

**Comment by marceldegraaf** [comment]
@armon @slackpad any updates on getting this functionality into Consul?

**Comment by marceldegraaf** [comment]
![YASSSS](http://i.imgur.com/fIhLNdo.gif)

Thank you so much! :tada:

**Comment by slackpad** [comment]
lol - np! should be released in the next couple days :-)
