### ISSUE TITLE
Documentation unclear on how to associate tokens with policies

### ISSUE THREAD

**Issue by centromere** [hashicorp/consul#782]
There doesn't seem to be a section in the documentation which specifies how to link ACL tokens to policies. It is very possible that I overlooked it.

**Comment by ryanbreen** [comment]
I made some tweaks to docs/internals/acl.html to improve coverage of this: https://github.com/hashicorp/consul/blob/d90a466f45e0ffd01f682ee2503a385076ab1d8f/website/source/docs/internals/acl.html.markdown
