### ISSUE TITLE
web-ui doesn't support UTF-8 values in kv

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul#783]
If I paste a UTF-8 value into the content box in the kv UI for a new key, it will submit the data properly, but when viewing in Chrome or Safari, the value comes back as a different character.

If I extract the value via the API, it comes back as the correct value.

Steps to reproduce:
1. In the Web-UI create a new key called `foo` with the value of `✈`
2. Reload the page, the value will now be `â`
3. Make a curl request to validate the value: `curl --verbose http://localhost:8500/v1/kv/foo`
4. Take the base64 encoded value and decode it, which will yield a byte sequence of `\xe2\x9c\x88`, which in turn can be decoded as the proper UTF character.

Python decoding example:

```
import base64

print(base64.b64decode('4pyI').decode('utf-8'))
```

**Comment by pearkes** [comment]
Thanks for this. Looks like this is our problem:

```
> window.atob("4pyI")
"â"
```
That decoding isn't working with the value. Tagged as a bug.

**Comment by pearkes** [comment]
[Related note](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_.22Unicode_Problem.22).

**Comment by nodakai** [comment]
web-ui 0.7.5 seems to be handling ✈ and other advanced Unicodes such as 🍺 correctly both in a key and in a value. Debian Chrome 56 and Iceweasel (Firefox) 45.7

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
