### ISSUE TITLE
Maintenance mode for external services

### ISSUE THREAD

**Issue by allgeek** [hashicorp/consul#786]
It seems the maintenance mode features in 0.5 only support agent-local services; both the CLI commands and the HTTP API related to maint are under the 'agent' context.  Are there any plans to support configuring maintenance mode via the catalog API so we can similarly control external services?

Thanks,
Levi

**Comment by ryanuber** [comment]
@allgeek The general idea was to wrap a disruptive operation to the local node or one of its services in `consul maint` to minimize the impact to clients. We could probably do something similar to support this use case though, marking as an enhancement!

**Comment by i0rek** [comment]
We haven't gotten around to do this one yet and I doubt we will in the future because it is not something that is frequently requested. If you want to provide a PR I would be happy to give you feedback!
