### ISSUE TITLE
Unknown field "failures_before_critical" error on registration

### ISSUE THREAD

**Issue by GBDBEN1** [hashicorp/consul#7869]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

When registering a service through the API, the following error is returned by consul
b'Request decode failed: json: unknown field "failures_before_critical"'

#### Reproduction Steps

1) Create a single dockerized consul instance with the following command.

`docker run -d -p 8500:8500 -p 8301:8301 -p 8301:8301/udp -p 8300:8300 -p 8302:8302 -p 8302:8302/udp -p 8400:8400 consul:1.7 agent -dev -client=0.0.0.0 -bind=0.0.0.0`

2) Run the following python script

```
import requests

consul_adress= ""
service_address = ""
payload = {
        "ID":"consuldebug",
        "Name": "consuldebug",
        "Address": f"{service_address}",
        "Port": 5000,
        "Weights": {
            "Passing": 10,
            "Warning": 2
        },
        "checks": [{
            "name":"example_check",
            "tls_skip_verify": True,
            "HTTP": f"http://{service_address}/",
            "Interval": "3s",
            "failures_before_critical":2
        }]
    }

requests.put(f"http://{consul_adress}:8500/v1/agent/service/register", data=json.dumps(payload),timeout=3)

```

### Consul info for both Client and Server

agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = 8b4a3d95
        version = 1.7.3
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = ########
        server = true
raft:
        applied_index = 133
        commit_index = 133
        fsm_pending = 0
        last_contact = 0
        last_log_index = 133
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:1976992f-584a-f3af-69bb-1ea44d90504f Address:#######:8300}]
        latest_configuration_index = 0
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 78
        max_procs = 2
        os = linux
        version = go1.13.7
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1

### Operating system and Environment details

Docker container, running on RHEL 7.6

### Log Fragments

b'Request decode failed: json: unknown field "failures_before_critical"'

**Comment by mkeeler** [comment]
We should probably make it support snake_case but if you change `failures_before_critical` to `FailuresBeforeCritical` it should work

**Comment by GBDBEN1** [comment]
It is indeed working when CamelCase is used, thank you. FYI: The [checks](https://www.consul.io/docs/agent/checks.html) documentation page has a snake_case example.
