### ISSUE TITLE
How to list existing WATCHES of an agent

### ISSUE THREAD

**Issue by imcom** [hashicorp/consul#787]
I just could not mange to find how can I list all WATCHES of a given agent, is there any method/API to provide such information? Plus, modifying config file each time to dynamically add/remove WATCHES seems also a bit troublesome.

**Comment by armon** [comment]
Unfortunately, there is no API to expose the active watchers.

**Comment by kaelumania** [comment]
I would love to see this as an API implemented.

**Comment by OferE** [comment]
+1
would be great to see all watchers
why did you close this?

**Comment by sobertooth** [comment]
+1 to this!

**Comment by robert-blankenship** [comment]
Running into a major performance degradation with a Consul consumer (Docker), this would be extremely helpful but seemingly simple to implement
