### ISSUE TITLE
[Doc][Bug] typo in acl-troubleshooting page

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#7871]
There is a typo in the acl-troubleshooting page. 

https://learn.hashicorp.com/consul/security-networking/acl-troubleshooting

`Llist` should be `list`

>»Consul ACL policy Llist
The consul acl policy list command will output all the available policies. When you're first setting up tokens you should use it to ensure the list of policies and their rules are as expected. In the example output below, there are two policies; the Consul created global-management policy and a user created policy named server-one-policy.

![Screenshot 2020-05-13 11 46 14](https://user-images.githubusercontent.com/242382/81846503-6fbe1e00-950f-11ea-93d1-c9daac8a24a1.png)

I don't think the learning pages are public, otherwise I would fix this.

**Comment by blake** [comment]
Thanks @spuder. We'll fix this shortly.
