### ISSUE TITLE
Promote inclusive behavior by removing whitelist/blacklist terminology 

### ISSUE THREAD

**Issue by cainejette** [hashicorp/consul#7901]
Something my workplace has started focusing on is improving inclusive behaviors and language. We've started an audit of our codebase and are looking for ways of replacing exclusive language like whitelist/blacklist with more neutral terms like allowlist/denylist. It would be great if consul did the same, so our codebase were cleaner.

**Comment by banks** [comment]
Thanks for raising this @cainejette, we're certainly interested in ensuring our language is inclusive and will discuss across all products the right scope for changes here.

Would you be able to confirm where you've found this terminology? To my knowledge, we don't use those terms anywhere in our actual configuration syntax currently but do use them once each on the documentation page for our configuration. I've not yet grepped the whole codebase.

> so our codebase were cleaner
To be clear, are you talking about the Consul code base or your application? If your app, how would changing Consul code or docs help you app codebase?

**Comment by cainejette** [comment]
Thanks for the response @banks 

We vendor our go dependencies, and I see in `vendor/github.com/hashicorp/consul/api/connect_intention.go` a comment that mentions whitelist/blacklist. 

Looks like that's [here](https://github.com/hashicorp/consul/blob/b14696e32ad54cca96784c9010910c1606272b56/api/connect_intention.go#L36).

**Comment by banks** [comment]
For context several other HashiCorp products have already intentionally moved away from "white/black list" language so we should too.

There are a few examples in the docs and a handful in code comments that should be relatively simple to replace with something more neutral as suggested.

Auditing for any additional non-inclusive terms is something we'll undertake separately as we develop a more comprehensive organisation-wide policy on terms that we want to avoid to avoid scope creeping this too much!

**Comment by cainejette** [comment]
Happy to open a PR if you're accepting them.

**Comment by cainejette** [comment]
https://github.com/hashicorp/consul/pull/7969
