### ISSUE TITLE
Non Primary Datacenter Cluster with ACLS and Connect CA produces: Error parsing CA cert: no PEM-encoded data found

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/consul#7906]
#### Overview of the Issue

We have a WAN federated cluster setup where we have "primary-cluster" and "gateway-cluster" both attempting to use Consul Connect.  The exact same service and registration work in the "primary-cluster" but when the same job (we use nomad for convenience) is scheduled in the "gateway-cluster" we receive the error

2020-05-15T17:52:25.710Z [ERROR] agent.client: RPC failed to server: method=ConnectCA.Sign server=XX.XX.XX.XX:8300 error="rpc error making call: rpc error making call: error parsing CA cert: no PEM-encoded data found"

Over and over in our logs.

For simplicity we are using the bootstrap consul token and an ACL policy of *->* ALLOWED has been set up.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1.  Create a primary cluster (3 nodes) with ACLS enabled.
2. Create a gateway cluster (3 nodes) -  wan joined to the primary.   Note: "Central config has been enabled"
3.  Attempt to create any Consul Connect enabled service on the gateway-cluster (won't work) but does on the primary-cluster

Additionally we have verified that the results of curl "http://localhost:8500/v1/connect/ca/roots" is identical on servers in all clusters.

The config CA we are using is the default:

"connect": {
        "enabled": true
    },

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 5
	services = 5
build:
	prerelease =
	revision = 9ea1a204
	version = 1.7.2
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = XX.XX.XX.XX:8300
	server = true
raft:
	applied_index = 764
	commit_index = 764
	fsm_pending = 0
	last_contact = 27.238652ms
	last_log_index = 764
	last_log_term = 4
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:74ec4144-b1f5-755c-889e-00ad6bd00196 Address:10.84.132.172:8300} {Suffrage:Voter ID:400b7034-657f-8626-0518-ae63b47c0dc5 Address:10.84.132.62:8300} {Suffrage:Voter ID:e85e8870-6366-b87b-c030-6ec2c0129650 Address:10.84.132.99:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 4
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 118
	max_procs = 8
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 4
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 7
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 10
	members = 6
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

PhotonOS3

### Log Fragments

See synoposis/overview

**Comment by idrennanvmware** [comment]
`job "database-primary" {
    datacenters = ["primary-cluster"]
    type = "service"

    group "database-primary" {
        count = 1

        network {
            mode = "bridge"
        }

        service {
            name = "database-primary"
            port = "25432"

            connect {
                sidecar_service {}
            }
        }

        task "database-primary" {
            driver = "docker"

            config {
                image = "nicholasjackson/fake-service:v0.9.0"
            }

            env {
                NAME = "database"
                MESSAGE = "ok"
                LISTEN_ADDR = "0.0.0.0:25432"
                TIMING_VARIANCE = "25"
                HTTP_CLIENT_KEEP_ALIVES = "true"
            }

            resources {
                cpu    = 100
                memory = 256
            }
        }
    }
}
`

The nomad job we are using for scheduling on each of the clusters

**Comment by idrennanvmware** [comment]
We did a quick experiment - switching 

    "acl": {
        "enabled": true,
{% if consul_acl_agent_token %}
        "default_policy": "deny",
        "tokens": {
            "agent": "{{ consul_acl_agent_token }}"
        },


TO

    "acl": {
        "enabled": true,
{% if consul_acl_agent_token %}
        "default_policy": "allow",
        "tokens": {
            "agent": "{{ consul_acl_agent_token }}"
        },

Allows it to work so it appears to be some ACL permissions issue.   The system in question is using the bootstrap tokens for the agent though so if anyone has any insight why this is not working - we would appreciate the guidance

**Comment by idrennanvmware** [comment]
Ok - Found the issue (if this helps others).   The replication token wasn't set.   What's strange is that the federation didn't fail outright, in fact it looked healthy and even logging in to ACL across the clusters worked BUT certain ACL pieces were failing until Mesh tried to use them.

**Comment by Crizstian** [comment]
probably this are the same issue or related, I though it was a Nomad issue but perhaps is a Consul issue: https://github.com/hashicorp/nomad/issues/8019
