### ISSUE TITLE
MetaData issue with ACL

### ISSUE THREAD

**Issue by melhir** [hashicorp/consul#7916]
**Overview of the Issue**

During creating my first consul cluster, I've noticed that when ACL is enabled on server and clients, there is no metadata in nodes catalog. When I've disabled ACL on server, metadatas showed up, but after enabling and adding new client the procedure had to repeated. In my case, I want to store some metadatas of nodes and I don't want to disable and enable ACL to add every host with metadatas.

**Reproduction Steps**
1. Bootstrap the cluster (I have only one server in it).
2. Enable whitelist ACL on server/client agent(s).
3. Configure client with metadatas and join cluster.
![image](https://user-images.githubusercontent.com/9166954/82312834-e18edf80-99c7-11ea-8d10-84d8d3593f86.png)

**Consul info for both Client and Server**

Client
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 8b4a3d95
	version = 1.7.3
consul:
	acl = disabled
	known_servers = 1
	server = false
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 46
	max_procs = 1
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 27
	members = 3
	query_queue = 0
	query_time = 1
```
Server
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 8b4a3d95
	version = 1.7.3
consul:
	acl = enabled
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = xxx.xxx.xxx.xxx:8300
	server = true
raft:
	applied_index = 673
	commit_index = 673
	fsm_pending = 0
	last_contact = 0
	last_log_index = 673
	last_log_term = 7
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:fc7d2x69-xxx-xxx-7xx13e-xxxxxxxx Address:xxx.xxx.xxx.xxx:8300}]
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 7
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 94
	max_procs = 2
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 27
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 1
	query_queue = 0
	query_time = 1

```
**Operating system and Environment details**
The cluster is one server agent standalone on Ubuntu 18.04, Clients agent running standalone on Ubuntu 18.04.

Server Config (consul.json)
```
{
    "server": true,
    "ui": true,
    "bootstrap_expect": 1,
    "advertise_addr": "xxx.xxx.xxx.xxx",
    "bind_addr": "0.0.0.0",
    "client_addr": "0.0.0.0",
    "datacenter": "dc1",
    "data_dir": "/opt/consul",
    "encrypt": "**************************************************",
    "node_meta": {
        "meta": "data"
    }
}
```
Server ACL config (acl.hcl)
```
acl {
  enabled = true
  default_policy = "deny"
  enable_token_persistence = true
}
```
Client config (consul.json)
```
{
    "advertise_addr": "yyy.yyy.yyy.yyy",
    "bind_addr": "0.0.0.0",
    "client_addr": "0.0.0.0",
    "datacenter": "BlueBrick",
    "data_dir": "/opt/consul",
    "encrypt": "******************************************",
    "node_meta": {
        "meta": "data"
    },
    "retry_join": ["xxx.xxx.xxx.xxx"]
}
```
Client ACL config (acl.hcl)
```
acl {
  enabled = true
  default_policy = "deny"
  enable_token_persistence = true
}
```
There is no log for this issue.

**Comment by johncowen** [comment]
Hi @melhir 

Thanks for the ticket! Would it be possible for you to check the API response when you are seeing no metadata.

You can do this by looking in the Web Inspector in you browser, in the [Network] tab you should see the URL for 

```
/v1/internal/ui/node/<your node name>?dc=<your datacenter name>
```

![Screenshot 2020-05-19 at 11 16 28](https://user-images.githubusercontent.com/554604/82314988-85758c80-99c2-11ea-92f7-59568b725461.png)


If you see meta data in that response and you do not see it in the UI then we know this is a UI related issue or not. Although my initial thoughts are that it is potentially a permissions/ACLs issue.

Thanks!

**Comment by melhir** [comment]
Okay, you were right, I am not seeing any metas in response, but I don't understand why I am having this issue.

**Comment by mkeeler** [comment]
@melhir Have you set up agent ACL tokens? 

https://www.consul.io/docs/agent/options#acl_tokens_agent

Each Consul agent will need its own token for updating its service registration which includes setting node metadata. The initial node registration is made on behalf of the agent by the leader server in response to joining the gossip pool. This initial registration is done without ACLs and its expected that a gossip encryption key be used to ensure only trusted parties can join the cluster and initiate this auto-registration. It appears from your configuration that you have already set this up, so I believe all you need to do is configure the agent token if to allow `node:write` on the node name of the agent and then it should work.

**Comment by melhir** [comment]
Okay, I've added token to the acl.hcl and metadatas showed up, thank you for your help :).

**Comment by johncowen** [comment]
Sounds like this is resolved @melhir ? Feel free to reopen if not. I'm going to close this for now. Thanks!
