### ISSUE TITLE
Allow verification of server capabilities via TLS SAN

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#792]
Currently we do not depend on the hostname verification features of TLS, since they don't make much sense in the case on Consul internal traffic (e.g. we are doing IP based not DNS based, as Consul typically is the DNS server). This means we do not use hostnames or SANs. Instead we can overload this to do verification of nodes and their ability to become a server.

As discussed on this thread: https://groups.google.com/forum/#!topic/consul-tool/3kPrS0yu4k0
If a Consul client is currently compromised, it can be restarted in server mode. Once added to the Raft replication group, all the data will be replicated and stored on disk. An attacker could then just read the contents of disk to recover any information about the cluster.

The reason this is possible is that the distinction between a client and server is managed by the gossip layer, which uses symmetric encryption. This provides confidentiality and integrity but does not provide a mechanism to separate ability or authorizations. This means any node can simply declare that it is a server.

To work around this, we should add a new config, `verify_servers` or equivalent, that enables hostname validation when connecting to servers. This would require the servers have a TLS certificate that is valid for a specific name like: "server.node.<datacenter>.<domain>". This way, even if a client node was compromised and switched to server mode, the TLS validation would fail, preventing any of the servers from replicating data to the node.

**Comment by mfischer-zd** [comment]
If the node were compromised, what's to stop the attacker from generating and installing a replacement TLS certificate that meets the hostname requirements?

**Comment by armon** [comment]
@mfischer-zd At that point, it means the attacker also has access to the keys of the certificate authority as well. Access to just the client side public/private keys are not enough to forge a new key signed by the CA.

**Comment by mfischer-zd** [comment]
So to clarify, not only would there be hostname verification (not based on the DNS name, but some name pattern that is unique to servers), but also that new certificate must also be signed by the expected CA.  Correct?

**Comment by armon** [comment]
@mfischer-zd The same certificate authority would be used that exists now. The `ca_file` configuration currently allows you to specify the CA used to validate the certs. https://consul.io/docs/agent/options.html#ca_file

So the only real change is that outgoing requests to servers would validate the hostname against a specific pattern.

**Comment by pforman** [comment]
This is a blocker for us adopting Consul, for the reasons outlined in the mailing list.  I'd imagine it's a problem for some other organizations as well.  Having the privilege escalation would flatten out our network security, making our DMZs ineffective.

Thanks for looking into this and the quick response!

**Comment by ketzacoatl** [comment]
+1 on the severity of this, and the reluctance in adopting consul for a security-conscious environment.

@armon, A question to clarify on the CA/TLS proposal, would it be possible to validate the server/client certs independently, or is this an illusion of security?

I also like the idea of having separate shared secrets for server-to-server vs agent/server communication (servers would have both keys, agents would not have the key used for server to server configuration). Does this make sense to consider?

**Comment by fazy** [comment]
+1 and thanks @armon for raising the issue and all the discussion.

**Comment by armon** [comment]
@ketzacoatl I'm not sure quite what you mean by the server vs client cert validation. Both must be signed by a trusted CA (or multiple different CAs). The difference is that server certificates would contain additional data to distinguish them.

I'm not sure where this additional shared secret would come into play? Do you mean in the gossip protocol layer?

**Comment by ketzacoatl** [comment]
@armon. On my certs question, I think you answered it with _(or multiple different CAs)_.

On the shared secret, the thought is for there to be separate secrets used for servers who pass around updates to the directory, and agents which just read the directory.

**Comment by armon** [comment]
@ketzacoatl I'm not sure the shared secret adds any more security here, but just additional complexity for the user.

**Comment by ketzacoatl** [comment]
@armon, If it is optional (servers could have same secret as agents, or a unique secret), the user is not inhibited. If an agent is compromised, they need to get the server secret (along with generate a cert with the right CA) before they can impersonate a consul server. What do you see that is not reasonable?

**Comment by armon** [comment]
Sorry I meant users of Consul / operators. Not clients of the system. This proposal protects against impersonation of servers already, so the secret key seems like a redundant mechanism that doesn't protect against any additional cases.
