### ISSUE TITLE
500 (The backend responded with an error)

### ISSUE THREAD

**Issue by yagashiraevil** [hashicorp/consul#7927]
I setup vault with consul cluster in AWS using Terraform. they set up ran for a month and all the sudden it starts giving me an error. 
500 (The backend responded with an error)
Consul 1.7.2
Vault v1.4.0

2 vault servers 
2 consul servers.

initial diagnosis suggests that no leader is selected.
##consul operator raft list-peers -stale
Error getting peers: Failed to retrieve raft configuration: Unexpected response code: 500 (No cluster leader)
## consul members
Node                 Address             Status  Type    Build  Protocol  DC         Segment
i-073a14454e1789f6f  172.31.2.238:8301   alive   server  1.7.2  2         eu-west-3  <all>
i-0ca6511481c563e8e  172.31.42.142:8301  alive   server  1.7.2  2         eu-west-3  <all>
i-000e40b72ddc95924  172.31.30.128:8301  alive   client  1.7.2  2         eu-west-3  <default>
i-0ffc15ccd24faf9af  172.31.12.115:8301  alive   client  1.7.2  2         eu-west-3  <default>

web browser shows below 

![image](https://user-images.githubusercontent.com/26820733/82415588-2e3eed00-9a92-11ea-947b-7585626d8253.png)

with console

![image](https://user-images.githubusercontent.com/26820733/82415886-9f7ea000-9a92-11ea-8316-310ce324cd6e.png)

Network tab
![image](https://user-images.githubusercontent.com/26820733/82416000-cd63e480-9a92-11ea-8ec2-1db3d69b3945.png)

I restart all the servers that didn't help

**Comment by jsosulska** [comment]
Hi @yagashiraevil ,

Thanks for posting, and sorry you're running into problems with your deployment. For questions like this, I recommend posting on our [Forum](https://discuss.hashicorp.com/c/consul/29). I've posted the answer [here](https://discuss.hashicorp.com/t/unexpected-response-code-500-no-cluster-leader/8967)

I hope this helps.
