### ISSUE TITLE
consul maint -service=<ServiceID with wildcard>

### ISSUE THREAD

**Issue by sielaq** [hashicorp/consul#793]
Hello,

Sometimes I got containers with one app which expose multiple ports like (for ex. http / ajp), or even more...

All backends are register by Registartor (one service name with different tags) .
so I can get easily get  for example only http backends or only ajp etc.

Problem I got with maintenance mode.
First of all I have no direct knowledge how ports are mapped - so I have to "calculate" them,
second of all I have to put into maintenance every exposed port.

Since ServiceID contains <container_id> so what is different is just the last part - port - like:

```
service:paas44-1-registrator:mesos-0ea21b49-d322-4b04-ae42-d1982288dc2d:8080
service:paas44-1-registrator:mesos-0ea21b49-d322-4b04-ae42-d1982288dc2d:8009
```

It would be much easier to do it with one command,
all container would go into maintenance mode, at once, 
without thinking which ports are exposed.

sth like:

```
consul maint -http-addr=${consul}:8500 -service="paas44-1-registrator:mesos-0ea21b49-d322-4b04-ae42-d1982288dc2d:*"
```

this would be awesome!

**Comment by ryanuber** [comment]
@sielaq Thanks for opening this. Tagged as an enhancement!

**Comment by i0rek** [comment]
@sielaq Thanks again for opening this! This issue has been around for some time and given the fact that we did not implement it, I don't think it is likely that we are doing it in the future. If you or someone else wants to contribute a PR, I would be happy to review it.
