### ISSUE TITLE
Bulk upload key-value props under a prefix

### ISSUE THREAD

**Issue by sudiptasish** [hashicorp/consul#7951]
Is your feature request related to a problem? Please describe.
Today the conventional consul http PUT endpoint takes a single value and upload it against a key. It would be nice to have a bulk upload API.

Describe the solution you'd like
To give you an example, I am looking something like below:
Here is my config file, tmp.props :

```
[
   {
     "key": "thread/pool/size",
     "value": "20"
   },
   {
     "key": "thread/pool/name",
     "value": "core_pool"
   },
   {
     "key": "thread/pool/group",
     "value": "group_1"
   }
]
```
The below command should create the the new keys underneath the prefix "ecm".
curl -X PUT http://localhost:8500/v1/kv/ecm --data-binary @./tmp.props

However, today it is storing the complete file as a blob. Which is fine as it serves my other use case, where I want my (json) file to be stored as a blob. However, for files in above format (simple key-value pair), it would be nice to provide an option, so that instead of storing the entire file content as a blob, it can actually create complete key hierarchy.

Something like: curl -X PUT http://localhost:8500/v1/kv/ecm?**recurse** --data-binary @./tmp.props

To be precise, I am looking for an http version of the below command:
`./consul kv import @tmp.props`

**Comment by mkeeler** [comment]
@sudiptasish have you seen the Txn APIs?

https://www.consul.io/api-docs/txn#create-transaction

You can set multiple keys in the same transaction that way?

**Comment by sudiptasish** [comment]
Thank you @mkeeler . Does it maintain the atomicity and consistency ?

E.g if I am updating the above 3 properties via the /v1/txn API, and client is trying to read all 3 the  properties at the same time. Is it possible that client may end up getting the some inconsistent data?

**Comment by mkeeler** [comment]
Yes, the Txn APIs perform all the requested operations in a single raft/memdb transaction any errors writing one key will result in a rollback of all. Also any blocking queries on the keys will not fire until until the transaction is complete so no intermediate state will be seen.

**Comment by sudiptasish** [comment]
Btw, I was trying out this API. Seems to be working fine. 
Does it have any limit in terms of number of key-value pair that one can specify in the payload?

**Comment by sudiptasish** [comment]
That sound interesting "... any blocking queries on the keys will not fire until the txn is complete ....." .
Can you send me the url for blocking KV queries ?

**Comment by mkeeler** [comment]
The max number of operations in a request is 64: https://github.com/hashicorp/consul/blob/85b20d371396feecd310600b8c7d60aa1c532dbd/agent/txn_endpoint.go#L19

Tha max aggregate request size is 512 KB. 

As for the docs blocking queries are done using the typical KV APIs. 

https://www.consul.io/api-docs/kv#read-key

Generic blocking query docs are here: https://www.consul.io/api-docs/features/blocking
