### ISSUE TITLE
[1.8.0-beta1] Unable to create intention,  Invalid query parameter: "ns"

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#7952]
## Setup

Consul v1.8.0-beta1 (439d148fb)  
ACL's enabled  

I've installed consul 1.8.0-beta1 on a single node and enabled ACLs and bootstrapped the ACL system. I am using the boostrap token in the GUI. 

When navigating to the 'intentions' page, it returns a 404. In the logs I see the following error: 

```
[ERROR] agent.http: Request error: method=GET url=/v1/internal/ui/services?dc=home&ns=* from=192.168.1.108:54841 error="Bad request: Invalid query parameter: "ns" - Namespaces is a Consul Enterprise feature"
```

What I suspect is happening is the open source version of consul is hard coded to use namespaces which are only present in enterprise, Particularly this part in the url seems bizzar. `ns=* `

<img width="900" alt="Screenshot 2020-05-24 22 42 46" src="https://user-images.githubusercontent.com/242382/82778878-e57b9100-9e0f-11ea-9a35-3ecbd7478602.png">

This appears to only the a problem in the gui, since I can create intentions from the command line. 

```
consul intention create foo bar
Created: foo => bar (allow)
```

But I can't view any intentions (including those created from the command line) without getting the 404

**Comment by spuder** [comment]
Possibly duplicate of https://github.com/hashicorp/consul/issues/7896
Fixed in beta2

**Comment by johncowen** [comment]
Hey @spuder ,

Sorry about this! It is indeed a dupe of #7896 and was fixed in beta2.

Thanks for taking things for a spin though! 👍
