### ISSUE TITLE
Make session TTL limits configurable

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [hashicorp/consul#796]
We would like to be able to configure the minimum Session TTL rather than have it be hardcoded to 10s (although it could default to 10s if a minimum value isn't explicitly passed in).  This would be a command line flag as well as a config file option.  Specifically, we have several automated tests where we spin up a local consul cluster and test behaviour around locks being acquired and released, and don't want to have to wait for things to happen on a 10s time scale.

Would you all support a pull request for this feature?

For symmetry the maximum TTL could also be made configurable if that's desirable.

Thanks,
Amit + @ematpl

**Comment by armon** [comment]
@Amit-PivotalLabs I'd be open to a PR that allowed min/max values to be configurable. I'd avoid adding a CLI flag, since it's a very advanced tuning parameter that most people should not touch.

**Comment by Amit-PivotalLabs** [comment]
Okay, so config file settings only?

**Comment by armon** [comment]
@Amit-PivotalLabs Yep!

**Comment by ryanuber** [comment]
Fixed by #821.
