### ISSUE TITLE
consul lock should pass TERM signals to its children

### ISSUE THREAD

**Issue by osheroff** [hashicorp/consul#797]
I'm trying to use `consul lock` to run a singleton process via runit, and I'm running an issue where `consul lock` leaves its children running when it gets a TERM signal.  Here's a simplified repro:

```
ben@descartes1:$ consul lock foobashery /bin/sleep 10d

ben@descartes1:~$ ps fx
  PID TTY      STAT   TIME COMMAND
 7494 ?        S      0:00 sshd: ben@pts/4
 7496 pts/4    Ss     0:00  \_ -bash
17766 pts/4    Sl+    0:00      \_ consul lock foobashery /bin/sleep 10d
17771 pts/4    S+     0:00          \_ /bin/sleep 10d

ben@descartes1:~$ kill 17766
ben@descartes1:~$ ps fx
  PID TTY      STAT   TIME COMMAND
...
17771 pts/4    S      0:00 /bin/sleep 10d
```

this seems like counter-intuitive behavior, I would have presumed that consul lock would have killed off the child and then released the lock upon TERM...

**Comment by mfischer-zd** [comment]
What happens if a SIGINT is received?  See https://github.com/hashicorp/consul/blob/master/commands.go#L144 - it looks like they need to handle SIGTERM there as well.

**Comment by armon** [comment]
Yep, we should catch SIGTERM as well. Tagged for enhancement!
