### ISSUE TITLE
技术无国界

### ISSUE THREAD

**Issue by simsq** [hashicorp/consul#7975]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by Zeady** [comment]
6666

**Comment by jetaime-chen** [comment]
777

**Comment by dbv** [comment]
888

**Comment by OPSTime** [comment]
666

**Comment by egmkang** [comment]
999

**Comment by OPSTime** [comment]
这也很可能是西方人推广的一种手段
采用不齿的手段 无所不用其极 原始人一样

**Comment by bubbleatgit** [comment]
```
Before you download and/or use our enterprise software for evaluation purposes, you will need to agree to a special set of terms (“Agreement”), which will be applicable for your use of the HashiCorp, Inc.’s (“HashiCorp”, “we”, or “us”) enterprise software.
```

这些的 `our enterprise software for evaluation purposes`，说的意思是不能下载和使用他们的企业软件进行评估。 这个企业软件指的是 HaschiCorp 这家企业的软件，还是企业版的软件。。。

**Comment by qiangmzsx** [comment]
你们这帮人，说的是企业版，又不是开源版。
ou people, you're talking about the enterprise version, not the open source version.

**Comment by chennqqi** [comment]
大家散了吧

**Comment by runbird** [comment]
why ??? 
PLEASE NOTE THAT THE SOFTWARE MAY NOT BE USED, DEPLOYED OR INSTALLED IN THE PEOPLE’S REPUBLIC OF CHINA.

**Comment by chennqqi** [comment]
@simsq 结贴吧 @runbird 你分得清楚啥是开源软件，啥是商业软件吧。

**Comment by jsosulska** [comment]
Hello. 
If this is a question, please post on our discuss forum, and our community will be able to help :) If you are running into issues with Consul open source, please open a new issue with a way to replicate the issue, and detailed configurations. If you are an Enterprise user, please reach out to your technical account manager.

Sorry for inaccuracies in the translation
----------------------------------------------------
你好。
如果有問題，請在我們的論壇上發帖，我們的社區將能夠為您提供幫助：)如果您遇到Consul開源的問題，請以復制問題和詳細配置的方式打開新問題。 。 如果您是企業用戶，請與您的技術客戶經理聯繫。

對不起，翻譯不准確
