### ISSUE TITLE
别飘啊，咋就搞政治风向了

### ISSUE THREAD

**Issue by AviorAlong** [hashicorp/consul#7976]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by qiangmzsx** [comment]
ou people, you're talking about the enterprise version, not the open source version.
