### ISSUE TITLE
Will the Terms of Evaluation for HashiCorp Software at https://www.hashicorp.com/terms-of-evaluation affect the use of the open source version of consul in China?

### ISSUE THREAD

**Issue by Mstch** [hashicorp/consul#7979]
Will the “PLEASE NOTE THAT THE SOFTWARE MAY NOT BE USED, DEPLOYED OR INSTALLED IN THE PEOPLE’S REPUBLIC OF CHINA.” at “Terms of Evaluation for HashiCorp Software”at https://www.hashicorp.com/terms-of-evaluation affect the use of the open source version of consul in China?

**Comment by jsosulska** [comment]
Hello,

I will need to follow up on this with other teams. I'll update here when there is more information.

**Comment by Mstch** [comment]
thank you

**Comment by jsosulska** [comment]
Hi @Mstch , and anyone else who follows this topic in the future!
The ToE is currently in the process of being updated to more clear language. Apologies for the confusion! 

The ToE explicitly states that it applies to the Enterprise versions of our Software, so this does NOT affect Consul Open Source software at all. Consul can be evaluated, deployed, and operated by users in all regions. This applies to both OSS and ENT.

I hope this helps clarify the situation around the ToE

**Comment by Mstch** [comment]
OK ,Thank you for yuor reply
