### ISSUE TITLE
Setting acl_default_policy=deny and acl_token with write permissions, completely bypasses any security for services and nodes.

### ISSUE THREAD

**Issue by rockymtnlinux** [hashicorp/consul#798]
For consul v0.5.0,  I'm using the following acl config:

```
{
           "acl_datacenter":"dtc1",
            "acl_default_policy":"deny",
            "acl_down_policy":"extend-cache",
            "acl_token":"agent_token",
}
```

where "agent_token" has the following policy:

```
service "" {
    policy = "write"
}
```

It is still possible, not only to list the nodes and services, but to register and deregister them using either no token ( anonymous ) or a token that doesn't have the correct read or write policies set.

If the agent token's policy isn't set or is set to "deny", then requests using other tokens ( including the master token ), are denied.

This probably also is a consequence of issue #734 where the client token isn't passed through to the catalog.

With "acl_token" not set and the default policy set to "deny",  I was not only able to registers/deregister services but was also able to deregister my node and its services with:

```
curl -X PUT -d '{ "Datacenter":"dtc1","Node":"node_name"}' http://localhost:8500/v1/catalog/deregister
```

I'm assuming that when acl_default_policy is set to "deny", an agent token should allow the agent to communicate with the rest of the cluster and to register/deregister the node,consul service, and the default service check.  It probably shouldn't allow access to any of the HTTP API end points beyond what is needed for the acl system specifically and consul in general to be functional.  Only clients with an appropriate token and policy should be allowed to read/write the list of services/nodes as well as the key/value info.  Unfortunately, if I remove acl_token from the config, then clients with tokens are unable to register/deregister services. ( issue #734 ).

**Comment by armon** [comment]
This is rather strange... This behavior sounds like the ACL system is not enabled. Can you confirm that all these settings were present on the servers, and that they were hard restarted ("reload" cannot currently handle toggling ACL availability).

**Comment by rockymtnlinux** [comment]
After encountering issue #734 and reading issue #754, I added the agent token, configured the acl_token property for each server and shutdown and restarted all of the servers in my cluster.   That's when I noticed that, with the acl_token configured and given write privileges, I was able to register/deregister not only services but the nodes themselves when using the agent endpoints.  It didn't matter what token I used.  Likewise, if the agent token wasn't given write privileges, even the "master token" wasn't able to write service info ( I don't think I tried deregistering the node in that case. ).  I also used a single test node where I restarted it after every change to verify what I was seeing.

**Comment by armon** [comment]
I'm having a hard time understanding exactly what the issue is here. Could you provide a repro case? I'm not sure if this is a duplicate bug or something else entirely

**Comment by rockymtnlinux** [comment]
1) Create a directory structure: 
```
mkdir -p /consul/{bin,data,dist,etc}
```
2) Download and copy the latest consul into /consul/bin.  Copy the web-ui code into /consul/dist.  Although, if you know the HTTP API, you probably don't need the web-ui.
3) Create a consul config file ( /consul/etc/consul.json ):
```
{
    "acl_datacenter":"dc1",
    "acl_default_policy":"deny",
    "acl_down_policy":"extend-cache",
    "acl_master_token":"the_one_ring",
    "acl_token":"15b93aea-165a-4b7b-99c1-22353259a864",
    "bootstrap_expect":1,
    "datacenter":"dc1",
    "data_dir":"/workspace/consul/data/",
    "server":true,
    "ui_dir":"/workspace/consul/dist"
}
```
4) Startup the consul agent:
```
/consul/bin/consul agent -config-file=/consul/etc/consul.json
```
5)  Using the master token, create client tokens called `agent_token` and `client_token`.  Give both tokens the following policy:
```
service "" {
    policy = "write"
}
```
6) Using the client_token uuid, try to register a service.  You'll run into Issue #734.
```curl -X PUT -d '{"Name":"Test Service","Port":8080}' "http://localhost:8500/v1/agent/service/register?token=dfd1569c-9f98-8b25-6e86-518e22d8dafa"
```
7) Remove the policy from the client_token so that is using the default of "deny".
8) Stop the consul agent.
9) Edit the config file and configure the acl_token property to use the uuid for the agent_token:
```
    "acl_token":"8926c1a8-e596-9576-78aa-cc5ab4b2676a",
```
10) Restart the consul agent.
11) Register a test service anonymously and verify that it exists.
```
> curl -X PUT -d '{"Name":"Test Service","Port":8080}' "http://localhost:8500/v1/agent/service/register"
> curl "http://localhost:8500/v1/agent/services"
{"Test Service":{"ID":"Test Service","Service":"Test Service","Tags":null,"Address":"","Port":8080},"consul":{"ID":"consul","Service":"consul","Tags":[],"Address":"","Port":8300}}
```
12) Deregister the service anonymously
```
> curl "http://localhost:8500/v1/agent/service/deregister/Test%20Service"
> curl "http://localhost:8500/v1/agent/services"
{"consul":{"ID":"consul","Service":"consul","Tags":[],"Address":"","Port":8300}}
```
13) Deregister the node anonymously
```
> curl -X PUT -d '"Node";"node.domain","Address":"1.2.3.4"}' 
"http://localhost:8500/v1/catalog/deregister"
> curl "http://localhost:8500/v1/catalog/nodes"
[]
```
13) Repeat steps 11 and 13 using the client token.   

The bug is this:  With the default policy set to "deny", a client should neither be able to read or modify  services ( and nodes ).  However if the agent is configured with it's own token, then anybody, whether using a token or not, can access whatever the agent can access.   While I think you might want the agent to have a certain set of permissions in order to function, particularly within a cluster,  I'm not sure those permissions should extend to a client.

**Comment by armon** [comment]
@rockymtnlinux So I think this is a few different issues being conflated together. Issue one is that the agent's local service representation is distinct from the global catalog. You can register a service via `/v1/agent/service/register` but that may be blocked from the global catalog. We are planning on adding a pre-flight check so that the local agent registration will fail too, but from the perspective of the cluster, that service has not been registered.

The second issue is that you cannot currently do per-registeration token overrides. (See #734). Instead, only the agent ACL is used. So in this example the `client_token` is being completely ignored. That will be addressed shortly.

Lastly, with 0.5 the ACL system only protects registration of services, not discovery. That is a roadmap item for 0.6, so it is expected that you can read all of the services currently.

I hope that helps clarify!

**Comment by rockymtnlinux** [comment]
Thanks for the explanation.  I had actually seen the 1st issue, but hadn't put it together in this context.  The second issue I'd obviously seen, and I'm glad to know that the 3rd is on the road map.  Is there an ETA on when 0.6 will be out?  I'm very much interested in implementing consul but need to be able to add extra security beyond depending on just firewalls.

**Comment by tillig** [comment]
**Does this apply to the key/value store as well?** I just ran into this trying to lock down read access to the key/value store - if the agent has an `acl_token` (say, so it can register service checks via configuration at startup) then anonymous requests using the HTTP API through that agent end up using the agent's token and end up with access they shouldn't.

If I remove the `acl_token` on the agent, I can't set up service checks via configuration (you get an error at startup) but then anonymous requests through the HTTP API actually obey the anonymous access policy.

Running v0.5.2 on Windows.

**Comment by armon** [comment]
@tillig You can instead of setting a `acl_token` for the entire agent now set the token for a per-service registration. This allows the service to be registered without causing the anonymous HTTP requests to pickup the token.

**Comment by tillig** [comment]
@armon Is there some doc or an example showing how to specify a per-service `acl_token`? Do I just add an `acl_token` parameter to a [service definition](https://consul.io/docs/agent/services.html) when defining it in configuration?

**Comment by bluefeet** [comment]
I have a host with a Consul client agent running which has an `acl_token` defined in its configuration.  On this host I'd like a particular script to have management privileges.  So, when I interact with the local HTTP API I have this script configured to use the `master` token and make changes to ACLs.  The use of the master token is ignored and the script is treated as if it is using the token specified in the agent configuration.

Is this expected?  It seems very much similar to the issues reported in this thread.

Running Consul 0.7.0.

If this is expected, it seems like I'm required to run this script on a host who's local consul agent is configured with the master acl token.  Not what I had expected.

This also seems to be resolved if I remove the local consul agent's acl_token configuration.  If I do that requests to its HTTP API default to the anonymous token, but if I specify a token I actually get access at that token's level.

**Comment by slackpad** [comment]
Closing this out - we've added complete ACL coverage (including the /v1/agent APIs) in Consul 0.8.x, and we've also cleaned up CLI commands and HTTP endpoints for their handing of ACL tokens.
