### ISSUE TITLE
在政治面前，开源协议就是纸老虎zz

### ISSUE THREAD

**Issue by yuanmengqing** [hashicorp/consul#7994]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl ...`
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by yuanmengqing** [comment]
在政治面前，开源协议就是纸老虎zz

**Comment by yuchen001** [comment]
你们真不容易，又跑来这儿用简体中文拉屎了。

**Comment by wizardforcel** [comment]
开源协议本来就是君子协定啊，你可以撕那我也可以撕啊。

才知道啊。

**Comment by jsosulska** [comment]
这里已经回答了：
https://github.com/hashicorp/consul/issues/7979

**Comment by royorange** [comment]
能分清开源版和企业版吗？

**Comment by jsosulska** [comment]
Hi @royorange

Instructions for installing the enterprise version of consul can be found [here](https://www.consul.io/docs/enterprise#licensing). This has a list of most of the features with links on more details.

I apologize if the translation is poor
-----
嗨@royorange

可以在 [here](https://www.consul.io/docs/enterprise#licensing）中找到有关安装consul企业版的说明。 其中列出了大多数功能，并提供了更多详细信息的链接。

如果翻译不好我很抱歉
