### ISSUE TITLE
consul lock executes new handler during shutdown

### ISSUE THREAD

**Issue by kazeburo** [hashicorp/consul#800]
I found consul lock executes new handler after receiving SIGINT. Here is log of consul_lock.

```
[2015-03-19T11:03:39] Shutdown triggered, killing child
[2015-03-19T11:03:39] No child process to kill
[2015-03-19T11:03:39] Starting handler '/usr/local/bin/foo args'
[2015-03-19T11:03:39] Cleanup succeeded
```
The handler that was executed during shutdown phase remains after consul lock ended.

**Comment by armon** [comment]
Yikes! Tagged as bug!

**Comment by babbottscott** [comment]
Issue appears to be https://github.com/hashicorp/consul/blob/master/command/lock.go#L140-L141

If c.ShutdownCh signals, lu.lockFn (Lock) will return 'nil, nil' (https://github.com/hashicorp/consul/blob/master/api/lock.go#L156).  This should be instead something like:
```
if lockCh == nil {
  if err != nil {
     c.Ui.Error(fmt.Sprintf("Lock acquisition failed: %s", err))
     return 1
  } else {
    c.Ui.Info("Shutdown triggered before lock acquisition")
    return 0
  }
}
```

**Comment by babbottscott** [comment]
Also 'return code of 1 for all error states' may be something that could use enhancement.

**Comment by babbottscott** [comment]
Bump:  really needing this one squashed.

**Comment by mfischer-zd** [comment]
Unfortunately #1080 didn't fix this bug.  However it did improve the messaging, so it's still useful.

#1158 should fix it completely.
