### ISSUE TITLE
Ingress gateway - path based routing

### ISSUE THREAD

**Issue by pvyaka01** [hashicorp/consul#8018]
#### Feature Description

Currently as documented for ingress gateway, we can add multiple listeners. This request is to allow path based routing - for example: 
http://<ip>:<listenport>/api_service1, http://<ip>:<listenport>/api-service2 

instead of
http://<ip>:listenport1 , http://<ip>:listenport2 

Host headers is not an option for existing apps.

#### Use Case(s)

How can we expose multiple ports within a single service in k8s? If there is a good option, can you pls let me know? We're trying to connect to multiple k8s microservices from outside (legacy apps). Not sure if using this is the right approach or if you all suggest something else.

Thank you!

**Comment by pvyaka01** [comment]
Thank you, will try it out!

**Comment by pvyaka01** [comment]
yes, seems to work fine. Thank you!

**Comment by jay-manday** [comment]
this issue explored EXACTLY what i've been trying to wrap my head around as well. more documentation on this front would be killer, thanks.

**Comment by ericbrumfield** [comment]
@crhino Thank you for your example, this really needs to be an example in the documentation as I had a hunch this was a possibility to achieve with the new features but it was not clear anywhere how to apply L7 routing rules like this at the ingress gateway.  This was exactly what I needed and can now most likely ditch/kill our use of Traefik.
