### ISSUE TITLE
Not working on Solaris 64-bit sparcv9

### ISSUE THREAD

**Issue by Srini59** [hashicorp/consul#8030]
Hello,

When i try to install latest version/even tried older version too of Consul (consul _1.7.3_solaris_amd64.zip) on one of my solaris 64-bit sparcv9 system getting below error msg.

"---login: /usr/local/bin/consul:Invalid argument "

Could someone help me understanding the issue ?
Or solaris_amd64.zip pig won't support sparc systems ??

**Comment by mkeeler** [comment]
@Srini59 Consul and the Go programming language do not support Solaris with the Sparc CPU architecture.

https://golang.org/doc/install/source#environment

It doesn't even officially list solaris/amd64 there but Consul does support that os/arch combination.
