### ISSUE TITLE
Does this end point /acl/policy/name/:name work ?

### ISSUE THREAD

**Issue by sudiptasish** [hashicorp/consul#8032]
The end point /v1/acl/policy/name/node-read is failing with below error:

rpc error making call: failed acl policy lookup: index error: UUID must be 36 characters

**Comment by mkeeler** [comment]
@sudiptasish It does work but was added pretty recently in v1.7.3. If you are running a version of consul prior to that then you will see that error.

**Comment by jsosulska** [comment]
Hello, @sudiptasish ,

I am closing this question due to inactivity. Please comment if this is an issue with 1.7.3 or later.
