### ISSUE TITLE
Can’t connect to consul in dev mode without network_mode: host

### ISSUE THREAD

**Issue by Zlobin** [hashicorp/consul#8046]
Hello.

I’m using consul in docker-compose, which looks like this. Before, I created my own network:
`docker network create -d bridge --subnet 172.25.0.0/16 mynetwork`

```
  consul_master:
    image: consul:1.8.0-beta2
    container_name: containerConsul
    network_mode: mynetwork
    command: [
      "agent",
      "-dev",
      "-http-port=8000",
    ]

  ms_auth:
    image: <someimage>
    container_name: containerMS
    network_mode: mynetwork
```

this is ms_auth - nodejs app

```
import * as consul from 'consul';

  const consulApp = consul({
    host: 'containerConsul',
    port: 8000,
  });

  consulApp.catalog.node.list((err, result) => {
    // Here I have an error
  });
```

```
Error: connect ECONNREFUSED 172.25.0.2:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '172.25.0.2',
      port: 8000
    }
```

But when I’m changing network_mode: to host for both consul and my app, everything is working as expected. Could you please help me what to do to work consul with ms in one network without host mode

**Comment by mkeeler** [comment]
@Zlobin There are a couple things here. First is that you probably need to have docker expose the http port outside of the container network.

It looks like you are using docker compose here so the syntax would look something like so:

```
 ports:
    - "8000:8000"
```

A secondary issue is that Consul is going to be binding the "client" addresses to 127.0.0.1. This is probably not what you want. You could set `-client 0.0.0.0` to bind to all addresses within the container or even use a go-sockaddr template like: `-client "{{ GetInterfaceIP \"eth0\" }}"`. That template will bind to whatever IPv4 address is assigned to the eth0 device.

**Comment by Zlobin** [comment]
@mkeeler, maaan! thank you!
"-client=0.0.0.0" helps me
