### ISSUE TITLE
Documentation: Rendering errors for "Server Performance" page

### ISSUE THREAD

**Issue by boldandbusted** [hashicorp/consul#8049]
Sorry to post this as a "bug", but I see no other more relevant place for documentation rendering bugs... And I'm sorry for posting outside the posting guidelines, but, again, this isn't a "consul" code bug. Please don't hate me.

So, this is how this paragraph is rendered on the Consul Docs pages:

![Screen Shot 2020-06-08 at 11 20 52 AM](https://user-images.githubusercontent.com/879972/84049364-58414c00-a97a-11ea-9116-3dcbf347f1cb.png)

<div>Spurious leader elections can be caused by networking issues between the servers or insufficient CPU resources. Users in cloud environments often bump their servers up to the next instance class with improved networking and CPU until leader elections stabilize, and in Consul 0.7 or later the [performance parameters](/docs/agent/options#performance) configuration now gives you tools to trade off performance instead of upsizing servers. You can use the [`consul.raft.leader.lastContact` telemetry](/docs/agent/telemetry#last-contact) to observe how the Raft timing is performing and guide the decision to de-tune Raft performance or add more powerful servers.</div>

In Markdown, as viewed on Github, it renders as I think it was intended:

"Spurious leader elections can be caused by networking issues between the servers or insufficient CPU resources. Users in cloud environments often bump their servers up to the next instance class with improved networking and CPU until leader elections stabilize, and in Consul 0.7 or later the performance parameters configuration now gives you tools to trade off performance instead of upsizing servers. You can use the consul.raft.leader.lastContact telemetry to observe how the Raft timing is performing and guide the decision to de-tune Raft performance or add more powerful servers."

Ref: https://github.com/hashicorp/consul/blob/master/website/pages/docs/install/performance.mdx

Hope this helps. Cheers.

**Comment by blake** [comment]
Thanks for reporting this, @boldandbusted. I opened a PR which resolves the rendering issue (#8050).
