### ISSUE TITLE
Consul Client Memory Leak 

### ISSUE THREAD

**Issue by kpurdon** [hashicorp/consul#8051]
#### Overview of the Issue

I'm seeing patterns of memory usage on the client that indicate a memory leak.

<img width="619" alt="Screen Shot 2020-06-08 at 10 41 07 AM" src="https://user-images.githubusercontent.com/5130441/84061427-2086d400-a97b-11ea-8dae-4dbd9cf37658.png">

#### Reproduction Steps

1. Create a Private GKE Cluster (maybe not relevant)
2. Deploy Consul via Helm (v 1.7.3)
3. Register services using the injector (we have 2 services currently ~10 pods)
4. See client memory usage grow until it hits a limit (set in Helm chart) and restarts, dropping memory back to normal, then growing again.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 6
	services = 6
build:
	prerelease =
	revision = 8b4a3d95
	version = 1.7.3
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 16
	goroutines = 347
	max_procs = 16
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 9
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 433
	members = 15
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 8b4a3d95
	version = 1.7.3
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.12.1.35:8300
	server = true
raft:
	applied_index = 2592258
	commit_index = 2592258
	fsm_pending = 0
	last_contact = 0
	last_log_index = 2592258
	last_log_term = 26
	last_snapshot_index = 2582551
	last_snapshot_term = 26
	latest_configuration = [{Suffrage:Voter ID:372100d2-9083-7de2-3d1d-ffddb0912c0a Address:10.12.5.136:8300} {Suffrage:Voter ID:e3bbb10e-6ad9-1ebf-7bff-0ddfd3cf77dc Address:10.12.1.35:8300} {Suffrage:Voter ID:50438c36-ce2d-5072-0e07-bb093b2d2a6f Address:10.12.0.62:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 26
runtime:
	arch = amd64
	cpu_count = 16
	goroutines = 239
	max_procs = 16
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 9
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 1
	member_time = 433
	members = 16
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 87
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

GCP + Private GKE (1.16.8-gke.15) + Helm3 + Consul 1.7.3

### Log Fragments

[logs.zip](https://github.com/hashicorp/consul/files/4747555/logs.zip)

**Comment by jsosulska** [comment]
Hi @kpurdon ,

Thanks for posting! Would you mind posting this in the [consul-helm](https://github.com/hashicorp/consul-helm) github issues page? Please also include the values.yml file that you are using, as that will help the team over there with reproducing the issue, and you will likely get a faster response :)

Happy Coding!

**Comment by rrondeau** [comment]
Hi

I'm facing the same issue.

![image](https://user-images.githubusercontent.com/1677718/84365576-ed8a4d80-abd1-11ea-9513-75553be16ab6.png)
I'm using consul-helm with consul-k8s injector and i'm starting to think this is comming from the lifecycle mecanism which re-register the same service every 10s by default

**Comment by rrondeau** [comment]
I rebuilt consul-k8s without lifecyle sidecar injection.
Same graph 6 hours later :
![image](https://user-images.githubusercontent.com/1677718/84409712-0b75a380-ac0e-11ea-88fa-f01b2131e0dc.png)
Something is going on here :-)
