### ISSUE TITLE
Clearer documentation for session TTL

### ISSUE THREAD

**Issue by feldoh** [hashicorp/consul#8059]
#### Feature Description

I was caught out because the current docs on [https://www.consul.io/api/session.html](https://www.consul.io/api/session.html) claim:

> TTL (string: "") - Specifies the number of seconds (between 10s and 86400s)

A number of my colleagues and I interpreted the unit as not required. After all when docs claim something is in seconds adding "s" seems pointless and liable to cause a number parsing failure. 

This is in fact not a number of seconds but is meant to be a duration string parsed by the ParseDuration function and thus a unit is actively required except in the special edge cases of "0" and "".

#### Use Case(s)

Avoiding errors in user code through better documentation such as:

> Consul request failed with status [500]: rpc error making call: rpc error making call: Session TTL '180' invalid: time: missing unit in duration 180

**Comment by feldoh** [comment]
Sorry, I made the commit and failed to make a PR https://github.com/hashicorp/consul/pull/8141
Not sure why it's not linked

**Comment by jsosulska** [comment]
Hey @feldoh , Thanks for your contribution! :) GitHub gives you the ability to use [closing keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references), like `fixes #<issuenumber>`, and it will close the matching issue in the same repository.

You can also paste the link to the issue in the description at PR create time, and it will do the linking, as seen above :)

Happy Coding!
