### ISSUE TITLE
[1.8.0-beta2] Can not configure config_entries

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#8066]
Using consul 1.8.0-beta2 with the new ingress feature. 

## Problem

Kind is not a valid key for `config_entries` in the config file

---
According to the documentation, an ingress-gateway requires a 'configuration entry'. 

https://www.consul.io/docs/agent/config-entries

Valid configuration entry`Kind` values are: 

- ingress-gateway
- proxy-defaults
- service-defaults
- service-resolver
- service-router
- service-splitter
- terminating-gateway

When adding a config_entries to the /etc/consul/config.json, it returns error invalid
```
invalid config key config_entries.Kind
invalid config key config_entries.Listeners
```

```
  "acl": {
    "enabled": true
  }
  "config_entries": {
    "Kind": "ingress-gateway",
    "Listeners": [
      {
        "Port": 8080,
        "Protocol": "http",
        "Services": [
          {
            "Name": "*"
          }
        ]
      }
    ],
    "Name": "ingress-service",
    "TLS": [
      {
        "Enabled": false
      }
    ]
  },
  "connect": {
    "enabled": true
  }
}
```

Perhaps I'm misunderstanding how to configure an ingress-gateway, but it appears that the `config_entries` config option doesn't support `kind`. 

https://www.consul.io/docs/agent/options#config_entries

**Comment by dnephin** [comment]
Thank you for trying out the beta! It looks like our documentation could be improved in this area. There are a couple ways you can create the config entry. One is from a config file for a server agent. It looks like that is what you are doing in your example. To create a config entry from the config you would do something like this:

```json
"config_entries": {
  "bootstrap": [
    {
      "Kind": "ingress-gateway",
      "Name": "ingress-service",
      ...
    }
  ]
}
```

The other option is to create a config entry using the CLI (or API) with `consul config write FILENAME`.

**Comment by spuder** [comment]
Thank you. That does appear to be getting further. 


```
  "config_entries": {
    "bootstrap": [
      {
        "Kind": "ingress-gateway",
        "Listeners": [
          {
            "Port": 8080,
            "Protocol": "http",
            "Services": [
              {
                "Name": "*"
              }
            ]
          }
        ],
        "Name": "ingress-service",
        "TLS": [
          {
            "Enabled": false
          }
        ]
      }
    ]
  },
  "connect": {
    "enabled": true
  },
```

I'm encountering another issue but I will debug it in a separate github issue.

**Comment by freddygv** [comment]
Hi @spuder were you able to resolve the issue you were running into? Is there anything we could clarify?

**Comment by samsara-team** [comment]
> Thank you. That does appear to be getting further.
> 
> ```
>   "config_entries": {
>     "bootstrap": [
>       {
>         "Kind": "ingress-gateway",
>         "Listeners": [
>           {
>             "Port": 8080,
>             "Protocol": "http",
>             "Services": [
>               {
>                 "Name": "*"
>               }
>             ]
>           }
>         ],
>         "Name": "ingress-service",
>         "TLS": [
>           {
>             "Enabled": false
>           }
>         ]
>       }
>     ]
>   },
>   "connect": {
>     "enabled": true
>   },
> ```
> 
> I'm encountering another issue but I will debug it in a separate github issue.

For those who follow the recommendation - it's also required to wrap this into {}. Otherwise, consul fires another parsing error.
