### ISSUE TITLE
[1.8.0-beta2] Unable to set namespace in ingress-gateway

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#8069]
Troubleshooting setting up an ingress-gateway. In the documentation it says that you can specify a namespace. When I attempt to set the namespace to 'default' it gives this error
```
            "Services": [
              {
                "Name": "*",
                "Namespace": "default"
              }
```
```
consul[32139]: ==> config_entries.bootstrap[0]: 1 error occurred:
consul[32139]:         * invalid config key "Listeners[0].Services[0].Namespace"
consul[32139]:     2020-06-09T13:13:47.667-0600 [ERROR] agent: Reload config failed: error="1 error occurred:
consul[32139]:         * Failed to reload configs
consul[32139]: "
```

This _should_ be valid according to the documentation

https://www.consul.io/docs/agent/config-entries/ingress-gateway

```
  "config_entries": {
    "bootstrap": [
      {
        "Kind": "ingress-gateway",
        "Listeners": [
          {
            "Port": 8080,
            "Protocol": "http",
            "Services": [
              {
                "Name": "*",
                "Namespace": "default"
              }
            ]
          }
        ],
        "Name": "ingress-service",
        "TLS": [
          {
            "Enabled": false
          }
        ]
      }
    ]
  },
```

**Comment by freddygv** [comment]
Hi @spuder, thank you for opening this issue.

Are you using a Consul Enterprise build of the beta? Namespaces are not available in Consul OSS, and will lead to errors when the field is specified.

In other areas of the code the error message is explicit when using an Enteprise feature in OSS. We can look into having that also be the case with config entries provided in agent configuration.

**Comment by spuder** [comment]
I am using the OSS version. 
I have since removed this value. From a user experience standpoint I think it would be good to make the error consistent opposed to preventing consul from starting entirely.
