### ISSUE TITLE
Allow creation of api.Semaphore in non-default DC

### ISSUE THREAD

**Issue by tcolgate** [hashicorp/consul#808]
Hi,
  From the look of it, it's not possible to create a semaphore in a non-default DC. Perhaps SemaphoreOpts should support providing the underlying sessions rather than just the key name?

**Comment by armon** [comment]
@tcolgate This can be done currently by setting the `Session` in `SemaphoreOptions`

**Comment by tcolgate** [comment]
From what I could tell, that is a string name that would be looked up in
the current DC

**Comment by armon** [comment]
@tcolgate It is the actual Session ID value, not it's name. The Semaphore doesn't allow directly setting of the Datacenter, but you can create a client associated with any datacenter, and then use the Semaphore.

**Comment by tcolgate** [comment]
I'd missed the dc setting on the client and was using read write opts! No
probs. Thanks. Will close the ticket

**Comment by armon** [comment]
Resolved
