### ISSUE TITLE
Latest git tag for api/

### ISSUE THREAD

**Issue by sriyer** [hashicorp/consul#8097]
#### Feature Description

Tag requested for consul/api with the most recent changes to the api lib

#### Use Case(s)

The current tag that exists for api is 1.4.0, this does not have the most recent updates to consul/api for example on 1.7.4. 

the go.mod file consul/go.mod replaces the consul/api dependency with ./api which allows consul itself to use the latest api package however has a dependency to 1.4.0 which results in consumers of only the api package, having to use 1.4.0 which does not have the most recent and awesome additions to the api package.

Also, Since 1.7.x switches to a more stricter API construct, it is better if we could leverage the latest api library with our client code that talks to consul.

we have worked around this by using the CI release commit for 1.7.4 as a version on go.mod on our services

**Comment by mkeeler** [comment]
@sriyer We are in the middle of beta releases moving towards Consul 1.8.0 being released. Our usual approach is to only tag the API module during final releases and not betas/rcs.

Consul 1.7.4 didn't include any API changes which is why a new tag wasn't generated when we released it on Wednesday.

I wonder if we should be tagging the api module during beta/rc releases. The tag would be something like `v1.5.0-betaX`. Would that help you?

**Comment by sriyer** [comment]
thanks @mkeeler for looking into this.

I don't suppose 1.7.4 is a beta release, which at the moment is the greatest GA release on the consul repo

Looking at the api package on 1.7.4 i see differences to what's available on 1.4.0 of the api tag. 
eg : https://github.com/hashicorp/consul/blob/v1.7.4/api/acl.go#L670
isn't available on https://github.com/hashicorp/consul/blob/api/v1.4.0/api/acl.go

I was looking for the Fetch Policy by name on the api module and could not find it on 1.4.0 and that lead me to look at the 1.7.4 release of consul which had it, now, i could use 1.7.4's api package, however the conflicting mod references and the replace directives prevents us from doing that. 

It's no big deal to use a general HTTP client to make the API call :) however, it would be nice if there was an api tag that already wraps these.

**Comment by mkeeler** [comment]
hmm, right you are. Looks like we missed tagging the API module for that change.

**Comment by jsosulska** [comment]
Hello! A new version, [v1.5.0](https://pkg.go.dev/github.com/hashicorp/consul/api@v1.5.0?tab=doc) has been released. I will close this, as the new release should bring forward needed upgrades. If there are any issues, please open a new issue. Thanks!
