### ISSUE TITLE
Update force-leave documentation to reflect LAN vs WAN behavior

### ISSUE THREAD

**Issue by jsosulska** [hashicorp/consul#8100]
#### Overview of the Issue
Based on conversation found [here](https://groups.google.com/d/msgid/consul-tool/c2bcd98c-4653-46be-b322-3b96e9a0f28co%40googlegroups.com), the `force-leave` command needs to be clarified for how it handles LAN pool connections. Currently, `force-leave` does not handle WAN connections. 

This is a documentation PR related to #6582 
#### Reproduction Steps
- Run 2 DCs on 2 Docker networks, or have a WAN joined deployment of 2 DCs.
- Exec into Primary DC Server0
- On primary - `consul members --wan`
- In new terminal - Loop kill dc2
- On primary - Try running `force-leave`, `force-leave -prune` on nodes of secondary DC
- On primary - Deregister nodes with Curl

**Result: **
There is currently no way to remove the secondary DC from the serf WAN pool, when a primary DC loses connection to the secondary DC. Our docs say
“The force-leave command can be used to transition the "failed" nodes to a "left" state more quickly, as reported by consul members.”
This is not how the command currently works in the WAN pool context.

When running the force-leave and deregister workflows, the primary is unable to communicate with the secondary, and the workflow breaks. Because the servers can’t be reached, all transactions break. There is no way for the primary to tell its members “Forget this DC” unless the second DC is up. The only way for the primary DC to stop communicating to a failed DC is for the tombstone timeout to be reached, transitioning the entirety of nodes into a left state.

**Acceptance**
[] Documentation shows LAN capabilities of `force-leave` and notes WAN behavior.

**Comment by blake** [comment]
As of Consul 1.11.0, `force-leave` now accepts a `-wan` flag to specify that the specified node should only be removed from the WAN gossip pool (introduced in #11722).

PR #11886 added this new flag to the CLI and API documentation.
