### ISSUE TITLE
Tune DNS return code when DC does not exists

### ISSUE THREAD

**Issue by pierresouchay** [hashicorp/consul#8102]
#### Feature Description

For now, DNS returns SERVFAIL if datacenter is not available or if it does not exists. We would like to propose to return NXDOMAIN (RCODE: 3) when datacenter does not exist and keep SERVFAIL if DC exists and cannot be reached.

#### Use Case(s)

The DNS servers caching queries might use this information to keep track of queries constantly failing and have different behavior for those errors.

#### Implementation

This information might be already available since we know can find if the DC does exists or not: https://github.com/hashicorp/consul/blob/master/agent/consul/rpc.go#L607 since https://github.com/hashicorp/consul/commit/be50400c62dad0d6d3cb4735132934f182026357 has been merged.

So, DNS server would only have to check for:
* `ErrDCNotAvailable` and return `SERVFAIL` (current case)
* `ErrNoDCPath` return `NXDOMAIN`

**Comment by pierresouchay** [comment]
Implemented in https://github.com/hashicorp/consul/pull/8103

**Comment by jsosulska** [comment]
Hi @pierresouchay  - Since this has been implemented, I will go ahead and close this issue :) Feel free to comment if it needs reopening.
