### ISSUE TITLE
Cannot create HashiCorp Consul Service on Azure

### ISSUE THREAD

**Issue by akamenev** [hashicorp/consul#8104]
#### Overview of the Issue

Getting a "We experienced a temporary error. Please try again." when validating the deployment of HCS on Azure

#### Reproduction Steps

Steps to reproduce this issue, eg:
1. Search for an HCS on Azure offer in Marketplace
2. Fill in resource group, choose region, number of nodes, application name and the name of a managed resource group. Click "Next: Consul Settings"
3. Fill in 'Cluster Name' and change 'External Endpoint' to enabled. Click "Next: Review and Create"
4. Validation Passed but there is an error message below "We experienced a temporary error. Please try again."

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

Not applicable

</details>

<details>
  <summary>Server info</summary>

Not applicable

</details>

### Operating system and Environment details

Not applicable

### Log Fragments

Not applicable

**Comment by jsosulska** [comment]
Howdy @akamenev,

Thank you so much for bringing this to our attention. 
I went ahead to tried to replicate using your steps. I chose HCS in the Azure Marketplace, made a resource group, used the default region and most default settings. I did set the Cluster Name and enabled external endpoint. Under "Review and Create" I saw the Validation Passed, and I was able to "Accept" the terms and agreement and create the cluster.

It is important to note that at this time HCS is only able to be deployed in the following regions:
```
(US) East US
(US) West US 2
(Europe) West Europe
(Europe) North Europe
```

We have a [learn guide](https://learn.hashicorp.com/consul/hcs-azure/deploy#create-a-resource-group) posted with this information if this helps.

For now, I am going to close this issue. If you continue to run into the issue, please post here with what settings you used to set up HCS, like region. :slightly_smiling_face:
