### ISSUE TITLE
consul services register command returns successfully when registering a service into a non-existing consul namespace

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#8123]
version: consul enterprise 1.8.0-rc1 (although unlikely to be specific to this version)

If I have a service definition that sets a consul namespace that doesn't exist, the `consul services register <file>` command doesn't error out but the agent will continually log:

```
    2020-06-16T22:31:07.613Z [ERROR] agent: failed to sync changes: error="rpc error making call: Namespace "luke" does not exist"
    2020-06-16T22:31:17.782Z [ERROR] agent.client: RPC failed to server: method=Catalog.Register server=10.32.4.186:8300 error="rpc error making call: Namespace "luke" does not exist"
    2020-06-16T22:31:17.782Z [WARN]  agent: Syncing service failed.: service=luke/consul-ingress-gateway2-59779f75bb-zzkw2 error="rpc error making call: Namespace "luke" does not exist"
```

Not sure if this is expected behaviour? I would have expected the service registration to fail.

**Comment by mkeeler** [comment]
Client agents do not themselves know if a namespace exists. So registering with the agent apis just allows it right now. We could potentially use the same token used during registration to read the namespace to see if it exists. However that would turn every registration into a non-default namespace into an immediate RPC and anti-entropy is kind of meant to prevent that.

**Comment by mkeeler** [comment]
There could be similar issues if we allowed registration but the namespace was removed prior to syncing the service with the Catalog or if the ACL permissions changed that no longer allow the registration to work with the Catalog.

So for these reasons this behavior likely cannot be changed in a meaningfully better way without getting rid of the agent syncing process all together and making it a blind pass through for the underlying RPC APIs.

**Comment by lkysow** [comment]
Closing as wontfix because this is solved when using the catalog register api (which is used now for kubernetes) and because that's likely the direction we'll move for VMs.
