### ISSUE TITLE
Docs don't render code-formatted links in some cases

### ISSUE THREAD

**Issue by carlpett** [hashicorp/consul#8128]
#### Overview of the Issue

In the online docs, text which is both "code-formatted" **and** a link (but additionally not under some(?) circumstances, see below) do not get rendered, instead a HTML comment appears in the source.

For example, [here](https://www.consul.io/docs/agent/options#_encrypt):
>The easiest way to create an encryption key is to use . 

Note "space period" at the end. In the rendered page, this looks like
```html
[...] The easiest way to create an encryption key is to use
<!---->
. [...]
```

In the mdx source, on the other hand:
https://github.com/hashicorp/consul/blob/a9851e181259f3e09240d1afee7a8406755851fd/website/pages/docs/agent/options.mdx#L236

There are several examples of this in the docs, but I did find one place in the same file where it *is* rendered correctly:
https://github.com/hashicorp/consul/blob/a9851e181259f3e09240d1afee7a8406755851fd/website/pages/docs/agent/options.mdx#L266

This outputs 
```html
[...] can be combined with <a href="#_log_rotate_bytes"><code>-log-rotate-bytes</code></a> [...]
```

My first theory was that it was about absolute href:s vs in-document anchors, but this also doesn't render:
https://github.com/hashicorp/consul/blob/a9851e181259f3e09240d1afee7a8406755851fd/website/pages/docs/agent/options.mdx#L230

Best guess I have is that somehow the leading `-` convinces the parser to output the right thing?

**Comment by jsosulska** [comment]
Thanks for reporting this! We'll get that fixed up :)

**Comment by pruett** [comment]
Terrific bug report @carlpett . Very clear, thanks. I'm thinking [this custom plugin](https://github.com/hashicorp/remark-plugins/tree/master/plugins/anchor-links) that we wrote might not account for this use case.

I'll incorporate these examples in our test suite to see if we can get this fixed up!

**Comment by pruett** [comment]
It looks like one of our dependencies (`@hashicorp/nextjs-scripts`) was a few major versions behind. This dependency is responsible for the markdown plugins which (were behind as well)...updating this seemed to correctly render the problematic areas outlined in the issue.

**Comment by jsosulska** [comment]
This has been merged and fixed.
