### ISSUE TITLE
UI: Display nodes failing serfHealth as unreachable

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/consul#813]
Reference: #811 
/cc @pearkes

**Comment by issmirnov** [comment]
This would help a ton! Just ran into this today, definitely caused some confusion. Any chance of this making it in the 0.8.x releases?

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
