### ISSUE TITLE
Node UI get broken when we have named session

### ISSUE THREAD

**Issue by nati** [hashicorp/consul#814]
Node 
UI get broken when we have named session

![screen shot 2015-03-24 at 11 16 09 am](https://cloud.githubusercontent.com/assets/105922/6809429/748202e6-d217-11e4-80ca-7248a8d231d0.png)

**Comment by nati** [comment]
with version 0.5.0
Browser Chrome

**Comment by agchillibean** [comment]
Is there any solution for this issue yet? I'm having the same problem and I can't see the remaining sessions. :(

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
