### ISSUE TITLE
Session creation fails with missing node registration error

### ISSUE THREAD

**Issue by fraenkel** [hashicorp/consul#819]
Using v0.5.0, 3 servers. In our test, we are starting 3 members in our cluster and then attempting to acquire a lock. Every so often we see the following.  We can also recreate it with 1 member. We always notice the the Error occurs at the same time the member reports that it joins.

failed to create session: Unexpected response code: 500 (Missing node registration)

[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] raft: Election won. Tally: 2
[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] raft: Node at 127.0.0.1:5024 [Leader] entering Leader state
[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] consul: cluster leadership acquired
[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] consul: New leader elected: 0
[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] raft: pipelining replication to peer 127.0.0.1:5030
[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] raft: pipelining replication to peer 127.0.0.1:5036
[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] consul: member '2' joined, marking health alive
[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] consul: member '0' joined, marking health alive
[o][consul_cluster[0]]     2015/03/26 15:07:35 [ERR] http: Request /v1/session/create, error: Missing node registration
[o][consul_cluster[0]]     2015/03/26 15:07:35 [INFO] consul: member '1' joined, marking health alive

**Comment by ryanuber** [comment]
@fraenkel this sounds like it could be a startup race. The error message `Missing node registration` indicates that the node is not yet registered in the catalog. Are you attempting to create a session immediately after starting Consul, in a script or similar? If so, you might need to allow Consul some time to initialize and sync the node registration to the catalog.

**Comment by fraenkel** [comment]
Yes, it happens when we are starting/restarting consul and clients are attempting to connect.
All we are doing is driving the Lock API which does the session magic underneath the covers.

**Comment by nh2** [comment]
I just saw this error too.

> you might need to allow Consul some time

(ala "sleep a bit") doesn't sound like a robust solution to it, so here I have a question:

What endpoint should one in general query to find out whether a consul cluster is fully up and running, ready to perform actions like using locks, putting values etc?

So far I assumed that `/v1/status/leader` was that endpoint until I got said error today.

For failure scenario retrying is of course always mandatory, but it'd still nice to have an endpoint that signals when it makes sense to _start_ doing so.

**Comment by ketzacoatl** [comment]
The issue here is that requests from the agent need to wait until the agent registration is complete. I haved used https://gist.github.com/ketzacoatl/736a56532843afb05266#file-consul-online-py to block host init and other processes until the agent's registration is complete. This has worked well for me in production with clusters between 20 and 1k nodes.

**Comment by denglifeng3** [comment]
@ketzacoatl @ryanuber ,Hi, I met the same issue, but the consul had started. I can read some kvs from consul already. I tried to create session minutes later, and the same error occur. 
`

2019-02-22 09:21:24.250 [] PST [info] c.c.o.d.s.r.l.ConsulLock - the session created:af3d4161-7490-b967-3021-253ef1cac915
--


`
I want to add a lock in two dcs, I create success session in one dc succssfully, but the other failed. 
`for (String dc : dcList) {
                String sessionIdTemp = createSession(dc);`
Is it not correct ?
If I want to create a cross dc lock, what shall I do ?

Thank you so much.
