### ISSUE TITLE
Could not access KV and Intentions page using master key.

### ISSUE THREAD

**Issue by w6m6** [hashicorp/consul#8207]
#### Overview of the Issue
we setup a cluster with 1 server, and get message of  "log in with a different token" appeared, when we use master token. 

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

[root@vm172-20-228-17 consul]# ./consul  info   
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 144
build:
        prerelease = 
        revision = 3111cb8c
        version = 1.8.0
consul:
        acl = enabled
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 172.20.228.17:8300
        server = true
raft:
        applied_index = 138586
        commit_index = 138586
        fsm_pending = 0
        last_contact = 0
        last_log_index = 138586
        last_log_term = 6
        last_snapshot_index = 131891
        last_snapshot_term = 2
        latest_configuration = [{Suffrage:Voter ID:54a34ba9-7a66-10ae-77ca-62d74d6db4b5 Address:172.20.228.17:8300}]
        latest_configuration_index = 0
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 6
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 95
        max_procs = 2
        os = linux
        version = go1.14.4
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 2
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 339
        members = 1
        query_queue = 0
        query_time = 1
</details>

**Comment by johncowen** [comment]
Hi @w6m6 

Can I just double check ythat ou are seeing this in the UI (thats what it sounds like)?

> get message of "log in with a different token" appeared, when we use master token.

If so, have you added any intentions or KVs to the cluster yet?

Thanks,

**Comment by w6m6** [comment]
by now, we do not add any intention of kv into the cluster.

**Comment by w6m6** [comment]
my bad, might be a misunderstanding of the wording.
