### ISSUE TITLE
Build fails on illumos

### ISSUE THREAD

**Issue by ptribble** [hashicorp/consul#8213]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

On illumos (OpenSolaris derivative), building from source fails in gofrs/flock

#### Reproduction Steps

gmake (using Go 1.14) gives the following error:

# github.com/gofrs/flock
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:28:22: undefined: syscall.LOCK_EX
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:39:22: undefined: syscall.LOCK_SH
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:56:12: undefined: syscall.Flock
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:66:12: undefined: syscall.Flock
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:96:12: undefined: syscall.Flock
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:96:42: undefined: syscall.LOCK_UN
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:118:21: undefined: syscall.LOCK_EX
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:130:21: undefined: syscall.LOCK_SH
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:149:9: undefined: syscall.Flock
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:149:44: undefined: syscall.LOCK_NB
../../../../../pkg/mod/github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b/flock_unix.go:149:44: too many errors

That's correct. You can't use syscall for flock on Solaris or illumos. It should be using x/sys/unix (and making that simple replacement gave me a successful build

**Comment by jsosulska** [comment]
Hi @ptribble .

Welcome to Consul, and thank for posting. Consul doesn't use this library, so I am a bit confused about what you're doing here. The [Golang](https://github.com/golang/go/issues) public repo, however, does use this package, so you may want to consider reaching out to them regarding the incompatibility with Illumos.

Hope this helps, and happy Coding!
