### ISSUE TITLE
Missing Docs for the Serf CIDR restrictions

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#8220]
The docs were reverted here: https://github.com/hashicorp/consul/commit/c6a6fe6949edb9bb8d09a9f8a8c294cdb3cb5605

But the feature is still in the 1.8.0 release. My guess is that we just merged master into stable-website instead of force pushing. Regardless we need these changes in stable-website.

Also it looks like before we didn't document that they could be used in the config file as well as on the CLI.

```
serf_lan_allowed_cidrs = [...]
serf_wan_allowed_cidrs = [...]
```

**Comment by mkeeler** [comment]
It was also not added in the changelog.

**Comment by i0rek** [comment]
Added to the changelog here: https://github.com/hashicorp/consul/commit/1b69a24f36548000f5e0920905488e7b7bfd55f1.
