### ISSUE TITLE
TTL service health check not showing output

### ISSUE THREAD

**Issue by sundalova** [hashicorp/consul#8225]
After upgrading from consul 1.6.3 to 1.7.3 I don't see output field for TTL healthcheks in consul UI.
I can see data via querying consul api (both agent/checks and health/node endpoints return data correctly). Http health checks are displaying output but TTL not.

I also don't see changes related to this functionality in release notes and I checked latest version 1.8.0 with the same result.

**Comment by dnephin** [comment]
Thank you for the bug report! This was fixed recently in #8187 and will be in the next 1.8.x release.

Related to issue #8161
