### ISSUE TITLE
Conflicting Node IDs after 1.7.0 and even with upgrading to 1.7.3

### ISSUE THREAD

**Issue by JacobCalmes** [hashicorp/consul#8232]
#### Overview of the Issue

After upgrading our servers to 1.7.0 around the end of February we have been seeing a constant stream of conflicting node ID messages. These messages build up and eventually lead to `Too many pending push/pull requests` and `handler queue full, dropping message`. The only "fix" is to restart one of the Consul servers. Sometimes this works but most of the time the server is unable to load it's local snapshot due to the conflicting node ID problems. The server will then exit. The only way to bring it back is to delete it's local data directory and start it up. Again, sometimes this works, but if there are conflicting node IDs propagated from the other servers the server will not start fully and will show `ACL not found errors`. This has happened to 2/3 of our servers and caused a complete outage. We had to restore from a snapshot 7 days previous (soonest with no node ID conflicts) to bring the cluster back.

Version 1.7.3 has a changelog message of `agent: don't let left nodes hold onto their node-id` which references #7775. We updated our servers to 1.7.3 and some of our clients to 1.7.3 but not all of them. We still see these upgraded clients referenced inside the log having conflicting node IDs. We most often see the conflicting node IDs coming from Windows clients. The interesting thing is the `from=` address is always one that is not upgraded to 1.7.3. Does every single client have to be upgraded to 1.7.3 for this to go away? We have about 3400 nodes in our cluster.

This issue is also causing our servers (4 CPU, 6 GB RAM) to go from 5-10% CPU usage to 90-100% CPU usage. We also see memberlist TCP messages go from 50k-100k to 2-6 million.

#### Reproduction Steps

Reproduction happens on it's own. We will use `consul force-leave -prune` against the conflicting ID clients to remove them from the `consul members` list but it can take hours to have them disappear from the log, if they even do. The conflicting messages reappear after a day or so. We are unable to reproduce it on demand in our smaller (~10 node) development environment.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 133
build:
	prerelease =
	revision = 8b4a3d95
	version = 1.7.3
consul:
	acl = enabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 45
	max_procs = 4
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 58
	failed = 349
	health_score = 0
	intent_queue = 0
	left = 49
	member_time = 317495
	members = 3566
	query_queue = 0
	query_time = 2970
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 2
build:
	prerelease =
	revision = 8b4a3d95
	version = 1.7.3
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 172.16.34.160:8300
	server = true
raft:
	applied_index = 52183962
	commit_index = 52183962
	fsm_pending = 0
	last_contact = 0
	last_log_index = 52183962
	last_log_term = 3
	last_snapshot_index = 52179298
	last_snapshot_term = 3
	latest_configuration = [{Suffrage:Voter ID:f6fd3b05-1ab3-ae43-4b60-260c68f450bf Address:172.16.34.160:8300} {Suffrage:Voter ID:d748b3b5-e246-638b-98b8-834045a49290 Address:172.16.34.161:8300} {Suffrage:Voter ID:8656e331-ac0d-42b8-a6b4-ca474519bdbc Address:172.16.34.162:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 3
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 8055
	max_procs = 4
	os = linux
	version = go1.13.7
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 58
	failed = 318
	health_score = 0
	intent_queue = 0
	left = 57
	member_time = 317476
	members = 3537
	query_queue = 0
	query_time = 2970
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 91
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

We use the Consul binary on a mix of operating systems:
- Centos 7.7 (all servers)
- Centos 7.6
- Windows 2008 R2
- Windows 2016

### Log Fragments

Here are some examples we see:

```
Failed push/pull merge: Member 'lower-case-hostname' has conflicting node ID 'f00e29ad-498c-6a3d-a408-4dae49aec7d6' with member 'UPPER-CASE-HOSTNAME' from=172.23.10.30:50509
```

```
Jul 02 12:29:09 CONSUL-SERVER-0 consul[75336]: 2020-07-02T12:29:09.713-0500 [ERROR] agent.server.memberlist.lan: memberlist: Too many pending push/pull requests
Jul 02 12:29:09 CONSUL-SERVER-1 consul[75336]: 2020-07-02T12:29:09.756-0500 [WARN]  agent.server.memberlist.lan: memberlist: handler queue full, dropping message (3) from=172.21.1.37:8301
```

**Comment by jsosulska** [comment]
Hi @JacobCalmes ! Thanks for reporting this. For questions like this, we recommend asking on our [Discuss forum](https://discuss.hashicorp.com/c/consul/29), but I'll address this here for now. You gave us a lot of info, so let me just clarify your ask here.

>Does every single client have to be upgraded to 1.7.3 for this to go away? We have about 3400 nodes in our cluster.

The short answer is *yes* , all Agents (Servers AND clients) will need to be updated to 1.7.3. This is because the dependency library Consul uses for `memberlist` has the needed changes. As older agents don't have the updated dependency, they will continue to show this behavior. 

I hope this helps!
Best,
Jono

**Comment by jkirschner-hashicorp** [comment]
Hi @JacobCalmes and @dontlaugh,

I'm closing this issue under the assumption that @jsosulska 's reply above gave you what you needed. If you still think there's something to be done here, please reply and reopen the issue. Thanks!
