### ISSUE TITLE
Reverse-proxy friendliness

### ISSUE THREAD

**Issue by jan-johansson-mr** [hashicorp/consul#8240]
### Feature Description

It's possible to re-route UI from `/ui` path to `/somepath` with `"ui_content_path": "/somepath"` (in config file), but the UI itself requires root route to consul, e.g. `/v1/...` to enable UX features with consul.

Access to root route can be (and almost always) is problematic in reverse-proxy scenarios.

### Use Case(s)

This feature request is about being able to define a base route for consul, thus making it easier to set up environments in reverse-proxy scenarios.

I haven't tried it out yet, but I figure one way to "fix" this reverse-proxy issue may be to put another proxy before consul, that map some route from the front reverse-proxy [e.g.] `/mesh` to `/`, but this causes unnecessary complexity and may add computational load in scenarios where HTTPS is used throughout.

**Comment by adamdecaf** [comment]
This looks to be related with https://github.com/hashicorp/consul/issues/10374#issuecomment-859571122 and https://github.com/hashicorp/consul/issues/9829#issuecomment-857685303? Having a "base path" to view the consul UI under would be a great addition. We deploy lots of infra services behind an endpoint, but consul does not support this deployment currently.
