### ISSUE TITLE
Service Discovery without registering the service

### ISSUE THREAD

**Issue by Srini59** [hashicorp/consul#8257]
Hi,

Is there any way we can do service discovery without registering the service ?

Example:
I have a environment in AWS cloud where its add new instances to the cluster thru auto scaling and want to have the consul do self discovery of the processes like http/tcp/script check on the new instances with out  registering the service like in json format.

 Is this achievable?

Can someone please suggest.

**Comment by jsosulska** [comment]
Hi Srini,

Apologies for the long tail on response. Questions such as this are better handled in our [Discuss Forum](https://discuss.hashicorp.com/c/consul/29), where our community can provide more varied opinions. The answers to this question vary wildly depending on your infrastructure and deployment strategy. Consul, however, does not have the capability to scan a new instance and create service definitions.

Hope this helps!
Jono
