### ISSUE TITLE
Doc Issue: Anchors are not linked correctly

### ISSUE THREAD

**Issue by apoydence** [hashicorp/consul#826]
It looks like the links in [watches](https://www.consul.io/docs/agent/watches.html) are trying to point to different sections of the page, however the anchors aren't setup correctly.

**Comment by ryanbreen** [comment]
Any list item that contains a code block automatically creates an anchor and a link to that anchor.  This is to make it easier to copy and paste a link to where you are in the docs, but I agree it can be kinda confusing since you expect a link to take you somewhere else.

**Comment by ryanbreen** [comment]
I'm going to leave this ticket open, though, because I think we should override that default behavior and link to the sections of the watch docs.  I'll take this.

**Comment by ryanbreen** [comment]
This will be fixed with the next push of docs to consul.io.
