### ISSUE TITLE
How does consul api use tcp connection underly

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#8299]
Hi,

I thought the consul will use the one keepalive tcp connection to server all the requests from the same client ip.
But I found sometimes the consul will create more then one tcp connections to server requests.
How does consul handle the large concurrent requests via consul api from the same client ip w.r.t the tcp connection?

**Comment by mkeeler** [comment]
The API client uses the github.com/hashicorp/go-cleanhttp library to setup the underlying HTTP client. Unless you override the transport used for the HTTP client:

https://github.com/hashicorp/consul/blob/e72af87918fe0224b769f41e98fe570686ac8285/api/api.go#L285-L286

It is going to use the default HTTP Transport which is setup here:

https://github.com/hashicorp/go-cleanhttp/blob/d3fcbee8e1810ecee4bdbf415f42f84cfd0e3361/cleanhttp.go#L23-L37

The API client will reuse TCP connections (and will utilize keep-alives). However the default transport also utilizes connection pooling to help with making more than one concurrent requests without waiting for the main connection to finish its request.

More information about the Golang HTTP Transport (which we end up using) can be found here: https://golang.org/pkg/net/http/#Transport

**Comment by hehailong5** [comment]
Hi
thanks, this explains.
can this behavior be configured in some place? such as the connection pool size or I don't want to use this pool at all and hope to keep one single connection per client in all cases?
