### ISSUE TITLE
Lock is reported lost when it might not be

### ISSUE THREAD

**Issue by fraenkel** [hashicorp/consul#830]
https://github.com/hashicorp/consul/blob/master/api/lock.go#L308

If the client used during a successful Lock() has a timeout on the connection, the aforementioned Get will return eventually with an error when the connection is closed. This immediately drives a lost lock. The lock might not in fact be lost and there should be some attempt to retry since it should be allowed to have connections time out.

**Comment by armon** [comment]
There is definitely some room to improve this behavior, tagging for enhancement. The safest path is to assume the lock is lost, which is the current behavior.

**Comment by slackpad** [comment]
Retries were added to the lock monitor in https://github.com/hashicorp/consul/pull/1567. Closing this out.
