### ISSUE TITLE
consul client agent can't reconnect when server IPs change

### ISSUE THREAD

**Issue by discordianfish** [hashicorp/consul#838]
Hi,

it looks like when a client joins a cluster, it resolves the DNS name provided by `-consul` once at start but not after losing the connection. This means if you need to replace a server node and the new server has a different IP, you need to restart all consul clients manually.

Instead, consul client should resolve the DNS name again before reconnecting.

**Comment by ryanuber** [comment]
@discordianfish this is a symptom of #457. There is a bit more to it since the node IP addresses are persisted on other members of the cluster as well, but we are very aware of this. Let's track this in #457. Thanks for reporting!
