### ISSUE TITLE
How to build consul in arch mips64el

### ISSUE THREAD

**Issue by PoplarYang** [hashicorp/consul#8381]
#### Feature Description
I want to use consul in arch mips64el, but I find `GOOS=linux GOARCH=mips64le go build` doesn't work. The error is:
```
../../go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:101:13: undefined: maxMapSize
```

#### Use Case(s)
According to the error above, I add below to `../../go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go`.  `GOOS=linux GOARCH=mips64le go build` passed. But I think it's not a good idea.
```
const maxMapSize = 0xFFFFFFFFFFFF // 256TB

// maxAllocSize is the size used when creating array pointers.
const maxAllocSize = 0x7FFFFFFF

// Are unaligned load/stores broken on this arch?
var brokenUnaligned = false
```

**Comment by jsosulska** [comment]
Hello @PoplarYang 

Thank you for posting this. This is an issue with boltdb as a dependency. Unfortunately, that project is no longer being maintained. There is an [open issue](https://github.com/hashicorp/consul/issues/8442) to upgrade the bolt database. Please follow that issue and then try to recompile after.

I followed [the thread](https://github.com/boltdb/bolt/issues/656) on the github issues page, and found someone who built with the [following configuration](https://github.com/boltdb/bolt/pull/663/files).

In the meantime, I will go ahead and close this issue.

Best, Jono
