### ISSUE TITLE
Release and delete a lock as one operation

### ISSUE THREAD

**Issue by fraenkel** [hashicorp/consul#840]
The current behavior follows what I consider the default behavior for a session to release a lock. With the addition of being able to specify delete, wouldn't it also be useful to allow the Release() API to optionally delete as well? We have cases where we would prefer to avoid the Release/Destroy 2 step and just be able to combine them as one.

I could easily imagine that the DELETE of an acquired KV could also allow the flag & release parameters.

**Comment by armon** [comment]
Tagged as enhancement, makes sense to me!

**Comment by slackpad** [comment]
This is now supported in Consul 0.7 - https://www.consul.io/docs/agent/http/kv.html#txn.

**Comment by fraenkel** [comment]
@slackpad May I ask how txn solves this? You can only do PUTs in a txn, so how do I combine a PUT (to unlock) and DELETE?

**Comment by slackpad** [comment]
@fraenkel with the /v1/txn endpoint you PUT a JSON structure with a list of operations to perform - you would PUT a structure like this:

```
[
  {
    "KV": {
      "Verb": "unlock",
      "Key": "<key>",
      "Session": "<session id>"
    }
  },
  {
    "KV": {
      "Verb": "delete",
      "Key": "<key>"
    }
  }
]
```

These are done atomically, so if the unlock succeeds it will delete the key as part of the same request.

**Comment by fraenkel** [comment]
@slackpad The docs say PUT is only supported which is why I asked.

**Comment by slackpad** [comment]
That's correct - you always PUT to /v1/txn with a list of updates and their associated verbs.
