### ISSUE TITLE
`forwardRPC` and `globalRPC` do not take LAN `ServerLookup` into account when the target datacenter is the local datacenter

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#8403]
https://github.com/hashicorp/consul/blob/4c8a15b698d1c8402e45a44a25808fe84d1f108b/agent/consul/rpc.go#L604-L669

When performing a keyring listing we use the `globalRPC` function to issue the RPC against all datacenters and collect the results. `globalRPC` in turn just calls `forwardDC` on all known datacenters including the local DC. 

This doesn't sound too bad but when coupled with #8401 it can cause some issues. Mainly that in a single node cluster (or multi-node where the servers WAN gossip ports are firewalled from each other) the router being used by `forwardRPC` to lookup a server in the local DC will report that there are no reachable servers in the datacenter and fail to perform the RPC.

We should either 1) exclude the local DC from the globalRPC call 2) ensure that `forwardRPC` uses the `ServerLookup` instead of the `Router` for finding a server to use in the local datacenter or 3) avoid all the server lookups for the local DC and just field the RPC locally.

Right now I am leaning toward the second option as it seems most robust.

**Comment by i0rek** [comment]
This is the globalRPC function, it uses `forwardDC` even for its own dc: https://github.com/hashicorp/consul/blob/d1c879e06c2bd4dbb895f695bde06dd1ae56bc33/agent/consul/rpc.go#L641-L660

We were unsure if #8406 fixes this issue. After this fix, single node dcs are healthy and a single server marks itself as healthy. That means that even a call through the router should be successful.

@mkeeler suggested to

> ensure that forwardRPC uses the ServerLookup instead of the Router for finding a server to use in the local datacenter

`forwardRPC` is only "misused" from `globalRPC` and in the other cases it properly checks if forwarding is required. Changing this function to do the same check again doesn't seem right to me. If we were to optimize `globalRPC` I would vote for checking against the local dc in this function and field the RPC directly.

I agree that a server shouldn't RPC itself, but apart from this optimization, there is no bug anymore.

**Comment by mkeeler** [comment]
So it turns out that the server does need to RPC itself.

The first server that gets the keyring request will update the WAN keyring and then issue `globalRPC`. That RPC will update the LAN keyring of each DC with the sent RPC. Therefore in order to update the LAN keyring in the local DC the second RPC is done.

Do we need an RPC to do this: No.
Is the code a little convoluted: Yes.
Is it functionally correct: Yes.
