### ISSUE TITLE
Restarting 3 server cluster after hostname change lead to: [ERR] agent: failed to sync remote state: No cluster leader

### ISSUE THREAD

**Issue by discordianfish** [hashicorp/consul#841]
Hi,

I'm running consul 0.5 by using the progrium/consul docker image, each with `-server -bootstrap-expect 3 -advertise (external ip) -retry-join A-record-with-all-3-nodes-external-ip`.
After running for a few days, I changed the server nodes hostnames and recreated the container (although keep the data volume). Now all node seems to have agreed on a leader but the log shows:

```
2015/04/06 16:22:00 [ERR] agent: failed to sync remote state: No cluster leader
```

I'm not sure if this is expected or related to #457 but wanted to report in case it's not.

**Comment by discordianfish** [comment]
The same happened to me when starting over from scratch: When starting up a cluster in parallel, I seem to get into this situation pretty reliably. I'll try to reproduce if I find some time.

**Comment by armon** [comment]
Does that error continue to be logged? It may be logged for the duration of the time there is no leader (e.g. prior to bootstrap, leader transition period, etc). It is only an issue if that message is being continuously repeated meaning the cluster cannot elect a stable leader.

**Comment by discordianfish** [comment]
@armon This happened for quite some time (several minutes at least) after all nodes were up and running, so it wasn't just, as expected, during the initial bootstrapping. Once I started the cluster one-by-one, things worked as expected.

**Comment by slackpad** [comment]
Closing this out I don't think there's any more follow up to do here.
