### ISSUE TITLE
Setting acl_default_policy=deny has no effect on catalog deregistration

### ISSUE THREAD

**Issue by centromere** [hashicorp/consul#842]
A malicious user can deregister an entire node without an ACL token on 0.5, which will also delete all the services associated with that node.

**Comment by armon** [comment]
The current enfacement only extends to registration. The goal is to protect the entire catalog over time. Hopefully 0.6 will have a very broad surface covered.

**Comment by slackpad** [comment]
Closing this as a dup of #1383.
