### ISSUE TITLE
Protect against silent cluster merging

### ISSUE THREAD

**Issue by armon** [hashicorp/consul#843]
With 0.5 we protect against an active cluster merge as a result of an agent joining the wrong gossip pool. However, silent merging is still possible through stale state or operational context. As an example:

1) Start Node1 at IP1 in DC1
2) Join Node1 to DC1 peers
3) Restart Node1 at IP1 to DC2
4) Join Node1 to DC2 peers
5) A TCP anti-entropy between a peer in DC1 and Node1 will now cause a cluster merge.

We should be able to protect against this passive / silent merge as well by dropping the status updates.

**Comment by dpurrington** [comment]
My team (120 members) is stalled on consul adoption until this vulnerability can be resolved. I urge you to prioritize fixing this issue as we cannot proceed without it.

**Comment by ryanbreen** [comment]
Is this still in the works for 0.5.1?

**Comment by ryanuber** [comment]
@ryanbreen @dpurrington this is definitely in the crosshair for 0.5.1 (the next release of Consul), which should be on its way out in the coming weeks. The release won't go out the door without this.

**Comment by amitgilad3** [comment]
Hi,
my team is also working with consul and we have 2 security groups in aws.
1.dev
2.uat
and we also have agents on our local computers that have access to both security groups .
this causes a silent merge.
is there any workaround or eta for consul 0.5.1??
thanks :)

**Comment by armon** [comment]
This is now fixed upstream in Serf and Memberlist. This will go out with 0.5.1.

**Comment by ryanbreen** [comment]
Awesome, thanks!

**Comment by dpurrington** [comment]
Fantastic, thank you for making it happen, and so quickly!
