### ISSUE TITLE
Improve Azure MSI cloud auto-join documentation

### ISSUE THREAD

**Issue by pvandervelde** [hashicorp/consul#8432]
In PR #7000 the documentation was updated to include some information on how to configure Consul to use a Managed Identity for cloud auto-join in Azure. Having gone through the process there are a few additional instructions that would make it easier to configure this capability. 

When using individual VMs I found I needed to set up the following additional things.

* The tag (that is pointed to by `tag_name` and `tag_value`) needs to be on the virtual Network Interface Card (vNIC), not on the VM
* The permission that is required is `Microsoft.Network/networkInterfaces/read`. It needs to be applied to the resource group that owns the vNIC
* The permission can be assigned to an Azure AD group
* In the consul configuration you need to specify the `tag_name`, `tag_value` and the `subscription_id` (and the Subscription ID can be specified through the environment variable as well)

Note that I have tested with a system assigned managed identity, not a user assigned one, however I would assume the above changes are the same for both.

I'll be happy to put in a PR. I think the correct file to change is `/website/pages/docs/agent/cloud-auto-join.mdx`?

**Comment by jsosulska** [comment]
Hello @pvandervelde !

Thanks for posting :) A PR would happily be accepted for documentation. Please tag me in it for review.

Best, 
Jono
