### ISSUE TITLE
Upgrade from BoltDB to bbolt

### ISSUE THREAD

**Issue by jsosulska** [hashicorp/consul#8442]
#### Feature Description
Per [BoltDB's Repo](https://github.com/boltdb/bolt):

> Bolt is in a stable state and has years of successful production use. As such, I feel that leaving it in its current state is the most prudent course of action.
> If you are interested in using a more featureful version of Bolt, I suggest that you look at the CoreOS fork called [bbolt](https://github.com/etcd-io/bbolt).

#### Use Case(s)
https://github.com/hashicorp/consul/issues/7471 and https://github.com/hashicorp/consul/issues/3771#issuecomment-415358971 illustrate the need for a newer version of Bolt.

**Comment by jsosulska** [comment]
Consul uses bbolt via the [hasicorp/raft-boltdb](https://github.com/hashicorp/raft-boltdb) package. This package then depends on the original [BoltDB's Repo](https://github.com/boltdb/bolt) at v.1.3.1.

History:
From there, it was forked to coreos/bbolt @[1.3.1, with changes](https://github.com/boltdb/bolt/compare/v1.3.1...etcd-io:v1.3.1-coreos.0). Coreos continues to commit [for 7 tags](https://github.com/etcd-io/bbolt/compare/v1.3.1-coreos.0...etcd-io:v1.3.1-coreos.6), before turning it over to [etcd-io](https://github.com/etcd-io/bbolt/compare/v1.3.1-coreos.6...etcd-io:v1.3.1-etcd.8) for ownership.  The current version is [1.3.5](https://github.com/etcd-io/bbolt/compare/v1.3.1-etcd.8...etcd-io:v1.3.5). A summary of all the changes From [fork to latest](https://github.com/boltdb/bolt/compare/v1.3.1...etcd-io:v1.3.5).  

Findings:
- Overall the dependency would be easy/medium to implement in the library, but would need to be tested. 
- Not all version jumps outline on the history are needed. As a control - cutting over directly to 1.3.2 would be sufficient to suss out initial compatibility impact and avoid multiple package renames.
- `hasicorp/raft` is a cross dependency.

Considerations:
- Nomad also has a dependency on this library, and as such, blast radius of an upgrade like this should be discussed.
- Vault is not affected as that product does not use the `raft-boltdb` library.

<img width="596" alt="Bolt" src="https://user-images.githubusercontent.com/42216911/91909958-217a8980-ec7c-11ea-9ddf-da36c9de2c1b.png">

**Comment by jsosulska** [comment]
Working with Sarah Notes:
- Main concern - upgrade `raft-boltdb`


raft-boltdb (before upgrade): 2.234s, 2.21s, 1.7s
raft-boltdb (after upgrade): 2.174s, 1.7s, 1.7s

First hashicorp/raft-boltdb needs to import the new dependency, and release a new version.
Then hashicorp/raft needs to import the new dependency, and release a new version.
Lastly, consul needs to import hashicorp/raft when it is ready to update.

**Comment by Asara** [comment]
Looking forward to this as it is the only thing blocking building consul for riscv64 for me right now.

**Comment by blake** [comment]
Closing this issue as the work was recently completed in PR #11720.
