### ISSUE TITLE
agent/service/register fails in new consul

### ISSUE THREAD

**Issue by shankarkc** [hashicorp/consul#8444]
#### Overview of the Issue
v1/agent/service/register doesnt work as expected with consul `1.7.2`
To register the service we use http://Consul-IPHere:8500/v1/agent/service/register endpoint. I am using below json for registering
```
{
  "ID": "redis-dde-V-8ea49f1-29-1595595937-redis-feb086797487",
  "Service": "redis-dde-V-8ea49f1-29-1595595937-redis",
  "Tags": [
    "master",
    "master2"
  ],
  "Meta": {},
  "Port": 6379,
  "Address": "10.1.90.7",
  "TaggedAddresses": {
    "lan_ipv4": {
      "Address": "10.1.90.7",
      "Port": 6379
    },
    "wan_ipv4": {
      "Address": "10.1.90.7",
      "Port": 6379
    }
  },
  "Weights": {
    "Passing": 1,
    "Warning": 1
  },
  "EnableTagOverride": false,
  "Name": "redis-dde-V-8ea49f1-29-1595595937-redis"
}
```

#### Reproduction Steps

Steps to reproduce this issue:

1. Save above json as service.last.update.json
2. run curl -k -s -X PUT -d@/tmp/service.last.update.json http://Consul-IPHere:8500/v1/agent/service/register
I get below error
```
Request decode failed: json: unknown field "Service"
```
If I run same with `Consul 1.5.1` it works fine

**Comment by blake** [comment]
Hi @shankarkc,

Consul 1.7.0 introduced [stricter JSON decoding](https://www.consul.io/docs/upgrading/upgrade-specific#stricter-json-decoding) which now results in an HTTP 400 error code being returned when unknown fields are present in a request. As stated in the error, `Service` is not a valid field for the [`/v1/agent/service/register`](https://www.consul.io/api-docs/agent/service#register-service) endpoint.

This change to JSON decoding was called out as a breaking change in the [1.7.0 CHANGELOG](https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#170-february-11-2020) and 1.7 version specific [upgrade information](https://www.consul.io/docs/upgrading/upgrade-specific#consul-1-7-0). I recommend reviewing these docs for a complete list of potentially breaking changes prior to upgrading your environment.

I hope this helps. Let me know if you have any other questions.

**Comment by shankarkc** [comment]
Thank you @blake It was helpful
