### ISSUE TITLE
update CHANGELOG.md in master branch

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/consul#8445]
the changelog in the master branch has not been updated to reflect the release of 1.8.1, 
https://github.com/hashicorp/consul/blob/v1.8.1/CHANGELOG.md
https://github.com/hashicorp/consul/blob/master/CHANGELOG.md

but the download page does point to 1.8.1
https://www.consul.io/downloads

**Comment by mikemorris** [comment]
Fixed in https://github.com/hashicorp/consul/commit/0ff4f46c52462410ec104269cd7b351b72446724
