### ISSUE TITLE
Unable to use Vault as a CA provider in Consul 1.8.0

### ISSUE THREAD

**Issue by ashwinkupatkar** [hashicorp/consul#8448]
I am trying to setup vault as a CA provider in my consul connect setup.
But it does not take the configuration specified for vault as a CA provider.

It goes by the default consul as a CA provider neither does it show any error messages in the consul server logs.

connect configuration: 

   "connect": {
        "enabled": true
        "ca_provider": "vault"
        "ca_config": {
            "address": "<vault_address>"
            "token": "<vault_root_token_for_demo>"
            "root_pki_path": "/consul-connect-demo-root"
            "intermediate_pki_path": "/consul-connect-demo-intermediate"
            "TLSSkipVerify": "true"
    }
},

log snippet:

    2020-08-06T18:18:48.158Z [INFO]  agent.server.connect: initialized primary datacenter CA with provider: provider=consul
    2020-08-06T18:18:48.158Z [INFO]  agent.leader: started routine: routine="federation state anti-entropy"
    2020-08-06T18:18:48.158Z [INFO]  agent.leader: started routine: routine="federation state pruning"
    2020-08-06T18:18:48.158Z [INFO]  agent.leader: started routine: routine="CA root pruning"

Operating system: centos 7

Consul version: 1.8.0
Vault version : 0.10.4

What am I missing ?

Regards,
Ashwin

**Comment by jsosulska** [comment]
Hi @ashwinkupatkar ,

Thanks for posting. A question like this is better suited for our [Discuss Forums](https://discuss.hashicorp.com/c/consul/29), where users can better troubleshoot that for you. 

I moved the content [there](https://discuss.hashicorp.com/t/issues-using-vault-10-4-and-consul-1-8/12501) and have asked some additional questions.

Thank you,
Jono

**Comment by ashwinkupatkar** [comment]
Sure. Thanks @jsosulska .

I will update there.
