### ISSUE TITLE
Support configuring Envoy circuit_breakers and retry_policy using Consul proxy.upstream[].config

### ISSUE THREAD

**Issue by GordonMcKinney** [hashicorp/consul#8472]
#### Feature Description

Can Hashicorp expose upstream service `circuit_breakers` and `retry_policy` configuration in `proxy.upstream[].config`?

#### Use Case(s)

As a service owner, I am using Consul's L7 router, splitter, and resolver configuration and I'm unable to create escape hatch configuration for `circuit_breakers` and `retry_policy`.

As a service owner, I find the escape hatch Envoy configuration complex for my needs.

### Reference:

https://www.consul.io/docs/connect/proxies/envoy#proxy-upstream-config-options

https://www.consul.io/docs/connect/proxies/envoy#escape-hatch-overrides

https://github.com/nicholasjackson/consul-escape-hatch-demo#consul-connect-escape-hatch-example

**Comment by dnephin** [comment]
Envoy `circuit_breakers` are exposed as limits (https://www.consul.io/docs/connect/proxies/envoy#limits) in the Upstream config. `retry_policy` is not exposed yet.

**Comment by GordonMcKinney** [comment]
@dnephin thank you for the clarification on limits. That's great news.

Is there a roadmap feature for `retry_policy`? TIA

**Comment by GordonMcKinney** [comment]
I'm going to close this issue and open a new issue for retry_polcy.
