### ISSUE TITLE
Support configuring Envoy retry_policy using Consul proxy.upstream[].config

### ISSUE THREAD

**Issue by GordonMcKinney** [hashicorp/consul#8475]
#### Feature Description

Can Hashicorp expose upstream service `retry_policy` configuration in `proxy.upstream[].config`?

#### Use Case(s)

As a service owner, I am using Consul's L7 router, splitter, and resolver configuration and I'm unable to create escape hatch configuration for `retry_policy`.

As a service owner, I find the escape hatch Envoy configuration complex for my needs.

### Reference:

https://www.consul.io/docs/connect/proxies/envoy#proxy-upstream-config-options

https://www.consul.io/docs/connect/proxies/envoy#escape-hatch-overrides

https://github.com/nicholasjackson/consul-escape-hatch-demo#consul-connect-escape-hatch-example

**Comment by blake** [comment]
Support for configuring `retry_on` in the service-router config entry was added by PR #12890, and will be available in Consul 1.14.

**Comment by GordonMcKinney** [comment]
Thank you! :-)
