### ISSUE TITLE
HTTP error code from Consul: 500 Internal Server Error           

### ISSUE THREAD

**Issue by hanxiaole** [hashicorp/consul#848]
when i run command : consul agent -server -data-dir /tmp/consul_root -config-dir /etc/consul.d  -ui-dir /var/dist -bootstrap -client 0.0.0.0 , the browser print out error: 
"HTTP error code from Consul: 500 Internal Server Error
          This is an error page for the Consul web UI. You may have visited a URL that is loading an unknown resource, so you can try going back to the root.

Otherwise, please report any unexpected issues on the GitHub page. " and the console print " 2015/04/08 15:23:51 [ERR] http: Request /v1/internal/ui/services?dc=undefined&token=, error: No path to datacenter" .  
However, it's ok to access the ui by create a ssh tunnel .

**Comment by ryanuber** [comment]
Thanks for reporting this. The `undefined` makes me think maybe this is a javascript problem in the UI. @pearkes any ideas here?

**Comment by pearkes** [comment]
We display that error when we receive an error from the Consul cluster. From the same machine, as the browser would, can you curl the consul API?

**Comment by pearkes** [comment]
Error could also be unable to connect over HTTP.

**Comment by ryanuber** [comment]
There is an error coming from the consul API. Consul returns a 500 because the requested DC is invalid, but in the log, the requested DC == `undefined`. I know the constant `undefined` is a javascript thing, which is why I thought maybe this was related to the UI specifically.

**Comment by andrewmeissner** [comment]
Any word on this being fixed?

**Comment by PierluigiRiti2** [comment]
any update on this?

**Comment by PierluigiRiti2** [comment]
I debug the error happen to me and find the possbile root the message is "No cluster leader"

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
