### ISSUE TITLE
Consul Go client Config taking a single consul server address

### ISSUE THREAD

**Issue by abronan** [hashicorp/consul#849]
Is there any way to specify multiple addresses in `Config` at client creation?

If I look at the `Config` struct in **api.go**:

```
// Config is used to configure the creation of a client
type Config struct {
	// Address is the address of the Consul server
	Address string

    [...]
```

There is no way to specify an array of addresses and handle the failover of a consul server in client's side. I'm probably missing something obvious but do I need to create a client for each consul server and handle the failover logic myself?

Thanks!

**Comment by ryanuber** [comment]
@abronan You are right that the client has no way of handling failover on its own. Normally we rely on Consul's DNS server for this. If you are able to resolve the .consul zone, then you could just point your api client at consul.service.consul, which should always return a healthy consul server node.

Hope that helps!

**Comment by abronan** [comment]
Thanks for the quick answer @ryanuber! It's everything I wanted to know ;-)

**Comment by awishformore** [comment]
I'm sorry to resurrect such an old thread, but wouldn't multiple IPs be needed for bootstrapping a node, in case you are not sure which ones are healthy?
