### ISSUE TITLE
Learning Ingress Gateway has typo `dashboard.ingress.dc1.consul`

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#8533]
The learning tutorial for ingress gateways has a typo. It says to query the `dashboard` services with `dig`

```
dig @127.0.0.1 -p 8600 dashboard.ingress.dc1.consul. ANY
```

This doesn't make any sense since at no point was a service or ingress gateway with the name `dashboard` ever defined. 
`dashboard.ingress.dc1.consul` should probably say `counting.ingress.dc1.consul` (Though I can't be positive because I'm running into other issues with the tutorial). 

https://learn.hashicorp.com/tutorials/consul/service-mesh-ingress-gateways

**Comment by jsosulska** [comment]
Hi @spuder , thanks for bringing this up. Our Learn guides are actually updated separately from our products.
At the bottom of the guide you will find "Was this guide helpful?" After selecting an option, a freeform box is available for you to include your feedback.
This is preferable as it gives direct feedback to our Education team, as well as identifies the specific guide you are referencing.
Thank you for your time. I will close this thread, and have let the education team know. For further questions, see our [Discuss forum](discuss.hashicorp.com). Our very helpful community can often help where others can't!

**Comment by spuder** [comment]
Thanks. I've submitted feedback via the link.

**Comment by danielehc** [comment]
Fixed internally at https://github.com/hashicorp/learn/pull/2238

The tutorial should now show the correct service:

```
dig @127.0.0.1 -p 8600 counting.ingress.dc1.consul. ANY
```

thanks @spuder for the catch.
