### ISSUE TITLE
Issue with syntax "has no field or method Cleanup"

### ISSUE THREAD

**Issue by ajeetas** [hashicorp/consul#8538]
#### Overview of the Issue : **we are trying to run suite with one test case/envoy version**
make test-envoy-integ ENVOY_VERSIONS="1.11.2" FILTER_TESTS="gateways-local"

root@ubuntu:~/consul/consul#  make test-envoy-integ ENVOY_VERSIONS="1.11.2" FILTER_TESTS="gateways-local"
==> Building Consul - OSes: linux, Architectures: amd64
Building sequentially with go install
--->   linux/amd64
# github.com/hashicorp/consul/sdk/testutil
sdk/testutil/io.go:48:3: t.Cleanup undefined (type *"testing".T has no field or method Cleanup)
sdk/testutil/io.go:74:3: t.Cleanup undefined (type *"testing".T has no field or method Cleanup)
sdk/testutil/server.go:240:28: cannot use t (type "testing".TB) as type CleanupT in argument to defaultServerConfig:
        "testing".TB does not implement CleanupT (missing Cleanup method)
sdk/testutil/testlog.go:14:41: cannot use t (type "testing".TB) as type CleanupT in argument to NewLogBuffer:
        "testing".TB does not implement CleanupT (missing Cleanup method)
ERROR: Failed to build Consul for linux/amd64
GNUmakefile:190: recipe for target 'linux' failed
make: *** [linux] Error 1

P.S.
I have ran the test cases with go version 1.13 and also with 1.1.3.3. both are having same issue.

**Comment by rboyer** [comment]
The `master` branch of Consul assumes a Go version of `v1.14.7`. The `*testing.T` type picked up a `Cleanup()` method in go `>=1.14.0`.

**Comment by preetapan** [comment]
Closing based on comment above - these tests require using Go 1.14.7 or above.
