### ISSUE TITLE
Reassert ownership of a lock

### ISSUE THREAD

**Issue by fraenkel** [hashicorp/consul#855]
My latest dilemma is re-acquiring sessions and locks.
In the case where a connection breaks in the monitor lock, I understand the requirement to report the lock is lost.
I am able to renew my session which means it wasn't lost yet, but if I attempt to acquire a lock which my session does own, I block. And since I have renewed my session, the lock will continue to be held.
Seems like the client code should allow a lock.Lock() to detect that I still own the lock and skip the acquire phase.

**Comment by armon** [comment]
@fraenkel Good call, that should be an easy enough check! Tagging as bug

**Comment by james-maloney** [comment]
+1

**Comment by armon** [comment]
Fixed by #861
