### ISSUE TITLE
The server is http2.

### ISSUE THREAD

**Issue by HaoLife** [hashicorp/consul#8565]
When the check is executed, the service returns an error when HTTP2 is turned on.

**Comment by jsosulska** [comment]
Hi @HaoLife 

Currently, there is an open feature request for HTTP2 health checks: https://github.com/hashicorp/consul/issues/6260 and PR here: https://github.com/hashicorp/consul/pull/8431. Feel free to 👍 or add your use case to the issue or PR, or add additional comments on the implementation. 

For general questions, please see our [Discuss Forum](https://discuss.hashicorp.com/c/consul/29).

Best
