### ISSUE TITLE
Consul Service Mesh with Kiali Integration

### ISSUE THREAD

**Issue by ashwinkupatkar** [hashicorp/consul#8570]
Hello Consul Team,

Wanted to check, if there is any plan to bring support for integrating service mesh with Kiali for more observability features apart from prometheus integration.

Currently their is lack of Visualization to see what services are communicating to one another (service graphs), the applied intentions and other features similar to what kiali provides while integrating with Istio

Do let me know on this ?

Thanks

**Comment by jsosulska** [comment]
Hi @ashwin-venkatesh, 

Thank you for your request. We're looking at improving the workflow around visualizations in the future.  With those improvements, we're weighing a lot of different workflows and integrations, and as solutions are developed, you can be sure we'll be letting folks know 😄 
If you would like, I can mark this issue as a feature request specifically for Kiali integrations. That way, as other community members interested in kiali integrations can vote this issue up.
Best,

**Comment by ashwin-venkatesh** [comment]
Hey @jsosulska ,

You might have the wrong Ashwin here 😄

**Comment by jsosulska** [comment]
> Hey @jsosulska ,
> 
> You might have the wrong Ashwin here 😄

Sorry @ashwin-venkatesh . My bad on tagging v.v XD

**Comment by jsosulska** [comment]
@ashwinkupatkar (I checked this time!) Updated the title to make this specifically about Kiali support, as there weren't any tickets so far.

**Comment by david-yu** [comment]
Will close this issue as we don't have plans to support a Kiali integration and look to provide native service visualization capabilities within the Consul UI. If you do have any asks for service visualization within the Consul UI please file issues related to specific use case you'd like to see addressed. Thanks!
