### ISSUE TITLE
Is consult 1.8.3 compatible with 1.2.3?

### ISSUE THREAD

**Issue by xu644629187** [hashicorp/consul#8574]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by jsosulska** [comment]
Hello @xu644629187 ,

This question is better suited for our [Discuss Forums](https://discuss.hashicorp.com/c/consul/29), where the community can help you. I will be closing this issue in the meantime.

I am unsure if you are asking about 2 different versions of Consul, but I recommend looking at [Upgrading specific versions of Consul](https://www.consul.io/docs/upgrading/upgrade-specific). In short - no, those two versions would be incompatible. 

I hope this helps :) Happy Coding
Jono
