### ISSUE TITLE
ServiceRegister got blocked, no timeout to fast failure

### ISSUE THREAD

**Issue by seanjoe** [hashicorp/consul#8605]
the consul is 1.6.0
when our consul machine come accoss some problem, the consul couldn't reach. while my app register it to consul. it got block for ever.

the config is the default config `api.DefaultConfig()`.when i debug, i found it block on `c.config.HttpClient.Do(req)` --http `c.send(req, deadline)`.
is there some params to let the register fast failed?

**Comment by dnephin** [comment]
Thank you for opening this issue! It looks like some of the requests support a `context.Context`, but this one did not. I opened #8609 which adds a context so that requests can be timed out. There's an example in the test case that shows how to use it.

**Comment by seanjoe** [comment]
Thanks @dnephin , fast response. The context make it sense.
