### ISSUE TITLE
Debian package does not load systemd unit after install

### ISSUE THREAD

**Issue by satwell** [hashicorp/consul#8625]
#### Overview of the Issue

Installation of the Hashicorp Debian packge of consul does not reload the systemd daemon configuration.  This results in commands such as `systemd enable consul` failing with the error message `Unit consul.service could not be found.`

The workaround is to manually run `systemctl daemon-reload` after installing the package.

This is caused by a bug in consul's `postinst` script.  From `/var/lib/dpkg/info/consul.postinst`:

```shell
if [ -f "/usr/bin/systemctl" ] && [ $(systemctl status consul | grep -c "Loaded: loaded") -eq 1 ]; then
    systemctl daemon-reload
fi
```

The `systemctl` binary lives in `/bin`, not `/usr/bin`, at least on Debian Buster, so the if block never runs.  There's a second bug here too.  If a package update includes a different systemd unit file, it won't get loaded until the user reboots or installs/updates a different package with a systemd unit.

One possible fix for both bugs would be to replace the above if block with:

```shell
if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
```

This is close to what debhelper would give you.  (Another option would be to just use debhelper.)

#### Reproduction Steps

1. Install the consul package from the Hashicorp apt repository, following the directions at https://learn.hashicorp.com/tutorials/consul/get-started-install#install-consul for Linux Ubuntu/Debian.
1. Run `systemd enable consul`.  This should enable the consul unit, but instead prints an error: `Unit consul.service could not be found.`

### Consul info for both Client and Server

N/A

### Operating system and Environment details

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

```
# apt-policy consul
consul:
  Installed: 1.8.3-2
  Candidate: 1.8.3-2
  Version table:
 *** 1.8.3-2 1001
        500 https://apt.releases.hashicorp.com buster/main amd64 Packages
        100 /var/lib/dpkg/status
[...]
```

### Log Fragments

N/A

**Comment by kpenfound** [comment]
Hi @satwell , thanks for reporting this!

I haven't run into this case yet, definitely curious
```
vagrant@buster:~$ which systemctl
/usr/bin/systemctl
vagrant@buster:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

I agree that checking against `-d /run/systemd/system` is a better way to go here. I've updated the packaging scripts with this change and new packages will be generated shortly.

**Comment by satwell** [comment]
Thanks for the quick turnaround!

@kpenfound, it's strange that you have a `/usr/bin/systemctl`.  This doesn't exist for me anywhere I've checked, including a freshly installed GCE debian-10 instance.  Running `dpkg -S /usr/bin/systemctl` should tell you if it's owned by a package.

There does seem to be a systemctl package in Debian that owns `/usr/bin/systemctl`:

```
# apt-get install apt-file && apt-file update
# apt-file search /usr/bin/systemctl
systemctl: /usr/bin/systemctl
```

But, confusingly, this package isn't part of systemd.  It's the package for https://github.com/gdraheim/docker-systemctl-replacement.  And it's only in buster-backports, so definitely not in a default install.

**Comment by kpenfound** [comment]
That's interesting. I'm using the vagrant `debian/buster64` box, which was probably packaged in a different way than the standard iso.  At least going forward this will be compatible with either install location. It looked like there are a few debian distros that use `/bin` while most other distros are using `/usr/bin`

**Comment by satwell** [comment]
My curiosity finally got the best of me, and I tracked down the discrepancy here between `/bin/systemctl` and `/usr/bin/systemctl`.

The `debian/buster64` vagrant box has a merged `/bin` and `/usr/bin`.  Which means that `/bin` is a symlink to `/usr/bin`.  Apparently this is the default now.  But confusingly, Debian didn't make this change with the release of Buster, but rather in a debootstrap change that probably went into some buster point release.  So older buster installs won't have them merged, and newer buster installs will.  There's [more info](https://wiki.debian.org/UsrMerge) in the Debian Wiki.

**Comment by kpenfound** [comment]
Interesting, nice work looking into it! I was aware of that merge, but at the point of me looking into it, Buster had the change.  My (bad) assumption was that Buster must have had this from the start!
