### ISSUE TITLE
consul/api/watch/funcs.go:makeQueryOptionsWithContext，add wait params for blocking

### ISSUE THREAD

**Issue by YK-peng** [hashicorp/consul#8626]
#### Feature Description

``` go
func makeQueryOptionsWithContext(p *Plan, stale bool) consulapi.QueryOptions {
	ctx, cancel := context.WithCancel(context.Background())
	p.setCancelFunc(cancel)
	opts := consulapi.QueryOptions{AllowStale: stale}
	switch param := p.lastParamVal.(type) {
	case WaitIndexVal:
		opts.WaitIndex = uint64(param)
	case WaitHashVal:
		opts.WaitHash = string(param)
	}
	opts = *opts.WithContext(ctx)
        opts.WaitTime = p.XXXXX//  from watch.Parse to Plan
        return opts
}
```

#### Use Case(s)

service watch，can control the wait time for blocking。

**Comment by jsosulska** [comment]
Hello @YK-peng ,

Please open a PR for code review. 

Can you please include your usecase for this change, tests, and an what this change can affect.

See our [Contributing Guidelines](https://github.com/hashicorp/consul/blob/master/.github/CONTRIBUTING.md#making-changes-to-consul) for how to do this. 

Best
