### ISSUE TITLE
Debian package does not restart consul service after upgrade

### ISSUE THREAD

**Issue by victor-sudakov** [hashicorp/consul#8644]
#### Overview of the Issue

After "apt upgrade", the consul package is upgraded but the agent itself is not restarted.

#### Reproduction Steps

1. Run "apt upgrade"
1. Run "systemctl status consul" or "consul members" and notice that the old agent binary is still running.

### Consul info for both Client and Server

Package: consul
Version: 1.8.3-3
APT-Sources: https://apt.releases.hashicorp.com buster/main amd64 Packages

### Operating system and Environment details
Debian 10 buster amd64

### Suggested solution

Some mechanism is  needed in accordance with https://sources.debian.org/src/dpkg/1.20.5/doc/triggers.txt/

**Comment by kpenfound** [comment]
Hi @victor-sudakov , thanks for reporting this! I agree the upgrade should trigger a service restart. I'll update the packaging scripts and post back here when that is available.

**Comment by kpenfound** [comment]
Thanks again for bringing this up! The latest version, `consul_1.8.4-3` has the proper service restart trigger. This means that it will restart consul upgrading _from_ 1.8.4-3 onward.

Cheers!

**Comment by victor-sudakov** [comment]
Thank you for the quick reaction.
