### ISSUE TITLE
invalid config key node - Bootstrap the ACL system

### ISSUE THREAD

**Issue by 94bharathraj** [hashicorp/consul#8688]
Hi

I am using Consul v1.8.0

I have a working cluster with TLS certificates and Gossip encryption key setup.

I am trying to integrate ACL following below documentation
https://learn.hashicorp.com/tutorials/consul/access-control-setup-production

But i am facing below error

**$/usr/bin/consul agent -config-dir=/etc/consul.d/ -data-dir=/var/consul
==> Error parsing /etc/consul.d/consul-server-one-policy.hcl: 1 error occurred:
	* invalid config key node**

I suspect the option for "node" does not exist , is the documentation up to date ?

and file content of consul-server-one-policy.hcl:

**node "consul-server-one" {
  policy = "write"
}**

**Comment by 94bharathraj** [comment]
Folks would appreciate help

**Comment by blake** [comment]
Hi @94bharathraj, ACL configuration cannot be specified as part of the agent configuration. ACLs must be configured using the [`consul acl policy`](https://www.consul.io/commands/acl/policy) commands, or [/acl/policy](https://www.consul.io/api-docs/acl/policies) HTTP APIs.

For example, the [Create the agent policy](https://learn.hashicorp.com/tutorials/consul/access-control-setup-production#create-the-agent-policy) section in the guide you linked uses the `consul acl policy create` command to write the configuration to Consul.

```shelll-session
$ consul acl policy create \
  -name consul-server-one \
  -rules @consul-server-one-policy.hcl
```

The additional policies in that doc are accompanied by similar `acl policy create` commands.

**Comment by 94bharathraj** [comment]
i have followed the same , but still it's still pointing to the same error.  
I did create the policy using the same command as per guide.

**$consul acl policy list -token=XXXXX**
**consul-server-one:
   ID:           baed6b7e-24dc-3cf7-7b41-38ccebfca8e2
   Description:
   Datacenters:**

I think it has something to do with the syntax

**Comment by blake** [comment]
@94bharathraj Have you removed `consul-server-one-policy.hcl` from `/etc/consul.d/`? Consul will not be able to start if unknown or invalid configuration is present within the `-config-dir`.

**Comment by 94bharathraj** [comment]
I did not think that could cause issue .
Thank you so much ! 
Yes its working now !

**Solution: Keep /etc/consul.d/ clean 
                Do not keep policy file inside the configuration**

**Comment by 94bharathraj** [comment]
@blake  There is a followup - question on this 
I would really appreciate your help on this

I was able to bootstrap ACL in the existing cluster .And things worked fine .


But how do i add a completely new client into the cluster  [ couldn't find any docs on adding a new client ]
I am trying not to change anything in server config and achieve this.

Server config file
**consul.hcl**
```
{
  "server":true,
  "encrypt":"XXXXXXXXX",
  "verify_incoming": true,
  "verify_outgoing": true,
  "ca_file": "/etc/consul.d/consul-agent-ca.pem",
  "cert_file": "/etc/consul.d/dctest-server-consul-0.pem",
  "key_file": "/etc/consul.d/dctest-server-consul-0-key.pem",
  "auto_encrypt": {
    "allow_tls": true
  },
  "performance": {
     "raft_multiplier":1
  },
  "acl": {
  "enabled":true,
  "default_policy":"deny",
  "enable_token_persistence":true
  },
  "bootstrap_expect": 3,
  "ui":true,
  "client_addr": "0.0.0.0",
  "retry_join": ["server-consul-02.XXXXXX","server-consul-03.XXXXXX"]
}
```






Below is my config file for the **new client** that i am trying to add [ Same config as an existing client already reporting to consul server]
**consul.hcl**
```
{
  "encrypt":"XXXXXXXXXXX",
  "verify_incoming": false,
  "verify_outgoing": true,
  "ca_file": "/etc/consul.d/consul-agent-ca.pem",
  "auto_encrypt": {
    "tls": true
  },
  "acl": {
     "enabled":true,
     "default_policy":"deny",
     "enable_token_persistence":true,
      "tokens": {
      "agent":"XXXXXXX"
    }
   }
  "retry_join": ["server-consul-01.XXXXXX","server-consul-02.XXXXXX","server-consul-03.XXXXXX"]
}
```


Following is the error that i am facing
**$ /usr/bin/consul agent -config-dir=/etc/consul.d/ -data-dir=/var/consul**
```
==> Starting Consul agent...
           Version: 'v1.8.0'
           Node ID: '020295f8-8c18-74d0-59bf-8596a9c1dd5c'
         Node name: 'shared-consul-07.XXXXXXXX.com'
        Datacenter: 'dc1' (Segment: '')
            Server: false (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 10.50.75.72 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: true, TLS-Outgoing: true, TLS-Incoming: false, Auto-Encrypt-TLS: true

==> Log data will now stream in as it occurs:

    2020-09-16T12:50:17.399Z [WARN]  agent: Node name will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.: node_name=shared-consul-07XXXXXXX.com
    2020-09-16T12:50:17.400Z [INFO]  agent.client.serf.lan: serf: EventMemberJoin: shared-consul-07.XXXXXXXXXXX.com 10.XX.XX.12
    2020-09-16T12:50:17.400Z [WARN]  agent.client.manager: No servers available
    2020-09-16T12:50:17.523Z [WARN]  agent.client: AutoEncrypt failed: error="rpcinsecure error making call: rpcinsecure error making call: Permission denied"
    2020-09-16T12:50:17.632Z [WARN]  agent.client: AutoEncrypt failed: error="rpcinsecure error making call: Permission denied"
    2020-09-16T12:50:17.632Z [WARN]  agent.client: retrying AutoEncrypt: retry_interval=41.923635104s
```

**Comment by blake** [comment]
@94bharathraj I recommend creating a post on our community forum at https://discuss.hashicorp.com/ to debug this issue further. It might be helpful to include the ACL policy assigned to the node's token, and well as using the [`consul keyring -list`](https://www.consul.io/commands/keyring#consul-keyring) command to verify the gossip key defined in this agent's config matches the key currently in use by the rest of the cluster.

**Comment by 94bharathraj** [comment]
@blake Thank you for the reply 
Sure i'll post it in that forum if i continue to have this issue.

I'll troubleshoot using consul keyring-list meanwhile
