### ISSUE TITLE
Add host header for terminating gateway services addressed by host name

### ISSUE THREAD

**Issue by freddygv** [hashicorp/consul#8707]
Currently, terminating gateways do not attach the host header for requests to an HTTP service addressed by a hostname.

This means that requests to these services can result in a 404 error if the hostname is not provided by the client.

Envoy has the possibility of automatically rewriting the host header based on the hostname of the upstream cluster: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-auto-host-rewrite

Terminating gateways should become aware of the destination service's protocol and set a catch-all route with this flag enabled.

**Comment by lawliet89** [comment]
I second this. I bumped into this issue when I was trying out terminating gateway.

**Comment by mikemorris** [comment]
Fixed in #9042
