### ISSUE TITLE
Systemd service does not work properly if TLS/tokens are enabled.

### ISSUE THREAD

**Issue by apollo13** [hashicorp/consul#8717]
The shipped systemd service file executes `consul leave` and `consul reload` on `ExceStop` and `ExecReload`. This generally does not work if access to the node is secured via TLS/tokens etc.

The current service file look like this:
```
[Service]
User=consul
Group=consul
ExecStart=/usr/bin/consul agent -config-dir=/etc/consul.d/
ExecReload=/usr/bin/consul reload
ExecStop=/usr/bin/consul leave
KillMode=process
Restart=on-failure
LimitNOFILE=65536
```
I think it would be good if `ExecStop`/`ExecReload` used signals like the nomad service file does. This way stop & reload would work independent on whether access to consul is restricted or not.

**Comment by kpenfound** [comment]
Hi @apollo13 , thanks for opening this!  After some internal discussion, we have changed the packaged systemd file to use signals.  This will be available starting with the consul-1.8.5-2 package.

The new service block looks like:
```
[Service]
User=consul
Group=consul
ExecStart=/usr/bin/consul agent -config-dir=/etc/consul.d/
ExecReload=/bin/kill --signal HUP $MAINPID
KillMode=process
KillSignal=SIGTERM
Restart=on-failure
LimitNOFILE=65536
```

Thanks again for raising this!
Kyle
