### ISSUE TITLE
Document signals involved in a graceful shutdown.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul#877]
I spent some time figuring out this as I needed to declare in Upstart what a normal exit is in Consul, so that `consul leave` works and the process is not re-spawned again by Upstart.

**Comment by c4milo** [comment]
Please correct me if I'm wrong, the only graceful shutdown signal I found was SIGINT with exit status 0.

**Comment by sethvargo** [comment]
Here's a sample upstart script:

```conf
description "consul"

start on runlevel [2345]
stop on runlevel [06]

respawn
post-stop exec sleep 5
normal exit 0 INT
kill signal INT

exec /usr/local/bin/consul agent \
  -config-dir="/etc/consul.d"
```
