### ISSUE TITLE
Support changing service tags via checks

### ISSUE THREAD

**Issue by Gufran** [hashicorp/consul#8773]
#### Feature Description

Allow a service to update its tags via health checks. A service with multiple health checks should be able to indicate enabled tags by marking a health check as critical or passing.

#### Use Case(s)

Imagine a storage server of some kind that supports replication, lets say it has following commands:

 1. `REPLICATE IP PORT` - to start replication from `IP:PORT`
 1. `REPLICATE off` - to stop replication

It runs with a sidecar that has two HTTP endpoints to indicate the current status of the leader:

 1. `health/leader` - return `200 OK` if the server is the leader, `429` otherwise.
 2. `health/follower` - returns `200 OK` if the server is a follower, `429` otherwise.

The sidecar also attempts to maintain leadership status by acquiring a lock in consul. Depending on the state of the lock the sidecar returns appropriate status code on health endpoints and runs the appropriate `REPLICATE` command on its server.

Other services want to be able to connect to a server node based on whether it is a leader or a follower.
Right now this can be achieved by registering two services in consul catalog with one health check each. the health endpoints being mutually exclusive will always make sure that every node has only one passing service and one critical. Other services can then connect to `the-leader.service.consul` or `a-follower.service.consul`.

This method does not play nice with a lot of things because one of the health checks will never become healthy. It will cause problems with deployments and monitoring etc.

The other method — that is being proposed here — could be to register only one service in consul catalog with two health checks on it, and each health check has a list of tags that will be added to the service when that check is healthy.

These two checks can have same name if necessary so that the detail is not exposed to the deployment or monitoring system and the service is only marked as failed when both checks are failing.

----

Following is a service stanza from a hypothetical nomad jobspec to demonstrate the idea:

<details>

```
    service {
      name = "server"
      port = "server"

      connect {
        sidecar_service {}
      }

      # failing this check will mark the service as failed
      check {
        name           = "alive"
        type           = "tcp"
        port           = "server"
      }

      # failing the following two checks at once will mark the service as failed.
      # marking the first as critical and second as healthy will keep the service healthy and add tag `leader` to it
      # marking the first healthy and second critical will keep the service healthy and add tag `follower` to it.
      # marking any of them critical will remove that tag from the service.
      check {
        name           = "leadership-status"
        initial_status = "warning"
        type           = "http"
        protocol       = "http"
        port           = "sidecar"
        method         = "GET"
        path           = "/health/leader"
        tags           = ["leader"]
      }

      check {
        name           = "leadership-status"
        initial_status = "warning"
        type           = "http"
        protocol       = "http"
        port           = "sidecar"
        method         = "GET"
        path           = "/health/follower"
        tags           = ["follower"]
      }
    }
```

</details>

**Comment by jsosulska** [comment]
Hi @Gufran 

Thanks for posting. I appreciate the detailed description you left here. Please take a look at our [Leader Election](https://learn.hashicorp.com/tutorials/consul/application-leader-elections) guide. There is also our [distributed locking](https://learn.hashicorp.com/tutorials/consul/distributed-semaphore?in=consul/developer-configuration) guide that can help with your use case. Tags being added/removed based off of health is not a workflow that is sustainable as a feature.

I hope this helps with your usecase.
