### ISSUE TITLE
API Filtering Page could use examples of string quoting and some docs around when its necessary

### ISSUE THREAD

**Issue by mkeeler** [hashicorp/consul#8793]
The [API filtering page](https://www.consul.io/api-docs/features/filtering) has several examples of how the filtering language can be used. One thing that is missing is information about when values to be matched on may need to be quoted.

In general values that look like Go identifiers (alphanumeric + underscores) do not need quoting. However other things such as a hyphenated service name like `web-service` will require quoting in the expression. Then it would be useful to document that only the value to match on requires quoting and not the whole expression.

Example, if you have an intention to allow the `web-service` to communicate with other services and want to find all the intentions regarding its access the request would look like:

```sh
curl 'localhost:8500/v1/connect/intentions?filter=SourceName=="web-service"`
```

In particular the filter needs to be: `SourceName == "web-service"` with the value to match on being quoted.

**Comment by blake** [comment]
This should be resolved with the changes in #9202. The updated examples now show the value as being quoted in the filtering expression.

While quoting is not strictly necessary for all values, the updated examples should largely address the issues folks experienced by not quoting values which necessitated improving the docs.
