### ISSUE TITLE
Add/document reliable way to figure out if server node joined cluster successfully

### ISSUE THREAD

**Issue by discordianfish** [hashicorp/consul#880]
Hi,

I'm trying to create a AWS AutoScaling configuration to fully automate rolling upgrades of my consul nodes. The idea is that the ASG will terminate one instance, create a new one and wait with the next one until I signal success for the first one.
Now I need to know when a consul server node successfully joined the cluster (-> has all state and is part of the cluster), aka when it's save to kill another server node, so I can signal success.

I might be able to check if the node is in /v1/status/peers but I'm not sure this goes through the raft log and is guaranteed to be consistent. Or I assume that a node sucesffully joined as soon as /v1/status/leader returns something, but same here - I'm not sure about the consistency guarantees.

So *if* there is a way to programatically tell that a node successfully joined it should be documented. If not, I think it would be useful to have a API endpoint for that.

**Comment by armon** [comment]
The `/v1/status/peers` does require a Raft log to be updated, so if that is updated, then you should be good to go!

**Comment by discordianfish** [comment]
@armon Great, thanks! I think this should be documented? I'd say this is a concern everyone who is replacing nodes in the cluster automatically has. But I'm good, so feel free to close this ticket if you want.
