### ISSUE TITLE
base auth url @ escaped

### ISSUE THREAD

**Issue by mj520** [hashicorp/consul#8811]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl ...`
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
/ #  curl https://mj520:123456@consul.8866.info/v1/kv/key
[
    {
        "LockIndex": 0,
        "Key": "key",
        "Flags": 0,
        "Value": "IyEvYmluL3NoCmlmIFsgIiRDT05TVUxfS0VZRklMRSIgPSAiIiBdO3RoZW4KICAgIGVjaG8gIkNPTlNVTF9LRVlGSUxFIGlzIGVtcHR5IgogICAgZXhpdCAxCmZpCndoaWxlIHRydWU7ZG8KICAgIGtmX2FycmF5PSR7Q09OU1VMX0tFWUZJTEUvLywvIH0KICAgIGZvciBrZmEgaW4gJGtmX2FycmF5O2RvCiAgICAgICAga2V5PSR7a2ZhJToqfQogICAgICAgIGZpbGU9JHtrZmEjKjp9CiAgICAgICAgcGVyZml4PSR7a2V5OjA6MX0KICAgICAgICBpZiBbICIkcGVyZml4IiA9ICIvIiBdO3RoZW4KICAgICAgICAgICAga2V5PSR7a2V5OjF9CiAgICAgICAgZmkKICAgICAgICBpZiBbICIkQ09OU1VMX09QVCIgPSAicHV0IiBdO3RoZW4KICAgICAgICAgICAgY29udGVudD1gY2F0ICR7ZmlsZX1gCiAgICAgICAgICAgIGNvbnN1bCBrdiBwdXQgJHtrZXl9ICIke2NvbnRlbnR9IgogICAgICAgIGVsc2UKICAgICAgICAgICAgY29uc3VsIGt2IGdldCAke2tleX0gPiAke2ZpbGV9CiAgICAgICAgZmkKICAgIGRvbmUKICAgIHNsZWVwICRDT05TVUxfSU5URVJWQUwKZG9uZQ==",
        "CreateIndex": 13,
        "ModifyIndex": 2170
    }
]
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here

/ # env
CONSUL_VERSION=1.8.4
HOSTNAME=faf988230330
SHLVL=1
CONSUL_OPT=put
HOME=/root
CONSUL_KEYFILE=key:/start.sh
TERM=xterm
HASHICORP_RELEASES=https://releases.hashicorp.com
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CONSUL_INTERVAL=60
CONSUL_HTTP_ADDR=https://mj520:123456@consul.8866.info
PWD=/
/ # consul kv get key
Error querying Consul agent: Get "https://mj520:123456%40consul.8866.info/v1/kv/key": dial tcp: lookup mj520:123456@consul.8866.info: no such host
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by blake** [comment]
Hi @mj520,

The [`CONSUL_HTTP_AUTH`](https://www.consul.io/commands#consul_http_auth) environment variable can be used to specify HTTP basic auth credentials.

Can you try setting your credentials using that environment variable and see if it resolves your issue?

**Comment by mj520** [comment]
OK, I still hope to support URL base auth directly, and server can support base auth directly

**Comment by blake** [comment]
@mj520 Did the `CONSUL_HTTP_AUTH` option work for you?

**Comment by mj520** [comment]
available，support URL base auth  Less parameters can be transmitted

**Comment by likeaxa** [comment]
@blake Hi, I donot know the CONSUL_HTTP_AUTH how to use
1. i docker pull consul and run it commend （docker run -p 8500:8500/tcp -e 'CONSUL_HTTP_AUTH="admin:admin"' consul agent -server -ui -bootstrap-expect=1 -client=0.0.0.0） 
2 and i test the url  ，it is not work
3 then i exec the container and export CONSUL_HTTP_AUTH="admin:admin and  consul reload ，it is not work too
4 how i need to do ，it  can work

**Comment by blake** [comment]
@likeaxa,

`CONSUL_HTTP_AUTH` designed to be used when Consul's HTTP API is accessed through a reverse proxy which requires HTTP basic authentication. The environment variable needs to be set prior to executing commands using the Consul CLI. For example:

```shell
$ export CONSUL_HTTP_AUTH="admin:admin"
$ consul members
Node          Address         Status  Type    Build  Protocol  DC   Segment
e60602518592  127.0.0.1:8301  alive   server  1.9.0  2         dc1  <all>
```
