### ISSUE TITLE
Use consul DNS with Windows DNS server

### ISSUE THREAD

**Issue by florentvaldelievre** [hashicorp/consul#883]
I am trying to setup our DNS server hosted on windows in order to target our consuls instances when a client requests something within the 'consul' zone.
As far as I understand, we need to setup either a Forward Lookup zone or a Stub Zone on our master DNS.

**Setup**
Our master DNS: 192.168.1.130
Our consul instances: 192.168.1.190, 200, 210

All our clients have 192.168.1.130 as primary DNS.
They need to be able to resolve **.consul. In another hand, everything ending with '.consul' needs to be forwarded to consul.

````
[shopmedia@staging3:~] $dig @192.168.1.190 postfix.service.consul SRV

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.30.rc1.el6 <<>> @192.168.1.190 postfix.service.consul SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11013
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 3

;; QUESTION SECTION:
;postfix.service.consul.                IN      SRV

;; ANSWER SECTION:
postfix.service.consul. 0       IN      SRV     1 1 2500 staging5.node.staging.consul.
postfix.service.consul. 0       IN      SRV     1 1 2500 staging3.node.staging.consul.
postfix.service.consul. 0       IN      SRV     1 1 2500 latest.node.staging.consul.

;; ADDITIONAL SECTION:
staging5.node.staging.consul. 0 IN      A       192.168.1.210
staging3.node.staging.consul. 0 IN      A       192.168.1.190
latest.node.staging.consul. 0   IN      A       192.168.1.201

;; Query time: 1 msec
;; SERVER: 192.168.1.190#53(192.168.1.190)
;; WHEN: Thu Apr 23 16:35:57 2015
;; MSG SIZE  rcvd: 378
````

Windows does not seem to recognize consul as an Authoritative zone.
Do you know if what i am trying to achieve is supported ?

PS: For some reason, it worked once for few minutes(despite error message saying that its not an Authoritative zone), and then went down. I never managed to make it work again.

**Error message on windows:**
https://www.dropbox.com/s/ql32tic5du8on9j/dns-1.jpg?dl=0
https://www.dropbox.com/s/yrxwvoxoewul5lk/dns-2.jpg?dl=0

Any feedback would be greatly appreciated

@mfischer-zd, @ryanuber and @armon you might have an idea

**Comment by florentvaldelievre** [comment]
FYI, the issue has been solved by adding 'consul' zone within a "Conditional Forwarder"

**Comment by rdgreis** [comment]
404 on dropbox images. :(
