### ISSUE TITLE
Comparison Graphs.

### ISSUE THREAD

**Issue by timothysc** [hashicorp/consul#885]
Are there any published comparison graphs on consul vs. etcd on: 

writes
reads
& watches ?

Against recent versions of etcd?

**Comment by ryanuber** [comment]
Hi @timothysc,
I'm not aware of any comparisons in this sense. We have a general feature comparison against various solutions available on the consul.io website, but otherwise I don't know that there have been any performance comparisons published for recent versions of consul vs. etcd.
