### ISSUE TITLE
HTTP service health check problem

### ISSUE THREAD

**Issue by mikerobins** [hashicorp/consul#889]
Hello,

I've just started using Consul but I'm having trouble when using certain characters in the check URL. I have an app (the RabbitMQ management plugin) that needs / sent as the escaped char seq, namely %2F instead of a / for the health check.

For example, the following fails:

"check":
  {
    "http": "http://user:pass@127.0.0.1:2222/api/checkme/%2F",
    "interval": "30s",
    "timeout": "10s"
  }

tcpdump shows the actual request being sent is 'http://user:pass@127.0.0.1:2222/api/checkme//' with a trailing / instead of %2F

I guess I could use a 'script' check and 'curl' instead but would rather not if possible.

I'm using Consul 0.5.

**Comment by ryanuber** [comment]
Hey @mikerobins,

Internally, we are just using Go's `net/http` to do the request, which always parses and unescapes the URL (you can follow this in the codepath [here](http://golang.org/src/net/http/request.go?s=15726:15798#L482)). To avoid this we would need to do some hand-crafting or dissection/replacement of certain parts of the request, so I would say that the best way to handle this for now is to just use a script.

**Comment by ryanuber** [comment]
Closing this one out, the workaround above is the best solution for this at the moment.

**Comment by Nirkus** [comment]
URL-emcoding the ```%``` character of the URL-encoded ```/``` character will probably do as a workaround for this issue (not verified):
```
"check":
{
"http": "http://user:pass@127.0.0.1:2222/api/checkme/%252F",
"interval": "30s",
"timeout": "10s"
}
```
