### ISSUE TITLE
ACL Tokens in UI must be re-entered during page reloads

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/consul#892]
Since the ACL tokens are currently not passed as part of the URL's in the UI, a page refresh can cause the user to need to re-enter their ACL token. It also prevents sharing a URL with a team, which could be useful if you wanted to pass around a read-only token in a direct link.

Original report is here: https://groups.google.com/forum/#!topic/consul-tool/4XItKG8jO4M
/cc @pearkes

**Comment by armon** [comment]
I think this is on purpose, to avoid leaking them. The token is saved in a cookie or local storage though. I'll let @pearkes comment.

**Comment by pearkes** [comment]
It should persist past refresh, that would be a bug. It's saved in local storage.

The only conceivable way to share it would be to tack it on to the query param, which as @armon noted would be pretty unsafe. But it's an option and doable.

Otherwise, don't know how you could share.

**Comment by sethvargo** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
