### ISSUE TITLE
chocolatey package received a patch that looks unpulled

### ISSUE THREAD

**Issue by petemounce** [hashicorp/consul#893]
[This comment](https://chocolatey.org/packages/consul#comment-1660768280) indicates that some enhancements have been submitted to the chocolatey package for consul.
* Use [NSSM](https://nssm.cc/) instead of WinSXW for service wrapper
* Support for -ia flag (whatever that is!)

I think because the repo isn't in a network connected to chocolatey, it might have been missed (?). The repo is at https://github.com/sitano/chocolatey-packages.

Where is the repo for the hashicorp-supported package? Perhaps @sitano or I can merge & re-PR.

**Comment by ryanuber** [comment]
Hey @petemounce,
I'm not sure I follow entirely, but there currently isn't an officially supported repo for anything like this. Any official Consul releases and code will be found either on this GitHub repo, or on the consul.io website. Please do let us know if you have found another source claiming to be officially HashiCorp supported.

**Comment by petemounce** [comment]
Hi @ryanuber 
* [this is the link to the chocolatey package](https://chocolatey.org/packages/consul)
  * the comments (scroll down) are what I'm talking about.
* I _think_ the package source is https://github.com/sitano/chocolatey-packages, and I would guess community-provided.
  * this is the maintainer: https://chocolatey.org/profiles/mirthy

However, the chocolatey package lists @mitchellh and @armon as authors, so I assumed it was owned by Hashicorp.

I've used the package to bootstrap my use on Windows nodes - it saved me needing to figure out a service wrapper and so forth.

**Comment by ryanuber** [comment]
That makes sense, thanks for clarifying. Mitchell, Armon, and HashiCorp are listed under Authors, and the Maintainers section I think is what indicates who is maintaining the package. Perhaps you can get in touch with @sitano directly about the changes?

BTW, it's great to see this kind of community initiative!

**Comment by ryanuber** [comment]
Closing this since the source for the package is maintained within the community and not in this repo.
