### ISSUE TITLE
[WARN] memberlist: Refuting a dead message between a KVM VM and a physical host

### ISSUE THREAD

**Issue by domrod** [hashicorp/consul#894]
Hi,

<h4>Environment</h4>

I use consul in the following environment :
- 2 physical hosts (with a public IP), say _host1_ and _host2_
- 1 VM (with a local IP) hosted in one of the physical hosts, say _vm0_ on _host1_
- 1 OpenVPN configured between the 2 hosts to expose the local VM IP to the other host

Here are the config files of the 3 environments

**host1** => bootstrap/config.json
{
  "server": true,
  "bootstrap": true,
  "datacenter": "dc",
  "node_name": "host1",
  "bind_addr": "167.1.2.3",
  "encrypt": "***********************==",
  "ca_file": "/consulpath/consul.d/ssl/ca.cert",
  "cert_file": "/consulpath/consul.d/ssl/consul.cert",
  "key_file": "/consulpath/consul.d/ssl/consul.key",
  "verify_incoming": true,
  "verify_outgoing": true,
  "data_dir": "/consulpath/data",
  "log_level": "INFO"
}

**host2** => server/config.json
{
  "server": true,
  "datacenter": "dc",
  "node_name": "host2",
  "bind_addr": "167.4.5.6",
  "encrypt": "********************==",
  "ca_file": "/consulpath/consul.d/ssl/ca.cert",
  "cert_file": "/consulpath/consul.d/ssl/consul.cert",
  "key_file": "/consulpath/consul.d/ssl/consul.key",
  "verify_incoming": true,
  "verify_outgoing": true,
  "data_dir": "/consulpath/data",
  "log_level": "INFO"
}

**vm0** => client/config.json
{
  "server": false,
  "datacenter": "dc",
  "node_name": "vm0",
  "bind_addr": "10.10.1.10",
  "encrypt": "********************==",
  "ca_file": "/consulpath/consul.d/ssl/ca.cert",
  "cert_file": "/consulpath/consul.d/ssl/consul.cert",
  "key_file": "/consulpath/consul.d/ssl/consul.key",
  "verify_incoming": true,
  "verify_outgoing": true,
  "data_dir": "/consulpath/data",
  "log_level": "INFO"
}

The VM **vm0** is based on KVM and uses a TAP interface.

<h4>Issue</h4>

From time to time (about ~1% of the total time), our monitoring sees some interruptions in the consul service.

On the other hand, the logs show the following:

On **vm0**
    2015/04/29 06:05:13 [INFO] consul: adding **host2** (Addr: 167.1.2.3:8300) (DC: dc)
    2015/04/29 06:05:33 [INFO] memberlist: Suspect **host2** has failed, no acks received
    2015/04/29 06:07:14 [WARN] memberlist: Refuting a suspect message (from: **host2**)
    2015/04/29 06:08:12 [WARN] memberlist: Refuting a suspect message (from: **host2**)
    2015/04/29 06:08:27 [WARN] memberlist: Refuting a suspect message (from: **host2**)
    2015/04/29 06:09:32 [INFO] memberlist: Suspect **host2** has failed, no acks received
    2015/04/29 06:10:01 [WARN] memberlist: Refuting a suspect message (from: **host2**)
    2015/04/29 06:10:22 [WARN] memberlist: Refuting a suspect message (from: **host2**)
    2015/04/29 06:11:22 [INFO] memberlist: Suspect **host2** has failed, no acks received
    2015/04/29 06:11:27 [WARN] memberlist: Refuting a suspect message (from: **host2**)
    2015/04/29 06:14:15 [WARN] memberlist: Refuting a suspect message (from: **host2**)

On **host2**
    2015/04/29 06:16:38 [INFO] memberlist: Marking **vm0** as failed, suspect timeout reached
    2015/04/29 06:16:38 [INFO] serf: EventMemberFailed: **vm0** 10.10.1.10
    2015/04/29 06:16:38 [INFO] serf: EventMemberJoin: **vm0** 10.10.1.10
    2015/04/29 06:17:21 [INFO] memberlist: Suspect **vm0** has failed, no acks received
    2015/04/29 06:18:20 [INFO] memberlist: Suspect **vm0** has failed, no acks received
    2015/04/29 06:18:32 [INFO] memberlist: Suspect **vm0** has failed, no acks received
    2015/04/29 06:18:37 [INFO] memberlist: Marking **vm0** as failed, suspect timeout reached
    2015/04/29 06:18:37 [INFO] serf: EventMemberFailed: **vm0**t 10.10.1.10
    2015/04/29 06:18:37 [INFO] serf: EventMemberJoin: **vm0** 10.10.1.10
    2015/04/29 06:18:43 [INFO] memberlist: Suspect **vm0** has failed, no acks received

So actions using Consul mainly succeed, excepted few ones. But those few fails are a true problem for us.

<h4>Discussion</h4>

I've seen the same kind of issue from people using Docker. I already tried to use "conntrack -F" to empty UDP cache, but it has no effect in my case.

Another interesting point is that we have exactly the same platform in another hoster environment, and we don't have this issue.

So, I'll be glad if somebody has some insight on the reasons that may cause the observed issue.

**Comment by Erfane** [comment]
Hello,

conntrack -F should have no effect as you're not creating/destructing virtual environnements.
Do you see constant UDP packet dropping on these environnements?

**Comment by ryanuber** [comment]
Hi @domrod, were you able to get this sorted out? At first glance it does sound like a network issue, as @Erfane pointed out above.

**Comment by domrod** [comment]
We still have some interruptions (~0.5%). We have been thinking also about some physical network issues between the 2 hosts. You're right, there is some packet monitoring to install to see if the issue may come from that.

**Comment by slackpad** [comment]
Closing this out since we didn't hear anything further.
