### ISSUE TITLE
Allow specifying a statsd namespace

### ISSUE THREAD

**Issue by grantr** [hashicorp/consul#898]
It's great that Consul can emit statsd metrics, but without a configurable namespace they aren't as helpful as they could be.

Currently, the namespace varies between `consul` and `consul.<fqdn>`. A configuration parameter like `statsd_namespace` would allow separate consul deployments to each write separate stats.

**Comment by ryanuber** [comment]
Thanks for the suggestion, marked as an enhancement!

**Comment by pwielgolaski** [comment]
I looked at the PR that close this issue and it is very misleading.

```
statsite_prefix The prefix used while writing all telemetry data to statsite. By default, this is set to "consul".
```
Documentation mention only statsite, but in fact in code this value can be used also for Statsd& DataDog 
https://github.com/hashicorp/consul/blob/5f140f197203d7be39f2da7a381272beaf4e777b/command/agent/command.go#L570

I think name should be change or at least description for option
