### ISSUE TITLE
Bind and drop privileges 

### ISSUE THREAD

**Issue by mitchellh** [hashicorp/consul#9]
Since Consul is meant to be able to act like a DNS server, it is preferable for it to be THE DNS server, running on port 53. Binding to this port requires root, but it is not ideal for consul itself to actually run as root. 

Consul should take a `-user` flag so it can `setuid` to that user after binding ports.

**Comment by sargun** [comment]
The other thing one can do here is use setcap.

**Comment by shibumi** [comment]
I strongly advise not to use setuid for this. It will give the process too much permissions. You should stick to a saner solution like giving the process  the kernel capability `CAP_NET_BIND_SERVICE`. This will only allow binding on port 1023, nothing else. You can easily set this capability via systemd service files.
