### ISSUE TITLE
sdk: figure out if we can stop doing our /tmp/consul-test temp dir workaround

### ISSUE THREAD

**Issue by rboyer** [hashicorp/consul#9050]
In `testutil.TempDir` in the `sdk` package we make our own temp directory at `/tmp/consul-test` for weird macOS reasons https://github.com/hashicorp/consul/blob/master/sdk/testutil/io.go#L23 

Figure out if these reasons are still valid and ideally stop doing any of this in favor of normal temp directory acquisition processes.

**Comment by jkirschner-hashicorp** [comment]
Closed by #10494
