### ISSUE TITLE
Deregistered node is not getting registered as service after rejoin

### ISSUE THREAD

**Issue by marc-** [hashicorp/consul#906]
I have consul (v0.5.0) server and two clients. Clients are part of 'web' service: 
```json
{
  "service": {
    "name": "web",
    "address": "192.168.33.37",
    "port": 8080,
    "tags": [
      "web"
    ]
  }
}
```
When I click deregister button on node in consul server UI, after a while node joins cluster again, but it never gets assigned to `web` service until I restart consul client on that node.
Client config:
```json
{
  "data_dir": "/var/lib/consul",
  "retry_join": [
    "192.168.33.33"
  ],
  "node_name": "client2",
  "advertise_addr": "192.168.33.37",
  "ports": {
    "dns": 8600,
"http": 8500,
"rpc": 8400,
"serf_lan": 8301,
"serf_wan": 8302,
"server": 8300
  },
  "leave_on_terminate": true
}
```

**Comment by armon** [comment]
@marc- This should already be fixed in master. Can you confirm? It will go out with Consul 0.5.1

**Comment by marc-** [comment]
Confirmed. Works for Consul v0.5.0-240-g739d1fd.dev (739d1fdf0343d56e8fc9cc194831673b8c162e31) .
