### ISSUE TITLE
怎么通过kong调用consul上注册的dubbo服务（dubbo协议，grpc协议）

### ISSUE THREAD

**Issue by 470139387** [hashicorp/consul#9064]
现在可以实现：通过kong调用consul上注册的http服务（使用consul的dns功能，kong的配置文件dns_resolver=127.0.0.1:8600）。
问题：怎么通过kong调用consul上注册的dubbo服务（dubbo协议，grpc协议）。不知道dubbo服务注册的服务名称是什么

**Comment by jsosulska** [comment]
Using https://github.com/istio/istio/issues/26712 to track.
