### ISSUE TITLE
Add metric type to key metrics tables

### ISSUE THREAD

**Issue by mkcp** [hashicorp/consul#9069]
#### Feature Description

On telemetry.mdx we do not mark the type of metric for each table under key metrics. It's important to know the type to understand how to work with them. An example of the intended table format can be found lower in the telemetry.mdx doc, where a type column is included after the description. This is an easy fix and a great first issue for contributors interested in Consul monitoring.

**Comment by rkuska** [comment]
👋🏻 @mkcp , I decided I want to try to contribute to consul and picked this issue as it is the most recent one marked as `type/good-first-issue`.  I just pushed the changes and opened MR to address this issue. https://github.com/hashicorp/consul/pull/9674
