### ISSUE TITLE
Hide metrics for ingress gateways in topology tab

### ISSUE THREAD

**Issue by freddygv** [hashicorp/consul#9075]
Currently mesh topology metrics aren't functional for Ingress Gateways:

1. The summary stats for the ingress gateway itself only account for TCP traffic.
2. The upstream stats are empty because listeners for ingress gateways are defined differently than sidecar listeners. The Prometheus provider does not account for these differences.

The fix to #1 is scheduled for the 1.9.x release cycle, so rather than displaying a partial fix in 1.9.0 we should just hide the functionality.

**Comment by kaxcode** [comment]
Fix in PR #9081
