### ISSUE TITLE
Specifying invalid datacenter in query args returns an 500 instead of 404

### ISSUE THREAD

**Issue by gmr** [hashicorp/consul#908]
When querying the KV database specifying an invalid datacenter value, consul returns a `500` `Internal Server Error` with a body of `No path to datacenter`. I believe this should be a `404` as a `500` generally indicates a problem occurred instead of the filtering criteria not returning any data.

This may be a duplicate of #848.

Example:

`curl http://localhost:8500/v1/kv/foo?dc=bar`

Output:

```
> GET /v1/kv/foo?dc=bar HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
* Server nginx is not blacklisted
< Server: nginx
< Date: Wed, 06 May 2015 00:24:14 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 21
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
No path to datacenter
```

**Comment by armon** [comment]
Yeah, the error codes are pretty bad currently. Basically 500 just indicates "problem". We should definitely have this be more buttoned down.

**Comment by slackpad** [comment]
Closing this as a dup of #848.
