### ISSUE TITLE
Automatic deregistering service health checks when removing a service?

### ISSUE THREAD

**Issue by Kosta-Github** [hashicorp/consul#913]
I would expect that when removing/deregistering a service that all service health checks associated to that specific service would also get deregistered automatically. This doesn't seem to be the case right now (version 0.5.0). If I remove a service the associated HTTP health check is still performed periodically (showing up in the consul logs but not within the consol UI).

Explicitly deregistering the service health check manually via a `curl` request against the `consul agent REST API` works. But I would expect to automatically remove the associated health checks when deregistering a servce...

**Comment by ryanuber** [comment]
@Kosta-Github this sounds like a bug, thanks for reporting!
