### ISSUE TITLE
Key-value stores per service?

### ISSUE THREAD

**Issue by devinrsmith** [hashicorp/consul#915]
Are there any plans to introduce key-value stores per service?

**Comment by ryanuber** [comment]
@devinrsmith not at this time. A pretty common use case is to use a `service/` top-level key, and namespace services within it, like:

```
.
└── service
    ├── postgres
    │   ├── key1
    │   └── key2
    └── redis
        ├── key1
        └── key2
```

Using ACL's you could also protect each keyspace with a different token if isolation is a concern. Does that cover your use case?

**Comment by devinrsmith** [comment]
Yep I figured building up a key would work... just thought I'd check since it is a "common use case".
