### ISSUE TITLE
Upgrade from to 1.8.5 results in consul being overwhelmed by nomad

### ISSUE THREAD

**Issue by dansteen** [hashicorp/consul#9169]
#### Overview of the Issue

We have been running a set of consul / vault / nomad clusters for 4 years.   We were previously on version 1.6.1 of consul, and decided to upgrade to 1.8.5.   The consul servers upgraded without issue, however, the agents running on each box now become overwhelmed by requests from nomad to the point that they are no longer able to resolve simple kv queries or respond to simple requests like `consul members`.   The response is typically something like this:

```Error retrieving members: Get "http://127.0.0.1:8500/v1/agent/members?segment=_all": EOF```

Once nomad jobs are drained off of that box we are able to resolve requests to consul again.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl ...`
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 4
        services = 4
build:
        prerelease =
        revision = 1e03567d
        version = 1.8.5
consul:
        acl = enabled
        known_servers = 5
        server = false
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 449
        max_procs = 8
        os = linux
        version = go1.14.9
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 44003
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 38012
        members = 51
        query_queue = 0
        query_time = 1759
```
</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 1
        checks = 1
        services = 1
build:
        prerelease =
        revision = 1e03567d
        version = 1.8.5
consul:
        acl = enabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.0.250.118:8300
        server = true
raft:
        applied_index = 290393846
        commit_index = 290393846
        fsm_pending = 0
        last_contact = 17.051241ms
        last_log_index = 290393846
        last_log_term = 40558
        last_snapshot_index = 290385351
        last_snapshot_term = 40558
        latest_configuration = [{Suffrage:Voter ID:11b2f688-80a1-75ea-5e43-c82f254343f3 Address:10.0.250.118:8300} {Suffrage:Voter ID:616148f6-f756-7ed6-3597-5d59576a6418 Address:10.0.252.14:8300} {Suffrage:Voter ID:f3fd72a5-eaee-87e2-ba28-e55dfe403846 Address:10.0.253.247:8300} {Suffrage:Voter ID:dabdeca3-5d76-f99d-9aaf-0033d29f9c71 Address:10.0.253.25:8300} {Suffrage:Voter ID:9d97c24f-bac4-8ff9-fddf-418f4cdb293b Address:10.0.252.135:8300}]
        latest_configuration_index = 0
        num_peers = 4
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 40558
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 2006
        max_procs = 2
        os = linux
        version = go1.14.9
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 44003
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 43
        member_time = 38010
        members = 94
        query_queue = 0
        query_time = 1759
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 389
        members = 5
        query_queue = 0
        query_time = 3
```

</details>

### Operating system and Environment details
Debian 9.3 Running on an AWS m5.2xlarge ( 8 cores 32G RAM)

### Log Fragments
There are no errors in the consul logs.   Nomad shows a lot of errors similar to this:

`` 2020/11/12 01:50:35.899843 [WARN] (view) kv.get(app/84b2b442eba0a23471440620c33f88bb5193aa6d/infra/apache/error_log/stag): Get "http://127.0.0.1:8500/v1/kv/app/84b2b442eba0a23471440620c33f88bb5193aa6d/infra/apache/error_log/stag?stale=&wait=60000ms": read tcp 127.0.0.1:40696->127.0.0.1:8500: read: connection reset by peer (retry attempt 8 after "32s")
```

**Comment by pierresouchay** [comment]
Might be linked to https://github.com/hashicorp/consul/issues/7527

=> adding  http_max_conns_per_client might solve your issue if you did not configured it

**Comment by dansteen** [comment]
Hi @pierresouchay ,

That did indeed solve our issue -  thanks so much!  I read through the changelog and even searched the config docs to see if a new variable was added, but somehow I totally missed this.
