### ISSUE TITLE
[req] ACL New Token page's drop-downs are neither sorted nor searchable

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/consul#9227]
**Old UI or New UI**
New, as of 1.8.5

**Describe the problem you're having**
On the New Token page (`/acls/token/create`) the roles and policies drop-down menus are rather painful to use as they are not sorted. Making selecting a role a tedious process of slowly walking through the list. In our case, we have hundreds of roles.

![image](https://user-images.githubusercontent.com/90741/99586481-6d042000-29ad-11eb-982f-0f25eca24d3c.png)

**Describe the solution you'd like**

A quick fix would be to simply sort the list. Near-zero work and a helpful intermediate step. Sorting any list presented to a user is always a great first-pass in my book!

But a super awesome usability improvement would be if the drop-downs were instead implemented with an inline drop-down search to make finding and selecting an option easy.

**Share inspiration**
How have you seen this problem solved well in other UIs?

**Comment by johncowen** [comment]
Hi @dekimsey 

Just a quick note here that this is included in Consul 1.9, both sorting and searching.

Thanks for the issue!
