### ISSUE TITLE
Please ensure SHA256 included for windows 

### ISSUE THREAD

**Issue by cixelsyd** [hashicorp/consul#923]
Hello!  Big thank you, yet again, for making consul available to us!  Just wanted to ask/remind you to include the sha256 sum for the windows .zip installer inside the release.version_SHA254SUMS text file when you cut a new release.  It was there for 0.4.1, but seems to be left out of the 0.5.0 release.

Thanks.  Keep up the great work!
Steve

**Comment by slackpad** [comment]
This is automated now - thanks!
