### ISSUE TITLE
a agent iptables operation,affect another one agent serfHealth status,lead to the disappearance of session

### ISSUE THREAD

**Issue by lindane** [hashicorp/consul#925]
consul version 0.5.0

Clustered environment for three server, two agent.
server address: 192.168.2.103,192.168.2.104,192.168.2.105
agent address: 192.168.2.106(rhel64-mysql1),192.168.2.107(rhel64-mysql2)

1.consul server create service/innosql/leader kv, 192.168.2.106 create session acquire service/innosql/leader,as follows：
Use /v1/session/list query 192.168.2.106 session as follows:
<pre><code>[
{
"CreateIndex": 22963,
"ID": "7bea9361-77e6-f7f4-85ae-82efc629842c",
"Name": "innosql",
"Node": "rhel64-mysql1",
"Checks": [
"serfHealth",
"service:innosql"
],
"LockDelay": 15000000000,
"Behavior": "release",
"TTL": ""
}
]</code></pre>

Use /v1/kv/service/innosql/leader as follows:(Session is on the 192.168.2.106)
<pre><code>[
{
"CreateIndex": 104,
"ModifyIndex": 22965,
"LockIndex": 87,
"Key": "service/innosql/leader",
"Flags": 0,
"Value": "c2VydmVyIHJoZWw2NC1teXNxbDEgMTkyLjE2OC4yLjEwNjozMzA2",
"Session": "7bea9361-77e6-f7f4-85ae-82efc629842c"
}
]</code></pre>

2.The following operation in 192.168.2.107(192.168.2.106 no operation)
<pre><code>[root@rhel64-mysql2 check]# cat iptables.sh 
PORT=3306
ACTION=DROP
IF=eth1
LO=lo
iptables -A INPUT -i $IF -j $ACTION
iptables -A INPUT -i $LO -j $ACTION</code></pre>

3.Use /v1/health/service/innosql api query as follows:
<pre><code>[
{
"Node": {
"Node": "rhel64-mysql1",
"Address": "192.168.2.106"
},
"Service": {
"ID": "innosql",
"Service": "innosql",
"Tags": [
"master"
],
"Address": "",
"Port": 3306
},
"Checks": [
{
"Node": "rhel64-mysql1",
"CheckID": "service:innosql",
"Name": "Service 'innosql' check",
"Status": "passing",
"Notes": "",
"Output": "cmha_name\ cmha_check_update\ ",
"ServiceID": "innosql",
"ServiceName": "innosql"
},
{
"Node": "rhel64-mysql1",
"CheckID": "serfHealth",
"Name": "Serf Health Status",
"Status": "critical",           #passing change critical,critical change passing
"Notes": "",
"Output": "Agent not live or unreachable",
"ServiceID": "",
"ServiceName": ""
}
]
},
{
"Node": {
"Node": "rhel64-mysql2",
"Address": "192.168.2.107"
},
"Service": {
"ID": "innosql",
"Service": "innosql",
"Tags": [
"slave"
],
"Address": "",
"Port": 3306
},
"Checks": [
{
"Node": "rhel64-mysql2",
"CheckID": "service:innosql",
"Name": "Service 'innosql' check",
"Status": "passing",
"Notes": "",
"Output": "cmha_name\ cmha_check_update\ ",
"ServiceID": "innosql",
"ServiceName": "innosql"
},
{
"Node": "rhel64-mysql2",
"CheckID": "serfHealth",
"Name": "Serf Health Status",
"Status": "critical",
"Notes": "",
"Output": "Agent not live or unreachable",
"ServiceID": "",
"ServiceName": ""
}
]
}
]</code></pre>

4.Use /v1/ kv/service/innosql/leader as follows:(192.168.2.106 session disappear)
<pre><code>[
{
"CreateIndex": 104,
"ModifyIndex": 22997,
"LockIndex": 88,
"Key": "service/innosql/leader",
"Flags": 0,
"Value": "c2VydmVyIHJoZWw2NC1teXNxbDEgMTkyLjE2OC4yLjEwNjozMzA2"
}
]</code></pre>

issue:Iptables operation of 192.168.2.107,influence 192.168.2.106 serfHealth status for critical(critical immediately change for passing status)，service/innosql/leader session disappeared.The 192.168.2.107 operation，192.168.2.106 will affect the state of health,Lead to the disappearance of session?

**Comment by armon** [comment]
@lindane This is happening due to how the gossip based failure detector works. When "rhel64-mysql2" sends a ping to "rhel64-mysql1", the response is being dropped by iptables. Eventually "rhel64-mysql2" marks "rhel64-mysql1" as failed, which causes the session to be invalidated.

The gossip system requires that UDP packets not be dropped, otherwise you will get a very high rate of failure detection. 

See for more details: https://consul.io/docs/internals/gossip.html
