### ISSUE TITLE
consul_autopilot_healthy metric is `NaN`

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/consul#9274]
#### Overview of the Issue

After upgrading to 1.9, the metric `consul_autopilot_healthy` is `NaN`. Might be related to https://github.com/hashicorp/consul/issues/9208

![image](https://user-images.githubusercontent.com/983101/100185898-ebb60b80-2f1f-11eb-9bb2-39ee46061533.png)

The autopilot health endpoint reports the cluster is healthy.

![image](https://user-images.githubusercontent.com/983101/100185971-199b5000-2f20-11eb-9a30-2b0200af5849.png)

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Upgrade to 1.9
1. Go to `/v1/agent/metrics?format=prometheus`

### Operating system and Environment details

Linux AMD 64 running on Kubernetes

For additional context, this did not present itself in 1.9-beta1.  It might be related to the changes introduced in https://github.com/hashicorp/consul/pull/9198

**Comment by mkeeler** [comment]
@lawliet89 When you used the `v1/agent/metrics` endpoint did you query the leader? That metric is only ever accurate on the current leader.

**Comment by lawliet89** [comment]
Thanks. You're right. `1` is only returned from a single instance which is the leader.

![image](https://user-images.githubusercontent.com/983101/100685373-366bd380-33b7-11eb-8c2b-aacff3aff66e.png)

I went back to 1.8.4 to check and only the leader would return `1` and the rest of the agents would return nothing.

If this is expected, please feel free to close the issue, although this is a change in behaviour that might trip others up.
