### ISSUE TITLE
Consul tries to bind to first private address, including loopback

### ISSUE THREAD

**Issue by sersim** [hashicorp/consul#928]
One of our servers had 10.1.1.20 as his private IP and 10.1.0.254 as a loopback
#ip addr | grep 10.1
inet 10.1.0.254/32 scope global lo

Consul used 10.1.0.254 and, as a consequence it was continuously added and removed from the cluster.
In order to fix we had to remove the loopback IP
#ip addr del 10.1.0.254/32 dev lo
or specify the bind address manually, a less-preferred method

**Comment by slackpad** [comment]
Fixed via #948.
