### ISSUE TITLE
dns returns critical instance ip via ping

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul#9286]
Version: 'v1.6.6'

I notice that a service with one critical instance will be discovered by consul via ping. please help confirm if this is as expected.
thanks!

        "Checks": [
            {
                "CheckID": "service:pg-v-broker-1e3c02c4-4dc0-4ad4-bb29-fde1887cde92_null_xxxx_9999::1a_5000",
                "CreateIndex": 11998,
                "Definition": {},
                "ModifyIndex": 11998,
                "Name": "",
                "Node": "opcs-internal",
                "Notes": "",
                "Output": "",
                "ServiceID": "pg-v-broker-1e3c02c4-4dc0-4ad4-bb29-fde1887cde92_null_xxxx_9999::1a_5000",
                "ServiceName": "pg-v-broker-1e3c02c4-4dc0-4ad4-bb29-fde1887cde92-xxxx",
                "ServiceTags": [
                    "\"ip\":{\"ip_v4\":\"172.30.0.26\",\"ip_v6\":\"9999::1a\"}"
                ],
                "Status": "critical",
                "Type": ""
            }
        ]

[root@ctrl2:~]$ ping pg-v-broker-1e3c02c4-4dc0-4ad4-bb29-fde1887cde92-xxxx
PING pg-v-broker-1e3c02c4-4dc0-4ad4-bb29-fde1887cde92-xxxx.dddd.eeeee (172.30.0.26) 56(84) bytes of data.
64 bytes from 172.30.0.26 (172.30.0.26): icmp_seq=1 ttl=64 time=0.843 ms
64 bytes from 172.30.0.26 (172.30.0.26): icmp_seq=2 ttl=64 time=0.225 ms
64 bytes from 172.30.0.26 (172.30.0.26): icmp_seq=3 ttl=64 time=0.245 ms
64 bytes from 172.30.0.26 (172.30.0.26): icmp_seq=4 ttl=64 time=0.247 ms

**Comment by pierresouchay** [comment]
@hehailong5 Do you use only_passing in your configuration?

https://www.consul.io/docs/agent/options.html#only_passing

**Comment by hehailong5** [comment]
Thank you for the reply, I did't setup this option. will close this issue for now.
