### ISSUE TITLE
UI for KV store does not expose "Flags"

### ISSUE THREAD

**Issue by pkmurph** [hashicorp/consul#930]
It would be very helpful if the UI for the KV store would allow setting (or at least persisting existing values of) the Flags attribute for a given Key.  A display of the current value would also be very helpful.

I noticed that when I add a key using a PUT operation through the API, and then attempt to update that value through the UI, the Flags attribute is reset to 0.

**Comment by ryanuber** [comment]
Makes sense to me, preserving the values might be the way to go since flags are not such a commonly used feature, so I'm not sure if we want to expose it in the UI. I'll defer to @pearkes on that. Thanks for reporting!

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
