### ISSUE TITLE
Prometheus does not like it when metrics with dynamically generated labels don't have the same help string as their definitions

### ISSUE THREAD

**Issue by mkcp** [hashicorp/consul#9303]
#### Overview of the Issue

When I was testing out the metric definitions I unfortunately did not test what happens when a metric with a similar name but different labels gets added when a definition already exists. I implicitly expected prometheus would use the already-existing help string, but it appears there's a conflict whether you provide an empty help string or a new one. This issue went unseen for a while because we didn't have definitions for many metrics when this was first shipped, and when I was adding definitions for the hundred+ metrics, I did not check the agent logs on any of the servers in the docker cluster I was running - I just looked at the prometheus page output 😞.

Thankfully, it does not appear that any measurements are lost -- prometheus is just *very* noisy in warning us that the help strings don't match. If you're a user reading this looking for a workaround without upgrading Consul, the best option I see right now is to add drop filters in your log aggregator to ignore the logs that are prometheus help string warnings.

The two forms this bug seems to be taking now are: issues when the prometheus sink first collects its metrics. We see some recently added definitions like `consul.fsm.intention` and `consul.fsm.summary`. We also see issues whenever HTTP requests are handled because the new (as of 1.9.0) `consul.api.http` metric has new labels for every endpoint. 

I'm looking into a few ways to fix this. Ideally we're able to provide the same help string when we dynamically generate labels. This will require some changes to the go-metrics prometheus sink to store the definitions on the sink so we can look up if a help string exists when we encounter a metric we haven't written before. If this for some reason isn't possible, then squashing or filtering the error messages before the agent logs them might be a practical, albeit undesirable, way of fixing this for users.

#### Reproduction Steps

- Enable prometheus metrics
- Start up consul with prometheus enabled
- View post-startup agent logs for first-collection errors
- Create an http request and view agent logs

### Consul info for both Client and Server
`telemetry = { prometheus_retention_time = "10s" }`

### Operating system and Environment details

Debian

### Log Fragments

Example one, with issues immediately following agent start on the first prometheus collection:
```
* collected metric consul_consul_fsm_ca label:<name:"op" value:"set-config" > summary:<sample_count:1 sample_sum:0.12478599697351456 quantile:<quantile:0.5 value:0.12478599697351456 > quantile:<quantile:0.9 value:0.12478599697351456 > quantile:<quantile:0.99 value:0.12478599697351456 > >  has help "" but should have "Deprecated - use fsm_ca instead"
* collected metric consul_fsm_ca summary:<sample_count:1 sample_sum:nan quantile:<quantile:0.5 value:nan > quantile:<quantile:0.9 value:nan > quantile:<quantile:0.99 value:nan > >  has help "Measures the time it takes to apply CA configuration operations to the FSM." but should have ""
* collected metric consul_consul_fsm_ca label:<name:"op" value:"set-roots" > summary:<sample_count:1 sample_sum:0.04682699963450432 quantile:<quantile:0.5 value:0.04682699963450432 > quantile:<quantile:0.9 value:0.04682699963450432 > quantile:<quantile:0.99 value:0.04682699963450432 > >  has help "" but should have "Deprecated - use fsm_ca instead"
* collected metric consul_fsm_intention summary:<sample_count:1 sample_sum:nan quantile:<quantile:0.5 value:nan > quantile:<quantile:0.9 value:nan > quantile:<quantile:0.99 value:nan > >  has help "Measures the time it takes to apply an intention operation to the FSM." but should have ""
* collected metric consul_consul_fsm_ca label:<name:"op" value:"set-provider-state" > summary:<sample_count:2 sample_sum:0.1443130038678646 quantile:<quantile:0.5 value:0.048705000430345535 > quantile:<quantile:0.9 value:0.09560800343751907 > quantile:<quantile:0.99 value:0.09560800343751907 > >  has help "" but should have "Deprecated - use fsm_ca instead"
* collected metric consul_consul_fsm_intention label:<name:"op" value:"delete-all" > summary:<sample_count:1 sample_sum:0.15876099467277527 quantile:<quantile:0.5 value:0.15876099467277527 > quantile:<quantile:0.9 value:0.15876099467277527 > quantile:<quantile:0.99 value:0.15876099467277527 > >  has help "" but should have "Deprecated - use fsm_intention instead"
* collected metric consul_consul_fsm_ca label:<name:"op" value:"increment-provider-serial" > summary:<sample_count:1 sample_sum:0.10190799832344055 quantile:<quantile:0.5 value:0.10190799832344055 > quantile:<quantile:0.9 value:0.10190799832344055 > quantile:<quantile:0.99 value:0.10190799832344055 > >  has help "" but should have "Deprecated - use fsm_ca instead"
```

Example two, with `consul.api.http` occurring during runtime:
```
    2020-11-30T14:56:02.889-0800 [INFO]  agent: error gathering metrics: collected metric consul_api_http summary:<sample_count:3 sample_sum:nan quantile:<quantile:0.5 value:nan > quantile:<quantile:0.9 value:nan > quantile:<quantile:0.99 value:nan > >  has help "Samples how long it takes to service the given HTTP request for the given verb and path." but should have "consul_api_http"

```

**Comment by pierresouchay** [comment]
Hello @mkcp,

Maybe you could have a look at my PR https://github.com/armon/go-metrics/pull/122 I made to fix my duplicated issue #9471

**Comment by pierresouchay** [comment]
On our preprod, this creates ~3200 logs/hour per server, for us ~16k logs/h per cluster (and we do not scape every 10s, and we have 12 clusters in prod, so pushing that to prod would generate at least 190k lines of log every hour), so I think this is a real issue for Consul 1.9.1 (we are still running 1.8.6 on prod for this reason)

**Comment by pierresouchay** [comment]
@mkcp Tested today on our real clusters (with https://github.com/criteo-forks/consul/tree/v1.9.1-criteo2 ) -> works very well on a real-world cluster
