### ISSUE TITLE
Semaphore Acquire does not respect DefaultSemaphoreRetryTime

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#932]
https://github.com/hashicorp/consul/blob/master/api/semaphore.go#L237

The DefaultSemaphoreRetryTime argument is not used during the wait if the semaphore is not acquired, unlike the lock variant:

https://github.com/hashicorp/consul/blob/master/api/lock.go#L187

**Comment by armon** [comment]
@highlyunavailable I think this is okay actually. Lock makes use of the `?acquire` operation which may be affected by a lock-delay, while semaphore uses `?cas` which does not have the same sort of deferral mechanism.

**Comment by highlyunavailable** [comment]
Fair enough. Does it make sense to remove `DefaultSemaphoreRetryTime` from the code then, since it isn't used anywhere?

**Comment by armon** [comment]
Probably, I think that is a copy/paste artifact
