### ISSUE TITLE
Should Semaphore.Release() delete the .lock subkey that is created under the lock prefix?

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#933]
https://github.com/hashicorp/consul/blob/master/api/semaphore.go#L314

I notice it deletes the locksession key, but not the .lock key that contains the limit/holders.

**Comment by highlyunavailable** [comment]
Further note: if the .lock key is not removed when all holders unlock the semaphore, it means the Limit value cannot be changed without deleting the key with KV.Delete() and recreating it with a new Semaphore.

**Comment by armon** [comment]
@highlyunavailable That is what the `Destroy` command is for!

**Comment by highlyunavailable** [comment]
Makes sense, thanks.
