### ISSUE TITLE
1.9.0 Agent Memory Leak - Service Running Old Envoy (1.13.0) - Envoy 1.13.0 is too old of a point release

### ISSUE THREAD

**Issue by kpurdon** [hashicorp/consul#9331]
#### Overview of the Issue

After upgrading to 1.9.0 (via Helm) I started seeing a memory leak in the agents. I noticed the following log `2020-12-05T17:07:31.531Z [ERROR] agent.envoy: Error handling ADS stream: error="rpc error: code = InvalidArgument desc = Envoy 1.13.0 is too old of a point release and is not supported by Consul because it does not support RBAC rules using url_path. Please upgrade to version 1.13.1+."` in the leaky agents. 

It turns out I missed a deploy of a service after the upgrade so it was still running the old consul version and injected pods (specifically envoy 1.13.0).

This caused a memory leak eventually resulting in agent restarts (9pm is the 1.9.0 upgrade).

<img width="674" alt="Screen Shot 2020-12-05 at 10 28 32 AM" src="https://user-images.githubusercontent.com/5130441/101259193-a2667880-36e4-11eb-888a-5a72aedbbd5f.png">

After deploying the missed service the memory leak seems gone (one example):

<img width="446" alt="Screen Shot 2020-12-05 at 10 33 14 AM" src="https://user-images.githubusercontent.com/5130441/101259305-549e4000-36e5-11eb-9ec9-3dc7fcb6b144.png">

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. create a cluster using consul 1.8.2 
2. deploy services using inject (envoy 1.13.0)
3. upgrade to consul 1.9.0
4. don't re-deploy service

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 2
	checks = 6
	services = 4
build:
	prerelease =
	revision = a417fe51
	version = 1.9.0
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 165
	max_procs = 4
	os = linux
	version = go1.15.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 18
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 9
	member_time = 219062
	members = 35
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = a417fe51
	version = 1.9.0
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.12.47.61:8300
	server = true
raft:
	applied_index = 44703294
	commit_index = 44703294
	fsm_pending = 0
	last_contact = 9.819462ms
	last_log_index = 44703294
	last_log_term = 45
	last_snapshot_index = 44703121
	last_snapshot_term = 45
	latest_configuration = [{Suffrage:Voter ID:99cfed90-f958-a116-3b8b-4d694504c2be Address:10.12.47.61:8300} {Suffrage:Voter ID:0b78569b-c37a-1e18-72d5-3f6679ba13f0 Address:10.12.9.5:8300} {Suffrage:Voter ID:c840a477-778a-486b-8d55-73031dc5a25e Address:10.12.17.26:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 45
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 258
	max_procs = 4
	os = linux
	version = go1.15.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 18
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 9
	member_time = 219064
	members = 35
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 114
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

GKE

### Log Fragments

```
2020-12-05T17:07:31.531Z [ERROR] agent.envoy: Error handling ADS stream: error="rpc error: code = InvalidArgument desc = Envoy 1.13.0 is too old of a point release and is not supported by Consul because it does not support RBAC rules using url_path. Please upgrade to version 1.13.1+."
```

**Comment by mikemorris** [comment]
Have you tried updating the Envoy sidecars to Envoy 1.13.1 or newer?

**Comment by kpurdon** [comment]
> Have you tried updating the Envoy sidecars to Envoy 1.13.1 or newer?

Yes, as noted:

> After deploying the missed service the memory leak seems gone (one example):

**Comment by david-yu** [comment]
Hi @kpurdon the current Helm chart for Consul Kubernetes deploys 1.16.x by default. Are you currently pinning the envoy version in the Helm chart? It sounds like you would expect envoy to be upgraded to a new version after upgrading to Consul 1.9 so you don't have this issue? We do know that if you use an older unsupported version of Envoy xDS will close your socket and refuse to talk to Envoy. Here is a link to our current compat matrix for Envoy and Consul Service Mesh: https://www.consul.io/docs/connect/proxies/envoy#supported-versions

**Comment by kpurdon** [comment]
I'm not pinning my Envoy version. I do not expect Envoy to be automatically upgraded. It's upgraded when I re-deploy each service after upgrading via Helm. I made a mistake and missed one of the services in this upgrade.

While I do expect an error when an envoy version is not compatible I would not expect that error to result in a memory leak for the consul agents. That memory leak is the bug I'm filing here.

Sorry for any confusion.
