### ISSUE TITLE
Consul is trying to bind to an interface that isn't up

### ISSUE THREAD

**Issue by rishid** [hashicorp/consul#934]
I was having a problem where the first address being found was for an interface that was in the "down" state.

In consul/util.go:GetPrivateIP() you should probably be using net.Interfaces() and then select an interface that has FlagUp set and also does NOT have FlagLoopback set to make it more robust in finding a usable private IP.

**Comment by ryanuber** [comment]
Thanks for reporting this, marked as a bug.

**Comment by highlyunavailable** [comment]
This would be solved by #948.
