### ISSUE TITLE
Startup ACL Token

### ISSUE THREAD

**Issue by wkennington** [hashicorp/consul#935]
Consul should support another parameter for acl_startup_token, which is a token used for registering configured services with consul and is only to be used by the agent itself, unlike the default token which can be used by anyone who connects to the consul instance.

**Comment by ryanuber** [comment]
Hey @wkennington, Consul 0.5.2 allows specifying tokens when registering services, which should make it possible to do this kind of configuration in the Consul configuration files. More info on that [here](https://consul.io/docs/agent/services.html). Does that satisfy your use case?

**Comment by wkennington** [comment]
In theory this should solve my problem. I haven't implemented this yet as it will take a non-trivial rework of my service distribution mechanism.

**Comment by slackpad** [comment]
Closing this out since we have a per-service solution for this.
