### ISSUE TITLE
ui: Lots of instances of a service break out of it's bounding box

### ISSUE THREAD

**Issue by mattrobenolt** [hashicorp/consul#938]
Should be pretty self explanatory:

![image](https://cloud.githubusercontent.com/assets/375744/7644825/d7497038-fa5f-11e4-87d7-187e9ab2a131.png)

**Comment by ryanuber** [comment]
Thanks for reporting this, marking as a bug! /cc @pearkes @markupboy

**Comment by mattrobenolt** [comment]
@ryanbreen fwiw, this happens similarly as well for Lock Sessions:

![image](https://cloud.githubusercontent.com/assets/375744/7888426/7e2c43f6-05ed-11e5-94c0-2ddefe6c61d7.png)

**Comment by rafikk** [comment]
I've run into this all over the place as well.

I'd be interested in contributing a patch and I've already fixed several instances of this on our local cluster. The main offender here is setting explicit element heights in Ember's ListView. Personally, I've found the nested scrolling UI buggy and distracting and have opted to just remove it altogether. If no one is attached to the nested scrolling, I can submit a PR.

Thoughts?

**Comment by pearkes** [comment]
@rafikk Agreed about the nested scrolling, but unfortunately it's for performance. In large clusters (thousands of services/nodes) the UI chokes without ember listview.

**Comment by rafikk** [comment]
@pearkes Does that mean removing ListView is a non-starter? Is pagination an option?

Is there a good way for me to test the UI against such a cluster?

**Comment by pearkes** [comment]
@rafikk Best way to test the UI is to replace the JSON endpoint to a json file on disk (the ui dir serves a directory, so you can just copy a file in there. Then give the file a fake response of some 1000s of nodes. That's the best way I remember. Proper fixtures would be nice though. Ember has a come a long way since this UI was made, so there are a number of "better" tools now as well.

**Comment by nickwales** [comment]
I've got instances of this happening with very long node and check names. 

Long check names push the status down to where it is almost illegible. 
Long service names break out of their bounding boxes on the services view.

**Comment by macb** [comment]
Long node names also cause issues on the `nodes` endpoint (pushes the `Deregister` button around)

**Comment by slackpad** [comment]
Kicking over to @meirish who's been looking into some UI bugs.

**Comment by slackpad** [comment]
Hey there,

We are currently hiring for a full time position to manage the Consul UI. They are going to do a full revamp, so we'll make sure this is included then!
