### ISSUE TITLE
Support setting multiple keys in one atomic commit

### ISSUE THREAD

**Issue by dcieslak19973** [hashicorp/consul#940]
Zookeeper supports updating multiple nodes in one atomic commit. This can be very useful.

http://zookeeper.apache.org/doc/r3.4.3/api/org/apache/zookeeper/ZooKeeper.html#multi(java.lang.Iterable)

Looks like the etcd folks are working on something similar:

https://github.com/coreos/etcd/issues/860

The kubernetes folks are hot-to-trot on this feature.

**Comment by armon** [comment]
Marked as enhancement! Something we've thought about, but not much demand for it.

**Comment by ryanuber** [comment]
Dup of #886. Let's track this over there!
