### ISSUE TITLE
Feature request: Include datacenter in consul members output.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul#942]
I'm not sure everybody feels the same. But, I'm constantly in need of knowing exactly to what datacenter a member belongs too, when faced with this list: 

![](https://cldup.com/pwAg2v-OmH.png)

**Comment by tgwizard** [comment]
@c4milo perhaps using the `-detailed` flag would be good enough?

**Comment by tgwizard** [comment]
It would be nice to have in this standard output as well, I think.

**Comment by tgwizard** [comment]
I submitted a PR to add this. @c4milo I'm very sorry if this was something you wanted to do and I just rushed into this :/

**Comment by c4milo** [comment]
@tgwizard how dare you :)

**Comment by ryanbreen** [comment]
You know a tool has a robust community when folks are fighting over who gets to submit PRs. :+1:

**Comment by armon** [comment]
@ryanbreen Good problems to have :)
