### ISSUE TITLE
UI bug when deleting KV entry

### ISSUE THREAD

**Issue by commarla** [hashicorp/consul#9423]
#### Overview of the Issue

When I want to delete a KV entry from the UI I got this :
![image](https://user-images.githubusercontent.com/4509360/102506236-39d3b000-4083-11eb-947b-9313ede419ad.png)

It's working but I think the design is wrong.

#### Reproduction Steps

Start consul and add a KV entry

```
consul agent -server -bootstrap-expect 1 -client 0.0.0.0 -bind 127.0.0.1 -ui -data-dir $(mktemp -d)
consul kv put test/test
```

Then open the UI and click on the 3 dots to delete the entry

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
build:
	prerelease = 
	revision = ca5c3894
	version = 1.9.1
```

</details>

### Operating system and Environment details

On both macos and linux debian and firefox and chrome

**Comment by johncowen** [comment]
Thanks for the report @commarla ! Glad you took the time to report this as I'd made a change to intentions for this but completely overlooked the KV area 🤦 

🙇‍♂️ 

Fix linked there ^ should be in the next release.
