### ISSUE TITLE
1.9.1 in GitHub Releases, but 1.9.0 on website

### ISSUE THREAD

**Issue by reezer** [hashicorp/consul#9435]
When looking on [consul.io](https://www.consul.io/downloads) the Current Version is 1.9.0, while in the GitHub releases it's 1.9.1. In the master branch the ChangeLog mentions 1.9.0 and nothing for Unreleased. Some third package repositories seem to deliver 1.9.1. The 1.9.1 tag's changelog mentions the release on December 11, so seven days ago.

Is 1.9.1 officially released, or pulled back?

Might be related to #9409.

**Comment by mikemorris** [comment]
Website has been updated with 1.9.1 now and it is officially released, thanks for catching this!
