### ISSUE TITLE
testing: Add a completeness test for all types that have a CacheInfo method

### ISSUE THREAD

**Issue by dnephin** [hashicorp/consul#9437]
`CacheInfo()` is used by the agent cache to generate a `RequestInfo` for the cache. Many of the fields in the `RequestInfo` struct are passthrough (ex: token, datacenter, MinIndex, etc), but the `Key` field is special. It is used as the cache key. If any fields are not represented in the cache key then cache entries could overlap and pollute a different cache entry. An example of this problem can be seen in #9436

In order to ensure that new fields are not missed from the `Key` we should add a test for every type that has a `CacheInfo()` method, which does the following:
1. Populate every field of the struct using random values (we have examples of this [here](https://github.com/hashicorp/consul/blob/master/proto/pbservice/convert_test.go)).
2. For each field in the struct, change the value to another random value and assert the cache key has changed. We may want the option to explicitly exclude some fields from this iteration, but by default they should all be included.

If a field is not represented in the cache key, the key value would not have changed and the test would fail.

**Comment by kevinkengne** [comment]
Hi 👋 , I'd be interested in working on this.

**Comment by kevinkengne** [comment]
Hey @dnephin 👋 , I've replied your comment on the PR.

**Comment by dnephin** [comment]
I believe with #9480 and #9556 we have full coverage now, so I'm going to close this issue.
