### ISSUE TITLE
Adding a new Consul API language

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#944]
The company I work for (PlayFab) uses Consul and I just finished porting the Go API to C# since that's what our stack is built on. We've also open-sourced it under the Apache license, and I'd like to add it to the list of APIs on the [Consul Tools](https://www.consul.io/downloads_tools.html) page. You can check it out at https://github.com/PlayFab/consuldotnet if you want.

Should I just make a PR to edit that page, if you think this should go there, or something else?

**Comment by ryanbreen** [comment]
Cool! Yep, just make a PR. Thanks!

**Comment by armon** [comment]
Awesome! Glad to see a full C# client lib!
