### ISSUE TITLE
can't filter nodes by using api.QueryQptions{Filter: "address == 10.10.10.10 "}

### ISSUE THREAD

**Issue by king131** [hashicorp/consul#9441]
```

teststring := fmt.Sprintf("Address == %v", "10.10.10.10")
nodes, _, err := c.Catalog().Nodes(&api.QueryOptions{

Filter: teststring,
})
```
and i get the error:
```
2020/12/21 17:14:33 Unexpected response code: 500 (rpc error making call: Failed to create boolean expression evaluator: 1:17 (16): rule "number": Invalid number literal)
exit status 1
```

**Comment by mkeeler** [comment]
@king131 If you change your `%v` to a `%q` in the format string then it should work. The filter language allows match values to be number literals, identifiers or quoted strings. An identifier is some ASCII letter (a-z and A-Z) followed by ASCII letters, numbers or underscores.

I think some of the confusion here is when some strings don't have to included quotes and that our documentation currently shows many examples that don't require quotes. That documentation is in the process of being reworked to hopefully make it clearer when to use quotes.

**Comment by king131** [comment]
@mkeeler  ok，It's work now. Thank you !
