### ISSUE TITLE
Connect CA rotation issue with both Vault CA provider and Built-in CA

### ISSUE THREAD

**Issue by mariusehr1** [hashicorp/consul#9443]
#### Overview of the Issue

I have a setup with multiple DC, I use Vault as a connect CA everywhere : each server from each DC is able to fetch their certs from Vault via a public endpoint. Each DC has a different connect-intermediate field , they all use the root token for simplicity purposes as I am still testing. Initialisation is fine, starting a bunch of services, gateways and upstreams, everything is functional ... At least until the rotation process from Vault comes in.

#### Reproduction Steps

* Run a consul cluster, plug multiple datacenter to it (k8s and VMs) with auto_encrypt to every agent 
* Configuration is as follows for the servers : 
```
[...]
connect {
    enabled = true
    enable_mesh_gateway_wan_federation = true
    ca_provider = "vault"
    ca_config {
        address = "https://vault.domain.com:8200"
        token = "ROOT_VAULT_TOKEN"
        root_pki_path = "connect-root"
        intermediate_pki_path = "dc1/connect-intermediate"
	ca_path = "/tls/aws-pub-vault.pem"
    }
}
[...]
```
* Wait a couple of days (usually 2/3)
* View error `x509: certificate has expired or is not yet valid: current time 2020-12-21T10:29:18Z is after 2020-12-10T17:05:39Z"`
* Looking at the consul `connect/ca/roots` endpoint, I get (I had the logs today, december 21st)  : 
```
{
  "ActiveRootID": "54:fd:62:7d:68:ec:0f:71:09:4d:80:f7:85:ca:e2:96:a6:3c:ea:3a",
  "TrustDomain": "69f90c95-0ef2-e5c3-95e4-e9f5761d5012.consul",
  "Roots": [
    {
      "ID": "54:fd:62:7d:68:ec:0f:71:09:4d:80:f7:85:ca:e2:96:a6:3c:ea:3a",
      "Name": "Vault CA Root Cert",
      "SerialNumber": 1089649549233987700,
      "SigningKeyID": "83:f1:a0:fe:66:5e:e0:4d:52:42:36:cf:73:73:3e:73:10:9a:2f:86",
      "ExternalTrustDomain": "69f90c95-0ef2-e5c3-95e4-e9f5761d5012",
      "NotBefore": "2020-11-16T15:29:35Z",
      "NotAfter": "2020-12-18T15:30:05Z",
      "RootCert": "ROOT_CERT",
      "IntermediateCerts": [
        "INTERMEDIATE_CERT",
        "INTERMEDIATE_CERT",
        "INTERMEDIATE_CERT"
      ],
      "Active": true,
      "PrivateKeyType": "ec",
      "PrivateKeyBits": 256,
      "CreateIndex": 8,
      "ModifyIndex": 8
    }
  ]
}
```
* Looking at the auto-encrypt certificate I have : 
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            01:85:0a:66:df:8c:ec:ca:78:42:b6:2d:0f:1f:36:7d:e7:c1:a0:a9
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN=pri-p7v7z0v.vault.ca.98315d78.consul
        Validity
            Not Before: Nov 16 15:29:35 2020 GMT
            Not After : Dec 18 15:30:05 2020 GMT
        Subject: CN=pri-p7v7z0v.vault.ca.98315d78.consul
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:c8:3f:23:5c:87:77:b7:58:e9:7b:e5:dc:b0:11:
                    0e:5e:4d:ef:1f:f6:d8:b2:07:67:aa:58:53:e5:27:
                    68:d2:b1:f9:40:0d:e3:21:b5:1e:b3:8b:61:40:a1:
                    e7:83:32:48:ab:1d:a2:72:b6:cf:78:ce:cf:ac:64:
                    c4:c8:1d:bf:0d
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier:
                D4:10:03:FB:24:FF:A3:C4:B1:B8:D2:84:AD:45:84:E2:A8:4B:E7:44
            X509v3 Authority Key Identifier:
                keyid:D4:10:03:FB:24:FF:A3:C4:B1:B8:D2:84:AD:45:84:E2:A8:4B:E7:44
            X509v3 Subject Alternative Name:
                DNS:pri-p7v7z0v.vault.ca.98315d78.consul, URI:spiffe://98315d78-e404-32b8-e8d1-56346b5b3b95.consul
```

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 1
        checks = 1
        services = 1
build:
        prerelease =
        revision = a417fe51
        version = 1.9.0
consul:
        acl = enabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 59
        max_procs = 2
        os = linux
        version = go1.15.5
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 6
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 116
        members = 9
        query_queue = 0
        query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease =
        revision = ca5c3894
        version = 1.9.1
consul:
        acl = enabled
        bootstrap = false
        known_datacenters = 7
        leader = false
        leader_addr = 10.0.3.235:8300
        server = true
raft:
        applied_index = 913663
        commit_index = 913663
        fsm_pending = 0
        last_contact = 44.735099ms
        last_log_index = 913663
        last_log_term = 9
        last_snapshot_index = 901924
        last_snapshot_term = 9
        latest_configuration = [{Suffrage:Voter ID:b7dd85fa-f768-6ac8-e20d-e0caa120b8ab Address:10.0.5.110:8300} {Suffrage:Voter ID:64cd3804-a3b9-af69-43dc-9b3b7dc38eab Address:10.0.3.235:8300} {Suffrage:Voter ID:61440e01-8e6e-a0fe-875d-10aeda240943 Address:10.0.4.98:8300}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 9
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 223
        max_procs = 2
        os = linux
        version = go1.15.6
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 6
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 116
        members = 9
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 815
        members = 16
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

I use Ubuntu 20.04 for my VMs and the default EKS image for my kubernetes datacenters.

Running Consul 1.9.1 as well as envoy 1.14.5, Vault  is running version 1.6.0.

It seems that the consul agents for Vault are running 1.9.0, does that change anything? Consul instances fetch from Vault via a public endpoint.

I had the issue before with Consul 1.8.5 and envoy 1.13.1.

### Extra information

I started an issue on consul-helm repository as I initially thought it was kubernetes related. As it is pretty hard to reproduce (e.g. waiting 2/3 days) but today I noticed that it was worst that I expected and all my VM DCs were also affected.

This is one of the main issue before moving into production, I would appreciate some help. 

I will try rebuilding my mesh with the built-in CA in the meantime to see if the same issue is happening.

Here is the link of the initial issue for reference : 
https://github.com/hashicorp/consul-helm/issues/731

Thanks,
Marius

**Comment by mariusehr1** [comment]
FYI, this issue also occurs when using the Consul Built-in CA with the exact same behaviour.

Looking further it seems that the primary datacenter is fine, up and running.

But whenever a primary server in a secondary datacenter has to rotate its certificate, it just doesn't happen. This occurs both in k8s and on VMs, the IntermediateCert in the `/ca/connect/roots` endpoint never changes.

It's worth mentioning that I use `auto_encrypt` for the agents and the sidecars are fetching their certificates from their local agents which causes a chain reaction.

This is fixable on VMs by deleting the `data_dir` from a secondary dc's server and restarting it, same logic applies to the k8s secondary datacenter , I have to delete the server secret and reload helm in order for consul-k8s to create it again, after that it works again.

I really wonder what is wrong, the documentation states : 

```
Certificate management in Connect is done centrally through the Consul servers using the configured CA (Certificate Authority) provider. 
A CA provider manages root and intermediate certificates and performs certificate signing operations. 
The Consul leader orchestrates CA provider operations as necessary, such as when a service needs a new certificate or during CA rotation events.
```

The snippet here is on the server in a secondary DC on VMs : 

```
connect {
    enabled = true
    enable_mesh_gateway_wan_federation = true
}
```
and here on k8s : 

```
server:
  connect: true
```

Is it intended ? Documentation is pretty vague regarding the rotation mechanism and I can't seem to find more clues there.

What should be the best practice ? 

Any help would be appreciated as its breaks the whole mesh and prevents me from moving to production.

Thanks,

Marius

**Comment by mariusehr1** [comment]
This was related to a mesh gateway on the primary datacenter not advertising the proper address.

It was advertising the same address on both LAN and WAN. 

My only concern is that, even though it was mesh-breaking, the federation could still occur and the mesh would "work" at least from the GUI point of view.

It feels wierd having to wait for an internal mechanism to happen to see a bug occurring.

If there is any chance to add some log/warning if the LAN and WAN addr are the same ? I know its probably just me but I'm pretty sure it will save people alot of time for a very low effort.

Mesh is now fully operational, so ill close the issue.

Marius

**Comment by lkysow** [comment]
Hi Marius, sorry to hear about your issues. Was there no logging on the secondary datacenters? I would have thought they would be logging that they couldn't reach the primaries.

**Comment by mariusehr1** [comment]
Yes , there were logs regarding a timeout indeed but it felt really confusing as most the logs are LAN addresses.

The problem is that they were able to reach it from time to time as I just put the address of the primary mesh gateway in my values.yaml but when it came to advertising their WAN ip's, mesh-gateways were advertising local addresses. So it was pretty obvious.

I know its really my fault but I just wish the UI could give me a warning, or some logs regarding WAN and LAN addresses being the same.

Either way, it took me a while to figure out but i'll be able to move forward with Consul into production very soon.

Marius

**Comment by lkysow** [comment]
We're definitely interested in exposing these misconfigurations in a better way. Would you be open to creating another issue that describes the "feature" request of exposing this in the UI as a warning?

**Comment by mariusehr1** [comment]
Sure, I will do that this week.

**Comment by mariusehr1** [comment]
Hello,

As I thought my mistake would fix this issue, I closed this but it just happened again..

More details : 

I got those logs on the server side after 4 days of running. Using vault as a CA provider. Every mesh-gateway is advertised properly this time around.

```
     2021-03-03T10:42:19.141Z [ERROR] agent.server.rpc: failed to read byte: conn=from=192.168.27.234:54488 error="tls: failed to verify client certificate: x509: certificate has expired or is not yet valid: current time 2021-03-03T10:42:19Z is after 2021-02-11T11:52:08Z"
     2021-03-03T10:42:19.189Z [ERROR] agent.server.rpc: failed to read byte: conn=from=192.168.48.247:49514 error="tls: failed to verify client certificate: x509: certificate has expired or is not yet valid: current time 2021-03-03T10:42:19Z is after 2021-02-11T11:52:08Z"
 ```
As there is full connectivity and advertised addresses are right, this should be automatic, right?

Looking a bit further I also saw some :  

```
    2021-03-03T10:42:15.641Z [ERROR] agent.server.memberlist.wan: memberlist: Failed to send gossip to 10.244.15.212:8302: read tcp 192.168.33.75:58760->192.168.79.41:8443: read: connection res
 et by peer
```

Which is the IP of the local mesh-gateway

Looking at the mesh-gateway logs I get the following : 

```

 2021-03-03T10:45:19.774Z [ERROR] failed to sync service: output="Error registering service "mesh-gateway": Put "https://192.168.13.80:8501/v1/agent/service/register": x509: certificate has expired or is not yet valid: current time 2021-03-03T10:45:19Z is after 2021-02-11T11:52:08Z" err="exit status 1" duration=4.900824715s
```

Mesh cannot register to the agent which himself cannot do a thing because he tries to use the mesh-gateway.

I really don't get it, this bug has been occuring for months now and is really preventing me from moving further with the product and I have to admit , it is really frustrating.

Willing to provide more info as per usual.

Marius

**Comment by mariusehr1** [comment]
Looking at the primary datacenter : I get the following for `/v1/connect/ca/roots` 

```
{
  "ActiveRootID": "a1:80:11:a0:55:6c:eb:13:ed:28:3c:05:49:89:b6:9e:8e:36:37:8e",
  "TrustDomain": "f3acc83e-3731-8560-9f5f-5bb9117b3254.consul",
  "Roots": [
    {
      "ID": "a1:80:11:a0:55:6c:eb:13:ed:28:3c:05:49:89:b6:9e:8e:36:37:8e",
      "Name": "Vault CA Root Cert",
      "SerialNumber": 2074584072412289800,
      "SigningKeyID": "6e:88:98:ad:9b:e7:da:f7:9d:a5:35:2c:f9:0f:4a:03:09:db:b7:37",
      "ExternalTrustDomain": "f3acc83e-3731-8560-9f5f-5bb9117b3254",
      "NotBefore": "2021-01-29T15:54:56Z",
      "NotAfter": "2021-03-02T15:55:26Z",
      "RootCert": "REDACTED",
      "IntermediateCerts": [
        "REDACTED",
        "REDACTED"
      ],
      "Active": true,
      "PrivateKeyType": "ec",
      "PrivateKeyBits": 256,
      "CreateIndex": 393,
      "ModifyIndex": 682
    }
  ]
}
```

Note the ` "NotAfter": "2021-03-02T15:55:26Z",` even though we are 2021-03-03 today.

**Comment by mariusehr1** [comment]
Taking a closer look into this issue, it turned out that it was actually related to my ACLs, I was using a bootstrap token which was causing unexpected behaviour.

Make sure you only use the "replicationToken" within your secondary datacenters.

**Comment by rboyer** [comment]
I see you were running 1.9.1 originally when this all started. I wanted to mention that at least 3 [changes were made in 1.9.3](https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#193-february-01-2021) related to this variant of wan federation: https://github.com/hashicorp/consul/issues/9519, https://github.com/hashicorp/consul/issues/9528, https://github.com/hashicorp/consul/issues/9366. One of them may have been a contributing factor to any of the above.

> This was related to a mesh gateway on the primary datacenter not advertising the proper address.

I wanted to offer more of an explanation of what was happening the first time when the lan/wan addresses were misconfigured slightly.

When using `connect { enable_mesh_gateway_wan_federation = true }` to federate a primary and secondary datacenter [a lot of stuff](https://www.consul.io/docs/connect/gateways/mesh-gateway/wan-federation-via-mesh-gateways) is going on under the covers  both when initially federating the secondary, and over time once it has been federated.

The `primary_gateways` configuration file setting used on the servers in the secondary datacenter is the seed addressing data the secondary uses to _initially_ dial the primary datacenter to get the whole thing started. In your situation this was the correct value and specified the WAN-accessible ip address. This is used to have the servers in the secondary datacenter start issuing RPCs to setup things like Connect CA roots replication, ACL replication, etc. So initially these things worked out fine.

One of the things it replicates is a list of all of the service discovery information for all mesh gateways in all datacenters. This lets any datacenter know how to directly dial any other datacenter via mesh gateways to ensure that federation is possible. Included in this blob of data is the catalog health information about those mesh gateways registered in the primary. This information is always treated as authoritative once a secondary receives it and then it will generally stop using the `primary_gateways` values.

In your case this meant that after the initial federation, the secondary basically severed its own _outbound_ connectivity to the primary datacenter, leaving all RPCs (like replication of Connect CA roots, or intermediate certificate signing RPCs) to fail. Since the mesh gateway addresses in the secondary were correct, the primary datacenter (likely where your UI was running from) could indeed reach the secondary and issue it RPCs. It was a one-way network partition.

This variation of federation has several safeguards in place under the covers to detect that key RPCs are failing and heuristically starts to use the `primary_gateways` configuration to reach the primary again. This was primarily made so that if all of the mesh gateways in the primary datacenter suddenly were recycled and came up with new ip addresses, you'd have some mechanism to re-federate.

Unfortunately since the authoritative data about mesh gateway registration was ultimately incorrect, this mechanism only offered mere blips of connectivity periodically before disconnecting again. This may have let a very small fraction of primary-bound RPCs through intermittently.

It would be great to have a way for Consul to detect such misconfigurations, but it is difficult to do so because every network topology Consul is deployed into is unique with its own eccentricities. In your specific case having `lan=wan` was incorrect and we could have warned about that, but in other flat networking environments that may actually be a desirable configuration and the warnings would be misleading to those operators instead.

> Taking a closer look into this issue, it turned out that it was actually related to my ACLs, I was using a bootstrap token which was causing unexpected behaviour.
> 
> Make sure you only use the "replicationToken" within your secondary datacenters.

Could you please clarify something about this for me? Was it that you were using the original master/bootstrap token as your replication token? If so that should have worked since  the bootstrap token has unrestricted privileges.

**Comment by mariusehr1** [comment]
Hello, 

Thanks for all those clarifications, I am not really experiencing those initial issues as I had both issues with my primary mesh-gateway as well as ACL settings.

It was actually the replicationToken that was used both for the replicationToken AND the bootstrapToken so obviously it was lacking permissions, the strangest thing is that it somehow made my whole mesh work but eventually caused some more cert renewal issues.

Removing the bootstrapToken (e.g. the expected ACL configuration) caused my mesh to work but only across k8s datacenters (e.g. not with VMs DC as a primary or secondary), but it fixed this issue that's why I am mentioning it here.

Currently working on getting k8s and VMs datacenters to work together, basically half-way there.

Using 1.9.4+ent and 1.16.2 for envoy.

FYI information I moved to enterprise so I won't be posting here much more, if you are interested in the ticket, here is the reference :  #42906.

Thanks.
Marius
