### ISSUE TITLE
request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Lemon-le** [hashicorp/consul#9470]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl ...`
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
output from client 'consul info' command here
```

</details>

<details>
  <summary>Server info</summary>

```
output from server 'consul info' command here
```

</details>

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the environment.

### Log Fragments

Include appropriate Client or Server log fragments. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue. Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

**Comment by jsosulska** [comment]
hello @Lemon-le 

Please fill out the complete template when filing a bug. If you are still experiencing this issue, open a new issue. We need the information provided in the template, especially your configuration file and settings, as well as steps to replicate it.

Have a good day,
Jon

--------------------------------------------------------------------------------

你好@ Lemon-le

提交错误时，请填写完整的模板。 如果您仍然遇到此问题，请打开一个新的问题。 我们需要模板中提供的信息，尤其是您的配置文件和设置，以及复制它的步骤。

对不起翻译不好

祝你有美好的一天，
乔恩
