### ISSUE TITLE
Please give a adapter M1 version of the consul

### ISSUE THREAD

**Issue by junchaogg996** [hashicorp/consul#9484]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by mikemorris** [comment]
Dupe of #9476
