### ISSUE TITLE
consul integration with oidc

### ISSUE THREAD

**Issue by himmakam** [hashicorp/consul#9503]
I am trying to integrate consul with keycloak for oidc authentication. I get this error - Looks like I need to pass the OIDCDiscoveryCACert in the json file. Can I know how we can pass the cert here. Is it the contents of the cert or path to the cert file. 

 consul acl auth-method create -type oidc -name keycloakauth -max-token-ttl=5m -config=@auth-method-config.json
Failed to create new auth method: Unexpected response code: 500 (Invalid Auth Method: error checking OIDCDiscoveryURL: Get

**Comment by rboyer** [comment]
It is the contents of the PEM file itself that is provided in the [`OIDCDiscoveryCACert`](https://www.consul.io/docs/security/acl/auth-methods/oidc#oidcdiscoverycacert) field.

**Comment by jsosulska** [comment]
Hi @himmakam ! 

Thank you for your question. 😃 

As this has been open for a while and answered by RB, I will close this thread. For further questions, see our [Discuss forum](https://discuss.hashicorp.com/c/consul/29). Our very helpful community can often help where others can't!

Best, 
Jono
