### ISSUE TITLE
Can't use KV-store recursively when ACL is enabled

### ISSUE THREAD

**Issue by onnimonni** [hashicorp/consul#952]
TL;DR ``` ?recurse ``` parameter doesn't work with ACL tokens.

**What I'm trying to achieve**
Only allow access to KV-store and register/deregister APIs from localhost using ACL. If there's better way this is what I want to do.
**What I'm doing.**
start to use ACL and try to access the all data under prefix ```/data``` 
```curl localhost:8500/v1/kv/data?recurse&token=xxxxxx-yyyy-zzzz-yyyyy-xxxxxxx```

Response:
```
HTTP/1.1 404 Not Found
X-Consul-Index: 63942
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Mon, 18 May 2015 17:30:47 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

My config file is
```/etc/consul.conf``` =>
```
{
  "ui_dir": "/opt/consul/dist",
  "disable_remote_exec": true,
  "domain": "consul.",
  "data_dir": "/opt/consul/data",
  "log_level": "INFO",
  "server": true,
  "client_addr": "0.0.0.0",
  "bind_addr": "0.0.0.0",
  "datacenter": "xyz",
  "bootstrap_expect": 2,
  "acl_datacenter": "xyz",
  "acl_master_token":"xxxxxx-yyyy-zzzz-yyyyy-xxxxxxx",
  "acl_default_policy": "deny",
  "acl_down_policy": "extend-cache",
  "rejoin_after_leave": true,
  "leave_on_terminate": false
}
```
**Working alternative:**
I can use recurse method normally if I add default acl_token into configs:
```
  "ui_dir": "/opt/consul/dist",
  "disable_remote_exec": true,
  "domain": "consul.",
  "data_dir": "/opt/consul/data",
  "log_level": "INFO",
  "server": true,
  "client_addr": "0.0.0.0",
  "bind_addr": "0.0.0.0",
  "datacenter": "xyz",
  "bootstrap_expect": 2,
  "acl_datacenter": "xyz",
  "acl_master_token":"xxxxxx-yyyy-zzzz-yyyyy-xxxxxxx",
  "acl_token":"xxxxxx-yyyy-zzzz-yyyyy-xxxxxxx",
  "acl_default_policy": "deny",
  "acl_down_policy": "extend-cache",
  "rejoin_after_leave": true,
  "leave_on_terminate": false
```
So again:
```curl localhost:8500/v1/kv/data?recurse&token=xxxxxx-yyyy-zzzz-yyyyy-xxxxxxx```

And Response is successful:
```
HTTP/1.1 200 OK
Content-Type: application/json
X-Consul-Index: 62564
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0
Date: Mon, 18 May 2015 17:35:32 GMT
Transfer-Encoding: chunked
```

**Comment by ryanbreen** [comment]
Is that exactly the command you're running?  If so, you probably need to escape the `&`:

```
curl localhost:8500/v1/kv/data?recurse\&token=xxxxxx-yyyy-zzzz-yyyyy-xxxxxxx
```

Without escaping it, anything after token is run as a separate command after the curl command is forked.

**Comment by onnimonni** [comment]
Thanks that was it. But actually I'm using the ruby implementation of the api called and trying to debug why it isn't working after ACL [diplomat](https://github.com/WeAreFarmGeek/diplomat/)

Seems that the problem is over there, so I keep digging. Thanks :).
