### ISSUE TITLE
[Question] Is the heartbeat info will update when the instance be modified in server?

### ISSUE THREAD

**Issue by horizonzy** [hashicorp/consul#9540]
Hi, If I register an instance to server, the heartbeat will send to server scheduled.
If the instance be modified in server, is the heartbeat info will be updated?

**Comment by jsosulska** [comment]
Thank you for your question, @horizonzy 

We recommend all questions be asked on our Discuss forum. Feel free to tag me (@jsosulska ) when you post there, and I would be happy to follow up 😄 

Can you please provide a little bit more information as to what you mean by "instance", "server", and "heartbeat"? Maybe give a scenario to help picture this? 🤔 
Are you talking about [sessions](https://www.consul.io/docs/dynamic-app-config/sessions) in Consul? Those can have either healthchecks or expire by TTL.

I will close this thread. For further questions, see our [Discuss forum](https://discuss.hashicorp.com/c/consul/29). Our very helpful community can often help where others can't!

Best, 
Jono
