### ISSUE TITLE
Some questions about only Server nodes in the architecture

### ISSUE THREAD

**Issue by wangyushuai** [hashicorp/consul#9545]
#### Feature Description

I only use Consul as a registry, can I only have Server nodes in my architecture, without Client nodes? If there are only Server nodes, is there a problem? What are the problems?

If there are only Server nodes, can I use LB (or ClusterIp Server, VIP) to mount all Server nodes.

#### Use Case(s)

Do you have any opinions? Do you have any suggestions?

**Comment by jsosulska** [comment]
Hello @wangfenjin 

Thank you for your message. I am Closing this issue, as this has been answered [here](https://discuss.hashicorp.com/t/some-questions-about-only-server-nodes-in-the-architecture/19598)

Please direct all questions to our discuss.hashicorp.com forums. 
Best, Jono
