### ISSUE TITLE
Check validity of certificates before they are used in Consul Connect to sign leaf certs

### ISSUE THREAD

**Issue by preetapan** [hashicorp/consul#9573]
It is possible for expired intermediate and root certs to be continued to be used to sign leaf certs. Right now, the fact that certs are expired ins't caught until TLS validation at request time. 

This affects both expired root certs that could be used to sign intermediate certs, and expired intermediate certs used to sign leaf certs.

Instead of waiting till request time for TLS verification, we should be checking for cert expiration/validity at certificate signing time. 

TBD - This behavior might be different across different CA providers, needs additional research to figure out which providers are affected.

**Comment by dhiaayachi** [comment]
Hi @preetapan ,
I did some research on this and my findings are the following:
- Consul provider: we definitely do not check the validity of the intermediate before using it to sign the leaf (locally)
- Vault provider: we send an API call to vault to sign the leaf, we provide the path the the intermediate in the API call and based on the path vault will use the right intermediate to sign the leaf (do vault check the validity before signing and return an error if expired? not sure)
- AWS provider: same as Vault we do not send the intermediate and rely on the provider
In both cases (AWS and Vault) we keep a copy of the intermediate locally that we can use to check but there is no warranty that it will not be stale for some reason)

Last thing I'm not sure about is what is the intended behaviour here?
- return an error if the intermediate is expired and refuse to sign to make the error visible
- start a process the regenerate the certificate as we are trying to do for #9574
