### ISSUE TITLE
Consumer, like a node registration service in a cluster, does not automatically generate a replica

### ISSUE THREAD

**Issue by AEGEGE** [hashicorp/consul#9579]
I deploy a consul cluster with three nodes, all in the role of server. After the deployment is completed, kv has achieved high availability, but when I register the service through one of the nodes, I found that the registered service cannot automatically generate a copy. Is there a way to register Does the service automatically generate a copy?

**Comment by jsosulska** [comment]
Hi @AEGEGE 

Thank you for your question.

Questions like this are better suited for our Discuss forum, where our community can help you out more. I recommend you take a look at our [Consul Architecture](https://learn.hashicorp.com/tutorials/consul/reference-architecture?in=consul/production-deploy) guide for more information. Usually, your services will register with a local (client) agent. These clients then pass the service information to the servers, who maintain and add it to the catalog. The [local client agents](https://learn.hashicorp.com/tutorials/consul/get-started-agent#server-and-client-agents) are the source of truth, so every running instance of a service will need to do its own registration. In short - no, a single registration does NOT generate a copy of the service definition.

I will close this thread. For further questions, see our [Discuss forum](https://discuss.hashicorp.com/c/consul/29). Our very helpful community can often help where others can't!

Best,
Jono
