### ISSUE TITLE
Cluster doesn't come back to life automatically after Cloud Provider Maintenance

### ISSUE THREAD

**Issue by mohitarora** [hashicorp/consul#958]
We have a consul cluster running in Microsoft Azure and there was a planned maintenance for Microsoft Azure yesterday where they restarted our consul nodes on a rolling basis (It may be graceful shutdown or may be not). 

There was a gap of almost an hour b/w the node restarts so all the nodes didn't go down at the same time. It is a 3 node cluster running consul v 0.5.0

Also none of the IPs got changed after maintenance

Configuration:

{
    "bootstrap": false,
    "server": true,
    "datacenter": "dev",
    "data_dir": "/var/consul",
    "encrypt": "X7icIBLbGBPk8aC4gcjnOw==",
    "log_level": "INFO",
    "enable_syslog": true,
    "ui_dir": "/home/consul/dist",
    "client_addr": "0.0.0.0",
    "recursor": "8.8.8.8",
    "acl_datacenter": "dev",
    "acl_master_token": "f45cbd0b-5022-47ab-8640-4eaa7c1f40f1",
    "acl_token": "f45cbd0b-5022-47ab-8640-4eaa7c1f40f1",
    "acl_default_policy": "deny",
    "acl_down_policy": "deny",
    "start_join": ["10.101.0.84", "10.101.0.85"]
}

The only configuration difference b/w the nodes is start_join.

After the maintenance none of the node had consul running.

What i did to bring it back to life

* Removed start_join from config on node1
* Removed peer nodes from peers.json file on node1 (Only left the node1 IP there)
* Start consul on node1 with new config
* Start consul on other nodes without modifying anything
* Stop consul on node1
* Reverted the config change on node1
* Started consul again on node1

I understand that if all nodes go down at the same time, then cluster can't come back to life but this was a rolling restart.

Can the configuration be any better? Will leave_on_terminate help, I didnt think so.

Please let us know.

**Comment by armon** [comment]
@mohitarora It is hard to tell given this information what happened. Do you have the log files during when the restart happened? Can you tell if the nodes did leave and join again?

When you say none of the nodes had consul running, that sounds like the machine didn't start Consul agent during the boot process. We typically recommend running Consul under a process supervisor like upstart, runit, or systemd.

**Comment by slackpad** [comment]
Closing this since we never heard back.
