### ISSUE TITLE
Datacenter is converted to lowercases with 0.5.1

### ISSUE THREAD

**Issue by Shinzu** [hashicorp/consul#959]
hello,

i upgraded 1 of my 3 master with the latest version from git, after this it cannot join the cluster anymore:

```
2015/05/19 18:11:33 [WARN] memberlist: Cluster merge canceled: Member 'test-consul01' part of wrong datacenter 'test'

2015/05/19 18:19:03 [WARN] memberlist: cluster merge canceled: Member 'test-consul02' part of wrong datacenter 'TEST'
```

consul.conf on all 3 masters:

```
{   "datacenter": "TEST",
....
```

**Comment by armon** [comment]
@Shinzu I've marked this as a bug, but the datacenter names should all be lowercased. Moving every agent to 0.5.2 should fix this as well.

**Comment by slackpad** [comment]
#2478 fixed this.
