### ISSUE TITLE
Log_json does not always log structured JSON messages

### ISSUE THREAD

**Issue by Laakso** [hashicorp/consul#9607]
#### Overview of the Issue

Hello,

We enabled `log_json` in consul configuration and we noticed that at least snapshot INFO messages are not structured JSON in journal. 

#### Reproduction Steps

1. Enable log_json
{

    ..snip..
    "log_level": "INFO",
    "log_json": true,
    ..snip..
}

2. sudo journalctl -u consul.service
3. wait for snapshot INFO message to appear

### Operating system and Environment details

Linux, Consul 1.7.3

### Log Fragments

```
Jan 20 14:57:21 consul-server consul[5192]:     {"@level":"info","@message":"starting snapshot up to","@module":"agent.server.raft","@timestamp":"2021-01-20T14:57:21.997535Z","index":50011280}
Jan 20 14:57:21 consul-server consul[5192]:     2021-01-20T14:57:21.997Z [INFO]  snapshot: creating new snapshot: path=/opt/consul/data/raft/snapshots/165-50011280-1611154641997.tmp
Jan 20 14:57:22 consul-server consul[5192]:     2021-01-20T14:57:22.017Z [INFO]  snapshot: reaping snapshot: path=/opt/consul/data/raft/snapshots/162-49978476-1611137566852
Jan 20 14:57:22 consul-server consul[5192]:     {"@level":"info","@message":"compacting logs","@module":"agent.server.raft","@timestamp":"2021-01-20T14:57:22.017296Z","from":49984622,"to":50001040}
```

**Comment by dnephin** [comment]
That you for the bug report! This bug was fixed in 5acf01ceeb88d83d67b3939d664e99731202a406 which is included in all the 1.9.x releases. Upgrading to 1.9.x should fix it for you.
