### ISSUE TITLE
Service tags should not inherit to sidecar proxies

### ISSUE THREAD

**Issue by apollo13** [hashicorp/consul#9643]
This might be somewhat controversial, so let me explain. Many proxy tools (ie traefik and fabio) use service tags to find services to route to. In my example I have a service called `netbox` and its sidecar `netbox-sidecar-proxy`. This results in the following catalog:

```
netbox                           traefik.enable=true,traefik.http.routers.netbox.rule=Host(`netbox.infra.mydomain`)
netbox-sidecar-proxy     traefik.enable=true,traefik.http.routers.netbox.rule=Host(`netbox.infra.mydomain`)
```
This is (as far as I understand) a result of nomad copying the service tags to the sidecar. If I manually register a service & a proxy I do not see them duplicated (or maybe I registered them wrongly, see [web-proxy.json.txt](https://github.com/hashicorp/nomad/files/5860334/web-proxy.json.txt) & [web.json.txt](https://github.com/hashicorp/nomad/files/5860335/web.json.txt) ).

Now this duplication is causing problems in loadbalancers because they try to route to the service with the copied tags as well -- this generally does not end well given the proxy has mtls only. See @spuder's comment and picture in https://github.com/hashicorp/nomad/issues/7941#issuecomment-651297879 for an example.

My current workaround is to explicitly set `tags = ["dummy"]` on the `sidecar_service` stanza. I cannot set `tags = []` because apparently that is treated as "unset" and the service tags are copied again.

I recently ran into this problem again because I am working on integrating consul connect in traefik and am not sure what the proper behavior should be. Personally I think nomad should not copy tags to the sidecar, if the user wants that they are welcome to copy the tags (or maybe add a `inherit_tags=false` flag?). As far as I understand, while there is a relation between the proxy and the upstream service in consul, they are still two completely separate services for most intents and purposes, so sharing tags might be the wrong thing to do.

I'd love to hear more about the rationale on why tags are copied and I am putting @blake into /cc so he might be able to give some extra consul insights.

@nomad-team: I could not find the location where the tags are actually copied on a quick dive through the nomad code, can you point me there?

**Comment by apollo13** [comment]
Hi @freddygv, between my initial comment and my work on the connect PR plenty happened. The connect PR works fine with how consul currently works. But other load balancers might still run into troubles and might need some logic to deduplicate the two services.

I guess in an ideal world I would like to be able to filter out sidecars from `/catalog/services` (sic) because there is no need for them -- I'd get their instances via `/health/connect/backend`. Currently the traefik PR magically filters out `backend-sidecar-proxy` because `/health/connect/backend-sidecar-proxy` returns nothing for the sidecar :)

Either way, I fully understand that this would most likely be a big shift and I also have no good ideas on how it should look like. My initial comment just tried to illustrate some pain points people are facing.

**Comment by AngelOnFira** [comment]
I just want to echo my support of this issue. I'm super excited to play with Traefik's new capability in 2.5 of creating an ingress into the private Docker network from the internet, and currently [Nomad's Consul Connect tutorial code](https://www.nomadproject.io/docs/integrations/consul-connect#run-the-connect-enabled-services) doesn't work by simply adding the tags you'd expect. I had to dive pretty deep to figure out that this duplication was the problem. I'll be trying to write a blog post about setting up this process, and I would really rather not have to explain why I'm adding `tags = ["dummy"]` to the sidecar :stuck_out_tongue:

**Comment by apollo13** [comment]
@AngelOnFira With Traefik 2.5 and connect awareness simply adding the tags is enough. You do not needs `tags = ["dummy"]` anymore.

**Comment by bradydean** [comment]
I'm running into this issue again with traefik 2.8.5. Adding a dummy tag fixes it.
