### ISSUE TITLE
UI - show history of up/down for each check

### ISSUE THREAD

**Issue by jdrago999** [hashicorp/consul#965]
Hi -

I think it would be useful to see (in addition to the current status) the history of each check.

Something like http://status.aws.amazon.com/#archived_events_block

If the web UI isn't the place to display this, perhaps simply a way to store and retrieve history via the API would suffice.

Thoughts?

**Comment by armon** [comment]
@jdrago999 Managing historic state has been out of scope for Consul traditionally. That is something we like to see built on top of Consul, like we have done with Atlas, or others with open source tooling. This allows Consul to focus on just the emergent current state problem.

**Comment by ryanuber** [comment]
Closing for now as this should be implemented on top of Consul. Thanks!
