### ISSUE TITLE
Failed to build "release/1.9.x" branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [hashicorp/consul#9659]
I've just tried to build "release/1.9.x" branch using Go 1.14.14 and got the following:
```
github.com/hashicorp/consul/agent/consul
# github.com/hashicorp/consul/agent/consul
agent/consul/server.go:385:5: cannot use s (type *Server) as type serverDelegate in argument to NewGatewayLocator:
	*Server does not implement serverDelegate (missing setDatacenterSupportsFederationStates method)
```

**Comment by blake** [comment]
Hi @SchweinDeBurg,

This seems to be caused by a change in f25a21960e87458952d81f3f5fedbdce1f15769a, which we should investigate.

In the mean time if you need to build Consul, you should have success with using the last released version, 1.9.2.

```shell
$ git checkout v1.9.2
$ make dev
--> Making [GH-xxxx] references clickable...
==> Building Consul - OSes: darwin, Architectures: amd64
Building sequentially with go install
--->   darwin/amd64
$ git rev-parse --short HEAD
6530cf370
$ ./bin/consul version
Consul v1.9.2
Revision 6530cf370
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

**Comment by dnephin** [comment]
Thank you for the bug report! We missed backporting #9519 which caused this issue.  I just backported that change now, which looks to have fixed the problem.

We should look at adjusting our backport automation to run tests before accepting the backport so that this doesn't happen again in the future.

**Comment by SchweinDeBurg** [comment]
Many thanks, I've just successfully built an RPM package containing bleeding-edge Consul 1.9.x!
