### ISSUE TITLE
SessionEntry.Behavior: delete doesn't work with Lock.Unlock

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/consul#968]
If a session is created with Session Behavior: `delete`, and then used with a Lock, Lock.Unock doesn't delete the key that was created.

Tiny repro:
```
package main

import (
	"fmt"
	"github.com/hashicorp/consul/api"
)

func main() {
	c, _ := api.NewClient(api.DefaultConfig())
	s, _, _ := c.Session().Create(
		&api.SessionEntry{Behavior: "delete"},
		nil,
	)

	l, _ := c.LockOpts(&api.LockOptions{Key: "test/eph", Session: s})
	l.Lock(nil)
	// Uncomment this to delete the key instead.
	// c.Session().Destroy(s, nil)
	l.Unlock()
	k, _, _ := c.KV().Get("test/eph", nil)
	fmt.Println(k)
}
```

Expected result: `k` is nil (`test/eph` doesn't exist)
Actual result: `test/eph` is not deleted and is returned.

It seems like the session must be invalidated (which triggers lock delay) to delete a key with a behavior of `delete`, but the `Lock.Unlock` call releases the KV key before the session is destroyed, which means that it is no longer associated and thus means the key is not deleted.

**Comment by armon** [comment]
It seems this is working as intended? Since the `Unlock` is properly removing the session association, it would be unexpected if the actual key was deleted. If the Session is actually invalidated while holding the lock, I would expect it to be deleted.

**Comment by highlyunavailable** [comment]
This feels like a really weird behavior though. I can make a session, I can make LockOpts with that session ID, I call Lock... and then to unlock, I destroy the session rather than calling Unlock? I would expect that if I set a session behavior, the Lock would respect that if I passed in that specific session ID via a LockOpts.

**Comment by highlyunavailable** [comment]
Maybe I'm incorrectly conflating "sessions" and "locks" in my head. I'm going by the language on http://www.consul.io/docs/internals/sessions.html that says:

> If the release behavior is being used, any of the locks held in association with the session are released, and the ModifyIndex of the key is incremented. Alternatively, if the delete behavior is used, the key corresponding to any of the held locks is simply deleted. This can be used to create ephemeral entries that are automatically deleted by Consul.

My use case for ephemeral locks is login creation - if a faulty process or impatient client tries to create an account `n` times, we want to have a webserver look up the entry in a DynamoDB secondary index, then if it's not there (either because it's not consistent yet from a previous successful request, or because it truly doesn't exist) attempt to acquire a lock on a key (e.g. `/createlogin/email/example@example.com`) and use that key to coordinate between multiple servers all trying to create the same user. Once the user has been successfully created, or the process that holds the lock has lost its session (because it crashed, for example), the key should be deleted so we don't end up with thousands of keys under `/createlogin/email`.

We could do something like:
* Obtain lock with session behavior `delete`
* Create the user
* Wait until the data has successfully showed up in DynamoDB
* Release the lock
* Delete the key

In an error condition the key would be deleted due to the session being "non-gracefully" invalidated.

I was expecting it would be something like:
* Obtain lock with session behavior `delete`
* Create the user
* Wait until the data has successfully showed up in DynamoDB
* Release the lock to implicitly delete the key.

**Comment by armon** [comment]
@highlyunavailable The "behavior" of a session affects what is done during invalidation of a session to any keys associated ("locked") by that session. So I guess the confusion here is between the behavior of a key "lock" in Consul vs the `api.Lock` client library.

The `api.Lock` will create the key if it does not exist, and in either case attempts to associate or "lock" the key with a session. On `Unlock` the client dis-associates the session ("unlock"), but does not delete the key. The `api.Lock` exposes a separate `Destroy` operation instead. The intended use case for that library was for locks that are longer lived than the sessions. For example, multiple services contending for the same lock as a leader election mechanism.

That said, you can get the behavior you want by doing the lock with a session with `delete` behavior, acquiring the lock, and then doing an explicit session invalidation. The session invalidation will cause the lock to be deleted / released without it lingering.

**Comment by highlyunavailable** [comment]
I think it's just that it seems like sessions are frequently conflated with the concept of a lock in the documentation. Thanks for the clarification.

**Comment by armon** [comment]
@highlyunavailable I agree. The downside of overloaded terminology and complex systems. But I'm happy to help clarify!
