### ISSUE TITLE
Bring back PowerISA / ppc64le as build option?

### ISSUE THREAD

**Issue by krosseyed** [hashicorp/consul#9686]
#### Feature Description

Allow weirdos like me to build on ppc64le. I do not ask to run this on my G5 Mac, I would like to run this on modern PowerISA chips.

I am currently stuck on v1.7.2 since that was the last time I tried building from source on ppc64le. I am not sure what has changed since v1.7.2 and v1.9.2 but it would be nice to see this feature return.

#### Use Case(s)

I cant update consul without it compiling, and there have never been any binaries available for ppc64le. This limits my usage as I now have to deal with security issues and missing new features.

**Comment by jftuga** [comment]
Having a PPC64le supported build would be very helpful for me, too.
