### ISSUE TITLE
Document that /agent/services supports ?ns and add to API client

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#9710]
#### Feature Description

1. The `/agent/services` endpoint supports namespaces but it's not documented (https://www.consul.io/api-docs/agent/service#list-services)
2. The API client doesn't support passing in a query object: https://github.com/hashicorp/consul/blob/master/api/agent.go#L525

**Comment by lkysow** [comment]
@blake does this fix the issue with the API client?

**Comment by blake** [comment]
It does not. I'll file that as a separate issue so that we can track those updates separately from the docs changes.

**Comment by blake** [comment]
@lkysow #9903 added the ability to specify the namespace on a few endpoints using the API client. I just opened #10691 to support specifying `ns` for the /agent/health/service/name|id/ and /agent/service/maintenance endpoints.
