### ISSUE TITLE
consul agent doesn't know about other data centers

### ISSUE THREAD

**Issue by eirslett** [hashicorp/consul#973]
I have set up 2 consul clusters, with 3 servers each (and a couple more agents/slaves), the servers know about each other across data centers (WAN pool).
The issue is that some of the agents (that are not servers) know about the other data center (curl localhost:8500/v1/catalog/datacenters) but others only know about their own data center.
Is that expected behaviour, or a possible bug?
I'm running the consul web UI on an agent that is not a server, so the admin UI sometimes shows two data centers, sometimes one.

**Comment by ryanuber** [comment]
Hey @eirslett,
What version of Consul are you using? Was the cluster ever running a pre-0.5.x build? Between 0.4.x and 0.5.2 (latest), there were a number of significant enhancements made to avoid this kind of thing. Is it possible that at some point a node from one datacenter was accidentally joined to one from the other datacenter?

**Comment by ryanuber** [comment]
Ah actually, I was too quick to respond. I was thinking of a different issue we had in 0.4.x builds. This sounds like it could be a bug, but knowing the consul version, and having a few logs from the node which is running the UI would be helpful in debugging this.

Thanks!

**Comment by eirslett** [comment]
We're currently running version 0.5.0 everywhere. I don't think any nodes have joined across data centers, since `consul members` only returns members from the local data center. (And I suppose there are sanity checks that warn if you try to join a cluster in a different data center from the one the agent is running on?)

We're not logging anything from consul yet, but I'll look into that as well, to get more data!

**Comment by eirslett** [comment]
I tried upgrading to consul 0.5.2, that seems to have fixed the problem.

**Comment by ryanuber** [comment]
@eirslett thanks for updating us. Let us know if this issue crops up again. For now I'll close it out. Thanks!
