### ISSUE TITLE
Add an ability to set things like Envoy lb_policy via proxy config in Consul Connect

### ISSUE THREAD

**Issue by Oloremo** [hashicorp/consul#9748]
#### Feature Description

It would be great if you'd add an ability to set things like Envoy lb_policy via proxy config in Consul Connect.
Maybe some other commonly changed things like connect_timeout, circuit_breakers, etc.

#### Use Case(s)

For example, I struggle to change the default Envoy **lb_policy** inside Nomad job definition, more details here: https://github.com/hashicorp/nomad/issues/9997

Any hints on how can I achieve that would be very helpful.

**Comment by blake** [comment]
Hi @Oloremo, Consul 1.9 added support for configuring Envoy's lb_policy using the [LoadBalancer](https://www.consul.io/docs/connect/config-entries/service-resolver#loadbalancer) parameter on a service resolver.

You just need to create a service resolver configuration entry for your service in Consul in order for it to be used when deploying your application in Nomad.

```hcl
# backend-service-resolver.hcl
Kind           = "service-resolver"
Name           = "backend"
LoadBalancer = {
  Policy = "random"
}
```

Then write that configuration to Consul using [`consul config write`](https://www.consul.io/commands/config/write).

```shell
consul config write backend-service-resolver.hcl
```

The proxies within the service mesh will use the specified load balancer policy when connecting to the `backend` service.

**Comment by Oloremo** [comment]
@blake Hi! 

Thanks for the reply, I thought about it but it's not convenient. Nomad does Consul service registration and Nomad does Consul Connect bootstrap and configuration as well, so splitting this into a second configuration entity will complicate things. 

It would be perfect to keep Nomad as a source of truth for the configuration like I set the upstream and I want this upstream to use different lb_policy for example. Since all the configuration is located in the Nomad job definition - it's easy to manage and reason about.

So if I could somehow set the lb_policy for the side-car Envoy that I actually define in the Nomad job spec, that would be awesome. Using your approach I'll have to create a Consul service resolver for each service each time I add new one.

Does it make sense to you?

**Comment by blake** [comment]
Hi @Oloremo, your request makes sense to me. Consul already exposes a way to configure the load balancing policy, but as was pointed out in https://github.com/hashicorp/nomad/issues/9997#issuecomment-781342105 it seems like you're really looking a first-class way to configure this from Nomad.

Do you mind if I close this issue as the Nomad team is tracking this feature request in https://github.com/hashicorp/nomad/issues/9997?

**Comment by Oloremo** [comment]
@blake Sure! I Thanks for the clarifications.
