### ISSUE TITLE
Document example health checks

### ISSUE THREAD

**Issue by spuder** [hashicorp/consul#975]
The demo site has some simple checks to verify disk utilization, ping, and memory usage. Those config examples aren't documented anywhere. 

I've spent several hours trying to script these checks with no luck. Also tried stackoverflow and IRC channel. 

http://stackoverflow.com/questions/30465443/consul-alert-if-drive-is-full

What does the disk utilizaiton and memory usage checks look like?

**Comment by mtchavez** [comment]
@spuder Easiest way I found is to install `nagios-plugins` package and set up your checks with consul for what you want to manage. But really the checks are as simple as any executable script that you want to have run at a certain interval.

Here is a sample of using some of the nagios plugin scripts as consul checks: https://gist.github.com/mtchavez/e367db8b69aeba363d21

**Comment by spuder** [comment]
Thanks, the nagios plugin does look very helpful. 

Do you have to manually install that plugin on every agent?

**Comment by mtchavez** [comment]
@spuder yes you would need to install that per node or provision your nodes with the necessary scripts to use in your checks.

**Comment by siddharthist** [comment]
@spuder Not to shamelessly self-promote, but you might also take a look at [Distributive](https://github.com/CiscoCloud/distributive). It was designed to work with Consul, and documents how to use it with Consul health checks on the wiki.

**Comment by spuder** [comment]
Thanks for the link on distributive. That looks useful.
