### ISSUE TITLE
Feature request: TCP health check. 

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul#976]

**Comment by gautamk** [comment]
:+1:

**Comment by ryanuber** [comment]
Seems like a useful generic check type, thanks! Also, for the time being, you can just use netcat to get this type of functionality.

```
nc -z -w5 <host> <port>
```

**Comment by c4milo** [comment]
@ryanuber nice trick! Although, I was thinking more in being able to monitor RDS instances from Consul.

**Comment by highlyunavailable** [comment]
@c4milo I use TCPing to do just that:

`/bin/tcping -t 1 rds.hostname.goes.here 1433`

**Comment by ryanuber** [comment]
What @highlyunavailable suggest should work too! Both commands would take a hostname and port, which should allow you to do exactly what you need.

**Comment by c4milo** [comment]
Cool! Thanks guys!

**Comment by Kosta-Github** [comment]
I still think, that a native TCP health check would be helpfull, especially in stripped down docker containers that might not contain `nc` or `tcping` ...

**Comment by DanyC97** [comment]
i agree with @Kosta-Github
