### ISSUE TITLE
consul.exe for windows has no version number in the file properties

### ISSUE THREAD

**Issue by pvandervelde** [hashicorp/consul#980]
The windows consul.exe file doesn't provide a version number in the file properties dialog. Having one would make it simpler to figure out which version of consul the exe is for

![image](https://cloud.githubusercontent.com/assets/96201/7853496/11fd939a-0563-11e5-97d4-b962aaecab9a.png)

**Comment by ryanuber** [comment]
To my knowledge, this isn't currently possible to embed in a Go binary without using specialized tooling outside of the normal `go build` toolchain. We might add something like this later on when the toolchain supports it, but for now the file name will provide this information. Thanks for the suggestion!
