### ISSUE TITLE
Panic when Vault Connect CA enable

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/consul#9800]
#### Overview of the Issue

I got a panic error when trying to configure Connect CA with Vault. 

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15e3764]
>goroutine 139 [running]:
>github.com/hashicorp/consul/agent/connect/ca.(*VaultProvider).Configure(0x40008caeb0, 0x4000af0db0, 0x24, >0x400056492b, 0x3, 0x1, 0x4000418990, 0x0, 0x5, 0x4000a4b3b0)
>	/home/circleci/project/consul/agent/connect/ca/provider_vault.go:90 +0x274
>github.com/hashicorp/consul/agent/consul.(*CAManager).initializeRootCA(0x4000178f00, 0x33a8820, 0x40008caeb0, >0x4000ce6b40, 0x0, 0x0)
>	/home/circleci/project/consul/agent/consul/leader_connect_ca.go:397 +0xbc
>github.com/hashicorp/consul/agent/consul.(*CAManager).InitializeCA(0x4000178f00, 0x0, 0x0)
>	/home/circleci/project/consul/agent/consul/leader_connect_ca.go:346 +0x790
>github.com/hashicorp/consul/agent/consul.(*CAManager).Start(0x4000178f00)
>	/home/circleci/project/consul/agent/consul/leader_connect_ca.go:254 +0x28
>github.com/hashicorp/consul/agent/consul.(*Server).startConnectLeader(0x400000d800, 0x3379860, 0x40006c5b80)
>	/home/circleci/project/consul/agent/consul/leader_connect.go:37 +0x38
>github.com/hashicorp/consul/agent/consul.(*Server).establishLeadership(0x400000d800, 0x3379ea0, 0x4000862120, >0xc004c55dd1d63128, 0x20f0ead28)
>	/home/circleci/project/consul/agent/consul/leader.go:352 +0x16c
>github.com/hashicorp/consul/agent/consul.(*Server).leaderLoop(0x400000d800, 0x400080c060)
>	/home/circleci/project/consul/agent/consul/leader.go:199 +0x83c
>github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership.func1(0x4000392e40, 0x400000d800, 0x400080c060)
>	/home/circleci/project/consul/agent/consul/leader.go:91 +0x58
>created by github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership
>	/home/circleci/project/consul/agent/consul/leader.go:89 +0x3d4

#### Reproduction Steps

1. Create a consul docker image (1.9, arm64) cluster with this configuration
```
server = true
datacenter = "dc1"
data_dir = "/var/consul/data"
bind_addr = "0.0.0.0"
client_addr = "0.0.0.0"
advertise_addr = "172.31.35.51"
bootstrap_expect = 1
retry_join = ["172.31.35.51", ]
ui = true
log_level = "DEBUG"
domain = <domain>
key_file = "/consul/config/pki/privkey1.pem",
cert_file = "/consul/config/pki/cert1.pem",
ca_file = "/consul/config/pki/chain1.pem"
auto_encrypt {
  allow_tls = true
}
connect {
    enabled = false
    ca_provider = "vault"
    ca_config {
        address = "http://<vault_dns>:8200"
        token = "<root_token>"
        RootPKIPath = "consul"
        intermediate_pki_path = "consul-agent"
    }
}
ports {
  http = 8500,
  https = 8501,
}
```
1. Run Vault docker image (latest, arm64) with the following configuration
```
storage "consul" {
  address = "172.31.35.51:8500"
  path    = "vault/"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_disable = true
}

api_addr = "http://172.31.35.51:8200"
cluster_addr = "http://172.31.35.51:8201"

ui = true
```
1. Init Vault, and unseal it
2. Change the consul config tu specify the Vault root token (I'm just trying this in dev for now, I kown that I need to create a token with appropriate policies for production), and turn on connect
3. Restart the container
4. Verify in vault, the 2 pki secret engine are created by Consul in Vault
5. Check consul logs, you will see the error message

### Operating system and Environment details

Ubuntu arm64 AWS instance `5.4.0-1037-aws`
Podman version: `podman version 3.0.0`
Consul running command: https://gist.github.com/quentin9696/7be32f2d697eb3cabfd2b4b559ec891c
Vault running command: https://gist.github.com/quentin9696/4028aaf32b77c4a123f09da52a3dd264

Both consul and Vault are running on the same host. Also, Vault need Consul (consul backend), and Consul need Vault (connect CA)

### Log Fragments

```
 2021-02-21T20:05:18.131Z [INFO]  agent.server: cluster leadership acquired
    2021-02-21T20:05:18.132Z [INFO]  agent.server: New leader elected: payload=baz
    2021-02-21T20:05:18.142Z [TRACE] agent.tlsutil: UpdateAutoEncryptCA: version=4
    2021-02-21T20:05:18.143Z [DEBUG] agent.server: Cannot upgrade to new ACLs: leaderMode=0 mode=0 found=true leader=172.31.35.51:8300
    2021-02-21T20:05:18.143Z [INFO]  agent.leader: started routine: routine="federation state anti-entropy"
    2021-02-21T20:05:18.143Z [INFO]  agent.leader: started routine: routine="federation state pruning"
    2021-02-21T20:05:18.144Z [DEBUG] agent.server.autopilot: autopilot is now running
    2021-02-21T20:05:18.144Z [DEBUG] agent.server.autopilot: state update routine is now running
    2021-02-21T20:05:18.144Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/vault/core/lock from=10.88.0.1:59472 latency=107.56µs
    2021-02-21T20:05:18.145Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/vault/core/lock from=10.88.0.1:59472 latency=33.387µs
    2021-02-21T20:05:18.146Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/vault/core/lock from=10.88.0.1:59472 latency=37.276µs
    2021-02-21T20:05:18.146Z [DEBUG] agent.http: Request finished: method=GET url=/v1/kv/vault/core/lock from=10.88.0.1:59472 latency=36.217µs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15e3764]

goroutine 119 [running]:
github.com/hashicorp/consul/agent/connect/ca.(*VaultProvider).Configure(0x4000101630, 0x400099b5c0, 0x24, 0x400057001b, 0x3, 0x1, 0x40002dbf80, 0x0, 0x5, 0x4000570050)
	/home/circleci/project/consul/agent/connect/ca/provider_vault.go:90 +0x274
github.com/hashicorp/consul/agent/consul.(*CAManager).initializeRootCA(0x4000178000, 0x33a8820, 0x4000101630, 0x40008ecd20, 0x0, 0x0)
	/home/circleci/project/consul/agent/consul/leader_connect_ca.go:397 +0xbc
github.com/hashicorp/consul/agent/consul.(*CAManager).InitializeCA(0x4000178000, 0x0, 0x0)
	/home/circleci/project/consul/agent/consul/leader_connect_ca.go:346 +0x790
github.com/hashicorp/consul/agent/consul.(*CAManager).Start(0x4000178000)
	/home/circleci/project/consul/agent/consul/leader_connect_ca.go:254 +0x28
github.com/hashicorp/consul/agent/consul.(*Server).startConnectLeader(0x400092f500, 0x3379860, 0x4000927c80)
	/home/circleci/project/consul/agent/consul/leader_connect.go:37 +0x38
github.com/hashicorp/consul/agent/consul.(*Server).establishLeadership(0x400092f500, 0x3379ea0, 0x400012e758, 0xc004cd1f87de5e85, 0x1d368a83b)
	/home/circleci/project/consul/agent/consul/leader.go:352 +0x16c
github.com/hashicorp/consul/agent/consul.(*Server).leaderLoop(0x400092f500, 0x4000102960)
	/home/circleci/project/consul/agent/consul/leader.go:199 +0x83c
github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership.func1(0x400012dfc4, 0x400092f500, 0x4000102960)
	/home/circleci/project/consul/agent/consul/leader.go:91 +0x58
created by github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership
	/home/circleci/project/consul/agent/consul/leader.go:89 +0x3d4
```

**Comment by rboyer** [comment]
From the setup and repro steps above it sounds like there's a circular dependency between the consul cluster (of one server) and the vault cluster (of one server) on each other to start.

- vault is configured to use consul for storage, and cannot operate unless that is up
- consul is configured (during the restart) to use vault for the Connect CA and cannot finish electing a leader unless that is up

The line that is panicking is when consul is trying to do `/v1/auth/token/lookup-self` to Vault to determine if it can auto-renew its lease. Since Consul isn't fully "up" yet, vault technically isn't "up" yet either, so consul can't proceed with startup and there's a stalemate.

In this circumstance, the vault api is returning no data vs an error which causes the panic. If it returned an error instead it would still fail to start, just with an error message instead.

You can break the circular dependency by either switching vault to use [integrated storage](https://www.vaultproject.io/docs/concepts/integrated-storage) or by using an isolated consul cluster *just* for vault storage and nothing else which I believe might be a recommended pattern somewhere over on the vault docs.

**Comment by quentin9696** [comment]
Hi @rboyer 

Thanks for your reply, this is what I guess, I got an egg-chicken issue. 
I'll check with integrated storage, I think this can solved my circular dependency.

A last question, what if I use the `service_registration` stanza to register my vault to consul ? Vault should start, even if consul is not started ?

**Comment by rboyer** [comment]
I made https://github.com/hashicorp/consul/pull/9806 to handle this situation better (by not panicking).

I am not a vault expert, but I don't see why [`service_registration`](https://www.vaultproject.io/docs/configuration/service-registration/consul) would block vault startup.

**Comment by quentin9696** [comment]
Thanks for the change, and thanks for the information
