### ISSUE TITLE
Load git configuration files to consul agent? Inbuilt

### ISSUE THREAD

**Issue by sonaljambhule87** [hashicorp/consul#9837]
Please search the existing issues for relevant feature requests, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description
Trying to load the git configuration files into KV store consul agent, can we have inbuilt or need to use tool. If yes then is there way to deploy on GCP cloud run.
A written overview of the feature.

#### Use Case(s)
Load git configuration file into Consul agent KV in using GCP Cloud run

Any relevant use-cases that you see.

**Comment by blake** [comment]
Hi @sonaljambhule87,

Consul provides a [`consul kv import`](https://www.consul.io/commands/kv/import) CLI command to import keys into the KV store. This uses the [create/update key](https://www.consul.io/api/kv#create-update-key) API internally.

Consul does not provide a built-in way to load configuration from Git directly into the KV store, although a couple tools exist which were created by our community that may provide the functionality you're looking for.

https://github.com/breser/git2consul
https://github.com/KohlsTechnology/git2consul-go

**Comment by sonaljambhule87** [comment]
@blake  Thank you very much for your reply. git2consul its look like no updates for a long time, and it's not supported on GCP cloud run as well. 
I am not sure about git2consul-go. I will check that. Hope it will work. Thank you

**Comment by blake** [comment]
@sonaljambhule87 There are a few more tools listed on https://www.consul.io/docs/download-tools (file2consul and Gonsul) which might help. Hopefully one of these works for your use case.

If you don't mind, I'm going to close this issue. I recommend posting on our community forum at https://discuss.hashicorp.com/c/consul/29 if you have any followup questions about using these tools with Consul.

**Comment by sonaljambhule87** [comment]
@blake Thank you very much, Gonsul tool working for me.
