### ISSUE TITLE
Configurable grace period for `consul lock ...`

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/consul#984]
According to the commit in #981 it seems like the shutdown grace period for `consul lock ...` is hard coded to 5 seconds. I suggest this is made configurable as some processes can take longer to properly shut down.

**Comment by JensRantil** [comment]
...also, this is a not a feature I need right now, but I'm sure this is a feature request that is going to come up eventually. ;)

**Comment by slackpad** [comment]
Closing this out as this hasn't gotten a lot of other requests, and it's best to avoid extra configuration if we can.
