### ISSUE TITLE
Documentation around -address and Port for ingress gateways is not clear, plus an improvement

### ISSUE THREAD

**Issue by chrisjohnson** [hashicorp/consul#9849]
#### Problem Description
We have been struggling with the ingress gateways recently. I asked @blake and he was similarly unsure of the behavior, but admitted it was probably just a documentation issue. Here's what we read:

https://learn.hashicorp.com/tutorials/consul/service-mesh-ingress-gateways

https://www.consul.io/commands/connect/envoy#address

https://www.consul.io/docs/connect/config-entries/ingress-gateway#port

The tutorial specifies that the config entry for the ingress gateway will use `Port = 8080` but that the ingress gateway's envoy proxy should start with the argument `-address '{{ GetInterfaceIP "eth0" }}:8888'`

It's not clear why the two separate ports are specified, and port 8888 is never referenced again.

Through some digging and experimenting, I have found the following to be true:

##### -address
`-address` specifies the port that the envoy proxy will present a readiness port for the consul agent to check the health. I was able to deduce this by hitting envoy's /config_dump and seeing that the definition for the listener on the port specified in `-address` is defined simply as responding 200 OK to /ready and 404 to anything else (if you're curious, expand the following)

<details>
  <summary>Click to view the excerpt response from /config_dump</summary>
  
```
...
         "address": "10.1.28.102",
         "port_value": 8888
        }
       },
       "filter_chains": [
        {
         "filters": [
          {
           "name": "envoy.http_connection_manager",
           "hidden_envoy_deprecated_config": {
            "stat_prefix": "envoy_ready",
            "route_config": {
             "virtual_hosts": [
              {
               "routes": [
                {
                 "match": {
                  "path": "/ready"
                 },
                 "route": {
                  "cluster": "self_admin",
                  "prefix_rewrite": "/ready"
                 }
                },
                {
                 "direct_response": {
                  "status": 404
                 },
                 "match": {
                  "prefix": "/"
                 }
                }
               ],
               "domains": [
                "*"
               ],
               "name": "self_admin"
              }
             ],
             "name": "self_admin_route"
            },
            "codec_type": "HTTP1",
            "http_filters": [
             {
              "name": "envoy.router"
             }
            ]
           }
          }
...
```
</details>

##### ingress-gateway Port

The ingress-gateway's config entry Port is where envoy will listen for incoming traffic. Interestingly it seems to bind to the interface specified in `-address`, so you can't just omit `-address`

#### Requests

1. I think the documentation needs to be made clearer, though I'm not quite close enough to know the way to word things. Some key information I think needs to be called out:
    a. The inbound traffic destined for the ingress gateway should be sent to the port specified on the config entry, not the port listed for `-address`
    b. The port for `-address` *must* differ from the one specified in the config entry (we assumed they should be the same and tried setting them as such) or the /ready endpoint will clobber the ingress listener
    c. The interface that you use for `-address` will become the interface that the config entry-specified port will listen on. This one is particularly not obvious -- we thought "ok we'll just omit `-address` entirely" but then the ingress listener ends up binding to 127.0.0.1 which isn't helpful
2. I would love to see `-address` supplemented or replaced with an option *just* for specifying the interface that the ingress listener should bind to (or if there is an option for that already, better documentation pointing to that fact). As it stands, you are forced to configure the port for the `/ready` listener merely because you want to configure the interface used for the ingress listener, and it's not obvious that your one flag is being used to drive both things. I would rather see the `/ready` listener always bind to 127.0.0.1 and choose its own port automatically, ideally a non-conflicting one, like how sidecar port registration works. If there are use cases for explicitly specifying the interface and/or port then maybe renaming this argument to be more clear about its intended target

**Comment by blake** [comment]
@chrisjohnson, I opened PR #10810 to try to address these documentation gaps. Would you mind taking a look and letting me know whether the proposed changes address the issues you've identified?

Thanks.

**Comment by chrisjohnson** [comment]
Blake,

I think this is a good first step. I think another change that would really help solidify this would be to just make it impossible to specify the same interface+port for both, rather than calling out in the docs that one "should not" specify the same interface+port. But this will at least call out the footgun.

I also still think it would be beneficial to be able to specify the interface for the ingress listener separately, right now you have to just intuitively know that the interface for your listener will be the interface you specified on `-address`. At any rate I left a comment on your PR to further call this fact out from the ingress gateway config entry documentation in addition to the docs found at `-address`

Thanks
