### ISSUE TITLE
Prebuilts for darwin/arm64 (M1 Apple Silicon)

### ISSUE THREAD

**Issue by clienthax** [hashicorp/consul#9852]
#### Feature Description

Generate prebuilds for darwin/arm64 and make available on consul.io website.

#### Use Case(s)

Allows easier use of consul on darwin/arm64 for M1 / apple silicon devices

**Comment by hxnets** [comment]
**con't install in m1 silicon**

brew install --build-from-source consul
==> Cloning https://github.com/hashicorp/consul.git
Updating /Users/sparknets/Library/Caches/Homebrew/consul--git
==> Checking out tag v1.9.4
HEAD is now at 10bb6cb Release v1.9.4
HEAD is now at 10bb6cb Release v1.9.4
==> make
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - bin/consul

**Comment by hollow** [comment]
please make darwin arm64 a first-class citizen. as of today it is still a major hassle for almost all hashicorp products 😢

**Comment by jkirschner-hashicorp** [comment]
Hello all,

Just letting you know that we're targeting an October/November timeframe for the release of an official `darwin/arm64` Consul binary.

Additionally, official builds for the `darwin/arm64` target were recently released for [Vault](https://github.com/hashicorp/vault/issues/10645), [Terraform](https://github.com/hashicorp/terraform/issues/27257), [Packer](https://github.com/hashicorp/packer/issues/10708), and [Waypoint](https://releases.hashicorp.com/waypoint/0.5.2/).

**Comment by tyrantkhan** [comment]
@jkirschner-hashicorp do you think the official consul binary is close to being released?

**Comment by jkirschner-hashicorp** [comment]
Hi @tyrantkhan,

Thanks for following up on this! We merged PR #11844 earlier today to add `darwin/arm64` support to our release pipeline. All future open-source and enterprise releases should include a `darwin/arm64` build.

The Consul open-source 1.11.1 build (released today) was actually made after #11844, so its first [`darwin/arm64` build is available now](https://releases.hashicorp.com/consul/1.11.1/consul_1.11.1_darwin_arm64.zip)! The first enterprise `darwin/arm64` build should be available with the next patch release (1.11.2).
