### ISSUE TITLE
Unable to delete unwanted services

### ISSUE THREAD

**Issue by JokerDevops** [hashicorp/consul#9861]
My version is Consul v1.9.4.

Create service：
```
curl --location --request PUT 'http://consul.irybd.com/v1/agent/service/register' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "redis-192.168.0.39:7373",
    "name": "redis-YUQING",
    "address": "192.168.0.39", "port": 7373,
    "tags": ["192.168.0.34:9121","redis-YUQING"],
    "checks":[{"http":"http://192.168.0.34:9121/", "interval": "5s"}]
}'
```
Delete service：
```
curl --location --request PUT 'http://consul.irybd.com/v1/agent/service/deregister/redis-YUQING' \
--data-raw ''
or
curl --location --request PUT 'http://consul.irybd.com/v1/agent/service/deregister/redis-192.168.0.39:7373' \
--data-raw ''
```
Unable to delete service

**Comment by dnephin** [comment]
Thank you for the bug report! Can you please share the full HTTP response, and any warnings or errors in the logs that result from this delete request.

**Comment by ChipV223** [comment]
Hi @JokerDevops!

In addition to providing the information that @dnephin mentioned in his 03/10 response, I'm curious if you are able to remove the services using the [Catalog Deregister Entity API](https://www.consul.io/api-docs/catalog#deregister-entity)

**Comment by Clivern** [comment]
i faced the same but Node was missing while calling `/catalog/deregister` but api works fine with version 1.9.5

**Comment by jkirschner-hashicorp** [comment]
Hi @Clivern and @JokerDevops,

With the information I have, I'm unable to reproduce the issues you describe. If possible, can you provide the information requested by @dnephin?

I wouldn't expect `curl --location --request PUT 'http://consul.irybd.com/v1/agent/service/deregister/redis-YUQING'` to work because the service ID must be used, not name (see #10861).

But I would expect `curl --location --request PUT 'http://consul.irybd.com/v1/agent/service/deregister/redis-192.168.0.39:7373'` to work. And it does for me.

I originally wondered whether the `:` in the ID was causing problems, but that doesn't appear to be the case.

---

This is what I see (v1.9.4)...

```
==> Starting Consul agent...
           Version: '1.9.4'
           Node ID: '189afaab-2668-f541-16bc-f73ea170da69'
         Node name: 'consul-client2-windows'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

// ...

$ curl http://127.0.0.1:8500/v1/agent/services
{
    "redis-192.168.0.39:7373": {
        "ID": "redis-192.168.0.39:7373",
        "Service": "web",
        "Tags": [
            "rails"
        ],
        "Meta": {},
        "Port": 80,
        "Address": "",
        "SocketPath": "",
        "Weights": {
            "Passing": 1,
            "Warning": 1
        },
        "EnableTagOverride": false,
        "Datacenter": "dc1"
    }
}

$ curl --location --request PUT http://127.0.0.1:8500/v1/agent/service/deregister/redis-192.168.0.39:7373 --data-raw ''

$ curl http://127.0.0.1:8500/v1/agent/services
{}
```

Logs:
```
2021-08-16T20:42:41.213-0400 [DEBUG] agent: removed check: check=service:redis-192.168.0.39:7373
2021-08-16T20:42:41.213-0400 [DEBUG] agent: removed service: service=redis-192.168.0.39:7373
2021-08-16T20:42:41.213-0400 [DEBUG] agent: Node info in sync
2021-08-16T20:42:41.214-0400 [DEBUG] agent.http: Request finished: method=PUT url=/v1/agent/service/deregister/redis-192.168.0.39:7373 from=127.0.0.1:60649 latency=16.6828ms
```

**Comment by jkirschner-hashicorp** [comment]
Hi @Clivern and @JokerDevops,

Unfortunately, we don't have enough information at this time to take any further action and haven't heard any updates in a few months, so I'm closing this for now.

If you are still experiencing this issue, please reopen and provide some of the additional information requested by @dnephin.

Thanks!
