### ISSUE TITLE
Support envoy v1.17

### ISSUE THREAD

**Issue by Legogris** [hashicorp/consul#9898]
#### Feature Description

v2 API is fully deprecated as of envoy v17 (released 2021-02-12).

Some deprecation messages are already resolved as per #9602, but as mentioned in that PR, some deprecated functionality is still relied upon.

#### Use Case(s)

Can enjoy bugfixes made in newer envoy releases than 1.16.

Related issues: #9697 #8425

**Comment by rboyer** [comment]
This was done as part of https://github.com/hashicorp/consul/pull/9658

**Comment by Legogris** [comment]
Missed that one - awesome, thanks for your work :)
Do you think we can expect to see it in 1.9.5?

**Comment by rboyer** [comment]
The support for envoy 1.17.x will be in Consul 1.10.
