### ISSUE TITLE
Update documentation that Service.Address in the service registration can be an IP or a string

### ISSUE THREAD

**Issue by ltagliamonte-dd** [hashicorp/consul#9929]
Consul 1.8.8
consul server is recording in its catalog the following service:
```
cat <<EOF > payload.json
{
  "Node": "foobar",
  "Address": "192.168.10.10",
  "Service": {
    "ID": "deploy",
    "Service": "deployment-service-web",
    "Address": "192.168.1.400+what",
    "Port": 8000
  }
}
EOF

curl --request PUT --data @payload.json http://127.0.0.1:8500/v1/catalog/register

```

IP: `192.168.1.400+what` is not a valid IP.
<img width="470" alt="Screen Shot 2021-03-25 at 1 33 09 PM" src="https://user-images.githubusercontent.com/51684360/112539827-afc87100-8d6e-11eb-9a00-cd6ae5cafed9.png">

**Comment by ltagliamonte-dd** [comment]
I chased the problem and the bug appears to be here:
https://github.com/hashicorp/consul/blob/master/ipaddr/ipaddr.go#L38-L40

**Comment by jsosulska** [comment]
Hi @ltagliamonte-dd ,

Thanks for catching this. Would you mind creating a PR for the change, and adding some tests (like in your original post)? Feel free to tag me in it, and I'll give it a shot :)

**Comment by ltagliamonte-dd** [comment]
@jsosulska to be host i briefly tried to "fix the code" but this [check](https://github.com/hashicorp/consul/blob/master/ipaddr/ipaddr.go#L24) from my code understanding it completely wrong
and it breaks even the consul server bootstrap.

**Comment by jsosulska** [comment]
Thanks for taking a look at this @ltagliamonte-dd . I'll dig into it a bit as well. If the logic for validation lives in a downstream dependent library, we may need to make additional changes. I'll follow up on this one by start of next week :) Feel free to update this ticket with any information you may come across.

**Comment by ltagliamonte-dd** [comment]
so i gave another read at the code and the IsAny just checks that isn't a ANY address.
So there is a total lack in IP validation. I opened https://github.com/hashicorp/consul/pull/9965

**Comment by jsosulska** [comment]
Hi @ltagliamonte-dd ,
Bringing over the conversation from #9965 

> i don't know how the doc update works if you have some doc i can look into improving the doc.

Thank you for offering to update the documentation! The documentation on our consul.io site can be found in the [`/website`](https://github.com/hashicorp/consul/tree/master/website#contributions-welcome) folder. The link leads to the contributing guide for website edits :). For this particular update, the webpage the would need to be updated (https://www.consul.io/docs/discovery/services) would be found in [here](https://github.com/hashicorp/consul/blob/master/website/content/docs/discovery/services.mdx). Feel free to let us know about how the process goes for you!

In the meantime, I am going to close #9965 and update the title of this ticket. Let me know if you run into any challenges with the PR :)

Best, Jono

**Comment by ltagliamonte-dd** [comment]
@jsosulska i opened https://github.com/hashicorp/consul/pull/10123
