### ISSUE TITLE
ui: Create Intention -> Cancel results in JS error

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul#9940]
#### Overview of the Issue

If you click "create intention" and then click "cancel" in the create intention view, you get this error:

```
consul-ui-1dd096136f952718bf4065c00258f7ef.js:745 Uncaught TypeError: Cannot read property 'args' of null
    at value (consul-ui-1dd096136f952718bf4065c00258f7ef.js:745)
    at HTMLButtonElement.<anonymous> (vendor-4f6b2352943214ccc7e7113ab286a174.js:1274)
```

Consul 1.9.4.

Can be reproduced with `consul agent -dev` => Intentions => Create Intention => Cancel button.

**Comment by johncowen** [comment]
Hey @lkysow 👋 

From our chats offline it sounds like this is the same as https://github.com/hashicorp/consul/issues/9764 what was fixed in https://github.com/hashicorp/consul/pull/9901, so can this be closed now?
