### ISSUE TITLE
Why is Consul using service tags instead of labels?

### ISSUE THREAD

**Issue by brommer** [hashicorp/consul#997]
Hi everyone,

I was wondering, why Consul is using tags instead of labels. At the moment, if I wanted to add a value to a service which I need to parse in a Consul template, I had to use a prefix for the tag in order to identify the value within the template. E.g. if I was adding a hostname, I had to put "hostname_<myhost>" as a tag, where "hostname" is the key / prefix and <myhost> the value I needed to use in my template. I know that there is the key value store available, but I feel that this would not be the right place for storing this kind of information about a service, since it is service instance specific information and would get decoupled from the instance somehow. I guess, it should be bound to the service instance directly. To me, the key value store seems to be more the place for storing general configuration data. 

Please let me know what you think about it and what would be your "best practice" in such a case.

Thanks!

**Comment by armon** [comment]
@brommer We want to move to labels eventually, its just "legacy" decisions. You can either overload the tags currently or use the KV store.

**Comment by brommer** [comment]
Hi @armon thanks for your answer. Great hearing about that decision. I am just curious, how you would integrate that by still having valid DNS names. Is there any idea for that already? 

Thanks!

**Comment by armon** [comment]
@brommer It should work fine if you use letters and numbers, for example, "arch-x86" label can be used like "arch-x86.api.service.consul"

**Comment by brommer** [comment]
Ok, great, thanks.

**Comment by armon** [comment]
Closing, since this seems to be resolved!

**Comment by emilevauge** [comment]
Hi! Is there any chance that Consul will support labels instead of tags? Is it still in the roadmap?

**Comment by BrianHicks** [comment]
This would be super helpful for us too, actually.
