### ISSUE TITLE
Documentation is unclear around serf_lan / retry_join when using network segments

### ISSUE THREAD

**Issue by chrisjohnson** [hashicorp/consul#9972]
https://www.consul.io/docs/agent/options#serf_lan_port

https://learn.hashicorp.com/tutorials/consul/network-partition-datacenters

This guide makes no mention of configuring ports.serf_lan but ports.serf_lan makes no mention of inheriting the serf lan port from the retry_join list. Do either of these options influence one another? If so, we need to update the options docs I linked first. If not, the guide needs to mention the additional step

**Comment by blake** [comment]
@chrisjohnson I created a PR to address this gap in our docs. Could you take a look and let me know whether these changes sufficiently clarify the behavior for you?

**Comment by chrisjohnson** [comment]
This looks great, thanks @blake!
