### ISSUE TITLE
Consul user events are missed and agents don't record ever getting some events.

### ISSUE THREAD

**Issue by ckalotra** [hashicorp/consul#9996]
#### Overview of the Issue

We are observing that events are sometimes missed in consul cluster and agents. With high number of agents we are able to replicate this. It is not consistent but happens from time to time.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 317 client nodes and 3 server nodes
2. Raise events from one of agents.
3. Some events are not received on all agents.

### Consul info for both Client and Server

<details>
      <summary>Client info</summary>
    
             agent:
                check_monitors = 0
                check_ttls = 0
                checks = 0
                services = 0
        build:
                prerelease =
                revision = 9be6dfc3
                version = 1.6.1
        consul:
                acl = disabled
                known_servers = 3
                server = false
        runtime:
                arch = amd64
                cpu_count = 16
                goroutines = 68
                max_procs = 16
                os = linux
                version = go1.12.1
        serf_lan:
                coordinate_resets = 0
                encrypted = true
                event_queue = 0
                event_time = 7698039
                failed = 15
                health_score = 0
                intent_queue = 0
                left = 0
                member_time = 1625347
                members = 332
                query_queue = 0
                query_time = 8

</details>

<details>
      <summary>Server Info</summary>
          agent:
            check_monitors = 0
            check_ttls = 0
            checks = 0
            services = 0
        build:
                prerelease =
                revision = 9be6dfc3
                version = 1.6.1
        consul:
                acl = disabled
                bootstrap = false
                known_datacenters = 1
                leader = true
                leader_addr = x.x.x.x:8300
                server = true
        raft:
                applied_index = 4507694
                commit_index = 4507694
                fsm_pending = 0
                last_contact = 0
                last_log_index = 4507694
                last_log_term = 7842
                last_snapshot_index = 4492253
                last_snapshot_term = 7842
                latest_configuration = [{Suffrage:Voter ID:08e2e01a-ef68-98b8-3562-fd180b7eebb4 Address:x.x.x.x:8300} {Suffrage:Voter ID:df2a07c0-4fff-960a-33b5-f95a0c1bd1ec Address:x.x.x.x:8300} {Suffrage:Voter ID:beeab0ba-be1f-6b9e-362c-01ff860617a7 Address:x.x.x.x:8300}]
                latest_configuration_index = 2141027
                num_peers = 2
                protocol_version = 3
                protocol_version_max = 3
                protocol_version_min = 0
                snapshot_version_max = 1
                snapshot_version_min = 0
                state = Leader
                term = 7842
        runtime:
                arch = amd64
                cpu_count = 4
                goroutines = 3265
                max_procs = 4
                os = linux
                version = go1.12.1
        serf_lan:
                coordinate_resets = 0
                encrypted = true
                event_queue = 149
                event_time = 7697139
                failed = 29
                health_score = 7
                intent_queue = 0
                left = 0
                member_time = 1625348
                members = 343
                query_queue = 0
                query_time = 8
        serf_wan:
                coordinate_resets = 0
                encrypted = true
                event_queue = 0
                event_time = 1
                failed = 0
                health_score = 0
                intent_queue = 0
                left = 0
                member_time = 253
                members = 3
                query_queue = 0
                query_time = 1

</details>

**Comment by jsosulska** [comment]
Hi @ckalotra - please see my response in #9997
